scummvm/scummvm

dists/macosx/Info.plist
dists/macosx/Info.plist.in

Bug #11430.
Enabling Dark Mode compatibility on macOS, either by using `NSRequiresAquaSystemAppearance` on older SDKs, or by building with 10.14+ SDKs, makes the display blurry on Retina screens on Mojave (and probably Catalina).
This happens in OpenGL or SDL2 mode, filtered or not, with any rendering mode, etc.
This is possibly a macOS bug in OpenGL:
https://bugzilla.libsdl.org/show_bug.cgi?id=5087
https://communities.vmware.com/thread/618831
https://code.videolan.org/videolan/VLCKit/issues/82#note_30971
https://openradar.appspot.com/45895864 
This has been reported to Apple, but I don't think it's going to be fixed soon. SDL2 developers are hesitant about adding even more NSOpenGLView workarounds.
The only workaround that looks OK today is:
* to continue building official ScumMVM on …

MACOSX: Remove NSRequiresAquaSystemAppearance from Info.plist

---

engines/ultima/ultima8/filesys/idata_source.h
engines/ultima/ultima8/filesys/odata_source.h

These commits fix compiler warnings that come from headers.
They are all about shadowing a member variable.
Since these headers are included in many other files, the warnings are reduced by about 600 lines.

ULTIMA8: Fix compiler warnings

---

engines/ultima/nuvie/core/converse.h
engines/ultima/nuvie/core/timed_event.h

These commits remove compiler warnings about variable shadowing that come from headers.
As the headers are included in many other files, the warnings are reduced by about 200 lines.

NUVIE: Fix compiler warnings

---

dists/redhat/scummvm.spec
dists/redhat/scummvm.spec.in
ports.mk

The canonical location for AppStream XML files has been changed to `/usr/share/metainfo` four years ago at least, with `/usr/share/appdata` left as legacy location. It is time to switch to the right location.

DISTS: install the AppStream file to the canonical location

---

engines/director/lingo/lingo-builtins.cpp

Improvements to chars implementation:
- handle pass by reference next to pass in of string
Makes the D4 dictionary movie `chars` not exit with a segfault.
- handle when from_id is larger than to_id and return an empty string.
The lingo function chars(string, from_id, to_id) returns the
from_id'th char till and including the to_id'th char of the string, 1 indexed.

DIRECTOR: LINGO: Improve `chars` implementation

---

engines/director/lingo/lingo.cpp
engines/director/lingo/tests/strings.lingo

Fixes the comparison of strings with diacritics

DIRECTOR: LINGO: Ignore diacritics in = operator

---

engines/sci/sound/drivers/midi.cpp

Sierra used MIDI controller 75 for internal purposes, and it shouldn't
be issued to the real MIDI device.
This fixes issue #11409

SCI: MIDI - don't send "controller 75" to physical device

---

devtools/create_project/xcode.cpp

With the project including both iOS and macOS targets, using an absolute path ensures it is incorrect for at least one of those. Since it was using /usr/local/lib/ all the paths had to be changed in Xcode to build the iOS target.
Also as the paths where we expect the libraries to be (/usr/local/lib on macOS and lib under the build directory for iOS) are added to the search path in the Xcode project, we do not actually need to use absolute path). Also this make it easier to use a different path for libraries (e.g. if using MacPort or brew) as we only need to change the search path setting in the Xcode project and not the path for each library).
This was tested on two different machines, one with Xcode 9.2 and one with Xcode 11.4, and on both I was able to build for both iOS and macOS …

CREATE_PROJECT: Use relative paths for static libraries for Xcode

---

common/str.cpp
common/str.h
gui/launcher.cpp
gui/widgets/list.cpp
gui/widgets/list.h

This PR introduces dictionary sort to the list of games.
Thus, 'The Dig' is inserted between 'Deja Vu' and 'Discworld'.
Quick search by typing also works properly.

GUI: Sort games list ignoring articles

---

backends/platform/dc/dc.h
backends/platform/dc/dcmain.cpp

Commit f5238c6 added the `soundType` argument to the `play()` function, which resulted in `DCCDManager` having a different signature for `play()` compared to the base class. A similar fix was made for Linux, Mac OS X and SDL 1.2 in commit de886a8.
As an aside, it might be a good idea to move `DCCDManager` into `backends/audiocd` alongside the Audio CD managers for other platforms, to reduce the possibility of issues like this happening in the future.
This has not been tested.

DC: Fix broken physical audio CD playback

---

backends/events/default/default-events.cpp
backends/platform/ios7/ios7_osys_main.cpp
backends/platform/ios7/ios7_osys_video.mm
backends/platform/ios7/ios7_video.mm
common/system.h
engines/dialogs.cpp
gui/launcher.cpp

I am creating this Pull Request mostly for a review on the first commit (commit 27a4ad0) since it touches common code.
The main idea is that for various reasons on some platform we do not want to allow quitting the application programatically, for example through the use of a Quit button. One such platform is iOS. The first commit in this pull request does the following:
- It adds a kFeatureNoQuit in OSystem.
- If this feature is supported by a backend
- it removes the Quit button from the launcher
- it removes the Quit button from the GMM
- it remaps EVENT_QUIT to EVENT_RTL in the event manager.
The rest of the commits are specific to the iOS backend to use this feature and further remove all use of exit() as well as cleanup the error reporting.

Add kFeatureNoQuit in System to remove the Quit buttons from the GUI

---

common/translation.cpp
common/translation.h
configure
gui/ThemeEngine.cpp
snapcraft.yaml
snapcraft.yaml.in

Added GNU FriBidi, thus allowing Hebrew (or other future RTL languages)
to be displayed correctly.
It's been implemented for all ScummVM GUI (as far as I have noticed),
and can be further used by the engines as needed.
This work is only partial, because for complete BiDi support we'll need
to mirror the widgets, and support input text areas (which currently
don't even support Hebrew text input at all).
Some changes are required in order to to use this:
- Visual Studio:
-- add FriBidi lib from https://github.com/ShiftMediaProject/fribidi
(and place the files in the other libs location)
-- add fribidi.dll to the current directory
-- add fribidi.lib to VS library list
(in GUI it's: Project -> scummvm Properties -> Linker ->
input -> Additional Dependencies)
-- Add USE_FRIBIDI define
either …

GUI: Added (partial) BiDi support

---

engines/ultima/shared/conf/conf_serializer.h

The following change fixes compiler warning about shadowing a variable, because a method with same name exists.
Since the header is included elsewhere, this removes over 580 lines of compiler errors.

JANITORIAL: Fix compiler warning

---

devtools/create_project/xcode.cpp

I broke some builders with a trailing comma in an enum, but xcode was totally ok with it and didn't even issue a warning.
I suggest we add `-Wc++11-extensions` to the build in xcode so others will be warned about the same.  Details on the warnings this adds [are here](https://clang.llvm.org/docs/DiagnosticsReference.html#wc-11-extensions).  Adding this also warns about some uses of `long long`, which we should be mostly avoiding anyway.
I don't have very strong feelings on this, so happy to hear opinions on whether this is a good idea.

CREATE_PROJECT: Add c++11 warnings to xcode project

---

base/plugins.cpp

Doing this as a pull request as I wanted to get a sanity check on it as an idea.
CoreMIDI provides hardware midi device support.
On my MacBook, the first call to MIDIGetNumberOfDestinations() takes around 2
seconds.  Using one of the midi devices lower on the plugin list (mt32,
fluidsynth, etc) takes 2 extra seconds on every game start as
MidiDriver::getDeviceHandle() enumerates all the plugins to find the right one, 
and hits CoreMIDI first.
This change simply moves CoreMIDI to the bottom of the list.  It will still
take 2 extra seconds when opening the options box, but that's a rare operation
relative to starting games.

BASE: Move CoreMIDI to end of list to speed up finding the right device

---

engines/pink/pink.cpp

As mentioned [here](https://github.com/scummvm/scummvm/blob/3c03b4bfc2d31744b43b318ab78623a78d5a2129/common/system.h#L1053), engines should use `CursorMan` instead of calling the `OSystem` cursor functions directly. As such, this PR modifies the Pink engine to reflect that.

PINK: Remove direct use of OSystem cursor functions

---

engines/scumm/palette.cpp

I've added a unique palette for Apple IIgs games, as suggested by a comment in `palette.cpp`. The previous workaround was to use `tableC64Palette` as default.
Color information was pulled [from the bottom of this page](https://mrob.com/pub/xapple2/colors.html), which list converted 12 bits values documented in [Apple IIgs Technical Notes: IIgs 2523063 Master Color Values](https://archive.org/details/IIgs_2523063_Master_Color_Values/mode/2up). Rearranged the palette order to match `tableC64Palette` and tested it with Maniac Mansion (by comparing the scenes[ with screenshots from MobyGames](https://www.mobygames.com/game/apple2/maniac-mansion/screenshots/gameShotId,43107/). 
The only hickup is that, using real hardware, all text is displayed white regardless of context. ScummVM actual …

SCUMM: Add Apple IIgs custom color palette

---

engines/director/score.cpp

D4 kTextCast can be childless, handle that case.

DIRECTOR: Handle D4 copyCastStxts without children

---

engines/director/lingo/lingo-the.cpp

QuickTime is always present since ScummVM handles that.

DIRECTOR: Implement is QuickTimePresent check

---

engines/director/frame.cpp

Fixes a segfault for the rectangle not being valid and
resolves multiple test crashes in the buildbot.

DIRECTOR: return early where textCast is null

---

engines/sci/console.cpp

For SCI debug console,
- Adds missing help doc for script related commands
- These commands were already implemented by missing the help console documentation

SCI: add missing but implemented help commands for script related debug commands

---

engines/pink/gui.cpp
engines/pink/pink.cpp

This pull request makes pink panther scenes to resume correctly after using menu bar

PINK: fixed pausing when menu bar disappears

---

engines/ultima/detection_tables.h

The English usecode file eusecode.flx was not included in the installs for French or German versions of the game when installed from the Gold Edition CD. The checksums remain the same for the language specific usecode.

ULTIMA8: Fix detection of FR_FRA & DE_DEU from Gold Edition CD installs

---

backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/openglsdl/openglsdl-graphics.h
backends/platform/sdl/sdl-window.cpp
backends/platform/sdl/sdl-window.h
backends/platform/sdl/sdl.cpp
backends/platform/sdl/sdl.h

This PR unifies the code for detecting the desktop resolution across both ScummVM and ResidualVM, which previously handled it slightly differently. It's also needed by residualvm/residualvm#1624.

SDL: Move detection of the desktop resolution into the SdlWindow class

---

backends/events/default/default-events.cpp
backends/events/ps3sdl/ps3sdl-events.cpp
backends/platform/3ds/osystem-events.cpp
backends/platform/3ds/osystem.h
backends/platform/android/jni-android.cpp
backends/platform/android/jni-android.h
backends/platform/psp/image_viewer.cpp
backends/platform/psp/image_viewer.h
backends/platform/psp/powerman.cpp
backends/platform/psp/powerman.h

Fix some missed uses of `Engine::pauseEngine` from #2147.

Ports: Pause token mk2

---

engines/director/images.cpp
image/bmp.cpp
image/codecs/codec.cpp
image/codecs/codec.h
image/codecs/jyv1.cpp
image/codecs/jyv1.h
image/module.mk
video/avi_decoder.cpp

The movies for Crusader: No Remorse have a unique decoder which is not too hard
to implement.  Unfortunately, they don't properly implement the "compression"
FourCC, and instead put their ID in the "Stream Handler".  Since supporting
them requires a change to the existing Image API, I thought I should make a
pull request for comments.
With this change, the movies in Crusader can all be played nicely.

IMAGE: Add support for Crusader: No Remorse  movie decoding

---

backends/events/sdl/sdl-events.cpp

Before this commit, when typing in Hebrew, SDL reported the equivalent
English keycode. Thus, if user typed Hebrew letter Aleph, it was
reported as ascii of 't' (or 'T', I don't remember...).
It's still impossible to type Hebrew letters in the GUI's input dialogs,
but it's a step forward.
This was supposed to be part of a bigger PR, adding support for Hebrew in SQ3 (SCI0), but I'm waiting with this PR until there will be a decision in PR #2217. However, it's taking time, and I realized it might help @aryanrawlani28 's work on the GUI, and @BLooperZ 's work on other engines, therefore, it's submitted alone.

SDL: Return unicode keycode for Hebrew input

---

common/stream.cpp
common/stream.h
devtools/create_titanic/zlib.cpp

This is needed for [Biik scripts](https://github.com/ccawley2011/scummvm/blob/5bb055994137e7f909b9df06e67fa6c2dc72d6ab/engines/biik/script.cpp#L55), where CR is used for line breaks within formatted text, while LF is used for separating individual script entries.

COMMON: Allow ignoring CR line breaks in SeekableReadStream::readLine()

---

engines/ultima/ultima8/gumps/container_gump.cpp
engines/ultima/ultima8/gumps/gump.cpp
engines/ultima/ultima8/gumps/gump.h
engines/ultima/ultima8/gumps/item_relative_gump.cpp
engines/ultima/ultima8/gumps/paperdoll_gump.cpp
engines/ultima/ultima8/gumps/slider_gump.cpp
engines/ultima/ultima8/misc/debugger.cpp
engines/ultima/ultima8/ultima8.cpp

ULTIMA8: Custom type checking cleanup
Use template methods for type checking instead of referencing static ::ClassType variable directly.
Alter Gump::FindGump to check matches against a function instead of referencing the RunTimeClassType and remove no_inheritence option as it is never used. These changes should help migration from p_dynamic_cast if desired.

ULTIMA8: Custom type checking cleanup

---

engines/ultima/ultima8/ultima8.cpp

Both the old class name and the new class name for a process or object must be registered for load compatibility

ULTIMA8: Fix loading of game saves after music process rename.

---

engines/director/lingo/lingo-code.cpp
engines/director/lingo/tests/lists.lingo

This fixes property array comparison and implements the special case when a longer array is compared with a shorter array.

DIRECTOR: LINGO: Array comparison fixes

---

engines/director/lingo/lingo-code.cpp
engines/director/lingo/tests/lists.lingo

Upon further testing, this behavior only applies to the = operator.

DIRECTOR: LINGO: Remove quirk handling from <> op

---

engines/petka/detection_tables.h

Yet another "that's so henke37" detection entry update.

PETKA: Engine doesn't use midi, mark the games as such

---

engines/petka/file_mgr.cpp
engines/petka/sound.h

As fun the `pink` games are, this isn't that engine.

Petka: Fix copy and paste errors in comments

---

engines/ultima/ultima8/meta_engine.cpp
engines/ultima/ultima8/misc/debugger.cpp
engines/ultima/ultima8/misc/debugger.h
engines/ultima/ultima8/world/actors/avatar_mover_process.cpp
engines/ultima/ultima8/world/actors/avatar_mover_process.h

ULITIMA8: Improve basic avatar keyboard movement.
This adds continuous movement while the movement keys are depressed. I'm an unsure how Crusader should move, so this was just experimenting until the controls felt good for the Avatar.  I'm thinking a few adjustments might be keyboard jumping being a jump forward instead of towards mouse, and maybe shift modifier to run and control modifier to step.

ULITIMA8: Improve basic avatar keyboard movement.

---

backends/platform/sdl/win32/win32.cpp
common/translation.cpp
common/translation.h
common/unicode-bidi.cpp
common/unicode-bidi.h
engines/sci/detection.cpp
engines/sci/detection_tables.h
engines/sci/graphics/text32.cpp
engines/sci/sci.cpp
engines/sci/sci.h

- Detect fan made Hebrew translation of Torin's Passage
- Use BiDi algorithm in SCI engine

SCI: add support for Hebrew translation of Torin

---

engines/dragons/dragons.cpp
engines/dragons/midimusicplayer.cpp
engines/dragons/midimusicplayer.h
engines/dragons/minigame2.cpp
engines/dragons/minigame3.cpp
engines/dragons/module.mk
engines/dragons/scriptopcodes.cpp
engines/dragons/sound.cpp
engines/dragons/sound.h
engines/dragons/specialopcodes.cpp
engines/dragons/talk.cpp

I'm starting to implement music for Blazing Dragons. It uses PS1 SEQ files for music. These files are almost identical to standard SMF MIDI but use specific sound bank for instruments.
I've copied the method that is used by the tinsel engine to support SEQ files.
I was thinking that we could load the sound bank samples automatically in the engine and convert them into the soundfont format to be used by midi drivers that support loading samples.
I haven't implemented the soundfont loading bit yet. It would probably require changes to base audio classes.
What does everyone think?
This PR implements the midi player. I've tested it with a manually converted VAB to SF2 file and it sounds good to my ears.
I could also apply this technique to the tinsel engine to add proper sound samples there …

DRAGONS: Implementing midi music player

---

configure

This is useful when building using the docker images from [dockerized buildbot](https://github.com/lephilousophe/dockerized-bb) separately from the buildbot setup.

ANDROID: Set a default path for PKG_CONFIG_LIBDIR

---

engines/director/util.cpp

Filepaths are converted between mac and windows filepaths. In some cases the filenames were converted correctly, without doing a pass. A filepath conversion would return the same filepath. This wasn't recognized as a conversion that succeeded.
The fix is check if the resulting filename can be opened.

DIRECTOR: Fix file path loading

---

.travis.yml

Current builds saturate Travis CI caches:
```diff
$ diff -U999 /tmp/ccache_before /tmp/ccache_after || true
--- /tmp/ccache_before	2020-05-08 16:34:12.987955074 +0000
+++ /tmp/ccache_after	2020-05-08 16:45:45.570927610 +0000
@@ -1,13 +1,13 @@
cache directory                     /home/travis/.ccache
primary config                      /home/travis/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
cache hit (direct)                  2816
cache hit (preprocessed)            1045
-cache miss                       5751026
-called for link                    85473
-called for preprocessing            3832
-compile failed                     11462
-no input file                       2558
-files in cache                     11334
-cache size                         451.9 …
```

TRAVIS: enable ccache compression

---

backends/platform/null/null.cpp
backends/timer/default/default-timer.cpp
backends/timer/default/default-timer.h

It's necessary for all backends to implement timers, as there are major issues without them. Most notably, it's not possible to get past the initial splash screen without `getMillis()`.
The changes related to `DefaultTimerManager` are loosely based on how timers are implemented in the N64, iPhone and iOS 7 backends. It could potentially be used to clean up timer handling in those backends, however I'm not able to test the required changes.

NULL: Add implementation of timers on POSIX systems

---

backends/graphics/opengl/opengl-graphics.cpp

`GL_RGBA` and `GL_UNSIGNED_BYTE` are guaranteed to be usable with `glReadPixels()` when using OpenGL ES 1.

OPENGL: Use a 4 bytes per pixel mode when taking screenshots

---

base/module.mk
base/test_new_standards.cpp
configure

Adding C++11 compatibility tests, disabled by default.
See instructions inside the file.

BASE: Added 'test_new_standards.cpp'

---

base/test_new_standards.cpp
configure

I am creating a pull request for this so that a second pair of eyes can take a look before this is pushed (I am not very confident with my c++11 skills since we are not allowed to use it yet where I work).

BASE: Fix and enable INITIALIZIER_LIST1 c++11 test

---

backends/platform/3ds/osystem-events.cpp

That makes build fail when using -ansi

3DS: Don't use auto as it's a C++11ism

---

engines/wintermute/detection_tables.h
engines/wintermute/wintermute.cpp
engines/wintermute/wintermute.h

Add 'Informer Alavi' Beta version.
Note: Dates in description are Persian-calendar based, as found in the developers page

WINTERMUTE: Add Informer Alavi Beta version

---

engines/hugo/dialogs.cpp

Fixing a potential memory leak reported by deepcode.ai.
Opening this as PR to check deepcode.ai integration.

HUGO: Properly deallocate _arrayBmp

---

engines/director/frame.h
engines/director/score.cpp
engines/director/score.h
engines/director/transitions.cpp

To facilitate later refactoring, transitions are moved out of the frame and into the score.

DIRECTOR: Move transitions to the score

---

backends/platform/ds/ds.mk

Compiling externally provided C files using CXXFLAGS makes build fail
when specifying -ansi because files are not ANSI C compliant.
configure script don't provide a CFLAGS variable so we just override
using -std flag

DS: Fix build of C files when specifying -ansi in CXXFLAGS

---

configure

This allows backends to use non-ANSI functions.
As it was the main reason to not set -ansi on these platforms, add it
back to ensure strict adherence to C++ standard.
This commit makes compilation work when using --enable-c++11 on tested platforms.
Adding -ansi is where the risk is and we could add -U__STRICT_ANSI__ only when enabling C++11 on newlib platforms.
Though, I think using -ansi everywhere would be nice to have.
:warning: This commit has only be tested on some platforms impacted by this change and some are still missing.
Most tests have been done using [dockerized-bb](https://github.com/lephilousophe/dockerized-bb).
For DS, PR #2294 is needed to compile without C++11 mode.
@sev- I don't really know how to ask to porters to test this change, hence I request your review :)

CONFIGURE: Undefine __STRICT_ANSI__ for newlib based platforms

---

engines/director/lingo/lingo-events.cpp
engines/director/lingo/lingo-the.cpp
engines/director/sprite.cpp
engines/director/sprite.h

This implements the sprite property `immediate`, which causes sprite scripts to run on mouseDown instead of mouseUp.

DIRECTOR: LINGO: Implement kTheImmediate

---

graphics/macgui/macwindowmanager.cpp

This pull request fixes activation of menu if it is active.
If menu is activated more than 1 time, it restores screen with menu drawn and moreover leads to error due to assigning to busy PauseToken, which leads to bugs in Pink Panther games .

MACGUI: don't activate menu if it is active

---

audio/mididrv.cpp
audio/mididrv.h
audio/softsynth/fluidsynth.cpp

* Add ability for engine to supply its own soundfont data.
* Add MDT_PREFER_FLUID to allow engines to indicate they prefer the fluidsynth driver.
The fluidsynth driver will only be given preference if the midi driver is set to auto.
This PR allows engines to specify their own soundFont data. This will be used by Blazing Dragons and Tinsel to support PSX SEQ midi music.
I will work on a midiPlayer to extracts the soundFont data in another PR.
I added the following new virtual methods to the midi driver class.
```
// Allow an engine to supply its own soundFont data. This stream will be destroyed after use.
virtual void setEngineSoundFont(Common::SeekableReadStream *soundFontData) { }
// Does this driver accept soundFont data?
virtual bool acceptsSoundFontData() { return false; }
``` …

AUDIO: Add ability for engine to supply its own soundfont data.

---

engines/director/lingo/lingo-preprocessor.cpp
engines/director/score-loading.cpp

This is a new version of #2305, which removes a faulty whitespace check in loadScriptText and skips garbage in script text.

DIRECTOR: LINGO: Fix script text loading

---

common/util.h

If the boundary arguments of CLIP function are not ordered as expected (the first should the min of the two), then the function may return an invalid result. This is more likely to happen if the boundary arguments are variables rather than literals.

COMMON: Use assert for CLIP() if bounds are not properly ordered

---

common/config-manager.cpp
common/config-manager.h
common/gui_options.cpp
engines/advancedDetector.cpp
engines/advancedDetector.h
engines/mohawk/detection.cpp

This allows subclasses to post-process the games detected by AdvancedMetaEngine before they are added to / updated in the configuration file.
This fixes the issue @antoniou79 noticed where the list of available languages was incorrect in the edit game dialog after starting Myst Masterpiece 25th Anniversary Edition for the first time.

ENGINES: Make AdvancedMetaEngine::toDetectedGame virtual

---

common/unicode-bidi.cpp

FriBidiChar is mapped to uint32_t (from stdint.h) while U32String is
composed of uint32 (from scummsys.h/config.h). On some platforms (like in 3DS) those
two types aren't defined using the same base type (long int vs int) and
compilation errors occur.

COMMON: Fix build when uint32_t and uint32 are not defined the same

---

engines/wintermute/POTFILES
po/scummvm.pot

Fixed typo in Wintermute POTFILE. It was missing the folders. The file also needed a carriage return at the end.
I haven't updated the translations.dat before so I've make a PR just to check I'm following the right process.

I18N: Fixed typo in wintermute/POTFILES. Updated translations.dat

---

engines/wintermute/base/base_engine.h
engines/wintermute/wintermute.cpp

Let's merge recently added "flags & GF_3D" check and existing 3D characters lookup heuristic check into a single notification warning.
It's useful to have both:
* for known games, GF_3D flag is set manually for 2.5D games
* for unknown games, 3D-characters lookup is made

WINTERMUTE: Fix double-notifications for 3D games

---

engines/sci/resource_audio.cpp

ScummVM doesn't play several Adlib sounds in The Colonel's Bequest when using the Adlib driver: https://bugs.scummvm.org/ticket/10734 
The current logic in SoundResource::getChannelFilterMask() is intended to always play channel 9 if a driver has a rhythm channel, even if the driver's play-flag isn't set in the sound resource. The way it's written though, it also bans channel 9 from ever playing if a driver doesn't have rhythm channel, such as Adlib, which is incorrect.
This PR adds the normal play-flag check to channel 9 when the driver doesn't have a rhythm channel. (This switch hasn't been touched in 10 years!)
For example, here are the channels in sound 48, when knocking on the door in room 14:
channel: 01 voices: 00 flags: 30
channel: 09 voices: 82 flags: 0F [ Adlib flag 04 ]
Other …

SCI: Allow channel 9 on all matching audio drivers

---

engines/director/director.cpp
engines/director/director.h
engines/director/lingo/lingo-preprocessor.cpp

This allows the preprocessor to be debugged without tens of thousands of lines of parse output.

DIRECTOR: LINGO: Add preprocess debug flag

---

engines/voyeur/data.cpp
engines/voyeur/data.h
engines/voyeur/files_threads.cpp
engines/voyeur/voyeur.cpp
engines/voyeur/voyeur.h

Persist data that the original game kept between games.
Took the time to remove an unneeded duplicate variable. Which was unfortunately in the save file, so the save version had to be bumped.

VOYEUR: Persist data in the config file

---

engines/scumm/string.cpp

Apparently, my previous PR #1989 for supporting fan-translated hebrew version of SCUMM games broke official translation of HE games (HE version 73 and 99).
It made the games crash with `handleNextCharsetCode: invalid code ...` (even with subtitles off)
I have added a condition so HE games are not affected by the reversal of strings.
Now HE games are working again, sorry.

SCUMM: do not reverse strings in HE

---

audio/midiparser.cpp
audio/midiparser.h
audio/midiparser_xmidi.cpp
engines/ultima/ultima8/audio/midi_player.cpp
engines/ultima/ultima8/audio/midi_player.h
engines/ultima/ultima8/audio/u8_music_process.cpp
engines/ultima/ultima8/audio/u8_music_process.h

This adds support for the "sequence branch index" feature of the XMIDI format. 
These "branches" (positions in the MIDI bytestream) are defined in the track 
header. I've added two generic functions to the MidiParser interface to set the 
current parsing position to one of these positions, or to check for the 
existence of a position with a certain number.
Additionally, I've added an option to the MIDI parser to prevent the parser 
from starting playback immediately after parsing, so that a starting position 
(or a track) can be selected first.
Ultima 8 uses sequence branches to mark different playback starting points in 
the music files. I've added support for starting playback at these points.

MIDI/ULTIMA8: Add XMIDI sequence branch indexes

---

dists/engine-data/testbed-audiocd-files/TEST3/FILE.txt
dists/engine-data/testbed-audiocd-files/Test2/File.txt
dists/engine-data/testbed-audiocd-files/tEST4/fILe.txt
dists/engine-data/testbed-audiocd-files/test1/file.txt
dists/engine-data/testbed-audiocd-files/test5/file
engines/testbed/config-params.cpp
engines/testbed/detection.cpp
engines/testbed/graphics.cpp
engines/testbed/graphics.h
engines/testbed/testbed.cpp
engines/testbed/testbed.h
engines/testbed/testsuite.cpp
engines/testbed/testsuite.h

1. Minor refactoring to have a single function to create testsuites list both at TestbedEngine() constructor and metaengine's getAchievementsInfo() method. Some code was moved away from GFXTestSuite() constructor to avoid running it inside getAchievementsInfo() from main menu.
2. Fixed a bug that chashed TestBed after Return-To-Launcher
3. Give achievement for each testsuite and a secret achievement for completing them all.
4. Added some files required for FS testsuite to pass (test1/file.txt, etc)

TESTBED: Bugfix & Achievements

---

audio/midiparser_xmidi.cpp

XMIDI uses Note On events with a length which specifies when a corresponding
Note Off event should be generated. Some XMIDI data contains notes with length
0, which are played very briefly by AIL. However, the ScummVM MidiParser will
treat Note On events with length 0 as "active notes", meaning it will wait for
a Note Off event before turning off the note. The Note Off will never come and
the note will hang.
This is particularly noticeable in Ultima 8 (first section of the track that
plays at the beginning of the game, at the shore) and The 7th Guest (the track
that plays while solving the cake puzzle).
I've fixed this by changing the length from 0 to 1. This will cause the notes
to be active for the minimum length.

MIDI: Fix XMIDI hanging notes

---

engines/xeen/dialogs/dialogs_char_info.cpp

The code was correct when clicking the stats with the mouse (case 1001 through 1020).

XEEN: Fix crash when accessing character stats with keyboard

---

engines/glk/comprehend/draw_surface.cpp

This commit removes a compiler warning about discarding qualifiers.

GLK: COMPREHEND: Fix compiler warning

---

common/c++11-compat.h
common/lua/lcode.cpp
engines/draci/walking.cpp
engines/glk/adrift/scparser.cpp
engines/glk/adrift/scprintf.cpp
engines/glk/tads/tads2/regex.cpp

The first commit is cherry-picked from the [shivers2 branch](https://github.com/csnover/scummvm/commit/7cf86625f9fbb30562e24b368e580594d1818aed). The remaining commits fix compilation errors caused by the replacement `final` keyword clashing with variable names.

COMMON: Allow use of C++11 final keyword

---

configure
engines/wintermute/wintermute.cpp

The use of operator names works fine on gcc and clang, but breaks MSVC.  Make
them error on gcc/clang too.
According to this random link, gcc and clang have supported this flag for a
really long time, so it shouldn't need an extra compile check:
https://phabricator.kde.org/D3850
Since I've never changed the `configure` file before I wanted to get more eyes on this change, so doing as a PR.
Background: My last PR (#2214) contained an `and`, which worked on all the buildbots, but broke when someone tried to compile with MSVC.  This should avoid similar breakage in the future.

CONFIGURE: Add -fno-operator-names for clang/gcc

---

engines/wintermute/ad/ad_game.cpp
engines/wintermute/base/base_game.cpp
engines/wintermute/base/base_game.h

This implements enhancement #11032 WME: Add save thumbnails to Corrosion: https://bugs.scummvm.org/ticket/11032
1. Move some code to separate methods to make it accessible from other code points.
2. Clean cached thumbnail on game load (I believe it's original WME engine bug that this thumbnail may be not cleared after game load)
3. Save thumbnail to cache on Game.FadeOut(750) for Corrosion
4. Delete thumbnail on Game.UnloadObject(<interface\\system\\mainmenu.window>) for Corrosion
This has some unsupported scenarios like "opening the save menu, then opening ScummVM menu, save in second one, save in first one", but works in all normal use-cases.

WINTERMUTE: Add save thumbnails to Corrosion

---

engines/wintermute/base/base_game.cpp
engines/wintermute/base/base_game.h
engines/wintermute/base/base_game_custom_actions.h
engines/wintermute/keymapper_tables.h
engines/wintermute/platform_osystem.cpp

This implements enhancement  #11503 WME: Implement walking with arrow keys for Corrosion: https://bugs.scummvm.org/ticket/11503
"Corrosion: Cold Winter Waiting" (both original and enchanted edition) requires a lot of walking.
However, this is originally controlled with mouse, by clicking on the edges or the center of the screen, which requires a lot of mouse moving and is not fun.
Mapping some arrow keys to mouse clicks on given regions may be a nice way to improve this game experience.

WINTERMUTE: Implement walking with arrow keys for Corrosion

---

audio/mididrv.cpp
audio/mididrv.h
audio/midiparser.cpp
audio/midiparser.h
audio/midiparser_xmidi.cpp
audio/miles.h
audio/miles_midi.cpp
engines/kyra/sound/sound_pc_midi.cpp

This PR fixes a few minor issues with MIDI playback in KYRA engine games:
- SysExes embedded in MIDI files would cause an OSystem:delayMillis call, which 
would affect the timing of the MIDI parser and cause MIDI events to "pile up" 
and be executed in a shorter timespan than intended. I've changed this so the 
MIDI parser will pause playback for the necessary time between SysExes, which 
avoids this problem. This restores a sound effect after the MT-32 
initialization of Legend of Kyrandia.
- I've added the instrument fallback feature of the Roland SC-55 that corrects 
invalid bank selects. Lands of Lore depends on this in some cases, f.e. the 
sound effect of the ring in the introduction.
- Lands of Lore GM initialization was not done. These SysExes only affect the 
display of the …

KYRA/MIDI: Fix minor MT-32/GM issues

---

engines/wintermute/base/base_game.cpp
engines/wintermute/base/scriptables/script_engine.cpp
engines/wintermute/base/scriptables/script_engine.h

Previous PR was completed too soon.
1. Added if-statement & comment to state that those custom actions are currently for Corrosion only
2. Fixed kClickAtBottom offset for original game
3. Fixed stuck-at-map buug for Enchanted Edition

WINTERMUTE: Improve keyboard walking for Corrosion

---

audio/mididrv.cpp
audio/mididrv.h

Fixes a missing variable initialization and unnecessary if statement introduced by 
my latest KYRA changes.

MIDI: Fix _gsBank init and bad if statement

---

engines/director/director.cpp
engines/director/director.h
engines/director/score.cpp
engines/director/score.h

It's now possible to screenshot all played frames by using:
`--debugflags=screenshot`
Note: it's PNG.

DIRECTOR: implement debugflag for screenshotting

---

engines/wintermute/detection_tables.h

Everyday Grey is a 2D game, which contains no 3D scenes or 3D actors. Removed GF-3D flag.

WINTERMUTE: Remove GF_3D flag for Everyday Grey

---

engines/wintermute/base/base_file_manager.cpp
engines/wintermute/video/video_theora_player.cpp

Some things that popped up during implementing the WIntermute 3D port in ResidualVM.
The theora video player should use the appropriate factory method to create a surface instead of constructing it directly.
The file manager changes forward to backward slashes when opening files from a dcp package. However, when it's only looking for a file, slashes are not flipped, which is inconsistent and causes bugs in Alpha Polaris.

WINTERMUTE: Theora and BaseFileManager::hasFile residualvm fixes

---

backends/dialogs/gtk/gtk-dialogs.cpp

[`GtkFileChooserNative`](https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html) was introduced in GTK 3.20, however Ubuntu 16.04 only has GTK 3.18.

GTK: Support building with older versions of GTK

---

devtools/create_project/xcode.cpp

The existing code broke create_project in ResidualVM, as
the loop that creates the actual build configurations
generated the hash from the actual object name, which
for ResidualVM would be XCConfigurationList_residualvm.
The same logic was not applied when generating the reference,
as that would use the hardcoded name XCConfigurationList_scummvm.
This patch makes a minimal fix for that, by using the
PROJECT_NAME define instead of the hardcoded name.

DEVTOOLS: Unhardcode scummvm-name in create_project for XCode.

---

engines/glk/zcode/windows.cpp

Currently Beyond Zork does not display correctly. It appears that the text is not correctly placed in the Text Grid Window. I don't know if this is the correct change, but just removing the division by the font width and height in `Glk:ZCode::Window::setCursor()` seems to fix the issue. I have not tested with any other games though.
Here are comparaison between current master with and without this change.
Copyright screen without the change:
And with the change:
Character setup without the change:
And with the change:
Hilltop without the change:
And with the change:

GLK: ZCODE: Fix moving cursor in TextGridWindow

---

engines/director/lingo/lingo-builtins.cpp
engines/director/lingo/lingo-builtins.h
engines/director/lingo/tests/strings.lingo

scummvmAssert is a scummvm specific Lingo function.
Useful for getting feedback on lingo code tests without
having to check if the output is as expected.
Example:
set x = True
scummvmAssert(x)    // will pass
set x = False
scummvmAssert(x)    // will fail
The core of the implementation is: `assert(d.asInt() == 1)`.
It's defined as a Lingo builtin function for D2.
strings.lingo has been modified to leverage the new scummvmAssert.

DIRECTOR: LINGO: implement scummvmAssert

---

engines/wintermute/ad/ad_game.cpp
engines/wintermute/ad/ad_game.h
engines/wintermute/base/base_game.cpp
engines/wintermute/base/base_game.h
engines/wintermute/base/base_game_custom_actions.h
engines/wintermute/keymapper_tables.h

1. Added keymaps for Carol Reed 5-12 and Life in 3 minutes
2. Keyboard movement added to 10 more 1st person WME2D games!
3. Keyboard movement now use "smart" forward key, which clicks on object closest to screen center (useful for opening doors, picking the only one object on the screen, etc)
4. Carol Reed 4 keymap is tweaked to avoid using up/down keys and joy controls.

WINTERMUTE: Add move keymaps and improve keyboard movement

---

backends/platform/android/android.mk
configure

BUILD: Support building Android on OSX
Updated the build files to enable Android compilation on OSX, and remove the NDK version from the env var.
Can someone on Linux make sure nothing broke there?

BUILD: Support building Android on OSX

---

.clang-format
audio/decoders/flac.cpp
common/scummsys.h
devtools/create_project/create_project.cpp
devtools/create_project/create_project.h
devtools/create_project/msbuild.cpp
devtools/create_project/msbuild.h
devtools/create_project/msvc.cpp
devtools/create_project/msvc.h
devtools/create_project/visualstudio.cpp
devtools/create_project/visualstudio.h

[vcpkg](https://github.com/microsoft/vcpkg) is a C++ Library Manager, primarily for Windows. It's fairly popular as Windows is missing a proper package manager built into the system. Vcpkg also provides support for targetting different architectures supported by MSVC: x86, AMD64, arm64.
Last year I built ScummVM for Windows on Arm as a one-off binary and created relevant ports in vcpkg upstream. The last has finally landed and I want to contribute a more sustainable way of producing vcpkg-based ScummVM builds and extend support for MSVC arm64.
My initial plan was to use cmake, the cross-platform meta build system, but ScummVM seems to take the cross-platform out of it, so instead I restorted to using the msbuild-based system.
I tried keeping with the code style, but given how many …

Add support for MSVC AArch64 and vcpkg

---

.github/workflows/ci.yml

CI integration extracted from https://github.com/scummvm/scummvm/pull/2248 which uses GitHub Actions to provide builds.
Not expected to work until #2248 gets merged, but at the same time #2248 won't get verified with GitHub Actions due to missing workflow definitions in the upstream.
There's caching of vcpkg libraries implemented inside the action, however my tests suggest it works for x86 and arm64 only, with AMD64 job rebuilding them over and over again. I don't know why that is and would rather see the job removed instead of investigating why. The jobs all produce relevant artifacts: libs as produced by vcpkg, scummvm binaries with all used libs, debug symbols.
You can see how it works over at https://github.com/janisozaur/scummvm/actions

CI: Add GitHub Actions-based CI to excercise vcpkg and MSVC AArch64

---

engines/sci/graphics/video32.cpp
engines/wintermute/base/base_persistence_manager.cpp
engines/wintermute/base/gfx/base_image.cpp
engines/wintermute/base/gfx/osystem/render_ticket.cpp
graphics/conversion.cpp
graphics/conversion.h
graphics/surface.cpp
graphics/surface.h
graphics/transparent_surface.cpp
graphics/transparent_surface.h

In addition, this also allows the bilinear scaling code to be used with pixel formats other than RGBA8888, which should hopefully fix [Trac 11332](https://bugs.scummvm.org/ticket/11332).

GRAPHICS: Move code for scaling out of TransparentSurface

---

common/str.cpp
common/str.h

It's UB to compare pointers that aren't from the same array. Cast to uintptr_t to reduce the issue to IB.

COMMON: Dedicated function for in buffer check

---

.github/workflows/ci.yml

This works around the issue of the x86 and x64 builds timing out when installing packages.

CI: Disable fribidi for all MSVC builds

---

base/commandLine.cpp
engines/director/detection.cpp
engines/director/director.h
engines/director/lingo/lingo.cpp
engines/director/stage.cpp
engines/director/stage.h

A frame number can be given to --start-movie and it will start
at that frame.
Examples:
--start-movie=movie.dir:45  # start movie.dir at frame 45
--start-movie=:23           # start the default movie frame 23
--start-movie=movie.dir     # start movie.dir as usual

DIRECTOR: Extend --start-movie to start at frame

---

common/unicode-bidi.cpp
gui/widgets/editable.cpp

- Fix a small issue of 2 chars being wobbled together if pressing home/end in EditableWidgets.
- Fix warnings being repeatedly printed in the console, when using an RTL language with FriBiDi disabled.

GUI: Small patches.

---

engines/agi/agi.cpp
engines/agi/agi.h
engines/agi/cycle.cpp
engines/agi/detection.cpp
engines/agi/detection_tables.h
engines/agi/menu.cpp
engines/agi/words.cpp

Following the suggestion at https://bugs.scummvm.org/ticket/7026, added a `Speed` menu to Apple2GS AGI games.
This menu is configurable, and can be disabled.
The speed can also be changed by text parser commands.
`Normal` speed is as before, with the speed set by the apple2gs workaround mechanism that was added in the past to solve sound issues.
Other speeds are used only if there isn't a specific workaround speed for that room.
Edit
====
It's disabled by default.

AGI: Apple2GS: Add `Speed` menu and commands

---

backends/platform/null/null.cpp
configure

This allows the debugger to be activated when using the null backend. This is done using a signal handler. In addition, the text console is now enabled by default when using the null backend, since the regular console obviously won't work without proper graphics or input support.

NULL: Allow using Ctrl+C to open the debugger

---

backends/platform/dc/dc.h
backends/platform/ds/arm9/source/osystem_ds.h
backends/platform/n64/osys_n64.h
backends/platform/ps2/Gs2dScreen.cpp
backends/platform/psp/osys_psp.h
backends/platform/wii/osystem.cpp
backends/platform/wii/osystem.h
backends/platform/wii/osystem_gfx.cpp
graphics/colormasks.h

A number of backends use `Graphics::createPixelFormat<>()`, to specify the pixel format used by the overlay, however the GUI was rewritten to use `Graphics::PixelFormat` instead of `Graphics::ColorMasks` in commit a3516483587b736922901ae74305dcf6f043987c. Replacing this means that some of the platform-specific `ifdef`s in `graphics/colormasks.h` can be removed.
In addition, I also removed the additional use of `Graphics::ColorMasks` in the Wii backend, which means that the Wii-specific ARGB3444 ColorMask can also be removed. It's only used in `setPalette`, `grabPalette` and `setCursorPalette`, so the performance impact should be minimal.
The Dreamcast and N64 changes have not been tested. I also didn't touch the iPhone and iOS 7 backends.

BACKENDS: Replace use of Graphics::ColorMasks

---

engines/director/lingo/lingo-object.cpp
engines/director/lingo/lingo.h
engines/director/lingo/tests/XObjects.lingo
engines/director/lingo/tests/flushXObj.lingo
engines/director/lingo/xlibs/flushxobj.cpp
engines/director/lingo/xlibs/flushxobj.h
engines/director/lingo/xlibs/palxobj.cpp
engines/director/lingo/xlibs/palxobj.h
engines/director/module.mk

FixPalette is an XObject for Mac that patches the palette.
According to the docs it's either needed after an 8 palette switch
or when using QuickTime movies with more than one custome palette.
Afterwards the colors will be wrong.
The mPatchIt function that correctly sets the palette is stubbed.
Note: It's at the moment of writing this commit unknown if the
bug will show itself on the mac versions of games.

DIRECTOR: LINGO: STUB XObject FixPalette

---

engines/director/cast.cpp
engines/director/cast.h
engines/director/lingo/lingo-bytecode.cpp
engines/director/movie.cpp
engines/director/movie.h

Repair the castIds of script when the scripts are loaded.
The castIds that are defined in the scripts can be wrong.
A better way to link scripts with casts is via the scriptId.
To achieve this casts need to be fetched by their scriptId.
This commit implements the necessary getCastMemberByScript functions
to enable fetching a cast by it's scriptId.

DIRECTOR: LINGO: Add scripts to the correct cast

---

engines/pink/pink.cpp

Write to the log when the timestamps are mismatched so that the issue has a chance of being spotted.

PINK: Warn when the timestamps mismatch

---

engines/agi/saveload.cpp

`_game.horizon` is defined as uint16, but was casted to uint8 before saving
thus, caused problems for values bigger than 128 - they were interpreted
as negative values

AGI: Fix bug #11209 (wrong `horizon` value saved)

---

engines/cine/anim.cpp

Hopefully a fix for Coverity check CID 1430586
("Untrusted value as argument").

CINE: Add _animDataTable bounds checkings.

---

engines/cine/sound.cpp

Fix bug #11547 ("CINE: FW: Game crashes during intro with MT-32 music").
Future Wars PC disassembly passes 256 to writeInstrument and
writeInstrument overwrites it with value 246 here. So the value
becomes 246 in the end.

CINE: FW: Fix Roland MT-32 sample playing.

---

engines/agos/string.cpp
engines/agos/subroutine.cpp

Proposed fix for a bug I've reported some years ago:
https://bugs.scummvm.org/ticket/6220
SIMON2-FR would crash really early with a SIGBUS on OpenBSD/loongson, which is a mips64el system with strict alignment constraints.
Aligning to `sizeof(byte *)` in alignTableMem(), and calling alignTableMem() in loadTextIntoMem() seems to be enough. It just took me a bit of time to test this :)
(Maybe alignTableMem() could be optimised a bit, but I'm not sure it's worth it.)
Tested with SIMON2-FR and SIMON1-FR on OpenBSD/loongson and on macOS Mojave (x86-64).
I don't really know how to test the "running out of memory" possible case that lordhoto reported above, though. Don't know which platform or use case would be more likely to hit it.

AGOS: Fix compatibility with strict-alignment architectures

---

engines/cine/cine.cpp
engines/cine/saveload.cpp

This pull request has two bugfixes:
#1:
Future Wars PC disassembly does not save disableSysteMenu variable.
After adding versioning to Future Wars saves this value was also
saved and loaded but using it on load seems to have caused the
action menu (EXAMINE, TAKE, INVENTORY, ...) to be disabled sometimes
when it is not supposed to be disabled. Thus, now skipping the loading
of disableSystemMenu variable for versioned Future Wars saves.
#2:
Using the current screen contents for autosaves now.
For non-autosaves the screen contents before opening
the system menu are used.

CINE: Fix disabled action menu and autosave thumbnail.

---

backends/text-to-speech/windows/windows-text-to-speech.cpp

A number of additional voices on Windows 10 are listed as OneCore voices, and are intended to be used via the Universal Windows Platform APIs, however it is possible to use them via SAPI using the hack provided in this PR. Tested on both Windows 10 and Windows XP.
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1544143

WIN32: Support using additional OneCore voices for text to speech

---

backends/platform/sdl/sdl-window.cpp

Currently, `getDesktopResolution()` is only used when OpenGL support is enabled, but since it appears that all supported Maemo devices have the same screen resolution, it shouldn't hurt to add a special case here.
This has not been tested.

MAEMO: Fix compilation with older SDL versions

---

engines/kyra/gui/gui_lol.cpp

This small quality-of-life change suggests a new savegame name with the current time and date for the Land of Lore games. This allows to play the games with less usage of a keyboard (e.g. only qith mouse or remapping keys to a gamepad).

KYRA: Automatically suggest current time when adding a new savegame

---

engines/sci/graphics/text16.cpp

Adding BiDi function call for menus if the language is RTL.
Before this fix, the menu names were written reversed in Hebrew.

SCI: Make menus BiDi

---

engines/sci/parser/vocabulary.cpp
engines/sci/parser/vocabulary.h

Added verb prefix rules required for SQ3 Hebrew translation.
Removed the suffix rules, since they are now added with a vocab.901 file

SCI: Hebrew - add prefix rules

---

audio/module.mk
audio/soundfont/VGMTrans_LICENSE.txt
audio/soundfont/common.h
audio/soundfont/rawfile.cpp
audio/soundfont/rawfile.h
audio/soundfont/rifffile.cpp
audio/soundfont/rifffile.h
audio/soundfont/sf2file.cpp
audio/soundfont/sf2file.h
audio/soundfont/synthfile.cpp
audio/soundfont/synthfile.h
audio/soundfont/vab/psxspu.cpp
audio/soundfont/vab/psxspu.h
audio/soundfont/vab/vab.cpp
audio/soundfont/vab/vab.h
audio/soundfont/vgmcoll.cpp
audio/soundfont/vgmcoll.h
audio/soundfont/vgminstrset.cpp
audio/soundfont/vgminstrset.h
audio/soundfont/vgmitem.cpp
audio/soundfont/vgmitem.h
audio/soundfont/vgmsamp.cpp
audio/soundfont/vgmsamp.h

This PR adds support for converting PS1 VAB sample data into soundfont2 format. This can then be used by fluidsynth to play music from playstation games. 
These include Blazing Dragons and tinsel engines.
I've taken the VAB to SF2 logic from the VGMTrans project. I've removed all  C++11 code and converted everything over to the ScummVM code style.
example usage.
```
MemFile *memFile = new MemFile(vabData, vabDataSize);
debug("Loaded vab file size: %lu", memFile->size());
Vab *vab = new Vab(memFile, 0);
vab->LoadVGMFile();
VGMColl vabCollection;
SF2File *file = vabCollection.CreateSF2File(vab);
const byte *bytes = (const byte *)file->SaveToMem();
```
I would like to use this to play PS1 SEQ files in the blazing dragons engine. It should also work for vab data used by the PS1 version in …

AUDIO: SoundFont2 creation support

---

engines/kyra/engine/lol.cpp

This removes the extra ')' in the first two entries of the keymap description and add the map button (m).

KYRA: Fixed typos in keymap entries and added map key

---

engines/glk/adrift/detection_tables.h

GLK: Fix typo in ADRIFT game title

---

engines/glk/adrift/detection_tables.h

There has been a mix-up in one game title.
1hgfrog is actually "The Green Princess" while 1hgprincess1 is "The Princess In The Tower" as the in-game titles suggests
- Added an ADRIFT 5 game comment (1hgamonkeytoomany)
- Fixed three leading whitespaces in game titles
- Fixed two "TODO" game titles ("Doom Cat!!!" and "A Masochist's Heaven")

GLK: ADRIFT - Fix/Add game titles and one mixup

---

engines/director/director.h
engines/director/movie.h

The InfoEntry struct owns a buffer, so the default copy constructor is wrong. This oversight lead to a double free.

DIRECTOR: Fix info entry double frees

---

engines/glk/adrift/detection_tables.h

"tcom" is "The Cave of Morpheus"
(i *think* it consists of part 1 and 2 but i can´t be sure, since this is an unsupported v5 game)
According to the information given in this results list from if-archive.org, it matches:
https://www.ifarchive.org/if-archive/games/competition2001/results.txt
See entry 33, second line (It´s the only game that matches the short name)
In addition this also fixes bug #11569
(https://bugs.scummvm.org/ticket/11569)
It´s because of a second entry with the same short name of "tcom" living in GLK/GLULXE ("The Colour of Magic")
They clash and break the "Add game" option on my platform.
See here for the entry in GLULXE:
​https://github.com/scummvm/scummvm/blob/master/engines/glk/glulxe/detection_tables.h#L206

GLK: ADRIFT - Fix #11569 by extending game entry

---

devtools/create_project/codeblocks.cpp
devtools/create_project/config.h
devtools/create_project/create_project.cpp
devtools/create_project/create_project.h
devtools/create_project/msbuild.cpp
devtools/create_project/msvc.cpp
devtools/create_project/msvc.h
devtools/create_project/visualstudio.cpp
devtools/create_project/visualstudio.h

One of the biggest challenges of updating the prebuilt MSVC libraries has been the hardcoded libraries in CREATE_PROJECT, as they don't match modern package managers like vcpkg and require manual work. In the process of updating them, I refactored several things:
- MSVC libraries can have different names depending on configuration, so now the `MSVCProvider` has a table of library names for every configuration (Debug/Release/etc) and dependencies. This makes it much easier to maintain, and is similar to the other project providers.
- This removed the need for the BuildSetup `libraries` property, as it was only really used by MSVC. The other providers have their own logic for handling libraries, which makes sense as there is no "global" list of libraries, every platform and tool will have …

CREATE_PROJECT: Update MSVC libraries

---

engines/agi/detection_tables.h
engines/agi/menu.cpp

This PR is based on https://github.com/scummvm/scummvm/pull/2384 (`AGI: Apple2GS: Add 'Speed' menu configuration to other games`), and fixes a small display glitch in Goldrush! - it looked like:

AGI: Apple2GS: Goldrush! - make `Speed` menu in screen

---

engines/groovie/groovie.h
engines/groovie/music.cpp
engines/groovie/music.h
engines/groovie/script.cpp

This PR contains fixes for 3 small MIDI issues in The 7th Guest:
- Music fade-outs would sometimes cause the background music to start playing 
while there would be no music in the original interpreter, and it would not 
always restore volume when playing a new track, causing it to play at volume 0.
- Loading a savegame would start or continue playing background music for a few 
seconds before the music for the loaded room would start playing.
- Checking if the game should start background music would only happen if the 
game was receiving input.

GROOVIE: The 7th Guest MIDI fixes

---

engines/agi/detection_tables.h

Previous commits added an optional Speed menu to few Apple2GS
games. Now adding it to all other games, except:
- manhunter
- agi demo
- winnie the pooh (that seems like a wrong detection entry)
Thanks to @trembyle for testing this PR :-)

AGI: Apple2GS: Add `Speed` menu configuration to other games

---

engines/zvision/scripting/actions.cpp
engines/zvision/scripting/actions.h
engines/zvision/scripting/script_manager.cpp
engines/zvision/scripting/script_manager.h

It was pointed out on the GOG forum that you can't get a perfect score in Zork: Grand Inquisitor. Once case I've found that looks like it should award points, but doesn't, is the Spell Checker (tp4g.scr). It turns out that the script doesn't award the points until after it has changed your location. Example:
```
puzzle:12183 {	# tp4g_gnusto_odibil
criteria {
[17225] = 2	# tp4g_deactivate
[01013] = 4	# person_talking
[12164] = 1	# tp4g_odibil_in_machine
}
results {
action:assign(17225, 0)	# tp4g_deactivate
action:cursor(U)
action:disable_control(12160)	# tp4g_null
action:assign(12183, 0)	# tp4g_gnusto_odibil
action:assign(12159, 0)	# tp4g_machine_full
action:assign(12164, 0)	# tp4g_odibil_in_machine
action:set_partial_screen(124 77 tp4gv011.tga 0 -1)
action:universe_music:19549(0 …
```

ZVISION: Fix ZGI scoring

---

backends/events/symbiansdl/symbiansdl-events.cpp
backends/events/symbiansdl/symbiansdl-events.h
backends/platform/symbian/src/SymbianActions.cpp
backends/platform/symbian/src/SymbianActions.h
backends/platform/symbian/src/SymbianOS.cpp
backends/platform/symbian/src/SymbianOS.h
backends/platform/symbian/src/portdefs.h
engines/dialogs.cpp
engines/dialogs.h
engines/scumm/dialogs.cpp
gui/Actions.cpp
gui/Actions.h
gui/Key.cpp
gui/Key.h
gui/KeysDialog.cpp
gui/KeysDialog.h

The Actions system is only used by the Symbian port, and it’s main purpose is something that can be accomplished in a much simpler way using the keymapper. This PR moves as much code from the actions system as possible behind the GUI_ENABLE_KEYSDIALOG, and adds compiler warnings if the code is used on any new platforms. It should be possible to move the Symbian port over to the keymapper (with some minor limitations) by simply undefining GUI_ENABLE_KEYSDIALOG, but I have no way of testing this.
Requesting a review from @fedor4ever as the most recent Symbian porter.

SYMBIAN: Deprecate the actions system

---

audio/decoders/adpcm.cpp
audio/decoders/adpcm.h
audio/decoders/adpcm_intern.h
video/psx_decoder.cpp
video/psx_decoder.h

This was tested with the demo versions of Broken Sword 1 and 2. The new audio code introduced here could be used to replace the duplicated code in the Blazing Dragons engine, however since I don't have that game, I wasn't able to make the necessary changes.

AUDIO: Separate the XA ADPCM decoder from the PSX video decoder

---

engines/neverhood/detection.cpp
engines/neverhood/gamemodule.cpp
engines/neverhood/modules/module1000.cpp
engines/neverhood/modules/module2300.cpp
engines/neverhood/neverhood.cpp
engines/neverhood/neverhood.h

This adds support for a new demo version of the game.
In addition to the detection entry, it fixes the game logic to allow for fully accessing the demo.

NEVERHOOD: Big demo

---

engines/illusions/illusions.cpp
engines/illusions/illusions.h
engines/illusions/resources/scriptresource.cpp
engines/illusions/resources/scriptresource.h
engines/illusions/resources/talkresource.cpp
engines/illusions/resources/talkresource.h
engines/illusions/threads/talkthread.cpp
engines/illusions/threads/talkthread.h
engines/illusions/threads/talkthread_duckman.cpp
engines/illusions/threads/talkthread_duckman.h

This should fix the issue with wide text processing on big endian systems.
Could someone try this on a big endian system for me to see if I've fixed it.

ILLUSIONS: Fix wide text handling logic for big endian systems. (#11236)

---

backends/module.mk
backends/platform/sdl/sdl.cpp
backends/platform/sdl/sdl.h
backends/presence/discord/discord.cpp
backends/presence/discord/discord.h
configure
devtools/create_project/cmake.cpp
devtools/create_project/create_project.cpp
devtools/create_project/msvc.cpp
devtools/create_project/xcode.cpp
po/POTFILES

Reworked version of @Mataniko 's PR: https://github.com/scummvm/scummvm/pull/1247
This adds support for [Discord rich presence](https://discord.com/developers/docs/rich-presence/how-to), showing the currently running game in a user's status (if they have Game Activity enabled):
Based on the similar taskbar integration. Tested on Windows, should also work on OSX and Linux (welcome testing). You'll need to install [discord-rpc](https://github.com/discord/discord-rpc/releases), it's deprecated but still works (the new Discord SDK isn't GPL-compatible).
The game images have to be provided by us via the [Discord Developer Portal](https://discord.com/developers/applications), instead of provided by the player. I created a ScummVM team with @sev- as admin so he has full control over it.
In my …

BACKENDS: Discord rich presence support

---

backends/platform/sdl/amigaos/amigaos.mk

The created readme.guide file features some in-guide links that point to local files (I.e. AUTHORS), which need to be in the same directory level.
It will otherwise silently fail, when a user clicks on said links.
Due to all documents (except the readme.guide) being installed into the doc/ subdirectory since a few months now, the in-guide links stopped working.
We fix that by restructure the install order to
1) place the .guide creation into the documents loop
2) make sure the /doc subdirectory is available before the guide creation is processed and
3) place the readme.guide into the /doc subdir to secure working in-guide links

AMIGAOS4: Reorder .mk file to fix readme.guide

---

engines/zvision/scripting/actions.cpp

This was the worst glitch I encountered in my playthroughs while debugging scoring in ZGI, so I figured I should at least make an attempt at fixing it before the next release.
When riding with Charon in one direction, the script stops the background sounds. This is done in hp1f.scr:
```
puzzle:08618 {	# hp1f_pay_charon
criteria {
[08616] = 1	# hp1f_charons_hand
[08622] = 0	# hp1f_charon_state
[00009] = 87	# Inventory
[08620] = 1	# hp1f_payed_first_coin
[08419] = 0	# user_is_charon
}
results {
action:inventory(drop 87)
action:assign(08616, 0)	# hp1f_charons_hand
action:assign(08620, 0)	# hp1f_payed_first_coin
action:kill(05182)	# universe_hades_sound_task
action:streamvideo(hp2ea021.avi 0 0 640 344 0 1)
action:assign(19421, 0)	# hp1f_start_bg_music
action:flush_mouse_events(0) …
```

ZVISION: Possible fix for music playing over Charon cutscenes in ZGI

---

common/ustr.cpp
common/ustr.h

Build broke for AmigaOS due to varying types of pointers of the internal string of U32. This attempts to fix that.

COMMON: U32: Fix different types of string pointers for u32

---

engines/cine/gfx.cpp

In French Amiga Future Wars from bug #10643 when walking left from the
scene with the open manhole cover a call to renderOverlay with a
type 0 (color sprite) overlay happens. The source mask for the overlay
is NULL and a memcpy using a NULL pointer as source is initiated.
This results in a memory access violation.
This fixes that memory access violation by simply setting the
destination mask to all zeroes when the source mask is NULL.
Seems to work fine at least in this case.
Fixes bug #10643.

CINE: Fix for bug #10643 to branch-2-2 ("Fix overlay rendering with NULL source mask").

---

engines/wintermute/achievements_tables.h
engines/wintermute/detection_tables.h
engines/wintermute/keymapper_tables.h

All the related games are available on Steam:
* Reversion 2&3 - detection of recent builds
* Shadow on Vatican 1&2 - achievements
* Stroke of Fate 1&2 - detection, keymap
* Way of Love: Sub Zero - detection, keymap

WINTERMUTE: Update detection/keymap/achievements tables

---

audio/softsynth/fluidsynth.cpp

Blazing Dragons provides a custom SoundFont to the FluidSynth driver. Unfortunately, I can't find any sensible way to use that because my global SoundFont setting takes precedence over the in-memory data. Even overriding the MIDI settings for Blazing Dragons and leaving the SoundFont setting blank did not help.
What I've tried to do here is to soften the check so that FluidSynth will prefer in-memory data unless a SoundFont has been explicitly configured for the current game.
Does this seem like a sensible solution? If so, should it also go into the 2.2 branch?

[RFC] Prefer in-memory SoundFont data over global setting in FluidSynth driver

---

common/translation.cpp
common/translation.h
common/ustr.cpp
common/ustr.h
po/be_BY.po
po/ca_ES.po
po/cs_CZ.po
po/el.po
po/es_ES.po
po/fr_FR.po
po/he.po
po/nb_NO.po
po/pt_BR.po
po/pt_PT.po
po/ru_RU.po
po/uk_UA.po

Now that the GUI uses UTF-32, we no longer need to restrict language names to ASCII characters. This means we can use accentuated characters and non-latin alphabets.
This pull request proposes to do that.
Possible issues:
- I pulled the language names from the wikipedia language selection menu. Hopefully this is correct, but it would be good to check.
- I only implemented a basic sorting of `U32String` based on the character values. This is not ideal, so if somebody wants to implement proper unicode string sorting, that would be welcome. But I considered that it was overkill just for a language selection menu. I only considered doing the sorting based on the language code, but this is not ideal either (for example we end up having Suomi between Euskara and Français).

Use native language names

---

engines/cine/texte.cpp

If the error messages can not be found (They are in the file
ERRMESS.DAT in Operation Stealth) then use the default values.
There are now the following default error messages included in ScummVM
for Operation Stealth:
- American English (Protagonist is James Bond)
- British English (Protagonist is John Glames)
- French
- German
For the Italian and Spanish releases of Operation Stealth the error
messages from Future Wars are used as fallback. This is incorrect
but better than nothing.
This makes the error message handling more lenient than before so that
not having an ERRMESS.DAT does not block the starting of the game
anymore.
Fixes bug #11649.

CINE: OS: Fallback to default error messages

---

engines/cine/cine.cpp
engines/cine/script_fw.cpp
engines/cine/sound.cpp
engines/cine/various.cpp
engines/cine/various.h

In Operation Stealth DOS and Atari ST versions, but not Amiga or
demo versions, sound effects are loaded in AUTO00.PRC using a
combination of o2_loadAbs and o2_playSample(1, ...) before
o1_freePartRange(0, 200). This is a better heuristic for ending the
script at the correct position than checking whether global variable
255 is compared to 0. In the original game AUTO00.PRC was run when
starting or restarting the game and one could not load a savegame
before passing the copy protection. Thus, we try to emulate that
behaviour by running at least part of AUTO00.PRC before loading a
savegame.

CINE: OS: Fix MT-32/AdLib SFX & loading savegames

---

audio/mods/paula.cpp
audio/mods/paula.h
audio/mods/soundfx.cpp
audio/mods/soundfx.h
engines/cine/anim.cpp
engines/cine/sound.cpp

Hi!
Here are fixes for Amiga music and sample playing in Operation Stealth.
This also slightly touches some common audio source code (See commits
0a4ebbf and 1f28961) but they were done in order to fix playing music
correctly in Amiga versions of Operation Stealth.
Please could you also cherry-pick these to the branch-2-2 branch?
Thank you!
Kari Salminen

CINE: OS: Fix Amiga music and sample playing.

---

audio/mods/soundfx.cpp
audio/mods/soundfx.h
engines/cine/anim.cpp
engines/cine/main_loop.cpp
engines/cine/saveload.cpp
engines/cine/script_fw.cpp
engines/cine/sound.cpp
engines/cine/various.cpp

Hi!
Here are some fixes to the Cine-engine. I think they should be
quite safe to put into the 2.2.0 release branch too (I used
them on the branch-2-2 while testing locally. I played through
Italian Amiga version of Future Wars while working on them).
Kari Salminen

CINE: 9 fixes to music, UI, savegame etc

---

engines/glk/detection.cpp
engines/ultima/detection.cpp
engines/ultima/detection_tables.h
engines/ultima/shared/early/ultima_early.cpp
engines/ultima/shared/engine/resources.cpp

This is necessary on RISC OS to avoid linker errors due to the size of the executable.

GLK/ULTIMA: Disable unstable subengines by default

---

engines/testbed/module.mk
engines/testbed/networking.cpp
engines/testbed/networking.h
engines/testbed/testbed.cpp

There seems to be a need for a test suite for non webserver related networking functionality.
To start off it checks if the `OSystem::isConnectionLimited` member function works.

TESTBED: Test networking

---

base/plugins.cpp

Currently, the plugin architecture searches for plugins in ScummVM's
base directory and in the plugins directory itself.
However, for Win32, we need to bundle several DLL files in order to
make ScummVM run at all. Currently, this leads to several warning
messages since ScummVM tries to load those DLLs as plugins.
This patch excludes the ScummVM base directory when running on Win32 and
only accepts plugins from the plugins directory.

BASE: WIN32: Exclude scummvm's base directory from plugin path

---

backends/graphics/graphics.h
backends/graphics/null/null-graphics.h
backends/graphics/windowed.h
backends/modular-backend.cpp
backends/modular-backend.h
backends/platform/3ds/osystem.h
backends/platform/dc/dc.h
backends/platform/ds/arm9/source/osystem_ds.cpp
backends/platform/ds/arm9/source/osystem_ds.h
backends/platform/ios7/ios7_osys_main.h
backends/platform/iphone/osys_main.h
backends/platform/n64/osys_n64.h
backends/platform/psp/osys_psp.cpp
backends/platform/psp/osys_psp.h
backends/platform/wii/osystem.h
common/system.h

Only the SDL and OpenGL graphics managers have been tested so far.

BACKENDS: Add a function to return if the overlay is visible

---

backends/keymapper/virtual-mouse.cpp

Without this PR, the virtual mouse, controlled via game controller analog stick, is stuck in a 320x200 top left rectangle when VKBD is displayed with graphics mode 2x in low res games like Dreamweb in-game. Note gfx mode 2x or higher has long been the default on almost all platforms that have at least 640x400 capability.
This bug is a consequence of g_gui.isActive() returning false when vkbd is being displayed (why is this?!?!). Due to this, the game resolution is used erroneously instead of the overlay resolution for clipping the virtual mouse.
This should be included for 2.2.0 Switch and Vita releases, otherwise VKBD is unusable in 320x200 games in docked Switch modes and VitaTV modes due to not being able to move the mouse pointer over the whole keyboard.

(Do not merge yet) KEYMAPPER: Fix virtual mouse bound in small rectangle in VKBD

---

graphics/conversion.cpp
graphics/conversion.h
gui/ThemeEngine.cpp
gui/ThemeEngine.h

From what I understand, all backends with 16-bit colour support should support RGB cursors using the same format as the overlay, meaning that custom cursors in the GUI can be used directly on those platforms without converting them to CLUT8 first. The old code path has been kept for the DS and N64 backends.

GUI: Use RGB cursors on supported platforms

---

engines/wintermute/detection_tables.h

In this release, 2 different languages were provided (EN and RU)
All other match Nov 2019 release

WINTERMUTE: Added Reversion : The Metting (Steam, Windows, March 2020)

---

common/platform.cpp
common/platform.h

This PR adds the Sega Mega Drive/Genesis as a platform.
I'm working on support for Scooby Doo Mystery on the Genesis.

COMMON: Add Sega Megadrive/Genesis platform

---

configure
devtools/create_project/create_project.cpp
dists/scummvm.rc

Currently, the Win32 builds (and possibly other ports as well) bundle all resources (engine-data, fonts, wwwroot...) straight into the main executable. This might have been a good idea back in the days, but now that we easily exceed 20MB for single resource files, this could be pretty limiting in the future.
This patch adds an option to the configure script to create a "slim" build by excluding the resources from being built into the executable. This is currently only used for the Win32 build via scummvm.rc, but it might be helpful for other builds as well.
By default, the resources are built in, so devs have everything in one executable, while the release builds for the end users could be created as what I call slim builds.

BUILD: Add option not to bundle all resources in the executable

---

audio/mixer_intern.h

Digital iMuse in Grim engine (GrimE) require more channels in audio mixer available.

AUDIO: Increase number of audio mixer channels to 32

---

common/platform.cpp
common/platform.h

There are PS2 and XBOX game versions of Myst III: Exile.
Change add them to platform definitions which are used by code game detection in Myst engine.

COMMON: Added PS2 and XBOX platform definitions.

---

graphics/fonts/ttf.cpp
graphics/fonts/ttf.h

The change introduce support for stem darkening in TTF.
It's used in The Longest Journey game engine.

GRAPHICS: Added support for stem darkening in TTF

---

video/bink_decoder.cpp
video/bink_decoder.h
video/smk_decoder.cpp
video/smk_decoder.h

Added public method, getter for SMK and BINK video frame rate.
It's used for override frame rate by video player in The Longest Journey engine.

VIDEO: Added getter for getFrameRate() for BINK and SMK video streams.

---

video/bink_decoder.cpp
video/bink_decoder.h

This change introduce support for seeking BINK streams.
It's used by Grim engine for "Escape from Monkey Island".
Video player needs support for looping and restore movie state from save game.

VIDEO: Added support for seeking BINK streams

---

graphics/yuv_to_rgb.cpp
graphics/yuv_to_rgb.h
video/bink_decoder.cpp

This adds support for BINK videos with alpha component used in Myst3 engine.
It's also integrate support alpha channel in yuv to rgb conversion code.

VIDEO: Added support for alpha component support for BINK videos

---

video/mpegps_decoder.cpp
video/mpegps_decoder.h

This change introduce support PS2 audio codec in MPEG stream.
It's used by Grim engine for "Escape from Monkey Island" in video player.

VIDEO: Added support for PS2 audio codec in MPEG stream

---

engines/composer/composer.cpp

Fix regression in macintosh version of "Gregory and the Hot Air Balloon" and "Darby the Dragon" caused by commit #1948

COMPOSER: fix regression macintosh darby & gregory

---

backends/graphics/sdl/sdl-graphics.cpp

When using SDL1, mouse events can range from 0 to `_windowWidth` instead of 0 to `_windowWidth` - 1. This causes mouse input to stop working in full screen on RISC OS when moving the mouse to the lower edge of the screen, as well as causing the mouse to warp back to the centre of the screen when doing so on Windows.

SDL: Clip the coordinates sent by mouse events

---

gui/options.cpp
po/hi.po

- ~Remove redundant constructor/function since shifted to C++11 from the U32 code~
- Hindi language proper name
- improper GUI fixed when changing to Hebrew in the classic theme. (see pictures below.)
**Before**
**After**

GUI: Small Improvements

---

common/array.h
common/initializer_list.h
configure
devtools/create_project/create_project.cpp
engines/petka/configure.engine
test/common/array.h

What I am proposing in with this pull request is to:
- Allow any engine to use c++11
- Allow any backend to use c++11
- Restrict c++11 in common code to features that can be disabled
The idea is that I would like to avoid breaking compilation for ports that do not yet support c++11, while allowing more c++11 use in the project.
The way I went about this is:
1. Add a cxx11 feature that can be used as a dependency by engines that use c++11. This will automatically disable those engines when c++11 is not enabled. This is added for the petka engine, and should fix the compilation on buildbot for the canoo, dingux, gp2xwiz, openpandora, and osx_intel builders.
2. Add a USE_CXX11 define when C++11 is enabled. This can be used in common code to add code such as constructors with the move …

Partial c++11 support

---

devtools/create_project/xcode.cpp

Added MacPorts paths to Xcode project.
Current paths only support /usr/local.

CREATE_PROJECT: Added MacPorts paths to Xcode

---

video/flic_decoder.cpp

This pull request adds support for BLACK chunk in FLIC decoder.
[> All pixels in the frame have colour 0. This chunk has no data following the chunk header.](https://www.compuphase.com/flic.htm#BLACK)
Red comrades flics use this chunk.

VIDEO: add support for BLACK chunk in FLIC decoder

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp

SDL 2.0.10 and above favors Metal over OpenGL rendering on macOS, but
this currently causes blurriness issues on Retina displays.
Going back to OpenGL rendering works around this bug for now.
Users can override this with the SDL_RENDER_DRIVER environment variable.
c59bf95ba85b25b1 and 70f79d3df8b4a9d4 are still a requirement to
work around this bug, too.
Bug #11430.
(This should probably backported to any 2.2.1 release)

SDL: Prefer OpenGL over Metal rendering on macOS

---

common/achievements.h
common/algorithm.h
common/archive.h
common/array.h
common/bitstream.h

Add and improve doxygen blocks in the header file.
Just opening a PR with a single file to get some feedback from you if this is the way to proceed.
Output is available on https://b-gent.github.io/PR2467/index.html
@sev- @Mataniko

[DNM] DOXYGEN: updates in header files 1

---

common/bufferedstream.h
common/callback.h
common/config-manager.h
common/coroutines.h
common/cosinetables.h
common/dcl.h
common/dct.h
common/debug-channels.h
common/debug.h

Edited files in the common folder:
- bufferedstream.h
- callback.h
- config-manager.h
- coroutines.h
- cosinetables.h
- dcl.h
- debug.h
- debug-channels.h
Output is available on https://b-gent.github.io/PR2488/group__common__buffstream.html

[DNM] DOXYGEN: doxygen changes in header files 2

---

engines/petka/objects/heroes.cpp
engines/petka/objects/heroes.h
engines/petka/objects/object.cpp
engines/petka/petka.cpp
engines/petka/sound.cpp

I checked engine in valgrind and have fixed some memory leaks

PETKA: Fix memory leaks

---

common/array.h

Comment speaks about double-linked list but we actually have an array

common/array: Fix comment

---

backends/platform/maemo/maemo.cpp
backends/platform/sdl/macosx/macosx.cpp
backends/platform/sdl/win32/win32.cpp
backends/platform/symbian/src/SymbianOS.cpp

This is needed with SDL1 so that `SDL_GetVideoInfo` works properly.

SDL: Ensure that SDL is initialized before creating the window object

---

Makefile.common
ports.mk

Since the commit "CONFIGURE: Do not enable opengl_shaders feature flag for gles2. " (b3ffd89c6824b82b958784305017d5c9e4f207d9), the shaders are no more installed for opengles2 systems.
But they need them as they are used in the code.
I don't know if my way to test "USE_OPENGL_SHADERS or USE_GLES2" in Makefile is the standard of ScummVM but it works.
I'm open to any suggestions ...

CONFIGURE: Also install shaders if gles2 enabled

---

gui/editgamedialog.cpp
gui/options.cpp

The new graphics settings (I assume they were added in the ResidualVM merge) are always active in "edit game", even if we're not overriding the global settings. This attempts to fix that.
I'm not sure if I got it all right, and the "V-Sync" checkbox is a bit unusual in that this setting is true by default. But it's a start.

GUI: Update "edit game" for new graphics options (please test before merge!)

---

backends/graphics/sdl/sdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.h
backends/graphics3d/sdl/sdl-graphics3d.cpp
backends/platform/sdl/sdl-window.cpp
backends/platform/sdl/sdl-window.h
engines/grim/gfx_tinygl.cpp
engines/grim/grim.cpp
engines/icb/surface_manager.cpp
engines/myst3/gfx.cpp
engines/myst3/gfx_tinygl.cpp

This is a continuation of residualvm/residualvm#1712. Compared to that PR, this PR now adapts the Myst3 and ICB engines as well.

ENGINES: Use ScummVM's 2D API for blitting the TinyGL framebuffer

---

backends/base-backend.cpp
backends/base-backend.h
backends/graphics/graphics.h
backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
backends/graphics3d/openglsdl/openglsdl-graphics3d.h
backends/graphics3d/surfacesdl/surfacesdl-graphics3d.cpp
backends/graphics3d/surfacesdl/surfacesdl-graphics3d.h
backends/modular-backend.cpp
backends/modular-backend.h
backends/platform/android3d/graphics.cpp
backends/platform/android3d/graphics.h
common/system.h

The getScreenPixelBuffer() system call is no longer needed.

BACKENDS: Drop getScreenPixelBuffer() as no longer needed.

---

engines/engine.cpp
engines/grim/gfx_base.h
engines/grim/gfx_opengl.cpp
engines/grim/gfx_opengl.h
engines/grim/gfx_opengl_shaders.cpp
engines/grim/gfx_opengl_shaders.h
engines/grim/gfx_tinygl.cpp
engines/grim/gfx_tinygl.h
engines/grim/grim.cpp
engines/grim/grim.h
engines/grim/grim_controls.cpp
engines/myst3/gfx.cpp
engines/myst3/gfx.h
engines/myst3/myst3.cpp
engines/stark/gfx/driver.cpp
engines/stark/gfx/driver.h
engines/stark/stark.cpp
engines/util.h
engines/wintermute/base/base_game.cpp
engines/wintermute/wintermute.cpp

This is already handled by the SDL backend.

ENGINES: Remove code for toggling fullscreen mode

---

backends/graphics/downscalesdl/downscalesdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.cpp
backends/graphics3d/sdl/sdl-graphics3d.cpp
backends/platform/sdl/sdl-window.cpp
backends/platform/sdl/sdl-window.h

Following on from PR #2517, this PR fixes the issues with SDL1 relating to the fact that grabbing and locking the mouse are both done using `SDL_WM_GrabInput`.

SDL: Refactor grabbing and locking the mouse

---

engines/icb/debug_pc.cpp
engines/icb/detection.cpp
engines/icb/main_menu_pc.cpp

As far as I'm aware, there are two different demo versions of In Cold Blood - the one from [here](https://www.scummvm.org/frs/demos/icb/icb-eng-demo.zip), as well as a second one that appears to be larger and mentions Dreamcatcher in the opening title scroll instead of Ubi Soft Entertainment. I'm fairly sure it's the one from [here](https://web.archive.org/web/20020206060605/http://dreamcatchergames.com:80/games/downloads.html), but the Wayback Machine doesn't have it and I couldn't find it anywhere else. If necessary, I can share the copy of the demo I have locally.
This PR also contains a couple of commits that are necessary to get the game to start.

ICB: Add detection entries for the demo versions

---

base/version.cpp
configure
devtools/create_project/create_project.cpp
engines/grim/configure.engine
engines/icb/configure.engine
engines/myst3/configure.engine
graphics/module.mk
graphics/renderer.cpp

Enabling TinyGL increases the size of the main executable considerably, which causes problems for the DS port.

CONFIGURE: Allow building with TinyGL disabled

---

engines/wintermute/detection_tables.h

Detection entry for the full version of the Wintermute game Sunrise in german.

WINTERMUTE: Add detection entry for german Sunrise version

---

common/config-manager.h
common/hashmap.h

Makes for simpler/more efficient code when keys are optional.
Saves having to check for the key existing and then fetching the element at that key, which is two searches in the hashmap and two function calls in the code using the map.

COMMON: Try get functionality for HashMap and ConfMan

---

engines/grim/grim.cpp

Joystick buttons are not working in EMI for actions:
It seems that key mapping doesn't map joystick buttons to correct key events.
According to manual: https://mocagh.org/lucasfilm/mi4-manual.pdf
- Examine/Look is E or L
- Use/Talk is U
- Pick up/Put in inventory is P or + (keypad)
- Inventory is I or Insert
With these modifications, the joystick buttons are now working.
Tested on x64 (Ubuntu) and Raspberry 2 and 3 with the French Windows and PS2 versions of the game.

GRIM: Fix mapping of joystick action buttons in EMI

---

common/str.cpp
common/str.h

This is the same as String::asUint64 but supports 0x and 0 prefixes

COMMON: Add String::asUint64Ext

---

engines/wintermute/base/gfx/base_renderer3d.h
engines/wintermute/base/gfx/opengl/base_render_opengl3d.cpp
engines/wintermute/base/gfx/opengl/base_render_opengl3d.h
engines/wintermute/base/gfx/opengl/base_render_opengl3d_shader.cpp
engines/wintermute/base/gfx/opengl/base_render_opengl3d_shader.h
engines/wintermute/base/gfx/opengl/base_surface_opengl3d.cpp
engines/wintermute/base/gfx/opengl/base_surface_opengl3d.h
engines/wintermute/base/gfx/opengl/shadow_volume_opengl_shader.cpp

This should remove all non-conforming OpenGL calls from the shader renderer.

WINTERMUTE: Opengl es 2 conformance

---

backends/vkeybd/virtual-keyboard-gui.cpp

This commit fixes a problem which avoids to display the virtual keyboard on OpenGL/OpenGLES systems, encountered on x64 and Raspberry models.
Indeed, the surface containing the image of the virtual keyboard is loaded at startup.
And later, the `OSystem_SDL::setGraphicsMode` switches to a new graphical manager `OpenGLSdlGraphics3dManager`.
But, in that case, the virtual keyboard has been loaded in 2 bytes-per-pixel format (for initial graphical manager) and overlay is 4bpp (for `OpenGLSdlGraphics3dManager`).
And due to these lines of `blit` method in `virtual-keyboard-gui.cpp`, the keyboard is not displayed:
```
if (surf_dst->format.bytesPerPixel != surf_src->format.bytesPerPixel)
return;
```
The proper way to solve the problem is perhaps to reload the virtual keyboard surface after the …

GUI: Fix display of virtual keyboard for OpenGL/OpenGLES

---

devtools/create_project/cmake.cpp

This is useful for e.g. clangd or other clang based tools like the analyser.
https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html
I'm using the generated `compile_commands.json` with clangd and vscode (the file must be located in the project root to be found automatically by clangd)
Install the clangd plugin for vscode, execute `cmake`, copy the `your_build_dir/compile_commands.json` to `scummvmcheckout/compile_commands.json` and execute `Restart clangd` in vscode.
```bash
cd devtools/create_project/cmake
cmake .
cmake --build .
cd ../../..
./devtools/create_project/cmake/create_project . --cmake
mkdir build
cd build
cmake ..
cd ..
ln -sf build/compile_commands.json compile_commands.json
```
Now install clangd and open the project. It might be problematic if you …

CREATE_PROJECT: export compile_commands.json via cmake

---

.clang-tidy

This adds a basic clang-tidy configuration that is e.g. picked by by the clang-analyser or clangd for IDE integration.

ALL: add .clang-tidy

---

engines/twine/detection.cpp
engines/twine/twine.cpp

This adds detection for the UK release of Little Big Adventure. This is what my CD looks like:
https://www.mobygames.com/game/dos/relentless-twinsens-adventure/cover-art/gameCoverId,198155/
And this is what the box looks like:
https://www.mobygames.com/game/dos/relentless-twinsens-adventure/cover-art/gameCoverId,198153/
It may be misleading to call it an "UK release", because the "vox" directory (which I added to the search manager, even though I'm not sure if it's used) contains files prefixed "en_", "de_" and "fr_". But the CD says "Made in the U.K.", and the manual - which I **clearly** need to read, because right now I'm just hitting buttons blindly - is in English, so... But feel free to edit the description in any way.
The "fla" directory is probably animated cutscenes, or something …

TWINE: Add detection for UK version of Little Big Adventure

---

engines/stark/visual/actor.cpp

Fixes https://bugs.scummvm.org/ticket/11872
Alternatively, we can fix material name during initialization.

STARK: Workaround to support Emma's lipsync

---

engines/stark/services/staticprovider.h
engines/stark/ui/cursor.cpp
engines/stark/ui/cursor.h
engines/stark/ui/world/actionmenu.cpp
engines/stark/ui/world/actionmenu.h
engines/stark/ui/world/gamewindow.cpp
engines/stark/ui/world/inventorywindow.cpp

* Play sound when hovering over action menu items. Fixes https://bugs.scummvm.org/ticket/11875
* Play sound when hovering useable items. Fixes https://bugs.scummvm.org/ticket/11874
* Rename `_fading` cursor property to `_itemActive` to reflect that this property now controls more than just fading.

STARK: Play sound when hovering active cursor

---

backends/vkeybd/virtual-keyboard.cpp
backends/vkeybd/virtual-keyboard.h

When starting a game from the command line (without using the menu) and opening the virtual keyboard, the keymap `kKeymapTypeGui` is not defined and it is not possible to click on virtual keyboard with a joystick/controller.
So, this patch initializes the `kKeymapTypeGui` keymap if it was not already done before (using the standard GuiManager mapping).
Perhaps, there are other solutions to solve this issue: For instance, make `GuiManager::initKeymap()` public and directly call it.
I'm open to any suggestion.

GUI: Fix keymap of virtual keyboard if no GUI opened before

---

engines/sci/graphics/controls16.cpp

When using original save/load screens, the games list wasn't properly
aligned, if contained Hebrew text. Fixed by calling the BiDi algorithm
in `drawListControl`.

SCI: Add RTL support in GfxControls16::drawListControl

---

engines/scumm/he/sound_he.cpp
engines/scumm/he/sound_he.h

This change allows the user to replace the in-game music
with high-quality audio files.
When the game loads a sound ID it will check if the file
`music{SOUND_ID}.wav` exists. If it does the engine will
use this file instead of the original one. If it doesn't the
original sound is used.
Here is an example of the directory structure for
Putt-Putt Saves the Zoo and high-quality soundtrack.
```
puttzoo
|-- PUTTZOO.HE0
|-- PUTTZOO.HE1
|-- PUTTZOO.HE2
|-- PUTTZOO.HE3
|-- PUTTZOO.HE4
|-- PUTTZOO.HE4
|-- music8007.wav
|-- music8008.wav
|-- music8027.wav
|-- music8028.wav
|-- music8029.wav
|-- music8030.wav
|-- music8031.wav
|-- music8032.wav
|-- music8033.wav
|-- music8034.wav
|-- music8035.wav
|-- music8036.wav
|-- music8038.wav
|-- music8052.wav
|-- music8053.wav
|-- music8054.wav
|-- …
```

SCUMM: Add music override for HE games

---

engines/sci/engine/file.cpp
engines/sci/engine/kfile.cpp

Make sure that Hebrew save games are using UTF8 (otherwise, when saving
in Hebrew it works well from original Sierra save/restore dialogs, but
when loading from ScummVM's dialog, it looks garbled)

SCI: Hebrew - fix save games encoding

---

engines/wintermute/base/gfx/opengl/shaders/wme_modelx.vertex

GLSL version 1.10 does not allow implicit conversions between data types.

WINTERMUTE: Fix implicit conversion in shader

---

common/memstream.h

A seekable read and writeable memory stream that operates on an already existing memory buffer
I need this for TwinE - the others are copying the memory - this one operates on the given memory buffer. If it's not worth it to add to `Common` it will just live in `TwinE` namespace.
Opinions?

COMMON: added MemorySeekableReadWriteStream

---

engines/mohawk/livingbooks.cpp

The german and french version of "Just Grandma and Me" (Mohawk engine) have the special characters "ç" and "ö" in their config files. This causes ScummVM to crash when trying to start the game in german or french. Allowing non english chars in config files for Living Books games fixes this issue.

MOHAWK: Fix game "Just Grandma and Me" german and french version crash

---

configure
ports.mk

This PR contains several little fixes to the Makefile based build system which are needed for my iPhone toolchain.
- defines are updated to match what's done in create_project for Xcode in ios7 platform
- When configure script don't find SDL but SDL_Net (when it is patched to not depend on SDL), don't try to link with SDL.
- Link against Security framework when linking with curl statically, in the case curl uses DarwinSSL.
These changes shouldn't affect existing buildbot toolchain except maybe the first one.

IPHONE: Fix building with recent cross-compiled SDK

---

common/ustr.cpp
common/ustr.h
engines/ultima/ultima8/graphics/fonts/tt_font.cpp
engines/wintermute/base/font/base_font_truetype.cpp
engines/wintermute/base/scriptables/script_ext_string.cpp
graphics/macgui/macmenu.cpp
graphics/macgui/mactext.cpp
graphics/macgui/mactextwindow.cpp

It's safer than direct array manipulation. Replace current uses
of subsetting with substr.

COMMON: introduce substr for U32String

---

devtools/create_project/codeblocks.cpp
devtools/create_project/create_project.cpp
devtools/create_project/create_project.h
devtools/create_project/msbuild.cpp
devtools/create_project/msvc.cpp
devtools/create_project/visualstudio.cpp

Keeps the main project clean and is a prerequisite for building detection as a plugin.

CREATE_PROJECT: Put detection in a separate project

---

engines/wintermute/ad/ad_actor_3dx.cpp
engines/wintermute/base/gfx/opengl/base_render_opengl3d_shader.cpp
engines/wintermute/base/gfx/opengl/base_render_opengl3d_shader.h
engines/wintermute/base/gfx/opengl/meshx_opengl.cpp
engines/wintermute/base/gfx/opengl/meshx_opengl.h
engines/wintermute/base/gfx/opengl/meshx_opengl_shader.cpp
engines/wintermute/base/gfx/opengl/meshx_opengl_shader.h
engines/wintermute/base/gfx/opengl/shaders/wme_flat_shadow_mask.fragment
engines/wintermute/base/gfx/opengl/shaders/wme_flat_shadow_mask.vertex
engines/wintermute/base/gfx/opengl/shaders/wme_flat_shadow_modelx.fragment
engines/wintermute/base/gfx/opengl/shaders/wme_flat_shadow_modelx.vertex
engines/wintermute/base/gfx/x/frame_node.cpp
engines/wintermute/base/gfx/x/frame_node.h
engines/wintermute/base/gfx/x/meshx.h
engines/wintermute/base/gfx/x/modelx.cpp
engines/wintermute/base/gfx/x/modelx.h

Adds support for flat shadows (so called in the WME source code).
These shadows work by first rendering the model which is supposed to cast a shadow into a texture and then project this texture onto a flat plane via projected texture coordinates.

WINTERMUTE: Flat shadows

---

common/translation.cpp
common/translation.h
gui/ThemeEngine.cpp

U32String can contain characters from all languages, without relation
to the GUI's language. Therefore, we need to always call it.
Use case:
In Hebrew SQ3, when using the game's original save/restore dialogs, it's
possible to give save games Hebrew names.
What happens when we then use ScummVM's load dialog?
- If ScummVM's GUI language is Hebrew, it's calling BiDi algo, and
the text direction is OK.
- However, if ScummVM's GUI language is English, before this commit it
didn't call the BiDi algo, and the text was reversed.

I18N: Always call BiDi algorithm for U32String

---

engines/grim/textsplit.cpp

A previous fix in ResidualVM changed 2 calls to free() into delete
operators because scumm_strdup() was using the new operator.
Later scumm_strdup() switched to malloc() to be aligned with strdup()
function. So move back to free().

GRIM: Fix alloc-dealloc mismatch in grim engine

---

engines/wintermute/base/gfx/opengl/base_render_opengl3d.cpp
engines/wintermute/base/gfx/opengl/meshx_opengl.cpp
engines/wintermute/base/gfx/opengl/shadow_volume_opengl.cpp

The ShaderSurfaceRenderer sets a VBO once without resetting it. This has lead to graphical bugs in the past with the fixed-function renderer (which does not use VBOs), so the current VBO has been reset in several places in the code. Now it is only reset once during renderer initialization, which should suffice.

WINTERMUTE: Reset VBO once during init in fixed-function renderer

---

engines/kyra/script/script.cpp
engines/kyra/script/script.h

KYRA: Fix crash in Siberian Goblin translation of HoF

---

engines/scumm/charset.cpp
engines/scumm/string.cpp

SCUMM: Add support for basic Korean fan translation
This PR is part of scummvm-kor merge project.
It makes minimal changes enabling Korean fan translation for SCUMM games.
Most of the foundation is already laid, so just removing restriction is enough for basic functions.
However, many games require some more changes to actually "work", so those will come as separate PR.
Tested with:
- Loom (DOS/CD/Korean patched)
- Monkey Island 2 (DOS/Korean patched)
- Monkey Island 2 (FMT/Japanese)
- DOTT (DOS/CD/Korean patched)

SCUMM: Add support for basic Korean fan translation

---

engines/scumm/charset.cpp
engines/scumm/charset.h
engines/scumm/scumm.cpp
engines/scumm/scumm.h
engines/scumm/string.cpp

This PR is part of scummvm-kor merge project.
It adds the ability to load and use multiple external Korean fonts to match the original look.
On a separate note, I intend to refactor CJK text rendering to use Graphics::Font*.
Tested with:
- Loom (DOS/CD/Korean patched)
- Monkey Island 2 (DOS/Korean patched)
- Indy 4 (DOS/CD/Korean patched)
- DOTT (DOS/CD/Korean patched)

SCUMM: Multi-font for Korean fan translated games

---

engines/scumm/charset.cpp
engines/scumm/charset.h
engines/scumm/string.cpp

This PR is part of scummvm-kor merge project.
This patch introduces alternative line-break style (similar to CSS word-break: break-all), and moves the hanging punctuation mark to the next line for cleaner text display.
This is used in Monkey2 (in the Phatt Island Library.)

SCUMM: Hacks for alternative line-break

---

common/base-str.cpp

Remove a useless creation of a BaseString object with a C string in
comparison operators of this class, because there is a function equals()
that accepts a C string in parameter. So this was not necessary but
moreover the created BaseString object was never freed.

COMMON: Use appropriate equals() in BaseString

---

backends/platform/sdl/switch/switch.cpp
backends/platform/sdl/switch/switch.h

This commit adds language detection on Switch

SWITCH: Implement OSystem_Switch::getSystemLanguage()

---

.gitignore
devtools/create_project/cmake.cpp
devtools/create_project/cmake.h
devtools/create_project/create_project.cpp
devtools/create_project/create_project.h

With these patches I'm now able to configure, compile and link with cmake
* Support for pkg-config was added
* Shortened the CMakeLists.txt by more than 4000 lines
* Added macro for feature detection
* Configure stage is reporting missing libs as error now (they were reported as compile errors during the build before)
* Link the scummvm-detection lib (this was missing before)
* Added missing defines like `DETECTION_STATIC` and `USE_SDL2`
* Added the generated `CMakeLists.txt` to `.gitignore`

CREATE_PROJECT: fixed cmake generator

---

graphics/opengl/shader.cpp

On Raspberry PI, an error in OpenGLES shaders is not reported during the compilation step but during the link step.
See https://www.raspberrypi.org/forums/viewtopic.php?t=26205 for more information (last post).
This commit simply adds reporting of errors which occurred during the link step.

GRAPHICS: Fix no shader error on Raspberry PI

---

backends/module.mk
backends/platform/ios7/ios7_osys_main.cpp
backends/platform/ios7/ios7_osys_main.h
backends/platform/iphone/osys_main.cpp
backends/platform/iphone/osys_main.h
configure

This has not been tested, but it should help to reduce code duplication and make future refactoring simpler.

 IPHONE/IOS7: Make use of ModularMutexBackend

---

devtools/create_project/create_project.cpp
devtools/create_project/create_project.h
devtools/create_project/msbuild.cpp
devtools/create_project/visualstudio.cpp

There is no need to show an unusable console window, so only show that if the text console is enabled.

CREATE-PROJECT: Set MSVC subsystem

---

Makefile.common

Delete detection.dwo files on make clean (Issue #11922)

BUILD: Remove detection.dwo files on clean

---

engines/scumm/imuse_digi/dimuse.cpp
engines/scumm/imuse_digi/dimuse.h
engines/scumm/imuse_digi/dimuse_music.cpp
engines/scumm/imuse_digi/dimuse_script.cpp
engines/scumm/imuse_digi/dimuse_track.cpp

`SCUMM: COMI: Fix iMUSE Digital #4635/#10473 bugs`
This commit fixes the early stopping of ArriveBarber sequence, during the first arrival in Barbery Coast.
If this particular cutscene is skipped while this sequence is playing (e.g.: via ESCAPE key), the sequence is faded out
and the main Barbery Coast theme is played, as per correct behavior.
That's also the only COMI sequence using a transitionType with value 4, so the fix should not be able to break anything else, and in fact I haven't been able to break anything during my test run.
`SCUMM: COMI: Fix #4391 iMUSE Digital fades`
This commit implements fade-ins during song transitions (e.g. statePreVooOut --> statePreVooIn --> statePreVooLady) and also between regions of the same song (e.g. any JUMP instruction used for looping songs). …

SCUMM: COMI: Fix #4635/#10473 and #4391 (iMUSE Digital)

---

backends/graphics/graphics.h
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h
backends/modular-backend.cpp
backends/modular-backend.h
backends/platform/android3d/graphics.cpp
backends/platform/android3d/graphics.h
common/system.h

This function used to be called from the Engine class, but was not longer used since commit 432fd52. The single remaining use was an internal use in the SurfaceSdlGraphicsManager, and I kept the behaviour there while removing the function.

COMMON: Remove resetGraphicsScale from OSystem

---

engines/scumm/detection_internal.h
engines/scumm/resource.cpp
engines/scumm/scumm.cpp
engines/scumm/scumm.h
engines/scumm/string.cpp

This adds support for language bundle to the SCUMM v1~v7 games.
It enables fan translation without the need for patching game resource.
While it's kind of similar to the DIG/COMI language bundle, the file format and the logic is different.
Tested with:
- Maniac Mansion (V1 DOS)
- Indy 3, 4 (Steam)
- Loom (EGA)
- Day of the Tentacle (CD)
- Sam & Max (CD)
- Full Throttle

SCUMM: Implement language bundle for Korean fan translation

---

engines/scumm/imuse_digi/dimuse.h
engines/scumm/imuse_digi/dimuse_music.cpp
engines/scumm/imuse_digi/dimuse_script.cpp
engines/scumm/imuse_digi/dimuse_tables.cpp
engines/scumm/imuse_digi/dimuse_tables.h

These modifications make so that COMI Demo music is handled mostly in the same way as it'shandled in the full game.
As a bonus, iMUSE transition crossfades between tracks automatically work!

SCUMM: COMI (Demo): properly handle demo music and transitions

---

engines/startrek/detection.cpp

This adds some detection entries to the Star Trek engine, though I'm not sure whether or not they should be labelled floppy versions or not.
- English Star Trek: 25th Anniversary included on Interplay's 10 Year Anniversary: Classic Collection.
- English Star Trek: Judgment Rites included on The White Label - Doubles
- French Star Trek: Judgment Rites included on The White Label - Doubles
So are they floppy versions? Well, none of them have speech at least.
The White Label CD contains three versions of Judgment Rites: English, German (already detected by ScummVM, albeit as a CD version) and French. Each folder takes up about 44 MB on the CD, for a total of about 133 MB. (The 25th Anniversary CD also has English, German and French versions, but they are all detected by ScummVM. I think the …

STARTREK: Additional detection entries

---

gui/saveload-dialog.cpp

Currently, deleting a save game resets the scroll position, scrolling the list to the very top. This isn't noticeable if there's not many saves, but once there's a lot it's a pain to delete save 72, get kicked back to the beginning, and then try to find where you were again. This happens to me frequently. It doesn't look like the current behavior is intentional and I think it's reasonable to expect the list to be stable when deleting.

GUI: Retain scroll position when deleting a save

---

backends/platform/android/android.cpp
backends/platform/android/android.h
backends/platform/android/jni-android.cpp
backends/platform/android/jni-android.h
backends/platform/android3d/android.cpp
backends/platform/android3d/android.h
backends/platform/dc/dc.h
backends/platform/dc/dcmain.cpp
backends/platform/dc/vmsave.cpp
backends/platform/maemo/maemo.cpp
backends/platform/maemo/maemo.h
backends/platform/sdl/sdl.cpp
backends/platform/sdl/sdl.h
backends/platform/wii/osystem.cpp
backends/platform/wii/osystem.h
base/main.cpp
common/system.h
engines/engine.cpp
engines/icb/surface_manager.cpp
engines/scumm/he/script_v100he.cpp
engines/scumm/he/script_v70he.cpp
engines/scumm/he/script_v72he.cpp
engines/sword2/maketext.cpp

This is in draft mode until PR #2586 is merged.

BACKENDS: Use Common::U32String for OSystem::setWindowCaption

---

engines/scumm/imuse_digi/dimuse_track.cpp

This commit fixes an oversight in which I allowed fade-ins for every track, regardless of their type (VOICE, SFX and MUSIC).
Now, fade-ins at sound start are allowed for music tracks only.

SCUMM: COMI: prevent SFX and VOICE from using fade-in

---

engines/scumm/imuse_digi/dimuse.cpp
engines/scumm/imuse_digi/dimuse_music.cpp
engines/scumm/imuse_digi/dimuse_sndmgr.cpp
engines/scumm/imuse_digi/dimuse_track.cpp

These commits fix the root cause for bug [#11956](https://bugs.scummvm.org/ticket/11956) (even though that song now starts way too early, I need some help on figuring out why that happens, but at least the JUMP behavior is now correct), and implements handling for "_end" triggers found in transitions type 4 and 9.
As a result, this fixes the ending point for a couple of music tracks (seqArriveBarber and seqAttack), which played until the whole audio file had finished, instead of ending on the "_end" marker.

SCUMM: COMI: improve handling of iMUSE markers and triggers

---

backends/dialogs/amigaos/amigaos-dialogs.cpp
backends/dialogs/amigaos/amigaos-dialogs.h
backends/module.mk
backends/platform/sdl/amigaos/amigaos.cpp
configure

This adds a native file browser (ASL) to the AmigaOS port.
utf8 is handled just like MorphOS does it
Thanks a lot Capehill and jabirulo

AMIGAOS: Add native system dialogs support through ASL

---

engines/grim/lua_v1_text.cpp

Fixes bug where cutscenes lines were always written to dialogue transcript in english regardless of game language
as described in https://bugs.scummvm.org/ticket/11878
The change removes the second condition of checking the string to localize ends with `/`
sayLine do receive string formatted as `/{msgId}/`
but in cutscene they received as `/{msgId}/{original}`
as `parseMsgText` / `localize` only care about the first part `/{msgId}/` (rest is ignored)
it seems to work on both cases

GRIM: fix localization of dialogue transcript

---

audio/mididrv.cpp
audio/mididrv.h
audio/midiparser.h
audio/midiparser_smf.cpp
audio/miles.h
audio/miles_adlib.cpp
audio/miles_midi.cpp
audio/module.mk
audio/mt32gm.cpp
audio/mt32gm.h
engines/sci/sound/drivers/midi.cpp

MIDI: Add MT-32/GM MidiDriver
I've added a MidiDriver subclass specifically for MT-32 and GM devices. This 
pulls together some functionality which I saw was duplicated in a number of 
engines. I've moved some existing MT-32/GM specific code over from the 
MidiDriver base class and the Miles driver.
This driver can be used as a basis for implementing support for these devices 
in new engines, or old engines can be reworked to use this driver if they want 
to use some of the features of this driver.
I've used this driver to complete MT-32 support in Lure of the Temptress. I've 
also updated the SMF parser to be able to use the multiple source feature for 
use with this game.
The driver has the following features (see mt32gm.h for more details):
- MIDI device initialization
- MT-32 <> GM …

MIDI: Add MT-32/GM MidiDriver

---

doc/doxygen/groups.dox
engines/advancedDetector.h
engines/engine.h
engines/game.h
engines/metaengine.h
engines/obsolete.h
engines/savestate.h
engines/util.h

This is a doxygen review for 4 header files that have been
identified as high priority for GSoD:
- advancedDetector.h
- metaengine.h
- engine.h
- util.h
It also adds doxy groups to other headers from this folder to
make them appear properly in the structure.
HTML output available here:
https://b-gent.github.io/2633/de/d3d/group__engines__advdetector.html
@sev-  @criezy

DOXYGEN: Review of high prio headers from engines

---

NEWS.md
backends/platform/sdl/amigaos/amigaos-main.cpp
configure

- Readability
- Changed and added comments
- Changed one variable name for comprehensibility
- Added no builtin resources as default to save as much binary size as possible
- Tried to apply to the coding standards (and probably failed miserably)
- Re-activate the formerly locked-out nuked OPL Adlib driver
- Reflect changes in NEWS.md

AMIGAOS: Platform updates

---

engines/parallaction/disk_ns.cpp

This fixes a crash when starting the Nippon Safes Inc. demo.

Revert "PARALLACTION: Fix buffer overrun"

---

Makefile.common
configure

This provides a fairly significant reduction in code size at the cost of not being able to detect games from disabled engines. This should hopefully fix the N64 port, which is currently failing on the buildbot due to the .rodata section overflowing, and is likely to be useful on other platforms with very limited amounts of RAM.

CONFIGURE: Allow building without detection code for disabled engines

---

engines/kyra/detection_tables.h
engines/made/detection_tables.h
engines/mohawk/detection_tables.h
engines/saga/detection_tables.h
engines/sherlock/detection_tables.h
engines/xeen/detection_tables.h
engines/zvision/detection_tables.h

I have several more to add, but I wanted to submit these in case detection code changes and they become obsolete.
Korean Return to Zork is only dubbed. There are no fonts to render, even in the menus. Unlike the Japanese version, this version should work without further changes.
KYRA.DAT still needs to be updated.

ENGINES: Add detection for international releases in many engines

---

backends/platform/sdl/amigaos/amigaos.mk
dists/amigaos/Ext_Inst_so.rexx

amigaos.mk
- Add force to rm
- Always remove shared objects before installing, otherwise outdated ones will bitrot
Ext_Inst_so.rexx:
- Add used gcc version check to be able to install libgcc.so from it's default install directory
- Fixed a wrong *copy from* directory
- *Never* use anything installed in system's SOBJS: (since users can install stuff there from all over the place)

AMIGAOS: Fix automatic (dynamic) building process

---

engines/mohawk/myst_areas.cpp

This is my attempt at fixing https://bugs.scummvm.org/ticket/11954
Apparently, when reading a movie file name the engine needs to read an even number of bytes (probably to keep the rest of the data aligned), so if the length of the file name is even (not counting the terminating 0) it has to read an extra byte. This was already done, but apparently the String class used to allow you to add terminators to a string, and these were then counted into
the length of it. Not adding the terminator avoids this disambiguity, in case the behavior changes again. (I know it was changed to its current behavior to fix regressions in other engines.)
I've played through the non-Masterpiece version of Myst, getting both the red and blue pages and watching all the bad endings, without any crashes. I figured …

MOHAWK: Fix Myst regression (bug #11954)

---

engines/kyra/sound/drivers/adlib.cpp
engines/kyra/sound/drivers/pc_base.h

I'm fixing some issues with the Westwood ADL driver in AdPlug, which
is based on ScummVM's Kyra AdLib driver. I think these fixes should
go upstream, so I'm submitting them here first.
Most of the work will be about adding safety checks such that even
manipulated sound files can't crash the driver. I'm fixing other issues
along the way when I encounter them, as in the first few commits.
Later, I may also try to name some of the remaining unknowns and
simplify some code.
Don't hesitate to comment if you have suggestions.

KYRA: adlib driver fixes

---

engines/sci/console.cpp

When debugging, I'm constantly inspecting the SCI VM registers and thought this would be a great command to have an alias for.
I am proposing the following alias: `reg` for the command `registers` and also updated the help docs.

SCI: add a shortcut alias for the registers debug console command

---

engines/scumm/input.cpp

This PR fixes bug [#12022](https://bugs.scummvm.org/ticket/12022) by bypassing the _skipVideo flag only for that certain room and script, preventing unintended side effects for the remainder of the game.

SCUMM: FT: fix bug #12022

---

engines/scumm/script.cpp

Due to poor translation of the v2 script to v5 an if statement jumps in the
middle of a cutscene causing a endCutscene() without a begin cutscene()
Previous "fixes" do improve the code, but do not fix this cutscene issue.
See also
https://bugs.scummvm.org/ticket/3099
https://bugs.scummvm.org/ticket/5624
and commits
1d40f7849965e8b758b88197820daf9c6af4d120
Fixes the mistranslation of getState08(465) into classOfIs(465,[0]) at 001A
0725be325f60fa578b918aaaaef1d5f4008d310a
Fixes several mistranslations of setClass

SCUMM: ZAKFM Add script bug workaround, fixes bug #5624

---

engines/scumm/script_v6.cpp

This PR patches a script bug (or oversight?) which was of course also present in the original EXE: 
after greasing the cannonballs in the Plunder Town Theater, during the juggling show, the game cuts from room 18 (backstage) to room 19 (stage).
Usually, when loading a room, script 29 is in charge of switching the background music, based on which room we've just loaded.
Unfortunately, during this cutscene, script 29 is not executing, therefore the music is unchanged from room 18 to 19.
This creates a coherency issue between the current music (state 1277, which is a muffled version of the juggling theme, used in the backstage) and the drums fill played afterwards (sequence 2225, which is a continuation of the unmuffled juggling theme played on the stage).
This fix checks for this exact …

SCUMM: COMI: fix missing soundKludge call

---

gui/options.cpp

Fix for issue #11744, with similar fix for updating graphics mode as well.
Selecting "\<default\>" for "Graphics Mode" and "Stretch Mode" and clicking "Apply" under Options...->Graphics now immediately reflects the changes in ScummVM window.

GUI: Reflect default Gfx/Stretch Mode immediately

---

gui/widgets/list.cpp

Lately I've been modifying the descriptions of the games I've added to ScummVM to give each engine and/or company its own unique prefix, e.g. "[LucasArts] Loom (Floppy)".
Today I decided to change "[Comprehend]" to "[Polarware]" so I entered "Comprehend" in the search box and started editing. For each edit, the game would - of course - be removed from the filtered list. When I got to the last one, and the filtered list became empty, ScummVM crashed with the following assertion:
```
scummvm: gui/widgets/list.cpp:139: void GUI::ListWidget::setSelected(int): Assertion `item >= -1 && item < (int)_list.size()' failed.
Aborted
```
I _think_ the problem is that setSelected() uses _listIndex.size() to determine if the list is filtered. That works as long as there is something in the _listIndex: …

GUI: Fix crash in launcher dialog when search filter no longer matches anything

---

engines/scumm/input.cpp

Updated the workaround for bug #12022, accounting for the existence of Version B.
Luckily this didn't require comparing md5 values, as it appears there are no edge cases which can take the wrong if-"route" on the non correspondent version.

SCUMM: FT: update cutscene fix to account for Version B

---

backends/dialogs/amigaos/amigaos-dialogs.cpp
backends/dialogs/amigaos/amigaos-dialogs.h

The codesets library is provided separately from the main SDK, and it's only used for converting from UTF-8 to ISO 8859-1, which can be done using ScummVM's builtin encoding code.
This has not been tested.

AMIGAOS: Remove dependency on the codesets library

---

Makefile.common

I'm trying to have successful builds with the "make -j 6 clean all" command and before this change, the failure rate was 100%.
This change fixes the problem that the clean target was run partially at the start of the build and the rest just before the linking of the final executable, which was the reason of the 100% failure rate. The change prevents the redefinition of the "clean" target by hooking on the existing one instead.
Unfortunately, it's not good enough to entirely fix the problem, the failure rate is now about 50%. While the "clean" target runs entirely at the start, it seems that "all" can still start before "clean" is fully completed. I attempted to serialize the "clean" and "all" targets using the ".ORDER" directive and also order only prerequisites with no success.
I'm …

BUILD: Fix parallel "clean all" builds

---

engines/sci/detection_tables.h
engines/sci/resource/resource_patcher.cpp

This PR has 2 commits. One to tolerate a slightly invalid image and another adds the hashes

SCI: Add City's fan Russian translation support

---

audio/softsynth/mt32.cpp

This seems to be a leftover from commit 7058daaed164934ba66a6554235e8b23a9ccf110.

MT32: Remove setting the palette when the driver is initialized

---

backends/platform/sdl/amigaos/amigaos.mk
dists/amigaos/RM2AG.rexx
dists/amigaos/RM2AG.rexx.in

Updated the readme converter script and amigaos.mk
Someone has to please update rm2ag.rexx.in as i have no idea what to do there and don´t want to break anything

AMIGAOS: Fixes to the automatic installation

---

engines/wintermute/detection_tables.h

WINTERMUTE: Add IndieGala version of Corrosion: Cold Winter Waiting (Enhanced Edition)
This fixes https://bugs.scummvm.org/ticket/12049
Game link: https://freebies.indiegala.com/corrosion-cold-winter-waiting
WINTERMUTE: Add detection for Reversion: The Return (Steam, December 2020)
Steam DB: https://steamdb.info/depot/281082/manifests/

WINTERMUTE: Update detection table

---

engines/wintermute/detection_tables.h

Main game files and all other language files are the same as May 2020 release

WINTERMUTE: Add Reversion 3 (Steam, November 2020)

---

engines/sci/engine/message.cpp

Before this PR, Hebrew text in parentheses was treated as stage direction (because it doesn't contain English lower case letters, and usually doesn't contain digits), and wasn't printed.
This PR makes Hebrew letters behave similar to English lower case letters - if they exist - print the message.
(There is no point in translating the stage direction to Hebrew, if ever there will be a Hebrew dubbing project, the actors will use the English directions...)
This PR is coordinated with the group that translated previous Sierra titles to Hebrew (Torin, GK2, SQ3), and working now on QFG1VGA - that's were we understood that problem. In previous titles, the text in parentheses wasn't translated at all, thus, this fix won't make any unwanted text to start appearing.

SCI: Hebrew in parentheses isn't stage direction

---

engines/ultima/ultima4/game/creature.cpp

Through an interesting series of events I noticed that the xu4 damage was different from the DOS version of the game.
Disassembled DOS version: https://github.com/ergonomy-joe/u4-decompiled/blob/master/SRC/U4_AI.C#L127
Note: D_23D2[C_7C25((unsigned char)Fighters._tile[bp04])] is equivalent to creature.basehp
If I'm doing the math right then they are equal when the monster base health is below 64. But above that they diverge with xu4 creatures doing significantly less damage.
(It is possible that the xu4 version is getting the damage calculation from a different port of the game. I haven't been able to check that.)

ULTIMA4: Change damage to match DOS version

---

dists/android/build.gradle
dists/android3d/build.gradle

My tablet runs Android 4.4, and I haven't encountered major crashes with recent versions of ScummVM. As such, this commit would prevent ScummVM from working on it outright.

Revert "ANDROID: Set minimal SDK to 21+ (Android 5+). The app crashes at launch on Android 4"

---

graphics/managed_surface.cpp
graphics/managed_surface.h

This adds scaling support for non transparent blit functions of the ManagedSurface class
Related issue is https://bugs.scummvm.org/ticket/12050

GRAPHICS: allow scaling for opaque surfaces

---

backends/audiocd/default/default-audiocd.cpp

this allows us to use the unmodified version of dotemu lba1 enhanced music track paths
see 1b67a288abbed4e130fac8507d8f66940fcc0530

BACKENDS: search also for track_x and track_xx audio cd tracks

---

backends/platform/symbian/src/SymbianOS.cpp
backends/platform/symbian/src/SymbianOS.h

SYMBIAN: call main menu by key asterisk.
Replace hotkeys for calling main menu by asterisk because that used long ago. Asterisk used to call main menu because it presen on phone keyboard. On devices with touchscreen symbian sdl backend provides screen keyboard with several layouts with that key.

SYMBIAN: Global Main Menu called with asterisk.

---

base/main.cpp

When the Options...->Misc->"Always return to the launcher on leaving a game" option is checked, the "relaunched" launcher GUI will not launch with correct stretch mode, if "Edit Game...->Graphics->Stretch Mode" was set to <default> from some non-default value. This also results in the game re-launching with the same non-default setting as applied above, as described in Issue #12041.
This requires the same fix as was done in PR #2690, which was to remove the hasKey() constraint, because setStretchMode() and ConfMan.get() methods together were able to set the <default> setting properly in absence of a key.

GUI: Refresh stretch mode upon returning to launcher

---

engines/sci/engine/script_patches.cpp

Issue #11660 is caused by signTalker overriding global90,
which keeps speech and subtitles settings.
That's fixed in this patch.
Similar problem can also be caused by computerTalker.
Waiting to see it happening, before fixing.

SCI: PQ4 - Partial fix for #11660 (keep speech and subtitles setting)

---

engines/mohawk/dialogs.cpp
engines/sci/detection.cpp
gui/ThemeEval.h

This addresses bug [GUI: I18N - RTL: "Edit game" dialog looks distorted for SCI games](https://bugs.scummvm.org/ticket/12028#no1).
The issue affects all engines with a custom options widget, as currently the RTL layout doesn't apply to widgets created via code. I made the following changes:
- Set `useRTL` to `true` in the `addWidget()` calls.
Should this be the default instead? There's no other uses of `addWidget()`.
- Renamed the dialogs to `"GameOptions"` so the RTL rule would apply correctly: https://github.com/scummvm/scummvm/blob/master/gui/widget.cpp#L119
Should this be a Widget property instead? Relying on a magic name isn't obvious.

GUI: Fix RTL layout in engines with custom options widget

---

backends/cloud/dropbox/dropboxcreatedirectoryrequest.cpp
backends/cloud/dropbox/dropboxcreatedirectoryrequest.h
backends/cloud/dropbox/dropboxinforequest.cpp
backends/cloud/dropbox/dropboxlistdirectoryrequest.cpp
backends/cloud/dropbox/dropboxlistdirectoryrequest.h
backends/cloud/dropbox/dropboxstorage.cpp
backends/cloud/dropbox/dropboxstorage.h
backends/cloud/dropbox/dropboxtokenrefresher.cpp
backends/cloud/dropbox/dropboxtokenrefresher.h
backends/cloud/dropbox/dropboxuploadrequest.cpp
backends/cloud/dropbox/dropboxuploadrequest.h
backends/module.mk
gui/options.cpp

Dropbox [is switching](https://www.dropbox.com/lp/developers/reference/oauth-guide) to short-lived `access_token` OAuth mid 2021. This commit adapts `Cloud::DropboxStorage` to use `refresh_token` similarly to how other Storages do: by introducing a `DropboxTokenRefresher`.
@Mataniko already added a new endpoint on cloud.scummvm.org, which will be used for Dropbox from now on. Older versions of ScummVM, which do not have this change, will still work with "Legacy" endpoint until Dropbox deprecates it.
I've checked all the `Dropbox*Request` classes with Testbed for handling the "expired_access_token" error (handled via the `DropboxTokenRefresher`) and all of them work.

CLOUD: Update Dropbox to use refresh_token

---

engines/scumm/smush/smush_font.cpp
engines/scumm/verbs.cpp

Fixes bug in dialogue text in COMI hebrew fan translation,
bug was: when the dialogue option should have span on multiple lines, it was instead cropped out of the screen.
this is solved by aligning the text to the right after lines are splitted.
Thanks.

SCUMM: COMI: fix hebrew multiline dialogue

---

audio/decoders/asf.cpp
audio/decoders/wave.cpp
audio/decoders/wave_types.h
engines/titanic/sound/wave_file.cpp
video/avi_decoder.cpp
video/avi_decoder.h

I noticed the A/V code duplicates the WAV Format Tags multiple times, so I combined all of them into the common `wave_types.h` header, as this should make it easier to add new formats in the future and avoid conflicts.
Dunno if decimal or hexadecimal is better, but since the format specification uses hexadecimal I went with that.

AUDIO: Combine WaveFormat enums under one header

---

engines/ags/detection_tables.h

This patch adds an detection entry for the Windows release of "Unavowed" available at Steam and GoG.
The came is currently unable to launch and fails with the following stacktrace:
https://paste.ubuntu.com/p/zT8KCCH9wk/

AGS: Add detection entries for 'Unavowed (English/Windows)'

---

base/plugins.cpp
base/plugins.h

This should fix [Trac #12094](https://bugs.scummvm.org/ticket/12094).

BASE: Fix crash when building with uncached plugins and static detection

---

backends/graphics/sdl/sdl-graphics.cpp
backends/platform/sdl/sdl.cpp

When switching between the SDL and OpenGL graphics managers, trying to restore the state could fail as the two managers do not have the same list of supported formats, so we may not be able to transfer the pixel format from one to the other. This then resulted in an assert.
This fixes [bug #12079](https://bugs.scummvm.org/ticket/12079).
I am not sure the way I fixed it is the best way to do it. So I am opening that pull request for review before merging.

SDL: Fix trying to set unsupported pixel format when changing  gfx mode

---

configure
devtools/create_project/xcode.cpp
dists/macosx/Info.plist
dists/macosx/Info.plist.in

This is related to bugs #11430 and #11305.
It appears that commit a1d930209a6452649ab704dbbcf2084c9177936e is actually enough to avoid blurriness display issues on Retina screens (i.e. favour OpenGL rendering over Metal rendering inside SDL2, because of interaction problems between macOS on Retina screens and SDL2).
Previous attempts at working around this included disabling Dark Mode (c59bf95ba85b25b134110eb0ff9c3d0e17750630) and passing a particular "invalid" argument to the `-platform_version` linker flag (70f79d3df8b4a9d4c6d1b69838ff5a722c51b61e), but it appears that `SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengl")` is sufficient to avoid this bug (until a future version of SDL2 possibly fixes this for good and makes any workaround unnecessary).
(Note when manually testing changes to …

MACOSX: simplify Retina blurriness workarounds and restore Dark Mode

---

devtools/create_project/create_project.h
devtools/create_project/xcode.cpp

Here's a set of changes I had to make so that `create_project` could be built on Mac OS X Leopard.
In summary:
* pick the `override` compat macro from `c++11-compat.h` to `msbuild.h`, because this file makes use of the `override` keyword, and older compilers don't have it.
* use `<CommonCrypto/CommonDigest.h>`, not `<CommonCrypto/CommonCrypto.h>` for `CC_MD5()`. This is what the manpage documents, and Leopard will not find it without the proper header.
* use the older POSIX.1-2001 syntax for `realpath()`, not the POSIX.1-2008 one, because it will cause a crash on older systems. Don't `free(rp);` anymore, since we're no longer using the heap for this.
This is maybe useless (although the one for `CommonDigest.h` still looks good to me), or you may want to do this a bit differently, but …

CREATE-PROJECT: Various portability fixes for Mac OS X Leopard and other older systems

---

engines/ags/detection_tables.h

This pull request adds detection entries for Viki.si Studio's M*A*S*H*: The Point n' Click Adventure (mash, demo and full version, https://mashthegame.viki.si) and differentiates the Steam version of Size Five Games' Ben There, Dan That! (bentheredanthat) as "Special Edition".

AGS: Ben There, Dan That! (Special Edition) and M*A*S*H*: The Point n' Click Adventure

---

engines/ags/plugins/ags_galaxy_steam/ags_blackwell_steam.cpp
engines/ags/plugins/ags_galaxy_steam/ags_blackwell_steam.h

AGS:  This pull request adds the AddAchievment method to AGSGalaxySteam to fix a script crash when starting Blackwell Epiphany.

AGS: Add AddAchievment method to AGSGalaxySteam

---

image/codecs/mpeg.cpp
image/codecs/mpeg.h

This avoids to pollute declarations with inttypes.h and mpeg2dec.h when
including mpeg.h

IMAGE: Move mpeg2dec.h inclusion in CPP file

---

engines/sci/sound/music.cpp
engines/sci/sound/music.h
engines/sci/sound/soundcmd.cpp

When kDoSoundPlay is called on a sound that's already playing, SSCI would restart that sound, but ScummVM has instead just allowed the existing sound to continue. Not many scripts depend on this but a few do and bugs have built up in the tracker. The codepaths for handling samples vs MIDIs are different but they're in the same function and it causes the same kinds of issues.
Fixed by restarting MIDIs:
- QFG4 doorbell puzzle not playing the same bell multiple times in a row. The script expects to be able to interrupt and restart the bell. https://bugs.scummvm.org/ticket/12105
- KQ6CD wallflower dance lockup when playing the flute while the music is still playing doesn't start the song over. If the song doesn't start over, the signals the script waits on never occur. …

SCI: Restart sounds in kDoSoundPlay when already playing

---

engines/ags/shared/util/compress.cpp

The Android NDK uses unsigned char by default. Fixed the decompression algorithm by replacing them with int8. Also not using the fixed PixelFormat with OpenGL as it is not supported there. These changes allow the Games to run, albeit with messed up colors.

AGS: Fix Android crash to OS on game launch

---

backends/platform/3ds/config.cpp
backends/platform/3ds/config.h
backends/platform/3ds/main.cpp
backends/platform/3ds/options-dialog.cpp
backends/platform/3ds/options-dialog.h
backends/platform/3ds/osystem-audio.cpp
backends/platform/3ds/osystem-events.cpp
backends/platform/3ds/osystem-graphics.cpp
backends/platform/3ds/osystem.cpp
backends/platform/3ds/osystem.h
backends/platform/3ds/sprite.cpp
backends/platform/3ds/sprite.h

This fixes a clash with a define from the devkitPro build scripts.

3DS: Rename the _3DS namespace

---

common/ini-file.cpp
engines/agi/wagparser.cpp
engines/agi/wagparser.h

AGI: support new WinAGI *.wag file format

---

engines/scumm/imuse_digi/dimuse.cpp
engines/scumm/imuse_digi/dimuse_script.cpp

This is an urgent fix which is contained in PR [#2701](https://github.com/scummvm/scummvm/pull/2701). Since that PR is quite big and it's taking some time to be approved, and since people are rightfully telling me that FT is currently broken in the current dev build, I'm sending these _urgent_ fixes as a separate PR.
_Please_ merge this as soon as you can, since this fixes Full Throttle crashing and another bug in COMI which allowed zero volume (toBeRemoved) tracks to be able to make JUMPs and loops before being flushed.

SCUMM: Digital iMUSE: fix FT crash and music breaking bug

---

config.guess
config.sub

New version handles Darwin arm64

CONFIGURE: Update config.* to latest version

---

gui/console.cpp

This is useful for situations where the game crashes or is quit, but you still need to
output of the debug commands for investigating the issue

GUI: added debug output for console prints

---

gui/ThemeEngine.cpp
gui/gui-manager.cpp

This was spotted with a FreeType disabled build and with Address Sanitizer

GUI: Don't leak theme and TextDrawData when loading fails

---

engines/ags/engine/gfx/gfxdriverbase.cpp

This translates types to their sized expected variant (unsigned int ->
uint32).
One simplication is done too with ptrLong vs. memPtrLong.

AGS: Remove unsized types

---

engines/ags/detection.cpp
engines/ags/detection.h
engines/ags/engine/main/config.cpp
engines/ags/engine/platform/windows/setup/winsetup.cpp

AGS games can have multiple languages by providing additional translations as .tra files. The language selection is done by setting the config "translation" key to the tra file name. This means that we cannot easily use the standard ScummVM language selection for this purpose as the tra file name may not map to language names easily.
Also the advanced detector does not allow specifying multiple languages for a game, and adding separate detections for all the languages by using the tra files for the detection would be cumbersome.
Instead this pull request  does something similar to the original games by detecting at runtime the available .tra files, but replaces the original setup utility by a game option widget.
It's not ideal that we have an ineffective Language selector in the Game tab, …

Add engine option widget for language selection

---

engines/scumm/imuse_digi/dimuse.cpp

The iterator `l` was used inside the loop, which caused it to bail out
after 12 iterations instead of 16.
Amends 434d1f37f9398b6a7a1b08cd5464a1d5ecccdc41.

SCUMM: Fix bad offset on game loading

---

graphics/fonts/ttf.cpp

Update color blending to match blending found in ManagedSurface. TTF rendering assumed the alpha channel of the surface was completely opaque. ULTIMA8 TTF rendering attempts to use a transparent surface and became near-illegible for text on scrolls. This change will affect TTF rendering on surfaces that are not already painted.

GRAPHICS: Improve TTF rendering on transparent surfaces.

---

common/hashmap.cpp
common/hashmap.h

Gives better error messages if someone is using `const char*` as the hashmap Key.

COMMON: Specialize unknownKeyError for more types

---

engines/sci/engine/ksound.cpp
engines/sci/sound/music.cpp
engines/sci/sound/music.h
engines/sci/sound/soundcmd.cpp
engines/sci/sound/soundcmd.h

This fixes subtle sound bugs in SCI16 games with speech. The SQ4CD introduction has at least two:
- When the alien dissolves in a puddle of vomit, the sound keeps playing during the narration in the next room
- When the Vohaul hologram appears, the static sound effect keeps playing when he talks
In both of these cases, the digital sample should have stopped as soon as speech started.
In SSCI, digital samples are handled by kDoAudio. If a digital sample is played with kDoSound then SSCI just calls kDoAudio and it still does the work. When kDoAudio plays, it first stops any samples that it already played.
In ScummVM, all sounds played with kDoSound are handled separately from kDoAudio, even if they're samples, so an extra step is needed for our kDoAudio to stop all samples as SSCI does.
[ …

SCI: kDoAudio stops samples played with kDoSound

---

graphics/managed_surface.cpp
graphics/managed_surface.h

A change made yesterday forces `ManagedSurface` to be fully opaque. This may be an issue for some engines.
This commit revert this and also adds proper handling of the surface alpha when blitting pixels.

GRAPHICS: Support having transparent ManagedSurface

---

graphics/font.cpp
graphics/font.h
graphics/fonts/ttf.cpp
graphics/managed_surface.h
graphics/screen.h

This pull request resolves the outstanding problem with rendering TTF text onto surfaces in the AGS engine.. the problem being that with the surfaces having a designated transparent color, partially transparent pixels in the TTF glyphs were doing an alpha blend of the font color with the pink color AGS uses for transparency. Since this affects the core font code, I figure to make it a pull request for review first.
This change introduces a new virtual method on Graphics::Font called "setTransparentColor", and then overrides that in TTFFont.  In the TTFFont glyph drawing code, if it's drawing a partially transparent pixel and detects the transparent color, it forces it to be transparent so it won't be blended.

AGS: Fix text rendering onto surfaces with a transparent pixel color

---

engines/director/lingo/lingo-builtins.cpp
engines/director/lingo/lingo-builtins.h

Normally, `colorQD` is a `TheEntity`. However, "Eastern Mind: The Lost Souls of Tong-Nou" instead uses it as a builtin with no arguments, both in Mac and Windows versions of the game.
cc @sev-

DIRECTOR: implement colorQD builtin

---

common/scummsys.h

bits/os_defines.h has #define NOMINMAX 1, which conflicts with the
non-value #define NOMINXMAX in scummsys.h.
```
In file included from ../scummvm/common/lua/lua.h:12,
from ../scummvm/common/lua/ltable.cpp:27:
../scummvm/common/scummsys.h:111: warning: "NOMINMAX" redefined
111 |   #define NOMINMAX
|
In file included from C:/msys64/mingw64/include/c++/10.2.0/x86_64-w64-
mingw32/bits/c++config.h:518,
from C:/msys64/mingw64/include/c++/10.2.0/cmath:41,
from C:/msys64/mingw64/include/c++/10.2.0/math.h:36,
from ../scummvm/common/lua/ltable.cpp:21:
C:/msys64/mingw64/include/c++/10.2.0/x86_64-w64-mingw32/bits/
os_defines.h:45: note: this is the location of the previous definition
45 | #define NOMINMAX 1
|
```
Amends commit 88f685217b1c8e7ab2c7a588677ad4744480b4a3.

COMMON: Fix warnings on mingw build

---

engines/ags/plugins/plugin_base.cpp

Might help in those cases where the assert is triggered, because the plugin is not known.

AGS: added debug message about unsupported plugin

---

doc/docportal/other_platforms/ios.rst

Just fixing a link that I found broken while following the iOS building documentation

DOCS: Fix link to the iOS Libraries

---

engines/cine/saveload.cpp
engines/engine.cpp
engines/metaengine.cpp
engines/metaengine.h
engines/ultima/nuvie/files/nuvie_io_file.cpp

I think this is a straightforward minor change, but since it touches the engine base, I thought I'd do a pull request for a quick review.
This change changes the methods for appending the new style extra savegame info to instance methods, and the method that generates the thumbnail a virtual method. This will allow engines to override the method in their own meta engine subclass, and do things like create a thumbnail without any on-screen dialogs showing.

ENGINES: Make creation of savegame thumbnails an overrideable method

---

engines/grim/pool.h

A user reported a crash with `Unknown key!` error when trying to load a save game in MI4 today on IRC/Discord.
@henke37 suggested that the likely culprit was the code changed in this pull request.
I don't have the game, and the demo doesn't let me save games. So I am unable to test this. This is why I am proposing this as a pull request so that developers who know the engine or can at least test it can validate the change.

GRIM: Fix unknown key error when loading savegame

---

engines/scumm/script_v8.cpp
engines/scumm/verbs.cpp

The value of left is applied from the script all the time, and was replaced in drawVerb.
The problem with this approach is that redrawVerbs maps the mouse location to verb index **before** calling drawVerb, so the rectangles it compares against are invalid in X-axis (right is always `_screenWidth - 1`, and left is always 5).
This caused several bugs:
* Each verb was clickable all over the screen's width, although it was not highlighted.
* If the mouse was between 2 verbs, long above short, the Y-axis has 6 overlapping pixels (e.g. 1: 330-360, 2: 354-384). Scanning is done bottom-up, so 1 was highlighted, but 2 was selected because of the previous bullet.
* The text on Hebrew was aligned to the right without any padding. Other languages have `left = 5`.
Fixed by setting right instead of …

SCUMM: Fix wrong rect for verbs on Hebrew

---

audio/softsynth/fluidsynth.cpp

I'm using a SoundFont file called 8MBGMSFX.SF2 that was included with my old SoundBlaster sound card. You'd think that would be as close to an official SoundFont that you can find, and yet I'm still getting a bunch of annoying warnings when the FluidSynth driver is initialized:
```
fluidsynth: warning: Instrument 'Piano 1': Some invalid generators were discarded
fluidsynth: warning: Instrument 'Piano 2': Some invalid generators were discarded
fluidsynth: warning: Instrument 'Piano 3': Some invalid generators were discarded
fluidsynth: warning: Instrument 'Honky-tonk': Some invalid generators were discarded
```
And then when the drive is de-initialized:
```
fluidsynth: warning: No preset found on channel 0 [bank=0 prog=34]
fluidsynth: warning: No preset found on channel 1 [bank=0 prog=73] …
```

RFC: Make FluidSynth logging less noisy by default

---

backends/events/sdl/sdl-events.cpp

The ResidualVM merge 35b9cccbde37d20fdbc10254d4ab8cc260551e84 introduced a regression: the return value from SdlGraphicsManager::notifyMousePosition() became ignored, causing SdlEventSource::processMouseEvent() to always return true even when the mouse is outside of the active area. This appears to be unintentional and wasn't a problem for ResidualVM code because SdlGraphics3dManager::notifyMousePosition() always returns true.
This bug causes invalid mouse positions to be exposed to game engines through DefaultEventManager::getMousePos(). Instead of clipping coordinates to the active area, real window coordinates are exposed. For example, if the window is sized so that there's 100 pixels above the active area, then mousing above the top edge sets the y coordinate 100 instead of 0, causing …

EVENTS: Fix mouse position outside active area

---

engines/private/cursors.cpp
engines/private/private.cpp
engines/private/private.h

This could be improved further by loading the cursor data from the executable resources instead of hardcoding it.

PRIVATE: Simplify the cursor code

---

engines/sci/engine/savegame.cpp
engines/sci/sound/midiparser_sci.cpp
engines/sci/sound/music.cpp
engines/sci/sound/music.h
engines/sci/sound/soundcmd.cpp

SCI: SCI0 sound restoring/restarting fixes
The main purpose of this is fixing incorrect sound restore after loading a savegame. Permanently hanging notes could sometimes be experienced when saving while a sound was playing and then reloading that savegame. That bug (and how it could be reproduced in KQIV) was pointed out to me by sluicebox. I just went over disasm (in this case mostly QFG, since I have the best disam there) and tried to match the original behavior a bit better. Commit b449564 is mainly for that. Commit cb50e48 aims at fixing inconsistent thread handling I had introduced with the initTrack method. I don't know whether it actually causes glitches. It was just one of the things I examined during my bug fixing attempts.
Commit 2a8289c fixes ScumVM specific things I had broken …

Sci0 sound restart

---

engines/myst3/archive.cpp

The String class underwent some rewriting recently. I think it was this: https://github.com/scummvm/scummvm/commit/29cfa7bb0f2c1c76a9ef285b8e5799a7ec91020b
As I understand it, one of the changes was that string comparison now bails out if the two strings have different length. That means that "Hello World" and "Hello World\0" are no longer equal.
This caused regressions in Myst III (the game would complain that it could not find the subtitles font because the string it created for it had an extra terminator), and reportedly also in The Longest Journey though I do not know exactly how. So a change was made to ignore attempts at appending extra terminators to a string. See https://github.com/scummvm/scummvm/commit/54b0b4ac4cd4a42de660ea426edb27840ddfd4f0
This, however, caused a regression …

RFC: Address possible fallout from recent String change

---

engines/scumm/imuse_digi/dimuse.cpp
engines/scumm/imuse_digi/dimuse.h
engines/scumm/imuse_digi/dimuse_script.cpp
engines/scumm/imuse_digi/dimuse_track.cpp
engines/scumm/imuse_digi/dimuse_track.h

...second time's the charm, I guess 😓 
This PR consists in accuracy fixes to iMUSE Digital for Full Throttle with respect to the original DOS interpreter.
We have:
- A fix in `switchToNextRegion(Track *track)` (my fault, it was caused by a regression introduced by COMI fixes);
- A substantial refactoring in dimuse.cpp (which removes a lot of code duplication, since COMI and FT share lots of traits for music handling);
- Added fade-ins (they occur when there was another music track already running, otherwise the new music track is played without a fade-in); this implementation also prevents a bug found in the original EXE (i.e.: try getting in and out of the bar at the beginning of the game, the music will not fade properly and instead is replaced by silence)
- Fixed bug …

SCUMM: FT: improve and fix iMUSE Digital

---

audio/decoders/wave_types.h
audio/decoders/xan_dpcm.cpp
audio/decoders/xan_dpcm.h
audio/module.mk
engines/ultima/ultima8/games/remorse_game.cpp
engines/ultima/ultima8/games/u8_game.cpp
engines/ultima/ultima8/graphics/avi_player.cpp
engines/ultima/ultima8/graphics/avi_player.h
engines/ultima/ultima8/gumps/movie_gump.cpp
engines/ultima/ultima8/gumps/movie_gump.h
engines/ultima/ultima8/gumps/weasel_gump.cpp
engines/ultima/ultima8/misc/debugger.cpp
image/codecs/codec.cpp
image/codecs/xan.cpp
image/codecs/xan.h
image/module.mk
video/avi_decoder.cpp
video/avi_decoder.h

IMAGE, VIDEO, AUDIO: Add support for Origin Systems Xxan video format
Part of my ongoing work to add Crusader: No Remorse and Crusader: No Regret support to the Ultima 8 engine, this PR adds support for the Xxan movie format used in Crusader: No Regret.
Since I'm adding some more common code I thought it would be good to get some more eyes on this.  All changes should be compatible with existing games.
This also makes it potentially possible to some day create the Wing Commander IV adventure game cut, skipping all those annoying flying bits :)

IMAGE, VIDEO, AUDIO: Add support for Origin Systems Xxan video format

---

common/unicode-bidi.cpp
common/unicode-bidi.h

```
/data/src/master/common/unicode-bidi.cpp: In member function 'void
Common::UnicodeBiDiText::initWithU32String(const Common::U32String&)':
/data/src/master/common/unicode-bidi.cpp:78:3: error: invalid conversion
from 'uint32*' {aka 'unsigned int*'} to 'FriBidiParType*' {aka 'long
unsigned int*'} [-fpermissive]
78 |   &_pbase_dir,
|   ^~~~~~~~~~~
|   |
|   uint32* {aka unsigned int*}
```

COMMON: Fix FriBidiParType failure on 3ds

---

engines/ultima/nuvie/core/nuvie_defs.h

All the comparisons are done against Shared::MouseButton. Using values
from SpecialButtons makes no sense.

ULTIMA: Use correct enum for button constants

---

engines/titanic/star_control/fmatrix.cpp
engines/titanic/star_control/fmatrix.h
engines/titanic/star_control/fpose.cpp
engines/titanic/star_control/fpose.h

```
warning: definition of implicit copy assignment operator for 'X' is deprecated because it has a user-declared copy constructor
```

TITANIC: Fix Clang warning

---

engines/ultima/nuvie/gui/widgets/gui_widget.cpp

button cannot be any of these values. It is not even the right enum.
Detected by Clang.

ULTIMA: Remove wrong conditions

---

engines/twine/scene/movements.h

TWINE: Remove unused private member

---

math/matrix.h

```
../scummvm\math/matrix.h:146:2: warning: definition of implicit copy assignment operator for 'MatrixBase<4, 4>' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy]
MatrixBase(const MatrixBase<rows, cols> &m);
^
../scummvm\math/squarematrix.h:37:7: note: in implicit copy assignment operator for 'Math::MatrixBase<4, 4>' first required here
class MatrixType<dim, dim> : public MatrixBase<dim, dim> {
^
../scummvm\math/matrix4.h:36:7: note: in implicit copy assignment operator for 'Math::MatrixType<4, 4>' first required here
class Matrix<4, 4> : public MatrixType<4, 4>, public Rotation3D<Matrix<4, 4> > {
^
../scummvm\engines/grim/costume/mesh_component.h:45:65: note: in implicit copy assignment operator for 'Math::Matrix<4, 4>' first required here
void …
```

MATH: Fix Clang warnings on Matrix

---

common/queue.h

They're equivalent to the implicit ones anyway.

COMMON: Remove explicit ctors and copy assignment operator

---

engines/mohawk/livingbooks_code.cpp
engines/mohawk/livingbooks_code.h

```
warning: definition of implicit copy assignment operator for 'LBValue' is deprecated because it has a user-declared copy constructor
```

MOHAWK: Fix Clang warning

---

engines/glk/quest/string.h

This amends commit bedba56f24ccb1eaa9381ab36c446bb0b00cfb0c.

GLK: Fix compilation

---

common/unicode-bidi.cpp
common/unicode-bidi.h

Yet another stab at the FriBidiParType bug.
I use long unsigned int as it's the type used by the original enum defined in Fribidi (use of L suffixed integer literals).
According to https://en.cppreference.com/w/cpp/language/types, using uint32 could fail on some platforms where long unsigned int is 64 bits (LP64).
In addition, don't define constants in unicode-bidi.h as they are not available without Fribidi include.
This would fail if someone would want to use these constants.
As a consequence, the constructor with pbase should not be used outside of unicode-bidi.

COMMON: Don't use unavailable macros in unicode-bidi.h

---

engines/tinsel/bmv.cpp

It's not really needed, only to satisfy the compilers.

TINSEL: Add a missing case to switch statement

---

engines/ultima/shared/core/str.h
engines/ultima/shared/gfx/sprites.cpp
engines/ultima/shared/gfx/sprites.h
engines/ultima/ultima4/map/map_tile.h

```
warning: definition of implicit copy assignment operator for 'X' is deprecated because it has a user-declared copy constructor
```

ULTIMA: Fix Clang warnings

---

backends/graphics/gph/gph-graphics.cpp

Following removal of DownscaleSdlGraphicsManager, there is still some code calling it left.
I don't know enough of graphics code, hence the PR.
I am not sure about how all of this will behave on real hardware.

GPH: Don't call DownscaleSdlGraphicsManager anymore

---

Makefile.common

It is way faster than git update-index.

BUILD: Use git describe --dirty for git 2.x

---

engines/dragons/bag.cpp
engines/dragons/font.cpp
engines/dragons/screen.cpp
engines/dragons/screen.h

Hi,
This is related to https://bugs.scummvm.org/ticket/11710.
DRAGONS has some important rendering issues with big-endian systems. I have a PowerBook G4 running Debian unstable on ppc32 (big-endian), so I tried having a look at this. (I'm doing my tests with `Blazing Dragons (Sony Playstation/French)`, for reference.)
This first commit is incomplete, and has been mostly done through naive trial-and-error, so see this more as an attempt at showing where the problem lies. Feel free to improve on it or to rewrite it completely in a better way :)
It seems that, in this engine, screen content must be written in native endianness here, not in little-endian. So, I've just introduced a naive `WRITE_SCREEN` macro that choses `WRITE_LE_UINT16` or `WRITE_BE_UINT16`, depending on your platform. …

DRAGONS: Incomplete attempt at improving big-endian compatibility

---

engines/scumm/insane/insane.cpp
engines/scumm/smush/smush_player.cpp

In Hebrew there are no distinction between capital/small letters,
which results in wider text that although originally was able to fit in screen width, usually go beyond the width of the screen in translation.
This may be the easier way to solve this and it doesn't seem to have negative side effect. 
(the other way is to change the text flag in all animation files)
Thanks

SCUMM: SMUSH: always enable line wrap on hebrew fan translation

---

configure

This PR adds support of 64-bit iPhone to configure script.

IOS7: Add 64-bit target

---

audio/soundfont/vgmcoll.cpp

size_t and long are not the same on Win64.

AUDIO: Fix compiler warning

---

engines/scumm/he/moonbase/net_main.cpp

long and size_t are not the same on Win64.

SCUMM: Fix compiler warnings for bad formats

---

graphics/font.cpp
graphics/font.h
graphics/fonts/bdf.cpp
graphics/fonts/bdf.h
graphics/fonts/macfont.h
graphics/fonts/ttf.cpp
graphics/fonts/winfont.cpp
graphics/fonts/winfont.h

This pull request adds a `getFontAscent()` function to the `Font` class and implements it various classes that derives from it. I decided to make it optional with a default implementation that returns -1 to avoid having to add it to all the fonts implemented in engines where it is not needed (I saw that at least bladeruner and cryomni3d are implementing other font classes). It is implemented for all the font classes in the Graphics namespace.
This is needed in the AGS engine to properly align vertically the text drawn with TTF fonts.
Since this is a change in common code I am proposing this as a pull request. But I would like to merge this quickly so that I can push the changes in the AGS engine to properly display the text.

GRAPHICS: Expose ascent value in font class

---

engines/tinsel/tinlib.cpp

```
../scummvm/engines/tinsel/tinlib.cpp:1610:3: warning: variable 'playfield' is used uninitialized whenever switch case is taken [-Wsometimes-uninitialized]
CORO_INVOKE_ARGS(PlayFilmc, (CORO_SUBCTX, hFilm, x, y, 0, false, false, myEscape != 0, myEscape, bTop, playfield));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../scummvm\common/coroutines.h:226:17: note: expanded from macro 'CORO_INVOKE_ARGS'
return; case __LINE__:; \
^~~~~~~~
<scratch space>:143:1: note: expanded from here
1610
^~~~
../scummvm/engines/tinsel/tinlib.cpp:1610:106: note: uninitialized use occurs here
CORO_INVOKE_ARGS(PlayFilmc, (CORO_SUBCTX, hFilm, x, y, 0, false, false, myEscape != 0, myEscape, bTop, playfield));
^~~~~~~~~ …
```

TINSEL: Fix Clang warning

---

engines/glk/tads/tads2/debug.cpp

```
../scummvm/engines/glk/tads/tads2/debug.cpp:227:30: warning: cast from 'const char *' to 'unsigned char *' drops const qualifier [-Wcast-qual]
lstadv((uchar **)&p, &len);
^
```
Notice that lstadv doesn't modify the pointer contents, only the pointer itself,
so it really should have been const uchar ** in the first place, but changing that
requires too many changes in calling functions, so I took the easy path.

GLK: Fix Clang warning

---

engines/dragons/scriptopcodes.cpp

pointer and long are not equivalent. Cast to int.

DRAGONS: Fix format warning on MinGW64

---

engines/scumm/string.cpp

Control characters are already handled in getStringWidth. There is no
reason to copy the entire string for stripping them.

SCUMM: Simplify and optimize calculation of left position in Hebrew

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp

Tonight I noticed that ScummVM is crashing when switching from the OpenGL graphics mode to any other graphics mode. The crash I get is an assertion:
```
Assertion failed: (_transactionMode == kTransactionActive), function setStretchMode, file backends/graphics/surfacesdl/surfacesdl-graphics.cpp, line 727.
```
And from what I saw in the debugger it seems to be caused by recursive calls to `OSystem_SDL::setGraphicsMode()`.
A bisection indicates that the crash was introduced in commit 12878afc0.
And indeed reverting part of that commit fixes the crash.
I am not sure why that change was made as it seems to be unrelated to the other changes in that commit or indeed to the commit message. But there may have been a good reason to do it, and maybe my proposed change is not good.

SDL: Fix crash when switching from OpenGL to another graphics mode

---

engines/engine.h
engines/nancy/input.cpp
engines/nancy/nancy.cpp
engines/nancy/nancy.h

This hasn't been tested, since I don't have any of the games supported by this engine. `Engine::getDebugger()` has also been marked as final in order to catch future cases like this.

NANCY: Update the console code

---

engines/scumm/string.cpp

The text buffer starts on the i offset. This was overlooked in the original patch.
This amends commit 89c5cd5e5d81d780c74bf5da01ac6fb227e0695c.

SCUMM: Fix calculation of arrow position on Hebrew

---

common/scummsys.h

With `__printf__`, MinGW prefers the portable old ms-style printf, and
warns if formats like `%lld` and `%hhd` are used.
In practice, if __USE_MINGW_ANSI_STDIO is not defined, it defaults to 1
on C++11, and these formats are supported. Using `__gnu_printf__`
suppresses bad format warnings.

COMMON: Use __gnu_printf__ instead of __printf__ for gcc on MinGW

---

engines/wage/design.cpp
engines/wage/gui.cpp
graphics/macgui/mactext.cpp
graphics/macgui/mactext.h
graphics/macgui/mactextwindow.cpp
graphics/macgui/mactextwindow.h
graphics/macgui/macwindow.cpp
graphics/macgui/macwindow.h
graphics/macgui/macwindowmanager.cpp
graphics/macgui/macwindowmanager.h
graphics/nine_patch.cpp
graphics/nine_patch.h

GRAPHICS: MACGUI: fix the scroll bar of mactextwindow, fix the incorrectly behaviour when appendText of mactextwindow

---

audio/decoders/mac_snd.cpp
audio/decoders/quicktime.cpp
audio/decoders/wave.cpp
engines/cge/sound.cpp
engines/cge2/sound.cpp

This cleans up audio code that mallocs raw audio data just to discard format headers, instead of just wrapping the stream. This reduces redundant reallocations since a lot of engines/decoders already do this anyways, and makes it easier to add WAV decoders since the extra headers are always discarded now.
One downside of this change is some engines have edge cases freeing sounds that are still being played (eg. closing the game mid-sound), which now crashes. I tried to fix the engines I ran across, but obviously I can't test every engine using raw WAVs, so I'd appreciate extra testing (and engine fixes) for this.

AUDIO: Use SeekableSubReadStream instead of reallocating streams

---

.gitattributes
configure
engines.awk

Translated most of the engine work from shell to awk.
Tested that the output is the same (except the order of created files).
Time comparison
---------------
Windows:
* Little gnomes - 99s -> 0.3s
* Creating - 68s -> 1s
* Total - 205s -> 35s
Linux:
* Little gnomes - 3s -> 0.03s
* Creating - 2s -> 0.11s
* Total - 8s -> 3.8s

CONFIGURE: Speed up and get rid of little gnomes

---

Makefile.common

Running `make -r` used `.o` (with no base name) for the compilation output of `base/version.o`.

MAKEFILE: Fix build without implicit rules

---

Makefile.common

When adding/removing an engine, config.mk is changed, and this effectively
passes different -DENABLE_* command-line arguments to the compiler.
If base/plugins is not recompiled, the list of active plugins is not updated.
Before b813d1ca0d6f7dbb09deeaebb687d28c2bcf58e9 config.h was created every
time configure was executed, so everything was recompiled anyway. Now we need
to have an explicit dependency.
The only source file that's supposed to be affected is base/plugins, so there
is no reason to rebuild everything. Just add this dependency to update the
plugin list.

MAKEFILE: Add a dependency for rebuilding base/plugins when config is changed

---

engines/agi/global.cpp

The typo caused music and sound effects volumes values to be swapped for PCjr (but not to MIDI, because `sound_midi` doesn't call MixerImpl::getVolumeForSoundType)

AGI: fixed typo in music volume settings

---

backends/platform/ios7/ios7_osys_main.cpp
base/main.cpp
engines/ags/ags.cpp
engines/ags/plugins/ags_galaxy_steam/ags_galaxy_steam.cpp
engines/cine/metaengine.cpp
engines/cine/saveload.cpp
engines/dialogs.cpp
engines/engine.cpp
engines/engine.h
engines/hadesch/hadesch.cpp
engines/petka/interfaces/save_load.cpp
engines/twine/menu/menuoptions.cpp
engines/twine/twine.cpp
engines/ultima/nuvie/files/nuvie_io_file.cpp
engines/ultima/ultima8/ultima8.cpp
engines/wintermute/ext/wme_galaxy.cpp
engines/wintermute/ext/wme_steam.cpp
gui/launcher.cpp
gui/saveload-dialog.cpp
gui/saveload-dialog.h
gui/saveload.cpp
gui/saveload.h

This fixes [Trac #12016](https://bugs.scummvm.org/ticket/12016) by having the engine hold a pointer to the MetaEngine instance, rather than looking it up again when it's needed.

BASE: Avoid calling PluginMan.getEngineFromMetaEngine where possible

---

engines/grim/detection.cpp

Following #2880
This adds detection entry for hebrew fan translation
Also, fixes off-by-1 error for the string reversal
Thanks

GRIM: Add hebrew fan translation detection entry

---

backends/platform/sdl/win32/win32.mk

When an engine is added or removed, it affects the embedded resources in
scummvm.rc, so config.mk is required.
Apart from that, list all the files it uses and set them as dependencies,
so if a file changes, the resource file will be rebuilt.

MAKEFILE: Add dependencies for scummvm.rc

---

backends/graphics/opengl/opengl-graphics.h
backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/openglsdl/openglsdl-graphics.h

This reverts commit 0f118d0210d1dc1d4e4174fd72179de82b263ed8.
Instead it attempt to fix the `hiding overloaded virtual function` warning in a cleaner way.

OpenGL: Fix warning for hidden overladed virtual saveScreenshot() function

---

audio/softsynth/fluidsynth.cpp

This fixes compilation and removes warnings about deprecated versions.

Make use of Fluidsynth 2.2.0 API when available

---

gui/widget.cpp

Since different engines may have different number of options we have to recreate "Edit Game" dialog layout every time and avoid caching.

GUI: Fix caching of Edit Game dialog layout

---

engines/scumm/script_v6.cpp

There's this rare script bug in Backyard Baseball 2001 and 2003 where bunting a foul ball as Pete Wheeler may softlock the game if the ball goes far left or right field.  This is because the actor animation variable never sets to 1 under this condition due the game thinks he has hit a good ball while in reality he didn't.  You can see a couple instances of this occurring [here in Baseball 2003](https://www.reddit.com/r/BackyardBaseball/comments/m8xkrs/when_its_stuck_on_this/), and [here in Baseball 2001](https://clips.twitch.tv/HonorableCarefulGoatSeemsGood-hVQ4yDighlEYHqYS).  Unsure if this is a ScummVM specific issue somewhere or not, but I've heard from some people this has occurred in the original engine as well.  The original Backyard Baseball 1997 release does not seem to have this …

SCUMM: Add workaround for Pete Wheeler softlock

---

backends/cloud/cloudmanager.cpp
backends/cloud/googledrive/googledrivestorage.cpp
backends/cloud/googledrive/googledriveuploadrequest.cpp

`uint64` is unsigned long on linux64 (first match in `configure:find_type_with_size`), so the format should be `lu`, but this is incompatible with Win64, so just cast to make it portable and warning-clean.
Amends commit 1496ad6bb5.

CLOUD: Fix compiler warnings on linux64

---

engines/ags/ags.cpp
engines/ags/music.cpp
engines/ags/music.h
engines/ags/plugins/ags_flashlight/ags_flashlight.cpp
engines/ags/shared/util/filestream.cpp
engines/ags/shared/util/filestream.h

AGS: Remove unused private members and globals

---

engines/tsage/blue_force/blueforce_dialogs.cpp
engines/tsage/blue_force/blueforce_logic.cpp
engines/tsage/blue_force/blueforce_scenes0.cpp
engines/tsage/blue_force/blueforce_scenes1.cpp
engines/tsage/core.cpp
engines/tsage/detection_tables.h
engines/tsage/metaengine.cpp
engines/tsage/scenes.cpp
engines/tsage/staticres.cpp
engines/tsage/staticres.h
engines/tsage/tsage.h

This change has two parts
- make the ScummVM TSAGE engine not crash with the Spanish version of Blue Force.
- translate all remaining bits (taken from Spanish BLUE.EXE).
More info provided in the individual commits.

TSAGE: Support Blue Force Spanish

---

engines/tsage/blue_force/blueforce_dialogs.cpp
engines/tsage/blue_force/blueforce_logic.cpp
engines/tsage/ringworld/ringworld_dialogs.cpp
engines/tsage/ringworld/ringworld_logic.cpp
engines/tsage/ringworld/ringworld_logic.h
engines/tsage/ringworld/ringworld_scenes1.cpp
engines/tsage/ringworld/ringworld_scenes10.cpp
engines/tsage/ringworld/ringworld_scenes2.cpp
engines/tsage/ringworld/ringworld_scenes5.cpp
engines/tsage/ringworld/ringworld_scenes8.cpp
engines/tsage/scenes.cpp
engines/tsage/staticres.cpp
engines/tsage/staticres.h

Text was extracted from the Spanish RING.EXE using a hex editor.
These include the options menu, dialogs, and inventory items.
Now the game plays fully in Spanish, like the original version.
Note that some menu options were originally translated in different
ways for Ringworld and Blue Force (e.g. Save -> Salvar/Guardar).

TSAGE: Include and handle Ringworld Spanish messages

---

backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/opengl-graphics.h
backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/openglsdl/openglsdl-graphics.h
backends/graphics/psp2sdl/psp2sdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.h
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h
backends/graphics/windowed.h
backends/platform/android/graphics.cpp

The old code from PR #1895 isn't needed any more, and removing it should simplify the code and resolves some issues with scaling the cursor.

Revert "OPENGL: Implement high DPI support on Android (#1895)"

---

backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/openglsdl/openglsdl-graphics.h
backends/graphics/sdl/sdl-graphics.h

This tries to correct handling coordinates from mouse events and window events on high-DPI systems:
- on some platforms (eg. Windows), mouse and window events need to be unscaled 
- on some platforms (eg. OSX), mouse and window events need to be scaled by the DPI
We try to determine this by comparing the WindowSize and DrawableSize and scaling appropriately.
Only tested on Windows, appreciate testing and feedback from other systems.

BACKENDS: Fix incorrect cursor scaling on high-DPI Windows

---

devtools/create_access/create_access_dat.cpp
engines/access/resources.cpp

I assume we want to use stable language codes in access/resources.cpp
even if language.h keeps changing, so I've used language code "23" for
ES_ESP since this was the enum value in language.h the last time
access.dat was generated.
Note: we still need access.dat to be regenerated for the game to work,
but create_access should now be able to extract the needed info
from the Spanish version of AMAZON.EXE and the game should run fine
afterwards.

ACCESS: Support Amazon Spanish in access.dat R/W

---

engines/nancy/action/actionmanager.cpp
engines/nancy/action/actionrecord.h

When compiling the nancy engine I get the following warnings:
```
In file included from engines/nancy/action/primaryvideo.cpp:29:
./engines/nancy/action/primaryvideo.h:41:29: warning: declaration shadows a variable in namespace
'Nancy::Action' [-Wshadow]
enum ConditionType : byte { kNone = 0, kEventFlags = 1, kInventory = 2 };
^
./engines/nancy/action/actionrecord.h:41:2: note: previous declaration is here
kNone               = 0,
^
In file included from engines/nancy/action/primaryvideo.cpp:29:
./engines/nancy/action/primaryvideo.h:41:57: warning: declaration shadows a variable in namespace
'Nancy::Action' [-Wshadow]
enum ConditionType : byte { kNone = 0, kEventFlags = 1, kInventory = 2 };
^
./engines/nancy/action/actionrecord.h:42:2: note: previous declaration is here
kInventory …
```

NANCY: Silence variable shadowing warnings

---

engines/saga/script.cpp

At Alamma's cottage, the wrong object's hitzone is selected when using it with an item (cottage door's 8295 vs door's 24578). In order to make it more easy to progress, we reset the objectId to ID_NOTHING in this case.
-This fixes [Ticket #10369](https://bugs.scummvm.org/ticket/10369)

SAGA: Fix a hitzone detection bug in ITE

---

audio/decoders/raw.cpp
audio/decoders/raw.h
audio/decoders/wave.cpp

Some AGS games use 24 bit WAVE audio. Currently this does not work as our code only supports 8 and 16 bit PCM, but not 24 bit PCM. This is an attempt to implement this. Since this is my first foray into the audio code (and it includes some interesting template code), I would appreciate some review to make sure it looks OK.
This was tested with The Rail (https://www.adventuregamestudio.co.uk/site/games/game/1670-the-rail/), that uses 8, 16, and 24 bit PCM WAVE audio.

AUDIO: Add support for 24 bit PCM WAVE

---

backends/graphics/opengl/opengl-graphics.cpp

BACKENDS: Fix aspect ratio bug when switching render 
Detailed description of the bug: https://bugs.scummvm.org/ticket/12394

BACKENDS: Fix aspect ratio bug when switching render

---

engines/wintermute/achievements_tables.h
engines/wintermute/ad/ad_game.cpp
engines/wintermute/detection_tables.h
engines/wintermute/ext/scene_achievements.cpp
engines/wintermute/ext/scene_achievements_tables.h
engines/wintermute/ext/scene_hooks.h
engines/wintermute/ext/wme_steam.cpp
engines/wintermute/ext/wme_steam.h
engines/wintermute/keymapper_tables.h
engines/wintermute/module.mk

Add detection for:
* many Carol Reed versions
* "Idiot's Tale" - https://store.steampowered.com/app/810450/The_Idiots_Tale
* "I Must Kill...: Fresh Meat" demo
* Polish versions of Dead City & Mental Repairs
Add a hook for ChangeScene to grant achievements - useful for non-steam versions of Carol Reed 10-11
Add keyboard walking feature for Carol Reed 13-16
Remove GF_3D flag from "J.U.L.I.A.: Among the Stars" (was mistakenly marked)

WINTERMUTE: Add detection and improve Carol Reed support

---

engines/advancedDetector.cpp
engines/advancedDetector.h
engines/ags/detection.h

The advanced detector does not allow adding unknown variants and running them. In the AGS engine however were we have additional checks on the unknown variants to ensure they are AGS games, nothing prevent us in principle to run those games. This pull request allows that.
I am proposing this change as a pull request in case there this change has an impact that I have not foreseen. But since it doesn't change the default behaviour, I think it should be safe.

Allow engines using the advanced detector to run unknown variants

---

configure

This is based on [this Debian patch](https://salsa.debian.org/games-team/scummvm/-/blob/master/debian/patches/dont-use-gold.patch), since apparently gold crashes on i386. Some minor cleanup has also been made to the LLD code.

CONFIGURE: Allow linking with GOLD to be disabled

---

doc/docportal/advanced_topics/configuration_file.rst

The configuration key "iconpath" is actually "iconspath"
Also, there's more to explain about this feature, but it would probably bloat the details table cell for a minor feature that probably not many people use. 
Anyway, for reference the code seems to accept naming formats of:
* (gameid).(extension), where gameid is as it appears in scummvm.ini for the game entry
* (engineid)-(gameid).(extension), where engineid and gameid are as they appear in scummvm.ini for the game entry
* (gameTarget).(extension), where gameTarget is the "tag" as it appears in scummvm.ini for this game's entry section, which is also what is exposed to the ScummVM launcher GUI as "ID". (Our documentation currently actually points to this one).
If the _iconspath_ is empty or missing, the code will also look for an …

DOCS: Fix misprint for iconspath

---

test/cxxtest/cxxtest/ValueTraits.h

```
../scummvm/test/cxxtest/cxxtest/ValueTraits.h:120:52: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
120 |         ValueTraits( CXXTEST_NEW_CLASS n ) : _old( (CXXTEST_OLD_CLASS)n ) {} \
|                                                    ^~~~~~~~~~~~~~~~~~~~
```

TESTS: Fix GCC warnings

---

configure

When a subengine is added, its parent engine needs to be rebuilt.
A real solution will be to create a make-dependency file for each engine,
and touch it when its subengines change, but for now we'll just rebuild
everything.

CONFIGURE: Force full rebuild on configuration change

---

common/taskbar.h

When an icon for game ID is not found, use the engine icon instead. This provides a fallback so that every game doesn't need an icon.
When discussing this with @SupSuper, I was hoping that this could be extended to the icons used by Discord RPC. Unfortunately we have no way of knowing which icons are stored as assets on the Discord dev portal, and so couldn't check whether a game ID is present there or not.

COMMON: Fall back to engine icon in taskbar

---

engines/scumm/saveload.cpp
engines/scumm/script_v2.cpp
engines/scumm/script_v5.cpp
engines/scumm/script_v6.cpp
engines/scumm/script_v8.cpp
engines/scumm/verbs.cpp
engines/scumm/verbs.h

`curRect.left` is assigned in the script, and it is not modified. `right` is
assigned with the screen width - original left.
This results in bad highlighting of the verbs all over the line width,
instead of being limited to the actual string.
Due to that, sometimes the selection range of the up/down arrows overlaps
with some of the verbs, and then these verbs cannot be selected.
Solve by storing the original left value, and using it as initial x
position for the string (the actual right-to-left manipulation is done in
`drawString()`), and modify the value of `curRect.left` to match the string
that was actually drawn.
This bug is similar to the one that was fixed in 58e921eb87, but the
solution that was done there for v7 and v8 cannot work here, because the
string logic is much more …

SCUMM: Fix X-range of selection for Hebrew on scumm<7

---

engines/scumm/script_v6.cpp

The original commit containing the Pete Wheeler workaround for the Baseball games (#2933) has caused a regression where batting with any other bat as Pete Wheeler would slow down his swinging animation after hitting the ball.  Whoops, This fixes the regression by adding another check to determine whether he is bunting or not.  So sorry about that.

SCUMM: Fixed regression caused by Pete Workaround

---

engines/dragons/font.cpp
engines/dragons/screen.cpp
engines/dragons/screen.h

This continues the work related to https://bugs.scummvm.org/ticket/11710 and previous PR #2784.
With this, Blazing Dragons visuals on big-endian systems are almost identical to those on little-endian systems. The only remaining visual difference I still see is in the copyright menu, where the left creature has some weird pixels around it (I don't know how to fix that part, but everything else seems to be improved).
(In `font.cpp`, I had to revert the `WRITE_SCREEN` change from my previous PR in order to have proper text rendering.)
Note that `void Screen::drawScaledSprite()` was the only place where an uint16 was used for a read. Changing it to an int16 like the rest doesn't seem to cause a regression.
I haven't tested it back on a little-endian system, yet.

DRAGONS: More visual fixes for big-endian systems

---

backends/platform/sdl/sdl-sys.h
common/forbidden.h

This should make it easier to identify issues where forbidden symbols are used in system headers, since this will ensure that the relevant symbol is always included in the error message.

COMMON: Improve debugging of forbidden symbol issues

---

engines/wintermute/base/base_game.cpp

Fixes part of https://bugs.scummvm.org/ticket/12377 issue.
BaseGame::initialize2() is synced with similar functions from #2973

WINTERMUTE: Sync render creation code with other engines

---

devtools/create_lure/create_lure_dat.cpp

Appear in travis build.
```
create_lure_dat.cpp:1491:1: error: narrowing conversion of `'\37777777665'` from `char` to `unsigned char` inside { } [-Wnarrowing]
```

DEVTOOLS: Fix GCC warnings

---

engines/scumm/imuse/imuse_player.cpp

The size in snprintf includes the final null character, so here
3 bytes are not enough to store a space, 2 digits and the null
character.
The compiler complained and the output used to display 1 digit
instead of 2, for each byte.
Extend this size from 3 to 4 in the snprintf call.

SCUMM: Fix format-truncation warning in IMUSE player

---

engines/ags/achievements_tables.h

2 games were described twice at achievements_tables.h: "atotkdeluxe" and "theterribleoldman"

AGS: Remove duplicate achievements entries

---

backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.h
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h
backends/platform/sdl/sdl-window.cpp
backends/platform/sdl/sdl-window.h

Currently most SDL2 calls are hardcoded to displayIndex 0 (the primary monitor), so if the ScummVM window is moved to a separate monitor, the results will be incorrect. This attempts to fix this by passing the window display index whenever possible.
This solves the most common bug of resizing / fullscreening on a separate monitor using the wrong resolution, though more work is still necessary to fully support multiple monitors (such as refreshing cached display values when the window is moved).

SDL: Improve multi-monitor support by replacing display 0 with window display

---

engines/scumm/scumm.cpp
engines/scumm/scumm.h

Autosave was centralized in 30d34fa63d1f5ccf37dfd9c80b0009c4115e78f2, but
SCUMM engine was left behind.
Bugreport #12026

SCUMM: Fix autosave

---

backends/dialogs/morphos/morphos-dialogs.cpp
backends/fs/morphos/morphos-fs.cpp

- remove utf8toLocal and use internal encode
- save only path (drawer) in browser_lastpath

MorphOS: cleanup code

---

engines/tinsel/tinsel.cpp

When testing the original V0 Floppy Demo of Disworld (`dw-dos-floppy-demo-en.zip`) on a big-endian PowerPC machine, the game would immediately trigger `assert(numPolys <= MAX_POLY)` in `MaxPolygons()`.
It appears that numPolygons was left uninitialized, and so it was set to a big value which would trigger this assertion.
Looking at the changes done in commit 24b77f1, I think the original intent was to use the `(cptr != NULL) ? READ_32(cptr) : 0` idiom, like the rest around it.
Tested with the various available Discworld1 demos on a big-endian system.

TINSEL: numPolygons fixes for big-endian systems

---

backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
base/main.cpp
common/module.mk
common/system.cpp
common/system.h
common/text-to-speech.cpp
common/text-to-speech.h
engines/engine.cpp
engines/lure/surface.cpp
engines/mads/dialogs.cpp
engines/mortevielle/dialogs.cpp
engines/mortevielle/sound.cpp
engines/mortevielle/sound.h
engines/sherlock/scalpel/scalpel_user_interface.cpp
engines/sherlock/talk.cpp
engines/twine/audio/sound.cpp
engines/twine/text.cpp
gui/ThemeEngine.cpp
gui/Tooltip.cpp
gui/gui-manager.cpp
gui/options.cpp
gui/widget.cpp
gui/widgets/popup.cpp

This removed the need for the engine authors to add scummvm compile time options checks into their engine code. 
There are however still some places where I've left the check in the engine code - this is e.g. for UI options.
OSystem now just returns a `nullptr` if there is no text to speech manager instance (because none is compiled into the binary, or the system doesn't provide support for it).

COMMON: removed USE_TTS check from engines

---

engines/tinsel/tinlib.cpp

This adds support for opcode 217. I have made the assumption that it's
voiceover, and given it an enum value to reflect that. This enables
voiceover to be played in the opening movie.

Tinsel: Discworld Noir: Support for opcode 217.

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h
backends/platform/sdl/sdl.cpp
backends/platform/sdl/sdl.h

I found leaks running scummvm built with address sanitizer.
They are easy to reproduce: just starts scummvm and exit when
the launcher appears.
```
Direct leak of 432 byte(s) in 1 object(s) allocated from:
#0 0x7f08a98daef0 in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xeaef0)
#1 0x55b41cbb76eb in SurfaceSdlGraphicsManager::supportedGraphicsModes() const backends/graphics/surfacesdl/surfacesdl-graphics.cpp:310
#2 0x55b41cbb7b6d in SurfaceSdlGraphicsManager::getSupportedGraphicsModes() const backends/graphics/surfacesdl/surfacesdl-graphics.cpp:325
#3 0x55b41a8e2886 in OSystem_SDL::setupGraphicsModes() backends/platform/sdl/sdl.cpp:904
#4 0x55b41a8e867b in OSystem_SDL::initBackend() backends/platform/sdl/sdl.cpp:290
#5 0x55b41a8f1ea5 in …
```

BACKENDS: SDL: Fix memory leak in supported graphics modes

---

gui/widget.cpp

- Found leak playing Full Throttle:
```
Direct leak of 3384 byte(s) in 3 object(s) allocated from:
#0 0x7f21b8b94d30 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xead30)
#1 0x55cedb20980e in GUI::PicButtonWidget::setGfx(Graphics::Surface const*, int, bool) gui/widget.cpp:613
#2 0x55cedb0e9241 in GUI::SaveLoadChooserGrid::updateSaves() gui/saveload-dialog.cpp:1110
#3 0x55cedb0def72 in GUI::SaveLoadChooserGrid::open() gui/saveload-dialog.cpp:913
#4 0x55cedaf2b498 in GUI::Dialog::runModal() gui/dialog.cpp:74
#5 0x55cedb0e5856 in GUI::SaveLoadChooserGrid::runIntern() gui/saveload-dialog.cpp:1051
#6 0x55cedb0aede4 in GUI::SaveLoadChooserDialog::run(Common::String const&, MetaEngine const*) gui/saveload-dialog.cpp:196
#7 0x55cedb0a495a in …
```

GUI: Fix leak of ManagedSurface in PicButtonWidget

---

graphics/managed_surface.cpp
graphics/managed_surface.h

With the commit just merged about leak from PicButtonWidget, the ManagedSurface object is freed but not its pixel buffer because _disposeAfterUse was overwritten with value NO after the allocation with copyFrom().
That causes this indirect leak of thumbnail buffers (160x100x2 bytes):
```
Indirect leak of 96000 byte(s) in 3 object(s) allocated from:
#0 0x7f21b8b93518 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe9518)
#1 0x55cedbde0908 in Graphics::Surface::create(unsigned short, unsigned short, Graphics::PixelFormat const&) graphics/surface.cpp:75
#2 0x55cedbde14dc in Graphics::Surface::copyFrom(Graphics::Surface const&) graphics/surface.cpp:96
#3 0x55cedbd82895 in Graphics::ManagedSurface::copyFrom(Graphics::Surface const&) graphics/managed_surface.cpp:218
#4 0x55cedbd7b331 in …
```

GRAPHICS: Fix leak in ManagedSurface, not forcing _disposeAfterUse to NO

---

engines/testbed/graphics.cpp
engines/testbed/graphics.h

I have noticed that Wintermute and FullPipe games are not working on PSP
port (and it looks like they never worked). This was caused by missing
ABGR8888@4 support on the backend, while some engines explicitly
requested this Pixel Format.
I have decided to add a test so that all the backends could be easily
checked for similar issues.
Surprisingly, "backends/graphics/null/null-graphics.h" holds up-to-date,
full and correct list of pixel formats requested by different engines.
There are lots of different Pixel Formats mentioned in different engines
code, but NullGraphicsManager lists all that are explicitly needed for
intGraphics(), not data reading, etc...

TESTBED: Add another PixelFormat test

---

base/plugins.cpp
engines/advancedDetector.cpp
engines/advancedDetector.h
engines/metaengine.h
gui/launcher.cpp

Define a Singleton that stores the md5 and size of files, used during mass add.
This skips the double computing of md5s during a single mass add, with the cache being cleared in subsequent mass adds.

DETECTOR: Modify getFileProperties to cache md5 results

---

gui/ThemeEngine.cpp

This fixes a regression from commit 0fc5c4c3916992691b3c8777e8ffaaf45af99ba5, although a better long term solution might be to handle conversion in `Graphics::CursorManager` instead.

GUI: Convert the cursor bitmap to the overlay format

---

common/installshield_cab.cpp
common/installshield_cab.h
engines/agos/metaengine.cpp
engines/nancy/nancy.cpp
engines/tony/tony.cpp

This PR adds support for versions 6-13 InstallShield cabinets,
which can be both single- and multi-volume (v5 multi-volume
cabinets are still not supported since I have no test cases). This is
used in some of the Nancy Drew games. The code was written
several years ago by waltervn and clone2727, but never made its
way into the main tree.
This makes some minor changes to the AGOS and Tony engines
which I am unable to test since I don't own any of the games;
I'd appreciate if someone who has The Feeble Files or one of
the Simon the Sorcerer's Puzzle Packs could test the
unextracted versions and see if there are any issues.

COMMON: Add support for multi-file InstallShield cabinets

---

engines/testbed/graphics.cpp
engines/testbed/graphics.h

There are 2 tests that features Pixel Format testing:
* pixelFormatsSupported - testing formats implemented by backend
* pixelFormatsRequired - testing formats required by engines
Original Pixel Format test was just displaying 6 colored rectangles.
This PR replaces it with displaying gradients of 7 given colors.
For pixel formats with full alpha, both vertical and horizontal gradients are visible.
For pixel formats that ignores alpha, only horizontal gradient is visible.
For pixel formats with 1-bit alpha, the part with alpha < 128 is completely transparent.
Before testing a group of formats, a sample is displayed with CLUT8 pixel format:

TESTBED: Modify Pixel Format tests to display brightness and alpha gradients

---

engines/testbed/graphics.cpp

It seems that gp2x-1 is the only platform that does not support STATIC_ASSERT(expression, "message").
Changed to STATIC_ASSERT(expression, some_very_long_message_id) to fix the compilation.

TESTBED: Fix STATIC_ASSERT expression compilation on gp2x-1

---

engines/director/channel.cpp

in this movie
./scummvm --start-movie=STAMBUL/FNCOPS warlock
cursor is not visible when it opens the chatbox
the reason is it has a very frequent switch in _wm->_activewidget
for the speed and correctness, i've add the check when we are setting castmember editable
and the problem is solved

DIRECTOR: fix the cursor blinking problem in warlock

---

common/achievements.cpp
common/achievements.h
engines/ags/plugins/ags_galaxy_steam/ags_galaxy_steam.cpp
engines/ags/plugins/ags_galaxy_steam/ags_galaxy_steam.h
engines/testbed/achievements.cpp
engines/testbed/achievements.h
engines/testbed/module.mk
engines/testbed/testbed.cpp
engines/twine/twine.cpp
engines/wintermute/ext/scene_achievements.cpp
engines/wintermute/ext/wme_galaxy.cpp
engines/wintermute/ext/wme_galaxy.h
engines/wintermute/ext/wme_steam.cpp
gui/options.cpp

I have noticed that `AchMan.setActiveDomain()` and `AchMan.setAchievement()` requires too much code the engines need to write around. 
New API is much simplier - `AchMan.setActiveDomain(<result of MetaEngine's getAchievementsInfo()>)` now additionally stores messages to be displayed on `AchMan.setAchievement(id)` calls instead of old `AchMan.setAchievement(id, message)` call.
Additional things in this review:
* TWINE had no `AchMan.setActiveDomain`, added it to `TwinEEngine::run()`
* moved AGS achievements API calls to the base class AGS2Client
See Commits list for easier reading.

ACHIEVEMENTS: Simplify the achievements API 

---

gui/saveload-dialog.cpp
gui/widgets/list.cpp

As someone who accumulates a lot of temporary saves, I push the delete key a lot to try and delete them. Now it works!
This revealed that ListWidget::scrollToCurrent() has been doing a less-than comparison that includes the sentinel value -1, causing the list to jump to to the top when there is no currently selected item, such as right after deleting a save and clearing the selection. As that's behavior I fixed in the Delete GUI button in #2628, I added a check so that scrollToCurrent() doesn't scroll when there isn't a current item. This also fixes some existing unusual scroll position resets in the save/load list. I tested the other lists and didn't detect any behavior changes.

GUI: Add delete/backspace support to save/load list

---

dists/ios7/Info.plist
dists/ios7/Info.plist.in
ports.mk

Add signing to MacOS for arm64 builds
This has not been tested but it adds CodeResources file which seem to indicate the whole bundle will be signed.
This does the same thing for iPhone even though I suppose jailbroken devices are less sensitive to the missing signature on all binaries.

MACOS/IPHONE: Sign whole bundle

---

common/achievements.cpp
common/achievements.h
engines/ags/achievements_tables.h
engines/ags/plugins/ags_galaxy_steam/ags_galaxy_steam.cpp
engines/wintermute/achievements_tables.h
engines/wintermute/ext/wme_galaxy.cpp

This PR introduces a new "[special]" section at achievements ini-files.
For Steam it's quite useless, containing the same information as the file name - `platform=steam"` and `gameid=<gameid>`.
For GOG it additionally stores clientId and clientSecret provided as a required parameters to various Galaxy plugins like AGSGalaxy & SXWMEGalaxyAPI.
Those are NOT player's personal data and are not even unique for each played - clientId and clientSecret are actually always the same for each gameid and can be looked up at gogdb.com. However, I'd prefer to keep it inside achievements file just in case.
Also switching appId for GOG games from clientId to gameId which is shorter and usable by user in links like https://www.gog.com/u/[username]/game/1469845437.

ACHIEVEMENTS: Improve GOG achivements support

---

common/achievements.cpp
common/achievements.h
devtools/steam_achievements.py
engines/ags/achievements_tables.h
engines/ags/metaengine.cpp
engines/ags/plugins/ags_galaxy_steam/ags_galaxy_steam.cpp
engines/ags/plugins/ags_galaxy_steam/ags_wadjeteye_steam.cpp
engines/dialogs.cpp
engines/testbed/achievements.cpp
engines/testbed/testsuite.cpp
engines/twine/achievements_tables.h
engines/twine/metaengine.cpp
engines/wintermute/achievements_tables.h
engines/wintermute/metaengine.cpp
gui/editgamedialog.cpp
gui/options.cpp
gui/options.h

1. AchievementsInfo is extended to contain Stats info, which are used in 2 scenarios:
i. When active domain is set in AchMan, all Stats are created with default values if they are not present in the INI-File
ii. UI tab is added to Game Options, both in the launcher and in-game options, featuring Stats names and current values
2. steam_achievements.py devtool is extended to provide Stats as well.
3. AGS achievements tables are updated to have Stats lists for game integrated with SteamAPI Stats.
4. Testbed engine is updated to have a sample stat, which is displayed as well.
\+ minor improvements at ags_galaxy_steam and achievements.cpp
Obligatory screenshots:

ACHIEVEMENTS: Improve AGS achievements support and add Statistics tab for game that are using SteamAPI Stats

---

engines/advancedDetector.cpp

This fixes a bug with PR #2997 
Currently the MD5 cache is cleared when adding new games. However, starting games uses detection as well. So starting different games with same-name files will result in a "data not found" error, as the cache won't update.
This makes sure to clear the cache before starting new games. @a-yyg mentioned in the PR clearing the cache in detectFiles was a bad idea, so I put it here instead. Feedback welcome.

DETECTION: Fix MD5 cache when starting engine

---

engines/agos/agos.h
engines/agos/window.cpp

This is an attempt at fixing a regression in The Feeble Files: Pressing the "Off" button in the Oracle interface, causes the game to crash.
This appears to have been caused by the changes surrounding Elvira/PC-98/Jp. The restoreBlock() function generates an invalid Rect. The whole function looks a bit strange: It claims to take x, y, w and h, but in reality it seems to take left, top, right and bottom. Except in one case, it is called with the parameters in the wrong order, as far as I can tell.
This needs testing, of course. At a quick glance, things seem ok, but I'd like to hear some feedback on whether or not my changes look right. Also, I don't have Elvira/PC-98/Jp to test with.

AGOS: Fix restoreBlock() regression (needs testing!)

---

backends/midi/timidity.cpp
base/commandLine.cpp
common/debug.h
common/scummsys.h
common/str.h
common/textconsole.h

Currently ScummVM uses the GCC_PRINTF annotation to validate strings in printf-like functions. This doesn't work for MSVC which has a different annotation for this, so I added it, and corrected some incorrect usages.
Sadly MSVC requires annotating the parameter, not the function, so I couldn't combine both macros into one.

MSVC: Add compiler printf validation

---

math/matrix.h

When the ```math``` folder is added to ```doc/doxygen/scummvm.doxyfile``` as an input directory, the period would cause the doxygen build to fail.

JANITORIAL: Remove extraneous period from math/matrix.h

---

engines/trecision/detection.cpp

Added the German demo to the detection table. It's working right now. No other changes needed.

TRECISION: Add Deutsch demo (#12600)

---

backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/windowed.h
doc/docportal/advanced_topics/understand_graphics.rst

The commit in this pull request add a new pixel perfect mode. This mode ensure that an integral scaling from the original game resolution is used both for the width and for the height, thus providing homogeneous pixels. Compared to the old pixel perfect stretch mode it thus differs in the way it handles the aspect ratio correction as it may stretch or squeeze the vertical direction to snap it to a multiple of the original game height. When aspect ratio correction is off, the two modes should behave in exactly the same way.
For example with DOTT, which has an original resolution of 320x200, when I use aspect ratio correction and fullscreen on my laptop (with a screen resolution of 2880x1800) I get:
- Old Pixel Perfect: Stretch (320, 200) -> (2240, 1680) with scaling x7 and x8.4
- New Pixel …

SDL: Add new pixel perfect stretch mode

---

engines/director/channel.cpp
engines/director/lingo/lingo-the.cpp
engines/director/window.cpp

The game Majestic dynamically sets the castNum to video casts and expects them to play directly. Videos were also stopped erroneously. Video stoppage is assumed when movieRate is 0. The comment indicated that it was probably broken for D4.
The corresponding lingo code is: *anim is a cast label*
```
set the castNum of sprite 48 to cast(anim)
updateStage()
set the movieRate of sprite 48 to 1
repeat while the movieRate of sprite 48
updateStage()
end repeat
```

DIRECTOR: allow setting of video casts to castNum

---

common/zlib.cpp

```
==1313424== Conditional jump or move depends on uninitialised value(s)
==1313424==    at 0x682225: Common::wrapCompressedReadStream(Common::SeekableReadStream*, unsigned int) (zlib.cpp:498)
==1313424==    by 0x46CDB9: DefaultSaveFileManager::openForLoading(Common::String const&) (default-saves.cpp:134)
==1313424==    by 0x68334D: Common::PlaybackFile::openRead(Common::String const&) (recorderfile.cpp:74)
==1313424==    by 0x444558: GUI::RecorderDialog::updateList() (recorderdialog.cpp:206)
==1313424==    by 0x4446BD: GUI::RecorderDialog::runModal(Common::String&) (recorderdialog.cpp:218)
==1313424==    by 0x3DF0E5: GUI::LauncherDialog::recordGame(int) (launcher.cpp:461)
==1313424==    by 0x3E0397: GUI::LauncherDialog::handleCommand(GUI::CommandSender*, unsigned int, unsigned int) …
```

COMMON: fixed invalid read in zlib read stream

---

engines/metaengine.cpp

Currently for an engine to support custom savegame formats it needs to overload both `MetaEngine::listSaves` and `MetaEngine::querySaveMetaInfos`.
This simplifies the process by just having the default `listSaves` call `querySaveMetaInfos`, since the functionality is identical.

COMMON: Simplify default MetaEngine::listSaves

---

doc/docportal/use_scummvm/game_files.rst

Previously, these would display like
>  A list of required data files for each game is found on the *wiki entry \<https://wiki.scummvm.org/index.php?title=Category:Supported_Games>* for that game.
(i.e. in italics, with literal angle brackets and the full URL displayed inline.)

DOCS: Fix Category:Supported_Games links

---

engines/startrek/console.cpp

Fix `format-security` warnings emitted by gcc due to a missing format string literal in two calls to `debug`.
These warnings make it impossible to build the `scummvm-git` package in Arch Linux AUR since a few days ago, when `Werror=format-security` was added to the default `CFLAGS`.

STARTREK: Fix format-security warnings

---

engines/ags/module.mk
engines/ags/plugins/ags_agi/ags_agi.cpp
engines/ags/plugins/ags_agi/ags_agi.h
engines/ags/plugins/ags_fire/ags_fire.cpp
engines/ags/plugins/ags_fire/ags_fire.h
engines/ags/plugins/plugin_base.cpp

AGS_Fire: Doesn't do anything, but allows games using plasma fire effects to load
and run.
All methods return 0
A sample game using this plugin is Maniac Mansion Mania 46.
AGS_AGI: Allows games who use AGI lowres effects to load and run.
Games using scaling mode 0 will be squashed on the screen, but others
should be playable without the screen effect.
Sample working games: Gladiator Quest, The Secret of Hutton Grammar School

AGS: Add ags_fire and ags_agi plugin stubs (AGS_Fire.dll + ags_agi.dll)

---

engines/advancedDetector.cpp
engines/advancedDetector.h
engines/agi/detection.cpp
engines/ags/detection.cpp
engines/ags/detection.h
engines/asylum/detection.cpp
engines/cge/detection.cpp
engines/cge2/detection.cpp
engines/cryomni3d/detection.cpp
engines/director/detection.cpp
engines/director/detection_tables.h
engines/gob/detection/detection.cpp
engines/made/detection.cpp
engines/mohawk/detection.cpp
engines/queen/detection.cpp
engines/sci/detection.cpp
engines/sci/metaengine.cpp
engines/sludge/detection.cpp
engines/tinsel/detection.cpp
engines/toon/detection.cpp
engines/touche/detection.cpp
engines/tucker/detection.cpp
engines/wintermute/detection.cpp
engines/wintermute/metaengine.cpp

trello card which describe the task https://trello.com/c/jpwJCfZA/332-add-target-name-to-custom-detection
detect custom targets like Director Dictionary.
we need to add some info to those custom targets to get the correct description and version number.

DIRECTOR: add custom target detection to director

---

engines/wintermute/keymapper_tables.h

Game specific keymaps take priority over the global keymaps, which means that it wasn't possible to open the Global Main Menu with the default mappings.

WINTERMUTE: Disable conflicting keymap in Alpha Polaris

---

engines/wintermute/base/base_sub_frame.cpp
engines/wintermute/base/font/base_font_truetype.cpp
engines/wintermute/base/gfx/base_surface.h
engines/wintermute/base/gfx/opengl/base_surface_opengl3d.cpp
engines/wintermute/base/gfx/opengl/base_surface_opengl3d.h
engines/wintermute/base/gfx/osystem/base_render_osystem.cpp
engines/wintermute/base/gfx/osystem/base_surface_osystem.cpp
engines/wintermute/base/gfx/osystem/base_surface_osystem.h
engines/wintermute/base/gfx/osystem/render_ticket.cpp
engines/wintermute/base/gfx/osystem/render_ticket.h

This fixes "WME: Transparent render regression" https://bugs.scummvm.org/ticket/12641
Regression appeared when Transparent Surface internal pixel format was changed - WME had no translation ad assumed that number in script files are the same that in Transparent Surface.
Fix involved some refactoring:
* Minimized using headers at 51fe011
* Removed unused internal method displayZoom at f6e99c7
* Merged internal methods displayTrans and displayTransOffset at 7022a4b
* Moved Graphics::TransformStruct usage to /gfx/ (so that non-gfx code would not require color translation) at 40527cc
* And finally, translated color pixel format at base_surface_osystem at 8715e1c
Before fix:
After fix:

WINTERMUTE: Translate color pixel format at base_surface_osystem from WME to TS format

---

backends/graphics/opengl/context.cpp
backends/graphics/opengl/opengl-defs.h
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/opengl-sys.h
backends/graphics/opengl/texture.cpp
backends/graphics/opengl/texture.h

As part of this PR, `FakeTexture` has been extended to handle converting from any pixel format, not just RGB555 and RGBA8888, which is potentially useful for OpenGL ES as well. None of the 3D games were adapted to support this. Testing was done on Windows 98 SE with the built-in GDI Generic renderer.

BACKENDS: Add support for OpenGL 1.1 contexts

---

common/unicode-bidi.cpp
common/unicode-bidi.h
engines/wintermute/base/font/base_font_truetype.cpp

Some BiDI games require providing exact base paragraph direction for a string.
For example, some Wintermute games are storing BiDi strings as strings that are only displayed correctly with in LTR.
There are 2 possible techniques to fix this - manually adding RTL/LTR Unicode Marks, or using different base paragraph directions.
It seems that current font renderer actually displays "invisible" Unicode Marks, so I selected another way.
This PR adds optional `BiDiParagraph dir = BIDI_PAR_ON` parameter to BiDi constructors and helpers.
Original behavious is provided by default values, desired WME behaviour is provided by other values.
P.S. Results of some experiments with Persian game that is NOT using RTL paragraph direction:

COMMON: Introduce BiDi base paragraph directions

---

audio/mt32gm.h

While looking into why Lure of the Temptress takes so long to start with MT-32 audio (turns out that it's because it is setting up a lot of custom sounds?), I noticed what to me looks like a missing mutex lock in MidiDriver_MT32GM::isReady().
Lure of the Temptress calls isRead() to see if the driver has finished processing all the SysEx data. This checks if the queue is empty, but it does so without waiting for the mutex to unlock. Doesn't that mean the queue can be accessed simultaneously from two different threads?
Of course, such problems are notoriously hard to debug. I added some debug() calls, and it _looked_ like it happened a couple of times... assuming I can count on such debug messages to be printed in the correct order.
I tried asking around, but there was no one there who …

RFC: AUDIO: Add missing (?) mutex locking to MidiDriver_MT32GM::isReady()

---

backends/events/ds/ds-events.cpp
backends/mixer/maxmod/maxmod-mixer.cpp
backends/mixer/maxmod/maxmod-mixer.h
backends/platform/ds/osystem_ds.cpp
engines/bbvs/minigames/bbloogie.cpp

Running the mixer callback from a timer interrupt is proving to be problematic. This probably isn't the best way to approach this, and introduces stuttering with some games, including FOTAQ and ITE, but it does fix [Trac #12343](https://bugs.scummvm.org/ticket/12343) and [Trac #12344](https://bugs.scummvm.org/ticket/12344).

DS: Update the MaxMod callback manually

---

gui/Tooltip.cpp
gui/dialog.cpp
gui/dialog.h
gui/gui-manager.cpp
gui/gui-manager.h
gui/widget.h

This PR is a more proper fix to the issue that my previous (now closed) PRs were addressing:
(https://github.com/scummvm/scummvm/pull/3055, https://github.com/scummvm/scummvm/pull/3057)
The tooltip will show only if mouse cursor was moved but not on a hovered focused editText field
Changes and implications in this commit:
- Fix _lastMousePosition coordinates and time being changed upon giving focus to the tooltip. They now will not (specifically for "focusing" on a Tooltip).
- Check for mouse cursor movement first in the decision for showing the tooltip, then check if sufficient time for mouse resting position has passed (kTooltipDelay).
- Prevent showing a tooltip for a widget if it is an editable field (editText) and has both mouse hovering above it and the current focus. This is so …

GUI: Fix tooltip behavior to be less disruptive

---

engines/director/castmember.cpp
engines/director/castmember.h
engines/director/channel.cpp
engines/director/channel.h
engines/director/director.cpp
engines/director/director.h
engines/director/events.cpp
engines/director/lingo/lingo-builtins.cpp
engines/director/lingo/lingo-code.cpp
engines/director/lingo/lingo-object.cpp
engines/director/lingo/lingo-the.cpp
engines/director/lingo/lingo-the.h
engines/director/movie.cpp
engines/director/movie.h
engines/director/score.cpp
engines/director/sprite.cpp
engines/director/window.cpp
graphics/macgui/macbutton.cpp
graphics/macgui/macbutton.h
graphics/macgui/macfontmanager.cpp
graphics/macgui/macfontmanager.h
graphics/macgui/mactext.cpp
graphics/macgui/mactext.h
graphics/macgui/macwindowmanager.cpp
graphics/macgui/macwindowmanager.h

add checkBoxType for macbutton, implement the checkBoxType for lingo.
fix hilite state for button castmember.
modify event handling to make director behave more like the original one.
drawing on _screen of wm instead of drawing directly on screen. 
fix zoombox of apartment
since the Beam Cursor for macgui will get conflict when we set the cursor type explictly, i added a check for whether the cursor type is modified manually.
and the cursor type is not managed well when we are pop the cursor. fortunately, we will only use one level for macgui, so we always get the default one (kMacCursorArrow) when we are popping up the cursor. Thus, i restore the cursor type whenever we pop the cursor. And this will fix Apartment/User Interface/cursor. 
add plainBytesMode for mactext to deal with the …

DIRECTOR: Apartment/User Interface fix

---

common/base-str.cpp

There is a mistake in current `contains()` implementation - it does not backtrack after partial match, which causing wrong results.
For example, with current implementation word "Russian" contains "ssian", but does not contain "si".
This PR fixes this, however it proposes the simpliest algorithm possible.
Do we need something more clever and efficient here?

COMMON: Fix BASESTRING::contains()

---

engines/parallaction/parser_br.cpp

The command version of IFCHAR was skipping the commands for the current character, instead of those for the other characters. After this change it behaves like the location version of IFCHAR.
The IFCHAR command appears for the first time in BRA part 3.

PARALLACTION: make IFCHAR command skip other characters' commands

---

audio/mixer.h
audio/mixer_intern.h
engines/scumm/players/player_ad.cpp
engines/scumm/players/player_ad.h
engines/scumm/scumm.cpp

This experiment was prompted by https://bugs.scummvm.org/ticket/12649 but also https://bugs.scummvm.org/ticket/12617
It seems that it's quite easy to accidentally cause deadlocks in various music players, and one of the causes seem to be that the mixer and music player tend to have one mutex each. So would it be safer if the music player had access to the mixer's mutex? This is a proof-of-concept branch where I've added a mutex() method to the Mixer to get its mutex, and then use that in the Player_AD music player.
Is this a good idea or not? It would - at least in theory - apply to a lot of other music players, of course.

RFC: Allowing music players to use the Mixer mutex

---

engines/tinsel/detection_tables.h
engines/tinsel/tinsel.cpp

Follow up on: https://bugs.scummvm.org/ticket/11368
Adds detection for German Playstation version.
Also corrects detection of Japanese Playstation version.
getSampleIndex and getSampleFile in tinsel.cpp now fallback to ENGLISH files if they fail to find (e.g.) GERMAN.IDX.
This was an easy way to add support for the PSX German CD, without breaking the German DOS CD, Japanese PSX CD etc.
The German PSX version should be as compatible as the English PSX version.
The Japanese PSX version subtitles are not supported, and cause ScummVM to crash when you first try to hover over an object. However, you can view the intro cutscene, and hear the audio.
__
_Edit: I only marked as draft as this is my first submission, the code should be ready as is._

TINSEL: Add detection for Discworld 1 PSX Ger/Jap PSX versions

---

audio/soundfont/sf2file.cpp
audio/soundfont/vgminstrset.h
audio/soundfont/vgmitem.cpp
audio/soundfont/vgmsamp.h

WARNING: Can't find following headers in User or System Include Paths "vgmitem.h" "sf2file.h" "common.h" "vgmitem.h" "common.h"

AUDIO: SOUNDFONT: Fix warnings for header search failure.

---

common/lua/lauxlib.h
common/lua/lua.h
common/lua/lualib.h

WARNING: Can't find following headers in User or System Include Paths "luaconf.h" "lua.h" "lua.h"

COMMON: LUA: Fix warnings for header search failure.

---

engines/wintermute/debugger/breakpoint.cpp
engines/wintermute/debugger/debugger_controller.h
engines/wintermute/debugger/listing.cpp
engines/wintermute/debugger/listing_provider.h
engines/wintermute/debugger/listing_providers/basic_source_listing_provider.cpp
engines/wintermute/debugger/listing_providers/basic_source_listing_provider.h
engines/wintermute/debugger/listing_providers/cached_source_listing_provider.cpp
engines/wintermute/debugger/listing_providers/cached_source_listing_provider.h
engines/wintermute/debugger/script_monitor.cpp
engines/wintermute/debugger/watch.cpp

WARNING: Can't find following headers in User or System Include Paths
"listing.h" "script_monitor.h" "listing.h" etc

WINTERMUTE: Fix many warnings for header search failure.

---

gui/widgets/scrollcontainer.h

WARNING: Can't find following headers in User or System Include Paths "scrollbar.h"

GIU: Fix warnings for header search failure.

---

graphics/tinygl/zgl.h

WARNING: Can't find following headers in User or System Include Paths "opinfo.h"

GRAPHICS: Fix warnings for header search failure.

---

engines/toltecs/script.cpp

engines/toltecs/script.cpp:527:10: warning: array subscript is above array bounds [-Warray-bounds]
warning("Getting unimplemented game variable %s (%d)", varNames[variable], variable);
Logging print garbage because array varNames[] has 22 elements.

TOLTECS: Fix warnings for subscript is above array bounds.

---

engines/icb/common/px_array.h
engines/icb/common/px_walkarea_integer.h

Get rid from legacy "typedef struct ..." too.

ICB: Fix compilation failure due usage C++ header cstring.

---

engines/zvision/graphics/render_manager.h

WARNING: Can't find following headers in User or System Include Paths "graphics_effect.h"

ZVISION: Fix warnings for header search failure.

---

engines/mutationofjb/tasks/taskmanager.h

WARNING: Can't find following headers in User or System Include Paths "task.h"

MUTATIONOFJB: Fix warnings for header search failure.

---

engines/wintermute/base/gfx/osystem/base_render_osystem.cpp
engines/wintermute/wintermute.cpp

I have noticed, that for 2D games graphics initialization was done twice - at WintermuteEngine::run() and BaseRenderOSystem::initRenderer(int width, int height, bool windowed).
The first call looks unnecessary, let's remove it.
Probably, this would fix https://bugs.scummvm.org/ticket/11160, since second call seems to be ineffective when this first one is called with different screen dimentions.

WINTERMUTE: Init screenmode once

---

engines/parallaction/callables_ns.cpp
engines/parallaction/exec_br.cpp
engines/parallaction/inventory.cpp
engines/parallaction/inventory.h
engines/parallaction/parallaction.h
engines/parallaction/parallaction_br.cpp

The SWAP command switches control from the playing character to another one onscreen (the 'current' character becomes an NPC).
Limitations:
- the mouse cursor is not switched, as the engine has no such capability yet
- the playing character's follower is not switched, as I'd need to reach a place where the feature is used first

PARALLACTION: implement SWAP command for BRA

---

engines/sci/resource/resource_patcher.cpp

Before build symbian build system process every source file with prehistoric preprocessor.
I was unable to replace it with a modern version from gcc, since there are special specific commands. There is no description of the commands.

SCI: Fix Symbian compilation.

---

engines/parallaction/exec_br.cpp
engines/parallaction/objects.cpp
engines/parallaction/objects.h
engines/parallaction/parser_br.cpp

This PR implements the whole GIVE command, which is used to transfer inventory items among the 3 BRA playable characters.
I haven't verified it in practice, but this change should make PART 3 completable.

PARALLACTION: implement GIVE command for BRA 

---

common/achievements.cpp

`common/achievements.cpp` would fail to compile without this, in a `--disable-translation` build.

ACHIEVEMENTS: Fix compilation when translations are disabled

---

backends/audiocd/win32/win32-audiocd.cpp
backends/fs/stdiostream.cpp
backends/fs/windows/windows-fs.cpp
backends/fs/windows/windows-fs.h
backends/midi/windows.cpp
backends/platform/sdl/win32/win32-main.cpp
backends/platform/sdl/win32/win32.cpp
backends/platform/sdl/win32/win32_wrapper.cpp
backends/platform/sdl/win32/win32_wrapper.h
backends/plugins/win32/win32-provider.cpp
backends/saves/windows/windows-saves.cpp
backends/taskbar/win32/win32-taskbar.cpp
backends/text-to-speech/windows/windows-text-to-speech.cpp
configure
devtools/create_project/create_project.cpp
devtools/create_project/create_project.h
devtools/create_project/msbuild.cpp
engines/engine.cpp

This PR adds the ability to configure Windows builds with UNICODE (and _UNICODE) defined. It keeps existing behavior when they are not defined. It does not change default configurations. The idea is that this is safe to merge, `--enable-windows-unicode` can be tested for a while, and then eventually become the default.
Windows builds currently can't handle paths with most unicode characters because we always use the Windows ANSI API. On NT-based Windowses, that means strings are converted to and from the native wide-character API using CP_ACP. This works on some characters but it's a lossy conversion that depends on machine settings. A path that gets returned by Windows might not work when ScummVM passes it back to open a file or list a directory. Games can't be loaded if a path contains …

WIN32: Enable building with UNICODE

---

engines/cine/detection_tables.h
engines/director/detection_paths.h
engines/director/detection_tables.h

Adds 92 new gameIDs and 205 new md5 entries.
See individual commits for more detail on the contents of these entries.
I made a small change to detection in CINE engine. The `os-demo-amiga-gb` entry used the filename `demo`, which was generic enough that it was constantly being matched against Mac demos in Director engine. I adjusted this so that the filename is in line with the OS DOS demo (with a different md5).

DIRECTOR: Add new detection entries

---

engines/wintermute/keymapper_tables.h

Unlike Carol Reed series and Corrosion games, Rhiannon has an Map/Help/Notes bar at the bottom, and no Walk Back feature. So, adding only 3 extra controls for now.

WINTERMUTE: Allow keyboard walk at Rhiannon

---

engines/engine.cpp

When autosave triggers in the AGS engine, it causes an infinite recursive loop because the AGS engine polls events when saving games. Here is a portion of the call stack (I don't think you need the remaining 1705 lines ;-) ):
```
frame #1706: AGS3::update_polled_stuff_if_runtime() at game_run.cpp:989:19
frame #1707: AGS3::save_game(slotn=0, descript="Autosave") at game.cpp:924:2
frame #1708: AGS::AGSEngine::saveGameState(slot=0, desc, isAutosave=true) at ags.cpp:233:8
frame #1709: Engine::saveAutosaveIfEnabled() at engine.cpp:550:19
frame #1710: Engine::handleAutoSave() at engine.cpp:535:3
frame #1711: DefaultEventManager::pollEvent(event) at default-events.cpp:89:13
frame #1712: AGS::EventsManager::pollEvents() at events.cpp:45:38
frame #1713: AGS3::update_polled_stuff_if_runtime() at …
```

ENGINES: Ensure there is no recursive call to auto-save

---

gui/widget.cpp

Removes interfering invisible thumbnail with list item selection in saveload-dialog (OpenGL, large scale)
This issue is more apparent at least on the Android port, which uses OpenGL rendering and may default to large scale mode. It is not Android specific, though. It can be observed on the Windows builds too.
In large scale mode, ScummVM's Load/Save dialogue screen displays only a list of the saved game entries. No thumbnail is shown when selecting an entry -- the space at the right for thumbnail, playtime and save datetime is removed/hidden. However, in that Large scale mode, before this fix, when selecting an item entry from the list, the SaveLoadChooserSimple::updateSelection() method would be called, and eventually _gfxWidget->setGfx(thumb, true), which essentially would create a …

GUI: If GraphicsWidget is hidden do not proceed with setGfx()

---

engines/illusions/resources/talkresource.cpp

From what I understand, Illusions games use wide strings, and we swap their endianness on big-endian systems. However, some strings would sometimes remain in the wrong endianness, such as the second sentence from the army guy at the start: the `0x0057` character (87d) being misread as `0x5700` (22272), and so `getCharInfo()` wasn't happy with that.
The problem appears to be in the loop doing the uint16 endianness swap:
```
#if defined(SCUMM_BIG_ENDIAN)
for (byte *ptr = (byte *)_text; ptr != _tblPtr; ptr += 2) {
WRITE_UINT16(ptr, SWAP_BYTES_16(READ_UINT16(ptr)));
}
#endif
```
It stops just before `_tblPtr`. But, from what I understand, `_tblPtr` is always going to be way pat all TalkEntry text parts, as hinted by these debug lines:
```
TalkEntry::load() _talkId: 000F00C8; textOffs: …
```

ILLUSIONS: Fix text handling crash on big-endian systems

---

backends/platform/sdl/sdl-sys.h

- add unistd.h to scummsys.h so that it is included before common/forbidden.h
- e.g. on ppc64, armv7, aarch and s390, SDL.h would include indirectly
unistd.h after common/forbidden.h and so the preprocessor would
generate broken code even if the symbols are never called by the
scummvm source code
- according to my understanding how the forbidden.h feature works, any include file which contains some forbidden library function but might be included by depending librarires (in this case SDL) must be included manually before common/forbidden.h 
- the referenced commit fixes the compile issue for all mentioned architectures on Fedora but I'm not 100% sure whether it has negative side-effects to other architectures supported by scummvm
- specific example
- build for ppc64le
- …

RFC: SDL: build fix for various non-x86 architectures

---

image/png.cpp
image/png.h

This PR reverts part of 9f98cddf8dc015e0cdc6b57e303b693bba3cc1fc commit - the byte order part of the commit is kept as is, but I restored the code that checked if alpha-channel is present and providing `isAlpha ? 8 : 0` bits for pixel format.
This fixes the root cause of https://bugs.scummvm.org/ticket/11568 issue, because Wintermute engine decides to use color key for PNG images by checking `getSurface()->format.aBits() == 0`.

IMAGE: Use 0-bit alpha for non-transparent PNGs

---

engines/testbed/graphics.cpp

When pixel format isn't supported an assertion can be raised during
blitting. Don't draw anything instead.

TESTBED: Don't fail when pixel format couldn't be set

---

common/recorderfile.cpp
common/recorderfile.h

EVENTRECORDER: Use a dynamic array for buffer in PlaybackFile

---

backends/cloud/cloudicon.cpp
backends/keymapper/keymapper.cpp
common/events.cpp
common/events.h
common/osd_message_queue.cpp
common/recorderfile.cpp
common/recorderfile.h
engines/twine/input.cpp
gui/EventRecorder.cpp
gui/EventRecorder.h

The record file format is changed. But the version wasn't bumped because the old state wasn't working anyway.
This added the custom engine events from the key mapper to the serialization of the event recorder. 
With this change I can record a play in twine.
During a playback there is currently no interaction possible as all event sources except the recorder are disabled. I don't consider this a problem atm - as I see the main benefit on running the recorded plays on the buildbot - but if someone needs to have this back, I would consider doing this in a future PR.
* create recording for game demos
* integrate into buildbot
https://www.youtube.com/watch?v=SOD97joxFds

EVENTRECORDER: fixes for keymapper custom engine events

---

engines/queen/command.cpp
engines/titanic/support/avi_surface.cpp
engines/trecision/anim.cpp

- Fix -Wsign-compare in engines/titanic
- Fix -Wformat-truncation in engines/queen
- Fix -Wunused-variable in engines/trecision

ENGINES: Fix some compiler warnings

---

backends/platform/3ds/osystem-graphics.cpp
engines/sword25/gfx/screenshot.cpp
engines/titanic/support/avi_surface.cpp

Resolves leftover signedness issues to conform to baccbedf50e8d2b08df508170e0c0a4b25b8b0b6.

BACKENDS: 3DS; SWORD25, TITANIC: Resolve leftover signedness issues

---

engines/ags/detection_tables.h

"symploke1" Steam demo version is the same as the "symploke1" (English) release as the game became free2play.
No symploke1 demo is available anywhere

AGS: Remove dupped entry

---

engines/ags/engine/ac/string.cpp
engines/ags/lib/allegro/unicode.cpp

New string arithmetic is using pointers diff casted to long...
Trying to avoid C++11 features, the best option is to cast them to intptr_t instead of long

AGS: Pointers should not be casted to long

---

base/commandLine.cpp
common/rendermode.cpp
common/rendermode.h
engines/scumm/charset.cpp
engines/scumm/charset.h
engines/scumm/gfx_mac.cpp
engines/scumm/palette.cpp
engines/scumm/script_v5.cpp
graphics/macega.h

This adds a black-and-white mode for Mac Loom and Indy3. This feature was actually requested several years ago [1]. I don't know if that guy is still around, but maybe others want it as well.
Each color is dithered to a 2x2 pattern. I don't know if the actual patterns were some sort of standard, or if LucasArts came up with them themselves. But I believe that the result is pixel-perfect compared to the originals. I have put these, along with the Mac "EGA" palette, in a new header file, graphics/macega.h in case they can be reused elsewhere. When I did it, I was mainly thinking about the Mac AGI games, though looking closer at screenshots I suspect they used 3x2 dither patterns instead. Oh well.
Text is rendered as black or white (I think all of the in-game text is white), except for dark …

Add Macintosh black-and-white mode for Mac Loom and Indy3

---

base/commandLine.cpp
configure

Previously available on the wiki as a patch file for developers to apply to their configure script, this PR moves the option to a flag. The default behavior is for NO console output because users prefer that (for some weird reason).
`--enable-windows-console` and `--disable-windows-console` are the new flags. I'm open to suggestions if someone has a better name or description.
I noticed this when PR #3003 moved things around in `configure`, which caused the patch to stop working. If this PR is merged, I'll remove the patch from the wiki and suggest that devs use this flag instead.
I've tested this only on mingw-w32 with the console enabled, the console disabled by the new flag, and the console disabled as the default option.

CONFIGURE: Enable building with Windows text console output

---

engines/gob/videoplayer.cpp

Lost in Time (English floppy version but CD version might be affected as well) garbles colours during some clips playback otherwise.
The easiest way to reproduce is in manor section of the game: when it starts, just click the horse at the gate or any object in the tractor. A video will play that will also garble one colour in the picture to red (the same happens in other parts of manor section when small clips play). 
I believe it's caused by an off-by-one error in palette copy (e.g. for PORTAL04.IMD colours 16-127 are copied).
This patch seems to fix it.

GOB: Avoid an off by one

---

engines/agi/agi.cpp
engines/agi/agi.h
engines/agi/global.cpp
engines/agi/saveload.cpp

This change simplifies the AGI engine volume handling by using the music
and sound fx volumes set in the ScummVM GUI as the maximum levels which
can be set by the scripts. This avoids the complexity of synchronising
changes between these and the scripts (which only had a single 16 step
volume range which is inverted in meaning by quite a large number of
fangames).
This still allows the game scripts to adjust the volumes, but only within
the maximum range set in the Launcher / GMM.
This avoids issues such as https://bugs.scummvm.org/ticket/10732 where
users complained about extremely loud output in some cases.

AGI: Modify Volume to use ScummVM GUI as maximum range for Script Volume

---

backends/fs/symbian/symbian-fs.cpp
backends/fs/symbian/symbianstream.cpp
backends/platform/symbian/src/SymbianOS.cpp
backends/platform/symbian/src/SymbianOS.h

SYMBIAN: Simplify access to file server session.

---

engines/mohawk/dialogs.cpp
engines/mohawk/dialogs.h
engines/mohawk/myst.cpp
engines/mohawk/myst.h
engines/mohawk/myst_metaengine.cpp

This patch adds support for artificial delays during scene transitions in order to mimic the behavior of CD-ROM drives.
Usually, games supported by ScummVM are limiting their speed by themselves, e.g. through actor movement. This is not the case for the Myst series where the only transitions are the different scenes/cards. Even though the game itself is pretty slow-paced, the current implementation allows to 'rush' through it since you'll notice basically no loading times at all.
While faster loading speeds are in general a good idea, this is not the case for Myst (at least in my opinion). When this game was first released in 1993, CD-ROM drivers were slow - like double-speed slow. This means not only access times of 80 to 200ms (depending on which source you trust), but also a blazing …

MOHAWK: MYST: Add simulation for CD-ROM loading times

---

.github/workflows/ci.yml

Cache is improved, so vcpkg itself is not built every time.
Upgrade of vcpkg itself is required due to
https://github.com/microsoft/vcpkg/issues/18718.

CI: Upgrade vcpkg action to v7 and vcpkg to a recent commit

---

engines/cge/cge.h
engines/cge/detection.cpp
engines/cge/talk.cpp
engines/cge/talk.h

Some adjustments to the way TTS is done
- remove unnecessary header
- move void textToSpeech(const char *text) to talk engine
- adjust tooltip description in detection.cpp
- adjustments to the function void textToSpeech(const char *text)

CGE: Change declaration place and descriptions

---

engines/glk/level9/level9_main.h
engines/glk/tads/tads2/lib.h

GLK: Fix warnings for TRUE/FALSE redefinition on Symbian build.

---

.github/workflows/ci.yml

Analysis is 4.5x slower, and most users don't even look at the warnings.

CI: Switch Windows build to Debug

---

devtools/create_project/create_project.cpp
devtools/create_project/xcode.cpp

`--enable-fluidlite` doesn't work because create_project doesn't define USE_FLUIDSYNTH when fluidlite is enabled. USE_FLUIDLITE requires USE_FLUIDSYNTH to be defined. The two libraries are mutually exclusive but not the definitions. 
See: https://github.com/scummvm/scummvm/blob/fcf56cae45244e0d53f5870437439f4fdf6d22be/audio/softsynth/fluidsynth.cpp#L27
And: https://github.com/scummvm/scummvm/blob/fcf56cae45244e0d53f5870437439f4fdf6d22be/configure#L5013

CREATE_PROJECT: Fix enabling fluidlite

---

graphics/VectorRendererSpec.cpp
graphics/VectorRendererSpec.h

Everything is in the title.
Simplify drawTriangle in the same time and fix a bad copy paste when
drawing outline with w == h

GRAPHICS: Implement horizontal triangles

---

Makefile

This allows easy `CMakeLists.txt` creation. I would like to check the cmake build against ninja and make as well as the unity build versus the normal build. These targets were produced to ease the build dir creation and compilation. Maybe others find them useful, too.

MAKE: added target to build via cmake

---

backends/platform/sdl/sdl.cpp
backends/platform/sdl/sdl.h
common/system.h
common/textconsole.cpp
common/textconsole.h
engines/director/director.cpp
engines/engine.cpp

Previously, if an error occurred that couldn't be handled by the debugger, it would only be reported to stdout/stderr. This would result in ScummVM exiting without warning on platforms where the console isn't visible when such an error occurs. This PR adds a message box function to `OSystem` and uses it as a fallback when the currently registered error handler fails.

BACKENDS: Add OSystem::messageBox() and use it for error handling

---

engines/scumm/string.cpp

This is my attempt at reinstating a line of text in Monkey Island 2 that is printed, then immediately erased, after Rapp gives you his map piece. The comments in the commit and on bug #12734 should provide the necessary background.
I've given it some testing, but I don't know how much time I will have for ScummVM in the next few weeks. And it's hardly the only way of doing it, so any feedback is appreciated.
My main concern was that I want the animation of Rapp turning back to ash to play without any further delay. Rapp doesn't care what you're talking about. Admittedly, it may make Guybrush seem a bit less caring, too...

RFC: SCUMM: Workaround for bug #12734

---

gui/gui-manager.cpp

Fixes nested GUI dialogs causing background shading to be applied multiple times. This is a regression that occurred between release 1.8.0 and 1.9.0.  The GUI code tries to prevent this by testing the dialog stack count, so presumably the structure changed but this wasn't updated.
To reproduce and see another unintended effect:
1. Click Options (applies shading)
2. Go to MIDI tab
3. Click FluidSynth Settings (bug: applies more shading)
4. Go to the Chorus tab (extra shading goes away on redraw)

GUI: Fix shading being applied more than once

---

engines/scumm/detection.cpp
engines/scumm/players/player_v3m.cpp
engines/scumm/players/player_v3m.h
engines/scumm/scumm.cpp

This is guesswork, but it seems like the first channel always contains a complete rendition of the music. I think that's intended for low-end Macs, while the other voices (four, but the last one never seems to be used) is the standard version of the music.
It doesn't sound particularly good, and also not quite as with Mini vMac (I'm not fully prepared to rule out emulation problems), but it seems reasonably close.
So this is basically the Mac version of PC Speaker music, and I'm adding it as a curiosity. The pull request is mostly to get feedback on the name/description of the engine option and the way it is added, since I've never done that before.

SCUMM: Add support for Mac Loom low quality music

---

engines/ags/plugins/plugin_base.cpp

There is a circulating version of AGS Shell plugin as agsshell.dll
used by some games (Rosewater). Internally it's the same
ags_shell.dll so simply an alias will allow these games to run.

AGS: recognize alternative name of shell plugin

---

engines/scumm/actor.cpp

This commit fixes bug [#12030](https://bugs.scummvm.org/ticket/12030), but to do so it reverts commit [SCUMM: Fix UB shifting negative integers in Actor](https://github.com/scummvm/scummvm/commit/57084b4a1b23e131be7497c4c97c75db060210c9).
I tried comparing the calculations of these two versions of the code and they do indeed give different results when being fed negative values, and while I don't know if that's intentional or not, with my commit I'm restoring the behavior which matches the disassembly, just in case.

SCUMM: FT: Fix softlock on negative walk destination

---

engines/scumm/actor.cpp

This PR fixes bug [#12029](https://bugs.scummvm.org/ticket/12029). The problem stems from an oversight in `Actor::calcMovementFactor()`:
`ABS(deltaXFactor) > (_speedx << 16)` is not the same as `ABS(deltaXFactor >> 16) > _speedx`, which is the correct version. This probably went unnoticed because the old calculation pipeline led to slightly wrong (by one or two pixels) values for actor's x and y when walking.
This fix was taken from the disassemblies for COMI, DIG and FT, and it appears to be working fine for old SCUMM versions (I have tried at least MI2 and DOTT).

SCUMM: COMI: Fix bug #12029

---

backends/platform/sdl/win32/win32.mk
configure

* Default to `sdl2-config` instead of `sdl-config`
* Use `peldd` when cross-building
* Fix `strip`
* Do not undefine `__STRICT_ANSI__`

BUILD: Fix some cross-mingw issues

---

configure

sdl2-config should return the correct paths without it. Trying to determine
the path by name lookup is error-prone.
For example, if both the host and a cross-toolchain have sdl2 installed,
the host executable is typically /usr/bin/sdl2-config, and the
cross-toolchain is <triplet>-sdl2-config and
/path/to/toolchain/triplet/bin/sdl2-config.
The toolchain bin path should not be part of PATH, because this can cause
clashes when building for the host (depends on the PATH order, and if the
tool exists on both).
And even if we do add the toolchain bin path, like we currently do at least
on MXE container, if the host path comes before the toolchain then the
<triplet>-sdl2-config will be detected, but this executable *is not* in the
directory that relates to this toolchain, but in the host bin …

CONFIGURE: Do not pass --prefix to sdl2-config

---

configure

Works without setting PKG_CONFIG_LIBDIR.

CONFIGURE: Use cross-pkg-config on MXE

---

configure

See the commit message of a6ded8907570bb4b14101d67f076968f0775f460 for the
gory details. Until we come up with a proper fix, revert that part to make
it compile again.

CONFIGURE: Partially revert recent mingw change

---

backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/platform/3ds/osystem-graphics.cpp
backends/vkeybd/virtual-keyboard-gui.cpp
graphics/font.h
graphics/macgui/macmenu.cpp
graphics/macgui/mactext.cpp

This change was made for a couple of reasons:
- The default is now consistent with the one in Font::getBoundingBox
- Engines are unlikely to want ellipsis
I checked the current use of `Font::drawString`:
- The GUI always specify if it wants ellipses or not. So changing the default does not impact this code.
- The OSD and virtual keyboard used the default and I changed the code to continue using ellipsis if needed.
- The MacGUI code (`MacMenu` and `MacText`) used the default and  I changed the code to continue using ellipsis if needed (except for the `MacMenu` accelerator string). I am not familiar with this code, and not sure if it should use ellipsis or not. So I would be happy to change it if you think I got it wrong.
- The engines always (or almost always - I did not check all the …

Change the default for useEllipsis to false in Font::drawString

---

engines/scumm/imuse_digi/dimuse.cpp
engines/scumm/imuse_digi/dimuse.h
engines/scumm/imuse_digi/dimuse_script.cpp
engines/scumm/imuse_digi/dimuse_tables.cpp
engines/scumm/imuse_digi/dimuse_tables.h
engines/scumm/imuse_digi/dimuse_track.cpp

When the COMI DiMUSE engine encounters a JUMP instruction, a crossfade is executed from the current region of the track to the destination one.
I originally implemented this quirk in a very convoluted and hacky way, and guess what: it crashed the game on Android during certain app pause/resume situations (thanks for the heads up, @antoniou79 ).
I have now deleted my crossfading system and cleaned up the corresponding code: the game now just switches to the destination region without a crossfade, which is a thing that is very much rock solid and still pleasing to the ears.
I think this will suffice until I get around to implement the disasm.

SCUMM: COMI: Fix iMUSE crashes on Android

---

common/random.cpp

Calling RandomSource::getRandomNumber() results in divide by zero
exception when called with max = 4294967295 as max + 1 overflows to zero
and the subsequent modulus operation causes the exception.
Certain game saves in Bladerunner trigger this.

COMMON: Fix divide by zero in getRandomNumber()

---

engines/scumm/script_v5.cpp

In the EGA and VGA floppy versions, the close-up of captain Smirk has animated cigar smoke. This is missing from the VGA CD version. This pull request fixes that. (Note that it's already fixed in the "Ultimate Talkie" version, but my fix should not interfere with that.)
The animated smoke is set up by the entry script for room 76. In the VGA floppy version (I don't have the EGA one) it looks like this:
```
[001A] (A8) if (VAR_FIXEDDISK) {
[001F] (13)   ActorOps(12,[Costume(76)]);
[0024] (18) } else {
[0027] (13)   ActorOps(12,[Costume(0)]);
[002C] (**) }
[002C] (13) ActorOps(12,[Init(),Palette(2,3),Palette(9,3),Palette(3,7)]);
[0039] (5D) setClass(12,[150,148]);
[0043] (11) animateCostume(12,250);
[0046] (2D) putActorInRoom(12,76);
[0049] (01) putActor(12,172,78);
[004F] (11) …
```

SCUMM: Restore missing cigar smoke to captain Smirk's close-up

---

backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
backends/platform/3ds/osystem-graphics.cpp
backends/platform/android3d/graphics.cpp
backends/platform/dc/display.cpp
backends/platform/ds/ds-graphics.cpp
backends/platform/ios7/ios7_osys_video.mm
backends/platform/iphone/osys_video.mm
backends/platform/n64/osys_n64_base.cpp
backends/platform/psp/osys_psp.cpp
backends/platform/wii/osystem_gfx.cpp
gui/EventRecorder.cpp

Use specific copy code where applicable and replace duplicated code by
calls to copyBlit which optimizes blitting
This is a follow-up of 5af11925809267eee1abd5ddf251530f6f5f5572 and 5c8bd3b687ac166ada7d26362aa16523c002d6a6.
crossBlit can't be use on all platforms (PSP and DS especially). Instead of encouraging to pass whatever surface format we want, expect the format to be the one given by `getOverlayFormat`.
Instead of cropping image to surface size and hiding bugs, just make sure we will never overflow allocated memory.
Bug if any must be fixed at the correct place.
This way, all platforms are safe and rendering looks as expected.

BACKENDS: Harden grabOverlay in all platforms

---

.gitignore

Such files are created during compilation, and should not appear in the
output of `git status` nor should `git add` add them.

JANITORIAL: add *.o.tmp to .gitignore

---

engines/scumm/object.cpp

Today, while I was testing some sound stuff in COMI, I found out that one of the three destroyable turrets (the farthest one) in the cannon minigame in Part 1 couldn't be destroyed.
...and I took that personally.
Turns out that while Full Throttle (and I believe every previous SCUMM game) indeed did what ScummVM already does when checking for object coordinates, The Dig and COMI use the '>=' operator in place of '>'.
And now, when I try to destroy that turret:
Yay!

SCUMM: Fix findObject(x,y) for DIG and COMI

---

backends/platform/ios7/ios7_osys_misc.mm
backends/platform/sdl/sdl.cpp
common/system.h
common/text-to-speech.cpp
common/translation.cpp
gui/ThemeEngine.cpp
gui/gui-manager.cpp
gui/options.cpp

The change in this pull request change `Common::TranslationManager` so that `getCurrentLanguage` and `getLangById` both return "en" instead of "C" for the built-in language.
This seems more logical to me and allows to simplify some code (which is also included in this pull request).
Advantages of this change include:
- Better readability
For example
```c++
#ifdef USE_TRANSLATION
Common::String cl = TransMan.getCurrentLanguage();
#else
Common::String cl("en");
#endif
```
makes more sense than
```c++
#ifdef USE_TRANSLATION
Common::String cl = TransMan.getCurrentLanguage();
#else
Common::String cl("C");
#endif
```
- No need for special cases
We can remove the following in various places
```c++
if (currentLanguage == "C")
currentLanguage = "en";
```
- More language id in themes:
If we ever …

COMMON: Change TransMan builtin language to "en" instead of "C"

---

engines/scumm/saveload.cpp

This commit prevents an edge case in COMI, in which SMUSH videos were terminated in case of an event of autosaving.
Also, saving and loading was disabled in the original exe, so I guess we're not losing much here...

SCUMM: COMI: Disable saving/loading during SMUSH videos

---

configure

`a52_init()` unconditionally calls `a52_imdct_init()`, which prints "No
accelerated IMDCT transform found". This interferes with the normals
configure output, which looks like this:
```
Checking for liba52... No accelerated IMDCT transform found
yes
```

CONFIGURE: Suppress output of a52 test app

---

configure

I was trying to get `--enable-text-console` working on mac and ran into some issues:
1. configure detected apple's libedit as readline, even though doing that produces a broken build.
2. Passing `--with-readline-prefix=/opt/homebrew/Cellar/readline/8.1` caused configure to correctly detect the presence of readline, but then incorrectly detect the readline function signature, which also produced a broken build. The readline tests are run with different include orders and the second one used Apple's libedit even though the previous test had just correctly found and used readline with the prefix I specified.
Now configure's detection test includes a reference to `rl_hook_func_t` which gui/debugger.cpp depends on so that it fails early instead of producing a broken build.
The function …

CONFIGURE: Improve readline detection

---

engines/scumm/resource.cpp
engines/scumm/script_v5.cpp
engines/scumm/scumm.h
engines/scumm/scumm_v5.h

Apparently some lines for Lemonhead went missing when The Secret From Monkey Island was updated for the CD version. It looks like a mistake, since one of the message that's still there isn't even displayed long enough to see. This pull request re-inserts the missing lines for the English CD version. Apparently localized versions are affected too, but I don't have them so all I can do is trying to make it as easy as possible to extend the workaround for them as well.
The "Ultimate Talkie" also has the bug. This pull request does nothing to fix that. I don't even know if the missing lines were recorded.
Unfortunately, my only savegame is based on boot params, not playing. (I did replay the game recently, but that was on a tablet and frog knows where those savefiles were hidden!) …

SCUMM: Add missing MI1 Lemonhead lines

---

engines/adl/POTFILES
engines/adl/adl.cpp
engines/adl/adl.h
engines/adl/metaengine.cpp

The keymap isn't particularly complicated, but having one stops the default game keymap from overriding the global one.

ADL: Add keymapper support

---

engines/sword25/gfx/animation.cpp
engines/sword25/gfx/bitmap.cpp
engines/sword25/gfx/bitmap.h
engines/sword25/gfx/graphicengine.cpp
engines/sword25/gfx/graphicengine.h
engines/sword25/gfx/image/image.h
engines/sword25/gfx/image/renderedimage.cpp
engines/sword25/gfx/image/renderedimage.h
engines/sword25/gfx/image/swimage.cpp
engines/sword25/gfx/image/swimage.h
engines/sword25/gfx/image/vectorimage.h
engines/sword25/gfx/image/vectorimagerenderer.cpp
engines/sword25/gfx/panel.cpp
engines/sword25/gfx/renderobject.h
engines/sword25/gfx/staticbitmap.cpp
engines/sword25/gfx/text.cpp
engines/sword25/gfx/text.h

This PR fixes a regression from commit 4df3f333990c4cd0f0d1fda9ad1eb03e054fb2e9 which affects text rendering in the main menu, as well as some other places where colour modulation is used.

SWORD25: Properly handle colour conversion

---

backends/platform/symbian/S60v3/build_app_config.mmh

Add a dependency static library with libc functions missing in Symbian.

SYMBIAN: Add a dependency static library

---

engines/mohawk/dialogs.cpp

This is just a small patch to reword the new accessibility option in Myst's game options.
Opening as PR since english is not my first language and there might be better solutions.

MOHAWK: MYST: Reword accessibility option for Selenitic Age

---

engines/scumm/script_v5.cpp

This pull request is a continuation of https://github.com/scummvm/scummvm/pull/3211 and is an attempt at getting the same colors for the cigar smoke in the CD version as in the floppy version.
My reasoning here is that while we probably can't do anything about the colors in the other cases where this animation is used, and the special edition made the new colors canonical anyway, the cigar smoke has never before been seen in the CD version. Therefore, the floppy version is the canonical version in this particular case.
The CD version without this pull request:
The CD version with this pull request:
The floppy version:

SCUMM: MI1: Use correct colors for Smirk's cigar smoke in CD version

---

engines/scumm/script_v5.cpp

By popular demand...
It was pointed out that the clock tower in The Secret of Monkey Island behaves slightly differently in the VGA CD version than it did in the VGA floppy (and presumably also EGA floppy, but I don't have that one) version. While I don't think it _completely_ ruins the joke, I agree that the old behavior is preferable.
In the floppy version, if you examine the clock tower you get a new description (there are three possible ones, with a random variation on the last one) when you examine it, but only if you've left the room in between. The reasoning, I guess, is that you've been away for a while and the clock still hasn't changed.
In the CD version, the description changes _immediately_ when you examine the clock tower, with no need to leave in between. Guybrush's remark …

SCUMM: Restore old clock tower behavior to the CD version of MI1

---

engines/scumm/resource.cpp
engines/scumm/script_v5.cpp

This commit adds the italian translation for the patch implemented by @eriktorbjorn for the CD version of MI1.

SCUMM: Add italian translation for MI1 Cannibal script patch

---

NEWS.md

Here's some stuff I had in mind for the next release.
For Apple M1, I'm inferring that the download page for 2.3.0 will provide an M1 build which is going to be close to what's currently available in the buildbot, but that's just a guess.

NEWS: Mention macOS improvements and big-endian fixes

---

backends/fs/windows/windows-fs.cpp

Into `backends/fs/windows/windows-fs.cpp`, the macros `F_OK`/`R_OK`/`W_OK` are not defined by system includes of MSVC, so they have been added manually into the code.
While this solution works, in my opinion it would be much cleaner to use `GetFileAttributes()` for getting this information.
Actually, this is what the `_access()`/`_waccess()` functions do and, afterall, this is a piece of code expected to work on Windows only.

WIN32: Remove F_OK/R_OK/W_OK hack

---

backends/graphics/graphics.h
backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/openglsdl/openglsdl-graphics.h
backends/graphics/sdl/sdl-graphics-osx.mm
backends/graphics/sdl/sdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.h
backends/modular-backend.cpp
backends/modular-backend.h
backends/module.mk
backends/platform/android/android.cpp
backends/platform/android/graphics.cpp
backends/platform/android/graphics.h
backends/platform/ios7/ios7_osys_main.cpp
backends/platform/ios7/ios7_osys_main.h
backends/platform/ios7/ios7_osys_video.mm
common/system.h
gui/gui-manager.cpp
gui/options.cpp

The main purpose of this pull request is to fix issues with the HiDPI handling on macOS and iOS.
On macOS the main issue is that on some non-retina screens, the code in master currently think that the screen is a HiDPI screen with a scale of 2. This results in various issues, such as:
- the GUI appearing by default in lowres layout despite the window being big enough for the normal layout
- the window get smaller and smaller each time we close and restart ScummVM (https://bugs.scummvm.org/ticket/12590)
On iOS the issue is the other way around. The code in master currently assume the HiDPI scaling is 2. But on some iOS device it can be 3, and that causes the GUI to be too small by default (and it makes it difficult to go into the option to change the GUI scale).
Both are fixed by adding a …

Fix HiDPI scaling on macOS and iOS

---

engines/scumm/imuse_digi/dimuse.cpp
engines/scumm/imuse_digi/dimuse_script.cpp
engines/scumm/imuse_digi/dimuse_track.cpp

I hope this is gonna be the last PR for the old Digital iMUSE system, I really want to get the new one done soon.
This commit implements constraints for setPan and setVolume (see [here](https://github.com/AndywinXp/Digital-iMULATOR/blob/57255e3a4637dfbc7cff61e700ef3fa505a4fcbd/iMUSE/tracks.c#L369)). 
The decomp ignores any attempt to set a volume or a pan greater than 127 so we do that. In ScummVM (because of how these parameters are then handled by the Mixer class) we also have to account for negative values which, at least for panning, do appear sometimes.
As a result, all three DiMUSE games behave as they should, and I also managed to delete some nasty COMI hacks :-)

SCUMM: DiMUSE: Implement actual setVolume and setPan constraints

---

engines/metaengine.cpp
engines/metaengine.h
engines/twine/detection.cpp
engines/twine/metaengine.cpp
engines/ultima/detection.cpp
engines/ultima/detection.h
engines/ultima/metaengine.cpp
engines/ultima/metaengine.h
engines/ultima/ultima8/meta_engine.cpp
engines/ultima/ultima8/meta_engine.h

This is more consistent with the other engines, and allows simplifying the `MetaEngine` interface slightly.
Only the twine changes have been tested. Both engines would potentially benefit from using `ADExtraGuiOptionsMap`, but I've left that for another PR.

ENGINES: Move all implementations of getExtraGuiOptions into the detection plugin

---

backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.h
backends/module.mk
backends/platform/sdl/macosx/macosx-window.h
backends/platform/sdl/macosx/macosx-window.mm
backends/platform/sdl/macosx/macosx.cpp
backends/platform/sdl/module.mk
backends/platform/sdl/sdl-window.cpp
backends/platform/sdl/sdl-window.h

This should make it simpler to provide custom implementations by overriding the `SdlWindow` class.

SDL: Move getDisplayDpiFromSdl and getDpiScalingFactor into the SdlWindow class

---

engines/scumm/resource.cpp
engines/scumm/script_v5.cpp

This commit adds a patch that will readd the missing Lemonhead lines for the German CD version of Monkey Island

SCUMM: Add German MI1 Lemonhead lines

---

engines/director/detection_tables.h

Only the first Zoombinis demo launches in ScummVM at the moment. All three demos have playable sections using Mohawk, and ScummVM currently crashes when trying to launch them instead of failing more gracefully.

DIRECTOR: Add Orly's Draw-A-Story and Logical Journey of the Zoombinis demos

---

engines/scumm/charset.cpp
engines/scumm/script_v8.cpp

While researching for another bug ([the object line being out of place in COMI](https://bugs.scummvm.org/ticket/12796)), I found a bug in how `o8_getStringWidth()` calculates the width for object lines.
Originally, ScummVM calls `translateText()` on the string (say, `/SSBT001/` for objects). This works fine when the input is dialogue string (since it contains not only the `/*/` code, but also the full string. 
And it pretty much falls apart when sending just the  `/*/` code 🤕 This means that if by any chance there's an object line whose width should exceed 640 pixel, the script looking for it will never catch that (e.g.: global script 39).
A call to `convertMessageToString()` is enough to fix that and get the expected width... almost.
For some reason, `getStringWidth()` always, always, …

SCUMM: COMI: Fix getStringWidth behavior

---

engines/grim/detection.cpp

Hi
This PR makes it so the Steam and GOG versions of Escape from Monkey Island can be added and played.
The actual commit is simple enough, but there are a few points to note:
The files used for the Steam and GOG versions are mostly the same as for the CD versions, but of course there is no duplicate data situation. In particular there is only one `FullMonkeyMap.imt`, but as far as I can tell this works fine.
When trying to launch the game, the resources check will complain that `monkey4-patch.m4b`is missing. This is because the file is called `patch.m4b`. Simply renaming it fixes this.
Now, it's not ideal that one has to rename `patch.m4b`. But to be completely honest, I don't understand the codebase well enough to know whether there is a good solution for this, and if there is, …

GRIM: Add Monkey4 Steam/GOG version detection

---

engines/scumm/resource.cpp

This adds the missing Lemonhead lines to English FM-Towns version of Monkey Island as well using @eriktorbjorn's resource patch for this. Playtested it.

Add missing Monkey1 FM-Towns Lemonhead lines

---

engines/scumm/resource.cpp

This adds the missing Lemonhead lines to English SegaCD version of Monkey Island as well using @eriktorbjorn's resource patch for this. Playtested it.

SCUMM: Add SegaCD MI1 Lemonhead lines

---

backends/platform/sdl/sdl-window.cpp

Previously SdlWindow::getDpiScalingFactor only returned 100% or 200% scale. This is pretty limiting, as OSes have more fine-grained scales, for example on Windows, the "DPI" (or text scale) is set in increments of 25%: 100% (96dpi), 125% (120dpi), 150%, 175%, etc.
This changes SDL HiDPI to return the exact scaling factor, bringing it line with #3264 for macOS/iOS. I've only tested it on Windows, so I'd appreciate testing on other platforms, and seeing if there's any potential side-effects.

SDL: Fix HiDPI scaling on Windows (and others?)

---

backends/graphics/openglsdl/openglsdl-graphics.cpp

This pull request take advantage of the changes I made in feac996b50 cleanup the hacks to handle HiDPI scaling on macOS.
The SDL library handles HiDPI differently depending on the system. On some systems, such as macOS, the drawable area and the SDL window have a different size (the window is on low-dpi size) while on other systems such as Windows they have the same size. Because of that we sometimes need to scale sizes or coordinates between the two, and sometimes we don't.
This was handled in two different ways.
- In some places we queried the SDL window size and the SDL drawable area to compute the scaling between the two. As far as I know currently the scaling is 1 for all the systems except macOS with Retina screen.
- In other places we used preprocessor directives to apply a scaling …

SDL: Cleanup HiDPI macOS hacks

---

engines/sci/sci.cpp

The button behavior was reversed.
"Download patch" did nothing and "ok" downloaded the patch.

SCI: Fix GK2 patch dialog button behavior

---

engines/ags/plugins/ags_waves/ags_waves.cpp
engines/ags/plugins/ags_waves/ags_waves.h
engines/ags/plugins/ags_waves/sound.cpp

I looked at the original code of the ags_wave plugin for reference (https://github.com/Dualnames1/AGSWaves) but it handles the audio in quite a different way from this is implemented in ScummVM, so I am not really sure I understood everything properly.
These changes seem to fix all the audio issues I was having at the start of the game though.
So this also fix https://bugs.scummvm.org/ticket/12781
One thing that is still missing is the audio commentary.

Fix various audio issues in Strangeland

---

engines/prince/script.cpp

When examining an object, if the description has multiple phrases, only the first one was displayed on the screen (but speech audio continues).
Thant's because multiple phrases are encoded in the same string using '\0' separator, so strcpy/strncpy should be avoided.

PRINCE:  Only the first phrase was displayed when examining an object

---

engines/dialogs.cpp
gui/editgamedialog.cpp

This fixes [Trac #12027](https://bugs.scummvm.org/ticket/12027).

GUI: Fix displaying dynamic engine options widgets in the Edit Game dialog

---

engines/scumm/script_v5.cpp

Both bugs also occur in original.
The crashes are triggered by "background scripts" resetting inventory objects in cutscene state. Details are in the commits.

SCUMM: MONKEY-VGA fix bug #346 and #10571, Object stopped with active cutscene

---

backends/fs/abstract-fs.h
backends/fs/amigaos/amigaos-fs.h
backends/fs/chroot/chroot-fs.cpp
backends/fs/chroot/chroot-fs.h
backends/fs/morphos/morphos-fs.h
backends/fs/n64/n64-fs.h
backends/fs/posix/posix-fs.h
backends/fs/psp/psp-fs.h
backends/fs/riscos/riscos-fs.h
backends/fs/symbian/symbian-fs.h
backends/fs/wii/wii-fs.h
backends/fs/windows/windows-fs.h
backends/networking/sdl_net/handlers/downloadfilehandler.cpp
backends/networking/sdl_net/handlers/filespagehandler.cpp
backends/networking/sdl_net/handlers/listajaxhandler.cpp
backends/platform/dc/selector.cpp
common/archive.h
common/fs.cpp
common/fs.h
engines/kyra/resource/resource_intern.cpp
engines/ultima/shared/engine/data_archive.cpp
engines/wintermute/base/base_file_manager.cpp
gui/ThemeEngine.cpp
gui/browser.cpp
gui/debugger.cpp

Currently FSNode has two identical functions: **getName** and **getDisplayName**. They return the same on every backend AFAICT, but the documentation distinguishes them as:
- **getName**: Return a string representation of the name of the file. This can be used e.g. by detection code that relies on matching he name of a given file. However, it is *not* suitable for use with fopen / File::open, nor should it be archived.
- **getDisplayName**: Return a human-readable string for this node, usable for display (e.g.  in the GUI code). Do *not* rely on it being usable for anything else, like constructing paths.
Now that our GUI is Unicode-aware, I thought it would make more sense for **getDisplayName** to return a U32String, thus separating it from **getName** and allowing backends with unusual …

BACKENDS: Support Unicode display names for FSNode

---

backends/events/default/default-events.cpp
backends/events/default/default-events.h
base/main.cpp
common/events.h

When pressing Enter to start a game in the GUI, the key-up event remains in the event queue when an engine starts. In the SCI game Phantasmagoria 1, the game scripts for the introduction respond to any input event by skipping the introduction. This means that you only see the introduction by starting the game from the ScummVM GUI with a mouse. The introduction skips if you start the game by pressing Enter.
This PR adds EventManager::purgeKeyboardEvents() and calls it before Engine::run() so that GUI keyboard events no longer leak into engines. There is already a purgeMouseEvents() so I modeled it after that.
Tested on Windows and Mac.

BASE: Purge keyboard events before running Engine

---

backends/platform/sdl/amigaos/amigaos.mk
backends/platform/sdl/morphos/morphos.mk

This prevents the doxygen and docportal sources from being included in packages.

AMIGAOS/MORPHOS: Avoid copying the entire doc directory when packaging

---

backends/graphics/openglsdl/openglsdl-graphics.cpp

_Disclaimer: Not sure if this change is allowed right now or if it's affected by the current freeze. Would be nice to get it into the next release though._
Last time, I didn't know about the various SDL window flags, but this is my next try. This patch makes ScummVM remember if we left off with a maximized window and restores it properly.

BACKENDS: OPENGLSDL: Remember maximized window state, fix off-screen positioning of window

---

Makefile.common
backends/platform/androidsdl/androidsdl.mk
backends/platform/dingux/dingux.mk
backends/platform/gph/caanoo-bundle.mk
backends/platform/gph/gp2x-bundle.mk
backends/platform/gph/gp2xwiz-bundle.mk
backends/platform/n64/n64.mk
backends/platform/openpandora/op-bundle.mk
backends/platform/sdl/amigaos/amigaos.mk
backends/platform/sdl/morphos/morphos.mk
backends/platform/sdl/ps3/ps3.mk
backends/platform/sdl/psp2/psp2.mk
backends/platform/sdl/riscos/riscos.mk
backends/platform/sdl/switch/switch.mk
backends/platform/wii/wii.mk
ports.mk

Don't use special characters in file name as make and shell don't have
same rules.
When we use parentheses, shell expects them to be escaped (or quoted) while make doesn't want to hear about quotes nor escaping (it doesn't see file).
Spaces are not ideal too but they can be handled as we don't do heavy processing with the variables.
Then, add the $(DIST_FILES_DOCS) as a prerequisite to all targets using it. This will download the manual when it's not present and curl is available.

BUILD: Add a target to download manual when not present

---

common/random.cpp

Common::RandomSource fix rng seeding
Rng seeding on Windows had a small range of possible values, because it was set in the constructor based on milliseconds since process start. This was greatly reducing the number of possible seeds. @TehGelly noticed this issue and pointed out that the only seeds he ever gets when playing Shivers are between about 900 to 1050.
```
uint32 OSystem_NULL::getMillis(bool skipRecord) {
#ifdef POSIX
timeval curTime;
gettimeofday(&curTime, 0);
return (uint32)(((curTime.tv_sec - _startTime.tv_sec) * 1000) +
((curTime.tv_usec - _startTime.tv_usec) / 1000));
#elif defined(WIN32)
return GetTickCount() - _startTime;
#else
return 0;
#endif
}
```

fix rng seeding

---

engines/advancedDetector.h
engines/stark/detection.cpp
engines/stark/detection.h
engines/stark/services/userinterface.cpp
engines/stark/services/userinterface.h
engines/stark/stark.cpp
engines/stark/stark.h
engines/stark/ui/dialogbox.cpp
engines/stark/ui/dialogbox.h

This is an alternative fix for bug https://bugs.scummvm.org/ticket/12762
This fix will set a flag at detection time (when adding the game to ScummVM)
so that the Steam version of The Longest Journey will skip trying to load a background image resource (147.bmp) from the exe file (game.exe), since that specific build is missing this resource and this leads to an assertion fault.
Edit: It wont be necessary to re-add (redetect) the game, if it has already been added before this fix.
The previous fix was this commit and it was based only on version info of the exe file.
That one also works without having to re-add/re-detect the game, but perhaps just checking
version info is not the best approach.
https://github.com/scummvm/scummvm/commit/565a0559ed09660daa83cd529afa4e0efb6949c5

STARK: Detect TLJ Steam version to fix missing bg resource

---

engines/scumm/script_v5.cpp

WORKAROUND bug #12420 (also occurs in original) Broken window and coat missing
This happens when you skip the cutscenes in the beginning, in particular
the one where Indy enters the office for the first time. If object 23 (National
Archeology) is in possession of Indy (owner == 1) then it's safe the force the
coat (object 24) and broken window (object 25) into the room to compensate for
the skipped code.

SCUMM: Indy4 - Put coat/window in office, fixes bug #12420

---

engines/scumm/input.cpp

There are several Ctrl+Key combinations that are accepted by the engine.
Most famous one is Ctrl+W, which is Instant Win on monkey1 (monkey2 uses
Alt+W, and has a similar hack for passing it correctly).
This used to work with ScummVM 1.9.0/SDL1, but broke with SDL2, and was
later broken further even for SDL1 in f5ed14e93d85.
Fixes #10644.

SCUMM: Fix handling of Ctrl+Key in monkey1 and monkey2

---

common/language.cpp
common/language.h
common/platform.cpp
common/platform.h
engines/director/detection_paths.h
engines/director/detection_tables.h

This adds over 100 new game IDs and many new platforms and languages
to existing ones.
New platform for Shockwave has been added to COMMON. It's not very
relevant to the end user whether these games were developed on Mac or
Windows. The same files are used for both platforms.
Three new language codes were added after consultation with native
speakers. Flemish is sometimes specifically targeted, rather than
Standard Dutch, especially by publishers based in Belgium. At least
one publisher in Barcelona regularly released edutainment and reference
works in Catalan.
I've also recently uncovered a large body of work in Arabic, primarily
published by Egyptian companies. This PR begins to add these games into
the detection tables.

DIRECTOR: Add detection, platform, and languages

---

engines/asylum/asylum.cpp
engines/asylum/asylum.h
engines/asylum/detection.cpp
engines/asylum/detection_tables.h

This patch adds a detection entry for the German Steam version of Sanitarum.
Unfortunately, this version is currently completely broken and crashes with
```File::open: opening 'palette' failed
Assertion failed: _handle, file common/file.cpp, line 142
```
on startup. I'm adding this version basically just for reference at this point. Hopefully, I'll get my hands on a proper German CD release as well.

ASYLUM: Add detection entry for German Steam version

---

gui/console.cpp
gui/console.h

Persisting the debug console history in the save dir of the engine (history.txt)

GUI: persist the debug console history

---

engines/scumm/input.cpp

Tested with Loom and The Dig. It seems to be consistent.
Sam&Max seems to have different mapping for Ctrl. The DOS version
has the following actions:
Ctrl-I: Rotates the current action
Ctrl-J: Switches to Joystick Mode
Ctrl-K: Shows memory stats
Ctrl-C: Prompts to quit
Ctrl-M: Switches to Mouse Mode
Anyway, since it doesn't break anything, I did not add an exclusion for it.

SCUMM: Extend Ctrl handling to all the games on versions 3-7

---

devtools/README
devtools/docker.sh

This handles both fetching images from the Docker Hub and launching a shell with the ScummVM source directory within the image.

DEVTOOLS: Add a build script to simplify building with Docker

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp

Now that we have higher scale factors than 3, it makes sense to try and figure out a default scaler for high-resolution games that approximate the window size of a low resolution game.
That also means that we are not necessarily restricted to the normal scaler, since AdvMame has both 2x and 4x versions.
Since my own default scaler is Normal 3x, this change won't affect me much personally, though.

SDL: Set better default scaler for high-resolution games

---

configure

On replace mode (r), u tells ar to replace object files only if the source
file is newer than the one in the archive.
When binutils is configured with --enable-deterministic-archives, the
default mode for ar is D (deterministic), which means that all the files
are stored with zero for UID, GID and timestamp. This means that ar has no
way to tell if the archived file is older than the source file, so it just
archives all the input files and issues the following warning:
```
`u' modifier ignored since `D' is the default (see `U')
```
Fix by dropping this flag. The performance gain is negligible anyway.

CONFIGURE: Drop `u` flag for ar

---

engines/cine/cine.cpp
engines/cine/cine.h
engines/cine/prc.cpp
engines/cine/rel.cpp
engines/cine/saveload.cpp
engines/cine/script.h
engines/cine/script_fw.cpp
engines/cine/various.cpp
engines/illusions/bbdou/illusions_bbdou.cpp
engines/illusions/duckman/illusions_duckman.cpp
engines/illusions/illusions.h
engines/illusions/saveload.cpp
engines/lab/interface.cpp
engines/supernova/supernova1/state.cpp

This is one of the issues causing [Trac #11712](https://bugs.scummvm.org/ticket/11712).

ENGINES: Avoid using static objects with destructors

---

Makefile.common
backends/platform/androidsdl/androidsdl.mk
backends/platform/dingux/dingux.mk
backends/platform/gph/caanoo-bundle.mk
backends/platform/gph/gp2x-bundle.mk
backends/platform/gph/gp2xwiz-bundle.mk
backends/platform/n64/n64.mk
backends/platform/openpandora/op-bundle.mk
backends/platform/sdl/amigaos/amigaos.mk
backends/platform/sdl/morphos/morphos.mk
backends/platform/sdl/ps3/ps3.mk
backends/platform/sdl/psp2/psp2.mk
backends/platform/sdl/riscos/riscos.mk
backends/platform/sdl/switch/switch.mk
backends/platform/wii/wii.mk
ports.mk

Fixes trying to copy the user manual pdf file when it is not present.
This does so by checking if the file is present before adding it to `DIST_FILES_DOCS`.
This is an alternative to pull request #3317 that instead automatically downloads the manual if not present (or at least try to do so). Since that pull request had already been merged, this pull request includes reverting the commits it contained.
I am not sure which approach is best, which is why I am proposing this as a pull request. With the changes here, if we want to bundle the user manual, we need to run manually `make manual` first. But in the case of a release, the file could be included in the release tarball.
One issue with the automatic download is that it requires an internet access. Without one trying to do `make bundle` …

Manual manual download

---

common/punycode.cpp
common/punycode.h

I saw this in the coverity report (CID 1461548 and 1461550) and it seemed easy enough to fix.

COMMON: Use const references where possible in punycode

---

NEWS.md
engines/cine/detection_tables.h
engines/cine/gfx.cpp
engines/cine/gfx.h
engines/cine/part.cpp
engines/cine/various.cpp

Hello!
Here are fixes for the following bugs/feature requests:
- #11687 ("CINE: OS: Space missing in verb line")
- #11708 ("CINE: OS (Atari ST/German) - Dialogue window overflow")
- #11723 ("CINE: OS: Crash in Secret Base")
- #12812 ("CINE: Unknown game variant for Operation Stealth, Amiga OCS Italian.")
Please could you cherry pick these to the 2.3.0 branch also? Thank you very much!
Kari Salminen

CINE: Fixes for #11687, #11708, #11723 and #12812

---

NEWS.md
engines/cine/detection_tables.h

Add detection for Future Wars CD version with French translation patch
applied.
Closes #12490
Please could you also cherry pick this to the 2.3 branch? Thank you very much!
Kari Salminen

CINE: Add detection for French patched FW CD (#12490)

---

engines/buried/biochip_view.cpp

This should fix the missing research points described in https://bugs.scummvm.org/ticket/12881
Basically, the bug boiled down to the points only being awarded when pressing the "previous" button. And that would never take you to the pages that awarded the points.
Note that since I've never gotten around to playing the game, it's quite difficult for me to tell if I've accidentally mixed up anything. I'd be grateful if someone more familiar with the game could test it.

BURIED: Fix missing research points (bug 12881)

---

engines/buried/scene_view.cpp

The comment says it will clear the live text window, but instead disabled the navigation arrows (I think), which it then does again right aftewards. A cut and paste error, perhaps? Anyway, I hope this produces the correct behavior as described in https://bugs.scummvm.org/ticket/12887
I also noticed that there are a number of updateLiveText("") calls (to clear the text), even though an empty string is the default value for it. But I didn't bother cleaning that up.

BURIED: Clear the live text window when moving, as advertised (bug 12887)

---

backends/log/log.cpp
backends/modular-backend.cpp
base/commandLine.cpp
base/main.cpp
common/recorderfile.cpp
common/recorderfile.h
engines/engine.cpp
gui/EventRecorder.cpp
gui/EventRecorder.h
gui/gui-manager.cpp

- Screenshot frequency can now be specified from the command line.
- Screen redraws are now tracked, and all events and screenshots are force-aligned with a screen redraw.
- A few cases of recursion in the event processing stream have been removed.
- Compatibility with the previous version of Event Recorder file format has been dropped, on the advice that no testing efforts use this feature yet.
- A new 'update' mode has been added to the EventRecorder. This new mode is functionally identical to playback mode, however
a new recording file is used to track the actual output of ScummVM. This feature can be used to update a suite of existing recordings after a renderer or a timing change.

EVENTRECORDER: Fix synchronisation, add 'update' mode

---

common/random.cpp
common/random.h

The old RNG method had non-standard periods, ranging from some seeds looping on themselves (seed = 1184201285) to some seeds having periods as low as 11 or 48, as listed in https://github.com/scummvm/scummvm/pull/3340. This is a problem even for games that run the RNG once a frame, as the possibilities for random events is greatly reduced should the initial seed be in one of these sets of small periods.
Xorshift is a standard, fast, non-cryptographic PRNG with academic backing that has period 2^32-1 (all seeds lead to another seed except 0, which is excluded from the initial seeds).  Many different flavors are possible, as listed in the paper, but the choice implemented in this pull request uses only a single 32-bit integer as a state, like the old PRNG.

COMMON: Change PRNG Function to Xorshift

---

engines/ags/engine/ac/character_extras.h
engines/ags/engine/ac/dialog.cpp
engines/ags/engine/ac/game_state.h
engines/ags/engine/ac/global_api.cpp
engines/ags/engine/ac/global_file.cpp
engines/ags/engine/ac/global_file.h
engines/ags/engine/ac/move_list.h
engines/ags/engine/ac/parser.cpp
engines/ags/engine/ac/room_object.h
engines/ags/engine/ac/room_status.h
engines/ags/engine/gui/new_control.h
engines/ags/engine/main/game_run.cpp
engines/ags/engine/main/game_run.h
engines/ags/engine/script/executing_script.h
engines/ags/globals.h
engines/ags/plugins/ags_pal_render/ags_pal_render.cpp
engines/ags/plugins/ags_plugin.h
engines/ags/shared/ac/character_info.h
engines/ags/shared/ac/dynobj/script_audio_clip.h
engines/ags/shared/ac/game_struct_defines.h
engines/ags/shared/ac/interface_button.h
engines/ags/shared/ac/interface_element.h
engines/ags/shared/ac/inventory_item_info.h
engines/ags/shared/ac/mouse_cursor.h
engines/ags/shared/ac/old_game_setup_struct.h
engines/ags/shared/game/room_file_deprecated.cpp
engines/ags/shared/game/room_struct.h

This is done to explicitly specify that they should be treated as signed
Some ports may treat an (unspecified) "char" as unsigned by default. Android does this for its ARM architectures and while we did fix this by enforcing -fsigned-char to its compiler, the issue may come up for other ports. Also it should be better to clarify in the engine when a variable is not actually storing string characters.
I've spotted and changed the most "safe" cases I could find for this. As far as I can tell, out of these, only the Outline field and fontoutline[] array could potentially be assigned valid negative values which would cause bugs for ports treating chars as unsigned.

AGS: Change a few char variables to int8

---

engines/sludge/saveload.cpp

Clang 11 and newer check the types of return values more strictly and
generate an error if there is a discrepancy.
However the "bool loadGame()" function, returns the value "NULL", if
loading of a savegame was unsucessful, whereas Clang expects a return
value of type "bool".
Remedy the issue by using "false" as return value instead of "NULL".

SLUDGE: Fix build with Clang >= 11.0.0

---

engines/ags/shared/ac/game_struct_defines.h
engines/ags/shared/font/fonts.cpp
engines/ags/shared/font/fonts.h
engines/ags/shared/font/ttf_font_renderer.cpp

Possible fix for https://bugs.scummvm.org/ticket/12923
This is quite an oblivious fix, though, since I use FontInfo Flags field (which as far as I can tell is unused) to set bit flags to track if a loaded font uses a TTF or WFN renderer and also I renamed a method (get_outline_font() to get_outline_ttf_font()) to specify that it's specifically for TTF fonts use cases.
Maybe there's a better way of fixing this.

AGS: Only load ttf font as outline for ttf font

---

engines/groovie/clangame.cpp
engines/groovie/cursor.cpp
engines/groovie/detection.cpp
engines/groovie/music.cpp
engines/groovie/script.cpp
engines/groovie/script.h
engines/groovie/tlcgame.cpp

Fixes crashes when you have saved games. Also makes the preview images on saved games work.
Also fixes Mac/iOS cursors and music, because they use slightly different filenames for them.

GROOVIE: Clandestiny fixes

---

engines/buried/environ/da_vinci.cpp

This should hopefully fix https://bugs.scummvm.org/ticket/12885 but needs to be tested by someone who knows the game.
I take no credit for this, since the code was handed to me through sev from "Keith" (Kaisershot?). There seems to have been some cut and paste error, because instead of choosing between the regular and first time door opening animation, it was choosing between the first time and breaking in animation, always picking the first time one.
The break in animation is presumably always handled by droppedItem(), so it shouldn't even have come into consideration here. I think. The regular door opening animation isn't even the same type of transition, which may explain why I was completely unable to find it.

BURIED: Fix door opening transition to Da Vinci study (bug 12885)

---

engines/advancedDetector.cpp

I figure this would be helpful when people submit their log files, so we know what version of the game they're running.
Looks like this
```
[2021-09-15 15:27:24] ScummVM 2.4.0git (Sep 15 2021 12:10:44)
[2021-09-15 15:27:24] Vorbis FLAC MP3 RGB zLib FluidSynth Theora FreeType2 FriBiDi JPEG PNG taskbar TTS cloud (servers, local) TinyGL OpenGL (with shaders) GLEW 
[2021-09-15 15:27:24] --- Log opened.
[2021-09-15 15:27:29] Running The 11th Hour: The Sequel to The 7th Guest (Windows/English)
[2021-09-15 15:27:29] script.grv: bdb9a783d4debe477ac3856adc454c17, 62447 bytes.
[2021-09-15 15:27:29] introd1.gjd: 9ec3e727182fbe40ee23e786721180eb, 6437077 bytes.
[2021-09-15 15:27:36] --- Log closed successfully.
```
Ubuntu build initially failed, so this can be squash merged

COMMON: logging hashes when starting a game

---

engines/metaengine.cpp

This was broken for most engines.

ENGINES: Fix moving savegames to a new free slot

---

engines/director/sound.cpp

`AIFC` is already handled by `makeAIFFStream`. This fixes audio in the Music Island games.

DIRECTOR: Add AIFC detection

---

base/main.cpp

I noticed that while bilinear filtering is disabled by default with ``RegisterDefault();`` at startup, bilinear filtering is always applied when starting a game (at least on the OPENGLSDL backend) unless you explicitly set ``filtering=false`` in the configuration file by simply opening the options dialog, applying the settings and closing it again.
While researching this, I think the culprit is that main.cpp checks for ``ConfMan.hasKey("filtering")``, but ``registerDefault()`` technically won't set a configuration key. This means that this checks override our defaults.
I think that this check is not necessary. With the checks for ``hasKey`` removed, it will first try to load the values set in the configuration file and otherwise fall back to the values set by ``registerDefault()`` …

BASE: Don't check for config key presence when loading gfx mode

---

base/main.cpp
engines/ags/detection.cpp
engines/ags/detection.h
engines/ags/dialogs.cpp
engines/ags/metaengine.h
engines/ags/module.mk
engines/metaengine.h
engines/mohawk/detection.cpp
engines/mohawk/metaengine.cpp
engines/nancy/detection.cpp
engines/nancy/metaengine.cpp
engines/sci/detection.cpp
engines/sci/detection_options.h
engines/sci/dialogs.cpp
engines/sci/dialogs.h
engines/sci/metaengine.cpp
engines/sci/module.mk
gui/editgamedialog.cpp

This should slightly reduce the size of the detection plugin, and serves as a step towards fixing [Trac #12345](https://bugs.scummvm.org/ticket/12345).

ENGINES: Move all custom engine options dialogs into the engine plugin

---

engines/director/detection_tables.h

It's been bugging me that the detection entry didn't have the full title of the game, so I fixed it.

DIRECTOR: Add full title for ernie in detection

---

engines/ags/engine/ac/global_video.cpp
engines/ags/engine/media/video/video.cpp
video/avi_decoder.cpp
video/avi_decoder.h

This is a commit that has a minor change to the AVIDecoder, and whilst it's only a minimal change, I'd like a second opinion on it before I push it to master and backport it to the release branch.
It basically makes two changes:
* A video track isn't added to the track list unless it has a known supported codec
* The loadStream method overall aborts the load, and returns false, if the loaded AVI video doesn't have a video track registered
Due to this, any AGS games which have unsupported video codecs like XVid will still be able to play.. they'll now simply skip the video rather than throwing an error like happened previously.

AGS: Skip videos with unsupported video tracks rather than erroring

---

engines/agi/agi.h
engines/agi/cycle.cpp
engines/agi/keyboard.cpp
engines/agi/menu.cpp
engines/agi/op_cmd.cpp
engines/agi/op_test.cpp
engines/agi/saveload.cpp
engines/ags/engine/script/script.cpp
engines/glk/agt/metacommand.cpp
engines/glk/jacl/parser.cpp
engines/glk/tads/tads2/error_message.cpp
engines/grim/emi/lua_v2.cpp
engines/hdb/lua-script.cpp
engines/myst3/myst3.cpp
engines/saga2/button.cpp
engines/saga2/gtextbox.cpp
engines/saga2/panel.cpp
engines/saga2/tile.cpp
engines/stark/stark.cpp

Fixing this misspelled word across multiple parts of the codebase.
See ["Occurred, Occured, or Ocurred—Which Spelling Is Right?"](https://www.grammarly.com/blog/occurred-occured-ocurred/)

COMMON: Fixing misspellings "occured" -> "occurred"

---

engines/grim/imuse/imuse.h
engines/grim/imuse/imuse_track.cpp

The moveToFadeOutTrack() function was introduced many years ago to fix "sound skipping a bit when a fade out track starts". Unfortunately, while this may have worked flawlessly back then it causes crashes in certain cases now. See https://bugs.scummvm.org/ticket/12932 for details.
The point of this is to avoid the crash for the upcoming release. A more long-term solution should be in the works. See https://github.com/scummvm/scummvm/pull/3368
I did not revert this part, because it looked harmless to me. I could be wrong about that:
```
@@ -216,7 +216,7 @@ void Imuse::callback() {
// Ignore tracks which are about to finish. Also, if it did finish in the meantime,
// mark it as unused.
if (!track->stream) {
-				if (!g_system->getMixer()->isSoundHandleActive(track->handle))
+				if …
```

GRIM: Partially revert 6bb4658ea6 to work around bug #12932

---

backends/graphics/sdl/sdl-graphics.cpp

The previous SdlGraphics3dManager::toggleFullScreen() was not using
beginGFXTransaction / endGFXTransaction in toggleFullScreen().
Restore this logic for 3D games, as using transactions in such games
results in a black screen for 3D games when switching to full screen
A regression from d33487f64
Alternate fix for the situation reported in PR #3387

SDL: Fix full screen toggling for 3D games

---

engines/neverhood/sound.cpp

This is the fix I suggested on https://bugs.scummvm.org/ticket/12930
I don't know if it's correct - I never got any feedback on it - but it does seem to fix the game crashing on exit for me. If I'm right, it was trying to keep playing a sound after the audio data for it had been freed. With the change, sound 3 is handled the same way as sounds 1 and 2, i.e. stopped first.

NEVERHOOD: Possible fix for bug #12930 (crash on exit)

---

engines/stark/resources/speech.cpp
engines/stark/services/settings.cpp
engines/stark/services/settings.h

Fix for bug https://bugs.scummvm.org/ticket/12967

STARK: Fix bad subtitle for Cortez in theater

---

engines/twine/parser/body.cpp
engines/twine/scene/grid.cpp
engines/twine/scene/grid.h

This fixes a crash on startup on RISC OS. It doesn't get in game however, since it hits the following assert:
```
"./common/array.h", line 244: const T& Common::Array<T>::operator[](Common::Array<T>::size_type) const [with T = TwinE::BlockDataEntry; Common::Array<T>::size_type = unsigned int]: Assertion failed: idx < _size
Fatal signal received: Aborted
Stack backtrace:
Running thread 0xab6848 (Main Thread)
(  bf8758) pc:   56b6ec lr:   56bb98 sp:   bf875c  __write_backtrace()
(  bf87c8) pc:   56b80c lr:   56bef8 sp:   bf87cc  __unixlib_raise_signal()
(  bf87d8) pc:   56bedc lr:   573bc0 sp:   bf87dc  raise()
(  bf87ec) pc:   573b84 lr:   54e808 sp:   bf87f0  abort()
(  bf8810) pc:   54e7b0 lr:   563b78 sp:   bf8814  __assert2()
(  bf8824) pc:    a8bcc lr:    a9844 sp:   bf8828 …
```

TWINE: Additional stream checks when loading the body data

---

engines/kyra/engine/kyra_hof.cpp

Following #3277
This PR fixes the action string for multi-worded object in Hebrew fan translation of Kyrandia 2
as well as reversing the order of the sentence.
The game resource have objects names along with the indefinte article,
then, on command string, the engine removes the article and uppercase the first letter, e.g.
an empty flask -> Empty flask taken.
This logic caused object with multiple words to skip the first word in hebrew.
The reversing of the sentences is to avoid having to consider the object gender,
so the sentence become dependent on the player and not the object
(you (plural, indefinite) have dropped [object].) instead of ([object] placed (gender needs to match).)
Thanks

KYRA: HOF: Fix hebrew multiword object action strings

---

backends/networking/sdl_net/reader.cpp
backends/networking/sdl_net/reader.h

This only changes what's related to the local webserver (SDL_net), not to the Cloud sync (libcurl). 
I revisited Networking::Reader (remembering that file upload speed wasn't as fast as I wanted it to be). This class uses a "window" buffer to detect the boundaries in POST multipart requests.
First commit does what I actually intended to do back in the GSoC days: have a circular buffer, so we don't have to shift the whole buffer all the time.
The second commit tries to avoid doing unnecessary linear string comparisons all the time by calculating a "hash" of a boundary string and dynamically recalculating "hash" of what's in buffer. Strings are only compared if these "hashes" match. This is not exactly a hash, as it's just a xor sum of all the bytes in the string/buffer. If someone knows …

CLOUD: Update Networking::Reader to increase file upload speed

---

engines/mohawk/detection_tables.h

"Making of Myst" from JP and IT Win 3.11 is in English, so mark it as `EN_ANY`
Doesn't resolve the hash collision with the EN v1.0.1 and DE v? entries.

MOHAWK: Add sizes, versions to some Myst entries

---

doc/docportal/advanced_topics/configuration_file.rst
doc/docportal/advanced_topics/understand_search_box.rst
doc/docportal/index.rst
doc/docportal/use_scummvm/the_launcher.rst
gui/launcher.cpp
gui/launcher.h
gui/widgets/list.cpp
gui/widgets/list.h

This PR extends filter of games list to use some simple google-like syntax.
Filter is split into tokens, each token are checked separately, if any token does not match a game, it's filtered out.
Oldfashioned requests are still supported with tokens without ":", "=", "~":
* `Hamlet Hungarian` - games that have "Hamlet" and "Hungarian" substrings in description
Three kinds of property checkers added:
* "=" is used to check exact value of something, e.g. `gameid=reversion2` - games with exact gameid match
* ":" is used to search substring at something, e.g. `description::` - games with ":" substring at description
* "~" is used to match wildcard against something, e.g. `path:D:\\games\\*` - games at Windows folder D:\Games\
6 properties can be abbrivated:
* For "description" you can use "d", …

RFC: Use custom matcher for games list

---

engines/bladerunner/ui/kia_section_load.cpp
engines/bladerunner/ui/kia_section_save.cpp
engines/bladerunner/ui/ui_input_box.cpp
engines/bladerunner/ui/ui_input_box.h

If you type save names like e. g. "äöüß" in the GMM this will now show up correctly in the ingame save/load dialogs.
You still cannot type these characters ingame due to the current implementation of UIInputBox::charIsValid(). I don't know the purpose of the function. If I comment out everything and simply return true it works fine (I can enter all these special characters). So it is not a limitation of the font, even though I have the English version. If the only reason for charIsValid() was the wrong encoding it might make sense to limit or even remove it.

BLADERUNNER: fix encodings for save descriptions

---

base/version.cpp
base/version.h

The following variables:
```
gScummVMVersion
gScummVMBuildDate
gScummVMVersionDate
gScummVMFullVersion
gScummVMFeatures
```
are declared as pointers to strings but there is no need to do so.
They can be simply declared as const strings, since they will be never modified when SCUMMVM runs.

BASE: Convert version strings to const objects. 

---

backends/events/ds/ds-events.cpp
backends/platform/ds/ds-graphics.cpp
backends/platform/ds/keyboard.cpp
backends/platform/ds/keyboard.h
backends/platform/ds/module.mk
backends/platform/ds/osystem_ds.cpp
backends/platform/ds/osystem_ds.h

This is opened as a PR because it affects common code. Fixes [Trac #12341](https://bugs.scummvm.org/ticket/12341).

DS: Virtual keyboard support

---

devtools/create_project/create_project.cpp

Allows disabling full detection with `--disable-detection-full`, just like the configure script. `detection_table.h` now has the same content as the one generated by the configure script. This doesn't change any default behavior.
Tested on msvc and xcode. Speeds up compiling my one-engine local builds. Also makes it possible to build again on older msvc versions that have trouble with some of the newer engine code that detection objects bring in, but that's just a bonus for me.

CREATE_PROJECT: Add DETECTION_FULL feature

---

engines/agos/drivers/accolade/adlib.cpp
engines/agos/drivers/accolade/adlib.h
engines/agos/midi.cpp

This is an attempt at fixing the Waxworks AdLib music. See https://bugs.scummvm.org/ticket/13048 for some details.
The problem turned out to be that when calculating the value to be written to the 40 - 55 AdLib registerers, it could underflow so instead of 0 (max volume) it would write some negative value, probably close to the minimum volume.
Much of this calculation is done in the noteOn() function, but the `channelVolumeAdjust` variable (which is clipped to the appropriate interval) is never used. I assume that was the main error. I've also changed it so that the clipping is done after all the adjustments have been made. (And since we're working with small 16-bit integers, there is no need to use floating-point math either, so I've eliminated that.)
Is it correct? I don't know. At …

AGOS: RFC: Fix Waxworks AdLib music (bug #13048)

---

devtools/dumper-companion.py

This fixes dumping the MacPeople 1998 #2 coverdisc, which has Mac-Roman filenames on the (Japanese) disc.

DEVTOOLS: Work around Mac-Japanese sequences missing low byte

---

engines/grim/sector.cpp

Originally reported in https://github.com/tobiaspfaff/grim_mouse/issues/9.

GRIM: Fix some missing hotspots with mouse enabled

---

devtools/dumper-companion.py

Use "MacJapanese" instead of "Mac Japanese", remove commented code from previous PR. These were requested by @rvanlaar

DEVTOOLS: Add test for previous dumpercompanion workaround, other changes

---

engines/director/detection_tables.h

Some childhood games I still had laying around here.

DIRECTOR: Add detection for a few german games

---

engines/director/detection_paths.h
engines/director/detection_tables.h

This adds several new variants of games that are already in ScummVM; some are full versions of demos, others are language variants. Some notes:
Jungle Park:
* ScummVM immediately closes with an error in the console: `Cast::loadConfig(): Wrong format. VWCF resource missing!`
Peace Land:
* ScummVM closes immediately after loading. The console complains about not being able to locate a score with a specific name, several unimplemented xlibs, an unhandled movie resource, and an unhandled `PICT` resource.
Pickle's Book:
* The Windows and Mac versions seem to have been compiled with different Director versions.
* Gets to the title screen correctly, then hangs with glitchy audio.
Pyramid Interactive:
* Immediately throws an in-ScummVM error from inside `Cast::loadCastDataVWCR()`
World Engine …

DIRECTOR: add new variants of existing games

---

engines/director/detection_paths.h
engines/director/detection_tables.h

This adds a new batch of Director games, along with tweaks to another couple that were already in the tables.
* Tri 3D was another game affected by the Mac filesize bug, so I've fixed it.
* Amusement Planet Phantasmagoria is the first hybrid rerelease, not the original version, so I've added a release comment.
Aquaplanet:
* Exits immediately with `Cast::loadCastDataVWCR(): non-existent reference to BitmapCastMember!`
Browser: Artopolis 97:
* Mac version errors out on startup due to inability to parse RIFX.
* Windows version crashes on startup due to an index out of bounds while reading an array.
Chun-Chun World:
* Both versions have various sub-apps. The "theme song view" is Windows-only; it's a Quicktime app on Mac.
* Mac version can't locate movies.
* Windows version runs with minor …

DIRECTOR: add more games

---

engines/sci/console.cpp

Since I am constantly evaluating the stack, please consider adding this alias for the stack command. 
* Add `st` as an alias to `stack` command
* I'm hoping this is a reasonable request since it also nicely models stack based addresses such as: `ST:0001`
* I previously added an alias for the `registers` command as well named: `reg`

SCI: add "st" as an alias to the debug "stack" command

---

engines/director/sound.cpp

`getAudioStream()` was leaking file descriptors. The caller closes the file if a stream could be created, but in the case one isn't then the file will never be closed. In the worst case scenario, it could hit the descriptor table size and prevent any further file open calls from working.
cc @moralrecordings

DIRECTOR: close file handles when no stream created

---

engines/director/sound.cpp
engines/director/sound.h

Certain audio streams can (and often do) contain resource forks, so the dumper companion will write them as macbinary. Right now, the audio code will choke on them since it tries to read from the macbinary header assuming it's audio. This adds a check for whether the file is macbinary and handles it appropriately.
In the future, I might run a pass over the Director code to support native Mac files on HFS+/APFS macOS, but there's a lot I'd need to update for that.
To test this, you can try the Pippin/Mac version of Jungle Park run through the dumper companion. Without this patch, it'll fail to recognize `JUNGLE/JINGLE.AIFF`; it won't play the intro audio and will spam the console with errors about it. With this patch. it works fine.

DIRECTOR: handle macbinary audio streams

---

engines/xeen/combat.cpp

As reported by the compiler:
```
engines/xeen/combat.cpp: In constructor ‘Xeen::Combat::Combat(Xeen::XeenEngine*)’:
engines/xeen/combat.cpp:97:21: warning: array subscript 32 is above array bounds of ‘int [32][32]’ [-Warray-bounds]
97 |         Common::fill(&_monsterMap[0][0], &_monsterMap[32][32], 0);
|         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./engines/xeen/character.h:30,
from engines/xeen/combat.cpp:25:
./engines/xeen/combat.h:166:13: note: while referencing ‘Xeen::Combat::_monsterMap’
166 |         int _monsterMap[32][32];
|             ^~~~~~~~~~~
engines/xeen/combat.cpp: In member function ‘void Xeen::Combat::moveMonsters()’:
engines/xeen/combat.cpp:455:21: warning: array subscript 32 is above array bounds of ‘int [32][32]’ …
```

XEEN: fix out-of-bounds accesses

---

backends/dialogs/gtk/gtk-dialogs.cpp

One thing that's always bothered me about the GTK+ dialogs is that the main window doesn't get updated while they are open. At least for me this causes ugly trails in the main window of anything that's moved across it while the dialog is open.
This patch adds an idle handler to keep the main window updated.
Maybe the idle handler should be part of the GtkDialogManager class, but https://stackoverflow.com/questions/21478803/member-function-as-callback-function-to-g-signal-connect suggested that it might be more portable to keep it outside the class? I don't know for sure.
I'd be grateful for feedback for anyone more familiar with GTK+ than me. (Which would be most people familiar with GTK+ at all.)

BACKENDS: DIALOG: GTK: Keep main window updated during GTK+ dialog

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp

Added fallback for SDL surface backend in case lack of VSYNC.
Missing VSYNC is possible in case SDL renderer doesn't support, like dummy driver or system GFX driver not able (broken) or can not enable it (lack VSYNC on output).
Tested only with "SDL_VIDEODRIVER=dummy"
Along with changes added missing kFeatureVSync functionality for getFeatureState()

SURFACESDL: Implemented fallback in case lack of VSYNC

---

engines/director/lingo/lingo-patcher.cpp

The `changedrive` patch is currently necessary as the current `FileIO` implementation will blindly check for invalid characters in filenames.

DIRECTOR: Add patches to get Windows version of A Silly Noisy House in-game

---

engines/director/resource.cpp
engines/director/util.cpp
engines/director/util.h

DIRECTOR: decode movie paths before loading

---

engines/director/cast.cpp

While this should definitely be a warning, I don't think it should be an error that prevents execution from continuing.
I'm running into this in Aquaplanet, whose mystery resource I haven't figured out yet, but I'm able to get in-game if I allow this to continue.

DIRECTOR: do not error on missing cast resource

---

engines/director/castmember.cpp
engines/director/channel.cpp
engines/director/sprite.cpp
engines/director/sprite.h

Sprites stored in frames are referenced by position (minus the
registration offset), width and height. Film loops are the same. As
such, fix the bounding box calculation for the film loop to use the
correct sprite positions (e.g. center for bitmaps), then fix the
subchannel generator to take these into account.

DIRECTOR: Fix position of film loop subchannels

---

engines/director/detection_paths.h
engines/director/detection_tables.h
engines/director/lingo/lingo-patcher.cpp

Additionally correct a few whitespace issues (tabs following spaces) and at least one spelling mistake

DIRECTOR: Add more games, fix some entries

---

engines/xeen/dialogs/dialogs_spells.cpp

Steps to reproduce:
- bring the casting dialog while not in combat
- try selecting another character
→ instead of changing the caster, the spell is aborted

XEEN: fix caster selection during non-combat spell casting

---

engines/saga/music.cpp

This attempts to fix the music looping regression described in https://forums.scummvm.org/viewtopic.php?t=16434
See commit message for details about where the regression came from.
I was tempted to commit it right away, but I'd appreciate if someone much more familiar with Inherit the Earth could comment on it first. After that, it's probably a good candidate for the 2.5 branch as well.

SAGA: Fix ITE digial music looping regression

---

engines/director/detection_tables.h

This adds the Dutch Windows version of Four Seasons in Pepperon Village, titled "Op avontuur in kabouterstad". Like the French version, it seems to be either 100% compatible or very close to it.

DIRECTOR: add Dutch version of Pepperon

---

.github/workflows/ci.yml
devtools/create_project/msvc.cpp

The MSVC builds have been failing because PCRE changed their download server. https://github.com/microsoft/vcpkg/issues/21201
Fixed by updating vcpkg commit and dropping the "d" from the libjpeg-turbo debug library. There's no longer a suffix on this library when buildling with vcpkg.
I'm doing this as a PR so that someone with access can update the lib filename in http://downloads.scummvm.org/frs/build/scummvm_libs_2015.zip

CI: Fix MSVC builds

---

.gitignore

A few other devtools-generated data files that aren't tracked in git are in this `.gitignore` to prevent them showing up as untracked files to git. I think it makes sense to add these two files as well. They're generated by two scripts in `devtools`.

DEVTOOLS: add Mac fonts to gitignore

---

engines/bbvs/detection.cpp

Fixes bug tracker #13068 https://bugs.scummvm.org/ticket/13068
This is only the detection part.
As mentioned in the bug tracker, the demo suffers from missing updates to the main window, see screenshot there.
Should i open a new tracker item for this bug?
Where should i upload the demo data?
Thanks

BBVS: Add another Loogie demo variant

---

engines/director/detection_tables.h

The Bandai Kawara-ban Vol 3 disc was submitted before the Mac data fork size calculation was fixed; these need to be updated so they're still recognized. Another couple things:
* I missed that the Space Station Warlock demo was standalone the first time around.
* The web punycoding for the MS Seifuku demo is isn't recognized on filesystems that present Unicode in decomposed form, since the `で` is reported by the filesystem as `て` followed by a dakuten combining character. I've added a second line, though IMO at some point figuring out at the ScummVM level and/or puncode handling level how to handle this on filesystems that use decomposed representation would be great.

DIRECTOR: fix Bandai filesizes

---

devtools/dumper-companion.py

The `mac` command in the Python dumper companion tried to handle filename encodings, which is, if I'm being honest, a fool's errand. This led it to error out on certain Japanese filenames, for example:
```
Resource in ÇœÇªÇ∑ÇØPPC
Traceback (most recent call last):
File "/Users/mistydemeo/github/scummvm/devtools/dumper-companion.py", line 488, in <module>
exit(args.func(args))
File "/Users/mistydemeo/github/scummvm/devtools/dumper-companion.py", line 404, in collect_forks
to_file.write(file_to_macbin(file, to_filename.encode("mac_roman")))
File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/encodings/mac_roman.py", line 12, in encode
return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode …
```

DEVTOOLS: fix encoding with the dumper companion `mac` command

---

devtools/dumper-companion.py

This is the Python implementation of https://github.com/scummvm/scummvm-web/commit/26ba196db17c3d3b3f39b8ef7f78b29f4cdc3884.

DEVTOOLS: Return string encoded in Mac-Roman on error

---

backends/platform/sdl/opendingux/README.BUILD
backends/platform/sdl/opendingux/build_odbeta.sh
backends/platform/sdl/opendingux/opendingux.mk
configure
dists/opendingux/make-opk.sh

This PR embeds the various platforms supported by OpenDingux beta directly in the configure script.
This will allow the buildbot to include builds for these platforms as it can't use the release build script.
In addition some autodetections are enabled back to allow make use of the features on GCW0 (Fluidsynth, Theora, SDL2) and OpenGL ES2 is enabled on GCW0 as the toolchain provides Mesa.
Some small fixes are provided to the make-opk script and the build_odbeta is reworked to make use of configure changes and to make use of arguments instead of environment variables to create the build.

OPENDINGUX: Various improvements to building process

---

devtools/dumper-companion.py

macOS has trouble with encodings for non-MacRoman HFS filesystems, which means the `mac` command's punycode option generates gibberish when given languages like Japanese, etc. I wanted a good solution and ended up landing on this. It requires the user to specify the source encoding on the disc so that it can determine how to reinterpret the text. The reason for that is a little annoying...
When not able to figure out the correct encoding for legacy non-Unicode HFS filesystems, which is most of the time, macOS interprets filenames as though they're MacRoman. Once mounted, the files are presented via all of the macOS filesystem APIs as though they're UTF-8. This is great for Western European languages, but falls over for other languages. For example, Japanese filenames will be rendered as …

DEVTOOLS: allow correcting filenames when punycoding

---

common/quicktime.cpp
common/quicktime.h
engines/mohawk/riven_video.cpp
video/qt_decoder.cpp
video/qt_decoder.h

The KQ6 Mac QuickTime opening movie doesn't play correctly in ScummVM. There are frozen frames and other problems at transitions between tracks and edits. https://bugs.scummvm.org/ticket/11085
There are two bugs preventing correct playback:
1. A workaround from three years ago for a video in a Spanish version of Riven. The workaround has several problems and it breaks valid movies. (Added in: b8abe400850a23d12fe5cdc24d7106820d0f13fd)
2. QuickTimeDecoder doesn't correctly handle tracks where the first edit is empty (a delay) and the second has a `mediaTime` offset. `mediaTime` is ignored in this case, causing the first frame of the media to be played instead of the intended later frame.
I've limited the Riven workaround to just Riven through a flag, this mitigates that regression. It's …

VIDEO: Fix QuickTimeDecoder bugs

---

NEWS.md
backends/platform/sdl/win32/win32.cpp
backends/platform/sdl/win32/win32.h
backends/platform/sdl/win32/win32_wrapper.cpp
backends/platform/sdl/win32/win32_wrapper.h
backends/saves/windows/windows-saves.cpp
backends/saves/windows/windows-saves.h
gui/options.cpp

This PR adds a "portable mode" to Windows builds. This has been requested several times and produced some long threads in the forums. The idea is that if someone manually puts a scummvm.ini file in a directory along with the exe, ScummVM will operate in a self-contained portable mode and use that config file and directory for logs/saves/screenshots. In other words: in portable mode, ScummVM won't touch the user profile directory.
I'm not the one asking for this feature but I see why it's wanted, it opens up interesting possibilities for people to play with. I can think of some experiments of mine it would help with. Being able to easily have a self-contained copy of highly configurable software is still in fashion! More importantly: it's pretty easy to implement given the recent cleanups …

WIN32: Add Portable Mode

---

engines/grim/emi/sound/mp3track.cpp
engines/grim/lab.h
engines/hadesch/rooms/monster/projectile.cpp
engines/hadesch/rooms/riverstyx.cpp
engines/myst3/database.cpp
engines/nancy/resource.cpp
engines/pegasus/neighborhood/mars/mars.cpp
engines/saga2/grequest.cpp
engines/saga2/intrface.cpp
engines/saga2/path.cpp
engines/saga2/tilemode.cpp
engines/stark/formats/iss.cpp
engines/stark/formats/xarc.cpp

Using clang-tidy modernize-use-override

ENGINES: Use override

---

engines/xeen/dialogs/dialogs_items.cpp

Use the destination character's name.

XEEN: fix "backpack is full" dialog string

---

engines/xeen/dialogs/dialogs_exchange.cpp

Don't try to exchange a character with themself...
Steps to reproduce:
- open the character panel
- press 'e' to exchange
- select the current character
→ trigger the assert in https://github.com/scummvm/scummvm/blob/master/engines/xeen/item.cpp#L138 because the source and destination array are the same.

XEEN: fix possible crash in exchange dialog

---

engines/ngi/gfx.cpp
engines/ngi/gfx.h

The default destructor did not freed the picture data belonging
to the PictureObject instances, causing many memory leaks.
PR note: I controlled before and after with Valgrind.

NGI: Fix memory leak in PictureObject

---

backends/graphics/sdl/sdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.h
backends/graphics/windowed.h
backends/platform/sdl/sdl-window.cpp
backends/platform/sdl/sdl-window.h

The latest version of SDL2 from git adds a new function to confine the mouse to the specified area of the screen. Currently, ScummVM confines the mouse position by warping the mouse manually when it's grabbed and a stretch mode that leaves empty space is enabled, but that doesn't work with Wayland. While I did initially encounter issues with this in the Fedora 35 + Plasma 3.22.5 VM that I set up for Wayland testing, it seems to have been resolved somehow.
See also: https://github.com/libsdl-org/SDL/issues/4822

SDL: Use SDL_SetWindowMouseRect to confine the mouse area

---

NEWS.md
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/opengl-graphics.h
backends/graphics/opengl/texture.cpp
backends/graphics/opengl/texture.h
configure
graphics/conversion.cpp
graphics/conversion.h

TODO:
- ~Dirty rects don't always redraw correctly~
- ~Cursors aren't yet scaled~
- Needs testing on big endian with GLESv2
Fixes [Trac #12848](https://bugs.scummvm.org/ticket/12848).

OPENGL: Implement scaler support

---

engines/director/lingo/lingo-patcher.cpp

This adds a patch for Difficult Book Game (henachoco03) that fixes up a couple ambiguous lines that are being misparsed. From talking with djsrv, this is parsed differently between D3 and D4/later, and would be really difficult to handle properly.
I've also added the ability to handle Punycode filenames in patches.
This is one of three fixes needed to promote this game to fully working status.

DIRECTOR: patch henachoco03

---

engines/director/score.cpp
engines/director/sound.cpp

I've found a Director 3 game that tries to play back audio on channel 3, which currently leads to an assertion failure - see #3539. I'm not entirely clear how it was determined that older Director versions had only two channels; looking at the commit history D4 was given 4 channels in 88d8577cb3a1634bd23ead85ccfec8375d293aed, but it's not really clear to me if it was determined for sure that pre-D4 should only have two channels.
cc @moralrecordings for thoughts, since you bumped the number of channels for D4.

DIRECTOR: allocate more than 2 audio channels for earlier Director versions

---

engines/director/lingo/lingo-events.cpp

These events are handled by the primary handler above, and in D2/D3 they don't have other handlers. However, not being handled at all in the switch statement means it's falling through to the default case below and printing spurious "unhandled event" logs.

DIRECTOR: add stub handler for some events

---

gui/gui-manager.cpp

Currently, with vsync enabled, the mouse cursor in the GUI Launcher feels very sluggish on a 60 Hz display. The issue is that the artificial waiting/frame times in the GUI launcher code cause a race condition between VSync an GUI manager's own frame timing.
This patch fixes this by skipping our own frametime calculation with VSync enabled. Hardcoding it to `delayMillis(1);` is required here since otherwise, ScummVM would always max out one CPU thread entirely.

GUI: Fix cursor stuttering with vsync enabled

---

backends/graphics/opengl/opengl-graphics.cpp

In the long term, a better way to fix the issue is to split the `ScalerPluginObject` class into two parts, so that each texture can have a separate instance of the scaler's internal state. For now, though, reverting this commit fixes [Trac #13086](https://bugs.scummvm.org/ticket/13086). The normal and advmame scaler were the only ones that supported cursor scaling to begin with, so this shouldn't be a major loss.

Revert "OPENGL: Implement cursor scaling"

---

graphics/VectorRendererSpec.cpp

The code would create a rectangle of width+1 by weight+1, resulting in buffer overflows when drawing at the bottom limit of a surface.
The crash occurs when not using the builtin/classic theme, since 6850297c3838c9d527429920e585911aa91e8c05 (which adds 2 buttons at the bottom of the GUI):
```
==280335==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x1488d826e86c at pc 0x562c57f47f34 bp 0x7ffc65483590 sp 0x7ffc65483580
WRITE of size 2 at 0x1488d826e86c thread T0
#0 0x562c57f47f33 in void Graphics::colorFill<unsigned short>(unsigned short*, unsigned short*, unsigned short) graphics/VectorRendererSpec.cpp:452
#1 0x562c57f0da70 in Graphics::VectorRendererAA<unsigned short>::drawInteriorRoundedSquareAlg(int, int, int, int, int, unsigned short, Graphics::VectorRenderer::FillMode) …
```

GRAPHICS: fix off-by-one errors when drawing a rounded rectangle

---

engines/scumm/imuse_digi/dimuse_defs.h
engines/scumm/imuse_digi/dimuse_dispatch.cpp
engines/scumm/imuse_digi/dimuse_engine.cpp
engines/scumm/imuse_digi/dimuse_engine.h
engines/scumm/imuse_digi/dimuse_internalmixer.cpp
engines/scumm/imuse_digi/dimuse_tracks.cpp
engines/scumm/imuse_digi/dimuse_wave.cpp
engines/scumm/smush/smush_player.cpp

Hiya, this PR contains several minor fixes for the DiMUSE engine:
1. A fix for [this ](https://bugs.scummvm.org/ticket/13084) bug;
2. A fix for an issue in which streamZone aren't correctly deallocated when terminating the engine or releasing a dispatch;
3. A fix for both DiMUSE streams being kept busy after skipping a SMUSH video in DIG full version (I simply forgot to implement the correct behavior...);

SCUMM: DiMUSE: Fix several minor bugs

---

backends/audiocd/audiocd.h
backends/audiocd/default/default-audiocd.cpp
backends/audiocd/default/default-audiocd.h
engines/engine.cpp
engines/engine.h
engines/scumm/scumm.cpp

ScummVM currently warns that the FM Towns SCUMM demos (indyzak and zakloom) are missing the audio tracks. That's because we always check for track 1, and neither demo has that.
This could be extended further, if we want to, e.g. if we want to verify that _all_ tracks are present instead of just one. But I don't know if that's worth bothering with?

Allow the checking of other audio tracks than number 1

---

common/stuffit.cpp
common/stuffit.h
engines/kyra/detection_tables.h
engines/kyra/engine/util.cpp
engines/kyra/engine/util.h
engines/kyra/resource/resource.cpp
engines/kyra/resource/resource.h
engines/kyra/resource/resource_intern.cpp
engines/kyra/resource/resource_intern.h
engines/kyra/sound/sound_mac_lok.cpp
engines/kyra/sound/sound_mac_res.h

The Macintosh version of The Legend of Kyrandia that I have is a non-talkie version distributed on CD. This version is supported now that arthxx added a music driver for it.
Annoyingly though, the game data files aren't unpacked on the CD. Instead, everything is inside a self-extracting StuffIt installer. This means that in order to play the game in ScummVM, you have to install the game (probably using a Mac emulator) and then copy the files from the emulated hard disk. Not the smooth kind of experience we want people to have.
This is my attempt at adding support for playing the game directly from the files on the CD, without having to go through the installation process. This is the first time I've worked with the Archive class, but hopefully I got it right.
Obviously it needs more …

KYRA: Don't require the Mac version of Legend of Kyrandia to be installed

---

engines/director/lingo/lingo-preprocessor.cpp

The continuation marker is at the same codepoint in MacRoman as the half-width katakana tsu (ﾂ) in MacJapanese. Since parsing happens after Lingo source has been converted from its original encoding to Unicode, the continuation marker is being translated into the wrong character and treated as a syntax error. This patch works around it by checking for ﾂ and translating it back into the continuation character. While this could eventually be fixed by having the parser work on the raw bytes of the Lingo source instead of decoded strings, this is good enough for now to fix the affected games. I've tested several games with the issue - Difficult Book Game (henachoco03), The Seven Colors (the7colors), and Oz (erikotamuraoz).
Here's what the source code with the wrong continuation marker looks …

DIRECTOR: fix Japanese continuation marker while preprocessing

---

configure

As discussed here: https://github.com/SerenityOS/serenity/commit/59b2bac3a53a5b7605fc85d10b307147f1702635
This adds SerenityOS as a valid POSIX target for ScummVM. ScummVM is supported as a port in SerenityOS, and this change allows us to remove the only patch needed to get everything to compile.
CC @sev-

BUILD: Support SerenityOS in configure script

---

backends/graphics/graphics.h
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/opengl-graphics.h
backends/graphics/opengl/texture.cpp
backends/graphics/opengl/texture.h
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h
backends/modular-backend.cpp
backends/modular-backend.h
common/system.h
graphics/scaler/dotmatrix.cpp
graphics/scaler/dotmatrix.h
graphics/scaler/edge.cpp
graphics/scaler/edge.h
graphics/scaler/hq.cpp
graphics/scaler/hq.h
graphics/scaler/normal.cpp
graphics/scaler/normal.h
graphics/scaler/pm.cpp
graphics/scaler/pm.h
graphics/scaler/sai.cpp
graphics/scaler/sai.h
graphics/scaler/scalebit.cpp
graphics/scaler/scalebit.h
graphics/scaler/tv.cpp
graphics/scaler/tv.h
graphics/scalerplugin.cpp
graphics/scalerplugin.h
gui/options.cpp

`ScalerPluginObject` now provides a function to create a `Scaler` object, which can have multiple independent instances that are owned by the backend instead of the plugin system. More work will be needed for the HQ scaler, which uses global variables for the assembly code, but once this is complete, it should be possible to restore cursor scaling in OpenGL mode.

GRAPHICS: Split ScalerPluginObject into two classes

---

engines/engine.cpp
engines/savestate.cpp
engines/savestate.h

Some engines (like kyra) return a SaveStateDescriptor with slot assigned,
even when the slot is free. The indication for an empty save is empty
description on these cases.

ENGINE: Suppress autosave overwrite warning when description is empty

---

engines/director/detection_tables.h
engines/director/lingo/lingo-patcher.cpp

This applies the henachoco03 patches to the demo. The same ambiguous syntax occurs there, but on different line numbers and in different filenames. The original patch was added in #3545.
I've also added a second commit that fixes the file sizes for the demos, since they were added before the Mac file size bug was fixed.

Director apply henachoco03 patches to demo

---

engines/grim/grim.cpp

When using a keymapper in Grim Demo, the keys don't work.
Fixing the `KEYCODE_` constants make it work.
This change has not been tested in EMI.

GRIM: Fix bindings in the keymapper

---

doc/docportal/other_platforms/amigaos_4.rst

- Fixed typo in optional hardware name
- Optioned two former mandatory install steps
- Change path to user-definable and add info about settings

DOC: Update AmigaOS4

---

engines/director/detection_tables.h

This adds a second file to All the Lunar to fix the ambiguity in its `install.exe` name.

DIRECTOR: add second file to All the Lunar

---

engines/sherlock/people.cpp
engines/sherlock/tattoo/tattoo_people.cpp

This is an attempt at fixing https://bugs.scummvm.org/ticket/7090 ("SHERLOCK: Watson isn't animated while talking"). If I understand it correctly, the problem is simply that we compare the wrong strings when looking up the talking actor, and therefore he's not animated.
I don't know if this affects any other actors than Watson.
If this is the correct fix, I'd suggest we apply it to the 2.5 branch as well.

SHERLOCK: Fix missing Rose Tattoo talk animations (bug #7090)

---

engines/xeen/map.cpp
engines/xeen/sound.cpp
engines/xeen/sound.h

* remove some dead code
* fix some sounds not being correctly muted when Efx is off (e.g. vendor voices, some combat FXs)
* fix missing music when loading a save from the main menu
* fix toggling music back on
* fix sound settings not getting saved

XEEN: sound related improvements

---

engines/sherlock/tattoo/tattoo_map.cpp

This attempts to fix the bug described in https://bugs.scummvm.org/ticket/10850
Since the map always snaps to its saved position, there's no need to show the upper left corner for a split second first.

SHERLOCK: Fix Rose Tattoo glitch when opening map

---

engines/sherlock/sound.cpp

This fixes the doorbell sound at Lord Brumwell's mansion so that it's played at 11000 Hz instead of 1100 Hz. This seems to match the behavior of the 3DO version pretty well, though since that's not supported by ScummVM I've only seen YouTube playthroughs.
This fixes https://bugs.scummvm.org/ticket/10838

SHERLOCK: Workaround for bad doorbell sound in Serrated Scalpel

---

backends/graphics3d/android/android-graphics3d.cpp
backends/graphics3d/android/android-graphics3d.h
backends/graphics3d/android/texture.cpp
backends/graphics3d/android/texture.h

With this PR, pausing and resuming a 3D game is fixed.
The game GLES state is preserved across drawing calls to ensure a consistent display in all cases.
The program and texture are unbound after the draw to prevent the engine from using them by accident.
Finally some cleanup is done and the HiDPI factor is applied to have a consistent overlay look'n'feel between 2D and 3D games.

ANDROID: New fixes for 3D support

---

engines/macventure/gui.cpp

This silences a warning in MSVC about an unsafe operation.

MACVENTURE: Correct datatype for active flag

---

engines/director/detection_paths.h
engines/director/detection_tables.h

This removes several entries from the Director detection paths and switches over to the new in-place path specification that was added recently.

DIRECTOR: remove some detection_paths entries

---

engines/sherlock/tattoo/tattoo.cpp

In The Case of the Rose Tattoo, certain rooms have a hard-coded haze. This is loaded in TattooEngine::startScene(), but this was bypassed if the room was loaded through the overhead map. (I think that only happens for Cleopatra's Needle.) This pull request fixes that by handling the map case first.
If this is the correct fix (and I've convinced myself that this is likely), it should probably be fixed in 2.5 as well.

SHERLOCK: Fix missing haze when going to Cleopatra's Needle

---

engines/grim/gfx_tinygl.cpp
engines/myst3/gfx_tinygl.cpp
engines/playground3d/gfx_tinygl.cpp
engines/stark/gfx/tinygl.cpp
graphics/tinygl/tinygl.h
graphics/tinygl/zdirtyrect.cpp
graphics/tinygl/zgl.h

This seems to work, but is in draft mode until it can be tested more thoroughly.

TINYGL: Use the existing list of rectangles when copying to the screen

---

audio/mixer.cpp
audio/mixer.h
audio/mixer_intern.h
backends/mixer/null/null-mixer.cpp
backends/mixer/sdl/sdl-mixer.cpp
backends/platform/android/android.cpp
backends/platform/android3d/android.cpp
backends/platform/ios7/ios7_osys_sound.cpp
backends/platform/iphone/osys_sound.cpp
engines/scumm/imuse_digi/dimuse_engine.cpp
engines/scumm/imuse_digi/dimuse_engine.h
engines/scumm/imuse_digi/dimuse_tracks.cpp

For [this bug](https://bugs.scummvm.org/ticket/13080) to be fixed, I needed to avoid setting an arbitrary `_maxQueuedStreams` value in `IMuseDigital::tracksCallback()`, and instead do a proper calculation based on the audio buffer size.
To do that I needed the audio backend to pass the buffer size along to the mixer (with which DiMUSE can communicate). This has been done for all the ports/platform I could be able to test. For the others I left a fallback value of 4 for the maximum number of queued streams (until someone can test all the other platforms).
The changes in this PR have also been tested with various manually inserted values for `output_rate` (22050, 44100, 48000) and `audio_buffer_size` (from 512 up to 8192) in the `scummvm.ini` config files, and I can happily report that …

SCUMM: DiMUSE: Fix bug #13080

---

engines/sherlock/detection_tables.h

This removes entries for "music.lib" in cases where "talk.lib" was already present. In all these entries, the "music.lib" hash given is identical to the English CD version. In a few cases, such as with the German floppy version (real MD5 of `8c91a1a6ea98d0a890bc2f9376ec4bf0`, 159485) and one of the German CD versions (as in https://bugs.scummvm.org/ticket/12992), this was incorrect.

SHERLOCK: Remove music.lib from detection entries

---

engines/director/sound.cpp

I've run into one game, Ganbare! Inu-chan (ganbareinuchan), which doesn't explicitly stop sounds before playing new ones in the same channel. With the original Director runtime, the previous sound in that channel is automatically stopped. In ScummVM, without this patch, the previous sound keeps playing and the new sound is added on top. It leads to multiple background songs playing simultaneously.

DIRECTOR: stop sound before playing stream

---

engines/sherlock/scalpel/scalpel_darts.cpp

The power bars in the Serrated Scalpel darts minigame moves a lot slower in ScummVM than they do in the original, making the game trivially easy since you're pretty much guaranteed to always score 25 or 50 points per throw if you want to. They also move a lot slower than when your opponent plays.
The reason for this is that in addition to the regular delay, ScummVM adds an extra delay when polling events. Changing that makes it match the original speed much better.
This makes the minigame more frustrating, of course, but as far as I know it's completely optional since you can blackmail the bartender for the information instead.

SHERLOCK: Make the Serrated Scalpel darts minigame harder (to better match original)

---

backends/graphics/android/android-graphics.cpp
backends/graphics3d/android/android-graphics3d.cpp
backends/graphics3d/android/android-graphics3d.h
backends/graphics3d/android/texture.cpp
backends/graphics3d/android/texture.h
backends/platform/android/jni-android.cpp
backends/platform/android/jni-android.h
backends/platform/android/org/scummvm/scummvm/ScummVM.java
backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java

This PR makes the 3D subsystem more flexible for various texture formats.
In addition, the 3D graphic backend is removed its 2D features and the cursor scaling is fixed.

ANDROID: Use 24/32 bits textures when possible

---

engines/sherlock/talk.cpp

This attempts to fix a regression from 2175ee951ab2a62a0e3a3c6c28341fe447514072. I'm not sure of the exact circumstances, but I think it may be when a character starts talking to you. The first time I saw it was entering the scene of the murder at the beginning of the game. Lestrade greets you, and afterwards the user interface isn't displayed correctly.
I've played through almost the entire game with this fix, so I'm fairly confident that it works the way it should.

SHERLOCK: Fix Scalpel user interface regression

---

engines/sherlock/talk.cpp

I didn't encounter this bug until I met Lord Brumwell. Unlike most characters, he actually initiates conversation with you. This puts the engine in "talk mode". But if you had, say, the inventory window open at the time, it will first close that window. That puts the game in "standard mode".
Because the code then broke out of a loop instead of allowing it to run all of its final iteration, the game was never put back in "talk mode". It printed the conversation topic, but you couldn't click on it. And then the user interface got all messed up.
This is the fix that got the least testing since this is pretty close to the end of the game. But it seems pretty straightforward to me.

SHERLOCK: Fix Scalpel user interface being left in wrong mode

---

backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java

On a Chromebook, the keyboard may be present but hidden (not available for
use) because the device is flipped around in Tablet mode.  In this case we want
the soft keyboard to be available.  This change also hides the soft keyboard
button if the hardware keyboard is available, since it doesn't do anything.
Fixes #13138.

ANDROID: Fix softkeyboard button for Chromebooks

---

engines/sherlock/fonts.cpp

When calculating the max height and width of characters in a font, we only took the size of the images into consideration. Not how much they were offset when drawing them. (And even with this patch, we don't take _yOffsets[] into consideration. I don't know if we have to?)
This is closer to what charWidth() and charHeight() already does, but those add 1 for reasons unknown to me. (Also, if you want to use them instead, not that they will call translateChar().)
This fixes a tiny glitch that I spotted when talking to a character who had a lot of things you could ask about. Scrolling down, the "Up" button would be enabled. When disabling it, the bottommost pixel of the "p" was still white.
I'm a bit concerned there may be things that depend on the font height that _could_ be broken by this. …

SHERLOCK: Calculate font height/width more accurately

---

backends/platform/android/android.cpp

This fixes a conceptual issue in which, while all the other platforms are handled correctly, Android used the frame size as the effective buffer size, a thing which caused the assertion in `mixer.cpp:mixCallback()` to be triggered on some devices. This was fixed on commit https://github.com/scummvm/scummvm/commit/466c8b8c76df8584f612f488cc5df4a0f9e25d72, but this meant I had effectively forgotten both to do what was done in the commit, and to divide the value passed to the mixer by `wordSize * numChannels`, or in our case, four.
This PR fixes the latter issue so that when the `getOutputBufSize()` function is called from Android it correctly yields the frame size instead of the byte size.

ANDROID/AUDIO: Convert the output buffer size value given to the Mixer from bytes to frame size

---

engines/sherlock/scalpel/scalpel_talk.cpp
engines/sherlock/talk.cpp
engines/sherlock/tattoo/tattoo_talk.cpp

This is an attempt at fixing long-standing bug https://bugs.scummvm.org/ticket/10931
If I understand it correctly, when you initiate a conversation (at least one where you get the first word), the engine pushes the current animation for the character on a stack. It may then push further animations while displaying the character portrait, but once the conversation is done it should be able to pull the original animation back from the stack.
But because of some unintentional code duplication, what it pulled at the end was the animation (or lack thereof) used when talking to you. You could see this pretty clearly at the scene of the murderer: Talk to the police, and he'll stop swinging his baton. He won't resume when the conversation is over, until you leave and re-enter the room.
Most of …

SHERLOCK: Fix Scalpel animations not being resumed after conversation (bug #10931)

---

engines/director/detection_tables.h

This adds a very large number of new games, mostly but not entirely Japanese. I can write out some detailed compatibility notes on each game if requested. This also adds a new set of demos, which I can make available to ScummVM devs.
A few of these discs are sets of digital/interactive artwork and have no menu, so they have many files per detection entry.
I've also fixed Mac filesizes for a few games I tested out of my collection when I discovered that they were added before the Mac filesize bug was fixed.

DIRECTOR: many more games

---

NEWS.md

Just fixes a small typo in the word "license".

JANITORIAL: Fix typo

---

engines/scumm/debugger.cpp
engines/scumm/debugger.h
engines/scumm/imuse_digi/dimuse_engine.cpp
engines/scumm/imuse_digi/dimuse_engine.h
engines/scumm/imuse_digi/dimuse_tables.cpp
engines/scumm/scumm.cpp

Ahoy!
This PR:
1. Adds a debugger for DiMUSE: you can now play and stop SFX/music, change parameters and check various internal information (that is, for all SCUMM v7-8 games);
2. Adds a missing sequence table entry for FT (it actually paid to implement this debugger); no matter how you can triple check a thing, you will always miss something :-)
3. Moves some DiMUSE specific code from SCUMM to DiMUSE itself, and removes a redundant function call to `diMUSEProcessStreams()` (now it is coherent with the interpreters).
EDIT: I forgot to say, the debugger can't currently tamper with speech files because in order to play those you would need the filename; needless to say, there's too many of those and I can't simply print a list on the console :-) I'll have to think of a clever way to do that

SCUMM: DiMUSE: Add a debugger/player and fix oversights

---

backends/fs/psp/psp-stream.cpp
backends/platform/psp/psp.spec
backends/plugins/psp/psp-provider.cpp

The new PSP toolchain automatically links system libraries which wasn't
the case before. The ordering of libraries builtin in GCC and our spec
file collided. This fixes the order.
PSP SDK includes time.h so it needs an exemption.
A warning was emitted about a if without curly braces which are needed.
The changes compile with both the old and the new toolchain. No test has been done.

PSP: Fix build failures with latest PSP toolchain

---

engines/director/detection_tables.h

From this CD: https://www.discogs.com/release/28434-EBN-Telecommunication-Breakdown
The data track was an absolute pain to get at; it's stored in the pregap to an audio track. Never seen that before.
It boots, but immediately halts with several early Lingo errors.

DIRECTOR: add EBN - Telecommunication Breakdown

---

graphics/scaler/hq.cpp
graphics/scaler/hq.h
graphics/scaler/hq2x_i386.asm
graphics/scaler/hq3x_i386.asm

This is considered as a good practice to not have relocations in text segment.
The resulting binary is now completely PIC and can easily be relocated at any address (ASLR).
After a quick benchmark done on real game, the performance seems to be equivalent if not faster to the older assembly code.
The C++ implementation is still around 3 times slower even in x86_64 mode (so with SSE2 extensions enabled).

GRAPHICS: Make HQx ASM scalers relocations free

---

engines/cge/bitmap.cpp
engines/cge/cge_main.cpp
engines/cge/fileio.cpp
engines/cge/fileio.h
engines/cge/sound.cpp
engines/cge/talk.cpp
engines/cge/text.cpp
engines/cge/vga13h.cpp
engines/cge2/bitmap.cpp
engines/cge2/cge2_main.cpp
engines/cge2/fileio.cpp
engines/cge2/fileio.h
engines/cge2/hero.cpp
engines/cge2/map.cpp
engines/cge2/sound.cpp
engines/cge2/talk.cpp
engines/cge2/text.cpp
engines/cge2/vga13h.cpp

It doesn't need it and when linked with detection and with UBSan enabled build fails because CGEEngine and CGE2Engine aren't linked in

CGE/CGE2: Don't pass the engine object to EncryptedStream

---

configure

This new configure flag allows to use the [undefined behavior sanitizer](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) easily.

CONFIGURE: added --enable-ubsan to enable the undefined behavior sanitizer

---

gui/gui-manager.cpp
gui/launcher.cpp
gui/widgets/grid.cpp

These were found with ASan.
I am not sure why `themepath` and `iconspath` handling are different.

GUI: Fix various memory leaks related to grid widget

---

graphics/cursorman.cpp
graphics/fonts/ttf.cpp
gui/widgets/grid.h

These errors were detected with UBSanitizer

GRAPHICS/GUI: Fix various undefined behaviours

---

devtools/create_project/cmake.cpp
devtools/create_project/codeblocks.cpp
devtools/create_project/create_project.cpp
devtools/create_project/msvc.cpp

The feature name didn't match with other code.

CREATE_PROJECT: Consistent name for zlib

---

devtools/create_project/cmake.cpp
devtools/create_project/create_project.cpp
devtools/create_project/msvc.cpp

The feature name was inconsistent with the main build system.

CREATE_PROJECT: Fix feature name for freetype

---

engines/scumm/players/player_v2cms.cpp

Possible fix for bug #10696
Reason for not playing the Scumm Bar music again, after entering the kitchen, seemed to be that the _loadedMidiSong var did not clear its value, despite the music being stopped when entering the kitchen. Same issue would happen exiting the bar from the external door and re-entering; Same issue seems to be with church (mentioned in the bug ticket).

SCUMM: Fix CMS not playing a music midi track again

---

.gitattributes

Needed when core.autocrlf is set on Windows, and building with WSL.

JANITORIAL: Force LF EOL for shell scripts

---

devtools/create_project/cmake.cpp

This mutes the following warning:
```
CMake Warning (dev) at CMakeLists.txt:1581 (target_sources):
Policy CMP0076 is not set: target_sources() command converts relative paths
to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
the cmake_policy command to set the policy and suppress this warning.
An interface source of target "scummvm" has a relative path.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

DEVTOOLS: Bump minimum cmake version to 3.13

---

engines/metaengine.h

```
In file included from C:/Projects/scummvm/common/array.h:25,
from C:/Projects/scummvm/common/achievements.h:25,
from C:/Projects/scummvm/engines/metaengine.h:25,
from C:/Projects/scummvm/engines/advancedDetector.h:25,
from C:/Projects/scummvm/engines/sci/detection.cpp:22:
C:/Projects/scummvm/common/scummsys.h:400:44: warning: attribute ignored [-Wattributes]
400 |                 #define WARN_UNUSED_RESULT [[nodiscard]]
|                                            ^
C:/Projects/scummvm/engines/metaengine.h:565:16: note: in expansion of macro 'WARN_UNUSED_RESULT'
565 |         static WARN_UNUSED_RESULT bool readSavegameHeader(Common::InSaveFile *in, ExtendedSavegameHeader *header, bool skipThumbnail = true);
|                ^~~~~~~~~~~~~~~~~~ …
```

ENGINES: Fix GCC warnings

---

engines/savestate.cpp

Save names in Groovie are limited to 15 characters, and it's probably not the only engine with a similar limit, I wanted to see if there was any interest in a global fix that could help many engines.
The length of the German translation for Autosave is 23 characters. This meant you would get a warning on every autosave, even though you just told it to overwrite.
I currently have it set to a minimum of 14 characters for confidence that the name is a match and not a false positive, but this could definitely be reduced.

ENGINES: Fix autosave name check

---

engines/agi/detection.h
engines/agi/detection_tables.h
engines/agi/loader_v3.cpp

Includes a change to how Mac data files are loaded for three games: Gold Rush and both Manhunter games - all AGI version 3.
I've tested this for all three games and all platforms: Amiga, Atari ST, DOS, Mac, Apple IIgs and Tandy CoCo 3. Testing involved detecting the game files, starting the game, playing the first couple screens, **restarting** the game, and quitting. Restart was tested because the resources are reloaded on restart.
I also tested the same on the fanmade V: The Graphic Adventure.
Everything seems to work fine. The ST version of MH1 hangs on startup for me, but that happens in the ScummVM 2.5.1 release as well (it's possible that I dumped the disk incorrectly). And the CoCo3 V3 games don't work yet anyway. That's a project for another day.

AGI: Add support for Mac Manhunter games

---

engines/sky/control.cpp
engines/sky/control.h
engines/sky/metaengine.cpp

Fix for bug #13218 "Can Populate More Than One Save Slot At A Time"
We use a dirty string buffer to temporary store the edited text for the selected slot

SKY: Fix saving names for non selected save slots

---

Makefile.common
backends/graphics/android/android-graphics.cpp
backends/graphics/opengl/opengl-sys.h
backends/graphics3d/android/android-graphics3d.h
backends/graphics3d/opengl/framebuffer.cpp
backends/graphics3d/opengl/framebuffer.h
backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
backends/module.mk
backends/platform/android/android.cpp
backends/platform/android/android.h
backends/platform/android3d/android.cpp
backends/platform/android3d/android.h
backends/platform/android3d/graphics.cpp
backends/platform/android3d/graphics.h
backends/platform/sdl/sdl.cpp
backends/platform/sdl/sdl.h
base/version.cpp
configure
devtools/create_project/create_project.cpp
dists/scummvm.rc
engines/grim/gfx_opengl_shaders.cpp
engines/stark/gfx/opengltexture.cpp
graphics/opengl/context.cpp
graphics/opengl/system_headers.h
graphics/renderer.cpp

With the advent of GLAD, OpenGL libraries don't need to be linked with ScummVM for those platforms.
In addition, GLAD support is known at configure step by knowing the platform to configure.
This PR also tries to merge two configure paths: the one for 2D engines, and the one for 3D engines.
It builds correctly on Linux and Android. No other tests have been done yet.
In addition, create_project still has a USE_GLES2 define and no USE_GLES_MODE.

ALL: Rework OpenGL detection

---

image/bmp.cpp
image/codecs/bmp_raw.cpp

Added support for 16 bit bitmap images (using RGB555 format). Implemented according to the algorithm documented in the link below:
https://docs.microsoft.com/en-us/windows/win32/directshow/working-with-16-bit-rgb

IMAGE: Add 16 bitmap support to raw decoder

---

gui/launcher.cpp

The current recommended and de factor behavior from both Microsoft and Apple is to have "About" menus be without trailing ellipses. Therefore, I think we should follow suit.
----
Traditionally, About menus and buttons had a trailing ellipsis. [This article](https://uxdesign.cc/dot-dot-dot-7ce6170bfc7f) demonstrates this behavior for  both Mac OS 1.0 (technically "System 1.0") and Windows 1.0.
However, current versions of macOS and Windows do not have a trailing ellipsis in About menus. Moreover, their design guidelines recommend not using them. From [Apple](https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/):
> Use an ellipsis whenever choosing a menu item requires additional input from the user. The ellipsis character (…) means a dialog or separate …

GUI: Changing "About..." button to "About"

---

audio/fmopl.cpp
audio/fmopl.h
audio/module.mk
audio/rwopl3.cpp
audio/rwopl3.h
base/version.cpp
configure
devtools/create_project/cmake.cpp
devtools/create_project/create_project.cpp
devtools/create_project/msvc.cpp
devtools/create_project/xcode.cpp

This PR adds support for the SudoMaker RetroWave OPL3 sound card
(https://www.tindie.com/products/sudomaker/retrowave-opl3-sound-card/).
This requires the retrowave library to build. I've attached Windows and 
linux x64 builds; other platforms will have to build their own 
(source at https://github.com/SudoMaker/RetroWave/tree/v0.0.9).
I've added a build feature --enable-retrowave to configure and build_project.
It would be great if someone could check if I've done that right, as I'm not 
very familiar with the build system.
On the off-chance that someone has one and wants to test it, add the following 
settings to scummvm.ini:
retrowaveopl3_bus=serial
retrowaveopl3_port=<port> f.e. COM3 or ttyACM0
We could maybe add options to the GUI for this, but for now I think this is 
fine as this …

AUDIO: Add support for RetroWave OPL3

---

engines/scumm/scumm.cpp
engines/scumm/sound.cpp
engines/scumm/sound.h

If the game is a talkie version, on which the verbs reference sounds, but it is missing the sound file, and the user chose Voice Only, a warning appears for every playback attempt.
Force subtitles on this case, to avoid these warnings.
Fixes [trac 13151](https://bugs.scummvm.org/ticket/13151)

SCUMM: Show subtitles on talkie versions without sound file

---

backends/platform/sdl/win32/win32_wrapper.cpp

`SHGetSpecialFolderPath` was introduced as part of the Microsoft Internet Explorer 4.0 Desktop Update, and is not in stock Windows 95 installations prior to OSR 2.5.
See also scummvm/dockerized-bb#43.

WIN32: Detect SHGetSpecialFolderPath at runtime

---

doc/docportal/advanced_topics/configuration_file.rst
doc/docportal/help/report_bugs.rst
doc/docportal/use_scummvm/save_load_games.rst

There are several sections in the documents that describe Windows paths. Each one of them did so in a slightly different way. This PR makes them all consistent.
Additionally, it was discovered that `%APPDATA%` resolves the same on Windows 2000/XP/Vista/7/8/10/11 (and we presume NT4). Therefore, there was no need to have separate instructions for versions before Vista.

DOCS: Consistent and simplified Windows path descriptions

---

engines/director/detection_tables.h

This adds software I've found on the Japanese "What is Macromedia Director 3.1" disc. Most are demos of things that are already in ScummVM.
One or two of these demos are already in ScummVM, but I had to correct the file size - they're from before the off-by-`0x100` Mac size bug was fixed. A few others are *close* to `0x100` off from the size of something already in ScummVM, but not exactly. I think the original submitter of those demos may need to review them to make sure those sizes are right.
Macromedia Director紹介 is a demo movie from Something Good Inc extolling the virtues of Director itself.

DIRECTOR: add more software

---

README.md

One of the links to the Supported Games wiki page had an extra `>` at the end.

JANITORIAL: Fix link in README

---

engines/ags/globals.h
engines/ags/shared/game/main_game_file.cpp
engines/ags/shared/gui/gui_main.cpp

Resolves bug #13251 for Zniw GUI language selection screen being non-interactable
The fix is from AGS' github repository commit: https://github.com/adventuregamestudio/ags/commit/a087584a26106d2fb6a17c13b0cb3f6857f4cbed
by @ivan-mogilko on 26 Dec, 2021.

AGS: Fix for transparency test being unintentionally in 3.5.0

---

backends/graphics/sdl/sdl-graphics.cpp
backends/platform/sdl/sdl-window.cpp

This PR fixes two independent, but very similar issues in how the mouse is captured to the drawable area in HiDPI mode. Both are needed for proper mouse control in scaled HiDPI mode, when the drawable area doesn't fit the whole window. I was experiencing the issues on a MacBook with Retina display, when the ScummVM graphics mode was set to OpenGL.
The mouse position is set in window coordinates, but it's clipped to the game area in drawable area coordinates. Previously, the scaling between these two was not taken into account when calculating the right/bottom edges of the game area. When the clipped mouse position was converted back to window coordinates and rounded to the nearest integer, it could end up on the edge of the game area, not inside of it. This leads to a loop in which the …

SDL: Fix mouse capture in HiDPI mode

---

backends/platform/sdl/macosx/macosx.cpp
backends/platform/sdl/sdl.cpp
backends/platform/sdl/sdl.h
backends/platform/sdl/win32/win32.cpp
base/commandLine.cpp
doc/docportal/advanced_topics/command_line.rst

This allow specifying a path where to save screenshots on the command line.
See pull request #3675 for another pull request that attempt this. That pull request was however incorrect with no feedback from the author since it was open. So I decided to rewrite it.
See also https://bugs.scummvm.org/ticket/13245.
There are two questions I have in this pull request:
1. Should we only commit the first commit or all three?
2. Is there a better way to handle the terminating '\\' or Windows, and does the code I have work for all cases.
The first commit is simple and corresponds to what was done in the earlier pull request but without the bugs (and with an update to the documentation). It adds a command line option that, when used, adds a screenshotpath to the transient domain of `ConfMan`. Since …

Allow specifying the screenshot path on the command line

---

engines/scumm/detection_internal.h

In its [officially-licensed Monkey Island Anthology](https://limitedrungames.com/products/monkey-island-30th-anniversary-anthology-pc), Limited Run Games included a corrupted fourth disk for the EGA Version of Monkey Island 1. The affected files are `903.LFL` and `DISK04.LEC`, breaking a font, the Mêlée Island map, thus making the game unplayable very early on.
Fortunately, Limited Run Games also included a [KryoFlux](https://www.kryoflux.com) dump of the same floppy, so it's possible to restore working `903.LFL` and `DISK04.LEC` files from it.  But this is out of the scope of ScummVM.
ScummVM could maybe provide a binary patch for this, but unfortunately, `903.LFL` is almost entirely corrupted, so providing a binary patch for it would make it too close to the full and copyrighted …

SCUMM: Reject the corrupted version of MONKEY1-EGA from Limited Run Games

---

README.md
gui/launcher.cpp

Rename Edit Game to Game Options and Options to Global Options to make it less confusing.
Remove ellipsis on launcher buttons.

GUI: rename options buttons

---

engines/mohawk/dialogs.cpp

Covers the tooltips for screen transitions, water effect and zip mode
The game options for the Myst game already have tooltips. I pretty much copied the ones for zip mode and screen transitions (minor edits) from those.

MOHAWK: Add tooltips for Riven game options

---

engines/agos/detection_tables.h

SUBSYSTEM: AGOS detection tables update
- NOTE that there's already a variation of this dub, but the one in this PR has a different set of MD5 checksums, it's a different flavour of the game where the patch was manually applied.
- Adding support for Simon The Sorcerer newly released Hebrew professional fan Dub patch provided in this trailer video: https://www.youtube.com/watch?v=TGveX6tTcJ4&ab_channel=HebrewAdventure
- Verified on Windows 10 by building on VS2022 Community Edition, adding the patched game and running it through the startup sequence and into the first interactable scene.

AGOS: Adding support for Simon The Sorcerer Hebrew Fan Dub Patch when applied on the Mahshevet version
