engines/agos/detection_tables.h
This reverts commit 7516504b70b3da617803d619fe6fc33f27cd6a4e.
Revert #3725 as this is an incorrect dupe of 653199a
The method used to obtain these md5's isn't correct, instead of reading the initial 5000 bytes and applying MD5 on them, I applied on the entire file, hence this litters the header file, sorry about that.
=> Revert "AGOS: Adding support for Simon The Sorcerer Hebrew dub - the Gal Shemesh patch"

engines/scumm/script_v5.cpp
NOTE: This has _only_ been tested with the English version, but dwa has promised to try the Japanese version when he has the time. It should preferrably not be merged before this.
This is an attempt at working around a script bug in the TurboGrafx-16 / PC Engine version of Loom. It works by simulating a WaitForMessage() instruction if you examine the dragon's pile of gold a second time.
In the EGA version, script-109 does something like this:
```
[0000] (14) print(1,[Center(),Text("Wow!")]);
[0009] (28) if (!Var[217 Bit 4]) {
[000E] (28)   if (!Var[219 Bit 12]) {
[0013] (40)     cutscene([0]);
[0018] (1A)     Var[219 Bit 12] = 1;
[001D] (AE)     WaitForMessage();
... The dragon responds
[03A9] (80)     breakHere();
[03AA] (C0)     endCutscene();
[03AB] (**)   }
[03AB] (**) }
[03AB] (A0) …
```
=> SCUMM: Work around TurboGrafx-16 / PC Engine Loom glitch

doc/docportal/advanced_topics/configuration_file.rst, doc/docportal/advanced_topics/understand_audio.rst
This adds info to the documentation on the RetroWave OPL3 and how to configure it.
=> DOCS: Add RetroWave OPL3 documentation

engines/icb/configure.engine
Very small change: I don't think icb can compile without having bink enabled (or I haven't figured out how).
=> Add bink as a dependency to icb

engines/scumm/script_v5.cpp
This fixes a timing bug when Mandible uses the distaff in VGA Loom. Right now it's restricted to English, because I actually have no idea if the VGA version was ever translated into other languages. And if it was, it may already work fine in those.
The bug is that it looks like the distaff only lights up three times, not four, when Mandible uses the distaff. Actually, the first two animations are so close that they look like one. The workaround is to make the second animation happen a bit later.
I'm pretty sure this happens in the original. These YouTube videos appear to be made with the original interpreter:
https://www.youtube.com/watch?v=0kEqyb5OhuQ
https://www.youtube.com/watch?v=Nk2WtuOPYwI
https://www.youtube.com/watch?v=QbokcgdGt5k
Here are savegames for that scene for all the Loom …
=> SCUMM: Work around timing bug when Mandible uses the distaff in VGA Loom

devtools/create_project/xcode.cpp
@ccawley2011 Please review. I'm not sure if this is compatible with older versions of Xcode.
=> CREATE_PROJECT: Replace c++0x with c++11 in Xcode generator

video/paco_decoder.h
This is a minor tweak to a file introduced recently in 24b7267b8beade20342822e3e29484590758beb4. The compiler flags the member function as needing `override`:
```
In file included from video/paco_decoder.cpp:29:
./video/paco_decoder.h:52:15: warning: 'loadStream' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
virtual bool loadStream(Common::SeekableReadStream *stream);
^
./video/video_decoder.h:82:15: note: overridden virtual function is here
virtual bool loadStream(Common::SeekableReadStream *stream) = 0;
^
1 warning generated.
```
A few other `override`s were added in fa9f8850bfaa8ec7dc9cf750e5861a5bf6140add, but looks like this one got missed.
=> PACo: mark method as override

engines/ngi/fullpipe/scene13.cpp
Bug [#10396](https://bugs.scummvm.org/ticket/10396) would set a wrong bridge state if someone initiated a bridge unroll and teleported before the animation was complete. This change fixes [#10396](https://bugs.scummvm.org/ticket/10396) by giving the bridge a state before it starts unrolling. While checking this bug, I found another one. Will post it on the tracker and drop the link here.
=> NGI: Fixing Rolling bridge state in Scene 13

engines/scumm/imuse_digi/dimuse_dispatch.cpp, engines/scumm/imuse_digi/dimuse_engine.cpp, engines/scumm/imuse_digi/dimuse_internalmixer.cpp, engines/scumm/imuse_digi/dimuse_internalmixer.h
This PR removes the need for a nasty hack in the Dispatch module where to avoid clicks/pops artifacts I would simply discard the last sample of every sound.  That is in fact not what the original does, and those glitches were caused by the fact I was using the InternalMixer module "as is" for the Full Throttle engine variant.
Turns out, the FT engine does not need all the edge cases that DIG and COMI use, and also does a couple things a little differently.
I took this opportunity to also slightly adjust formatting and accuracy issues in the current InternalMixer code.
Every single mixer function has been tested for regressions after these changes on all SCUMM v7-8 games.
=> SCUMM: DiMUSE: Create separate InternalMixer flow for FT engine

common/hashmap.h
Moved Node Struct from private to public in HashMap container so that it can be used with Common::find_if from algorithm.h. 
At the moment it is possible to use find_if when iterating through other containers (e.g. Common::Array) because the type contained is typically public. However, attempting to do this with a Hashmap requires the use of the inner Node struct as part of the lambda or function object signature when it is passed to find_if as a predicate.
Using a range based for loop works in C++11, which is required to use lambdas, but this alternative would not be possible for code bases still relying on earlier versions of C++ where a function object would be used.
=> COMMON: Moved Node struct from private to public in HashMap

engines/ngi/fullpipe/scene32.cpp
Implemented Cactus HasGrown check in scene32.cpp which resolves [#9669](https://bugs.scummvm.org/ticket/9669)
=> NGI: Fix Inconsistent character state (bug #9669)

backends/platform/ios7/ios7_common.h, backends/platform/ios7/ios7_osys_main.cpp, graphics/opengl/context.cpp
This adds implementation for GLAD's `loadFunc` for iOS.
Implementation use dynamic library function `dlsym` to get function pointer from running app.
Backend code still use directly linked GLES2 library, but common OpenGL and engines will use GLAD header and loader.
This allows compile all engines OpenGL code and also runtime GL API binding.
=> IOS: Added support for GLAD

base/commandLine.cpp
This makes it clear that ALSA Direct FM can be selected for AdLib
FM synthesis on the CLI.
=> BASE: Add alsa to the opl-driver CLI help

engines/saga/font.cpp, engines/saga/interface.cpp, engines/saga/introproc_ite.cpp, engines/saga/itedata.cpp, engines/saga/itedata.h, engines/saga/puzzle.cpp, engines/saga/saga.cpp
Adds support for ongoing hebrew fan translation of Inherit the Earth
will also add detection entry when the final patch will be ready
Thanks
=> SAGA: ITE: support hebrew fan translation

engines/scumm/players/player_mac.cpp, engines/scumm/saveload.cpp
I noticed that all my old savegames for the Mac version of The Secret of Monkey Island had been mysteriously broken. I tracked it down to this commit:
https://github.com/scummvm/scummvm/commit/9916b263831f20e5841275051a8ed014de1f24eb
As I understand it, in the old version of the code, mac_player.cpp would first save the channel entries, then the instrument entries. In the rewrite, the channel entries were saved twice and the instrument entries not at all.
Unfortunately I can't think of any way of fixing the savegames that were broken. This pull request is only for saving the correct data. But I'm not well versed in the save/load code, so I'm submitting this as a pull request so that others can point out if I made any mistakes along the way.
=> SCUMM: Fix regression in saving/loading Mac music

engines/scumm/scumm.cpp
According to https://bugs.scummvm.org/ticket/13354 ScummVM is running slightly too slow, so ScummVM takes too long to drown. My guess it's because ScummEngine::waitForTimer() isn't exact, and is likely to overshoot its target.
With this change, the "stop watch" will start at the time waitForTimer() theoretically finishes, so that the overshoot is factored into the measured time the main loop takes.
This seems slightly better to me than trying to fix waitForTimer(), since in the end it will probably be implemented in terms of SDL_Delay(), and that function is documented as not being completely accurate. See https://wiki.libsdl.org/SDL_Delay for details.
=> SCUMM: Attempt to improve timing (see bug #13354)

engines/scumm/script_v5.cpp
You're both still outside, so it doesn't make sense for the background sound to suddenly stop. I guess the makers of the Special Edition agree, because there the sound doesn't stop either:
https://www.youtube.com/watch?v=MPcL_eScS6I&start=4797
Of course, in the Special Edition it's much more obvious that you're still outside because of the detailed background.
The sound is stopped by the exit script. All exit scripts have the same internal number, so it tells which one by checking which room you're in and which room you're moving to.
You can test the scene with boot param 888. I've assumed that the workaround should apply to all versions that have CD audio tracks, though I've only tested it with the VGA CD version and the unofficial talkie. I don't have the FM Towns and SEGA CD versions, …
=> SCUMM: Keep playing outdoors sound in CD version of MI1 during Smirk close-up

engines/director/detection_tables.h
This has another set of new software. Some notes:
* This is the rare original Canadian release, not the American rerelease that's already in ScummVM. It has significant differences.
* Like the US release, there are separate directories for the English and French versions.
* The Wallobee Jack demo is from its own CD. It seems to have been designed for stores.
* The demo is bilingual.
* Cover disc for a magazine. It has a few pieces of software that are unique to this disc, plus a large set of demos.
* Some of these demos are for Japanese localizations of overseas games, and it seems likely that the English versions will also be Director. Some of those aren't in ScummVM yet.
* In addition to the demos, it republishes a few pieces of animation or interactive media that were originally …
=> Director: more software

engines/director/lingo/xlibs/winxobj.cpp, engines/director/lingo/xlibs/winxobj.h, graphics/macgui/macwindowmanager.cpp, graphics/macgui/macwindowmanager.h
This adds a stub implementation for a RearWindow method I saw being called by a D4 game, The Trip of Choroli. It appears to be an alternative to `IndexColorToWindow`, taking three integers for R, G, and B values instead of a single index colour.
=> DIRECTOR: add RearWindow stub

engines/director/lingo/xlibs/fileio.cpp
D3 game called "Wacky Jacks" attempts to open `Wacky Jacks:Wacky Jacks 1.2:WJPrefs`. Before this would be passed straight to File->open, now properly opens `Wacky Jacks 1.2/WJPrefs`
=> DIRECTOR: LINGO: Make the path relative before trying to open

backends/platform/sdl/sdl.cpp, engines/grim/gfx_opengl.cpp, engines/grim/gfx_opengl_shaders.cpp, graphics/opengl/shader.cpp
This PR is a batch of fixes for bugs found during AmigaOS dynamic switch (#3679) development.
Each commit should explain itself.
Latest one is bigger and only makes sure that OpenGLContext is initialized using the OpenGL version which is really chosen by SDL.
When a GLES2 implementation is loaded by SDL, framebuffer support is now properly detected.
=> Various small fixes on OpenGL

engines/wintermute/base/gfx/opengl/base_render_opengl3d_shader.cpp
Similar fix was already applied to OpenGL-without-Shaders code
See https://github.com/lolbot-iichan/scummvm/commit/7e278ebffc04eb6689ae217cfed4f796520b162a
=> WINTERMUTE: Remove halfpixel offset in OpenGL+Shaders

backends/graphics/sdl/sdl-graphics.cpp, backends/platform/android/android.cpp, backends/platform/android/android.h, backends/platform/sdl/sdl.cpp, backends/platform/sdl/sdl.h, base/commandLine.cpp, common/system.h, engines/grim/debugger.cpp, engines/grim/grim.cpp, engines/grim/lua_v1.cpp, engines/myst3/gfx.cpp, engines/myst3/myst3.cpp, engines/playground3d/gfx.cpp, engines/playground3d/playground3d.cpp, engines/stark/gfx/driver.cpp, engines/stark/stark.cpp, engines/wintermute/base/base_game.cpp, graphics/opengl/context.cpp, graphics/opengl/context.h, graphics/renderer.cpp, graphics/renderer.h, gui/options.cpp
This PR is over #3780 and takes its commits.
It's an attempt to have better and clearer decisions to choose the renderer to use in 3D games.
The selection algorithm is now shared to avoid the same bug being spread over all engines.
In addition, a new OSystem API is used to allow early detection of OpenGL features.
Before this PR, to detect which OpenGL version is available or if shaders are supported, one need to init 3D graphics which is not handy before being sure about what to do.
=> OPENGL: Rework renderer selection functions

engines/scumm/script_v5.cpp
There's a minor subtitle color error in Loom Talkie.
Quick video here: https://www.youtube.com/watch?v=Nk2WtuOPYwI&t=15.
i.e. when Mandible speaks with Goodmold, Mandible's second line is suddenly printed in white, while all his other lines in this closeup are green.
Looking at `DISK_0001/LE/LF_0090/RO/LS_0203`, it looks like the script writers just forgot to set a color for the second line:
```
(14) print(255,[Center(),Pos(160,152),Color(10),Text("That all depends ^")]);
...
(14) print(255,[Center(),Pos(160,152),Text("on how far this sphere can help me see ^")]);
```
Quick way to reproduce it:
* Start Loom Talkie, with Bobbin next to the tree. Subtitles must be enabled.
* Type `room 17` into the debugger
* Exit the room, and go inside the tower that's next to it
* Listen to Bishop and …
=> SCUMM: Fix text color when Mandible speaks with Goodmold (Loom Talkie)

engines/scumm/script_v5.cpp
This works around what appears to be an original bug in VGA Loom that makes it so that you have to click on a thin sliver below the cave entrance to enter it. Usually you have no reason to go back into the caves. Only if you forgot to learn the Reflection draft while you were in there.
I'm a bit torn on whether or not to mark this as an enhancement. I can't imagine anyone wanting to turn this off, so maybe I'm just being petty? :-)
=> SCUMM: Make it easier to go back to the cave in VGA Loom (bug #13385)

engines/scumm/imuse_digi/dimuse_cmds.cpp, engines/scumm/imuse_digi/dimuse_engine.cpp, engines/scumm/imuse_digi/dimuse_engine.h, engines/scumm/imuse_digi/dimuse_scripts.cpp, engines/scumm/imuse_digi/dimuse_triggers.cpp, engines/scumm/sound.cpp, engines/scumm/sound.h
Months ago, when I started working on the current iteration of DiMUSE, I noticed that The Dig made a call to `diMUSESetTrigger()` every time it loaded a speech file. I couldn't make any sense of it so I just ignored it, as it didn't seem to do anything other than call a strange function everytime the trigger was activated.
Turns out, that "strange function" was in fact a procedure which retrieved mouth sync times from the text markers which every speech file had in its iMUSE map.
After retrieving the info, the sync is carried out like it's done on FT (with a couple of small differences -- see `Sound::isMouthSyncOff()`)
While I agree this is done in a very strange way, (quoting my own comment)...
>  A good reason why this is the way it's done, is that in The Dig the whole speech file,
> …
=> SCUMM: DIG/DiMUSE: Implement mouth sync times retrieval and handling

engines/scumm/script_v5.cpp
Some versions of Loom will always show the close-up of sleeping Rusty where he's wearing his own clothes. Later versions (e.g. FM Towns and VGA) will show different close-ups depending on if you've used the Reflection draft on him. So this adds that check to the older versions as well.
| Version | Has bug? |
| ----- | ----- |
| EGA | Yes |
| Macintosh | Yes |
| Atari ST | Yes |
| Amiga | Yes |
| TurboGrafx-16 | No |
| FM Towns | No |
| VGA | No |
The Macintosh version uses a different bit variable to keep track of Reflection, compared to the other three buggy versions. Thanks to eientei for verifying that the Amiga and Atari ST versions could be fixed the same way as the EGA version.
Steps to reproduce the bug if you don't have a nearby savegame:
* Play the game until you get the distaff …
=> SCUMM: Work around Loom script bug to show correct sleepy Rusty close-up

common/ini-file.cpp, common/ini-file.h, test/common/ini-file.h
This adds a lot more unit tests for Common::INIFile and fixes some small problems identified during their creation.
Adding as a pull request as I'm changing some common code in a way I believe is safe, but would like some more eyes to check.
The biggest change is stricter rules on section and key names even in `allowNonEnglishCharacters` mode, which previously allowed anything (even things that would break when reading back in).  This feature is used by the PETKA and MOHAWK engines and my own use in the ULTIMA engine.
The other feature is enforcing section validity in `addSection`, which is only used by the MOHAWK engine.
The complete changes are: 
* addSection() did not check the validity of the section name, which meant it
was possible to create a section that could not then be operated …
=> COMMON: INIFile bugfixes and unit tests

gui/object.h, gui/widget.h
This should address the #13106 issue and similar
It makes widgets, who don't implement handleMouseWheel(), call the handleMouseWheel() of their parent by default
Logic is borrowed from how widgets forward unhandle commands to their parent in handleCommand()
=> GUI: Fix scrolling in launcher and GMM tabs

engines/glk/scott/definitions.cpp, engines/glk/scott/definitions.h, engines/glk/scott/game_info.cpp, engines/glk/scott/game_info.h
Fixes a crash when destructing global array `g_games` while exiting the program.
=> GLK: SCOTT: Replace non-trivial global objects.

engines/scumm/he/script_v100he.cpp, engines/scumm/script_v6.cpp
This PR includes a couple of patches to make playing Moonbase Commander a slightly better experience.  The first one skips over the unnecessary 20 frame pause when starting up the game, while the other fixes a bug where the ScummVM-based game quit confirmation message shows up when exiting the game (The game has its own confirmation prompt, rending showing the ScummVM one unnecessary).
=> SCUMM HE: Couple patches for Moonbase Commander.

base/version.cpp, base/version.h, common/hashmap.h, configure, devtools/create_titanic/hashmap.h, devtools/create_xeen/hashmap.h, graphics/scaler/scale2x.h, graphics/scaler/scale3x.h, gui/about.cpp
This is mostly a suggestion. This PR embeds the current compiler version number in `base/version.o` and includes it inside the `(built on [date])` line in the About dialog.
Supported compilers are: MSVC, ICC, Clang, GCC (couldn't test ICC, though), since the project now requires a C++11 compiler.
As for the why:
* some bugs or performance problems only happen with a particular compiler or a particular version of it (I remember GCC 4.2.1 on PowerPC producing buggy code with some complex multiple inheritance scheme in ScummVM 1.9.0). End-users don't necessarily know which compiler has been used, so this PR makes it easy to obtain this information.
* running `strings` on the ScummVM binary doesn't always print this information (I think that Mach-O binaries don't embed that by default, for …
=> GUI: Print compiler name/version in About dialog

engines/mohawk/riven_scripts.cpp
It seems that the stop condition in this loop is incorrect. See https://bugs.scummvm.org/ticket/13416.
=> MOHAWK: Fix typo in script builder function

engines/agi/detection.cpp
While investigating https://bugs.scummvm.org/ticket/13414 I've discovered the problem addressed by this PR:
Before this PR, if an AGI game is modified with WinAGI, and its `GameID` is set to `ZZ`, the following message is printed:
Your game version has been detected using fallback matching as a
variant of ZZ ("" "" "14/04/2022 15:09:13").
which is not accurate, because there is no known `ZZ` game, which this game can be a variant of.
And in the suggested games list, the last entry is:
which is not very helpful.
With this PR, the message is changed to:
Your game version has been detected using fallback matching as a
variant of agi-fanmade ("" "" "14/04/2022 15:09:13").
and the last entry in the suggested games list is:
=> AGI: set gameid according to *.wag file only if it's a known value

engines/agi/detection.cpp
If changing a game in WinAGI, and not setting `Description` and `Game Version` fields (and changing it's `GameID` - this is taken care of in https://github.com/scummvm/scummvm/pull/3814), the fallback message is:
Your game version has been detected using fallback matching as a
variant of ZZ ("" "" "17/04/2022 10:11:04").
With this PR it's:
Your game version has been detected using fallback matching as a
variant of ZZ (Unknown v2 Game).
=> AGI: *.wag fallback - use description and version only if not empty strings

base/commandLine.cpp, gui/debugger.cpp
This pull request does two things:
1. Add the option to compute the tail md5 in the debugger (when passing a negative size, as is done for the command line `--md5` command).
2. Improve the formatting for the result
I am mostly looking for feedback on the second point (the first one should be fairly uncontroversial).
Currently there are three places where we can see the result of a md5 hash computation:
1. In the Advanced Detector (for example when starting a game) 
```
lang_fr.b25c: 690caf157387e06d2c3d1ca53c43f428, 1006043 bytes.
```
2. With the `md5` and `md5mac` debugger commands
```
) md5 lang_fr.b25c
94892fe8c58c39bd89502ca3e9f71f0a  lang_fr.b25c  1006043
) md5 -n 5000 lang_fr.b25c
690caf157387e06d2c3d1ca53c43f428  lang_fr.b25c  1006043
```
3. With the `--md5` command line command …
=> Improve formatting of md5 commands result

configure
Missing this little edit on configure
=> MORPHOS: add morphos to use gnu++ (std_variant)

test/cxxtest/cxxtestgen.py
Python on Windows seems to default encoding to Windows-1252, so cxxtestgen.py crashes when attempting to compile tests due to UTF-8 characters in punycode.h that are illegal on that code page.
This forces the encoding to UTF-8.
```
Traceback (most recent call last):
File "D:\src2\scummvm\test\cxxtest\cxxtestgen.py", line 594, in <module>
main()
File "D:\src2\scummvm\test\cxxtest\cxxtestgen.py", line 54, in main
scanInputFiles( files )
File "D:\src2\scummvm\test\cxxtest\cxxtestgen.py", line 170, in scanInputFiles
scanInputFile(file)
File "D:\src2\scummvm\test\cxxtest\cxxtestgen.py", line 181, in scanInputFile
line = file.readline()
File "C:\Users\Eric\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
return …
```
=> TEST: Fix cxxtestgen.py crash in Python 3 when digesting punycode.h

engines/scumm/resource_v4.cpp
It looks like the French versions of the various SCUMM games tend to follow [CP850](https://en.wikipedia.org/wiki/Code_page_850) for their text and associated font resources (while the English versions mostly used CP437, especially in the first games).
But, well, not *all* French versions… one small game of indomitable monkeys still holds out against that convention: the floppy EGA/VGA versions of Monkey Island 1. They messed up the (frequent) « à » letter, at `\x85`, and put a « ç » there instead (although that one *is* already available at its usual `\x87` place) in that particular font.
| Source / code point | `\x82` | `\x83` | `\x84` | `\x85` | `\x86` | `\x87` | `\x88` |
|--------|-------|-------|-------|-------|-------|-------|-------|
| CP850, MONKEY1-CD-FR | é | â | ä | **à** ← | …
=> SCUMM: Fix a-grave character in French Monkey1 904.LFL font

engines/scumm/script_v5.cpp
This is related to [Trac #2762](https://bugs.scummvm.org/ticket/2762), which I've just reopened.
This is an original script issue in the FM-TOWNS version of Zak that's said to happen under the Unz emulator too, and so in 2006 this was closed as not-a-bug, but nowadays the project is more open about fixing original script bugs.
If you use the blue crystal on the bird in Lima in that version, and then switch back from the bird to Zak, then the following will happen (I wish I could find a YouTube video for this, but it looks like every player immediately quits the room after switching back to Zak…):
* the bird will disappear
* then it will go back to its pedestal and eat again
* Zak will talk a bit
* then the bird will disappear again
* and then it will go back to its pedestal and eat yet …
=> SCUMM: Fix Lima bird glitch in Zak FM-TOWNS (bug #2762)

engines/scumm/script.cpp, engines/scumm/script_v6.cpp, engines/scumm/string.cpp
This pull request attempts to improve the timing of the Sam & Max intro. See https://bugs.scummvm.org/ticket/13378 for further details.
It does so in a number of ways:
- The German version inexplicably speeds up the scene where the scientist says "Wirst Du brutzeln, wie eine grobe Bratwurst!" ("You'll fry like a pork sausage."). I've slowed that down to match the speech.
- Sam's German actor speaks quite slowly while Max beats up the scientist. I've slowed down Sam's animation to match that, and the other two animations (Sam fiddling with the rope and Max beating up the scientist) are played twice. This isn't quite seamless, but I think it looks better than just leaving them frozen.
- Several broken-up lines (i.e. lines with embedded "wait" instructions) have been re-timed so that the …
=> SCUMM: Improve timing in Sam & Max intro (bug #13378)

backends/graphics/openpandora/op-graphics.cpp, backends/graphics/openpandora/op-graphics.h, backends/graphics/sdl/sdl-graphics.h, backends/platform/sdl/sdl.cpp
This was reported on the forums as https://forums.scummvm.org/viewtopic.php?t=16560
This appears to be a regression since v1.8.0 where refactoring of the SDL backends code resulted in calls to disable SDL cursor which cause issues on OpenPandora. See:
https://web.archive.org/web/20200810044118/https://www.distant-earth.com/index.php/openpandora-using-custom-cursors-in-fullscreen-x11-sdl-windows-without-touchscreen-driftinggrabbing-issues/
This PR attempts to fix this by guarding these calls to disable them on OpenPandora in various ways. However, since I do not have a working OpenPandora toolchain, hardware or any way to test, it would be good to get team feedback and maybe some testing from OpenPandora maintainer before merging this.
=> OPENPANDORA: Restore Fix For Touchscreen Issues with libSDL

engines/scumm/script_v6.cpp
See [Trac #3832](https://bugs.scummvm.org/ticket/3832) for more context, screenshots and saves.
In Sam & Max, when Bruno and Trixie leave Bumpusville, a new actor is used for their escape animation, but the original script never removes this actor from the scene, so some parts of Bruno can still be seen on the wall when the door closes (although it's not extremely visible, since Bruno's colours match that of the wall… but once you've seen it…). So this PR forces the removal of this actor just before this happens.
This actually just follows @eriktorbjorn's initial suggestion. The original script (no. 202 in room 47) does this:
```
...
[06B4] (7F) putActorInXY(6,160,100,47)  # <== Combined Bruno+Trixie actor
[06C1] (82) animateActor(6,250)
[06C8] (82) animateActor(6,6)
[06CF] (7F) …
```
=> SCUMM: Fix glitch when Bruno flees Bumpusville (bug #3832)

engines/scumm/costume.cpp, engines/scumm/scumm.h
One glitch I noticed recently in the Day of the Tentacle intro is that when Bernard looks out of the Chron-O-John, every time he faces to the left side of the screen part of the Chron-O-John is mirrored, like this:
This appears to be because part of the Chron-O-John is a limb on Bernard's costume, perhaps so that opening the lid can be handled as part of the character animation. The glitch was fixed in the remastered version, though it's still there when using the original graphics. This pull request attempts to get around that by always keeping that limb mirrored and adjusting the position of Bernard's head slightly. This is the result:
I've tested it with my English CD version, and with the English non-interactive demo. (The demo don't show this scene at all.)
=> SCUMM: Work around DOTT glitch when Bernard looks out of Chron-O-John

common/ptr.h, devtools/create_project/scripts/scummvm.natvis, test/common/ptr.h
Currently WeakPtr is functionally a SharedPtr because it does refcounting in the base class and as a result, prevents object deletion.
This refactors SharedPtr+WeakPtr to use a tracker object with 2 counters: The strong counter is non-zero if any SharedPtr refs are alive.  If it falls to zero, the object is deleted and weak counter is decremented.  The weak counter is non-zero if any SharedPtr OR WeakPtr refs are alive.  If it falls to zero, then the tracker is deleted.
Also adjusts the API slightly, e.g. it's no longer possible to construct or reset a WeakPtr to a regular pointer (because it has no way of tracking the lifetime).
Regression tested with AGS and fixed a bug so hopefully this should be good now.
=> COMMON: Fix WeakPtr not being weak

gui/console.cpp
Do not persist empty strings, prevent scolling upwards to _historyIndex entry when full, and save to history file in proper order
=> GUI: Improve behavior of console history

engines/tinsel/cursor.cpp, engines/tinsel/dialogs.cpp, engines/tinsel/dialogs.h, engines/tinsel/dw.h, engines/tinsel/handle.cpp, engines/tinsel/handle.h, engines/tinsel/heapmem.cpp, engines/tinsel/module.mk, engines/tinsel/music.cpp, engines/tinsel/noir/notebook.cpp, engines/tinsel/noir/notebook.h, engines/tinsel/noir/sysreel.cpp, engines/tinsel/noir/sysreel.h, engines/tinsel/pid.h, engines/tinsel/scene.cpp, engines/tinsel/tinlib.cpp, engines/tinsel/tinsel.cpp, engines/tinsel/tinsel.h
By:
- working around PCM playback deadlock, sound does not work yet anyway
- remapping values of special PID constants
- remapping values of special inventory indices
- implementing the SystemReel subsystem
- implementing a minimal notebook subsystem
- implementing a few libcalls, some only partially
Current issues:
- hailing the loading screen in INVMAIN produces an invalid coroutine stack
=> TINSEL: Allow noir to reach city map

backends/plugins/elf/elf-loader.cpp, backends/plugins/psp/plugin.ld
The ELF loader can't handle plugins with these sections, and it doesn't appear to be needed for our purposes.
=> PSP: Remove .MIPS.abiflags* sections from plugins

engines/draci/animation.cpp, engines/draci/draci.h, engines/draci/game.cpp, engines/draci/sprite.cpp
In the Draci engine, `lround()` was replaced with a custom `scummvm_lround()` inline for non-C99 compilers (i.e. old MSVC, I guess), but ScummVM now requires C++11 which implies it, as far as I can say (the wiki still mentions old MSVC versions, but it's probably out of date).
The sparc64 compiler/assembler on OpenBSD would also [complain about "Illegal operands"](https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/games/scummvm/patches/patch-engines_draci_draci_h?rev=1.1&content-type=text/x-cvsweb-markup) with the `scummvm_lround()` trick, so they had to patch this for the last 10 years.
Tested with clang++ 13.1 on macOS 12, and g++ 10 on Debian 11. As for MSVC, I'm letting Github Actions do its job :)
(I see that AGS already uses plain `lround()` too, so it should be OK.)
=> DRACI: Remove scummvm_lround() workaround for non-C99 compilers

engines/scumm/costume.cpp
See [Trac issue #13433](https://bugs.scummvm.org/ticket/13433) and this video from RetroSpeedruns: https://www.youtube.com/watch?v=lennSAcOqag.
In the Amiga version of Monkey Island 2, if you:
1. reach Phatt Island
2. pick up the stick under the mattress inside the jail
3. (escape the jail with the usual scenario)
4. go to Booty Island and use this stick on the dog at the front of the Governor's Mansion
then, Guybrush will switch to costume 55, which has a palette glitch on this version and room. (The Trac issue above also contains a savegame.)
From what I understand, this costume doesn't meet the palette contraints of room 53 (the mansion) but it's fine when used in room 29 (the jail).
So I've picked up the colors from Guybrush's default costume (cost. 1) which is very similar and which …
=> SCUMM: Fix costume palette glitch in Amiga Monkey2 (bug #13433)

engines/sci/sound/music.cpp
The fix for bug no. 13447 addressed the saving via GMM, but it does not (always?) work correctly with auto saves.
You can just try the LSL3 scene in the bug report.
If your patience does not allow you to wait for the auto saving to kick in you can decrease the multiplier in `engines/engine.cpp, line 560`. Just change it from 1000 to 100 (or 50)...
There is the unpause before the save which can't lower the pause counter any more, because it is already 0. And then the sounds are paused (for the first time) after the save.  I've just changed it, so that the pause counter can go below 0 and then is restored to 0 after the save.
=> SCI: improve sound pause handling during auto-save (bug 13447)

engines/teenagent/callbacks.cpp
Left-clicking the spider in the cellar raises unknown callback 0x7962.
This PR makes the spider callback the same as the shovel (0x7966)
which is identical to the behaviour of the DOS English game.
=> TEENAGENT: Add missing callback 0x7962 for spider

configure
On macOS, if you do some local builds where you `--disable` some stuff, you'll often see this:
```
AR       audio/libaudio.a
AR       math/libmath.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: audio/libaudio.a(qdm2.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: audio/libaudio.a(maxtrax.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: audio/libaudio.a(eas.o) has no symbols
RANLIB   math/libmath.a
RANLIB   audio/libaudio.a
AR       common/libcommon.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: audio/libaudio.a(qdm2.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: audio/libaudio.a(maxtrax.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: …
```
=> CONFIGURE: Avoid "file has no symbols" noise from ranlib on macOS

engines/scumm/object.cpp
See https://bugs.scummvm.org/ticket/13419 for details.
The strips are drawn one column at a time. But because it's using the wrong height, the whole thing comes out skewed. It appears we always adjust the height of an object before drawing it by masking out the three least significant bits, making it a multiple of eight. This turns out not to be correct in Full Throttle. Apparently it's not correct in The Dig and The Curse of Monkey Island either, but there I have no example of it causing any problems.
I'm a bit uncertain if drawObject() needs to meddle with the height at all, or if this can safely be left to resetRoomObject() where it's already done for _most_ SCUMM versions. But if I'm erring, it's on the side of caution. At least until someone can tell me otherwise.
=> SCUMM: Fix Full Throttle drawing glitch (bug #13419)

engines/scumm/imuse_digi/dimuse_files.cpp
This fix removes a file handle leak during dialogs in Full Throttle. The leak caused the "monster.sou" file to be opened dozens of times in rapid succession, once during every speech snippet, without those opens ever being closed.
I am not sure this is the best fix, but it seems to work.
It can be tested by wrapping some printf output around the fopen and fclose calls, and monitoring whether every fopen is accompanied by a corresponding fclose.
The PSP is especially vulnerable to file handle leaks like this, because the PSP only allows very few open files at the same time. The leak caused dialogs to become silent after a few sentences on PSP, because all available open file handles that the OS allows were used up by the dozens of open monster.sou instances hanging around. The PPSSPP …
=> SCUMM: Fix file handle leak during dialogs in FT

engines/tinsel/bmv.cpp, engines/tinsel/cursor.cpp, engines/tinsel/dialogs.cpp, engines/tinsel/movers.cpp, engines/tinsel/multiobj.cpp, engines/tinsel/multiobj.h, engines/tinsel/pdisplay.cpp, engines/tinsel/play.cpp, engines/tinsel/tinlib.cpp
Some refactoring to simplify a few changes that are incoming with Noir:
* Add a convenience version of MultiDeleteObject that behaves similarly to free/delete when nullptr is passed. 
This simplifies code in a few places, as we can then avoid some nullptr checks.
* Combine MultiSetAniXY and MultiSetZPosition into MultiSetAniXYZ. 
The menu/inventory logic in Noir (but also the former games) does a lot of this.
* Add a MultiBounds function so that we can get all 4 bounds in one call.
Making for more readable code (this happens more often in Noir), as we can get shorter, more concise results when using Common::Rect
=> TINSEL: Refactor a few Multi-object details

graphics/maccursor.cpp, graphics/maccursor.h
This adds an optional flag for when the CURS data is oversized but the engine knows that it's in CURS format (i.e. because it loaded it from a "CURS" resource and not "crsr")
Needed for mTropolis (which has two 70-byte cursor resources in its standard cursor pack).
=> GRAPHICS: Add support for loading oversized Mac CURS resources

devtools/create_engine/create_engine.cpp, devtools/create_engine/create_engine.sln, devtools/create_engine/create_engine.vcxproj, devtools/create_engine/create_engine.vcxproj.filters, devtools/create_engine/create_engine.vcxproj.user, devtools/create_engine/files/configure.engine, devtools/create_engine/files/console.cpp, devtools/create_engine/files/console.h, devtools/create_engine/files/credits.pl, devtools/create_engine/files/detection.cpp, devtools/create_engine/files/detection.h, devtools/create_engine/files/detection_tables.h, devtools/create_engine/files/metaengine.cpp, devtools/create_engine/files/metaengine.h, devtools/create_engine/files/module.mk, devtools/create_engine/files/xyzzy.cpp, devtools/create_engine/files/xyzzy.h
Following on from a musing I had on Discord recently, I decided to try my hand at making a tool for creating the skeletons of new engines, saving potential authors the trouble of copying and pasting from existing engines or Quux, and trying to properly rename everything. The tool is fairly simple, it:
1) Takes in a single command line parameter specifying the engine name
2) Creates a folder for it in engines/
3) Copies the files from the files/ subfolder included with the tool, replacing occurances of a "Xyzzy" placeholder with the engine name, maintaining the upper/lower/camel case of the Xyzzy being replaced.
4) Finally, for those of us using Visual Studio, creates a batch file in dists/msvc/ to simply creating a solution file with just that engine enabled.
At the moment I've only built …
=> DEVTOOLS: New create_engine tool

engines/tinsel/dialogs.cpp, engines/tinsel/dialogs.h, engines/tinsel/dw.h, engines/tinsel/inv_objects.cpp, engines/tinsel/inv_objects.h, engines/tinsel/module.mk, engines/tinsel/multiobj.cpp, engines/tinsel/multiobj.h, engines/tinsel/noir/notebook.cpp, engines/tinsel/noir/sysreel.h, engines/tinsel/pcode.cpp, engines/tinsel/pcode.h, engines/tinsel/tinlib.cpp, engines/tinsel/tinsel.cpp
This adds a (slightly over-engineered) way to resolve the size difference between INV_OBJECT in Noir and before, and relies on inheritance to provide the new fields.
Also this adds very basic menu support (save/load menus work, the options menu itself works, but the actual sub menus are not fully implemented yet).
To provide the mapping, the way the versioning is handled for the menu tables has been modified slightly, to avoid nesting ternaries.
Hence I think it's worthwhile to get this reviewed before pushing it, in case I've misunderstood something about the engine.
=> TINSEL: Implement a solution for INV_OBJECT being different in Noir, and add basic support for menus.

engines/scumm/scumm.cpp
This fixes an old bug by adding some behavior of the original saveload script to our loading process (without actually running the script, since that would display the original save screen).
I turned this into  a PR, so it can be thoroughly tested with as many savegames as possible.
The affected versions are DOS EGA, FM-TOWNS, Amiga and Atari ST.
I have tried loading many savegames for the versions I have, but there might be more.
And I don't have Atari ST.
=> SCUMM: (LOOM) - fix bugs #6011 and #13369

gui/saveload-dialog.cpp
This is about the removal of the dialog
"WARNING: Existing save has longer gameplay duration than the current state. Are you sure you want to overwrite it?"
I think it has more negative than positive impact on the user experience, so I'd remove it.
I recently asked in the discord dev channel about it, but there wasn't much response. @dreammaster, @sluicebox and myself really don't like that dialog, but it is unclear whether everyone else thinks it is a great idea to have it.
=> GUI: (SaveLoad) - remove unnecessary dialog

devtools/create_project/msbuild.cpp
Fixes https://bugs.scummvm.org/ticket/13471
By default, VS sets the __cplusplus macro to the C++98 value regardless of what feature level the compiler is configured to allow, so some code checking the value of the macro for C++11 feature support is not compiling.  This enables the compliant behavior.
=> CREATE_PROJECT: Add /Zc:__cplusplus so __cplusplus macro matches C++ feature level

engines/scumm/scumm.cpp, engines/scumm/scumm.h
=> SCUMM: Use inline member initialization

NEWS.md, engines/scumm/gfx.cpp
Commit 985ccfa8dff9560af7f38a41368f82879684d55d ("SCUMM: Fix MM NES dark rooms and flashlight") forgot to update the `SCUMM_NEED_ALIGNMENT` case in `gfx.cpp`, and thus on strict-alignment archs the various dark rooms in Maniac Mansion NES would still be displayed with the wrong color (i.e. light grey instead of plain black).
Tested on Apple M1, but Dreamcast and iOS/Android were probably impacted, too. Mentioning it in the NEWS file, since this platform disparity was here since ScummVM 2.2.0 AFAICS.
To reproduce:
1. Have a strict-alignment platform and make the following test with and without this diff, OR manually trigger the `SCUMM_NEED_ALIGNMENT` cases if your platform doesn't define that
2. Start Maniac Mansion NES, pick up the key under the doormat, unlock the door with it, enter the …
=> SCUMM: Fix MM NES dark rooms colors on strict-alignment archs

backends/fs/amigaos/amigaos-fs.cpp, configure
- Add FS directory creation
- Remove hardcoded newlib toolchain (there may be follow-up FR's)
=> AMIGAOS: Mutliple fixes

backends/platform/sdl/win32/win32.cpp
I would like to suggest to migrate from `ShellExecute()` to `ShellExecuteEx()`.
That function allows to write a more readable code, without the ugly that needs to test if returned value is greater than 32.
Supported platforms are:
*    Windows 95: Supported.
*    Windows 98: Supported.
*    Windows NT: Required Windows NT 4.0 or later.
*    Windows 2000 and newer: Supported.
*    Windows CE: Requires Windows CE 1.0 or later. 
This fix comes from my port of SCUMMVM for Windows CE/Embedded/Mobile since this family of OSs support `ShellExecuteEx()`, but not `ShellExecute()`. However, this fix will also work on all versions of Windows supported by SCUMMVM.
=> [WIN32] Migrate to ShellExecuteEx()

engines/scumm/scumm.cpp, engines/scumm/scumm.h, engines/scumm/string.cpp
Store it in a member instead of duplicating the condition.
=> SCUMM: Centralize RTL support condition

engines/tony/sound.cpp
This was fixed in one of the OS updates.
Tested locally, no more weird slowdowns.
Please review if I have broken something
Thank you
=> TONY: Remove hack in sound.cpp (AmigaOS4)

gui/launcher.cpp, gui/widget.cpp, gui/widget.h
just an idea I had as opposed to manually calling setLabel in reflowLayout and using hardcoded 320 pixels screen width
we could convert all of the buttons to use this, or even just bake it into the ButtonWidget class and make lowresLabel required in the constructor
=> GUI: auto shorten label for Options buttons

configure
Currently, SEQ MIDI (`/dev/sequencer`) is the default audio device on Mac builds, even though it does not exist on Mac. This means that the default behavior for Mixed-Up Mother Goose Deluxe on Mac is no music. Users have to know to change the audio device to Apple DLS Software Synthesizer. Presumably this affects other games whose only music is GM MIDI. https://bugs.scummvm.org/ticket/12817
To my knowledge, SEQ MIDI (`/dev/sequencer`) is never on Mac, so the simplest thing is to just exclude it from Mac builds as we do with other hosts. Apple DLS Software Synthesizer becomes the new default. We already exclude SEQ MIDI in `create_project` so Xcode builds already have this working behavior. 
Alternatively, if SEQ MIDI is in fact needed on Mac, we could add a check to …
=> CONFIGURE: Disable SEQ MIDI on Mac builds

common/keyboard.h
I´m not sure if this was intended, but it looks so wrong without indentation.
Feel free to reject if it was intended
=> COMMON: Add (missing?) indentation to defines

engines/sci/sound/music.cpp, engines/sci/sound/soundcmd.cpp
These are two different bugs in that one scene.
I have fixed the one in processInitSound() without making more changes than necessary.  The relevant part is that there may not be any call to processStopSound() which would happen when calling processDisposeSound().
The original works a bit different than what we do: If there is an existing node for a sound, it will not remove and delete it. It will just use that node and not create a new one. A new node will only be created when there isn't already one for that sound.
To stay in line with our current code I just remove the existing node with soundKill, since it doesn't really matter which way round you do this (use the old node or remove it and make a new one). The relevant part is really just avoiding processDisposeSound() and …
=> SCI: fix bug no. 10183 (QFG1EGA: Baba Yaga's hut sound bug)

engines/scumm/script_v2.cpp
This is related to [Trac issue #13473](https://bugs.scummvm.org/ticket/13473).
The official French version of Maniac Mansion hangs in the cutscene where Purple Tentacle is bullying Sandy in the lab.
Once Dr Fred is done talking, he should quit the room laughing, and Sandy should have a strong reaction, but with the original bug, the game just gets stuck and the characters indefinitely look at each other until your press Esc.
Here's an example where it hangs: <https://www.youtube.com/watch?v=MwKuK8RI5X0&t=5194s> (with what looks like an original Atari interpreter). It'd hang in DOSbox, too.
With some help from athrxx in the issue above (thanks!), we found that script no. 155 seems to be responsible for this:
```
...
[0064] (14) print(23,"Bas les pattes!");
[0074] (3B) waitForActor(13); …
```
=> SCUMM: Fix hanging Maniac Mansion cutscene with the French version

engines/sci/engine/kfile.cpp, engines/sci/sound/music.cpp, engines/sci/sound/music.h, engines/sci/sound/soundcmd.cpp, engines/sci/sound/soundcmd.h
This is similar to what we recently fixed for the saving. It does concern only the loading from the SCI menu and from the SCI death dialog (that's how it got my attention).
I have written a long comment in SciMusic::resetGlobalPauseCounter()  which explains it.
I have decided to make this very obvious (you could say: more ugly), so it won't cause confusion in the future.
=> SCI: fix sound pausing when loading via kRestoreGame

engines/scumm/object.cpp
We shouldn't bypass the security door in the NES version of Maniac Mansion: there was no copy protection there (since the game was on a cartridge), so the player is meant to open this door just like a regular door. That, and the associated sound effect, add to the dramatic effect when exploring the mansion.
Original interpreter here:
https://www.youtube.com/watch?v=9EU0Ml28keg&t=301
Plus, our bypass would prevent from closing that door again: nothing would happen at all.
=> SCUMM: Keep the security door closed by default in Maniac Mansion NES

engines/scumm/actor.cpp, engines/scumm/script_v5.cpp
This PR tries to improve the available workaround for [Trac issue #1025](https://bugs.scummvm.org/ticket/1025) in Loom. The diff and the the commit message are way shorter than my explanation below, but if you need my reasoning it's there :)
Most (probably all) v3 releases of Loom forget to set any `Local[0]` value when triggering the following `print()` call in script 232, room 23:
```
[0000] (01) putActor(1,4,16127);
[0006] (00) stopObjectCode();
[0007] (5D) setClass(422,[132]);
[000E] (94) print(Local[0],[Center(),Text("We are the masters of stealth," + newline() + "little wizard.")]); # <==
...
```
i.e. when you try to use the stealth draft on the shepherds. In the original interpreters, it seems that this line is just completely skipped. In ScummVM, it would have triggered a crash. …
=> SCUMM: Get the workaround for bug #1025 closer to the original behavior

backends/platform/sdl/amigaos/amigaos.mk, configure
Pending feedback from @BeWorld2018 and @theIDinside (emscripten author, though i didn`t touch the code itself)
Also still need to check with a full build (looks promising though)
Any other feedback (especially gcc gurus and dynamic stuff) welcome (looking at you @lephilousophe) :-D
Please ask, if you find something odd, so i can revise and maybe even rethink a change
configure, line 2572ff
- Streamlined target
- Added some gcc safeguard switches
- Fixed comments and a typo
configure, line 4036ff to 4113ff
- Sort emscripten dynamic target alphabetically
I'd like to get your confirmation on the next changes, since it also touches MorphOS.
Otherwise i'll have to split targets.
Conforming to many of the other platforms use of plugin naming
and to distinguish between ScummVM's engine plugins …
=> AMIGAOS: Few additions and changes to AmigaOS target

engines/sci/console.cpp, engines/sci/console.h, engines/sci/engine/features.cpp, engines/sci/engine/features.h
Now we can test/set/clear SCI game flags in the debugger. Almost every SCI game uses the same scheme of storing flags in an array of global variables.
Example usage on first screen of KQ6 after moving the plank, which sets flag 11:
```
debug> tf 10 11 12
Flag 10 is clear (global var 137, flag 0020)
Flag 11 is set (global var 137, flag 0010)
Flag 12 is clear (global var 137, flag 0008)
debug> sf 10 11 12
Flag 10 is set (global var 137, flag 0020)
Flag 11 is already set (global var 137, flag 0010)
Flag 12 is set (global var 137, flag 0008)
debug> cf 10 11 12
Flag 10 is clear (global var 137, flag 0020)
Flag 11 is clear (global var 137, flag 0010)
Flag 12 is clear (global var 137, flag 0008)
```
The tricky part is that each game stores flags at a different global index. This could …
=> SCI: Add debugging commands for Game Flags

configure
@lephilousophe mentioned in #3886 that -ldl is not used in SDL backends.
To satisfy buildbot and thanks to him for showing me the wrongs in my ways, this is now reverted.
Did a fresh complete build and quickly tested some engines, together with a few starts and quits, no bad things happened so far.
...sorry for breaking buildbot :-/
I could always use more of those pointers :-D
=> AMIGAOS: Revert use of -ldl to satisfy buildbot

backends/module.mk, backends/platform/sdl/macosx/macosx.cpp, backends/platform/sdl/macosx/macosx_wrapper.h, backends/platform/sdl/macosx/macosx_wrapper.mm, backends/plugins/sdl/macosx/macosx-provider.cpp, backends/plugins/sdl/macosx/macosx-provider.h, configure, ports.mk
This PR lets one build and run a macOS Bundle (= `ScummVM.app`) with dynamic plugins for the game engines.
I'm doing this to resurrect the Mac PowerPC port, where the old PowerPC linker can't cope with a single static ScummVM binary with all engines anymore (and Mach-O doesn't offer as many flags as ELF to work around this).
This is split into several smaller commits:
* split `OSystem_MacOSX::addSysArchivesToSearchSet()` so that we now have a separate `getResourceAppBundlePathMacOSX()` wrapper (so that both the shader and plugin loading code can use it).
* let macOS have its own `addCustomDirectories()` (like the Nintendo DS port does), so that plugins can be loaded from the current macOS bundle if it exists.
* use `strip -x` to strip the main scummvm binary when building plugins, in …
=> MACOSX: Add dynamic plugin support to macOS bundles

audio/decoders/wave.cpp, audio/decoders/wave.h, engines/scumm/he/sound_he.cpp
This is a fix for [ticket 10630](https://bugs.scummvm.org/ticket/10630).
Backyard Baseball 2003 was missing dialog which was lip-synced to animations. It didn't use to be this way. I did a `git bisect`, and found the issue was caused by commit 6ac4c9d. 
It turns out the issue was do to it using the WAV block alignment as a count of bytes per sample. This is true for normal PCM wav files, but it is not true for the IMA ADPCM format used for speech in Backyard Baseball 2003.
The IMA ADPCM format includes extra parameters in the `fmt` section (the length of the `fmt` section is 20 instead of the normal 16). The significant extra parameter is the `SamplesPerBlock` parameter which is the number of samples per channel per block. (see [here](http://www.icculus.org/SDL_sound/downloads/external_doc …
=> SCUMM: Lip syncing fixes for some HE games.

engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/tests/builtin.lingo
This change implements the lingo command `move` which moves the given cast member to either the provided cast window or to the first empty cast window. This and changes done in https://github.com/scummvm/scummvm/pull/3903 together make the findEmpty workshop movie work as intended.
This also needed a change in the tests as one of the move tests was causing another test to fail
=> DIRECTOR: Implement STUB Lingo command move

engines/director/lingo/lingo-builtins.cpp
This change implements the `findEmpty` Lingo Function, which checks for the nearest empty castMember from the passed parameter. For the parameter > `c_end` (end of `loadedCast`), it returns parameter back (as the Cast doesn't extend to that index, so effectively that index is empty). This might be wrong, will fix if it is.
=> DIRECTOR: Implement STUB builtin b_findEmpty

engines/director/lingo/lingo-the.cpp
This change implements the STUB [here](https://github.com/scummvm/scummvm/blob/c8c4e04211d85579e6576e7749bee40fa919b7f4/engines/director/lingo/lingo-the.cpp#L714). Takes the current pause state and typecasts it into an integer. This change makes `pauseState` workshop movie work.
=> DIRECTOR: Implement kThePauseState STUB in getTheEntity

engines/director/lingo/lingo-the.cpp
This change implements `kTheRightMouseDown`, `kTheRightMouseUp` and  `kTheRomanLingo` cases of `getTheEntity()` function. The Right mouse implementation is very similar to `kTheMouseUp` and `kTheMouseDown` cases. TheRomanLingo is always set to false to support character sets of all languages.
Description of the romanLingo in Director 4 Lingo Dictionary:
```
Description 
System property; specifies whether Lingo uses a single-byte (true) or double-byte interpreter (false). 
The Lingo interpreter is faster with single-byte character sets. Some versions of Mac system software—Japanese, for 
example—use a double-byte character set. U.S. system software uses a single-byte character set. Normally, 
romanLingo is set when Director is first started and is determined by the local version of the …
```
=> DIRECTOR: Remove STUB for RightMouseUp, RightMouseDown and RomanLingo

backends/platform/sdl/ps3/ps3.cpp
The PS3 backend had that weird behavior where you'd need to check the "Aspect Ratio" option in order to disable it, by default. [Trac#11743](https://bugs.scummvm.org/ticket/11743) reported a similar problem on Android.
Looking at the various `backends/platform/` backends, this appears to come from the fact that only `ConfMan.registerDefault()` is called in the PS3 backend but that's not enough; so I've copied what the PSP2, Android and Switch do. The Android backend gives the most [explanations](https://github.com/scummvm/scummvm/blob/97a138ae2e51e357d93e2eb689ad797338fae4fb/backends/platform/android/android.cpp#L370) about this.
Tested with the PS3 toolchain and the (very nice) `devtools/docker.sh` build script.
=> PS3: Properly init the fullscreen and aspect_ratio config keys

engines/hdb/ai-funcs.cpp, engines/hdb/hdb.cpp, engines/hdb/hdb.h, engines/hdb/menu.cpp, engines/hdb/menu.h, engines/hdb/sound.cpp, engines/hdb/sound.h
I've tested HDB Linux for a while, looked into the code and came up with a few quick fixes.
1. Retrieve the "cheats enabled" value properly from ScummVm configuration. Previously, the game would always begin in cheat mode.
2. Set the "back" button for the warp screen in the proper position (where the code sets the hotspot for it). Hopefully this does not break the PPC support, but the code removed for this seemed to be something left over. 
3. Remove the need to access some menu members via _gdb->_menu, which also seemed like leftover code.
4. Separate some members to boolean and integer, since the code previously would use booleans as ids or counters as well, assuming values 0 and 1 for true, false, but also increasing them beyond these values. This should improve readability with …
=> HDB: A few menu fixes for Hyperspace Delivery Boy!

engines/scumm/detection_tables.h
The new entry uses the "The Farm" pattern, the existing entry uses "farm"
The existing entry was also updated to refer to the Dutch version, for which it was added
(https://github.com/scummvm/scummvm/commit/2e497bb9f83d0435e88bcd283b636c4e2c9043e3).
This commit fixes the issue reported in https://bugs.scummvm.org/ticket/13483
Related forum thread is here: https://forums.scummvm.org/viewtopic.php?t=16585
and Discord discussion here: https://discord.com/channels/581224060529148060/581224061091446795/975285829696102410
=> SCUMM: Add Explore the Farm Mac version to detection

engines/grim/lua/lobject.cpp
```
lobject.cpp: In function 'int32 Grim::luaO_equalObj(TObject*, TObject*)':
lobject.cpp:51:35: warning: comparison between two arrays [-Warray-compare]
51 |                 return svalue(t1) == svalue(t2);
```
=> GRIM: Fix string comparison in lua

engines/glk/conf.cpp
Previously setting a gcolor_x font color (eg. gcolor_0) value in scummvm.ini, it would overwrite the corresponding tcolor_x (here tcolor_0) value. 
The fix makes sense to me, since it now works as I would expect, but probably someone with deeper knowledge of the engine should okay this.
=> GLK: Fix loading font colors for gStyles

dists/scummvm.appdata.xml
Commit 1f4e197 changed the AppData id to a rDNS one, however the actual appdata/desktop file names stayed non-rDNS. This broke the metadata since AppStream parsers cannot match the correct desktop file anymore. This PR reverts the change.
Another possible "solution" would be to add `<launchable type="desktop-id">scummvm.desktop</launchable>` tag (just the `<provides>` tag is not sufficient and useful in this case), however I consider that being a workaround, especially in this case when the appdata file name is also non-rDNS (_scummvm.appdata.xml_ instead of _org.scummvm.ScummVM.appdata.xml_).
True proper solution would be to rename [scummvm.desktop](https://github.com/scummvm/scummvm/blob/master/dists/scummvm.desktop) to `org.scummvm.ScummVM.desktop` and …
=> DISTS: Fix AppData id

engines/scumm/detection_tables.h, engines/scumm/script_v5.cpp
In the NES version of Maniac Mansion, each kid has their own CD player playing a different background music by default.
Each CD player script does something like this when you turn it off:
```
...
(2F) if (!getState04(46)) {
(D8)   printEgo("It's already off.");
(18) } else {
(67)   clearState04(46);
(1A)   Var[224] = 0;  # <==
(3C)   stopSound(71);
(**) }
...
```
but Wendy's CD player script is missing the `Var[224] = 0` line (all the other CD player scripts have it), so although her music was stopped, the game scripts weren't properly aware of this, and so her music could suddenly resume, such as when entering and leaving room 3 with her character. (This would also happen with Nestopia.)
Indeed, here's `exit-3.dmp`:
```
(3C) stopSound(25);
(3C) stopSound(20);
(3C) stopSound(29);
(3C) …
```
=> SCUMM: Properly stop Wendy's music in MM NES

engines/metaengine.cpp
I recently got notice of the fact that we lost the capability of repeated keypresses for the standard actions mapped in the keymapper. Although this is a very small fix, I wanted to get some opinions on this, to see if it could potentially break anything (but AFAIK the keymapper just routes its data onto each engine input handling routines, so if it wasn't broken before it _shouldn't_ be broken now).
=> KEYMAPPER: Allow repeated keypresses for standard actions

engines/ags/engine/util/library_scummvm.h, engines/scumm/debugger.cpp
While making some quick 2.6.0git tests on OpenBSD, some lines appeared in /var/log/messages:
```
scummvm: vfprintf %s NULL in "|%2d|%-12.12s|%4d|%4d|%3d|%3d|%4d|%3d|%3d|%3d|%3d|%3d|%3d|%3d|$%08x| "
scummvm: vfprintf %s NULL in "pluginOpen returned: %s"
```
Indeed, OpenBSD likes being a bit of a torture development environment, and so the system complains if you call printf-like functions with a NULL pointer given for `%s`, which is undefined behavior (most systems will print `(null)` for them but that's not guaranteed).
For SCUMM, it complained when calling `actors` or `objects` in the debugger (a quick example is Woodtick in Monkey2). `getObjOrActorName()` may return a nullptr, and all the other places check its return value.
For AGS, it just happened when starting Maniac Mansion Deluxe …
=> Fix some undefined %s NULL printf

engines/sci/sound/music.h, engines/sci/sound/soundcmd.cpp
This is really a necessary fix, so recommended for merging before the release.
The negative global pause counter (that I really added only for the GMM/autosave situation) may not be used from within kDoSoundPause. It causes issues, the counter will go out of the expected range (also, the "Music also seems to randomly disappear when saving / restoring games" mentioned in ticket no. 13496 might be related to this).
I didn't see this, since we were focussed on SCI0. But it can be easily tested with e. g. LSL1 VGA. Just save right at the start and restore the game, it will call kDoSoundPause and trigger the issue (the counter will go out of range more and more, for me it just triggered the assert in resetGlobalPauseCounter()).
=> SCI: fix regression from c2975276 (fix music handling during auto-save)

engines/hypno/configure.engine
As far as I can tell, only Spider-Man: The Sinister Six requires high resolution support, and none of the games targeted by this engine require 16-bit graphics support.
=> HYPNO: Remove unneeded feature dependencies

configure, rules.mk
The issues was introduced with commit 0974f168b204b26f620d2a7e1a55021e66309e64. Before that commit the `$LDFLAGS` were used for the link command on the plugins, and this includes the sanitizer flags. After that commit it uses the `$SAVED_LDFLAGS` instead and that results in link errors (undefined symbols) when address sanitizer is enabled (and probably also for than and ubsan, although I have not checked).
Reverting the commit fixes the issue for me on macOS. However it is probably not a good fix, and is meant to open a discussion on the best way to fix the issue. Which is why I marked it as draft.
The commit was added in PR #2082 by @besser82 . From the discussion there I understand that it fixes link errors on some platforms (see …
=> Fix building plugins with address sanitizer enabled

engines/kyra/script/script_hof.cpp
```
../scummvm/engines/kyra/script/script_hof.cpp: In member function 'int Kyra::KyraEngine_HoF::o2_defineSceneAnim(Kyra::EMCState*)':
../scummvm/engines/kyra/script/script_hof.cpp:875:32: warning: comparing the result of pointer addition '(((const char*)script->Kyra::EMCState::dataPtr->Kyra::EMCData::text) + ((sizetype)READ_BE_UINT16((((const void*)script->Kyra::EMCState::dataPtr->Kyra::EMCData::text) + ((sizetype)(((int)((Kyra::KyraEngine_HoF*)this)->Kyra::KyraEngine_HoF::<anonymous>.Kyra::KyraEngine_v2::<anonymous>.Kyra::KyraEngine_v1::emcSafeReadStack(script, 12, 875, ((const char*)"../scummvm/engines/kyra/script/script_hof.cpp"))) << 1))))))' and NULL [-Waddress]
875 |         if (stackPosString(12) != nullptr)
```
=> KYRA: Fix pointless NULL validation

engines/glk/tads/tads2/debug.cpp
```
../scummvm/engines/glk/tads/tads2/debug.cpp: In function 'int Glk::TADS::TADS2::dbgnam(dbgcxdef*, char*, int, int)':
../scummvm/engines/glk/tads/tads2/debug.cpp:158:47: warning: the address of 'Glk::TADS::TADS2::tokthdef::tokthhsh' will never be NULL [-Waddress]
158 |         if (!ctx->dbgcxtab || !ctx->dbgcxtab->tokthhsh)
|                                ~~~~~~~~~~~~~~~^~~~~~~~
In file included from ../scummvm/engines/glk/tads/tads2/run.h:42,
from ../scummvm/engines/glk/tads/tads2/debug.cpp:24:
../scummvm/engines/glk/tads/tads2/tokenizer.h:222:19: note: 'Glk::TADS::TADS2::tokthdef::tokthhsh' declared here
222 |         tokthpdef tokthhsh[TOKHASHSIZE];                          /* hash table */
|                   ^~~~~~~~
```
=> GLK: Remove pointless NULL validation

engines/glk/zcode/processor.cpp
```
../scummvm/engines/glk/zcode/processor.cpp: In member function 'void Glk::ZCode::Processor::call(Glk::ZCode::zword, int, Glk::ZCode::zword*, int)':
../scummvm/engines/glk/zcode/processor.cpp:349:17: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
349 |                 if (h_version <= V4)            // V1 to V4 games provide default
|                 ^~
../scummvm/engines/glk/zcode/processor.cpp:352:25: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
352 |                         *--_sp = (zword)((argc-- > 0) ? args[i] : value);
|                         ^
```
=> GLK: Fix bad indentation

engines/gob/goblin.cpp
```
goblin.cpp: In destructor 'virtual Gob::Goblin::~Goblin()':
goblin.cpp:110:77: warning: comparing the result of pointer addition '(((Gob::Goblin*)this)->Gob::Goblin::_goblins[i]->Gob::Goblin::Gob_Object::realStateMach + ((sizetype)(((long long unsigned int)state) * 48)))' and NULL [-Waddress]
110 |                                         if (_goblins[i]->realStateMach[state])
|                                                                             ^
```
=> GOB: Remove needless NULL validation

engines/hypno/cursors.cpp
```
../scummvm/engines/hypno/cursors.cpp:146:96: warning: the address of 'Hypno::HypnoEngine::_pixelFormat' will never be NULL [-Waddress]
146 |         CursorMan.replaceCursor(entry->getPixels(), entry->w, entry->h, hotspotX, hotspotY, 0, &_pixelFormat);
|                                                                                                ^~~~~~~~~~~~~
```
=> HYPNO: Add a missing argument in function call

engines/scumm/dialogs.cpp, engines/scumm/dialogs.h, engines/scumm/metaengine.cpp, engines/scumm/script_v5.cpp, engines/scumm/sound.cpp
When ripping the audio tracks from CD, you may not get quite what the game expects, e.g. my copy of Loom has less silence at the start of the track than the CDDA.SOU file from the Steam version, causing numerous sound glitches. And the MI1 intro appears to be timed with the assumption that there is no silence at all at the start of that track.
This pull request adds game-specific settings to help compensate for this without having the edit the audio files. ("Why settings?" you may ask. Well, I'm told that all CD rippers/CD drives don't produce quite identical results, so hard-coding the adjustments seems risky. And for MI1, I can easily see a situation where someone may want to replace the audio tracks, e.g. from the Special Edition.)
There are three settings:
- For VGA talkie Loom, …
=> SCUMM: Add adjustment sliders for VGA Loom (CD) and MI1 (CD) audio

common/module.mk, common/xpfloat.cpp, common/xpfloat.h, engines/director/lingo/lingo-bytecode.cpp
Per request, moves extended precision float parsing from Director to Common and adds proper handling of subnormal numbers.
Put in a little bit of futureproofing because Intel x87 can actually load the same format but has slightly different flags for INF/NaN, for now it only supports MC68881/SANE semantics.
"Should there be code to code to byte-swap an entire 80-bit value?"  Uh maybe, since 8087 values are stored that way, but so far the only 2 known cases of 80-bit floats in data are always big endian.
=> COMMON: Move 80-bit float parsing from Director to Common

engines/sci/sound/music.cpp, engines/sci/sound/music.h
Make use of the mixer's mutex instead of creating a new one. Otherwise there can still be lock-ups when the main thread and the mixer thread lock each other up in different mutexes (causing a deadlock/freeze). I just noticed this with KQ5 FM-Towns.
We had the same issue in AGOS, it was fixed by allowing access to the mixer's mutex. We can use the same thing here...
=> SCI: avoid deadlocks by using only one mutex

engines/glk/quetzal.h, engines/wintermute/base/gfx/x/modelx.cpp
Apart from generating warnings from GCC when -Walloc-zero is passed, the behaviour when
malloc or new is called with zero sized is implementation dependent and could result in
portability issues. See:
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
````
-Walloc-zero
Warn about calls to allocation functions decorated with attribute alloc_size that specify zero bytes, including those to the built-in forms of the functions aligned_alloc, alloca, calloc, malloc, and realloc. Because the behavior of these functions when called with a zero size differs among implementations (and in the case of realloc has been deprecated) relying on it may result in subtle portability bugs and should be avoided.
````
The GLK Queztal code has an instance of this calling malloc and the WINTERMUTE engine …
=> Fix Instances of Zero Sized Memory Allocations

engines/scumm/saveload.cpp, engines/scumm/scumm.cpp, engines/scumm/scumm.h, engines/scumm/scumm_v2.h, engines/scumm/scumm_v3.h, engines/scumm/scumm_v4.h
This is a followup to
https://github.com/scummvm/scummvm/pull/3792
which improved the post-loading process for LOOM.
This will now be done for all v1-3 games by running the scripts that the games would expect. Which means that e. g. the music is restarted properly in ZAK and MM after loading (can be tested in ZAK v1/2, at the airport, you wouldn't have music after loading, because the script that starts it isn't run).
It won't do anything for Mac versions. These need separate analysis/testing, since the save/load process has been modified a bit  for these versions (no save/load "room", instead using Mac style menus and modified scripts).
This is limited to situations where the original games allow loading and saving, because games might glitch otherwise. E. g. in INDY3 I have a savegame …
=> SCUMM: improve savegame loading for SCUMM1-3

engines/director/lingo/lingo-builtins.cpp
This change would implement the `LB::b_union` builtin which returns the smallest rect that can cover the two rects passed in the arguments.
=> DIRECTOR: LINGO: Implement STUB builtin b_union()

engines/director/lingo/lingo-the.cpp
This change implements the getting STUB of `kTheStageColor`, returning an 8 bit integer for the stage color.
=> DIRECTOR: LINGO: Implement STUB kTheStageColor in Lingo::getTheEntity()

engines/hypno/hypno.cpp, engines/hypno/hypno.h
`Graphics::Surface::scale()` is slow, and can be avoided if the original surface is already the requested dimensions. In addition, using  more specialised routines for copying and colour key blitting instead of the more generic `blitFrom` and `transBlitFrom` from `Graphics::ManagedSurface` also provides a performance boost on slower systems.
This includes the changes from PR #3956.
=> HYPNO: Optimize rendering routines

engines/scumm/saveload.cpp
Since the saved mouse position uses game coordinates, any rendering mode that causes the graphics to be rescaled will have to convert them to screen coordinates before warping the mouse there. (The rendering mode scalers are separate from the backend scalers.)
Note that I have only tested this with Mac Indy3 and Loom, and a little bit with the Hercules rendering mode. It would be good if someone else could help me test, particularly the "(_useCJKMode && _textSurfaceMultiplier == 2)" thing.
=> SCUMM: Correctly reposition mouse on loading savegames when using render mode with its own scaling

engines/director/castmember.cpp, engines/director/lingo/lingo-object.cpp, graphics/macgui/macfontmanager.cpp, graphics/macgui/mactext.cpp, graphics/macgui/mactext.h
This Pull Request contains commits required to implement kTheTextFont, kTheTextHeight, kTheTextStyle, kTheTextSize STUBs in the Director Engine. Also contains changes for comparing styles and fonts while ignoring cases.
=> DIRECTOR: LINGO: Implement TextCastMember property STUB (kTheTextFont, kTheTextHeight, kTheTextStyle, kTheTextSize)

engines/toltecs/screen.cpp
The `toltecs-demo.zip` demo would SIGBUS in `Screen::addAnimatedSprite()` when playing it on OpenBSD/loongson, which has a mips64el CPU with strict-alignment constraints. This is the same setup as for my older PR #2241.
Changing the `FROM_LE_16()` calls there to `READ_LE_UINT16()` calls fixes the issue. Looking a bit at `common/endian.h`, it appears that only the latter properly deals with unaligned memory accesses. Commit 30e3a8161857260e75c84e4a54cf0849afa10dfd was a similar change.
This possibly fixes the game on other strict-alignment ports such as Dreamcast, PSP or some old ARM devices.
On x86-64 and Apple M1, `screen.o` remains identical before and after this change, as expected. I think it's safe to cherry-pick this for the 2.6.0 release, but you're the judges :)
=> TOLTECS: Fix unaligned access causing SIGBUS in Screen::addAnimatedSprite()

gui/widgets/list.cpp, gui/widgets/list.h
Strip formatting from the list widget string before taking the length of it to calculate the caret position. This can be seen e.g. in the save dialog when not using the icon view.
Otherwise, you'll end up with something like this:
(It was a bit tricky to get a screenshot, because the keypress to save screenshots in ScummVM will apparently cause the caret to be hidden.)
=> GUI: Fix caret position in list widget

common/platform.cpp, common/platform.h, engines/twine/audio/music.cpp, engines/twine/audio/sound.cpp, engines/twine/audio/sound.h, engines/twine/detection.cpp, engines/twine/metaengine.cpp, engines/twine/text.cpp, engines/twine/text.h, engines/twine/twine.cpp, engines/twine/twine.h
This was available in 2014 via Humble Bundle and is notable as it doesn't use VOX files, instead having split ogg files for the sound effects. I'm marking this as a draft for @mgerhardy. This also adds `kPlatformAndroid` as required.
I'm not sure as to the proper format for the build date, the ARMv7a .so has `LBA/Relentless (Sep  8 2014 / 15:55:03)` while the x86 .so has `LBA/Relentless (Sep  8 2014 / 15:56:52)`. I used the date/time from the x86 version converted into the same format the other entries use.
=> TWINE: Add detection for DotEmu Android version of LBA1

gui/launcher.cpp, gui/widgets/grid.cpp, gui/widgets/grid.h
This PR fixes [#13499](https://bugs.scummvm.org/ticket/13499).
In addition, before this, filter became inconsistent when we changed the grouping option.
Additionally, the selected game is now preserved when switching between grid and list and restored at startup.
Finally a small memory optimization is done by not storing the grid items twice but only storing pointers to original list.
=> GUI: Multiple fixes to grid widget

engines/scumm/script_v5.cpp
*This fixes an original, small and absolutely non-critical bug of Monkey2, so it can be safely ignored for the 2.6.0 release if necessary.*
This one comes from https://www.moviemistakes.com/main7214 (eh!).
When Guybrush interacts with Dread, Dread should turn and face him if he's not already looking at him. But the original script forgot to do this check, if Guybrush already met him, tries giving him an object and then immediately talks to him.
Indeed, this is what happens in script 201 (room 22) if it's the first time you talk to Dread and know his name (= OK):
```
[006C] (1D)   if (classOfIs(243,[147])) {
[0075] (D8)     printEgo([Text("Are you Captain Dread?")]);
[008E] (AE)     WaitForMessage();
[0090] (28)     if (!Bit[129]) {  # <==
[0095] (05)       drawObject(237setImage(,1)); …
```
=> SCUMM: Fix Captain Dread's head when Guybrush says "It's me again."

base/plugins.cpp, engines/adl/detection.cpp, engines/advancedDetector.cpp, engines/advancedDetector.h, engines/ags/detection.cpp, engines/ags/detection.h, engines/glk/detection.cpp, engines/glk/detection.h, engines/metaengine.h, engines/scumm/detection.cpp, engines/sky/detection.cpp, engines/sword1/detection.cpp, engines/sword2/detection.cpp, gui/massadd.cpp
Skip over targets with ADGF_WARNING and ADGF_UNSUPPORTED flags when using "mass add".
The alternative would/could be to just invent a new flag like ADGF_NOMASSADD
For me, this is mostly about fixing bug no. 13282.
https://bugs.scummvm.org/ticket/13282
We sometimes have bogus entries which only have the purpose of presenting the error message (reasons for being unsupported) contained in the extra field of the detection entry.
This PR certainly does not attend to all issues that the "mass add" option currently has, but it does clean it up a bit...
=> COMMON: reduce mass add detection output by skipping certain ADGF flags and skipping incomplete file/md5/size matches

configure
The commits are unrelated but they're small changes to the same file.
Contrary to FreeBSD, OpenBSD completely removed its `/dev/sequencer` support back in 2013, since sndio is its replacement (for which we already have a MIDI backend):
https://marc.info/?l=openbsd-cvs&m=136333866832000&w=2
So the first commit moves OpenBSD to its own section and always disables SEQ MIDI there, as was recently done for macOS in commit 1aabe9087e815efa56c9692c5b856b9e199528d6.
The other OpenBSD commit just disables `-pedantic` there, because some system headers make the build noisy, otherwise. (It builds fine with `-std=c++11`, though.)
(Basically, this is a backport of what the official OpenBSD port has been doing for some years; I'm trying to reduce the number of patches which are applied in the ports …
=> CONFIGURE: Some OpenBSD tweaks + let the endianness check build if there's no __attribute__

common/scummsys.h
There are currently some `tolower()` or `toupper()` calls where its argument has some side effects:
```sh
git grep '\btolower(' | egrep -e 'tolower\((.*)\+\+(.*)\)' -e 'tolower\((.*)\((.*)\)'
git grep '\btoupper(' | egrep -e 'toupper\((.*)\+\+(.*)\)' -e 'toupper\((.*)\((.*)\)'
```
The Dingux/OpenDingux port currently defines its own `toupper()` macro "to avoid triggering an assert in uClibc dingux library", but it currently does so this way:
```c
#define toupper(c) (((c & 0xFF) >= 97) && ((c & 0xFF) <= 122) ? ((c & 0xFF) - 32) : (c & 0xFF))
```
and so if `(c)` has side effects, they're going to happen more times than intended on this platform.
Fixing the toupper()/tolower() callers is a solution, but sometimes the error comes back, so making a safer macro shouldn't hurt.
The following PR …
=> DINGUX: Only evaluate the toupper() macro argument once

graphics/wincursor.cpp
Hard to prove this is correct because the Microsoft docs for the cursor group format is garbled and has CURSORDIR listed as many of the field types when they're actually WORD or DWORD for some reason:
https://docs.microsoft.com/en-us/windows/win32/menurc/resdir
... but right now this code is spamming a bunch of false-positive warnings when loading cursors from Obsidian because the "planes" field is usually 32 or 64.  I think what's going on is that the Planes/BitCount fields are actually xHotSpot/yHotSpot for cursors, corresponding with the difference between ICO and CUR format.
Either way, in-the-wild data is coming up with other numbers that appear to be valid, so this removes the check.
=> GRAPHICS: Remove false positive warning from Win cursor group parser

common/recorderfile.cpp, gui/recorderdialog.cpp, gui/recorderdialog.h
Also prevent segmentation fault cases related to low-res or switching from low-res to hi-res
And fix memory leak related to loading and scaling of the thumbnail image
A lot of the updated logic is borrowed from the saveload-dialog.cpp for the simple list view (with the thumbnail to the right of the list).
=> GUI: Fix thumbnails for event recorder dialogue

graphics/thumbnail.cpp
Common::fill() fills up to but not including the address of the last item
Previously the last item of array v was not filled with 0, so if the rest of the code in the scaleLine() method did not update it, it would have a random int value which could cause segmentation fault when using the scale() method.
I had this issue while doing some test recording with the event recorder.
=> GRAPHICS: Fix segmentation fault for thumbnail from incomplete fill

engines/toon/audio.cpp, engines/toon/audio.h, engines/toon/subtitles.cpp, engines/toon/toon.cpp, engines/toon/toon.h
These commits update the menu to bring its behavior closer to the original game. 
I've tested with the full game (GOG version) and the English and German Demo versions. 
Changes include:
- Proper sounds to buttons
- Button click is effected at mouse down, not mouse up
- Moving the mouse around while holding the mouse button down activates / affects only one control (not every control that the mouse passed over)
- Button and slider animations in Options Menu
- Reduce frequency of checking and updating a control's state
- DEMO: don't allow middle Text option which does not exist in Demo
- Text options dial moves to area clicked. If Text Off mode conflicts with mute speech or speech volume or "mute all" setting, then dial will select Text On and the proper Font type.
- Sync music / sfx and …
=> TOON: Menu fixes, and settings synchronization with ScummVM config

engines/director/frame.cpp, engines/director/score.cpp
This fix corrects custom palettes for D3 movies. They were very much implemented but the index being fetched was incorrect. This fix also enables `The Seven Colors : Legend of Psys City` to work with the correct palette in scummvm
=> DIRECTOR: Fix Palette loading wrong Palette index

base/commandLine.cpp
Proposing this change as a pull request as I am not completely sure if this is a good idea or not.
The main impact of this change is that settings stored in the Session domain are no longer saved in the Transient domain, which saves a bit of memory in ConfMan. It also keeps the logic to transform '-' to '_' in a single place.
I was also thinking that instead of listing the settings that go into the Session domain, it might be better to list the settings that go into the Transient domain. That way we can easily see which ones have not been migrated yet, and see if it would make sense to changes those. But I was too lazy to build such a list.
=> BASE: Reorganize code to save command line settings

graphics/managed_surface.cpp
Improves the performance of managed surface blits by avoiding expensive operations in common cases:
- Copies the source/destination formats to local variables so the compiler can determine that they're constant in the loop (i.e. that writing to a pixel won't change values in the format), allowing more optimizations.
- Precomputes an alpha bitmask for the source format to quickly determine if the pixel is opaque or transparent (note that the condition is done in a way that 0 alpha mask is always opaque).
- Avoids decomposing and recomposing the color if the source and destination are the same format and the pixel is opaque.  In that case, just copies the pixel value.
- Uses cheaper alpha blend math if the destination pixel is opaque.
=> GRAPHICS: Optimized managed surface blit

engines/scumm/debugger.cpp, engines/scumm/debugger.h
At the end of Indy3, you must find the real Grail among 10 grails in front of the old knight.
For this you need to:
* think of taking notes when visiting the catacombs and the painting in Castle Brunwald, and not lose them until the end of the game.
* and own and read all the related hints in the original manual, but it's quite long, in English only (at least on GOG 😞), there's a lot of cursive content, and so on.
* or have some luck (10% probability).
If you get it wrong:
* you die,
* and you need to restart the 3 trials again.
* (the original game would event prevent you from using your saves).
I don't think the debugger is meant to contain the solution for every puzzle, but finding the real Grail is not just a cheap 1/2 chance and I'm not sure all modern players are as meticulous as …
=> SCUMM: Add a `grail` command to the debugger

backends/graphics/android/android-graphics.cpp, backends/graphics/android/android-graphics.h, backends/graphics3d/android/android-graphics3d.cpp, backends/graphics3d/android/android-graphics3d.h, backends/platform/android/android.cpp, backends/platform/android/android.h, backends/platform/android/events.cpp, backends/platform/android/jni-android.cpp, backends/platform/android/jni-android.h, backends/platform/android/options.cpp, backends/platform/android/org/scummvm/scummvm/ScummVM.java, backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java, backends/platform/android/org/scummvm/scummvm/ScummVMEventsBase.java, dists/android/res/drawable/ic_action_touchpad.xml
This PR do two things:
- it adds settings to let user decide which touch mode is preferred in menus, in 2D games, in 3D games.
- it merges toggle screen keyboard button with the touch mode button: a long press on the button shows the keyboard while a normal press toggles the touch mode. When keyboard is shown, any press will hide it.
=> ANDROID: Improve touch input

engines/director/lingo/lingo-object.cpp
This change implements the getting of kTheDepth property of BitmapCastMember in `BitmapCastMember::getField()`. As this is a read only property, it displays a warning if setField() tries to edit this property.
=> DIRECTOR: LINGO: Implement kTheDepth property of BitmapCastMember

engines/director/archive.cpp, engines/director/archive.h
This change implements `Archive::dumpChunks()` to dump all the Archive chunks instead of just RIFX ones.
=> DIRECTOR: Refactor dumping of RIFX chunks to dump all archive chunks

doc/docportal/settings/engine.rst
This documents the `enable_enhancements` flag in the SCUMM engine, as hinted by @sev-.
=> DOCS: Describe SCUMM game-specific enhancement setting

engines/scumm/script.cpp
The fire animation is sped up along with the rest of the game while the messenger nymph is flying. Slow it down to make it appear to run at constant speed throughout the intro. This does not apply to the VGA talkie version, because there the fire isn't animated.
This depends on the fire "actor" having the same number across versions. I've tested it with my EGA, Mac, TurboGrafx-16 and FM Towns Looms, all in English.
=> SCUMM: Make Loom intro fire animation run at constant speed

audio/decoders/aiff.cpp, audio/decoders/aiff.h, engines/director/lingo/lingo-object.cpp, engines/director/lingo/xlibs/aiff.cpp, engines/director/lingo/xlibs/aiff.h, engines/director/lingo/xlibs/gpid.cpp, engines/director/lingo/xlibs/gpid.h, engines/director/lingo/xlibs/jwxini.cpp, engines/director/lingo/xlibs/jwxini.h, engines/director/lingo/xlibs/movutils.cpp, engines/director/lingo/xlibs/movutils.h, engines/director/module.mk
This adds a minimal implementation of the various XObjects used in Gahan Wilson's Haunted House, of note is that this does some modifications to the common aiff-decoder to be able to implement the "Duration" query in the aiff-xobject.
The XObjects stubbed/implemented are:
* GPID - Product Identification Number
* JourneyWareXINI - Windows Registry queries
* MovUtils - MovieUtilities
* AIFF - Mainly support for querying the duration of AIFF-files.
This does make the intro to Gahan Wilson work a bit better, but sadly the game still doesn't progress beyond the Foyer yet.
Comments are very welcome.
=> DIRECTOR: Stub/Implement the XObjects used in Gahan Wilson's Haunted House.

engines/director/lingo/lingo-builtins.cpp
This change implements the stubbed function `LB::b_clearGlobals()`. Functionality is implemented as described in the Lingo Dictionary for D4 and has been tested using the `clearGlobals` workshop movie. Behaviour in ScummVM matches movie's behaviour in BasiliskII
=> DIRECTOR: LINGO: Implement clearGlobals Lingo command

engines/director/lingo/lingo-builtins.cpp
This change implements the showGlobals command, which outputs the globals and their values in stdout. This can be used in the lingo debugging mode `lingo on`. Changes tested using the showGlobals workshop movie. It deviates in 2 ways:
* The version also shows the patch of Director in ScummVM but not in BasiliskII
* A SerialPort XObject is also in the output in ScummVM but not in BasiliskII
According to the Lingo Dictionary for D4, open XObjects should also be shown by the showGlobals command. I am not quite sure why SerialPort doesn't show up in BasiliskII
=> DIRECTOR: LINGO: Implement b_showGlobals builtin command

engines/director/lingo/lingo-builtins.cpp
This change implements the `showLocals` lingo command and removes the STUB from lingo-builtins.cpp. The changes have been tested using `showLocals` workshop movie, and the behaviour in ScummVM is identical to behaviour of the said movie in BasiliskII. This command would output the localVars to the stdout and can be used in the debugging mode with `lingo on`
=> DIRECTOR: LINGO: Implement showLocals lingo command

devtools/dumper-companion.py
Been sitting on this for ages, the partition table parsing fixes extraction of many hybrid discs that previously had issues. Setting the folder modtimes is just a QOL thing, but it works.
=> DEVTOOLS: Add basic Apple partition parsing, recursively set folder modtimes

engines/director/lingo/lingo-object.cpp
This change prevents setting of `_initialRect` of the CastMember from the setField() function and implements the STUB
=> DIRECTOR: LINGO: Implement setting of kTheRect field in CastMember::setField()

engines/director/lingo/lingo-bytecode.cpp, engines/director/lingo/lingo-code.cpp, engines/director/lingo/lingo.h
Instead of using the STUB keyword to log `LC::cb_localcall` and `LC::call`, this change moves it to a macro and uses the macro for this purpose. This won't confuse these functions as "STUBbed" or missing something
=> DIRECTOR: LINGO: Replace printSTUBWithArglist with macro printWithArglist

engines/scumm/script_v6.cpp
Thanks to NeoDement on Tcrf for spotting this:
https://tcrf.net/Maniac_Mansion:_Day_of_the_Tentacle/Unused_Scripts#Chron-O-John_Status_Check
When Dr. Fred receives a new diamond, he's supposed to report the status of Hoagie's and Laverne's units, but the `talkActor()` lines for that don't have any associated `wait.waitForMessage()`, so they were unseen and unheard in
the game until now. The Remastered version didn't fix this…
Global script 9 (stored in room 7):
```
...
[0170] (5D) } else if (dup[1] == 216) {
[017B] (5D)   if (bitvar9) {
[0182] (5D)     if (bitvar10) {
[0188] (5E)       startScript(0,30,[])
[0192] (7C)       stopScript(0)
[0196] (**)     }
[0196] (**)   }
[0196] (68)   beginCutscene([2])
[019D] (43)   bitvar40 = 1
[01A3] (95)   beginOverride()
[01A4] (73)   jump 4d2
[01A7] …
```
=> SCUMM: Fix missing Dr. Fred line when he receives a new diamond

backends/module.mk, backends/plugins/elf/arm-loader.cpp, backends/plugins/elf/elf32.h, backends/plugins/elf/plugin.syms, backends/plugins/riscos/plugin.cpp, backends/plugins/riscos/plugin.ld, backends/plugins/riscos/riscos-provider.cpp, backends/plugins/riscos/riscos-provider.h, configure
This PR adds the ability for RiscOS to use plugin-based split builds.
This will let us overcome the size limitations we hit on the buildbot and provide a unique distribution with all engines bundled.
Some small changes are needed on the configure script to allow for RiscOS specifics: comma in file name and plugins directory different from other SDL ports.
=> RISCOS: Implement plugin provider

backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp, backends/graphics3d/openglsdl/openglsdl-graphics3d.h, engines/engine.cpp, po/POTFILES
This has two main advantages:
- The mouse cursor is now restricted to the correct area when grabbing the cursor with SDL 2.0.18 or later. This fixes [Trac #13152](https://bugs.scummvm.org/ticket/13152).
- 3D games now make use of the selected stretch mode, which replaces the old aspect ratio code. This fixes [Trac #12475](https://bugs.scummvm.org/ticket/12475).
It looks like `WindowedGraphicsManager` is able to handle games that support arbitrary resolutions without any additional changes. The important thing is to make sure that `getWidth()` and `getHeight()` return the correct values when `recalculateDisplayAreas()` is called.
=> OPENGL3D: Make use of the active rect provided by WindowedGraphicsManager

engines/scumm/script_v5.cpp
This one was found by Threepwang while he was testing his own French translation.
This only happens with the Ultimate Talkie edition of Monkey Island 2, when you go to the Booty Boutique and try to buy/sell some objects.
Script 215 in room 48 (talkie edition 0.2) does this:
```
...
[0004] (48) if (Local[0] == 530) { # <===
[000B] (D8)   printEgo([Text(sound(0xACDDEDE, 0xA) + "Can I sell back this hub cap?")]);
[003B] (48) } else if (Local[0] == 529) { # <===
[0045] (D8)   printEgo([Text(sound(0xACE4833, 0xA) + "Can I sell back this pirate hat?")]);
[0078] (48) } else if (Local[0] == 534) {
[0082] (D8)   printEgo([Text(sound(0xACEC310, 0xA) + "Can I sell back this wreath?")]);
[00B1] (48) } else if (Local[0] == 547) {
[00BB] (D8)   printEgo([Text(sound(0xACF2463, 0xA) + "Can I sell back …
```
=> SCUMM: Fix missing voice when selling back the hub cap and pirate hat

engines/director/lingo/lingo-the.cpp
This change implements scriptNum of sprite property in `Lingo::getTheSprit()` and makes `scriptNum of sprite` workshop movie work as intended.
=> DIRECTOR: LINGO: Implement scriptNum of sprite STUB in lingo-the.cpp

engines/mtropolis/detection_tables.h, engines/mtropolis/mtropolis.cpp
This patch simply adds a detection entry for the German Obsidian release I have. Since I don't have any _reliable_ information regarding a possible release date, I left them out for now and just refer to the publisher/brand instead.
Current test status: The game launches, I walked through the forest and bureau realm. Interestingly, the Cloud Ring/WordMixer/Form puzzle is completely skipped, you receive the proper form directly at the bridge repair booth and need to get it signed.
=> MTROPOLIS: Add detection entry for German Obsidian release

engines/sci/resource/resource_audio.cpp, engines/sci/sound/midiparser_sci.cpp, engines/sci/sound/music.cpp, engines/sci/sound/music.h
This is a followup to
https://github.com/scummvm/scummvm/pull/3934
It cleans up some things I noticed when I implemented the mute flag handling. In particular, it properly implements handling of flag 1 and removes the hack  that always set flag 2 on channel 9. I haven't encountered any actual bugs that would be noticeable (apparently, the hack works), so there is no hurry to merge this.
The only game where I actually encountered flag 1 usage is KQ5 (both floppy and CD).
=> SCI: (SCI1+) - improve channel sound flag handling

engines/scumm/script_v5.cpp
This comes from quickly diffing my Indy4 Talkie PC release with my Talkie Macintosh release, but [TCRF also mentions this](https://tcrf.net/Indiana_Jones_and_the_Fate_of_Atlantis#Revisional_Differences) among some other differences. The Macintosh releases often fixed some small issues in the original games… I think this one's worth "backporting".
In one of the first scenes, Kerner will use the phone booth in New York to report that he stole some interesting stuff. The talkie version changed these lines for some reason, but in the PC talkie release the new text doesn't match the new audio:
* Kerner says: `"Dr. Ubermann… Fantastic news! We've found the treasure we seek."`
* but the text prints: `"Fritz… Fantastic news! I think we've found the treasure we seek."`
the real problem is the …
=> SCUMM: Fix Kerner's text mentioning the wrong person in New York

configure
Since GLAD was introduced and the massive amount of fixes to the 3D part, this platform dependant special case is not needed anymore and frankly i don´t think this ever worked anyway :-/
=> CONFIGURE: Remove special case for GLES2

engines/director/lingo/lingo-the.cpp
This change implements the getting of number of castMembers. THe changes have been tested using the `number of castMembers` workshop movie which shows identical behaviour to as observed in BasiliskII
=> DIRECTOR: LINGO: Implement Number of Castmembers STUB in Lingo::getTheEntity()

engines/director/events.cpp, engines/director/lingo/lingo-the.cpp, engines/director/movie.cpp, engines/director/movie.h
Implements the beepOn property by creating a bool `_isBeepOn` for the movie and emitting a beep at every mouse down event which meets these conditions:
* beepOn is true
* castMember being clicked is not active
Tested using `beepOn` workshop movie and shows identical behaviour as in BasiliskII
=> DIRECTOR: LINGO: Implement the beepOn property and remove their respective STUBs

engines/director/cast.cpp, engines/director/director.cpp, engines/director/director.h, engines/director/lingo/lingo-the.cpp
This change implements `fixStageSize` STUB by adding a bool and Rect variable for it in the Director namespace. The changes have been tested using `fixStageSize-movie 1` workshop movie and it shows identical behaviour as seen in BasiliskII
=> DIRECTOR: LINGO: Implement kTheFixStageSize property STUB

engines/director/lingo/lingo-the.cpp
This change implements scoreColor of sprite property in the director engine. It looks for the last 3 bits of _colorcode byte of a sprite (As its overall value can mean more than one thing, like setting sprite editable and movable)
Change has been tested with `scoreColor of sprite` workshop movie and it shows identical results as to the original
=> DIRECTOR: LINGO: IMplement kTheScoreColor STUB in Lingo::getTheEntity()

engines/mtropolis/detection_tables.h, engines/mtropolis/mtropolis.cpp
Some things to note:
- 3 of the PC demos are of unknown providence
- All of the PC demos lack word data
- Mac demo comes extracted on the disc, thus the need for a separate resource setup
=> MTROPOLIS: Add detection for Obsidian demos, support for Mac, preliminary support for PC

engines/director/lingo/lingo-bytecode.cpp, engines/director/lingo/lingo-bytecode.h, engines/director/lingo/lingo-code.cpp, engines/director/lingo/lingo-code.h, engines/director/lingo/lingo-codegen.cpp, engines/director/lingo/lingo-the.cpp, engines/director/lingo/lingo.cpp, engines/director/lingo/lingo.h, engines/director/types.h, graphics/macgui/macmenu.cpp, graphics/macgui/macmenu.h, graphics/macgui/macwindowmanager.cpp, graphics/macgui/macwindowmanager.h
This change:
- Implements the MENUREF Datum type to refere to menus and menuItems
- Implements the missing getter and setter functions for the STUB.
- Cleans up the old way of findMenuItem() (It would have required 4 overloads)
With these changes, all the workshop movies concerning the menus and menuItems are working.
=> DIRECTOR: LINGO: Implement MENUREF Datum type and STUB for Menu, Menus, MenuItem and MenuItems

engines/director/director.cpp, engines/director/director.h, engines/director/events.cpp, engines/director/lingo/lingo-the.cpp
This change adds a baseline which is subtracted from the timer to give the modified lapsed time. The baseline is set to 0 by default so the modified lapsed time won't show up unless it has been set. The changes have NOT been tested as there weren't any workshop movies testing for the same. I will update it after making a movie and testing it
=> DIRECTOR: LINGO: Implement setting of timeOutLapsed property

backends/platform/sdl/amigaos/amigaos.mk, configure
This only touches AmigaOS
- adds a DEBUG_BUILD define to the build environment
- makes use of the define to not strip any information from debug builds
Sorry for the wrong indentation in amigaos.mk, but my shell still doesn´t like indented ifdefs
=> AMIGAOS: Debug builds with all debug information

engines/director/frame.cpp
#3979 introduced a fix for fetching the palette. However, it misinterpreted the number as an unsigned int instead of a signed int, leading to incorrect palettes on certain other games.
@einstein95 suggested this. I confirmed that via reading as a signed int, Japan Art Today 07 is fixed while The Seven Colours retains the correct palette from #3979.
Fixes https://bugs.scummvm.org/ticket/13615.
=> DIRECTOR: fix palette regression

engines/director/castmember.cpp, engines/director/castmember.h, engines/director/lingo/lingo-object.cpp
This is a quick fix to implement the STUB for the `Modified` property of CastMember
=> DIRECTOR: LINGO: Implement kTheModified field in CastMember::getField()

engines/director/cast.cpp, engines/director/movie.cpp
This fixes a null pointer crash and potential issues when switching between movies.
Examples: Let's play dressup with Bert (exit), Learn the art of magic (instant)
=> DIRECTOR: Let Cast class manage registering the archive

doc/docportal/settings/engine.rst, engines/agos/agos.cpp, engines/agos/agos.h, engines/agos/detection.cpp, engines/agos/vga_ww.cpp
Simon the Sorcerer 1 & 2 play a fade-out to black effect when you leave a room.
The problem is that you're *very* frequently moving from one room to the next, and this effect is a bit slow (and on some devices where SDL doesn't have a lot of acceleration, it gets quite painful).
Moreover, Simon walks in a really… relaxed manner, so I know a lot of "modern" players who complain about the pace of the game being way too slow, in 2022. I've found that disabling the fade-out effect makes the experience a bit nicer: you feel less interrupted by a slow animation every 20 seconds.
So, this PR adds a new `disable_fade_effects` option (disabled by default, since the fade-out is part of the original game). I'm only applying it on the `simon1` and `simon2` targets, because they're the only AGOS games …
=> AGOS: Add an option to disable the fade-out effects in Simon1/Simon2

backends/platform/sdl/morphos/morphos.cpp, backends/platform/sdl/morphos/morphos.h
Use printf if DEBUG_BUILD only.
This removes a lot of console messages.
=> MORPHOS: logMessage override

common/punycode.cpp, devtools/dumper-companion.py
This is left as-is in the current code, and even Python's punycode encoding does too.
=> DEVTOOLS: COMPANION, COMMON: Add DEL character to be punycoded

engines/toltecs/detection.cpp
I've just discovered a couple of days ago that there's been a 2019 remaster of 3 Skulls of the Toltecs (which is currently on sale on GOG and Steam) made by Casual Brothers for Windows.
It features improved graphics from the original drawings (except in some scenes) so there's much less aliasing going on, the subtitles are much more readable, and the audio has been denoised a bit, it seems.
This PR just detects it and marks it as unsupported for now (since the resources are different).
(I'll probably update the wiki page too, if you're OK with this PR.)
Tested with the GOG and Steam versions.
=> TOLTECS: Detect the (currently unsupported) 2019 remaster of 3 Skulls of the Toltecs

engines/mohawk/detection_tables.h
Links for FRS-suitable zips:
[daniel-demo-mac-en.zip](https://github.com/scummvm/scummvm/files/8986016/daniel-demo-mac-en.zip)
[lbsampler-android-wanderful-en.zip](https://drive.google.com/file/d/1KUrOl1XKDOE4mwtvaPpKl1aL2vqLEqMn/view?usp=sharing)
=> MOHAWK: Add detection for Story of Creation Mac, Daniel in the Lions Den Mac demo, Wanderful Android sampler

engines/mohawk/detection_tables.h
This adds detection entry for the unsupported* Hebrew CD release of "Just Grandma and Me"
(*)Game has graphical glitches when played
I assumed it v2 beacuse outline filename extension is LB, as v2 examples in wiki
+ checking the EXE in hex viewer it says "Living Books Player v2"
=> MOHAWK: Add detection entry for Hebrew release of Just Grandma and Me

devtools/create_kyradat/create_kyradat.cpp, devtools/create_kyradat/games.cpp, devtools/create_kyradat/resources.cpp, devtools/create_kyradat/resources/mr_dos_cd_hebrew.h, engines/kyra/detection_tables.h, engines/kyra/gui/gui_mr.cpp, engines/kyra/resource/staticres.cpp, engines/kyra/text/text_mr.cpp
Following #2683 and #3277
this PR adds support for hebrew fan translation of Legend of Kyrandia 3: Malcolm's Revenge
changes:
Add kyra3 hebrew fan translation detection entry*
Add kyra3 hebrew strings to KYRA.DAT (+Bump KYRA.DAT version)
Reverse strings in the family album and align to the right
Adjust ordering of object action strings
Adjust scores display
Thank you
(*)A new macro `KYRA3_CD_INS_FAN_FLAGS` was introduced to allow the translation patch to work with GOG version (in which the westwood installer is not unpacked**).
(**)IMHO, it might better to move this logic away from detection (merge duplicated installer/installed entries in detections), and just try to load the installer file if it exists, but it is out of scope for this PR😅. (If this suggestion seems OK I will open …
=> KYRA: Support hebrew fan translation of MR

doc/docportal/settings/audio.rst
Playing around with the "talkspeed" values, the name of this setting may be counter-intuitive:
Higher values do not mean higher speed. Instead they lead to higher (longer) display time.
In other words, talkspeed zero is fast, 255 is slow.
Related discussion (from 2008, though): https://forums.scummvm.org/viewtopic.php?t=6496
=> DOCS: fix talkspeed explanation

video/hnm_decoder.cpp
Previously, videos without sound would cause -1 frames to be added to the next frame start time on top of the regular frame delay. This fixes transitions in Lost Eden on some platforms.
=> VIDEO: Fix playing HNM videos without sound

engines/director/lingo/lingo-builtins.cpp
This change adds warning messages for unsupported Lingo Commands in lingo-builtins.cpp
=> DIRECTOR: LINGO: Add BUILDBOT warnings for unsupported lingo commands

engines/director/channel.cpp, engines/director/lingo/lingo-builtins.cpp, engines/director/sprite.cpp
This change implements the b_map builtin. It also introduces a change in how we handle constraints of sprites (by checking them each frame instead of just handling them during events) and classifies movable sprites as Active sprites too. Changes have been tested using the `map` workshop movie and also by plugging values in the Lingo Message window and ScummVM debugger.
=> DIRECTOR: LINGO: Implement map builtin STUB

engines/director/lingo/lingo-builtins.cpp
This change implements the STUBbed builtin b_abort and adds warning messages for unsupported debugging commands showResFile, showXlib. Changes tested by the `abort` workshop movie
=> DIRECTOR: LINGO: Implement abort builtin command, issue warnings for unsupported commands showResFile, showXlib

audio/mididrv.h
Adds some MIDI constants that I need for mTropolis enhanced MIDI support.
Basically, trying to track MIDI channel state, and some of these are reset by Reset All Controllers messages, and sostenuto is needed to track sustained notes (similar to sustain).
=> AUDIO: Add some more MIDI constants.

gui/options.cpp
Normally, the clear button is supposed to be greyed out when no soundfont is selected, however recreating the button during a layout change caused the button to be re-enabled.
=> GUI: Preserve the enabled state of _soundFontClearButton when reflowing the window

engines/scumm/detection.cpp
This is to avoid ambiguity since "external audio" can mean speakers and such. Also, changing from "Use" to "Load" both to make it clearer what is happening and also to match the "Load modded assets" setting in the Stark engine.
=> GUI: Change SCUMM audio override label to "Load modded audio"

gui/widgets/grid.cpp
When using the mouse wheel (scroll up/down) in the Grid view, item tray for a selected game, ScummVM would exit.
To replicate the buggy behavior, from the ScummVM launcher, go to Grid view, select a game and then use mouse-wheel to scroll over any of the buttons of the highlighted game's small popup (ie. the buttons for Play, Edit and Saves).
I didn't notice any side-effects from the fix, but someone more familiar with the code should confirm.
=> GUI: Fix mouse wheel on grid item tray causing ScummVM to exit abruptly

engines/scumm/sound.cpp, engines/scumm/sound.h
Ciao! It seems that we didn't support this functionality at all, so I took advantage of the code eriktorbjorn already had in place for the Loom replacement tracks to implement this for MI1 CD (DOS version, FM-Towns is a totally different beast).
LOOM and any FM-Towns game are quite different: 
* In order for this to work for LOOM CD, I would have to store some new data in the savegames (the offset and the delay obtained in `ScummEngine_v5::decodeParseString()`, case 8;
* FM-Towns has its own CD Player class, which I'm currently not touching with a ten foot pole.
Both the two points above represent changes which are out of the scope with respect to this PR; rest assured though that the code I introduced is only reachable within MI1CD DOS.
=> SCUMM: MI1 (CD DOS): Implement reloading CD Audio track when reloading game

common/endian.h, common/scummsys.h, common/serializer.h, common/stream.h, test/common/endian.h
Relevant issue: https://bugs.scummvm.org/ticket/13470
This fixes movement in Full Pipe on RISC OS. Remaining issues:
=> COMMON: Fix reading and writing doubles from streams with older ARM toolchains

common/str-enc.cpp, common/str-enc.h, common/str.h, common/ustr.h
This updates the string encode API to return a status code indicating whether the encoding completely succeeded, or if it contains errors.
Currently, unmappable characters are just silently encoded as "?" so there is no way to determine if a Unicode code point is valid on a particular code page other than seeing if it comes out as "?" when the input character wasn't "?" which is a pretty gnarly hack.
The mTropolis engine needs this to filter out keystrokes that don't map to a valid character.
=> COMMON: Add string encoding API with more informative error behavior

engines/director/lingo/lingo-the.cpp
This change returns true for the property searchCurrentFolder as we won't be supporting the setting of this property to False
=> DIRECTOR: LINGO: Implement searchCurrentFolder STUB in Lingo::getTheEntity()

audio/midiparser_smf.cpp, audio/midiparser_smf.h
Not sure this is the greatest way to do this.
Obsidian uses type 1 SMF, and two parts of the game conditionally mute MIDI tracks (the Church puzzle unmutes tracks the further you get through it, and the canvas puzzle mutes the piano track if you solve or are attempting to solve the puzzle).
Unfortunately, it does this by muting track numbers, not channels, but MidiParser currently wipes out the track information from type 1 when it converts it to type 0.
This adds a flag to keep the tracking information as metadata so it can be recovered, and passes the track number with MidiParser events.
=> AUDIO: Add flag to preserve MIDI Type 1 source track information

engines/director/lingo/lingo-builtins.cpp
This change implements the xFactoryList builtin function in a modified way. While the original worked this way:
This implementation will treat all inputs as "EMPTY"
This is because we don't currently save the filename from when an opened XObject is coming. Also some XObjects we load don't seem to have a filename (I used [this](https://github.com/scummvm/scummvm/blob/01d264569ca243552d6c65d9d2245ab3adb8bfb8/engines/director/lingo/lingo-builtins.cpp#L1149) but it didn't quite work)
So I am keeping it this way for now, as djsrv said that the usage of this function in target movies would be very very rare.
This change has been tested using ScummVM's debugger
=> DIRECTOR: LINGO: Implement xFactoryList Lingo Function

gui/downloadiconsdialog.cpp, gui/downloadiconsdialog.h, gui/gui-manager.cpp, gui/gui-manager.h, gui/launcher.cpp, gui/options.cpp, gui/widgets/grid.cpp
The icons download calls callbacks in the `DownloadIconsDialog`. When we click Hide the dialog is closed, and the next attempt to access one of the callbacks causes a crash. To fix this issue, this pull request moves the callbacks for the icons download from the `DownloadIconsDialog` to the `DialogState`.
This first change then caused two other issues to become apparent:
* There was a race condition with the `GuiManager::_iconsSet` variable as the icon download is calling `GuiManager::initIconsSet` from one of the callback (when the download has finished), which runs in a separate thread. This was not an issue before fixing the crash, but now that we can close the download and options dialog while downloading the icons, the grid launcher can be accessing the `_iconSet` when the download …
=> Fix crash when clicking Hide while downloading icons

engines/director/debugger.cpp, engines/director/debugger.h, engines/director/director.h, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-the.cpp
This change implements traceLogFile and the required function in g_debugger. There is a new wrapper of debugPrintf which will log the stdout and stderr output in the log file specified. Functionality has been tested and us found consistent to that of the original
=> DIRECTOR: LINGO: Implement traceLogFile Lingo Property

configure
SDL's version scheme has changed so that the minor version is increased when new versions, with the micro version being reserved for bugfix-only releases. However, ScummVM's configure script assumed that all SDL versions have a minor version of 0, which broke detection of OpenGL and SDL_net.
=> CONFIGURE: Fix compilation with SDL 2.23.0 or later

engines/director/detection_tables.h
This adds the full version of Through the Window; the demo was previously supported. Unlike the demo, the full version is some sort of HyperCard/Director hybrid. The main entry point is a `STAK`, not a Director movie, but it includes a full MacroMind Player and significant chunks of the game are Director.  Setting the entry point to the main executable or the player causes it to not boot, with the error `WARNING: Movie::loadArchive(): Wrong movie format. VWSC resource missing!`. I've set it instead to the first Director movie the game plays, `whales`.
I've also corrected the filesize of the demo, which was added before the Mac file size bug was fixed.
=> DIRECTOR: full release of Through the Window

engines/director/channel.cpp, engines/director/lingo/lingo-the.cpp, graphics/macgui/macmenu.cpp
This small change checks for a null macmenu before accessing its properties. This is a fix for some build steps for the director buildbot.
=> DIRECTOR: Fix buildbot failure on null macmenu

image/pict.h
Clang flagged a warning here on build, which this PR cleans up: `warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]`
=> GRAPHICS: IMAGE: clean up build warning

engines/mohawk/detection_tables.h
Adding [this version](https://apps.apple.com/nz/app/storybook-sampler/id632152206) from the Mac App Store.
Resolves [Bug #13647](https://bugs.scummvm.org/ticket/13647)
=> MOHAWK: Adding macOS Wanderful Story Sampler (lbsampler) to detection

engines/mohawk/detection_tables.h, engines/mohawk/livingbooks.cpp, engines/mohawk/livingbooks_code.cpp
Marking the Mac versions of the Daniel in the Lions' Den demo and The Story of Creation working is due to d096b78acaa510e02cb9be9a2e2dc17e53f80e3e adding in a check to use LBv1 if the game is marked as LBv2 and kPlatformMacintosh. Ideally it should be changed, but I don't have all the Mac versions to check if it's the case for just that one game or all other Mac games.
The Wanderful version of the sampler uses a 32 byte ANI, the extra bytes being nuls. The `&& source[pos] != 95` part is due to some variables using `_` in the names, which the engine was previously failing on parsing.
=> MOHAWK: A couple of hacks to get some games partially working

engines/director/director.cpp, engines/director/director.h, engines/director/game-quirks.cpp, engines/director/lingo/lingo-the.cpp, engines/director/movie.cpp
Kids Box boots to a 320x150 splash screen, then switches to 640x480 for the main content. This causes ScummVM to pick an awkward window size: it selects a screen based around the splash screen, then squashes the main game down into that. See the sample images below.
@sev suggested implementing a quirk which sets the screen to desktop mode, which I confirmed works well when using the desktop mode. This is the start of that work, but it doesn't quite work yet. I've moved `wmMode` to an instance variable on `DirectorEngine` so it's accessible on `g_director`. I've confirmed that the quirk is evaluated before `_wm` is instantiated, but perhaps I'm scoping this incorrectly and it's assigning to the wrong value.
=> DIRECTOR: add Kids Box quirk to run in desktop mode

engines/director/lingo/lingo-builtins.cpp
This change implements a warning for unsupported open Lingo command in `LB::b_open()`
=> DIRECTOR: LINGO: Add warnings for b_open Lingo function

engines/director/director.cpp, engines/director/director.h, engines/director/game-quirks.cpp, engines/director/movie.cpp
Currently, the resolution set by the debug desktop mode is hardcoded to 1024x768. This isn't always that convenient, especially given that many Director games target 640x480 screens.
Currently, the only place this is used is the Kids Box quirk. I've set the window to 640x480 so that the main game is fullscreen, and only the opening splash screen is displayed as a window within the desktop. It could potentially be exposed in other ways too.
=> DIRECTOR: permit setting the desktop resolution

NEWS.md
In part related to PR #4096, but since the 2.6.0 release will have many enhancements for the SCUMM games, I wonder if it's not just simpler to "advertize" the https://wiki.scummvm.org/index.php?title=SCUMM/Game_Enhancements wiki page in the release notes.
Moreover, the description for each enhancement is pretty long, so I think that referring to the wiki is just simpler (otherwise the release notes for SCUMM would become really verbose).
Also, I reformulated these entries so that people know more clearly that most of the game enhancements can be disabled, if they prefer the original behavior of the games.
=> NEWS: Add some wiki links for the various SCUMM enhancements

common/gui_options.h, engines/advancedDetector.h, engines/agos/detection.cpp, engines/agos/detection_tables.h, engines/drascula/detection.cpp, engines/hypno/detection.cpp, engines/made/detection.cpp, engines/made/detection_tables.h, engines/mtropolis/detection.cpp, engines/mtropolis/detection_tables.h, engines/neverhood/detection.cpp, engines/sword25/detection.cpp, engines/sword25/detection_tables.h, engines/toltecs/detection.cpp, engines/twine/detection.cpp
=> ENGINES: Use ADExtraGuiOptionsMap for the options in engines using AdvancedMetaEngineDetection

engines/director/sprite.cpp
This change renders the QDShape sprites correctly. QDShape in D4 don't have a CastMember associated with the sprite in the score, while setCast() changed the _spriteType, which didn't render them correctly in D4. This change prevents this erroneous change of _spriteType in setCast() for QDShapes
=> DIRECTOR: Prevent changing of spriteType for QDShapes

engines/director/frame.cpp
These logs were added in e42610c3bfb1c50a48f672a11ef74597b553dd82. They're currently unconditionally printed, which gets very noisy. I've adjusted them to only print when they have interesting (e.g., non-0) values.
=> DIRECTOR: only print frame logs when non-0

engines/director/cast.cpp, engines/director/cast.h, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-the.cpp, engines/director/movie.cpp, engines/director/movie.h, engines/director/score.cpp
These changes remove unnecessary occurrences of _loadedCast outside of the Cast namespaces and also implement multiple casts, something which will be used in D5.
=> DIRECTOR: LINGO: Remove all occurences of _loadedCast outside of the Cast namespace

engines/director/cursor.cpp
Starting with 1ac3cb27ac53b1c3e6b9160e611e6e8ea1cd8fac, Bandai Previews Vol. 3 crashes on startup with a failure to load a cursor (`RIFXArchive::getResource(): Archive does not contain 'CURS' 280!`). That commit just registers a new archive to search, so I was confused at first why it would cause it to fail to find the cursor, until I checked the backtrace.
The cursor fetching happens in a loop, here in `Cursor::readFromResource`: https://github.com/scummvm/scummvm/blob/abea37c9bbd92e2f864fb9c7cc1453b56c144572/engines/director/cursor.cpp#L181 It walks through every archive looking for the cursor, and breaks once it's found it. However, inside the archive code, if it fails to find the requested resource, it simply calls `error` instead of returning a `nullptr` so the caller can act on it: …
=> DIRECTOR: failure to fetch from archive may not be fatal

configure
see bug #13603 and advice from @dwatteau.(thank you)
The detection code (not the engines themselves) should only be moved to a dynamic plugin when the backend or memory is extremely limited (e.g. the Nintendo DS and Dreamcast ports, which have very limited RAM on board).
I could live with not backporting, I'll do a manual change for the release build then.
Thank you
=> AMIGAOS: Revert dynamic detection features

devtools/create_japanesemacfonts.sh, devtools/xar-unpacker.py
Replaces the hdiutil/pkgutil based path with one that uses xarunpacker and 7-zip.  Unfortunately while 7-zip can parse XAR, it attempts to extract from the Payload file inside of the XAR instead for from the XAR archive for some reason, which is the wrong file for the first package stage, an issue that's been outstanding since 2015 at least.
This also deletes intermediates immediately after each stage to cut down on the amount of temp storage required since most of the intermediates are in the 4.5GB range.
=> DEVTOOLS: Make create_japanesemacfonts portable using 7-zip and xarunpacker

engines/agos/detection_tables.h
This allows configuring subtitles for The Feeble File on "Edit game" panel.
In current version, subtitles are available but only via special keys (t & v) as described in the game's [ScummVM Wiki Page](https://wiki.scummvm.org/index.php/The_Feeble_Files)
Please note that the subtitles themselves are in english in all localized version
=> AGOS: FF: Enable subtitles configuration

engines/sludge/builtin.cpp, engines/sludge/event.cpp, engines/sludge/sludge.cpp, engines/sludge/sludge.h, engines/sludge/sludger.cpp
This allows opening webpages from inside games. E.g. the help option in out of order.
As a bonus it gets rid of a few global variables.
=> SLUDGE: Reimplement builtin launch for webpages

engines/sludge/detection_tables.h
The filename in the detection was wrong, so it wasn't correctly detected.
=> SLUDGE: Fix detection of nsc

engines/toltecs/detection.cpp
Without this, the EN demo, for example, gets detected as "3 Skulls of the Toltecs (DOS/English)".
=> TOLTECS: Mark demos as demos

base/plugins.cpp, base/plugins.h, engines/ags/metaengine.cpp, engines/cine/metaengine.cpp, engines/composer/metaengine.cpp, engines/cryomni3d/metaengine.cpp, engines/griffon/metaengine.cpp, engines/hugo/metaengine.cpp, engines/lilliput/metaengine.cpp, engines/metaengine.cpp, engines/mohawk/metaengine.cpp, engines/mortevielle/metaengine.cpp, engines/parallaction/metaengine.cpp, engines/stark/metaengine.cpp, engines/teenagent/metaengine.cpp, engines/touche/metaengine.cpp, engines/tucker/metaengine.cpp
`getEngineId()` is only implemented in `MetaEngineDetection` subclasses; in `MetaEngine` subclasses, it always returns `nullptr`. This PR replaces all uses of `getEngineId()` in MetaEngines with `getName()` and removes the default implementation from the base `PluginObject` class.
=> ENGINES: Remove use of getEngineId() in MetaEngine subclasses

engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-the.cpp
This change implements the offset rect function. It also introduces the case of kTheRect in `Lingo::setTheSprite()` which the console was complaining of being nonexistent. The changes have been tested by the `offset rect` workshop movie
=> DIRECTOR: LINGO: Implement offset rect Lingo builtin

engines/director/cast.cpp
This change implements checksum validation VWCF resources. It is based on the ProjectorRays implementation [here](https://github.com/ProjectorRays/ProjectorRays/blob/6ae150ab7449cf7d694691131499a79d112579fc/src/director/chunk.cpp?ts=4#L515-L616)
These changes would work for D4 movies and above.
=> DIRECTOR: Implement VWCF resource checksum validation for pre-D7 movies

engines/director/lingo/lingo-builtins.cpp, engines/director/stxt.cpp
installMenu loads a menu definition from a text cast member. In our
implementation, at load time we coerce the contents to Unicode based on
the platform encoding. Unfortunately for us, Macromedia decided to use
two non-ASCII codepoints for indicating checkmarks and code separators,
which are evaluated as the byte value instead of whatever physical
character they correspond to.
Amending this is slightly hacky, as the UTF-8 equivalent of these
codepoints is two bytes long. The text is first normalised to remove the
platform transformation. The checkmark UTF-8 sequence is replaced with
the single byte equivalent, to maintain compatibility with MacMenu.
Finally, the code separator UTF-8 sequence is used to split the line
between menu definition and script definition.
Fixes the menu system in …
=> DIRECTOR: Fix b_installMenu string decoding

engines/scumm/string.cpp
The following PR fixes some misattributed lines when speaking to Evelyn Morrison near the end of the game, in Sam & Max. If you wear the bigfoot costume and talk to her, the lines are said with Sam's voice, but they're wrongly attached to Max (and so the subtitles and lip-syncing will not be applied to the intended actor).
As far as I can say, this doesn't happen in the CD/DOS/English version of the game, but maybe an earlier version or the Floppy/English has this bug. Anyway, this workaround fixes the script whenever it detects it's wrong.
Script 52-102 does this while talking to Evelyn Morrison while wearing the costume, in the non-English versions:
```
...
if (!bitvar95)
...
[155D] (5D)   if (dup[11] == 998) {
[1564] (BA)     talkActor(sound(0x58724A9, 0xA) + "Quel beau costume!" + …
```
=> SCUMM: Fix some misattributed lines in Sam & Max (non-English)

engines/scumm/string.cpp
For example: 07 FF 07 21 00
The first 07 is the skull, then ff 07 21 appends the verb referenced in
variable 33. If this verb contains control characters, the result is
something like "07 FF 0A 0F 29 ... Some text".
Now, the bidi algorithm *doesn't* skip all the initial control characters
(they are skipped later in the loop), and it only reverses the text, but
the 07 remains in the beginning. The result is 07 FF 0A 0F 29 ... txet emoS
Use a similar technique like was done for INDY4 - Skip the initial 07
character, then append it in the end, and replace the original one with a
space. This gives 32 FF 0A 0F 29 ... txet emoS 07.
=> SCUMM: Fix RTL display for verbs with indirection on MI2

engines/scumm/script_v5.cpp
Yes, there is a dead-end in Monkey Island 2! But it only happens in the [Ultimate Talkie Edition](http://gratissaugen.de/ultimatetalkies/monkey2.html), because another bug in the original game prevented an intended scene from being triggered… so I'm fixing both issues in this PR (in separate commits).
Thanks to Ninou for discovering this dead-end, last summer. I also see that someone [recently reported this problem on Reddit](https://www.reddit.com/r/MonkeyIsland/comments/u7065m/monkey_island_2_glitch_help/). Spoilers ahead…
Whenever you acquire one of of the four map pieces during Part 2, one SCUMM Bit is set so that the other scripts may know about this:
- `Bit[366]` (Rapp's)
- `Bit[55]` (Elaine's)
- `Bit[70]` (Antiques dealer's)
- `Bit[69]` (Rum Roger's)
Then, if you go back to Captain …
=> SCUMM: Fix a dead-end in Monkey Island 2 and restore a reaction from Dread

engines/scumm/string.cpp
fakeBidiString accepts an argument named ignoreVerb. When it is set, we do
not reverse the current section at this point (only these 2 characters are
swapped, so that they'll be swapped back when reversing everything at once
afterwards).
But the condition above covers also end of string *current == 0 along with
the control characters, so on this case, the function still looked for the
newline character past the string buffer. On some cases, a previous string
that was written on the same buffer (the buffer is reused for every string
in the engine), can have newline exactly at this point, and we applied the
same logic, and swapped the newline with 0, which eventually resulted with
some garbled text from the previous buffer.
Fix by excluding end of buffer for this condition.
=> SCUMM: Fix past-buffer read on fakeBidiString

base/commandLine.cpp, configure
This PR fixes 3DS build and cleans up the file a little to remove outdated blocks.
@BallM4788 you may want to take a look at this.
=> Fix commandLine.cpp build on 3DS and various cleanups

engines/mohawk/detection.cpp, engines/mohawk/detection_tables.h
`WSKL.CFG` uses an identical format to Living Books, but uses 16bpp images and a database. Attempting to force the current code to draw the first image (9000) in `Credits.MHK` gives the following log output:
```
Decoding Mohawk Bitmap (640x480, 16bpp, Raw Packing + Unknown Drawing)
Unhandled bpp 16!
```
=> MOHAWK: Add detection for the Williams-Sonoma Guide to Good Cooking

gui/ThemeEngine.cpp, gui/ThemeEngine.h, gui/editgamedialog.cpp, gui/gui-manager.h, gui/widgets/editable.cpp, gui/widgets/editable.h
This allow writing unicode to editable text input, including BiDi support (write RTL and LTR languages together).
The neat trick here is appending single space to calculate the caret position which changes according to last character direction.
=> GUI: Support unicode and BiDi in editable widget

engines/scumm/script_v6.cpp
In DOTT, you can't make George Washington leave the main hall without starting a fire, but this fire can't be started if George Washington is not wearing the chattering teeth.
So, when he comes back to that room, he should be wearing them, but this is not the case during the associated cutscene (he does wear them if you talk to him outside, or come back to this room again after this cutscene). The 2016 remaster didn't fix this either.
So this PR forces costume 69 (= chattering teeth) instead of costume 53 (= no chattering teeth) for George Washington in this script.
1. Start the DOS/English CD release with the [following savegame](https://github.com/scummvm/scummvm/files/9226959/tentacle.s08.zip). Boot param `101` is also very close to this, if you know this part.
2. Pick up the …
=> SCUMM: Fix a continuity error with George Washington's teeth (DOTT)

backends/cloud/cloudmanager.cpp, backends/cloud/cloudmanager.h, backends/cloud/savessyncrequest.cpp, backends/cloud/savessyncrequest.h, backends/cloud/storage.cpp, backends/cloud/storage.h, gui/saveload-dialog.cpp, gui/saveload-dialog.h
Changed SaveLoadCloudSyncProgressDialog and SaveLoadChooserDialog to poll CloudMan instead of being updated from another thread -- in order to fix [#11244](https://bugs.scummvm.org/ticket/11244).
Additionally, some minor GUI changes so SaveLoadChooserDialog is redrawn while SaveLoadCloudSyncProgressDialog is modal, and progress is displayed in bytes (more precise than files count).
Also, removed `loadTimestamps()` in sync request, because it was not only re-reading the file (which seems excessful), but also invalidating save file manager's cache. I've encountered a segfault or a freeze a few times in `MemoryPool::freeUnusedPages()` while testing the other changes, which seems to happen when `DefaultSaveFileManager::assureCached()` clears a hashmap, so this was an attempt to make it much …
=> CLOUD: Fix #11244 crash; do minor changes to GUI

engines/scumm/akos.cpp, engines/scumm/he/script_v72he.cpp
This workarounds https://bugs.scummvm.org/ticket/3533
In general, there seems to be some opcodes in the costume scripts that should be skipped by some unknown condition...
The animation frames in the same costume (809) seems to be 2 sequences:
- freddi talks
- luther talks
So the genral flow of this costume is
- when freddi finishes moving her lips, it's luther turns
- when luther finishes moving his lips, voice become disembodied
for now, this is somewhat hacky solution to loop when the sequence ends prematurely by the counting the amount of lines to be said.
NOTE: This bug does not occur in the original interperter, so there should be some other method, that should solve it from the root cause.
=> SCUMM: FREDDI4: workaround lipsync issues in final scene

engines/sci/detection_tables.h
1. Added a missing King's Quest 4 entry.
2. Added missing version information to some King's Quest 4 entries.
3. Sorted King's Quest 4 detection entries by version and platform.
=> SCI: Improve King's Quest 4 detection entries

engines/pink/gui.cpp, engines/pink/pink.h
This ensures consistent behavior between listing and loading of saves.
I was getting strange results with my localized version, seems like i have saves using both the `peril` and `peril-se` prefixes. With this change both listing and loading uses the new `peril-se` prefix.
=> PINK: Use the actual target when searching for saves

video/qt_decoder.cpp, video/qt_decoder.h
Fixes an error when playing a QuickTime video that has a mediaTime set
on its first edit. This was caused by mediaTime changes in:
ef184a6cef98a1756c0669a03fa9b6fa2386b6e7
Those changes buffered frames during initialization so that the keyframe
and other frames don't play instead of the intended start frame that
mediaTime specifies. My mistake was that decoding isn't allowed during
VideoDecoder::loadStream(); VideoDecoder::setDitheringPalette() requires
that no frames have been decoded yet, and Director calls that.
Now the initial mediaTime buffering is delayed until the first decode.
Fixes bug #13479 where certain Myst videos error.
Fixes the opening movie in the Director game Chop Suey.
=> VIDEO: Fix QuickTime regression with mediaTime and dithering

engines/scumm/script_v5.cpp
In Indy 4, you can play as Sophia in some scenes (for example, in the Azores).
But if you look at Indy with her, she'll speak with Indy's voice, in the Talkie version.
The culprit seems to be script 68-161:
```
(48) if (Var[181] == 2) {
(42)   chainScript(162,[]);
(48) } else if (Var[181] == 11) {
(48)   if (VAR_EGO == 2) {
(D8)     printEgo([Text(sound(0x865362C, 0xA) + "No thanks.")]);
(18)   } else {
(D8)     printEgo([Text(sound(0x8638E5D, 0xE) + "There's nothing to look at.")]);
(**)   }
(18) } else {
(D8)   printEgo([Text(sound(0x8638E5D, 0xE) + "There's nothing to look at.")]);
(**) }
(A0) stopObjectCode();
END
```
I'm not sure what `Var[181]` is, but when using the "Look at" verb, we reach the last `else` block. But this default case uses the same sample for Indy and Sophia, hence …
=> SCUMM: Fix Sophia speaking with Indy's voice when looking at him

backends/platform/sdl/amigaos/amigaos.mk
- Fix an edge-case error during target installation
- Change hardcoded "cp" to it's envvar equivalent
Using
--disable-engine-all
together with plugins will lead to an empty plugins directory/list.
In turn, at least on my platform, both "cp" and "strip" will error out due to missing source files, breaking the rest of the installation.
This fix checks if there are plugins available before attempting to install them, otherwise plugins installation is simply skipped.
It works here locally with and without plugins compiled.
NB: A quick peek at the other targets show that
- opendingux and
- riscos
might be affected aswell?
But due to me knowing nothing about those platforms or how "cp" will react there on missing source files, I'll leave them be.
Also, this is such an edge-case it's probably …
=> AMIGAOS: Fix target installation

common/quicktime.cpp, common/winexe.h
Fixes Coverity defect 1490111 and some VS code analysis warnings.
=> COMMON: Uninitialized field cleanup

engines/dialogs.cpp, engines/engine.h, engines/scumm/metaengine.cpp
It's a distraction to have a button that doesn't do anything useful in all but one engine. So hide it when not supported.
=> Declare custom help support

engines/scumm/script_v5.cpp
This adds an artificial delay to the "Turbo Technologies" loading screen in the PC Engine version of Loom. The original gets its delay - about 10 seconds, judging by the emulator I tried - by loading resources. ScummVM does that in the blink of an eye. Of course, we don't want the full delay. Just a tasteful one to give the player a chance to read it.
I have only tested this with the English version of the game. It would be great if someone could test the Japanese one as well.
This is the script. Attaching the delay to the breakHere opcode was the best way I could think of.
[script-44.dmp.txt](https://github.com/scummvm/scummvm/files/9056378/script-44.dmp.txt)
=> SCUMM: Add delay to "Turbo Technologies" PC Engine Loom loading screen

engines/director/util.cpp
This fixes a bug introduced by 1823539136a680e40153108542db4b8f3481e6ca. That commit made it possible to look into directories when loading files in Util's `testPath`. However, this introduced a bug: if a movie existed in the same path as a directory of the same basename, `testPath` will now find the directory first before the movie. It will return that as the file to open, which will then fail further down the stack when `File::open` fails on it. This adds a check first if the file is a directory before accepting it as the path.
Affected games include Ganbare Inuchan 2 and the Windows version of Spaceship Warlock. I've confirmed this fixes Inuchan 2.
Fixes https://bugs.scummvm.org/ticket/13733.
cc @sev-
=> DIRECTOR: do not try to open dirs as files

backends/platform/ios7/README.md, backends/platform/ios7/ios7_common.h, backends/platform/ios7/ios7_game_controller.h, backends/platform/ios7/ios7_game_controller.mm, backends/platform/ios7/ios7_gamepad_controller.h, backends/platform/ios7/ios7_gamepad_controller.mm, backends/platform/ios7/ios7_mouse_controller.h, backends/platform/ios7/ios7_mouse_controller.mm, backends/platform/ios7/ios7_osys_events.cpp, backends/platform/ios7/ios7_osys_main.h, backends/platform/ios7/ios7_osys_misc.mm, backends/platform/ios7/ios7_scummvm_view_controller.mm, backends/platform/ios7/ios7_touch_controller.h, backends/platform/ios7/ios7_touch_controller.mm, backends/platform/ios7/ios7_video.h, backends/platform/ios7/ios7_video.mm, backends/platform/ios7/module.mk, configure, devtools/create_project/xcode.cpp, dists/ios7/Info.plist, dists/ios7/Info.plist.in, doc/docportal/other_platforms/ios.rst, ports.mk
=> iOS7 Add pointer device support

engines/sludge/detection_tables.h
SLUDGE: Add missing entries to 3 sludge games
Add missing entries for 3 sludge games
- Life Flashes By (Alternate filename)
- Nathan's Second Chance (Alternate filename)
- Cubert Badbone, P.I. (German subtitled version)
=> SLUDGE: Add missing entries to 3 sludge games

engines/scumm/script_v5.cpp
As far as I know, the "I am Choas." typo in Loom was only part of the VGA talkie release (and even Brian Moriarty complained about it!).
So this diff just restricts the existing workaround to the v4 English game, mainly in order to follow the current practice of making the SCUMM workarounds as precise as possible when we can. (The code as it is today wouldn't cause any issue, though, since we `strcmp()`)
I could only test the EGA and talkie releases, though, because they're the only ones I have in English.
@eriktorbjorn: do you think that this is worth it and correct?
=> SCUMM: Restrict the "I am Choas." Loom workaround to the English talkie

backends/graphics/openglsdl/openglsdl-graphics.cpp
Size of the alpha channel is not set to its default value and this caused totally corrupted graphics on my PC.
See:
https://bugs.scummvm.org/ticket/13712
=> BACKENDS: OPENGLSDL: Fix corrupted graphics.

.github/workflows/ci.yml
I'm seeing some `missing jpeglib.h` errors on the CI for macOS today, hopefully this fixes it?
Don't know what it'd suddenly cause an error, though. Maybe we were relying on an implicit dependency that Homebrew has just removed?
**EDIT:** In Homebrew, `jpeg` is the original IJG libjpeg, while `jpeg-turbo` is the libjpeg-turbo fork. Since the Linux builds already use libjpeg-turbo, I thought that using IJG libjpeg in the macOS runner would help cover both cases.
=> CI: Add missing jpeg library for macOS

devtools/README, devtools/make_class.py
When working on new parts of an engine or new engines, the boilerplate needed to add a new
class can be a bit of a chore.  I created a simple script to save some work that others might find useful.
Comments welcome.
=> DEVTOOLS: Add a helper script for adding a class to an engine

engines/sci/detection.cpp, engines/sci/detection_tables.h
SCI: SCI-fanmade detection (ticket #13742)
-   Remove cat-date gameid, since it was only detected as sci-fanmade
-   Rename Osama to full title Osama Been Skatin'
-   Rename The Dating Pool Demo (2019 One Day) to (2016 One Day) based on timestamp in original zip
-   Add detection for 4 new/variants of SCI fanmade games
-   Add commented out detection of 2 variants that crash on start-up with error message
=> SCI: Added detection for SCI fanmade games and removed unused gameid

.github/workflows/ci.yml
This should help catch issues with older versions of GCC in pull requests.
=> CI: Use g++ 4.8 in ubuntu-18.04 builds

engines/scumm/string.cpp
This fixes the skull marker appearing on the wrong line in Monkey Island 2.
specifically when the dialogue has multi-line interpolation (library catalog)
Before:
After:
CC @orgads 
Thanks
=> SCUMM: MONKEY2: fix BiDi in multi-line dialogue interpolation

engines/scumm/string.cpp
This aligns the library cards in Monkey Island 2 to the right
comparison (based on #4189)
Before:
After:
CC @orgads 
Thanks
=> SCUMM: MONKEY2: align library cards to the right

gui/gui-manager.cpp
8cda1fe870e76efd7b13514ab304af64a8187377 introduces a bug where launching a game via the CLI, bypassing the game selection GUI, fails if the game is marked as unsupported. This affects Director games in particular, since almost all of them are marked as unsupported.
To reproduce, try to launch a Director demo directly via the commandline. ScummVM should pop up a "The game you are about to start is not yet fully supported" warning. In `master`, the dialogue is immediately cancelled because of the `secondCommand()` call. Before 8cda1fe870e76efd7b13514ab304af64a8187377, and without this patch, the player is given the chance to choose "start anyway" or "cancel". 
This isn't a permanent fix, but I'm suggesting this partial revert for now to fix the regression.
cc @criezy
=> GUI: temporarily revert dialogue notification

engines/director/archive.cpp
Almost every path returns an error if `getResource` is called but the resource can't be found. These two paths returned a `nullptr` instead. The `MacResource` side of this led to a runtime crash in Alice before 1ed15b789d0f623fc1fab520e8a5fca6ba003ac3. This PR unifies the behaviour so all versions behave identically.
=> DIRECTOR: unify getResource behaviour

engines/scumm/script_v5.cpp
This is a very small issue, since I don't think a lot of players would do the following action… so if you think it's not worth it, that's fine ;)
At the end of Part I, if you close the door just before using the pins with the voodoo doll near Largo, the door will "glitch" this way when he opens it again:
It looks like this is because the door is made of several layers, one of them dealing with the presence/absence of the laundry claim ticket. When Guybrush opens the door, script 13-213 is called and properly clears this, but when Largo escapes from the room, the state of this layer isn't properly updated.
Here's how script 13-200 deals with this action when Largo opens the door:
```
...
[0391] (36) walkActorToObject(6,108);
[0395] (0F) VAR_RESULT = getObjectState(100);
[039A] (08) if …
```
=> SCUMM: Work around a small glitch with Largo's door in Monkey2

engines/scumm/imuse_digi/dimuse_dispatch.cpp, engines/scumm/imuse_digi/dimuse_engine.h
The map in IMuseDigiDispatch can contain unaligned blocks if it contains a TEXT block with a length not divisible by four. This causes unaligned memory accesses in a few places.
I discovered the bug while trying to run The Curse of Monkey Island on my build of version 2.6.0 for the 3DS. Starting the game immediately results in a crash before the first menu of the game can be shown. This also occurs when building from the master branch.
Debugging revealed that this crash happens due to an unaligned write in IMuseDigital::dispatchConvertMap. The pointer mapCurPos can become unaligned if rawMap contains a TEXT block with a length that is not divisible by 4.
Running COMI with `fsanitize=alignment` enabled showed more alignment issues in the same file. (Thanks @dwatteau!)
To fix this, i …
=> SCUMM: DiMUSE: Fix unaligned map access

configure
`-fsanitize=undefined` implies `-fsanitize=alignment` ([source](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#available-checks)), so we need to define `SCUMM_NEED_ALIGNMENT` for UBSan builds, otherwise many false positives will be reported, such as for `engines/scumm/smush/codec47.cpp`.
That's also a good way of having more tests for the `SCUMM_NEED_ALIGNMENT` code paths during development :)
=> CONFIGURE: Enable SCUMM_NEED_ALIGNMENT when using --enable-ubsan

engines/scumm/debugger.cpp
I sometimes need to use the `actor` command in the SCUMM debugger, but some of its useful options (such as `anim`) are not printed in the help section and are just hidden in the code.
This PR will now print all the valid option names.
=> SCUMM: Document all the available actor commands in the debugger

engines/grim/md5check.cpp
This allows to use correct url based on detected game
Related notes: Before this PR, for this translatable string: https://github.com/scummvm/scummvm/blob/master/engines/grim/md5check.cpp#L565
the French and Dutch translations still used the old (now defunct) url: https://wiki.residualvm.org/index.php/Datafiles. 
The newer translations do use a valid url but it's very generic with no immediate info about Grim Fandango or EMI: https://wiki.scummvm.org/index.php/Datafiles
This PR uses a variable string there, so that the correct url is used, based on the detected game. It will be one of these:
- https://wiki.scummvm.org/index.php?title=Grim_Fandango#Required_data_files 
- https://wiki.scummvm.org/index.php?title=Escape_from_Monkey_Island#Required_data_files
=> GRIM: Move required data url into a variable String

engines/scumm/input.cpp, engines/scumm/script_v4.cpp
The `(a == 2) || (_game.platform == Common::kPlatformNES)` doesn't make sense as the NES version only does `saveLoadGame(1)` / `saveLoadGame(2)`, so it's already covered by the first check.
=> SCUMM: Convert if/else if in o4_saveLoadGame to switch; fix typos

engines/scumm/actor.cpp, engines/scumm/akos.cpp, engines/scumm/he/script_v72he.cpp, engines/scumm/scumm.h
Fixes https://bugs.scummvm.org/ticket/3533
by simulating a delay of one frame to unsetting _heTalkie flag.
It seems to match the behaviour in the original interperter.
The workarounds in #4138 are reverted as well as they are no longer needed
Notes:
- Should the revert commit be squashed/rephrased?
- It seems to be potentialy a big change so I limited this behaviour to this game only. perhaps should be reused if other games have lipsync issues.
- ~~I am not sure that sound.cpp is appropriate place for this fix, but for some reason it didn't work when put in actor processing loop.~~
- I didn't notice issues when testing this, but if some are found, some more checks can be added to the test condition.
=> SCUMM: FREDDI4: fix lipsync issues

common/language.h, common/platform.h
This reduces the size of the detection plugin on x86_64 Linux by about 100kb.
=> COMMON: Change Common::Language and Common::Platform to use a smaller type

backends/audiocd/audiocd.h, backends/audiocd/default/default-audiocd.h, backends/audiocd/win32/win32-audiocd.cpp, engines/engine.cpp
This moves the platform-specific logic out of `engine.cpp` and into the backends where it belongs.
=> BACKENDS: Move isDataAndCDAudioReadFromSameCD() to AudioCDManager

engines/scumm/script_v2.cpp
I forget where I saw it, but it was pointed out that the English version of Maniac Mansion (v1) has a typo in Syd's biography, where it says he's "tring" to start his own new-wave band.
Edit: Found it: https://forums.thimbleweedpark.com/t/maniac-mansion-released-on-steam/2162/59
This was fixed in the enhanced version, and at least judging by YouTube videos of the C64 version the typo isn't there either. The NES version apparently rewrites the biography so that the word "trying" is no longer in it.
This pull request fixes the typo, if enhancements are enabled:
(I know I could have used memmove to adjust the string, but I thought a loop made it much clearer exactly what was being moved.)
=> SCUMM: Work around typo in Syd's biography in DOS Maniac Mansion (v1)

engines/glk/zcode/detection_tables.h
Found on the Tandy 2000 release, the only known Infocom game for this computer.
=> GLK: ZCODE: Add detection for The Witness R20-831119

engines/director/director.h, engines/director/lingo/xlibs/cdromxobj.cpp
This adds a non-stubbed implementation of AppleCDAudio. I've tested with the original 1991 Mac version of Alice, and confirmed it works fine.
I haven't implemented the methods that operate on absolute times, because they rely on a CD playback API that works on the full disc TOC. Unless I've missed something, `AudioCDManager` doesn't implement that and there isn't something else that does. However, Alice doesn't use it.
=> DIRECTOR: Implement AppleCDAudio

backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp, backends/graphics3d/openglsdl/openglsdl-graphics3d.h
The Stark engine relies on this to perform it's own aspect ratio correction.
This fixes a regression from commit 60c73721989a7108540646118b43548b36ecc331.
=> OPENGL3D: Restore support for aspect ratio correction

engines/scumm/script_v5.cpp
Monkey Island 1 has a small continuity error which was only fixed in the (quite rare) VGA floppy release.
At the start of Part 2, you see the Sea Monkey ship in the middle of the sea, with its Jolly Roger (pirate flag). You see this scene again when you complete the voodo recipe, and when Guybrush uses the cannon. But the Jolly Roger shouldn't be visible on the ship anymore at this point, since Guybrush must pick it in order to complete the recipe.
That's a small continuity error that the VGA v4 releases (**EDIT:** only *some* of them, see below) actually fixed. But that fix was lost when the game was ported to SCUMM v5. (The Special Edition has this error too. The Ultimate Talkie Edition fixed it.)
In that scene, the flag is drawn by the entry script of room 87. In the EGA release, it's …
=> SCUMM: Bring the Jolly Roger fix from Monkey1 VGA to the other releases

engines/scumm/dialogs.cpp, engines/scumm/he/logic/football.cpp, engines/scumm/he/moonbase/ai_types.cpp, engines/scumm/imuse_digi/dimuse_bndmgr.cpp, engines/scumm/imuse_digi/dimuse_sndmgr.cpp, engines/scumm/resource.cpp, engines/scumm/script_v5.cpp, engines/scumm/scumm.h, engines/scumm/scumm_v7.h, engines/scumm/smush/smush_player.cpp, engines/scumm/sound.cpp, engines/scumm/string.cpp
This replaces every single strcpy call in the engine with
Common::strlcpy.
Some of these cases might seem a bit pointless, but it is
supposed to discourage future use of strcpy. If people don't
see a single occasion of it they might think twice before they
use it...
I have turned it into a PR so whoever is interested can
check whether he/she sees anything suspicious.
=> SCUMM: replace strcpy calls with Common::strlcpy

engines/wage/combat.cpp, engines/wage/detection_tables.h
Removing `ADGF_DEMO` as otherwise it'd apply `ADGF_GENERIC` to `BIGGAMED` entries, which shouldn't have it.
=> WAGE: Simplify armor check, add some games that slipped past

audio/decoders/qdm2.cpp, audio/decoders/wma.cpp, common/bitstream.h, common/stuffit.cpp, engines/macventure/image.cpp, engines/macventure/text.cpp, image/codecs/indeo/get_bits.h, image/codecs/indeo/indeo.cpp, image/codecs/indeo4.cpp, image/codecs/indeo5.cpp, image/codecs/jyv1.cpp, image/codecs/svq1.cpp, video/bink_decoder.cpp, video/bink_decoder.h, video/psx_decoder.cpp, video/smk_decoder.cpp
This helps to improve the performance of the Smacker decoder with the Nintendo DS port.
=> COMMON: Make better use of inlining in BitStream functions

engines/scumm/script_v5.cpp, engines/scumm/scumm_v5.h
The first commit just moves the `SO_TEXTSTRING` decoding part to a separate function, since we're adding more workarounds and that part became quite hard to read.
The second commit adds a new workaround in that place, in order to fix this inconsistency:
https://www.youtube.com/watch?v=BjQqd0zNI-w&t=15485s
When Guybrush meets LeChuck at the end of the game, the priest's lines will vary between 3 different colors fo no reason. The original EGA and VGA floppy don't have this problem.
(You may say that the `"Who's that?"` line may come from LeChuck instead, but it's attached to the priest in the original releases, and it's said with the priest's voice in the Special Edition.)
This only happens in the v5 releases of the game, except for the SegaCD one with its reduced palette (I don't have it …
=> SCUMM: Fix the inconsistent text color for the priest in Monkey1-CD

gui/widgets/list.cpp
Fixes the GUI formatting being read when using TTS
=> GUI: TTS: strip GUI formatting before reading list item

devtools/scumm-md5.txt
`scumm-md5.txt` includes a small script example when one wants to update the file size field if it's still set to `-1`. But this script relies on GNU tools, so it won't work out of the box on macOS, for example.
**Changes:**
* `find` without a path is not portable, so I'm using `find .`
* `head -c` is not portable, so this uses `dd`, instead
* `md5sum` is not portable (it's `md5` on BSD systems), but people usually have OpenSSL so I use that instead
* `du -b` is not portable either, but `wc -c` does the job (POSIX imposes counting bytes and handling binary files)
* `sed -i` is not 100% portable, but in practice it's almost always there on modern systems, and working around this becomes quite inconvenient. So I'm just leaving it as-is
* I'm also using a single call to `find`, only checking …
=> JANITORIAL: SCUMM: Make the MD5/filesize script more portable

.github/workflows/ci.yml
The Xcode CI builds are very noisy at the moment, especially if you compare them to the Ubuntu CI builds. It's so noisy that it's slow to load in Github UI, and it's hard to see and search for what's important.
xcodebuild has a `-quiet` flag, but it appears to remove a lot of stuff, so this `awk` call will just remove the noisiest lines.
OK?
=> CI: Make the Xcode builds around 90% less verbose

engines/sci/sound/music.cpp
This just adds a reverb reset that the original intepreters have. We already had a TODO comment for this, but it was apparently forgotten later.
=> SCI: fix bug no. 11683 ("QFG2 - Heavy reverb from city street sounds")

engines/sci/graphics/text32.cpp
The default behaviour for `Common::convertBiDiString` is to use
`BIDI_PAR_ON` for direction, which means that it tries to guess to
paragraph language, and choose the direction according to it.
However, in SQ6 many (all?) texts begin with control characters,
which make that function to think that these are English texts,
and therefore it chooses LTR direction, and punctuations are wrongly
placed.
Since the call to the function is under `if` clause for RTL,
it's safe to hard code that direction.
=> SCI32: Make RTL BiDi conversion direction hard coded

engines/avalanche/animation.cpp, engines/avalanche/avalot.cpp
Resolves 2 different bugs:
1) _The original game doesn't update the little icon which represents the direction Avalot is facing if you control him with the mouse by clicking on the background. At the moment, this bug is also present in the ScummVM version of the game._ 
from [the wiki page](https://wiki.scummvm.org/index.php/Avalanche).
2) Second commit fixes a bug where the arrow and main character are using the same sprite data which causes them to instantly collide and end the game during a scene.
=> AVALANCHE: Bug fixes

engines/director/castmember.cpp, engines/director/graphics.cpp, graphics/macgui/macwidget.cpp, graphics/macgui/macwindowmanager.cpp, graphics/macgui/macwindowmanager.h, graphics/managed_surface.cpp, graphics/managed_surface.h, graphics/primitives.cpp, graphics/primitives.h
These changes reimplement decomposeColor in macwindowmanager to fix missing text in buttons in 32bpp mode
=> DIRECTOR: Fix missing text in buttons in 32bpp mode

configure
This already fixes a strange hiccup in Grim videos, probably more
@lephilousophe 
Any objections regarding buildbot?
=> AMIGAOS: Use LTO, -O3 and dead code elimination by default

engines/scumm/script_v5.cpp
This was found by @einstein95 on Discord while comparing the scripts of the 1.0/1.1/1.2 EGA releases of Loom.
In the earliest 16-color releases of Loom (English only, it seems), Bobbin will walk *through* the stairs (literally) if you exit one of the rooms in the dragon's cave by using the staircase on the right, after entering the room with the stairs in the middle of the ground. The 16-color 1.2 releases (and probably all later versions) fixed this, but it seems that the original 16-color English release is always 1.0/1.1 and so it always has this bug.
(**EDIT:** this problem also happens with the original DOS interpreter, if using a 1.0/1.1 version.)
It appears that the staircase is drawn with two objects, no. 540 and 541. Their states should change in some conditions (I can't say why …
=> SCUMM: Fix the stairs in room 32 for the earliest Loom EGA releases

engines/groovie/detection.cpp
This PR adds detection for the Russian Akella version reported in trac feature request 13315
The script.grv file is identical to the english version, so I added and additional file to the detector.
Unfortunately I only have the GOG version so somebody needs to check that the Steam version is the same
(it should be)
=> GROOVIE: Update detection 11th Hour ENG version, add RUS version

engines/sci/sound/music.cpp
("hanging MIDI notes")
The original interpreter resets the channels more often than we do
in the remap function. The assumption apparently was that the
loop at the very end of the function would catch everything. But
it does not catch the dontRemap channels if they are not within
the _driverFirstChannel/_driverLastChannel range.
If more bugs like this come up it might be necessary to add even
more resets, but I am very reluctant about unnecessary changes
to the remap function. And this code has been around for a long
time without any other bug reports of this sort. So I think we have
reason to be optimistic about it.
=> SCI: (FPFP/Demo) - fix bug no. 12610

engines/scumm/actor.cpp, engines/scumm/script_v6.cpp
**EDIT:** This PR was improved a bit later on. Please see below.
In Monkey Island 3, if Guybrush reads the clock in Puerto Pollo, he'll imitate a [speaking clock](https://en.wikipedia.org/wiki/Speaking_clock). ScummVM disables this for the German release though, since the result was poor for that language, and because it was disabled in that original release (see [Trac#1493](https://bugs.scummvm.org/ticket/1493)).
I see that the official French release did the same thing, back then (tested with my French CDs in a Windows 98 VM, and on Windows 10 running the original interpreter and then using DREAMM).
Indeed, the result isn't really good in French, either. For example, Guybrush will say *"sept-oh-un et trente-un secondes"* while our speaking clock would say *"dix-neuf heures, une minute, …
=> SCUMM: Replicate the original clock tower behavior (COMI)

dists/scummvm.6
This is a follow-up to PR #4121, regarding the manual page.
I tried to expand/update some descriptions, and improve the formatting a bit. This has been split into many smaller commits for easier (?) review.
I also plan to submit a similar update for `base/commandLine.cpp`, but probably in a distinct PR to avoid reviewing too many commits at once.
=> DOCS: MAN: Various small improvements to the manual page

engines/scumm/script_v5.cpp
In the versions of Monkey Island 1 with the full 256-color inventory, going at Stan's (when he's not there) will mess up the color of some objects, such as the "striking yellow color" of the flower from the forest suddenly being greenish in this room. 
This also happens with the original interpreter.
**Before this fix:**
**After this fix:**
The yellow petals are yellow again, and Guybrush's trousers have their grayish gradient again. (This also fixes some other objects, such as the beak of the rubber chicken.)
The VGA floppy release doesn't appear to have the issue with Guybrush's trousers, so this bug is probably another oversight from the v5 release.
* I'm doing this in `o5_setClass()` because the entry script for room 59 has some `setClass(915,[6])` calls and that's the only reliable …
=> SCUMM: Fix an original palette issue at Stan's in MONKEY1-CD (WORKAROUND)

engines/scumm/scumm.cpp
Commit 2fe65d95ef86433460c2c59eca9de022564c2926 limited render modes to suitable targets, but many users are used to render the DOS/V2 versions of Maniac Mansion and Zak in Amiga mode, to avoid the so-called "sunburn effect".  Playing the game with this setting doesn't cause any issue, as far as I know.
This trick was known for years I believe, it was mentioned somewhere on our forums and PC Gaming Wiki even mentions it:
* https://www.pcgamingwiki.com/wiki/Maniac_Mansion#Higher_quality_graphics_in_V2_.22enhanced.22_version_.28ScummVM.29
* https://www.pcgamingwiki.com/wiki/Zak_McKracken_and_the_Alien_Mindbenders#Higher_quality_graphics_in_.22enhanced.22_EGA_version_.28ScummVM.29
Tested with my English and French V2/DOS versions of Maniac Mansion and Zak. I don't know if using the Amiga …
=> SCUMM: Allow rendering v2 games in forced Amiga mode again

engines/scumm/string_v7.cpp
Following the wonderful work of @AndywinXp and @athrxx for implementing original GUI [1] and perfecting string rendering
The removed block of code is no longer needed, and seems to cause problems on original GUI display on Hebrew (which the block is scoped to).
Thanks
[1] https://github.com/scummvm/scummvm/pull/4206
=> SCUMM: GUI: remove forced alignment

common/quicktime.cpp, common/quicktime.h
Adds a function to flatten the edit lists of a movie, reducing it to a single edit.
Needed to fix this bug in Obsidian: https://github.com/elasota/scummvm/issues/136
For some reason, some vidbot movies have edit lists of exactly-half-second edits, but the audio media time offsets are spaced 22080 apart, causing it to skip ahead 30 audio samples every half-second.  I can't find anything that would explain why this doesn't cause problems elsewhere except that other players might be ignoring edit lists or not handling them accurately.
So, this adds a function that allows the engine to ignore the edit lists, effectively treating the movie as only contiguous tracks.
=> COMMON: Add function to flatten QuickTime edit lists

engines/scumm/actor.cpp, engines/scumm/actor_he.h
Small refactor to SCUMM HE user conditions and talk conditions,
extract the shared bitmask logic to shared function, for this logic to be easier to follow.
generally there is a bitmask of uint32
the first 16 bits are talk conditions (according to the mask, it seems only 13 are used)
and the other 16 bits are user conditions
talk conditions are mutually exclusive, when a talk condition is set, the rest are cleared, except for the first bit.
user conditions can be set without clearing other bits.
=> SCUMM: HE: share condition mask logic

engines/agi/detection.h, engines/agi/detection_tables.h, engines/agi/keyboard.cpp, engines/agi/loader_v2.cpp, engines/agi/text.cpp, engines/agi/words.cpp
Full support for extended characters in French translations, detection for SQ1 FR.
AGI bug fix: Prevents right-click and mouse scroll wheel from adding unwanted keypresses to the player input line when language is HE_ISR or RU_RUS for AGI games.
=> AGI: French Translation support

engines/advancedDetector.h, engines/grim/grim.h
The `ADGameDescription` struct has the following comment about the flags:
```
/**
* A bitmask of extra flags.
*
* The top 16 bits are reserved for generic flags defined in @ref ADGameFlags.
* This leaves 16 bits to be used by the client code.
*/
```
However, the value of `ADGF_TAILMD5` is in the lower 16-bits, rather than the top 16-bits. This PR fixes that discrepancy.
=> ENGINES: Adjust ADGameFlags to fit the specified range

engines/scumm/actor.cpp
This fixes a regression caused by #4225
In Pajama Sam 2 when Sam hides under the sofa the game is stuck on a loop without advancing to the next lines.
seeing the diff, seems I have accidently negated the boolean value, sorry about that 😅 
Thanks
=> SCUMM: HE: fix costume loop regression

engines/groovie/detection.cpp, engines/groovie/script.cpp, engines/groovie/video/player.h
cancelation of fast playback video by right mouse click and proceed watching video with normal speed and sound. It is needed to prevent skipping ghost scenes after speed up slow movement in game.
=> GROOVIE: stop fast video playback capability

video/theora_decoder.cpp, video/theora_decoder.h
Previously the frame rate returned by `TheoraDecoder` was always 0 as it was never set anywhere.
Change it to set the decoder's frame rate to the video frame rate when a video track is loaded.  Possibly not always exactly correct (eg, if there are multiple video tracks), but will be right for most situations.
=> VIDEO: Set decoder frame rate when loading Theora video.

common/xmlparser.cpp, common/xmlparser.h
I'm working on an engine that needs basic text node support in the XML parser.
This is a simple implementation which I think works for my needs, but I'm open to other ideas - eg, should it provide the active element name, or some other structure with more information?
=> COMMON: Add basic text node support to XMLParser

backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
This is due to `glClear()` potentially being called before GLAD is initialised.
=> OPENGL: Fix crash in forced GLES2 mode

engines/scumm/script_v5.cpp
Once more, the v5 release of Monkey Island 1 (likely) didn't use the intended color in some places. This is similar to what was found in PR #4266 or #4168. The root cause appears to be identical: the palette was reordered between the v4 and v5 VGA releases, but some color parameters weren't updated (except in the official SegaCD release, and in the fan-made Ultimate Talkie Edition).
When the navigator head speaks, the v4 VGA floppy release properly kept its text brown, but the v5 VGA release forgot to adjust the `Color(6)` parameters for the v5 palette changes, meaning that the text was in dark purple.
Here's the behavior in the VGA floppy release:
https://www.youtube.com/watch?v=UAvuZsflglw&t=12326s
and here's what happens in the VGA CD release: …
=> SCUMM: Fix the navigator head text color in MI1 CD (WORKAROUND)

engines/mohawk/video.cpp, engines/mohawk/video.h
based on https://github.com/scummvm/scummvm/pull/4186
This adds subtitles support for showing subtitles for videos in Mohawk games.
Specifically tested with MYST.
The overlay approach fits here very well as the video is on very small windows, whereas the overlay can be placed anywhere. 
TODO: define custom positioning per video/frame.
=> MOHAWK: MYST: Add support for video subtitles

engines/agos/animation.cpp, engines/agos/animation.h
This adds subtitles support for The Feeble Files.
based on #4186 
NOTES:
- Only implemented for SMK video. the same method could work for DXA, but couldn't convert with the recent RADTools release to test.
- There is black background when using SDL Surface, which is transparent in OpenGL.
Thanks
=> AGOS: FEEBLE: Add subtitles support for SMK videos

engines/groovie/resource.cpp, engines/groovie/resource.h, engines/groovie/script.cpp, engines/groovie/video/player.cpp, engines/groovie/video/player.h
subtitle file names prepend with GJD name to be compatible with 25th Annv files
@sev- started working on the subtitle support, so I'm not sure if he has a different source for subtitle files we need to be compatible with
also fixed the timestamps for the subtitles
=> GROOVIE: subtitle fixes

engines/scumm/debugger.cpp
This adds the `OBIMoffset` and `OBCDoffset` values to the `objects` table inside the SCUMM debugger. That was quite handy for me when working on PR #4293.
Any objection?
Tested with most of my LucasArts titles, and the handful of HE games I have.
=> SCUMM: DEBUGGER: Add OBIM and OBCD offsets to `objects` command

devtools/scumm-md5.txt, engines/scumm/scumm.cpp
The French VGA floppy version of Monkey Island 1 (and, apparently, this version alone) is missing the usual `'roland'` room, and the index references an invalid `DISK00.LEC` file, although the game scripts didn't disable the MT-32 feature itself. This causes a fatal error when trying to run this game with MT-32 support, even with the original interpreter (while it does work with the English and Spanish VGA floppy versions).
(This is not related to the "Roland Upgrade": this one was meant for the EGA version only; the VGA floppy version had MT-32 support included by default, AFAIK.)
We can't do much about this, since many resources appear to be missing, but we can detect this version (since we have the MD5 sum of the `00.LFL` index referencing that invalid `DISK00.LEC` disk) and warn the …
=> SCUMM: Disable MT-32 support for MONKEY1-VGA-FR

engines/hypno/spider/hard.cpp
Implements the Hebrew version of the chipered message puzzle.
Summary of changes:
- hebrew messages and bounding boxes added
- letter index when selecting letter is reversed in hebrew (letter index decrease when going right).
- hard coded numbers were replaced with appropriate value from the relevant bounding box.
- the method of retreiving the value was changed to be dependent on the index in alpha string rather than rely on codeplage.
(because the letter ordering in the hebrew localization is not standard, also seems to be reverse of how we got the letter)
=> HYPNO: SPIDER: Hebrew chiper message puzzle

engines/scumm/actor.cpp, engines/scumm/actor.h, engines/scumm/boxes.cpp
⚠️ I'm submitting this one in good faith, but I'd need a review from someone with more experience in the SCUMM boxes code than me…
When building with `--enable-ubsan` (with clang++ 14.0 on macOS 12.6) and if I:
1. Start a new Loom Talkie game
2. Click on the leaf on the tree, and let it fall
then UBSan catches this:
```
engines/scumm/actor.cpp:1375:13: runtime error: index 255 out of bounds for type 'uint16[65]'
```
which comes from:
https://github.com/scummvm/scummvm/blob/9c7c48077a86eabde9e91a8eabf60b8cb4727863/engines/scumm/actor.cpp#L1375
`_walkbox` is equal to `kOldInvalidBox` (= 255) in that case, but this array only has 65 elements.
Reading nearby code, the top of `ScummEngine::getMaskFromBox()` and [Trac#791](https://bugs.scummvm.org/ticket/791), I wonder if this could be another …
=> [UNSURE] SCUMM: Prevent an OOB _extraBoxFlags access in Actor::remapDirection()

common/bitstream.h, video/smk_decoder.cpp, video/smk_decoder.h
Performing shifts on 64 bit integers is slower on architectures that don't support them natively (e.g. classic ARM). This isn't done for all users of the BitStream class since it's necessary to make sure that the buffer can be refilled easily if there aren't enough bits available.
=> VIDEO: Avoid 64-bit math in Smacker bitstreams

engines/director/director.h, engines/director/lingo/xlibs/cdromxobj.cpp, engines/director/lingo/xlibs/cdromxobj.h
This takes out the global CDDA state from the Director object and moves it into the AppleAudioCD XObj itself. I've tested with Alice, and it still works as expected.
=> DIRECTOR: move AppleAudioCD CDDA status into CDROM XObj

engines/ags/shared/util/multi_file_lib.cpp
User Joseito reported on Discord that `kq1agdi` crashes on Wii, with `Common::vector` trying to allocate 1409286144 bytes (= 1.4 GB).
This is because `MFLUtil::ReadEncInt32()` didn't properly use the return value of `SwapBytesInt32()`, when building for a big-endian system. Then, huge values would be returned to `MFLUtil::ReadV21()`. The following diff just adds the missing intended `return` keyword, so that the value is properly swapped for big-endian.
This is a backport of my https://github.com/adventuregamestudio/ags/pull/1798 upstream PR, which has been merged.
OK to also backport this to `branch-2-6`?
=> AGS: Fix ReadEncInt32() on big-endian systems

engines/sword1/objectman.cpp
The Spanish demo of Broken Sword is missing a few lines, as indicated
in trac [#12008](https://bugs.scummvm.org/ticket/12008).
There is already a workaround implemented for the other versions, but
it does not work for this demo. In this case, the behavior is similar to
bug #[3753](https://bugs.scummvm.org/ticket/3753).
The PR also replaces the user-provided text with the correct ones,
transcribed from the Spanish speech (thanks to IlDucci).
Demo is available on ScummVM website.
=> SWORD: Fix missing lines in Broken Sword 1 Spanish Demo

engines/mohawk/video.cpp
Fixes https://bugs.scummvm.org/ticket/13874
Which was caused by #4285 , sorry.
The issue was caused when using OpenGL graphics, if the opening logo movie is skipped (so the end was not reached according to `VideoManager`)
also fixed that overlay will not be shown if there are no movies to play.
=> MOHAWK: hide overlay when movie is skipped

NEWS.md
Hi @lotharsm,
Here are some suggestion for the 2.6.1 release notes.
* Use past tense everywhere
* AGS: adjust the description a bit (basically, all `kMFLVersion_MultiV21` games were impacted AFAICS)
* SCUMM: mention commits e177d662e3ccd23f5950e199e040b72fbd116412 and 5bd3ee86fe46206d9dc1a0a47d327e1b37b0c733
* Toltecs: mention commit 277ad722b1a243bd69378725873666675be416b1
* Toon: mention commit ea9e900bfe27217720184e5c25b9f2a84ad8ad95
=> NEWS: Mention more improvements for 2.6.1

configure
I have a workflow where I often run `./configure --help | grep something`, but getting this output is a bit slow.
This part of the configure script repeats some internal checks on each engine: optimizing those checks so that they run fewer processes and do simpler comparisons brings some noticeable improvements.
On macOS 12 where `/bin/sh` is the ancient Bash 3.2.57, this gives me a 30% speed increase. On a WSL1 host where `/bin/sh` is Dash, I see a 40% speed increase, i.e. I save a couple of seconds whenever I run `./configure --help`.
=> CONFIGURE: Make `configure --help` around 30% faster

gui/MetadataParser.cpp, gui/launcher.cpp, gui/launcher.h
This PR adds fields to LauncherEntry structure and makes the building process of the entries list common to both launchers.
It also make sure that when metadata is queried the engined ID is used to match games and not only the game ID as this prevent miscategorization of games because of game ID clashes.
Finally, in grid mode, when grouping by first letter, the title is used as it's what is displayed on the screen.
=> GUI: Rework launcher grouping

engines/scumm/script_v6.cpp
In Sam & Max, if one tries to buy an object at Snuckey's without having the money for it, the employee will tell you to put it back where you've picked it up. As usual, Max has a funny comment for this, but his line will be very quickly cut by the "Anything else?" question from the employee.
This PR makes sure that Max will be able to finish his sentence.
This small oversight also happens in the original DOS interpreter (run through DREAMM) and with the 2002 interpreter from Aaron Giles.
As already done in `o6_talkActor()`, I'm just emulating the missing `waitForMessage()`.
I'm reusing some checks from scripts 11-67 and 11-205 in order to only target the impacted line.
We can't reuse the `_forcedWaitForMessage` trick, since we want to add the missing `waitForMessage()` *immediately …
=> SCUMM: Let Max finish his comment on capitalism at Snuckey's (WORKAROUND)

engines/scumm/gfx.cpp, engines/scumm/script_v5.cpp
This has been bugging me for years, but I'm a bit torn on whether or not ScummVM should work around it. When you drug the dogs in the VGA floppy version, the sign looks like this:
Nice and easy to read. In the VGA CD version, it looks like this:
Which I personally find both ugly and hard to read. Maybe the people who made the Special Edition thought so too, because this is one case where the CD version's behavior wasn't carried over. (Image taken from YouTube playthrough.)
In this pull request, I've tried my best at reproducing the floppy version's colors. The green text color isn't an exact match, but it's as close as I could get it.
I hope the workaround is technically sound. I've tried it with the VGA CD version, and with my two Mac versions.
Come to think of it, I should probably make …
=> SCUMM: Work around hard-to-read colors in MI1 VGA CD and Mac versions compared to the VGA floppy version

engines/agi/op_cmd.cpp
This log() function was previously unimplemented in ScummVM. Its purpose is to write log messages and some metadata about the game state to a file.
This functionality does not affect game play. Presumably Sierra used this to beta test their games. They would log the words that their testers used but the game did not understand. The testers would then submit the log file back to Sierra. Sierra would add the missing words or descriptions to their games before release.
This is the first diff of a couple which will incrementally add this functionality. In this diff, we just collect the information we need to generate a log message close to what AGI actually did.
There are two notable differences which will be fixed in future diffs: (See the comments in the code for more details.)
1. No …
=> AGI: Initial Implemention of AGI's log() Function

base/test_new_standards.cpp
C++11 char arrays initialized by a string literal were not properly implemented before GCC 5.1: <https://gcc.gnu.org/bugzilla/show_bug.cgi?id=43453#c7>.
But we still have some ports using older GCC versions, such as the RISC OS, Dreamcast and OS X PPC ports.
Sometimes, some code wants to use this feature (see commit 6ac3994e3e582ec6a304c2a566bb1b0c69d507d2), so we've forced one of our runners to use an older GCC version to catch this: PR #4164. Otherwise, the build will fail with `error: array used as initializer`.
I thought that also adding it to our C++11 test suit made sense, then?
Tested on the OS X PPC environment (using `./configure --enable-test-c++11`), with G++ 4.8.5 and G++ 7.5.0, and then on macOS 12.6 with Clang++ 14.0. Also tested with MSVC 2022.
=> BASE: Add C++11 char array initialized by a string literal test

engines/scumm/script_v5.cpp
In the v5 releases of Monkey Island 1, the storekeeper on Mêlée Island closes the door *after* going to the counter, which looks very strange since he's far away from it, at this point. In the v4 releases, he just closes it *before* walking away from it, which is much more natural.
This also happens in the original interpreter, and in the Special Edition.
AFAIK the storekeeper isn't meant to have the same Jedi powers as the troll on the bridge, so that's probably yet another scripting oversight from the SCUMM v4 to v5 update.
Fix this by calling the related script (`startScript(26,[387,437])`) just before the storekeeper is going to move away from the door (`walkActorTo(11,232,141)`). That `26` script takes care of checking/updating the state of the `[387,437]` objects, so with the …
=> SCUMM: Prevent the storekeeper from using the Force in in MI1CD (WORKAROUND)

doc/docportal/advanced_topics/command_line.rst
This updates the command line documentation in the doc portal with the following changes:
- improve `Usage` description
- add a section on `Starting a game`
- fix errors in some examples
I am opening this pull request so that I can check that the output is correct using the automatic checks and do not need to install sphinx locally. But feedback on the changes are of course welcome.
=> DOC: Improve command line usage description in docportal

doc/cz/PrectiMe, doc/de/LIESMICH, engines/bbvs/detection.cpp
"Beavis and Butt-head in Virtual Stupidity" -> "Beavis and Butt-Head in Virtual Stupidity"
This matches how it [appears on Wikipedia](https://en.wikipedia.org/wiki/Beavis_and_Butt-Head_in_Virtual_Stupidity) as well as how it's capitalized in [the show itself](https://en.wikipedia.org/wiki/Beavis_and_Butt-Head).
=> ENGINES: Correcting capitalization of bbvs full name

engines/scumm/charset.cpp, engines/scumm/imuse/imuse.cpp
Some `warning()` and `error()` routines in the SCUMM engine will print some raw chars on the terminal, but there's no guarantee that they're printable characters, especially if you've hit a decoding issue and encounter some random bytes.
* For the `charset.cpp` change, an example comes from the fan-made German translation of Zak FM-TOWNS (see [Trac#10530](https://bugs.scummvm.org/ticket/10530#comment:6)) which embeds some erroneous `\r` characters and prints `'!RNING: findVirtScreen(200) failed, therefore printChar cannot print '` (sic) because of this.
* For `imuse.cpp`, the existing code didn't handle non-printable characters either, and it was actually wrong. Just use `tag2str()` (which knows how to deal with unprintable chars), like we do in some other places in that engine.
Any …
=> SCUMM: Don't print unprintable chars in warnings and errors

engines/agi/agi.cpp, engines/agi/agi.h, engines/agi/op_cmd.cpp
Now the log() function writes to a file, as
the AGI engine did.
It appears that ScummVM doesn't have any "append" functionality. As a result, I made this implementation create a new file each time ScummVM it started and a message is logged. The file name includes the game name and the current time, ensuring that logs won't be overwritten.
The format is: agi.\<gameid\>.\<currentime\>.log and will be logged to the working directory.
Last week I first implemented the log() function. In that commit I just had it log to the console. In this commit we start writing to a file.
=> AGI: Write log() Function to File

engines/agi/op_cmd.cpp
Log messages need to be formatted. To do this, we can use the stringPrintF function on text.
=> AGI: Format Logs

engines/scumm/script_v5.cpp
@AndywinXp says I should go submitting this one 😛 
A workaround for [Trac#420](https://bugs.scummvm.org/ticket/420) was added more than 20 years ago, but I can't reproduce the issue anymore with the DOS, Macintosh, or Amiga versions, and back in 2008 @eriktorbjorn said he couldn't reproduce this old issue anymore either.
I couldn't reproduce any lock-up with the original DOS version in DOSBox either.
(I'll submit a second PR for the other getDist() workaround that's just below this one, as all my tests aren't done for that one yet)
=> SCUMM: Remove old MI2 getDist() workaround for Trac#420

NEWS.md, audio/midiplayer.h, doc/cz/PrectiMe, doc/se/LasMig, engines/touche/configure.engine, engines/touche/detection.cpp, engines/touche/midi.cpp, engines/touche/touche.h
The full title is *Touché: The Adventures of the Fifth Musketeer* (with the accented é) as shown on the [Wikipedia page](https://en.wikipedia.org/wiki/Touché:_The_Adventures_of_the_Fifth_Musketeer).
The engine name and game id are still `touche`.
=> ENGINES: Changing Touche to Touché in game & engine name

engines/grim/lua/lstx.cpp
See [Trac#13784](https://bugs.scummvm.org/ticket/13784): this fixes a runtime error whenever pressing a key in EMI in MSVC debug builds.
Upstream fix from GNU Bison 1.28c on 2000-10-02 (since this lstx.cpp file was intentionally built with the now ancient Bison 1.25)
https://git.savannah.gnu.org/cgit/bison.git/commit/?id=da9abf4366d824a23da3d2416856e9a482794eb1
`engines/director/lingo/lingo-gr.cpp`, `engines/hypno/grammar_arc.cpp`, `engines/hypno/grammar_mis.cpp` and `engines/private/grammar.cpp` (built with newer GNU Bison) have the same code.
Tested with MSVC 2022.
@aquadran: Does this look acceptable to you?
=> GRIM: Backport a Bison fix for uninitialized yyval (Trac#13784)

backends/graphics/graphics.h, backends/graphics/null/null-graphics.h, backends/graphics/windowed.h
This adds methods to retrieve the game and overlay rects so I can scale and position subtitles in the overlay in a consistent way relative to the game screen.
=> GRAPHICS: Add a mechanism to get the game and overlay display rects

engines/made/detection_tables.h
Marked as ADGF_UNSTABLE due to lacking MUSIC.BLK (entirely CD-Audio). Commenting out the check for this file gives another error later on: `Failed to find picture 10`
CD contents:
```
187 Jun 22  1990 AUTOEXEC.BAT
84 Jun 22  1990 CONFIG.SYS
33K Jun 22  1990 CONTROL.EXE
863 Jun 22  1990 DICUTY.COM
128K Jun 22  1990 DRIVE_R.IMG
76K Jun 22  1990 IO.SYS
117K Sep  7  1990 MANHOLE.DAT
112K Sep  7  1990 MH.EXP
6.0K Jun 22  1990 OAK2USR.DIC
4.3M Sep  7  1990 PICS.BLK
73K Jul 17  1990 RUN386.EXE
59K Sep  7  1990 SNDS.BLK
80K Jun 22  1990 TBIOS.BIN
387 Jun 22  1990 TBIOS.SYS
238K Jun 22  1990 TMENU.EXP
32K Jul 17  1990 TMENU.ICN
128 Jul 17  1990 TMENU.INF
112K Jun 22  1990 T_OAK2.EXE
```
=> MADE: Add detection for FM-Towns version of The Manhole

engines/glk/scott/detection.cpp, engines/glk/scott/detection_tables.h
Currently the glk/scott detector reports any file with extension .d64 or .t64 as a possible variant of a scott game.
This is not ideal and can lead to a huge number of useless detections if a user picks a folder filled with commodore roms.
This PR simply filters out z80/dat/d64/t64 files. Files with extension .saga and .fiad are not excluded as these extensions
are quite unusual.
The PR also adds the missing fallback entry "Scott Adams IF Game" (previously, all unknown games were reported as
possible Adventureland variants)
=> GLK: SCOTT: Add fallback entry and avoid reporting any C64 rom as a possible variant

engines/dreamweb/dreamweb.cpp, engines/dreamweb/dreamweb.h, engines/dreamweb/saveload.cpp
When the 'Use original save/load screens' option is checked, thumbnails contain the save screen contents instead of the actual map
=> DREAMWEB: fix thumbnails when using original save/load screens

engines/director/lingo/lingo-builtins.cpp
While `go` is intended to be called with either one int arugment or one string and one int argument, Director accepts multiple int args. In this case, it treats the first argument as an integer and silently discards the rest. Before this branch, ScummVM would always treat two arguments as being the movie + frame case and throw a typecheck error for the first argument. This fixes it by checking the type of the first arg and discarding the rest, matching Director's behaviour.
This was seen on the title screen of Wallobee Jack: The Thai Sun Adventure, which calls it like so: `go (the frame) 0`
=> DIRECTOR: handle go with multiple int arguments

backends/dialogs/amigaos/amigaos-dialogs.cpp, backends/fs/amigaos/amigaos-fs.cpp
amigaos-fs.cpp:
- Enhanced some of the debug output
- Renamed some variables for better readability
- Removed two debug outputs (if it works, don't bother me) :-)
- Removed lots of superfluous blank lines
- Removed two unneeded variables
- Tried to follow coding conventions
amigaos-dialogs.cpp:
- initialize pathBuffer
These only touch the AmigaOS4 platform, but i'd still be grateful for comments (especially about coding convention breaches)
Thank you
=> AMIGAOS: Clean up amigaos-fs.cpp/amigaos-dialogs.cpp

.editorconfig, .gitattributes
Subtle parsing problems with labels can happen if Windows batch files are checked out with Unix LF line-endings.
See:
* https://stackoverflow.com/questions/232651/why-the-system-cannot-find-the-batch-label-specified-is-thrown-even-if-label-e
* https://www.dostips.com/forum/viewtopic.php?t=8988
* https://github.com/coq/coq/issues/8610
Submitting this as PR in case someone sees an issue with this, since Windows is not my main development environment.
=> ALL: Force CRLF line-endings for Windows .bat files

backends/platform/android/org/scummvm/scummvm/MouseHelper.java
ANDROID: Fix touchscreen stylus check
Fix issue where all touch input on some tablets was being treated
as mouse input.  Check the tool type used instead of the input device
because SOURCE_STYLUS only indicates a device is capable of obtaining
input from a stylus.  This should fix Ticket #11711.
=> ANDROID: Fix touchscreen stylus check

.github/workflows/ci.yml
This is a follow-up to commit 5fe99667ce48699c7b8053440f1d0235b52c5826.
According to <https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell>, if the Bash shell is used as an implicit configuration instead of an explicit configuration, it won't be run with the `set -o pipefail` option, on Linux and macOS runners.
I think it's probably just better to always enable `pipefail` in the main shell of a CI environment, but maybe someone sees a reason why we should keep things the way they are? Hence the PR.
=> CI: Explicitly use the Bash shell on macOS and Linux for proper `pipefail`

engines/savestate.cpp, gui/options.cpp
Restructure isAutosave() function:
-  Prioritise name test
-  Access saveType test only if name test fails
Performs both tests when required, resolving false positives unique to each test, and ensures that only saves which fail both tests appear in autosave warning dialogs.
Change Global Options autosave test to isAutosave().
Properly fixes #12363, refers #13842
#
=> ENGINES: Properly identify the autosave file

engines/wintermute/base/scriptables/script_ext_directory.cpp, engines/wintermute/detection_tables.h, engines/wintermute/ext/plugins.h, engines/wintermute/ext/wme_windowmode.cpp, engines/wintermute/ext/wme_windowmode.h, engines/wintermute/keymapper_tables.h, engines/wintermute/module.mk, engines/wintermute/wintermute.cpp
This PR provides very basic parts of support for https://questzone.ru/enzi/game/2156
The game is detected and starts, keys works and can be remapped, the internal savefiles are created and seems to be managed correctly, screenmode can be changed.
2 known issues:
* Once you beat any level, the game hangs inside some WME scripts calling Sleep(100) in a loop. Need debugging.
* Sometimes level starts incorrectly, showing static screen instead of interactive playing field. Need debugging.
=> WINTERMUTE: Add initial detection for Lost Bride

engines/dreamweb/stubs.cpp
During Beckett's monologue (location 14), the music plays so loud that I can barely hear him.
This can be due to a bug in the original code preventing this case from being handled properly:
https://github.com/scummvm/scummvm/blob/2d33e5d318b6e43417dbfe94859075cafced0f17/devtools/tasmrecover/dreamweb/dreamweb.asm#L2231-L2239
There are two `cmp`'s in a row here, and I think it should look like this instead:
```assembly
cmp	reallocation,2
jnz	notlouisvol
cmp	mapy,0
jz	fullvol
```
=> [RFC] DREAMWEB: lower the music volume in the last scene

engines/illusions/screen.cpp
Found by UBSAN/ASAN:
```
engines/illusions/screen.cpp:314:13: runtime error: index 768 out of bounds for type 'byte[768]'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior engines/illusions/screen.cpp:314:13 in 
engines/illusions/screen.cpp:315:13: runtime error: index 769 out of bounds for type 'byte[768]'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior engines/illusions/screen.cpp:315:13 in 
```
while starting the demo of Duckman, right after clicking on the very first intro screen of the game.
`_lastFaderIndex` is 256, _mainPalette is 3*256, so if you do something like `_mainPalette[i * 3 + 2]` you don't want the `i ==  _lastFaderIndex` case.
=> ILLUSIONS: Fix an off-by-one in ScreenPalette::updateFaderPalette()

engines/sword25/detection_tables.h
heb patch changes:
- translation of two letters in the game
- improvment of some of the fonts and the menu graphichs
=> SWORD25: set new md5 and size of heb patch

engines/sword2/detection_tables.h
+ add more files to the current entry, so it won't get dismissed by 3-files match for English.
=> SWORD2: Add detection entry for Hebrew V2

gui/widget.cpp
This check has been added in commit 1eff73cb412c6c403be82cde77ee61b9944f805e in 2006 and modified in commit 21989844a9800fe76af93c6b2d70ffd76bf73546 in 2008.
Since then I believe the visible flag couldn't be used and hasn't missed to anyone.
This isVisible function is really time critical because it is called many times at each draw iteration in runLoop.
Checking the theme implies composing a string, hashing it, and looking it up and running the GUI under a profiler (callgrind) makes it pop as time consuming.
=> GUI: Remove visible check in theme

backends/graphics/openglsdl/openglsdl-graphics.cpp
Without this, the window is not refreshed when it is recovered or minimized and restored.
I use a PR for this because I want to be sure it doesn't cause troubles in other platforms.
The same is done in SurfaceSDL backend.
In OpenGL 3D backend it has not to be done because there is no optimization on drawing.
=> OPENGLSDL: Redraw screen when receiving an expose event

engines/scumm/script_v5.cpp
I remember hitting that one with the original interpreter twenty years ago…
In Indy4, in the room in Crete with the "elevator" and where you pick up the gold box, quickly clicking on the right side of the room while Indy's entering it will make him make a "leap of faith" again. But that wasn't intended (since it's not Indy3), and more importantly you'll get completely stuck if you do that:
https://www.youtube.com/watch?v=aQpHjqJ7Zfg&t=19s
This is because the original entry script for room `60` initializes the walkbox matrix too late, so it's possible to move to the other side of the room before the walkbox restrictions kick in. This workaround just copy the original `setBoxFlags()` and `createBoxMatrix()` calls, but trigger them at an earlier stage.
Relevant output from that original …
=> SCUMM: Prevent Indy from being stuck in Crete (WORKAROUND)

backends/audiocd/audiocd-stream.cpp, backends/audiocd/audiocd-stream.h, backends/audiocd/linux/linux-audiocd.cpp, backends/audiocd/linux/linux-audiocd.h, backends/audiocd/macosx/macosx-audiocd.cpp, backends/audiocd/macosx/macosx-audiocd.h, backends/audiocd/win32/win32-audiocd.cpp, backends/audiocd/win32/win32-audiocd.h
This **doesn't** ⚠️  revert these files to GPLv2+. Read their complete headers to be sure to understand what I'm fixing.
The `backends/audiocd/` files are derivative works of the Cabal project, which was GPLv2+. We have the right to put our derivate work under GPLv3+ (since the "+" in GPLv2+ explicitly allows this), but yet when we're quoting the `Original license header:` we shouldn't change the fact that Cabal is a GPLv2+ project.
So this change just keeps our GPLv3+ license header, while mentioning that the original was GPLv2+. (I think this just snuck in during the search/replace that took place in commit abea37c9bbd92e2f864fb9c7cc1453b56c144572).
@sev-: do you agree with this?
=> BACKENDS: Restore original Cabal license header when quoting it

engines/mohawk/detection_tables.h
See the original ticket (https://bugs.scummvm.org/ticket/5724) for confirmation: The French version was accidentally added as English. This can also be confirmed by looking at the filename (lmas**f**.lb), or simply by starting the game.
=> MOHAWK: Fix wrong language for French lilmonster

engines/agi/text.cpp, engines/glk/jacl/interpreter.cpp, engines/glk/jacl/parser.cpp, engines/glk/level9/os_glk.cpp, engines/glk/tads/tads2/vocabulary_parser.cpp, engines/mutationofjb/commands/changecommand.cpp, engines/saga/actor.cpp, engines/saga/interface.cpp, gui/predictivedialog.cpp
This fixes several warnings in buildbot.
strcpy_s is used when strncpy would have the ability to overflow the destination buffer.
In other cases, strlcpy is used. This ensures the string is always zero terminated.
=> ALL: Fix strncpy usages

backends/graphics/android/android-graphics.cpp, backends/graphics/opengl/framebuffer.cpp, backends/graphics/opengl/framebuffer.h, backends/graphics/opengl/opengl-graphics.cpp, backends/graphics/opengl/opengl-graphics.h, backends/graphics/opengl/pipelines/clut8.cpp, backends/graphics/opengl/pipelines/clut8.h, backends/graphics/opengl/pipelines/fixed.cpp, backends/graphics/opengl/pipelines/fixed.h, backends/graphics/opengl/pipelines/libretro.cpp, backends/graphics/opengl/pipelines/libretro.h, backends/graphics/opengl/pipelines/pipeline.cpp, backends/graphics/opengl/pipelines/pipeline.h, backends/graphics/opengl/pipelines/shader.cpp, backends/graphics/opengl/pipelines/shader.h, backends/graphics/opengl/texture.cpp, backends/graphics/opengl/texture.h, gui/gui-manager.cpp
This PR makes several changes to the OpenGL backend.
Majority of changes are quite straightforward but some are less.
The rationale behind all these changes was to allow the LibretroPipeline to own two ShaderPipelines.
This allows to hide all the play with these pipelines inside LibretroPipeline and let OpenGLGraphicsManager play with only one Pipeline and no framebuffer.
The _libretroPipeline object is still here to handle the calls specific to it as having a scaling shader is still something not possible with the base Pipeline model (and we don't necessarily want that).
In the end this let us support the Prev textures (previous frames) in an elegant way.
A clean fix, needed for metacrt shader, is also applied thanks to this rework (the image was up and down).
Finally, there are serval …
=> BACKENDS: OPENGL: Rework libretro pipeline

gui/browser.cpp, gui/widgets/list.cpp, gui/widgets/list.h
Currently file containing \1 in its name causes erroring out with "Wrong string format".
Hades Challenge Mac partiton has such files in the root. So if they are copied then it's impossible to select folder with Hades Challenge. Many tools skip (as they are hidden) or rename them while saving original name in AppleDouble or MacBinary. dumper-companion also renames them but scummvm transparently decodes punycode back.
=> GUI: Fix browsing in presence of files with \1 in names

engines/director/tests.cpp, engines/sci/detection_tables.h, engines/sci/engine/kernel.cpp, engines/sci/engine/kgraphics.cpp, engines/sci/engine/kmisc.cpp, engines/sci/engine/kvideo.cpp, engines/sci/graphics/controls16.cpp, engines/sci/graphics/controls16.h, engines/sci/graphics/cursor.cpp, engines/sci/graphics/macfont.cpp, engines/sci/graphics/macfont.h, engines/sci/graphics/maciconbar.cpp, engines/sci/graphics/maciconbar.h, engines/sci/graphics/scifont.h, engines/sci/graphics/screen.cpp, engines/sci/graphics/screen.h, engines/sci/graphics/text16.cpp, engines/sci/graphics/text16.h, engines/sci/module.mk, engines/sci/resource/resource.cpp, engines/sci/resource/resource.h, engines/sci/sci.cpp, engines/sci/sci.h, engines/scumm/charset.cpp, graphics/font.cpp, graphics/font.h, graphics/fonts/macfont.cpp, graphics/fonts/macfont.h, graphics/macgui/macfontmanager.cpp, graphics/macgui/macfontmanager.h
High-resolution native Macintosh fonts are now supported in the following games when the game's executable is present:
- Castle of Dr. Brain
- Freddy Pharkas
- King's Quest 6
- Leisure Suit Larry 1
- Leisure Suit Larry 5
- Space Quest 1
And on these games when classicmacfonts.dat is present:
- Leisure Suit Larry 6 (floppy)
- Quest for Glory 1
If you're interested in the SCI details about this, engines/sci/graphics/macfont.h starts with a large explanation. If the Mac fonts aren't present then we fall back to SCI fonts like we do now. KQ6 and Freddy Pharkas should always use Mac fonts since we require the game executable for their icon bars.
I modded a few of the games to display internal text wrapping/sizing metrics and I'm happy to say that I can no longer locate discrepancies between …
=> SCI: Macintosh Fonts

backends/midi/coreaudio.cpp, backends/platform/sdl/macosx/appmenu_osx.mm, backends/platform/sdl/macosx/macosx_wrapper.mm
The first part is just a simplification of the checks done to build with the older CoreAudio API, which is required for macOS 10.4 support. Instead of checking for PowerPC CPUs to determine that we're (likely) targeting macOS 10.4, I just reuse the `MAC_OS_X_VERSION_MAX_ALLOWED < MAC_OS_X_VERSION_10_5` preprocessor checks we do in other places, which simplifies things and should make it possible to build for x86 10.4 again (if someone really wants to…).
I'm also fixing the `ComponentDescription`/`AudioComponentDescription` check: this change was done in macOS 10.6, not 10.5.
The other change is for `NSUInteger`. We only redefine it when targeting macOS 10.4, but it should be an `unsigned int` and not an `unsigned long`, on 32-bit architectures. The preprocessor checks come from Apple …
=> MACOSX: Tiger/Leopard CoreAudio and NSUInteger cleanup

configure
By specifying a `*` at the end of the engine in `--enable-engine`, all of its subengines get enabled too.
The `*` character could be changed to something else (like `+`) to avoid globbing in shell.
The code is slightly refactored to be more readable by avoiding nested blocks.
Use of return is superfluous as the error functions make use of exit but it was already done like that above.
In addition I changed a `[` to `test` for consistency.
=> CONFIGURE: Allow to enable all subengines of an engine

engines/scumm/insane/insane_scenes.cpp
In Full Throttle, when Ben uses the goggles to find the secret area in the old mine road, the first and last number being displayed on that view should be formatted in hexadecimal in the original game (yeah), not octal.
Here it is in DREAMM (notice the two `FC` counters):
in the 2002 Windows interpreter by Aaron Giles:
and in ScummVM before this change (notice the `164` counters):
Checked against the DOS version in DREAMM, the 2002 Windows interpreter from Aaron Giles, and the 2017 remaster (all in French though...). I also have the Macintosh release, but I think you'll forgive me if I stop there :)
AFAICS, the 4 counters have the following maximum values, when I visually compare the results while playing with the various interpreters:
```
FF+
78+ 1300- FF+
```
(`+` means that it …
=> SCUMM: INSANE: Fix one of the counters when Ben uses the goggles

doc/docportal/help/faq.rst
The most common definition is that the game is no longer being sold. Clarifying why it is not permitted and removing the out-of-context link to the Game Downloads page.
=> DOCS: Rewriting FAQ paragraph on abandonware

engines/scumm/help.cpp
Two small suggestions for the about dialog in the SCUMM games. I've seen people on Twitch having a look at it, so it still has some use!
1. Always document the '`.`' shortcut to skip lines
* It was restricted to v5+ [a long time ago](http://bugs.scummvm.org/ticket/942), but (fortunately) it looks like we now always implement it (tested while going back to Maniac Mansion v1).
2. Document the original Shift + V cheat shortcut to pass the bike fight / derby action sequences in Full Throttle
* We're already documenting a similar cheat shortcut for Indy4 fights.
* (I've added a small `ADD_LINE;` before it, since it's a cheat and not a regular control.)
OK?
=> SCUMM: Properly document '.' and (Full Throttle) Shift-V shortcuts in help

backends/platform/sdl/opendingux/opendingux.cpp
The default cursor speed is too fast to navigate the menus and pixel-hunt. Reduces the default speed to 2 ("8") to make it manageable.
Also makes the cursor speed configurable from the UI.
/cc @citral23
=> OPENDINGUX: Reduce default cursor speed

engines/bladerunner/slice_renderer.cpp
This patch just moves the calls to `sin()` and `cos()` outside the declaration of the rotation matrix, so that those values are calculated only one time, as it has been already done in other parts of this source code.
=> BLADERUNNER: optimize math calculations.

backends/platform/sdl/amigaos/amigaos.cpp
This adds some defaults for first time users
- scumm remastered theme
- opengl
- gui large enough
- extras and theme path
- audio buffer locked at 2048
this only touches the amigaos part, still, please review
=> AMIGAOS: Add first time user defaults

engines/scumm/help.cpp
Previous `// I18N` description of mine was confusing, especially since it got applied to `_("Shift")` and not `_("Fight cheat")`. Let's be explicit about both lines.
(Mainly making a PR to make sure that no compiler complains about the I18N comments inside the the macro, **DON'T MERGE** before CI is done)
=> SCUMM: I18N: More explicit description of the Shift+V Full Throttle shortcut

engines/saga/detection.h, engines/saga/detection_tables.h, engines/saga/font.cpp, engines/saga/metaengine.cpp, engines/saga/resource.cpp, engines/saga/saga.cpp, engines/saga/saga.h
This is a follow up to PR #4433.
=> SAGA: Move extra tables out of the detection plugin

devtools/create_project/xcode.cpp
Building for macOS [with Xcode](https://wiki.scummvm.org/index.php/Compiling_ScummVM/macOS#Compiling_ScummVM_via_the_Xcode_GUI) currently outputs hundreds of warnings that we normally choose to ignore with ` -Wno-shorten-64-to-32` in the main Makefile.
Xcode has a `GCC_WARN_64_TO_32_BIT_CONVERSION` setting to trigger this option, but it's currently only set for iOS builds. This PR moves this setting to be common to iOS *and* macOS builds. 
End result is much less warning noise in Xcode build console.
Any objection?
=> CREATE_PROJECT: Disable Xcode GCC_WARN_64_TO_32_BIT_CONVERSION on macOS

engines/scumm/dialogs.cpp, engines/scumm/dialogs.h
Add the "use original gui" checkbox to the custom Loom EGA/VGA and Monkey 1 CD version game options window.
Also slightly change to layout for consistency with the other games.
=> GUI: Add "use original gui" checkbox in Loom and MI CD

common/macresman.cpp, common/macresman.h, common/stuffit.cpp
This adds some methods to Archive for getting Mac file metadata from formats that support it, and adds support for it to StuffIt archives.  This is intended to help make it easier to get a generic game boot process for mTropolis going (where the file type codes are useful), but may have other uses.  In the future, will add some things to get the metadata from MacBinary and AppleDouble files, and implement in the Installer VISE 3 reader.
=> COMMON: Add Mac file metadata retrieval API to Archive and implement it for StuffIt

backends/graphics/opengl/opengl-graphics.cpp, engines/agos/animation.cpp, engines/agos/animation.h, engines/groovie/script.cpp, engines/groovie/video/player.cpp, engines/groovie/video/player.h, engines/mohawk/video.cpp, engines/mohawk/video.h, video/subtitles.cpp, video/subtitles.h
This is the follow up of #4417.
This PR:
- avoids clearing the overlay when it supports alpha,
- avoids updating screen when the engine will do it afterwards,
- reorders calls to draw subtitles in engines to have them displayed at the proper frame
- avoids calling `showOverlay` repeatedly,
- prevents messing with overlay when there is no subtitles,
- applies cosmetic changes to developer mode.
In the mean time it fixes some display bugs and properly handles pauses in MOHAWK (it has only been tested on the intro scene).
It has not been tested in GROOVIE and AGOS.
=> GRAPHICS: Optimize and fix subtitles

common/macresman.cpp, common/macresman.h, engines/advancedDetector.cpp, engines/hadesch/hadesch.cpp, engines/hadesch/pod_file.cpp, engines/hadesch/video.cpp
Currently HFS+ partition is supported in following formats:
* On Mac OS X natively
* Apple Double
* Detached .rsrc
* Executable as MacBinary and rest as plain
The last one is used by e.g. dumper-companion.py and automode of hfsutils hcopy but other tools support e.g. hfsutils hcopy 
in macbinary mode copies everything as macbinary and this is a better mode for data preservation as it keeps i.a. file types and finder data. This PR add support for full macbinary copy while keeping other possibilities
=> HADESCH: Support playing HFS partition fully extracted as macbinary

engines/mtropolis/elements.cpp, engines/mtropolis/elements.h, engines/mtropolis/runtime.cpp, engines/mtropolis/runtime.h
This PR makes two changes so SPQR's second puzzle works:
- It adds the `postponeredraws` attribute to the worldmanager.
- It allows setting the animation range of an mToon to a floating-point range. SPQR does this and it used to crash. Note: I have not RE'd the original interpreter so I cannot be sure this behavior is correct, but it works fine for SPQR.
=> MTROPOLIS: Two fixes for SPQR

engines/mtropolis/boot.cpp, engines/mtropolis/detection.cpp, engines/mtropolis/detection.h, engines/mtropolis/detection_tables.h
Currently fails on `if (subObjectSize < lengthOfName * 256u)` in `PlugInModifier::load`
=> MTROPOLIS: Add detection for Star Trek: The Game Show demo

engines/mads/audio.cpp, engines/mads/detection.cpp, engines/mads/detection.h, engines/mads/detection_tables.h, engines/mads/mads.h, engines/mads/metaengine.cpp, engines/mads/resources.cpp
Also yes, OUaF's EXE does reference `drag009.dsr` despite not containing that file. The demos still error out trying to load `FONTINTR.FF` that's apparently in `GLOBAL.HAG`.
After extracting the HAG files, the Rex Nebular demo doesn't use the FAB compression, instead using what's in ScummVM as `Common::GzioReadStream::deflateDecompress`.
=> MADS: Add detection for Once Upon a Forest; fix segment loading for Rex Nebular, Dragonsphere and Phantom demos

.github/workflows/ci.yml
This PR makes the msbuild CI task use [`/v:minimal`](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022) in order to have an output that's comparable to the Xcode and Linux build output (i.e. not excessively verbose).
Rough estimate:
* before: 20 000 lines, 3.8 MB log ooutput
* after: 7 000 lines, 630 KB log output
(Otherwise, I think most people tend not to read this output, because it's so gigantic it takes forever to load, and it's very hard to notice any warning in it.)
Any objection?
=> CI: Make msbuild less verbose

audio/softsynth/cms.cpp, audio/softsynth/cms.h
The DOSBox CMS emulator was removed in 2018 and replaced with MAME's SAA1099 emulator, but there are still a couple of potentially useful changes that were made since it was imported into ScummVM.
=> AUDIO: Backport changes from DOSBox to the CMS emulator 

engines/engine.cpp, engines/engine.h
Similar to the fix already done in 55d31b02601591c8b126b2115d91d3ad6fabc9c5 for strings.  Fixes a warning in Visual Studio:
`G:\src2\scummvm\engines\engine.cpp(482,2): warning C4840: non-portable use of class 'Common::U32String' as an argument to a variadic function`
`G:\src2\scummvm\engines\engine.cpp(482,2): note: 'Common::U32String::U32String' is non-trivial`
`G:\src2\scummvm\engines\engine.cpp(482,2): note: the constructor and destructor will not be called; a bitwise copy of the class will be passed as the argument`
=> ENGINES: Fix warning about passing a non-trivial class to va_start.

.github/workflows/ci.yml
This updates several GitHub Actions components that we use.
Most of them deal with the current Node.js 12 and set-output deprecation warnings:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: `actions/checkout@v2`, `mikehardy/buildcache-action@v1`
> 
> GitHub Actions: Deprecating save-state and set-output commands: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> CI: Update various GitHub actions

common/str.cpp, test/common/str.h
Default value for pos is npos:
`size_t rfind(char c, size_t pos = npos) const;`
So if default value was used, after its cast to int a very big negative value appeared in the right part of MIN((int)_size - 1, (int)pos). Additional check was added to handle this case.
=> COMMON: fix String::rfind for default value of pos (max value of size_t)

engines/tinsel/actors.cpp
On big-endian PowerPC, several Discworld 2 (DOS) characters have very hard to read black subtitles:
(when the narrator reacts after looking at the accelerator for the first time in the High Energy Facility)
(when talking to the Suffrajester in the cemetery)
Those should be red, instead.
It appears that the color given to `SetActorRGB()` is already in native endianness, so there's no need to call `TO_32()` which would do a double conversion on big-endian hosts (but act as a no-op on little-endian hosts).
Looking at `tinlib.cpp:CallLibraryRoutine()` comments, `SetActorRGB()` is apparently only used by DW2 and Discworld Noir. But the `TO_32()` macro was apparently added there in commit b05fa7f20414d6a7571a9ba52f542e527f598c62 for DW1 Mac — maybe just as a small oversight?
I don't have …
=> TINSEL: Fix DW2 subtitle color on big-endian systems

audio/audiostream.cpp, audio/audiostream.h, audio/mixer.cpp, common/ptr.h
Currently DisposablePtr Allows to transparently switch between raw
pointer and ScopedPtr semantics. Add a possibility to have SharedPtr
semantics as well.
Kill getDispose and disownPtr as they unnecessarily expose internal details
Their only user is Channel::loop together with its callee LoopingAudioStream,
switch them to a more modern and transparent Common::move semantics
=> COMMON: Allow DisposablePtr to be backed by SharedPtr

graphics/macgui/mactext.cpp
Fixes a warning about use of uninitialized variable nsx, which can happen if _textLines[nrow].chunks.size() is 0.  In that case, `chunk--` underflows to UINT_MAX and then the conditional block is skipped, and `sx` is returned with uninitialized memory.
=> GRAPHICS: Fix getRowCol returning uninitialized variable nsx if there were no chunks for the chosen line.

engines/director/util.cpp
Pippin videos for Lzone have resource fork and end up in MacBinary format. This apparently fixes Pippin version of L-zone but I didn't check whether it's completable.
=> DIRECTOR: Accept MacBinary for Macintosh and Pippin versions

common/scummsys.h, common/stream.h, common/substream.h, engines/director/archive.cpp, engines/gob/anifile.cpp, engines/gob/anifile.h, engines/gob/cmpfile.cpp, engines/gob/decfile.cpp, engines/gob/decfile.h, engines/gob/rxyfile.cpp, engines/gob/rxyfile.h, engines/kyra/gui/saveload_eob.cpp, engines/kyra/gui/saveload_hof.cpp, engines/kyra/gui/saveload_lol.cpp, engines/kyra/gui/saveload_mr.cpp, engines/kyra/resource/resource.cpp, engines/kyra/resource/resource_intern.h, engines/kyra/resource/resource_segacd.cpp, engines/kyra/script/script_eob.cpp, engines/kyra/script/script_eob.h, engines/mohawk/livingbooks.cpp, engines/mohawk/livingbooks.h, engines/mohawk/livingbooks_code.cpp, engines/mohawk/livingbooks_graphics.cpp, engines/sci/video/robot_decoder.cpp, engines/sci/video/robot_decoder.h, engines/trecision/resource.cpp
This is intended as a replacement for `Common::SeekableSubReadStreamEndian` - since most engines using it don't actually need a partial substream, the new class is simpler and avoids unpredictability when directly accessing the parent stream.
There are a few places in the Director, Kyra and mTropolis that do need a substream, however since adapting those cases is a bit more involved, I've simply marked the old class as deprecated for now.
=> COMMON: Add SeekableReadStreamEndianWrapper

backends/platform/sdl/macosx/appmenu_osx.mm, backends/platform/sdl/macosx/macosx-compat.h
They're the recommended APIs now, and `openFile` is deprecated starting with macOS 11.0. `openURLs:withApplicationAtURL` (for TextEdit usage) requires macOS 10.15+, so we need different code paths.
~~Please don't merge yet, I'd like to test this on macOS 10.4 too.~~ EDIT: done.
=> MACOSX: Prefer openURL/openURLs over openFile on macOS 10.15+

audio/softsynth/cms.cpp, audio/softsynth/cms.h
It would be nice to get rid of the integer division as well, but for now this improves performance in the DS port quite a bit.
This includes the changes from PR #4447.
=> AUDIO: Use fixed-point arithmetic in the CMS emulator

NEWS.md, engines/sky/control.cpp, engines/sky/control.h, engines/sky/sky.cpp, engines/sky/sky.h, engines/sky/skydefs.h, engines/sky/text.cpp, engines/sky/text.h
Unlike other releases that have strings in sky.dsk, Chinese has the strings and the font in the executable.  Including all the strings and entire Big5 font in our code or data seems a bit too much when all we need to read them are 3 values:
* difference between virtual and file offsets
* offset to string index
* offset to font
So far I'm aware of only one release with Chinese but I don't think maintaining this table would be a problem. Probably
with more work first value can be read from some headers and other two can be scanned for, just so far it's not necessarry
=> SKY: Support Chinese Traditional language

engines/agos/agos.h, engines/engine.h, engines/glk/adrift/scprotos.h, engines/glk/adrift/sxprotos.h, engines/glk/archetype/string.h, engines/icb/common/px_string.h, engines/kyra/text/text_lol.h, engines/scumm/scumm.h, engines/sherlock/screen.h, engines/sherlock/tattoo/tattoo_user_interface.h, engines/sky/control.h, engines/sword1/control.h, engines/testbed/testsuite.h, gui/console.h, gui/debugger.h
This adds `MSVC_PRINTF` in several cases where only `GCC_PRINTF` was used until now.
`MSVC_PRINTF` isn't as useful as `GCC_PRINTF` because (AFAIK, just a very casual MSVC user) it's only going to be checked if you enable `/analyze`, but using it shouldn't hurt.
Submitting this as a PR so that I can check the CI part (I've tested some cases myself in Visual Code 2022 but it looks like the whole thing would take a couple of hours…) and in case any MSVC user has an objection.
=> Use MSVC_PRINTF when GCC_PRINTF is used

common/span.h, engines/advancedDetector.h, engines/dragons/dragons.h, engines/glk/events.h, engines/lastexpress/shared.h, engines/mohawk/view.h, engines/mtropolis/data.h, engines/mutationofjb/widgets/widget.h, engines/neverhood/gamevars.h, engines/parallaction/objects.h, engines/sci/engine/script.h, engines/scumm/he/wiz_he.h, engines/scumm/resource.h, graphics/colormasks.h
MSVC shows quite a lot of `warning C4309: 'initializing' : truncation of constant value` when an enum contains an unsigned value.
With C++11, it seems that making those enums do an `: unsigned int` is just a reasonable way of silencing any warning, while making it more explicit that having an unsigned value there is intended.
Not a C++ language lawyer, though, so I hope that's the right approach…
=> ALL: Fix various MSVC C4309 enum sign warnings

engines/wintermute/base/base_object.cpp
Objects used by WME after loading are somehow casted from raw memory without calling constructors.
Thus, _xmodel may be uninstanciated, causing SEGFAULT on `delete _xmodel;` on scene change.
Test case:
1. Start James Peris 2, create a savegame
2. Exit ScummVM
3. Start ScummVM
4. Load game
5. Walk main character to any different location
Expected result: scene change
Actual result (e.g., on dayly Nindendo Switch build): SEGFAULT on  `delete _xmodel;`
=> WINTERMUTE: Fix crash on loaded games

engines/scumm/he/script_v100he.cpp, engines/scumm/he/script_v72he.cpp
This may prevent some possible issues when the scripts define array range assignment of reversed range.
Not sure if it's a good idea to have this fix, as I haven't find any game that used it yet, so I'm unable to test it.
=> SCUMM: prevent possible issues when range is reversed

doc/docportal/other_platforms/ios.rst
With iOS 15, the setting for trusting your own developer certificate has moved to a new location, and on iOS 16, building your own version of ScummVM becomes even more of a burden, because you need to enable Developer Mode (and keep it enabled for the app to continue working… for 7 days).
Since iOS users tend to be quite up-to-date generally, this is probably important.
=> DOCS: Update for iOS 15 and iOS 16 new security settings

engines/draci/sound.cpp
Draci Historie uses a single zipped file for the voices, which are simply numbered .mp3 files.
However, not all "numbers" are present in the filenames, so the total number of files in the archive is lower than the
identifiers; as a result, all the identifiers that are above the filetotal are considered out-of-bounds and ignored.
The bug does not occur when using the original uncompressed file because the maximum value is calculated when unpacking the resources.
The PR simply checks all files and finds the "highest" one, to be used as a limit.
Tested with Czech version, Polish version, English version with czech dub.
NOTE: The Polish dub is missing some lines, but that's unrelated to this bug.
Solves TRAC 6646
=> DRACI: Find max speech file using iterator

doc/docportal/help/faq.rst
=> DOCS: Fixing the hyperlink on FAQ 1.1.5

engines/gob/detection/tables_adibou.h
Source is the double CD-ROM *Le kit rentrée scolaire de la Fnac* (August 1999) that was given for free at the Fnac French retail stores.
It appears to work ouf of the box (cc @sdelamarre). It's an interactive demo.
Should appear as `adibou2-dos-demo-fr.zip` on our demos page soon…
=> GOB: Add detection for Adibou 2 French demo (interactive)

engines/scumm/dialogs.cpp
See [Trac#13947](https://bugs.scummvm.org/ticket/13947).
Before we had support for the original F5 SCUMM menus, ScummVM's own UI was used and so most of the settings (such as enabling subtitles/voices) were properly localized (by us).
However, now that we have support for the original SCUMM UI, an original oversight from LucasArts shows up and may appear as a regression to some ScummVM users (think of kids not being able to read English for example):
Here, in the official French CD release of DOTT, only half of the settings are translated. The ones on the left were hardcoded. (They don't appear in the floppy release at all, AFAIK.)
This was fixed in Sam &  Max CD, though. And Sam & Max uses the same menu, just with a different set of colors.
So this PR just brings the untranslated DOTT …
=> SCUMM: Bring some untranslated DOTT menu strings from Sam & Max

common/array.h
Minor perf improvement: Copies the `_storage` value to a local before operating on the loop so the compiler doesn't have to assume that `_storage` might be modified by the loop (either due to `_storage` aliasing the array, or as a side-effect of calling the constructor/destructor).
This should speed up byte/char array resizes in particular by allowing the compiler to convert them to memsets.
=> COMMON: Optimize some array ops.

engines/director/lingo/tests/chunks.lingo
These were testing `word 1000 of` when the previous checks in the sections are testing `char * of`
=> DIRECTOR: Fix a couple copy-paste errors in chunks.lingo

engines/ultima/module.mk, engines/ultima/ultima8/filesys/savegame.cpp, engines/ultima/ultima8/gumps/minimap_gump.cpp, engines/ultima/ultima8/gumps/minimap_gump.h, engines/ultima/ultima8/misc/debugger.cpp, engines/ultima/ultima8/world/minimap.cpp, engines/ultima/ultima8/world/minimap.h
ULTIMA8: Store minimap data for all maps and add to savegame
This fixes bug [#11486](https://bugs.scummvm.org/ticket/11486)
Since this is an update to the save version, I wanted some discussion around it.
First, this now creates new surfaces for every visited map that are added to the save. When each surface is actually initialized it becomes 512x512 2bpp. With 38 maps in Ultima8, that would mean roughly 19 mb of ram. For saving, the surfaces are cropped to the non-black areas, resulting in a noticeably smaller size. I tested this by generating full maps for around 30 of the maps in game and was pleased that the savegave only increased by less than 500kb, thanks to savegame compression.
Any thoughts on this are greatly appreciated. Thanks!
=> ULTIMA8: Store minimap data for all maps and add to savegame

common/ini-file.cpp, common/ini-file.h, engines/composer/detection_tables.h, engines/composer/metaengine.cpp
This allows reading book configuration file when using the recommended method of extracting files from Macintosh CDs
https://docs.scummvm.org/en/v2.6.1/use_scummvm/mac_game_files.html#python-dumper
fixes some detection entries (previously added with different extraction method)
=> COMPOSER: Support MacBinary format for Macintosh V1 games

common/fs.cpp
Implicit conversion of string to path caused splitting by / instead of intended by DIR_SEPARATOR
=> COMMON: Fix handling of / that caused The 7 colors to fail

common/archive.cpp, common/archive.h
This allows to keep memory footprint low on systems that are low on memory
=> COMMON: Make MemcachingCaseInsensitiveArchive configurably to use weak pointers

backends/fs/posix/posix-iostream.cpp, backends/fs/stdiostream.cpp, configure, devtools/create_project/cmake.cpp, devtools/create_project/xcode.cpp
This tries to be a next step in the 64-bit file offset journey started by PR #3133.
StdioStream currently does this on non-Windows systems (that one already uses `_ftelli64()`): 
```c++
// ...
#elif defined(__linux__) || defined(__APPLE__)
int64 oldPos = ftello((FILE *)_handle);
fseeko((FILE *)_handle, 0, SEEK_END);
int64 length = ftello((FILE *)_handle);
fseeko((FILE *)_handle, oldPos, SEEK_SET);
// ...
```
but several platforms are missing (e.g. BSDs), and having `fseeko()`/`ftello()` doesn't mean that its `off_t` is always 64-bit capable, unfortunately :(
So the following PR tries to improve on this with some new `configure` checks. I'm mostly following the build logic used in most GNU tools:
* test for fseeko() and check whether its `off_t` is >= 8 bytes
* (if fseeko() is there, just …
=> BACKENDS: Make StdioStream use a 64-bit fseeko/ftello on more platforms

engines/agos/agos.cpp, engines/agos/detection_tables.h, engines/agos/res.cpp, engines/agos/res_snd.cpp, engines/agos/string.cpp, engines/agos/subroutine.cpp
It seems that ScummVM expected files copied from HostFS using RedSquirrel or VirtualAcorn, which attempt to map RISC OS file types to Windows file extensions, which isn't done by most other methods of copying data from RISC OS systems. Most of the subdirectories were also missing from the search path.
Detection for the demo version has also been added, which is what this has been tested with. While I haven't tried this with the full version, file names like "gamebase.dat" wouldn't fit in the 10 character limit that was prominent at the time, so it seems likely that this is needed there as well.
=> AGOS: Use proper filenames for the Acorn Floppy version of Simon 1

engines/gob/detection/tables_adibou.h, engines/gob/inter_v1.cpp
The demo tries to load `ADIBODEM\INTROENV.STK`, which on Mac/Linux will fail. Unsure if any other GOB game uses subfolders or how they do it.
[adibou2-demo-en.zip](https://github.com/scummvm/scummvm/files/10204769/adibou2-demo-en.zip)
=> GOB: ADIBOU2: Add couple detection entries and a fix to get one in-game

engines/scumm/dialogs.cpp, engines/scumm/gfx_gui.cpp, engines/scumm/input.cpp, engines/scumm/scumm.cpp, engines/scumm/scumm.h
Thanks to @einstein95, I've been able to fully implement the menu for the Sega CD version of The Secret Of Monkey Island.
F5 will open the GMM, while the SPACE key, acting as our pause button, opens the menu just like on the original.
The SegaCD apparently has no banners (I haven't been able to trigger those...), so those are disabled here as well.
The passcode saving/loading system is fully functional, but please give it some further testing if you can 🙂 
Here are the usual screenshots:
=> SCUMM: GUI: Implement MI1 SegaCD menu

engines/glk/scott/disk_image.cpp
The method `diCreateFromData()` is set up as if it is going to copy the `data` supplied by the caller to the `_image` member, allocating memory for it, but then just assigns `data` to it instead (at line 759), leaking the allocated memory.
This also means that if the data supplied is not a valid disk image, it will delete the original data when it reaches the `default` switch case, potentially causing a double delete down the line if the caller does not anticipate it.
We fix this by just removing the allocation and the deletion. An alternative would have been to actually copy the data instead.
This is based on the updated [original C source](https://github.com/angstsmurf/garglk/blob/c0c4f6df352226b96b493d3ffca08ac4f115ca17/terps/c64diskimage/c64diskimage.c#L476-L541).
=> GLK: SCOTT: Fix leak in disk_image.cpp

engines/glk/scott/resource.cpp
If `nv` or `nn` (number of verbs or number of nouns) is equal to or larger than `nw` (number of words) + 2, these loops will try to write out of bounds and assert. This happens for example in the C64 version of *The Golden Baton*.
To fix this, it is really enough to change the `>=` operator to `>`, but I took the opportunity to simplify the code a bit.
This is based on the updated C source at https://github.com/angstsmurf/garglk/blob/c0c4f6df352226b96b493d3ffca08ac4f115ca17/terps/scott/detectgame.c#L120-L137
=> GLK: SCOTT: Fix out-of-bounds write

common/macresman.cpp, common/macresman.h, common/path.cpp, common/path.h
This is common if HFS(+) directory was compressed in a zip or copied to a FAT or (more rarely) UFS
=> Support AppleDouble inside __MACOSX directory

backends/platform/android/android.h, backends/platform/android/events.cpp, backends/platform/android/org/scummvm/scummvm/ScummVMEventsBase.java, backends/platform/android/org/scummvm/scummvm/ScummVMEventsModern.java
This is an attempt to address [ticket #13909](https://bugs.scummvm.org/ticket/13909).
Previously A and B buttons were sending to left and right click events, X was sending an ESC key event, and Y was opening the system menu. This commit changes those and wires up additional gamepad buttons to the associated Joystick events instead so that more gamepad buttons can be used.
=> ANDROID: Map gamepad inputs to joystick events

engines/ultima/ultima8/kernel/mouse.cpp, engines/ultima/ultima8/kernel/mouse.h, engines/ultima/ultima8/ultima8.cpp
Switching the mouse cursor from an in-engine paint to use of the CursorManager. This makes use of the keycolor now available on the mouse shape frames - tested in Ultima 8 & Crusader: No Remorse. The cursors still needs to update on every frame as the red cross (not-allowed) cursor flashes on a timer.
=> ULTIMA8: Switch to CursorManager for mouse cursor

gui/options.cpp
This is a minor change to the "return to launcher" checkbox that, as indicated in bugreport [#12839](https://bugs.scummvm.org/ticket/12839), is not supported by all engines and could confuse users.
Since implementing that feature is not necessarily trivial and indicating whether the feature is supported or not per-engine
seems redundant, I simply added a generic "not supported by all games" to the tooltip, which should be enough for most
users.
This is just a proposal, feedback is appreciated :)
=> GUI: Change wording of "return to launcher" checkbox

engines/glk/glk_api.cpp
We need to convert ScummVM color values back to Glk format when returning them from `glk_style_measure()`. We do this by encoding the value as a string with `Conf::encodeColor()` and then back with `strtol()`.
This fixes [ticket 13622](https://bugs.scummvm.org/ticket/13622) and the same problem (cyan background in the graphics window) in `Magnetic` and `Level9`.
=> GLK: Return Glk colors from glk_style_measure()

engines/gob/detection/tables_adibou.h
This patch adds a detection entry for the German version of Adibou 2 (dubbed "Adi Junior 2" here) I got with an Packard Bell PC, so it is a OEM bundled version.
And yes, this version is most likely the very first PC game I ever played - thank you @sdelamarre!
This version is playable, but in ScummVM, it is missing the intro sequence and starts straight with the character selection screen.
There are a bunch of warnings printed when starting the game:
```
WARNING: File "APPLIS.BOU" not found!
WARNING: File "ENVIR.BOU" not found!
WARNING: File "RESEAU.BOU" not found!
WARNING: File "RAM.BOU" not found!
WARNING: File "RAM16.BOU" not found!
WARNING: File "DEBUGA.BOU" not found!
WARNING: File "CHEAT.BOU" not found!
WARNING: Urban/Playtoons Stub: Unknown Video/Music command: -2, DEBUT!
WARNING: …
```
=> GOB: Add another German variant of adibou2

configure
I would like to suggest to allow the use of Cygwin as development platform.
This is not intended for providing builds for this environment (although SCUMMVM can be already built on it without problems), but for having an easy way for testing POSIX code on Windows. There could be some alternatives, like the (defunt) Microsoft POSIX subsystem, the (also defunct) Windows Services for UNIX or the WSL1 and WSL2, but they are all painful experiences, at least for me, especially when debugging graphical applications connected to an X server or working with physical devices (try to believe). Alternatively, it is also possible to make a full virtual machine by using emulators like QEMU, but it has not the same advantages of having the code running natively, especially when sharing the same files. …
=> CONFIGURE: Allow Cygwin as development platform.

engines/hpl1/engine/libraries/newton/core/dgVector.h
Removes an assert from a constexpr constructor.  The assert attempts to call a bunch of non-constexpr functions, which is not allowed.
=> HPL1: Fix compile failure in VS2022.

backends/networking/curl/networkreadstream.cpp
We still need to support older versions, so mute the warnings as long as the old APIs can still be used.
=> BACKENDS: Disable curl deprecation warnings

engines/hpl1/engine/libraries/angelscript/angelscript.h
Changes `asEObjTypeFlags` to unsigned to fix constant truncation warnings that are spamming the VS build logs.  As far as I can tell, it's always operated on with asDWORD which is also unsigned so this should be more correct anyway.
=> HPL1: Fix spammy warning in AngelScript

backends/keymapper/remap-widget.cpp
=> GUI: Move keymap descriptions to the left if there isn't enough room

common/scummsys.h, engines/grim/lua_v1.cpp, engines/ultima/nuvie/sound/adplug/opl_class.h
The AmigaOS, MorphOS and Nintendo DS ports hit frequent (several per months) buildbot errors because they use `long` to define `int32` for their own reasons, but `int != int32` is not something that's expected on the most common development environments, and the current CI doesn't catch this case (Github Actions is limited to Ubuntu, Windows and macOS "native" builds, although we could work around this with containers?).
So I was looking for a way to catch this in our current CI *and* on common daily development environments. The sooner we detect an int/int32 mismatch, the better.
On most 32-bit systems, `long` is a 32-bit value too, but building 32-bit binaries is becoming hard on the versions of macOS and Ubuntu supported by GitHub Actions (and they don't want to support any other Linux …
=> COMMON: BUILD: Use 'long' for int32 in MSVC 32-bit builds

engines/gob/detection/tables_ajworld.h
The title screen uses "Jnr." as the abbreviation, so I've used it here
=> GOB: Add detection for ADI Jnr. (Amiga)

engines/scumm/bomp.cpp, engines/scumm/bomp.h, engines/scumm/smush/codec1.cpp
This refactors SMUSH RLE codec (previously codec1) to use BOMP decoder (which is the same algorithm)
Added a flag to BOMP decoder to support transparency (another option was to zero-out the buffer before decoding).
There was a slight difference in the old implementation, of using the source length instead of the given width,
I haven't seen any difference when batch decoding all graphics from FT/DIG/COMI/Mortimer back when I implemented it in python.
anyway, judging by the last line in old implementation* (`dst += pitch - left - width;`), it could potentially cause graphic glitches if for some reason the source line stopped prematurely. (might be a good idea to verify this on disasm, and if needed add both conditions)
I have verified FT's mineroad looks ok.
* the `- width` is apparently …
=> SCUMM: Reuse bomp decoder for SMUSH RLE codec

engines/advancedDetector.cpp, engines/advancedDetector.h, engines/director/detection.cpp, engines/game.cpp, engines/game.h, engines/sludge/detection.cpp, engines/wintermute/metaengine.cpp
This is a second attempton https://github.com/scummvm/scummvm/pull/4377 with 3 changes:
1) Modify as little code as possible
2) Keep ADGF_MACRESFORK semantics unchanged (falling back to datafork)
3) Warning for incorrect dump is moved to next PR
=> ENGINES: Allow AdvancedDetector to match on data fork and to specify type on per-file basis

engines/neverhood/detection.cpp
Opening a PR for this because I don't know if it's related to copyright or something else.
The game title screen is indeed "The Neverhood Chronicles", but that title is never used anywhere
(boxart, manual, mobygames...) so it seems appropriate to just use "The Neverhood" for the
detection entry.
=> NEVERHOOD: Remove "Chronicles" from detection entry

engines/buried/buried.cpp, engines/buried/gameui.cpp, engines/buried/scene_view.cpp
The controlDown boolean is used to check if the CTRL key is pressed, thus
enabling "fast mode". But the status is only updated on key release, meaning
that combinations using CTRL that open GUI windows (GMM and others specific to the engine)
leave the game in this state (unless the player presses another key).
The PR clears the flag when opening these windows and on MAINMENU event.
NOTE: There is a borderline not-working case when the player attempts to quit using CTRL-Z
and exit confirmation is enabled.
fixes TRAC #13584
=> BURIED: Clear _controlDown flag on GUI windows opening

engines/director/game-quirks.cpp
Rodem tracks mouse movement outside the game window. It's not possible to trigger Rodem's movement to the next screen to the left or right just by moving the mouse cursor to the edge of the screen; it has to be tracked outside the screen altogether.
This can be fixed by enabling ScummVM's desktop emulation. I've confirmed this makes both the Mac and Windows versions playable. Since an existing quirk already implemented this behaviour, I've renamed the existing function and given it a more generic name.
Requires @moralrecordings's branch https://github.com/moralrecordings/scummvm/tree/yakenrodem_compat to be able to test gameplay; otherwise the game doesn't get past the loading screen.
=> DIRECTOR: add quirk for henachoco05

engines/neverhood/menumodule.cpp, engines/neverhood/menumodule.h
My big question with it: can I have UTF-8 strings in the source code or should I encode them somehow?
=> NEVERHOOD: Show Japanese overwrite prompt if running Japanese version

configure
This fixes undefined references while the FLAC check is performed during configuring.
My local FLAC dependency was compiled with stack protection, leading to it not being picked up at all, due to a missing -lssp flag.
Forcing -lssp globally in the AmigaOS build now, which hopefully will catch all future dependies that might be compiled with stack protection as well.
Similar fix is in the tools PR.
Thank you very much @sev- and @lephilousophe 
Please review
=> AMIGAOS: Fix FLAC being skipped in configure

configure, ports.mk
RetroWave was not enabled by default in configure and didn't link with it although the library was available.
In addition, the library name was not correct and was missing parts to link on OSX.
=> CONFIGURE: Enable Retrowave if it is available and fix it

engines/scumm/imuse_digi/dimuse_engine.cpp, engines/scumm/imuse_digi/dimuse_engine.h, engines/scumm/imuse_digi/dimuse_tracks.cpp
Posting this as a PR since I'm touching the AUDIO subsystem 🙂 
After a long and painful history of me manually setting the "optimal" value for the number of stream buffers in the queue for DiMUSE games, and after getting a new Android phone which showed me that I still could get audio stutters 🙂, I decided to implement a routine for an adaptive buffer underrun correction. 
This was tested on Windows 10 and Ubuntu 21.10, but testers for different platforms are very welcome! (e.g. other Android devices, AmigaOS, MacOS, etc.)
=> SCUMM: DIMUSE: Implement adaptive buffer underrun correction

engines/ags/engine/ac/sys_events.cpp
When incorporating commits from upstream, it seems this line was left out (not on purpose, I think).
This causes the "repeated mouseclicks" and lines skipping reported in bugs [13894](https://bugs.scummvm.org/ticket/13894), [13988](https://bugs.scummvm.org/ticket/13988), [13994](https://bugs.scummvm.org/ticket/13994)
The related commit is (https://github.com/scummvm/scummvm/commit/5987bc5e6e01c22ee2bd1c1d86fa32e28230de78)
from upstream (https://github.com/adventuregamestudio/ags/commit/471098d239b076c494beb2d554572ccb69372667)
=> AGS: Fix mousepress not being tracked

gui/about.cpp, gui/about.h
This adds mouse wheel scrolling to the credits.  On any mouse wheel interaction, it stops auto-scroll and instead moves up or down 5 lines per mouse wheel tick.
Looking for a specific credit?  Trying to check that something in the About box is displaying correctly?  This'll let you get to it way faster.
=> GUI: Add mousewheel scrolling to credits.

engines/ultima/nuvie/nuvie.h, engines/ultima/shared/early/ultima_early.h, engines/ultima/shared/engine/ultima.cpp, engines/ultima/shared/engine/ultima.h, engines/ultima/ultima8/gumps/container_gump.cpp, engines/ultima/ultima8/gumps/credits_gump.cpp, engines/ultima/ultima8/gumps/difficulty_gump.cpp, engines/ultima/ultima8/gumps/game_map_gump.cpp, engines/ultima/ultima8/gumps/keypad_gump.cpp, engines/ultima/ultima8/gumps/mini_stats_gump.cpp, engines/ultima/ultima8/gumps/minimap_gump.cpp, engines/ultima/ultima8/gumps/paged_gump.cpp, engines/ultima/ultima8/gumps/u8_save_gump.cpp, engines/ultima/ultima8/gumps/widgets/button_widget.cpp, engines/ultima/ultima8/kernel/mouse.cpp, engines/ultima/ultima8/kernel/mouse.h, engines/ultima/ultima8/misc/debugger.cpp, engines/ultima/ultima8/misc/debugger.h, engines/ultima/ultima8/ultima8.cpp, engines/ultima/ultima8/ultima8.h, engines/ultima/ultima8/world/actors/avatar_gravity_process.cpp, engines/ultima/ultima8/world/actors/avatar_mover_process.cpp
As discussed on Discord, I'd like to split the Ultima engine into multiple separate engines to reduce requirements on lower-end devices. This PR removes most of the dependencies on shared code from the Ultima 8 subengine, so it can be cleanly separated from the rest of the engine.
Two exceptions remain for now:
- `UltimaDataArchive` is still used for reading from `ultima.dat`. I plan to split the archive in a separate PR.
- The classes in the `Ultima::Std` namespace are still used throughout the engine, but can easily be duplicated if necessary.
=> ULTIMA8: Remove most dependencies on shared code

common/macresman.cpp
They are created silently by various versions of OSX and may contain garbage describing plain macbinary rather than historically dumped data from disk.
=> COMMON: Downgrade AppleDouble and actual resource forks in macresman

engines/composer/composer.cpp, engines/composer/detection_tables.h, engines/composer/resource.cpp, engines/composer/scripting.cpp, engines/game.cpp, engines/hadesch/detection_tables.h, engines/kyra/detection_tables.h, engines/saga/detection_tables.h, engines/zvision/detection_tables.h
Some of the abuse and suboptimal use stems from past limitations of AD:
* Usage of data fork with ADGF_MACRESFORK
* Checksumming of resource fork when we  don't use it otherwise. Remaining case in MADE engine
This doesn't cover following problems:
* Checksumming macbinary
* Checksumming file when checksum of data fork is intended
=> Improve usage of Advanced detector for Mac case

devtools/dumper-companion.py
Handles an edge case of a disc which had a partition table overwritten with another, making
```
00000430: 4170 706c 655f 4846 5300 6974 696f 6e5f  Apple_HFS.ition_
00000440: 6d61 7000 0000 0000 0000 0000 0000 0000  map.............
```
=> DEVTOOLS: dumper-companion.py: better handle removing null bytes from partition type

graphics/VectorRendererSpec.cpp
This fixes visual issues with the classic theme on some platforms.
=> GRAPHICS: Fix darkened fills on overlays with alpha bits but no blending

backends/graphics/surfacesdl/surfacesdl-graphics.cpp, backends/graphics/surfacesdl/surfacesdl-graphics.h, graphics/VectorRendererSpec.cpp, graphics/colormasks.h, graphics/scaler/hq.cpp, graphics/scaler/hq.h
TODO:
- Both SDL1 and SDL2 always request a 16-bit format for now.
- The dirty rectangle for the cursor isn't always correct and causes graphical issues when moving the mouse large distances.
- Not all scalers support all pixel formats.
=> SURFACESDL: Initial support for 32-bit screen output

engines/bladerunner/fog.cpp, engines/bladerunner/fog.h
There are some values that are read from stream and never changed by the calculations. Since they are used as parameter on expensive math functions like cos() and tan(), it would be worth to pre-calculate their values and use them when needed.
=> BLADERUNNER: pre-calculate some math constants

gui/widgets/grid.cpp
The current GUI has problems rendering complex SVGs, e.g. the Brazilian flag, Croatia, and in general any flag
containing detailed emblems.
Since using simpler flags is unacceptable for various reasons, a possibile approach is to use .png for these flags.
This PR simply updates the loadFlagIcon routine to look for a .png if the .svg file is not available.
Also slightly changes the positioning to preserve alignment.
NOTE!!!
For this PR to work the relative PR in scummvm-icons must be merged:
https://github.com/scummvm/scummvm-icons/pull/88
=> GUI: Attempt loading of .png flags if .svg version is not available

engines/sludge/region.cpp
The engine is using -1 as an undefined direction, so keep it that way after save & restore cycle. Otherwise persons will spin around for a while trying to rotate themselves to 65535 degrees when aligning to a region with undefined direction.
https://user-images.githubusercontent.com/126204/212193088-d8c9963c-0d42-4ed2-83f7-fd4b70774d8e.mp4
=> SLUDGE: Save/restore region's direction as signed integer

engines/sludge/backdrop.cpp
loadHSI calls reserveBackdrop, which resets camera values. Apply camera position and zoom in loadBackdrop after calling loadHSI, so the stored camera state gets preserved.
=> SLUDGE: Fix camera getting reset after loading saved game

engines/sludge/builtin.cpp
newText is an escaped filename, which escapes characters like : and /, which are essential for URLs. Use unescaped version like original OpenSLUDGE does, as otherwise URLs get mangled and become unusable.
=> SLUDGE: Use unescaped value when calling openUrl in launch

engines/glk/scott/unp64/6502_emu.cpp, engines/glk/scott/unp64/6502_emu.h, engines/glk/scott/unp64/exo_util.cpp, engines/glk/scott/unp64/exo_util.h, engines/glk/scott/unp64/unp64.cpp
Parts of the code of Unp64 comes from Exomizer, a tool which uses a modified Zlib license which is actually not compatible with the GPL license that ScummVM uses, as it disallows commercial use. However, the author of Exomizer, Magnus Lind, has given permission to distribute this code under an unmodified Zlib license, so I have updated those parts of the header license text in the Unp64 files.
This is his statement:
>The copyright holder of the Exomizer code, Magnus Lind, hereby dual licenses the code from Exomizer used in unp64. It is now also available under the Zlib-license which makes it compatible with the GPL. (https://en.wikipedia.org/wiki/Zlib_License).
The author of Unp64, iAN CooG, has agreed to let us distribute his code under a GPL license. Or any license we want, to be more …
=> GLK: SCOTT: UNP64: Update license

engines/sludge/transition.cpp
Instead of manipulating alpha with BLEND_MULTIPLY, simply blend in normal mode with translucent black. This fixes transitions with low brightness levels (close to 0), which previously would effectively act as if the level was set to 255.
=> SLUDGE: Fix transitionFader 

engines/director/cast.cpp, engines/director/detection_tables.h, engines/director/resource.cpp, engines/director/window.h
This fixes Fukuoka-Go-Round, which ends up passing the main EXE as a movie to (re)open at runtime instead of a movie. Without this, clicking back to the main menu crashes the disc because it tries to open the EXE as RIFX.
=> DIRECTOR: openMainArchive may be opening an EXE

engines/director/images.cpp
The expected decompression size for D4 and above was being mistakenly overwritten by the D3 size.
Fixes leaves animation in GOODBYE.DIR for Chop Suey.
=> DIRECTOR: Fix pitch calculation for BITDDecoder

engines/sludge/backdrop.cpp
OpenSLUDGE draws the first backdrop image with alpha channel intact. Afterwards, next images are blended with previous backdrop contents.
So far ScummVM always did the later part, but never the former, which caused parallax to not work as it relies on alpha channel being propagated into backdrop (which gets initiallly filled with opaque black, so it had no chance to ever be transparent).
Fix that by clearing the area the first backdrop image is about to get blitted into with full transparency.
=> SLUDGE: Make sure initial backdrop gets its alpha channel stored

engines/scumm/actor.cpp
This would cause the meteor explosion in the Maniac Mansion (V2) intro to not play. Bug reported in Discord by Vanfanel
=> SCUMM: Fix regression in Actor::animateActor from 546fd42749d

backends/networking/curl/curlrequest.cpp, engines/scumm/he/moonbase/net_main.cpp
```
==84284== Mismatched free() / delete / delete []
==84284==    at 0x484371B: operator delete(void*) (vg_replace_malloc.c:923)
==84284==    by 0x5BFBBF: Networking::CurlRequest::~CurlRequest() (curlrequest.cpp:38)
==84284==    by 0x5C0963: Networking::CurlJsonRequest::~CurlJsonRequest() (curljsonrequest.cpp:40)
==84284==    by 0x5ACF0B: Cloud::GoogleDrive::GoogleDriveTokenRefresher::~GoogleDriveTokenRefresher() (googledrivetokenrefresher.cpp:37)
==84284==    by 0x5ACF27: Cloud::GoogleDrive::GoogleDriveTokenRefresher::~GoogleDriveTokenRefresher() (googledrivetokenrefresher.cpp:37)
==84284==    by 0x5BC2FC: Networking::ConnectionManager::interateRequests() (connectionmanager.cpp:189)
==84284==    by 0x5BC0FA: Networking::ConnectionManager::handle() (connectionmanager.cpp:158)
==84284== …
```
=> NETWORKING: fixed mixed malloc/delete/delete[]

engines/director/director.cpp
Games for windows use filepaths where '\' is the separator. Games for mac use ':', which was the default.
This fixes a bug where the filename for c:\fileio.dll was parsed to \fileio.dll. Due to the default ':' everything after the ':' was seen as the filename.
=> DIRECTOR: set dirseparator on windows platforms: \

engines/sludge/sprites.cpp
Otherwise the only difference between it and pasteSpriteToBackDrop is the different color used for blending.
burnString is supposed to transform brightness into alpha. This is pre-rendered already at load time in burnSurface, so use that.
While at that, remove useLightTexture TODOs from above-mentioned functions. The only thing the original interpreter does with useLightTexture in those places is to make sure it's disabled.
=> SLUDGE: Use burnSurface in burnSpriteToBackDrop

.github/workflows/ci.yml
This is a temporary fix for the failing Windows builds in Github CI.
I've forked vcpkg and made a branch at the previous working commit from March 2022 and cherry picked the recent commit that fixes the broken msys-libtool url. This avoids the other incompatibilties that have arisen since March. Specifically, the SDL2_net library file name has changed again. (And maybe there are more problems?)
I know that @SupSuper is working on a proper fix in `create_project`. Until then, I think it would be nice to get our green checkmarks back. =)
Previous working vcpkg commit: https://github.com/microsoft/vcpkg/commit/be5c4ef68b51142ba705f0678b45d284977de677
Recent vcpkg commit that fixes msys-libtool download: https://github.com/microsoft/vcpkg/commit/fd766eba2b4cf59c7123d46189be373e2cee959d
=> CI: Use a fork of vcpkg (temporarily)

engines/neverhood/dialogs.cpp, engines/neverhood/neverhood.cpp
We can't use SearchMan directly in dialogs.cpp as the engine may not be running when dialogs.cpp is called
This has a quirk that you need to reopen settings after changing the extra path. Is there any way to avoid this quirk?
=> NEVERHOOD: Allow loading NHC from extrapath

backends/events/default/default-events.cpp, engines/engine.h, engines/scumm/dialogs.cpp, engines/scumm/gfx_gui.cpp, engines/scumm/metaengine.cpp
This fixes an issue in which keyboard-less platforms would have to always use the virtual keyboard to exit any SCUMM game using the original GUI. Sorry :-)
Now we expose a `Engine::kSupportsQuitDialogOverride` feature from the `Engine`, so that any engine implementing its own GUI (and specifically, dialogs which would overlap with the ScummVM event generated ones, like the quit dialogs) can override the ScummVM ones.
Now, the SCUMM confirmation banners for exiting the game will only appear if the "Ask for confirmation on exit" toggle is active, and when they do, they won't overlap with the ones from the outside world.
Shamelessly requesting a review from anyone who participated in the relevant debate about it 😝
=> SCUMM: GUI: Make quit confirmation dialogs visible only if "confirm_exit" is true

engines/neverhood/gamemodule.cpp, engines/neverhood/gamemodule.h, engines/neverhood/saveload.cpp
This has slightly different logic that original NHC override library. Original library attempts to rotate the solution and current state by the same amount. We do the following:
1. If correct solution didn't change, load as usual
2. If correct solution changed and puzzle was already solved, set both current and correct solution to the new correct solution
3. If correct solution changed and puzzle was not already solved, reinit the puzzle
=> NEVERHOOD: Reload BOBBY puzzle when changing languages with NHC.

engines/ags/engine/ac/character.cpp, engines/ags/engine/ac/display.cpp, engines/ags/engine/ac/display.h, engines/ags/engine/ac/game_state.cpp, engines/ags/engine/ac/global_inventory_item.cpp, engines/ags/engine/ac/global_overlay.cpp, engines/ags/engine/ac/overlay.cpp, engines/ags/engine/ac/screen_overlay.cpp, engines/ags/engine/ac/screen_overlay.h, engines/ags/engine/ac/speech.cpp, engines/ags/engine/device/mouse_w32.cpp, engines/ags/engine/game/savegame_components.cpp, engines/ags/engine/game/savegame_v321.cpp, engines/ags/shared/core/def_version.h, engines/ags/shared/game/main_game_file.cpp, engines/ags/shared/util/multi_file_lib.cpp
This PR continues the task to incorporate AGS upstream commits
from
https://github.com/adventuregamestudio/ags/commit/0f5c6178ac07b96f0703b35334d77f83977d43fd (not included)
up to
https://github.com/adventuregamestudio/ags/commit/17503d7bd066e8bd4a5af490c9ab053a47e4468f
Includes fix for trac [13882](https://bugs.scummvm.org/ticket/13882)
SKIPPED COMMITS:
All the commits related to the "touch-to-mouse emulation", since we still need to decide if it's needed
0f5c6178ac07b96f0703b35334d77f83977d43fd
571d1ccfbb560e31998088e5efe00b415dd572d3
1d59972ba2e4560dbc2c327f7ffdfada9815f938
f9a5ee81a34acfcd63137703df10d199e2eb0013
7d33416a9c96137ec5bc0c738751de0434394d04
14f34b60067679064208096538010702192560b7
5f5acede172c0162e5a721bc740f32d5be1b589f
cc3f2a45f56db9d305e21c82ce4589c76968c944
Engine: …
=> AGS: More commits from upstream

engines/game.cpp
The unknown game report punycode encode the file path of detected file. Currently it treats those as file name. This is an issue for engines that use the `kADFlagMatchFullPaths` flag, as they can have directory separator as part of this path , causing it to be encoded.
For example with Broken Sword unknown variants:
```
{"xn--clustersscripts.clm-2a08g", 0, "6b6d9a32668e6f0285318dbe33f167fe", 1088468},
{"xn--clustersswordres.rif-3a62h", 0, "6b579d7cd94756f5c1e362a9b61f94a3", 59788},
{"xn--smackshicredits.smk-2a08g", 0, "9cea2fbd374c7723f59cfa0ed077df7a", 12467196},
{"xn--smackshiintro.smk-0a88f", 0, "d602a28f5f5c583bf9870a23a94a9bc5", 13525168},
```
This PR delegates the punycode encoding to the `Common::Path` class, to properly handle splitting the path into its components, and encoding …
=> ENGINES: Fix punycode encoding of directory separator in unknown game report

engines/glk/conf.cpp
Currently glk is enabled on low-resolution devices but due to defaulting to 640x400 error()'s out on startup. This changes default on low-resolution devices
=> GLK: Fix invalid default config on low-res devices

gui/options.cpp
This PR improves the display of the achievements descriptions in the achievements tab, taking gui scale
into account and splitting the string into two or more lines if needed.
Reported in TRAC [12946](https://bugs.scummvm.org/ticket/12946)
=> GUI: Show the entire length of descriptions in Achievements tab

engines/scumm/script_v6.cpp
This one was reported by NeoDement on Discord. Thanks!
In DOTT, script 13-21 calls `startScript(1,106,[91,5])` when Jefferson builds the fire, but this script continuously changes the state of the fire object to a random value between 1 and 5 (this stops when you exit his room), and so if Hoagie tries interacting with it, he'll say "I can't reach it." instead of the intended "No. Fire bad." line, most of the time.
This also happens with the original DOS interpreter, the 2002 Aaron Giles Windows interpreter, and the Remastered version.
Script 13-21 (once Jefferson is done building the fire):
```
....
(9C) roomOps.roomScroll(160,VAR_ROOM_WIDTH)
(70) setState(83,0)
(6E) setClass(83,[160])
(70) setState(88,1)
(6E) setClass(88,[32])
(6E) setClass(91,[32])
(5E) startScript(1,106,[91,5]) # <== …
```
=> SCUMM: Fix randomly unreachable fire in DOTT (WORKAROUND)

backends/graphics/opendingux/opendingux-graphics.cpp, configure
By requesting a videomode of 320x200, we can let the software upscaler kick in, which is very sharp
compared to IPU upscaling
=> OPENDINGUX: restore the scaler for the rs90/rg99 ports and use 320x200 for the RG99

backends/platform/sdl/win32/win32.cpp, backends/platform/sdl/win32/win32.h
This should fix jpeg decoding crashing on Win95: https://bugs.scummvm.org/ticket/13643
@ccawley2011 and @lephilousophe figured this out, I just wrote it up in a Win95-compatible check. I haven't tested this code on Win95 as I'm not setup to do those builds, but I have tested the environment variable. When it's set, the Journeyman Project demo no longer crashes on Win95 in vmware.
=> WIN32: Disable libjpeg-turbo SSE usage on Win95

engines/director/castmember.cpp, engines/director/castmember.h
If a bitmap cast member has a custom palette, createWidget() has a routine to dither the image to the current score palette. However, this needs to be done every time there is a change in palette, as the dithering might not match, or not be necessary due to a matching score palette.
Fixes the menu screen in the Mac version of Majestic Part 1.
=> DIRECTOR: Force a widget refresh for bitmaps with custom palettes

engines/scumm/he/intern_he.h, engines/scumm/he/script_v60he.cpp, engines/scumm/saveload.cpp, engines/scumm/scumm.h
This PR makes the save out file table seekable for HE games, and since compressed save files cannot be seeked, it has been disabled when playing Moonbase Commander.  This allows custom maps to be saved properly.  It has been tested with other games, and it does not break saving/loading in those games.
=> SCUMM HE: Disable save compression for Moonbase.

gui/ThemeEngine.cpp
Modern remastered uses cursor with alpha. It's not correctly converted and so we get black rectangle around it when using --disable-16bit
=> GUI: Fix black rectangle around cursor in modern theme without RGB

graphics/tinygl/colormasks.h, graphics/tinygl/texelbuffer.cpp, graphics/tinygl/texelbuffer.h, graphics/tinygl/texture.cpp
This reduces the amount of memory required for textures with packed pixels, and should hopefully offer some performance improvements as well.
=> TINYGL: Make use of ColorMask templates for NearestTexelBuffer

engines/stark/stark.cpp
When using TinyGL, bitmaps need to be deleted before the context is destroyed, otherwise the memory used won't actually be freed.
=> STARK: Fix memory leak

engines/hugo/hugo.cpp, engines/hugo/metaengine.cpp, engines/hugo/parser.cpp
The Hugo games keep a save slot which  is used when restarting the game using CTRL-N.
This PR uses slot 99 (the last available) instead of slot 0, which is normally used for autosaves.
Also fixes TRAC 11559
=> HUGO: Use slot 99 for the "restart" fallback save instead of slot 0

engines/tinsel/saveload.cpp, engines/tinsel/savescn.h, engines/tinsel/sysvar.cpp, engines/tinsel/sysvar.h
With this change we now once again can read pre 2.6 savegames. Similarly savegames created after this fix will be readable by ScummVM < 2.6.0. We will also be able to load savegames created by ScummVM 2.6.x.
The only limitation is that since we now create the same kind of savegames as older versions again, ScummVM 2.6.x will be unable to load savegames created after this.
This fixes bug #13897
=> TINSEL: Handle DW2 saves that had Noir-sized SysVars

dists/macosx/Info.plist, dists/macosx/Info.plist.in
When run from terminal, it'd spit out `NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.` This silences that warning.
=> MACOS: Fix warning about CFBundleTypeRole

engines/stark/gfx/opengltexture.cpp, graphics/opengl/context.cpp, graphics/opengl/context.h, graphics/opengl/system_headers.h
This is split out from PR #4633, and may be useful with OpenGL 1.1 as well.
=> OPENGL: Check if GL_TEXTURE_MAX_LEVEL is supported before using it

common/util.cpp, common/util.h, gui/downloaddialog.cpp, gui/downloadpacksdialog.cpp, gui/options.cpp, gui/saveload-dialog.cpp
This makes it easier to use in debug commands, avoids unnecessary string conversions and fixes a few cases where the units weren't being translated correctly.
=> COMMON: Simplify API for getHumanReadableBytes()

devtools/create_project/xcode.cpp
Mac xcode builds are currently broken when using the latest xcode on anything less than the latest macos version.
We have not been setting `MACOSX_DEPLOYMENT_TARGET` in the project file. This was okay before xcode 14, because xcode would use a reasonable default value. Xcode 14 changed this. Now when this property isn't set, xcode defaults to the maximum os version it's aware of. If the current os is less than this then the build fails.
Xcode 14 introduced `RECOMMENDED_MACOSX_DEPLOYMENT_TARGET` for this purpose, so now we use that. This shouldn't change behavior for earlier xcode versions, but I'm not in a position to test that.
=> CREATE_PROJECT: Set Xcode MACOSX_DEPLOYMENT_TARGET

gui/options.cpp
Previously, the popups for Stretch modes and Scalers would always be created, but were hidden if they aren't supported, leaving a noticeable gap between widgets.
=> GUI: Don't create popups for options that aren't supported

backends/plugins/riscos/riscos-provider.cpp, backends/plugins/riscos/riscos-provider.h, configure
This picks up from where https://github.com/lephilousophe/scummvm/tree/riscos37 left off, and allows builds with dynamic plugins enabled to run on 26-bit versions of RISC OS. Compared to that branch, the RMA fallback has been dropped for simplicity, and dynamic detection has been disabled since it's currently not possible to unload it while engines are running.
Thanks to @lephilousophe for doing the initial work on this.
=> RISCOS: Use dynamic areas for data and application space for plugins

backends/graphics/surfacesdl/surfacesdl-graphics.cpp, graphics/fonts/ttf.cpp, graphics/managed_surface.cpp, image/bmp.cpp, image/bmp.h
This fixes some crashes and visual issues when using hardware palettes in non-RS90 builds, although there are still some issues with the mouse and OSD, as well as when opening the GMM in-game.
=> GRAPHICS: Additional changes for RGB332 overlays

engines/mtropolis/elements.cpp, engines/nancy/cursor.cpp, engines/nancy/font.cpp, engines/nancy/graphics.cpp, engines/nancy/ui/inventorybox.cpp, engines/nancy/ui/viewport.cpp, engines/private/private.cpp, engines/ultima/nuvie/gui/gui_font.cpp, engines/ultima/nuvie/misc/sdl_compat.cpp, engines/ultima/nuvie/misc/sdl_compat.h, engines/ultima/nuvie/screen/screen.cpp, engines/ultima/ultima4/gfx/image.cpp, engines/ultima/ultima4/gfx/image.h, engines/ultima/ultima4/gfx/imagemgr.cpp, graphics/managed_surface.cpp, graphics/managed_surface.h, gui/options.cpp
Palettes with alpha transparency are not used by any engines, and using a different format for palettes compared to the rest of ScummVM prevents blitting code from being reused, in addition to some ambiguity for engines calling `setPalette` or `getPalette`.
This PR only changes the public interface, adapting `ManagedSurface` itself to use a standard palette format will be done in a follow-up PR.
This is currently a draft until proper testing can be done.
=> GRAPHICS: Remove or deprecate RGBA palette functions in ManagedSurface

common/formats/xmlparser.cpp, common/formats/xmlparser.h
For Tetraedge version of Syberia 2 I have a need to parse an xml file which has many key names - the name of the key is used to create a mapping.
Rather than add dozens of functions, I added a simple way of customizing unknown key handling.  This should be completely backward-compatible as the default behaviour is still to raise a parsing error.
=> COMMON: Add ability to handle unknown xml keys

engines/mtropolis/modifiers.cpp, engines/mtropolis/runtime.cpp
When SPQR opens a dialog box it wants to return from, it sets `worldmanager.opint` to 7 before switching `worldmanager.currentscene`  to the dialog box scene. (Other values encountered in SPQR are 2 and 4, which seem to be used for scene transitions that do not go to dialogs.) It therefore seems logical that 7 is used to indicate that the add-to-return-list flag should be set. This PR tentatively assumes that the least significant bit of `opint` is the add-to-return-list flag and sets this flag accordingly when handling writes to `currentscene`.
Together with a (very simple) implementation of the Return Modifier, this PR makes SPQR's dialog handling work (i.e., dialogs can be closed with the exit button now).
Please note that I have not reverse-engineered anything here (as I have no real …
=> MTROPOLIS: Implement the Return Modifier and tentative opint handling

engines/director/sound.cpp
This fixes two separate issues that kept the looping sound in the bedroom from working in The Seven Colours:
* The heuristic to determine if a sound could loop in D3 didn't consider that the start sample could be `0`.
* D3 and D4 seem to have different behaviour for looping sounds, and the conditional that stops loop from the next iteration was stopping sounds that should keep going under D3.
I need to double-check the behaviour for that second one in the editor, but it definitely fixes The Seven Colours.
=> DIRECTOR: fix sound loop in The Seven Colours

engines/ags/shared/util/data_stream.cpp, engines/ags/shared/util/file_stream.cpp
EOS should always return false in this case.
This should fix [#13417](https://bugs.scummvm.org/ticket/13417).
If this works, this needs to be backported to 2.7
=> AGS: Fix FileStream::EOS when used on a file opened for writing

devtools/dumper-companion.py
The script would start trying to set the last-modified date for each part of the output directory path (e.g. /home/).
The previous code was getting too complex so I just implemented a simpler method.
In addition, when run using `--dryrun`, no paths were printed as a side effect of e5cf05a1fa49bcc329dd2461431b914d542b5558, so I've added that back in
=> DEVTOOLS: COMPANION: Fix bug with absolute paths as the output directory

common/compression/stuffit.cpp
This improves file corruption checking but due to its breakage potential I propose to shunt it to the next version. Opening PR so it doesn't get lost
=> COMMON: Check CRC16 in Stuffit

backends/platform/sdl/sdl-window.cpp
As shown by bug https://bugs.scummvm.org/ticket/14132, getting the DPI can be unreliable on some system, causing abnormal DPI scaling factor to be used. So I am proposing to clip the DPI scaling factor to a reasonable range. This should fix that bug since it will now return a factor of 1 instead of 0.289459 (I don't see any case where returning a value below 1 would make sense).
The change is simple, but I am creating a pull request in case I overlooked a possible issue with it.
=> SDL: Clip DPI scaling factor to ensure we get a reasonable value

backends/graphics/opengl/texture.cpp
As in SurfaceSDL, the dirty rect must be grown.
The operation is done in [surfacesdl-graphics.cpp:1677](https://github.com/scummvm/scummvm/blob/08b79f77c3377a0a04df53f23d4d877ad0162476/backends/graphics/surfacesdl/surfacesdl-graphics.cpp#L1677)
This should fix [#14168](https://bugs.scummvm.org/ticket/14168).
=> OPENGL: Properly take extra pixels into account when using scalers

audio/softsynth/eas.cpp, audio/softsynth/fluidsynth.cpp
This PR basically adds support for loading soundfonts using custom callbacks with FluidLite.
It then adds an Android specific workaround to always use our file system abstraction to load the sound font.
=> AUDIO/ANDROID: Add support for loading SoundFonts using SAF

engines/scumm/he/logic/football.cpp
This fixes a crash that occurs when trying to load and save a custom playbook file in Backyard Football 2002.  That line was randomly added in commit 3d39d206eeb7156562534fad5ba499781e5b79bd, and will always result in an assertion error.  That call wasn't here previously, and I do not see any reasoning behind it, so might as well get rid of it.
=> SCUMM HE: Fix loading playbooks in Football 2002.

dists/scummvm.appdata.xml
This changes license in the project_license tag to a correct one as suggested by @lotharsm in https://github.com/flathub/org.scummvm.ScummVM/pull/28#pullrequestreview-1297508199.
This should ideally be merged not only into master, but also into the upcoming 2.7 branches (if possible) and ideally before ScummVM 2.7.0 gets released.
=> DISTS: Fix project_license in AppStream metadata

engines/hpl1/engine/libraries/newton/core/dgPolyhedra.cpp
The HPL1 engine seems to be still under heavy development so this is rather a workaround to fix the build on x64 platforms with Clang which is very strict regarding pointer conversions to smaller types.
=> HPL1: Fix build with Clang on x64 platforms

engines/glk/scott/c64_checksums.cpp, engines/glk/scott/unp64/6502_emu.cpp, engines/glk/scott/unp64/exo_util.cpp, engines/glk/scott/unp64/exo_util.h, engines/glk/scott/unp64/scanners/action_packer.cpp, engines/glk/scott/unp64/scanners/byte_boiler.cpp, engines/glk/scott/unp64/scanners/caution.cpp, engines/glk/scott/unp64/scanners/ccs.cpp, engines/glk/scott/unp64/scanners/cruel.cpp, engines/glk/scott/unp64/scanners/eca.cpp, engines/glk/scott/unp64/scanners/exomizer.cpp, engines/glk/scott/unp64/scanners/expert.cpp, engines/glk/scott/unp64/scanners/master_compressor.cpp, engines/glk/scott/unp64/scanners/megabyte.cpp, engines/glk/scott/unp64/scanners/pu_crunch.cpp, engines/glk/scott/unp64/scanners/section8.cpp, engines/glk/scott/unp64/scanners/tbc_multicomp.cpp, engines/glk/scott/unp64/scanners/tcs_crunch.cpp, engines/glk/scott/unp64/scanners/xtc.cpp, engines/glk/scott/unp64/unp64.cpp, engines/glk/scott/unp64/unp64_interface.h
This updates UNP64, the library used by the ScottFree engine to decompress Commodore
64 files.
The UNP64 code was not endian safe, contained many unaligned and a couple of
out-of-bounds reads and errors made in the translation to C++.
This fixes that, mainly by adding a number of helper functions to `exo_util.cpp` and
replacing the unsafe code with calls to them.
Some of the helper functions might replicate functionality that already exists in
`common/endian.h`, I haven't really looked into this.
It also changes the  interface called by the ScottFree engine, removing one
parameter and moving the parsing of "switches" out of  `c64_checksums.cpp` 
in Scott into `unp64.cpp`.
There is a small number of other minor fixes and cleanups of the UNP64 code.
I have tested this with all the relevant …
=> GLK: SCOTT: Update UNP64

engines/director/images.cpp, engines/hpl1/engine/libraries/newton/core/dgHeap.h, engines/hpl1/engine/libraries/newton/core/dgNode.h, engines/hpl1/engine/libraries/newton/core/dgPolygonSoupDatabase.h
The purpose of `Common::remove_const` (and `std::remove_const` outside of ScummVM` is not to remove the const specifier from a variable, but to remove it from a type and define a non-const type in the process. It is typically use in template code, such as this example given by @lephilousophe on Discord (thanks, that saved me the trouble of creating one myself 😄 ):
```cpp
template<typename T>
class Test {
Common::remove_const<T> mutable_item;
T *array;
}
```
The previous commit to fix the warning thus did not fix anything as the code was still doing a C cast from a const type to a non-const one to remove the const specifier from the byte array. The proper way to fix that warning is to use a const_cast, as done in this pull request.
The main reason I am not committing this directly and …
=> DIRECTOR: Really fix warning

engines/asylum/detection_tables.h, engines/asylum/system/text.cpp
This adds BiDi text rendering support for the upcoming Hebrew fan-translation of Sanitarium.
RES.005 is used for detection as it's less likely to change (RES.005 contains chapter 1 fonts, RES.000 contains texts)
Thanks
=> ASYLUM: Support hebrew fan-translation

engines/vcruise/POTFILES, engines/vcruise/audio_player.cpp, engines/vcruise/audio_player.h, engines/vcruise/configure.engine, engines/vcruise/credits.pl, engines/vcruise/detection.cpp, engines/vcruise/detection.h, engines/vcruise/detection_tables.h, engines/vcruise/metaengine.cpp, engines/vcruise/module.mk, engines/vcruise/runtime.cpp, engines/vcruise/runtime.h, engines/vcruise/script.cpp, engines/vcruise/script.h, engines/vcruise/textparser.cpp, engines/vcruise/textparser.h, engines/vcruise/vcruise.cpp, engines/vcruise/vcruise.h, video/avi_decoder.cpp, video/avi_decoder.h
This adds initial support for the V-Cruise engine used by Reah: Face the Unknown and Schizm: Mysterious Journey and initial detection for Reah.  (I actually need to figure out the detection some more because the GOG version and DVD version only ship English VO.)
This is very preliminary right now, right now it boots Reah to the intro cinematic and then gets stuck at the opening screen, I'm working on getting navigation implemented.
Documentation of its formats (and a decoder/encoder for the scripts) currently resides at https://github.com/elasota/vcr, everything is documented except for yet-to-be-understood script ops and the "morph" format which was added in Schizm.
The biggest change to core is the addition of cursor masks.  Reah uses a magnifying glass cursor where the lens part is …
=> VCRUISE: Add V-Cruise engine

engines/ags/shared/gfx/image.cpp, engines/mtropolis/debug.cpp, graphics/managed_surface.h
This allows to remove the palette argument and removes the need for getPalette.
=> GRAPHICS: Make rawBlitFrom take a ManagedSurface

engines/glk/scott/load_game.cpp
Line 255, `if (!(_G(_game)->_subType & (C64 | MYSTERIOUS)))`, is supposed to check whether the current game is a Commodore 64 version of one of the eleven Mysterious Adventures by Brian Howarth, and if so set the appropriate system messages. Currently it does the opposite.
~~A one-character change that may also fix~~ Fixes https://bugs.scummvm.org/ticket/14255.
EDIT:  Now it is properly fixed.
EDIT 2: The [lines 139-263](https://github.com/scummvm/scummvm/blob/6cf8b64c270895d1dce5ea07f693969c2188acae/engines/glk/scott/load_game.cpp#L139-L263) in `load_game.cpp` set the entries of the Common::StringArray `_sys` to the right string from `_systemMessages`, which contains strings read from the original game data.
All Scott Adams format games have roughly the same system messages, but to save …
=> GLK: SCOTT: Fix inverted conditional statement

engines/director/resource.cpp
Before returning a nullptr result (i.e. loading the EXE failed), we should first delete the existing exeStream
=> DIRECTOR: Fix a couple memory leaks in Window::loadEXE

engines/dreamweb/titles.cpp, engines/dreamweb/vgagrafx.cpp, engines/engine.cpp, engines/plumbers/3do.cpp, engines/plumbers/POTFILES, engines/plumbers/configure.engine, engines/plumbers/detection.cpp, engines/plumbers/metaengine.cpp, engines/plumbers/module.mk, engines/plumbers/plumbers.cpp, engines/plumbers/plumbers.h, engines/plumbers/windows.cpp, engines/util.h, graphics/mode.h, graphics/module.mk, graphics/scaler/downscaler.cpp, graphics/scaler/downscaler.h, graphics/scaler/downscalerARM.s
Dreamweb has undeclared dependency on highres. It's used only for titles. Downscale titles if necessary instead.
Plumbers uses highres only for the windows version. Again BMPs are simple to downscale and the windows version has no movies.
3DO version needs 16-bit but it's better to disable only 3do version if 16-bit is unavailable.
3DO and windows share almost no code and instead it's a mess of variables which are glorified platform markers. I've split windows and 3do versions of plumbers into separate classes
=> Fix dependencies on highres and 16-bit in plumbers and dreamweb

gui/widgets/editable.cpp, gui/widgets/editable.h, gui/widgets/edittext.cpp, gui/widgets/edittext.h
This adds the ability to select text in a EditTextWidget. 
The following list of behaviour is implemented:- 
- Double Click: Selects all the text
- SHIFT + L/R: Increments/Decrements selection.
- SHIFT + Left Click: Selects text between caret position and the mouse click.
- SHIFT + Home/End : Selects Text between the caretPosition and starting of the string/the end of the string.
- Dragging the mouse over the string will select that part of the string.
- Pressing backspace while a selection has been made will delete that selection.
- Pressing CTRL+C while a selection has been made will copy the selection to clipboard.
- Pressing CTRL+V while a selection has been made will replace the selected text with the text from clipboard.
Many thanks to @sev- for answering my questions and writing …
=> GUI: Make text selectable in input boxes

engines/saga2/magic.cpp
In function [skillProtoFromID, magic.cpp](https://github.com/scummvm/scummvm/blob/8fea0be1bdd2bb613e76e481e693fbb14131794c/engines/saga2/magic.cpp#L95) the logic to get skill is simple, If the id given is greater than maximum spells then it simply returns game object from address, whereas if not then it will return spell from the spell book! This is based upon the assumption that _Spell objects will have IDs > the number of spells_, however, it sometimes happens that spell object get Id between this safe range, thus the error of **Wrong spellID**.
The patch fixes this by fetching the game object from the address and checking if it is a spell, If it is, then it simply returns the address, else checks for range.
```
int16 manaColor = spellBook[sProto->getSpellID()].getManaType();
int16 …
```
=> SAGA2: Fix Wrong spellID crash when using spells from inventory!

engines/director/detection_tables.h
This adds a detetion entry for the hebrew game מיץ פטל which works on Director version 4
The game itself does not work yet (`Lingo::openXLib: Unimplemented xlib: 'Draw'!`)
=> DIRECTOR: Add detection entry for Mitz Petel

doc/docportal/advanced_topics/autostart.rst, doc/docportal/index.rst
=> DOCS: Document autostart feature

backends/fs/android/android-saf-fs.cpp, backends/fs/android/android-saf-fs.h, backends/platform/android/org/scummvm/scummvm/SAFFSTree.java
Instead of caching path string, cache nodes and their children. This allows a better tracking of what is in cache and what is not.
Use SoftReference to allow for simple cleanup and ensure we have unique SAFFSNode instances.
This PR is an alternative to #4761
=> ANDROID: Rewrite cache to make it more efficient

configure
This tiny fix allows to build SCUMMVM with dynamic modules, when `--enable-cygwin-build` is also activated.
=> CONFIGURE: fix build of dynamic modules under Cygwin

backends/graphics/opengl/opengl-graphics.cpp, backends/graphics/opengl/texture.cpp, backends/graphics/opengl/texture.h
Fixes two regressions from PR #4713 
First, cursor transparency was breaking when toggling fullscreen mode on Windows (alt+enter) and possibly other platforms because the cursor texture was still mapped to an ID from the destroyed GL context.
Second, cursor mask transparency wasn't being applied when using scalers that can scale cursors (Normal and AdvMame), which was causing a border to appear around them in some games due to it being filled with the key color, despite the key color not actually being keyed out.
=> GRAPHICS: Fix cursor mask regressions

engines/freescape/gfx_tinygl.cpp, engines/grim/gfx_tinygl.cpp, engines/hpl1/engine/impl/low_level_graphics_tgl.cpp, engines/myst3/gfx_tinygl.cpp, engines/tetraedge/te/te_renderer_tinygl.cpp, graphics/tinygl/api.cpp, graphics/tinygl/gl.h
This avoids needing to cast the parameters to doubles, only for the functions to cast them to floats.
=> TINYGL: Replace tglFrustum, tglOrtho and tglClearDepth with float versions

engines/cine/metaengine.cpp, engines/engine.cpp, engines/metaengine.cpp, engines/savestate.cpp, engines/savestate.h, engines/sci/metaengine.cpp
Due to very slow connection speeds, I've opted to close, rather than attempt to rebase, #4358, and reopen with this appropriately named PR, and the commits relevant to the issue.
This replaces the content of #4355 & #4358, which contained previously merged commits from #4350. 
For an overview of the proposed changes in 73f48d3c010fe3a3a1e56ce69e30fae6cc8f1151 & ae1c1dbde56c16307448da160de3ba745b8d9c42, please refer to the description in #4355.
For an overview of the proposed changes in 52ceabeca519dfd01e95fecfb95470136365085f, 4f304bdc745f28feef06d44799c26af455a8688c & 0c7ea96fb382aab808a5cdd5c7aea1cab071873e, please refer to the description in #4358.
For a preliminary discussion regarding the resolution of this issue, please refer to #4358.
In summary, the issue is that a saveType …
=> ENGINES: Prevent autosave overwriting regular save without warning

configure
The new ENet stuff checks for various system calls, but some systems may want some additional system headers for the checks to succeed.
The additions mostly come from OpenBSD 7.2 (https://man.openbsd.org) and Debian 11 manual pages, and they shouldn't hurt since `backends/networking/enet/source/unix.cpp` already includes those headers.
OK?
=> CONFIGURE: ENET: Add more system headers in checks

backends/graphics/surfacesdl/surfacesdl-graphics.cpp
PR #4754 fixed a crash in SDL1 when using negative shake offset. But reviewing the PR I think it did not correctly handle the dirty rect in the case of a negative offset. However the PR was merged before this could be confirmed and fixed.
Instead of shifting the destination to the left, if was moving the source to the right, which had the effect of shifting the dirty rect. So part of the surface that should have been copied to the screen was not, and instead it was copying part of the surface that did not need to be copied.
I am not completely confident with the change, and did not test it as no longer have a SDL 1.2 at hand to try it. So having another pair of eyes on this would be welcome.
=> SDL: Fix incorrect handling of dirty rect with negative shake offset in SDL1

Makefile, configure
The `-Wshadow` and `-Wmissing-field-initializers` GCC flags gave many false positives before GCC 5, and this creates a lot of irrelevant noise in the build logs. See the Ubuntu 20.04 g++ 4.8 CI for an example, or the Dreamcast or RISC OS buildbots. Even Linus complained about the old `-Wshadow` at the time.
The flags are now only enabled on Clang builds and GCC >= 5 builds.
=> BUILD: Disable -Wshadow and -Wmissing-field-initializers before GCC 5

configure
Looking at [buildd.debian.org](https://buildd.debian.org/status/logs.php?pkg=scummvm) or our buildbot logs, I see that `configure` prints `unknown` for some archs we do support (poor Dreamcast, it's been so long!) and I feel a bit sad for them.
I don't think this PR solves anything, though, especially for the old architectures (Alpha, HPPA…) where running ScummVM would just be a challenge in itself, but…
(as for the `tvos` line, it was just misindented)
=> CONFIGURE: Recognize more common architectures, and sort them

.github/workflows/ci.yml, devtools/create_project/msvc.cpp
This adds libvpx and giflib support to most Github Actions runners, so that the `sludge` (where libvpx support was recently added) and `hpl1` (giflib is required to build it) engines have better CI coverage.
This PR also completes libvpx support in `create_project` for MSVC.
=> CI: Enable libvpx and giflib in most runners

backends/platform/sdl/sdl-sys.h, base/version.cpp, configure, devtools/create_project/create_project.cpp
This tweaks the build system a bit, so that the About dialog will now show whether SDL1.2 or SDL2 (or later) is used.
The idea is to have a quick way of figuring out when an official port still uses SDL1.2, just after starting it. Knowing it from memory or from the build logs is not always convenient.
=> BASE: Show SDL1.2/SDL2 in the About dialog

backends/networking/curl/socket.cpp, backends/networking/curl/url.cpp
This is just meant to fix the following `ARRAYSIZE` macro redefinition warnings on Win32:
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\winnt.h(1375,1): warning C4005: 'ARRAYSIZE': macro redefinition (compiling source file ..\backends\networking\curl\socket.cpp) [D:\a\scummvm\scummvm\build-scummvm\scummvm.vcxproj]
D:\a\scummvm\scummvm\common\util.h(91,1): message : see previous definition of 'ARRAYSIZE' (compiling source file ..\backends\networking\curl\socket.cpp) [D:\a\scummvm\scummvm\build-scummvm\scummvm.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\winnt.h(1375,1): warning C4005: 'ARRAYSIZE': macro redefinition (compiling source file ..\backends\networking\curl\url.cpp) [D:\a\scummvm\scummvm\build-scummvm\scummvm.vcxproj] …
```
=> BACKENDS: CURL: Fix libcurl redefining ARRAYSIZE on Win32

configure, ports.mk, video/mkv/mkvparser.cpp, video/mkv_decoder.cpp
AppleTV and iOS need the libvpx.a file to be added to their build flags like other libraries.
MKV decoder needs proper support for Tremor. This is copied from Theora decoder.
libvpx can be built statically. In this case additional libraries may be needed (like pthread for multithreaded decoding).
Without this, it fails to build on platforms like Vita.
Finally, patch MKV parser to make it use our own objects instead of STL ones. This makes the code compile under MacOS i386 toolchain.
As the C++ headers are replaced by our own (which include C versions of them), `LLONG_MAX` needs to be redefined on some platforms (newlib based ones) and isnan can't be defined as a function as it may be a macro.
Without this PR, new toolchains which have libvpx can't be deployed.
=> VIDEO: Fix VPX build for various platforms

engines/ultima/nuvie/menus/game_menu_dialog.cpp
Fix a use-after-free bug. The chain of events causing it is as follows:
In-game the user changes the current view (e.g. by pressing TAB to go to inventory view). The user next presses ESC to open the GameMenuDialog and then clicks the "Load Game" button. A save slot is selected and then loaded.
The resulting call chain is:
```
GUI_Button::Activate_button()
GameMenuDialog::callback()
GameMenuDialog::close_dialog() <-- This marks GameMenuDialog
for deletion by the GUI
g_engine->loadGameDialog()
GUI::AddWidget() <-------------- This deletes GameMenuDialog
and its children, including
the "Load Game" button
```
Control then returns to GUI_Button::Activate_button() with "this" containing the address of the freed button.
An attempt to call Redraw() finally dereferences the invalid pointer.
This …
=> NUVIE: Fix Ultima 6 crash on loading save

engines/ultima/nuvie/core/obj.cpp, engines/ultima/nuvie/core/obj.h, engines/ultima/nuvie/core/obj_manager.cpp, engines/ultima/nuvie/usecode/usecode.cpp
Addresses the following problems:
1. UseCode::search_container() moves items to the map in the wrong order
2. When loading a chunk items are added to containers in the wrong order (e.g. Iolos starting bag and the chest in the Avatars room SW of the throne room)
This assumes the correct order is the one expected by the inventory GUI.
The items should be ordered as follows when starting a new game with these fixes:
Gargoyle corpse: weapons first, helmets/armor last
Iolos bag: knife first, grapes last
Avatar chest: torches first, chain coif last
Fixes [#13514](https://bugs.scummvm.org/ticket/13514)
=> NUVIE: Fix Ultima 6 item order

engines/ultima/nuvie/script/script_cutscene.cpp
Input polling function: Stay in the event loop instead of returning on events we do not want to handle. Always push a return value on the lua stack unless the event queue is actually empty.
=> NUVIE: Fix event handling in cut-scenes

devtools/create_ultima/files/ultima6/scripts/u6/actor.lua
Remove thrown weapons from the inventory first instead of the hands so they stay readied.
Requires regeneration of ultima.dat
Fixes [#12534](https://bugs.scummvm.org/ticket/12534)
=> NUVIE: Fix Ultima 6 throwing weapon auto-ready

common/formats/ini-file.cpp, common/formats/ini-file.h, engines/vcruise/runtime.cpp
V-Cruise uses an INI-like format for sfx files, where values under the "playlists" section are only simple strings and not formatted as key-value pairs.  The INI parser is capable of parsing them, but throws an extreme amount of warnings as there are usually hundreds of lines per animation file in this format.
This adds a function to disable the warning.
=> COMMON: Add ability to disable warning for valueless lines in INI files

graphics/managed_surface.cpp
Fixes signed/unsigned mismatch warning introduced by 3b27bce87b0272f1f58d7ce327acf6f547f16bb5
=> GRAPHICS: Fix VS signed/unsigned mismatch warning

graphics/svg.cpp, graphics/svg.h, gui/ThemeEngine.cpp, gui/widgets/grid.cpp
Maybe you are aware of other places in code like this?
(I found this one the hard way)
=> GRAPHICS: Speed up and refactor SVG handling

engines/ags/engine/main/config.cpp
ags64 (and also ags32) are the name of the engine executable on Linux. These names seems to be exclusively used for that OS. Fix a bug in Zniw Adventure (GOG, Linux) due to translation path being different between Linux and Windows.
=> AGS: auto-detect Linux games based on executable

gui/ThemeParser.cpp, gui/ThemeParser.h, gui/themes/common/highres_layout.stx
In portrait mode, the buttons are moved to the bottom of the screen instead of next to the game list, so that there's more room for the game description to be displayed.
=> GUI: Add a portrait version of the launcher

base/commandLine.cpp
Inspired by @raziel-'s comment at https://github.com/scummvm/scummvm/pull/4788#issuecomment-1461469285, this patch shows the currently running SDL2 version when using the `--version` command:
```
ScummVM 2.8.0git2438-g4b14cdd8fed (Mar  9 2023 08:31:57)
Using SDL backend with SDL 2.26.3
Features compiled in: Vorbis FLAC MP3 RGB zLib MPEG2 FluidSynth Theora VPX AAC A/52 FreeType2 FriBiDi JPEG PNG GIF taskbar TTS cloud (servers, local) ENet TinyGL OpenGL (with shaders)
```
Unfortunately, `SDL_GetVersion` is only available in SDL2+, so we can't exactly determine the version when using SDL1.
=> BASE: SDL: Show SDL version in --version output

gui/launcher.cpp, gui/widgets/grid.cpp, gui/widgets/grid.h
Unlike the list view, currently the invalid entries are not indicated in any way.
This PR:
* Changes the color of the invalid entries to KFontColorAlternate (like the listview)
* Adds a simple svg overlay (which is just a 60% dark square) to darken the icon so that it looks "inactive"
The .svg is placed in /icons/extra/ but maybe another location would be better suited (suggestions welcome)
=> GUI: In grid view show invalid entries in grey text and darken the thumbnail

backends/graphics/atari/atari-graphics.cpp, graphics/blit-atari.cpp
Atari buffers (maybe some other platforms, too?) benefit from being aligned on a 16-byte boundary. Not only the cache line is 16 bytes big but on the 68040 and 68060 CPUs there is a special instruction, move16, which is specifically optimised for moving data aligned on 16 bytes.
As this slightly pollutes `surface.h`, I'll appreciate your feedback (:+1: is also sufficient ;-)).
=> GRAPHICS: ATARI: Align surface on a 16-byte boundary

engines/tetraedge/te/te_input_mgr.cpp, engines/tetraedge/tetraedge.h
The only thing that quitGame() does is to send a new QUIT event, but  we already have one. So this is unnecessary. Furthermore this causes  an infinite loop in the case of a RTL event if the option to return to the launcher on quit is on. Indeed  DefaultEventManager::pushEvent() has a check in the case of a EVENT_QUIT to ignore it if it already received one, which avoids the infinite loop, unless the EVENT_QUIT are converted to RTL events.
This fixes bug [#14328](https://bugs.scummvm.org/ticket/14328) and [#14329](https://bugs.scummvm.org/ticket/14329).
I checked that the games still quits properly with all known way to quit a game:
- The in-game menu.
- Using CMD+Q (on macOS).
- Using the `Quit ScummVM` menu item in the ScummVM menu (on macOS).
- Using the close button in the Window …
=> TETRAEDGE: Do not call quitGame() when receiving a QUIT or RTL event

engines/scumm/he/script_v72he.cpp
This is probably the first of a few PRs that will add small mods for competitive online play for Backyard Baseball 2001. They'll all be behind `if (ConfMan.getBool("enable_competitive_mods")) {` and other checks so that they apply only when the user is playing online and has the competitive play mods option enabled.
This mod is somewhat of a quality-of-life change, as it eliminates a frustrating in-game experience. The most common case of this is: a weak pop-up is hit with a runner on first base. The game automatically "jogs" this baserunner towards second base at half speed. The user cannot return the runner to first base, because they're technically [forced](https://en.wikipedia.org/wiki/Force_play) and the game's logic doesn't allow this (dictated in room 3 script 2076). The ball is …
=> SCUMM HE: BYB '01 online mod: allow forced runner turnaround

backends/keymapper/keymap.cpp, backends/keymapper/keymapper-defaults.h
This allows backeds to override a keymap action mapping with lists of mapped hardware inputs instead of just one hardware input id
However, it will still be an overridding, so it will require all hardware input ids for a given keymap action to be added. In other words, if a backend uses addDefaultBinding() for a given action, it will not ADD to any existing mappings of the action, other than the ones that the backend itself has added (with addDefaultBinding())
Pros: Extended functionality, resolves an issue with Android controller devices (virtual mouse movement needing to be mapped to DPAD directional keys and (left) joystick movements).
Cons: Adds complexity to the implementation, and does not keep any mappings to an action that are set elsewhere -- it still overrides the mappings with …
=> KEYMAPPER: Allow multiple inputs bound to a keymap action as defaults

engines/bladerunner/waypoints.cpp
In my opinion, there is no need to write values into X/Y/Z pointers two times, it can be more efficient to write only once the value that we need.
=> BLADERUNNER: avoid writing two times XYZ waypoints

engines/testbed/config.cpp, engines/testbed/config.h, gui/dialog.cpp, gui/dialog.h, gui/object.cpp, gui/object.h, gui/widget.cpp, gui/widget.h, gui/widgets/editable.cpp, gui/widgets/editable.h, gui/widgets/edittext.cpp, gui/widgets/edittext.h, gui/widgets/list.cpp, gui/widgets/list.h
The `GUIObject::resize()` function has a flag indicating that the given values need to be scaled with the HiDPI scaling factor. The constructor however does not have this flag, and does not do the scaling. This causes:
- Code where a widget is created with some dimensions, and then resize() is called immediately afterward with the same dimensions to fix the size on HiDPI displays. This is a bit weird.
https://github.com/scummvm/scummvm/blob/3c7b7b4a724271a539dae794513d41a06fdb517b/engines/testbed/config.cpp#L178-L179
- Some dialogs to have an incorrect size has it is not scaled.
In this pull request a `scale` is added to constructors of the dialog, and many widgets. Using it means we no longer have to call resize() to get the correct size. Also this makes more explicit that by default the …
=> GUI: Allow scaling dialog and widget sizes in constructors

engines/director/cast.cpp, engines/director/castmember.cpp, engines/director/castmember.h, engines/director/cursor.cpp, engines/director/director.cpp, engines/director/director.h, engines/director/graphics.cpp, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-object.cpp, engines/director/lingo/lingo.cpp, engines/director/lingo/lingo.h, engines/director/lingo/tests/equality.lingo, engines/director/module.mk, engines/director/picture.cpp, engines/director/picture.h, engines/director/tests.cpp, engines/director/types.h
This does a refactor of how BitmapCastMember deals with it's picture, so that we can get/set the picture. In particular we now pass around copies, so that we can ensure that if we set a global to the picture of some cast member, the picture survives the cast member from which it came.
=> DIRECTOR: Add support for "set picture of cast" and "get picture of cast"

engines/ultima/nuvie/views/spell_view.h, engines/ultima/nuvie/views/spell_view_gump.h
Fix a NULL pointer dereference when opening the "new style" spellbook gump.
In an attempt to initialize a new SpellViewGump the code erroneously called the init() method of the parent class (SpellView). This left the "font" member variable set to NULL.
To reproduce the bug:
1. Enable "new style" in the video options (requires a restart)
2. Get a spellbook (e.g. from the Avatars room SW of the throne room)
3. Open the inventory by pressing TAB and click the spellbook to ready it
4. Press c to open the spellbook gump
Fixes [#12536](https://bugs.scummvm.org/ticket/12536)
=> NUVIE: Fix Ultima 6 crash on opening spellbook

engines/ultima/nuvie/files/nuvie_bmp_file.cpp
Set the pixel format of actor doll and various gump ManagedSurfaces to match the format loaded into their buffers.
This corrects colors in:
with style set to "new style" (in video options):
- Actor dolls (the small figure showing equipped items)
- The spellbook gump (opened when casting a spell)
- The sun / moon ribbon to the top right
with style set to "original" and "use new actor dolls" on:
- Actor dolls
Fixes [#13513](https://bugs.scummvm.org/ticket/13513)
=> NUVIE: Fix Ultima 6 actor doll and gump colors

engines/ultima/nuvie/core/events.cpp
Fix a NULL pointer dereference when looking at some objects which are either invisible or hidden in the darkness.
To reproduce the bug:
1. Go to the Avatars room SW of the throne room.
2. Stand outside the room with the door closed.
3. Use the "look" action on the wall sharing a tile with the bed.
=> NUVIE: Fix Ultima 6 crash on look action

base/commandLine.cpp
This means building and running scummvm in tree works out of the box.
Unfortnatelly registering them as defaults would not work as ConfMan::hasKey() returns false when only defined as a default, and in most places this is checked before using those paths. So if we wanted to use defaults we would need to replace all those checks with a check that the path is not empty.
There is a drawback to using the session domain though: it takes priority over all other domains. So a custom extrapath defined for a game will be ignored. I tried to mitigate the issue by only adding those path if they exist(so that it does not break shadow builds for example). I am not sure if this is a big issue or not. I suspect it could be an issue for example when using munt for some games and a custom extrapath for …
=> BASE: Add default extrapath and themepahth when running in tree

engines/director/lingo/lingo-code.cpp, engines/director/lingo/lingo-object.cpp, engines/director/lingo/lingo.h, engines/director/lingo/xlibs/dialogs.cpp, engines/director/lingo/xlibs/dialogs.h, engines/director/lingo/xlibs/fileio.cpp, engines/director/module.mk
Pull request is fragmented into three atomic commits for each of these, please review!
1. Set 'the result' for calls - Before this, the value of the result was not being set in XObject/Factory calls, this patch fixes it and thus the result will now be set after each caller! (eg. used for FileIO, for verifying status of operation after executing handler)
2. Normalise xlib calls for mac delimiters - Before patch, delimiters such as : and @: were not removed from openXLib calls, this patch fixes it and removes them.
3. Fully working Saves for total distortion! - Load/Save games are fully working, also the same goes for loading/saving video files under total distortion!
=> DIRECTOR: Set 'the result' for calls, Normalise xlib calls for mac delimiters (:, @:), Working Saves for TD!

engines/ultima/nuvie/core/events.cpp
Fix failed assertion when starting the "rest" action and holding down a number key at the prompt ("How many hours?"):
"core/events.cpp:3189: void Ultima::Nuvie::Events::doAction(): Assertion `input.str' failed."
Give priority to requests for text input in Events::handleEvent() to prevent unrelated events from interfering.
Event handlers can request text input by setting some state (input.get_text, mode, etc.). Events::handleEvent() will then check for input and provide it to a method ultimately determined by current mode. Unrelated events could interfere with this by changing state since they were handled before checking for input requests.
=> NUVIE: Fix Ultima 6 failed assert on resting

engines/ultima/nuvie/gui/widgets/msg_scroll.cpp
Fix failed assertion on left-clicking while a "new style" prompt is displayed:
"engines/ultima/shared/std/string.h:93:char& Ultima::Std::string::operator[](size_t):Assertion `idx < _size' failed."
To reproduce the bug:
1. Enable "new style" in video options
2. Go to the two pools near the castle entrance
3. Use the fountain on the top left part of a pool
4. Left-click anywhere while the prompt	is open
=> NUVIE: Fix Ultima 6 failed assert on click during prompt

engines/ultima/nuvie/keybinding/keys.cpp
Do not discard modifier keys (CTRL, ALT, etc.) when looking up keybinds.
=> NUVIE: Fix input handling of modifier keys

engines/ultima/nuvie/core/map.cpp, engines/ultima/nuvie/core/map.h, engines/ultima/nuvie/script/script.cpp
Make the line drawing algorithm used in projectile collision detection operate in screen space to match the original game.
Before this change the calculation was done in tile space, which caused incorrect results.
Note that the modified method Map::lineTest() is also used in other parts of the code unrelated to projectiles. Regressions are possible. If it breaks anything projectiles might need to be handled separately.
To reproduce the incorrect behavior :
1. Get a ranged weapon (e.g. Iolos crossbow)
2. Stand directly left of the SW pillar S of the throne room
3. Attack tiles/targets to the NE
In the original game the pillar will block the shots.
=> NUVIE: Fix Ultima 6 projectile collision

backends/graphics/opengl/opengl-graphics.cpp
Preserving the alpha channel for screenshots is not really needed and causes problems in
the AGS engine (and possibily other engines) in OpenGL mode.
Fixes TRAC #[13348](https://bugs.scummvm.org/ticket/13348)
NOTE: please test on big endian machines
=> GRAPHICS: Remove alpha channel for screenshots (OPENGL)

backends/networking/curl/connectionmanager.cpp, backends/networking/curl/networkreadstream.cpp, backends/networking/curl/socket.cpp, backends/platform/android/android.mk, configure
Bundle CA certificates and make use of it instead of not verifying peers.
Cleanup configure to not define macros pointing to `/usr/local` and remove the `ANDROID_PLAIN_PORT` define which is not used anymore.
=> ANDROID: Bundle CA certificates and cleanups

engines/dreamweb/titles.cpp
If not specified, format selection may fall back to `g_system->getSupportedFormats().front()`, which may provide a not appropriate format (e.g. `RGBA8888@4` will not display titles correcty).
=> DREAMWEB: specify CLUT8 format for titles modes

base/commandLine.cpp
When parsing the command line option "window-size" the DO_LONG_OPTION inserts "window-size" into the settings StringMap. This is soon later deleted, but instead of deleting "window-size" it deletes the non-existent setting "window_size". This is needed because width and height are stored in "last_window_width" and "last_window_height" respectively and "window-size" is not used anywhere afterwords.
=> ALL: Fixed typo when erasing window-size

graphics/wincursor.cpp
Currently the cursor loader flags pixels as inverted if the pixel's color index is non-zero.
Per the WDDM spec, a pixel with 1 in the AND field is inverted if the color is white.  No behavior is defined for pixels with non-white color, but in practice, the behavior Windows uses is that any other color becomes transparent.
This fixes the cursor loader to reflect that behavior.
Fixes https://bugs.scummvm.org/ticket/14386
=> GRAPHICS: Fix incorrect Win cursor mask behavior when a non-white color is masked

engines/wintermute/base/gfx/opengl/base_surface_opengl3d.cpp, engines/wintermute/base/gfx/osystem/base_surface_osystem.cpp, graphics/blit-alpha.cpp, graphics/blit.h, graphics/module.mk, graphics/surface.cpp, graphics/surface.h, graphics/transparent_surface.cpp, graphics/transparent_surface.h
The new version can be used from regular surfaces, and should work with any pixel format that has an alpha component.
=> GRAPHICS: Add generic versions of applyColorKey() and setAlpha()

engines/dialogs.cpp, graphics/VectorRenderer.h, graphics/VectorRendererSpec.cpp, graphics/VectorRendererSpec.h, gui/ThemeEngine.cpp, gui/ThemeEngine.h, gui/launcher.cpp, gui/onscreendialog.cpp, gui/predictivedialog.cpp, gui/recorderdialog.cpp, gui/saveload-dialog.cpp, gui/widget.cpp, gui/widget.h, gui/widgets/grid.cpp
By doing this, we can assume that colour keys and alpha channels are mutually exclusive, which allows for future optimisation.
=> GUI: Only use a transparent colour for BMP images

engines/engine.cpp, engines/engine.h
Ran into this while testing Reah.  Basically, `syncSoundSettings` is normally called by the UI any time you leave the menu, however it is not called when launching the game (including when loading a save), which means the engine has to call `syncSoundSettings` itself.
I think it would make sense that if the exiting the UI sets the sound mixer to the expected state by default, then it should be set correctly by default when the game launches too.
I think it is probably not safe to just call `syncSoundSettings` in `runGame` because engines may expect things to be set up a certain way before `syncSoundSettings` is called, however I believe it should be safe to just initialize the mixer.
From what I can tell, every existing engine except for Drascula calls `Engine::syncSoundSettings` in its …
=> ENGINES: Initialize mixer volume levels to levels from config

video/dxa_decoder.cpp
See scummvm/scummvm-tools#68 for more details regarding this change.
=> VIDEO: Use endian-safe loads in for type 12 DXA frames

common/compression/installshield_cab.cpp
This PR adds support for InstallShield cabinets with files split across
volumes. It should, in theory, also add support for format v5
cabinets with multiple volumes, but I don't have any on hand
to test with.
Code is based on unshield.
=> COMMON: Upgrade InstallShield archive code

engines/asylum/system/cursor.cpp, engines/asylum/system/graphics.cpp, engines/asylum/system/screen.cpp, engines/made/graphics.cpp, engines/made/scriptfuncs.cpp, graphics/cursorman.cpp, graphics/cursorman.h
This helps engines which pass `Surface` buffers to `CursorManager::replaceCursor()` and `CursorManager::pushCursor()` while the surface is not guaranteed to have width == pitch.
Internally the cursor is still represented as a linear surface for backward compatibility with the existing API.
I've attached a couple of commits where I have so far found cases which do not play nicely with 8bpp surfaces with pitch != width.
I've tested it quite thoroughly; I'm happy for second opinion.
=> GRAPHICS: Add support for cursor as Surface

backends/networking/enet/source/win32.h
```
packet.cpp:121:9: warning: declaration of 'byte' shadows a global declaration [-Wshadow]
121 |     int byte;
|         ^~~~
In file included from C:/msys64/mingw64/include/wtypes.h:8,
from C:/msys64/mingw64/include/winscard.h:10,
from C:/msys64/mingw64/include/windows.h:97,
from C:/msys64/mingw64/include/winsock2.h:23,
from C:/Projects/scummvm/backends/networking/enet/source/win32.h:18,
from C:/Projects/scummvm/backends/networking/enet/source/enet.h:16,
from C:/Projects/scummvm/backends/networking/enet/source/packet.cpp:7:
C:/msys64/mingw64/include/rpcndr.h:63:25: note: shadowed declaration is here
63 |   typedef unsigned char byte;
|                         ^~~~
```
Fix by defining WIN32_LEAN_AND_MEAN, which prevents this typedef.
=> BACKENDS: ENET: Fix GCC/MinGW warning

engines/sci/detection_tables.h, engines/sci/video/robot_decoder.cpp
See [bug #14388](https://bugs.scummvm.org/ticket/14388) for details: the PQ:SWAT demo (`pqswat-win-demo-en.zip`) requires version 4 robot decoding, which is not implemented yet.
Submitting this as a PR just in case, since I'm not really familiar with the way this engine is maintained :)
=> SCI32: Mark PQ:SWAT demo as unsupported

.github/workflows/ci.yml, audio/mods/impulsetracker.cpp, devtools/create_project/cmake.cpp, devtools/create_project/create_project.cpp, devtools/create_project/msvc.cpp, devtools/create_project/xcode.cpp
This continues the work from PR #4836 so that the libmikmod library (used by the Sludge engine) may also be used in `create_project` and in our CI builds.
Done as a best-effort; I'm not 100% sure all `create_project` changes are correct.
Tested with an Xcode and an MSVC build, and with the Github Actions I'm also updating in the same PR.
=> CREATE_PROJECT/CI: Add libmikmod support

base/version.cpp, base/version.h, engines/scumm/he/net/net_lobby.cpp, engines/scumm/script.cpp
This PR contains three changes, hope it's OK that I've combined them in this PR:
* Adds whether the user has competitive play mods enabled (`ConfMan.getBool("enable_competitive_mods")`) to the payload sent to the lobby server with the login request. We can log this on the server end, and maybe at some point in the future will want to use it on the server end to make it so that players with these mods enabled can only play against others who have them enabled, and players without them can only play opponents without them. Otherwise, we can end up with confusing or unfair gameplay.
* Sends `gScummVMFullVersion`, which includes the build timestamp, as `version` in the login request. We've made some bugfixes and changes to online play more frequently than ScummVM releases new versions, and …
=> SCUMM HE: Additional data in login payload, hit quality mod

gui/launcher.cpp, gui/widgets/grid.cpp, gui/widgets/grid.h, gui/widgets/groupedlist.cpp, gui/widgets/groupedlist.h
GroupedListWidget and GridWidget can save what groups they have collapsed to the config file and reload them. "launcher.cpp" uses those functions to persist those collapsed groups through
- changing how the games are grouped by
- going from list to grid mode and vice versa
- quitting scummvm and starting it again
=> GUI: Collapsed game groups are persisted

gui/widgets/editable.cpp, gui/widgets/list.cpp
This disables text selection in the list widget, fixing issue [#14400](https://bugs.scummvm.org/ticket/14400).
=> GUI: Disable text selection in list widget

graphics/VectorRendererSpec.cpp, graphics/VectorRendererSpec.h
Introduce `shadowIntensity` to tab drawing functions.
- New implementation can behave slightly differently with old one under fractional scaling factors. E.g. when `scale=1.2 offset=2`, the offset is rounded to `2.4->2` while scaling factor be `1.2`, only `[offset/1.2]+1=2` rectangles will be drawn
- `drawSquareShadow()` and `drawSquareShadowClip()` are already self-contained under scaling and don't need to be changed.
=> GUI: Fix hard shadow of tabs under HiDPI

engines/tetraedge/detection.cpp, engines/tetraedge/game/application.cpp, engines/tetraedge/te/te_font3.cpp
This adds support for hebrew fan translation of Syberia 1 and 2.
Specifically, if the game is detected as hebrew, the text is converted to the correct BiDi ordering.
Thank you for your amazing work, which have made this possible.
=> TETRAEDGE: Support Hebrew fan translation

engines/tetraedge/te/te_font3.cpp, engines/tetraedge/te/te_font3.h
This fixes an issue in the text drawing where the glyphs to use are implicitly casted to uint32 and does not get the current glyph range in the font.
I understand that implicit conversion from 8-bit encoding as-is is similiar to Latin-1 encoding, please correct me if it's not the case... I didn't notice problem with these languages but I'm not a native speaker.
Specifically, it fixes russian translation and allow better integration in the hebrew fan translation...
before:
after:
(Also not a native speaker, but it seems to match the voice over)
Thank you
=> TETRAEDGE: Encode text before draw

engines/drascula/drascula.cpp, engines/drascula/drascula.h
Tracks the status of LMB and avoids calling the delay while the button is pressed. This prevents the generalized slowdown and icons "bouncing" in the inventory.
Fixes TRAC #3799
=> DRASCULA: Track left mousebutton press and apply delay as needed

engines/scumm/script.cpp
This PR implements a mod for competitive online Backyard Baseball 2001 play: not giving players a hitting powerup after double plays. Hitting powerups can decide games, especially when they're low scoring. Since they are given for double plays, the fielding team is incentivized to allow slow runners on-base in hopes of getting a double play, and the offensive team is incentivized to intentionally get out with these slow hitters to avoid these double-play-prone situations.
By disabling powerups for double plays, this kind of intentionally "bad" gameplay won't be incentivized any longer.
=> SCUMM HE: BB01 competitive online play: no double play powerups

engines/ags/engine/media/video/video.cpp, graphics/managed_surface.cpp, graphics/managed_surface.h
Playing CLUT8  videos (such as FLIC videos) was not working properly:
- If the game itself is CLUT8, it was using the previously set palette from the game and ignore the one from the video decoder, resulting in wrong colors.
- If the game uses 16bit or 32bit colors, it was crashing as the decoder palette was not passed to the blitting code that was expected it.
There were two separate crash:
- If the video is stretched in AGS, it was asserting in `Graphics::transBlitPixel` due to the source palette being a nullptr pointer.
- If the video is not stretched in AGS, it was trying to access 0x0 memory. There was an incorrect assert that was not triggered and should have caught this before getting to the invalid memory access.
The `ManagedSurface` blitting code only allowed blitting from CLUT8 …
=> AGS: Fix playing CLUT8 videos

backends/platform/ios7/ios7_app_delegate.mm, backends/platform/ios7/ios7_keyboard.mm, backends/platform/ios7/ios7_osys_main.h, backends/platform/ios7/ios7_scummvm_view_controller.h, backends/platform/ios7/ios7_scummvm_view_controller.mm, backends/platform/ios7/ios7_video.h, backends/platform/ios7/ios7_video.mm
This should fix incorrect orientation being detected on some devices, which caused the virtual keyboard to appear in landscape mode instead of portrait mode.
This includes three main changes that are tied to each others:
- Use the interface orientation and not the device orientation. This may be different for example when locking the orientation. 
-  Changes the way orientation changes are detected using the documented method. However this means dropping support for iOS 7 as this method is only available since iOS 8, and alternative methods available in iOS 7 have been deprecated in iOS 13. See https://developer.apple.com/documentation/uikit/uiviewcontroller?language=objc
- Properly detect the interface orientation instead of inferring it from the view bounds, which was incorrect on some …
=> Change orientation detection mechanism on iOS

engines/pink/objects/actors/lead_actor.cpp, engines/pink/screen.cpp, engines/pink/screen.h
Addresses bug #13860 "PINK: Animations will freeze after exiting PDA"
Basically it prevents pausing again (increasing pauselevel) if the macmenu (popup menu on top of screen, which can be used to open PDA) is active, since that one already pauses the engine.
Tested with Passport to Peril US English version. I am unsure if this would resolve the similar issue mentioned for Hocus Pocus in the same ticket (maybe a different but similar fix is required for that one).
=> PINK: PDA open from menu does not change pause level

engines/pink/objects/actions/action_text.cpp
Should address bugs #13865 and #13866 PINK: German Umlauts not displayed
Also added text encoding support for the other language codes that are in the detection_tables.h for the PINK engine. Namely, IT_ITA, NL_NLD, and EN_GRB. The NL_NLD one I am uncertain about, but according to wikipedia, Windows-1252 should do for Dutch as well. I cannot test for it though.
=> PINK: Fix localized text encoding

engines/pink/constants.h, engines/pink/cursor_mgr.cpp, engines/pink/gui.cpp, engines/pink/objects/module.cpp, engines/pink/objects/pages/game_page.cpp, engines/pink/pink.cpp
This addresses the cause for #13869 PINK: Can't pickup the poker in sir Manley's house
However:
1. this will not retroactively fix the broken saved games that carry stale global game variables from other playthroughs
2. It will not set the "appropriate" global game variables if the player uses the debug console to jump to different modules and pages back and forth.
=> PINK: Clear global game variables on New Game

devtools/create_project/create_project.cpp
Turns out MT32Emu is compiled in even if the feature is disabled, and the linker is unable to remove `SERVICE_VTABLE` for some reason which results in most of the code being included as well.
This removes the source files from the VS solution if the feature is disabled.
=> CREATE_PROJECT: Exclude MT32Emu source files if the feature is disabled.

video/dxa_decoder.cpp
Fixes VS warning that can potentially cause wrong behavior in DXA decoder:
`dxa_decoder.cpp(72,18): warning C4245: 'argument': conversion from 'int' to 'uint32', signed/unsigned mismatch`
`skip` accepts a uint32 parameter and then passes it to `seek` which accepts an int64.  This is problematic because converting -4 to a uint32 may cause it to become 4294967292, causing the seek to fail if the underlying stream doesn't demote it back to 32-bit.
=> VIDEO: Fix signed/unsigned mismatch potentially breaking DXA seek.

engines/sci/console.cpp, engines/sci/engine/object.h, engines/sci/engine/script.cpp, engines/sci/engine/script.h, engines/sci/engine/vm_types.cpp, engines/sci/engine/vm_types.h, engines/sci/resource/resource.cpp, engines/sci/resource/resource.h, engines/sci/sci.h, engines/sci/util.cpp, engines/sci/version.h, engines/scumm/scumm.h, engines/scumm/usage_bits.cpp
When profiling a few games, we have spotted some functions which repeatedly made it to the top ten most called / cpu eating functions (on a 32 MHz hardware, so that explains why those numbers are so high...)
From the SCI camp we tested Gabriel Knight, Larry 2, Larry 7 and Sierra's Christmas Card 1988. The most CPU intensive functions (shown on Larry 2 intro but it is similar for the others):
8.30% of all spent CPU cycles: `Sci::reg_t::getOffset() const`
6.08%  of all spent CPU cycles: `Sci::getSciVersion()`
1.80%  of all spent CPU cycles: `Sci::reg_t::setOffset(unsigned int)`
1.25%  of all spent CPU cycles: `Sci::Script::offsetIsObject(unsigned int) const`
After applying this PR, the total `run_vm()` cost went from 0.00940s / call, down to 0.00672s / call, which is 28.5% improvement! …
=> Inline some of the most called functions in SCI and SCUMM

common/array.h, common/list.h, common/list_intern.h, common/rect.h, common/str-base.h, common/str.h, common/ustr.h, math/matrix.h, math/matrix3.cpp, math/matrix3.h, math/rotation3d.h, math/transform.h
While working on some code that had a large amount of global variables, I wanted to get rid of the global constructor warnings that ensued once I started to use our collections/string classes in these global variables. While the globals will eventually go away in my codebase, there are also constants that would benefit from not having to run constructors.
After having a bit of a look, it seems that as long as there is a constexpr constructor available (which requires that all members are also constexpr-constructible), we can avoid global constructors.
So this is a quick attempt at adding constexpr constructors to the above mentioned classes, as well as the beginnings of supporting this in the Matrix classes as well, however the Matrix attempt is currently blocked by the logic for …
=> COMMON/MATH: Add some constexpr constructors to Array/List/String/Rect and the Matrix base-classes.

gui/launcher.cpp
Fix issue mentioned in https://bugs.scummvm.org/ticket/13719. Display game description as title and move game title to tooltip under grid layout. This makes list and grid layout consistent.
=> GUI: Fix inconsistent game title display for list and grid layout

engines/ultima/nuvie/files/u6_lib_n.cpp
U6Lib_n::close(): Do not call close() on NuvieIO buffers passed to us
via U6Lib_n::open(). Let the caller handle this instead.
Prevents a crash caused by the following events:
- The game detects the files of the FM-Towns version
("townsu6" in the game directory) and eventually attempts to load
"sounds1.dat" in TownsSfxManager::loadSound1Dat()
- Here, it creates local objects U6Lib_n "lib" and NuvieIOBuffer "iobuf"
- File data is loaded into "iobuf", which is then passed to "lib" via
pointer. This pointer is stored by "lib"
- When TownsSfxManager::loadSound1Dat() returns, "iobuf" goes out of
scope and is destroyed before "lib"
- The destructor of "lib" tries to call close() via the stale pointer,
thus causing the crash
Fixes [#14429](https://bugs.scummvm.org/ticket/14429)
=> NUVIE: Fix Ultima 6 crash on FM-Towns sound load

.github/workflows/ci.yml, devtools/create_engine/create_engine.cpp, devtools/create_project/create_project.cpp, devtools/create_project/create_project.h, devtools/create_project/msbuild.cpp, devtools/create_project/msbuild.h, devtools/create_project/msvc.cpp, devtools/create_project/msvc.h, dists/msvc/create_msvc.bat, ports.mk, vcpkg.json
This PR adds a `--vcpkg` flag to create_project to get library dependencies directly from vcpkg instead of SCUMMVM_LIBS. This allows the CI to keep up with the latest vcpkg updates without requiring hacks and workarounds as libraries change (eg. #4648), and allows developers to use the latest library versions instead of pre-compiled if they prefer.
(based on the work of #2568)
=> CREATE_PROJECT/CI: Support vcpkg integration

engines/agos/detection.cpp, engines/agos/detection_fallback.h
This adds fallback detection for several AGOS titles.
Mainly to enable editing the games (such as adding subtitles)
and test them without the need to add specific detection entries and re-compile[1]
[1] https://forums.scummvm.org/viewtopic.php?p=97915#p97915
=> AGOS: Add fallback detection for some titles

engines/ags/module.mk, engines/ags/plugins/ags_trans/ags_trans.cpp, engines/ags/plugins/ags_trans/ags_trans.h, engines/ags/plugins/plugin_base.cpp
This PR simply adds stubs for the AGSTrans plugin (which I think was used only in the game
Death Wore Endless Feathers) to draw semitransparent windows.
With the stubs in place the game is playable and completable.
=> AGS: Add stubs for AGSTrans plugin

gui/Tooltip.cpp, gui/Tooltip.h, gui/gui-manager.cpp, gui/gui-manager.h
Follow-up of #4953 -- this makes tool tips noticeably faster as even a three letter tooltip would require a complete clearOverlay() & grabOverlay() & build the dialog stack.
This way it redraws only its parent dialog (dialog is key here; not parent widget).
One day I or perhaps someone else find the courage to implement a proper window manager into ScummVM, that way `kRedrawCloseDialog` would restore the underlying widget(s) (it is the "s" which makes this quite a complex change).
=> GUI: Don't enforce full redraw upon closing tool tip

engines/ags/engine/ac/draw.cpp
Fixes int-bool comparison that is breaking the Windows build.
=> AGS: Fix Windows build failing to compile

engines/scumm/he/script_v72he.cpp
The competitive play mod implemented in [this PR](https://github.com/scummvm/scummvm/pull/4829) introduced a bug in which, after turning around on a pop-up, the runner is "stuck" - they can't be turned _back_ around, and won't move until another runner reaches the base that they're standing on. [Here's](https://medal.tv/games/requested/clips/16SSgpxQP-1n6O/M3DmWPBn2dV9?invite=cr-MSxnVFAsMjUwNjI5Nzcs) an example of this bug in action.
This PR fixes this issue. [Here's a clip](https://streamable.com/zigteu) of the same situation as the above clip, with this fix.
=> SCUMM HE: Bugfix: Allow turned-around runners on pop-ups to turn back around

backends/platform/ios7/ios7_app_delegate.mm, backends/platform/ios7/ios7_osys_events.cpp, backends/platform/ios7/ios7_osys_main.cpp, backends/platform/ios7/ios7_osys_main.h, devtools/create_project/xcode.cpp
Implement use of Dispatch Sources to drive timeHandler. The timerHandler will run on a background thread and not block the UI.
Include two other minor fixes as well. The first disabling bitcode by default for iOS and tvOS, the using the correct delegate methods depending on iOS version.
=> IOS7: Implement use of Dispatch Sources to drive timeHandler

engines/watchmaker/classes/do_keyboard.cpp, engines/watchmaker/ll/ll_diary.cpp
Per commit description, this happens because C-style local function prototypes wind up in the global scope, causing them to be linked against a symbol that doesn't exist, because the actual implementation is in the `Watchmaker` namespace.
=> WATCHMAKER: Fix MSVC linker failure

engines/scumm/detection_internal.h
Chinese Full Throttle puts the font in video directory. ScummVM accepts it there in the game but not in the detection. So user needs to select language manually in order for it to work. Check the second location as well
=> SCUMM: Fix detection of Chinese Full Throttle

engines/ultima/detection.cpp
Noticed this while updating some retroarch thumbnails when the name detected never made the correct named thumbnail appear, then noticed the extra space.
=> Ultima: Remove extra space in quest of the avatar name

backends/platform/ios7/ios7_video.mm, dists/ios7/Info.plist, dists/ios7/Info.plist.in
This PR contains 2 commits.
The first one fixes inaccurate touches which was discovered on devices where the frame had to be resized to comply with the safeArea of the screen.
The second commit adds the [ITSAppUsesNonExemptEncryption](https://developer.apple.com/documentation/bundleresources/information_property_list/itsappusesnonexemptencryption?language=objc) to the Info.plist so we don't have to answer about export compliance every time a new build is submitted.
=> Update frame on safe insets changes and update Info.plist with export compliance

engines/asylum/system/text.cpp
String goes out of scope but its c_str is still used. Keep a reference while we still need it.
=> ASYLUM: Fix use-after-free

engines/twine/text.cpp, engines/twine/text.h
Hebrew translation use ISO-8859-8 in visual ordering. This is nasty but we can't change it. Instead do the best with what we have. One of problems is that characters fade in in the order that is reverse to reading order. This patch improves this and sets a groundwork for other RTL languages, hopefully in logical ordering.
=> TWINE: Fade-in characters starting from the right when playing in Hebrew

engines/titanic/pet_control/pet_glyphs.cpp, engines/titanic/true_talk/tt_concept.cpp, engines/titanic/true_talk/tt_concept.h, engines/titanic/true_talk/tt_concept_node.cpp, engines/titanic/true_talk/tt_concept_node.h, engines/titanic/true_talk/tt_parser.cpp, engines/titanic/true_talk/tt_parser.h, engines/titanic/true_talk/tt_sentence.cpp
This silences some `identifier 'concept' is a keyword in C++20 [-Wc++20-compat]` warnings when building the Titanic engine with G++ 13.
Small notes:
* The renaming was done with Xcode contextual rename function to be sure not to make any mistake.
* For `addConcept()` and `removeConcept()` I'm just using `*c` as the parameter, since the function itself reads a bit ambiguous otherwise, to me.
* The `pet_glyphs.cpp` change is for an unused variable.
=> TITANIC: Fix -Wc++20-compat warning for the C++20 'concept' keyword

graphics/macgui/macmenu.cpp
This was introduced way back in 99f458dafa10e96c671159b74f9cefa9b795ee34, at which time it was used. It looks like over the years the code has mutated a little bit, and in its current form this variable was added to but never actually read. I only realized when clang flagged it as a warning.
=> GRAPHICS: MACGUI: remove unused variable

engines/xeen/worldofxeen/clouds_cutscenes.cpp
The Mignt and Magic 4 game crashes in ending cutscene.
Looks like a Graphics::ManagedSurface-s are not initialised properly.
I guessed a way how it should be created.
Now I can watch a whole ending.
Monster animations int this cutscene is still missing a death frames.
See also https://bugs.scummvm.org/ticket/14431
=> XEEN: Fix crash in MM4 ending cutscene (branch 2-7)

engines/director/cast.cpp, engines/director/director.h, engines/director/graphics.cpp, engines/director/lingo/lingo-builtins.cpp, engines/director/score.cpp, engines/director/score.h
If the destination movie uses a palette cast member in the same location as the source, but with different data; Director will assume that the old palette is correct right up until it has to switch to something else via the score.
Additionally, ensure that all palettes are loaded into the index when the Cast is loaded, not just single ones that haven't been loaded before.
Fixes movie transitions and palette rendering in Phibos: Following the Comet.
=> DIRECTOR: Move _lastPalette to DirectorEngine

devtools/create_project/create_project.cpp, devtools/create_project/create_project.h, devtools/create_project/msbuild.cpp, devtools/create_project/msvc.cpp
There are various reasons that it may be undesirable to use an environment variable as part of configuring a build, such as the fact that it requires privilege elevation to set, which can make it more complicated to set up in a new build environment.
This adds a `--libs-path` parameter to create_project that lets you specify the path instead of using the environment variable.
=> CREATE_PROJECT: Add --libs-path command line parameter that can be used instead of the SCUMMVM_LIBS environment var

audio/mixer.cpp, audio/mixer.h, audio/mixer_intern.h, audio/rate.cpp, audio/rate.h, engines/sci/sound/audio32.cpp, engines/sword1/music.cpp
One of the Nancy Drew games has a puzzle that changes sounds' sample
rates to arbitrary values while they're playing. The initial plan for supporting
this feature was to create a custom AudioStream subclass; however, all
my attempts at doing so resulted in crackling and overly complicated code.
This PR is based around a rewrite of the RateConverter class merging
the previously separate CopyRateConverter, SimpleRateConverter,
and LinearRateConverter subclasses into a single class that supports
setting the input and output rates after creation. The optimized
code paths of those classes have been moved to separate functions,
with the correct one being picked on the fly.
The Mixer class has been upgraded to make use of the new feature,
so all an engine needs to do to change the playback speed …
=> AUDIO: Add support for manually setting sounds' sample rate

backends/platform/sdl/amigaos/amigaos.cpp
One user caught a GL crash/black screen on starting, while running ScummVM under emulation without any access to OpenGL/MiniGL/OGLES2.
No .ini file was created either.
This happened because gfx_mode was forced to "opengl" by default.
Setting gfx_mode to "surfacesdl" fixed the crash, the black screen and creating a usable .ini file.
...this only touches the AmigaOS target
=> AMIGAOS: amigaos.cpp - Set default gfx_mode to "surfacesdl"

engines/mohawk/riven.cpp
An issue exists where an autosave is performed when exiting the game during a cutscene, even though normal saving is disabled at this time.
When exiting the game during a cutscene, the game skips ahead to the first interactive frame outside the cutscene, then completes the exit.
Currently, the autosave is called after this change to the game state, creating the opportunity to complete an unexpected save that skips the unseen portion of the cutscene.
Fixed by repositioning the saveAutosaveIfEnabled() call to a position before the game state is changed, ensuring the autosave is always attempted based on the game state, and save condition, existing at the time the exit call is initiated.
In this example, the autosave fails to complete, as expected.
Fixes bug …
=> MOHAWK: RIVEN: Fix autosave on exit during cutscene

image/codecs/msrle.cpp
Fixes [14356](https://bugs.scummvm.org/ticket/14356).
It's possible that there's more bugs like this but I can't test it as this was the first occasion where I saw something corrupted.
For instance `MSRLE4Decoder::decode4` uses a slightly inefficient but safe `getBasePtr(x, y)` (which implicitly uses surface pitch) but I think this line:
`byte *output_end = (byte *)_surface->getBasePtr(_surface->w, y);`
is wrong -- technically speaking, nothing will be written past the allocated memory but the algorithm is writing past `width` pixels in the unused surface area.
=> IMAGE: Fix MSRLEDecoder if pitch > width

backends/platform/sdl/sdl.cpp, backends/platform/sdl/sdl.h, backends/platform/sdl/win32/win32.cpp, backends/platform/sdl/win32/win32.h, common/system.h, engines/testbed/events.cpp, engines/testbed/events.h, gui/EventRecorder.cpp, gui/EventRecorder.h
Definitely not sure the changes for the event recorder are in good places, open to suggestions.
This can be implemented on macOS as well with doubleClickInterval, see https://developer.apple.com/documentation/appkit/nsevent/1528384-doubleclickinterval
=> BACKENDS: Add double-click time feature to support OS-configurable double-click intervals, implement it for Windows.

backends/keymapper/remap-widget.cpp, gui/ThemeEval.cpp, gui/ThemeLayout.h, gui/themes/common/highres_layout.stx, gui/themes/common/lowres_layout.stx, gui/themes/scummclassic/classic_layout.stx, gui/themes/scummclassic/classic_layout_lowres.stx, gui/widget.cpp, gui/widgets/scrollcontainer.cpp, gui/widgets/scrollcontainer.h
This currently works for `ScrollContainerWidget`s created using XML layouts, but not ones created using `TabWidget::addTab()` or `OptionsContainerWidget`.
Before:
After:
=> GUI: Account for the scroll bar size in ScrollContainerWidget objects

engines/ultima/nuvie/actors/actor.cpp, engines/ultima/nuvie/actors/u6_actor.cpp
- Do not allow actors marked as passable to pass others who are not
- Allow others to pass actors marked as passable even if they share
the same movetype (e.g. a mouse should not block the Avatar despite
both having movetype MOVETYPE_U6_LAND)
- Allow Sherry the mouse to move onto tiles occupied by party members
Fixes [#14396](https://bugs.scummvm.org/ticket/14396)
=> NUVIE: Fix passable actor movement

engines/ultima/nuvie/usecode/u6_usecode.cpp
Make sextants usable in the gargoyle underworld and adjust coordinate calculation accordingly.
Fixes [#14408](https://bugs.scummvm.org/ticket/14408)
=> NUVIE: ULTIMA6: Fix sextant usage in gargoyle underworld

audio/decoders/qdm2.cpp, engines/director/resource.cpp, engines/freescape/loaders/8bitBinaryLoader.cpp, engines/groovie/video/roq.cpp, engines/saga2/interp.cpp
Some `-Wformat` warnings show up in the build logs of some of our 32-bits ports (such as Android 32 bit, Dreamcast, Debian i686…), when calling a printf-like function with something like `%ld` and an argument that's not guaranteed to be the same size as a `long` by default.
This is a proposal for fixing this.
The general idea is just to use an explicit cast to `long`, since it looks like this is what is done in general in the codebase (?), and AFAICS the impacted engines are for older games with no real-world possibility of 64-bit file offsets, especially for some simple debug output. Casting to `long long` is another possibility (which is potentially even better), but I just tried to follow the existing "style" of each component.
=> Fix various -Wformat warnings on 32-bit archs

engines/ags/engine/ac/draw.cpp, engines/ags/engine/ac/dynamic_sprite.cpp, engines/ags/engine/game/game_init.cpp, engines/ags/engine/gfx/gfx_driver_base.cpp, engines/ags/engine/gfx/gfx_driver_base.h, engines/ags/engine/media/audio/audio.cpp, engines/ags/engine/script/cc_instance.cpp, engines/ags/engine/script/cc_instance.h, engines/ags/engine/script/script_runtime.cpp, engines/ags/globals.h, engines/ags/shared/core/def_version.h, engines/ags/shared/font/fonts.cpp, engines/ags/shared/util/string.cpp
This PR adds the commits from upstream up to version 3.6.0.48, which is the first "patch" release
of the 3.6.0 branch.
As the branch is now considered stable, the changes are just minor bugfixes.
SKIPPED COMMITS:
[Engine: fixed <3.6.0 Animate functions default volume parameter](https://github.com/adventuregamestudio/ags/commit/e8c36158dadcaf48eddafcf853616f2d042b30d2)
Already merged
[Engine: fixed BytesPerSample() incorrectly returning bits per sample](https://github.com/adventuregamestudio/ags/commit/035c50bbd2e6d7701e3dddff92b9b5d7f922f556)
Not present
=> AGS: Commits from upstream up to version 3.6.0.48

common/str-base.cpp
Minor optimization.  Exits "trim" earlier if the string is already trimmed.
=> COMMON: Avoid makeUnique on string if trim wouldn't modify it.

engines/tetraedge/game/inventory_objects_xml_parser.cpp, engines/tetraedge/game/inventory_objects_xml_parser.h
There exist a Russian variant of Syberia 2 for mac. It's created by injecting iOS translation into official mac Syberia 2. Unfortunately inventory XML contains a garbage value entry. Ignore it but issue warning.
=> TETRAEDGE: Skip garbage value entry in inventory data

engines/ags/lib/std/functional.h
On Apple Silicon, clang seems to not compile exactly the same as gcc on Windows or Linux. This leads to a problem with AGS's std::function struct.
Before, when being cast to a boolean, it would return true if _fn was nullptr for some reason, so I added a boolean cast function to std::functional so that casting it to a boolean would be the same as seeing if _fn was not nullptr.
=> AGS: Fixed std::function bool cast on clang

engines/director/util.cpp
Fixes the Windows version of Mylk (D4), which tries to return to the main screen by opening mylk.exe via a call to open the movie "MYLK". This can be tested by opening the pane next to the lake, entering that screen, then clicking back. Without this fix, the game will stay stuck on that screen with the warning "Movie MYLK does not exist".
@moralrecordings Is the .exe extension also possibly valid for D5, or should I remove that addition?
=> DIRECTOR: .exe is a valid movie ext

engines/ags/lib/allegro/surface.h, graphics/managed_surface.h, graphics/surface.h
Chronicle of Innsmouth - Mountains of Madness allocates a very big (about 9000x300) surface used for a scrolling scene.
This causes pitch to overflow in Surface::create causing a segfault as reported in [14456](https://bugs.scummvm.org/ticket/14456)
Note: this does not make the game playable (yet), as it uses a still unsupported plugin to play videos and do other graphics trickery.
=> GRAPHICS: Change pitch from int16 to int32

engines/tetraedge/te/te_image.cpp
This appears to fix the [following kind of output](https://bugs.scummvm.org/attachment/ticket/14452/syberia2-macppc.png) for the menus of Syberia on big-endian hosts.
Tested with the Macintosh release from GOG, on a PowerPC G4. Mostly tested with Syberia 2, since Syberia 1 has a very low framerate on this device, for some other reason.
Submitted as a PR, because I'm not very familiar with the game or with the proper way of dealing with `Graphics::PixelFormat`. I just "stole" this from what the Grim engine does in a similar case.
(Please don't close the Trac issue above, as the Theora video slowness issue is still unresolved at the moment.)
=> TETRAEDGE: Fix TeImage output on big-endian hosts

engines/bladerunner/subtitles.cpp
This adds support for hebrew subtitles patch of Blade Runner (or future RTL languages),
by making Hebrew text displayed correctly by applying BiDi algorithm on the unicode string.
Thanks @phcoder and @antoniou79 for their amazing work and support.
=> BLADERUNNER: add BiDi support for subtitles

common/rect.h
This adds some new constructors to Rect for constructing a rect from a top-left coordinate and either a bottom-right coordinate or a width and height.
Currently, this requires constructing a rect as:
`Rect(coord.x, coord.y, coord.x + size.x, coord.y + size.y)`
Most of the subexpressions in that are duplicated, which creates opportunities for mistakes, such as when constructing multiple rects.
With this change, you construct as:
`Rect(coord, coord + size)` or `Rect(coord, size.x, size.y)`
This doesn't add the ability to do `Rect(coord, size)` since it would have the same signature.  I opted to use top-left and bottom-right coordinates given the two options, since "`Point`" more intuitively makes sense as a coordinate than a size.
=> COMMON: Add new Rect constructors to make construction from coordinate+size easier

audio/decoders/wave.cpp
WAV files could contain a JUNK chunk for padding, that should be skipped when reading the header
instead of failing to find to 'fmt' chunk.
This is common in recent AGS games.
Reference here https://www.daubnet.com/en/file-format-riff
A similar issue https://github.com/tensorflow/tensorflow/issues/26247
=> AUDIO: Skip JUNK padding in WAV files

engines/saga/actor_walk.cpp
On switching scenes:
Reset _actor->_lastZone in Actor::updateActorsScene().
Actors can store a pointer to a HitZone in _lastZone (see Actor::handleActions()).
The HitZone pointed to is held by ObjectMap vm->_scene->_objectMap in array _hitZoneList.
When changing scenes the array elements are cleared via ObjectMap::clear() and _lastZone can become stale since only some code paths reset it (e.g. Actor::takeExit()).
The stale pointer is then passed to Actor::stepZoneAction() from Actor::handleActions() and dereferenced.
Fixes [#13661](https://bugs.scummvm.org/ticket/13661)
Thanks to @dwatteau for building and testing on OSX PPC.
=> SAGA: Fix use-after-free on handling actor action

engines/director/archive.h, engines/director/director.cpp, engines/director/director.h, engines/director/resource.cpp
1. Moved ProjectorArchive declaration to archive.h
2. getRawExeName to get executable file name without overriding from --start-movie parameter
3. Used multiarchive to detect and add resource files to searchman
=> DIRECTOR: Add multiple resources in exe using ProjectorArchive

common/language.cpp, common/language.h, dists/scummvm.6
Need this to allow the language to be set to Bulgarian for the Schizm: Mysterious Journey Steam release.
=> COMMON: Add Bulgarian language code

engines/director/cast.cpp
According to the manual, in addition to separate files, xlibs can be loaded from the shared cast:
However, right now ScummVM only does this search in `probeMacBinary`, which doesn't get called on this resource in this context.
Adding this ensures that the shared cast's xlibs get enabled. Fixes recognizing Journey to the Source's (journey2source, Mac) custom xlib. I have a separate branch where I'm implementing that custom xlib, but I'm opening this as a PR first to make sure everything looks OK for this change on the buildbot.
=> DIRECTOR: Cast: search for xlib

engines/ags/module.mk, engines/ags/plugins/ags_sprite_video/ags_sprite_video.cpp, engines/ags/plugins/ags_sprite_video/ags_sprite_video.h, engines/ags/plugins/plugin_base.cpp
This PR adds stubs for the ags_spritevideo plugin, which is a dropin replacement for the old D3D plugin.
The D3D plugin was used in Chronicle of Innsmouth - Mountains of Madness to play some "videos" which are
still images with little animation, used mostly during the intro and the final part of the game.
With the stubs in place the game is playable (not yet confirmed as completable)
=> AGS: Add stubs for ags_spritevideo plugin

backends/graphics/opengl/opengl-graphics.cpp, backends/graphics3d/android/android-graphics3d.cpp
This looks like an overlook since the creation of the backend.
Previous Android backend used this and it shouldn't harm other
platforms.
This should fix a bug on ChromeOS.
In addition a small fix on Android3D is done.
=> BACKENDS: OPENGL: Clear screen using opaque black instead of transparent

engines/mm/mm1/data/character.cpp
This assumes the intention was to guard against both: invalid portrait numbers passed in portraitNum and also invalid values loaded from the save.
@dreammaster Is this correct?
=> MM: MM1: Fix portrait validation

engines/director/lingo/lingo-builtins.cpp
In 6e47994fc793f122768565185b1d6c6052aca2d9, openResFile was changed to use the new `openArchive` method. However, that method tries to treat the file as a Director archive and it may not be. This broke, for example, loading external cursors via `openResFile`. This reverts to the previous behaviour.
Tested by confirming that mominoki-mac-ja's cursor works again.
cc @moralrecordings
=> DIRECTOR: revert changes to openResFile

base/commandLine.cpp, engines/advancedDetector.h, engines/metaengine.h, engines/scumm/detection.cpp, engines/sky/detection.cpp
This adds the `--stats` command line option to print the number of engines, games, game variants, and added targets. This is related to https://bugs.scummvm.org/ticket/13741 that already includes commands to obtain a similar result. But I though an easier way to obtain it would not hurt.
This can be combined with `--engine=` to list statistics for the specified engine. This accepts a list of multiple engines separated by a coma, and the special value `all`.
And while I was at it, I also made separate commits to support specifying multiple engines with `--engine=` for the `--list-games`, `--list-all-games`, and `--list-targets` options as well.
With no engine specified, only a summary is printed:
```
scummvm % ./scummvm --stats                      
--------------- ---------------- …
```
=> 📊 Add command line option to print statistics  

engines/director/channel.cpp, engines/director/sprite.cpp, engines/director/sprite.h
Self explanatory, do not merge, WIP.
=> DIRECTOR: Fix sprite position setting

engines/mm/shared/xeen/sprites.cpp
Some resource files from MM1 are opened by ID, that is hash(filename). The ID for "049.att." file is exist and incorrect for this file. MM4-5 games should not use IDs at all.
Not sure if here is the right place to select the way sprite loads. But it fixes bug #14503.
=> MM: XEEN: workaround for broken canrnage hand animation.

engines/mm/mm1/data/roster.cpp
Do not ignore EOS when loading roster save.
This prevents a comparison with an uninitialized variable.
Fixes [#14509](https://bugs.scummvm.org/ticket/14509)
=> MM: MM1: Fix crash on roster load

engines/scumm/players/player_mod.cpp, engines/scumm/players/player_v2a.cpp, engines/scumm/players/player_v3a.cpp
This fixes bug [#14470](https://bugs.scummvm.org/ticket/14470) with a fix provided by athrxx and also put a sort of safeguard in place for when I'll have a bit of time to implement a 50Hz mode for Amiga SCUMM games (which has already been requested a few times). 
Posting it as a PR: while this fix (again, courtesy of athrxx) is certainly logical, I haven't tampered with this part of the codebase enough to directly commit the change to master. The bug was originally introduced here 104b39ef67e4e1ddcf5e6124b8a0844a7062346a when trying to fix another bug which caused music to be playing too fast.
As for the second and third commits, which are pretty straightforward, I report here the commit message:
> (Since the previous commit fixes something that was historically
put in place to fix a …
=> SCUMM: Fix some V2-3 Amiga Player timing issues

engines/metaengine.cpp
A long description greater than 255 chars currently breaks the remaining parts of the extended savegame header.
The correct fix is likely to prevent this size before writing, but something should be handled during write. Other options could be to assert or return an error.
=> ENGINES: Prevent save description length overflow

engines/mm/mm1/views_enh/character_inventory.cpp
To reproduce the problem:
1. start/load a game in enhanced mode
2. Select a character
3. Press i to open inventory
4. Press a to go to arms view
5. Press r to get the remove item prompt
6. Press a number key one greater than the last item in the list
This should lead to a crash/assert
=> MM: MM1: Fix bounds check in enhanced mode inventory handling

gui/dialog.cpp, gui/dialog.h, gui/gui-manager.cpp
This PR is two fold:
- The bug #7124 is fixed by sending a fake mouse moved event at the end of drag
- The tooltip caused the drag operation to abort which caused inconsistencies between before and after displaying the tooltip
=> GUI: Fix bug #7124

engines/mm/mm1/views_enh/character_inventory.cpp
- Switch to equipped items view when selecting the unequip action
- Switch to backpack items view when selecting the equip action
Depending on current mode, ViewsEnh::CharacterInventory holds either a list of backpack or equipped items (BACKPACK_MODE/ARMS_MODE).
When calling the equip(/unequip) method, the index of the selected equipment from the list is passed.
However, these methods always access the backpack(/equipped) item list regardless of the current mode.
The use of an invalid index then leads to manipulating the wrong item and/or the use of uninitialized/stale values.
This is fixed by setting the appropriate mode before the call.
=> MM: MM1: Fix (un)equipping items in enhanced mode

engines/metaengine.cpp, engines/metaengine.h, engines/vcruise/vcruise.cpp
V-Cruise kind of needs this to properly handle the "Continue Game" feature, which loads the most recent save.  Previously, doing that loaded the autosave slot, but that doesn't work correctly if the user has disabled autosaves, so instead it was changed to parse the date from the savegame.
Unfortunately, the date is stored with the most-significant values in the least-significant bit positions, so comparing the raw date value doesn't work, it has to be decomposed.  Also unfortunately, `parseSavegameHeader` doesn't extract the date in a numeric format, it extracts it into a formatted string.
This adds some functions to decompose the savegame date to deal with this problem without the engine having to make assumptions about how the savegame header format stores dates.
=> ENGINES: Add functions to decompose the date and time values from a savegame header

graphics/yuv_to_rgb.cpp, graphics/yuv_to_rgb.h, video/theora_decoder.cpp, video/theora_decoder.h
This PR adds support for YUV422 and YUV444 Theora video decoding.
Most code was already implemented in yuv_to_rgb.cpp, so the changes are minor.
Format 422 is required to play one of the introductory movies in Downfall Redux. I also tested YUV444 using a sample movie.
Other less common formats (such as 411) are not implemented.
=> VIDEO: Add YUV422 and YUV444 to Theora decoder

common/archive.cpp, common/archive.h, common/compression/installshieldv3_archive.cpp, common/compression/installshieldv3_archive.h, common/compression/stuffit.cpp, common/compression/stuffit.h, common/compression/vise.cpp, engines/grim/grim.cpp, engines/groovie/groovie.cpp, engines/kyra/resource/resource_intern.cpp, engines/mtropolis/boot.cpp, engines/private/private.cpp
This adds some enhancements for engines to process StuffIt archives more accurately by preserving the directory structure.
It also adds a function for returning the path separator for archive formats and fixes up StuffIt path stringification to use the HFS path delimiter.  (Slash and backslash characters are legal in filenames in Mac archive formats.)
=> COMMON: Add "flattenTree" param to createStuffItArchive to preserve directory structure, add function to get path separators for archives

common/compression/gentee_installer.cpp, common/compression/gentee_installer.h, common/compression/module.mk, engines/vcruise/module.mk, engines/vcruise/vcruise.cpp
Adds support for Gentee Installer packages.  This has already been tested against the German and Polish versions of Schizm and appears to work OK.
=> COMMON: Move Gentee Installer loader from V-Cruise to Common

common/compression/stuffit.cpp
Cherry-picked from PR #5108
PR #5060 has an off-by-one error in the directory termination (rfind needs to start at size-2 because the last character is a path separator unless the prefix is empty), which causes subpaths to be incorrect.  This fixes it.
=> COMMON: Fix incorrect StuffIt directory paths

backends/platform/sdl/amigaos/amigaos-main.cpp
Fixes [#6956](https://bugs.scummvm.org/ticket/6956) "ScummVM returned with unfreed signals (AmigaOS4)"
=> AMIGAOS: Cleanup and free signals via atexit()

engines/grim/debugger.cpp, engines/grim/debugger.h, engines/grim/gfx_base.cpp, engines/grim/gfx_base.h, engines/grim/gfx_opengl.cpp, engines/grim/gfx_opengl_shaders.cpp, engines/grim/gfx_tinygl.cpp, engines/grim/grim.cpp, engines/grim/grim.h
Also some bugs were noticed (I guess it is not really that they should be reported here, but I don't want to register in the bug tracker):
1. `set_renderer`/`renderer_set` doesn't work properly.
2. Monkey Kombat health bar display is broken. It is always displayed fully. It reproduces with all the renderers.
=> GRIM: Add runtime introspection of renderer type used via `renderer_get` console command. Rename `set_renderer` into `renderer_set`.

engines/hdb/sound.cpp
Sound::playVoice():
Do not delete source stream on failed MP3/Vorbis decoding. This is already handled by the created Audio::MP3Stream/VorbisStream.
Possibly fixes [#14478](https://bugs.scummvm.org/ticket/14478)
=> HDB: Fix double-free on voice playback

engines/ags/shared/gfx/image.cpp
After commit b458ced "IMAGE: Speed up 16/24/32bpp BMP decoding",
some AGS games which use external BMP files don't work anymore (such as Strangeland or Troll Song)
because some allegro routines only support 1, 2 or 4 BPP.
This PR simply blits to a 32bpp surface after loading (i'm not sure this is the best or fastest way to do so,
please review)
=> AGS: Convert 24bpp to 32bpp when loading bitmaps

common/scummsys.h
Newer versions of Clang can tell us when UBSan has been enabled, which is useful to define `SCUMM_NEED_ALIGNMENT` when `-fsanitize=alignment` is in use (see https://reviews.llvm.org/D52386).
Can be useful to avoid some false positives about alignment when doing a build with UBSan but without using the `configure` script which already tries to detect this setting (see earlier PR #4208). NetBSD does a similar thing, it seems.
A good example is building and running a v7/v8 SCUMM game, through an Xcode build where UBSan is enabled through its UI (Product > Scheme > Edit Scheme… > Diagnostics > Undefined Behavior Sanitizer).
=> COMMON: BUILD: Try detecting UBSan when not using configure

engines/sci/detection_tables.h
This adds detection entry for Hebrew fan translation of Phantasmagoria
from https://github.com/adventurebrew/HebrewAdventure
(based the Spanish fan translation, which allowed using subtitles in game)
Thanks
=> SCI: Detect hebrew fan translation of PHANT1

engines/gob/detection/tables_crousti.h
This adds detection for the german fan translation of Croustibat, available at https://github.com/BJNFNE/coktel-vision-translations --> Releases --> Croustibat (German Translation).
=> GOB: Add German Translation of Croustibat

gui/ThemeLayout.h
The theme layout padding values are parsed and stored as 16 bit signed integers. However ThemeLayout::setPadding treated the values as 8 bit signed integeres.
The padding values parsed from the STX file suited for the screen resolution are multiplied with the device content scale factor. The scale factor determines how content is mapped from the logical coordinate space (measured in points) to the device coordinate space (measured in pixels).
If the scale factor and the padding value results in a value greater than 255 it will wrap since the 8 bit type can't hold bigger values than that.
Running the iOS backend in debug configuration on an iPhone 12 mini, having the content scale factor value 3, and drawing the launcher in vertical mode where the bottom padding value is 92, the result …
=> GUI: Change ThemeLayout::setPadding input types to int16

engines/hopkins/events.cpp
This should address the issue of tiny cursor for Hopkins FBI (on Open GL mode)
Tested with Hopkins FBI Win95 / English demo.
=> HOPKINS: Fix cursor not scaling in OpenGL

backends/graphics/android/android-graphics.cpp, backends/graphics/android/android-graphics.h, backends/graphics3d/android/android-graphics3d.cpp, backends/graphics3d/android/android-graphics3d.h, backends/graphics3d/android/texture.cpp, backends/platform/android/android.cpp, backends/platform/android/android.h, backends/platform/android/events.cpp, backends/platform/android/org/scummvm/scummvm/ScummVM.java, dists/android/AndroidManifest.xml
This PR includes #2724 which enabled rotation.
Now, resize is enabled too: the user can split the screen with ScummVM running in half of the screen.
A bunch of fixes is also included:
- the framebuffer is not used when it's not needed, this may improve performance
- overlay background never worked before and is now fixed
- Android textures implementation got several fixes
- several code paths where GL functions were called without a valid context have been removed.
=> ANDROID: Various fixes around rotation and resize of activity

graphics/fonts/winfont.cpp, graphics/fonts/winfont.h, graphics/macgui/macfontmanager.cpp
Allow scaling of window font, ie FON, FNT. Internally this uses same implementation as BDFScaling and MacFontScaling. Uses function scaleSingleGlyph to scale each glyph.
Fonts in `mcluhan-win` used some of these fonts where the sizes
were different than parsed.
=> GRAPHICS: Add scaling for winfont

engines/ultima/metaengine.cpp, engines/ultima/metaengine.h, engines/ultima/ultima8/filesys/savegame.cpp, engines/ultima/ultima8/filesys/savegame.h, engines/ultima/ultima8/games/game_info.cpp, engines/ultima/ultima8/metaengine.cpp, engines/ultima/ultima8/metaengine.h, engines/ultima/ultima8/ultima8.cpp
Fixes bug #14043
Hello everyone! I'm looking for feedback on this change. Our Ultima 8 save game handling comes mostly from Pentagram, but there are incompatibilities as Pentagram saved to a zip archive and our engine used a different method.
This change makes the save game reader determine which archive method to choose based on the file's magic number.
=> ULTIMA8: Support reading of Pentagram save game files

engines/pink/objects/actions/action_text.cpp, graphics/macgui/mactext.cpp
This fixes hebrew rendering of PDA in Pink,
by avoiding usage of "lossy" codepage when on windows mode (utf-8 should be reversible in regards to utf-32)
also reverts commit 2fe812db972b5ccfe5034142be3273db313b1e8f from #5127.
=> MACGUI: Encode UTF-8 in windows mode

engines/sword1/logic.cpp
Reset `_scriptVars[SAM_RETURNING]` when changing to scene 33.
In the hospital, after pulling the plug from the socket, it is possible to save the game before Sam the janitor returns to his position.
On loading this save, he will be reset, but `_scriptVars[SAM_RETURNING]` will be set to 1.
This causes a softlock when the plug is pulled again.
Fixes [#14521](https://bugs.scummvm.org/ticket/14521)
=> SWORD1: Fix softlock when saving in hospital

engines/ags/lib/alfont/alfont.cpp
When displaying hires fonts, alfont applies an alternative blending mode which was not implemented, causing hi-res text to display improperly in multiple games (Mage's Initiation, Starship Quasar and Larry Lotter the most relevant cases).
This is not related to the recent Freetype discussions (those bugs are mostly related to the lowres fonts)
Before
After
Before
After
Fixes [13758](https://bugs.scummvm.org/ticket/13758) and some of the issues in [12940](https://bugs.scummvm.org/ticket/12940)
=> AGS: Fix blending of hires fonts in alfont

engines/ags/engine/script/cc_instance.cpp, engines/asylum/system/text.cpp, engines/bladerunner/vqa_decoder.cpp, engines/buried/scene_view.cpp, engines/chamber/cga.cpp, engines/chamber/input.cpp, engines/chamber/room.cpp, engines/chamber/script.cpp, engines/cine/anim.cpp, engines/director/sound.cpp, engines/dragons/background.cpp, engines/freescape/loaders/8bitBinaryLoader.cpp, engines/gob/inter_v7.cpp, engines/hypno/grammar_mis.y, engines/icb/breath.cpp, engines/icb/function.cpp, engines/icb/gfx/psx_pcgpu.cpp, engines/immortal/immortal.h, engines/immortal/logic.cpp, engines/myst3/archive.cpp, engines/nancy/graphics.cpp, engines/petka/interfaces/interface.cpp, engines/petka/objects/heroes.cpp, engines/petka/objects/object.cpp, engines/petka/objects/text.cpp, engines/watchmaker/classes/do_action.cpp, engines/watchmaker/ll/ll_anim.cpp
This cleans up all Visual Studio warnings except for the following, which need further investigation:
Glk:
```
_G(_hulkImageOffset) = -0x7ff;
```
_hulkImageOffset is a size_t
Immortal:
```
Common::Array<SFlame> f7{SFlame(576 - 384, (112 + 32) - 256, kFlameNormal), SFlame(576 - 384, (112 + 32) - 256, kFlameNormal),
SFlame(928 - 384, (48 + 32) - 256,  kFlameNormal)};
```
Several of these values are negative, but the SFlame constructor takes a uint16
Watchmaker:
- Several casts of rCreateSurface result from int to gTexture*.  rCreateSurface is currently stubbed and always returns 0, but there is some inconsistency of whether it is supposed to return an int or pointer.
- `PointInside2DRectangle` performs arithmetic on `inside_flag` which is a bool, and then returns it.  It's also returned as …
=> GLOBAL: Bulk MSVC warning cleanup

graphics/fonts/winfont.cpp, graphics/fonts/winfont.h, graphics/macgui/macfontmanager.cpp
Memory leak happened because the scaled generated fonts were not being cached or saved anywhere, thus they were not being destructed and freed. Added logic to cache generated font in _winFontRegistry itself.
Leaks observed in `trektech-win` in first few frames itself.
=> DIRECTOR: Fix WinFont scaling memory leak when scaling fonts.

engines/director/lingo/xlibs/fileio.cpp, gui/filebrowser-dialog.cpp, gui/filebrowser-dialog.h
Certain callers may want to specify a default filename for their savegames. This is used in Director, where the file browser can be constructed with the filename field prefilled. I've implemented this by adding a second optional positional argument.
For example, when the player starts a new game or loads an existing game in Ganbare! Inuchan 2 (ganbareinuchan2), the game prefills the name `INU.DAT`. Right now, ScummVM ignores the provided string and initializes the UI with no filename; with this patch, it works as expected.
I figured I'd open a PR for this since it's modifying the signature of a function outside the Director namespace.
=> FileBrowser: support setting a default name

engines/cge2/vmenu.cpp
Add nullptr check before using TTS in the exit dialog.
Fixes [#14383](https://bugs.scummvm.org/ticket/14383)
Also make sure TTS only plays in the exit dialog when enabled in the game
options ("Enable Text to Speech for Objects and Options").
=> CGE2: Fix Sfinx crash in builds without TTS

backends/graphics/android/android-graphics.cpp, backends/graphics/android/android-graphics.h, backends/graphics/windowed.h, backends/graphics3d/android/android-graphics3d.cpp, backends/graphics3d/android/android-graphics3d.h, backends/platform/android/android.cpp, backends/platform/android/android.h, backends/platform/android/jni-android.cpp, backends/platform/android/jni-android.h, backends/platform/android/org/scummvm/scummvm/ScummVM.java, backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java
This change also include a change in windowed.h which let backend specify where the game screen should be placed.
This part needs a careful review.
=> ANDROID: Move game screen at top while displaying keyboard

backends/graphics/opengl/pipelines/libretro.cpp, backends/graphics/opengl/pipelines/libretro.h, backends/graphics/opengl/pipelines/libretro/parser.cpp, backends/graphics/opengl/pipelines/libretro/parser.h, backends/graphics/opengl/pipelines/libretro/types.h, common/archive.cpp, common/archive.h, common/path.cpp, common/path.h, test/common/path.h
This PR is another try to fix https://forums.scummvm.org/viewtopic.php?p=98550#p98550 like #5140 
Instead of trying several paths, the path from where the shader preset is loaded is used as a base path.
This makes sure that all files are coherent.
For this to work, a function has been added in SearchSet to return the Archive a member pertains to.
In addition, a normalization function has been added to Path object: this avoids lossy transcode to String.
The implementation and tests have been copied from normalizePath function: they both behave the same.
There is still a limitation on Windows: the paths saved in configuration (themepath, iconspath, shader path) all contain backslashes.
The Path objects are created with the / delimiter by default this makes all path above considered as an …
=> BACKENDS: Fix libretro preset loading

engines/director/lingo/lingo-bytecode.cpp
Statements like `set the perFrameHook to me` where `me` was used to refer own object and setting `the` property of it were not allowed. This patch fixes this by returning current object from `me`.
'totaldistortion-win' uses this feature to set `the perFrameHook` to current factory mAtFrame method.
Additionally game
=> DIRECTOR: Allow using of 'me' in setting `the` expressions

engines/advancedDetector.cpp
int64 value is being printed using %ld which prints "long" except on Windows, int64 is "long long" and "long" is 32-bit.  This changes it to %lld and casts the parameter to long long int.
=> ENGINES: Fix wrong printf format specifier

engines/director/score.cpp
1. totaldistortion dream games, `Ok` button sticking is fixed.
2. `rect of window` takes window rect than default [0, 0, 1, 1]
Fix: https://trello.com/c/J3frDAgc/616-d4-openwindow-should-load-the-movie-right-away
=> DIRECTOR: Fix immediate execution of lingo scripts after frame jumping or opening movie

engines/director/lingo/lingo-code.cpp, engines/director/lingo/lingo-object.cpp, engines/director/lingo/tests/mperform.lingo
There are some builtins and methods that require this boolean allowRetVal to decide if they need to return anything, or pass them on, one such example is `m_perform` which can be called with or without a return.
Fixes problem where multiple `m_perform` inside `mAtFrame` were giving error of returning too many values.
=> DIRECTOR: Workaround m_perform to send allowRetVal to handler

engines/sci/engine/script_patches.cpp
This pull request speeds up the palette animation for Mr. Bigg's close-up in the LSL5 intro.
Looking at the dumped SCI scripts that @sluicebox announced recently, I could see that every version of rm130.sc contains the following method:
```
(method (doit)
(super doit:)
(if (not (mod (++ local2) 32))
(Palette palANIMATE 206 254 -1)
)
)
```
My workaround changes 32 to 6.  It's unclear what the intended speed was, but ScummVM currently runs it so slow that at first I thought the animation was missing completely.
Is this a good idea or not? I don't know, but it was a fun experiment either way.
=> SCI: Speed up the palette animation for Mr. Bigg's closeup in LSL5 (don't merge without careful review, if ever!)

engines/ultima/ultima4/controllers/read_player_controller.cpp
If user presses esc while selecting a character the controller returns -22 instead of the expected -1. This led to an out of bounds array reference and a crash.
=> ULTIMA4: Fix crash when pressing ESC after Cast

engines/director/lingo/lingo-code.cpp, engines/director/lingo/tests/lists.lingo
This was a regression, where the comparison between string and symbol
was broken in commit https://github.com/scummvm/scummvm/commit/343e3af14fd135244d2d9b4abed9e54275c1469d, This
was originally implemented in https://github.com/scummvm/scummvm/commit/236dd400381874f80eb94029741c5c6d984cc961.
=> DIRECTOR: Fix regression, string and symbol comparison working again.

engines/director/lingo/lingo-builtins.cpp, engines/director/movie.cpp
1. `sort.lingo` was using `scummvmassertequal` for comparing two arrays, now the code for array equality was absent so added it.
2. `builtin.lingo` throwing errors due to memory leak in when using `b_move`, fixed it.
=> DIRECTOR: Fix lingotests `builtin.lingo` and `sort.lingo` for greener builds.

engines/director/channel.cpp, engines/director/frame.cpp, engines/director/frame.h, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-events.cpp, engines/director/lingo/lingo-the.cpp, engines/director/score.cpp, engines/director/score.h, engines/director/sprite.cpp, engines/director/sprite.h
1. Copy channel sprites to frame before loading (ie lingo override score changes)
2. Refactor main channels to struct
3. Refactor cache property logic for tempo and palette
4. Improve auto-puppets, support individual property
Total distortion's bed dream game fully working now.
=> DIRECTOR: Improve frame loading, add support to lingo override score, refactor frame channels, autopuppet improve

common/archive.cpp
The dumped games through `dumpArchive()` were not able to get detected. This was because the `f->getName()` ends up having `/` and further puny encoding the filename with the `/` makes it unable to detect properly.
This PR fixes this by using the Path::punycodeEncode() and the new getPathInArchive().
Also fixes: the archive's contents were being dumped one directory back the `destPath`
=> COMMON: Use getPathInArchive() in dumpArchive() to get filename and fix directory issue

engines/ags/shared/util/file_stream.cpp, engines/ags/shared/util/file_stream.h
In AGS there is a possibility to define a function, FileCloseNotify with arguments, which is called when closing a file. This possibility seems not to be used by any of the engines supported by ScummVM since it's set to nullptr. This is not a problem in itself. Hoewever when enabling compiler optimisiations the compiler may optimise away the FileCloseNotify definition. This was discovered when compiling iOS with Apple Clang in "Release" mode that the if-case in the code block below was removed while the args parameter was left:
if (FileCloseNotify) {
CloseNotifyArgs args;
args.Filepath = _fileName;
args.WorkMode = _workMode;
FileCloseNotify(args);
}
This caused a nullptr exception since FileCloseNotify was nullptr. A bit strange behavior by the compiler which could remove the entire code …
=> AGS: Remove function FileCloseNotify

engines/director/score.cpp
Initially, the frames data were only being reset and rebuild when jumps were made to frame that is different than current one, ie this in case when `_nextFrame != _curFrameNumber`, this however had problems with `majestic-mac` not opening and stuck on loading screen.
Fixed problem where `majestic-mac` would constantly jump to main-menu screen (ie same frame) and would not load the game.
=> DIRECTOR: Rebuild frames when there is jump to current frame

gui/widgets/groupedlist.cpp
With monospaced fonts, adding spaces indents the line much more than it would otherwise. This is a problem with the DS port, where the number of characters per line is very limited because of the small screen.
=> GUI: Fix indentation in GroupedListWidget with monospaced fonts

engines/sludge/movie.cpp
MKVDecoder takes ownership of the passed stream, it can't be allocated
on the stack. This fixes a crash in MKVDecoder destructor.
=> SLUDGE: movie: Allocate substream on heap

engines/director/lingo/lingo-object.cpp, engines/director/lingo/xlibs/quicktime.cpp, engines/director/lingo/xlibs/quicktime.h, engines/director/module.mk
This xlib is specific to Journey to the Source (and possibly other discs by Grid Media). I've tested with the Mac version and it's largely working as expected now, aside from a minor issue related to [movies being loaded late in ScummVM](https://trello.com/c/J3frDAgc/616-d4-openwindow-should-load-the-movie-right-away).
I haven't implemented incorporating the video's palette yet - the method used by XPlayAnim doesn't work here. To work around that, I've added a quirk that sets it to run in 32bpp mode. That's why I'm opening a PR - I figured this is more of a temporary hack than a permanent fix, and I wasn't sure if other devs would mind me adding it.
=> DIRECTOR: Journey to the Source: add Quicktime xlib

engines/mohawk/myst_graphics.cpp
The map picture in the Polish version of Myst ME has a weird pixelformat that causes it to look inverted.
This PR simply converts the picture so it looks normal.
It could probably be fixed on load, but I don't know enough about this engine to attempt a different fix.
Can be tested using the GOG version, which includes the Polish language.
Fixes TRAC #12044
=> MOHAWK: Fix inverted map colors in Myst ME (polish)

engines/director/window.cpp
When changing from shared casts in `Window::loadNewSharedCast`, and in instance where previousCast need to be deleted, we just deleted the cast itself but not the underlying `Archive`, this resulted in memory leaks. `~Director()` was not deleting this archive because it was being removed from `_allSeenResFiles` in favour of loading new archive.
Fixed by deleting `Archive *_castArchive` of previousCast after erasing its entry from `_allSeenResFiles`.
=> DIRECTOR: Fix memory leaks when changing sharedCast

engines/director/lingo/lingo-code.cpp, engines/director/lingo/tests/factory-do.lingo, engines/director/resource.cpp
Anonymous functions are allowed to access the instance variables that are in scope, just like localVariables. This patch restores the  original behavior by not resetting `_state->_me` when a context is pushed that belongs to anonymous function while it is being called from object, ie `kFactoryObj | kScriptObj`. Commands like `do("set instanceVar = 1")` and `do("set abc = instanceVar")` will now work.
Fixes food maker in food bar where up/down buttons were not working.
--start-movie="ATD\HD\cfTWR4FO.DXR" totaldistortion-win
=> DIRECTOR: Anonymous function access object

engines/director/sprite.cpp
It has been observed that for `Shape` cast members, the default color is white, as there were no foreColor in frames data for white fore-color casts. This indicates  how director saves more memory by omitting this foreColor(255).
`mediaband-win` used several of transparent white rectangle shape cast to identify hover and click events. Using lingo `rollOver` command However these shapes were set foreColor white which was not being embedded in frames data. This caused the shapes to be rendered black which is default foreColor.
=> DIRECTOR: Fix black patches in meet-media band
