scummvm/scummvm

engines/agi/systemui.cpp
French version the AGI system UI translated by Threepwang (https://github.com/Thpwg).
=> AGI: Add French UI case

audio/decoders/qdm2.cpp, engines/glk/agt/os_glk.cpp, engines/hdb/map.cpp, engines/hypno/libfile.cpp, engines/saga2/interp.cpp, engines/saga2/sprite.cpp, engines/testbed/cloud.cpp, engines/toltecs/script.cpp
=> JANITORIAL: Add some long casts to match %ld format

configure, engines/glk/adrift/sctafpar.cpp, engines/ultima/ultima8/graphics/fonts/tt_font.cpp, engines/ultima/ultima8/graphics/fonts/tt_font.h
This includes the changes from PR #4003 and PR #4018.
=> RISCOS: Increase the optimization level

backends/midi/riscos.cpp, backends/module.mk, base/plugins.cpp
=> RISCOS: Add a native MIDI driver

devtools/dumper-companion.py
This is the same as #3495 but rebased and reworded commit message
=> DEVTOOLS: COMPANION: MacJapanese mapping of SHIFT-JIS range, log levels, typo fixes

engines/director/detection_paths.h, engines/director/detection_tables.h
Additionally remove duplicate Invisible Universe entries
=> DIRECTOR: Yet more games, remove some of detection_paths

engines/director/detection_tables.h
=> DIRECTOR: Actually add Tenrou Toshi entry

common/platform.cpp, common/platform.h, engines/glk/module.mk, engines/glk/scott/detection.cpp, engines/glk/scott/detection_tables.h, engines/glk/scott/globals.h, engines/glk/scott/load_game.cpp, engines/glk/scott/load_ti99_4a.cpp, engines/glk/scott/load_ti99_4a.h, engines/glk/scott/scott.cpp, engines/glk/scott/scott.h, engines/glk/scott/ti99_4a_terp.cpp, engines/glk/scott/ti99_4a_terp.h
Following games have been added to detection:
Scott Adams adventures 1-12 in the TI99/4A format. The archive includes:
- Adventureland
- Pirate Adventure
- Secret Mission
- Voodoo Castle
- The Count
- Strange Odyssey
- The Mystery Fun House
- Pyramid of Doom
- Ghost Town
- Savage Island Part I
- Savage Island Part II
- Golden Voyage
source: http://www.ifarchive.org/indexes/if-archive/scott-adams/games/ti99/
=> GLK: SCOTT: Add support for TI-99/4A games

engines/ags/detection_tables.h
Additionally corrected the title of timegentlemenplease to "Time Gentlemen, Please!" as it was missing the exclamation mark
=> AGS: Add some Steam demo entries

image/pict.cpp, image/pict.h
This is a WIP pull request to add PICTv1 support to image/pict.cpp
=> GRAPHICS: IMAGE: Add version identifier for PICT, Implement o_clip function

devtools/dumper-companion.py
A couple features that were requested
=> DEVTOOLS: COMPANION: Add warning when possible JP string is found, punycode by default

engines/wage/detection.cpp, engines/wage/detection_tables.h
GrailQuest added as a "BIGGAME" due to being released as a physical retail game. Also added some punycoded names.
=> WAGE: Add some more games

engines/director/castmember.cpp, engines/director/director.cpp, engines/director/game-quirks.cpp, engines/mtropolis/elements.cpp, engines/wage/world.cpp, graphics/fonts/winfont.cpp, graphics/fonts/winfont.h, graphics/macgui/macfontmanager.cpp, graphics/macgui/macfontmanager.h, graphics/macgui/mactext.cpp, graphics/macgui/mactext.h, graphics/macgui/macwindowmanager.cpp, graphics/macgui/macwindowmanager.h
These are changes in `Graphics::MacFontManager` and `Graphics::MacText` which will reflect the fallback to some other font in the TextCastMember. These also add windows fonts for mcluhan in its respective quirk.
WIP for now
=> DIRECTOR: Reflect change of Font in TextCastMember, add Windows fonts for McLuhan

graphics/palette.cpp, graphics/palette.h
Needed for palette caching in #4033 and possibly future SCUMM GUIs.
=> GRAPHICS: Add naive algorithm option for PaletteLookup

engines/ags/detection_tables.h
* Add detection for recent games (from ags forums)
* Add detection for old French games (multiple sources)
* Add detection for various itch.io AGS games
=> AGS: Add detection for some games + minor fixes

AUTHORS, doc/docportal/help/credits.rst, engines/director/credits.pl, gui/credits.h
I'm opening this as a PR to make sure I've handled the accept correctly.
=> CREDITS: add Misty De Méo

engines/ags/detection_tables.h
=> AGS: Add detection for some commercial games (including issue #13721)

engines/director/detection_tables.h
=> DIRECTOR: Fix warlock demo detection entries

engines/icb/detection.cpp
Link to the English demo: https://drive.google.com/file/d/1k26J170s9xsogvvTmFzXy4mh_BM9opt-/view?usp=sharing
=> ICB: ELDORADO: Add detection for PS1 versions, Spanish, Italian, Portuguese versions and English demo

NEWS.md, doc/docportal/settings/game.rst
Adds news announcement line and settings docs for Obsidian
=> NEWS/DOC: Add Obsidian announcement+documentation

engines/macventure/detection.cpp
=> MACVENTURE: Add more Mac and IIGS versions to detection

engines/director/archive.cpp, engines/director/archive.h, engines/director/cast.cpp, engines/director/movie.cpp
These changes use the KEY* Chunk to load resources which are owned by the Movie (parentIndex 1024). This implements a MovieMap, which stores the indices and tags of the chubnks which are children of the movie.
=> DIRECTOR: Read KEY* resource before reading CAS* resource

engines/macventure/detection.cpp
=> MACVENTURE: Fix detection for Deja Vu 1993, others

engines/sword2/maketext.cpp, engines/sword2/sword2.cpp, engines/sword2/sword2.h
=> SWORD2: Add Hebrew support

engines/sci/detection_tables.h
Additionally add version numbers for some existing entries
=> SCI: Add detection for QFG2 v1.105

engines/scumm/script_v2.cpp, engines/scumm/script_v5.cpp, engines/scumm/script_v6.cpp
=> SCUMM: Simplify bug #4556 workaround; whitespace and comment fixes

engines/mtropolis/detection.cpp, engines/mtropolis/detection.h, engines/mtropolis/detection_tables.h
Demo: https://drive.google.com/file/d/1zeVS-HiI-sUrsKnuaqW3__UK_gSOJxVj/view?usp=sharing
=> MTROPOLIS: Add detection for Muppet Treasure Island (EN, IT, ES (MX), EN demo)

engines/scumm/script_v5.cpp
The crowd has some reaction lines while Guybrush plays the spitting contest on Booty Island, but some of them are missing an audio sample in the current version of the Monkey Island 2 Ultimate Talkie builder:
* the `"Hey spitter hey spitter hey spitter…"` lines
* and the `"C'mon!  What are you?  Afraid?"` lines.
You'll see the text, but you won't hear anything. The other dozen reaction lines are fine, though.
You'd need to wait quite a bit while Guybrush tries spitting before you'd reach them, though, so that's probably why it's been unnoticed before Threepwang told me about it!
Script 47-218 does this:
```
...
[0404] (48) } else if (Local[1] == 1) {
[040E] (27)   PutCodeInString(29, sound(0xA1506C1, 0xA) + "Let's go!");
[042B] (48) } else if (Local[1] == 2) {
[0435] (27) …
```
=> SCUMM: Work around some silent lines in the spitting contest of MI2 Talkie

engines/dragons/dragons.cpp, engines/dragons/metaengine.cpp
Also put the urls in the messages in a const char* variable, hardcoded.
=> DRAGONS: Fix depracted url for data files

engines/grim/resource.cpp
Also use hardcoded url for the download location address
=> GRIM: Use GUIErrorMessageWithURL for missing patches

engines/myst3/myst3.cpp
Also hardcode the url for the download location address
=> MYST3: Use GUIErrorMessageWithURL() for missing patch

engines/ags/detection_tables.h
=> AGS: Add detection for new games

common/array.h, engines/ultima/shared/std/containers.h
The implementation is taken from the Ultima engine.
=> COMMON: Add a range-based version of Common::Array::erase()

configure
=> CONFIGURE: Fix typo

configure
=> CONFIGURE: Fix even more typos

audio/audiostream.cpp, audio/audiostream.h, engines/director/cast.cpp, engines/director/graphics.cpp, engines/director/lingo/lingo-events.cpp, engines/director/lingo/lingo-the.cpp, engines/director/sound.cpp, engines/director/sound.h, engines/director/sprite.cpp
In Director 4, with score scripts it is possible for the compiler
to produce a generic handler which is empty, in addition to named
handlers (e.g. mouseUp). The original behaviour for sprite scripts
was to default to the generic handler if it exists, even if there
is a named handler that matches the event. This change makes the
generic handler the fallback choice.
Fixes opening the inventory in Eastern Mind.
=> DIRECTOR: Fixes made while testing Eastern Mind

engines/director/images.cpp
This change fixes the regression introduced in db01ec1dbdbd8bcef7159a79f4b8c2054f7fd191
BITD decoding was changed between D3 and D4, relevant tests have been pushed to the tests repository.
=> DIRECTOR: Fix 8bpp BITD decoding regression

devtools/dumper-companion.py
=> DEVTOOLS: COMPANION: Catch errors if filename can't be decoded as Mac-Japanese; Remove unused function

engines/groovie/video/roq.cpp
we should take minimum to be sure that we won't exceed maximum size and didn't fail on assertion
=> GROOVIE: Fix bug - https://bugs.scummvm.org/ticket/13809

engines/groovie/detection.cpp
suggested by realisticrain on Discord
waiting for confirmation that this works
=> GROOVIE: UHP Beta detection entry

engines/director/debugger.cpp, engines/director/detection.cpp, engines/director/detection.h
=> DIRECTOR: Revert use of detection code

engines/director/cast.cpp, engines/director/cast.h, engines/director/debugger.cpp, engines/director/debugger.h, engines/director/frame.cpp, engines/director/frame.h, engines/director/lingo/lingo-bytecode.cpp, engines/director/lingo/lingo-codegen.cpp, engines/director/lingo/lingo-object.cpp, engines/director/lingo/lingo-object.h, engines/director/lingo/lingo.cpp, engines/director/lingo/lingo.h, engines/director/score.cpp, engines/director/util.cpp
=> DIRECTOR: More debugger features

video/subtitles.cpp
Following #4186
This adds support for BiDi text in subtitles.
Thanks
=> VIDEO: Support BiDi text in subtitles

common/macresman.cpp, common/macresman.h, engines/director/archive.cpp, engines/director/cast.cpp, engines/director/castmember.cpp, engines/director/lingo/lingo-code.cpp, engines/director/lingo/lingo.cpp, engines/director/resource.cpp, graphics/macgui/macfontmanager.cpp, video/video_decoder.cpp
=> DIRECTOR: Fix last of the the memory leaks

engines/glk/agt/agil.cpp, engines/glk/agt/agility.h, engines/glk/agt/agt.h, engines/glk/agt/agtread.cpp, engines/glk/agt/agxfile.cpp, engines/glk/agt/auxfile.cpp, engines/glk/agt/exec.cpp, engines/glk/agt/gamedata.cpp, engines/glk/agt/interface.cpp, engines/glk/agt/interp.h, engines/glk/agt/metacommand.cpp, engines/glk/agt/os_glk.cpp, engines/glk/agt/parser.cpp, engines/glk/agt/savegame.cpp, engines/glk/agt/token.cpp
This PR includes all the commits relevant to ScummVM to update the Agility interpreter to version 1.1.2,
as asked in feature request [13574](https://bugs.scummvm.org/ticket/13574)
I personally tested the games mentioned in bugreports:
[12794](https://bugs.scummvm.org/ticket/12794)
[12795](https://bugs.scummvm.org/ticket/12795)
[12798](https://bugs.scummvm.org/ticket/12798)
and can confirm that the issues are solved.
No changes applied to the original code (except indentation and a couple minor warning fixes)
=> GLK: AGT: Update Agility interpreter to version 1.1.2

engines/director/debugger.cpp, engines/director/debugger.h, engines/director/lingo/lingo-code.cpp, engines/director/lingo/lingo.cpp, engines/director/window.cpp
=> DIRECTOR: Add movie select and breakpoint commands to debugger

video/subtitles.cpp, video/subtitles.h
just add `subtitle_dev=true` to your scummvm.ini file, and it will show the filename for any missing file along with the current timestamp
so you can record a video of yourself playing the whole game, then create the files that it was missing and use the shown timestamps to figure out the proper timing for the subtitles
=> VIDEO: subtitles dev mode for making subtitles txt files

engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-utils.h, engines/director/lingo/tests/the.lingo
`put the length of 123` always returns 0 in both D3 and D4
`put numToChar("a")` returns different results between D3 and D4:
D3 returns a script error
D4 gives interesting results (thus the warning about unimplemented behaviour)
=> DIRECTOR: Add BUILDBOT to some warnings; a couple Lingo findings

engines/director/lingo/lingo-builtins.cpp
=> DIRECTOR: Fix numToChar in D4+ when converting an integer

engines/director/detection_tables.h, engines/director/game-quirks.cpp
=> DIRECTOR: Convert note about wolfgang into quirk

engines/agos/script.cpp, engines/agos/vga.cpp
Fixes https://bugs.scummvm.org/ticket/5856
Extends the solution introduced in https://github.com/scummvm/scummvm/commit/d64ea1ad87066aae2fae5f06b70d7b0358b78af9 for StS1 CD Demo
=> AGOS: SIMON2: Fix pirate dialogue freeze

engines/scumm/object.cpp
The 256-color versions of Indy3 have a very strange purple line next to the big tapestry that's in the middle of room 135, in Castle Brunwald.
Yeah, it's just that little purple line and I'm probably too obsessive, but the good news is that it's been reported by some other users years ago in [Trac#3208](https://bugs.scummvm.org/ticket/3208), so I'm not alone! That's the first room you can enter in Castle Brunwald, and the only thing there is in this room is this tapestry, and this glitch. Also happens in the original interpreters.
It looks like an artist made some wrong click when redrawing this object for the VGA versions, or maybe the compression routine for those images had some bug. QA was probably rushed for this port, too, since Indy3 has various oversights related to the VGA …
=> SCUMM: Fix an original tapestry glitch in Indy3 VGA (Trac#3208)

engines/director/castmember.cpp, engines/director/castmember.h, engines/director/channel.cpp, engines/director/debugger.cpp, engines/director/debugger.h, engines/director/detection_tables.h, engines/director/frame.cpp, engines/director/frame.h, engines/director/lingo/lingo.cpp, engines/director/score.cpp, engines/director/score.h, video/qt_decoder.cpp, video/video_decoder.cpp
=> DIRECTOR: Debugger + Chop Suey fixes

engines/engine.h
Minor cleanup as I learn the code.
=> JANITORIAL: Adjust comment: SaveFileMAnager -> SaveFileManager

engines/director/resource.cpp
I've only tried this on the Wrath of the Gods demo (https://archive.org/download/WRATH_201408/WRATH.zip), so may not work for other movies.
=> DIRECTOR: Add support for multi-entry D3 EXEs

common/lua/scummvm_file.cpp, engines/sword25/detection_tables.h, engines/sword25/gfx/graphicengine.cpp, engines/sword25/gfx/graphicengine.h, engines/sword25/gfx/text.cpp
changes:
* use unicode-bidi for hebrew text
* add detection of hebrew patch to detection table
=> SWORD25: Add hebrew support

doc/docportal/.readthedocs.yaml, doc/docportal/conf.py, doc/docportal/requirements.txt
DRAFT: Opening a PR to to check whether changing requirements file and adding specific dependencies fixes the issue where text after "note" directives remain within the note, even when it shouldn't.
=> DOCS: updates Read the Docs build dependencies

engines/sword1/detection.cpp, engines/sword1/detection.h, engines/sword1/detection_tables.h, engines/sword1/metaengine.cpp, engines/sword1/obsolete.h, engines/sword1/sword1.cpp, engines/sword1/sword1.h
This will require the detection table to be fleshed out a bit before this can be merged.
=> SWORD1: Switch to AdvancedMetaEngineDetection

backends/fs/amigaos/amigaos-fs.cpp
Yeah, well, i'm blind without my glasses
Sorry :-/
=> AMIGAOS: Fix oversight in debug output

engines/director/lingo/lingo-builtins.cpp
=> DIRECTOR: LINGO: Fix xlib name resolution

engines/wage/detection_tables.h
This version of "The Ashland Revolution" says that it's a full 1.0 but registering gets you 2.0 which has even more stuff. I've marked it as a non-demo regardless. (I can't remember what the ones marked as demos do)
[World Builder.zip](https://github.com/scummvm/scummvm/files/9946985/World.Builder.zip)
=> WAGE: Add games from "Wayzata's Best of Shareware for Macintosh" shareware disc

engines/scumm/metaengine.cpp
When the gamedir contains multiple valid entries, narrow selection by platform and also demo status.
Fixes bug #10117 when using C64 images of both the full version and demo of Maniac Mansion in the same folder.
=> SCUMM: Also filter demo entries if detector reports multiple hits

graphics/maccursor.cpp
Fixes bug #13922 where black cursor pixels in the SCI game QFG1VGA-Mac weren't being drawn. MacCursor uses 255 as its color key but in CRSR resources 255 is defined as black. CRSR resources use a mask for transparency so they have no color key. Now 255 is remapped to black.
=> GRAPHICS: Fix MacCursor handling of color 255

graphics/managed_surface.cpp
Function `blitFromInner()` excludes source formats with 3 bytes per pixel.  These are commonly returned from opaque full-color image decoders, like JPEG.  This change enables blitting with these source images.
- Add `== 3` to the list of acceptable source formats
- Add READ_UINT24 handling for 3-byte source formats
- Add READ_UINT24 and RGBA conversion for 3-byte destination when blending (copying non-opaque source to 24bpp surface)
=> GRAPHICS: Enable blitting 24bpp sources in managed_surface.cpp

backends/platform/sdl/opendingux/README.BUILD
1. Point to the new releases page.
2. Explain how to install the toolchain.
/cc @citral23
=> OPENDINGUX: Update build instructions

engines/saga/detection_tables.h, engines/saga/displayinfo.h, engines/saga/font.cpp, engines/saga/font.h, engines/saga/interface.cpp, engines/saga/itedata.cpp, engines/saga/itedata.h, engines/saga/metaengine.cpp, engines/saga/saga.cpp
Mostly works however:
1. The font is large. Some elements will still need adjustments. Smaller fonts are unavailable and original does adjustments and bad layout as well
2. "SAGA: Add language data for Chinese ITE" commit needs extra check as I don't speak Chinese
3. We need confirmation as to whether the release in question Chinese Simplified or Traditional
=> SAGA: Support for Chinese ITE

audio/casio.h, audio/midiparser.cpp, audio/softsynth/opl/mame.h, common/rect.h, devtools/create_mortdat/gametext.h, engines/ags/engine/main/game_run.cpp, engines/glk/adrift/os_glk.cpp, engines/glk/agt/agil.cpp, engines/glk/agt/gamedata.cpp, engines/glk/agt/metacommand.cpp, engines/glk/agt/util.cpp, engines/glk/tads/tads2/output.cpp, engines/kyra/sound/sound_pc_midi.cpp, engines/queen/musicdata.cpp, engines/saga2/actor.cpp, engines/saga2/localize.h, engines/scumm/scumm.h, engines/sherlock/tattoo/tattoo_people.cpp, engines/sherlock/tattoo/tattoo_scene.cpp, engines/sherlock/tattoo/widget_options.cpp, engines/tsage/sound.cpp, engines/tsage/staticres.cpp, engines/ultima/ultima4/core/settings.h, engines/ultima/ultima8/ultima8.h, engines/ultima/ultima8/world/container.h, engines/ultima/ultima8/world/fireball_process.cpp, engines/wintermute/base/gfx/base_renderer.h, graphics/macgui/mactext.cpp, gui/predictivedialog.cpp
This now combines commits together into one per engine / subsystem for easier review.
It also replaces the commits which change game data with FIXME comments instead so these commits now only change comments and thus should be uncontroversial and easy to review and merge.
@raziel- : Thanks for tracking down these mistakes.
=> Fixed Up Version of PR 4408 i.e. JANITORIAL: Spelling Mistakes

engines/director/cast.cpp, engines/director/castmember.cpp, engines/director/castmember.h, engines/director/channel.cpp, engines/director/debugger.cpp, engines/director/detection_tables.h, engines/director/director.h, engines/director/frame.cpp, engines/director/frame.h, engines/director/graphics.cpp, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-code.cpp, engines/director/lingo/lingo-the.cpp, engines/director/score.cpp, engines/director/score.h
=> DIRECTOR: Fixes for Devo

devtools/dumper-companion.py
Adds --forcemacbinary switch, which forces data-only files to use MacBinary encoding, ensuring the file type code and other metadata is preserved.
Also cleans up a few things that were blocking testing this on Win:
- Minor refactor of file_to_macbin to write directly to the file.  Previously this caused a memory spike of up to 3 times the data fork size (once for the file.data buffer, once for the macbin buffer, once for the temp buffer when appending to it), which was causing OOMs with 32-bit Python when digesting large CD-ROM sized files.  Now it only needs enough memory for one copy of the fork.
- Add file encoding spec to fix it not starting.
=> DEVTOOLS: COMPANION: Add --forcemacbinary switch and clean up some things.

NEWS.md, engines/neverhood/blbarchive.cpp, engines/neverhood/blbarchive.h, engines/neverhood/detection.cpp, engines/neverhood/neverhood.cpp, engines/neverhood/resourceman.cpp, engines/neverhood/resourceman.h
It was choking on missing "Making of". I tested by going through first couple of puzzles and main menu. Menu is fully translated but the puzzles are textless so far.
=> NEVERHOOD: Enable Japanese version.

devtools/dumper-companion.py
Minor janitorial commit after #4415 was merged
=> DEVTOOLS: COMPANION: Format using black

engines/sword1/animation.cpp, engines/sword2/animation.cpp, video/dxa_decoder.cpp
=> VIDEO: Switch DXA decoder to gzio.

backends/graphics/opengl/opengl-graphics.cpp
This seems like the wrong way to check for scaling so need some feedback there.
Better way to do this would be clamp-to-border and expand the geometry+texcoords by a half-texel, but GLES2 doesn't support border color, so do this instead.
Before: https://i.imgur.com/pcQFWhT.png
After: https://i.imgur.com/2BGLnaO.png
=> BACKENDS: Add 1-pixel transparent border to cursors for nicer edge behavior with linear filtering.

common/crc.h, common/crc_slow.h, common/macresman.cpp, common/unzip.cpp, engines/mtropolis/boot.cpp, test/common/crc.h
This allows i.a. themes without using zlib. Also this prepares for the use of algorithms other than deflate and store. Kyra1 floppy installer uses 2 other algos
=> COMMON: Change unzip.cpp to use gzio rather than zlib

engines/sci/console.cpp, engines/sci/engine/script_patches.cpp, engines/sci/engine/vm.cpp, engines/sci/engine/vm.h
See commit message. I ain't touching the VM without a PR! =)
=> SCI: Track location and size of temp variables 

base/commandLine.cpp, base/plugins.cpp, engines/metaengine.h
=> Fix error where launching a game from command line with -p would erase it from scummvm.ini

gui/widgets/groupedlist.cpp
=> GUI: Place empty metadata games last when sorting

backends/platform/3ds/3ds.mk, configure
This allows compiling with
```
wget https://curl.haxx.se/ca/cacert.pem
export DEVKITPRO=/opt/devkitpro
export DIST_3DS_EXTRA_FILES=$HOME/scummvm/cacert.pem
export BANNERTOOL=$HOME/bannertool/output/linux-x86_64/bannertool
export MAKEROM=$HOME/Project_CTR/makerom/bin/makerom
./configure --host=3ds --enable-plugins --default-dynamic
make dist_3ds
```
This PR is not mandatory but shortens the needed incantation for 3ds compilation
=> 3DS: Make configuration simpler

engines/freescape/detection.cpp
Reformatted the entries to be more consistent with other engines while I was at it
[freescape_games.zip](https://github.com/scummvm/scummvm/files/10246558/freescape_games.zip)
=> FREESCAPE: Add detection for 14 3D Construction Kit shareware

common/array.h, engines/ultima/shared/std/containers.h, test/common/array.h
This replaces the version in the Ultima engine.
=> COMMON: Add a version of Common::Array::resize with a fill value

engines/neverhood/menumodule.cpp, engines/neverhood/modules/module1000.cpp, engines/neverhood/modules/module2200.cpp, engines/neverhood/modules/module2200.h
=> NEVERHOOD: Improve support of Japanese version

doc/docportal/help/faq.rst
This is the result of a Discord discussion in `#teamtalk`, especially in relation to fan upscales.
=> DOCS: Adding FAQ item about fanmade mods

engines/ags/lib/std/set.h
This removes the need for items to implement equality operators and adds a way to erase an item directly in a way similar to stl set.
=> AGS: improve std::set replacement

engines/hpl1/engine/libraries/newton/Newton.cpp, engines/hpl1/engine/libraries/newton/Newton.h, engines/hpl1/engine/libraries/newton/core/dgGoogol.cpp, engines/hpl1/engine/libraries/newton/core/dgList.h, engines/hpl1/engine/libraries/newton/core/dgTree.h, engines/hpl1/engine/libraries/newton/physics/dgCollisionCompoundBreakable.cpp, engines/hpl1/engine/libraries/newton/physics/dgMeshEffect.h, engines/hpl1/engine/libraries/newton/physics/dgMinkowskiConv.cpp, engines/hpl1/engine/libraries/newton/physics/dgNarrowPhaseCollision.cpp, engines/hpl1/engine/libraries/newton/physics/dgWorld.cpp, engines/hpl1/engine/libraries/newton/physics/dgWorldDynamicUpdate.cpp
Fixes build failures caused by pull #4557
=> HPL1: Fix VS C2807 errors caused by change of int32 to long.

engines/scumm/sound.cpp
See [Trac#13887](https://bugs.scummvm.org/ticket/13887).
In Indy3 **Macintosh**, if you ring the boxing bell right at the start of the game, you'll see Indy hit it 3 times, but the actual bell sound will only be heard twice. This doesn't happen in the original interpreter (checked against my B&W G3 running OS9) or in the other releases where it can be heard 3 times as expected.
The byte at offset 26 might be responsible for this, in that if it's unset, the current (identical?) sound is maybe meant to be interrupted (the code currently completely ignores this byte). This is just based on the Indy3 Amiga fixes brought by PR #3598 (see [1]) and from some naive guesswork.
I've tested it with a couple of old saves I have; I can't see any regression, and this code only impacts Indy3 Macintosh …
=> SCUMM: Fix a couple of sound issues in Indy3 Macintosh (Trac#13887)

engines/queen/detection.cpp
This PR applies the following changes to the FOTAQ detection:
* Change detection entries of the Floppy ENG and the Floppy RUS (that had the same checksum/size) to TAILMD
* Update the extra field to show "CD" or "GOG" instead of "Talkie", for consistency with the other engines
=> QUEEN: Fix clash in detection and change Talkie->CD

NEWS.md
=> NEWS: Backfill entries related to my improvements

engines/petka/detection_tables.h, engines/petka/petka.cpp, engines/petka/petka.h
This PR adds support for the compressed (not installed) versions of Red Comrades 1-2
Also changes the game titles to the correct Cyrillic title, since these games are Russian-only
and no translations are available it makes sense to keep the original titles in the launcher.
Fixes TRAC [11985](https://bugs.scummvm.org/ticket/11985)
=> PETKA: Add support for compressed Red Comrades 1-2

engines/agos/detection.cpp, engines/gnap/detection.cpp, engines/hugo/detection.cpp, engines/illusions/detection.cpp, engines/lilliput/detection.cpp, engines/myst3/detection.cpp, engines/sword25/detection.cpp
The PR fixes some minor issues with game titles (such as using "2" instead of "II")
and completes partial tiles using Mobygames as reference.
"Gnap" is the only significant change, which is changed to "U.F.O.s" which is the common
title used in the US and in the EU outside Germany.
=> Small fixes/improvements to some game titles

NEWS.md
I figured news should mention the user-noticeable changes since last release.
Are these good entries?
=> NEWS: Mention notable changes for Ultima 8

engines/saga/resource.h
=> SAGA: Correctly handle the case of missing patch file.

engines/saga/resource.cpp
Now the file handle is shared among the readers of the same context, so closing it will close it for all user which leads to a crash.
=> SAGA: Don't close file even after it was overriden by a patch

common/macresman.cpp, engines/saga/resource.h
=> SAGA: Fixes for IHNM and ITE after switch to common macbinary parser

engines/saga/detection_tables.h, engines/saga/saga.cpp
=> SAGA: Support ite demo 3 without unpacking it.

engines/director/images.cpp
=> DIRECTOR: Fix visual regression in D3 with bitmap compression detection

backends/graphics/surfacesdl/surfacesdl-graphics.cpp, backends/graphics/surfacesdl/surfacesdl-graphics.h, backends/module.mk, backends/platform/sdl/opendingux/build_odbeta.sh, backends/platform/sdl/opendingux/opendingux.mk, backends/vkeybd/virtual-keyboard-gui.cpp, base/main.cpp, configure, dists/opendingux/startGame.rs90.desktop, dists/opendingux/startUI.rs90.desktop, graphics/VectorRendererSpec.cpp, graphics/surface.cpp, graphics/surface.h, gui/ThemeEngine.cpp
This improves rg99 support and add rs90.
It uses one combined package for both of them
=> RS90: Add support for RS90 and improve support for RG99

backends/graphics/surfacesdl/surfacesdl-graphics.cpp, backends/platform/sdl/opendingux/build_miyoo.sh, backends/platform/sdl/opendingux/miyoo.mk, backends/platform/sdl/opendingux/opendingux.cpp, configure, dists/opendingux/scummvm.miyoo
This adds support for 1st gen Miyoo devices. Tested on Powkiddy V90
=> OPENDINGUX: Add miyoo (1st gen) support

engines/scumm/imuse_digi/dimuse_internalmixer.cpp
Fixes https://bugs.scummvm.org/ticket/14026
=> SCUMM: FT: Fix unitialized stream in low latency mode

common/compression/unarj.cpp, common/compression/unarj.h, common/compression/unzip.cpp, common/compression/unzip.h, engines/saga/detection_tables.h, engines/saga/saga.cpp
=> SAGA: Support ITE windows demo 1 and 2

backends/graphics/openglsdl/openglsdl-graphics.cpp, backends/graphics/openglsdl/openglsdl-graphics.h, backends/graphics/sdl/sdl-graphics.cpp, backends/graphics/sdl/sdl-graphics.h, backends/graphics/surfacesdl/surfacesdl-graphics.cpp, backends/graphics/surfacesdl/surfacesdl-graphics.h, backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp, backends/graphics3d/openglsdl/openglsdl-graphics3d.h, base/main.cpp, common/system.h, engines/ags/engine/gfx/ali_3d_scummvm.cpp, engines/engine.cpp, engines/hpl1/engine/impl/LowLevelGraphicsSDL.cpp, engines/hpl1/engine/impl/low_level_graphics_tgl.cpp, gui/options.cpp
Some additional refactoring has also been done to make the VSync feature match the others.
=> SDL: Support VSync with OpenGL in SDL1 builds

backends/graphics/surfacesdl/surfacesdl-graphics.cpp
=> SDL: Add missing init of _prevCursorNeedsRedraw

backends/graphics/opendingux/opendingux-graphics.cpp, backends/graphics/opendingux/opendingux-graphics.h, backends/graphics/surfacesdl/surfacesdl-graphics.cpp, backends/graphics/surfacesdl/surfacesdl-graphics.h, backends/module.mk, backends/platform/sdl/opendingux/opendingux.cpp
=> Move RS90-specific code to opendingux directory

engines/ags/engine/ac/dialog.cpp, engines/ags/engine/ac/game.cpp, engines/ags/engine/ac/mouse.cpp, engines/ags/engine/ac/timer.cpp, engines/ags/shared/core/def_version.h
This PR continues the task to incorporate AGS upstream commits
From https://github.com/adventuregamestudio/ags/commit/cf49501a18b48767184e5f3d5da355405e29ad9e
up to https://github.com/adventuregamestudio/ags/commit/0f5c6178ac07b96f0703b35334d77f83977d43fd (not included)
Includes fix for trac [13828](https://bugs.scummvm.org/ticket/13828)
SKIPPED COMMITS:
18492820b7f6763e03c0daa064accf52ab8b6a1e
APEG: provided a break in case the OggS start was not found in file  
(scummvm does not use apeg)
ffa414d615d230be38f98e2e7f0f99393da2eee5
Fixed build numbers everywhere
(already done in previous commit)
5742cda12958e9eb4138e246d958d48bfff8b419
Engine: fixed a typo, which made window toggle shift + enter
(already fixed in scummvm)
3990ab6d533bb101fad5cfc267b6faa88c1f189c
Engine: fixed listing saves …
=> AGS: Incorporate some commits from upstream

engines/neverhood/diskplayerscene.cpp, engines/neverhood/gamemodule.cpp, engines/neverhood/gamemodule.h, engines/neverhood/messages.h, engines/neverhood/modules/module1000.cpp, engines/neverhood/modules/module2200.cpp, engines/neverhood/neverhood.cpp, engines/neverhood/neverhood.h, engines/neverhood/resourceman.cpp, engines/neverhood/resourceman.h, engines/neverhood/smackerplayer.cpp, engines/neverhood/sprite.cpp, engines/neverhood/subtitles.cpp, engines/neverhood/subtitles.h
=> NEVERHOOD: various small improvements

engines/director/castmember.cpp, engines/director/castmember.h, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-object.cpp, engines/director/lingo/lingo.cpp, engines/director/resource.cpp, engines/director/stxt.cpp, engines/director/stxt.h, engines/director/window.cpp, engines/director/window.h
=> DIRECTOR: Fix normaliseXLibName for kPlatformWindows

gui/widgets/grid.cpp
For the extra overlay, try to load a .svg first and if not available fallback on png.
New .svg already uploaded here https://github.com/scummvm/scummvm-icons/pull/312
=> GUI: Add SVG loading for extras overlay

engines/neverhood/menumodule.cpp, engines/neverhood/menumodule.h, engines/neverhood/resourceman.cpp, engines/neverhood/resourceman.h
=> Fixes for japanese neverhood

backends/platform/3ds/3ds.mk
.cia supports version only in form X.Y.Z so just put there MAJOR.MINOR.PATCH
=> 3DS: Specify version in .cia metadata

devtools/README, devtools/dumper-companion.py
Error was in line 686: NameError: name 'io' is not defined. Did you mean: 'id'?
After this fix, the script seems to complete successfully with the createmacfonts parameters, and a non-empty classicmacfonts.dat file is created.
=> DEVTOOLS: COMPANION: Fix python error for createmacfonts

backends/platform/ios7/ios7_osys_video.mm, backends/platform/ios7/ios7_video.h, backends/platform/ios7/ios7_video.mm, configure, devtools/create_project/xcode.cpp, ports.mk
=> IOS7: Add support for 32 bit pixel formats 

backends/platform/ios7/ios7_osys_video.mm, backends/platform/ios7/ios7_video.h, backends/platform/ios7/ios7_video.mm, configure, devtools/create_project/xcode.cpp, ports.mk
=> Ls backport 32bit

backends/graphics/surfacesdl/surfacesdl-graphics.cpp
Hotspot was not correctly taken into account when it changed.
Calculations are simplified and only done in one place.
=> SURFACESDL: Really fix mouse dirty rectangle

base/main.cpp
Instantiating GUI manager takes care of the language selection
=> ANDROID: Do language selection before early popup

engines/director/cast.cpp, engines/director/cast.h, engines/director/castmember.cpp, engines/director/lingo/lingo-codegen.cpp, engines/director/lingo/lingo-codegen.h, engines/director/lingo/lingo-preprocessor.cpp, engines/director/lingo/lingo.cpp, engines/director/lingo/lingo.h, engines/director/score.cpp, engines/director/types.h
=> DIRECTOR: Fixes for Wrath of the Gods

graphics/blit-scale.cpp
Fixes Visual Studio C4146 warning on negation of an unsigned integer.
=> GRAPHICS: Fix negation of unsigned integer warning

engines/testbed/testbed.cpp, engines/testbed/testbed.h, engines/testbed/video.cpp, engines/testbed/video.h
This allows it to be easily used on platforms without convenient command line access.
=> TESTBED: Add a test suite for the video player

graphics/surface.cpp
This change makes Surface::copyFrom() slightly slower but Surface::copyRectToSurface() performs better for rectangles with the same width as the surface.
And of course we avoid unnecessary code duplication.
=> GRAPHICS: Refactor Surface::copyFrom() & Surface::copyRectToSurface

engines/ngi/metaengine.cpp
=> NGI: Remove parts that overlap with ExtendedSaves

AUTHORS, devtools/credits.pl, doc/docportal/help/credits.rst, gui/credits.h
This adds myself as the current OSX PPC maintainer.
Only using a smaller nickname on purpose here; please always keep it this way.
As a PR to be sure I'm not missing anything :)
=> CREDITS: Add dwa for macOS PPC

common/ustr.cpp, common/ustr.h, test/common/str.h
Hey! This adds replace() methods for U32String.
=> COMMON: Add replace() methods for U32String

engines/sherlock/detection_tables.h, engines/sherlock/fixed_text.cpp, engines/sherlock/fonts.cpp, engines/sherlock/fonts.h, engines/sherlock/image_file.cpp, engines/sherlock/journal.cpp, engines/sherlock/journal.h, engines/sherlock/scalpel/scalpel_fixed_text.cpp, engines/sherlock/scalpel/scalpel_journal.cpp, engines/sherlock/scalpel/scalpel_journal.h, engines/sherlock/scalpel/scalpel_screen.cpp, engines/sherlock/scalpel/scalpel_screen.h, engines/sherlock/scalpel/scalpel_talk.cpp, engines/sherlock/scalpel/scalpel_user_interface.cpp, engines/sherlock/scalpel/scalpel_user_interface.h, engines/sherlock/scalpel/settings.cpp, engines/sherlock/scalpel/settings.h, engines/sherlock/talk.cpp, engines/sherlock/tattoo/widget_base.cpp, engines/sky/sky.cpp, engines/sky/sky.h, engines/sky/text.cpp, graphics/big5.cpp, graphics/big5.h, graphics/module.mk
=> SHERLOCK: Support Chinese serrated scalpel

backends/fs/android/android-posix-fs.cpp, backends/fs/android/android-posix-fs.h, backends/fs/android/android-saf-fs.cpp, backends/fs/android/android-saf-fs.h, backends/platform/android/android.cpp, backends/platform/android/org/scummvm/scummvm/SAFFSTree.java
And create a specific save manager which uses this new ability to delete saves.
This makes deleting saves on SAF possible.
=> ANDROID: Add ability to delete files

backends/platform/android/android.cpp, backends/platform/android/android.h, backends/platform/android/jni-android.cpp, backends/platform/android/jni-android.h, backends/platform/android/org/scummvm/scummvm/ScummVM.java, backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java
Do not pass arguments to the process but customize the backend instead.
=> ANDROID: Simplify Android startup

engines/grim/detection.cpp, engines/grim/emi/lua_v2.cpp, engines/grim/font.cpp, engines/grim/font.h, engines/grim/gfx_opengl.cpp, engines/grim/gfx_opengl_shaders.cpp, engines/grim/gfx_tinygl.cpp, engines/grim/grim.cpp, engines/grim/localize.cpp, engines/grim/lua.cpp, engines/grim/lua_v1.cpp, engines/grim/md5check.cpp, engines/grim/remastered/lua_remastered.cpp, engines/grim/resource.cpp, engines/grim/savegame.cpp, engines/grim/textobject.cpp
We require the user to run the translation patcher in advance themselves
=> GRIM: Support Chinese Fan translation

backends/graphics/surfacesdl/surfacesdl-graphics.cpp
Current code results in a crash
=> SDL: Fix shaking with SDL1 and negative offsets

engines/testbed/config.cpp, engines/testbed/config.h
The Testbed used ListWidget and double-clickable text to select options, which is illogical and unfriendly for users. Now they are replaced with ScrollContainerWidget and CheckboxWidget.
=> TESTBED: Switch to CheckboxWidgets for Testbed

engines/grim/detection.cpp, engines/grim/emi/sound/vimatrack.cpp, engines/grim/emi/sound/vimatrack.h, engines/grim/gfx_opengl.cpp, engines/grim/imuse/imuse.cpp, engines/grim/imuse/imuse_mcmp_mgr.cpp, engines/grim/imuse/imuse_mcmp_mgr.h, engines/grim/imuse/imuse_sndmgr.cpp, engines/grim/imuse/imuse_sndmgr.h, engines/grim/localize.cpp, engines/grim/md5check.cpp, engines/grim/movie/codecs/smush_decoder.cpp, engines/grim/movie/codecs/vima.cpp, engines/grim/movie/codecs/vima.h, engines/grim/resource.cpp
=> GRIM: Add support for Russian translation (7Wolf)

engines/grim/localize.cpp, engines/grim/textobject.cpp
=> GRIM: Add support for Russian Translation (ENPY)

engines/grim/detection.cpp, engines/grim/md5check.cpp
=> GRIM: Support Fargus translation

engines/sword2/detection.cpp, engines/sword2/detection_tables.h, engines/sword2/header.cpp, engines/sword2/header.h, engines/sword2/maketext.cpp, engines/sword2/maketext.h, engines/sword2/object.h, engines/sword2/screen.h, engines/sword2/sword2.cpp
=> SWORD2: Support Chinese translation

engines/director/director.h, engines/director/util.cpp, engines/director/util.h
- Added a function `MachineType()` which will look up the max resolution and max depth for the specified machine.
=> GUI:Added function setMachineType() which will look up the max resolution and max depth for the specified machine

common/archive.cpp, common/archive.h, common/compression/clickteam.cpp, common/compression/clickteam.h, common/compression/gzio.cpp, engines/scumm/detection.h, engines/scumm/detection_internal.h, engines/scumm/detection_tables.h, engines/scumm/scumm.cpp
=> SCUMM: Support playing most RuSCUMM-translated games without patching manually

engines/director/resource.cpp
This pull adds a ProjectorArchive class which can be used to extract various DIR files from within a projector.
The code has been adapted from https://github.com/59de44955ebd/unpacker.py/blob/main/unpacker.py
=> DIRECTOR: Add ProjectorArchive

devtools/create_ultima/files/ultima6/scripts/u6/intro.lua
Requires regeneration of ultima.dat
Fixes [#11478](https://bugs.scummvm.org/ticket/11478) and [#12697](https://bugs.scummvm.org/ticket/12697)
=> NUVIE: Fix Ultima 6 main menu input lag

engines/voyeur/animation.h, engines/voyeur/detection_tables.h, engines/voyeur/events.cpp, engines/voyeur/files.cpp, engines/voyeur/files.h, engines/voyeur/files_threads.cpp, engines/voyeur/screen.cpp, engines/voyeur/staticres.cpp, engines/voyeur/staticres.h, engines/voyeur/voyeur.cpp, engines/voyeur/voyeur_game.cpp
The purpose of this PR is to add support to the German fan-made version made by Bakhtosh.
This variant is based on the buggy CDi German version and their patch produces a stable German DOS version.
http://bakhtosh.bplaced.net/?page_id=27
Most of the code modified in ScummVM is also Baktosh's legacy
=> VOYEUR - Support for the German DOS Fan-Made version

engines/asylum/system/text.cpp
=> ASYLUM: Decrease Chinese font size to 16 closer to original

engines/grim/font.cpp, engines/grim/font.h
It's buggy and results in a crash. Additionally it's not necessarry.
=> GRIM: Remove Chinese font scaling

engines/grim/font.cpp
=> GRIM: Fix handling of single-byte character in DBCS font

engines/sherlock/detection_tables.h, engines/sherlock/fonts.cpp, engines/sherlock/tattoo/tattoo_fixed_text.cpp
=> SHERLOCK: Use more accurate ZH_CHN rather than ZH_ANY for Rose Tattoo

engines/director/lingo/xlibs/fileio.cpp
Verified with FILEIO.C. Redo of 4a2aeb1d2194b0730434cb7cfbba8b7465a66b61
=> DIRECTOR: LINGO: FileIO uses CR endings cross-platform

devtools/generate-appdata.py, dists/scummvm.appdata.xml
This PR adds a script to support multilanguage in scummvm.appdata.xml. The multilanguage data is extracted from po/*.po files.
Related Discord discussion: https://discord.com/channels/581224060529148060/1086942326489895033/1086976457311531058
=> I18N: Add script to automatically generate scummvm.appdata.xml from .po files

devtools/generate-appdata.py
A quick fix to fix export file name in PR: https://github.com/scummvm/scummvm/pull/4826
=> I18N: Fix appdata file name in translation script

backends/fs/chroot/chroot-fs-factory.cpp, backends/fs/chroot/chroot-fs-factory.h, backends/fs/chroot/chroot-fs.cpp, backends/fs/chroot/chroot-fs.h, backends/platform/ios7/ios7_osys_main.cpp, backends/platform/ios7/ios7_osys_main.h, backends/platform/ios7/ios7_osys_misc.mm, backends/platform/sdl/macosx/macosx.cpp, backends/platform/sdl/macosx/macosx.h, backends/platform/sdl/macosx/macosx_osys_misc.mm, backends/platform/sdl/macosx/macosx_wrapper.h, backends/platform/sdl/macosx/macosx_wrapper.mm, backends/platform/sdl/module.mk, base/commandLine.cpp, base/main.cpp, common/system.cpp, common/system.h, doc/docportal/advanced_topics/autostart.rst
This pull request simplify creating game bundles on macOS.
It takes two of the recent additions and adapt them to be more platform-aware, with macOS custom implementations.
- PR #4586
- Auto-run mode added in commits 6cb1c7d and 399285b.
It also makes some adjustment to the macOS backend to better support game bundles.
Most of the changes here should also be easily transferable to the iOS backend. And other backends could also possibly have a different customised experience.
In details:
1. It introduces a new `updateStartSettings()` method in `OSystem` that is called after command line parameters have been parsed, but before processing them. This way backends can customise the start command and settings.
2. The auto-run code is moved to the default implementation of this new method.
3. On …
=> Backend specific start sequence

graphics/managed_surface.cpp, graphics/managed_surface.h
This is a follow up to PR #4541.
=> GRAPHICS: Use standard palettes in ManagedSurface

audio/mods/impulsetracker.cpp, audio/mods/impulsetracker.h, audio/module.mk, configure, engines/sludge/sound.cpp, engines/testbed/sound.cpp
Changes
1. Added libmikmod compilation and scripts to configure!
2. Impulse tracker mod wrappers in audio/mods!
3. Testbed engine updated to support .it files playback!
4. Sludge engine sound updated to add support for impulse tracker files!
=> SLUDGE: Added support for impulse tracker files using libmikmod!

engines/ultima/nuvie/core/egg_manager.cpp, engines/ultima/nuvie/core/obj_manager.cpp
Change NPC and object spawn probability and count to match original behavior.
=> NUVIE: Fix Ultima 6 spawn probability

engines/sci/sound/music.cpp
It is possible in SCI to have a MIDI track which defines _dontRemap twice for the same channel. _dontRemap is needed for devices like the Roland MT-32, where percussion sounds are only available on MIDI channel 10. As such, we must assume that any use of _dontRemap in successsion is legitimate, not just the final use.
Fixes various bits of music in pq1sci when played back on the MT-32 (e.g. the musical transition after handing the ticket to the woman, followed by the music when driving in the car).
=> SCI: Fix _dontRemap handling in SciMusic::soundInitSnd

gui/options.cpp
Fixes some signed/unsigned mismatch regressions from cf578e832b92918c692175e787c96f5be88d3562
=> GUI: Fix signed/unsigned mismatches

engines/mm/mm1/data/items.cpp, engines/mm/mm1/data/items.h, engines/mm/mm1/game/equip_remove.cpp, engines/mm/mm1/game/equip_remove.h, engines/mm/mm1/game/use_item.cpp, engines/mm/mm1/game/use_item.h, engines/mm/mm1/maps/map27.cpp, engines/mm/mm1/views/locations/temple.cpp, engines/mm/mm1/views_enh/locations/temple.cpp
rename some item parameters.
Add function to change a character parameter if an item is equipped or removed
Add function to change a character parameter if an item is used
=> MM: MM1: Items data update

graphics/VectorRenderer.cpp
=> GUI: Fix draw-size computation

video/qt_decoder.cpp, video/qt_decoder.h
Please review the changes, divided into two commits!
=> VIDEO: Quicktime multiple edit reverse playback and custom rate!

graphics/VectorRenderer.cpp, graphics/VectorRenderer.h, graphics/VectorRendererSpec.cpp, graphics/VectorRendererSpec.h, gui/ThemeParser.cpp
Decrease the number of rendered shadow rectangles under HiDPI
- Introduce `shadowIntensity` (encoded using 16 bits mantissa) which indicates the interval for drawing shadow rectangles
=> GUI: Fix hard shadow under HiDPI rendering

graphics/font.cpp, graphics/font.h, graphics/fonts/bdf.cpp, graphics/fonts/macfont.cpp
- The primary change is to fix or improve the scaling of BDF fonts
- Now uses the same approach as in MacFonts scaling
- Bugs - there are still some problems when testing in capital letters
- Note: the change in graphics.cpp for the testbed engine now calls the scale font function.
=> GUI: Change in the BDF fonts scaling code

engines/scumm/script.cpp
This PR implements a mod for competitive online Backyard Baseball 2001 play: enables random bounces to work as they do offline. In offline play on certain fields (Dirt Yards, Playground Commons, and a few others), ground balls bounce in random directions. This makes grounder and line drive based offensive play more viable, adds another challenge for the defensive player, and gives the different fields more uniqueness and personality.
=> SCUMM HE: BB01 competitive online play: random bounces

engines/director/detection_tables.h, engines/director/game-quirks.cpp, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-object.cpp, engines/director/lingo/lingo-patcher.cpp, engines/director/lingo/tests/equality.lingo, engines/director/lingo/xlibs/applecdxobj.cpp, engines/director/lingo/xlibs/barakeobj.cpp, engines/director/lingo/xlibs/fplayxobj.cpp, engines/director/lingo/xlibs/fplayxobj.h, engines/director/lingo/xlibs/hitmap.cpp, engines/director/lingo/xlibs/hitmap.h, engines/director/lingo/xlibs/miscx.cpp, engines/director/lingo/xlibs/prefpath.cpp, engines/director/lingo/xlibs/prefpath.h, engines/director/lingo/xlibs/printomatic.cpp, engines/director/lingo/xlibs/printomatic.h, engines/director/lingo/xlibs/stagetc.cpp, engines/director/lingo/xlibs/stagetc.h, engines/director/lingo/xlibs/valkyrie.cpp, engines/director/lingo/xlibs/valkyrie.h, engines/director/lingo/xlibs/xio.cpp, engines/director/module.mk, engines/director/resource.cpp
I've tried to group the commits as much as I could.
=> DIRECTOR: More detection entries and other things

.github/workflows/ci.yml, devtools/create_project/create_project.cpp, devtools/create_project/create_project.h, devtools/create_project/xcode.cpp, devtools/create_project/xcode.h, doc/docportal/other_platforms/ios.rst, doc/docportal/other_platforms/tvos.rst
The scummvm-ios7-libs-v3 packages the pre-built static libraries into xcframeworks, allowing to have arm64 libraries for both iPhoneOS and iPhoneSimulator.
The new scummvm-ios7-libs-v3 contains some new libraries compared to the v2-libs:
- faad
- gif
- mpeg2
- theoradec
- vex
Update the instructions using the scummvm-ios7-libs-v3.
The scummvm-ios7-libs-v3 can be downloaded at https://github.com/larsamannen/scummvm-ios7-libs-v3/blob/main/scummvm-ios7-libs-v3.zip
=> Use scummvm-ios7-libs-v3

engines/saga/font.cpp
=> SAGA: Fix wrong calculation of Big5 string height

engines/mm/detection_tables.h
=> MM: Mark Chinese Xeen games as using Traditional spelling

gui/gui-manager.cpp
This is something I wanted to fix for a long time: https://bugs.scummvm.org/ticket/14364
Not only it drastically speeds up button and scrolling redraws ~~but it makes tool tips pleasant to watch -- without this patch every tooltip freezes my backend for about 500 ms. You can imagine that user experience, one has to literally run away with mouse to avoid showing tooltips. ;)~~ (EDIT: actually, I got carried away here -- tool tips of course still redraw the background upon closing; I've had another optimization implemented but it's not suitable for a PR yet).
As I'm not a GUI expert, putting this for review whether I haven't overlooked something obvious.
From what I could see, there is only one potential risk: if there is a dialog which has the Apply button which updates something in the …
=> GUI: Don't redraw whole dialog stack with kRedrawTopDialog

engines/lastexpress/entities/chapters.cpp, engines/lastexpress/entities/entity.cpp, engines/lastexpress/game/entities.cpp, engines/lastexpress/game/savegame.cpp, engines/lastexpress/game/savegame.h, engines/lastexpress/game/scenes.cpp, engines/lastexpress/game/state.h, engines/lastexpress/lastexpress.cpp, engines/lastexpress/lastexpress.h, engines/lastexpress/menu/clock.cpp, engines/lastexpress/menu/menu.cpp, engines/lastexpress/metaengine.cpp, engines/lastexpress/resource.cpp, engines/lastexpress/resource.h, engines/lastexpress/shared.h, engines/lastexpress/sound/entry.cpp
Changes in this PR:
- Added support for naming the saved games based on game target, listing saved games and loading from launcher, and removing saved games.
- Fixed a few compiler warnings about uninitialized variables.
- Fixed a bad array initialization for 39 instead of 40 entities.
- Early support for the demo (not crashing on launch, proper menu text)
=> LASTEXPRESS: Save system updates, a few warnings fixed and early demo support

gui/cloudconnectionwizard.cpp
=> GUI: Correct some grammar in the cloud connection wizard

engines/saga/font.cpp
Without this fix it cuts last character of the line which is a space in Western languages but a drawable character in Chinese
=> SAGA: Fix word-wrapping bug

graphics/big5.h
=> GRAPHICS: Fix default bpp value for drawBig5Char

engines/sherlock/scalpel/scalpel_talk.cpp, engines/sherlock/scalpel/scalpel_user_interface.cpp
=> SHERLOCK: Fix lines displayed out of visible space

backends/platform/ios7/ios7_gamepad_controller.h, backends/platform/ios7/ios7_gamepad_controller.mm, backends/platform/ios7/ios7_options.mm, backends/platform/ios7/ios7_osys_events.cpp, backends/platform/ios7/ios7_osys_main.cpp, backends/platform/ios7/ios7_osys_main.h, backends/platform/ios7/ios7_osys_video.mm, backends/platform/ios7/ios7_video.h, backends/platform/ios7/ios7_video.mm, backends/platform/ios7/module.mk, po/POTFILES
Implement use of port specific options widget which may be used to enable/disable mouse modes.
Also implement support of Virtual controller (onscreen controls) with one configuration with a dPad and A and B buttons.
=> IOS7: Implement port specific options widget

engines/director/detection_tables.h
=> DIRECTOR: Correct spelling mistake pointed out by kane159

devtools/dumper-companion.py
=> DUMPER-COMANION: Fix compatibility with python 3.8

engines/ultima/detection_tables.h
Detect unofficial French translation patch by Docwise Dragon.
Fixes [#14451](https://bugs.scummvm.org/ticket/14451)
=> ULTIMA: Add detection entry for French Ultima 6

engines/director/archive.cpp, engines/director/cast.cpp
Note: this doesn't add support for D6, only improves error message
=> DIRECTOR: Fix abort with director 6

engines/scumm/charset.cpp, engines/scumm/charset.h
Some spacing fixes may still needed though to get it pixel-perfect but it looks already good enough
=> SCUMM: Fix Mojibake in Japanese Macintosh atlantis

common/dbcs-str.cpp, common/dbcs-str.h, common/module.mk, common/str-base.cpp, engines/grim/detection.cpp, engines/grim/font.cpp, engines/grim/font.h, engines/grim/grim.cpp, engines/grim/grim.h, engines/grim/localize.cpp, engines/grim/resource.cpp, engines/grim/textobject.cpp, engines/grim/textobject.h
=> GRIM: Support Chinese Monkey4

engines/sky/detection.cpp
=> SKY: Show only available language in language selection

engines/director/cast.cpp, engines/director/castmember/bitmap.cpp, engines/director/castmember/bitmap.h, engines/director/detection_tables.h, engines/director/movie.cpp, engines/director/palette-fade.h, engines/director/score.cpp, engines/director/sound.cpp, engines/director/sound.h
=> DIRECTOR: Fixes for D5/The Cute machine

common/macresman.cpp, common/macresman.h, engines/scumm/charset.cpp, engines/scumm/detection_internal.h, engines/scumm/file.cpp, engines/scumm/file.h, engines/scumm/file_nes.cpp, engines/scumm/he/sound_he.cpp, engines/scumm/imuse_digi/dimuse_bndmgr.cpp, engines/scumm/imuse_digi/dimuse_bndmgr.h, engines/scumm/imuse_digi/dimuse_sndmgr.cpp, engines/scumm/insane/insane.cpp, engines/scumm/nut_renderer.cpp, engines/scumm/players/player_he.cpp, engines/scumm/resource.cpp, engines/scumm/scumm.cpp, engines/scumm/smush/smush_player.cpp, engines/scumm/sound.cpp, engines/scumm/string.cpp
=> SCUMM: Support playing MAC games dumped with --forcemacbinary or similar options

engines/twine/resources/resources.cpp, engines/twine/resources/resources.h, engines/twine/text.cpp, engines/twine/text.h
=> TWINE: Support rendering Japanese strings

engines/director/archive.cpp, engines/director/resource.cpp
This reverts commit 036297b605dbaf4894a3ea2c560d99a53e84c092. Then it solves the same problem in a way that is more compliant with how similar code is written in this engine thus avioding accidentally introduced memory leak.
=> DIRECTOR: Redo "Fix use-after-free"

engines/mm/xeen/worldofxeen/clouds_cutscenes.cpp
This commit fixes access to Graphics::ManagedSurface.
There is a new crash in this cutscene in later stage.
This is the same diff as in https://github.com/scummvm/scummvm/pull/4992
Ticket https://bugs.scummvm.org/ticket/14431
=> XEEN: Fix crash in MM4 ending cutscene

common/bitarray.h, engines/hypno/hypno.h, engines/hypno/wet/hard.cpp, engines/hypno/wet/wet.cpp
=> HYPNO: Implement rendering of Korean font

.gitignore, gui/dump-all-dialogs.cpp, gui/dump-all-dialogs.h, gui/module.mk
- Each resolution needs to be cycled manually in the code, default is 800x640.
- Dumps .png files in the root folder for all languages at a given resolution.
TODO:
- Cycle resolutions automatically through code.
=> GUI: Dump .png files of the launcher to check UI for various translations

engines/sludge/detection_tables.h
I've double checked the version, and did not found v0.1
=> SLUDGE: Add detection for v 1.0 outoforder 

image/codecs/bmp_raw.cpp
Most engines already convert the image to the current screen format after loading, so this avoids intermediate conversions and allows reading entire rows in one go.
=> IMAGE: Speed up 16/24/32bpp BMP decoding

devtools/dumper-companion.py
This allows to easily simulate behaviour of other dumping tools. It's very useful in tests wven if not so much for end users
=> DEVTOOLS: Allow to add .bin extension in dumper-companion.

engines/ags/module.mk, engines/ags/plugins/ags_collision_detector/ags_collision_detector.cpp, engines/ags/plugins/ags_collision_detector/ags_collision_detector.h, engines/ags/plugins/plugin_base.cpp
This PR adds a barebones implementation of the AGS Collision Detector plugin (only the sprite-sprite collision detection
is implemented).
The plugin was used for Bear Story, which now is playable and completable, and a few other games.
The variable names and defines are taken from the original plugin documentation.
=> AGS: Partial implementation of AGS_Collision_Detector plugin

engines/mm/xeen/dialogs/dialogs_items.cpp
https://bugs.scummvm.org/ticket/14428
=> XEEN: show class restriction icons in shops

graphics/sjis.cpp, graphics/sjis.h
=> GRAPHICS: Support PC98 font ROM

graphics/sjis.cpp
=> GRAPHICS: Fix glyph offsets for PC98 glyphs *9e

common/macresman.cpp
=> COMMON: Fix logic error in macresman

engines/bladerunner/bladerunner.cpp, engines/bladerunner/detection.cpp, engines/bladerunner/slice_animations.cpp
Right now we ask user to reshuffle files. After this commit it's possible to just merge contents of all CDs.
=> BLADERUNNER: Support merging of CDs in original layout.

engines/bladerunner/text_resource.cpp
=> BLADERUNNER: Add assertion for undershort files

engines/sci/detection_tables.h
=> SCI: Add Md5 of Another variant of Hebrew Laura Bow

engines/queen/detection.cpp
=> QUEEN: Add another FOTAQ MD5

engines/saga/resource.cpp
Fixes [#14334](https://bugs.scummvm.org/ticket/14334)
=> SAGA: Fix memory and file handle leak in loadResource

engines/director/lingo/xlibs/popupmenuxobj.cpp, engines/director/lingo/xlibs/popupmenuxobj.h, graphics/macgui/macmenu.cpp, graphics/macgui/macmenu.h, graphics/macgui/macpopupmenu.cpp, graphics/macgui/macpopupmenu.h, graphics/macgui/macwindowmanager.cpp, graphics/macgui/macwindowmanager.h, graphics/module.mk
Base work #4214 , Some more work done:
1. More functions in macpopup class for better abstraction.
2. Finding last selected, active item in macmenu.
3. Implement mPopText and mPopNum in xlib object.
=> DIRECTOR: Improve popupxmenulib

common/stablemap.h
Hey, this fixes the operator[] of StableMap.
=> COMMON: Fix operator[] of StableMap

engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-object.cpp, engines/director/movie.cpp, engines/director/window.cpp, engines/director/window.h, graphics/macgui/mactextwindow.cpp, graphics/macgui/mactextwindow.h, graphics/macgui/macwindow.cpp, graphics/macgui/macwindow.h
=> DIRECTOR: Set `rect` property of window, allow dynamic resize/move.

common/algorithm.h, test/common/algorithm.h
This adds the equivalent of `std::remove()` to `Common/algorithm.h`
The code for the same has been adapted from llvm.
=> COMMON: Add remove() to algorithm

engines/director/lingo/lingo-object.cpp, engines/director/window.cpp, engines/director/window.h, graphics/macgui/macwindow.cpp, graphics/macgui/macwindow.h, graphics/macgui/macwindowmanager.cpp, graphics/macgui/macwindowmanager.h
Self-explanatory.
Base work from #4114
=> DIRECTOR: Implement the titleVisible & modal property of window

backends/graphics/surfacesdl/surfacesdl-graphics.cpp
This avoids artefacts on borders when using scalers like AdvMame.
This fixes bug [#14308](https://bugs.scummvm.org/ticket/14308)
=> SURFACESDL: Apply the key color in the cursor margins

common/zip-set.cpp, engines/director/archive.cpp, engines/director/cast.cpp, engines/director/cast.h, engines/director/director.cpp, engines/director/director.h, engines/director/game-quirks.cpp, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-bytecode.cpp, engines/director/lingo/lingo-code.cpp, engines/director/lingo/lingo-codegen.cpp, engines/director/lingo/lingo-object.cpp, engines/director/lingo/lingo-object.h, engines/director/lingo/lingo-the.cpp, engines/director/lingo/lingo-utils.h, engines/director/lingo/lingo.cpp, engines/director/lingo/lingo.h, engines/director/lingo/tests/sort.lingo, engines/director/lingo/xlibs/colorxobj.cpp, engines/director/lingo/xlibs/colorxobj.h, engines/director/lingo/xlibs/qtvr.cpp, engines/director/module.mk, engines/director/movie.cpp, engines/director/resource.cpp, engines/director/tests.cpp, engines/director/window.cpp, engines/director/window.h, graphics/macgui/macfontmanager.cpp
=> DIRECTOR: Refactor archive loading

engines/director/detection_tables.h, engines/director/lingo/lingo-object.cpp, engines/director/lingo/xlibs/miscx.cpp
=> DIRECTOR: Fixes for regressions

backends/graphics/opengl/opengl-graphics.cpp, backends/graphics/openglsdl/openglsdl-graphics.cpp, backends/graphics/sdl/sdl-graphics.cpp, backends/graphics/surfacesdl/surfacesdl-graphics.cpp, gui/options.cpp
Also fix compilation with --disable-aspect and remove the checkbox from GUI if the kFeatureAspectRatioCorrection is not supported by the system (or built without it).
=> BACKENDS: GRAPHICS: Implement scaler scrolling for OpenGL

engines/ags/engine/ac/character_info_engine.cpp, engines/ags/engine/script/cc_instance.cpp, engines/ags/engine/util/library.h, engines/ags/engine/util/library_scummvm.h, engines/ags/lib/alfont/alfont.cpp, engines/ags/plugins/ags_plugin.cpp, engines/ags/shared/core/def_version.h, engines/ags/shared/gui/gui_button.cpp
This PR includes the upstream commits up to the latest stable version 3.6.0 Patch 2 (aka 3.6.0.49)
Commit 
[Engine: fixed possible vector idx error in start_character_turning()](https://github.com/adventuregamestudio/ags/commit/fca247a28fe2d0609cdbd71ab734929c1c451f1c)
has been merged already
=> AGS: Commits from upstream up to version 3.6.0.49

engines/director/lingo/lingo.cpp
Fixes a lot of bugs in total distortion!
=> DIRECTOR: Fix comparison between symbol and string

engines/director/lingo/lingo-object.cpp, engines/director/lingo/xlibs/eventq.cpp, engines/director/lingo/xlibs/eventq.h, engines/director/module.mk
Used in meet mediaband, windows version
=> DIRECTOR: Implement EventQ xobject stubs

engines/director/cast.cpp, engines/director/castmember/text.cpp, graphics/fonts/macfont.h, graphics/macgui/mactext.cpp
=> GRAPHICS: MACGUI: Fix alignment issues for multiline text

engines/director/lingo/lingo.cpp, video/video_decoder.cpp, video/video_decoder.h
UnDo me of meet-mediaband (win), is working with all playback controls, rate, etc! Additionally some bugs are also fixed.
=> DIRECTOR & VIDEO: Fully working undome!

doc/docportal/advanced_topics/configuration_file.rst, doc/docportal/advanced_topics/understand_graphics.rst, doc/docportal/settings/keymaps.rst, doc/docportal/use_scummvm/keyboard_shortcuts.rst
Updates the shortcut documented in keyboard shortcuts page from (Ctrl+Alt+1 to 8) to (Ctrl+Alt+ 9 or 0) to cycle through graphical filter scalers.
And removes the shortcut documented in Advanced Settings>Understanding the graphics settings>Graphics Modes, which stated that using the shortcut (Ctrl+Alt+1 to 8) would switch between graphics modes.
Also updates the keymaps page (Settings > keymaps) accordingly.
=> DOCS: Update shortcut for cycling graphic scalers

graphics/font.cpp, graphics/fonts/bdf.cpp
=> Font scaling add

engines/pink/objects/actions/action_text.cpp
=> PINK: Fix Hebrew text encoding.

base/commandLine.cpp, engines/advancedDetector.cpp, engines/advancedDetector.h, engines/glk/detection.h, engines/metaengine.h, engines/scumm/detection.cpp, engines/sky/detection.cpp
`--dump-all-detection-entries` is a command that prints formatted detection entries to STDOUT.
Currently, it works for engines using `AdvancedDetector`, which includes all but 3 engines - Glk, Sky, and SCUMM.
=> BASE: Add --dump-all-detection-entries command

backends/platform/ios7/ios7_app_delegate.h, backends/platform/ios7/ios7_app_delegate.mm, backends/platform/ios7/ios7_common.h, backends/platform/ios7/ios7_options.mm, backends/platform/ios7/ios7_osys_events.cpp, backends/platform/ios7/ios7_osys_main.cpp, backends/platform/ios7/ios7_osys_main.h, backends/platform/ios7/ios7_osys_video.mm, backends/platform/ios7/ios7_scummvm_view_controller.h, backends/platform/ios7/ios7_scummvm_view_controller.mm, backends/platform/ios7/ios7_video.h, backends/platform/ios7/ios7_video.mm
This PR takes the same functionality recently implemented in Android to iOS.
It will allow users to configure a specific screen orientation for launcher and for games (can be set per game as well).
=> IOS7: Add option to set screen orientation

graphics/fonts/bdf.cpp
Instead of doing bbox-to-bbox scales, fill pixels based on distance to a reference coordinate, which ensures the same rounding behavior at each scanline.
It's not great, but it is much more consistent than the old algorithm.
I tried a few different ways of computing the reference coordinate and this seems to produce the best results.
Screenshot:
https://media.discordapp.net/attachments/636495083935629325/1127073104292741221/image.png
=> GRAPHICS: Improve BDF scaling quality.

engines/director/lingo/lingo-object.cpp, engines/director/window.cpp, engines/director/window.h
Some more testing is required before merging, marking draft for now.
=> DIRECTOR: Implement `fileName of window` property

engines/gob/detection/tables_gob1.h
Added russian version of Gobliins 1 (Bugreport #14531)
Adapted to CD by A.P.$lasH
=> GOB: added russian version of Gobliins 1 (Bugreport #14531)

engines/director/score.cpp
Fixes the 0% warning message in The Cute Machine.
=> DIRECTOR: Fix regression where previous frame's tempo is used

backends/platform/android/org/scummvm/scummvm/MultitouchHelper.java
We can receive a move event while having two fingers pressed but this doesn't always mean we really moved.
I took the opportunity to cache the getAction call and properly mask it.
This is the same as calling getActionMasked() though (which is available since API level 8).
=> ANDROID: Make 3 fingers multitouch easier to trigger

engines/director/cast.cpp, engines/director/castmember/filmloop.cpp, engines/director/castmember/filmloop.h, engines/director/frame.cpp, engines/director/frame.h, engines/director/game-quirks.cpp, engines/director/score.cpp, engines/director/sprite.h
=> DIRECTOR: Improvements to frame code

engines/asylum/puzzles/board.cpp, engines/asylum/puzzles/boardkeyhidesto.cpp, engines/asylum/puzzles/boardsalvation.cpp, engines/asylum/puzzles/boardyouth.cpp
Following #4716
This defines the positions of letters for the hebrew (fan translated) version of the board puzzle
Thanks
=> ASYLUM: Add Hebrew board puzzle

devtools/director-generate-xobj-stub.py, engines/director/cast.cpp, engines/director/director.cpp, engines/director/director.h, engines/director/game-quirks.cpp, engines/director/lingo/lingo-mci.cpp, engines/director/lingo/lingo-object.cpp, engines/director/lingo/lingo-the.cpp, engines/director/lingo/xlibs/maniacbg.cpp, engines/director/lingo/xlibs/maniacbg.h, engines/director/module.mk
=> DIRECTOR: Small fixes

engines/director/frame.cpp, engines/director/lingo/lingo-bytecode.cpp, engines/director/lingo/lingo.cpp, engines/director/movie.cpp, engines/director/movie.h
=> DIRECTOR: Add "the member" support for D5

backends/platform/ios7/ios7_gamepad_controller.mm, backends/platform/ios7/ios7_scummvm_view_controller.mm
This PR contains additional fixes for virtual controller for iOS 15 and later
=> IOS7: Virtual controller fixes

common/formats/quicktime.cpp, common/formats/quicktime.h, engines/director/blank-score.h, engines/director/cast.cpp, engines/director/castmember/text.cpp, engines/director/events.cpp, engines/director/lingo/lingo.cpp, engines/director/lingo/xlibs/fileio.cpp, engines/director/lingo/xlibs/fileio.h, engines/director/lingo/xlibs/maniacbg.cpp, engines/director/movie.cpp, engines/director/score.cpp, video/qt_decoder.cpp, video/qt_decoder.h
=> DIRECTOR: Fixes for Maniac Sports and Wallobee Jack

engines/gob/save/saveload_v7.cpp
Added French names of Addy Junior & Addy 4,
fix a typo for breakout.
=> GOB: Fix some comments in saveload_v7

graphics/scaler.h, graphics/scaler/thumbnail_intern.cpp
=> Allow creating thumbnails from a ManagedSurface

backends/networking/curl/connectionmanager.cpp, backends/networking/curl/curlrequest.cpp
Please verify before merging, thanks!
=> CLOUD: Fix some memleaks in CLOUD/NETWORKING code

backends/networking/curl/connectionmanager.cpp
=> CLOUD: Fix memleak in ConnectionManager

engines/ags/module.mk, engines/ags/plugins/ags_consoles/ags_consoles.cpp, engines/ags/plugins/ags_consoles/ags_consoles.h, engines/ags/plugins/plugin_base.cpp
=> AGS: Preliminary implementation of ags_consoles plugin

doc/docportal/settings/misc.rst
Add missing anchor as well as whole of a missing title (reason: description written under the wrong title and that title has no anchor)
=> DOCS: Added missing title for Check update

engines/scumm/resource_v4.cpp
This allows using the official Roland MT-32 patch available from LucasArts (Monkeyup.exe [*]) along with any EGA version by adjusting the sound directory offsets to match the available patch.
[*] More information about the patch available here: https://dwatteau.github.io/scummfixes/corrupted-monkey1-ega-files-limitedrungames.html (See "Bonus: adding the missing Roland Update")
Notes:
- This was tested specifically on the french EGA version, but as the patch is the only one available I think it safe to use the same offsets as long as this specific patch is present. but we might want to test more versions.
- This needs to be categorized it once #5102 is merged, I am not sure which category is appropriate for this
Thank you
=> SCUMM: Make roland patch work with any MI EGA

gui/gui-manager.cpp, gui/gui-manager.h
Basically using unsigned integer difference to address potential errors around the overflow point of getMillis()
=> GUI: Improve time difference checks in gui manager

engines/crab/PathfindingGrid.cpp, engines/crab/PathfindingGrid.h, engines/crab/TMX/TMXMap.cpp, engines/crab/TMX/TMXMap.h, engines/crab/ai/movement.h, engines/crab/animation/AnimationEffect.h, engines/crab/animation/AnimationFrame.cpp, engines/crab/crab.cpp, engines/crab/game.cpp, engines/crab/game.h, engines/crab/input/cursor.h, engines/crab/input/input.h, engines/crab/people/trait.h, engines/crab/rapidxml/rapidxml.hpp, engines/crab/text/color.h, engines/crab/ui/AlphaImage.h, engines/crab/ui/FileData.cpp, engines/crab/ui/HealthIndicator.cpp, engines/crab/ui/Inventory.cpp, engines/crab/ui/MapMarkerMenu.cpp, engines/crab/ui/PersonHandler.cpp
=> CRAB: Fix defects reported by Coverity

engines/crab/crab.cpp, engines/crab/event/gameeventmanager.cpp, engines/crab/event/triggerset.cpp, engines/crab/game.cpp, engines/crab/game.h, engines/crab/mainmenu.cpp, engines/crab/ui/AlphaImage.h, engines/crab/ui/ChapterIntro.cpp, engines/crab/ui/CreditScreen.cpp, engines/crab/ui/DevConsole.cpp, engines/crab/ui/GeneralSettingMenu.cpp, engines/crab/ui/GfxSettingMenu.cpp, engines/crab/ui/OptionMenu.cpp, engines/crab/ui/TraitMenu.cpp
=> CRAB: Display error dialog when loading save fails and fix issues reported by PVS Studio

engines/ags/engine/ac/character.cpp, engines/ags/engine/ac/character.h, engines/ags/engine/ac/display.cpp, engines/ags/engine/ac/draw.cpp, engines/ags/engine/ac/game.cpp, engines/ags/engine/ac/global_game.cpp, engines/ags/engine/ac/global_gui.cpp, engines/ags/engine/ac/speech.cpp, engines/ags/engine/ac/sys_events.h, engines/ags/engine/ac/system.cpp, engines/ags/engine/game/savegame.cpp, engines/ags/engine/game/savegame_internal.h, engines/ags/engine/gfx/gfx_driver_base.cpp, engines/ags/engine/main/game_run.cpp, engines/ags/engine/main/main.cpp, engines/ags/engine/main/update.cpp, engines/ags/engine/script/cc_instance.cpp, engines/ags/engine/script/script.cpp, engines/ags/globals.h, engines/ags/shared/ac/game_setup_struct_base.h, engines/ags/shared/ac/game_struct_defines.h, engines/ags/shared/ac/keycode.h, engines/ags/shared/core/def_version.h, engines/ags/shared/gui/gui_button.cpp, engines/ags/shared/gui/gui_button.h, engines/ags/shared/gui/gui_main.cpp, engines/ags/shared/gui/gui_main.h, engines/ags/shared/util/directory.cpp, engines/ags/shared/util/path.cpp
The PR includes all the relevant upstream commits up to version 3.6.0.51 (AKA 3.6.0 patch 4)
The only skipped commit is 63c0d4802e782851d80350750f7a4dd0d281bbc5 which addresses a rare
potential bug and can't be ported easily (and I'm not too convinced of the fix)
=> AGS: Commits from upstream up to version 3.6.0.51

engines/buried/graphics.cpp
This fixes a regression from commit ac803c6.
=> BURIED: Fix crash when dragging inventory items

backends/platform/ios7/ios7_common.h, backends/platform/ios7/ios7_game_controller.mm, backends/platform/ios7/ios7_gamepad_controller.mm, backends/platform/ios7/ios7_keyboard.mm, backends/platform/ios7/ios7_osys_events.cpp, backends/platform/ios7/ios7_osys_main.cpp, backends/platform/ios7/ios7_osys_main.h, backends/platform/ios7/ios7_osys_misc.mm, backends/platform/ios7/ios7_video.h, backends/platform/ios7/ios7_video.mm
The touch controls in iOS could cause  Lure of the Temptress to "hang" waiting for buttons to be "released".
The top main menu was also impossible to use in touch based systems like Android and iOS
=> IOS7: Fix touch inputs for gamepad controller dpad events for Griffon

common/formats/quicktime.cpp
This fixes the maze end vidbot in Obsidian's Japanese localization missing audio.
=> COMMON: When flattening QuickTime edit lists, don't flatten non-silent audio chunks into silent chunks or vice versa.

engines/pink/detection_tables.h
https://drive.google.com/file/d/1rMcPsqtaKZUzlPidmGxZj-MtMXcPXrGR/view?usp=drive_link
=> PINK: Add detection for German pink demo

engines/ags/lib/allegro/surface_neon.cpp
Removing more NEON intrinsics that don't run on v7 arm cpus.
=> AGS: GRAPHICS: Remove a32/a64 specific NEON code

engines/ags/lib/allegro/surface_neon.cpp
Build bot was having compiling errors on switch specifically about some messed up types in the AGS NEON blending code that hadn't been caught by the other compilers. It was using 32bit bitwise ops on 16bit types.
=> AGS: GRAPHICS: Fix NEON compiling errors on switch

engines/access/amazon/amazon_game.cpp
Fixes [#14601](https://bugs.scummvm.org/ticket/14601)
=> ACCESS: Fix resource/file handle leak in Amazon:GoE

engines/scumm/he/script_v72he.cpp, engines/scumm/script.cpp, engines/scumm/script_v6.cpp
This PR implements a bugfix and several mods for competitive Backyard Baseball 2001 online play. All mods are only enabled when the "Enable online competitive mods" game option is checked.
Changes include:
* Changed the impact of hitters' batting power stat on hit power (more in favor of weaker hitters and line drive and grounder swings)
* Bugfix: prevent runners from turning around on their way to first base
* Change frequency of clicks required to reach top sprinting speed for baserunners
* Allow clicking to run players at full-speed during a pop-up
* Change impact of pitch location on hit quality
=> SCUMM HE: Baseball '01 competitive online play mods

engines/gob/detection/tables_gob2.h, engines/gob/detection/tables_gob3.h, engines/gob/detection/tables_inca2.h
Added versionnumbers to
- Goblins 2
- Gobliins 3
- Inca 2
=> GOB: added versionnumbers to various games

backends/platform/ios7/ios7_app_delegate.mm, backends/platform/ios7/ios7_common.h, backends/platform/ios7/ios7_options.mm, backends/platform/ios7/ios7_osys_events.cpp, backends/platform/ios7/ios7_osys_main.cpp, backends/platform/ios7/ios7_osys_main.h, backends/platform/ios7/ios7_touch_controller.mm, backends/platform/ios7/ios7_video.mm
The current implementation of translating touch event to mouse actions is a bit messy (mostly caused by me in the beginning). The problems reported by users are e.g. that it's hard to understand the click-and-drag mode and that false mouse clicks could be triggered by fast or short touch movements.
Fix all these problems by using UIGestures instead. Tap gestures are used for left and right mouse button clicks while long press gestures are used for "holding down" the mouse buttons. This also deprecates the click-and-drag mode.
Two fingers touch triggers right mouse button click and it's possible to move the mouse while right clicking by making sure to move the first finger while keeping the second touch on the screen.
To know which touch that is the first one it's always easier to first …
=> IOS7: Rework touch events to mouse actions

backends/platform/ios7/ios7_keyboard.mm, backends/platform/ios7/ios7_scummvm_view_controller.mm, backends/platform/ios7/ios7_video.mm
This PR fixes 2 of the already known bugs in the iOS port on TestFlight.
=> IOS7: Fixes on bugs reported on TestFlight build

engines/director/castmember/filmloop.cpp
=> DIRECTOR: Fix film loop loading for D2

engines/composer/graphics.cpp
Found this by random testing. The flipped BMP can be preprocessed and use standard (faster) blitting functions. Especially the lack of check for clipping made the difference in performance for me.
=> COMPOSER: Optimize sprite drawing

engines/ags/module.mk, engines/ags/plugins/ags_controller/ags_controller.cpp, engines/ags/plugins/ags_controller/ags_controller.h, engines/ags/plugins/ags_controller/ags_controller_arcnor.cpp, engines/ags/plugins/ags_controller/ags_controller_arcnor.h, engines/ags/plugins/plugin_base.cpp
This PR adds a new (mostly stubbed) plugin derived from AGSController, used in the game Perfect Tides.
=> AGS: Add ags_controller_arcnor plugin and small rework to agscontroller plugin

engines/sci/detection_tables.h
This adds some detection entries for soon to be released hebrew fan traslations of SCI games
from https://github.com/adventurebrew/HebrewAdventure
Space Quest 5
Space Quest 6
Phantasmagoria 2
Thank you
=> SCI: Add detection entries for hebrew fan translations

audio/decoders/wave.cpp
This completes the previous PR #5053 
Modern WAV files may contain extra chunks before the FMT header, as specified in the Broadcast Wave Format extension. These chunks must be skipped to properly read the header.
One example of such occurrence is the waves/seagull sound effect in the intro of Perfect Tides, and on the pier
=> AUDIO: Detect and skip BFW chunks in WAV files

engines/director/castmember/digitalvideo.cpp, engines/director/castmember/filmloop.cpp, engines/director/castmember/text.cpp, engines/director/debugger.cpp, engines/director/detection_tables.h, engines/director/lingo/lingo-object.cpp, engines/director/lingo/lingo-patcher.cpp, engines/director/lingo/lingo-preprocessor.cpp, engines/director/lingo/lingo-the.cpp, engines/director/lingo/lingo-the.h, engines/director/lingo/lingo.cpp, engines/director/lingo/xlibs/wininfo.cpp, engines/director/lingo/xlibs/wininfo.h, engines/director/module.mk, graphics/macgui/mactext.cpp, graphics/macgui/macwindow.cpp
=> DIRECTOR: Make Wrath of the Gods completable

engines/director/castmember/bitmap.cpp, engines/director/castmember/palette.cpp, engines/director/detection_tables.h, engines/director/game-quirks.cpp, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/xlibs/spacemgr.cpp, engines/director/score.cpp, engines/director/window.cpp
=> DIRECTOR: Fixes for The Dark Eye

backends/platform/ios7/ios7_keyboard.h, backends/platform/ios7/ios7_keyboard.mm, backends/platform/ios7/ios7_options.mm, backends/platform/ios7/ios7_osys_main.cpp, backends/platform/ios7/ios7_osys_main.h, backends/platform/ios7/ios7_video.mm
This PR contains fixes for the following problems reported in the iOS-support Discord channel.
- No sound in later Scumm games when returning from suspended
- HW keyboard events are not handled until enabling the soft keyboard
- Special button toolbar not resizing the main frame properly on show/hide
=> IOS7: More fixes on problems reported on TestFlight build

common/language.cpp, engines/glk/adrift/detection_tables.h, engines/glk/agt/detection_tables.h, engines/glk/alan3/detection_tables.h, engines/glk/archetype/detection_tables.h, engines/glk/comprehend/detection_tables.h, engines/glk/glulx/detection_tables.h, engines/glk/hugo/detection_tables.h, engines/glk/jacl/detection_tables.h, engines/glk/magnetic/detection_tables.h, engines/glk/quest/detection_tables.h, engines/glk/scott/detection_tables.h, engines/glk/tads/detection_tables.h, engines/glk/zcode/detection_tables.h, engines/metaengine.cpp, engines/mohawk/dialogs.cpp, engines/mohawk/myst.cpp, engines/mohawk/riven.cpp, engines/neverhood/dialogs.cpp, engines/queen/detection.cpp, engines/queen/display.cpp, engines/scumm/metaengine.cpp, engines/supernova/detection.cpp, engines/supernova/metaengine.cpp, engines/sword1/detection.cpp, engines/sword2/metaengine.cpp, engines/tetraedge/metaengine.cpp, gui/launcher.cpp
Now the number of times the header file gui_options.h is added is much smaller.
=> ALL: Decrease header dependency for gui_options.h

gui/gui-manager.cpp, gui/widgets/editable.cpp
Fix issues in List and Debugger caused by #5366
=> GUI: FIX issues caused by PR #5366

engines/ngi/gfx.cpp, engines/ngi/gfx.h
Lightly tested with Full Pipe (Demo/Windows/German)
=> NGI: Replace use of TransparentSurface with ManagedSurface

gui/dump-all-dialogs.cpp
=> GUI: Add more dialogs to dialog dumper

engines/crab/TTSHandler.cpp, engines/crab/TTSHandler.h, engines/crab/event/gameeventmanager.cpp, engines/crab/module.mk, engines/crab/ui/ChapterIntro.cpp, engines/crab/ui/ChapterIntro.h, engines/crab/ui/PersonHandler.h, engines/crab/ui/ReplyMenu.h
=> CRAB: Enable TTS in Crab Engine

engines/sludge/objtypes.cpp, engines/sludge/objtypes.h, engines/sludge/variable.cpp, engines/sludge/variable.h
In Out Of Order, you are not able to talk/walk to the "Urban Leopard" character
=> SLUDGE: Fix bug caused by getTextFromAnyVar used for debugging

AUTHORS, doc/docportal/help/credits.rst, engines/ags/credits.pl, gui/credits.h
Added myself to the AGS engine credits.
Please check I didn't miss something :)
=> CREDITS: Add myself to AGS credits

backends/platform/ios7/ios7_osys_main.cpp
The state information was saved using ConfMan in the scummvm ini file, but this could cause corruption of that ini file if the application was killed while ConfMan was flushed (see  [bug #14623](https://bugs.scummvm.org/ticket/14623)). To reduce the risk of losing the config file, we now save the state to a separate file.
This does not fix the root cause of [bug #14623](https://bugs.scummvm.org/ticket/14623), but removes one of the main context in which it could occur.
=> IOS7: Save state to a separate file when closing ScummVM

graphics/opengl/context.cpp
When GLAD fails to parse version, glGetError is null and raises a SIGSEGV.
Current version of GLAD has a bug while parsing extensions so there is a workaround here which should disappear when it's fixed.
=> OPENGL: Use GLAD version when available and check functions before use

NEWS.md, engines/director/detection_tables.h, engines/director/resource.cpp, engines/director/score.cpp
=> DIRECTOR: Fixes for Gadget + 2.8.0 announcement

NEWS.md, engines/director/detection_tables.h, engines/director/resource.cpp, engines/director/score.cpp
=> DIRECTOR: Fixes for Gadget + 2.8.0 announcement (backport)

engines/gob/detection/tables_geisha.h
Added italian detection for a DOS version of Geisha that is actually multilanguage (ITA/ESP).
=> GOB: Provide additional geisha detection entry

engines/kingdom/kingdom.cpp, engines/kingdom/kingdom.h
This allows the game to run more comfortably with the Nintendo DS port.
=> KINGDOM: Reduce memory usage

engines/director/detection_tables.h
Demo found by IlDucci on Discord
https://gofile.io/d/bdRNlY
=> DIRECTOR: Add detection for Gadget: Past as Future Spanish demo

NEWS.md
=> NEWS: Typo

image/pict.cpp, image/pict.h
- This fixes rendering for certain PICT files, for example http://cd.textfiles.com/fantaziasampler/CLIPART/PCT/
=> IMAGE: PICT: Added rowbytes checking if there is lack of PixMap headers

engines/kingdom/kingdom.cpp, engines/kingdom/kingdom.h
Also adds a _mixer->stopAll() call in the engine's destructor
Motivation for the commit was bug ticket: https://bugs.scummvm.org/ticket/14787
=> KINGDOM: Supporting returning back to launcher feature

engines/sword1/detection_tables.h
As reported by YetAnotherGuy via IRC.
=> SWORD1: Add detection for SoldOut rerelease

devtools/director-generate-xobj-stub.py
=> DIRECTOR: Fixes for Team Xtreme

engines/cge/metaengine.cpp
=> CGE: Add keymaps to the engine

engines/director/castmember/digitalvideo.cpp, engines/director/frame.cpp, engines/director/score.cpp, engines/director/score.h
Re-adds the support removed in e13eba21629cc49d9aa3aa3029aa657843aa507c
Fixes the puppetTempo example in Lingo Dictionary.
=> DIRECTOR: Fixes for tempo/DV playback

engines/ags/plugins/ags_pal_render/ags_pal_render.cpp, engines/ags/plugins/ags_pal_render/raycast.cpp, engines/ags/plugins/ags_snow_rain/weather.cpp, engines/griffon/dialogs.cpp, engines/trecision/actor.cpp, engines/trecision/defines.h, engines/trecision/pathfinding3d.cpp, engines/trecision/renderer3d.cpp, engines/trecision/utils.cpp, engines/ultima/nuvie/sound/adplug/fm_opl.cpp, engines/ultima/nuvie/sound/adplug/opl_class.cpp, engines/ultima/nuvie/sound/decoder/pc_speaker.cpp, graphics/scaler/pm.cpp
There's also one remaining case in the Hypno engine that this PR hasn't addressed.
=> COMMON: Remove use of symbol PI to avoid clashing with system headers

engines/director/lingo/xlibs/miscx.cpp, engines/director/lingo/xlibs/miscx.h
Backpacker now seems to run well, where before it was crashing after the first scene.
=> DIRECTOR: XOBJ: Update MiscX stub

gui/options.cpp
Fixes https://bugs.scummvm.org/ticket/14818
=> GUI: Fix garbled browser last path on Windows

engines/cge2/metaengine.cpp
=> CGE2: Add Keymaps to the engine

devtools/director-generate-xobj-stub.py, engines/director/castmember/text.cpp, engines/director/channel.cpp, engines/director/channel.h, engines/director/events.cpp, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-funcs.cpp, engines/director/lingo/lingo-object.cpp, engines/director/lingo/lingo.cpp, engines/director/lingo/xlibs/panel.cpp, engines/director/lingo/xlibs/panel.h, engines/director/lingo/xlibs/processxobj.cpp, engines/director/lingo/xlibs/processxobj.h, engines/director/lingo/xlibs/window.cpp, engines/director/lingo/xlibs/window.h, engines/director/module.mk, engines/director/score.cpp, engines/director/util.cpp, engines/director/window.cpp, graphics/macgui/mactext-canvas.cpp, graphics/macgui/mactext.cpp
=> DIRECTOR: Fixes for Cosmology of Kyoto

backends/platform/sdl/miyoo/build_miyoo_musl.sh
=> MIYOO: Add a build script for musl variant of miyoo CFW

backends/platform/ios7/ios7_options.mm, backends/platform/ios7/ios7_osys_main.cpp, backends/platform/ios7/ios7_osys_main.h, backends/platform/ios7/ios7_osys_video.mm, backends/platform/ios7/ios7_video.h, backends/platform/ios7/ios7_video.mm, base/commandLine.cpp, dists/ios7/Info.plist, dists/ios7/Info.plist.in
This PR contains fixes to be able to run the iOS/iPadOS application on Mac computers with Apple Silicon, along with a small bug fix.
=> IOS7 Make "Designed for iPad" great again on Macs with Apple Silicon

backends/platform/sdl/miyoo/build_miyoomini.sh
=> MIYOOMINI: Enable neon and freetype2 in documented compilation script

common/language.cpp, common/language.h, engines/asylum/detection_tables.h, engines/asylum/puzzles/board.cpp, engines/asylum/puzzles/boardkeyhidesto.cpp, engines/asylum/puzzles/boardsalvation.cpp, engines/asylum/puzzles/boardyouth.cpp, engines/asylum/resources/encounters.cpp
=> [asylum] added basque fan translation

devtools/create_ultima/files/ultima6/scripts/u6/actor.lua, engines/ultima/nuvie/actors/actor.cpp, engines/ultima/nuvie/actors/actor.h, engines/ultima/nuvie/actors/actor_manager.cpp, engines/ultima/nuvie/actors/actor_manager.h, engines/ultima/nuvie/actors/u6_actor.cpp, engines/ultima/nuvie/actors/u6_actor.h, engines/ultima/nuvie/core/anim_manager.cpp, engines/ultima/nuvie/core/events.cpp, engines/ultima/nuvie/core/magic.h, engines/ultima/nuvie/core/obj.cpp, engines/ultima/nuvie/core/obj.h, engines/ultima/nuvie/core/obj_manager.cpp, engines/ultima/nuvie/core/obj_manager.h, engines/ultima/nuvie/core/player.cpp, engines/ultima/nuvie/gui/widgets/map_window.cpp, engines/ultima/nuvie/gui/widgets/map_window.h, engines/ultima/nuvie/menus/game_menu_dialog.cpp, engines/ultima/nuvie/pathfinder/party_path_finder.cpp, engines/ultima/nuvie/script/script.cpp, engines/ultima/nuvie/script/script.h, engines/ultima/nuvie/sound/sound_manager.cpp, engines/ultima/nuvie/views/spell_view_gump.cpp
Contains original behavior fixes for:
- placement of thrown weapons
- pushing actors and objects
- dropping objects
- actor passability (this includes changes to party/player movement code)
Additional changes:
- fix some cases of coordinates not wrapping around when a map boundary is crossed
- hide menu when creating save thumbnail
- fix some allocator/deleter mismatches
=> ULTIMA: NUVIE: Misc fixes

audio/softsynth/fluidsynth.cpp, backends/platform/ios7/ios7_keyboard.h, backends/platform/ios7/ios7_keyboard.mm, backends/platform/ios7/ios7_options.mm, backends/platform/ios7/ios7_osys_events.cpp, backends/platform/ios7/ios7_osys_main.cpp, backends/platform/ios7/ios7_osys_main.h, backends/platform/ios7/ios7_osys_video.mm, backends/platform/ios7/ios7_video.h, backends/platform/ios7/ios7_video.mm, base/commandLine.cpp, dists/ios7/Info.plist, dists/ios7/Info.plist.in
IOS7 backed patches targeted for 2.8.1
=> IOS7 backports

graphics/font.cpp, graphics/font.h, graphics/macgui/mactext-canvas.cpp, graphics/macgui/mactext-canvas.h
Enhanced word split handling across lines for edits and resizing, ensuring correct text flow and display.
=> GRAPHICS MACGUI: Process extra long words

configure
=> AMIGAOS: clean up compiler flags

backends/graphics3d/ios/ios-graphics3d.cpp, backends/platform/ios7/ios7_keyboard.mm, backends/platform/ios7/ios7_mouse_controller.mm, backends/platform/ios7/ios7_osys_misc.mm, backends/platform/ios7/ios7_video.mm, doc/docportal/other_platforms/ios.rst
A bunch of small fixes for the iOS backend
=> IOS7: Various fixes

engines/agi/detection_tables.h
Reviewed all the game in the website [SCI Community created Adventure games](https://sciprogramming.com/fangames.php?eng=agi&cat=All&sort=date) and added new ones in **engines/agi/detection_tables.h (fanmade titles)**
=> AGI: Review games and add new ones

graphics/macgui/macmenu.cpp, graphics/macgui/macmenu.h, graphics/macgui/macpopupmenu.cpp
Add the functionality to scroll submenu content when it exceeds the screen size.
=> GRAPHICS: MACGUI: Implement submenu scrolling

common/stream.h, image/ani.cpp, image/ani.h, image/icocur.h
This adds support for loading Windows ANI and CUR files.
=> IMAGE: Add support for loading Windows ANI and CUR files

engines/game.h, gui/massadd.cpp, gui/massadd.h, gui/widgets/list.cpp, gui/widgets/list.h
GUI: Skip games during Mass Add
[x] and [ ] are used as indicators, as well as background color.
=> GUI: Skip games during Mass Add

doc/docportal/settings/game.rst
This commit add documentation about Thimbleweed Park GUI options.
=> DOCS: Add Thimbleweed Park documentation

devtools/README, devtools/create_achievements/create_achievements.sh, devtools/create_achievements/steam_achievements.py
Fixed the python script for the steamdb requests to work with the cloudflare bot protection again.
Some other minor changes were needed because there were changes in the meantime on the output of the achievements
=> DEVTOOLS: updated create-achievement scripts

devtools/dumper-companion.py
=> DUMPER: Add feature to extract data from ISO9660 and hybrid disk images

engines/director/game-quirks.cpp, engines/director/lingo/tests/builtin.lingo
=> DIRECTOR: LINGO: TEST: Adds lingo test for getNthFileNameInFolder [WIP]

engines/chamber/anim.cpp, engines/chamber/bkbuff.cpp, engines/chamber/cga.cpp, engines/chamber/cga.h, engines/chamber/chamber.cpp, engines/chamber/chamber.h, engines/chamber/cursor.cpp, engines/chamber/dialog.cpp, engines/chamber/input.cpp, engines/chamber/invent.cpp, engines/chamber/kult.cpp, engines/chamber/portrait.cpp, engines/chamber/print.cpp, engines/chamber/room.cpp, engines/chamber/script.cpp
Refactor the existing CGA rendering code to make it compatible with HGA rendering. The main changes include the introduction of engine variables and a move away from macros.
=> CHAMBERS: Refactor code for HGA compatibility

graphics/yuv_to_rgb.cpp, graphics/yuv_to_rgb.h
=> GRAPHICS: Reduce the size of the YUV to RGB tables

dists/org.scummvm.scummvm.desktop
- due to the change to the rDNS-based filename some window managers like Cinnamon can't find the according desktop file for scummvm's application window anymore
- this causes some unwanted behavior (e.g. not using the correct icons in the task switcher)
- before commit f683b9b916a730d93defcd12522205633588059b the mapping worked by matching the WM_CLASS property of the scummvm window to the filename of the desktop file
- this patch sets the StartupWMClass property in the .desktop file to the name of scummvm's WM_CLASS X property which will allow a proper mapping
=> DISTS: Set StartupWMClass in .desktop file

common/substream.h
=> COMMON: Remove deprecated SeekableSubReadStreamEndian class

image/codecs/indeo3.cpp, image/codecs/indeo3.h
This improves performance a bit on the DS, although currently the YUV to RGB code is the main bottleneck.
=> GRAPHICS: Indeo 3 performance and memory improvements

base/commandLine.cpp
Here we go, let's do it 🙂 Take 2 of the previous PR by @lotharsm 
This was highly requested by people. And most importantly by me 😝 
Discussion on: https://github.com/scummvm/scummvm/pull/1542
=> BASE: Enable aspect ratio correction by default (take 2)

backends/platform/sdl/amigaos/amigaos-main.cpp, backends/platform/sdl/amigaos/amigaos.cpp
- Enhance stack cookie
- Set more default. ini values
=> AMIGAOS: Enhance stack cookie and set more default .ini values

engines/bagel/console.cpp, engines/bagel/console.h
=> BAGEL: Add 'megawave' and 'microwave' Console Commands

engines/director/channel.cpp, engines/director/channel.h, engines/director/debugtools.cpp, engines/director/lingo/lingo-events.cpp, engines/director/lingo/lingo-the.cpp, engines/director/lingo/xlibs/mmovie.cpp, engines/director/lingo/xlibs/unittest.cpp, engines/director/score.cpp, engines/director/sprite.cpp, engines/director/sprite.h
=> DIRECTOR: Fixes for Virtual Nightclub

engines/agi/detection_tables.h
This PR adds latest version for the following AGI Fan Made titles:
- Enclosure
- Voodoo Girl
=> AGI: Adds updated versions for "Enclosure" and "Voodoo Girl"

engines/ags/detection_tables.h
This PR adds new version for the following AGS titles:
- Graceward
- The Last Pirate Adventure: Drake's Treasure
- Zniw Adventure
=> AGS: Adds 3 new versions for existing entries

engines/director/graphics.cpp, engines/director/lingo/lingo-builtins.cpp, graphics/macgui/mactext-canvas.cpp, graphics/macgui/mactext.cpp
This pull request addresses various issues such as:
- Handling empty text in selection logic
- Fixing ZoomBox offset in desktop mode
- Ensuring correct duplication of cast member
- Correcting reverse ink rendering
- Fixing compilation with DEBUG enabled
=> DIRECTOR: Fixes for The Apartment and Lingo Workshop

engines/ags/detection_tables.h
This PR updates Steam version for "Beer!" plus about 25 entries from https://www.adventuregamestudio.co.uk/
=> AGS: Updates Steam "Beer!" & various free titles

engines/composer/composer.cpp, engines/composer/metaengine.cpp
Add Keymapper support for Composer engine
=> COMPOSER: Add keymapper support

engines/wintermute/detection_tables.h
Curse Branch: https://bugs.scummvm.org/ticket/14693
Rhiannon Ghosts of the Past: https://bugs.scummvm.org/ticket/14697
=> WINTERMUTE: add some Rhiannon variants reported to TRAC

engines/agos/agos.cpp, engines/agos/agos.h, engines/agos/animation.cpp, engines/agos/event.cpp, engines/agos/input.cpp, engines/agos/input_pn.cpp, engines/agos/metaengine.cpp, engines/agos/pn.cpp, engines/agos/saveload.cpp, engines/agos/script_s1.cpp, engines/agos/vga_pn.cpp
Keymapper Support for AGOS engine
=> AGOS: Add keymapper support

engines/scumm/script_v6.cpp
These are all adjustments to the patch made about 2 weeks ago. Clarification on specifics can be made if necessary.
=> SCUMM: Backyard Baseball 2001 Online Mode Game Balance Changes

engines/nancy/state/setupmenu.cpp
I didn't examine *all* the original games playable at this point, but SCK (1), STFD (2), and DOG (7) did it.
=> NANCY: Add sound to toggles in Game Setup

common/formats/quicktime.cpp, common/formats/quicktime.h, engines/testbed/video.cpp, video/qt_decoder.cpp, video/qt_decoder.h, video/video_decoder.h
This pull request introduces multiple features for QuickTime:
- Implement parsing for various QuickTime movie atoms.
- Add interactive control for QuickTime VR object movies.
- Start implementation of QuickTime VR panorama rendering (WIP).
=> ALL: QuickTime Enhancements & Director Fixes

engines/gob/hotspots.cpp, engines/gob/map_v1.cpp, engines/gob/sound/cdrom.cpp
* Overloads were reported as warnings in VS Code
=> GOB: Code Improvements

engines/agi/op_cmd.cpp, engines/agi/saveload.cpp, engines/agi/sound_midi.cpp
Fix a bunch of typos in comments
=> JANITORIAL: AGI: Fix comment typos

engines/kyra/text/text_lok.cpp
When both subtitles and voice are enabled use voice duration as in the original game.
=> KYRA: LoK - Fix chat duration

backends/imgui/imgui_fonts.cpp, engines/director/channel.cpp, engines/director/detection_tables.h, engines/director/director.cpp, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-code.cpp, engines/director/lingo/lingo-code.h, engines/director/lingo/lingo-object.cpp, engines/director/lingo/lingo.h, engines/director/lingo/tests/lists.lingo, engines/director/lingo/xlibs/fileio.cpp, engines/director/lingo/xlibs/movemousejp.cpp, engines/director/lingo/xlibs/movemousejp.h, engines/director/module.mk
=> DIRECTOR: Fixes for AMBER and Jungle Park

engines/director/lingo/lingo-code.cpp, engines/director/sprite.cpp, engines/director/window.cpp
In a few occasions the debug channel and debug level arguments were swapped
=> DIRECTOR: Fix argument order for setting debug channels

engines/dgds/console.cpp, engines/dgds/console.h
This allows dumping ADS scripts from debug console
example usage:
```scriptdump CLBATH.ADS```
=> DGDS: Dump script from debug console

engines/director/detection_tables.h
Reviews and Suggestions are welcome :)
=> DIRECTOR: add mac variants of Adibou

dists/org.scummvm.scummvm.desktop
Nuance change from "several" to "numerous"
=> DISTS: Update Swedish nuance in desktop file

engines/director/detection_tables.h, engines/director/lingo/lingo-object.cpp, engines/director/lingo/xlibs/mystisle.cpp, engines/director/lingo/xlibs/mystisle.h, engines/director/module.mk
=> DIRECTOR: Add detection for Mysterious Island; add MystIsle xobj

engines/kyra/engine/chargen.cpp, engines/kyra/engine/eobcommon.cpp, engines/kyra/engine/eobcommon.h, engines/kyra/gui/saveload.cpp, engines/kyra/gui/saveload_eob.cpp
More faithful AD&D rules for Eye of the Beholder 1 and 2, according to the discussion in PR #5946.
=> KYRA: (EOB) - HP per level rule enahncements

engines/bagel/baglib/exam.cpp, engines/bagel/baglib/fmovie.cpp, engines/bagel/baglib/fmovie.h, engines/bagel/boflib/gui/movie.cpp, engines/bagel/boflib/gui/movie.h
I hope i didn't miss any of the "foreward"s
PR on it's own since it touches actual code
edit: i did miss one, sorry about that
=> JANITORIAL: BAGEL: Fix in-code typos

audio/alsa_opl.cpp, audio/chip.cpp, audio/chip.h, audio/cms.cpp, audio/cms.h, audio/fmopl.cpp, audio/fmopl.h, audio/module.mk, audio/opl2lpt.cpp, audio/rwopl3.cpp, audio/rwopl3.h, audio/softsynth/cms.cpp, audio/softsynth/cms.h, audio/softsynth/opl/dosbox.h, audio/softsynth/opl/mame.h, audio/softsynth/opl/nuked.h
This should make it easier to support additional sound chips in the future.
=> AUDIO: Share code between OPL and CMS implementations

engines/bagel/baglib/chat_wnd.cpp, engines/bagel/baglib/log_msg.cpp, engines/bagel/baglib/movie_object.cpp, engines/bagel/baglib/pan_bitmap.h, engines/bagel/baglib/pan_window.cpp, engines/bagel/baglib/pan_window.h, engines/bagel/baglib/storage_dev_win.cpp, engines/bagel/baglib/time_object.cpp, engines/bagel/boflib/dat_file.cpp, engines/bagel/boflib/gfx/sprite.cpp, engines/bagel/boflib/string.cpp, engines/bagel/boflib/string_functions.h, engines/bagel/spacebar/filter.cpp, engines/bagel/spacebar/main_window.cpp, engines/bagel/spacebar/thud.cpp
Most of the fixes are in comments except one instance of "thru" that seems to be part of displaying in-game
I know "thru" is debatable, but since it's still considered non-standard i "fixed" them too :-)
=> JANITORIAL: BAGEL: Fix typos in comments

engines/chamber/input.cpp, engines/chamber/script.cpp
Additional PR since it touches the code
=> JANITORIAL: CHAMBER: Fix typos in code

engines/grim/grim.cpp
The help screen in the demo says that Alt + x quits the demo. Make it do so.
=> GRIM: Exit demo on Alt + x 

engines/glk/agt/exec.h, engines/glk/agt/metacommand.cpp, engines/glk/agt/runverb.cpp, engines/glk/agt/vars.cpp
Separate PR since it touches the code
=> JANITORIAL: GLK: Fix supress typos in vars/code

audio/softsynth/pcspk.cpp
=> SOFTSYNTH/PCSPK: fix overflow for sounds longer than 97 ms (at 44100 Hz)

backends/platform/ios7/ios7_gamepad_controller.mm, backends/platform/ios7/ios7_keyboard.mm
Fix some small memory leaks.
Make sure that the keyboard dismiss when the Return key is pressed.
=> IOS7: Fix memory leaks

engines/director/detection_tables.h
~I don't know how to determine the exact D3 version, but~ it fails to start when listed as D4.
=> DIRECTOR: Fix detection for Hollywood Online: Rob Roy

common/formats/quicktime.h, engines/director/castmember/text.cpp, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-bytecode.cpp, engines/director/lingo/lingo-the.cpp, engines/director/lingo/lingo-the.h, engines/director/lingo/xtras/qtvrxtra.cpp, engines/director/lingo/xtras/qtvrxtra.h, video/qt_decoder.cpp, video/qt_decoder.h
This PR makes progress on QTVR Xtra functionality by updating several function stubs with working implementations.
=> DIRECTOR: Implement QTVR Xtra Methods

engines/icb/common/px_scriptengine.cpp, engines/icb/common/px_scriptengine.h, engines/icb/floors.cpp, engines/icb/floors.h, engines/icb/function.cpp, engines/icb/player.cpp
Separate PR since it touches code
=> JANITORIAL: ICB: Fix allign and devide typos in code

engines/qdengine/qdcore/qd_game_dispatcher.cpp, engines/qdengine/qdcore/qd_music_track.cpp, engines/qdengine/qdcore/util/WinVideo.cpp
Add support to different types of encoding for filenames namely: 
- UTF-8
- Punycode
=> QDENGINE: Add support to UTF-8 & Punycode encoded filenames

engines/qdengine/system/graphics/gr_draw_sprite_rle.cpp
=> QDENGINE: Fix mask rendering by removing unnecessary * 2 multiplication

engines/qdengine/debugger/debugtools.cpp, engines/qdengine/debugger/debugtools.h, engines/qdengine/detection.cpp, engines/qdengine/module.mk, engines/qdengine/qdcore/qd_file_manager.h, engines/qdengine/qdengine.cpp, engines/qdengine/qdengine.h
=> QDENGINE: Implement a minimal version of the QDA debugger

devtools/dumper-companion.py
When using non-ascii characters, the filename needs punyencoding.
=> DEVTOOLS: COMPANION: Fix needs_punyencoding function

engines/qdengine/debugger/debugger.h, engines/qdengine/debugger/debugtools.cpp, engines/qdengine/system/graphics/gr_dispatcher.cpp, engines/qdengine/system/graphics/gr_dispatcher.h, engines/qdengine/system/graphics/gr_draw_sprite.cpp, engines/qdengine/system/graphics/gr_draw_sprite_rle.cpp
=> QDENGINE: Make improvements to the debugger

engines/qdengine/debugger/debugtools.cpp, engines/qdengine/debugger/dt-internal.h
=> QDENGINE: Add a Control Panel to the debugger

audio/softsynth/opl/nuked.cpp, audio/softsynth/opl/nuked.h
This is something I tried while looking at (and eventually giving up on) https://bugs.scummvm.org/ticket/15339
It didn't make any difference that I could make out, but I thought maybe it was worth applying anyway? The upstream commits are:
https://github.com/nukeykt/Nuked-OPL3/commit/e4afafc9ed6ceb22604cf3b18f310c3aa70c4a45
https://github.com/nukeykt/Nuked-OPL3/commit/cfedb09efc03f1d7b5fc1f04dd449d77d8c49d50
=> AUDIO: Sync with upstream Nuked OPL.

engines/scumm/insane/insane.cpp, engines/scumm/insane/insane.h, engines/scumm/insane/insane_enemy.cpp, engines/scumm/insane/insane_iact.cpp, engines/scumm/insane/insane_scenes.cpp
Separate PR, since it touches code
=> JANITORIAL: SCUMM: Fix occurences typos in code

engines/sci/sound/drivers/pcjr.cpp
I have reorganized the code a bit, fixed deviations from our coding conventions and moved all the version specific sound channel code into sub classes.
And I have added the missing pitch bend feature. The pitch bend is actually used, even by the PC Speaker driver.
=> SCI: PCJr sound driver - added pitchbend feature and major cleanup

engines/neverhood/blbarchive.cpp
This fixes crash with Fargus translation of Neverhood
=> NEVERHOOD: Support DCL entry with bogus size

engines/sherlock/resources.cpp
Russian translation of Rose Tattoo does funny things with compression. This fixes them AFAICT
=> SHERLOCK: Fix bugs with Russian translation  of Rose Tattoo

engines/asylum/system/text.cpp
=> ASYLUM: Add more colors for Chinese version

engines/neverhood/detection.cpp
Thanks to Ctpax for pointing to this release and supplying hashes
=> NEVERHOOD: Add an alternative Neverhood translation.

engines/mm/xeen/font.cpp, engines/mm/xeen/locations.cpp
=> XEEN: Series of small Chinese improvements

engines/scumm/string.cpp
Big5 aka Windows950 is only for Traditional Chinese. Simplified one uses EUC-CN/Windows936
=> SCUMM: Set the correct encoding for Simplified Chinese

engines/achievements.cpp
This is designed to allow disabling of the unlocked achievement OSD message as per https://forums.scummvm.org/viewtopic.php?p=99672#p99672 ...
=> ACHIEVEMENTS: Allow Disabling Of Unlocked Achievement OSD Using Config Option

engines/scumm/script_v6.cpp
This just adds a comment clarifying the behavior of the fix from https://github.com/scummvm/scummvm/pull/6138.
=> SCUMM HE: Update comment on BB01 stat buffs fix

graphics/blit/blit.cpp
The new version of the code is shorter and should be easier to maintain. A potential bug has also been fixed in the mask blitters that was overlooked because it's not currently being used.
=> GRAPHICS: Reduce complexity of the crossBlit() code

backends/events/sdl/sdl-events.cpp, backends/events/sdl/sdl-events.h
For this to happen virtual keyboard needs to be enabled at build time which is off by default on most platforms
=> SDL: Open virtual keyboard on three-finger tap

backends/platform/android/android.cpp, backends/platform/ios7/ios7_osys_misc.mm, base/main.cpp, engines/freescape/metaengine.cpp, engines/scumm/he/moonbase/dialog-mapgenerator.cpp, engines/stark/metaengine.cpp, gui/launcher.cpp
I focused particularly on what is found in translation files i.e. what is user-facing.
=> JANITORIAL: Fix some typos

backends/platform/sdl/sdl.cpp, backends/platform/sdl/sdl.h
This is split out from [this branch](https://github.com/ccawley2011/scummvm/tree/rendersdl) and slightly modified to be more standalone.
=> SDL: Support building with more than two renderers

engines/darkseed/animation.cpp, engines/darkseed/anm.cpp, engines/darkseed/anm.h, engines/darkseed/cutscene.cpp, engines/darkseed/cutscene.h, engines/darkseed/darkseed.cpp, engines/darkseed/darkseed.h, engines/darkseed/module.mk, engines/darkseed/morph.cpp, engines/darkseed/morph.h, engines/darkseed/player.cpp, engines/darkseed/player.h
This PR adds the remaining cutscenes. It also adds the morphing effect. Still need to work on transitioning from bed to nightmare cutscenes.
=> DARKSEED: cutscene morphing

engines/director/detection_tables.h, engines/director/resource.cpp, engines/director/util.cpp, engines/director/util.h
=> DIRECTOR: Fixes for Pop Up Computer

backends/platform/ios7/ios7_osys_main.cpp, backends/platform/ios7/ios7_osys_video.mm, backends/platform/ios7/ios7_video.mm
This PR address one of the most common crashes according to the crash reports from AppStore.
It also tries to align the on-screen button placement with Android, see attached screenshots from an iPhone 16.
=> IOS7: Crash fix + on screen button alignments

backends/platform/sdl/sailfish/rpm/org.scummvm.scummvm.spec
While on it remove stale variable
=> SAILFISH: Enable standard engine set

engines/m4/fileio/sys_file.cpp, engines/m4/fileio/sys_file.h, engines/m4/graphics/gr_font.cpp, engines/m4/mem/mem.cpp
This fixes [Trac #15148](https://bugs.scummvm.org/ticket/15148).
=> M4: Avoid unaligned memory access

NEWS.md
@athrxx We forgot to mention the first round of changes including the new feature flag "Faithful AD&D rules". Updated NEWS with all the changes.
=> Comprehensive KYRA (EOB) news

engines/ultima/POTFILES, engines/ultima/ultima8/games/u8_game.cpp, engines/ultima/ultima8/ultima8.cpp
@OMGPizzaGuy does this seem like a reasonable approach?
The game can't really start without this data, no need to continue.
This fixes #12790.
=> ULTIMA8: Report mising U8SAVE.000 file on startup

backends/fs/amigaos/amigaos-fs.cpp
just a missing closing bracket in a debug output
amigaos4 only
=> JANITORIAL: Add missing closing bracket in amigaos-fs.cpp

backends/platform/android/android.cpp, backends/platform/android/android.h, backends/platform/android/android.mk, backends/platform/android/jni-android.cpp, backends/platform/android/jni-android.h, backends/platform/android/org/scummvm/scummvm/ScummVM.java, backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java
This allows packagers to provide game files which get automatically added at startup.
=> ANDROID: Add game assets support

engines/ags/detection_tables.h
=> AGS: Update detection for The Crimson Diamond

engines/myst3/detection.cpp, engines/myst3/detection.h, engines/myst3/metaengine.cpp, engines/myst3/myst3.cpp, engines/myst3/myst3.h
This fixes [#13039](https://bugs.scummvm.org/ticket/13039).
=> MYST3: Add support for orignal layout of multilingual CD and DVD

doc/docportal/conf.py, doc/docportal/other_platforms/ios.rst, doc/docportal/requirements.txt
Done as a PR to check RTD rendering.
=> DOCS: Update Sphinx and its plugins versions

backends/platform/sdl/amigaos/amigaos.cpp
as per request from @ccawley2011 in https://github.com/scummvm/scummvm/pull/6251
=> AMIGAOS: Revert already default settings

engines/director/detection_tables.h
The demo can be found here: http://web.archive.org/web/20061024204538/http://www.adventurecompanygames.com/tac/dl/demo_pc_safecracker.zip
=> DIRECTOR: Add detection for the demo version of Safecracker

backends/fs/morphos/morphos-fs.cpp, backends/platform/sdl/morphos/morphos-main.cpp, backends/platform/sdl/morphos/morphos.cpp, backends/platform/sdl/morphos/morphos.h, backends/platform/sdl/sdl.cpp
Some little enhanced:
add initBackend (same as AmigaOS)
add getSystemLanguage() to detecte system language (use SDL_GetPreferredLocales)
add support create directory
=> BACKENDS: MORPHOS: enhanced init and add features

doc/docportal/use_scummvm/save_load_games.rst
To check the result on CI before merge.
=> DOCS: Fix savelocation anchor location

backends/plugins/kolibrios/kolibrios-provider.cpp, backends/saves/kolibrios/kolibrios-saves.cpp
=> KOLIBRI: Fix compilation on KolibriOS

NEWS.md
=> NEWS: Add iOS/iPadOS port news

backends/fs/kolibrios/kolibrios-fs-factory.cpp, backends/platform/sdl/kolibrios/build-kolibri.sh, configure
* getcwd is apprently missing from SDK I tried. Whatever, just use _ksys_getcwd
* Detection of freetype was broken
* Small updates to build script
=> KOLIBRI: Build fixes, round 2

LICENSES/COPYING.BSD, LICENSES/COPYING.MIT, LICENSES/COPYING.OFL, gui/themes/fonts/README
I'm not sure how to accommodate the VL Gothic licenses, since it seems to be a combination of multiple open-source licenses.
=> LICENSES: Update the license information for the fonts

engines/tsage/configure.engine, engines/tsage/core.cpp, engines/tsage/debugger.cpp, engines/tsage/debugger.h, engines/tsage/globals.cpp, engines/tsage/module.mk, engines/tsage/tsage.cpp
The engine is quite large with all subengines enabled compared to other low resolution engines, so this may be useful for platforms with less memory.
=> TSAGE: Split engine into multiple subengines

engines/gob/detection/tables.h, engines/gob/detection/tables_magicstones.h, engines/gob/obsolete.h
The changes were made to sync with the original gameid/gametitle like back then in 2009 added by Strangerke in  commit: https://github.com/scummvm/scummvm/commit/add4d124b29a6de01d69cc8f2a8d236deb969425
=> GOB: magicstones detection cleanup

audio/mods/tfmx.cpp, audio/softsynth/opl/mame.cpp, backends/fs/stdiostream.h, configure, devtools/create_drascula/staticdata.h, devtools/create_kyradat/resources/eob1_dos_english.h, devtools/create_kyradat/resources/eob1_segacd_english.h, devtools/create_kyradat/resources/eob2_amiga_english.h, devtools/create_kyradat/resources/eob2_dos_english.h, devtools/create_kyradat/resources/eob2_pc98_japanese.h, devtools/create_mm/create_xeen/en_constants.h, devtools/create_mm/files/mm1/strings_en.yml, devtools/create_teenagent/static_tables.h, devtools/create_titanic/create_titanic_dat.cpp, graphics/sjis.cpp
Fixes some typos and adds more FIXME's
=> JANITORIAL: Fix typos in general files

engines/darkseed/darkseed.cpp
I'm not sure about this one
sargent is obviously mispelled (sergeant), but maybe there is a character called "sargent"?
=> JANITORIAL: Fix sargent typos in darkseed.cpp

engines/scumm/palette.cpp, graphics/palette.cpp, graphics/palette.h
These changes define the methods currently used for palette color matching. I have no immediate plans to support additional methods.
For reference: https://en.wikipedia.org/wiki/Color_difference
=> Palette color distance definitions

configure, devtools/create_project/create_project.cpp, devtools/create_project/create_project.h
This will avoid having to add components at both place when it's not needed.
This also should fix the current build failure.
=> CREATE_PROJECT: Add components based features dynamically

engines/scumm/he/mixer_he.cpp
Heap buffer overflow mitigation
Fix of an issue that some russian translated games(tested on pajama1 and freddi fish 2). Cause ScummVM to hard crash on linux while clicking on some specific game elements.
=> SCUMM: mixer_he: Add check sample buffer size for fade in

configure, devtools/create_project/cmake.cpp
waitOnSocket in socket.cpp uses select, which is implemented in ws2_32.
=> BUILD: Fix build on mingw with libcurl

engines/hpl1/engine/graphics/bitmap2D.cpp, engines/twine/movies.cpp, engines/twine/movies.h, image/gif.cpp, image/gif.h
As I have not much time to check and build, I use a PR for CI testing.
=> IMAGE: Don't declare GIFDecoder when GIF support is not built

devtools/create_project/create_project.cpp
Also move the features hard-coded logic in its own function.
=> CREATE_PROJECT: Add support for meta-components

video/qtvr_decoder.cpp
Fixed some errors in QTVR hotspot calculation
=> VIDEO: QTVR: Fix hotspot inverse projection

engines/asylum/metaengine.cpp, engines/glk/hugo/hugo.cpp, engines/glk/jacl/jacl_main.cpp, engines/grim/grim.cpp
in i18n comment and elsewhere.
One of these changes a searchset node name so it's separate; @dreammaster ok?
=> JANITORIAL: Fix typo

backends/events/sdl/sdl-common-events.cpp, backends/events/sdl/sdl-events.h, backends/events/sdl/sdl1-events.cpp, backends/events/sdl/sdl2-events.cpp, backends/events/sdl/sdl3-events.cpp, backends/graphics/openglsdl/openglsdl-graphics.cpp, backends/graphics/sdl/sdl-graphics.cpp, backends/graphics/sdl/sdl-graphics.h, backends/graphics/surfacesdl/surfacesdl-graphics.cpp, backends/graphics/surfacesdl/surfacesdl-graphics.h, backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp, backends/imgui/backends/imgui_impl_sdl3.cpp, backends/imgui/backends/imgui_impl_sdl3.h, backends/imgui/backends/imgui_impl_sdlrenderer3.cpp, backends/imgui/backends/imgui_impl_sdlrenderer3.h, backends/imgui/scummvm.patch, backends/mixer/sdl/sdl-mixer.cpp, backends/mixer/sdl/sdl-mixer.h, backends/module.mk, backends/mutex/sdl/sdl-mutex.cpp, backends/platform/sdl/amigaos/amigaos.cpp, backends/platform/sdl/macosx/macosx-window.mm, backends/platform/sdl/sdl-sys.h, backends/platform/sdl/sdl-window.cpp, backends/platform/sdl/sdl-window.h, backends/platform/sdl/sdl.cpp, backends/timer/sdl/sdl-timer.cpp, base/commandLine.cpp, configure
This PR modifies the current SDL backend to add SDL3 support.
There are a lot of combinations so don't hesitate to read it carefully and/or test it.
I didn't test the SDL3_net library.
This is the first time I modify the configure file, so have a look and tell me if I need to do some changes (I'm sure you will ;)).
And maybe the way I handled all the `#ifdef` are not at your taste, so feel free to give some advice.
To do this PR I used these recommendations: https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md and of course https://wiki.libsdl.org/SDL3/CategoryAPI
=> BACKENDS: Add SDL3 backend + update imgui

engines/got/game/init.cpp, engines/got/got.cpp
This patch fixes the starting armor for Thor to match the setting in the original game for chapters 2 and 3.
=> GOT: Fix the starting armor for area > 1

engines/qdengine/qdcore/qd_game_dispatcher.cpp, engines/qdengine/qdcore/qd_game_object_moving.cpp, engines/qdengine/qdcore/qd_game_object_moving.h, engines/qdengine/qdcore/qd_game_scene.cpp, engines/qdengine/qdengine.h
- Fix pathfinding problem present in The Adventures of the Good Soldier Schweik
- Add separate debug screen for path drawing
=> QDENGINE: Fix pathfinding slowdown problem

engines/director/debugger/dt-score.cpp
DIRECTOR: DEBUGGER: Generate unique table ids to prevent warnings in channel dialog for fg, bg and script column.
Add PushID and PopID inside for loops for unique ids in tables.
For script column, we check if script id is integer or not, then call the displayScriptRef function.
=> DIRECTOR: DEBUGGER: Generate unique table ids to prevent warnings.

engines/chamber/cga.cpp
Modify ```C++ cga_BackBufferToRealFull()```to support splash screen rendering in HGA mode:
- Split CGA backbuffer into even/odd lines (pages) to match HGA memory layout.
- Double CGA pixel width (4 pixels/byte → 8 pixels/byte) for HGA.
- Center the image within the 720x348 HGA screen buffer.
=> CHAMBER: Fix cga_Blit to support HGA screen rendering

engines/hypno/arcade.cpp, engines/hypno/hypno.cpp, engines/hypno/hypno.h, engines/hypno/wet/arcade.cpp, engines/hypno/wet/wet.cpp
=> HYPNO: fix infinite video playback during missile sequence in wetlands

devtools/create_project/xcode.cpp, dists/scummvm.rc
Add cubemap shaders to `scummvm.rc` and Xcode list. @neuromancer
=> FREESCAPE: add cubemap shaders to configuration lists

engines/wage/combat.cpp, engines/wage/wage.cpp
=> WAGE: Fix missing text and extra newlines

engines/private/funcs.cpp, engines/private/private.cpp, engines/private/private.h
- Allows the player to view what they have done as memories in their diary, sorted by location
- Memories can be clicked to replay the videos associated with them
=> PRIVATE: Track game events in diary

engines/toltecs/menu.cpp, engines/toltecs/metaengine.cpp, engines/toltecs/movie.cpp, engines/toltecs/script.cpp, engines/toltecs/toltecs.cpp, engines/toltecs/toltecs.h
=> TOLTECS: Add keymapper support

engines/stark/detection.cpp, engines/stark/services/settings.cpp, engines/stark/ui/world/dialogpanel.cpp, engines/stark/visual/text.cpp
This add support for Hebrew fan translation of "The Longest Journey"
Thanks
=> STARK: Support Hebrew fan translation

gui/dialog.cpp, gui/dialog.h, gui/dump-all-dialogs.cpp, gui/dump-all-dialogs.h, gui/launcher.cpp, gui/launcher.h, gui/widget.cpp, gui/widget.h, gui/widgets/tab.cpp, gui/widgets/tab.h
This PR implements screenshot generation for the `GlobalOptionsDialog` within the `dumpAllDialogs` tool.
The primary goal is to facilitate automated visual verification of GUI text, especially for translations, ensuring they fit correctly within UI elements across different languages and resolutions.
=> GUI: Implement GlobalOptionsDialog dumping in dumpAllDialogs

engines/sky/control.cpp, engines/sky/control.h, engines/sky/detection.cpp, engines/sky/intro.cpp, engines/sky/logic.cpp, engines/sky/sky.cpp, engines/sky/sky.h, engines/sky/skydefs.h, engines/sky/text.cpp, engines/sky/text.h
This add support for Hebrew fan translation of "Beneath A Steel Sky" based on the freeware release on ScummVM's site
Thanks
=> SKY: Support Hebrew fan translation

engines/scumm/soundcd.cpp
I noticed while testing the Sega CD version that we don't handle audio tracks correctly after loading savegames. See https://bugs.scummvm.org/ticket/15886
There are two problems:
* We don't actually save the track position, but instead figure it out from the music timer. For looping audio tracks, the music timer may already be way past the end of the track.
* Playing a looping track from an offset means that when it loops, it doesn't loop back to the beginning of the track. It loops back to that offset. So we keep looping the end of the track instead of the whole thing.
This is my attempt at improving the situation:
* FM Towns games still do their own handling. That shouldn't have changed.
* Any audio track that's not looping exactly once is restarted from the beginning.
* Audio tracks …
=> SCUMM: Mitigate errors when resuming CD audio after loading a savegame

engines/scumm/script_v5.cpp, engines/scumm/scumm_v5.h
This is a follow-up to previous PR #4178, for Monkey1.
@eriktorbjorn mentioned that the enhancement fixing the continuity error with the Jolly Roger in Part II didn't work with the floppy VGA English.
That's funny, because that's the exact release I used to bring this game script fix (the only official release having any such fix, AFAIK). Except that it seems that LucasArts' own fix was incomplete.
i.e. the buggy v4-v5 releases unconditionally display the Jolly Roger (actor 9) in the entry script of room 87.
The floppy VGA release then adds this check:
```
(48) if (VAR_VIDEOMODE == 4) {
(33)   RoomColor(0,3);
(**) }
(68) VAR_RESULT = isScriptRunning(119);
(A8) if (VAR_RESULT) {
(13)   ActorOps(9,[Init(),Costume(49),Palette(0,6)]);
(5D)   setClass(9,[150,148]);
(11) …
```
=> SCUMM: MONKEY1: Make the Jolly Roger enhancement work on the floppy VGA release

engines/scumm/script_v5.cpp
As described in https://bugs.scummvm.org/ticket/15884 there appears to be a script bug in the Fate of Atlantis copy protection. This is basically what the room-81-204 script does:
```
if (VAR_VIRT_MOUSE_X >= 53 && VAR_VIRT_MOUSE_X <= 261) {
// Check what part of the copy protection stones the mouse is over...
x = (VAR_VIRT_MOUSE_X - 53) / 16;
y = (VAR_VIRT_MOUSE_Y - 21) / 10;
ch = STR35[y * 10 + x]
// ... and act on it
```
So it verifies that the mouse X position is within the copy protection stones, but doesn't care about the Y position. As you move the mouse to the top of the screen, negative indexes become first possible, and then inevitable.
In this particular script, we should return 48 (ASCII for "0") to indicate a non-clickable part of the stones. But anything that isn't 49-56 goes …
=> SCUMM: Add some bounds-checking to o5_stringOps() (bug #15884)

engines/tsage/blue_force/blueforce_logic.cpp, engines/tsage/blue_force/blueforce_scenes1.cpp, engines/tsage/blue_force/blueforce_scenes2.cpp, engines/tsage/blue_force/blueforce_scenes3.cpp, engines/tsage/blue_force/blueforce_scenes5.cpp, engines/tsage/graphics.cpp
=> TSAGE: More accurate surface scaling and fixes for Blue Force

engines/nancy/state/help.cpp
Like the original games. This commit mimics a Main Menu change in 00c7f4d128ec977507728e0154c7f24179ebb129.
=> NANCY: Don't change cursor over Help's Done button

backends/module.mk, backends/platform/sdl/emscripten/emscripten.cpp, backends/platform/sdl/emscripten/emscripten.h, backends/text-to-speech/emscripten/emscripten-text-to-speech.cpp, backends/text-to-speech/emscripten/emscripten-text-to-speech.h, common/text-to-speech.h, configure
This ads Text to Speech to the Emscripten Backend based on the [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API). 
As there's some variance between OS and Browser behaviour, most of the focus ended up being on how to make sure the voice selection makes sense. I had to make the description changeable to this effect.
Small demo video:
https://github.com/user-attachments/assets/69889486-9250-4c54-9bb7-6d58430fedbe
=> EMSCRIPTEN: TTS: Add TTS based on Web Speech API

backends/fs/atari/atari-fs-factory.cpp, backends/fs/atari/atari-fs-factory.h, backends/fs/atari/atari-fs.cpp, backends/fs/atari/atari-fs.h, backends/fs/posix-drives/posix-drives-fs-factory.h, backends/fs/posix/posix-fs.cpp, backends/module.mk, backends/platform/atari/build-release.sh, backends/platform/atari/build-release.sh.in, backends/platform/atari/build-release030.sh, backends/platform/atari/build-release030.sh.in, backends/platform/atari/osystem_atari.cpp, backends/platform/atari/readme.txt, backends/platform/atari/readme.txt.in, common/path.cpp
This is my follow-up of https://github.com/scummvm/scummvm/pull/6608. 
This is mainly to make sure that my changes to `backends/fs/posix/posix-fs.cpp` are acceptable or whether you have a better idea for implementation.
=> BACKENDS: ATARI: Introduce AtariFilesystemNode 

engines/qdengine/minigames/adv/RunTime.cpp, engines/qdengine/minigames/adv/RunTime.h, engines/qdengine/minigames/adv/m_puzzle.cpp, engines/qdengine/minigames/adv/m_puzzle.h, engines/qdengine/minigames/adv/m_scores.cpp, engines/qdengine/minigames/adv/m_scores.h, engines/qdengine/minigames/adv/m_swap.cpp, engines/qdengine/minigames/adv/m_swap.h, engines/qdengine/minigames/adv/m_triangles.cpp, engines/qdengine/minigames/adv/m_triangles.h, engines/qdengine/qdcore/qd_minigame.cpp, engines/qdengine/qdengine.cpp
- Make it possible to instantiate multiple MinigameManagers'
- Implement minigames for dogncat games
=> QDENGINE: Add support for adv minigames

engines/wintermute/base/base_game.cpp, engines/wintermute/base/gfx/base_image.cpp, engines/wintermute/base/gfx/base_image.h, engines/wintermute/base/gfx/base_renderer.h, engines/wintermute/base/gfx/base_renderer3d.cpp, engines/wintermute/base/gfx/base_renderer3d.h, engines/wintermute/base/gfx/opengl/base_render_opengl3d.cpp, engines/wintermute/base/gfx/opengl/base_render_opengl3d.h, engines/wintermute/base/gfx/opengl/base_render_opengl3d_shader.cpp, engines/wintermute/base/gfx/opengl/base_render_opengl3d_shader.h, engines/wintermute/base/gfx/osystem/base_render_osystem.cpp, engines/wintermute/base/gfx/osystem/base_render_osystem.h, engines/wintermute/base/save_thumb_helper.cpp, graphics/surface.cpp, graphics/surface.h
=> WINTERMUTE: Reduce the number of surface copies when taking screenshots

engines/mm/xeen/spells.cpp
Fix what looks like small typo. 
Also should close https://bugs.scummvm.org/ticket/15249 .
=> XEEN: Fix protection from elements spell

engines/sludge/sound.cpp
This is used for a couple of sounds in the arcade in The Game That Takes Place On a Cruise Ship.
=> SLUDGE: Support MP3 sound files

engines/voyeur/animation.cpp, engines/voyeur/files_threads.cpp, engines/voyeur/metaengine.cpp, engines/voyeur/voyeur.cpp, engines/voyeur/voyeur.h
=> VOYEUR: Add keymapper support

engines/cruise/backgroundIncrust.cpp, engines/cruise/cell.cpp, engines/cruise/cruise.cpp, engines/cruise/cruise.h, engines/cruise/cruise_main.cpp, engines/cruise/detection.cpp, engines/cruise/detection.h, engines/cruise/font.cpp, engines/cruise/function.cpp, engines/cruise/menu.cpp, engines/cruise/metaengine.cpp, engines/cruise/overlay.cpp
Adds a toggle for text-to-speech to the game options.
- Copy protection screen
- Credits
- Menus
- Dialog
- Command information
- Cutscene text
- Map locations
=> CRUISE: Add text-to-speech (TTS)

engines/awe/engine.cpp, engines/awe/sfx_player.cpp, engines/awe/sound.cpp, engines/awe/sound.h
This little pull request is a proposed implementation of the original music, more specifically the `playSfxMusic` method.
=> AWE: Implement playSfxMusic

devtools/dumper-companion.py
* Fix warnings from pylance
* Fix typing errors from mypy
* Simplify check_extension and search_encoding_parameter functions
* Format using black
=> DEVTOOLS: dumper_companion - Numerous fixes and cleanups

engines/cruise/cruise.cpp, engines/cruise/overlay.cpp
=> CRUISE: Fix TTS encoding, empty text queuing, and logo speech

engines/ngi/messagehandlers.cpp, engines/ngi/metaengine.cpp, engines/ngi/modal.cpp, engines/ngi/modal.h, engines/ngi/ngi.cpp, engines/ngi/ngi.h
=> NGI: Add keymapper support

engines/director/castmember/text.cpp, engines/director/castmember/text.h, engines/director/debugger.cpp, engines/director/detection_tables.h, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/lingo-events.cpp, engines/director/lingo/xtras/rtk.cpp, engines/director/movie.h
=> DIRECTOR: Fixes for Cracking the Conspiracy

engines/teenagent/inventory.cpp, engines/teenagent/metaengine.cpp, engines/teenagent/scene.cpp, engines/teenagent/teenagent.cpp, engines/teenagent/teenagent.h
=> TEENAGENT: Add keymapper support

doc/docportal/other_platforms/playstation_vita.rst
For context : https://github.com/scummvm/scummvm/pull/6783
=> DOCS: Update PS Vita doc to fix crashes on suspend

engines/draci/animation.cpp, engines/draci/detection.cpp, engines/draci/detection.h, engines/draci/draci.cpp, engines/draci/draci.h, engines/draci/game.cpp, engines/draci/game.h, engines/draci/metaengine.cpp, engines/draci/script.cpp
Adds toggles for text-to-speech to the game options.
- Subtitles
- Objects
- Inventory items
- Dialog options
- Map locations
- Credits
=> DRACI: Add text-to-speech (TTS)

engines/access/POTFILES, engines/access/access.cpp, engines/access/access.h, engines/access/amazon/amazon_game.cpp, engines/access/amazon/amazon_logic.cpp, engines/access/events.cpp, engines/access/events.h, engines/access/martian/martian_game.cpp, engines/access/martian/martian_scripts.cpp, engines/access/metaengine.cpp, engines/access/room.cpp, engines/access/scripts.cpp, engines/access/video/movie_decoder.cpp
=> ACCESS: Add keymapper support

engines/prince/POTFILES, engines/prince/cursor.cpp, engines/prince/detection.cpp, engines/prince/detection.h, engines/prince/draw.cpp, engines/prince/inventory.cpp, engines/prince/metaengine.cpp, engines/prince/mob.cpp, engines/prince/prince.cpp, engines/prince/prince.h, engines/prince/script.cpp, engines/prince/sound.cpp
Adds toggles for text-to-speech to the game options.
- Subtitles
- Dialog options
- Objects when hovered over
- Options menus
=> PRINCE: Add text-to-speech (TTS)

audio/mixer.cpp, audio/mixer.h, audio/mixer_intern.h, engines/director/lingo/lingo-builtins.cpp, engines/director/lingo/tests/math.lingo, engines/director/lingo/xlibs/voyagerxsound.cpp, engines/director/lingo/xlibs/voyagerxsound.h, engines/director/sound.cpp, engines/director/sound.h
=> DIRECTOR: Fixes for Puppet Motel

backends/platform/sdl/psp2/psp2-main.cpp, backends/platform/sdl/psp2/psp2.mk, configure
vitagprof is a library to get working gprof profiling on vita
https://github.com/Aztorius/vita-gprof
=> PSP2: Add profiling support with vitagprof

engines/neverhood/POTFILES, engines/neverhood/gamemodule.cpp, engines/neverhood/gamemodule.h, engines/neverhood/menumodule.cpp, engines/neverhood/metaengine.cpp, engines/neverhood/neverhood.cpp, engines/neverhood/neverhood.h
=> NEVERHOOD: Add keymapper support

engines/queen/input.cpp, engines/queen/input.h, engines/queen/journal.cpp, engines/queen/journal.h, engines/queen/metaengine.cpp, engines/queen/queen.h
=> QUEEN: Add keymapper support

engines/queen/metaengine.cpp
=> I18N: QUEEN: Fix capitalization in keymapper action description

engines/pink/POTFILES, engines/pink/metaengine.cpp, engines/pink/objects/actors/lead_actor.cpp, engines/pink/objects/actors/lead_actor.h, engines/pink/pink.cpp, engines/pink/pink.h
=> PINK: Add keymapper support

engines/drascula/animation.cpp, engines/drascula/converse.cpp, engines/drascula/drascula.cpp, engines/drascula/drascula.h, engines/drascula/graphics.cpp, engines/drascula/interface.cpp, engines/drascula/metaengine.cpp, engines/drascula/saveload.cpp, engines/drascula/talk.cpp
=> DRASCULA: Add keymapper support

engines/chamber/POTFILES, engines/chamber/chamber.h, engines/chamber/input.cpp, engines/chamber/metaengine.cpp
=> CHAMBER: Add keymapper support

engines/got/views/credits.cpp
=> GOT: Fix potential out-of-bounds access

engines/director/castmember/digitalvideo.cpp, engines/director/detection_tables.h, engines/director/lingo/lingo-object.cpp, engines/director/lingo/xlibs/xplaypacoxfcn.cpp, engines/director/lingo/xlibs/xplaypacoxfcn.h, engines/director/module.mk, engines/director/resource.cpp, engines/director/window.cpp, engines/director/window.h
=> DIRECTOR: Fixes for The Journeyman Project

engines/petka/metaengine.cpp, engines/petka/petka.cpp, engines/petka/petka.h, engines/petka/q_system.cpp
=> PETKA: Add keymapper support

engines/private/POTFILES, engines/private/metaengine.cpp, engines/private/private.cpp, engines/private/private.h
=> PRIVATE: Add keymapper support

engines/agi/detection_tables.h
=> AGI: Add detection entry for KQ1 Hebrew

engines/bagel/mfc/afxwin.h
I tried several tricks to have proper type checking instead of bluntly casting to some generic pointer, but it failed.
Here is a proposal to shut the warnings instead: this starts just before the offending macros are inserted and ends just after.
=> BAGEL: Silence GCC warnings when creating message maps

engines/agi/detection_tables.h
My partners did some testing on the game and I had to change the checksum.
=> AGI: update KQ1 hebrew funmade checksum

engines/director/detection_tables.h
DIRECTOR: add detection entries for "Peter endeckt die Steinzeit" and "Fliegen, Flattern, Flugmaschinen"
=> DIRECTOR: add detection entries for "Peter endeckt die Steinzeit" and "Fliegen, Flattern, Flugmaschinen"
