engines/director/score.cpp
engines/director/score.h
engines/director/types.h

This patch adds simple pixel-by-pixel comparison of screenshots between builds. It is helpful to detect regressions in graphics rendering.

DIRECTOR: Improve screenshot comparison of previous builds

---

common/fs.cpp
common/macresman.cpp

These broke in the archive refactor, b8acbe6bee730a9024e73acc769b54285be9afde/#5108, because it removed the ability to directly convert an `ArchiveMember` to an `FSNode`. There also isn't a way to get full non-relative paths anymore, which is what the `FSNode` cast was doing before; it made it possible to just get the raw path on disk and turn it into the magic path to the resource fork.
This is based on an approach suggested by @elasota, to make use of the existing archive code by making the archives aware of the resource forks. I'm not 100% sold mainly because it feels awkward to me - the rest of the code is based on iterating the actual filesystem, but resource forks aren't "real" files and can't be listed/iterated the same way real files are. That means it instead has to manually …

COMMON: fix MacResManager native resource forks

---

engines/director/lingo/lingo-events.cpp

This patch fixes the behaviour of having both scoped and scopeless lingo in the same score script. It has been observed that movies created with D3.1 that uses scopeless lingo can be ported to D4, in which case the scopeless lingo is executed first, before the scoped lingo. (for example in `put "abc" enterFrame put "enter" end`, abc will be printed first, then enter)
Fix the problem where frames in certain `totaldistortion-win` movies are played spontaneously because enterFrame handlers are not called due to scopeless statements contained in the movie.
--start-movie="ATD/HD/FISMH2H6.DXR"@50 totaldistortion-win

DIRECTOR: LINGO: Scoped and scopeless lingo score

---

engines/mohawk/myst_graphics.cpp

Fading in and out is a simple palette-based effect, but can be very slow on backends that exclusively use true colour.

MOHAWK: MYST: Skip fade steps on slower machines

---

engines/director/director.cpp
graphics/macgui/macwindowmanager.cpp
graphics/macgui/macwindowmanager.h

This patch sets the flag background for score (or main director engine window, It is useful because it prevents the window from jumping to front of other windows (ie from `open` command) and thus shadowing it.
Fixes `title of window` from workshop, where clicking outside opened window used to disappear it beneath the main window.
Also fixes 'totaldistortion-win' sequencer TV, when clicking anywhere except the TV screen, the window used to disappear.

DIRECTOR, GRAPHICS: MACGUI: Background director window!

---

devtools/create_project/create_project.cpp

Not sure why this is even a warning since the whole point of the alignment specifier is to pad if the structure is misaligned, but it is, so this turns the warning off.
This is triggering from the PROCESS structure introduced in `common/coroutines.h`

CREATE_PROJECT: Quiet VS "structure was padded due to alignment specifier" warning

---

engines/glk/zcode/detection_tables.h

GLK: ZCODE: Changes formatting style in detection_tables.h
This quick PR (only 60% complete) essentially adds no new content; it only updates the formatting style of detection_tables.h according to the following ideas:
1. 
An uniform use of whitespaces for vertical columns: IDEs usually start with a cursor in a `1` position so... first column (gameID) at 5th position, second column (gameTitle) at 29th position and third column (if present) at 105th position
2.
An uniform style while capitalizing titles: I've choosen Wikipedia formatting guideline.
3.
An uniform use of subtitles: no subtitile just to be sure. They are not always used even if present and different from the standard "An Interactive Fiction"
Example:
```
Detention
An attempt to escape from school by Hayden Ramm
Release 1 / …
```

GLK: ZCODE: Changes formatting style in detection_tables.h

---

engines/sci/detection_tables.h

This adds detection entry for the upcoming hebrew fan translation of Eco Quest
the patch will soon be available on https://github.com/adventurebrew/HebrewAdventurey

SCI: Detect hebrew fan translation of Eco Quest

---

engines/director/score.cpp
engines/director/window.cpp
engines/director/window.h

In the original engine, the enterFrame handler can only be called recursively upto second depth, and the third call will be ignored. This was formerly implemented by counting number of frozen lingo states, however there are cases where the lingo state is frozen, while enterFrame handler not called, so the count is not accurate.
This patch improves the logic by counting the number of enterFrame in frozen lingo states as well, so it can be identified that these previous frames are indeed of `enterFrame` handler.
Fixes bug where the elevator when jumping to next floor (yellow one) broke dimensional movement in `totaldistortion-win`.

DIRECTOR: Improve checking for recursive enterFrame

---

audio/softsynth/eas.cpp
base/plugins.cpp
base/version.cpp
configure

Following on from the discussion in #1815, this PR allows all platforms to build with the EAS driver using this fork of the libsonivox library: [pedrolcl/sonivox](https://github.com/pedrolcl/sonivox).
Notes
- Only Linux/x64 has been tested so far.
- The old code for dynamically loading the system `libsonivox.so` on Android has been retained for now, but can potentially be removed in the future.
- The driver has not yet been updated to make use of the newer API for `EAS_LoadDLSCollection`.

AUDIO: Support building the EAS MIDI driver on non-Android platforms

---

backends/platform/sdl/win32/win32-main.cpp
backends/plugins/win32/win32-provider.cpp

In 2006, a refactor removed the only reference to Win32PluginProvider: df5be194098e188f9cd3234af2bea34b67d19da2
Instead, SdlPluginProvider became the provider used in Window builds. It's unclear if the intent really was to disable Win32PluginProvider, as we've been maintaining it ever since.
The two classes are small and effectively do the same thing, but Win32PluginProvider has the advantage of using our Windows string conversion functions for paths, just like the rest of backend code. We've seen problems before where SDL handles encoding differently: 0ab9653556f837ced66f73de8499170dcd3079be

WIN32: Re-enable Win32PluginProvider

---

engines/sci/graphics/video32.cpp
engines/sci/graphics/video32.h
video/subtitles.cpp
video/subtitles.h

This allows reading subtitles from SRT files during videos in SCI32 games,
specifically Phantasmagoria and Phantasmagoria 2.
Some notes:
- Subtitles filenames have both the extension of the video and srt extension (e.g. `30.vmd.srt`, to prevent case of having e.g. twice 30.srt for two different video types... I am not sure if games may have the same number there or not.
- I have considered limiting the subtitles to the video display area (which is usually smaller then the whole screen, but it had issues when using OpenGL renderer (different place when resizing differently)
- Might be possible (and better) to utilize the mechanism used by Gabriel Knight 2 Subtitle patch instead
- Perhaps the drawing of subtitles should be delegated to the game itself somehow, so the TTF font rendering on …

SCI: Show SRT subtitles on SCI32 videos

---

engines/tinsel/events.cpp
engines/tinsel/token.cpp

Add extra bools to track token status. This allows setting
the owner to nullptr when a token is acquired from a
non-coroutine context / nullContext without marking it as free.
Fixes the following assert in Discworld 1 (see [#13220](https://bugs.scummvm.org/ticket/13220)):
After using the matches on the drainpipe to get the golden chimney
brush, the game switches to non-interactive scenes twice.
When changing back to the original scene, player control should be
disabled while a short animation plays, but this is not the case.
A mouse click by the player during this animation will then initiate
a walk action and cause a failed assert:
```
engines/tinsel/events.cpp:280:
void Tinsel::WalkProcess(Common::CoroBaseContext*&, const void*):
Assertion `_ctx->pMover->hCpath != NOPOLY' failed.
``` …

TINSEL: Fix token function calls from non-coroutines

---

backends/cloud/storage.cpp
backends/networking/sdl_net/localwebserver.cpp
backends/platform/ios7/ios7_osys_main.cpp
backends/platform/ios7/ios7_osys_main.h
backends/platform/ios7/ios7_osys_video.mm
common/system.h
gui/downloadpacksdialog.cpp

This pull request implements the following:
1. Add new `taskStarted` and `taskFinished` in `OSystem` to notify the backend when starting of finishing a task.
2. Call this new function in the following cases:
1. Running the local web server
2. Downloading games or savegames from the cloud.
3. Download icons and shaders pack.
3. Implement this in the iOS backend to prevent sleep while one of those task is running.
I was also trying to use this to keep the network tasks running in background, which is required for example for the cloud quick connection wizard (as it starts the local web server, and then opens safari which needs to connect to the local web server now in background). But I cannot seem to get this working, so I did not include the code in this pull request.
Also I need to do …

Prevent sleep on iOS while the local web server is running or ScummVM is downloading files

---

engines/scumm/script.cpp
engines/scumm/script_v6.cpp

When playing Backyard Football online, by default only 31 to 35 of the 38 playable characters are draftable in a given game. A random 3 to 7 are not shown sitting in the bleachers when drafting. This makes competitive play difficult, as the draft pool is not the same each game.
This mod, which is only active when the "Online competitive mods" option is enabled, allows all 38 characters to be shown on the draft screen.

SCUMM HE: Football online mod: Show full bench when drafting

---

common/archive.cpp
common/archive.h

Added check in `Archive::dumpArchive()` to determine if there is not enough storage left. 
Also, changed the return type to `Common::Error` to handle different error scenarios.

COMMON: Handle writing failure in dumpArchive when not enough storage

---

engines/director/score.cpp
engines/director/score.h

This PR:
1. Refactor frames loading to remove rebuildChannelData
2. Improves loading time by loading spriteCast only when required
3. Fix `chan` debugger command!

DIRECTOR: Refactor frames loading, Fix `chan` debugger command!

---

backends/platform/android/android.cpp
backends/platform/android/android.h
backends/platform/android/module.mk
configure

Fix the build by building cpu-features which is only provided as source in NDK.
As it's a C file and we don't set up a C compiler, make the C++ compiler (clang++) fallback on C and select proper standard.
Make the detection more static: architecture is determined at build time and don't try to cache the detection result.
cpu-features already caches it and our code is called only once: the first time blitting is used.
SSE2 is mandatory on Android x86 NDK so is expected to be always available.
It's also always available on x86_64 per specification of instruction set.
NEON is always available on armv8 which is the base of aarch64. This saves us some detection.

ANDROID: Fix build and improve SIMD detection

---

configure
graphics/module.mk

aarch64 doesn't need it and it fails to build with GCC when it's present
Enable NEON by default on Android

GRAPHICS: Use -mfpu=neon flag only on armv7

---

engines/stark/resources/textureset.cpp

STARK: Fix bug #14482 Texture mods with unusual names not loading
Addresses the following bug by re-encoding the special character causing it:
https://bugs.scummvm.org/ticket/14482

STARK: Fixes bug #14482 Texture mods with unusual names not loading

---

engines/sherlock/talk.cpp

Fixes [#14580](https://bugs.scummvm.org/ticket/14580)

SHERLOCK: RT: Cancel scene transition when interrupted by script

---

engines/gob/dataio.cpp

This leads to a massive speedup on atari: between the credits screen and the actual game loading takes 3m30s (!) on a 66 MHz machine, with this change it takes 5s (!!!)
I think the reason why nobody has noticed so far is that glibc (etc) implementation of fseek() contains an optimisation for `0, SEEK_CUR` and `<current offset>, SEEK_SET` respectively, i.e. that it doesn't really seek in such case.
I hope I got it right, that `0xFFFF` worries me a little but should be harmless with my changes. The only problem I can see is that if some part of code expects to read from a chunk _and not finish it_ (not sure whether that can happen but current code supports it) -- my change reads the whole chunk at once.

GOB: Preload chunk before unpacking

---

backends/platform/ios7/ios7_osys_misc.mm

IOS: Support keyboard hardware input set
The iOS backend currently supports a virtual keyboard, but none of the keyboard controls are mapped according to the
default mapping of a game. Only the mouse controls and a game controller (if connected) are registered as a hardware
input set currently.
This change adds the keyboard hardware as an input set so that the default controls are mapped, and the user can
use the virtual keyboard to perform actions like opening a game option menu in Blade Runner, for example.
The remapping of keys using the virtual controls is not working reliably on iOS currently, possibly due to the polling 
handling. This can be investigated further and addressed later, but having the default controls mapped is a start.

IOS: Support keyboard hardware input set

---

gui/widgets/editable.cpp

Clear the selection after deleting a character.
Not doing so can result in out-of-bounds reads in
`EditTextWidget::drawWidget()`, where `_selCaretPos` and `_selOffset` are used as offsets, and to a failed assertion when calling `EditableWidget::defaultKeyDownHandler()`:
```
gui/widgets/editable.cpp:566:
bool GUI::EditableWidget::setCaretPos(int):
Assertion `newPos >= 0 && newPos <= (int)_editString.size()' failed.
```
Fixes [#14584](https://bugs.scummvm.org/ticket/14584)

GUI: EditableWidget: Clear selection when handling backspace/delete

---

backends/platform/android/android.cpp
backends/platform/ds/ds-graphics.cpp
backends/platform/ds/portdefs.h
backends/platform/ios7/ios7_osys_main.cpp
backends/platform/wii/osystem.cpp
common/system.h
engines/lure/menu.cpp

This pull request adds the `kFeatureTouchscreen` enum value to `OSystem` to allow backends to indicate that they use a touchscreen. This is currently done in the iOS, Android, DS, and Wii backends (the ones that defined the `LURE_CLICKABLE_MENUS` define).
Another commit use this new feature in the lure engine to replace the `LURE_CLICKABLE_MENUS` define.
I imagine that other engines could make use of it to adapt their controls to be more adapted to touchscreens.
I also have in mind that it could for example be used in the `GUI::ScrollContainerWidget`, in the `ListWidget`, and in the `GridWidget` to allow scrolling with a left mouse button press and drag on the widget (and not just on the scrollbar). Maybe other widgets could also benefit from it.
@larsamannen, I think you had an …

Add kFeatureTouchscreen to OSystem to identify backends with a touchscreen

---

engines/scumm/he/mixer_he.cpp
engines/scumm/he/mixer_he.h

Detected by GCC 13:
```
mixer_he.cpp:278:15: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct Scumm::HEMixer::HEMixerChannel'; use assignment or value-initialization instead [-Wclass-memaccess]
278 |         memset(_mixerChannels, 0, sizeof(_mixerChannels));
|         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

SCUMM: HE: Fix initialization of mixer channels

---

engines/director/lingo/lingo-builtins.cpp

Horror Tour 2 occasionally calls this with one void argument. It looks like a bug in the original game, but one that original Director doesn't crash on.
It's usually called correctly, but there's a couple places where it ends up being called with a `void` argument.
```
[   16] c_argcpush 1
[   18] cb_call "soundBusy"
```
Not sure if simply hardcoding channel 1 is the right approach though.

DIRECTOR: handle void argument to soundBusy

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h

This moves the class definition out of the global namespace.

SURFACESDL: Move the AspectRatio class into the graphics manager class

---

engines/sword25/gfx/dynamicbitmap.cpp
engines/sword25/gfx/image/renderedimage.cpp
engines/sword25/gfx/image/renderedimage.h

This should provide a performance advantage when playing Theora videos, which don't provide an alpha channel. A potential bug was also fixed with the existing code - `checkForTransparency()` was only run on little endian CPUs, where it would incorrectly examine the red component of each pixel instead of the alpha component.

SWORD25: Add support for opaque blending modes

---

engines/pink/gui.cpp
engines/pink/pink.cpp
engines/pink/pink.h

This is aimed at and tested for the German Demo menu of Passport to Peril
In the original demo (ran with Windows 3.11), the menu item for "Songs" is missing from the menu. In this fix we disable it (greyed out) because the code for removing an item from the menu causes shifting of the subsequent menu items which leads to unreliable code and potential future bugs if it's not accounted for.
I should clarify that clicking on the Songs menu item in the demo crashes the engine with assert fault at https://github.com/scummvm/scummvm/blob/6c954858dfcf88b4ebb01f0b53cf183a38c3367a/engines/pink/file.cpp#L104
Potential issues to consider with this approach:
- Could there be other demos of Passport to Peril that support this Music item? This fix, as is, applies to any demo for Passport to Peril, and …

PINK: Disable the Songs entry from the demo menu

---

gui/gui-manager.cpp

This matches also the behavior as set in engines/metaengine.cpp MetaEngine::initKeymaps()
This change is needed at least to avoid a hack on Android. Setting the "kdbRepeat" flag for events of keeping the arrow keys pressed (on the touch virtual keyboard), as Android supports, would not work to eg. keep going through a list upwards or downwards with the respective arrow key pressed. Instead we had to emulate the behavior of a physical keyboard which sents multiple keypresses (keydown and keyup events), without setting the kbdRepeat flag. However, this hack would work poorly in some game engines (eg. in LBA while rotating Twinsen, the movement becomes "stuttering"). In-games the kbdRepeat flags is respected already due to the setting in engines/metaengine.cpp (as far as I can tell) and …

GUI: Add allowKdbRepeats() to up/down/left/right actions in launcher

---

common/str-base.cpp
common/str-base.h

This is mainly a QOL change for debugging in Visual Studio but also a minor performance optimization.
By default the keybinds for debugging in Visual Studio are F11 to Step Into, F10 to Step Over, Shift-F11 to Step Out.  It's nice to be able to just use Step Over and Step Into because they don't require an awkward 2-button keystroke.  Step Out is also prone to randomly misbehaving with optimizations on because it doesn't work properly with inlined function calls.
Attempting to step into a call that requires an implicit conversion of a char string to a `Common::String` frequently lands in the `BaseString` constructor that has its own strlen-like loop, which is slow to step through so it would be nice to be able to skip over it with just one Step Over keystroke.
This moves the string length …

COMMON: Move string length calculation to a separate function for nicer debugging

---

audio/mididrv.cpp
base/commandLine.cpp
gui/options.cpp

This mainly came about because Obsidian uses QuickTime MIDI originally, and Windows MIDI (while not amazing) is much closer to the QuickTime MIDI sound font than AdLib.  However, by default the `MDT_PREFER_GM` flag does nothing because the default GM device is "null" (a.k.a. "Don't use General MIDI music").
I discussed a few possible scenarios with @athrxx :
- If a game prefers using AdLib to GM, then it can just not pass `MDT_PREFER_GM` to `detectDevice` and it will get AdLib instead even when a GM device is configured.
- If a user wants to force a GM device even when the game isn't using `MDT_PREFER_GM`, they can set it as the music device in the "Audio" tab (or "music_driver" config option).
- If there is a problem with a GM device, then `detectDevice` should skip it if `checkDevice` …

AUDIO: Change default GM device to "auto"

---

configure

Silently ignore `--runstatedir` flag, which was introduced in Autoconf 2.70.

CONFIGURE: Ignore --runstatedir

---

engines/ultima/ultima8/misc/debugger.cpp
engines/ultima/ultima8/misc/debugger.h

In efforts to be sure changes in #5288 do not adversely effect performance, I made a quick benchmark command for the GUI debugger.
I don't think I could easily use unit tests to benchmark this currently, although that may be worth investigating further. Is there a better way to do this type of test?
I think I would need a larger sampling to claim improvement in that PR, but here's the current stats.
RenderSurface::benchmark 1 2 50000
Current:
[2023-08-26 17:04:18] Paint: 233
[2023-08-26 17:04:18] PaintNoClip: 211
[2023-08-26 17:04:18] PaintTranslucent: 258
[2023-08-26 17:04:19] PaintMirrored: 267
[2023-08-26 17:04:23] PaintInvisible: 3975
[2023-08-26 17:04:26] PaintHighlight: 2626
[2023-08-26 17:04:30] PaintHighlightInvis: 4198
PR 5288:
[2023-08-26 16:44:04] Paint: 229
[2023-08-26 …

ULTIMA8: Add debugger command to benchmark shape frame painting

---

engines/ags/lib/allegro/surface_neon.cpp
engines/ags/tests/test_gfx.cpp

The SIMD optimizations on the AGS engine wouldn't compile under iOS or Android because they used 16bit fp math intrinsics that weren't supported on that hardware. Now the optimizations only use 32bit math.

AGS: GRAPHICS: NEON only uses 32bit fp math now

---

backends/fs/abstract-fs.cpp
backends/fs/abstract-fs.h
backends/fs/posix/posix-fs.cpp
backends/fs/posix/posix-fs.h
common/archive.cpp
common/archive.h
common/compression/gentee_installer.cpp
common/compression/stuffit.cpp
common/compression/vise.cpp
common/formats/prodos.cpp
common/formats/prodos.h
common/fs.cpp
common/fs.h
common/macresman.cpp
engines/grim/lab.h
engines/mm/shared/utils/engine_data.cpp
engines/mtropolis/boot.cpp
engines/stark/formats/xarc.cpp
engines/ultima/shared/engine/data_archive.cpp
engines/wintermute/base/file/base_file_entry.cpp
engines/wintermute/base/file/base_file_entry.h

This sort of redoes PR #5189 to use an alternate stream API instead of having to handle the FS quirks of named streams on OSX.
This attempts to ensure that a stream is always openable for a file that exists even if it's empty, so opening an empty data fork from a StuffIt or VISE archive returns an empty memory stream instead of nullptr.

COMMON: Add alternate stream support for Mac resource forks and Finder info

---

engines/sword1/control.cpp
engines/sword1/control.h
engines/sword1/eventman.cpp
engines/sword1/logic.cpp
engines/sword1/logic.h
engines/sword1/mouse.cpp
engines/sword1/screen.cpp
engines/sword1/screen.h
engines/sword1/sound.cpp
engines/sword1/sound.h
engines/sword1/sword1.cpp
engines/sword1/sword1.h
engines/sword1/sworddefs.h

Ahoy! This is the first one of a series of changes and PRs which aim at finishing and implementing all those things from the original Broken Sword 1 executable which we are currently missing in our implementation. We have a great port of the engine and it would be a shame not to finish those last tasks; after all the devil is in the details 🙂
A full list can be seen here: https://wiki.scummvm.org/index.php?title=Sword1
In this first part I have implemented accurate palette fade-ins and fade-outs. In order to achieve this, one of the necessities was to fix the game timers, which was part of the to-do plan anyway.
Also, I implemented fast and slow modes from the original debug commands because at one point I was going insane debugging this 🙂 
All of this was implemented from the original …

SWORD1: Implement palette fades

---

backends/platform/null/null.cpp
test/common/str-helper.h
test/common/str.h
test/null_osystem.cpp

This PR contains two things:
- it makes warnings silent by default in tests as the INI tests and blending are quite spammy while their output isn't really useful while just checking if tests are good.
- it also adds a pretty-printer for Common::String. This allows to display the string content instead of raw bytes of the class.

TEST: Improve tests

---

gui/widgets/grid.cpp

Fixes [#14551](https://bugs.scummvm.org/ticket/14551)

GUI: GridWidget: Fix loss of focus when typing in the search box

---

backends/platform/ios7/ios7_osys_main.cpp
configure
devtools/create_project/create_project.cpp
devtools/create_project/xcode.cpp
engines/ags/lib/allegro/surface_neon.cpp
graphics/blit/blit-neon.cpp

This PR enables SCUMMVM_NEON for iOS/tvOS, simulators running on x86_64 excluded.
It also add extra preprocessor checks that ARM_NEON really is available if SCUMMVM_NEON is set.
To allow for Arm NEON optimisations SCUMMVM_NEON, __ARM_NEON__ or __ARM_NEON have to be defined.
Else it will bail out do use the default non-optimised functions.
Replaces https://github.com/scummvm/scummvm/pull/5286

IOS7: Utilise Arm Neon optimisation 

---

engines/engine.cpp

Without the below it shows the splash in the resolution `initGraphics3d()` was called with, there's probably a proper way to fix this but I'm not familiar enough with the code base.
```c++
Common::Event event;
g_system->getEventManager()->pollEvent(event);
```

ENGINES: Show splash screens on 3D engines

---

engines/tetraedge/game/in_game_scene.cpp

Fixes missing textures caused by empty path returned from Common::Path::getParent().
https://bugs.scummvm.org/ticket/14418

TETRAEDGE: Fix missing scene object textures.

---

engines/director/cursor.cpp

Fixes a bug introduced in 9aa095873683b990ac85b4c06b5fa843dcbd682a. That commit limited reading cursors to open res files, not all *seen* res files. However, that broke the custom cursor in Small Stories for Sleepless Nights for Mac (nemurenu-mac-ja), which stores its cursor in the game's main archive which is already closed at the time the cursor gets loaded.
I scoped this to Mac right now because that's the platform I encountered this on, and the other branches are specific to Windows. However, I'm not sure if this behaviour is actually Mac-specific. @sev- also suggested that possibly the main cast should always be present in `_allOpenResFiles`.
Broken:
Fixed:

DIRECTOR: fix loading cursor from main archive

---

engines/tinsel/saveload.cpp

MAX_SOUNDREELS was increased from 5 to 10 in commit [40f57bd67b6cc3c5b106b0f6f297d466f90dc972](https://github.com/scummvm/scummvm/commit/40f57bd67b6cc3c5b106b0f6f297d466f90dc972).
When loading an old save with less than 10 reels, the remaining ones are currently not reset. (The global holding the reels (Tinsel::g_soundReels) is, but the buffer the data is loaded into (static Tinsel::SAVED_DATA Tinsel::g_sgData) is not. Its contents are then memcpy'ied over).
This might only be a theoretical problem, since it would require creating/loading a save with more than 5 active reels first before then loading a save in the old format.

TINSEL: Initialize remaining sound reels when loading old save

---

engines/access/inventory.cpp

Clamp bounding box to valid dimensions when copying to the screen surface during item dragging.
Fixes [#14617](https://bugs.scummvm.org/ticket/14617)

ACCESS: Fix crash on inventory item dragging in Amazon: GoE

---

gui/widget.cpp

This makes it so that half the space before and after a slider value is assigned to that value
Currently for sliders with small value range, the whole space between two consecutive values on the slider is "assigned" to the lower value. Hence, the only ways to set the slider to the highest value is to either use the mouse wheel scroll, or click and drag, or click at a pixel of the far edge of the slider, which is hard to do especially with direct touch interface. 
This PR addresses the final option, making it a bit easier to get the final value when using simple clicks or direct touch. It still uses integer division to get the slider value from the click position, but "divides" the space between two values in half, assigning the first half to the left (smaller) value and the right half to …

GUI: Increase position range for a slider value

---

engines/sci/engine/scriptdebug.cpp

Followup patch from a few weeks ago that only affects debug logging when disassembling SCI scripts.
These opcodes weren't showing up with their selectors in all scenarios
Improves output formatting.
Sample output:
```sh
0048:03cc: 0x76,                                // push0			;y
0048:03cd: 0x78,                                // push1			;x
```

SCI: tweak to scriptdebug.cpp disassembler logic because the new logging wasn't quite working.

---

engines/tinsel/polygons.cpp

`for`'s condition is evaluated after the expression(s) so we ended up reading invalid memory in ptp (`numPoly` == 1 so basically it crashed by the end of first loop).
Strangely this corruption has been visible only in DW demo, with asserts enabled and it seems (judging from the lack of similar reports) only on my m68k atari backend.
I couldn't think of a more elegant solution without rewriting too much code.

TINSEL: Fix out-of-bounds memory corruption

---

common/archive.cpp
common/archive.h
common/compression/unzip.cpp
common/fs.cpp
common/fs.h
common/str.cpp
engines/sword25/package/packagemanager.cpp

This adds a few new functions:
- `Archive::isPathDirectory`: Returns true if a specified path is a directory
- `ArchiveMember:isDirectory`: Returns true if the archive member is a directory
- `ArchiveMember::listChildren`: Lists the children of an archive member
This also introduces some potentially-breaking functionality changes:
- `Common::String::matchString` will no longer match excluded characters with a trailing asterisk.  This was apparently unintentional, and causes `listMatchingMembers` and similar to not behave the same way for `FSDirectory` as it does for other archive types that support listing members.
- `ZipArchive` now strips trailing path separators from directory entries.  The directory detection code has also been updated to detect directory entries without trailing path …

COMMON: Refactor ArchiveMember directory support

---

engines/advancedDetector.cpp

[v]snprintf() / [v]fprintf() used in String::format() gets called roughly a million times (!) when adding a game.
Reducing the number of calls into libc leads to about 10% speed improvement on the atari backend (which is counting in seconds!)
I wish I could get rid of that `Common::String::format("%d", _md5Bytes);` construct, too. But even in its present form (i.e. with just reduced content passed to `String::format`) it leads to a measurable speed-up.

ENGINES: Optimize string handling

---

base/main.cpp

On iOS, and possibly emscripten which is the only other backend using `kFeatureNoQuit` currently, closing the launcher dialog without starting a game results in a blank screen and the user has to force close and reopen ScummVM. This was reported in https://bugs.scummvm.org/ticket/14624 using the Esc key, or corresponding iOS gesture, while on the launcher.
The change in this pull request adds a loop to reopen the launcher if it was closed without starting a game and avoid existing  `scummvm_main()`. I have tested that it indeed fixes the issue on the iOS simulator.
This is one of 4 possible solutions I considered. The other three are:
- Use the same solution, but in `LauncherChooser::runModal()` instead of `launcherDialog()`.
- Ignore the Escape key in the `LauncherDialog` so that it does …

BASE: Fix exiting scummvm_main loop in backend not allowing quit

---

common/fs.cpp
common/str-base.cpp
common/str-base.h

Some performance improvements to avoid unnecessary string construction and copies:
- Changes toLowercase and toUppercase to avoid calling makeUnique if the string doesn't require any modification.
- Changes FSNode::getName to avoid calling `punycode_decodefilename` and the subsequent String -> U32String -> String conversions if the filename isn't punycode.  This should significantly speed up `AdvancedMetaEngineDetection::composeFileHashMap`

COMMON: String performance improvements

---

engines/sword1/control.cpp
engines/sword1/control.h
engines/sword1/logic.cpp
engines/sword1/metaengine.cpp
engines/sword1/resman.cpp
engines/sword1/resman.h
engines/sword1/screen.cpp
engines/sword1/screen.h
engines/sword1/sword1.cpp
engines/sword1/sword1.h
engines/sword1/sworddefs.h
engines/sword1/swordres.h

Ciao! With this PR I'm rewriting the code for the main menu for Broken Sword 1. This is part of the series of changes I'm doing to the engine to have it match 1:1 (or as close as reasonably possible) with the source code/executable, the DOS version in particular.
There were several inaccuracies in the current code (which is only inspired by the original code, and has a completely different structure), so I got permission to rewrite it.
This brings us the following changes:
* Accurate text positioning;
* Save and Restore "stone bars" now move when scrolling the list;
* Implement the "Speed" section and setting;
* Play intro cutscene when selecting Restart from the main menu;
* During the tombstone screen (the death menu), the correct font is now used;
* Implement the "Disk full!" message; …

SWORD1: Rewrite main menu code

---

engines/sci/console.cpp
engines/sci/console.h

Introduces a new `kerncall` kernel/sub command to the debugger console only to aid in debugging all related SCI games. Similar in vein to using the `send` command.
Example within the SCI debug console:
```sh
) kerncall Random 4 8
kernel call result is: 0000:0008
```
- Additionally, adds a few annotations and clarifications when you are viewing decimal/hex segment ids.
- Lastly, to be more clear renames command: `functions` to `kernfunctions` to list all kernel routines.

SCI: adds support for debugging/executing kernel calls

---

.gitignore
devtools/create_project/cmake.cpp
devtools/create_project/cmake.h
devtools/create_project/codeblocks.cpp
devtools/create_project/codeblocks.h
devtools/create_project/create_project.cpp
devtools/create_project/create_project.h
devtools/create_project/msbuild.cpp
devtools/create_project/msbuild.h
devtools/create_project/xcode.cpp
devtools/create_project/xcode.h

This adds support for precompiled headers to speed up build times.  It does this by looking for MODULE_PCH_DIRS and MODULE_PCH_EXCLUDE to indicate what files should use PCH.  This supports one PCH file per directory, but not subdirectories.  While subdirectory scan might be more efficient in some cases, I think the added efficiency is not worth the extra complications with large engines that include third-party libraries.  We'd need a directory exclusion mechanism for those and I think it's just not worth it.
Example of usage: Suppose I wanted to add PCH to mTropolis engine, which has a base directory and "plugin" directory, and I want to add PCH for both of them.  I would add to module.mk:
`MODULE_PCH_DIRS := . plugin`
Then I would have to add the files …

DEVTOOLS: Add precompiled header support to MSBuild/MSVC.

---

engines/sci/graphics/frameout.cpp
engines/sci/graphics/frameout.h
engines/sci/graphics/lists32.h
engines/sci/graphics/plane32.h

This PR replaces a fixed array with `Common::Array`. It fixes an overflow that can occur in LSL7 at the pool entrance when the menu has many items. This also occurred in the original. Sierra used a fixed array, and our SCI32 code is based closely off of the original, so we have the same limit.
The screenshot from a 2019 GOG forum post that led to this:
Easy, right? Just replace a fixed array with a dynamic one. But it's tricky, because the array is storage in a template base class with a specific behavior that affects a lot of graphics code with performance implications. I just want to fix the one usage that has an edge case. I think I've come up with a good compromise, and even reduced the heap allocations when rendering a frame.
`Sci::StablePointerArray` is a template base class used in …

SCI32: Fix DrawList overflow with a dynamic array

---

engines/sci/sci.cpp
engines/sci/sci.h

Hello,
As discussed in bug: https://bugs.scummvm.org/ticket/14652
Here is a first draft at providing additional crash context when an error occurs in the SCI vm. This code will attempt to pull critical VM state data to provide additional details of what the user was doing and where they were in the game at the time of crash in addition to the error at the call site.
If the game crashes too early within the VM startup only the original error at the call site is provided.
One additional thing I need to do is provide arguments but I'm unsure how the args should be presented.
Example output when a crash occurs:
```sh
ERROR: something bad happened like a divide by zero
Game: pq4-cd, Version: 1.100.000
Room: 003, Script: 003, Selector: doTitle::changeState(params TODO) @ pc=0030:02ea
```

SCI: Provide additional errorString context on crash

---

gui/console.cpp
gui/console.h
gui/debugger.cpp
gui/debugger.h

Hello ScummVM team,
This code adds some simple command logic to the *console* version of the debugger to support clearing the debugger console using: `clear` or `cls` as an alias. 
This support was added to the GUI code (higher up the hierarchy) to provide this as a default feature to all games that might utilize the debugger.
A feature request ticket was created for this awhile back: https://bugs.scummvm.org/ticket/13386 and I've been hoping that this exists as well so I thought to contribute.

GUI: Adds clear and cls alias for gui console debugger

---

backends/platform/ios7/ios7_options.mm
backends/platform/ios7/ios7_osys_video.mm
backends/platform/ios7/ios7_video.mm

The tap gestures for right/left click in the iOS port was not protected by the TARGET_OS_IOS macro definition in the touchesMoved method which is called when a touch is moved.
Touches are used in tvOS when controlling the mouse pointer using the touch area on the Apple remote controller.
Fix some compiler warnings about unused variables and functions in the tvOS port.

IOS7: Fix AppleTV OS build errors and warnings

---

common/formats/cue.cpp
common/formats/cue.h
common/formats/module.mk
engines/director/tests.cpp

By request of @mistydemeo 
This is an extensible parser for Cue sheets. It does not implement _all_ the known tags, I decided to go with a pragmatic approach and add them as long as I see unprocessed commands. The missing things are reported via warnings and full parsing trace is visible at debug level 5.
The class does not implement any access API to the parsed data structures, as I need more information regarding usage. This is a trivial task since the data is kept in a neat hierarchy with nested `Common::Array` lists.
Also, I added a simple test to the Director engine, so you could see the implementation in action. To invoke the test, run `./scummvm -p engines/director/lingo/tests --debugflags=text -d5  --auto-detect`
Any feedback is welcome.

COMMON: Implement Cue sheet parser

---

backends/platform/ios7/ios7_scummvm_view_controller.mm

The system gestures on screen edges took precedence over the tap gestures again after screen rotations.
Call function setNeedsUpdateOfScreenEdgesDeferringSystemGestures on orientation changes to notify the system that it needs to read the edges from the view controller’s
preferredScreenEdgesDeferringSystemGestures property again.
Defer system gestures on all edges since the top changes when rotating the device.

IOS7: Defer screen edge system gestures on orientation changes

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp

I found a small bug in SurfaceSdl's cursor masks, source bpp is wrongly taken as output bpp when creating the masked image (visible only if the source bpp is != 4).

GRAPHICS: Fix an incorrect bpp in SurfaceSdl when applying cursor mask

---

engines/sherlock/events.cpp
engines/sherlock/sherlock.cpp
engines/sherlock/talk.cpp
engines/sherlock/tattoo/tattoo_darts.cpp
engines/sherlock/tattoo/tattoo_user_interface.cpp

Depending on its argument, the opcode does the following in the original game:
0x01: Hide the cursor and disable user input
0x02: Unhide the cursor and re-enable user input
In ScummVM, the opcode was only hiding/unhiding the cursor.
However, this was broken due to frequent showCursor() calls from setCursor().
So this PR does the following:
1. Fix cursor hiding
2. Disable input while cursor is hidden to match original behavior
3. Fix regressions caused by the changes
4. Add asserts pertinent to bug #14610
Fixes [#14610](https://bugs.scummvm.org/ticket/14610)

SHERLOCK: RT: Fix opcode 0xAE (cmdMouseOnOff())

---

engines/kingdom/kingdom.cpp
engines/kingdom/kingdom.h
engines/kingdom/logic.cpp
engines/kingdom/logic1.cpp

The detection that the demo movie was skipped is done by the external flag _demoMovieSkipped
This is not as clean as it would be updating a reference parameter variable from within playMovie() but that would require changing the signature of playMovie and all of its calls
This should fix the issue with the demo and full game both not being able to skip the demo movie (launch the game and select "Demo" from the main menu). And in addition, quitting the game (force quitting with Alt+F4, or via the ScummVM GMM -> Quit) would soft-lock ScummVM.

KINGDOM: Fix skipping and quitting demo movie

---

backends/keymapper/standard-actions.cpp
backends/keymapper/standard-actions.h
gui/dialog.cpp
gui/dialog.h
gui/gui-manager.cpp
gui/gui-manager.h
gui/widget.h
gui/widgets/editable.cpp
gui/widgets/editable.h

EditableWidget now uses the GUI keymap for most of the keys. Keypad keys have not been added to the  keymapper.

GUI: Use Keymapper for EditableWidget

---

engines/wage/guiborders.cpp
graphics/macgui/macwindow.cpp
graphics/macgui/macwindow.h
graphics/macgui/macwindowborder.cpp
graphics/macgui/macwindowborder.h
graphics/macgui/macwindowmanager.cpp
graphics/macgui/macwindowmanager.h
graphics/nine_patch.cpp
graphics/nine_patch.h

The NinePatch code only needed colour key transparency instead of full alpha blending, so it should be faster to use `ManagedSurface::blitFrom` with a paletted source instead of using `blendBlitFrom` and extra intermediate surfaces.
Only the WAGE engine has been tested with these changes.

GRAPHICS: Remove use of TransparentSurface in MacGUI code

---

doc/docportal/other_platforms/android.rst

When running `make html`, the warning `other_platforms/android.rst:80:
WARNING: Explicit markup ends without a blank line; unexpected
unindent.` would appear. This fixes the warning by removing the spaces
at the ends of the lines.

DOC: Fix warning in android.rst

---

engines/buried/environ/castle.cpp

in reference to  [Trac #13769](https://bugs.scummvm.org/ticket/13769) , during loading of global flag cgMWCatapultData with older value , there was a conflict with getMillis() which has been fixed by reinitalizing cgMWCatapultData to zero . This fixed the explosion timer , which was struck due to failing of condition `(timer + CATAPULT_TIMEOUT_VALUE < g_system->getMillis())) `

BURIED : fix explosion timer

---

engines/mtropolis/boot.cpp
engines/mtropolis/data.cpp
engines/mtropolis/data.h
engines/mtropolis/detection.cpp
engines/mtropolis/detection.h
engines/mtropolis/detection_tables.h
engines/mtropolis/elements.cpp
engines/mtropolis/miniscript.cpp
engines/mtropolis/mtropolis.cpp
engines/mtropolis/plugin/standard_data.cpp
engines/mtropolis/runtime.cpp
engines/mtropolis/runtime.h

_Unit: Re-Booted_ is [music CD](https://en.wikipedia.org/wiki/Unit_(album)) with a data partition which includes an
mTropolis-based music video program.
This is not much of a game, but uses some variants of the headers and data
structures which are nice to support and should help with future projects.
Known issues:
* Palette for the menu is a bit broken, needs some work
* The bottom-most button in the menu still crashes trying to load a PlugInModifier version 2001

MTROPOLIS: Add support for 'Unit Re-Booted'

---

engines/director/lingo/xlibs/cdromxobj.cpp

This is based on the documentation that says to name ripped audio tracks
starting at 1 rather than their actual track index. I've seen this in
other engines that use CD audio tracks as well.

DIRECTOR: cdromxobj: Subtract 1 from the track to play

---

engines/gob/detection/tables.h
engines/gob/detection/tables_fallback.h
engines/gob/detection/tables_fascin.h
engines/gob/detection/tables_gob1.h
engines/gob/detection/tables_gob2.h
engines/gob/detection/tables_gob3.h
engines/gob/detection/tables_lit.h
engines/gob/obsolete.h

General cleanup of the GOB detection tables, for uniformity with the other engines.
- Remove gob1cd, gob2cd, gob3cd identifiers and use the AD flag instead (gob1-cd, ...)
- Move "CD" string to description instead of using the game name (e.g. Gobliiins 2 CD (DOS/English) -> Gobliins 2 (CD/DOS/English)
- A couple minor fixes

GOB: Use ADGF_CD flag for gob games + general cleanup

---

gui/animation/Drawable.h

As GUI::Drawable is currently unused, there is little to note aside from the calculation of height.
I opted to pull the calculation for Transparent::getRatio() in to Drawable::getHeight() directly rather than add that to ManagedSurface.

GUI: Remove use of TransparentSurface in animation code

---

base/plugins.cpp
common/compression/installshield_cab.cpp
common/compression/installshield_cab.h
common/compression/installshieldv3_archive.cpp
common/compression/installshieldv3_archive.h
engines/advancedDetector.cpp
engines/advancedDetector.h
engines/game.cpp
engines/game.h
engines/nancy/detection.cpp
gui/launcher.cpp

This is motivated by certain detection entries in the Nancy Drew
engine containing filenames of InstallShield cabinets, which are
all standard (data1.cab/data1.hdr, etc), and thus trigger false
positives during detection.
The approach taken is to add the A: prefix to md5 sums,
which is used to signify that the desired file is embedded within
an archive. The type of archive and the filename of the archive
are placed inside the filename string, like in the following example:
is:data1.cab:file.dat
Where "is" is the identifier for InstallShield archives,
"data1.cab" is the name of the archive container file, and
"file.dat" is the name of the file whose size and md5 sum will
actually be evaluated.
When detecting, archives are only opened once and then
kept in cache until detection ends for all …

AD: Extend detection code to scan inside archives

---

engines/director/castmember/bitmap.cpp
engines/director/lingo/lingo-bytecode.cpp
engines/director/lingo/lingo.cpp

DIRECTOR: Fixes for The Dark Eye

---

backends/plugins/ds/ds-provider.cpp

Having all libc functions referenced in the main executable works around the issue described in [Trac #14554](https://bugs.scummvm.org/ticket/14554). This allows the SCUMM engine to run correctly, instead of crashing when launching a game.
If this PR is accepted, I plan to create the v2.7.1 release build with this change applied. Hopefully a proper fix will be available before v2.8.0, but I don't know how to do this myself.

DS: Hack to work around ARM/Thumb relocation issues in the SCUMM engine

---

gui/saveload-dialog.cpp

This PR seeks to clean up a few anomalies related to setting up an empty autosave slot in the Save dialog.
The dummy autosave exists to write protect an otherwise empty autosave slot, and as a bonus, also identifies the autosave slot. This is achieved by accessing the dummy autosave settings stored in the _saveList array.
Currently, this approach is only applied when setting the Save button in List View.
Other aspects of an empty autosave slot, such as the Delete button (List View) and the autosave button (Grid View), are currently set up using a less consistent approach.
This results in most engines displaying these anomalies in the Save dialog:
- in List View, the (empty) autosave slot’s Delete button is enabled, but, if selected, does nothing except launch the Delete Confirmation …

GUI: Fix usage of dummy autosave in empty autosave slot

---

engines/scumm/sound.cpp

This is an attempt at fixing https://bugs.scummvm.org/ticket/14663
Note that it refers to the original 16 color Macintosh version. The one sold these days on Steam is a much later port of the VGA version, as far as I know.
The problem is that we're trying to identify what is a digitized sound (and not a piece of music) in the Macintosh version of Indiana Jones and the Last Crusade by looking at values in a barely understood header, and this value turns out not to be identical in all sounds. One exception (and perhaps the only one?) is the sound used when pouring liquids, e.g. when loosening the torch in the Venice sewers, or when filling the beer stein in the castle Brunwald kitchen.
So here I'm instead trying to look for a value that appears to be constant for all music in the game, and …

SCUMM: [RFC, don't merge yet] Change heuristic for identifying Indy 3 Mac sound (bug #14663)

---

devtools/create_project/cmake.cpp

Some small changes to the CMake generator to let it support macOS with libraries installed from MacPorts.
Also an adjustment to support C++11 globally in the generated CMake files.
Pushing this as a PR in case someone disagrees with the global adding of /opt/local/lib.

CREATE_PROJECT: Default to C++11 and support MacPorts /opt/local/lib

---

engines/ags/engine/ac/global_video.cpp

A few (old) AGS games use WMV videos, which are not supported.
Notable examples are:
The Marionette https://archive.org/details/the-marionette
EGRESS https://kramsdesign.com/egress.html
Ghostdream (Steam)
However, the files can be easily converted to supported formats using ffmpeg or similar software.
This PR simply looks for files with the same name but a supported extension and plays those in place of the original,
allowing players to add their replacements.
Also shows a warning that wmv files are not supported (and avoids crashing the entire engine)
The warning says "Consult ScummVM wiki for details", I plan to add a brief explanation on the AGS engine page.

AGS: Avoid playing unsupported WMV videos and look for alternatives

---

common/memory.cpp
common/memory.h
common/module.mk
graphics/VectorRendererSpec.cpp
graphics/surface.cpp
graphics/tinygl/zbuffer.cpp
test/common/memory.h

The implementation is based on the one in VectorRendererSpec, and has been modified to use larger memory stores where possible.

COMMON: Add variants of memset for 16-bit, 32-bit and 64-bit values

---

backends/mixer/mixer.h
backends/mixer/null/null-mixer.cpp
backends/mixer/null/null-mixer.h
backends/mixer/sdl/sdl-mixer.cpp
backends/mixer/sdl/sdl-mixer.h
backends/module.mk
backends/platform/sdl/sdl.cpp
base/commandLine.cpp

I've attempted to clean this up but unfortunately untangling all of the cases where mixer readiness is not being checked is complicated.  EmulatedOPL doesn't do it, VideoDecoder doesn't do it, only 10 engines are actually checking `isReady` on the mixer because this is such a rare case.
However, it is a case that happens in the real world when the user has no audio output devices enabled.
Anything that fails to check immediately crashes in `playStream`.  Since there is a lot of code that isn't handling this correctly, I think it is better to use a null mixer fallback and add a way of detecting that it is a null device to MixerManager instead.

BACKENDS: SDL: Use null mixer if audio initialization fails

---

graphics/blit.h
graphics/blit/blit.cpp

These can be found in RISC OS sprite files, but may also be useful elsewhere.

GRAPHICS: Add functions for blitting with transparent masks

---

devtools/dumper-companion.py

This was inspired by a LucasArts disc having an additional (empty) HFS partition on the disc. Missing dependency warning was moved so as to not annoy users who only want to use the other modes.

DEVTOOLS: dumper-companion: Support images with multiple partitions; don't warn about missing deps when not running mac mode

---

graphics/palette.cpp
graphics/palette.h

The resulting map can be passed to `Graphics::crossBlitMap()`, which allows for faster conversion of images with different palettes.

GRAPHICS: Add a function for creating maps to PaletteLookup

---

engines/freescape/freescape.cpp
engines/freescape/games/dark/cpc.cpp
engines/freescape/games/dark/dos.cpp
engines/freescape/games/dark/zx.cpp
engines/freescape/games/driller/dos.cpp
engines/freescape/games/eclipse/cpc.cpp
engines/freescape/gfx.cpp
engines/mohawk/myst_graphics.cpp
graphics/managed_surface.h
graphics/surface.cpp
graphics/surface.h
gui/imagealbum-dialog.cpp

This will prevent it from reading out of bounds with smaller palettes.

GRAPHICS: Add palette start and size parameters to Surface::convertToInPlace()

---

engines/scumm/input.cpp

Dpad buttons are by default remapped to numpad keys. Up/Down are KEYCODE_KP8/KEYCODE_KP2 and Left/right are KEYCODE_KP4/KEYCODE_KP6.
The numpad keys are remapped to have a corresponding ASCII value since the state of the keys are stored in the _keyDownMap array, indexed by the ASCII value.
It was found that the ASCII values were calculated incorrectly for EVENT_KEYUP events but correctly for EVENT_KEY DOWN events. In the latter cases the keyboard event was stored to the _keyPressed member variable. The keycode was checked and if being a numpad key the corresponding ASCII value was calculated. The key state was then stored in the _keyDownMap array using the calculated ASCII value.
For the EVENT_KEYUP events the keyboard event was not stored to the _keyPressed member variable. The keycode …

SCUMM: Fix remapping of numpad keys on EVENT_KEYUP

---

engines/crab/console.cpp
engines/crab/console.h

Now keymap being used can be known by typing "what keymap" in the debugger console

CRAB: Add Debug output for Keymaps

---

engines/director/castmember/filmloop.cpp

This fixes a graphics glitch in the sonic cemetery scene of Total Distortion. The filmloop was producing extra bounding boxes that led to white artifacts being drawn.
In some cases, particularly in Total Distortion, there could be kInactiveSprite type sprites. We have to skip processing them to avoid the issue.
To reproduce the issue, run:
./scummvm --start-movie="ATD/HD/NJSONIC.DXR"@300 totaldistortion-win

DIRECTOR: Fix filmloop loading for non-bitmap sprites

---

gui/console.cpp
gui/console.h

ConsoleDialog had a hard-coded handler for Copy and Paste shortcuts. These shortcuts are now handled by the keymapper and produce Copy and Paste events.
Fixes CTRL+C and CTRL+V in the console on Windows builds.

GUI: Handle Copy and Paste events in ConsoleDialog

---

engines/crab/ui/dialogbox.cpp

Now pressing enter key loads the next statement of the character in the dialog box.

CRAB: Fix wrong keymap being set in the Dialog Box

---

engines/crab/game.cpp

Now the keymap is correctly set to KBM_GAME instead of KBM_UI after Hud elements are closed.

CRAB: Fix keymap not being changed in hud elements.

---

engines/sludge/freeze.cpp
engines/sludge/freeze.h
engines/sludge/graphics.cpp
engines/sludge/graphics.h
engines/sludge/sludger.cpp
engines/sludge/sprites.cpp
engines/sludge/sprites.h
engines/sludge/zbuffer.cpp
engines/sludge/zbuffer.h

This commit removes the "SpriteLayer" logic previously used in favour of a Z-Buffer implementation

SLUDGE: Add Z-Buffers

---

graphics/macgui/macwindowmanager.cpp
graphics/macgui/macwindowmanager.h

While working on the menu handling for the Macintosh versions of Indiana Jones and the Last Crusade and Loom, I've had the screen go mysteriously black on me two or three times. I think it's been when the menus have been either about to be activated or inactivated, which makes me suspect that it's a threading issue. The menus are activated by a timer, so anything that timer function touches could be at risk.
So I've added a mutex to try and guard against this. But threading is something I generally try to avoid (the Last Crusade GUI, despite its many timed animations, remain steadfastly single-threaded), so I don't know if I'm doing this right. At all.

GRAPHICS: MACGUI: [RFC] Attempt to fix suspected threading threading issues in the Macintosh Window Manager

---

engines/sludge/zbuffer.cpp

When window dimensions and scene dimensions are not equal, an out of bounds read occurred.

SLUDGE: Fix out of bounds read in Z-Buffer code

---

audio/rate.cpp
audio/rate.h

This is almost invisible on high-end machines but does it job nicely on lower-end ones (<100 MHz). Instead of calling `clampedAdd` with the same values just copy the value over.
As many (older) games use mono samples nearly always, it can be widely used, especially on platform which do not offer 16-bit mono output (yes, they exist ;)).

AUDIO: Optimize case for !inStereo && outStereo

---

common/formats/quicktime.cpp
test/common/formats/quicktime.h
test/module.mk

In parseStream, atom.size is initailized to uint32 max.  If the loop in readDefault then never executes because the stream has hit EOF, that size is passed as-is to seek.  This can cause a crash eg in SeekableSubReadStream because of an int overflow.
If nothing has been read just skip seeking at the end of readDefault. parseStream will correctly return false in this case as no MOOV will be found.

COMMON: Avoid Quicktime parsing crash on early EOF

---

engines/ags/lib/allegro/surface.cpp

Currently, the optimized blitting paths (SSE2, AVX2, and NEON)
all have issues with scaling and flipping. Due to the complexity
and poor structure of the code, all my attempts at fixing these
problems have so far failed.
This PR effectively quarantines these code paths so that when
a stretch blit or flipping are needed, they are done onto a
temporary surface, which is then blitted using the optimized
paths. This is obviously less than ideal, but with the impeding
release the only other alternative is to disable extension
support entirely, and I'd rather avoid that.

AGS: Disable optimized blit paths stretching and flipping

---

engines/sludge/objtypes.cpp
engines/sludge/people.cpp

In frasse 1.03, if you go up then right and try to pick up the box, the game would sometimes crash.

SLUDGE: Fix bug in logic for removing objects

---

engines/ultima/nuvie/gui/widgets/map_window.cpp
engines/ultima/nuvie/gui/widgets/map_window.h

Change local static variable to a field so it is reinitialized when using the return-to-launcher feature.
Fixes [#13971](https://bugs.scummvm.org/ticket/13971)

ULTIMA: ULTIMA6: Fix map not showing when using RTL

---

engines/ultima/nuvie/gui/widgets/map_window.cpp
engines/ultima/nuvie/gui/widgets/map_window.h
engines/ultima/nuvie/misc/sdl_compat.cpp

- Fix assert on loading roof bitmap
- Fix garbled roof drawing
Both regressions were introduced in commit c4970c95dc48fdf38891cec3740ccf98dfd090f9
"Fix crash in GUI on surface blit"
Fixes [#14687](https://bugs.scummvm.org/ticket/14687)
Note: The commit message prefix for Ultima 6 is pretty inconsistent in the log, let me know if I should change it.

ULTIMA: ULTIMA6: Fix roof drawing

---

gui/console.cpp

In a7d4d0f232231eb3d22c85d35ddfbcc2be0e587c, Console output was passed to `debug` so that it would appear in stdout and scummvm.log, but the code added a newline to every `ConsoleDialog::debugPrintf` string that didn't already end in one. This is a problem for Console code that builds lines with multiple `debugPrintf` calls. SCI's Console has many commands and most of them print output this way; this has been filling the debug output with unreadable partial lines. Other engines are affected, really any `debugPrintf` call that doesn't end in \n.
Now the code doesn't alter the newlines (or other whitespace). The `debug` output now matches the intended Console output.
After:
```
Call stack (current base: 0x0):
0: script 994 - DEMO::play()
obj@0001:0094 pc=0004:019e sp=ST:0000 fp=ST:0000 …
```

GUI: Fix Console newlines passed to `debug`

---

engines/director/channel.cpp
engines/director/frame.cpp
engines/director/sprite.cpp
engines/director/sprite.h

It is partial revert of 3cb61c54d749f385817fb8674236d4046af54271
Steps to reproduce:
1. Start Total Distortion
2. Start a new game / load game
3. Click on the "Options" button
4. The physical energy bar is not visible
Trello card : https://trello.com/c/mpZTlPoZ/628-physical-energy-game-bar-not-filled

DIRECTOR : Fix physical energy game bar not filled in total distortion.

---

engines/director/detection_tables.h

This PR adds a detection entry to a demo/preview version of "Maths Workshop", and [educational title released by Broderbund in 1995](https://www.mobygames.com/game/12160/math-workshop/).
While the full game doesn't run in DIRECTOR, but uses MOHAWK according to @eriktorbjorn, this preview release is made with Director 4.00.
I briefly tested the application and at first glance it seems to work fine using the fallback detection.
I'm submitting this as PR since I'm not that familiar with the DIRECTOR engine. In case we need a new test case for the DIRECTOR buildbot, I uploaded the demo provided by @eriktorbjorn [to our FRS](https://downloads.scummvm.org/frs/demos/director/d4/en/mathsworkshop-demo-win.zip).
I'll create a proper entry for it in the spreadsheet once this is merged.

DIRECTOR: Add demo/preview version of Maths Workshop

---

engines/gob/detection/tables_fallback.h

- use for Adi 2 640x400 instead of 640x480 like in tables_adi2.h
- set for Adi 4 Platform from DOS to Windows like in tables_adi4.h

GOB: updated fallback detection to latest changes

---

engines/scumm/players/player_v2base.cpp

When arriving at Castle Brunwald in the Macintosh version of Indiana Jones and the Last Crusade, we have the case where freqmod_incr is 300 and freqmod_modulo is 32. Simply subtracgint freqmod_modulo isn't enough to keep the value in line, leading to out of bounds access.
I don't know if freqmod_incr can ever be 0, but let's account for that case as well, by setting freqmod_offset to 0.
See https://bugs.scummvm.org/ticket/13908 for details. I have not been able to reproduce the other ASAN bug mentioned there, so maybe that one has already been fixed? Or maybe I just didn't try hard enough.

SCUMM: Fix runaway freqmod_offset values in player_v2base (bug #13908)

---

engines/mohawk/riven_vars.cpp

This pull request updates the code that randomizes the combination for the domes, so that the generated combinations correspond to those in the original game.
In the original game, the dome combination is not completely random; only the first number is one that can be learned in the school (range 2–10), the next two numbers are chosen from the range 11–15, and the last two numbers are chosen from the range 16–24. Presumably, this was done so that the code has approximately equal difficulty for every game.
Until now, ScummVM has generated completely random codes, which results in some games having very easy codes (when most of the numbers are below 10). Also, there's a 20% chance that the last number is 25, which never occurs in the original game's dome combinations.
Graphical summary of …

MOHAWK: RIVEN: Generate dome code as in original game

---

engines/dreamweb/metaengine.cpp

Save parsing in `querySaveMetaInfos` had an off-by-one error. `listSaves` contains the correct parsing.
This caused save descriptions to accumulate a leading junk byte (0x02). As saves were loaded and re-saved, this added more junk bytes until the ScummVM list GUI either displayed an empty string or crashed.
This bug affected users differently depending on if they used the list or grid view for saving and loading.
`querySaveMetaInfos` parsing now matches `listSaves`.
Fixes bug #14561

DREAMWEB: Fix save parsing in querySaveMetaInfos

---

backends/audiocd/audiocd.h
backends/audiocd/default/default-audiocd.cpp
backends/audiocd/default/default-audiocd.h
common/formats/cue.cpp
common/formats/cue.h
engines/director/lingo/xlibs/applecdxobj.cpp
engines/director/lingo/xlibs/applecdxobj.h
engines/director/lingo/xlibs/cdromxobj.cpp

This adds support for playing CD audio via absolute timecodes instead of via track numbers. This is needed for several Director games. In order for this to work via CD audio emulation, we need access to a full table of contents for the disc. We can't just use the audio files for the CD tracks, because in almost every case, a data track comes before the first CD track - it's impossible to know what absolute sector an audio track begins and ends that without knowing the size of the data track.
To fix this, I've made use of cuesheets in order to have access to a full table of contents of the disc. In absolute playback mode, we check to see if the game directory has a file named `disc.cue`, and if so, we parse that and use it as the TOC. I'm using the new cuesheet parser that @sev- wrote. …

DIRECTOR: add support for absolute timing CD audio playback via cuesheets

---

engines/trecision/logic.cpp
engines/trecision/metaengine.cpp
engines/trecision/trecision.h

When saving from the game's control panel, we use the thumbnail that was created before the control panel opened. But when using the ScummVM menu, we need to generate the thumbnail as usual. Otherwise, there may not be any thumbnail at all, causing the save to fail.
The cases I have at least tried are:
- Pressing ESC to save with the game's native save dialog
- Pressing Ctrl+F5 to save with ScummVM's save dialog
- Pressing ESC to save with ScummVM's save dialog (i.e. original dialogs not enabled in the game settings)
But I'm not familiar with this engine, so there may be a better way? I'm submitting this because https://bugs.scummvm.org/ticket/13834 is a prioritized bug for 2.8.0.

TRECISION: Fix thumbnail when using ScummVM menu to save (bug #13834)

---

engines/ags/lib/allegro/surface_avx2.cpp
engines/ags/lib/allegro/surface_neon.cpp
engines/ags/lib/allegro/surface_sse2.cpp

All optimized blitting paths exhibit similar overreading behavior, due to the flawed design of (almost) always loading a full 128/256-bit line, and discarding overread pixels afterwards. This PR patches up the code so the overreads never happen, albeit at the cost of a few memcpys at the end of every line of pixels.
The SSE2 and AVX2 paths have been tested quite well (thanks @tag2015 !), but the NEON path has not.

AGS: Fix ASAN crashes in SIMD blit paths

---

engines/director/lingo/lingo-builtins.cpp

The correct behaviour in Director, when polling getNthFileNameInFolder with an index higher than the number of available files, is to return an empty string. Previously our equality logic would coerce VOID to be equal to "", which is not correct, and disguised the issue of us returning VOID in b_getNthFileNameInFolder.
Fixes startup sequence in Team Xtreme: Operation Weather Disaster; however checking for "" is a fairly common pattern as it is the only way of testing how many files there are in a folder with Director's API.

DIRECTOR: Make b_getNthFileNameInFolder return "" on no match

---

engines/agi/detection_tables.h

Hi all,
submitting this as PR due to the various macros used in the AGI detection.
This resolves the following tickets:
[TRAC #13734](https://bugs.scummvm.org/ticket/13734)
[TRAC #14286](https://bugs.scummvm.org/ticket/14286)
[TRAC #13274](https://bugs.scummvm.org/ticket/13274)
[TRAC #14287](https://bugs.scummvm.org/ticket/14287)
[TRAC #14604](https://bugs.scummvm.org/ticket/14604)

AGI: Multiple detection entries imported from TRAC

---

common/compression/installshieldv3_archive.cpp
common/compression/installshieldv3_archive.h

Adds a function to open an InstallShieldV3 archive from a stream instead of just FSNode and filename.
To be used by mTropolis fallback loader.

COMMON: Add API for loading InstallShieldV3 from a stream

---

engines/director/lingo/xlibs/applecdxobj.cpp
engines/director/lingo/xlibs/applecdxobj.h

This was flagged by @sluicebox. I'll get it backported as well.

DIRECTOR: fix memory leak in AppleCD

---

engines/grim/detection.cpp
engines/grim/font.cpp
engines/grim/font.h
engines/grim/grim.cpp
engines/grim/localize.cpp
engines/grim/md5check.cpp
engines/grim/resource.cpp
engines/grim/textobject.cpp

Grim Fandango (Windows/Korean)
This supports Korean fan translations. (Korean fan translations are only available for openGL renderer.)
Korean FAN translation data is available at the link below.
[https://github.com/british-choi/ScummVM-Kor-Trs](https://github.com/british-choi/ScummVM-Kor-Trs)

GRIM: Fix support for Korean translation for Grim Fandango

---

engines/sword2/detection_tables.h
engines/sword2/maketext.cpp
engines/sword2/maketext.h
engines/sword2/resman.cpp
engines/sword2/sword2.cpp
engines/sword2/sword2.h

This supports Korean fan translations.
Korean FAN translation data is available at the link below.
[https://github.com/british-choi/ScummVM-Kor-Trs](https://github.com/british-choi/ScummVM-Kor-Trs)

SWORD2: Fix support for Korean translation

---

common/formats/ini-file.cpp
common/formats/ini-file.h
engines/mohawk/livingbooks.cpp

The pull request resolve a bug in French sheila(https://bugs.scummvm.org/ticket/13920)
in INI Parser
- Added a  flag  strictParser Do not allow garbage to be present in the file (default true)
- Added a condition to check for Non-Ascii

COMMON: Add a mode to the INI parser to ignore garbage in some files

---

common/formats/ini-file.cpp
common/formats/ini-file.h
engines/mohawk/livingbooks.cpp

The INI parser currently interprets lines that don't contain a key-value delimiter (the `=` character) as if the entire line is a key with an empty value. The European version of Sheila Rae, the Brave contains this INI file:
That junk line of 0x7F characters gets parsed as key with no value, the Mohawk Little Books engine iterates over key/values in `Globals` and does further parsing, and the unexpected 0x7F causes an `error` on engine init.
I don't think the current INI parser behavior is a good default, but at this point engines must already depend on it, so changing it would certainly break something. I've added a flag to enable stricter parsing that ignores lines without a delimiter and enabled it for Mohawk Little Books. (I think is also how Windows' parser behaves/behaved, but I'm …

COMMON: Add INIFile::requireKeyValueDelimiter(), Fix Sheila Rae

---

devtools/create_project/cmake.cpp
devtools/create_project/create_project.cpp
devtools/create_project/create_project.h

Created as pull request, as I don't have a windows to test this change on.

CREATE_PROJECT: add windows subsystem support to cmake

---

engines/sludge/people.cpp

In Out of Order, if you visit the alley that goes to the surgery you will notice a jarring transition between colours on Hurford.

SLUDGE: Fix drawModeDark colourmix values by swapping them

---

engines/director/detection_tables.h

Since support for its music was recently added, and this is the reference example of its xlib being used, I'd like to add this to the supported list at this time. If this gets merged I'll cherry-pick this commit to master as well.

DIRECTOR: mark classicalcats-mac-ja supported

---

engines/glk/adrift/detection_tables.h
engines/glk/glulx/detection_tables.h
engines/glk/zcode/detection_tables.h

This PR updates various GLK subsystem:
- ADRIFT: 2 new entries
- GLULX: 138 new entries
- ZCODE: 43 new entries
plus minimal adjustments for Competition titles and for gameIDs to avoids clashing.

GLK: Various detection tables updated

---

engines/director/score.cpp

Freezing changed pretty significantly in D4, so it figures that the conditions for a frame update would change with it.
Fixes regression where loading save games in The Dark Eye would result in a white screen.

DIRECTOR: Add D4 workaround for freezing behaviour fix

---

engines/director/score.cpp

Freezing changed pretty significantly in D4, so it figures that the conditions for a frame update would change with it.
Fixes regression where loading save games in The Dark Eye would result in a white screen.

DIRECTOR: Add D4 workaround for freezing behaviour fix (backport)

---

engines/ags/ags.cpp
engines/ags/ags.h
engines/ags/detection.h
engines/ags/detection_tables.h
engines/ags/dialogs.cpp
engines/ags/globals.h
engines/ags/metaengine.cpp
engines/ags/metaengine.h

This long-overdue PR adds two flags that can be used in the detection tables to disable autosaves or completely disable save/loading from the GMM.
Many AGS games (mostly commercial) already feature an autosave mechanism, and also keeping enabled the scummvm
system causes save duplication and various annoyances (e.g. most Blackwell games autosave in the map screen using slot 0, causing the "found save in autosave slot" box to appear)
The option to disable saves entirely is for games that feature permadeath or similar modes (Dustbowl, Dreams in the Witch House, Whispers of a Machine...) to discourage cheating.
However, since some users may not appreciate the change, I also added a checkbox in game options to disable the feature.
The PR also includes a fix (which is more of a workaround to …

AGS: Add GUIO options to disable autosaves/save management per-game

---

engines/tinsel/detection.h
engines/tinsel/detection_tables.h
engines/tinsel/metaengine.cpp
engines/tinsel/tinsel.cpp

Discworld 2 and Discworld Noir both render at 640x432, which by default is letterboxed in a 640x480 virtual window. The user can instead opt for a 640x432 virtual window; to remove the letterboxing.
Add a checkbox option (`GUI::CheckboxWidget`) so the user can remove the forced letterbox effect in Discworld 2 and Discworld Noir. Enabling the option allows the games to fit better in a window that has an aspect ratio wider than 4:3.
With the option disabled (using "Stretch Mode: Fit to Window"):
With the option enabled (using "Stretch Mode: Fit to Window")
Note: this replaces the (dormant) pre-processor directive for DW2 (`#ifdef DW2_EXACT_SIZE`) with a user configurable option that is also available for NOIR.
This feature can be tested with the demos for [DW2 and …

TINSEL: Game Option to crop black bars (DW2/NOIR)

---

NEWS.md

Change the wording of the news line about the GM device change.
I think "compatibility" suggests something working vs. not working when this is more of a quality change than anything.
I think describing it this way will be clearer about what has changed (General MIDI was previously disabled by default, and now it is not).

NEWS: Change news line about GM device setting change

---

engines/mtropolis/detection.cpp

clang flagged this variable, introduced in 8aadc2fcdff76c500617cc78f001cf57e301a690, as being assigned to but not written. Figured I'd open this as a PR just in case @elasota had a plan for it and it had gotten missed.

MTROPOLIS: remove unused variable

---

engines/director/lingo/xlibs/applecdxobj.cpp
engines/director/lingo/xlibs/applecdxobj.h

XObjects are cloned by LC::call, which apparently has a magic copy constructor. This means that any raw pointers inside the XObject will get thrown into the cloned object, upsetting the fragile kayfabe of ownership which underpins memory safety in C++.
Fixes the first movie switch in Classical Cats.

DIRECTOR: XOBJ: Make CueSheet in AppleCDXObject a SharedPtr

---

engines/director/detection_tables.h

This gets the demo to start, but neither the Windows or Mac versions get past the Toshiba EMI logo at the start.

DIRECTOR: Fix the version number for the Gadget Windows demo

---

engines/sci/engine/file.cpp

This is a trivial change to the character import function in Quest for Glory III-IV, to also show characters created by the QFG2 Remake by AGDI.
Fixes TRAC [14754](https://bugs.scummvm.org/ticket/14754)
I tested the save provided with the bugreport and from my (minimal tbh) experience with the QFG games everything seems to work as it should.

SCI: Also show qfg2-agdi characters in import

---

common/archive.cpp
common/archive.h
common/compression/stuffit.cpp
common/compression/vise.cpp
common/macresman.cpp
engines/mtropolis/vfs.cpp
engines/mtropolis/vfs.h

This adds functions to check if an archive member is in a Mac-native archive and skips most of the attempted methods of opening the resource fork in MacResManager when it is.
Due to the addition of alt streams, MacResManager::open attempts to open a file as MacBinary before checking for a resource fork alternate stream, which is because on macOS, files often wind up with system-native resource forks even when they're actually MacBinary.
This priority led to an unintentional performance regression because it means Mac archive formats must decompress a file's data fork to check if it's MacBinary before checking the alt stream, even though the archive format will always store resource data in the alt stream.
This adds a function to shortcut this check if the ArchiveMember reports that it is …

COMMON: Avoid unnecessary decompression of the data fork when opening resources of files in Mac-native archive formats

---

graphics/macgui/macmenu.cpp
graphics/macgui/macwindowmanager.cpp

This is my attempt at fixing https://bugs.scummvm.org/ticket/14741
However, I don't have  any good test case for how it's _supposed_ to work. Maybe I've broken things, maybe I'm going about this the entirely wrong way. That said...
When moving the mouse through the menu bar, over a part that's not occupied by menu items, the Mac menu class will start calling processEvent() recursively through eventLoop(). This is bad for two reasons: During the recursion (which can easily reach a depth of dozens or even hundreds of calls) there is no delay, so it will use 100% CPU. And once the recursion unwinds, all the delays will come at once.
The visible result is that the mouse cursor moves very sluggishly, and afterwards there may be a noticeable delay. (Though the latter is probably only noticeable …

GRAPHICS: MACGUI: [RFC, needs review] Avoid recursion in Mac menu event processing (bug 14741)

---

engines/ultima/nuvie/script/script.cpp

Fix regression introduced in commit 12a47d956ee00f62ed235c4009eb57ad0dbda19d
Keys bound via the keymapper were no longer usable in cutscenes, including the intro. This made it impossible to enter a name in the character creation screen or to skip a scene with the default keybinds.

ULTIMA: NUVIE: Fix input in cutscenes/character creation

---

engines/ultima/nuvie/metaengine.cpp

Cheat keys were no longer working since commit
12a47d956ee00f62ed235c4009eb57ad0dbda19d
This seems to be an oversight, as they were defined but not added to the keymap.
Re-add them.

ULTIMA: NUVIE: Fix cheat keys

---

engines/ultima/metaengine.cpp

Make sure gameId is defined in UltimaMetaEngine::initKeymaps when only ultima6 is enabled.
To reproduce the build failure:
./configure --disable-all-engines --enable-engine=ultima6 && make
This currently results in:
```
engines/ultima/metaengine.cpp: In member function ‘virtual Common::KeymapArray UltimaMetaEngine::initKeymaps(const char*) const’:
engines/ultima/metaengine.cpp:259:13: error: ‘gameId’ was not declared in this scope; did you mean ‘getGameId’?
259 |         if (gameId == "ultima6" || gameId == "ultima6_enh"
|             ^~~~~~
|             getGameId
make: *** [Makefile.common:178: engines/ultima/metaengine.o] Error 1
```

ULTIMA: Fix building when ultima6 is the only enabled ultima subengine

---

devtools/create_ultima/files/ultima6/scripts/u6/actor.lua
engines/ultima/nuvie/core/map.cpp
engines/ultima/nuvie/core/map.h
engines/ultima/nuvie/script/script.cpp

This aims to make ranged attacks behave closer to the original.
Fixes the following differences:
1. If a ranged attack is blocked, it should hit the blocking object (e.g. a closed door)
2. When failing a ranged attack roll the target coordinates are shifted randomly and another attack roll is made: It should be possible to roll against the same target again when the random shift is zero
3. The attack roll should be done before checking for collisions, so coordinates get shifted even if there is no line of fire to the target
4. In case a thrown weapon is blocked by an object, it should be placed on the tile traversed before the collision occurred (i.e. not on a door/wall)
5. Thrown weapons should only be placed on the map and removed from the attacker if the distance to the target is …

ULTIMA: ULTIMA6: Ranged combat rework

---

common/archive.cpp

This is causing problems when using listMatchingMembers with an archive type that uses the Mac path separator (e.g. StuffIt or Mac VISE).

COMMON: Fix listMatchingMembers not working properly with non-default path separator

---

engines/director/detection_tables.h

This PR adds a detection entry for the German sampler disc of Tivola, released in Summer 2000.
It contains various samples and demos of other DIRECTOR games made by the same publisher that can be launched through the START32/START16.EXE projects.
Reported DIRECTOR version according to the file details is 6.5G.

DIRECTOR: Add detection entries for Tivola Sampler discs

---

engines/ultima/detection_tables.h

- Add/fix detection entry for alt version ([#14659](https://bugs.scummvm.org/ticket/14659))
This was already added as "non-enhanced" in commit dcb4d9e91b8087056ed20a15a4b33ee2d94d97e5, but the entry for "enhanced" mode is missing.
- Add/fix detection entry for SirJohn's German fan translation v1.6
Like above: Adds missing "enhanced" entry. Normal mode was already present.
- Convert Ultima 6 detection table entries to macros to avoid repetition and make adding new versions less error-prone

ULTIMA: Use macros for Ultima 6 detection entries

---

engines/mm/mm1/maps/map12.cpp
engines/mm/mm1/maps/map12.h
engines/mm/mm1/views/character_info.cpp
engines/mm/mm1/views/character_info.h
engines/mm/mm1/views/spells/cast_spell.cpp
engines/mm/mm1/views/spells/cast_spell.h
engines/mm/mm1/views_enh/character_manage.cpp
engines/mm/mm1/views_enh/character_manage.h
engines/mm/mm1/views_enh/create_characters.cpp
engines/mm/mm1/views_enh/create_characters.h
engines/mm/mm1/views_enh/interactions/interaction_query.cpp
engines/mm/mm1/views_enh/interactions/interaction_query.h
engines/mm/mm1/views_enh/trade.cpp
engines/mm/mm1/views_enh/trade.h

These warnings are emitted from GCC-13 when -Wabi is passed.
The warnings are of the following type:
engines/mm/mm1/views/spells/cast_spell.cpp: In member function ‘MM::MM1::Views::Spells::CastSpell::draw()::<lambda(const Common::String&)>::operator void (*)(const Common::String&)() const’:
engines/mm/mm1/views/spells/cast_spell.cpp:109:25: warning: the mangled name of ‘MM::MM1::Views::Spells::CastSpell::draw()::<lambda(const Common::String&)>::operator void (*)(const Common::String&)() const’ changed between ‘-fabi-version=12’ (‘_ZZN2MM3MM15Views6Spells9CastSpell4drawEvENKUlRKN6Common6StringEE0_cvPFvS7_EEv’) and ‘-fabi-version=18’ (‘_ZZN2MM3MM15Views6Spells9CastSpell4drawEvENKUlRKN6Common6StringEE_cvPFvS7_EEv’) [-Wabi]
They appear to be emitted when a parameter is passed to a lambda …

MM: MM1: Fix GCC ABI Mangling Warnings Caused By Lambda Functions

---

common/fs.cpp
common/fs.h

OS X resource streams were changed to load as an alt stream from FSNode, and a forwarding method was added to FSDirectoryFile, but not to FSDirectory, which is probably why some games are failing to load resources on OS X.
This should hopefully fix https://bugs.scummvm.org/ticket/14753

COMMON: Add createReadStreamForMemberAltStream to FSDirectory

---

backends/platform/android/android.mk

This should allow to publish for Android TV and overcome the APK 100MB limitation

ANDROID: Add bundle build method

---

backends/platform/android/android.cpp
backends/platform/ios7/ios7_osys_misc.mm
gui/helpdialog.cpp

I want to avoid mistakes with the Android port, where many users were lost, so I am trying to squeeze in a last-minute change to the help.
Please review it and tell me what you think. I would really like to squeeze it into 2.8.0 in both ports.
The help is not yet translatable due to fonts, so it is not a problem that we will get no translations update.
If the porters agree, then it could get as a subtag only for Android and iOS, perhaps 2.8.0.1, or distributed as a patch (of course, it then be backported to branch-2-8 and branch-2-8-0).

HELP: Added explanation what ScummVM is and where to get help for Android and iOS

---

engines/engine.cpp
engines/util.h

This is intended to allow configurable resolutions with fallbacks to lower resolutions, such as with this example:
```
Graphics::PixelFormat format = Graphics::PixelFormat::createFormatCLUT8();
Graphics::ModeWithFormatList modes = {
Graphics::ModeWithFormat(_screenRect.width() >> 0, _screenRect.height() >> 0, format),
Graphics::ModeWithFormat(_screenRect.width() >> 1, _screenRect.height() >> 1, format),
Graphics::ModeWithFormat(_screenRect.width() >> 1, _screenRect.height() >> 2, format),
Graphics::ModeWithFormat(_screenRect.width() >> 2, _screenRect.height() >> 2, format),
};
int mode = initGraphicsAny(modes, ConfMan.getInt("resolution"));
```

ENGINES: Allow specifying a start position for initGraphicsAny()

---

common/compression/installshield_cab.cpp
common/compression/installshield_cab.h
engines/mtropolis/boot.cpp

This adds support for opening InstallShield cab archives from any archive instead of just SearchMan, and hooks it up to the mTropolis engine (so it can be used for Magic School Bus titles).

COMMON: Add API for opening an InstallShield cab archive inside of another archive

---

engines/mm/configure.engine

While the `mm1` and `xeen` sub-engines are enabled by default, the `mm` engine itself is not.
This leads to the engine completely being disabled when building in release mode since the engines are not built by default. Assuming that we already announced testing for the subengines, the main engines should be enabled by default as well.

MM: Enable engine by default

---

engines/cge/events.cpp

To see the current issue, open Soltys, skip intro, wait until character is playable in Screen 1, and press `ALT`+`X` once. `CGEEngine::quit()` gets executed twice and the Quit Menu will toggle twice, disappearing. Keeping `ALT`+`X` pressed makes it keep toggling. Normal intended behavior can be seen by mouse-clicking the Quit button. This fixes the keyboard route.

CGE: Make ALT+X trigger quit() only on initial keypress

---

engines/gob/detection/tables.h
engines/gob/detection/tables_playtoons.h

similar like dynastywood id
This Non-Interactive demo contains VMD's for every Playtoons game and not Playtoons 1 only.
This Demo is listed with the gameid already as playtoonsdemo under the Game Demos site of scummvm.org

GOB: Use playtoonsdemo for Non-interactive demo

---

common/error.cpp
common/error.h
gui/error.cpp

Normally, translating the error description only happens in `GUI::displayErrorDialog()` so that the English version can still be used for console logs, but because the string was modified in the `Common::Error` constructor, it doesn't match any of the original strings in `translation.dat`.

COMMON: Fix translation of error messages

---

engines/ags/ags.cpp
engines/ags/game_scanner.cpp
engines/ags/game_scanner.h

When detection is in dynamic plugin, the detection tables are included twice. Once in the detection plugin and once in the engine for the game scanner code.
We disable the feature in this case to prevent duplication as this feature is only used in specific cases.

AGS: Disable game scanner when detection is dynamic

---

engines/gob/detection/tables_woodruff.h

Woodruff requires Windows 3.1, its not an DOS game

GOB: Mark all Woodruff entries as Windows

---

engines/director/detection_tables.h
engines/director/lingo/lingo-object.cpp
engines/director/lingo/xlibs/findwin.cpp
engines/director/lingo/xlibs/findwin.h
engines/director/module.mk

Submitting as PR due to the new macro I defined. I did this because without this, the movies refuse to play after complaining about a too low color depth.
Launching the game currently fails:
```
Starting v501 Director game
Director pixelformat is: RGBA8888@4
WARNING: NinePatchBitmap::NinePatchBitmap(): Bad bitmap!
WARNING: NinePatchBitmap::NinePatchBitmap(): Bad bitmap!
WARNING: Lingo Inited!
WARNING: No LINGO.INI!
WARNING: DirectorEngine::loadEXEv5(): PJ95 projector pflags: 00000012  flags: 00000017!
WARNING: RIFX: type: APPL!
WARNING: mmap: version: 4c1!
WARNING: RIFX: type: MV93!
WARNING: mmap: version: 4c1!
WARNING: FSDirectory::createReadStreamForMemberAltStream: Can't create stream for file 'START516.EXE' alt stream type 2!
WARNING: Cast::loadCastInfo(): BUILDBOT: extra 6 strings! …
```

DIRECTOR: Add (preliminary) support for Tivola Spring 1999 demo

---

audio/soundfont/vab/psxspu.h
backends/plugins/psp2/psp2-provider.cpp
backends/plugins/riscos/riscos-provider.cpp
common/forbidden.h
engines/grim/emi/costume/emihead.cpp
engines/grim/emi/modelemi.cpp
engines/grim/emi/sound/track.cpp
engines/groovie/video/player.cpp
math/vector3d.h

Using `MIN` and `MAX` from `common/util.h` is more portable.

COMMON: Remove use of fmin/fmax/fminf/fmaxf

---

backends/fs/posix/posix-iostream.cpp
backends/fs/stdiostream.cpp
configure

The availability of `fseeko64`/`ftello64` doesn't necessarily mean that `fopen64` is available as well.

CONFIGURE: Check if fopen64 is available before using it

---

configure
graphics/blit/blit-avx2.cpp
graphics/blit/blit-neon.cpp
graphics/blit/blit-sse2.cpp
graphics/module.mk

This removes the compiler command line arch specifications from the SIMD blit code and replaces them with pragmas that only affect the blit code functions.
This prevents the functions defined in the headers from being compiled with instruction set extensions, which in turn prevents them from replacing definitions of the same functions defined in other modules due to the C++ one definition rule.

GRAPHICS: Use target pragmas instead of compiler flags to prevent ODR problems

---

engines/ags/lib/allegro/surface_sse2.cpp
graphics/blit/blit-sse2.cpp

This just includes the SSE2 intrinsics without the ones from later CPUs.

GRAPHICS: Use emmintrin.h for SSE2 intrinsics

---

engines/ultima/ultima8/graphics/fonts/font.cpp
engines/ultima/ultima8/graphics/fonts/font.h
engines/ultima/ultima8/graphics/fonts/jp_font.cpp
engines/ultima/ultima8/graphics/fonts/jp_font.h
engines/ultima/ultima8/graphics/fonts/shape_font.cpp
engines/ultima/ultima8/graphics/fonts/shape_font.h
engines/ultima/ultima8/graphics/fonts/tt_font.cpp
engines/ultima/ultima8/graphics/fonts/tt_font.h
engines/ultima/ultima8/gumps/book_gump.cpp
engines/ultima/ultima8/gumps/scroll_gump.cpp
engines/ultima/ultima8/gumps/widgets/edit_widget.cpp
engines/ultima/ultima8/gumps/widgets/text_widget.cpp
engines/ultima/ultima8/gumps/widgets/text_widget.h

Now interpreting page breaks in scrolls and books. Verified the behaviour of those two gumps in dosbox. Also verified that plaques treat '*' as a linebreak.
Fixes #14833.

ULTIMA8: Interpret book page breaks correctly

---

engines/ags/detection_tables.h

Adds the newest version of A Tale of Two Kingdoms to the detection table.

AGS: Detect ATOTK German update

---

engines/ultima/ultima8/graphics/fonts/font.cpp

This fixes trailing spaces on the last line of the text impacting centering, as well as tabs at the start of lines.
Fixes #14832.

ULTIMA8: Fix impact of certain spaces on text centering

---

dists/android/AndroidManifest.xml
dists/android/build.gradle
dists/android/res/values/strings.xml

This allows to have official release and daily builds side by side.
I expect this will be harmless on existing installations.

ANDROID: Set a different package name for debug builds

---

engines/pegasus/movie.cpp
engines/pegasus/movie.h

This is a proposed solution for bug report #14855
The workaround, enableEditListBoundsCheckQuirk(true), is applied to movies loaded with Movie::initFromMovieFile(), which is where the problematic video file is loaded from.
The problematic video file is under path "Images/AI/Caldoria/XAE1"
Not all files loaded from Movie::initFromMovieFile() need the workaround, but for the few I tested, it didn't seem to have side-effects on them. 
This change, as of yet, does not apply the workaround to video files loaded elsewhere in the engine (ie. outside Movie::initFromMovieFile())

PEGASUS: Use quicktime workaround for movies

---

engines/director/detection_paths.h

Fixes missing comma caught by Coverity from commit cd2b0fd434605e9e2f2d7f485983f2b6e2b1c7f9, which was breaking some detection paths.

DIRECTOR: Fix missing comma breaking some detection paths

---

common/tokenizer.cpp
common/tokenizer.h

This PR extends the StringTokenizer and U32StringTokenizer
classes with two new functions each. When called, they return
a substring of the original input, containing the lists of all
delimiters immediately surrounding the token that is
currently being processed.
Take the following string, when using ", " as a delimiter list:
"  Hey, hi, hello!   "
If we call nextToken() once, its return value will be the
string "Hey". The functions added in this PR allow us to
get the delimiters surrounding the "Hey". Thus, our output
will be the following:
delimitersAtTokenBegin() will return "   "
delimitersAtTokenEnd() will return ", "
Calling nextToken() again will change the functions' output
to the delimiters surrounding the token "hi", and so on.
They also take into account cases where a token is …

COMMON: Extend Tokenizer classes to allow extraction of delimiters around tokens

---

engines/stark/resources/sound.cpp

This should address bug report #12956 about the missing sounds
It seems that the Steam version of TLJ has the .ssn sounds (found in the GOG version) as ovs (ogg vorbis) sounds.
I have tested with the provided saved game, and this fixes the sounds that were not loading (I think it's trains arriving/leaving sfx)
I only have the GOG version and the Steam versions of the game to test. I do not have any of the CDs version(s).

STARK: Fix not loading ssn sounds in Steam version

---

common/path.cpp

This PR follows comment from @mikrosk and the bug [#14853](https://bugs.scummvm.org/ticket/14853) with @wjp analysis.
This change should be safe as our escape system doesn't mess with case.
In addition, we compare underlying strings to check equality so hashing its content should work too.
The Path class is supposed to always store the path in a canonical way.
It means that if escaping is not needed, the string is converted back to an unescaped version.
Hence, two identical paths can only be stored in the same identical way.
This fact is already used for equals and (in)equality operators.
That's why IMO it's OK to optimize these functions and skip the component iteration.
I issue a PR to be sure I don't miss any unintended side-effect in my reasoning.

COMMON: Use hashit, hashit_lower, equalsIgnoreCase on Path string

---

engines/scumm/script_v5.cpp

As discussed on #engine-scumm ...
Just before Guybrush sinks to the ocean floor, he is drawn at the wrong position for a split second. This happens in the original too, though I found it much easier to spot in ScummVM for some reason. We work around this by setting Guybrush's elevation at the same time as he's put into the room.
Maybe there's a better fix, maybe the comment needs to be reworded. I don't know, I just didn't want it to be lost.
The easiest way to test this is to use boot param 989.

SCUMM: Add workaround for MI2 glitch when diving to the Mad Monkey

---

base/commandLine.cpp

The "soundfont" option is excluded from this, since that is expected to be a file path.
The PR is submitted for consideration as an extension to the command line to allow more leniency with the path arguments, ie. when a file path is set for a folder path argument in command line, it is converted to the appropriate folder path for the file, so that scummvm won't throw an error and exit.
The motivation for the PR was the discussion in this forum thread: <https://forums.scummvm.org/viewtopic.php?t=17015>

BASE: Ensure folder path when file path set in command line

---

engines/scumm/insane/insane.cpp
engines/scumm/smush/smush_player.cpp

This was inspired by bug report https://bugs.scummvm.org/ticket/14876
It is a naive fix, whereby I've added checks for nullptr where Visual Studio debugging would crash with exception, due to trying to access a nullptr pointer.
It works for the specific crash case, but someone more familiar with the engines should review it.
The crash itself seems to be caused by the game data folder missing the resource file for subtitles in that scene (which I think is the "DATA\MINEROAD.TRS").

SCUMM: Fix crash when missing TRS file in Full Throttle

---

engines/director/castmember/bitmap.cpp

This Dumps all Bitmap cast members into PNGs when --dump-scripts is invoked.

DIRECTOR: Dump bitmap as PNGs when --dump-scripts is invoked

---

backends/graphics/android/android-graphics.cpp
backends/graphics3d/android/android-graphics3d.cpp
backends/platform/android/android.cpp
backends/platform/android/jni-android.cpp
backends/platform/android/jni-android.h
backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java

This makes the scaling more adapted to the smartphone screen.
I added some correction factor because without it, I found the texts quite big.

ANDROID: Get HiDPI density from Android metrics

---

graphics/opengl/context.cpp
graphics/opengl/shader.cpp

Aliasing doesn't cover all the functions we use.
In addition, old GLSL 1.00 doesn't support the #version stance.
This should fix bug [#14809](https://bugs.scummvm.org/ticket/14809).

GRAPHICS: OPENGL: Don't try to use GLAD aliasing for shaders

---

engines/hypno/detection.cpp

This adds another detection entry for the Hebrew release, matching the file structure available on CD before installing
which aligns with the instructions in https://wiki.scummvm.org/index.php?title=Marvel_Comics_Spider-Man:_The_Sinister_Six
Thanks

HYPNO: Add Hebrew detection entry for CD structure

---

engines/scumm/actor.cpp
engines/scumm/actor.h
engines/scumm/imuse/imuse_player.cpp
engines/scumm/players/player_mac_indy3.cpp

* warning: comparison of integer expressions of different signedness
* memset clearing an object of non-trivial type

SCUMM: Fix GCC warnings

---

.readthedocs.yaml
NEWS.md
doc/docportal/_static/custom.css
doc/docportal/advanced_topics/autostart.rst
doc/docportal/advanced_topics/command_line.rst
doc/docportal/advanced_topics/configuration_file.rst
doc/docportal/conf.py
doc/docportal/help/report_bugs.rst
doc/docportal/index.rst
doc/docportal/requirements.txt
doc/docportal/settings/keymaps.rst
doc/docportal/use_scummvm/install_computer.rst
doc/docportal/use_scummvm/mac_game_files.rst
doc/docportal/use_scummvm/save_load_games.rst

- Only enforce major versions and not specific versions of packages
- Replace obsolete sphinx_panels extension by sphinx_design which is
maintained
- Remove useless sphinx_tabs.tabs (tabs from sphinx_panels were used)
- Only enforce Python 3 instead of setting the minor version
This also fixes the documentation build and remove warnings.

DOCS: Update Sphinx to latest version

---

engines/director/archive.cpp
engines/director/archive.h
engines/director/channel.cpp
engines/director/director.cpp
engines/director/director.h
engines/director/events.cpp
engines/director/frame.cpp
engines/director/game-quirks.cpp
engines/director/lingo/lingo-builtins.cpp
engines/director/lingo/lingo-the.cpp
engines/director/score.cpp
engines/director/sound.cpp
engines/director/util.cpp
engines/director/util.h
engines/director/window.cpp

DIRECTOR: Spaceship Warlock fixes

---

engines/m4/burger/burger.cpp
engines/m4/platform/sound/digi.cpp
engines/m4/platform/sound/digi.h

This PR fixes the issue of not playing the correct speech sequence when using the kibble from Wilbur's inventory
It also fixes an issue that was detecting during testing the above fix, whereby some sounds would not play a second time. This was due to the unload() method for sounds being called twice in some cases, which seems unintended.

M4: Orion burger fix for using kibble in test2 and a general sound unload fix

---

engines/icb/common/px_array.h

I found a compile problem when building scummvm 2.8 for Fedora rawhide:
- Fedora 38: OK (GCC 13.2.1)
- Fedora 39: OK (GCC 13.2.1)
- Fedora rawhide / upcoming F40: doesn't compile (GCC 14.0.1):
```
g++ -MMD -MF "engines/icb/.deps/actor.d" -MQ "engines/icb/actor.o" -MP -Wall -O2  -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer   -Wshadow -W -Wno-unused-parameter -Wno-empty-body -fno-operator-names -std=c++11 -pedantic …
```

ICB: compile fix for GCC 14

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp

As discussed in https://bugs.scummvm.org/ticket/14872 it seems like when the scaler changes, the cursor scaler doesn't always change along with it. In this particular bug report, that caused it to use the HQ scaler for the mouse cursor, which normally isn't allowed. That, in combination with some hinky pointer arithmetics (that's also described in the bug report), then caused ScummVM to crash.
I hope that changing SurfaceSdlGraphicsManager::setGraphicsModeIntern() to refresh _mouseScaler along with _scaler (though only if there is a _mouseScaler to begin with, since I don't know if that's guaranteed) is the correct fix for it. I don't call _mouseScaler_>setFactor() because that's always left to SurfaceSdlGraphicsManager::blitCursor().
I don't know if the crash also points to some bug in …

SURFACESDL: [RFC] Possible fix for scaler crash (bug #14872)

---

gui/ThemeEngine.cpp
gui/ThemeEngine.h
gui/console.cpp
gui/console.h

GUI: Add feature to copy text from console

---

configure

While this flag did not exhibit known issues on the initial opendingux port, it is rather unsafe and hard to guarantee it won't in future builds.
Remove it for better stability.

OPENDINGUX: remove -ffast-math

---

engines/director/cast.cpp
engines/director/castmember/filmloop.cpp
engines/director/sprite.cpp

This patch adds support for filmloops composed of other filmloops. It also fixes a bug in the filmloop bbox computation during Sprite::setCast() , we have to create a case kCastFilmLoop to prevent it from going to default case as the default case equates it to dims which is initialrect (0 value) , so the setCast function basically made film loop bbox 0.
trello link:- https://trello.com/c/uOzokEHj/712-fish-in-aquarium-is-not-displayed

DIRECTOR: Manage filmloop composed of other filmloops.

---

NEWS.md
audio/mididrv.h
backends/midi/alsa.cpp
engines/mm/mm1/maps/map.cpp
engines/mm/module.mk
engines/mm/shared/xeen/sound.cpp
engines/mm/shared/xeen/sound.h
engines/mm/shared/xeen/sound_driver.cpp
engines/mm/shared/xeen/sound_driver.h
engines/mm/shared/xeen/sound_driver_adlib.cpp
engines/mm/shared/xeen/sound_driver_mt32.cpp
engines/mm/shared/xeen/sound_driver_mt32.h
engines/mm/xeen/dialogs/dialogs_control_panel.cpp

- Added MT32/LAPC-1 MIDI support for Xeen. It is currently the same as original game, so Roland GS and there are no conversion to GM. Music tracks requires at least MT32-compatible device with support of capital tone fallback in ROM. Game is also extensively uses extended sounds found in CM-32L for sound effects, MT-32 will produce silence for those. So using in combination with real CM-32L or emulated one is the best for now.
- Fixed Xeen regression which affects sound effects with countdown, like creaking door effect, and cause them to stop abruptly.
- Added previously missing sound effect in Xeen when Efx is enabled in control panel.
- Also support alternative version of resources circulating in the wild for MM1.

MM: MT32/LAPC-1 support for Xeen and other fixes

---

engines/voyeur/voyeur.cpp
engines/voyeur/voyeur.h
video/mve_decoder.h

This PR adds the Interplay logo animation to Voyeur. The animation is stored inside `logo8.exe` It is encoded as a MVE video stream.
Left mouse click, space or Escape will skip the video.

VOYEUR: Add Interplay logo animation sequence (logo8.exe)

---

backends/platform/sdl/amigaos/amigaos.cpp

- Fixed a typo in comment
- Reverted the locally set default aspect ratio setting (was set to true) since #5668 will (hopefully) be merged into main which will bring said setting

AMIGAOS: Fix typo and revert default aspect ratio

---

backends/platform/ios7/ios7_keyboard.h
backends/platform/ios7/ios7_keyboard.mm
backends/platform/ios7/ios7_osys_events.cpp
backends/platform/ios7/ios7_osys_main.h
backends/platform/ios7/ios7_video.mm

Currently the key inputs are sent to the IOS7 event handler on calls
to the delegate function:
"textField:shouldChangeCharactersInRange:replacementString:"
So when typing on either the software keyboard or a connected HW
keyboard the input is handled by the hidden textfield that is in
focus. The delegate is called on each key input and the character
typed is passed to the IOS7 event handler.
Doing as above has the drawback that if they user holds down a key,
common in games when shooting or moving, the key event is only sent
once. The delegate function is only called once per distinct key
press.
By implementing the keyCommands function and create UIKeyCommands
for a set of keys, the system will call a defined callback function.
This also enables repeatedly calls as long as the key is held …

IOS7: Overload key input

---

backends/keymapper/keymapper.h
engines/ultima/nuvie/core/effect.cpp
engines/ultima/nuvie/core/events.cpp
engines/ultima/nuvie/core/events.h
engines/ultima/nuvie/gui/gui.cpp
engines/ultima/nuvie/views/spell_view.cpp
engines/ultima/nuvie/views/spell_view_gump.cpp

- Fix regression which made it impossible to enter some spell syllables using the keyboard.
Fixes [#14959](https://bugs.scummvm.org/ticket/14959) "Cannot Cast Spells using Keyboard in Ultima VI"
- Fix crash due to inventory gump deleting itself in its own event handler when opening the spellbook from a look action or for selection of an object to use with the enchant spell.
Fixes [#14957](https://bugs.scummvm.org/ticket/14957) "Using an Enchanted Staff spell crashes the game in Ultima VI"
- Fix some spellbook crashes when selecting a spell for enchant.
- Lock input to spellbook when looking at it so it can be navigated using the keyboard.
- Fix regression which prevented controlling Wizard Eye via the cursor keys.

ULTIMA: NUVIE: U6 spellbook fixes

---

audio/softsynth/fluidsynth.cpp

The user can specify a custom soundfont to be used with fluidsynth. There was previously a hack for the iOS7 backend to get the path to the document folder where the user can put files in a sandboxed environment. This hack was removed in commit:
cac06647571a3352cb108faad48af9271a69ce36
The problem however occurred when creating a FSNode from the full system path because FSNode uses makeFileNodePath, which already prepends the root. So the full path is added twice which causes the fileNode.exists() to fail.
Create the FSNode from the path to the soundfont and check if the file exist. If so then return the full path.

AUDIO: Fix problem where fluidsynth soundfont could not be loaded

---

common/data-io.h
common/stream.h
engines/mtropolis/data.cpp
engines/mtropolis/data.h

This pulls the multi-value IO templates down from mTropolis into Common and integrates them with ReadStream and WriteStream.
This is intended to add some better API for reading and writing multiple endian-specific values and checking for failure.  The problem right now the number read functions don't report the error at the call site, and also return uninitialized garbage if the read fails.  We have 2 functions that have to be called for failure (eof and eos), and a lot of code just forgets to check them.  This also hits the stream interface a lot.
The new code uses C++ variadic templates to read all of the values into a stack buffer at once with a single read call, check if the read size was the expected size and return false if not, and decode the values if the read succeeded.
This …

COMMON: Add multiple-value IO functions

---

engines/director/castmember/sound.cpp
engines/director/sound.cpp
engines/director/sound.h

In some D4 version 400 (file version 0x45B) files, sound resource loop bounds are invalid but their cast member flags are set to loop. Examples are "Barbie and her Magical Dreamhouse" and "Necrobius" (Windows demo). Invalid is any situation where the following does not hold: `loop_start < loop_end <= size`
In the original environment, these resources are handled by disabling the looping flag and resetting the loop bounds on the sound resources to 0 -> sample size.
This commit checks for invalid loop bounds and applies roughly the same fix. This fixes the invalid sound looping behaviours present in the aforementioned titles.

DIRECTOR: Correct for invalid loop bounds in D4

---

engines/agi/words.cpp

This fixes bug #15000 "V Demo does not recognize valid word ammunition"
Our code was actually not parsing correctly many (all?) words starting with "a" in this particular game.
I've also quickly checked with Space Quest 0 AGI fan made game and it seems that the workaround code (which was made for a bug reported for that game) still works with my fix. 
Of course someone more familiar with the AGI engine should review this.

AGI: Fix missing words from our dictionary

---

doc/docportal/requirements.txt

Make a PR to have CI check before merge. This is a cherry-pick of 9e188bff2029bb55f8e4384a602220968135b295.
Latest versions of sphinxcontrib dropped sphinx requirement and checks the version at runtime.
By pinning to the latest versions supporting Sphinx 4, build succeeds.

DOCS: Fix docs build for 2.8

---

common/events.cpp

This fixes a segfault on a linux build for armhf Amlogic of the libretro port, occurring everytime a input event is received (e.g. user presses any button).
It seems related to compiler optimization level (as with `-O0` does not occur) and `gcc` version (occurs with v12.2.0 but not with v10.2.0).

COMMON: move mappedEvents declaration out of for loop

---

Makefile.common
backends/platform/sdl/win32/win32.mk

Fixes multiple issues with the new resource files on Win32 builds.
Make .rh files dependent on their contents (maybe they should be deps of the .rc file, but this seems slightly easier)
Make .rh files dependent on the .mk file that their item lists come from
Fix .rh files not creating destination directory
Fix .rh dependencies of .rc file being source-relative instead of build-relative
Fix .rh clean paths being source-relative instead of build-relative
Fix .rh generation appending to the old .rh instead of overwriting

DISTS: Fix numerous problems with resource compilation on Win32 MinGW build

---

engines/agi/agi.h
engines/agi/cycle.cpp
engines/agi/op_cmd.cpp
engines/agi/opcodes.cpp
engines/agi/opcodes.h

This fixes overwriting variables 27-29 in all AGI games.
AGIMOUSE was a modified interpreter that wrote mouse state to variables 27-29 so fan games could use mouse functions. We have been doing this unconditionally, and overwriting these variables in all games. When I saw this code, I said "wait, won't that break normal games?" and then looked in the tracker and found a three year old ticket about a fan game named Phil's Quest where you instantly die in ScummVM: https://bugs.scummvm.org/ticket/12747 . The health meter is variable 28, which is AGIMOUSE's x coordinate, so really you die depending on if the mouse is on the left or right side of the screen.
Scanning my corpus of AGI games, I see that these variables are used in plenty of others, so this has caused other subtle problems.
We …

AGI: Restrict AGIMOUSE feature to AGIMOUSE games

---

engines/macventure/macventure.cpp
engines/macventure/stringtable.h

files in games like "Déjà Vu" are dumped to disk after being unicode encoded, whereas the game expected them to be in MacRoman

MACVENTURE: Fix loading filenames with unicode characters

---

engines/agi/cycle.cpp

This PR fixes AGIMOUSE implementation issues. The fan game "DG: The AGIMouse Adventure" is now playable. The buttons can be clicked without freezing and there are no longer phantom clicks after message boxes disappear. https://bugs.scummvm.org/ticket/10737
1. Mouse button state is now reset when changing rooms. The `new.room` opcode stops the current script (logic) execution and re-executes script 0. We don't poll events before re-executing script 0, so if we don't reset this button state, then a script that calls `new.room` in response to a mouse click will keep seeing that click on the next re-execution, call `new.room` again, and loop forever.
2. AGIMOUSE variables are now only set when game scripts ask for them. According to the documentation, and the sample games, that's the entire …

AGI: Fix AGIMOUSE implementation

---

devtools/create_engine/files/xyzzy.cpp

Use the `FrameLimiter` to prevent using a fixed `delayMillis`

CREATE_ENGINE: use the FrameLimiter class in xyzzy template

---

engines/pink/screen.cpp
engines/scumm/gfx.cpp
engines/scumm/macgui/macgui_impl.cpp
engines/scumm/scumm.cpp
engines/scumm/scumm.h
graphics/macgui/macwindowmanager.cpp
graphics/macgui/macwindowmanager.h

This is my attempt at fixing https://bugs.scummvm.org/ticket/15006 where the screen gets corrupted if the Mac menu opens at the wrong time.
When the mouse cursor reaches the top of the screen, a timer is set to activate the menu. The timer function then pauses the game, makes a copy of the current screen (to be used for restoring the screen once the menu closes, I believe?), and tells the menu to activate.
The problem appears to be that if the SCUMM engine is in the middle of a graphics transition (e.g. when walking between rooms), the screen will keep changing even though the game is paused.
This patch does two things:
First, I suspect the timer itself can be the cause of unexpected behavior, so I've eliminated that. I've also moved the screen copying to right before the menu is drawn. …

SCUMM: Attempt to fix Mac menu screen corruption (bug #15006)

---

graphics/palette.cpp
graphics/palette.h

Adding a common definition for palette can allow us to simplify handling of palettes, reduce duplicate logic, and potentially share the memory rather than duplicate in some places.
Replacement for PR #5648 as a class and isolated use to PaletteLookup. The previous PR shows more potential uses that helped determine what what could be included in the Palette class. 
This also removes an unnecessary use of sqrt in color distance calculation.

GRAPHICS: Define Palette class (version 2)

---

engines/mtropolis/plugin/mti.cpp
engines/testbed/misc.cpp
gui/imagealbum-dialog.cpp
gui/imagealbum-dialog.h

Split out from #5648 - Replace palette byte arrays with Palette class in image album dialog
Note fi._decoder->getPaletteStartIndex() was always zero in practice but the use during memcpy was different in mtropolis & testbed

GUI: Use Palette class in image album dialog

---

graphics/macgui/macwindow.cpp
graphics/macgui/macwindowborder.cpp

Updating Border offsets when ever setBorderType is called and ensure resizeBordersurface reallocates memory to border only when dimensions have changed

GUI: Implement Window border draggability

---

backends/graphics3d/opengl/surfacerenderer.cpp
backends/networking/enet/source/unix.cpp
graphics/opengl/context.cpp
graphics/opengl/shader.cpp

This is an attempt to clean up and reduce usage of the configure define (AMIGAOS) from actual source files to only .mk files.
There are only six occurances within four source files, over the whole code base, that make use of that define.
-graphics/opengl/shader.cpp
-graphics/opengl/context.cpp
-backends/graphis3d/opengl/surfacerenderer.cpp
-backends/networking/enet/source/unix.cpp
while all other source files use the compiler define for my platform (__amigaos4__).
To not promote the usage of such define in future source file changes (apart .mk) i'd like to get rid of it.
If that doesn't sound logical, please advise
Thank you

AMIGAOS: (Janitorial) Subsitute mk defines with compiler defines

---

backends/platform/sdl/amigaos/amigaos-main.cpp
backends/platform/sdl/amigaos/amigaos.cpp
backends/platform/sdl/amigaos/amigaos.h

Second attempt at fixing [#6956](https://bugs.scummvm.org/ticket/6956) "ScummVM returned with unfreed signals (AmigaOS4)".
This only runs the cleanup code if the OSystem_AmigaOS instance has not been destroyed already.
Should prevent crashes after calls to error(), which on AmigaOS already cleans up via OSystem_SDL::fatalError().

AMIGAOS: Cleanup and free signals via atexit(), 2nd attempt 

---

backends/imgui/backends/imgui_impl_opengl3_loader.h
backends/imgui/backends/imgui_impl_opengl3_scummvm.cpp

This should fix builds of Raspberry Pi and Switch

BACKENDS: IMGUI: Use ScummVM facilities to get function pointers

---

configure

- revert -mlongcall as gcc flag
in raziel-@8366119
i tested with only one engine, to not make testing the changes as time consuming
as it would have been, given i had to rebuild scummvm every time (yes, it's a
strange platform and no, most of the make tricks to speed things up won't work) :-)
So, the engine i used for testing was AGI.
All went well, nothing bad happened and i removed some flags in the mentioned PR.
Until i began to test the AGS engine due to an exit crash and then things went
downhill. I got strange crashes right on start, ELF library errors and random
errors all over the place.
i don't know what the size peak for -mshortcall is (i did not test with different
sized engines as i would have to build every engine on it's own for every test, together
with the accompanying …

AMIGAOS: revert compiler flag and more cleanup

---

NEWS.md
audio/mididrv.cpp
audio/mididrv.h
base/commandLine.cpp

Changes GM device back to "null" in 2.8.1, pending addition of more status checks for "auto"

AUDIO: Change default GM device back to "null"

---

engines/ags/plugins/ags_waves/ags_waves.h
engines/ags/plugins/ags_waves/sound.cpp

This is another way to fix bug exposed in PR #5664.
I think it's a bit cleaner but not too invasive.

AGS: Don't use FSNode but rely on AGS facilities to load sound files

---

engines/ags/engine/media/video/video.cpp
engines/ultima/nuvie/misc/sdl_compat.cpp
engines/vcruise/runtime.cpp
graphics/managed_surface.cpp
graphics/managed_surface.h
graphics/palette.cpp
graphics/palette.h

Update many palette usages in managed surface from passed in byte arrays to the Palette class. There were surprisingly few uses of them, several being from decoders that have null palettes when checked.
Palette class can also now take a byte array pointer & size, which allows null and simply will set size to 0

GRAPHICS: Switch ManagedSurface to use Palette class

---

audio/mods/rjp1.cpp

Resolve an issue where the value was incorrectly treated as a signed integer during multiplication/division. This was causing fluctuations in volume, with levels varying up and down.
The original code reads the envelopeEnd(1 and 2) value as a byte, extends it to a word then ANDs it with 0x00FF before multiplying/dividing.

AUDIO: Fix integer sign extension issue in RJP1 envelope scaling

---

engines/agi/motion.cpp
engines/agi/op_cmd.cpp
engines/agi/saveload.cpp
engines/agi/view.cpp
engines/agi/view.h

This PR fixes inaccuracies in several AGI games by implementing motion/cycler overwrite behavior. ScummVM used to do this until a refactor unintentionally altered it. When this was discovered, a workaround was added with new behavior that fixed one instance but caused more inaccuracies.
In original AGI, motion and cycler data were both stored in the same 4 bytes of the screen object structure. If a script ran a motion during a cycler, or a cycler during a motion, then the interpreter would overwrite the previous action's state and let them both run. This caused the bytes from one action to be interpreted as another's state. This could alter a motion, or cause an unintended game flag to be set when a cycler completes.
At least four games rely on this:
- King's Quest I: Jumping at the eagle …

AGI: Implement motion/cycler overwrite behavior

---

engines/director/window.cpp
graphics/macgui/macwindow.cpp
graphics/macgui/macwindow.h

Fixes ["main stage should not be draggable"](https://trello.com/c/wzRGgaZB/424-main-stage-should-not-be-draggable-in-desktop-mode) for the Director engine.

DIRECTOR: fix "stage should not be draggable"

---

gui/launcher.cpp
gui/launcher.h
gui/widgets/grid.cpp
gui/widgets/grid.h
gui/widgets/groupedlist.cpp
gui/widgets/groupedlist.h

Adjust the selector position after removing a game in both list and grid views. The selector should move to the next game unless the removed game was the last one. In that case, the selector should move to the previous game.

GUI: Fix selector position after removing a game.

---

audio/softsynth/mt32.cpp

Fix mt32 to load rom data in pairs to prevent loading a mix of CM32L and MT32 files.
https://bugs.scummvm.org/ticket/15014#ticket
Loads after fix applied.

MIDI: load CM32L_*.ROM or MT32_*.ROM as pairs

---

engines/cryomni3d/cryomni3d.cpp
engines/cryomni3d/fixed_image.cpp
engines/cryomni3d/versailles/documentation.cpp
engines/cryomni3d/versailles/engine.cpp
engines/cryomni3d/versailles/menus.cpp
engines/freescape/freescape.cpp
engines/freescape/gfx.cpp
engines/glk/debugger.cpp
engines/mohawk/myst_graphics.cpp
engines/mtropolis/plugin/mti.cpp
engines/nancy/resource.cpp
engines/testbed/misc.cpp
engines/twine/renderer/screens.cpp
engines/ultima/ultima8/gumps/cru_credits_gump.cpp
engines/ultima/ultima8/gumps/cru_demo_gump.cpp
graphics/macgui/macwindowborder.cpp
graphics/managed_surface.h
graphics/surface.cpp
graphics/surface.h
gui/imagealbum-dialog.cpp
image/image_decoder.h

Part of ongoing cleanup of palette handling: The palette start value was always zero, adding complexity without benefit, and removal may ease adoption of the palette class.

IMAGE: Remove palette start from image decoder.

---

backends/platform/android/android.cpp
backends/platform/android/android.h
backends/platform/android/jni-android.cpp
backends/platform/android/jni-android.h
backends/platform/android/options.cpp
backends/platform/android/org/scummvm/scummvm/ScummVM.java
backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java

There are two changes:
- make the on screen buttons vertical when in landscape and horizontal when in portrait mode
- hide the menu icon while not in-game
I hope the last one will make the update pass on the store.

ANDROID: Fixes on on-screen buttons

---

engines/made/detection_tables.h

This is a rare release of The Manhole for Sega's TeraDrive computer, which contains both an IBM DOS PC and a Sega Genesis. This game mostly runs on the DOS half, but uses the Genesis hardware for sound. According to screenshots, it seems to be largely based on the FM Towns version and uses its 256 colour art, but was released on a floppy. It doesn't boot; it immediately crashes with "Failed to find picture 10!".
I'm unclear whether we need a new platform for this or if it counts as "DOS".

MADE: TeraDrive Manhole

---

engines/metaengine.cpp
engines/metaengine.h

This pull requests allow to override the default achievements platform, today this platform comes from the `extra`field from a game description.
**Why?**
In `Thimbleweed Park` I want to propose the steam achievements even for GOG and EPIC games.
**Example**
Here I have a game for GOG but using the Steam achievements:
```cpp
Common::AchievementsPlatform TwpMetaEngine::getAchievementsPlatform(const Common::String &target) const {
return Common::STEAM_ACHIEVEMENTS;
}
```

ACHIEVEMENTS: Allow to override the default achievements platform

---

graphics/nine_patch.cpp

This PR prevents a crash caused by an invalid rectangle in macventure games. The remaining stretch area is given to the first stretchable mark.
Previously, a stretchable ninepatch mark's length was rounded up to the next integer, this caused the total length to exceed the available length, leading to the crash in macventure.
The reason for rounding up can be found here: [url](https://blogs.scummvm.org/stablesteady/2022/07/17/week-8-working-on-wage/)

GRAPHICS: NINEPATCH: Change the way remaining_stretch is distributed

---

gui/widgets/editable.cpp
gui/widgets/editable.h
gui/widgets/edittext.cpp
gui/widgets/list.cpp

Something that's been bugging me for ages is that if you use the arrow keys to move the caret in an editable widget, the caret is not drawn. This makes it hard to know where you will end up.
So imagine my surprise when I realized that the editable widget all along has been trying to force the caret visible. Except it didn't work, because if the widget was also marked as "dirty" (which it usually is?), it's immediately drawn over the caret. To get around this, I've made EditableWidget responsible for drawing the caret as part of the widget when necessary.
To further complicate things, the widget's _x and _y are different depending on when drawCaret() is called. I've added an optional parameter to drawCaret() to choose whether to use relative or absolute coordinates. It seems to work, but …

GUI: Keep caret visible in editable widgets while moving it with the keyboard

---

engines/director/detection_tables.h

DIRECTOR: add various games to detection tables
Some points for documentation:
- Romjakten, Rymdjakten and "Wettlauf Ins All" are different translations of the same game
- Djuphavsjakten and "S.O.S. Tiefsee" are different translations of the same game
- Djuphavsjakten  (``havsjakt.exe``) was _not_ recognized by the generic Director detection. ScummVM did not recognize it as anything at all. Should I raise a bug for this?
- Games 1-3 of the Onkel Albert / Uncle Ernest series were not made with Director, but with Mtropolis. They already have their entries in the detection tables of that engine.
- Now we have at least one copy of the Director-based games in the edutainment series by former publisher Heureka-Klett, the *us games like Chemicus, Physicus and Mathicus
- Both Historion games in …

DIRECTOR: add various games to detection tables

---

engines/ultima/ultima4/controllers/intro_controller.cpp
engines/ultima/ultima4/gfx/image.cpp
engines/ultima/ultima4/gfx/image.h
engines/ultima/ultima4/gfx/imagemgr.cpp
engines/ultima/ultima4/gfx/scale.cpp
engines/ultima/ultima4/gfx/screen.cpp
engines/ultima/ultima4/map/tile.cpp
engines/ultima/ultima4/views/tileview.cpp
engines/ultima/ultima4/views/view.cpp

This allows Ultima IV to start on the Nintendo DS, which doesn't support RGB565, and should help performance on other platforms that require converting from RGB565 in software.

ULTIMA4: Support pixel formats other than RGB565

---

common/events.cpp

This is still related to #5677, which seems to have  not solved completely the issue, as segfault is still reported on RPi4 armv7 builds (ref https://github.com/libretro/scummvm/issues/54).
Though looks like redundant, checking if `mappedEvents` list is empty before clearing it seems to solve the issue, as otherwise at the second loop in the for cycle, clearing the empty list will cause segfault (as `_anchor._next` becomes `null` for no apparent reason).
Not sure if root cause is some gcc v12.2 bug (as compiling with `-O0` works properly) or it's some subtle bug somewhere else causing memory corruption for 32bit arm builds.
@bluegr

COMMON: clear mappedEvents list only if empty

---

devtools/create_project/cmake/CMakeLists.txt

Versions less than 3.5 are deprecated. The generated cmake has minimum version 3.13 too.

DEVTOOLS: Raise minimum cmake version to 3.13

---

common/fs.cpp
engines/ultima/nuvie/actors/actor_manager.cpp
engines/ultima/nuvie/files/nuvie_file_list.cpp
engines/ultima/nuvie/files/nuvie_file_list.h
engines/ultima/shared/engine/data_archive.cpp
engines/ultima/shared/engine/data_archive.h

- Do not ignore parameter `matchPathComponents` in `Common::FSDirectory::listMatchingMembers`.
- Implement/rework some Archive interface methods for `Ultima::Shared::UltimaDataArchive` (used in release builds) and `Ultima::Shared::UltimaDataArchiveProxy` (non-release builds).
- Make `Ultima::Nuvie::NuvieFileList::open()` use SearchMan instead of `Common::FSNode` to look up directories.
Fixes [#14960](https://bugs.scummvm.org/ticket/14960) "The nuvie feature 'Use Custom Actor Tiles' is non functional"
Note: Only tested with Ultima 6 on a Linux system.

ULTIMA: NUVIE: Fix loading custom actor tiles (#14960)

---

backends/platform/sdl/win32/win32_wrapper.cpp

This is required for scummvm/dockerized-bb#53.

WIN32: Ensure that _WIN32_WINNT is set high enough for required defines

---

backends/graphics/graphics.h
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.h
backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
backends/graphics3d/openglsdl/openglsdl-graphics3d.h
backends/modular-backend.cpp
backends/modular-backend.h
common/system.h
configure
engines/director/director.cpp
engines/twp/twp.cpp

This is various changes to:
- make `setImGuiRenderCallback` directly available from OSystem as this avoids dynamic_cast (for ImGui enabled target only),
- remove the `_imGuiRender` from the `GraphicsManager` abstract class,
- make ImGui more robust related to context changes in OpenGLSdlGraphics3dManager and remove the state variable,
- make USE_IMGUI defined only when it's actually supported (that is SDL2+ only),
- reset to `nullptr` ImGui callback while exiting engine (to avoid calling a function which could disappear if in a plugin).
This has been tested on SDL2 with TWP and Director and it builds on SDL1 (Win9x) toolchain.
@sev- I add you to reviewers as I touch OSystem interface.

IMGUI: Some cleanups

---

.github/workflows/ci.yml

CI has been breaking since github changed `macos-latest` from `macos-12` to `macos-14`. This also changed the architecture to arm64; that's the only option for `macos-14`.
`macos-13` works and is x86_64. We can still call this an upgrade!
I've also set the `xcodebuild` target because that will be a problem going forward; it's been warning that it's just choosing the first one, which makes the architecture unpredictable once more are available.
https://github.com/actions/runner-images/issues/9741
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

CI: Fix macosx build

---

backends/platform/android/org/scummvm/scummvm/CompatHelpers.java
backends/platform/android/org/scummvm/scummvm/CustomKeyboardView.java
backends/platform/android/org/scummvm/scummvm/ExternalStorage.java
backends/platform/android/org/scummvm/scummvm/ScummVM.java
backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java
backends/platform/android/org/scummvm/scummvm/ScummVMEventsBase.java
backends/platform/android/org/scummvm/scummvm/SplashActivity.java

This is a bunch of commits which remove deprecated warnings mainly by isolating code inside its own function in a class dedicated to compatibility shims.
There is also some API changes to determine if connection is limited (metered) and to make the application immersive.
This has been tested on API level 34 (U).
I will test later on API levels 29 (Q) and 19 (Kit Kat).
I could test on 16 (Jelly Bean) with an emulator too.

ANDROID: Remove deprecation warnings

---

backends/graphics/graphics.h
backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.h
backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
backends/graphics3d/openglsdl/openglsdl-graphics3d.h
backends/modular-backend.cpp
backends/modular-backend.h
common/system.h

I added 2 callbacks: `init` and `cleanup`.
The `init` callback is called just after the ImGui initialisation, in this method you can for example add a custom font or even specify a location where to save the ImGui configuration.
The `cleanup`is called just before the ImGui destruction.
To specify these `callbacks` I modified the `setImGuiRenderCallback` in `ModularGraphicsBackend`.
I changed
```cpp
void ModularGraphicsBackend::setImGuiRenderCallback(void(*render)());
```
by
```cpp
typedef struct ImGuiCallbacks {
void(*init)() = nullptr;
void(*render)() = nullptr;
void(*cleanup)() = nullptr;
} ImGuiCallbacks;
void ModularGraphicsBackend::setImGuiRenderCallback(ImGuiCallbacks callbacks);
```
In the engine you can specify the callbacks like this and that's it:
```cpp
#ifdef USE_IMGUI …
```

BACKENDS: Update setImGuiRenderCallback in OSystem

---

backends/imgui/imgui_fonts.cpp
backends/imgui/imgui_fonts.h
backends/module.mk

Allow to use fonts embedded in `fonts.dat` or `fonts-cjk.dat` in ImGui.
Here is an example how to use it, in this example we merge the default ImGui font with the font `OpenFontIcons.ttf` embedded in `fonts.dat`
```cpp
#include "backends/imgui/imgui_fonts.h"
void onImGuiInit() {
ImGuiIO &io = ImGui::GetIO();
io.Fonts->AddFontDefault();
ImFontConfig icons_config;
icons_config.MergeMode = true;
icons_config.PixelSnapH = false;
icons_config.OversampleH = 3;
icons_config.OversampleV = 3;
icons_config.GlyphOffset = {0, 3};
static const ImWchar icons_ranges[] = {0xE000, 0xF8FF, 0};
ImGui::addTTFFontFromArchive("OpenFontIcons.ttf", 13.f, &icons_config, icons_ranges);
```
Then you display an icon by using its unicode character: `ImGui::Text("\ue072");`
It will display a ❤️
Here is the list of the …

BACKENDS: Add the ability to load ScummVM fonts in ImGui

---

gui/widgets/grid.cpp
gui/widgets/grid.h

This makes it so that games are started on the release of the left mouse button after a double click, instead of during it being pressed.
This fixes the left mouse button release leaking into the launched game as actual engine input (e.g. the intro video to Broken Sword 1 being skipped, since the left mouse button is one of the valid inputs for skipping videos).

GUI: Implement handleMouseUp for Grid layout

---

engines/scumm/cursor.cpp

This is functionally the same, but adds the palette index offset rather than a check condition.
My motivation is to suggest the DefaultWinCursor & BusyWinCursor should include palette entries for the key color rather than using a palette start index of 1. The Scumm engine remap of DefaultWinCursor is the one odd place that would need adjustment for that to be possible as far as I can tell. This change would make that possible as the last three palette values are reserved for replacement by cursors in SCUMM (also done for v70)

SCUMM: Adjust v80 default cursor palette map.

---

graphics/macgui/macfontmanager.cpp
graphics/macgui/macfontmanager.h
gui/widgets/richtext.cpp

I used "GoMono-Regular.ttf" in this case.

GRAPHICS: MACGUI: TTF support in Markdown

---

engines/engine.cpp
engines/engine.h

This reverts commit 741620e4bc3c11b9bbe567ac4ef789975a6efe0e.
This commit breaks several engines like scumm and sword1 because they call quitEngine function without polling the event loop afterwards.
Purging the event loop after the engine has finished would solve this, but the EVENT_QUIT message is supposed to be processed while the engine is still running to let user confirm the quit action (if the setting is enabled).

Revert "ENGINES: Allow shouldQuit to return true immediately"

---

graphics/image-archive.cpp
graphics/image-archive.h
graphics/macgui/mactext-canvas.cpp
graphics/macgui/mactext-canvas.h
graphics/macgui/mactext.cpp
graphics/macgui/mactext.h
graphics/module.mk

Images are now pre-scaled with bilinear filtering. The relevant code has also been split out from the rest of the MacGUI code to allow easier reuse.

GRAPHICS: MACGUI: Improve image quality in markdown documents

---

engines/mtropolis/detection_tables.h
engines/mtropolis/hacks.cpp

MTROPOLIS: Fix Obsidian Widescreen Hacks
- Annotate and cleanup widescreen hacks
- Fix Typo in Win EN version (Limitation Document, Atlas Face) should be 0x4dfa22, was just missing before
- Fix Typo in Mac EN version (Limitation Document, Time Face) should be 0x4e2e7b, had wrong value before
- Enable widescreen hack for international versions
----
Tested these versions and verified GUIDs with the mTropolis debugger, GUIDs do not differ between versions:
- English Mac
- English Win
- German Win
- Japanese Mac
Did not test this version, but would be unlikely to differ from other international versions:
- Italian Win

MTROPOLIS: Fix Obsidian Widescreen Hacks

---

engines/scumm/script.cpp

This PR implements a small change to an existing mod (which is only enabled when the user has the optional "Enable online competitive mods" in ScummVM's game options) for Backyard Baseball 2001 online play. It slightly changes the velocity of hits when the player is using a power swing.
The previous iteration of this mod reduced the velocity of hits with power swings, making them less effective relative to line drive and grounder swings. After 6+ months of competitive play, the consensus among the community is that this has made power swings not viable - using a line drive swing is almost always optimal, which makes gameplay less interesting.
This change is intended to make the decisions on what swing type to use more interesting. This chart shows how the hit's "base power" (really more …

SCUMM HE: BYB01 competitive online play mods: hit power change

---

engines/scumm/gfx.cpp
engines/scumm/he/gfx_comp/trle_comp.cpp
engines/scumm/he/gfx_primitives_he.cpp
engines/scumm/he/wiz_he.cpp
engines/scumm/he/wiz_he.h
engines/scumm/he/wizwarp_he.cpp

Currently, buffers get allocated that do not get freed. Apparently, the reason is that it is not well known when it is actually safe to do that.
The spy watch mini game in Spy Fox 3 leaks A LOT.  This here should hopefully fix the situation. Or at least give some inspiration on how to fix it...

SCUMM: (HE) - fix wiz drawing mem leaks

---

engines/zvision/file/search_manager.cpp

Also comparison is now ignoring case (uses equalsIgnoreCase)
This fix was required since, as reported in #15132, the subtitles addon (within a subfolder "Addon") would no longer work in ScummVM 2.9.0git. As far as I've tested, apart from the ignoreCase comparison, normalize() has to be applied at least on the iterator of the _dirList, since those paths end with a separator ("/").

ZVISION: Fix addDir after 2.9.0 path changes

---

engines/zvision/text/truetype_font.cpp

This adds BiDi support for the subtitles of Zork Nemesis (with subtitles addon)
for supporting the upcoming Hebrew translation of subtitles patch
Thanks
Note: #5796 should be merged for subtitles to show

ZVISION: Add BiDi text support

---

engines/mtropolis/runtime.cpp

Move the assertion dereferencing the newly created `modifier` after the `nullptr` check for `modifier`
If the modifier is `nullptr` because it could not be created, then the early assertion would cause a segfault.
Naturally this did not affect release builds, but was nonetheless bothersome in debug builds.

MTROPOLIS: move assert after nullptr check

---

gui/saveload-dialog.cpp

This PR fixes a minor display regression in the save-load list dialog introduced two years ago: 829c600a02ad6124006ae8cc784a873f52140637
That commit altered how *some* empty slots are rendered when selected. Empty slots that appear before the last save stopped drawing selection color over the text area. Empty slots that appear after the last save continue to correctly draw the selection color across the row.
It looks to me like there are two bugs in the code:
1. The code blocks for creating empty "gap" slots and empty "end" slots are inconsistent.
2. Rendering an item with an empty string produces a much different result than rendering an item with an empty string *and* an embedded text color, even though there is no text to color.
I am only addressing the first bug because it's easy, …

GUI: Fix saveload display of selected empty items

---

gui/saveload-dialog.cpp
gui/widgets/list.cpp
gui/widgets/list.h

This PR addresses a collection of overlapping input issues on my favorite dialog: the save/load list.
Most of these involve ListWidget's editable mode. The save list is the only editable ListWidget in ScummVM. There are two similar sounding states: editable (you *can* edit items) and edit mode (you're currently editing an item).
Behavior changes:
1. Save list can now be navigated with the keyboard, just like the restore list. Before, changing the selection with the keyboard automatically entered edit mode, so you couldn't press a navigation key more than once. The first key would select an item and the second key would be trapped by edit mode. Pressing the Enter key still enters edit mode. Selecting an item with the mouse still enters edit mode as before, but with a bugfix.
2. Bugfix: …

GUI: Save/Load list input improvements

---

common/debug.cpp
common/log.h
common/system.h
common/textconsole.cpp

This allows to specify a log watcher:
```c++
static void onLog(LogMessageType::Type type, int level, uint32 debugChannels, const char *message) {
switch (type) {
case LogMessageType::kError:
// TODO: error
break;
case LogMessageType::kWarning:
// TODO: warning
break;
case LogMessageType::kInfo:
// TODO: info
break;
case LogMessageType::kDebug:
// TODO: debug
break;
}
}
Common::setLogWatcher(onLog);
```
When a log watcher is set, it will receive each message logged by theses methods:
* `error()`
* `warning()`
* all debug methods: `debug()`, `debugN()` and `debugC()`, `debugCN()`
It can be useful for example to create a logger with `ImGui`:

COMMON: Add a log watcher

---

engines/mtropolis/plugin/standard.cpp
engines/mtropolis/plugin/standard.h

Add support for loading the cue source of `MediaCueMessengerModifier` as a string.
Without supporting strings, the modifier will not be instantiated during boot. (Incidentially, this is how the segfault from PR #5801 was discovered.)
This constellation occurs in the retail version of _Star Trek: The Game Show_. Adding this game version to detection is subject of a future PR.
Evaluating the cue source string is not implemented yet. Support for the game is not far enough yet to trigger the situation where the cue happens.

MTROPOLIS: support loading cue source as string

---

engines/mtropolis/elements.cpp
engines/mtropolis/mtropolis.cpp

Plenty of mTropolis games have video files in a directory named `Video` - or some spelling thereof - on the CD.
This patch adds the capability to play those external video files.
Games that can demonstrate this capability will be added to the detection in a future PR.
Pending other patches to make them startable, this feature would be demonstrable with:
- _Hercules & Xena Learning Adventure: Quest for the Scrolls_
- _The Magical World of Beatrix Potter_

MTROPOLIS: add ability to play external video files

---

engines/director/director.cpp

Path separator is set to \ only on director 4+ and Windows platform in DirectorEngine constructor.
Don't use a \ separator in getCurrentAbsolutePath on versions older than Director 4.

DIRECTOR: Make absolute path coherent with path separator

---

common/singleton.h
common/stack.h
engines/adl/graphics.h
engines/startrek/fixedint.h
engines/titanic/support/fixed_queue.h

Fix repetitive warnings about template-id in constructor/destructor and ensure C++20 compatibility. Warnings encountered when compiling with GCC 14.

JANITORIAL: Fix repetitive warnings about template-id in constructor/destructor

---

README.md

It took me a while to find where the daily builds are. Since they will often be accessed by developers who may not have the website open, it could be helpful to link directly to them from the source code repository README.

JANITORIAL: Add Daily Build link to README

---

graphics/opengl/context.cpp
graphics/opengl/glad.h

As the file is autogenerated, avoid patching it.
Instead allow sscanf_s in context.cpp. That's the only place where GLAD will need to use sscanf_s as it's where GLAD implementation is enabled (GLAD_GL_IMPLEMENTATION is defined here).
All other places which use GLAD, only use it for the GL headers.
Making a PR to check it still builds.

GRAPHICS: OPENGL: Don't patch glad.h

---

graphics/tinygl/api.cpp
graphics/tinygl/init.cpp
graphics/tinygl/misc.cpp
graphics/tinygl/opinfo.h
graphics/tinygl/zbuffer.h
graphics/tinygl/zdirtyrect.cpp
graphics/tinygl/zdirtyrect.h
graphics/tinygl/zgl.h
graphics/tinygl/ztriangle.cpp

This is a quick and dirty implementation of glPolygonStipple for TinyGL. It seem to work, but there are some glitches here and there. I expect to have some discussion and improvements before merging this. For instance, it is not clear for me if the stipple pattern should be used for the depth buffer or not (that part is commented).

TINYGL: initial implementation of tglPolygonStipple

---

engines/director/detection_tables.h
engines/director/lingo/xlibs/jwxini.cpp
engines/director/lingo/xlibs/jwxini.h

The game uses an xLib named "INI.DLL", which is very similar to the already existing jwxini (probably its just the same). The version of the xLib is 1.0.
In addition there was a mixed formatting which I also uniformed.

DIRECTOR: Add detection and support for "Wellen, Wracks und Wassermänner"

---

engines/director/detection_tables.h

This is my attempt at adding detection for Jan Lindblad presenterar den sjungande Fågelboken:
(The original price tag says 595.00 SEK, or about $56. I paid quite a bit less for it at my local thrift store!)
It starts, which is encouraging:
But while you can click on the buttons, and they depress, they never pop back up and nothing else happens. There is also a Macintosh version on the CD, but extracting it with the Dumper Companion still gives you the Windows EXE in addition to the Mac one, so I don't know if there's any need for a separate detection entry for it? Though a bunch of the files get extracted as MacBinary, so maybe it is needed after all?

DIRECTOR: Add detection for Jan Lindblad presenterar den sjungande Fågelboken

---

audio/mixer.h
backends/mixer/maxmod/maxmod-mixer.cpp

I've also added comments to the `Mixer::getOutputBufSize()` functions, so I've opened a PR for it to make sure I've understood it correctly.

DS: Report the buffer size to the mixer

---

base/commandLine.cpp
common/path.cpp
common/path.h
common/punycode.cpp
test/common/path.h

This will avoid spurious warnings on Windows.
This also allows Windows users to use / instead of \ separator. We use the same method everywhere: when checking if the path exists, when reading directly from converting and when reading from the configuration generated from the command line.
I don't have a Windows at hand currently, so I put it as a PR to have someone else check it. :grin:

BASE: Fix path parsing in command line

---

engines/sci/engine/script_patches.cpp

JANITORIAL: Fix typo in SCI script_patches.cpp
In a comment related to patch for Conquests of the Longbow: The Legend of Robin Hood, "Marian" is misspelled as "Marion".

JANITORIAL: Fix typo in SCI script_patches.cpp

---

base/commandLine.cpp

clang interprets this expression as possibly a mistaken attempt to add a number to the string, rather than to index into the string. Adding parens around the string silences the warning.
Sample warning:
```
base/commandLine.cpp:917:4: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
DO_LONG_OPTION_PATH("extrapath")
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
base/commandLine.cpp:593:41: note: expanded from macro 'DO_LONG_OPTION_PATH'
#define DO_LONG_OPTION_PATH(longCmd)    DO_OPTION_PATH(0, longCmd)
^~~~~~~~~~~~~~~~~~~~~~~~~~
base/commandLine.cpp:569:25: note: expanded from macro 'DO_OPTION_PATH'
isLongCmd ? longCmd + 1 : ""); \
~~~~~~~~^~~
base/commandLine.cpp:914:4: note: use array indexing to silence this warning
base/commandLine.cpp:593:41: note: expanded from …
```

BASE: silence clang warning

---

backends/plugins/sdl/macosx/macosx-provider.cpp

This fises macOS builds using `--enable-plugins`, as used for building the OSX PPC releases
```
backends/plugins/sdl/macosx/macosx-provider.cpp:34:18: error: no matching conversion for functional-style cast from 'Common::String' to 'Common::FSNode'
dirs.push_back(Common::FSNode(bundlePath));
^~~~~~~~~~~~~~~~~~~~~~~~~
./common/fs.h:69:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'Common::String' to 'const Common::FSNode' for 1st argument
class FSNode : public ArchiveMember {
^
./common/fs.h:80:2: note: candidate constructor not viable: no known conversion from 'Common::String' to 'AbstractFSNode *' for 1st argument
FSNode(AbstractFSNode *realNode);
^
./common/fs.h:108:11: note: candidate constructor not viable: no known conversion from …
```

MACOSX: Fix macOS builds with plugins (as used for OSX PPC releases)

---

engines/sword25/gfx/image/renderedimage.cpp
engines/sword25/gfx/image/renderedimage.h
engines/wintermute/base/gfx/osystem/base_surface_osystem.cpp
graphics/VectorRenderer.h
graphics/VectorRendererSpec.cpp
graphics/VectorRendererSpec.h
graphics/managed_surface.cpp
graphics/managed_surface.h
graphics/surface.cpp
graphics/surface.h
gui/ThemeEngine.cpp
gui/ThemeEngine.h
gui/ThemeParser.cpp
gui/widget.cpp
gui/widget.h
gui/widgets/grid.cpp
gui/widgets/grid.h
gui/widgets/richtext.cpp

This makes use of the common blitting routines like `crossBlit`. Compared to `blitFrom()`, this should provide:
- Faster blitting when the source and destination format are the same.
- Faster blitting with paletted sources and true colour destinations.
- More effective dirty rectangle tracking (`blitFrom` simply marked the entire surface as dirty).
- Direct handling of colour keys (`blitFrom` redirects attempts to use colour keys to `transBlitFrom` instead).
The downside is that it doesn't do alpha transparency or scaling.
This PR also makes use of this in the GUI for bitmaps without alpha. This should be most noticeable in themes like `scummmodern` that use .bmp images instead of .svg images.

GRAPHICS: Add simplified blitting routines to ManagedSurface

---

configure
ports.mk

Two commits improving the libsonivox checks done in `./configure`. The commits messages give the details.
* Upsteam installs a `libsonivox-static.a` file by default, so check for `-lsonivox-static` too, when there's no `pkg-config` available (not all ports have it)
* Do an actual linking test of a libsonivox function inside the configure check.
* That's what we do for most library checks
* and it helps catching an upsteam issue at an earlier stage: they unconditionally use a GCC `__builtin` (with no fallback) which is not available before GCC 5.0. The error would only appear when linking the `scummvm` binary; this change helps finding the issue earlier, so that the library won't be used if the compiler is too old (some ports still use GCC < 5.0) and the library hasn't been patched for it. …

CONFIGURE: Improve libsonivox checks

---

engines/ultima/shared/conf/xml_tree.cpp

Re-enables nuvie.cfg file parsing that were impacted by XMLNode enhancement, picking the text value of first child if current subtree text is empty. Fixes issue #15207.

ULTIMA6: patch nuvie.cfg parsing by extracting text from child

---

engines/ags/engine/ac/parser.cpp

AGS: Parser fixes from upstream
Compilation of three bug fixes to text parser I recently made in the AGS project, around alternatives syntax:
* stop parsing when reaching end during alternatives skipping (causing an out-of-bounds memory read)
* correctly skip over multi-word alternatives (incorrect parsing of alternative lists)
* use dedicated function to identify word boundaries (affecting dash and apostrophe containing alternatives)
Original PRs:
https://github.com/adventuregamestudio/ags/pull/2442
https://github.com/adventuregamestudio/ags/pull/2443
Just wanted to flag these, if there's a separate process for applying changes from upstream feel free to ignore this PR.

AGS: Parser fixes from upstream

---

engines/nancy/state/setupmenu.cpp

Highlight "Done" on hover in Game Setup as the original games do and as is done for main menu buttons.

NANCY: Highlight Done button in Game Setup

---

graphics/managed_surface.cpp

This is reported to significantly reduce CPU usage in The Space Bar.

GRAPHICS: Only invalidate the updated area of the screen in ManagedSurface::blitFrom

---

engines/sci/graphics/gfxdrivers.cpp
engines/sci/graphics/gfxdrivers.h
engines/sci/graphics/screen.cpp
engines/sci/graphics/transitions.cpp

I noticed that the transitions weren't scaled to the screen resolution. The engine used OSystem::fillScreen() for this which bypassed the mode specific rendering.
I also addressed some things mentioned by @ccawley2011 on the other PR by getting rid of the unneeded EGA driver implementation and an unneeded buffer. These were basically leftovers from when I started the project and didn't yet know what was really needed.

SCI: fix Hercules and CGA b/w transitions and remove unneeded class

---

gui/editgamedialog.cpp

PR #5832 moved the engine options widget into a separate scroll container, but PR #5829 wasn't adapted for this and attempts to remove it from the tab container instead, leaving references to the deleted object.

GUI: Fix crash in edit game dialog when plugins are unloaded

---

engines/sci/graphics/gfxdrivers.h
engines/sci/graphics/screen.cpp

The rgb rendering option is not compatible with the current CGA/Hercules code. It could be implemented, but it isn't trivial and as far as my (limited) understanding goes it would be pointless for these modes (I think it is supposed to prevent palette transition glitches in games that actually have a palette).

SCI: disable rgb rendering for CGA/Hercules modes

---

engines/ags/lib/allegro/surface.cpp
engines/bagel/boflib/gfx/bitmap.cpp
engines/crab/image/Image.cpp
engines/director/tests.cpp
engines/griffon/resources.cpp
engines/mm/mm1/data/monsters.cpp
engines/mm/mm1/maps/maps.cpp
engines/mm/mm1/views/title.cpp
engines/mtropolis/assets.cpp
engines/nancy/state/logo.cpp
engines/tetraedge/te/te_images_sequence.cpp
engines/twine/movies.cpp
engines/twine/slideshow.cpp
engines/ultima/ultima8/gumps/cru_credits_gump.cpp
engines/ultima/ultima8/gumps/cru_demo_gump.cpp
engines/ultima/ultima8/gumps/minimap_gump.cpp
engines/wintermute/base/gfx/osystem/render_ticket.cpp
graphics/macgui/mactext-canvas.cpp
graphics/macgui/macwindowmanager.cpp
graphics/managed_surface.cpp
graphics/managed_surface.h
gui/ThemeEngine.cpp
gui/widget.cpp
gui/widgets/grid.cpp

As discussed in https://github.com/scummvm/scummvm/commit/7559ecdf84fff0e2d8bf82001e27d1dd21bc54f8#r142840479, there is some ambiguity about whether some of the `ManagedSurface` constructors copy the pixel data or reuse the memory from the original surface. I also noticed that because those construtors receive a reference rather than a pointer, it's really easy to use it by accident when supplying a pointer to functions like `blitFrom` instead of a reference. This PR deprecates these methods and adapts most of the previous users of it.
There are a few places in the GUI and Wintermute engines where the additional `copyFrom` call shouldn't be necessary, but I've added it to reflect the behaviour of the old code.
The remaining users of the deprecated methods are SLUDGE (which will be …

GRAPHICS: Deprecate ManagedSurface methods that implicitly copy pixel data

---

graphics/managed_surface.cpp

Compiler warnings flagged that this should be using `copyFrom`:
```
graphics/managed_surface.cpp:44:8: warning: 'operator=' is deprecated: Use copyFrom() instead [-Wdeprecated-declarations]
*this = surf;
^
./graphics/managed_surface.h:195:2: note: 'operator=' has been explicitly marked deprecated here
WARN_DEPRECATED("Use copyFrom() instead")
^
./common/scummsys.h:447:47: note: expanded from macro 'WARN_DEPRECATED'
#define WARN_DEPRECATED(msg) __attribute__((__deprecated__(msg)))
^
1 warning generated.
```
Looks like this might have gotten missed in ff530edcb1f0814cc54f649e678405178e1bd197.

GRAPHICS: replace deprecated operator

---

engines/mtropolis/elements.cpp
engines/mtropolis/elements.h

Without a palette provided to `blitFrom` here, there would be assertions and `nullptr` segfaults in `Graphics::ManagedSurface::blitFromInner`.
Observed in _MindGym_ and _The Day The World Broke_.
The palette content is not correct yet. Both titles render the video with the wrong colors.
Stacktrace for the assertion:
```
assert(!destFormat.isCLUT8() && srcPalette && srcPalette->size() > 0);
Graphics::ManagedSurface::blitFromInner(const Graphics::Surface & src, const Common::Rect & srcRect, const Common::Rect & destRect, const Graphics::Palette * srcPalette) Line 299
Graphics::ManagedSurface::blitFrom(const Graphics::Surface & src, const Common::Rect & srcRect, const Common::Rect & destRect, const Graphics::Palette * srcPalette) Line 247
MTropolis::MovieElement::render(MTropolis::Window * …
```

MTROPOLIS: add fallback palette to MovieElement blitting

---

gui/options.cpp

Fixes or works around https://bugs.scummvm.org/ticket/15243 . This may not be appropriate, but it avoids a segfault (nil _aspectCheckbox) for me when I've specified `--disable-aspect` and switch from SDL to OpenGL, anyway.

GUI: rebuild if _aspectCheckbox is expected

---

graphics/managed_surface.cpp
graphics/managed_surface.h

Among other things, having move constructors allow returning a ManagedSurface object from a function without having to make copies of the pixel data.
I've also deprecated the copy constructor and restored its previous behaviour. I don't know if it (or `operator=`) can ever be fully removed because `Common::Array` needs it, but for now it'll help to identify places where unnecessary copies are occurring.

GRAPHICS: Add move constructors to ManagedSurface

---

engines/director/detection_tables.h

Thanks to the tail checksums for Windows, the detection entries are now unique with only using one file which is the Projector itself.
After years of searching, I can now happily report that now all known language variants are detected, including the release that is most likely the very original one - even though the Dutch variant added here is from a disc that contains a re-release, it is the one with the _lowest_ Director version which is a very strong indicator that this is in fact the original one.
The French release has an HFS partition as well, but it looks like the Projector is embedded in a Setup program since I don't see a file that's obviously a Projector; so this needs more investigation.

DIRECTOR: Add remaining detection entries for melements

---

.github/workflows/ci.yml
devtools/create_project/create_project.cpp

This is complicated to support as the Xcode project is used for MacOS and iOS/tvOS where ImGui is not supported.
This needs to avoid building of some files in the engines in a selective way which is not easy to achieve without hacks.

CREATE_PROJECT: Disable ImGui when creating Xcode project

---

engines/startrek/detection.cpp
engines/startrek/graphics.cpp
engines/startrek/resource.cpp
engines/startrek/sound.cpp
engines/startrek/startrek.cpp

Note that currently text boxes don't render correctly with either CD demo. The DOS floppy demo also doesn't start yet, and instead gives the error "Room "DEMO0" unimplemented!"

STARTREK: Fixes for the demo versions

---

engines/kyra/sound/drivers/halestorm.cpp
engines/kyra/sound/drivers/halestorm.h
engines/kyra/sound/sound_mac_res.h

This should make it easier to move the driver into common code later - the Mac version of Star Trek 25th Anniversary appears to use the Halestorm driver as well.

KYRA: Remove engine dependencies from the Halestorm driver

---

engines/tucker/tucker.cpp

This is a fix for tracker issue #15264
The cause seems to have been that a method was trying to access unallocated space.

TUCKER: Fix bottom exit for UpperCorridor

---

engines/director/detection_tables.h

Made with Director 5.0. the "Making-of" video is created with Director 5.1.
The "Enhanced Version" of the game uses QTVR, the "Standard Version" just uses QuickTime video.

DIRECTOR: Add detection entry for "Robinson Crusoe"

---

devtools/create_project/msbuild.cpp
devtools/create_project/msvc.cpp

Visual Studio 2019 added support for [Address Sanitizer](https://learn.microsoft.com/en-us/cpp/sanitizers/asan?view=msvc-170), a popular tool for debugging memory errors, that most developers aren't even aware it exists.
This PR adds a ASan build configuration to the generated MSVC project with the correct compiler flags in place, so you can easily switch it on and off when debugging code:
It's not enabled by default since it runs slower and requires disabling some compiler debug features.
I also removed the obsolete Analysis build configuration (runs static analysis like Coverity), since MSVC added an Analyze menu that does the same thing.

MSVC: Add build configuration for ASan

---

.github/workflows/ci.yml

This adds [discord-rpc](https://github.com/discord/discord-rpc) support to the Ubuntu runners, so that CI has better coverage for this part of the code, even under Linux.
There's no real package for discord-rpc it seems, but we already `curl` so pre-built binaries for the Windows runners, anyway.
Any objection?

CI: Use Discord RPC lib in Ubuntu runners

---

ports.mk

The 76x76 app icon files (1x and 2x) are present, but appear to not be referenced by Info.plist.
I noticed after signing and installing https://downloads.scummvm.org/frs/scummvm/2.8.0/scummvm-2.8.0-ios9-armv7.ipa on an iPad 3rd gen that there was no app icon. I'll assume that this wasn't caught in the appstore release since it uses the asset catalog instead (?) 
It was resolved on my end by simply referencing the existing 76x76 icon files present in the bundle, using the existing ~ipad specific info.plist key. 
While looking through the current repo it didn't strike me as taking this into account yet, but if you think I've misunderstood something feel free to simply close this.
Sincerely,
big fan

IOS7: Add iPad app icons to Info.plist

---

engines/ags/engine/ac/draw.cpp
engines/ags/engine/ac/drawing_surface.cpp
engines/ags/engine/ac/game.cpp
engines/ags/engine/ac/sprite_list_entry.h
engines/ags/engine/game/savegame.cpp
engines/ags/engine/game/savegame.h
engines/ags/engine/game/viewport.h
engines/ags/engine/gfx/ali_3d_scummvm.cpp
engines/ags/engine/gfx/graphics_driver.h
engines/ags/engine/main/config.cpp
engines/ags/engine/main/engine.cpp
engines/ags/engine/main/graphics_mode.cpp
engines/ags/engine/script/script_api.h
engines/ags/globals.h
engines/ags/lib/allegro/surface_avx2.cpp
engines/ags/lib/allegro/surface_neon.cpp
engines/ags/lib/allegro/surface_sse2.cpp
engines/ags/lib/freetype-2.1.3/autohint/ahhint.cpp
engines/ags/lib/freetype-2.1.3/ftmemory.h
engines/ags/plugins/ags_plugin.cpp
engines/ags/shared/game/main_game_file.cpp
engines/ags/shared/util/data_ext.h
engines/ags/tests/test_gfx.cpp

I left out some typos in the game detection data base, since i'm pretty sure they are meant to be spelled wrong.
If not, here are my findings for anyone who wants to take a look:
/engines/ags/detection_tables.h
existance < (instead of > existence <) found on line 90 at position 5
{ "existance", "Existance" },
/engines/ags/detection_tables.h
existance < (instead of > existence <) found on line 90 at position 18
{ "existance", "Existance" },
/engines/ags/detection_tables.h
mistery < (instead of > mystery <) found on line 2055 at position 28
{ "misterybigwhoop", "The Mistery of Big Whoop" },
/engines/ags/detection_tables.h
creche < (instead of > crèche <) found on line 2855 at position 39
{ "silentnightcreche", "Silent Night Creche" },
/engines/ags/detection_tables.h
teh < (instead of > the …

JANITORIAL: AGS: Fix a bunch of typos in comments

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h

This is a fix for a bug I mentioned in https://github.com/scummvm/scummvm/pull/5315#issuecomment-1735288260, that occurs when using cursor masks in a high-color context with SurfaceSdl.
SurfaceSdl honors the cursor mask by creating intermediary masked_image, where the pixels made transparent by the mask are replaced by an ARGB color with alpha = 0 (ARGB 0x00000000). The problem is that the cursor surface still has a key color attached to it, which is set to 0 by the recursive call:
`setMouseCursor(&maskedImage[0], w, h, hotspotX, hotspotY, 0, dontScale, &formatWithAlpha, nullptr);`
and then passed to SDL_SetColorKey, which is _not_ sensitive to the alpha channel, so opaque black ARGB 0xFF000000 wrongly becomes transparent as well.
This PR provides an option to disable the unneeded color …

GRAPHICS: Fix a transparency issue when using cursor masks with high-color in SurfaceSdl

---

common/algorithm.h
common/array.h
common/memory.h
common/std/vector.h
engines/sci/graphics/lists32.h

This should reduce the amount of memory copying when amending an array of objects that have move constructors.

COMMON: Use uninitialized_move when resizing arrays

---

engines/kyra/engine/eobcommon.cpp

KYRA: Fixed level-up hit point gain in eob
Eye of the Beholder uses a table for looking up HP gains when
characters level up. Table is EoBCoreEngine::_hpIncrPerLevel,
has 3 subsections of 6 entries each:
```
+const uint8 EoBCoreEngine::_hpIncrPerLevel[] = {
10,   #0   # fighter HP die sides
4,   #1   # mage HP die sides
8,   #2   # cleric HP die sides
6,   #3   # thief HP die sides
10,   #4   # paladin? HP die sides
10,   #5   # ranger? HP die sides
9,   #6   # fighter max level to roll HP
10,   #7   # mage max level to roll HP
9,   #8   # cleric max level to roll HP
10,   #9   # thief max level to roll HP
9,  #10   # paladin? max level to roll HP 
9,  #11   # ranger? max level to roll HP 
3,  #12   # fighter static HP
1,  #13   # mage static HP
2,  #14   # cleric static HP
2,  #15   # …
```

KYRA: Fix EoBCoreEngine::_hpIncrPerLevel table lookup

---

engines/bladerunner/subtitles.cpp
engines/buried/graphics.cpp
engines/crab/text/TextManager.cpp
engines/glk/screen.cpp
engines/glk/zcode/screen.cpp
engines/gnap/gnap.cpp
engines/grim/font.cpp
engines/mohawk/myst_graphics.cpp
engines/mohawk/riven_graphics.cpp
engines/myst3/subtitles.cpp
engines/stark/services/fontprovider.cpp
engines/tetraedge/te/te_font3.cpp
engines/ultima/ultima8/gfx/fonts/font_manager.cpp
engines/vcruise/runtime.cpp
engines/wintermute/base/font/base_font_truetype.cpp
engines/zvision/text/truetype_font.cpp
graphics/fonts/ttf.cpp
graphics/fonts/ttf.h
graphics/macgui/macfontmanager.cpp
gui/ThemeEngine.cpp
video/subtitles.cpp

This reduces memory usage when loading larger fonts - the ZipArchive class already loads the entire file into memory, so requiring a second block of memory for use with FreeType is an issue when dealing with CJK files which can go up to 8 MB.

GRAPHICS: Use custom stream callbacks for loading TTF fonts

---

engines/gob/detection/detection.h
engines/gob/detection/tables.h
engines/gob/detection/tables_adi1.h
engines/gob/gameidtotype.h

ADI1 can be started in ScummVM. 
ADI2.STK is is the start archive name same as in ADI2. But at this Game it handles about ADI 1 and not ADI 2 to avoid confuse i want to mention it here.

GOB: add ADI1 to detection tables

---

engines/twp/motor.cpp
engines/twp/object.cpp

Hi!
This PR fixes two issues with TWP (GOG/1.0.958) that prevent game completion. Quoting the respective commit messages:
(This was reported as https://bugs.scummvm.org/ticket/15285)
Commit 7dd6c4ba627 (TWP: Fix give minimum distance, 2024-03-07) increased the maximum distance for allowing objects to be given from 15 to 30. This works fine for most of the game, but there is at least one instance where 30 prevents a crucial transaction: Ransome exchanging wallets with Willie. This is visible in the following debug log:
```
Give 'ransomeWallet' to 'willie'
exec(currentActor,9,ransomeWallet,willie)
noun1.inInventory: YES and noun1.touchable: YES nowalk: NO
walk to obj willie: (1533.000000,91.000000)
walk to obj ransome: 1503.000000,91.000000, 1
Give 'ransomeWallet' to 'willie'
actorArrived …
```

TWP: bump "give" distance and handle empty text lines gracefully

---

backends/platform/android/org/scummvm/scummvm/CompatHelpers.java
backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java
backends/platform/android/org/scummvm/scummvm/ShortcutCreatorActivity.java

This PR does two things.
The shortcut support added recently is extended up to Nougat MR1 (7.1) as I missed a portability trick for this version.
Then, dynamic shortcuts are now supported.
This means that every time a game is started, a shortcut, available by long pressing the ScummVM icon in the launcher, is created and the history contains the 4 last launched games.
This also has the benefit to make shortcut pinning on launcher easier: you just have to long press in the shortcut list and move the shortcut on the launcher.
This should allow users without a launcher supporting shortcut widgets to still be able to pin them.

ANDROID: Improve shortcuts

---

engines/illusions/bbdou/illusions_bbdou.cpp
engines/illusions/console.cpp
engines/illusions/console.h
engines/illusions/duckman/illusions_duckman.cpp
engines/illusions/input.cpp
engines/illusions/input.h
engines/illusions/module.mk

As #5954 aims to add keymapper support to ILLUSIONS, it would become possible to map over the keys for the "gosanta" cheat code.
This pull requests adds a debugger console to the engine with a command to set the cheat mode.

ILLUSIONS: Add cheat debug console command

---

engines/nancy/cif.cpp
engines/nancy/commontypes.cpp
engines/nancy/iff.cpp

Reported by asan
@fracturehill as discussed
Edit discussed below - adding:
1. CifTree::createReadStreamForMember's `buf` is free()d by way of Common::DisposablePtr<unsigned char const, Common::MemoryReadStream::CastFreeDeleter>::~DisposablePtr()
```
ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs free) on 0x7f454e5e3800
#0 0x7f45812b76a8 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:52
#1 0x562d8170717e in Common::MemoryReadStream::CastFreeDeleter::operator()(unsigned char const*) common/memstream.h:47
#2 0x562d8170717e in Common::DisposablePtr<unsigned char const, Common::MemoryReadStream::CastFreeDeleter>::~DisposablePtr() common/ptr.h:670
#3 0x562d81707289 in Common::MemoryReadStream::~MemoryReadStream() common/memstream.h:43
#4 …
```

NANCY: Fix some alloc-dealloc mismatches

---

engines/adl/adl.cpp
engines/adl/adl.h
engines/adl/adl_v4.cpp

When playing the later ADL games (Time Zone and The Dark Crystals are the ones I have), you will often see warning messages like this:
```
WARNING: Adding \0 to String. This is permitted, but can have unwanted consequences. (This warning will be removed later.)!
```
When the string class was refactored, for a while it was not permitted to add zeroes to a string. Doing so is allowed now, but still discouraged. The problem arises because the engine uses the string class to briefly store encrypted strings, which it then decrypts. With this change, the string is decrypted as it is being read, so only the decrypted string gets stored.
Note that I haven't actually played through these games. I did walk around for a bit in them, as well as Mystery House, Mission Asteroid, and The Wizard and the …

ADL: Fix string concatenation warnings

---

common/list.h
common/std/list.h
engines/ultima/shared/std/containers.h
engines/ultima/ultima8/world/current_map.cpp
test/common/list.h

This matches the C++ standard library, and removes the need for some overrides in subclasses.
The implementation in the Ultima engine didn't look correct, but it was only used in one place.

COMMON: Return an iterator for List::insert

---

engines/ultima/detection.cpp
engines/ultima/detection_tables.h

This pull request aims to improve detection for Ultima 8 and Crusader games by specifying paths to detection files and providing more entries.
For Ultima 8 the language prefixed intro movie (*intro.skf) was chosen to be the second entry. It is worth noting that French and German version also contain the English files and are detected as either.
I only have current access to the GOG / Gold CD version, so I would like to have entries for other versions added as well.
For Crusader games, I am unsure of a second entry to pick as videos may not be present until extracted, but might suggest "static/dtable.flx"
The older Ultima all appear to have flat folder structures and should not be affected by the change.

ULTIMA: Improve detection for Ultima 8 and Crusader games

---

engines/tinsel/detection_tables.h

I managed to get an original copy of the Japanese *Macintosh* release of Discworld 1.
This PR adds a detection entry for it. Most things appear to work: subtitles, audio, playing. The cursor looks a bit wrong when you interact with an object, though:
and the inventory also gets corrupted a bit:
I'm keeping the `ADGF_UNSTABLE` flag because I just played a few scenes from the first act, so I can't guarantee anything about its status (maybe it just crashes at some point later on). I don't have the time to play it more thoroughly yet, or to compare it with the original Classic interpreter, but having it in the detection tables shouldn't hurt.

TINSEL: Add detection for Discworld 1 Macintosh Japanese

---

engines/director/channel.cpp
engines/director/detection_tables.h
engines/director/images.cpp
engines/director/lingo/lingo-gr.cpp
engines/director/lingo/xlibs/movemousejp.cpp
engines/director/lingo/xlibs/popupmenuxobj.cpp
engines/director/resource.cpp

ok, need to get feedback on this one.
Two instances of misspelling in the detection tables
- amercia.exe (mind the character switch) from the [shramerica] director package
i have not been able to check this, since the demo on ScummVM's download site doesn't hold that .exe file (and the game itself doesn't start anyway in win11, so anyone with more insight, please shout)
- Dalmation game (it's Dalmatian as-in the dog breed, but the misspelling seems to be consistent through package, game and ScummVM naming here...should i let this slip?)
Thank you

JANITORIAL: DIRECTOR: Fix typos in comments

---

engines/dm/inventory.h

Separate PR since it touches the code, but i'm pretty sure this is an oversight, since in
inventory.cpp, line 315 it says
`void` InventoryMan::drawPanelScroll(Scroll *scroll) {

JANITORIAL: DM: Fix scoll typo in inventory.h

---

engines/ultima/nuvie/script/script.cpp

LUA seems to expect a "/" (POSIX) path separator, so using Common::Path::kNativeSeparator made engine unable to find the lua scripts on Windows
The issue was reported on ScummVM discord for Ultima 6 here: https://discord.com/channels/581224060529148060/581224061091446795/1269230221500878881
I've only tested on Windows with latest code from master HEAD (testing with the Ultima 6 version of the game on GOG and our ultima.dat distributable file).

ULTIMA: NUVIE: Fix loading lua scripts on Windows

---

engines/director/frame.cpp
engines/director/score.cpp
engines/freescape/games/castle/castle.cpp
engines/freescape/games/castle/dos.cpp
engines/freescape/games/palettes.cpp
engines/freescape/loaders/8bitBinaryLoader.cpp
engines/freescape/loaders/8bitImage.cpp
engines/freescape/sound.cpp

The following PR fixes GCC `-Wformat` warnings on 32-bits platforms in the DIRECTOR and FREESCAPE engines.
It's just a switch from `%ld` to `%lld` for int64 types.
Any objection?

DIRECTOR/FREESCAPE: Fix -Wformat warnings on 32-bit platforms

---

common/std/vector.h

`Std::vector` was previously separated from `Common::Array` in commit 830c1b0, but now that PR #5902 is merged it should be OK to combine them again to reduce code duplication.

COMMON: Make Std::vector a subclass of Common::Array

---

engines/mtropolis/detection_tables.h

Do not use MPX files in detection tables.
The intent behind the MPL/MPX split was to install the small MPL file on the disk with the mTropolis player, while the large MPX file remains on the CD.
This has the effect that in a vanilla game installation, the mTropolis player, the MPL file and the MPX files are usually not found together in such a constellation as current ScummVM detection with MPX files included would expect it.
To make detection work, the ScummVM user would have to manually copy files together in a way that is neither intuitive nor expressly documented.
This change also achieves greater consistency with the detection tables for existing supported titles Obsidian and MTI, which already do not use the MPX files for detection.

MTROPOLIS: disable MPX files in detection tables

---

engines/ultima/nuvie/pathfinder/astar_path.cpp
engines/ultima/nuvie/pathfinder/u6_astar_path.cpp

- Fix copy-paste error introduced in 4493bdcf5c08e040cb7f5afda029fb748d915cd4 "ULTIMA: NUVIE: Use foreach style loops for cleaner code"
- Fix pathfinding not detecting some doors
Fixes [#15308](https://bugs.scummvm.org/ticket/15308)

ULTIMA: NUVIE: Pathfinding fixes

---

common/array.h
common/util.h
test/common/array.h

Adds a few more things to Common::Array, in particular emplace, emplace_back (which uses emplace), and rvalue push_back.  Updates both push_back versions to use emplace_back (same approach as MSVCRT).

COMMON: Add emplace, emplace_back, and rvalue push_back to Array

---

engines/glk/agt/metacommand.cpp

Separate PR since it touches the code

JANITORIAL: Fix grammer typos in metacommand.cpp

---

engines/nancy/state/scene.cpp

`buf` wasn't freed.
The assignment to `description` copies the string; no need for heap here.
```
LeakSanitizer: detected memory leaks
Direct leak of 100 byte(s) in 2 object(s) allocated from:
#0 0x7f57a56b9628 in operator new[](unsigned long)
#1 0x5592ac6abb5c in Nancy::State::Scene::SceneSummary::readTerse(Common::SeekableReadStream&) engines/nancy/state/scene.cpp:105
#2 0x5592ac6c8fe0 in Nancy::State::Scene::load(bool) engines/nancy/state/scene.cpp:905
#3 0x5592ac6dc737 in Nancy::State::Scene::process() engines/nancy/state/scene.cpp:159
#4 0x5592ac253dba in Nancy::NancyEngine::run() engines/nancy/nancy.cpp:308
#5 0x5592ab7a5b6a in runGame base/main.cpp:311
```
@fracturehill for review

NANCY: Fix leak in scene.cpp

---

common/util.h

This fixes the unneeded double-copy in the existing constructor and adds move semantic stuff.
While C++ can automatically define a move constructor and move assign operator, it won't do it if either member of the pair doesn't support move semantics, even though the copy constructor or copy assign operator will be called in such a situation, so they are defined explicitly.

COMMON: Add move constructors and assign operators to Pair

---

engines/sci/graphics/cursor.cpp
engines/sci/graphics/gfxdrivers.cpp
engines/sci/graphics/gfxdrivers.h
engines/sci/graphics/screen.cpp

I have noticed (while playing QFG1VGA) that the engine makes use of OSystem::warpMouse() which will not work like that with the drivers that upscale the image.
I have implemented the function for the drivers that need it. It's basically just the reverse of getMousePos().
This wasn't so obvious from disasm, since the original gfx drivers don't need that. The mouse driver will always report coordinates within the 320x200 range there.
Also fixed some of my commments a bit...

SCI: add warpMouse functionality to gfx drivers

---

engines/ags/engine/ac/game_setup.h
engines/glk/tads/tads2/qa_scriptor.cpp

Some ports, such as OSX PPC or (AFAICS) AmigaOS, have `char` being unsigned by default.
Doing [an AmigaOS build](https://wiki.scummvm.org/index.php?title=Compiling_ScummVM/Docker) for the AGS or GLK engine, or looking at [the buildbot logs for it](https://buildbot.scummvm.org/#/builders/58/builds/11522), reveals a couple of issues with the AGS and GLK engines:
```
C++      engines/ags/engine/ac/global_game.o
engines/ags/engine/ac/global_game.cpp: In function 'void AGS3::SetMultitasking(int)':
engines/ags/engine/ac/global_game.cpp:670:41: warning: comparison is always true due to limited range of data type [-Wtype-limits]
if ((_GP(usetup).override_multitasking >= 0) && (mode != _GP(usetup).override_multitasking)) {
C++      engines/glk/tads/tads2/qa_scriptor.o …
```

AGS/GLK: Fixes for ports having 'char' unsigned by default

---

engines/sci/graphics/gfxdrivers.cpp
engines/sci/graphics/gfxdrivers.h
engines/sci/graphics/screen.cpp

Just some fixes on my own code.
The only one that probably can make a visible difference is the x-alignment fix.
Unless PQ2 actually does use text colors other than 0 somewhere.

SCI: some gfx driver code fixes

---

configure

The `configure` script has this `--enable-Werror` option, when one intentionally wants *any* compiler warning to cause a build failure. Of course, it's not enabled by default.
However, this option currently adds `-Werror` to `CXXFLAGS` at an early stage of the configure script, i.e. `-Werror` gets added to most feature and libraries detection code.
This PR moves the code around, so that `-Werror` only gets enabled as late as possible, i.e. only apply it for ScummVM itself, not for library/feature detection.
Here's an issue that the current behavior causes (with G++ 13.2.0 and Glibc 2.39):
```
g++    -Werror -Wshadow -W -Wno-unused-parameter -Wno-empty-body -fno-operator-names -std=c++11 -pedantic -Wglobal-constructors -Wno-undefined-var-template -Wno-pragma-pack …
```

CONFIGURE: Apply --enable-Werror *after* testing features and libraries

---

engines/cge/cge.h
engines/cge/cge_main.cpp
engines/cge/cge_main.h
engines/cge/events.cpp
engines/cge/events.h
engines/cge/metaengine.cpp
engines/cge/vga13h.h
engines/cge/vmenu.cpp
engines/cge/vmenu.h
engines/cge2/cge2.h
engines/cge2/cge2_main.cpp
engines/cge2/cge2_main.h
engines/cge2/events.cpp
engines/cge2/events.h
engines/cge2/metaengine.cpp
engines/cge2/vga13h.h
engines/cge2/vmenu.cpp
engines/cge2/vmenu.h

This adds keymaps for joystick buttons for CGE, and cleans up the keyboard input code
Fixes bug 15187: https://bugs.scummvm.org/ticket/15187
Edit: Added the same changes for CGE2, as the input code is basically the same as CGE
Fixes bug 15188: https://bugs.scummvm.org/ticket/15188

CGE/CGE2: Rewrite keymapper and add joystick support - bugs 15187,15188

---

engines/hpl1/engine/graphics/LowLevelGraphics.h
engines/hpl1/engine/impl/LowLevelGraphicsSDL.cpp
engines/hpl1/engine/impl/MeshLoaderCollada.cpp
engines/hpl1/engine/impl/low_level_graphics_tgl.cpp
engines/hpl1/engine/math/Math.cpp
engines/hpl1/engine/resources/FontManager.cpp
engines/hpl1/engine/scene/MeshEntity.cpp
engines/hpl1/penumbra-overture/GameEnemy_Worm.cpp
engines/hpl1/penumbra-overture/GameEnemy_Worm.h
engines/hpl1/penumbra-overture/GameEntity.cpp
engines/hpl1/penumbra-overture/GameTypes.h
engines/hpl1/penumbra-overture/HudModel_Weapon.cpp
engines/hpl1/penumbra-overture/PlayerHands.cpp
engines/hpl1/penumbra-overture/PlayerHands.h

Separate PR since it touches code
QUESTION, please:
Angelscript, Newton and TinyXML are upstream libraries (iiuc)
Are typo fixes for those desirable in-tree?
Or should i drag them to their up-stream versions (not sure if all of them are still maintained, though)?
Thank you

JANITORIAL: HPL1: Fix typos in code

---

common/scummsys.h

Commit d59f66dfe1981688ce7948e3b5cfacb95d214779 introduced more `<inttypes.h>` in the tree (as OK'd by @ccawley2011 and @lephilousophe on Discord), but this caused a new build failure on RISC OS:
https://buildbot.scummvm.org/#/builders/171/builds/6723
i.e. the `PRId64` macro from `<inttypes.h>` was still not available.
Looking at https://sourceware.org/bugzilla/show_bug.cgi?id=15366 or https://en.cppreference.com/w/cpp/types/integer#Notes, this may be because the RISC OS builder uses an earlier C++11 compiler (GCC 4.7.4) or because its libc isn't up-to-date with the removal of the `__STDC_XXX_MACROS` macro definitions in order to have all the features of `<inttypes.h>`, now that C++11 is a requirement for us.
So this PR just unconditionally defines the macros before including inttypes.h. …

COMMON: Fix inttypes.h support on RISC OS

---

engines/scumm/script.cpp
engines/scumm/string.cpp

So I have now have my own (DOS) copy of the censored German release of Indy3, and I had the time to look at some of the workarounds we've added for it, nearly 20 years ago… and I've found some issues.
This PR does the following (just copying my own commit message):
- Fix an off-by-one in `resStrLen()` return value, and apply its workaround for [Trac#2715](https://bugs.scummvm.org/ticket/2715) too.
- Merge the two `convertMessageToString()` workarounds into a single one, and fix another off-by-one in the [Trac#1675](https://bugs.scummvm.org/ticket/1675) case.
- Restrict both workarounds to the German release of Indy3 (DOS release checked against my own copy, Amiga release tested by gabberhead).
- Restrict both workarounds to the two rooms using the wrong byte for the German Eszett …

SCUMM: Improve Trac#1675 and Trac#2715 bugfixes for German Indy3

---

audio/alsa_opl.cpp
audio/fmopl.h
audio/opl2lpt.cpp
audio/rwopl3.cpp
audio/rwopl3.h
audio/softsynth/opl/dosbox.cpp
audio/softsynth/opl/dosbox.h
audio/softsynth/opl/mame.cpp
audio/softsynth/opl/mame.h
audio/softsynth/opl/nuked.cpp
audio/softsynth/opl/nuked.h

In addition to not being used by any engines, it's also not implemented by several of the drivers.

AUDIO: Remove unused interface for OPL reads

---

common/std/vector.h

We can now inherit the function from `Common::Array` instead.

COMMON: Remove emplace_back variant from Std::vector

---

audio/decoders/flac.cpp
configure

The following PR updates our FLAC requirement from 1.0.1 (2001) to 1.1.3 (2006), i.e. it drops support for the legacy stream decoder API for which we maintained compatibility code under a `LEGACY_FLAC` guard.
`audio/decoders/flac.cpp` says: *"`LEGACY_FLAC` code can be removed once FLAC-1.1.3 propagates everywhere"*. FLAC 1.1.3+ has probably propagated everywhere, 18 years after its release :p 
AFAIK, the oldest FLAC release we still build against is FLAC 1.2.1, for the OpenDingux and OpenPandora ports ([source 1](https://github.com/scummvm/dockerized-bb/blob/883fd791dbdde2d299323dc3d20dbe5f14f897f0/toolchains/opendingux/packages/flac/build.sh#L4), [source 2](https://github.com/scummvm/dockerized-bb/blob/883fd791dbdde2d299323dc3d20dbe5f14f897f0/toolchains/openpandora/packages/flac/build.sh# …

BUILD: AUDIO: Drop support for FLAC < 1.1.3

---

engines/zvision/scripting/controls/titler_control.cpp
engines/zvision/scripting/effects/ttytext_effect.cpp
engines/zvision/scripting/effects/ttytext_effect.h
engines/zvision/text/string_manager.cpp
engines/zvision/text/subtitles.cpp
engines/zvision/text/text.cpp
engines/zvision/text/text.h
engines/zvision/text/truetype_font.cpp
engines/zvision/text/truetype_font.h

This adds BiDi/RTL support for the death screens in Zork Grand Inquisitor
for the hebrew fan translation
(text itself still needs work)
On unmodified files (e.g. without the hebrew patch) there wouldn't be any change in the death screen
The change is divided into 3 commits
- The first fixes implicit casting of 2-bytes character to 1-byte
- The second refactors the tty processing to use UTF-32, which greatly simplify the logic (simple indexing rather than calculating how many bytes is taken by each character)
- The third add BiDi and RTL support for displaying hebrew text
Thanks

ZVISION: Support BiDi text in tty

---

engines/sci/graphics/controls16.cpp

I noticed that the button hilite colors are incorrect in KQV PC-98.
Turns out that all PC-98 targets use the xoring method for the hilite, like SCI0early.
Also, this has to be applied not only to the button control, but also to the text and icon controls. For SCI0 that might not make a visual difference, but for PC-98 it does...

SCI: (PC-98) - fix hilite control color

---

configure

When one looks at [the GCC 4.7 buildbot logs for RISC OS](https://buildbot.scummvm.org/#/builders/171/builds/6737/steps/4/logs/warnings__448_), many warnings show up, but a lot of them are false-positives which won't be printed by a newer compiler.
On the other hand, we have a GCC 4.8 Github Action runner, whose logs are here, for example:
https://github.com/scummvm/scummvm/actions/runs/10340786897/job/28621846127
and indeed many of the GCC 4.7 warnings don't appear in the 4.8 builds.
So, as done in earlier PR #4779, this new PR disables the most unreliable warnings when using this compiler.
In the RISC OS builds in particular (that's our "official" GCC 4.7 user), I'm also suggesting to move to `std_variant=gnu++ pedantic=no` in order to avoid invalid `-Wformat` warnings regarding "GNU …

CONFIGURE: RISCOS: Less false-positive warnings with GCC < 4.8 (and RISC OS)

---

backends/platform/sdl/sdl-window.cpp
doc/docportal/advanced_topics/configuration_file.rst

Adds a config option `forced_dpi_scaling` to override the DPI scaling reported by the system.  Useful for locked down systems where the reported value is consistently incorrect or if users want to override their system value for whatever reason.  
For instance, we force this value to `100` on builds sent to Steam Decks.
This is pretty much a hack-workaround, so understandable if this doesn't get merged.

GUI: Add ability to force DPI scaling via config

---

engines/ags/lib/freetype-2.1.3/autohint/ahglyph.cpp

FreeType 2.13.3 changed a few types of the struct members for FT_Outline struct to unsigned
This is the relevant commit from the FreeType source (github): https://github.com/freetype/freetype/commit/2a7bb4596f566a34fd53932af0ef53b956459d25
Note: FreeType 2.13.3 was only very recently released (on Aug 12, 2024, ie. two days ago).
This PR fixes compilation in MSYS2/Mingw-64 (maybe other toolchains as well, but I'm testing on this one), since that one got the updated version of the library yesterday.

AGS: Support for FreeType 2.13.3 changes to FT_Outline struct

---

engines/access/events.h
engines/grim/gfx_opengl.cpp
engines/grim/gfx_opengl.h
engines/icb/options_manager_pc.cpp
engines/mm/shared/xeen/sound_driver_mt32.h
engines/mortevielle/utils.cpp
engines/prince/hero.cpp
engines/sherlock/fonts.cpp
engines/startrek/actors.cpp
engines/toon/toon.cpp
engines/touche/touche.cpp
engines/vcruise/midi_player.cpp
engines/vcruise/midi_player.h
engines/vcruise/script.cpp

Just a bunch of `-Wunused-private-field` and `-Wunused-private-field` warning fixes for various engines.
It should be pretty trivial to review; I'm mostly opening a PR for the CI tests on all compilers
For the GRIM change, it just follow what earlier commit 6d7e92919792 did

ENGINES: Various small -Wunused-but-set-variable/-Wunused-private-field warning fixes

---

engines/bladerunner/detection_tables.h
engines/cge/detection.cpp
engines/gob/detection/tables_adi1.h
engines/gob/detection/tables_adi5.h
engines/gob/detection/tables_adibou3.h
engines/gob/detection/tables_adiboudchou.h
engines/gob/detection/tables_adiboupresente.h
engines/gob/detection/tables_nathanvacances.h
engines/gob/detection/tables_pierresmagiques.h
engines/groovie/detection.cpp
engines/lure/detection.cpp
engines/metaengine.cpp
engines/metaengine.h
engines/mohawk/detection_tables.h
engines/mtropolis/detection_tables.h
engines/myst3/detection.cpp
engines/saga/detection_tables.h
engines/sci/detection_tables.h
engines/stark/detection.cpp
engines/teenagent/detection.cpp
engines/toltecs/detection.cpp
engines/trecision/detection.cpp
engines/zvision/detection_tables.h

This avoids a duplication of the string in every module and possible discrepancies.
In addition, the string is now present in the binary only once.

ALL: Declare the Game not implemented message in only one place

---

engines/gob/detection/tables.h
engines/gob/detection/tables_adi5.h
engines/gob/detection/tables_adibou3.h
engines/gob/detection/tables_adiboudchou.h
engines/gob/detection/tables_adiboupresente.h
engines/gob/detection/tables_nathanvacances.h
engines/gob/detection/tables_pierresmagiques.h

We no longer need the include of translation.h due to we replaced it with the MetaEngine code.

GOB: remove usage translation.h include from DEV7 entries

---

engines/agi/agi.cpp
engines/agi/agi.h
engines/agi/detection.cpp
engines/agi/detection_tables.h
engines/agi/disk_image.h
engines/agi/loader_a2.cpp
engines/agi/loader_v1.cpp
engines/agi/metaengine.cpp
engines/agi/module.mk
engines/agi/objects.cpp
engines/agi/view.cpp
engines/agi/words.cpp
engines/agi/words.h

Apple II games are now detected and load. AGIv1 games are now reliably detected and load. Other than KQ2 and BC, all of them boot to the start and are somewhat playable.
These games are "booters"; instead of game files, we have floppy disk images without standard file systems. New custom detection makes this work reliably. If you have a directory containing a game's disk images, then as long as the image format is supported and their file extensions are correct, it should Just Work. Only "raw" images are currently supported, but my goal to adapt ADL's code so that other Apple II disk image formats and sector orders will work.
Apple II games also use a custom view format. I've reverse engineered that and included it in this PR. Otherwise there's not much to try out =)
Features:
- Apple II …

AGI: Apple II and PC Booter loaders and detection

---

engines/ags/detection.cpp
engines/ags/detection.h

Currently the desc.filesDescriptions[0].fileName would contain garbage after returing from ADDetectedGame AGSMetaEngineDetection::fallbackDetect()
This would result in error message like the one shown in this bug report:
https://bugs.scummvm.org/ticket/15319#comment:2
"ERROR: Unable to determine game data. Provided game location is not a valid path.
Cwd: D:/Games/KingsQuestIVGA/
Path:"

AGS: Maintain valid filename in fallback detection

---

engines/sci/detection.cpp
engines/sci/detection_internal.cpp
engines/sci/detection_internal.h
engines/sci/metaengine.cpp
engines/sci/module.mk

A recent refactor placed some static constant tables into `detection_internal.h`. This caused them to be compiled twice: once in `detection.cpp` and once in `metaengine.cpp`.
Now they are only compiled in `detection.cpp`. This reduces the gcc x86 executable by 5k.
Tested in gcc with and without --disable-detection-full, and msvc. I get easily confused by the detection stuff, so I'd like someone else to eyeball this =)

SCI: Fix detection_internal.h table duplication

---

engines/scumm/players/player_apple2.cpp

This change adds a separation between notes when Sid/Razor play the piano or when the demo tape is played.   This change prevents a note that was meant to be played multiple times consecutively from sounding like the note being only once for an extended time.

SCUMM: MANIAC (Apple II): add note separation when playing music

---

common/stream.cpp

Removes an abstraction-breaking assertion in `MemoryReadStream::seek()`. 
`MemoryReadStream::seek()` fails an assertion (crashes) when requested to seek out of bounds. Expected behavior is to not crash on an invalid seek, but to return false and not reset eos. Currently it always returns true.
Passing a `MemoryReadStream` as a `Stream` is currently unsafe, because any code that seeks, reads, and tests `eos()` (a common pattern) becomes a fatal error. This is blocking an AGI feature I'm working on.
In my case, parsing code takes a `SeekableReadStream`. This used to always be a `Common::File`, but now it can be a `MemoryReadStream`, so it crashes. This is detection/parsing code, so it will routinely encounter files it can't parse. That's good and expected; that's what the `seek()` return …

COMMON: Remove MemoryReadStream::seek() assertion

---

engines/immortal/compression.cpp
engines/immortal/cycle.cpp
engines/immortal/immortal.h
engines/immortal/kernal.cpp
engines/immortal/module.mk
engines/immortal/room.h
engines/immortal/sprite_list.h

If this is accepted, someone has to rename
*kernal.cpp* to *kernel.cpp*
otherwise this PR will always fail.
I have no idea how to do that from the web interface or without stomping the change history of that file.
Thank you and sorry for the additional workl

JANITORIAL: IMMORTAL: Fix typos in comments *and one file name*

---

engines/scumm/gfx_gui.cpp
engines/scumm/imuse/imuse.cpp
engines/scumm/imuse/imuse_internal.h
engines/scumm/sound.cpp
engines/scumm/sound.h

Posting this as a PR because I'm touching code which I'm not comfortable touching 😛 
The reduction algorithm is the one from the SAMNMAX sound drivers.
INDY4 and DOTT apparently use an earlier version of the algorithm, but this is not implemented because:
- I'm not sure if what I found is the algorithm
- If it is, I don't understand it
- My iMUSE disassemblies are heavily unlabeled
EDIT: At the cost of redundancy, please don't merge this until review is through, as any errors in this PR could break flagship games 🙂

SCUMM: IMUSE: Implement music volume reduction during speech

---

engines/sci/sound/music.cpp

Since I am the one who added the assert that gets triggered here, I have now prepared a fix.
The assumtion that the global pause would always have to be 1 here, is wrong. It can have higher values due to kDoSoundPause() calls from the scripts.

SCI: fix  bug no. 15336

---

engines/scumm/script.cpp

During a recent livestream with David Fox and Matthew Kane, a bug was discovered in Zak McKracken, it appears to be an original game bug and not a ScummVM issue.
The issue can be seen to occur here, https://youtu.be/HJ5CpEy4sio?t=5473 
Note, Annie has a crystal shard in her inventory and when trying to pick up the shard from the statue, the inventory still only has one shard.
If the player took Annie to the Mexican temple and tried to pick up the yellow crystal shard from the statue, the object was not added to the inventory.
I took a look at the V1 and V2 scripts in descumm, it looks like V2 fixes this issue by moving a pickupObject call outside of a check for the current actor.
Script 119 is the script in question, it does a check against the current actor and in V1 it only runs …

SCUMM: V0/V1 - Workaround for original blocker bug in V0/V1 Zak that prevented Annie from picking up the crystal shard from the statue in Mexico.

---

.github/workflows/ci.yml
devtools/create_project/msvc.cpp

OpenGL was disabled on Windows arm64 since it's not natively supported, however Microsoft has since added a [OpenGL Compatibility Pack](https://devblogs.microsoft.com/directx/announcing-the-opencl-and-opengl-compatibility-pack-for-windows-10-on-arm/) which should resolve the issue.
We don't need to statically link to "opengl32.lib" anymore, since we added GLAD which resolves it dynamically in runtime instead.

CREATE_PROJECT: Reenable OpenGL on Windows ARM

---

engines/ultima/nuvie/keybinding/keys.cpp
engines/ultima/nuvie/keybinding/keys.h

Injects ios gamepad d-pad key bindings in keys.cpp instead of regenerating ultima.dat
Following @dreammaster  suggestion, this commit adds ios d-pad key bindings programatically when JOY12-JOY15 were unmapped after loading the defaultkeys, game specific keys, and patch key bindings. This allows the use of Dpad-mode Directional button overlays on iOS 15 or later devices when playing ultima6-based games.

ULTIMA6: inject ios gamepad d-pad key bindings

---

engines/grim/configure.engine

libmpeg2 is only required for the PS2 version, and there's already fallback code for when it's not available.

GRIM: Remove mpeg2 requirement from Monkey4 subengine

---

engines/sci/engine/kfile.cpp

I would have added this to PR 6074, since it is part of the bug fix, but that one has already been merged.
In the bug no. 15336 scenario the global pause counter will be increased by 4 before the save/load dialog is shown. If we don't reset it it will still have that value after loading the savegame. Currently, we reset it only for the ScummVM dialogs but not for the original ones.

SCI: fix global pause counters when using original save/load dialogs (follow up to PR 6074)

---

devtools/create_project/create_project.cpp

Missing newline characters caused slightly unpretty output of the help text.

CREATE_PROJECT: add missing newlines to help text

---

engines/gob/detection/tables_gob1.h

This avoids Amiga version being picked over DOS EGA one. They now have the same number of files so the user is prompted which version it owns.
PR #5868 was not fixed as requested before the merge.

GOB: Fix DOS EGA game detection following #5868 merge

---

engines/grim/gfx_base.h
engines/grim/gfx_opengl.cpp
engines/grim/gfx_opengl.h
engines/grim/gfx_opengl_shaders.cpp
engines/grim/gfx_opengl_shaders.h
engines/grim/gfx_tinygl.cpp
engines/grim/gfx_tinygl.h
engines/grim/grim.cpp

This fix is needed to properly display the gamepad overlay on Android when in menus.
The `_doFlip` flag has been added by @eriktorbjorn in 24bcd2bd25d5 in order to reduce CPU usage while playing Smush videos.
The main problem is that it blocks redraws to take into account external events (for example screen resize) and I am almost sure that it would have cause black screen if a window would have gone over ScummVM one.
I am not completely sure it's valid because I may need to force some draw before.

GRIM: Refresh screen on a regular basis on hardware renderer

---

engines/agi/agi.cpp
engines/agi/agi.h
engines/agi/detection_tables.h
engines/agi/keyboard.cpp
engines/agi/module.mk
engines/agi/op_cmd.cpp
engines/agi/sound.cpp
engines/agi/sound.h
engines/agi/sound_2gs.cpp
engines/agi/sound_2gs.h
engines/agi/sound_a2.cpp
engines/agi/sound_a2.h
engines/agi/sound_coco3.cpp
engines/agi/sound_midi.cpp
engines/agi/sound_midi.h
engines/agi/sound_sarien.cpp

This PR was supposed to add sound to Apple II AGI games, but there was scope creep and now it does CoCo3 too. *Oops!*
I reverse engineered the A2 sound format, which is indirectly based on 6502 CPU cycle counts and CPU speed, and then counted all the CPU cycles and implemented this in a new sound generator. It uses `Common::PCSpeaker` to do the heavy lifting, and I think it sounds great. The tones sound just like the AppleWin emulator to me.
This was too much fun, so I used the information in Guillaume Major's CoCo3 AGI sound converter (cc3snd.c) to write a CoCo3 sound generator. This replaces the disabled shell of broken code we had in soundgen_coco3.h/cpp, so pretend that didn't exist, because it didn't.
The best part was writing a little proof-of-concept program to test the Apple II …

AGI: Apple II sound, CoCo3 sound

---

engines/gob/sound/sound.cpp
engines/gob/sound/sound.h

We found that some tracks where not played in Gobliiins 1, in the 
Windows version.
After a quick check we noticed that the boolean flag was always false, 
and the code was never executed to play a background track.

GOB: Fix missing background tracks in Gobliiins 1

---

engines/qdengine/qdcore/qd_interface_dispatcher.cpp

QDENGINE: Persist ConfMan changes across gameruns for sound/music

---

backends/platform/3ds/main.cpp
backends/platform/3ds/osystem-graphics.cpp
backends/platform/3ds/osystem.h
backends/platform/3ds/sprite.cpp
backends/platform/3ds/sprite.h

The memory allocated to processes on the 3DS is divided between the application heap (which is used by malloc) and the linear heap (which is used for memory that's used by hardware devices). Normally libctru divides this up semi-evenly, but this results in there being more linear memory than is strictly necessary and not enough regular memory for some engines. (especially on the old 3DS). This reduces the amount of linear memory that ScummVM needs so that a limit of 10 MB can be enforced, allowing the application heap to grow larger.
There's potentially some additional room for improvement by moving the `gfxInitDefault` framebuffer into VRAM as well, but it looks like it'll need initialising to avoid graphics corruption and I'm not sure what's the best way to do that.
On the old 3DS, …

3DS: Limit the linear heap to 10 MB

---

backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/openglsdl/openglsdl-graphics.h

Originally authored by @magicmyth in PR #1039
ScummVM is optimised to render frames when something changes on screen. As some host environments can perform poorly if the app does not reliably refresh its output regularly (notably Steam overlay) this new option ensures that Scummvm outputs a minimal amount of frames even if nothing is changing in the game renderer.
Currently this is only implemented in the SDL OpenGL renderer.
The new config option is called force-frame-update and it takes a integer value representing the desired minimum milliseconds Scummvm should wait before forcing a screen update/refresh. E.g: 50.
Note that the rendering system will not force a re-draw of a frame if the app has rendered a changed frame within the desired minimum refresh.
Thus if the app is outputting …

BACKENDS: Minimal render rate support (force-frame-update) redux

---

engines/ultima/nuvie/actors/actor_manager.cpp
engines/ultima/nuvie/actors/actor_manager.h
engines/ultima/nuvie/conf/configuration.h

This PR allows loading the `custom_tiles.bmp` file from the ultima6 game directory. In a subdirectory called `mods/`
It also decouples loading custom base tiles from the custom actor tiles config setting.
```
[ultima6]
ultima6/custom_actor_tiles=yes
```
Here is the brown dirt custom tileset in action! The bmp file can be found at [https://ultimacodex.com/2017/06/nuvie-support-for-exporting-and-importing-tilesets-added/](https://ultimacodex.com/2017/06/nuvie-support-for-exporting-and-importing-tilesets-added/)

NUVIE: Allow loading custom tiles from game dir mods/custom_tiles.bmp

---

engines/scumm/metaengine.cpp
engines/scumm/scumm.cpp

I checked the scripts for each version of MM and found that it was possible to run the demo/kiosk script in:
V1/V2 DOS
Amiga
Atari ST.
Now doing a platform check for these to mark them as valid targets.

SCUMM: MM - Update list of valid targets for demo checkbox.

---

engines/mtropolis/detection_tables.h

Some detection entries are faulty due too much copypasting and insufficient pre-submission tests.

MTROPOLIS: correct various hashes and filesizes in detection

---

engines/mtropolis/plugin/mti.cpp
engines/mtropolis/plugin/mti.h
engines/mtropolis/plugin/mti_data.cpp
engines/mtropolis/plugin/mti_data.h
engines/mtropolis/plugin/standard.cpp
engines/mtropolis/plugin/standard.h
engines/mtropolis/plugin/standard_data.cpp
engines/mtropolis/plugin/standard_data.h

Move the Print modifier from the MTI plugin to the Standard plugin. Usage of Print is very common in mTropolis games.
Although MTI had Print in its MTIKIT plugin, most of the content from MTIKIT, including Print, is found in the EXTRAS and EXPRMNTL plugins of many mTropolis 1.1 titles.

MTROPOLIS: Move Print modifier from MTI to Standard

---

configure
engines/ags/lib/allegro/surface_avx2.cpp
engines/ags/lib/allegro/surface_neon.cpp
engines/ags/lib/allegro/surface_sse2.cpp
engines/ags/module.mk
graphics/blit/blit-avx2.cpp
graphics/blit/blit-neon.cpp
graphics/blit/blit-sse2.cpp

This PR fixes leftovers following the PR #5581 where AGS code was not touched to apply the same recipe.
Then, the support for Clang is added with proper version checks.
Finally the checks for GCC and Clang version are relaxed for architecture which do not need such checks (ARMv8 for NEON and x86_64 for SSE2).
This is not perfect as old Android ARM cannot benefit from the SIMD code but it allows to widen the support to Android ARM64 and all MacOS platforms at least.

GRAPHICS: AGS: Fix ODR problems in AGS and add Clang support

---

engines/myst3/myst3.cpp

When autosaving, an Autosave file is created which often displays a different thumbnail image to the game state saved.
This is a regression from when the engine's tryAutosaving() method was replaced by the global saveAutosaveIfEnabled(), prior to merging ResidualVM with ScummVM.
Currently, a thumbnail of the game screen is generated whenever the user opens a menu, or pauses the game. This  thumbnail is saved to _saveThumbnail, then later copied when writing a save file. Works well for regular saves, but not when autosaving.
In the original tryAutosaving() method, the autosave generated its own thumbnail, immediately before calling saveGameState().
Fixed by modifying saveGameState() to enable an autosave to generate a thumbnail of the current game screen, prior to obtaining it from …

MYST3: Fix autosave thumbnail displaying incorrect game state

---

devtools/create_project/xcode.cpp
dists/ios7/PrivacyInfo.xcprivacy
dists/tvos/PrivacyInfo.xcprivacy
ports.mk

Apple will require a valid privacy manifest file bundled for applications uploaded to App Store Connect.
The privacy manifest describes the privacy practices of an app, describing the reasons of use of some core APIs that can be misused to try to identify the device or user, also known as fingerprinting.
Read more about which APIs that require a privacy manifest here: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
Add such manifest to ios7 and tvos ports and make sure they are bundled with the app.

DISTS: Add PrivacyInfo.xcprivacy to ios7 and tvos

---

audio/decoders/mpc.cpp
configure

Currently, only the latest libmpcdec is spported by our code.
This adds support for older versions of the API which are still in used in MacPorts and AmigaOS.
I removed the call to pkg-config because the library has no .pc file and I add the missing support for the `--with-mpcdec-prefix` which was already documented.

AUDIO: Add support for libmpcdec 1.2.6 and older

---

engines/mtropolis/boot.cpp
engines/mtropolis/coroutine_manager.cpp
engines/mtropolis/elements.cpp
engines/mtropolis/hacks.cpp
engines/mtropolis/plugin/ftts_data.h
engines/mtropolis/plugin/hoologic_data.h
engines/mtropolis/plugin/standard.cpp
engines/mtropolis/plugin/thereware_data.h
engines/mtropolis/runtime.cpp
engines/mtropolis/saveload.cpp

Resolve various typos and an error in a comment in the mTropolis engine code.

JANITORIAL: MTROPOLIS: resolve various typos

---

backends/platform/ds/portdefs.h
backends/platform/libretro/include/config.h
backends/platform/psp/display_client.cpp
backends/platform/psp/thread.cpp
backends/platform/psp/thread.h
common/scummsys.h
configure

Now that `inttypes.h` is included on all platforms, we can use those types as aliases for our own types. This avoids the complexity of detecting the sizes of types in `configure` and provides better defaults when using other build systems (`create_project`, libretro, etc.) Platforms where this is an issue can specify alternative types in the backend's `portdefs.h` file.
A workaround has been left in place for AmigaOS and MorphOS, but I'm hoping that both of them use long for `int32_t` and `uint32_t`, which would allow the workaround to be removed. (CC @raziel-, @BeWorld2018).

COMMON: Replace type detection in configure with aliases for stdint.h types

---

engines/watchmaker/3d/geometry.cpp
engines/watchmaker/render.h

Mostly for consistency.
enviroment is clearly wrong
even l'enviroment is wrong, it has to be l'environnement (fixed that too)
Just two lines, but it touches code, so...

JANITORIAL: WATCHMAKER: Fix enviroment typos

---

engines/lure/debugger.cpp
engines/lure/hotspots.cpp
engines/lure/hotspots.h
engines/lure/res.cpp
engines/lure/room.cpp

Separate PR, since it touches code
The one fix in debugger.cpp will probably stumble over the big bunch of typo fixes, since the warning message has been fixed there...so either we wait for that to get merged first or fix this PR later???

JANITORIAL: LURE: Fix persistant typos in in code

---

engines/pink/objects/actors/lead_actor.cpp
engines/pink/objects/handlers/handler.cpp
engines/pink/objects/handlers/handler.h
engines/pink/objects/handlers/handler_mgr.cpp

Need a little help here, since it could be intended
in lead_actor.cpp, line 64 _recipient is spelled correctly ONCE...all of the other instances are misspelled.
Was that an oversight?
Intended?
How did that piece of code even work? :-)
Or is that "if else" loop extremely unlikely to trigger?
Thank you

JANITORIAL: PINK: Fix recepient typos in code

---

engines/sci/sound/drivers/pcjr.cpp

After being asked to check the validity of PR #6064 I quickly noticed that our driver doesn't implement most of the components that make up the final volume. It gets calculated from the master volume, the channel volume, the velocity and a value produced by an envelope generator. SCI1 uses instrument patches for that, SCI0 has fixed tables.
I have now added the necessary code for SCI0 and SCI1.
The driver can still be considered WIP. I haven't added pitch bend support yet. Also, I would be surprised if it didn't require some more accuracy fixes, since I haven't tested this all that much.
And while I did manage to avoid a rewrite and just added some code on top, it might still be a good idea to clean this up.
I noticed that PCJr and PCS don't work with KQ4 Early for me. The engine seems to …

SCI: fix PCJr sound driver volumes

---

engines/mtropolis/boot.cpp

Add specific boot scripts for numerous mTropolis games, configuring plugins and explicitly stating the main segment file where necessary.

MTROPOLIS: add specific boot functions for numerous games

---

engines/sci/graphics/gfxdrivers.cpp
engines/sci/graphics/gfxdrivers.h
engines/sci/graphics/screen.cpp

Currently the screen shakes will not be scaled to the driver's screen resolution. This patch fixes that.
Now, this isn't exactly the original behaviour. The screen shaking was a hardware feature that only EGA and VGA adapters had. Therefore, the screen shake function is only implemented in the drivers for these devices. For all other graphics hardware the drivers have an empty dummy function for the screen shake (at least from what I have seen). But we needn't be strict here, we can shake everything...

SCI: add setShakePos() function to gfx drivers

---

engines/mm/xeen/font.cpp
engines/mm/xeen/font.h
engines/mm/xeen/window.cpp

Note: this isn't full Chinese support, only font rendering
Tested with "Might and Magic V: Darkside of Xeen"

XEEN: Support rendering Traditional Chinese characters

---

configure
dists/android/build.gradle

This version is the last one to support API level 17 (Jelly Bean).
It also gets rid of all remnants from the old binutils/GCC toolchain.
This also migrates from LLVM 9 to LLVM 12.
I have a Docker toolchain update ready for these changes.
This PR must be merged synchronously with a docker image update to keep the Buildbot happy.
Produced packages still need to be tested on various Android phones before merging.

ANDROID: Upgrade the NDK to version 23

---

engines/mtropolis/plugin/standard.cpp
engines/mtropolis/plugin/standard.h
engines/mtropolis/plugin/standard_data.cpp
engines/mtropolis/plugin/standard_data.h

Add stubs for the modifiers OpenTitle and Navigate. They can be found in the Extras plugin, which belongs to the set of default/standard plugins.
OpenTitle allows to load a new MPL file (or equivalent). About a dozen games work this way, spread out across numerous MPL files interlinked with this modifier.
Navigate executes scene changes. This feature is used more rarely.
The data structure of Navigate has not been determined yet.

MTROPOLIS: add stubs for OpenTitle and Navigate modifiers

---

engines/mtropolis/boot.cpp

There is a bit in ``PlugInModifier::load`` where it discriminates between Windows and Mac games. That Windows code path is only correct for early mTropolis versions, so the condition also tests the mTropolis version of the game. However, the current version detection heuristic is rather inaccurate. Many mTropolis 1.1 games choose the wrong code path and run into an error.
Luckily, all this can be worked around easily by explicitly setting the desired mTropolis version in the boot scripts of affected games.
Using the Hack subsystem for this instead would cause more complications.

MTROPOLIS: set engine version to V112 for various games

---

engines/mtropolis/data.cpp

Enable more revision codes in modifiers, especially for mTropolis 2.0.
Revisions were only enabled when there were no subsequent issues with data loading in the modifier.

MTROPOLIS: enable more revision numbers for modifiers

---

gui/widgets/grid.cpp

`_disabledIconOverlay`, a `ManagedSurface` regularly re-instantiated e.g. when the window is resized, should be deleted rather than merely have its `free()` method called.
While here, remove an if() which is guaranteed true lest scummvm segfault at `gfx->fillRect()`.
If I may I would ask @tag2015 for review.
Addresses `ERROR: LeakSanitizer: detected memory leaks`:
```
Direct leak of 224 byte(s) in 2 object(s) allocated from:
#0 0x7f4c796b94c8 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:95
#1 0x5562ef20fa29 in GUI::GridWidget::reflowLayout() gui/widgets/grid.cpp:1080
#2 0x5562eef1c366 in GUI::Dialog::reflowLayout() gui/dialog.cpp:116
#3 0x5562eef56ca3 in GUI::LauncherDialog::reflowLayout() gui/launcher.cpp:918
#4 0x5562eef30a97 in …
```

GUI: Fix leak in widgets/grid.cpp

---

engines/myst3/metaengine.cpp
engines/myst3/myst3.cpp
engines/myst3/state.cpp

The autosave process isn't set up properly for use with Myst3's non-slot-based save system, particularly when dealing with non-English versions of the game.
This PR seeks to exclude those aspects of the autosave process which are only relevant to engines with slot-based save systems.
Specifically, we exclude the unnecessary testing of the Autosave file before each autosave, and adding a custom dummy autosave to the Save List (whenever the Autosave file is either missing or has a non-English name).
We achieve this by always presenting slot 0 as an unused slot for pre-autosave testing purposes (currently, this is how it's done when the Save List is empty).
Slots are always ignored when saving, so detecting the Autosave file isn't an issue. For example, the English Autosave file is currently …

MYST3: Optimise autosaving for non-slot-based usage

---

engines/scumm/script_v6.cpp

This PR fixes a bug in Backyard Baseball 2001 online play in which stat adjustments due to things like siblings being on the same team don't get applied correctly for the away team. This results in the two clients showing and using different versions of players' stats, which 1. is unfair and 2. could cause desyncs.
[Here's the script in question.](https://github.com/whatisaphone/baller/blob/756703108fbd3c34c612406f567cef908074a29f/scripts/27/lsc2346.scu#L4) By returning (`push`ing) 0 for that line, the script doesn't early-exit for the away team. I'm unsure why it was written like this originally.

SCUMM HE: BYB01 online play stat buffs fix

---

engines/myst3/myst3.cpp

Thanks to @eriktorbjorn  and @criezy for reviewing my code in [44fc331](https://github.com/scummvm/scummvm/commit/44fc3315a4461c1a98a50b53f333ccb182034dfa), and identifying that my sanity check isn't properly constructed, and for providing the correct solution.

MYST3: Fix incorrectly constructed sanity check

---

engines/mtropolis/detection_tables.h

I would like to suggest to promote three mTropolis titles from Unsupported to Unstable. The mTropolis engine implementation is far enough that these titles can do something useful when run with ScummVM. 
HTBATP offers lectures on the titular subject which consist of audio talks combined with slide shows, but not actual video.
There is also a bit of general informational text to read.
ScummVM will play the audio lectures. But while the audio plays the app window freezes in the sense that it is not refreshed or repainted. When the lecture ends it unfreezes.
The text can be read.
FWA was originally a physical toy consisting of rubber stamps in various shapes that could be layed into buildings and printed onto paper with an inkpad. It also came with a booklet explaining some architectural …

MTROPOLIS: Promote three titles to Unstable

---

engines/mtropolis/detection_tables.h

After the criteria for a game's status were clarified in PR #6128, Star Trek: The Game Show demo should be demoted from unstable to unsupported.
After the start screen, STTGS demo runs into an error about being unable to load a data object of the unknown type 0xc5.
So while it can boot, it cannot do anything useful.
The retail version of STTGS suffers the exact same error, but is already listed as unsupported.

MTROPOLIS: declare Star Trek: The Game Show demo as unsupported

---

engines/scumm/gfx_gui.cpp
engines/scumm/metaengine.cpp
engines/scumm/saveload.cpp
engines/scumm/scumm.cpp
engines/scumm/scumm.h

This is my best bet at fixing the collision between autosaves and savestates made on slot 0 on original menus.
Quoting myself from a comment in this PR:
> In ScummVM 2.7.0, original GUI support was added.
> Unfortunately it came with an issue: in v4-7 games users could
> overwrite autosaves (slot 0). Why? Because I forgot about autosaves :-)
> 
> To amend this from 2.9.0 onwards we check for savegames which are on slot 0
> and are not autosaves (the heuristic is not optimal, but it will have to do),
> and performs a mass rename. Unless the user has used all 99 slots, in which case
> we just bail because there's no easy way to fix that...
Emphasis on "the heuristic is not optimal, but it will have to do": we have no means to see if a savegame is an actual autosave, we can only use its …

SCUMM: GUI (v0-3, v8): Prevent users from overwriting autosave slot

---

engines/ags/shared/core/platform.h
engines/ags/shared/util/file.cpp
engines/ags/shared/util/path.cpp
engines/ags/shared/util/string.h

Since we're using our common file system code, this functionality does not apply for ScummVM. The defines for this code were never set, so it's definitely unneeded.
This also allows us to remove a case of the NDEBUG define

AGS: Remove unused case sensitive file system code

---

common/hashmap.h
devtools/create_mm/create_xeen/hashmap.h
devtools/create_titanic/hashmap.h
engines/sci/graphics/celobj32.cpp

<strike>Remove the usage of NDEBUG
We don't define NDEBUG in release builds, but we have other means
of debugging in our common code, via debug levels</strike>
**Update:** This has been changed so that all the remaining usage of NDEBUG is replaced with RELEASE_BUILD
This is a follow-up to PR #2486

NDEBUG usage adaptation to RELEASE_BUILD

---

engines/scumm/he/resource_he.cpp
engines/scumm/resource.cpp
engines/scumm/resource_v4.cpp
engines/scumm/scumm.cpp
engines/scumm/util.cpp
engines/scumm/util.h

SCUMM leaks engine arrays when restarting a game. They are allocated on engine init and restart, but only freed when the engine is destroyed.
This PR adds a free/calloc utility function for the leaks I found. SCUMM devs may want to handle this differently; if so please feel free to close this PR and consider it a bug report =)

SCUMM: Fix memory leaks on restart

---

engines/mtropolis/elements.cpp

In How To Build A Telemedicine Program, all the video files have no video frames, and contain only audio. In this case, the QT player will keep playing the video until the audio is finished. Handle such cases, so that the game's UI is responsive

MTROPOLIS: Handle videos that have no video frames

---

gui/widgets/popup.cpp

Fixes a regression introduced five years ago, where clicking on a separator in a `PopUpDialog` causes an empty selection instead of the real item that's selected.
`PopUpDialog::handleMouseMoved` has the correct logic to handle separator items, but `handleMouseUp` didn't.

GUI: Fix clicking on PopUpDialog separator

---

engines/sci/graphics/celobj32.cpp

@bluegr this completes c4942be17feb5195a2993770eeb030604e5c8b85. At that commit build will fail if `RELEASE_BUILD` is defined, due to a couple of undefined variables.

SCI: fix RELEASE_BUILD tests

---

backends/graphics/sdl/sdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.cpp

This PR adds ImGui support to SdlSurfaceGraphicsMgr, in a similar fashion as other backends. It was tested using "Appartment 3" when ScummVM is launched with "--debugflags=imgui". The base SdlGraphicsMgr class was changed to accept a nullptr glContext which in turns calls ImGui_ImplSDL2_InitForOpenGL with a null context. The internal implementation of ImGui_ImplSDL2_InitForOpenGL allows for this situation, essentially falling back to the appropriate path for us.

BACKENDS: Add ImGui support to SurfaceSdlGraphicsManager

---

engines/glk/advsys/game.cpp

Previously Game::findWord() assumed words of fixed length (6)
Games like "one hand" and "pirating" failed to parse correctly most verbs, because the code would only work with words of the max length (6). The issue was mentioned on the ScummVM forums here: https://forums.scummvm.org/viewtopic.php?p=99918#p99918

GLK: ADVSYS: Fix verb parsing

---

engines/freescape/loaders/8bitImage.cpp

Simplified binary image RLE decoding, thereby implementing missing codes. This also allows decoding the bitmaps for Hercules display mode. Hercules images are encoded using the same scheme, but at 720x348 resolution.

FREESCAPE: Fix RLE decoding

---

backends/graphics/graphics.h
backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/openglsdl/openglsdl-graphics.h
backends/graphics/sdl/sdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.h
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h
backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
backends/graphics3d/openglsdl/openglsdl-graphics3d.h
backends/imgui/backends/imgui_impl_sdlrenderer2.cpp
backends/imgui/backends/imgui_impl_sdlrenderer2.h
backends/modular-backend.cpp
backends/modular-backend.h
backends/module.mk
common/system.h
configure
devtools/create_project/create_project.cpp
engines/director/debugger/debugtools.cpp
engines/qdengine/debugger/debugtools.cpp

This properly adds ImGui support to SDL using SDL_Renderer instead of OpenGL.
This needs a new backend from ImGui which has been added using the same commit as other files.
As ImGui doesn't handle image loading, a new API is added to instantiate the images and Director and QDEngine engines are ported to it.
These engines do not clean the images afterwards and this should be added.
The TWP engine is deeply intricated with OpenGL and the support has not been added.
Only the Director engine has been tested in OpenGL and SurfaceSDL mode.

SDL: Add ImGui support to SDL Renderer

---

backends/fs/posix-drives/posix-drives-fs.cpp
backends/fs/posix/posix-iostream.cpp
backends/fs/posix/posix-iostream.h
backends/fs/stdiostream.cpp
backends/fs/stdiostream.h
backends/log/log.cpp

A temporary file is used to write the data and the file is renamed when it is closed.
The string containing the destination path is a stored as a pointer to limit the size of the object (which is already doubled) as in majority of the streams the path will never be used.
This implementation is done in StdioStream to cover most of the backends.
The PosixIoStream code is adapted to avoid code duplication.
This should fix problems of configuration file corruptions which can happen on mobile platforms ~or on concurrent writes~.
EDIT: concurrent writes are not fixed as we use the same file in both processes.
Customizing using the PID would help but in case of a crash it would leave a dangling file which would be never cleaned up.

BACKENDS: FS: Atomic write of files

---

backends/cloud/onedrive/onedrivetokenrefresher.cpp
backends/cloud/onedrive/onedrivetokenrefresher.h

Fixes OneDrive sync by handling list of unexisting "saves" subdirectory.
Previously, code that worked with JSON didn't trigger, because string was intentionally malformed. If it wasn't, `OneDriveTokenRefresher::finishError()` would've treated it as JSON parse failure, tried to fix it, and call `finishJson()` instead of `finishError()`. Now, there's a separate method that doesn't try to fix JSON parse failure, and that method is called in case we're sure this is not a parse failure and `finishError()` should be called indeed.

CLOUD: fix #15337

---

backends/updates/macosx/macosx-updates.mm
configure

I didn't push that code directly as this would break buildbot macOS builds. This can be merged once Sparkle has been updated to version 2 on buildbot.
**Important:** We will also need to migrate to an EdDSA signature before the next release, but this is not included in this pull request. See https://sparkle-project.org/documentation/eddsa-migration/ for details.
This was tested on a Mac M1 with Sparkle 2.5.2.

MACOS: Migrate to Sparkle 2 API for updates

---

backends/dialogs/morphos/morphos-dialogs.cpp

Apparently, on MorphOS, if you try to add a game from a directory where no game exists, cancel out of the platforms native ASL requester and quit ScummVM, the lock on said directory is still present, making it impossible to I.e. delete it.
This change is courtesy of @BeWorld2018 as he has tested that patch on his platform, still I'd need confirmation from him that i didn't break something else.
The same fix "would" also work on AmigaOS (at least it doesn't break anything) but is not needed, because the steps to reproduce it on MorphOS doesn't trigger it on AmigaOS, so i leave it be.
Probably because of a more updated ASL?
Also removed some superflous blank lines

BACKENDS: MORPHOS: Fix ASL lock on directory

---

backends/platform/ios7/ios7_touch_controller.mm
backends/platform/ios7/ios7_video.h
backends/platform/ios7/ios7_video.mm
doc/docportal/other_platforms/ios.rst

Some time ago (~v2.2.0) the iOS version had very basic support for using the Apple Pencil as an input device.  
It seems, as more robust input handling has been implemented since then, that the Pencil now needs its own specific gestures in order to work.
This PR adds basic support so that the Pencil can be used in a similar way to touching the screen.
| Pencil Gesture | Description
| --- | ---
| Touch | Left mouse click
| Touch and hold for 0.5 seconds | Let mouse click and hold (for COMI style games)
| 3 quick taps on screen | Right mouse click
To explain a few choices, the Pencil does not seem to work well with `UITapGestureRecognizer` so I used `UILongPressGestureRecognizer` to detect a basic touch input. Because you don't seem to be able to have two `UILongPressGestureRecognizer` …

IOS7: Add Apple Pencil Input Support

---

engines/sci/detection_tables.h
engines/sci/engine/kernel.cpp
engines/sci/engine/kmisc.cpp
engines/sci/engine/savegame.cpp
engines/sci/graphics/screen.cpp
engines/sci/metaengine.cpp
engines/sci/sci.cpp
engines/sci/sci.h

This PR improves KQ6 CD with regards to the `enable_high_resolution_graphics` config setting:
1. `enable_high_resolution_graphics` is clarified for how it affects KQ6 CD: it overrides the ScummVM DOS platform setting and replaces it with Windows
2. `enable_high_resolution_graphics` is no longer enabled by default for the DOS platform
3. `enable_high_resolution_graphics` is no longer available for the Windows platform, because it had no effect
This addresses several sources of confusion:
1. When adding KQ6 CD, we prompt users for DOS or Windows, and then deliver the Windows experience regardless of which they choose.
2. The DOS experience is only achievable by first selecting DOS and then unchecking "Enable High Resolution Graphics".
3. Selecting Windows and then unchecking "Enable High …

SCI: Improve KQ6 CD `enable_high_resolution_graphics`

---

engines/freescape/games/driller/dos.cpp

The processing in DrillerEngine::load8bitTitleImage was rather overcomplicated, had a few potential off-by-one errors and had superfluous checks instead of checking for the end-of-line marker. This commit greatly simplifies the decoding.
Although I've not touched that aspect, I would have preferred the use x,y instead of i,j for coordinates, and using a for loop rather than a while countdown.

FREESCAPE: simplified 8 bit title image loading for Space Station Oblivion

---

engines/gob/POTFILES
engines/gob/gob.h

Since we replaced the common/translation code with the MetaEngine code we no longer have to use _s() in the detection tables.

GOB: remove detection headers from POTFILES

---

engines/grim/grim.cpp
engines/grim/lua.h
engines/grim/lua_grim_patch.cpp
engines/grim/module.mk

This is a follow up to fix #13139 and #14987.
All saves created with the faulty patch get contaminated so we decontaminate them at load time by applying a minimized fixup.
This will avoid players to restart a game from scratch and any game saved again will get this fix.
This will address comment in #5692.

GRIM: Patch saves on the fly

---

engines/tinsel/detection_tables.h

This adds detection for the DOS demo and second windows demo that are on the ScummVM website
Both of these demos are added as UNSUPPORTED since they both crash to the debugger at launch. I have also replaced the "demo" string with an empty string "" for both of the detection entries, since otherwise the error message when launching these games (after the detection is added) was a confusing "This game is unsupported for the following reason demo".
It also changes the platform for the one detected demo to be Windows to match with how it is presented on the ScummVM demos page. I am unsure though if this change is correct, or if the description on the demos page is wrong.
This does not add detection for the PSX demo offered on the ScummVM demos page, as it's not clear to me how that could be …

TINSEL: Add detection for unsupported DW2 demos

---

engines/wintermute/ad/ad_game.cpp

If `ENABLE_WME3D` is undefined, the engine won't build, as `_geom` for `Wintermute::AdScene` is not defined in this case.
This will fix the build, though I'm not sure if the returned value is correct from the point of view of the engine functionality.

WINTERMUTE: WME3D: fix missing condition

---

engines/kyra/engine/eobcommon.cpp
engines/kyra/engine/eobcommon.h
engines/kyra/engine/items_eob.cpp
engines/kyra/engine/kyra_rpg.h
engines/kyra/gui/gui_eob.cpp
engines/kyra/gui/saveload.cpp
engines/kyra/gui/saveload_eob.cpp

**KYRA: (EOB)** - Fix projectile weapon damage
**Note**: All changes of game functionality here are behind the "Faithful AD&D rules" flag.
Fixes a bug in the original games, where projectiles would deal an incorrect amount of damage (always 1d1):
- projectile weapon id is attached to a FlyingObject and checked when FlyingObject hits a monster or the party
- bumps the save format version to add a new field to FlyingObject (the new 16 bit field replaces the existing unused 8 bit field)
- fixes a bug in original code where a projectile weapon thrown into the 3D view would inflict projectile damage (should be 1d1)
- patch EotB 1 Bow and Sling damage according to AD&D 2nd Ed rules
Elves get +1 to hit bonus with bows and swords, according to manual
Patch EotB 1 NPCs Beohram (paladin) and Ileria …

KYRA: (EOB) - Fix projectile weapon damage

---

engines/bagel/spacebar/spacebar.cpp

This avoids additional conversion when RGB565 isn't supported natively by the backend. Ideally it would be nice to support 256 colour modes as well, but that would require extra work for cases where multiple windows use different palettes.

BAGEL: Allow using pixel formats other than RGB565

---

gui/widgets/grid.cpp

This fixes a regression from commit 4b7782448c7f551ead944be9a296a33505b26bee - the surface is stored in two separate HashMaps and gets deleted from both of them, which leads to a crash when the same pointer is in both of them.

GUI: Fix a crash when exiting the grid view

---

graphics/font.cpp
graphics/font.h

Creating a PR for this as it's common code and I want to check my change makes sense.
The DGDS engine word wrapping algorithm appends any amount of whitepsace on the end of the line before wrapping, allowing the nominal line length to go beyond the limit specified. The drawn length will still be within the limit.
Add a WordWrapMode flag that does the same.

GRAPHICS: Add wrapping mode that ignores trailing space

---

engines/crab/image/Image.cpp
engines/crab/image/Image.h

This follows commit 26938f6 that fixed dereferencing a null pointer. The same issue existed in another `Image::load()` overload (that starts by destroying the _texture and then accesses it). But it seems that that overload is actually not used, so it seems better to remove it rather than fix it. But this may need to be reviewed by developers familiar with that engine to confirm.

CRAB: Remove unused function

---

engines/sky/music/musicbase.cpp
engines/sky/music/musicbase.h
engines/tinsel/music.cpp
engines/tinsel/music.h

Here are two commits which should fix the crash in modern Android.
Instead of modifying Android code (which would have lowered the performance), I fixed the engine code to not attempt to open files from the audio thread.

SKY/TINSEL: Fix loading of music on Android

---

engines/dreamweb/dreamweb.h
engines/dreamweb/object.cpp
engines/dreamweb/vgagrafx.cpp

This PR fixes a crash when changing rooms after using a key on a thing: https://bugs.scummvm.org/ticket/15420
I'm unfamiliar with this engine and game, but the bug was easy to reproduce and seems straightforward.
`DreamWebEngine::_exFrames::_frames` is an array of 347 `Frame` objects. `DreamWebEngine::deleteExFrame` takes an index into this array as a parameter, but it was an 8 bit parameter. The caller passed 256, so it became zero, and an assertion failure followed.
I've fixed the parameter size and updated two other places where an 8 bit frame index variable was passed to a 16 bit parameter, for clarity.
This crash started occurring in release 1.6.0 in 2013, so the mystery is how this is the first time it's been reported.

DREAMWEB: Fix index overflow and crash in `deleteExFrame`

---

audio/mididrv.cpp
audio/mididrv.h
audio/musicplugin.h
audio/softsynth/fluidsynth.cpp
audio/softsynth/mt32.cpp
backends/midi/seq.cpp
backends/midi/windows.cpp
engines/dragons/midimusicplayer.cpp

This adds a few things:
- Support for `checkDevice` to FluidSynth, along with a check flag that allows an engine to signal that it will supply a sound font (so dragons engine doesn't fail)
- Quiet mode to `checkDevice`
- Proper device enumeration for OSS
- OSS synth device support

BACKENDS: MIDI: Improvements to automatic device detection, synth support for OSS

---

graphics/macgui/macfontmanager.cpp

Fixes regression introduced in https://github.com/scummvm/scummvm/pull/5658
where on hebrew version of Pink Panther the menu characters are blank

GRAPHICS: MACGUI: Fix blank characters on forced Win95 mode

---

engines/ultima/ultima8/ultima8.cpp

This stops the game from running if a required game data file is missing, such as U8SAVE.000. Fixes bug 12790
This is an alternative fix for that bug than the one proposed in PR #6217

ULTIMA8: Error out if required game resources aren't found on startup

---

engines/hypno/cursors.cpp
engines/hypno/hypno.cpp
engines/hypno/hypno.h

This is my attempt at fixing bug #15347, "HYPNO: Bad performance under Android in menu of Spider Man: Sinister Six".
Since this is apparently caused by the engine reading and decoding a Smacker frame every time the mouse moves, even though the cursor doesn't actually change, I have added a cursor cache to remember the previous decoded frame.
Another approach would have been to not update the cursor unless necessary, but I don't know the engine well enough for that. Since it looks like 2.9.0 may be approaching, I'm submitting this for discussion. But please don't merge it blindly, because it may be the wrong approach! (I also have no way of testing it on Android.)

[RFC] HYPNO: Cache Smacker cursors to address bug #15347

---

engines/scumm/sound.cpp

The background to this pull request is that I was playing the Mac version of The Secret of Monkey Island to see if recent work on the Mac GUI had caused any regressions. I got to the part where you have to follow the shopkeeper. The game is supposed to play a particular piece of music all the way up until you reach the swordmaster. But when I got to the island overhead map, the music stopped and was replaced by the regular overhead map theme.
What happened was that the engine decided to expire the music resource. The script checks if the shopkeeper theme is playing, but one of the conditions there is that the resource has to be loaded. Otherwise it starts the overhead map theme.
I don't think we can rely on the music engine keeping its own copy of the resource data, so checking that the …

SCUMM: Prevent expiration of music while it's playing

---

engines/agi/preagi/preagi.cpp

Fixes newlines in Winnie the Pooh. Tested in DOS, Amiga, and Apple II versions.
To test, start the game and go north until reaching the north pole, then read the sign.
I'm doing this as a PR because I'm new to preagi. This change would only be a problem if one of the other two games used character 13 for something special. (Troll's tale or Mickey's Space Adventure)
@bluegr for reference, you first added the character handling code in: 2182d758d07432d990b0e18beb569d539b901e00
Before:
After:

AGI: PREAGI: Handle carriage return characters

---

engines/agi/preagi/winnie.cpp

When trying to play this game (to test AGI picture code), it would randomly behave unexpectedly. Prompts were repeated, or selections were ignored, or the game would think it was in a different room than the picture on the screen. All of this was inconsistent, but frequent. Then I found a consistent example where an Eeyore menu always repeats: https://bugs.scummvm.org/ticket/15472
The problem is that the game loop attempts to test the return value of the `parser` function against two values ("goto" or "back") but instead it runs `parser` for each comparison. This causes unpredictable behavior depending on which `parser` call you happen to land on, as each call ignores one of the possible return values. With this change, I haven't had any of these problems.

AGI: PREAGI: Fix Winnie the Pooh game loop

---

backends/platform/android/android.mk
dists/android/build.gradle
dists/android/mainAssets.gradle
dists/android/settings.gradle

The AAB is still unique but there are several parts in it.
According to [Google](https://support.google.com/googleplay/android-developer/answer/9859372?hl=en#size_limits), this allows us to get more room for size increases.
In order to test the bundle installation on Android, the AAB file needs to be converted to an APK set.
The Google bundletool software needs to be used.
As we don't provide all architectures in our bundle, a device specification needs to be provided.
One can be obtained from a live device using `get-device-spec` subcommand.
Then, it must be provided to the `build-apks` subcommand using the `--device-spec=` flag.

ANDROID: Split assets in its own pack for AAB

---

backends/platform/android/android.mk
backends/platform/android/fatbundle.mk
configure
dists/android/build.gradle

This bundle contains all architectures.
To build it, a base architecture must be configured and the build process will invoke the make process for all other architectures in different subfolders.
Then, the bundle will be made with all libraries merged in the base build directory.

ANDROID: Add ability to build a fat bundle

---

engines/scumm/macgui/macgui.cpp
engines/scumm/macgui/macgui.h
engines/scumm/macgui/macgui_impl.cpp
engines/scumm/macgui/macgui_impl.h
engines/scumm/macgui/macgui_indy3.cpp
engines/scumm/macgui/macgui_loom.cpp
engines/scumm/macgui/macgui_strings.cpp
engines/scumm/macgui/macgui_v5.cpp
engines/scumm/scumm.cpp

This arose out of https://bugs.scummvm.org/ticket/15482
While there are currently no known unsupported versions, this patch allows the game to still run albeit without the Mac GUI.
It moves the string reading from the constructor into the initialize() method, which now returns true or false. I think that should be safe.
I hope disabling the Mac GUI like this is safe.
There should probably be a nice dialog telling the user what happened. I didn't add that, and it seems pretty close to a release to add new strings to translate.

SCUMM: MACGUI: Fall back on using no Mac GUI for unrecognized versions

---

backends/platform/sdl/win32/win32.cpp
base/commandLine.cpp
common/path.cpp
common/path.h
common/punycode.cpp

Under Win32 paths use colons and dots with a special meaning.
These are puny-encoded and the paths in configuration file are not quite readable anymore.
For such paths, don't puny-encode and return them using the traditional backslash path separator.
I only do it for absolute paths to avoid unplanned consequences with path not absolute (not sure if we have any).
I also fix a `fromConfig` leftover coming from before the introduction of `fromCommandLine`

COMMON: Avoid punycoding paths in configuration for Win32

---

engines/glk/agt/interface.cpp

This was caught by the OSX PPC build, where `-funsigned-char` is the default:
```
warning: comparison is always true due to limited range of data type [-Wtype-limits]
} else if (*s >= 0 && *s <= 9) linebuff[lp++] = ' ';
^
```
but I think this warning is just a happy accident; and that instead of showing a type limit problem, it showed a part of the code which probably intended to check for the digits '0' to '9', and not the 10 first characters of the ASCII table?
Still, I'm asking @dreammaster to double check this, since I'm not sure about the intent of this code. But it appears to be likely :)

GLK: AGT: Fix unintended comparison for digits in debugout()

---

engines/ags/engine/gui/my_listbox.cpp
engines/ags/engine/gui/my_textbox.cpp
engines/ags/engine/script/cc_instance.cpp
engines/ags/shared/core/types.h

It's illegal to reference an inactive member of a union and the types are not layout compatible (and even not of the same size). Instead, store every value in a integer of pointer size and cast pointers to and from it.
This should really fix bug [#13557](https://bugs.scummvm.org/ticket/13557).

AGS: Make NumberPtr a class instead of a union

---

backends/imgui/imgui.cpp
backends/imgui/imgui_demo.cpp
backends/imgui/imgui_draw.cpp

```
imgui_draw.cpp:3730: warning: cast from type 'const ImFontGlyph*' to type 'void*' casts away qualifiers [-Wcast-qual] imgui_draw.cpp: In member function 'void ImFont::SetGlyphVisible(ImWchar, bool)': imgui_draw.cpp:3730:44: warning: cast from type 'const ImFontGlyph*' to type 'void*' casts away qualifiers [-Wcast-qual]
3730 |     if (ImFontGlyph* glyph = (ImFontGlyph*)(void*)FindGlyph((ImWchar)c))
|                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

IMGUI: Fix some GCC const-related warnings

---

engines/scumm/scumm.cpp

Following 381fc1fc44 (SCUMM: Fix Duplicate Branches GCC Compiler Warning), some of the conditions can be omitted.

SCUMM: Simplify width and height initialization

---

backends/platform/3ds/osystem-graphics.cpp

`shader_shbin` has the type `const u8 *`, while the first parameter of `DVLB_ParseFile` is of the non-const type `u32 *`. The compiler throws up a "casts away qualifiers" warning when casting directly from `const u8 *` to `u32 *`. Casting away the constness of `shader_shbin` with a `const_cast` before casting it to `u32 *` silences the warning.

BACKENDS: 3DS: Silence "casts away qualifiers" warning.

---

engines/scumm/players/player_nes.cpp

```
player_nes.cpp:130: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'class Scumm::APUe::Square'; use assignment or value-initialization instead [-Wclass-memaccess] player_nes.cpp: In member function 'void Scumm::APUe::Square::Reset()': player_nes.cpp:130:15: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'class Scumm::APUe::Square'; use assignment or value-initialization instead [-Wclass-memaccess]
130 |         memset(this, 0, sizeof(*this));
|         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
player_nes.cpp:104:7: note: 'class Scumm::APUe::Square' declared here
104 | class Square : public SoundGen {
|       ^~~~~~
```

SCUMM: Avoid memset for initializing non-trivial types

---

engines/tinsel/background.cpp
engines/tinsel/cliprect.cpp
engines/tinsel/cliprect.h
engines/tinsel/module.mk
engines/tinsel/movers.cpp
engines/tinsel/movers.h
engines/tinsel/noir/spriter.cpp
engines/tinsel/noir/spriter.h
engines/tinsel/object.h
engines/tinsel/pcode.cpp
engines/tinsel/scene.cpp
engines/tinsel/tinlib.cpp
engines/tinsel/tinsel.cpp
engines/tinsel/tinsel.h

These patches add basic 3D rendering of the main character model, the only model in Discworld Noir.
The character model loads and renders successfully in the first scene, but there is no movement or animation, which requires additional reverse-engineering of the ground plane and the movers.
For 3D rendering, I used TinyGL because the Tinsel engine can draw the 3D model in the middle of the drawing of the other game objects, which might even be transparent. There is no easy way to use OpenGL directly due to this. 
These changes are limited to Discworld Noir. I tested the changes with Discworld 1 & 2, and they work as before.
I had these patches in my fork for some time and cleaned them up. It would be nice to get some eyes on them.

Tinsel: Basic 3D rendering of the main character for Discworld Noir.

---

engines/engine.cpp

This resolves a set of TODOs for 3D games. Opening it as a PR, for any possible side-effects (although, I haven't spotted any, at a first glance, running an assortment of 2D and 3D games with this change).
Now, when the launcher is in full screen, the game will also be in full screen. However, when returning to the launcher, graphics are reset to default with a setupGraphics() call. Thus, if the user hasn't selected full screen display in the options, but only used alt-enter to change the launcher to full screen, the launcher will return to window mode.
~~initCommonGFX() also applies the following to 3D games:~~
~~- Filtering mode~~
~~- Sets the scaler~~
~~- Sets the shader~~
**Update:** Changed `initCommonGFX()` to behave like the current code, after talking with @aquadran. Thus, this PR …

ENGINES: Use common GFX code for 3D games - fixes part of bug #14342

---

engines/scumm/macgui/macgui.cpp
engines/scumm/macgui/macgui.h
engines/scumm/macgui/macgui_dialogwindow.cpp
engines/scumm/macgui/macgui_impl.cpp
engines/scumm/macgui/macgui_impl.h
engines/scumm/palette.cpp
graphics/macgui/macwindowmanager.cpp

This is an attempt at fixing https://bugs.scummvm.org/ticket/15492 but since even my aging computer doesn't see any slowdowns it's hard for me to say if it does.
But assuming that the problem is in the frequent palette updates...
Currently, every palette change in the game gets passed on to the Mac Window Manager, which triggers a bunch of color lookups, and possibly some redrawing as well, which I suppose could be slow. It was fine for the early games, including Monkey Island 1, where palette changes are rare. But later games use a lot of palette animations, so there it can happen at least a couple of times per second.
Now the change palette is only passed to the Mac Window Manager when it's about to draw either a menu or a dialog (since those can be triggered outside of the menu). I had …

SCUMM: MACGUI: Optimize Mac palette handling (bug #15492)

---

backends/graphics/sdl/sdl-graphics.cpp

Normally when using the OpenGL mode the window is not resized when starting a game, unless the game requires a window bigger than the current window size. However this was not the case if the engine called `initSizeHint()` with sizes smaller than the current window size, as in this case the window was forcibly resized to the bigger of those provided sizes.
This can be seen for example with the Goblins games or Dreamweb. When using OpenGL graphics mode with scaler of 1x, and starting Gobliiins the window is resized to 320x240 (or 320x200 with AR correction). For Dreamweb it is resized to 640x480. This does not happen with engines that do not call `initSizeHint()` (which means it only happens with engines that have games that use multiple resolutions).
The initSizeHint() function was added …

BACKENDS: SDL: Never make window smaller in OpenGL mode when starting a game

---

base/plugins.cpp

The dynamic plugin for detection contains multiple static plugins for each engine, so if the dynamic plugin is deleted first there will be a crash when unloading the static plugins because the code is no longer available/executable.
Fixes [Trac #15517](https://bugs.scummvm.org/ticket/15517). Thanks to @BallM4788 for help with debugging.

BASE: Fix a crash on exit when the detection plugin is loaded

---

backends/platform/3ds/allocHeapsOverride.cpp
backends/platform/3ds/main.cpp
backends/platform/3ds/module.mk

The New 3DS requires more linear memory to launch the app than the Old 3DS does; this was causing the 3DS port to instantly crash on New 3DS models. 
This commit fixes that while allowing for future functionality coming soon(TM).

BACKENDS: 3DS: Fix instant crash on "New 3DS" systems

---

engines/mtropolis/metaengine.cpp

Without this, mTropolis games are unplayable on platforms that use a controller.
It would be nice to have actions for relevant keyboard keys as well, but I haven't investigated which ones are useful for any of the supported games.

MTROPOLIS: Add mouse button actions to the keymap

---

engines/vcruise/metaengine.cpp
engines/vcruise/runtime.cpp
engines/vcruise/runtime.h
engines/vcruise/vcruise.cpp

Without this, V-Cruise games are unplayable on platforms that use a controller.

VCRUISE: Add mouse button and escape actions to the keymap

---

engines/m4/mem/mem.cpp

This hasn't been tested, but should work correctly on both 32-bit and 64-bit systems.

M4: Fix the memory stash code on big endian

---

engines/adl/adl.cpp
engines/adl/adl.h
engines/adl/adl_v2.cpp
engines/adl/adl_v4.cpp
engines/adl/detection.cpp
engines/adl/hires1.cpp
engines/adl/hires5.cpp

This is a set of fixes for the ADL engine, by @waltervn
This addresses the following bugs:
- Bug #[15379](https://bugs.scummvm.org/ticket/15379) - HIRES5: Game unsolvable after loading savegame. Save state not properly restored?
- Bug #[15389](https://bugs.scummvm.org/ticket/15389) - HIRES5: "GET ALL" fails where picking up individual objects doesn't
- Bug #[15382](https://bugs.scummvm.org/ticket/15382) - HIRES5: Crash printing an apparently corrupt string
- Bug #[15301](https://bugs.scummvm.org/ticket/15301) - Mystery House: Barely seen title screen
Creating a PR for review

ADL engine fixes

---

configure
devtools/create_project/cmake.cpp
devtools/create_project/create_project.cpp
engines/freescape/configure.engine
engines/grim/configure.engine
engines/hpl1/configure.engine
engines/myst3/configure.engine
engines/playground3d/configure.engine
engines/stark/configure.engine
engines/tetraedge/configure.engine
engines/twp/configure.engine
engines/watchmaker/configure.engine
engines/wintermute/configure.engine

This allows to blacklist 3D engines on platforms not supporting 3D.
These platforms don't have OpenGL nor TinyGL enabled.

CONFIGURE: Add a 3D feature

---

engines/dreamweb/print.cpp

In the French version of the game, right at the start (in the first scene) there was a crash when moving the mouse around the screen due to an out of bound read with a string of length 1 (empty, with only the '\0' character) in the `DreamWebEngine::printDirect` function. This commit moves reading the next character to after checking that that the character is not '\0' to avoid this out of bound read.
This fixes [bug #15546](https://bugs.scummvm.org/ticket/15546).

DREAMWEB: Avoid out of bound read with empty strings in printDirect

---

engines/scumm/script_v5.cpp

Here's something I just tried for the fun of it, and thought I'd submit for evaluation. I noticed some time ago that the boat wreck in the foreground at the beginning of Monkey Island 2 has been removed in the Macintosh version:
It's possible that this was done for performance reasons. There is parallax scrolling going on here, and it was also remover from the Amiga version. I don't know how low-end color Macs compared to the Amiga, though. This pull request restores the missing graphics as "Restored content":
Apparently everything is still there in the resource files: The graphics and the scroll script. It just needs to be set up from the room's entry script. (At this point, we should probably define constants for the script numbers of entry/exit scripts, but that's outside the scope of …

SCUMM: Optionally restore boat wreck graphics at beginning of Mac MI2

---

configure

Some Linux distributions (Fedora, Gentoo…) are using LTO builds more and more. The following `configure` change comes [from Fedora](https://src.fedoraproject.org/rpms/scummvm-tools/blob/rawhide/f/configure.patch), which hit an issue with our endianness check when they build with LTO.
We already have the first part (explicit `__attribute__ ((used))` so that the compiler doesn't remove the objects we search later on with `strings`), but not the second part, that is [`-ffat-lto-objects`](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-ffat-lto-objects). It forces the compiler to produce both machine code and intermediate representation objects in the resulting file. Otherwise (as far as I understand), in some cases you could end up with the IR part alone, and/or a `strings` …

CONFIGURE: Add -ffat-lto-objects to the endianness check for LTO builds

---

backends/platform/sdl/macosx/macosx.cpp
backends/platform/sdl/macosx/macosx_wrapper.h
backends/platform/sdl/macosx/macosx_wrapper.mm
backends/saves/posix/posix-saves.cpp
dists/macosx/Info.plist
dists/macosx/Info.plist.in
doc/cz/PrectiMe
doc/de/LIESMICH
doc/docportal/use_scummvm/save_load_games.rst
doc/se/LasMig

The default savepath on macOS used to be in the user Document folder. However ScummVM requires special permission to access that folder, and if the user denied it, this caused various issues. This implement [ticket #11428](https://bugs.scummvm.org/ticket/11428).
The change should not be controversial. But I am interested in getting feedback on the migration method I implemented in `OSystem_MacOSX::initBackend()`. The idea I had was to:
- Have a `macos_savepath_migrated` setting in the config file that indicate it has been migrated.
- If the setting is not yet set, we set it. And if the config has games (i.e. it is an old config file), and if the savepath setting is not set (i.e. the default is used) then it explicitly set it to the old default.
That means that for existing users it will …

MACOS: Change default savepath to use the Application Support folder

---

engines/qdengine/qdcore/util/splash_screen.cpp

The stack is very small with the 3DS port, so creating the `PEResources` object on the stack causes it to crash.

QDENGINE: Avoid stack overflow with the 3DS port

---

backends/fs/stdiostream.cpp
common/path.cpp

After some tests, this patch seems to work to avoid puny-encode in cases like `/HostFS::HostFS.$/ScummVM/SC_DEMO` and `/<ScummVM$Dir>/SC_DEMO`.

RISCOS: Don't encode path when it's not needed

---

engines/composer/composer.cpp

This is a regression from commit bbc4d51.
This was reported in the forum in the call for testing thread: https://forums.scummvm.org/viewtopic.php?p=100132#p100132
This can for example be reproduced with the Windows demo of Baba Yaga from https://downloads.scummvm.org/frs/demos/composer/
The issue was simple. The old correct code (before the regression) did something like this:
```
filename = mangleFilename(filename)
init _bookGroup from filename
```
With the commit above this was changed to:
```
path = mangleFilename(filename)
init _bookGroup from filename
```
Because the result of `mangleFilename` was assigned to a different variable, the `_bookGroup` ended up being initialised from the old `filename` (without mangling).

COMPOSER: Fix error when starting games

---

engines/nancy/action/puzzle/rippedletterpuzzle.cpp

If a piece is swapped with another piece, the LastPos is forgotten too soon; after viewing an inventory item with the new piece in hand, that piece can't be put down.
```
scummvm: ./common/array.h:274: T& Common::Array<T>::operator[](size_type) [with T = signed char; size_type = unsigned int]: Assertion `idx < _size' failed.
```
AFAICT, does not affect nancy2 (in ScummVM 2.9) which has no viewable inventory items (and which re-initializes the puzzle on loading save game).
For @fracturehill's review

NANCY: Fixup RippedLetterPuzzle fix

---

engines/bladerunner/savefile.cpp

Graphics::loadThumbnail will overwrite it and it creates a memory leak.

BLADERUNNER: Don't allocate the thumbnail before needing it

---

engines/qdengine/qdcore/qd_animation.cpp
engines/qdengine/qdcore/qd_font_info.cpp
engines/qdengine/qdcore/qd_sprite.cpp
engines/qdengine/qdcore/util/plaympp_api.cpp
engines/qdengine/qdcore/util/plaympp_api.h
engines/qdengine/system/sound/wav_sound.cpp

There are still crashes due to running out of memory when testing on RISC OS, but I don't know if that means there are more memory leaks or if it's just a side effect of the `ZipArchive` class decompressing entire files in one go even when the files are quite large.

QDENGINE: Fix memory leaks when reading files

---

common/translation.cpp
common/translation.h

All of the strings for the selected language are loaded up-front, so between the increased size of each character and the lack of room in internal storage for `U32String`s, using `U32String` results in more than a 4x increase in memory usage compared to using `String` and converting from UTF-8 on demand.

COMMON: Reduce the amount of memory needed by translations

---

engines/bladerunner/slice_animations.cpp
engines/bladerunner/slice_animations.h
engines/bladerunner/slice_renderer.cpp
engines/bladerunner/vqa_decoder.cpp
engines/bladerunner/vqa_decoder.h
engines/bladerunner/vqa_player.cpp

This is the result of my investigation on the bugs [#11376](https://bugs.scummvm.org/ticket/11376) and [#13660](https://bugs.scummvm.org/ticket/13660).
After some debugging, it appears that these bugs occur because of an OOM situation.
When using new, the failed allocation triggers a brutal abort without any information.
When using malloc, nullptr is returned but it doesn't seem to trigger a fault on the Wii to dereference it.
This causes random errors and assertion faults.
As I ran the engine using ASan on Linux using a 16bpp pixel format, it also uncovered two other bugs.
First commit avoids to read out of bound in 16bpp surfaces.
The second commit plugs a leak in overlays, when Overlays::play is called twice for the same loaded video.
In this case, the VQAPlayer::open function is …

BLADERUNNER: Fix various leaks

---

backends/graphics/sdl/sdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.h
engines/director/director.cpp
engines/qdengine/qdengine.cpp
engines/twine/twine.cpp
engines/twp/twp.cpp

This segfault happens when discarding the engine with plugins.
Without this, the cleanup function is called too late (after the engine class is destroyed) and the code may not be present anymore.
Let's wait for build to finish before merging: I didn't build all the engines, only Twine, which works flawlessly under ASan.
EDIT: I thought about resetting the callbacks directly in Engine::~Engine() but it could make calls to code inside the subclass while it has just been destroyed. So I put the call directly in the run() function of every engine.

Fix ImGui related segfault

---

engines/sci/engine/kernel.cpp

I had issues to run any SCI1 game with MSVC ASan builds. Debug and release builds worked though. The ASan builds always failed to start up with a 'DoSoundMasterVolume: no previous signatures' error. When I recently had that issue (which I quickly discussed with digitall on discord) I got it fixed by simply doing a full rebuild. But now it failed again and couldn't be repaired like that. So I looked into it deeper. And I find it quite surprising that it usually works in 99,9% of all cases, since it does a comparison of two pointers that are meant to point to different strings. In the kDoSound_subops table, each entry gets its own string. My only explanation is that these string repetitions get optimized away (but apparently not or not always for the MSVC ASan build). I have replaced it …

SCI: fix kernel sub function mapping for certain builds

---

engines/scumm/he/resource_he.cpp

CachedCursor->bitmap and palette are allocated via new[] in ::extractResource.
```
ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs free) on 0x619000348080
#0 0x7fea95eb76a8 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:52
#1 0x55d6c546b996 in Scumm::ResExtractor::~ResExtractor() engines/scumm/he/resource_he.cpp:52
[...]
0x619000348080 is located 0 bytes inside of 1024-byte region [0x619000348080,0x619000348480)
allocated by thread T0 here:
#0 0x7fea95eb9628 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:98
#1 0x55d6c546ce70 in Scumm::Win32ResExtractor::extractResource(int, Scumm::ResExtractor::CachedCursor*) engines/scumm/he/resource_he.cpp:140
[...]
```

SCUMM: HE: Fix alloc-dealloc mismatch in ResExtractor

---

engines/sci/engine/kgraphics.cpp
engines/sci/graphics/paint16.cpp
engines/sci/graphics/paint16.h
engines/sci/graphics/screen.cpp
engines/sci/graphics/screen.h

This should fix issues 1- 3 from bug ticket no. 15594.
I have added redrawing functionality for the hires gfx from the original interpreter. I guess the original only needed that code to handle WM_PAINT messages (= full window redraw). It also does actually call a redraw in kDisposeWindow, the same way I implemented it here, to refresh the inventory. But that is only needed for the speech+text mode which isn't supported in the original. Maybe they ditched the mode only after they had already implemened that, who knows...
I have also improved the workaround for the out-of-bounds portraits to catch the case from the bug ticket.

SCI: (KQ6WinCD) - fix hires drawing glitches

---

engines/agi/agi.h
engines/agi/detection.cpp
engines/agi/picture.cpp
engines/agi/picture.h
engines/agi/preagi/mickey.cpp
engines/agi/preagi/winnie.cpp

This PR fixes picture inaccuracies and bugs in Winnie the Pooh and Mickey's Space Adventure:
- Circles not being drawn correctly
- Coordinates not being clipped
- Flood fills not being drawn
- Flood fills escaping due to the other bugs
- Frequent memory corruption
- https://bugs.scummvm.org/ticket/5730 (14 years old)
- https://bugs.scummvm.org/ticket/14549
Some of these bugs were TODOs in TrollVM (2004). Some were regressions from TrollVM being merged in 2007. Some were regressions from a 2016 refactor.
This is part of an ongoing effort to get our AGI picture code under control so that we can keep building on it. Right now it's tricky: some code is from Sarien, some code is from NAGI, some code is from TrollVM, some code has never executed and never will, much has been lost in …

AGI: Fix PREAGI pictures

---

common/stream.cpp
graphics/fonts/ttf.cpp

The [FreeType API Reference](https://freetype.org/freetype2/docs/reference/ft2-system_interface.html#ft_stream_iofunc) explains that a FT_Stream_IoFunc such as our `TTFLibrary::readCallback` should simply perform a seek if `count` is 0 and return a status.
In that case, `buffer` can be nullptr; previously, that was passed to a stream's read(), which in turn gave it to memcpy(). Some argue that memcpy(null, ..., 0) is acceptable, but it's undeniably undefined behaviour.
This PR includes a commit which checks nullptr in `MemoryReadStream::read`. I guess that ought never to be the case, so it may be dropped, but it has happened:
```
common/stream.cpp:119:8: runtime error: null pointer passed as argument 1, which is declared to never be null
#0  Common::MemoryReadStream::read …
```

GRAPHICS: Handle seek-only case in TTFLibrary readCallback

---

engines/sci/detection_internal.cpp
engines/sci/graphics/gfxdrivers.cpp
engines/sci/graphics/gfxdrivers.h
engines/sci/graphics/maciconbar.cpp
engines/sci/graphics/paint16.cpp
engines/sci/graphics/picture.cpp
engines/sci/graphics/screen.cpp
engines/sci/graphics/text16.cpp
engines/sci/graphics/video32.h
engines/sci/sci.cpp

SQ4/CD/Windows uses a similar interpreter to the KQ6 one, minus the hires graphics support. It has the same upscaling to 640x440 (or 320x220 for small windows) and also supports the same 16 colors mode.
I have attached the SQ4 Windows version to the gfx drivers I made for KQ6. The 16 colors mode now requires the SCIWV.EXE executable, though. I had hard coded the 512 bytes color pattern table for KQ6, since I thought it would remain the only one necessary. But SQ4 has a different table. So I now load them from the executable.
There might be more Windows games like that, I just currently don't know about it (probably other SCI_VERSION_1_1 titles). Adding support would be super easy. But it will not work right out of the box, since I explicitly check the game IDs in customizeGuiOptions(), to …

SCI: (SQ4/CD/Windows) - make use of windows gfx drivers

---

backends/platform/psp/png_loader.cpp
backends/platform/psp/png_loader.h
configure

This PR allows to revert back the -O1 flag switch.
It also improves the decoding by avoiding rewinding the stream.

PSP: Fix PNG loading and improve it

---

engines/ultima/nuvie/keybinding/keys.cpp
engines/ultima/nuvie/metaengine.cpp

Ultima:Nuvie Keymap Fixes
-Change keymap modifier from Win to Alt or Ctrl
-Fix shift not being recognized as a modifier
-Allow TELEPORT_TO_CURSOR to repeat
metaengine.cpp: The current key defaults show up as the Windows key which doesn't seem to work. I reverted them back to the Nuvie default of Alt except where Alt was used with the function keys (example Alt-F4). Allow TELEPORT_TO_CURSOR to repeat again.
keys.cpp: The Shift modifier is currently detected as an incorrect input so that is fixed.
I'm not sure how many commits you would normally break this into.
Edit: is there any documentation of Nuvie in scummvm?
Edit: changed added Ctrl modifiers to Shift instead to avoid conflict with main scummvm  keymaps

Ultima:Nuvie Keymap Fixes

---

gui/launcher.cpp
gui/launcher.h
gui/widgets/grid.cpp
gui/widgets/grid.h

In the List Launcher, the Load button was disabled for engines that do not support loading from the launcher, but was otherwise always enabled. With this pull request it is also disabled if no savegame exists for the selected game.
In the Grid Launcher, the Load button in the tray was always enabled. This pull requests adds the same check as for the List Launcher to only enable the Load button if supported by the engine and if savegames are available.

Disable load button in Launcher when no savegame is available for the selected game

---

gui/console.cpp
gui/console.h

`_selEnd` could become negative, so the console buffer could be accessed out of bounds.
Dragging outside the console text area resulted in a slightly strange start and/or end selection anchor.
Edit: I wrote before that there was significant increase in CPU usage while dragging beyond top or bottom of console. That was measured wrongly; it's a really minor difference, sorry. Even so, let's avoid the useless computations.
With ASan, try clicking near coordinate (0,0) in the console (within the margin--the black area), or dragging from anywhere out the top-left corner of the window.
The "Improve selection behaviour" commit was tough to explain; here are quick clips demonstrating.
|before|after|
|-|-|
|<video src=https://github.com/user-attachments/assets/cfbcb081-6d66-4967-b348-e68384aa121e>| …

GUI: Improve console selection

---

engines/director/lingo/lingo-patcher.cpp

Pink Gear Collection (Windows) has a check to see if it's running off the CD by checking if `PINKPINK.TXT` is the first file in `{exe path}\PG_WORLD\PINKCD`, and if it is then tells the user to move the EXE. Later it checks each drive to see if `PINKPINK.TXT` is the first file in `{drive}:\PG_WORLD\PINKCD`, and if it isn't then tells the user to insert the disc. Bypassing this check lets the game get to at least the title screen.
The Macintosh version merely checks to see if `PINKPINK` is in `the pathName`. Since ScummVM has `the pathName` be just `:`, this check is bypassed without any patches needed.

DIRECTOR: Add CD detection patch for Pink Gear Collection

---

backends/platform/sdl/macosx/macosx-touchbar.mm

They do not support it and it fails on invalidateIntrinsicContentSize.

BACKENDS: MACOS: Don't instantiate touch bar on old MacOS versions

---

backends/platform/ios7/ios7_osys_main.cpp
backends/platform/ios7/ios7_video.mm

More nice features was enabled for OpenGL ES 3.0 (commited in https://github.com/scummvm/scummvm/commit/255562991ce4d514cf3629ba4618db8ed1bfd9b5)
Many of the newer iOS devices supports OpenGL ES 3.0. Fallback to OpenGL ES 2.0 if not available.
This also enables more shaders in the iOS port which was requested by users.
Also, log to console when debugger is attached.

IOS7: Various fixes

---

audio/softsynth/mt32/module.mk

When configuration flags are changed (ASan enabling for example), force rebuild the MT32 objects.
They were not rebuild because not depending on config.h
I prefer to submit this as a PR because it's a bit hackish and if someone has a better idea, I take it.

AUDIO: MT32: Force MT32 rebuild after configure is run

---

backends/platform/libretro/src/libretro-graphics-surface.cpp
engines/hdb/gfx.cpp
engines/mtropolis/elements.cpp
engines/nancy/graphics.cpp
engines/sherlock/fonts.cpp
engines/sherlock/scalpel/3do/scalpel_3do_screen.cpp
engines/sherlock/scalpel/3do/scalpel_3do_screen.h
engines/sherlock/scalpel/scalpel.cpp
engines/sherlock/surface.cpp
engines/sherlock/surface.h
engines/sherlock/tattoo/tattoo_map.cpp
engines/sherlock/tattoo/tattoo_scene.cpp
engines/twine/movies.cpp
engines/twine/renderer/screens.cpp
graphics/managed_surface.cpp
graphics/managed_surface.h

The Sherlock engine was the only user of this feature, and it was only implemented for paletted surfaces. Removing it allows the ManagedSurface blitting code to be simplified a bit.

GRAPHICS: Remove overrideColor from ManagedSurface::transBlitFrom

---

engines/scumm/sound.cpp
engines/scumm/soundse.cpp

Based on the amazing work on https://github.com/scummvm/scummvm/pull/6313
This keeps the given offset when starting the talk sound,
seems to fix the offset issue when playing remastered speech sounds
the sfx sounds also seem correct

SCUMM: Fix DOTT Remastered offsets

---

engines/scumm/imuse/drivers/macintosh.cpp
engines/scumm/macgui/macgui_dialogwindow.cpp
engines/scumm/macgui/macgui_impl.cpp
engines/scumm/macgui/macgui_impl.h
engines/scumm/macgui/macgui_indy3.cpp
engines/scumm/macgui/macgui_indy3.h
engines/scumm/macgui/macgui_loom.cpp
engines/scumm/macgui/macgui_strings.cpp
engines/scumm/macgui/macgui_v5.cpp
engines/scumm/macgui/macgui_v5.h
engines/scumm/macgui/macgui_v6.cpp
engines/scumm/macgui/macgui_v6.h
engines/scumm/macgui/macgui_widgets.cpp
engines/scumm/scumm.cpp
engines/scumm/scumm.h
engines/scumm/scumm_v7.h
engines/scumm/smush/smush_player.cpp
graphics/macgui/macwindowmanager.cpp
graphics/macgui/macwindowmanager.h
image/cicn.cpp
image/cicn.h
image/image_decoder.h

This is work in progress, but I don't know how much more time I will have before Christmas.
The goal is to implement the Mac GUI for the remaining V6 and V7 games, and Maniac Mansion. Here is the current status:
About screens have been implemented:
The demos have less fancy dialogs. Currently the sizes of the dialogs (but not the contents) are hard-coded. The demos on our downloads page are broken, but the ones I've been able to track down are at least temporarily available from https://drive.google.com/drive/folders/19quZK2R9A067El36tcG41dZSP0CnHEbv
Options dialogs have been implemented. There are some minor color differences, but the layout should be pixel perfect for all five dialogs. Settings are saved and applied, though this needs testing.
I think all of the menu items have been …

SCUMM: Implement Macintosh GUI for the remaining SCUMM games

---

engines/agi/module.mk
engines/agi/picture.cpp
engines/agi/picture.h
engines/agi/picture_gal.cpp
engines/agi/picture_gal.h
engines/agi/preagi/mickey.cpp
engines/agi/preagi/mickey.h
engines/agi/preagi/picture_mickey_winnie.cpp
engines/agi/preagi/picture_mickey_winnie.h
engines/agi/preagi/picture_troll.cpp
engines/agi/preagi/picture_troll.h
engines/agi/preagi/preagi.cpp
engines/agi/preagi/preagi.h
engines/agi/preagi/troll.cpp
engines/agi/preagi/troll.h
engines/agi/preagi/winnie.cpp
engines/agi/preagi/winnie.h

This PR:
- Creates `PictureMgr` subclasses to separate PreAGI code from AGI
- Implements KQ1-Early picture support in a new `PictureMgr` subclass
- Implements Troll Tale's custom flood fill, fixing the Troll
- Documents `PictureMgr` and friends
At some point this was about adding Apple II picture cropping. Detours were made.
While testing, I saw that the Troll from Troll's Tale was missing flood fills in some rooms, so that got reversed and bundled in. It was a good test of the new structure.
To my knowledge, this is the first public implementation of the "Game Adaptation Langage" picture format from early KQ1. I reverse engineered it last month and developed the renderer in my tools, so porting it over was another good test. Although this KQ1 code isn't directly usable (yet??) I patched …

AGI: Refactor `PictureMgr`, support early KQ1 pics, fix Troll fill

---

graphics/managed_surface.cpp
graphics/managed_surface.h

This is split out from PR #6377.

GRAPHICS: Add simplified mask blitting routines to ManagedSurface

---

graphics/macgui/macmenu.cpp
graphics/managed_surface.h
graphics/primitives.cpp
graphics/primitives.h
graphics/surface.cpp
graphics/surface.h

This allows more functions to be overridden for improved performance - providing replacements for functions like `drawHLine` allows for simplified clipping, fewer calls to function pointers/virtual functions and calling optimised routines like `memset` instead of writing individual pixels.

GRAPHICS: Convert the primitives code to use classes

---

engines/mediastation/assets/movie.cpp
engines/mediastation/assets/sprite.cpp
engines/mediastation/bitmap.cpp

This should be straight forward since the engine exclusively uses paletted surfaces and doesn't seem to need scaling or palette remapping, but I haven't been able to test it.

MEDIASTATION: Make use of simpleBlitFrom

---

backends/platform/libretro/src/libretro-graphics-surface.cpp
engines/mtropolis/hacks.cpp
engines/twine/movies.cpp
engines/twine/renderer/screens.cpp
graphics/managed_surface.cpp
graphics/managed_surface.h

A new set of functions has been added in its place that wraps around the shared mask code. It should be sufficient to cover the one place that uses it, but I'm not able to test it. Some modifications have been made to the TwinE engine as well, which used the `maskOnly` parameter without actually having a mask, which I think is just to disable the colour key, but those changes are untested as well.

GRAPHICS: Remove masks from ManagedSurface::transBlitFrom

---

graphics/macgui/macmenu.cpp

On a real Macintosh, you can disable entire menus. They will show up as grayed out in the menu bar, everything in them will be grayed out, and you cannot open submenus. As seen in this screenshot from an emulator:
This is an initial attempt at implementing this in ScummVM. What I have so far:
- Disabled menus are rendered as grayed out in the menu bar.
- Keyboard shortcuts are not available for disabled menus.
- Disabled submenus now still get their (grayed out) submenu arrow glyph.
- Unlike top-level menus, disabled submenus do not open.
I'm definitely going to need help with testing it, because it's easy to miss things. (I almost missed the keyboard shortcuts.)
Here is a preview of what I intend to use it for. In v6 and v7 games, the Edit menu is disabled. (In earlier games, it's not.) …

GRAPHICS: MACGUI: Make it possible to disable menus

---

backends/platform/android/portdefs.h

Android libc (Bionic) had a bug in their memchr function where the needle wasn't considered as an unsigned char for Android below 6.0 except for aarch64 where the implementation was in assembly and behaves correctly.
This means that on every impacted platform, passing a needle made of a char >= 0x80 makes memchr never find a match because the value is signed extended.
Make sure we avoid this case by forcing a cast to unsigned char before passing an int.
Once merged, it will have to be backported to 2.9 branch.

BACKENDS: ANDROID: Fix memchr calls

---

engines/neverhood/modules/module2200.cpp

I've run into this several times before, as I'm used to solving this puzzle quickly. The problem is that clicking on the last cube to make the solution _before_ the previous cube has finished moving will cause the winning condition to run twice. Nothing game-breaking, but the "puzzle solved" sound is repeated! I've added an extra check to prevent this.
[Here](https://github.com/user-attachments/files/18396456/neverhood.zip) is a save file for testing (the puzzle is 2 steps away from being solved).
P.S. not sure if this is present in the original exe (unable to test right now), but even if it does, I don't think it should be kept as it's clearly a bug.

NEVERHOOD: Fix "puzzle solved" sound sometimes being played twice in the H room

---

engines/ags/engine/media/audio/sound_clip.cpp

Calculate new sample rate based on new_speed and apply to mixer channel.
Not sure how many games use that (I suspect not many). "Cheetahs Are Meant To Be Fast" uses it to slow down the background music and create an eerie atmosphere at the end of the game.

AGS: Implement SoundClipWaveBase::set_speed

---

engines/scumm/dialogs.cpp
engines/scumm/dialogs.h
engines/scumm/macgui/macgui_impl.cpp
engines/scumm/macgui/macgui_v6.cpp
engines/scumm/metaengine.cpp
engines/scumm/palette.cpp
engines/scumm/scumm.cpp
engines/scumm/scumm.h
engines/scumm/smush/smush_player.cpp

This adds a checkbox to the options dialog for the Macintosh games that use gamma correction. I haven't had the time to test it much (I haven't looked at what it does to the Humongous Entertainment games at all), but what I've tried seems to work.

SCUMM: Add option for gamma correction (for the Macintosh games)

---

common/rect.h
engines/vcruise/menu.cpp
engines/vcruise/menu.h
engines/vcruise/runtime.cpp
engines/vcruise/runtime.h
engines/vcruise/runtime_scriptexec.cpp
engines/vcruise/vcruise.cpp

This helps a bit with performance when running AD 2044 on the 3DS, since the code paths are simpler and it's no longer necessary to use a different true colour format to the screen in order to store transparency information. It doesn't completely fix the playback issues, but I suspect it might be an issue with the playback logic rather than just a performance issue since I've encountered cases where video playback never ends and the engine stops polling for events.
I haven't tested Reah or Schizm, but both of them should work assuming that none of the bitmaps require alpha blending, that scaling isn't needed, and that UI bitmaps 10 and 17 (and the screen) are true colour rather than paletted.
[Trac #14870](https://bugs.scummvm.org/ticket/14870) looks like it may be related.

VCRUISE: Make use of simpleBlitFrom and maskBlitFrom

---

engines/director/lingo/xlibs/spacemgr.cpp

The SpaceMgr objects (especially SpaceCollection) are pretty huge (over 1MB size) because they are made of HashMap which contain their object pool.
These objects should have never been allocated on stack.
As the nodes are not existing, make sure they are allocated directly on the heap using the getOrCreateVal call.
When needed, the result is recycled to avoid an extra lookup.

DIRECTOR: Don't allocate big objects in stack in SpaceMgr

---

configure
engines/bagel/baglib/save_game_file.cpp
engines/tony/window.h
engines/twp/vm.cpp

Following the (hard to debug) crash we got on Android due to a stack overflow, I think it could be good to be warned when the functions allocate too much memory on the stack.
In order to not start a huge witch hunt, I propose to begin with an arbitrary value of 300KB (which is a 640x480@8 buffer) and maybe lower this value in the future if there is a need.
This allowed me to detect 3 cases of huge allocations which are fixed in this PR.
For TWP, the buffer size is shrunk as I believe it was generously allocated.
For the other cases, I allocate on the heap the buffer instead.
This would have warned us for the Director case I fixed earlier.
The warning flag is supported since the dawn of time in GCC but on Clang it's more recent (though I could not identify the exact version).

CONFIGURE: Warn if the stack frames are too large

---

engines/director/cast.cpp
engines/director/frame.cpp

When debugging the Dark Eye crash on Android I met these two errors in ASan and UBSan.
First, an out of bound read in transformColor because the color read is added 0x80 but (as the tranformColor argument type is uint32) overflows the engine current palette.
Then, the checksum calculation raises an undefined behaviour error because the constant used for the multiplication was too big.

DIRECTOR: Fix UBsan and ASan warnings

---

engines/petka/interfaces/save_load.cpp
engines/petka/petka.cpp
engines/wintermute/base/font/base_font_truetype.cpp
engines/zvision/text/truetype_font.cpp
engines/zvision/text/truetype_font.h
engines/zvision/zvision.cpp
graphics/macgui/macfontmanager.cpp

Previous discussion suggests that the Liberation fonts work better as fallbacks for fonts like Arial that FreeFont does, so this PR switches all engines for games that originally used Windows fonts to use the Liberation fonts for consistency.

ENGINES: Use LiberationSans instead of FreeSans as a fallback

---

engines/ngi/ngiarchive.cpp
engines/ngi/ngiarchive.h

This makes the game perform poorly with Android SAF. The file is open once at the init and we then seek in it to look for contents.
It's how it works for other archives like Zip.
In the same time, cleanup the headers.
This fixes bug [#15449](https://bugs.scummvm.org/ticket/15449)

NGI: Don't reopen the NGIArchive when reading a content

---

engines/tetraedge/tetraedge.cpp

And don't try to fallback on classic OpenGL as it's not always available.
This avoids the engine to error out on Android.
Instead, the getBestMatchingType falls back on TinyGL.

TETRAEDGE: Don't declare OpenGL with shaders as supported

---

engines/freescape/freescape.cpp
engines/freescape/freescape.h

This change keeps the mouse cursor in the middle of the play area when switching to 'shoot mode' with SPACE. Currently, the cursor jumps to the top left of the view, which feels awkward.

FREESCAPE: Keep cursor in the middle of the view area when switching to shoot mode

---

engines/agos/animation.cpp
engines/groovie/video/player.cpp
engines/mohawk/video.cpp
engines/sci/graphics/video32.cpp

Unfortunately, I don't know how to test this.

ENGINES: Use LiberationSans for subtitles instead of FreeSans

---

engines/hadesch/detection_tables.h

This is from the Mac partition of an already detected pirated version.

HADESCH: Add pirated Mac version to detection

---

.github/workflows/ci.yml

In our current CI configuration, we have a second Ubuntu runner, intentionally using an older release and compiler, as a quick (and early) way to catch some portability problems.
(I think GCC 4.7 is the lowest GCC release that will build current ScummVM, as used for RISC OS, but the runner uses GCC 4.8 as a good-enough measure, since that release is relatively easy to install there.)
Anyway, for that we relied on Ubuntu 20.04, but this release is being deprecated by GitHub Actions, with some *brownout* periods due soon.
So this PR updates this runner to Ubuntu 22.04 (= the oldest available release supported by GitHub).
* The trick to use the GCC 4.8 packages from Ubuntu 18.04 still works there, but we now need some `apt-key` lines to cover the older GPG stuff they used.
…and that's it. …

CI: Update Ubuntu runner from 20.04 to 22.04

---

backends/platform/3ds/osystem-graphics.cpp
backends/platform/3ds/sprite.cpp

~~Up to this point, `Graphics::Surface`-derived `Sprite` objects have simply been decalred in the 3DS backend's `osystem.h` file. As such, the `Sprite` class's constructor was not being called, and the chunk of linear memory `Sprite._vertices` is meant to point to wasn't being allocated. This PR rectifies that.~~
~~The fact that the 3DS port has still been working to this point, despite writing into undefined space in main memory, is a happy accident. The undefined behavior only manifested during my efforts to make a framework with which 3DS hardware renderers can be created for 3D engines.~~
`Sprite.vertices` was being freed before it was meant to be freed.

3DS: Fix improper memory freeing (Sprite.vertices)

---

configure

This is a follow-up to previous PR #6285.
GNU Binutils 2.44 officially deprecated the (mostly unmaintained for some years) Gold linker:
https://lists.gnu.org/archive/html/info-gnu/2025-02/msg00001.html
So, make `--disable-gold` the default, now, since we know that it trigger internal (and unsolved?) linker errors on non-mainstream archs (see previous PR discussion). The previous PR limited this behavior to the non-mainstream archs; but since GNU Binutils itself marked the whole Gold linker as deprecated, and since alternatives exist nowadays (see the existing LLD/Mold integration, and GNU BFD being better than it used to be before Gold.), it just seems wiser to stop triggering its usage.
Users having good reasons to try linking with Gold anyway now need to set an explicit `--enable-gold`, …

CONFIGURE: Make --disable-gold the default, now that Binutils deprecated it

---

engines/freescape/gfx.h
engines/freescape/gfx_opengl_shaders.cpp
engines/freescape/gfx_opengl_shaders.h
engines/freescape/shaders/freescape_cubemap.fragment
engines/freescape/shaders/freescape_cubemap.vertex

Currently, Freescape does not draw a skybox when using opengl with shaders to run Castle Master. I have defined `OpenGLShaderRenderer::drawSkybox` and used seperate cubemap shaders for the rendering.  Only Castle Master will be affected by this.

FREESCAPE: Implement skybox for opengl with shaders

---

gui/themes/residualvm/remastered_gfx.stx
gui/themes/scummmodern/scummmodern_gfx.stx
gui/themes/scummremastered/remastered_gfx.stx
po/ka.po
po/zh_Hans.po
po/zh_Hant.po

This is complicated by the fact that there appear to be two Traditional Chinese translations - one that's empty but has a more descriptive language ID, and one that's 20% complete but is broken by the first commit which uses zh_Hant as the language ID in the theme files.
I'm also not sure if the second commit should have been done via Weblate instead, but I couldn't spot an easy way of doing it.

I18N: Miscellaneous fixes

---

dists/bash-completions/README
dists/bash-completions/scummvm

This is my attempt at adding a custom tab completions script for ScummVM, using the infrastructure provided by the bash-completions package. It is just an initial version that hopefully contains all the plumbing to easily add what we want.
It's the first time I've tried writing something like this, and I'm not good at Bash scripting to begin with. If it's correct, it's because I've looked at a lot of simple examples. If it's wrong, it's because I still did not understand them.
What I've added examples of so far:
- Some long options are completed. If they end with a "=" the space after the completion is suppressed.
- Some parameters to long and short options alike are completed.
- Domains from the scummvm.ini file are completed, except for "scummvm" itself since that isn't a game.
So …

DISTS: Add Bash tab completions script for ScummVM

---

common/debug.cpp
common/debug.h
common/log.h
common/rect.h
engines/director/debugger/debugtools.cpp
engines/twine/debugger/debugtools.cpp

This variable previously held several channels while it's only used for one channel now.

COMMON: Remove plural of debugChannels

---

backends/graphics/sdl/sdl-graphics.cpp
backends/graphics/sdl/sdl-graphics.h
backends/platform/sdl/sdl-window.cpp
backends/platform/sdl/sdl-window.h

This adds a new shortcut (Ctrl+R) which toggles the resizable state of the window and allows the user to lock the window size and prevents resizing.
Closes [bug:15124](https://bugs.scummvm.org/ticket/15124).
This PR replaces #6423.

BACKENDS: SDL: Let the user prevent resizing of the window

---

engines/got/game/back.cpp
engines/got/game/main.cpp
engines/got/game/move_patterns.cpp
engines/got/vars.h
engines/got/views/game_content.cpp

In chapter 2, there is a section where you enter in a pitch dark room and Thor is replaced with eyeballs. This is all you can see while you move around in the invisible maze to find the shovel.
This patch fully implements this mode and also adds these additional related features :
* bruised eye animation that happens after the shovel is found, with Thor's face.
* Saving and loading preserves the eyeball effect in the room 105.
* Thor's spinning animation takes the eyeballs mode in consideration. Although the only way the user can die in that room is to explicitely use the "die" feature/command.
The original code was used as a guideline to implement this feature.

GOT: Add eyeballs mode for chapter 2 shovel maze

---

engines/ags/engine/ac/game.cpp

Instead of allocating the GameState and GameSetupStruct variables on stack and erase the heap version, deallocate the old ones and reallocate new ones.

AGS: Avoid stack frame size warning in AGS3::unload_game

---

test/common/base64.h

The structure is loaded bytewise from Base64 data and should be compared in a little endian fashion as the Base64 test pattern was generated on a LE machine.
Closes [bug:15738](https://bugs.scummvm.org/ticket/15738).

TEST: Fix base64 test on big-endian

---

engines/scumm/dialogs.cpp
engines/scumm/dialogs.h
engines/scumm/metaengine.cpp
engines/scumm/palette.cpp
engines/scumm/scumm.cpp
engines/scumm/scumm.h

As can be seen on MobyGames, the Sega CD version of MI1 is really quite dark: https://www.mobygames.com/game/141074/the-secret-of-monkey-island/screenshots/sega-cd/
This attempts to implement that in ScummVM, while at the same time making it en enhancement ("Audio-visual improvements") to use the colors provided by the game data files. Though without access to a proper Sega CD emulator, this is just a guess. it seems to match the screenshots I've seen pretty well.
Before:
After:
I don't know if the dark graphics (apparently everything is drawn in "shadow mode") were deliberate or not. But you can tell that the developers were at least aware, because they made the SCUMM Bar sign a lot brighter than in other versions, making it stand out even with the darker colors:

SCUMM: "Fix" the bright graphics in the Sega CD version of MI1

---

engines/freescape/games/dark/dos.cpp

This PR fixes multiple UI rendering issues in the game to make the game match the original implementation.  
- **Step & Position Numbers:**  
- Previously, some parts of the loaded border image were not fully erased when updating the display.  
- **Fix:** A black rectangle (matching the background) is now drawn to clear the old data before rendering new numbers.  
- **Shield & Energy Bars:**  
- The bars were not rendered correctly, differing from the original game's implementation.  
- **Fix:** Adjusted rendering to match the original behavior.

FREESCAPE: Fix some UI Issues in Dark-Side

---

engines/hopkins/graphics.h
graphics/palette.cpp
graphics/palette.h
image/bmp.cpp
image/bmp.h
image/cel_3do.cpp
image/cel_3do.h
image/cicn.cpp
image/cicn.h
image/gif.cpp
image/gif.h
image/iff.cpp
image/iff.h
image/pcx.cpp
image/pcx.h
image/pict.cpp
image/pict.h
image/png.cpp
image/png.h
image/tga.cpp
image/tga.h

These changes expand use of the Graphics::Palette class to the internals for many of the ImageDecoder classes.
The palette clear method is changed from zeroing out the entries to deleting them. I do not believe this method previously in use.
The NeoDecoder was not changed due to more complex uses of a passed in palette variable.
The XBMDecoder was not changed due to the use of a static const palette.
Do we have good method to test these changes? I was able to test BMP with testbed, but I am unsure what other paletted images I can check with.

IMAGE: Replace palette byte arrays with Palette class

---

image/pcx.cpp

The RGB planes were flipped and TESTBED image decoder tests revealed this bug. AGS is the only engine that allows for 24bpp PCX image, but an example game is currently unknown.

IMAGE: Fix 24bpp PCX image decoding.

---

engines/asylum/views/video.cpp
engines/sword1/animation.cpp
engines/sword1/animation.h
engines/sword1/logic.cpp
engines/sword2/animation.cpp
engines/sword2/animation.h
engines/sword2/function.cpp
image/codecs/cinepak.cpp
image/codecs/indeo/indeo.h
image/codecs/indeo3.h
image/codecs/mjpeg.h
image/codecs/mpeg.h
image/codecs/svq1.h
image/codecs/xan.h
image/jpeg.h
video/bink_decoder.h
video/mkv_decoder.h
video/mpegps_decoder.cpp
video/psx_decoder.h
video/theora_decoder.h
video/video_decoder.cpp
video/video_decoder.h

This is currently a draft because it uncovers a bug in the PSX video decoder - `setOutputPixelFormats` needs to be called after `loadFile()` and before the first frame is decoded, however the PSX decoder decodes the first frame within the load function, meaning that it's not possible to override the default format.

SWORD1/SWORD2: Detect availability of RGB colour support at runtime

---

audio/decoders/qdm2.cpp
audio/decoders/qdm2.h
audio/decoders/quicktime.cpp
configure
engines/mohawk/configure.engine
engines/testbed/configure.engine
image/codecs/codec.cpp
image/codecs/svq1.cpp
image/codecs/svq1.h

These codecs were introduced in QuickTime 3 and 4 respectively, so are only likely to appear in games released in 1998/1999 or later.

CONFIGURE: Make SVQ1 and QDM2 optional components

---

engines/scumm/gfx_gui.cpp
engines/scumm/macgui/macgui_impl.cpp

The Mac GUI for the SCUMM games does not work well when the game is paused. At least not the way pause/message banners are handled, so the Mac GUI is suppressed while there is one on screen.
When it was just Loom and Indy 3, we just checked if the custom message banner had been created. When other games were added, we also tested the `_messageBannerActive` flag. But this was not set for old style games, and now Maniac Mansion (which was ported to the Mac for the Day of the Tentacle Easter Egg) is in the process of being supported. So this pull request sets the `_messageBannerActive` flag for that case as well. I hope this doesn't break anything, but there was no one around on Discord that I could ask.
(It also turns out that this flag is already set for Loom and Indy 3, so we don't have …

SCUMM: MACGUI: Disable Maniac Mansion Mac GUI while paused

---

graphics/managed_surface.cpp
graphics/managed_surface.h
test/image/blending.h

The copy constructor and operator= method ares still used, however in those cases it might be more practical to revise the behaviour in regards to ownership of the buffer and undeprecate it rather than to remove it outright.

GRAPHICS: Removed deprecated ManagedSurface constructors

---

engines/sword25/input/inputengine.cpp
engines/sword25/input/inputengine_script.cpp

Add proper reporting of character events to make the debug cheat codes work.

SWORD25: Fix keyboard input

---

engines/freescape/freescape.cpp

- Fix a condition in `checkIfGameEnded` function, so that the game ending (when energy reaches 0) happens only in Driller Game.

FREESCAPE: Fix Flying-Mode Related Issues

---

image/codecs/cdtoons.cpp
image/codecs/cdtoons.h
image/codecs/qtrle.cpp
image/codecs/qtrle.h
image/codecs/rpza.cpp
image/codecs/rpza.h

These changes are simple, but not all of it is tested. I am having difficulty finding examples demos with videos using these codecs.
Currently tested:
CDToons - Testbed video with Where in the USA is Carmen Sandiego? (Windows Demo)

IMAGE: Use palette class in more codecs

---

engines/scumm/script_v5.cpp
engines/scumm/scumm_v5.h

Some time ago, @eriktorbjorn mentioned on Discord that some EGA releases of Loom have that bug where Hetchel flies with two heads, for a few frames at the forge:
I can reproduce this problem in (at least):
* the original English EGA 1.0 release
* the original English EGA 1.1 release
* the original English Macintosh release
It's been fixed by LEC in (at least) the following EGA releases, though:
* original French EGA 1.2 release
* Hebrew EGA 3.2 release (as sold by LimitedRunGames)
And then I tested the PC-Engine Japanese release, the FM-TOWNS English release, and the talkie CD release, and there the problem never appears.
Erik suggested this short diff:
```diff
diff --git a/engines/scumm/actor.cpp b/engines/scumm/actor.cpp
index 8784d906255..78fd6fb63ed 100644
--- …
```

SCUMM: LOOM: Fix Hetchel flying with two heads in some EGA releases (Enhancement)

---

engines/ags/engine/ac/dynamic_sprite.cpp

AGS: fix DynamicSprite.Flip() to use CreateTransparentBitmap
DynamicSprite.Flip() is using CreateBitmap instead of CreateTransparentBitmap meaning flipped sprites lose their transparency.
Looks like this creeped in during refactoring here (other methods are OK, just Flip):
https://github.com/scummvm/scummvm/commit/3078b207d33d5e551811b3f26879f45016d6fe33#diff-4093ff4addff2a4251456a23d8da353c260c0dfd217919f3a0b0cfb31bae921bR126
Reference AGS code here:
https://github.com/adventuregamestudio/ags/blob/master/Engine/ac/dynamicsprite.cpp#L125
Test case are mirror reflections in The Crimson Diamond.

AGS: fix DynamicSprite.Flip() to use CreateTransparentBitmap

---

engines/chewy/video/cfo_decoder.cpp
video/coktel_decoder.cpp
video/coktel_decoder.h
video/dxa_decoder.cpp
video/dxa_decoder.h
video/flic_decoder.cpp
video/flic_decoder.h
video/mve_decoder.cpp
video/mve_decoder.h
video/paco_decoder.cpp
video/paco_decoder.h

Coktel video decoders were tested with various game demos. 
DXA, FLIC, and MVE tested with Testbed video alterations in #6473
PACo still needs a test case but appeared to be potentially leaking memory in prior code.

VIDEO: Use palette class in video decoders (Part 2)

---

engines/director/debugger/imgui_memory_editor.h
engines/director/lingo/lingodec/ast.h
engines/director/score.cpp

This PR aims to fix most of the warnings in the `director` engine, which are thrown by MSVC.
Opening as a PR to get feedback on the changes, mostly the one about signed integers in file offsets, plus to check if everything builds OK.
@sev-, @moralrecordings, @rvanlaar, any feedback is welcome :)

DIRECTOR: Fix MSVC warnings

---

graphics/macgui/macwindowborder.cpp

A `NinePatchBitmap` type requires a white color in the color palette otherwise it throws a warning `WARNING: NinePatchBitmap::NinePatchBitmap(): Bad bitmap!`. The bitmap is created [here](https://github.com/scummvm/scummvm/blob/master/graphics/macgui/macwindowborder.cpp#L112)

GRAPHICS: MACGUI: Fix color palette used in nine-patch bitmap for disabling border

---

engines/testbed/video.cpp
video/mve_decoder.cpp

The decoders for avi, dxa, flc, mve, and smk are selected based on file extension.
The MVE video width, height, and pixel format getters were causing infinite recursion due to the video decoder asking its tracks for the width, height, and pixel format by the same methods

TESTBED: Allow video test to handle more decoders

---

engines/freescape/games/dark/dark.cpp
engines/freescape/games/dark/dark.h

- **Fix infinite loop when shooting while flying**  
- Create a new SFXhandle for jetpack and use it to play it's sound.  
- **Fix jetpack sound not stoping when energy reaches 0**  
- Stop the jetpack SFXhandle using mixer.

FREESCAPE: Fix sound-related issues

---

engines/gob/detection/tables_bargon.h

In GO.BAT the value LANG was set to EN_GB for this variant of Bargon Attack

GOB: mark bargon entry as EN_GRB

---

engines/dgds/minigames/china_train.cpp

DGDS: Correct spelling in minigame
There's not much to say. I saw the news post about Heart of China and
noticed the glaring typo.

DGDS: Correct spelling in minigame

---

video/mpegps_decoder.cpp
video/mpegps_decoder.h

Recognize the type of the stream in .mpg files (ES or PS) In case of ES (Elementary Streams) bypass the PES header parsing process and directly feed the MPEG decoder the raw data. Remove warning that appears when opening the ND
logo when opening the game 3mice1-pl
Changes made in how ES stream packets are pushed
in the _demuxer queue for decoding in function queueNextPacket Made sure that the ES stream is handled in
the MPEGPSDecoder::MPEGPSDemuxer class entirely

VIDEO: Correctly handle raw Elementary Stream MPEG Videos

---

engines/wage/combat.cpp

Clear `_soundQueue` when re-entering a scene with stale timestamps. Previously, if a player left and later returned to a scene, the sound queue could contain old timestamps. This caused `installTimerProc` to compute a negative delay, triggering an assertion failure (`interval > 0`) in `DefaultTimerManager`.
Tested by re-entering scenes with sound timers and confirming no crashes.

WAGE: Fix crash due to outdated sound queue timestamps

---

graphics/tinygl/zdirtyrect.cpp

TGL_TRIANGLE_FAN was found to be causing an access violation error while drawing pixels due to a bad value which emerged when attempting to render celestial bodies in Total Eclipse. When the access violation was forestalled by some means, you would see the sun and moon rendered as disconnected triangles which looked like rays rather than a true triangle fan. The first issue was because the loop which draws the vertices was stepping one vertex too far, and the rendering issue was due the loop not reusing a vertex from the previous triangle for the next one, causing the skipped triangle rendering.

TINYGL: Fix TGL_TRIANGLE_FAN rendering

---

backends/audiocd/macosx/macosx-audiocd.cpp
backends/fs/posix/posix-fs.cpp

On OSX Tiger, playing Indy3 FM-TOWNS from its original CD (which has both an ISO-9660 layer and a Redbook layer) produced no music.
It looks like that's because we rely on dirent's `d_type` (on systems where it's available). Thing is, this field is not guaranteed to be meaningful for all filesystems (even on Linux; as seen in its `readdir(3)` manual page).
In OSX Tiger in particular, dirent returns completely bogus `d_type` values for the files being part of the CDDAFS volumes (used by MacOSXAudioCDManager). I'd get `DT_CHR` for the AIFF files, and `3` (which has no `DT_*` value name!) for the TOC file. (It looks like this is because their `cddafs` module, up until cddafs-240.0.9 in 2008, [uses improper constants](https://github.com/apple-oss-distributions/cddafs/commit/d7f85707277ac630e7a …

BACKENDS: FS: Use stat() fallback for all unexpected dirent d_type values

---

engines/grim/detection_tables.h
engines/grim/md5check.cpp

From my own French ASPYR CDs. Appears to properly work (just played a few scenes, though), which might not have been the case of the Macintosh English release, judging by commit b59d22dd09e64568daedaa986798f0db5255e906 description.
The Macintosh installer is called `Installation de Monkey Island 4`, there.
Regarding the `MD5SUM("local.m4b", emi_local)`, I've checked both my French Windows and French Macintosh CDs, and it does look like it's part of the MonkeyInstall resources, not the MonkeyData ones.
Submitting it as a PR, in case @aquadran wants to check a few things first.

GRIM: Add French Mac EMI detection entry

---

engines/freescape/area.cpp
graphics/tinygl/zbuffer.h

Fix incorrect depth buffer writing in render pipeline of TGL_LINES 
- Add `kDepthWrite` parameter to control depth updates
- Modify the the affected code to render first planar, then non-planar objects

FREESCAPE: Fix for #15486 TINYGL: triangles always override zbuffer from lines

---

engines/chamber/cga.cpp
engines/chamber/script.cpp

The PR includes following changes
- Adjust portrait rendering position for HGA mode.
- Add HGA support to ```cga_PrintChar()```.
- Fix crash in ```cga_blitToScreen()``` due to division by zero. A hard-coded value of 4 was being passed in ```SCR_D_DrawPortraitDotEffect()```.

CHAMBER: HGA Text Rendering Fixes

---

devtools/create_project/xcode.cpp
dists/scummvm.rc
engines/playground3d/gfx_opengl.cpp
engines/playground3d/gfx_opengl_shaders.cpp
engines/playground3d/gfx_opengl_shaders.h
engines/playground3d/gfx_tinygl.cpp
engines/playground3d/playground3d.cpp
engines/playground3d/playground3d.h
engines/playground3d/shaders/playground3d_offset.fragment
engines/playground3d/shaders/playground3d_offset.vertex
engines/playground3d/shaders/playground3d_viewport.fragment
engines/playground3d/shaders/playground3d_viewport.vertex

* Implement Tests 2 and 4 in the OpenGL Shaders renderer
* In Test 4, make sure the red square is completely out of view before it is warped from the top-right corner to the bottom-left corner.
* Left-clicking the screen starts the next test. For example, left-clicking when Test 1 is running will start Test 2; if Test 5 is the current test, the cycle will loop back to Test 1. This eliminates the need to recompile every time you want to do a different test.

PLAYGROUND3D: Make various improvements

---

engines/hpl1/detection_tables.h

Add a new detection entry for Penumbra: Overture bought from Steam.

HPL1: Add a new detection entry for Penumbra: Overture

---

engines/scumm/script_v5.cpp

The first time Guybrush enters the ship's hold, there is a message where he remarks that the whole thing reeks of monkeys. But the way it's scripted, it's only shown if it has already been shown. Here's how Nutcracker renders the script:
```
enter { ; ENCD LECF_0001/LFLF_0008/ROOM/ENCD
start-script bak 200 ()
break-here
if (B.321) {
B.321 = 1
say-line "Yech!!!\\xFF\\x03The unmistakable stench of Monkeys!!!\\xFF\\x03This whole ship smells like hot, sweaty primates.\\xFF\\x03I knew I should have taken it for a test sail."
}
end-object
}
```
I assume that variables are automatically initialized to 0, because these are the only references I can find to `B.321`. We can enable the message by inverting the check:
In most versions, you should be able to reach the scene easily by using boot param …

SCUMM: Add enhancement for missing message when entering ship's hold

---

AUTHORS
common/compression/dcl.cpp
devtools/credits.pl
doc/docportal/help/credits.rst
engines/sci/detection.cpp
engines/sci/sci.h
gui/credits.h

We have mislabeled PKWARE's DCL IMPLODE format as DCL INFLATE in the ScummVM credits and messages.
It's true that PKWARE's Data Compression Library also supported PKWARE's DEFLATE at some point, but that's a completely different format.
The Data Compression Library format we decompress is named IMPLODE. You'd call the `implode` library function to compress with it and `explode` to decompress.
https://support.pkware.com/pkzip/dcl
http://fileformats.archiveteam.org/wiki/PKWARE_DCL_Implode
https://github.com/madler/zlib/blob/master/contrib/blast/blast.c

COMMON: Fix DCL IMPLODE name

---

engines/sci/resource/decompressor.cpp
engines/sci/resource/decompressor.h

This PR ports the [LZW decompressor](https://github.com/sluicebox/sci-tools/blob/main/SCI/Resource/Decompressors/LzwDecompressor.cs) from my SCI tools to ScummVM. This replaces two FreeSCI-era decompressors with one small documented one.
That's right, we're compressing the decompressors.
SCI has two LZW compression formats. They only have two minor differences. The first is the bit order, the second is an off-by-one bug. The bug is so common in LZW implementations that it has a name and made the [LZW wiki page](https://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Welch): "early change".
I don't think it's known to the SCI community that the formats only differ by these two things. I learned it the hard way when developing my decompressors. I think what usually happens is that the …

SCI: Merge and cleanup LZW decompressors

---

backends/platform/3ds/osystem-graphics.cpp
backends/platform/3ds/sprite.cpp

When only the top screen is set to be used, the overlay must have a width of 400; otherwise there's a possibility that not all of the screen will be rendered. This is most notable at the launcher screen, where if only the top screen is set to be used, and `Sprite _overlay` has a width of 320, the right side of the screen will not be rendered.
This commit ensures that the overlay sprite has a width of 400 when only the top screen is set to be used. In all other cases, the overlay sprite will have a width of 320.

3DS: Fix top screen not fully rendering in some cases

---

engines/qdengine/qdcore/qd_camera.cpp
engines/qdengine/qdcore/qd_contour.cpp
engines/qdengine/qdcore/qd_contour.h
engines/qdengine/qdcore/qd_game_dispatcher.cpp
engines/qdengine/qdcore/qd_game_object_moving.cpp
engines/qdengine/qdcore/qd_grid_zone.cpp

- Fix inventory being empty in one scene in karliknos
- Fix zigzag pattern in generated paths for pilots3
- Fix impassable grid issue by bringing back the old mask-based implementation
- Fix inventory being drawn when switching to main menu

QDENGINE: Various fixes around older game versions 

---

backends/audiocd/macosx/macosx-audiocd.cpp

This is for `macosx-audiocd.cpp` (backend code).
* Fix a `-Wframe-larger-than` warning (macOS 13.7.4, Intel x64, Apple Clang 14), by allocating the `statfs` buffer on the heap instead of the stack
* Fix a `-Wsign-compare` warning when comparing with `UINT_MAX` (macOS 10.4.11, ppc32, GCC 7.5.0), with an `unsigned long` cast (since we already check `trackID > 0` just before it)
While there:
* Add a couple more headers for `getfsstat()`, as given by its manual page (although it always built just fine without them).
I can split this into multiple commits if you'd like, but I'm not sure it's worth it here.
Tested on macOS 10.4 (ppc32), 13.7 (Intel x64) and 15.3 (aarch64).
@criezy: Does this look good to you? Thanks :)

BACKENDS: MACOS: Fix various small warnings in macosx-audiocd.cpp

---

engines/ags/engine/media/audio/sound_clip.cpp

This is a fix for https://bugs.scummvm.org/ticket/15761 and https://bugs.scummvm.org/ticket/15307. 
Some games (namely Blackwell Legacy and Blackwell Unbound but there are probably more) have volume modifiers associated with the sound clips. The code for detecting and calculating the final volume was already present but it was not used.

AGS: Fix volume modifier not being respected

---

engines/scumm/script_v5.cpp
engines/scumm/scumm_v5.h

Here's a scary one!
Any conversation in the Sega CD version of MI1 is likely - perhaps even guaranteed - to set one or more bit variables that are intended for other things. Luckily none of them appear to be game breaking, but still...
Since this is a global bug, I've been relying on NUTCracker for dissecting the scripts. While I'm a bit fuzzy on some of the details, MI1 uses nine bit flags numbered 384 through 392. They are set when conversation options are presented. In the DOS CD version it can look like this:
```
V.100 = ((120 + 1) - 1)
verb V.100 at 2,V.229 name "So what was your name, anyway?" on key V.230
V.229 += 8
V.100 -= 120
++V.230
B.384[V.100] = 1
```
And then the script that handles conversation trees test and clears these variables. (They're cleared manually in some cases …

SCUMM: Add workaround for MI1 Sega CD clobbering bit variables

---

doc/QuickStart
doc/cz/PrectiMe
doc/de/LIESMICH
doc/docportal/advanced_topics/command_line.rst
doc/docportal/advanced_topics/configuration_file.rst
doc/docportal/advanced_topics/understand_audio.rst
doc/docportal/advanced_topics/understand_search_box.rst
doc/docportal/help/report_bugs.rst
doc/docportal/other_platforms/amigaos_4.rst
doc/docportal/other_platforms/ios.rst
doc/docportal/other_platforms/nintendo_3ds.rst
doc/docportal/other_platforms/playstation_3.rst
doc/docportal/other_platforms/playstation_vita.rst
doc/docportal/settings/audio.rst
doc/docportal/use_scummvm/add_play_games.rst
doc/docportal/use_scummvm/mac_game_files.rst
doc/docportal/use_scummvm/save_load_games.rst
doc/docportal/use_scummvm/taskbar_integration.rst
doc/doxygen/scummvm.doxyfile
doc/sv/LasMig

First I had commits for individual files, but that spammed the log; let me know if they should be exploded again in some way.
I tried not to use my own opinion for style, but rather to use what we already see elsewhere, sometimes within the same file. (e.g. "homebrew-enabled"; "PlayStation"; ...)

DOCS: Fix some typos and style

---

graphics/macgui/mactext-canvas.cpp
graphics/macgui/mactext.cpp

- Check for null pointer before handling any operations in getChunkNum function.
- Check for empty chunks to avoid extra operations.
- avoid signed/unsigned issue in chunk position.
- avoid possible overflow in cursor restoration logic

MACGUI: Null pointer and empty chunks tests in mactext , change cursor restoration in getmaxwidth.

---

graphics/macgui/macfontmanager.cpp
graphics/macgui/macfontmanager.h
gui/helpdialog.cpp
gui/widgets/richtext.cpp

This is a fix for https://planka.scummvm.org/cards/1245220086541714717 .
- Fixed caching of TTF/unicode fonts.
- Did minor refactor to unify naming with other parts of the code.
- Enabled help menu translations
Did some simple measurements, here is how long it took to create help widget before the fix:
and here is after:

GRAPHICS: Fix TTF font caching

---

engines/qdengine/system/sound/snd_dispatcher.cpp
engines/qdengine/system/sound/snd_sound.cpp
engines/qdengine/system/sound/snd_sound.h

- Implemented resuming a sound correctly
- Adjusted the methods for updating the volume, playing the sound so that the sound volume control actually affects the volume value. Also used the _volume instead of _volume_dB so that the volume range is in [0, 255] instead of [-10000, 0].

QDENGINE: Fix sound related issues

---

configure
devtools/create_project/create_project.cpp
devtools/create_project/xcode.cpp

Based on @sluicebox's comment on commit 599fbc290a25ef671f844cada1705219c735042b, where a missing `return` statement was caught by a fatal error in MSVC (thanks to previous PR #4561) but not in the GCC/Clang builds.
This PR now makes the three main builders (`configure`, MSVC, Xcode) have such a behavior, for this specific case.
For the `configure` scripts, the new flag is set by default, but one can turn it off with `--disable-Werror`, if some situation requires it (e.g. some Linux distributions having a good reason to do so, some future compiler upgrade introducing a stricter/buggier `-Wreturn-type`…).
(Regarding `CXXFLAGS`: I'm not using `set_flag_if_supported`, since `-Werror=flag-name` was introduced before GCC 4.7, which is our minimal C++11 requirement.)
Of course, turning a …

BUILD: Use -Werror=return-type (and MSVC equivalent)

---

devtools/create_project/cmake.cpp

If the engines directory contains plugins_table.h or detection_table.h from an in-source build, when building out-of-source, these files from the source directory were prioritized over build directory versions.
This caused issues when different plugins were enabled across builds.
The revised include order now matches the implementation in Makefile.

CREATE_PROJECT: Fix include order for cmake projects

---

video/qt_decoder.h
video/qtvr_decoder.cpp

Add the following missing features in QTVR panorama as described in the original director QTVR documentation
- 4 levels of quality mode, also added the dynamic quality where the quality is changing based on whether the user is actively intereacting with the panorama
- swing transition from the current node to the target node in a smooth animation
- 3 levels of warping

VIDEO: QTVR: Add quality, warpMode and swing transition

---

engines/director/lingo/xtras/qtvrxtra.cpp

Please refer to the pull request
https://github.com/scummvm/scummvm/pull/6548
Set the corner origin point in the QTVR decoder from QTVR Xtra
in order to make sure during the swing transition the QTVR video
decoder blits the panorama at the correct position

DIRECTOR: XTRA: Set origin for the QTVR decoder in QTVR Xtra

---

engines/director/events.cpp
engines/director/lingo/lingo-builtins.cpp
engines/director/movie.h

Alerts and Message are shown on the screen by ScummVM using 
GUI dialog boxes. They may have clickable buttons on them.
In Director, it may happen that the event of clicking or pressing the 
button on the GUI dialog box (mouseUp, keyUp) get recorded as a movie 
event, which may cause unpredictable change in the lingo script.
An example of this: in Testbed.dir, if you try to open a file that doesn't 
exist director engine throws a dialog box error with an "OK" button 
However, pressing the button triggers  a movie event `mouseUp` which 
causes the button to reappear.
The following video shows a demonstration of that
https://github.com/user-attachments/assets/24bd81cd-082f-4a50-9cc1-c7d86aa869e1
Prevent this by disabling all event processing in the Director movie using 
a flag …

DIRECTOR: Disable Movie Events while Alert is being shown

---

common/compression/gentee_installer.cpp
common/compression/gentee_installer.h
engines/vcruise/vcruise.cpp

This adds a few features necessary to support the Schizm Japanese version installer:
Adds support for loading PAKs embedded in the installer executable, both by adding the necessary functionality and by fixing the PAK header EOF location being misread as the PAK size.
Adjusts path handling to deal with the path separator at the end of the prefix being inconsistent in the unpack commands.

COMMON: Improve Gentee Installer loader to support Schizm Japanese version

---

common/macresman.cpp
common/macresman.h
common/md5.cpp
common/md5.h
gui/integrity-dialog.cpp
gui/integrity-dialog.h

* Add callback function that updates the bytes processed during the md5 calculation to display in the progress bar
* Implement event polling to keep UI responsive during operations
* Fix crash when clicking cancel button during checksum calculations
Here is a demo video - 
https://github.com/user-attachments/assets/c902147c-0445-4848-9932-b065dc275c0e

GUI: Fix integrity dialog freeze/update issue

---

engines/mm/mm1/gfx/gfx.cpp
graphics/palette.cpp
graphics/palette.h

One roadblock to expanded use of the palette class is my desire to not make extra memory copies the static palette data used in a number of classes. This new constructor with the use of DisposeAfterUse::NO and a const qualifier could be an answer to that problem.
Does this seem like a good path forward or are there alternate ideas?
Is this a silly concern and a small memory copy not a big enough deal to warrant a change?

GRAPHICS: Add palette constructor for ownership of data

---

backends/graphics/opengl/shader.cpp

This should fix [Trac#15860](https://bugs.scummvm.org/ticket/15860).
At least, I hope...
The current code only uses a linear scaling to look at the palette texture.
This means that lookup coordinate is on the form (when stretched to texture size):
0.0, 1.00196, 2.00392 ... 253.49607, 254.49803, 255.5
With the newer code it will be on the form:
0.5, 1.5, 2.5, ... 253.5, 254.5, 255.5
This needs proper testing because this code is used on many backends.

BACKENDS: OPENGL: Fix CLUT shader lookup

---

engines/sci/engine/script_patches.cpp

It was reported in https://forums.scummvm.org/viewtopic.php?t=17338 that the King's Quest IV demo (which can be found on the ScummVM demos page) crashes with the following messages:
```
User picked target 'kq4sci-demo' (engine ID 'sci', game ID 'kq4sci')...
Running King's Quest IV: The Perils of Rosella (SCI/Demo/DOS/English)
resource.001: 143e1c14f15ad0fbfc714f648a65f661, 205330 bytes.
resource.map: 992ac7cc31d3717fe53818a9bb6d1dae, 594 bytes.
WARNING: No selector vocabulary found, using a static one!
[kq4sci-demo-ego 699/994 Room699::<noname268> @ 0a11]: Send to invalid selector 0xffff (<noname65535>) of object at 0014:0170!
Debugger started, type 'exit' to return to the game.
Type 'help' to see a little list of commands and variables.
ERROR: [kq4sci-demo-ego 699/994 …
```

SCI: Fix King's Quest IV demo crash

---

engines/playground3d/gfx.h
engines/playground3d/gfx_opengl.cpp
engines/playground3d/gfx_opengl.h
engines/playground3d/gfx_opengl_shaders.cpp
engines/playground3d/gfx_opengl_shaders.h
engines/playground3d/gfx_tinygl.cpp
engines/playground3d/gfx_tinygl.h
engines/playground3d/metaengine.cpp
engines/playground3d/playground3d.cpp
engines/playground3d/playground3d.h
graphics/tinygl/api.cpp
graphics/tinygl/get.cpp
graphics/tinygl/init.cpp
graphics/tinygl/misc.cpp
graphics/tinygl/opinfo.h
graphics/tinygl/zblit.cpp
graphics/tinygl/zblit.h
graphics/tinygl/zbuffer.cpp
graphics/tinygl/zbuffer.h
graphics/tinygl/zdirtyrect.cpp
graphics/tinygl/zdirtyrect.h
graphics/tinygl/zgl.h
graphics/tinygl/zline.cpp
graphics/tinygl/ztriangle.cpp

This is a followup of #6412.
I implemented a test case in Playground3D (after enabling the keymapper for all tests) and, then, I managed to merge the already in-place clipping with the missing pieces to have a working scissor test.
Finally, a bug is fixed in the various pixel writing function where the update of the z, fog and color was not done.
@neuromancer you may want to test this with Freescape.

TINYGL: Implement scissor test

---

audio/mods/mod_xm_s3m.cpp
audio/mods/mod_xm_s3m.h
audio/mods/universaltracker.cpp
audio/mods/universaltracker.h
engines/sludge/sound.cpp

Most engines didn't specify a sample rate and just used the default value of 48000, which introduces additional resampling on most platforms.

AUDIO: Remove rate parameter for Mod/XM/S3M and Universal Tracker streams

---

engines/advancedDetector.cpp
engines/glk/detection.cpp
engines/metaengine.cpp
engines/metaengine.h
engines/scumm/detection.cpp

The code that uses them in glk and scumm is in #if 0.

ENGINES: Deduplicate escapeString and fix unused-function warnings

---

configure

When using the [`windows-9x` toolchain](https://wiki.scummvm.org/index.php?title=Compiling_ScummVM/Docker), the `make win32dist-mingw DESTDIR=win32dist-mingw` stage would end with this output:
```
...
ldd win32dist-mingw/scummvm.exe | grep -i mingw | cut -d">" -f2 | cut -d" " -f2 | sort -u | xargs -I files cp -vu files win32dist-mingw
not a dynamic executable
```
i.e. the `peldd` code from previous PR #3196 wasn't called.
Indeed, there is not such prefixed binary in the win9x toolchain:
```
$ ./devtools/docker.sh toolchains/windows-9x
not found
/opt/toolchains/mingw32/bin/peldd
```
Maybe something needs to be tweaked in the toolchain to have a prefixed version, but in the meantime I think also looking for a plain `peldd` in our build scripts is quite reasonable. 
@lephilousophe: Any …

BUILD: Support both $_host-peldd and peldd for mingw builds

---

engines/scumm/string.cpp

This fixes Ctrl-V output with French DOTT, when using `original_gui=false`. The `ç` character was not displayed at all, when using ScummVM's own UI for dialogs.
The `original_gui=true` code path is OK, because it calls `queryResString()`, which takes care of calling `getDialogCodePage()`.
But the `original_gui=false` code path never calls `queryResString()`/`getDialogCodePage()` and so the proper code page decoding was not applied.
I'm not sure this fix is enough, though: maybe the `original_gui=false` path would need more of that stuff being done in the last parts of `queryResString()`? It's not a part I know very well…

SCUMM: Fix encoding of some message dialogs with `original_gui=false`

---

video/qt_decoder.h
video/qtvr_decoder.cpp

The previous pull request (merged) https://github.com/scummvm/scummvm/pull/6548
implemented an upscaled panorama for projection in higher quality.
However, it also introduced a bug where if you change the node
(panorama), the `_constructedPano` is now the node you changed to
but the `_upscaledConstructedPano` is still on the previous node
This caused the `projectPanorama()` function to project the wrong panorama when
in high quality mode.
Fix this bug by resetting the  `_upscaleLevel` to 0 when we're constructing 
`_constructedPano` which implies that we have to
upscale the `_constructedPanorama` from scratch during `projectPanorama()`
So whenever the `_constructedPano` is reconstructed, so will be 
`_upscaledConstructedPano`

VIDEO: QTVR: Remove bug in QTVR while changing nodes

---

backends/graphics/opengl/shader.cpp
backends/graphics/opengl/texture.h
graphics/opengl/context.cpp
graphics/opengl/context.h
graphics/opengl/shader.cpp

This also reverts commit 84a31481fa70b56140ca5e62edf9cb287a7d3e7b. This will hopefully fix [Trac#15860](https://bugs.scummvm.org/ticket/15860) for good.
I also hope that nothing else will get broken because of this.
I would like to have the user test this before merging.

BACKENDS: OPENGL: Don't use HW CLUT8 lookup on low precision devices

---

backends/graphics/android/android-graphics.cpp
backends/graphics/ios/ios-graphics.cpp
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/pipelines/libretro.cpp
backends/graphics/opengl/texture.cpp
backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics3d/android/texture.h
backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
backends/platform/libretro/src/libretro-graphics-opengl.cpp
graphics/opengl/texture.cpp
graphics/opengl/texture.h

This should hopefully be a bit less prone to error.

OPENGL: Use helper functions for endian-specific pixel formats

---

audio/decoders/adpcm.cpp
audio/mods/protracker.cpp
common/compression/unarj.cpp
common/formats/prodos.cpp
common/stream.cpp
graphics/larryScale.cpp
graphics/macgui/macwindowborder.cpp
graphics/nanosvg/nanosvg.h
graphics/tinygl/texture.cpp
video/3do_decoder.cpp
video/mve_decoder.cpp

* Unused locals (assert is no-op in release build)
* Bad usage of strncpy
* Uninitialized variables

JANITORIAL: Fix some release build warnings

---

engines/freescape/gfx.cpp
engines/freescape/gfx_tinygl.cpp

This matches the other engines that use TinyGL, since TinyGL handles most of the differences between formats internally.

FREESCAPE: Support running with any pixel format with TinyGL

---

image/codecs/dither.cpp
image/codecs/dither.h
video/qt_decoder.cpp
video/qt_decoder.h

This fixes displaying two QTRLE videos in the Windows demo of Frankenstein: Through the Eyes of the Monster.

IMAGE: Fix dithering 8bpp images when the container owns the palette

---

engines/freescape/shaders/freescape_triangle.fragment
engines/twp/lighting.cpp

[OpenGLES 2.0 GLSL](https://www.khronos.org/files/opengles_shading_language.pdf) requires:
- Control flow is limited to forward branching and to loops where the maximum number of iterations can easily be determined at compile time. (Appendix A, 4 Control Flow)
- In the fragment shader, support for indexing is only mandated for constant-index-expressions. (Appendix A, 5 Indexing of Arrays, Vectors and Matrices)
Generally this doesn't seem to be a limit enforced on most hardware, but for WebGL, this conformity seems to be [enforced by the ANGLE Compiler](https://www.khronos.org/webgl/public-mailing-list/public_webgl/1012/msg00063.php) used in all major browsers.
This PR, fixes the following two errors when launching TWP or Freescape games:
* ['[]' : Index expression must be …

TWP: FREESCAPE: Fix non-compliant GLSL

---

engines/qdengine/system/graphics/gr_dispatcher.h
engines/qdengine/system/graphics/gr_draw_sprite.cpp

Added 32bpp code branches to methods that were marked as untested in [2599f60046addde759dd0f40f9c5e405d8acacb3]. Also removed stub warnings from them, except for grDispatcher::putSprMask(). I am yet to encounter the scenes/games where they are called, so the stubs are left there.

QDENGINE: Add 32bpp support to more drawing methods 

---

engines/glk/level9/detection.cpp
engines/glk/level9/detection_tables.h
engines/glk/window_text_buffer.cpp

Hi, this is my first contribution, hopefully not deviating too much from the guidelines ...
- I've introduced the MSX Level 9 detection entries which I collected over the years, which were also accepted over at David Kinder's Level 9 Interpreter project and in Gargoyle.
- I fixed the Level 9 v1 game detection.
- I introduced unknown Level 9 game variant detection.  This enables us to play Level 9 game variants which are not yet in the general detection tables floating around on the Internet.  This is perfectly possible through hacking the ini file, but now also through the gui.
- I removed the clear screen when adding a new scrollback section of 512 lines.  It is quite annoying to suddenly see your game interaction disappear in the middle of the game.  I don't know how that clear screen …

GLK: do not clear screen when adding scrollback buffer + GLK: LEVEL9: add MSX entries, v1 and unknown variant support

---

engines/grim/lua/lstrlib.cpp
engines/grim/lua/lua.h

and fix condition to avoid potential negative size passed to strncpy.

GRIM: Mark lua_error as noreturn

---

engines/drascula/animation.cpp
engines/drascula/converse.cpp
engines/drascula/detection.cpp
engines/drascula/detection.h
engines/drascula/drascula.cpp
engines/drascula/drascula.h
engines/drascula/graphics.cpp
engines/drascula/interface.cpp
engines/drascula/metaengine.cpp
engines/drascula/saveload.cpp
engines/drascula/sound.cpp

Adds a toggle for text-to-speech under the game options.
- Intro line describing the game's setting
- Dialogue options
- Menu and menu bar actions/verbs
- Names of interactable objects when hovered over
- Messages related to save slots in the original save/load screen
- Lines in the drunkard's cutscene explaining the history of Von Braun
- Subtitles enabled/disabled messages
- Exit confirmation message
- Verb selection with F1 to F6 keys
- Volume controls menu

DRASCULA: Add text-to-speech (TTS)

---

base/main.cpp

`metaEngine` could have been issued `createInstance` but not `deleteInstance` if an engine failed to instantiate (e.g. if user cancels start of a not-fully-supported game).
Attempts to fix:
```
=================================================================
==35138==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 496 byte(s) in 1 object(s) allocated from:
#0 in operator new(unsigned long) (scummvm/scummvm+0x17faead) (BuildId: 7d084231cb059720)
#1 in AdvancedMetaEngineDetection<Nancy::NancyGameDescription>::identifyGame(DetectedGame&, void const**) scummvm/engines/advancedDetector.h:616:18
#2 in identifyGame(Common::String const&, Plugin const**, DetectedGame&, void const**) scummvm/base/main.cpp:164:36
#3 in scummvm_main scummvm/base/main.cpp:748:26
#4 in main …
```

BASE: Fix MetaEngine leak in runGame

---

engines/sci/engine/vm_types.h

```
In member function 'void Sci::reg_t::setSegment(Sci::SegmentId)',
inlined from 'void Sci::reg_t::setSegment(Sci::SegmentId)' at engines/sci/engine/vm_types.cpp:39:6,
inlined from 'Sci::reg_t Sci::make_reg(SegmentId, uint16)' at engines/sci/engine/vm_types.h:196:14,
inlined from 'Sci::reg_t Sci::reg_t::operator+(Sci::reg_t) const' at engines/sci/engine/vm_types.cpp:70:19:
engines/sci/engine/vm_types.cpp:44:38: warning: 'r.Sci::reg_t::_segment' may be used uninitialized [-Wmaybe-uninitialized]
44 |                 _segment = (_segment & 0xC000) | (segment & 0x3FFF);
|                            ~~~~~~~~~~^~~~~~~~~
In file included from engines/sci/sci.h:29,
from engines/sci/engine/vm_types.cpp:22:
engines/sci/engine/vm_types.h: In member function 'Sci::reg_t …
```

SCI: Suppress GCC warnings on release builds

---

audio/mods/mod_xm_s3m.cpp
audio/mods/module_mod_xm_s3m.cpp
audio/mods/module_mod_xm_s3m.h

```
audio/mods/mod_xm_s3m.cpp: In member function 'void Modules::ModXmS3mStream::setSequencePos(int)':
audio/mods/mod_xm_s3m.cpp:1350:15: warning: 'void* memset(void*, int, size_t)' specified bound between 18446744056529682432 and 18446744073709551608 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
1350 |         memset(_playCount, 0, _module.sequenceLen * sizeof(int8 *));
|         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

AUDIO: Fix compiler warning on release build

---

engines/scumm/scumm.cpp

strncpy doesn't ensure the string is null-terminated. Replace with strlcpy.

SCUMM: Fix bad use of strncpy

---

backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
backends/platform/sdl/sdl.cpp
common/archive.h
image/jpeg.h

This fixes some recently added compiler warnings ( I tried to git blame them to ensure I understood the code):
- warning "'Image::JPEGDecoder::getPalette' hides overloaded virtual function" in `jpeg.h` - I think introduced with https://github.com/scummvm/scummvm/pull/6535/commits/4c4a94cf18dc48c8b483a2ebd9550f868b429314 / #6535
- warning "unused variable" in `archive.h` - I think introduced with https://github.com/scummvm/scummvm/commit/78859312f8e2d70002abe1001f10dbe99f6209f0
- SDL: warning "unused function 'sdlGetAttribute'" - I think introduced with https://github.com/scummvm/scummvm/commit/8afb2c1f62f518fa5872eefbd5a951b29e6ceb32
~Edit: Looks like the "sdlGetAttribute" change isn't working on all platforms. I'll have another look at it.~ _fixed_

JANITORIAL: Silence Compiler Warnings

---

engines/scumm/script_v5.cpp
engines/scumm/scumm_v5.h

It's been known for many years that Indy3 FM-TOWNS has some script/resource oversights (the PC VGA one also has its own set). We already fix some, and I hope to add more.
What's less known is that the Japanese release on the same CD *does* fix a good chunk of these issues.
So, after playing the full Japanese release from my own CD (which was… quite challenging as I can't read Japanese at all), I had a look at the script differences between the two FM-TOWNS releases, and the following was easy-enough to backport.
Basically, the English script (no. 12-132) does this:
```c
[0000] (16) Local[11] = getRandomNr(90);
[0004] (2B) delayVariable(Local[11]);
[0007] (1A) Local[12] = 0;
[000C] (9A) Local[8] = Local[7 + Local[12]];
[0013] (2B) delayVariable(Local[8]);
[0016] (16) VAR_RESULT = …
```

SCUMM: INDY3: Backport FM-TOWNS lightning effect from Japanese release

---

engines/scumm/charset.cpp

Most context is in [Trac#15931](https://bugs.scummvm.org/ticket/15931), including old saves.
Basically, it looks like, just before ScummVM 1.0.0, we had a bug (present in ScummVM 0.13.x) that could write bogus `_curId` data in the save files, for some reason (possible reasons given in the previous link). So, modern ScummVM isn't happy with that.
And, well, I have many ScummVM saves, some of them going back to (at least) 2004-2005, so then I sometimes find stuff like this 😁 
Anyway, this fix is inspired by what done in commit bd67214c96c1bb1b194cfc31abf05a08afc9cf64, back in 2007.
Putting this into a PR, so that my peers can tell if I got it right ;)
How to reproduce: load the Trac save above. (I have many more, if necessary.)

SCUMM: Fix out-of-bounds charset error with some v0.13.x saves (Trac#15931)

---

engines/grim/font.cpp

Opening the menu (F1) in a debug build triggers a crash due to an assertion failure in surface.h:
```
assert(x >= 0 && x < w && y >= 0 && y < h).
```
This problem occurs because `setPixel` is called with x equal to w. It's especially noticeable when rendering a single "Q" character, where the kerned width is 12, but the bitmap width is 14 pixels.
`getBitmapStringLength` returns the sum of character advance widths Kerning applies to spacing between glyphs not bitmap widths.
Since no subsequent glyph follows the final character, kerning is unused. Therefore the final character's bitmap width must be used This prevents `setPixel` from receiving x coordinates equal to w.

GRIM: Fix failed assertion on font rendering with TinyGL

---

engines/grim/lua/lstrlib.cpp

addnchar is effectively no-op for n==0, and it calls strncpy with 0, which is also redundant.

GRIM: LUA: Avoid unnecessary calls for empty string concatenation

---

gui/cloudconnectionwizard.cpp
gui/cloudconnectionwizard.h
gui/options.cpp

This simplifies the cloud wizard a bit:
- Skip Mode Select in setup wizard if only manual mode is available (on platforms without SDL_NET / webserver). 
- #4860 has removed the use of `kOpenUrlStorageCmd` but still left it in `options.cpp`.
- #4860 introduced `kCloudConnectionWizardOpenUrlStorageCmd` in `gui/cloudconnectionwizard.cpp` but doesn't consider the selected storage option anymore to construct the URL (despite selecting one still being required in `options.cpp`). This PR now passes the selected storage again to the opened URL as it was before.
UI Flow can also be observed at https://youtu.be/kYechxc5tvE  as discussed at https://discord.com/channels/581224060529148060/581224061091446795/1370153256176713808

CLOUD: Simplify Setup Wizard

---

engines/director/detection_tables.h

This is the italian release of Masters of the Elements, sourced from
https://editoririuniti.it/products/i-signori-degli-elementi
Built with Director 6.0.2 as well, so right now, the original Dutch release is the only one built with the older 6.0.1.

DIRECTOR: Add Italian version of Masters of the Elements to detection table

---

configure

The last version for GCC 4.x is 4.9.x, so testing for <=9 is redundant.

CONFIGURE: Remove needless condition for GCC version

---

backends/networking/curl/curljsonrequest.cpp
backends/networking/sdl_net/handlers/connectcloudhandler.cpp
common/formats/json.cpp
common/formats/json.h
gui/cloudconnectionwizard.cpp

JSON allows for keys and string values to be unicode encoded. Currently all non-ASCI characters are stripped by `JSON::untaintContents` and replaced with dots. This breaks access to files in cloud which have a unicode in the path (in my case it was `Ultima IV™`). 
This PR removes `JSON::untaintContents` and replaces it with `JSON::zeroTerminateContents` and fixes a check to ignore `char < 0` (which are all values >255 that overflow in a signed char to negative).
This was discussed also in detail on Discord earlier today: https://discord.com/channels/581224060529148060/711242520415174666/1369945380292395049. With @lephilousophe recommending changing this check instead of moving to unsigned chars.

COMMON: Fix Unicode support in JSON

---

engines/gob/save/saveload_v7.cpp

The initialization order must match exactly the order of _saveFiles.
Discovered by GCC warning on release:
```
engines/gob/save/saveload_v7.cpp: In constructor 'Gob::SaveLoad_v7::SaveLoad_v7(Gob::GobEngine*, const char*)':
engines/gob/save/saveload_v7.cpp:1466:45: warning: iteration 9 invokes undefined behavior [-Waggressive-loop-optimizations]
1466 |                 _saveFiles[index++].handler = _addy4GrundschuleHandler[i] = new FakeFileHandler(_vm);
|                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
engines/gob/save/saveload_v7.cpp:1465:27: note: within this loop
1465 |         for (int i = 0; i < 11; i++)
|                         ~~^~~~
```
Amends 7e3ec46082ea17e9666fa622d20ce41166dd985a.

GOB: Fix SaveLoad_v7 initialization

---

graphics/image-archive.cpp

During work on image caching improvements for help menu I noticed memory leaks in image-archive.cpp, this PR fixes them.
1. Surface stored in _imageCache[fname] needs to be explicitly freed as stated in Graphics::Surface *Surface::scale documentation.
2. Common::SeekableReadStream *stream needs to be properly deleted, so additional includes were added.

GRAPHICS: Fix memory leaks in image archive

---

configure
devtools/create_project/cmake.cpp
engines/alg/logic/game_bountyhunter.cpp
engines/grim/lua/lstrlib.cpp
engines/scumm/players/player_sid.cpp

Too many false-positives.
This reverts commits c613f2d4794, 03790b13500 and part of fc71b779a5a.

BUILD: Suppress stringop-overflow and stringop-truncation GCC warnings

---

engines/nancy/action/puzzle/safedialpuzzle.cpp

The select sound should play before the reset sound, instead of the reset sound twice (the first interrupted). Verified in nancy3 MHM (scene 3333) and nancy7 DOG (scene 2299).
(The actual reset sound is played in updateGraphics(). At first that seemed bad but it does not look trivial to move it elsewhere, given the kResetAnim transitions.)
Meanwhile in this PR I remove the frame number debug statement which I guess was accidentally left in. It could instead be decorated a bit and given a debug level so it doesn't always print--it's a bit noisy.
(By the way, the reset animation appears to run way too long at first, but a comment explains that we run it at ~60fps (and it does look beautiful) and in roughly the duration of the reset sound in MHM. The original game runs it at ... about 590 …

NANCY: Fix reset sound in SafeDialPuzzle 

---

engines/scumm/he/script_v72he.cpp
engines/scumm/input.cpp
engines/scumm/object.cpp
engines/scumm/room.cpp
engines/scumm/saveload.cpp
engines/scumm/script.cpp
engines/scumm/script.h
engines/scumm/script_v2.cpp
engines/scumm/script_v4.cpp
engines/scumm/script_v5.cpp
engines/scumm/script_v6.cpp
engines/scumm/script_v8.cpp
engines/scumm/scumm.h
engines/scumm/string.cpp

This is based on some words from @eriktorbjorn and @athrxx regarding some common patterns used for SCUMM enhancements.
The PR is cut in 3 commits:
1. Introduce `kScriptNumENCD` and `kScriptNumEXCD`, to some repetition for the "magical" `10002` and `10001` values for SCUMM entry/exit (ENCD/EXCD) numbers.
2. Introduce a `ROOM_VAL()`, to avoid the same magical `0x8000 + number` pattern, quite often used to access room vars.
3. Add a new `safeCurrentScriptSlotIs()` helper, that takes care of doing the `_currentScript != 0xFF` that we often miss before doing our many `vm.slot[_currentScript].number` checks (when building with UBSan, one can see that there are many cases where `_currentScript` is `0xFF`
(and some tiny adjustments here and there)
Some remarks:
* `ROOM_VAL()` is a macro because …

SCUMM: Add small helpers for shorter/safer/clearer enhancement checks

---

engines/sci/engine/vm_types.cpp
engines/sci/engine/vm_types.h

* A single function instead of call to setSegment and inline setOffset.
* Checks SCI version only once.
* Initializes _segment directly with both values instead of twice.
* Fixes -Wmaybe-uninitialized GCC warning.
This reverts commit 33643c7cc32b84dd6e2ce16a2dd7f500219ccfd9.

SCI: Improve reg_t initialization sequence

---

engines/grim/update/lang_filter.cpp
engines/grim/update/lang_filter.h
engines/grim/update/update.cpp

Fixes the following GCC warning on release build:
```
common/archive.h:353: warning: array subscript 'Common::SearchSet::__as_base [0]' is partly outside array bounds of 'unsigned char [13104]' [-Warray-bounds=]
In file included from engines/grim/update/update.cpp:23:
In destructor 'virtual Common::SearchSet::~SearchSet()',
inlined from 'virtual Common::SearchSet::~SearchSet()' at common/archive.h:353:34,
inlined from 'Common::Archive* Grim::loadUpdateArchive(Common::SeekableReadStream*)' at engines/grim/update/update.cpp:40:10:
common/archive.h:353:41: warning: array subscript 'Common::SearchSet::__as_base [0]' is partly outside array bounds of 'unsigned char [13104]' [-Warray-bounds=]
353 |         virtual ~SearchSet() { clear(); }
|                                         ^
``` …

GRIM: Use concrete types to avoid GCC warning

---

gui/gui-manager.cpp
gui/gui-manager.h

Objects could remain in the trash (unfreed) during quit. For example, hit the X or press Ctrl+C during:
Attempts to fix:
```
==77365==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 1048 byte(s) in 1 object(s) allocated from:
#0 in operator new(unsigned long) (scummvm+0xefcd4d) (BuildId: f8e86a9b42db40e7)
#1 in GUI::LauncherDialog::createSwitchButton(Common::String const&, Common::U32String const&, Common::U32String const&, char const*, unsigned int) gui/launcher.cpp:947:12
#2 in GUI::LauncherDialog::addLayoutChooserButtons() gui/launcher.cpp:938:16
#3 in GUI::LauncherDialog::LauncherDialog(Common::String const&) gui/launcher.cpp:195:2
#4 in GUI::LauncherSimple::LauncherSimple(Common::String const&) gui/launcher.cpp:1053:4
#5 in GUI::LauncherChooser::selectLauncher() …
```

GUI: Take out all the trash (fix memory leak)

---

graphics/macgui/mactext.cpp

Recent change replaced getRowCol in MacText::getMouseLink with getLineCharacter. This commits reverts it because getLineCharacter counts lines by paragraph not by rendered rows, which causes issues with clicking on links in help menu due to long text in said menu.
WIP!

MACGUI: Fix clicking on links in helpmenu

---

devtools/create_project/create_project.cpp
engines/director/lingo/lingo-lex.cpp
engines/director/lingo/lingo-lex.l
engines/hpl1/engine/libraries/newton/core/dgConvexHull4d.cpp
engines/hpl1/engine/libraries/newton/core/dgHeap.h
engines/hpl1/engine/libraries/newton/core/dgIntersections.cpp
engines/hpl1/engine/libraries/newton/core/dgMatrix.cpp
engines/hpl1/engine/libraries/newton/core/dgQuaternion.cpp
engines/hpl1/engine/libraries/newton/physics/dgBody.cpp
engines/hpl1/engine/libraries/newton/physics/dgCollisionConvexHull.cpp
engines/hpl1/engine/libraries/newton/physics/dgCollisionMesh.cpp
engines/hpl1/engine/libraries/newton/physics/dgCollisionSphere.cpp
engines/hpl1/engine/libraries/newton/physics/dgMeshEffect.cpp
engines/hpl1/engine/libraries/newton/physics/dgMinkowskiConv.cpp
engines/hypno/lexer_arc.cpp
engines/hypno/lexer_arc.l
engines/hypno/lexer_mis.cpp
engines/hypno/lexer_mis.l
engines/private/lexer.cpp
engines/private/lexer.l

Our includes must come before flex generated code to avoid macro redefinition of INTx_MIN/MAX macros.
Also make the license appear at the top of the generated file.
This PR is mostly to check MSVC result.

JANITORIAL: Fix MSVC macro redefinition warnings

---

engines/stark/gfx/opengltexture.cpp
graphics/opengl/system_headers.h
graphics/opengl/texture.cpp

This is split out from PR #4633.

STARK: Check for GL_MIRRORED_REPEAT before using it

---

engines/scumm/script_v5.cpp
engines/scumm/scumm_v5.h

When Guybrush needs to get a credit note from the storekeeper, he may pretend having various jobs; one of the options is him saying he's "waiting tables at the Scumm Bar".
But then, one of the storekeeper's lines was cut, because of a missing `WaitForMessage()` call before `endCutscene()`, in script 30-11.
So this PR tries to restore this missing call, looking at some `Var`/`Bit` context to be sure (script 30-11 is quite long and deals with various storekeeper interactions in Part 1, so I really want to avoid any bad side effect).
Releases I've tested:
Releases I've haven't tested or don't own:
How to test, with the "Restore content" enhancement setting on:
* have a nearby save, after Elaine's been kidnapped
* OR use boot param `666`, pick the fish, go at Stan's (give the fish to the …

SCUMM: Fix MI1 storekeeper line being skipped (original script error)

---

backends/graphics/android/android-graphics.cpp
backends/graphics/android/android-graphics.h
backends/graphics/ios/ios-graphics.cpp
backends/graphics/ios/ios-graphics.h
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/opengl-graphics.h
backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/openglsdl/openglsdl-graphics.h
backends/platform/libretro/include/libretro-graphics-opengl.h

This is a small fix to allow engines to use the optimum textures when 3D rendering.
I also removed the format argument from loadVideoMode as we were never using it (in 2D and in 3D).

BACKENDS: OPENGL: Fix getScreenFormat while running in 3D

---

engines/freescape/gfx_opengl.cpp
engines/freescape/gfx_opengl_shaders.cpp
engines/freescape/gfx_tinygl.cpp
engines/grim/gfx_opengl.cpp
engines/grim/gfx_tinygl.cpp
engines/myst3/gfx_opengl.cpp
engines/myst3/gfx_tinygl.cpp
engines/playground3d/gfx_opengl.cpp
engines/playground3d/gfx_tinygl.cpp
engines/stark/gfx/openglactor.cpp
engines/stark/gfx/openglactor.h
engines/stark/gfx/openglprop.cpp
engines/stark/gfx/openglprop.h
engines/stark/gfx/openglsurface.cpp
engines/tinsel/noir/spriter.cpp
engines/watchmaker/3d/render/opengl_2d.cpp
engines/watchmaker/3d/render/opengl_renderer.cpp

This is split out from PR #4633, and expanded to cover engines other than Stark.

ENGINES: Replace glColor3*/glColorPointer calls with OpenGL ES compatible calls

---

engines/sci/engine/savegame.cpp
engines/sci/engine/segment.h

Use default initialization for dummy.
```
In file included from engines/sci/engine/savegame.cpp:26:
In member function 'void Common::Serializer::syncAsUint16LE(T&, Version, Version) [with T = short unsigned int]',
inlined from 'void Common::Serializer::syncAsUint16LE(T&, Version, Version) [with T = short unsigned int]' at common/serializer.h:120:2,
inlined from 'void Sci::syncWithSerializer(Common::Serializer&, reg_t&)' at engines/sci/engine/savegame.cpp:77:18,
inlined from 'void Sci::syncWithSerializer(Common::Serializer&, Node&)' at engines/sci/engine/savegame.cpp:96:20,
inlined from 'void Sci::SegmentObjTableEntrySyncer<T>::operator()(Common::Serializer&, typename T::Entry&, int) const [with T = Sci::NodeTable]' at engines/sci/engine/savegame.cpp:136:23,
inlined from 'void …
```

SCI: Fix GCC warning

---

engines/sherlock/scalpel/scalpel.cpp

Previously, this was the only engine (besides Testbed) that directly used `initSize`, rather than relying on the common helper functions.
This has not been tested.

SHERLOCK: Use initGraphicsAny for 3DO screen resolutions

---

audio/mididrv.cpp
audio/mididrv.h

This stops "Apple Macintosh Audio" from being listed as a general purpose MIDI device, and ensures that it gets prioritised over DOS music types when available.

AUDIO: Fix order of Macintosh music types

---

backends/graphics/opengl/opengl-graphics.cpp
graphics/opengl/context.cpp
graphics/opengl/context.h
graphics/opengl/texture.h

The main addition here is support for ARGB8888, which is the preferred format for AGS in 32-bit mode, but some other formats have also been added/changed for consistency.
~TODO: Test with OpenGL ES implementations that support `GL_EXT_texture_format_BGRA8888`.~ Confirmed working on Android.

OPENGL: Add support for more pixel formats

---

backends/platform/ds/ds-graphics.cpp
backends/platform/ds/osystem_ds.cpp
backends/platform/ds/osystem_ds.h
engines/dreamweb/titles.cpp
engines/hypno/hypno.cpp

This allows engines like Dreamweb and Plumbers to handle selecting an appropriate resolution at runtime. A couple of issues within individual engines were uncovered by these changes, and the PR contains fixes for them.

DS: Support returning errors when switching to unsupported resolutions

---

engines/qdengine/qdcore/util/WinVideo.cpp
video/mpegps_decoder.cpp
video/mpegps_decoder.h

This PR attempts to fix issues I had with videos in some QdEngine games. In particular, I had two problems:
1. Audio is lagging behind video
2. Videos start with quite noticeable delay
For the 1), I figured that not enough audio packets (in relation to video packets) are being prebuffered, and so the audio can't keep up with video after playback starts. I decided to increase the number of PREBUFFERED_PACKETS.
For the 2), I've analyzed problematic videos with ffprobe, and noticed that the first video packet's pts_time is quite large (1.874 seconds), so that explains the delay. My solution is to offset both audio and video pts values, so that the first pts is zero. I've assumed that there is only 1 audio and 1 video stream per video.
This needs more testing, especially with mtropolis and …

VIDEO: Fix audio lag and delayed playback start in MPEG videos

---

engines/made/made.cpp
engines/made/music.cpp
engines/made/music.h
engines/made/scriptfuncs.cpp
engines/made/scriptfuncs.h

Macintosh music hasn't been implemented yet, but it should be relatively simple to reuse the Halestorm driver from the Kyra engine.

MADE: Split up the music player class to support other platforms

---

backends/graphics/graphics.h
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/opengl-graphics.h
backends/graphics/opengl/renderer3d.cpp
backends/graphics/opengl/renderer3d.h
backends/modular-backend.cpp
backends/modular-backend.h
common/system.h
engines/grim/gfx_opengl.cpp
engines/grim/gfx_opengl_shaders.cpp
engines/hpl1/engine/impl/LowLevelGraphicsSDL.cpp
engines/myst3/transition.cpp
engines/wintermute/base/gfx/opengl/base_render_opengl3d.cpp
engines/wintermute/base/gfx/opengl/base_render_opengl3d_shader.cpp

When 3D backends have been merged, I took the decision to use multisampling FBO to get AA rendering instead of relying on the OpenGL context having it.
This has allowed to add antialiasing to Android and iOS and avoids OpenGL context switches when a new setting is requested.
The main problem it introduces is that now, there are two distinct FBOs: one for reading and one for drawing and some engines expect to read what they just drew without issuing an updateScreen call first (to avoid polluting the display).
This PR adds a new presentBuffer call which does this offscreen rendering letting the engines read back what they have just rendered.
This has been tested with WME (fixing post filters), Grim (fixing save screenshots) and Myst III (fixing transitions).

BACKENDS: OPENGL: Fix rendering issues in 3D games when antialiasing is enabled

---

gui/launcher.cpp
gui/launcher.h
gui/widgets/grid.cpp
gui/widgets/grid.h
gui/widgets/groupedlist.cpp
gui/widgets/groupedlist.h
gui/widgets/list.cpp
gui/widgets/list.h

This PR fixes the launcher unnecessarily scrolling the list when removing a game. For a user such as myself with more than a full screen of games, this caused the list to confusingly jump around unpredictably. Now scrolling only occurs when setting a selection if the item isn't already visible, instead of always trying to re-scroll the newly selected item to the center.
While testing the scroll change, I found that list item selection doesn't work when grouping is enabled due an off-by-one bug from last year in da3c3d097c4a6e71a6385c8ad1c6736d6825c205, so that's fixed too.
This took a while to figure out because many supporting functions were named `getNextPos`, but there was nothing "next" about them, so I've renamed them.

GUI: Fixes and cleanup when removing games

---

video/mpegps_decoder.cpp

Fixes regression introduced in e00e378b24e6edad5dea5ca323445ad563161a64 by handling packets with invalid pts.

VIDEO: MPEGPS: Handle packets with invalid pts when offsetting

---

engines/awe/detection_tables.h
engines/awe/resource.cpp

Since the Amiga version is included as a bonus both with the GOG and the Steam version of the game, it would be nice if ScummVM would support it too.
This pull request adds a detection entry for it (I've made sure that it includes one file from Disk A and another from Disk B), and makes a tiny adjustment to the resource manager to ensure that 'detectAmigaAtari()` gets called for the Amiga version as well, and not just the Atari one.
I've played through the first mission, and it worked just fine. Except I can't find a way to skip the intro, which is a bit annoying.

AWE: Add detection entry for Amiga version

---

audio/midiparser_smf.cpp
audio/midiparser_smf.h
engines/mtropolis/plugin/midi.cpp

Commit debe30b25e666a1ef26a2550e6826cd1adba5810 broke the `_noteChannelToTrack` field, which in turn broke the track muting in certain parts of Obsidian.
This updates the mTropolis code to use the new `subtrack` field instead and deletes `_noteChannelToTrack`.

AUDIO: Remove obsolete note-to-track mapping and fix mTropolis usage of it

---

engines/sludge/debugger.cpp
engines/sludge/debugger.h
engines/sludge/fileset.cpp
engines/sludge/fileset.h
engines/sludge/module.mk
engines/sludge/sludge.cpp

Currently only dumping resources by name is supported, which limits this to games that store resource names.

SLUDGE: Add an initial Debugger implementation for dumping resources

---

engines/wintermute/base/base_sub_frame.cpp
engines/wintermute/base/font/base_font_truetype.cpp
engines/wintermute/base/gfx/base_surface.cpp
engines/wintermute/base/gfx/base_surface.h
engines/wintermute/base/gfx/opengl/base_surface_opengl3d.cpp
engines/wintermute/base/gfx/opengl/base_surface_opengl3d.h
engines/wintermute/base/gfx/osystem/base_surface_osystem.cpp
engines/wintermute/base/gfx/osystem/base_surface_osystem.h
engines/wintermute/ext/wme_vlink.cpp
engines/wintermute/video/video_theora_player.cpp

This was previously only supported by the OpenGL renderer. Some changes have also been made to `getPixel` and `isTransparentAt` to ensure that the surface exists when those functions are called.

WINTERMUTE: Support invalidating surfaces with the 2D renderer

---

engines/lastexpress/detection.cpp
engines/lastexpress/lastexpress.cpp
engines/lastexpress/lastexpress.h
engines/lastexpress/metaengine.cpp

The Interplay release of the game - my copy, at least - puts HD.HPF in an InstallShield archive. This pull request adapts some code from the Nancy engine to allow the game to be played without unpacking that. Instead of HD.HPF, copy the data1.cab and data1.hdr files instead.
I've only played the very beginning of the game, but didn't notice any problems that far at least.
It does print a "WARNING: File::open: node does not exist!" but as far as I can tell that's harmless.

LASTEXPRESS: Add InstallShield archive reader

---

engines/wage/POTFILES
engines/wage/detection.cpp
engines/wage/detection.h
engines/wage/gui.cpp
engines/wage/gui.h
engines/wage/metaengine.cpp
engines/wage/saveload.cpp
engines/wage/wage.cpp
engines/wage/wage.h
graphics/macgui/macdialog.cpp
graphics/macgui/macdialog.h
graphics/macgui/macmenu.cpp
graphics/macgui/macmenu.h
graphics/macgui/macwindowmanager.cpp
graphics/macgui/macwindowmanager.h

Adds a toggle for text-to-speech to the game options.
- Action log
- User input
- Command names when hovered over
- About, quit, and game over dialogs
- Names of scene objects when hovered over
- Scene name when moving to the scene
- MacGUI dialog buttons and submenu items

WAGE: Add text-to-speech (TTS)

---

engines/teenagent/teenagent.cpp
engines/teenagent/teenagent.h

Fixes text-to-speech for the Russian translation, which uses a custom encoding.

TEENAGENT: Fix Russian TTS encoding

---

engines/stark/gfx/openglssurface.cpp
engines/wintermute/base/gfx/opengl/base_render_opengl3d_shader.cpp

The documentation for `glUniform` says that "Either the i, ui or f variants may be used to provide values for uniform variables of type bool, bvec2, bvec3, bvec4, or arrays of these", however Amiga OS 4 is using int instead of bool, which makes it necessary to use the i variant for boolean variables.
This should fix [Trac #15053](https://bugs.scummvm.org/ticket/15053), but has not been tested.

ENGINES: Set boolean uniforms using integer calls for AmigaOS 4

---

engines/agi/sound_pcjr.cpp

Due to the PCjr code enforcing a square wave sign change on every
new note, fast note sequences caused a choppy or rasping sound to
be heard.
The original SN76496 chip doesn't reset either the sign or its square
wave counters on a frequency change, so this commit prevents that
from happening by properly handling "previous" frequencies and
modes when the sign and counters are reset.
Demonstration:
Before: https://vimeo.com/1094121036
After: https://vimeo.com/1094121870

AGI: Fix "choppy" sound on PCjr on fast notes

---

engines/awe/awe.cpp
engines/awe/resource_3do.cpp
engines/awe/video.cpp

This has not been tested, but should match the format used by rawgl: https://github.com/cyxx/rawgl/blob/master/systemstub_sdl.cpp#L154

AWE: Use RGB555 for 3DO graphics

---

common/str-base.h

Recent changes to operator variable type made asserts always be true.

COMMON: Remove always-true asserts on base string

---

engines/wintermute/base/gfx/base_image.cpp
engines/wintermute/base/gfx/opengl/base_surface_opengl3d.cpp
engines/wintermute/base/gfx/osystem/base_surface_osystem.cpp

This avoids needing to convert from RGB24 to RGBA32/RGBA8888, since libjpeg-turbo can directly output those formats.
~TODO: Do JPEG images need colour keys?~ @aquadran suggested on Discord that I should assume they do.

WINTERMUTE: Use setOutputPixelFormat when loading JPEG images

---

engines/wintermute/base/gfx/osystem/base_render_osystem.cpp
engines/wintermute/base/gfx/osystem/render_ticket.cpp
graphics/blit.h
graphics/blit/blit-alpha.cpp
graphics/blit/blit-alpha.h
graphics/blit/blit-generic.cpp
graphics/managed_surface.cpp
graphics/managed_surface.h

The Wintermute engine has been adapted to use it, which reduces memory usage since it no longer has to create intermediate surfaces, and should help performance during fades.

GRAPHICS: Add a ManagedSurface function for filling surfaces with blending

---

.github/vcpkg-ports/libmpeg2/0001-Add-naive-MSVC-support-to-sources.patch
.github/vcpkg-ports/libmpeg2/CMakeLists.txt
.github/vcpkg-ports/libmpeg2/portfile.cmake
.github/vcpkg-ports/libmpeg2/vcpkg.json
.github/workflows/ci.yml

Change the upstream URL for libmpeg2 to VideoLAN
The original libmpeg2 source archive is gone from SF.NET, so use the
patched libmpeg2 sources from the VideoLAN git repo instead.
Opening as a PR to check that Github actions compile the Windows builds correctly

CI: Fix libmpeg2 vcpkg source

---

common/events.h
engines/asylum/eventhandler.h

This was the root cause of a black screen with ASYLUM engine (Sanitarium) on PSP2
Fixes https://bugs.scummvm.org/ticket/15115
A casting was made in AsylumEvent() that expects 32 bits, but before this patch the cast would change the event type value thus breaking the ASYLUM engine.

COMMON: set EVENT_MAX for EventType to force size

---

configure

Although PSP2 was compiled with neon fpu parameter, SCUMMVM_NEON was not defined.
It in turn did not enabled neon paths.

BUILD: enable ARM NEON on PSP2

---

engines/bladerunner/outtake.cpp

There was a really high CPU usage when starting BladeRunner for the first time. There was in fact no frame rate limitation when playing videos. This caused a lot of calls to _vm->handleEvents(); Just call the wait() method
of FrameLimiter to prevent this.

BLADERUNNER: Wait with framelimiter in OuttakePlayer::play()

---

engines/director/castmember/palette.cpp
engines/director/castmember/palette.h

When duplicating, deep copy of palette should be made
If not it causes the `~PaletteCastMember()` to be called on both 
cast members when cleaning up the movie
If both cast members are pointing to the same palette data
then free is called on the same data twice causing problems

DIRECTOR: Fix Palette Duplication

---

backends/saves/default/default-saves.cpp
engines/testbed/config.cpp
engines/testbed/config.h
engines/testbed/fs.cpp
engines/testbed/sound.cpp

This fixes a few issues I encountered recently when working with Testbed:
- https://github.com/scummvm/scummvm/pull/6605 did not correctly handle the new setting to set non-interactive mode. It's not clear how I missed that (probably during cherry-picking for the PR). I also changed the behaviour to always run all (non-interactive) tests in non-interactive mode, as there's no way to select the tests when launching it non-interactive.
- [Trac#15754](https://bugs.scummvm.org/ticket/15754) turned out to be an issue with the test. It's not clear if this ever worked as the handling of trailing dots is in `SearchMan`, not `FSDirectory`. I checked the AGOS engine and it also uses `SearchMan`, so this should now be correct. Maybe this test pre-dates `SearchMan`?
- The `ImageAlbum` test also …

TESTBED: Fix broken tests and non-interactive mode

---

engines/awe/awe.cpp
engines/awe/detection_tables.h

The DOS version can be played in VGA or EGA mode, and that is already supported by the engine.
This PR simply enables the Renderer combobox in the GUI, with the EGA and VGA options (VGA by default)

AWE: Enable EGA/VGA renderer selection for DOS version

---

engines/ags/metaengine.cpp
engines/ags/shared/gfx/allegro_bitmap.cpp
engines/ags/shared/gfx/image.cpp
engines/ags/shared/gfx/image.h

In addition, `Image::writeBMP()` is now used for creating thumbnails.

AGS: Fix displaying thumbnails in the ScummVM GUI

---

backends/graphics/opengl/renderer3d.cpp
graphics/opengl/system_headers.h

#6651 removed the ifdefs that gated use of certain variables that aren't part of OpenGL ES2 and which aren't defined unless GLAD is used. This broke the build on Emscripten as it's targeting OpenGL ES2 and doesn't use GLAD.

BACKENDS: OPENGL3D: Fix builds with USE_FORCED_GLES and without USE_GLAD

---

backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/texture.cpp
backends/graphics/opengl/texture.h
common/util.h
graphics/blit.h
graphics/blit/blit-fast.cpp
graphics/blit/blit.cpp
graphics/module.mk

This is useful for cases where the optimal format for an engine or image codec doesn't match the optimal format for the backend, e.g. when loading PNG images with the 3DS port.
A similar fast path also existed in the OpenGL backend for use with GL 1.1 and GLES - this has been removed and the new code is used instead.

GRAPHICS: Add fast paths for converting between 32-bit pixel formats

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp

surfacesdl forces RGB565 pixel format for the hardware screen but the first supported format returned by detectSupportedFormats() may be very different (RGB565 VS ABGR8888 on PSP2 for example) thus a pixel format conversion is done at each blitting when calling SDL_BlitSurface().
On PSP2 with BladeRunner this conversion + blitting takes ~60ms. By moving the hardware screen format first on the
detectSupportedFormats() we will use RGB565 for all surfaces. By removing the format conversion on PSP2 we go down to ~2-3ms per frame.
This makes BladeRunner very playable on PSP2.
It may have a performance (positive) impact on other sdlsurface-based platforms.

GRAPHICS: Set hwFormat as first supported format in surfacesdl

---

engines/gob/detection/tables_inca2.h

cons.imd is enough for the detection. Also this change allows us the use AD_ENTRYs, 11 files are not required for an detection entry.

GOB: reduce detection files Inca2 demo entry

---

backends/keymapper/keymap.cpp
backends/keymapper/keymap.h
engines/metaengine.cpp

In previous code partial match would always be allowed, but this hides intended inputs for engines that neither define their own keymaps nor disable them on text input. The fallback engine-default keymap will no longer match partial inputs.
Tested with Space Quest 3, I mapped "Skip line" to semicolon, which produces period as the input. An input of 3 semicolons and 3 colons ("Shift + ;" on my keyboard) produced different results. Fix on left, previous behavior on right:
I proposed this on individual keymaps, and keeping partial match allowed on global and GUI keymaps as their default keys use Control or Alt modifiers.
Alternatively, we could make the entire keymapper have a single flag for this or make the default value for _partialMatchAllowed false and force devs to specify true when …

KEYMAPPER: Add keymap option for allowing patial matching.

---

backends/platform/3ds/osystem-graphics.cpp
backends/platform/3ds/osystem.h

It should be noted that with this PR, the surface returned by `lockScreen()` may have a pitch larger than `width * bpp`, so it may be necessary to fix up certain engines that make assumptions about this.

3DS: Avoid extra screen copies when no conversion is needed

---

engines/efh/efh.cpp
engines/efh/menu.cpp

Fixes what I think are a few issues that I encountered while working on text-to-speech:
- The "Give" and "Drop" actions currently only work for equipped items, making dropping or giving unequippable items impossible (which therefore locks the player out of events such as recruiting Hamlet).
- Trying to close the game when the status menu is open locks the player in the status menu. No player input is recognized at this point, and the game can only be closed by force quitting.
- When recruiting a new character to replace an existing party member, only 2 can be input, which means that the third party member can't be replaced.

EFH: Several bug fixes

---

common/path.cpp
common/path.h
engines/game.cpp

This fixes the triple Punycoding which can be witnessed with unknown variants of games having Punycoded file entries.
As our entries come are properly punycoded or not punycoded at all, it's safe to just check the prefix.
This has been tested with Wage engine (and PR #6801) by making some game entries not matching and running the detection code on the files dumped by the Dumper-Companion (Unicode and non-Unicode modes).

ENGINES: Fix unknown games report punycoding

---

engines/parallaction/balloons.cpp
engines/parallaction/callables_ns.cpp
engines/parallaction/detection.cpp
engines/parallaction/detection.h
engines/parallaction/dialogue.cpp
engines/parallaction/exec.h
engines/parallaction/exec_ns.cpp
engines/parallaction/graphics.cpp
engines/parallaction/graphics.h
engines/parallaction/gui_ns.cpp
engines/parallaction/metaengine.cpp
engines/parallaction/parallaction.cpp
engines/parallaction/parallaction.h
engines/parallaction/parallaction_ns.cpp

Adds a toggle for text-to-speech to the game options.
- Opening and end credits
- Slides
- Objects when hovered over
- Dialogue and dialogue options
- Location comments
Currently only tested with Nippon Safes, Inc.
The following hardcoded translations need verification:
- Opening credits, mouse click prompts, and intro messages in Italian, French, and German
- End credits in French and German (English translation may also need to be checked for mistranslations from the original text, which is in Italian)

PARALLACTION: Add text-to-speech (TTS)

---

doc/docportal/help/faq.rst

After seeing two separate questions on Discord about porting to consoles, I summarized @sev-'s answer ([Discord link](https://discord.com/channels/581224060529148060/581224061091446795/1380497639128305705)) as a FAQ entry.
I left out the bit about relicensing from the GPL, as it goes a bit too far in detail for a FAQ entry.

DOCS: Add FAQ entry about porting to consoles

---

audio/rate.cpp

Wintermute engine game 'Reversion 3' has 192khz mono voice samples.
To support that, interpolation conversion code needs to be updated.
Fraction point is shifted by one in fixed point value.

AUDIO: Support 192khz samples in rate conversion.

---

.github/workflows/ci.yml
backends/platform/sdl/emscripten/emscripten.cpp
configure
dists/emscripten/build.sh

This is a small set of changes:
- https://github.com/scummvm/scummvm/pull/6636 actually broke the build, I forgot to cherry-pick a include into the build
- add emscripten buld to ci.yml to avoid issues such as the above in the future
- change URLs of a52dec and mpeg2 libs from sourceforce to videolan.org 
- update of Emscripten SDK to 4.0.10 and a few other cleanups

DISTS: EMSCRIPTEN: Cleanup and fix build, add emscripten to Github CI

---

.github/workflows/ci.yml
engines/hpl1/engine/game/low_level_game_setup.cpp
engines/hpl1/engine/impl/CGProgram.cpp
engines/hpl1/engine/impl/CGProgram.h
engines/hpl1/engine/impl/LowLevelGraphicsSDL.cpp
engines/hpl1/engine/impl/LowLevelGraphicsSDL.h
engines/hpl1/engine/impl/OcclusionQueryOGL.cpp
engines/hpl1/engine/impl/OcclusionQueryOGL.h
engines/hpl1/engine/impl/SDLTexture.cpp
engines/hpl1/engine/impl/SDLTexture.h
engines/hpl1/engine/impl/VertexBufferOGL.cpp
engines/hpl1/engine/impl/VertexBufferOGL.h
engines/hpl1/engine/impl/VertexBufferVBO.cpp
engines/hpl1/engine/impl/VertexBufferVBO.h
engines/hpl1/graphics.cpp
engines/hpl1/opengl.cpp
engines/hpl1/opengl.h
graphics/opengl/system_headers.h

Disable the OpenGL case when GLES or GLES2 are forced as the code is not (yet?) compatible.
It fails to build when used without GLAD and it is useless anyway.
Also, don't fail to build when GLAD is disabled (by patching the configure script) and OpenGL mode is selected.
This PR is mostly to check for CI status.

HPL1: Fix build with GLES(2) without GLAD

---

backends/events/sdl/sdl-events.h
backends/events/sdl/sdl3-events.cpp
backends/plugins/sdl/sdl-provider.cpp
configure

This changes four things:
- Add emscripten backend to configure (to setup SDL3 manually)
- Fix `SDLPlugin` by using the correct types (doesn't compile currently with SDL3)
- Touch Events: Converting `SDL_FingerID` to `int` (in SDL2 it was signed, in SDL3 it's unsigned) to avoid an issue where on iOS devices the `id` turned negative (which we use to indicate that a finger isn't down anymore)
- Touch Events: Converting SDL3 nanosecond timestamps to milliseconds as that's what scummvm uses everywhere. This resolves an issue where simulated keypresses where not triggered as a difference between a (truncated from 64bit) uint32 and uint64 timestamp was calculated to determine the duration of a tap, as well as double clicks not being detected correctly either.

SDL: EMSCRIPTEN: SDL3 bug fixes and use SDL3 for emscripten backend

---

engines/director/cast.cpp
engines/director/lingo/lingodec/script.cpp
engines/director/lingo/lingodec/script.h
engines/director/util.cpp

While checking why the names of the lingo scripts being dumped for D5+
movies are incorrect, I realized the `castId` was being read incorrectly.
Instead of 1 we had 65537 (65536 (2^16)+1), instead of 2 we had 
65538 (65536 (2^16) + 2).  
In the hex dump of the movies I found that, the castId was a 16 bit-entry 
rather than 32-bit. The 16 bits before that were unknown and observed to 
be 0x0 for Director 4 movies and 0x1 for Director 5 movies (see screenshots below).
In each screenshot, the highlighted 32 bits are read previously as `castId`
D4 movies:
D5 movies:
Also fix the script type being written in the filename of the dumped lingo scripts.
The script must be associated with a cast member. If the cast member is `ScriptCastMember` 
the script type is given by …

DIRECTOR: Read `castId` in `Scripts::read()` as 16bit and dump scripts with correct names

---

engines/nancy/misc/hypertext.cpp

Fixes assertion fail for Nancy Drew 2 when calling Dwayne Powers (late into the game)
This bug was reported here: https://bugs.scummvm.org/ticket/16112

NANCY: Don't pop from empty newlineTokens list

---

common/path.h

[Python's Path class](https://docs.python.org/3/library/pathlib.html#parsing-and-generating-uris) overrides the division `/` operator to append path components.
I think it's much more readable than using `appendComponent()`.

Add operator/, +, and += as an alternatives to Path::join, append, and appendInPlace

---

audio/decoders/raw.cpp
audio/decoders/vorbis.cpp
base/commandLine.cpp
base/version.cpp
common/scummsys.h
configure

The WinCE port was removed in PR #1931, but we still had some old hacks for it.
This PR consists in 3 changes:
1. Drop [Tremolo](http://wss.co.uk/pinknoise/tremolo/) support (= an old Tremor fork with some ARM optimizations).
* AFAICS, it was only used by the WinCE port, and it has no other consumer.
* **Possible objection:** maybe some old ARM port could still benefit from it? 
2. There's an old macro hack in `audio/decoders/raw.cpp` that was introduced [more than 20 years ago](https://github.com/scummvm/scummvm/commit/c55652d4a60ee51dde381417c590fff9a59ecb0d), for the ancient compilers used by the earliest WinCE builds.
* My commit just adds a `// TODO` mentioning that the macro hack could maybe be removed in favour of the original template usage. I'm not adding such template use …

BUILD: Drop WinCE remnants and old hacks

---

engines/bladerunner/vqa_decoder.cpp
graphics/blit.h
graphics/blit/blit-fast.cpp
graphics/blit/blit-neon.cpp
graphics/blit/blit.cpp

On ARM devices with low compute power like the PSP2 we can drastically improve performance by using ARM NEON instructions.

GRAPHICS, BLADERUNNER: add ARM NEON blitting and use it for VQADecoder

---

audio/adlib_ms.cpp
audio/mt32gm.cpp

This one is a bit weird…
If one does a RISC OS build this way (note: it uses GCC 4.7):
```
$ ./devtools/docker.sh toolchains/riscos
```
then you may get this linking error:
```
LINK     scummvm,e1f
audio/libaudio.a(adlib_ms.o): In function `MidiDriver_ADLIB_Multisource::initOpl()':
adlib_ms.cpp:(.text+0x5a5c): undefined reference to `MidiDriver_ADLIB_Multisource::OPL2_NUM_CHANNELS'
adlib_ms.cpp:(.text+0x5a60): undefined reference to `MidiDriver_ADLIB_Multisource::OPL3_NUM_CHANNELS'
audio/libaudio.a(mt32gm.o): In function `MidiDriver_MT32GM::initControlData()':
mt32gm.cpp:(.text+0xde8): undefined reference to `MidiDriver_BASE::MT32_PITCH_BEND_SENSITIVITY_DEFAULT'
mt32gm.cpp:(.text+0xdec): undefined reference to `MidiDriver_BASE::GM_PITCH_BEND_SENSITIVITY_DEFAULT'
collect2: error: ld …
```

AUDIO: Fix linking errors in some setups with older compilers

---

engines/gob/detection/detection.cpp
engines/gob/detection/detection.h
engines/gob/draw.h
engines/gob/draw_fascin.cpp
engines/gob/draw_playtoons.cpp
engines/gob/draw_v1.cpp
engines/gob/draw_v2.cpp
engines/gob/game.cpp
engines/gob/gob.cpp
engines/gob/gob.h
engines/gob/hotspots.cpp
engines/gob/hotspots.h
engines/gob/inter_v1.cpp
engines/gob/metaengine.cpp
engines/gob/mult.cpp
engines/gob/util.cpp
engines/gob/videoplayer.cpp

Adds a toggle for text-to-speech to the game options.
- Dialog
- Names of objects when hovered over
- Menus
- Popup information
Currently only tested with interactive demos for Ween and the Goblins games, and non-interactive demos.

GOB: Add text-to-speech (TTS)

---

backends/platform/ios7/ios7_app_delegate.h
backends/platform/ios7/ios7_app_delegate.mm
backends/platform/ios7/ios7_scene_delegate.h
backends/platform/ios7/ios7_scene_delegate.mm
backends/platform/ios7/module.mk

UIScene is Apple's solution to support multiple windows for an iOS
application. A scene represents an instance of the applications UI.
ScummVM is a single window application and does not make use of the
scene concept. It is however mandatory to implement it since the next
major release following iOS 26 will require it.
https://developer.apple.com/documentation/technotes/tn3187-migrating-to-the-uikit-scene-based-life-cycle
The application life cycle delegate functions are handled as following
by the iOS versions::
version < iOS 13
applicationDidBecomeActive(_:)
applicationWillResignActive(_:)
applicationDidEnterBackground(_:)
applicationWillEnterForeground(_:)
version >= iOS 13
UISceneDelegate
sceneDidBecomeActive(_:)
sceneWillResignActive(_:)
sceneDidEnterBackground(_:) …

IOS7: Migrate to the UIKit scene-based life cycle 

---

engines/hugo/mouse.cpp

While testing TTS for the Hugo engine I was met with an annoying bug. When the mouse moves to the top of the screen it shows a top menu. Clicking outside of this top menu, or pressing escape should close the menu, but this does not work. This was actually already reported several years ago in [bug #12621](https://bugs.scummvm.org/ticket/12621).
The top menu is actually a GUI::Dialog. While it is shown the engines does not receive any event. In particular it does not get the mouse move events. As a result, as soon as the menu is closed, it thinks the mouse cursor is still in the top area, and reopens the top menu immediately (unless there is a pending mouse move event that updates the mouse position before it is checked again).
The solution in this pull request is very simple: when the top …

HUGO: Fix top menu not closing when it should

---

engines/dragons/actor.cpp
engines/dragons/actor.h
engines/dragons/actorresource.h
engines/dragons/credits.cpp
engines/dragons/cursor.h
engines/dragons/cutscene.h
engines/dragons/dragonflg.h
engines/dragons/dragonimg.h
engines/dragons/dragonini.h
engines/dragons/dragonobd.h
engines/dragons/dragonrms.h
engines/dragons/dragons.cpp
engines/dragons/dragons.h
engines/dragons/dragonvar.h
engines/dragons/font.h
engines/dragons/inventory.h
engines/dragons/metaengine.cpp
engines/dragons/midimusicplayer.h
engines/dragons/minigame1.h
engines/dragons/minigame2.cpp
engines/dragons/minigame2.h
engines/dragons/minigame4.cpp
engines/dragons/minigame4.h
engines/dragons/minigame5.cpp
engines/dragons/minigame5.h
engines/dragons/sound.h
engines/dragons/strplayer.cpp

This avoids the inclusion of large system headers in all files (e.g. system.h), and fixes compilation with MSVC, which would not compile this engine without enabling language extensions, as system headers were included in the wrong order
Creating this as a PR to check that the engine still builds correctly in all builders

DRAGONS: Clean up and reorganize includes

---

engines/macventure/gui.cpp
engines/macventure/gui.h
engines/macventure/image.cpp
engines/macventure/image.h
engines/macventure/macventure.cpp

This adds support for the MacVenture title screens, both StartupScreen (which would originally be shown when booting the computer from the game floppy) and the actual title screen. Deja Vu II only has the latter. I have tested this with the Zojoi re-releases. There is code for handling the older PACK format as well, but someone else will have to test and fix that if needed.
I had to change the 32-bit bit reader to an 8-bit one, because the length of the title screen PPIC isn't a multiple of 4.
How long the title screens should be displayed is debatable. You can skip them with ESC, but I think they set a nice mood. Though now I can't unsee how sloppily they painted over their old address for Uninvited...

MACVENTURE: Add title screens

---

engines/wage/combat.cpp

Currently, combat in the World Builder games appears to be quite broken, and this is a central game mechanic in many of them:
- I have yet to see a fight that didn't end as soon as either you or your opponent lands a hit.
- On winning a fight, your experience goes down instead of up.
I think the problem is a simple mix-up. The `Context` class has two sets of variables:
```
int16 _userVariables[26 * 9];
int16 _statVariables[18];
```
The `StatVariabe` enum has 18 values from 0 through 17. It seems reasonable to assume that they should only be used as indexes into `_statVariables`, so I've changed the few cases where they were used with `_userVariables` instead. Doing that seems to fix both issues. Note that there are still a number of "TODO" comments in combat.cpp, but I have no idea how to …

WAGE: Make combat less broken (bug #16194)

---

engines/made/detection.h
engines/made/detection_tables.h
engines/made/made.cpp
engines/made/made.h
engines/made/metaengine.cpp
engines/made/screen.cpp
engines/made/screen.h
engines/made/scriptfuncs.cpp
graphics/cursorman.cpp
graphics/cursorman.h

The Windows port of the MADE engine handles cursors through the usual
Win16 API, unlike the MS-DOS version which provides its own cursor
handling system.  Mouse cursors are stored in the MADE .exe file and
loaded at startup.  For Rodney's Funscreen, this is just the "hand"
cursor in-game, though others (e.g. a lightning bolt) are in the .exe too.
This PR allows using the Windows cursors in place of the lower-resolution
data file MS-DOS cursors, if the .exe is present alongside the data files.
Both the Windows and Tandy VIS executables work for this.
Note also this exposes the `dontScale` flag for `replaceCursor()`
in CursorMan.c - though the default is "false".

MADE: Allow using Win16 cursors for Rodney's Funscreen

---

engines/alcachofa/POTFILES
engines/alcachofa/graphics-opengl.cpp

`OSystem::messageBox` isn't implemented on many platforms, and is only really meant to be a last resort in case the GUI wasn't able to handle an error that would cause ScummVM to exit.
The error message string has also been marked as translatable.

ALCACHOFA: Use ScummVM GUI dialogs instead of OS message boxes

---

engines/hpl1/detection_tables.h

This commit expands detection for version 1.1.1 of the mac release by adding the Steam version's info.
This builds off of the work of pull request #6916.
Note that I have not personally tested this.

HPL1: Add detection entries for Mac Steam release

---

engines/hpl1/detection_tables.h

This adds a Steam Mac entry for Penumbra: Black Plague

HPL1: Add detection entry for Black Plague

---

engines/agi/detection_tables.h
engines/agi/text.cpp

I found that RTL is not working as properly in "display" method. In AGI games most of the messages are displayed using "print" method. But in kq1 - there are 2 cases where the game uses "display" method.
The cursor X position is sent by game logic.
I changed the position in RTL to be display frame size (40) minus position, minus text size.
In addition I had to change the game checksum due to small fixes.
Thanks.

AGI: fix display method on RTL language and update kq1 Hebrew fan made checksum 

---

engines/toon/script_func.cpp

Greetings, ScummVM community.
The other day, I decided to replay the wonderful adventure game Toonstruck and was disappointed by the Gift-O-Matic machine sequence. It moved very slowly and was easily passed on the first try. But from my childhood, I remembered being stuck on it for several days. This prompted me to download the ScummVM source code and build it (which turned out to be a separate multi-day quest in itself). (If I manage to improve the build process, I might write a more up-to-date tutorial on the wiki on how to build ScummVM from VS Code). I then started debugging the engine.
Through trial and error, hacking my way through the dense jungle of code (it's starting to feel like Monkey Island in here), I eventually stumbled upon the section that was preventing this puzzle from …

TOON: Fix very slow Gift-O-Matic animation

---

engines/director/lingo/lingo-builtins.cpp
engines/director/lingo/lingo-events.cpp

Resolve some compiler warnings in Director (GCC 10.2, Debian 11 Bullseye):
- Use `uint` as loop variable to avoid signed/unsigned mismatches
- Rename variables named `inst` to `instance` to avoid shadowing of `typedef inst` from `lingo.h`

JANITORIAL: DIRECTOR: resolve compiler warnings

---

engines/scumm/he/sprite_he.cpp

Convert some C-style casts to `const_cast` to silence `-Wcast-qual` warnings (GCC 10.2, Debian 11 Bullseye) about casting away qualifiers.

JANITORIAL: SCUMM: HE: use const_cast

---

engines/nancy/action/puzzle/tangrampuzzle.cpp

```
ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete)
...
#1 0x55907bd0818e in Nancy::Action::TangramPuzzle::Tile::~Tile() engines/nancy/action/puzzle/tangrampuzzle.cpp:421:2
...
```

NANCY: Fix alloc-dealloc-mismatch in tangrampuzzle

---

engines/hypno/actions.cpp
engines/hypno/arcade.cpp
engines/hypno/boyz/arcade.cpp
engines/hypno/hypno.cpp
engines/hypno/hypno.h
engines/hypno/scene.cpp
engines/hypno/spider/spider.cpp
engines/hypno/spider/talk.cpp
engines/hypno/wet/arcade.cpp
engines/hypno/wet/hard.cpp

This fixes [Trac #13268](https://bugs.scummvm.org/ticket/13268), although there are still a number of missing sound effects. Only tested with the demo of Spider-Man: The Sinister Six.

HYPNO: Fix playing music during cutscenes
