scummvm/scummvm

base/main.cpp
engines/engine.cpp
engines/engine.h
engines/scumm/saveload.cpp
engines/scumm/script_v6.cpp
engines/scumm/scumm.cpp
engines/scumm/scumm.h

Here is one possible way of supporting the Maniac Mansion easter egg in Day of the Tentacle, by adding a mechanism where instead of returning to the launcher dialog, it automatically launches another game. Optionally with a save game slot to load on startup.
So to start Maniac Mansion it first creates a temporary savegame, using the hitherto unused (I think) save slot 100, adds Maniac Mansion and itself to the "chained games" list and forces a return to the launcher. Manually returning to the launcher from Maniac Mansion resumes Day of the Tentacle at the temporary savegame.
It detects Maniac Mansion by looking if the ScummVM config file contains any game that is in a "Maniac" sub-directory of the current game. Since this may not always work, it also checks for an "easter_egg" config …

Day of the Tentacle easter egg

---

common/endian.h
common/stream.h
test/common/endian.h
test/common/memoryreadstream.h
test/common/memoryreadstreamendian.h

The concept is rather self explanatory. There are however, some potential problems:
1. First, I need someone to help me figure out if there is a mips instruction for 64 bit swap, and if so, help me write the asm
2. clone2727 brought up the point that int64 can be disabled in configure. If int64 is disabled, this code will fail to compile. There are a couple choices
1. Surround this code with #ifdef guards. This isn't the best solution because any engines that use the code will now be restricted to backends that allow int64.
2. Are there actually backends that don't have support for int64? If not, then we could remove the option to disabled int64 in configure
Let me know if you have any questions and feel free to comment.

COMMON: Add support for endian-safe reading/writing of int64

---

engines/scumm/help.cpp

This adds two new pages for the Help of Fate of Atlantis, for the missing "i" (IQ Points/Inventory toggle) and "f" (Keyboard Fighting toggle), and also the Fighting controls shared with Indy 3, with Sucker Punch added.

SCUMM: Improve FOA keyboard help

---

engines/mortevielle/dialogs.cpp
engines/mortevielle/graphics.cpp
engines/mortevielle/utils.cpp

Hi,
This is a patch for the following problems:
- The boxes are 1 pixel bigger in the DOS game. I fixed the drawBox() method to match original code.
- Also, alerts are missing the first character. So I fixed the show() method changing base string read index.
Thanks!

MORTEVIELLE: some display bugs fixed

---

engines/mortevielle/mortevielle.h
engines/mortevielle/mouse.cpp
engines/mortevielle/utils.cpp

Hi,
This is the 3rd part of the intro which is currently not handled by the code.
This message is displayed during disk access, so it may not visible as is in ScummVM version as things are quite fast nowadays, a delay is required. Also delay should hide the mouse to prevent frozen screen.
Thanks!

MORTEVIELLE: Added missing mesgId handling for 3rd intro screen

---

engines/mortevielle/actions.cpp
engines/mortevielle/mortevielle.h
engines/mortevielle/outtext.cpp
engines/mortevielle/utils.cpp

Hi,
Here is the code to display the inter screen messages. They are the small introduction messages shown while loading the next scene. I use a delay() to simulate the disk access delay.
Still don't know what is the _is variable but is seems to be used for this kind of messages.
Voila.
Thanks
Chris

MORTEVIELLE: added missing inter screen messages

---

backends/fs/amigaos4/amigaos4-fs.cpp

To keep consistency with the original code i re-added the DosList feature dol_Port (which was taken out due to a compiler error using SDK 53.24 and was named wrong anyway).
It offers a message port for the DosList.

AMIGAOS: Re-add a DosList feature

---

engines/mortevielle/utils.cpp

Hi,
This has been checked against french and german versions. “Your are alone” text isn’t centred in original code.
Thanks!

MORTEVIELLE: fixed text position

---

common/fft.cpp
common/fft.h

This change to the FFT class is needed by the WMA decoder from xoreos we intend to merge in ResidualVM in PR https://github.com/residualvm/residualvm/pull/1128.
The common code in ResidualVM is updated from time to time from ScummVM. The intent behind this PR is not to introduce differences for the FFT class between ScummVM and ResidualVM to keep the update process simple for this class.
The changes are simple and should not prove difficult to maintain.

COMMON: Add getRevTab to FFT

---

engines/wintermute/base/base_file_manager.cpp

In Dead City, WinterMute loads the wrong font (outline_red2.font) instead of outline_white.font, which is used by the original. This is a Windows-only issue. 
It seems that calling getParent returns trailing '\' which is absent on POSIX based file systems but not on Windows. This causes Wintermute to load outline_red2.font from russian.dcp, which is not desired.  This is fixed by calling it->getName() directly, which returns the folder name (without the trailing '\').

WINTERMUTE: Fixed parentFolder name check, Fix bug #6655 (Dead City - hotspot text issue)

---

engines/wintermute/base/base_keyboard_state.cpp
engines/wintermute/base/base_keyboard_state.h

Fix bug #6654 (white chamber - some keys don't work)
Wintermute games on ScummVM used SDL keycodes for keyboard mapping, wheras
the game scripts only accept VKeyCodes of Windows. Therefore an initial
set of mappings are added and the debug room is now loading properly, when
HOME is pressed (Rest of the keys need to be tested in-game)

WINTERMUTE: Added mappings for VKeyCodes->ScummVM KeyCodes

---

engines/drascula/actors.cpp
engines/drascula/talk.cpp

Fix bug #5903 DRASCULA-IT: Crash/graphic glitch at castle towers
http://sourceforge.net/p/scummvm/bugs/5903/
The problem was that if you looked at the tower Hacker's head started flying on the screen with the subtitle and the game crashed.
Now I fixed it: the game is not crash, there is no flying head and the subtitle is fixed on the screen upper-center.

DRASCULA: fix crash/graphic glitch at castle towers

---

backends/graphics/openglsdl/openglsdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h

This fixes an issue when switching to the OpenGL renderer on Windows 8 and later. On those systems, SDL seems to only detects 32bpp modes for fullscreen OpenGL. 
In the OpenGL renderer, we call SDL_ListModes with NULL as the format argument. This causes SDL to use the currently selected screen format as a base to list available modes. On initial load, this format is set to the "best" available (32bpp).
This results in the following behavior:
- When ScummVM starts in OpenGL mode, the available modes will be listed using 32bpp. Initialization will succeed.
- When ScummVM starts in non-OpenGL mode, the available OpenGL modes are also listed using 32bpp. The SDL surface renderer then switches the video mode to 16bpp. When switching to OpenGL later, the OpenGL graphics manager is initialized …

Fix crash and wrong fullscreen mode listing when switching to OpenGL

---

engines/sword25/fmv/movieplayer.cpp

This fixes the problem that the movies are played too fast
and get out of sync with additionally played speech samples.
This can be tested by watching the intro movies: In the plane, George should start talking about Nico once he is shuffling his papers on the tray. Without the bug fix, the movie plays on my system with twice the speed and he starts talking much later. Additionally, the audio track of the movie gets out of sync with the video, too.

SWORD25: Delay next movie frame by videoDecoder.getTimeToNextFrame()

---

configure

Not sure if there is any interest in this ("never change a running system"), but here it is anyway:
This PR adds a new function `append_var` to the `configure` script, which allows replacing constructs like
```
LDFLAGS="$LDFLAGS -static-libgcc -static-libstdc++"
```
by
```
append_var LDFLAGS "-static-libgcc -static-libstdc++"
```
or even
```
append_var LDFLAGS -static-libgcc -static-libstdc++
```
The goal is to improve readability and reduce "code duplication", and thus to reduce the risk of introducing certain bugs, like these two made-up ones:
```
LDFLAGS="$LDFLAG -static-libgcc -static-libstdc++"
CXXFLAGS="$CPPFLAGS -diag-error 10006,10148"
```
I also made sure constructs like this keep working correctly (i.e. the variable `srcdir` is not expanded prematurely):
```
append_var INCLUDES …
```

CONFIGURE: add and use append_var function

---

common/scummsys.h
devtools/README
devtools/create_project/create_project.cpp
devtools/create_project/msbuild.cpp
devtools/create_project/msbuild.h
devtools/create_project/msvc.cpp
devtools/create_project/msvc.h
devtools/create_project/msvc14/create_project.sln
devtools/create_project/msvc14/create_project.vcxproj
devtools/create_project/msvc14/create_project.vcxproj.filters
devtools/create_project/visualstudio.cpp
dists/msvc14/create_msvc14.bat
dists/msvc14/readme.txt

This is a modified version of Templier's previous pull request for adding support for Visual Studio 2015. It only introduces a single new warning 4267 to deal with the numerous spurious warnings of conversion of 'size_t' to 'type'. It also fixes extra warnings that were being generated due to exception handling.
I've also taken the liberty of recompiling all the required libraries, since the ones Templier provided were causing link warnings due to differences in the runtime libraries. Compiled libraries can be  located here:
Visual Studio 2015 libraries and includes:
http://sourceforge.net/projects/scummvm/files/build/scummvm_libs_2015.zip/download
Similar libraries for Visual Studio 2013 and earlier:
http://sourceforge.net/projects/scummvm/files/build/scummvm_libs_2013.zip/download

CREATE_PROJECT: Add support for Visual Studio 2015

---

engines/cine/cine.cpp
engines/cine/cine.h

This simply shows the Sony splash screen included with the CD version of Future Wars. I think it does all the necessary sanity checking and cleanups, though some might find it a bit hackish.

CINE: Show splash screen in CD version of Future Wars

---

engines/neverhood/menumodule.cpp
engines/neverhood/menumodule.h

If you have a list of savegames with a gap in the middle:
neverhood-win.000
neverhood-win.001
neverhood-win.003
loading a savegame after the gap will cause a crash.
This is caused by a confusion in the code between ScummVM's slot (3 in this case),
and the index in the engine's savegame array.

NEVERHOOD: Don't crash when loading savegames with a high slot ID

---

engines/neverhood/modules/module2700.cpp
engines/neverhood/modules/module2700.h

This is a possible fix for a glitch in The Neverhood that in some cases causes the car to move up even though you're clicking on a spot below it. I'm not sure if it's the correct fix, but I couldn't find any developer familiar with the engine to discuss it with. And even if it's the correct fix, it's possible that the same reasoning also applies to other parts of the code.
There is an overly long commit message that explains the details, as I understand them, but the short version is that a message is sent to the car with the coordinate to travel to, but it only has an X coordinate. The Y coordinate is always zero.

NEVERHOOD: Possible fix for bad car behaviour

---

engines/wintermute/base/font/base_font_truetype.cpp
engines/zvision/text/truetype_font.cpp
graphics/fonts/ttf.cpp
graphics/fonts/ttf.h
gui/ThemeEngine.cpp

Loading a TrueType font currenly requires specifying the point size. The point size not always a very handy metric. This pull request adds an extra parameter "sizeMode" to the font loading method allowing to give the size as the desired height in pixels.
The matching between point sizes and heights is done according to the metrics tables embedded in fonts. The matching algorithm is the same as the one used in Wine (though no code used here comes directly from Wine).
ZVision is changed to use the new size mode, removing a minor hack.
This code is likely to be used by @clone2727's Buried engine. It will also be used in some other engine soon to land in ResidualVM.

GRAPHICS: TrueType font creation from character height

---

configure

This PR does two related things:
It disables gcc mode, even if ICC is set to gcc-compatibility mode, since it doesn't accept all of the gcc command line options that we use.
It also adds custom version checking code for clang, since previously we output the version of gcc that clang is pretending to be.
I've tested this only on Linux, with gcc 4.8.3, gcc 4.9.3, clang 3.4.2, clang 3.7.0, icc 11.1, icc 15.0.2.

Improve compiler version checks

---

configure

OpenGL(ES) is the best rendering method on the Raspberry Pi host now that it's mature enough, so it's good idea to have it enabled.

SDL/GL Enabled OpenGL(ES) on the Raspberry Pi in the configure script.

---

.gitignore

This commit adds all temporary .opendb files to the .gitignore file.
.opendb files are generated by Visual Studio 2015 during compilation. They are hidden in the file system and seem to be temporary.

DEVTOOLS: Ignore *.opendb files generated by VS 2015

---

configure

Reasons:
- Shared objects aren't really shared on AmigaOS.
(Once two programs load the same .so, it will be available twice in memory, instead of sharing the already available one)
- To make the program run for everyone i need to provide a subdir (SObjs/) which holds all the .so's used while compiling (which are not available in a clean OS install), otherwise most people have to go hunting for the correct .so's online.
Even worse is the fact that, if users have older (incompatible) .so's installed, they might experience crashes.
- There is no benefit in building ScummVM with shared objects (at least on AmigaOS), because even *if* a new lib version (i.e. libPNG) would be made available as an .so (and features new stuff), it won't be mandatory to immediately switch to it, because ScummVM …

AMIGAOS: Static builds preferred

---

engines/sci/console.cpp
engines/sci/engine/kernel.h
engines/sci/engine/kernel_tables.h
engines/sci/engine/kgraphics.cpp
engines/sci/engine/kgraphics32.cpp
engines/sci/engine/kpathing.cpp
engines/sci/engine/kvideo.cpp
engines/sci/engine/savegame.cpp
engines/sci/engine/state.cpp
engines/sci/engine/state.h
engines/sci/graphics/frameout.cpp
engines/sci/graphics/frameout.h
engines/sci/graphics/maciconbar.cpp
engines/sci/graphics/palette.cpp
engines/sci/graphics/palette.h
engines/sci/graphics/palette32.cpp
engines/sci/graphics/palette32.h
engines/sci/module.mk
engines/sci/sci.cpp
engines/sci/sci.h

This PR includes implementation of the kPalCycle opcode, partial transcription of kSetPalStyleRange (commented out, since more work needs to be done in order to architect palette code to match the SCI32 architecture before it can be implemented), and some stubs for other parts of palette code from SCI32. This work is based on SQ6DOS disassembly.
There is also a small patch to scummsys.h to fix some warnings clang was emitting about redefined constants.
I’ll accept any feedback to improve the PR/fix problems in the code. Apologies that some things are interleaved into commits a little weirdly; if needed I can try to rewrite the commits to group functionality a little bit better. This was just an artefact of getting stuck and switching between multiple different features in the code. …

SCI32: palette management (full kPalCycle, partial kSetPalStyleRange and kPalFade)

---

engines/sci/detection.cpp
engines/sci/engine/kernel.h
engines/sci/engine/kernel_tables.h
engines/sci/engine/kgraphics32.cpp
engines/sci/engine/kmisc.cpp
engines/sci/engine/savegame.cpp
engines/sci/engine/savegame.h
engines/sci/graphics/frameout.cpp
engines/sci/graphics/frameout.h
engines/sci/graphics/helpers.h
engines/sci/graphics/palette.cpp
engines/sci/graphics/palette.h
engines/sci/graphics/palette32.cpp
engines/sci/graphics/palette32.h
engines/sci/sci.cpp
engines/sci/sci.h

I verified this does not break builds without `ENABLE_SCI32` this time! :), and tested against most of the rooms in SQ6 that call kPalVary.
Fades of the Sierra logo and SQ6 title screen are working correctly, but fades between rooms requires at least an implementation of `kSetShowStyle`, so I will probably do that next. kPalVary also appears to be working (in most SQ6 rooms it is used to lighten/darken Roger when he walks near light sources), but there are some lingering palette colour issues; based on a brief conversation with @lskovlun it sounds like Remap probably needs to be implemented for those to be fixed, but it is possible there are still a couple bugs in kPalVary. SQ6 only uses subops 0 (2, 3, and 5 arguments), 1 (1 and 2 arguments), and 3 so it would be great if someone could …

SCI32: kPalVary, kPalette fade support, kPalette findColor support, improvements to game time management

---

po/de_DE.po

This updates the German language file. Two SCI related strings are
added, one string that was not entirely clear is updated and fixed.
de_DE.po is now based on scummvm.pot as of commit
94207fbfb7a9090280c93f199a006e400aef6c24.

I18N: Update German translation

---

README

- Sorted "3.0) Supported Games" in alphabetic order and moved the none specific game parts to the bottom of that chapter
- Sorted "5.0) Running ScummVM" in alphatic order and adapted all references
- Added "Discworld II notes" to "3.0) Supported Games"
- Added "Nippon Safes Inc. Amiga notes" to "3.0) Supported Games"
- Added "Zork games notes" to "3.0) Supported Games"
- Added "Datafiles" to "3.0) Supported Games"
- Added "AmigaOS4" in "9.0) Compling"
- Added "Amiga/Macintosh" to "3.14) The Feeble Files notes"
- Added lots of missing subchapters to the main chapter list in "7.0) Music and Sound)"
- Changed "Maniac Mansion" title to better reflect the contents

Update README and consistency fixes

---

NEWS
README
backends/events/sdl/sdl-events.cpp
engines/scumm/input.cpp

This moves handling of Alt-x to quit ScummVM to the SCUMM engine. cbd867329e018d7eca12b3a8842e52b8db9f494d suggests which is why it was added in the first place.
Alt-x is used in AGI's Leisure Suit Larry in the Land of the Lounge Lizards to skip the age protection. This pull request assures that this works on our ports formerly using Alt-x to quit ScummVM.
The README is updated accordingly and the changes are also mentioned in the NEWS file.

Handle Alt-x internally in SCUMM.

---

engines/sword25/util/lua_persistence_util.cpp
engines/sword25/util/lua_persistence_util.h
engines/sword25/util/lua_unpersist.cpp

The call to lua_growstack in unpersistThread would unconditionally at
least double the size of the stack. This caused memory usage to grow
exponentially (literally) with the number of serialized threads.
Bugs #6977, #6999.

SWORD25: Use more appropriate function for growing the stack

---

NEWS
README
backends/fs/posix/posix-fs.cpp
backends/fs/posix/posix-fs.h
backends/platform/sdl/posix/posix.cpp
backends/platform/sdl/posix/posix.h
backends/saves/posix/posix-saves.cpp

This patch makes our POSIX ports use locations for configuration, log, and save games conforming to the XDG Base Directory Specification version 0.8 (right now the latest version, which can be found [here](http://standards.freedesktop.org/basedir-spec/basedir-spec-0.8.html)).
The new locations are as follows:
* Configuration file is now placed at `$XDG_CONFIG_HOME/scummvm/scummvm.ini`
* New default savegame directory is at `$XDG_DATA_HOME/scummvm/saves/`
* The log file is now placed at `$XDG_CACHE_HOME/scummvm/scummvm.log`
We still use the old locations for the configuration file and the savegame directory if those exist from a previous ScummVM installation.
This 'fixes' bug [#6036 POSIX: Use XDG dirs instead of HOME](https://sourceforge.net/p/scummvm/bugs/6036/). There is some discussion …

POSIX: Follow XDG Base Directory Specification for User's Files

---

doc/de/Liesmich
doc/de/Neues

This changes the release titles of supported games from the English original titles to the German ones.
I hope that I'm not too late for getting this merged in the 1.8.0 branch.

I18N: Use German release titles in NEWS and README

---

doc/de/Liesmich
doc/de/Neues

This PR addresses quite a lot of issues with the German README file ("Liesmich"). All the changes are brought to you by @SimSaw, thank you!
We also included the planned release date of ScummVM 1.8.0 to the German NEWS file.
Because getting the documentation ready for ScummVM 1.8.0, I pushed this to the 1.8 branch, but it would be great if someone could cherry pick those commits and merge them into the master branch.

Getting German documentation ready for 1.8.0

---

dists/ios7/Info.plist
dists/ios7/Info.plist.in

These keys are automatically added by Xcode when one compiles a regular Xcode project, but are missing when compiling from the command line.

IOS: Adds support for iPad

---

engines/wintermute/base/file/base_disk_file.cpp

Carol Reed 5 (the full game, data.dcp hash
27b3efc018ade5ee8f4adf08b4e3c0dd) appears to refer to the absolute path
"f:\dokument\spel 5\demo\data\scenes\credits\op_cred_00\op_cred_00.jpg"

WINTERMUTE: Add workaround for bug #7067

---

engines/lab/processroom.cpp

LAB: Fix bug #7022 - Events not processed during ending sequence.

LAB: Process events during ending sequence

---

engines/sword25/gfx/animationresource.cpp
engines/sword25/gfx/fontresource.cpp
engines/sword25/gfx/text.cpp

(Look https://sourceforge.net/p/scummvm/bugs/6980/)
The warning messages were appearing because when PRECACHE_RESOURCES is
not defined, ResourceManager's `requestResource()` was used to manually
"cache" them. When you do that, ResourceManager "locks" the resource
once, so you must `release()` it later.
Resources were not released, and warnings appeared. When you
`release()` resource, it still is loaded ("cached"). Resource's
`getLockCount()` is 0, though, so it might be unloaded by
ResourceManager if there is a lot of resources.

SWORD25: Fix "Resource not released" warnings [GSoC]

---

engines/wintermute/base/file/base_disk_file.cpp

This one adds a commit on top of #695, it's the result of a few words exchanged with @somaen.
It replaces the large if(){} block which only grew larger in #695 with a loop.
See if it turns out useful.

WINTERMUTE: Rewrite absolute prefix workarounds block with loop

---

engines/sword25/POTFILES
engines/sword25/detection.cpp
engines/sword25/package/packagemanager.cpp
engines/sword25/package/packagemanager.h

When selecting a non-English language, the scripts default to using
German voices. This commit adds an option to allow using English
voices instead. This is done by editing the file path on the fly. This
implements [bug #6804 - SWORD25: add option to choose language speech](https://sourceforge.net/p/scummvm/bugs/6804/).
If the English voice pack is not present it falls back to using German voices.
The way this is implemented here however does not allow to use German
voices with English text or English voices with German text. This could be
achieved with a slightly different implementation of the same idea.
This is proposed as a pull request to get some feedback:
Is this a good idea?
Is there a better way to implement this?
Should we allow using German voices with English text or English …

SWORD25: Add engine option to use English speech instead of German

---

engines/sherlock/tattoo/tattoo_darts.cpp

This patch fixes the compile error:
format not a string literal and no
format arguments [-Werror=format-security]
Just suply "%s" as the standard format.
This way the string is not interpreted as format
which may lead to security issues.

SHERLOCK: Add format to fix compile error

---

engines/bbvs/bbvs.cpp

This should fix bug #7057 ("BBVS: No clean-up when restarting"). However, I'm not familiar with the game so I haven't done much testing other than using the savegame from that bug report and checked that my inventory is empty when starting the game anew.
If this is the correct fix, it may also be a good candidate for the 1.8 branch.

BBVS: Move much of engine initialization to newGame()

---

engines/sword25/fmv/movieplayer.cpp

SWORD25: Fix frozen/flickering title menu movie
Fixes bug #6978.
And then corrected code formatting..

Sword25 video fix

---

backends/platform/tizen/system.cpp
backends/saves/default/default-saves.cpp
backends/saves/default/default-saves.h
common/savefile.h

This pull request switches our SaveFileManager to offer case insensitive file access. This is intended to feature the same logical behavior on all our supported platforms. That is regardless of whether the platform has a case sensitive FS or a case insensitive one, we always expose a case insensitive one on a logical level.
The state this puts us into is:
- SaveFileManager API documentation clearly states it treats savefile names case insensitively
- DefaultSaveFileManager is offering case insensitive access on all platforms
The DefaultSaveFileManager change comes at the cost of us caching the directory contents (to avoid going through all files and finding one matching case insensitively on every operation), this means changes to the savepath outside ScummVM after it has been cached …

ALL: Make SaveFileManager case insensitive.

---

engines/wintermute/base/base_persistence_manager.cpp

The TimeDate format stores year relative to 1900, and month relative to 1.

WINTERMUTE: [GSoC] Make Wintermute games show the right save date

---

common/platform.cpp
common/platform.h

Add Apple II to our possible game platforms list (which is not the same as the Apple IIgs which is already there).

COMMON: Add Apple II platform

---

engines/scumm/POTFILES
engines/scumm/detection.cpp

This has been split off from PR #736.
Adds a custom engine setting for COMI's object_labels.
At the moment this will only appear in the launcher, but the other PR makes it also appear in the GMM Options dialog.

SCUMM: Add checkbox for object_labels setting in "Edit Game" dialog

---

engines/sci/console.cpp
engines/sci/engine/savegame.cpp
engines/sci/engine/scriptdebug.cpp
engines/sci/engine/seg_manager.cpp
engines/sci/engine/segment.cpp
engines/sci/engine/segment.h

This removes an old hack in savegame.cpp which relied on template specialization to synchronize types. It uses much more natural function overloading instead, which is also nicer to distribute over multiple files, if desired.
Additionally, I cleaned up serialization of `SegmentObjTable::Entry` objects. The former approach required each individual `SegmentObjTale` subclass to specialize the serialization method for `Entry` and make sure `next_free` is serialized correctly. Now, only the contained type in `SegmentObjTable` needs to be serializable with `syncWithSerializer` and a generic serialization for `Entry` exists which takes care of `next_free`.
SegmentObjTable can now be easily used with fundamental types and pointers too.
I tested this manually by loading older KQ6CD saved games. I …

SCI: Cleanup of Save/Load Code

---

gui/options.cpp

Remove dummy FluidSynth Settings button from Edit Game.
The FluidSynth Settings button actually works only from the Options dialog.
https://sourceforge.net/p/scummvm/bugs/6821/

GUI: Remove dummy FluidSynth Settings button from Edit Game

---

engines/fullpipe/fullpipe.cpp
engines/fullpipe/fullpipe.h
engines/fullpipe/sound.cpp
engines/fullpipe/sound.h

This is an attempt to decouple the audio parts of FULLPIPE from the rest of the engine.
I changed all the `SoundHandle`s to pointers, so `fullpipe.h` and `sound.h` don't have to include `audio/mixer.h`.
The result:
If you change `audio/mixer.h`, only 3 fullpipe files are recompiled instead of 64.

FULLPIPE: Reduce audio header dependencies

---

gui/debugger.cpp

Some Windows users find that Windows marks ScummVM as unresponsive when using the readline debugger, because it doesn't consume events. This patch fixes this by dropping all incoming events while readline is waiting for input (thanks @waltervn for verifying).
I have not tested this with non-GNU readline (i.e. the OS X one), which might not have rl_event_hook, so it would be nice if someone could test it there (and we can add an extra check to configure if necessary).

DEBUGGER: Drop events when using readline debugger

---

gui/Tooltip.h
gui/dialog.cpp
gui/dialog.h
gui/gui-manager.cpp
gui/gui-manager.h

Previously, they only reacted to the mouse position once it was moved.
This meant that if the cursor was on a button that just gained focus, it did not highlight.
Fixes [#7101](https://sourceforge.net/p/scummvm/bugs/7101/).
A few notes:
1. If you want to test the case where a new dialog opens, and the mouse cursor is above a button, you could use a hotkey in the a launcher to open "Add Game" when reading the mouse to be over the "Go Up" button which has a tooltip. However, any hotkeys get caught by the game list. I managed to test it by having `ListWidget::handleKeyDown()` return `false` immediately.
2. I removed `tooltipCheck` from the GUI loop. I wasn't sure how to keep it around, since I wanted tooltips to work on the newly-focused dialog without having the mouse move. Without it, …

GUI: When dialogs gain focus, inform them of the current mouse position

---

gui/predictivedialog.cpp
gui/predictivedialog.h
gui/widget.cpp
gui/widget.h

This feature made pressed buttons wait a few moments before returning to an unpressed state. It was half-implemented, and caused several visual bugs.
Fixes [#7083](https://sourceforge.net/p/scummvm/bugs/7083/), which details the bugs involved.
The predictive dialog is buggy. It was buggy before this change, and I only made enough changes so it would compile. If you try to press two num keys at once on the keyboard, you'll notice that the first button pressed will maintain its "pressed" animation.
Once this is merged, I will open a new bug about the predictive dialog, and we can discuss how it should handle multiple key presses.

GUI: Remove 'sticky button' feature

---

engines/wintermute/base/sound/base_sound_manager.cpp

As it was, it didn't work because it turned
"some\\windows\\path.wav" into "some/system/pathogg" (not ".ogg"), so any file called by the scripts with its ".wav" extension but actually present in compressed .ogg form on the .dcp archive could not be found.
base_disk_file.cpp (apparently) takes care of preprocessing the path to make it system-agnostic already for those files which reside on the disk.
This one should fix https://sourceforge.net/p/scummvm/bugs/7088/
The corresponding bit in the original engine is:
```
// try to switch WAV to OGG file (if available)
_splitpath(Filename, drive, dir, fname, ext);
if(_stricmp(ext, ".WAV")==0){
_makepath(NewFile, drive, dir, fname, ".OGG");
CBFile* file = Game->m_FileManager->OpenFile(NewFile);
if(file){
Filename = NewFile; …
```

WINTERMUTE: Correctly find .ogg version of .wav files

---

engines/gob/gob.cpp
engines/gob/inter_playtoons.cpp
engines/gob/inter_v4.cpp
engines/gob/pregob/onceupon/onceupon.cpp
engines/gob/pregob/pregob.h
engines/gob/sound/bgatmosphere.cpp
engines/gob/sound/bgatmosphere.h
engines/gob/sound/sound.cpp
engines/gob/sound/sound.h
engines/gob/videoplayer.cpp
engines/gob/videoplayer.h

This is an attempt to decouple the audio parts of GOB from the rest of the engine.
I moved the background atmosphere audio enum from `bgatmosphere.h` to `sound.h`, so files that want to use `sound.h` won't have to include `bgatmosphere.h` which includes the `audio/` headers.
The result:
If you change a file in `audio/`, only 8 gob files are recompiled instead of 39.

GOB: Reduce audio header dependencies

---

gui/widget.cpp

redraw when StaticTextWidget is aligned (same problem as setLabel, text drawn on top of the old one)

GUI: [GSoC] Widget: redraw when setAlign() called

---

base/main.cpp

The if was wrong, we split in two the validation of the path, first we check if it's a existing path and then if the path is a directory
Bug:
https://sourceforge.net/p/scummvm/bugs/6765/

COMMON: [GSoC] Fix wrong warning message

---

common/algorithm.h
common/str.cpp
common/str.h
test/common/algorithm.h
test/common/str.h

Inplemented some useful replace functions, with interfaces mimicking those of [the C++ std:: library] (http://en.cppreference.com/w/cpp/string/basic_string/replace). Unit tests are added for each of the new functions. These are `not` implemented using Common::replace, since that would unnecessarily elevate the algorithinc complexity and cache faults by a lot,
An all-purpouse algorithm for instance replacement in containers. It follows directly the implementation suggested in [the wiki page](http://wiki.scummvm.org/index.php/TODO#Algorithm_.2F_String).
Also includes unit tests with Common::List<> and Common::String.

COMMON: [GSoC] String::replace and Common::replace functionality added.

---

engines/scumm/he/sound_he.cpp
engines/scumm/he/sound_he.h
engines/scumm/input.cpp
engines/scumm/smush/smush_player.cpp
engines/scumm/smush/smush_player.h
engines/scumm/sound.cpp
engines/scumm/sound.h
engines/scumm/string.cpp

Changed `SoundHandle` to pointers and moved some `#define`s and `#include`s around.
When modifying `audio/mixer.h`, only 31 files require recompilation instead of 58.

SCUMM: Reduce audio header dependencies

---

engines/neverhood/diskplayerscene.cpp
engines/neverhood/diskplayerscene.h
engines/neverhood/menumodule.cpp
engines/neverhood/modules/module1300.cpp
engines/neverhood/modules/module1300.h
engines/neverhood/modules/module1300_sprites.h
engines/neverhood/modules/module2800.cpp
engines/neverhood/navigationscene.h
engines/neverhood/neverhood.cpp
engines/neverhood/scene.cpp
engines/neverhood/scene.h
engines/neverhood/screen.cpp
engines/neverhood/screen.h
engines/neverhood/smackerscene.cpp
engines/neverhood/sound.cpp
engines/neverhood/sound.h

Changed `SoundHandle` to pointers and moved some `#define`s and `#include`s around.
When modifying `audio/mixer.h`, only 17 files require recompilation instead of 59.

NEVERHOOD: Reduce audio header dependencies

---

po/be_BY.po
po/ru_RU.po

I've updated Belarusian GUI translation for version 1.8.1 and fixed some typos in Russian translation.
UPD: I uploaded the .po files into the wrong folder at first, now they seem to be OK. Sorry!

I18N: Update Russian and Belarusian translations

---

engines/access/detection.cpp
engines/cge/detection.cpp
engines/cge2/detection.cpp
engines/hopkins/detection.cpp
engines/lab/detection.cpp
engines/mads/detection.cpp
engines/tsage/detection.cpp
engines/voyeur/detection.cpp
engines/wintermute/detection.cpp

The About dialog shows lower case copyright signs (c) on 9 engines, while the majority of engines displays it upper case (C) - so i guess upper case is the way to go.
Changed lower case to upper case on affected engines.
Question: Is there a reason the ASCII char © isn't used?
Is it because some backends can't display those or is ScummVM's font limited or maybe the compiler chokes?

GUI: Make (C) sign consistent in all engines

---

engines/agi/global.cpp
engines/agi/preagi.cpp
engines/agi/preagi.h
engines/agi/sound.cpp
engines/agi/sound.h
engines/agi/sound_2gs.cpp
engines/agi/sound_pcjr.cpp
engines/agi/sound_sarien.cpp

Changed `SoundHandle` to pointers and moved some `#define`s and `#include`s around.
When modifying `audio/mixer.h`, only 6 files require recompilation instead of 40.

AGI: Reduce audio header dependencies

---

backends/module.mk
backends/platform/sdl/win32/win32.cpp
backends/updates/win32/win32-updates.cpp
backends/updates/win32/win32-updates.h
devtools/create_project/create_project.cpp
dists/scummvm.rc
dists/scummvm.rc.in

This is a pull request to add support for WinSparkle - an update framework. WinSparkle is a port of Sparkle for MacOS, which is already supported, so the update logic was already there.
Sparkle is using special XML files for update information, called appcasts. The same appcast can be used for both Windows and MacOS updates, and is currently located here:
https://www.scummvm.org/appcasts/macosx/release.xml
Here is some more information, from Sparkle and WinSparkle:
Sparkle is a software update framework for Mac OS X which uses appcasts for
release information. Appcasts are RSS-like XML feeds which contain information
about the most current version at the time. If a new version is available, the
user is presented the release-notes/changes/fixes and is asked if he wants to
update, and if …

Add support for WinSparkle

---

engines/access/sound.cpp
engines/access/sound.h

**This was not tested!**
Changed `SoundHandle` to pointers and moved some `#define`s and `#include`s around.
When modifying `audio/mixer.h`, only 2 files require recompilation instead of 28.

ACCESS: Reduce audio header dependencies

---

engines/sci/graphics/celobj32.cpp
engines/sci/graphics/celobj32.h
engines/sci/graphics/frameout.cpp
engines/sci/graphics/frameout.h
engines/sci/graphics/plane32.cpp
engines/sci/graphics/plane32.h
engines/sci/graphics/screen_item32.cpp
engines/sci/graphics/screen_item32.h

The goal with this pass was primarily to get documentation in place, and try to clean up by giving variables more descriptive names, but while I was working on doing this I discovered some rendering errors in Torin when scrolling the transparent transcript window (opened by the book icon at the bottom-left). This sent me on a wild goose chase for a while that had me first try implementing `kPlaneTypeTransparentPicture`, before discovering that `_moved` and `_updated` were reversed in a couple of places and that’s why things were screwy. (As it turns out that swap was messing up rendering in quite a few games—just not the ones we’ve been mostly looking at!)
I also discovered that some 320x200 constant values were still existing in games with high-resolution scripts, so it seems that the …

SCI32: Graphics rendering code updates

---

engines/sci/engine/kmisc.cpp

SSCI implementation of the SYSDATE subop of the GetTime kernel function was
changed between SCI0-LATE and SCI01: The base year used was changed from 1920 to
1980.
This subop is used in "Codename: Iceman" (Say "ask for date" to a passing girl
on the beach).
The Atari ST version of "Codename: Iceman" use the 1980 base year.
The Amiga version of "Codename: Iceman" appears to return the time instead of
date, with 0 for the YEAR part.

SCI: Fixed KGetTime with SYSDATE subop in SCI0-LATE.

---

engines/sci/console.cpp
engines/sci/engine/kernel.cpp
engines/sci/engine/kernel.h
engines/sci/engine/kmisc.cpp
engines/sci/engine/vm.cpp
engines/sci/engine/vm.h
engines/sci/engine/workarounds.cpp

This has a few risky commits:
"Improve kernel subfunction logging" adds kernel subfunction information to ExecStack, and removes the re-use of debugSelector for kernel call information. I think I untangled all uses of this, but this could use review and testing. (Especially in workaround processing.)
"Remove unclear &rest handling" is potentially dangerous. It removes a change to a value _above_ the current stack pointer, which seems to have no clear effect. My guess is that this is an unintended part of these two commits from FreeSCI[*], attempting to adjust argc on the stack. Incorrectly setting argc would not necessarily have been noticed, as `add_exec_stack_entry` would store it on the stack properly afterwards. This also needs review and testing.
[*] …

SCI: Clean up some aspects of call handling

---

common/memstream.h
engines/sci/engine/file.cpp
engines/sci/engine/file.h
engines/sci/engine/kfile.cpp
engines/sci/engine/state.cpp
engines/sci/engine/state.h

It adds a ReadStream/WriteStream to support this, replacing the previous VirtualIndexFile which required reimplementation of most read/write functions.
This new implementation fixes corrupting phantsg.dir when creating new games in Phantasmagoria, and updating swat.dat on PQ:SWAT startup (and elsewhere).

SCI32: Improve FileIO read-write support

---

devtools/create_project/cmake.cpp
devtools/create_project/cmake.h
devtools/create_project/cmake/CMakeLists.txt
devtools/create_project/create_project.cpp
devtools/create_project/module.mk

This adds a CMake project generator to create_project. You might wonder why it would be a good idea to make a build project generator output a configuration file for another build project generator. I use it to work on ScummVM with CLion as an IDE. CLion uses CMake build files as its native project model.
The CMake build file generated by create_project could probably be used to generate projects for other tools, but I have not tried it.
The generated CMake files have been tested to produce working builds of ScummVM on the following platforms:
- Linux, CMake 3.5, native GCC 6.1
- Windows, CMake 3.4, MSYS2/MinGW64 GCC 5.4
Other platforms may require a bit of tweaking.
The generator has the following known shortcomings which I am not planning to address:
- It is impossible to generate CMake …

DEVTOOLS: Add a CMake project generator to create_project

---

engines/scumm/actor.cpp
engines/scumm/actor.h
engines/scumm/boxes.cpp
engines/scumm/gfx.cpp
engines/scumm/gfx.h
engines/scumm/object.cpp
engines/scumm/saveload.h
engines/scumm/scumm.cpp
engines/scumm/scumm.h
engines/scumm/scumm_v0.h

Hey All,
There is currently a number of small issues with MM V0. This patch addresses them, 
1. In the 'V0 Demo' room 5 during the 'hands off demo mode' Sandy runs down, then left to escape Purple Tentacle, instead of going around the stair case (this is due to the original engine finding the first path, not necessarily the fastest. This behavior is now implemented)
1. During the intro, the timing is off between the audio/video. The music builds up, but the "A LucasFilm Production" text has already been displayed.
1. Direction of actors after loading a save game is always putting right
1. Top text area is always cleared prior to screen fade in V0
Notes:
1. Original walkbox algorithm is implemented, we now calculate the walk boxes before walking, then remove them from the array as we walk …

SCUMM: Maniac V0: Walkbox / Timing improvements

---

engines/sci/detection.cpp
engines/sci/detection_tables.h
engines/sci/engine/kmisc.cpp

Added games are:
Hoyle Classic Games
Hoyle Bridge
Hoyle Children's Collection
Hoyle Solitaire (CD and Hard Drive versions)
Additionaly, kGetConfig was modified to support two settings used by
these games: "laptop" and "jumpto".

Add detection to the Hoyle 5 family of games

---

backends/events/sdl/sdl-events.cpp
backends/events/sdl/sdl-events.h

On Windows, SDL 1.2 ignores international keyboard layouts and returns keycodes valid for US keyboards. For example, pressing 'A' on an AZERTY keyboards returns a keycode with the value 'q'. This prevents engines from being able to reliably use the keycodes to identify keys.
SDL 2 does not have this problem, nor SDL 1.2 on macOS and Linux/X11.
The proposed change consists in making Windows API calls to obtain the keycode for the scancode sent by SDL using the currently active keyboard layout.

SDL: Fix Windows SDL1 keycodes to use the active keyboard layout

---

.travis.yml

According to https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments, container-based
jobs offer two cores, which should provide quicker turnaround times.
Check times against first-ever travis build:
https://travis-ci.org/scummvm/scummvm/builds/147974521

Use parallel build on travis

---

.travis.yml
backends/platform/sdl/sdl.cpp
backends/platform/sdl/sdl.h
common/recorderfile.cpp
common/scummsys.h
common/system.cpp
common/system.h
test/module.mk

Remove the EventRecorder dependency from OSystem, pushing it down to SDL. The event recorder only works with SDL backends, so it should be fine.

Fix tests when building with the event recorder

---

backends/platform/sdl/posix/posix.cpp
backends/platform/sdl/posix/posix.h

This allows ScummVM to find data files while running in a snap (e.g.
from the new Ubuntu store).

POSIX: Add $SNAP to search path if available.

---

engines/sci/engine/kfile.cpp

Torin has two sets of saves: autosave.### and torinsg.###, both with
their own slots and .cat file. The autosave system uses autosave.000
and autosave.001. It also checks the presence of autosave.cat to
determine if it should show the chapter selection menu on startup.

SCI32: Support Torin's autosave system

---

backends/graphics/opengl/opengl-sys.h
base/plugins.h
common/scummsys.h

This is undefined behavior and clang warns about it. Specifically, it's not supported by Visual Studio.
See <http://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20160118/147239.html>.
I haven't tested these changes carefully. Would be helpful to have more eyeballs :)

ALL: Don't use 'defined' in macro definitions

---

snapcraft.yaml

Now that https://github.com/scummvm/scummvm/pull/795 is merged, enabling snaps, we can merge the snapcraft.yaml.
This file is essentially the "Makefile" for the `snapcraft` binary, which will build a squashfs that can be mounted and run in a heavily AppArmor-constrained process space.
Right now this snapcraft.yaml allows access to the user's home directory through the `home` plug on line 15, but in future it would be possible to bundle games into their own snaps along with specific revisions of scummvm, and those could operate entirely without filesystem access outside the snap jail.  This can work no matter the base OS, as the environment overlays atop a ~60MB `ubuntu-core` image.
I've demonstrated this work in person to fuzzie, and have built 1.9.0git snaps using `snapcraft cleanbuild` …

Add snapcraft.yaml so you can `snapcraft build`

---

.travis.yml
NEWS
configure
dists/debian/control
snapcraft.yaml

This is the switch of SDL backend to SDL2. All the work has been already prepared, and the use of this library version tested many times. Thus, this patch boils down to adding new references in our build system.

BUILD: Switch SDL backend to SDL2 by default. SDL1 is still a fallback.

---

engines/sci/engine/kfile.cpp

This fixes deleting savegames in Phantasmagoria 1.
I'm not sure if there's SCI11 usage of kFileIORename that this would break, although it seems unlikely. I'm not aware of any yet, though, so can't test.

SCI: Make kFileIORename use wrapped filenames

---

backends/platform/android/asset-archive.cpp
backends/platform/android/asset-archive.h
configure

The AAssets API was added in android 2.3, so it also requires using
the android-9 toolchain.
Using this gives a rather large speedboost to starting the ScummVM
application.
This is being upstreamed from ReisdualVM https://github.com/residualvm/residualvm/commit/01459a674fb4875b822508b804b83e351f46938b

ANDROID: Update the asset archive code to use AAssets

---

graphics/macgui/macwindow.cpp
graphics/macgui/macwindowborder.cpp
graphics/macgui/macwindowborder.h
graphics/macgui/macwindowmanager.cpp
graphics/nine_patch.cpp

Since the addition of MacGui to mainline, a number of leaks and minor bugs in the code have been found, via Valgrind. They were mostly due to `free()` not being called when appropriate, which in a particular case created a 10MB leak every time the GUI was drawn. Regarding the bugs, there was only one found, which creashed the game when closing a window, due to a leftover index.
This PR is part of the cleanup of my GSoC project.

GRAPHICS: [GSoC] Fix leaks and bugs in MacGui

---

common/platform.cpp
common/platform.h

This adds a platform for the [Atari 8-bit family](https://en.wikipedia.org/wiki/Atari_8-bit_family). As 'atari' is already used for the Atari ST platform, I set all the codes to 'atari8'.

COMMON: Add Atari 8-bit platform

---

backends/platform/sdl/sdl-sys.h

SDL2 (2.0.4) that comes with MacPorts uses MacPorts' libiconv which ends up depending on `time.h` forbidden symbols
Here is the include-chain to time.h (pre-patch)
```
../backends/platform/sdl/sdl-sys.h:100
/opt/local/include/SDL2/SDL.h:32
/opt/local/include/SDL2/SDL_main.h:25
/opt/local/include/SDL2/SDL_stdinc.h:87
/opt/local/include/iconv.h:111
/usr/include/wchar.h:91
/usr/include/time.h
```
Homebrew doesn't have this problem because it uses the native (XCode) libiconv

SDL: Fix build with MacPorts SDL2

---

devtools/create_project/xcode.cpp

I think this is right, but since I don’t own any of the networking code I just wanted to double check that this is the correct and expected build setting for iOS.

CREATE_PROJECT: Fix networking backend file targets in Xcode

---

audio/softsynth/cms.h

The CMS emulation assumes the chips run at 8 MHz clock,
but in PCs they run at 7.15909 MHz, so the emulated pitch
is too high. Adjusting the requested sampling rate higher
by matching amount the pitch is lowered down to normal.

AUDIO: Fix CMS chips incorrect pitch.

---

backends/base-backend.cpp
backends/base-backend.h
backends/cloud/dropbox/dropboxlistdirectoryrequest.cpp
backends/cloud/googledrive/googledrivestorage.cpp
backends/graphics/dinguxsdl/dinguxsdl-graphics.cpp
backends/graphics/gph/gph-graphics.cpp
backends/graphics/graphics.h
backends/graphics/linuxmotosdl/linuxmotosdl-graphics.cpp
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/opengl-graphics.h
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h
backends/modular-backend.cpp
backends/modular-backend.h
backends/networking/curl/cloudicon.cpp
backends/networking/curl/cloudicon.h
common/system.h

The recent cloud feature set added the following methods to the OSystem interface:
```c++
void copyRectToOSD(const void *buf, int pitch, int x, int y, int w, int h);
void clearOSD();
Graphics::PixelFormat getOSDFormat();
```
These methods allow to draw pixel data that is expected to overlay the regular
screen, with alpha transparency.
These methods are, as of now,  only used to display an icon indicating that ScummVM
is synchronizing in the background with some remote data storage.
There are IMO several issues:
* The backends are expected to implement the OSD as a full screen surface.
It is not the case. For example the Android backend displays the OSD messages
with native pop-up messages. The SDL backend did have a full screen OSD surface,
but it was an implementation detail that I don't …

OSYSTEM: Allow drawing a background activity icon on the OSD

---

backends/platform/androidsdl/androidsdl-sdl.cpp

Default config key browser_lastpath changed to '/storage' for Android SDL port.

ANDROIDSDL: default config key browser_lastpath changed to '/storage'

---

backends/platform/androidsdl/androidsdl-sdl.cpp

set default gfx_mode to 2x (for android-sdl port)

ANDROIDSDL: set default gfx_mode to 2x

---

dists/raspberrypi/README_raspberrypi
dists/raspberrypi/scummvm.sh

This PR adds the specific README_raspberrypi file for notes and instructions specific to the Raspberry Pi port, and a small launch script so the scummvm port uses the included SDL 2.0.4 shared library included in libs with the binary package, so people doesn't have to build SDL 2.0.4 themselves (since the Pi foundation is taking very long to include SDL 2.0.4 with Raspbian by default).

RASPBERRYPI: Add specific README and launch script for using SDL 2.0.4 included in the release package. 

---

engines/chewy/chewy.cpp
engines/chewy/chewy.h
engines/chewy/configure.engine
engines/chewy/console.cpp
engines/chewy/console.h
engines/chewy/cursor.cpp
engines/chewy/cursor.h
engines/chewy/detection.cpp
engines/chewy/events.cpp
engines/chewy/events.h
engines/chewy/graphics.cpp
engines/chewy/graphics.h
engines/chewy/module.mk
engines/chewy/resource.cpp
engines/chewy/resource.h
engines/chewy/scene.cpp
engines/chewy/scene.h
engines/chewy/sound.cpp
engines/chewy/sound.h
engines/chewy/text.cpp
engines/chewy/text.h
engines/chewy/video/cfo_decoder.cpp
engines/chewy/video/cfo_decoder.h
video/flic_decoder.cpp
video/flic_decoder.h

This is pull request for the work in progress engine for Chewy: Esc from F5, as requested by @sev- :
http://www.mobygames.com/game/chewy-esc-from-f5
At the moment, the engine supports the majority of the game's resources, i.e.:
- Backgrounds
- Sprites
- Sound effects
- Speech
- Error texts
- Fonts
- Videos (custom FLIC videos, with extra functionality)
- Cursors
There are a lot of things still to be done, including:
- The game's hardcoded logic for its 4 episodes (chapters)
- Sprite animation (e.g. walking)
- Scene animations (e.g. the slime dripping in the first scene, the electricity zaps in the second one)
- Inventory handling
- ~~In-game text~~ (Implemented)
- Menus (main menu, options, in-game action menu)
- Music (custom MOD format)

Chewy: Esc from F5

---

engines/chewy/detection.cpp

I own two original disks of "Chewy: ESC von F5", and here are the detection entries.
The game was originally published in German, the English version followed later. Both game entries will show the first scene and the "This is a test message".

CHEWY: Add detection entries for German versions

---

audio/softsynth/mt32.cpp
backends/cloud/storage.cpp
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/opengl-graphics.h
base/main.cpp
common/module.mk
common/osd_message_queue.cpp
common/osd_message_queue.h

This is one attempt to fix bug #9609: SDL: Crash with displayMessageOnOSD called from separate thread in cloud code.
The OpenGL Graphics Manager was not having the issue because there was a hack to handle this case. But instead of also adding a hack to the SurfaceSDL Graphics Manager, or changing the cloud code to make sure all OSD messages are displayed from the graphics thread, I have instead added a OSD message queue class that takes messages from any thread which can then be polled by the graphics thread to be displayed.
I then modified the cloud code and MT32 code to use this new class and removed the hack from the OpenGL Graphics Manager.
I am opening this PR to get opinion on whether this is a good way to fix the issue, and also to get feedback on the actual implementation. For …

OSD messages from any thread

---

engines/kyra/timer.cpp
engines/lab/console.cpp
engines/scumm/sound.cpp
graphics/fonts/bdf.cpp

I've not fixed this one, maybe it's on purpose:
RELASE -> RELEASE
engines/mads/staticres.cpp:const char *const kGameReleaseTitleStr =
"GAME RELASE VERSION INFO";

JANITORIAL: Typos found by lintian

---

backends/events/sdl/sdl-events.cpp

This will hopefully fully fix keyboard issues for macOS / SDL2,
for example when pressing "alt-x".
Also reset .ascii to 0, when Num-Lock is NOT enabled and keypad
directional keys are pressed. This was fixed inside AGI+SCI
previously.
The latter shouldn't cause issues, but in case it does, the
affected engine should get fixed and use keycodes instead.

SDL: Fix keyboard on macOS, when using SDL2, fix directional keypad

---

gui/gui-manager.cpp

This patch fix bug #6841
If this runloop catches both the repeated key down event and the key up event.
In this case they key down will close the tooltip, because it got closed the key up event will be ignored.
As a result the LauncherDialog will never get notified the SHIFT state might have changed and not adapt the button description.
In this patch we just pass event to topDialog, if activeDialog was closed.
Also we must check, If topDialog doesn't exist.
Please check, whether it works.
If it is, I should change the comment in code, and maybe we should process tooltipCheck or make updates https://github.com/scummvm/scummvm/blob/master/gui/gui-manager.cpp#L344-L348

GUI: Fix "eaten" event by dialog which was closed

---

engines/wintermute/base/sound/base_sound_manager.cpp

Bickadoodle does this.
<s>Fixes #6594</s> It doesn't, that is best handled in #733

WINTERMUTE: Log warning if addSound is called with empty filename

---

backends/platform/ios7/ios7_osys_main.h
backends/platform/ios7/ios7_osys_video.mm

After my iPad went to sleep while I was looking at the DOTT intro cutscene I though that maybe it would be nice to disable the idle timer while an engine is running to prevent the iPad going to sleep.
The idle timer is only disabled while an engine is running. It is enabled again when returning to the launcher, so if the user doesn't do anything for a while while in the launcher, the iPad will go to sleep.
I am not sure if this is a good idea or not, so I am submitting this change as a PR.

IOS: Disable idle timer while an engine is running

---

engines/gnap/POTFILES
engines/kyra/POTFILES
engines/mads/POTFILES
engines/sci/POTFILES
engines/scumm/detection.cpp
engines/toon/toon.cpp
engines/wage/POTFILES
engines/zvision/POTFILES
engines/zvision/file/save_manager.cpp

This PR adds and updates some POTFILES, mostly for consistency purposes. Besides that, a few strings were added to translation. I also enabled translation for the "unknown game warning" in the SCUMM engine - we have it enabled in advancedDetector.cpp since ages.
Let me know if I did something wrong 👍

I18N: Update/add POTFILES, enable some more strings for translation

---

configure

OpenBSD, for example, uses ppc instead of powerpc.
This lets OpenBSD/macppc use ``_need_memalign=no``.
A similar fix, for amd64/x86_64, was commited in ed53292194682fb2ebc0d5a7ecd23e482899aefc.

CONFIGURE: Allow ppc as alias for powerpc

---

engines/cruise/font.cpp

Fixes wrong rendering when outlines overlap. Current:
With patch:
Original (DOSBox):

CRUISE: font: Don't overwrite transparent pixels

---

engines/cruise/font.cpp

The game uses 5px space instead of 4px.
Some screenshots for comparison. First DOSBox, then the current ScummVM.
English version:
Italian version. Symbols are narrower, but the space is still the same:

CRUISE: Fix font space width

---

README
engines/access/POTFILES
engines/access/resources.cpp
engines/drascula/POTFILES
engines/drascula/drascula.cpp
engines/hugo/POTFILES
engines/hugo/hugo.cpp
engines/kyra/staticres.cpp
engines/lure/POTFILES
engines/lure/lure.cpp
engines/mortevielle/POTFILES
engines/mortevielle/mortevielle.cpp
engines/sky/compact.cpp
engines/teenagent/resources.cpp
engines/tony/POTFILES
engines/tony/tony.cpp
engines/toon/toon.cpp

The helps translators a bit by removing filenames from messages so no duplicate messages have to be translated. Some engine didn't display a dialog box about the problem found. Some message were not yet translated.
Feedback appreciated.

ALL: Unify messages concerning engine data files

---

common/scummsys.h

As mentioned by @wjp, this header is included already by Director, SCUMM, Sky, and Sword25 engines so it should be fine to load in scummsys.h, but I always want to get a double-check before I put anything new into common.

COMMON: Add stddef.h to scummsys.h for ptrdiff_t

---

engines/wintermute/base/base_game.cpp
engines/wintermute/base/base_game.h
engines/wintermute/base/gfx/osystem/render_ticket.cpp
engines/wintermute/detection.cpp
engines/wintermute/detection_tables.h
graphics/transparent_surface.cpp
graphics/transparent_surface.h

1. Templat-ify scale() and rotoscale()
2. Add a menu item for bilinear filtering
3. Read the value of the above in RenderTicket and pick the correct specialization accordingly
This is useful in Bickadoodle, which makes a very liberal use of rotozooming; without bilinear on you can see some conspicuous pixels in a few places.

WINTERMUTE: Enable bilinear filtering in Wintermute

---

engines/wintermute/base/file/base_disk_file.cpp
engines/wintermute/dctypes.h
engines/wintermute/utils/path_util.cpp
engines/wintermute/utils/path_util.h
test/engines/wintermute/path_utils.h
test/module.mk

TL;DR: This is PR #733 + #714.
Fixes bugs 7068 and 6594
---- 
This is the same exact branch as PR #733;
In addition, I cherry-picked Zoltan's commit from #714; and added a patch on top of it so that it uses the existing normalizeFilename() method in PathUtils for the sake of having a bit less duplication.
After doing so, #7068 *appears* to not have come back, if I have understood the bug report correctly (I can get to the end of the conversation).
I also reworded Zoltan's commit so that it includes the line "fixed #7068".
it is a one-liner commit, but I find he deserves the credit for tracking down the bug.
If you like it enough, you can merge it directly, otherwise merging #733 and #714 separately and then maybe adding this on top is probably equivalent.

WINTERMUTE: Fix PathUtils and add workaround for mixed separators

---

engines/wintermute/dctypes.h
engines/wintermute/utils/path_util.cpp
engines/wintermute/utils/path_util.h
test/engines/wintermute/path_utils.h
test/module.mk

This avoids hitting a failing assert when passing strings == "".
E.g. Bickadoodle has a script bug that tries to load an empty filename.
This fixes #6594

WINTERMUTE: Fix PathUtils

---

test/module.mk

This fixes `make test` when wintermute engine is disabled after commit e3fdd8d5fe5b739b28c67539bbdb0b596f9dacbe, but I am not 100% sure that this is the right solution.

TEST: Only build Wintermute tests when that engine is enabled

---

engines/wintermute/detection_tables.h

- DFAF Adventure
- Dreamcat
- Open Quest
Freely available from https://jennibee.itch.io/ those are three (very short) fangames.
All of those games come in three packages (Linux, OSX, Windows32) but all the packages differ only in the included platform's main .exe, the data.dcp stays the same, so the entry is limited to one for all three games.
The packages even come with ScummVM 1.8.1
All three games tested and working (didn't solve the Open Quest final riddle though)
One script runtime error encountered in DFAF Adventure on examining the "speaker", other than that all games are fine and none crash.
Feel free to give hints on what i should change.
Thanks a lot

WME: Add three fangames from jennibee

---

.travis.yml

container-based infrastructure (by sudo: false) starts and runs
faster:
https://docs.travis-ci.com/user/migrating-from-legacy/
gcc and make are preinstalled by Travis-CI for C++ language
containers, so do not need to be listed as dependencies:
https://docs.travis-ci.com/user/trusty-ci-environment/#Compilers-%26-Build-toolchain
ccache caching prevents wasting time rebuilding unchanged code:
https://docs.travis-ci.com/user/caching#ccache-cache
This should work OK, though there is a [bug](https://github.com/travis-ci/travis-yaml/issues/58) in travis lint which means that there is a slight chance this change might break something. I am happy to monitor and unbreak the build if that happens.

BUILD: Speed up Travis-CI builds

---

engines/sci/engine/savegame.cpp
engines/sci/engine/savegame.h
engines/sci/graphics/palette.cpp

Additionally, add workaround to fix up old QfG3 saves with broken
_palVaryPaused state. Fixes bug #9674.

SCI: Unconditionally save palvary state

---

engines/scumm/actor.cpp
engines/scumm/costume.cpp
engines/scumm/script_v2.cpp

Hi,
This request is to resolve two issues
https://bugs.scummvm.org/ticket/4515
https://bugs.scummvm.org/ticket/6817
6817:
I have checked against DosBox, and can verify that both MM-V1 and Zak-V1 are off by 1 row, however other games utilising the ClassicCostumeRenderer (MM-V2, Indy-256) are not...
4515: 
The a->setFacing which was originally occurring in o2_putActor, was the cause of this bug. As _facing was being set, eventually a->animateActor is called (via o5_animateActor), the setDirection did nothing as _facing == _direction, but Fred was not facing the camera.

SCUMM: V0/V1: Fix two graphical issues

---

engines/scumm/script_v2.cpp

This is one possible fix for #2285, which is actually a scripting oversight, not a ScummVM bug.
I'm not really sure if bugs like this are generally fixed. But after spending the time investigating it, a fix was simple enough to put together. 
This bug affects C64, V1, and V2 versions of Zak (I do not have the FMTowns version, so can not check it)
I'll copy and paste the analysis of the problem from the bug report,
"
The cut scene (script-96) inside the telephone company triggers just after first using the crystal, setting Var[245] (Actor 7's Costume) to 0x1C (Disguise On) and locking object 344. This cut scene is not played again.
When you fly to the Bermuda Triangle and abducted, you can ring the door bell... this sets Var[245] back to 0x18 (Disguise Off). The previous variable state is …

SCUMM: Fix bug #2285 (ZAK C64/V1/V2 Caponians dont disguise after using crystal)

---

engines/bladerunner/detection_tables.h

I received my original copy of the German "Blade Runner" release today, so here is the detection entry.
At the moment, it seems that the German release is unsupported by the engine. I did a full installation from my original CDs on a Windows XP VM and copied the full "BLADE" directory on the virtual HDD to my main machine.
After starting the game, it fails with the following error message:
```
Opening hashed: MUSIC.MIX
Opening hashed: SFX.MIX
Opening hashed: SPCHSFX.TLK
getResource: Resource ACTORS.TRE not found.
```
I added the detection information as a Pull Request, because I don't know if you want to merge the detection entry at the current state.

BLADERUNNER: Add detection for German version

---

engines/sword25/util/lua_unpersist.cpp

This matches the behaviour of the Pluto rewrite Eris, and avoids
casting the integer indices to void *.
I verified this code by running this method in parallel with the current
lightuserdata/void* approach and asserting the retrieved objects were
identical when loading a savegame.
This fixes bug #7172 in an alternative way from #893.

SWORD25: Use direct integer index into indexTbl

---

base/commandLine.cpp
common/scummsys.h
devtools/create_project/create_project.cpp
devtools/create_project/create_project.h
devtools/create_project/xcode.cpp

This PR contains a collection of fixes for issues I encountered using create_project. The commits are independent from each others so we could decide to only keep some of them.
I am not familiar with create_project. I don't often use it and I had never looked at its source code before today. So don't hesitate to point issues or suggest better ways to fix some of the issues.
All the fixes result from looking at an issue recently posted in the iPhone forum (http://forums.scummvm.org/viewtopic.php?t=13965&start=120#83734). Compiling the current master code requires using `--disable-engine=fullpipe`. The first commit fixes this specific error (that also occur when compiling for OS X and I assume Windows). The other commits result from issues I noticed when testing this (for example that using …

Create project fixes

---

engines/dreamweb/detection_tables.h

The Italian CD release of Dreamweb (available on
https://www.scummvm.org/games/) was not properly
detected (the floppy version was detected, so
speech stayed disabled).
Added a proper entry to fix the issue.

DREAMWEB: fixed detection of Italian CD release

---

common/gui_options.cpp
common/gui_options.h
gui/options.cpp
gui/options.h

GUIO_NOSPEECHVOLUME can be used for games that allow toggling of speech but do not provide the ability for users to control speech volume. (e.g. GK2, which has a patch that can enable subtitles, but the game only allows control of music volume.)
GUIO_LINKMUSICTOSFX and GUI_LINKSPEECHTOSFX can be used for games that allow control of music, sfx, and speech in combinations, like games that provide control of digital audio separately from MIDI, or games that only control all three audio types through a single volume control. (e.g. Phant1 and KQ7, respectively.)
(And, before anyone asks: no, it’s not possible to cleanly split audio types in these games, since Robots sometimes contain speech or sound effects or both, and some games like GK2 put speech into non-Audio36 resources.)

GUI: Add three new options for volume slider controls

---

backends/events/sdl/sdl-events.cpp
backends/events/sdl/sdl-events.h
backends/events/wincesdl/wincesdl-events.cpp

Fixes https://bugs.scummvm.org/ticket/6996
This small change to the source fixes the "stopping, jerky" analog joystick mouse pointer control. In the original source, the mouse pointer was only updated when the analog joystick axes _changed_. Now it is updated also when the joystick axes stay at the same, unchanged values. This fixes the "stop and go" behaviour of the pointer when it is controlled by an analog stick. 
This bug was experienced by me on the Vita, on Android (Nvidia Shield Portable), and reported by several users on Raspberry Pi (RetroPie) when they used their controllers to control the mousepointer instead of a real mouse (or keyboard).

Fix Bug #6996 (Fixed jerky/laggy analog joystick mouse control)

---

backends/events/dinguxsdl/dinguxsdl-events.cpp
backends/events/gph/gph-events.cpp
backends/events/linuxmotosdl/linuxmotosdl-events.cpp
backends/events/maemosdl/maemosdl-events.cpp
backends/events/openpandora/op-events.cpp
backends/events/ps3sdl/ps3sdl-events.cpp
backends/events/sdl/sdl-events.cpp
backends/events/sdl/sdl-events.h
backends/events/symbiansdl/symbiansdl-events.cpp
backends/events/wincesdl/wincesdl-events.cpp

For some engines such as Dreamweb that a previous fix did not apply to, this fixes bug 6996: Android: Mouse pointer control with analog joystick is unusable.
The improvements are not limited to Android but apply to any host system that uses the SDL backend and allows analog joystick mouse pointer movement (Vita, Raspberry Pi etc.).
This PR fixes the remaining problems with analog joystick mouse pointer control.
Most importantly 
- handleKbdMouse now returns a bool so that the MouseEvents generated by it are not dropped anymore
Other analog joystick problems that are fixed in this PR are:
- increased resolution of analog joystick mouse speeds. It had only ~16 speed increments instead of the max possible 32768.
- improved smoothness of pointer movement. The position of the …

SDL: More fixes to jerky analog joystick pointer

---

engines/scumm/actor.cpp

Hi,
This PR is for two animation issues,
1. During the cutscene in script-151 (Purple Tentacle chases Sandy), Sandy appears to slide as the walk animation begins durnig the same frame as she begins speaking, this sets the 'repeat' flag for all limbs. We fix this by specifically running the speakCheck function, if speaking has been enabled.
2. Some walkboxes contain a 1 pixel gap, which the original handles using a JMP (when we reach a situation with no valid walkbox), and then move the actor again. I believe on the C64 this is unnoticeable, as it  enough time passes for the interrupts which redraw the screen to fire. In ScummVM, the actor is only drawn once per frame, causing them to move 2 pixels or 'skip'

SCUMM: MM V0: Fix two walk animation issues

---

engines/scumm/script_v2.cpp

Hi,
This fix is for a scripting oversight, 
have added the script analysis to the ticket: https://bugs.scummvm.org/ticket/4111
in the event Dr. Fred turns the power off and the player enters the lab, the script responsible for turning the power back on is stopped, resulting in the power never being turned back on.
This fix resolves it by setting the 'circuit breaker' object to on when termination of the script occurs
I'm not sure if it was the right choice, but decided to add 2 macros for the MM workarounds, as the continual IF/ELSE combinations with the various script/object numbers was rather unfriendly, have also applied it to the surrounding code... If this is ok, I'll back apply it to PR #902

SCUMM: Fix bug #4112 (MANIAC: Power never returns)

---

engines/scumm/script_v2.cpp

This is caused by a scripting oversight which will occur if you enter the lab entry room in less than 45 minutes since the first cutscene with Dr. Fred and Sandy.
Its simply because the cutscene trigger is time based and puts Purple tentacle in the room, leaving him in it on completion.
This fix will prevent the cutscene with Purple Tentacle, Sandy and Dr. Fred from executing if the lab has been stormed (someone kindly set a variable for us at the beginning of the 'storm' script, which isn't used anywhere else in the game)
These script numbers are for V0, however the V1/V2 scripts are usually (x + 5)
script-143 (Cutscene: Dr. Fred / Sandy #1) is triggered by USE on roomobj-1-28 (Outside side of the Front Door). At completion of the cutscene, it executes script-151.
script-151 (Cutscene: …

SCUMM: Fix bug #4556 (Maniac: Purple Tentacle appears in Lab after being chased out)

---

backends/events/sdl/sdl-events.cpp
gui/options.cpp

- control options tab is moved past graphics options tab
- control tab is not the default anymore
- changed label of "Mouse Speed" option to "Pointer Speed"
- changed Pointer Speed infotip description to make it more clear that it affects the keyboard/joystick pointer control only
- also made Pointer Speed labels translatable.

SDL: fix options control tab ordering and labels

---

backends/events/androidsdl/androidsdl-events.cpp
backends/events/gph/gph-events.cpp
backends/events/openpandora/op-events.cpp
backends/events/sdl/sdl-events.cpp
backends/events/symbiansdl/symbiansdl-events.cpp
backends/events/webossdl/webossdl-events.cpp
backends/events/wincesdl/wincesdl-events.cpp

With the new joystick pointer speed adjustment in the SDL backend which can be less then one pixel per frame delay, all calls to 
ProcessMouseEvent(event, _km.x / MULTIPLIER, _km.y / MULTIPLIER) 
with those exact second and third arguments need to be prevented from updating _km.x and _km.y since that will destroy the sub-pixel resolution and make the joystick pointer control less precise. But calls to ProcessMouseEvent with other arguments should still update _km.x and _km.y.
Before this PR, the call to ProcessMouseEvent inside handleKbdMouse was made to work correctly by first saving and, after the call, re-loading the hi-res _km.x and _km.y coordinate values. But all the other calls still exhibit the problem of overwriting _km.x and _km.y with imprecise numbers.
To fix this, in this PR, …

SDL: Always use sub-pixel joystick pointer

---

backends/graphics/psp2sdl/psp2sdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.cpp

There was a problem with calling gSystem->hasFeature(kFeatureShader) from within the constructor of SurfaceSdlGraphicsManager. If the system-specific OSystem does not enable that feature, the call is passed on to _graphicsManager->hasFeature(kFeatureShader) by ModularBackend. But since we are in the constructor of _graphicsManager, _graphicsManager is still a NULL pointer at this point and a crash occurs.
This is fixed in this commit.

SDL: Fix trying to init non-supported shaders

---

gui/ThemeEngine.cpp
gui/options.cpp

Fix for [GUI: Changing 'GUI Language' in Global Options removes theme overlay](https://bugs.scummvm.org/ticket/9711).  
Also, _cbcf819_ fixes the theme label to display the correct theme.  
For more details see the commit messages.

GUI: Fix for #9711

---

gui/gui-manager.cpp
gui/gui-manager.h
gui/launcher.cpp
gui/options.cpp

Currently changing the GUI language in the options results in an invalid write in delete memory. Here is one of the two possible valgrind error:
```
==38272== Invalid write of size 1
==38272==    at 0x10198D44E: GUI::ButtonWidget::handleMouseUp(int, int, int, int) (widget.cpp:341)
==38272==    by 0x101927DBE: GUI::Dialog::handleMouseUp(int, int, int, int) (dialog.cpp:212)
==38272==    by 0x101936FF0: GUI::GuiManager::processEvent(Common::Event const&, GUI::Dialog*) (gui-manager.cpp:553)
==38272==    by 0x101936819: GUI::GuiManager::runLoop() (gui-manager.cpp:334)
==38272==    by 0x101927779: GUI::Dialog::runModal() (dialog.cpp:80)
==38272==    by 0x10193C399: GUI::LauncherDialog::handleCommand(GUI::CommandSender*, unsigned int, unsigned int) (launcher.cpp:642)
==38272==    by 0x101A05D7A: …
```

Delay deletion of widgets when rebuilding launcher and options dialogs

---

engines/fullpipe/behavior.cpp
engines/fullpipe/fullpipe.cpp
engines/fullpipe/fullpipe.h
engines/fullpipe/gfx.cpp
engines/fullpipe/gfx.h
engines/fullpipe/interaction.cpp
engines/fullpipe/interaction.h
engines/fullpipe/motion.cpp
engines/fullpipe/motion.h
engines/fullpipe/objects.h
engines/fullpipe/scene.cpp
engines/fullpipe/scene.h
engines/fullpipe/sound.cpp
engines/fullpipe/sound.h
engines/fullpipe/stateloader.cpp
engines/fullpipe/statics.cpp
engines/fullpipe/statics.h
engines/fullpipe/utils.cpp
engines/fullpipe/utils.h

In this pull request, I've changed a lot of engine strings in Fullpipe so that they are handled via Common::String. This results in cleaner and more manageable code.
I've tried splitting up the commits so that all relevant changes are grouped together
Update: I've also added some memory leak fixes to this branch, as part of fixing memory leaks in this engine. These are relevant, because the original intention of this branch was to optimize code and identify memory leaks.

Fullpipe Common::String + memory leak fixes

---

engines/director/detection.cpp
engines/director/detection_tables.h

My versions are in Swedish but I'm pretty sure there aren't any other versions, that's why I chose `Common::EN_ANY`.
The game doesn't currently boot as `loadCastData` eventually tries to read non-Cast data and asserts [here](https://github.com/scummvm/scummvm/blob/master/engines/director/score.cpp#L495).

DIRECTOR: Add detection for Arnie and its demo

---

engines/xeen/detection_tables.h

This adds the hashes for the 2CD fully-voiced World of Xeen edition.

Xeen: Add detection for the 2CD "talkie" version

---

gui/ThemeEngine.cpp
gui/options.cpp

This PR focuses on GlobalOptionsDialog::apply() to determine incompatible font/charset and fallback to previous settings on error.
'Greek' always triggers an error out of unknown reasons to me. It is the only language with charset iso-8859-7, so looking at ThemeEngine::init(), how fonts/charsets are loaded and why it fails and falls back to ASCII is the next step.
@criezy you mentioned in #919 that you have mapped out combinations that broke previously.
Would be great if you could reply and paste your list here :)

GUI: Restore previous settings if GUI cannot be rendered

---

engines/testbed/module.mk
engines/testbed/testbed.cpp

The linker fails when building with `--disable-cloud` and not passing `--disable-libcurl`

TESTBED: Fix building with --disable-cloud

---

engines/director/frame.cpp
engines/director/frame.h
graphics/macgui/mactext.cpp
graphics/macgui/mactext.h

This is #940 + #939 in one handy package, merge conflict-free.
If you have no objections to either please merge this one, since each one conflicts with the other.

DIRECTOR: Clean up renderText and use MacFont in MacText.

---

graphics/pixelformat.cpp

Greetings from ResidualVM.
While debugging color issues, I felt the need to have the total byte count in addition to format: `RGB888` can mean 3 or 4 bytes.
My initial idea would be to get to something like: `RGB-8888` for the 4-bytes variant, but typically PixelFormats I have seen then lack the alpha shift as it does not matter for conversions and [un]packing, so I gave up when this code became significantly longer than it currently is. And I believe seeing the actual byte size value is enough to tell the debugging developer that there is more to this packing format than meets the eye.
So I settled for `RGB888@3` and `RGB888@4` for given examples, as the change becomes trivial.
I could not spot callers which would expect a certain format, so I believe it *should* be safe to change this …

GRAPHICS: Include bytesPerPixel in toString representation

---

engines/dialogs.cpp

Previously, they were only greyed out. According to the discussion on
patch #8925, this was a limitation of the GUI layout engine when these
buttons were introduced in 2008. This no longer seems to be a problem.
Are there are any potential issues with changing this that I haven't considered? I don't remember the exact situation from 9 years ago.

GUI: Fully hide GMM save/load buttons if not supported by engine

---

engines/advancedDetector.cpp
engines/advancedDetector.h

This allows an engine to match files that exist multiple times
in the same game directory with the same basename.
For example, different releases of Torin's Passage in SCI engine
come with zero or more GERMAN, FRENCH, ENGLISH, etc. directories,
all containing files with the same basenames but with different
contents per language. Because the allFiles map used only the
basename of a file as a key, it could not match more than one of
these localization directories, which made it impossible to select
from all the possible languages.
See https://github.com/csnover/scummvm/commit/425dd7ed19a32611b3cba1b0f812aac496602b61 for an example implementation.
This all came about because there are multiple releases of Torin with different available localizations but with the same main resource bundles, …

ENGINES: Allow detection entries to match on full paths

---

devtools/create_project/create_project.cpp

This adds a quick ~~workaround~~ fix so that any if blocks nested inside a if block with an unmet condition are handled with push(false) even if their condition is satisfied.
For example, before adding this, upon running create_project.exe --msvc --disable-cloud the block inside
ifdef USE_CLOUD
ifdef USE_LIBCURL
... 
endif
endif
would get evaluated (with unpredictable results) since it was inside USE_LIBCURL (=1).
It now works for me ~~(after applying #962).~~

CREATE_PROJECT: Add fix for nested ifs

---

engines/director/director.h
engines/director/events.cpp
engines/director/frame.cpp
engines/director/frame.h
engines/director/lingo/lingo-builtins.cpp
engines/director/lingo/lingo-events.cpp
engines/director/lingo/lingo.cpp
engines/director/lingo/lingo.h
engines/director/resource.cpp
engines/director/score.cpp

This also does slight changes to semantics that follow from the docs and stubs primaryEvent and MovieScript handling.

DIRECTOR: Refactor lingo-events.cpp so that 1-ary processEvent is the unique entry point to events

---

common/endian.h
engines/hopkins/hopkins.h
engines/lure/luredefs.h
engines/queen/queen.h
engines/toon/tools.h

These changes are a subset of a commit in the external BOLT engine tree used for Merlin's Apprentice:
https://github.com/beholdnec/scummvm-bolt/commit/def568f05f600c87b10a89ca83d40fe80b09ea57
Since this commit mixes engine changes with making changes to common code and other engines, including removal of a WinCE specific hack in the Queen engine, this should be reviewed and merged prior to that engine's future PR discussions.
This will allow the external engine to be rebased and cleaned up in an easier manner without possible conflicts due to work on those other engines in the master tree in the meantime.
Also, the proposed change here to common/endian.h looks reasonable and will avoid other duplications in future of these kind of READ* and WRITE* functions.

COMMON: Migrate Various Endian Functions to Common from Engine Code.

---

engines/scumm/imuse/imuse.cpp

Fix the "MI2: Two soundtracks playing at once" bug from the forum, as
well as the one the bug reporter experienced.
Both are caused by starting tunes as trigger from other tunes. This code suppresses the start or kills the hanging tune on start of the next. I left in some debug statements to see when the code kicks in so we can determine if there are any unexpected side effects. In the final version those probably should be removed.

SCUMM: MI2: Kill hanging tunes on start of next, Fixes bug #1410

---

engines/titanic/star_control/star_view.cpp

Before you could look down, but not up using the keyboard. This fixes "/" not being mapped. This is for #10018. It still remains to change the semicolon ";" functionality so that it goes forward instead of backwords. Currently, there are two keys for going backwords, but none for going forward. 
I don't plan to implement the forward moving part since the math in that involved looks complicated.

TITANIC: Star View: Added keyboard key to look up

---

backends/platform/sdl/sdl.cpp

The thread locale concerns display options (e.g. date formatting), not
the display language. They are typically, but not necessarily the same,
as Windows allows them to be configured separately.

Windows: Use GetUserDefaultUILanguage() instead of GetThreadLocale().

---

engines/titanic/core/project_item.cpp
engines/titanic/detection.cpp
engines/titanic/main_game_window.cpp

Before titanic couldn't load the last save, or show its name in the GMM once saved. Now it can.
I also made the different files use the same const instead of defining their own.
Now if it is desirable to have more saved games it can just be changed in titanic.h and it works everywhere else.
Resolves #10051

Titanic: access last save

---

engines/titanic/star_control/camera_mover.cpp
engines/titanic/star_control/camera_mover.h
engines/titanic/star_control/star_camera.cpp
engines/titanic/star_control/star_camera.h
engines/titanic/star_control/star_view.cpp

This changes the starview manual camera movement using semicolon.
Before it slowed down the ship. To make it more like the original
game it now adds negative velocity so that it slows down then
speeds up in the backward direction.
The functions were renamed accordingly.

TITANIC: Change Starview slowdown to reverse

---

graphics/transparent_surface.cpp

Hi, I meet a bug concerning transparent surface when importing the sludge engine, which is, when a horizontally flipped sprite leaves the scene from the left side, it begins to disappear from the right side. So I guess maybe we need to take the flip mode in to account when handling off-screen clipping in transparent_surface.cpp and it works for Sludge games.
But I'm not sure if this is the right level to fix the bug as this part of code has existed for a long time without anyone else noticing this need, so I made a PR to discuss the problem.

GRAPHICS: Consider flip mode when handling off-screen clipping

---

graphics/transform_struct.h
graphics/transparent_surface.cpp

Add multiply blend mode to blitting of transparent surface.

Graphics:: Add multiply blend mode

---

README

I alphabetized the games in the 6.2 section (converting original saved games)
of the readme.
Also some minor edits to the titanic notes section of the readme (3.17).
These changes were mostly cosmetic and added fact that mouse click in
starmap allows ship to fast travel to that star (a very cool thing).

TITANIC: add that titanic supports original saved games to readme

---

engines/titanic/star_control/dvector.cpp
engines/titanic/star_control/dvector.h
engines/titanic/star_control/star_camera.cpp
engines/titanic/star_control/unmarked_camera_mover.cpp

Renamed functions from ambiguous names to ones with their function. This code involves matrix rotations, and transforms so the naming was along those lines.
Added lots of comments.
Changed out a questionable 4-quadrant atan implementation to use the standard atan2 instead.
Tested it out works the same as before.
I may come up with better naming and refactoring like combing with fvector after I read more of the star control code (I just focused on dvector for this change set).

TITANIC: Star control dvector class refactor

---

engines/titanic/star_control/fmatrix.cpp
engines/titanic/star_control/fmatrix.h
engines/titanic/star_control/viewport.cpp

1. Renamed 2 functions with unhelpful names.
fn2->MatRProd and fn3->MatLProd
one does the product of matrices on the right side and the other on the left.
2. Pulled common code of matrix product into one function and had the other two functions call that.
3. The general matrix product function was made into a non-member.
The over behavior of the star puzzle doesn't seem any different from these changes.

TITANIC: fmatrix refactoring

---

engines/titanic/star_control/daffine.cpp
engines/titanic/star_control/daffine.h
engines/titanic/star_control/dvector.cpp
engines/titanic/star_control/dvector.h

1. Move useful constants in dvector moved to header from the cpp so that DAffine can use them.
2. Improved naming of parameters.
3. Added a clear function to setRotation. There should of been some errors fixed from its use in dvector (without the previous matrices values being reset). Previously if you called setRotation twice it would only update the elements it was changing the 2nd time and not erase the previous values.
4. Changed convention for Y axis rotation. Now all three rotations are consistent with wikipedia. Dvector::getFrameTransform was aware of this and was negating the value so that result should still be same. However, star_camera.cpp line 288 was not so after locking onto the 2nd star the y-axis rotation will now go in the opposite direction as before. The direction is …

TITANIC: DAffine refactor

---

engines/scumm/script_v6.cpp

Room 0 is a blank screen, fading out has no effect. So simply skipping the call is a reasonable way to prevent the crash mentioned in the bug report.

SCUMM: Prevent darkenPallete() in Room 0 in FT, fixes bug #9871

---

engines/titanic/star_control/daffine.cpp
engines/titanic/star_control/fpose.cpp
engines/titanic/star_control/fpose.h
engines/titanic/star_control/star_camera.cpp
engines/titanic/star_control/star_view.cpp
engines/titanic/star_control/viewport.cpp

1. Changed fpose, which is like daffine, but float, to have yaxis rotation like wikipedia
2. Fixed unmarked looking with keyboard keys and mouse going wrong way because of last change by adding negatives to angle directions.
3. Replaced inverse computation for daffine and fpose to just take transpose for rotation part of inverse.
This replaces a lot of code, and prevents stability issues.

TITANIC: Daffine and fmatrix work

---

configure

We get this warning a lot for the Singleton class due to the way we instantiate its specializations. An alternative way to fix the issue would be to change the way we do this instantiation, as proposed in PR #967, but this had drawbacks (related to loading plugins).
Silencing the warning doesn't seem to be an issue to me as we get a link error anyway in case we forget an instantiation. The warning is only useful insofar as it allows pinpointing the exact issue.
I opted to check if the flag is supported rather than add it depending if have_clang is set to yes and the compiler version as apple uses different clang versions from other releases, and using the gcc version reported by clang might not be a good indicator.
Note: I also added a `-Werror` when we check if a warning is supported, as …

CONFIGURE: Silence undefined-var-template warning

---

engines/titanic/star_control/base_stars.cpp
engines/titanic/star_control/base_stars.h
engines/titanic/star_control/camera_auto_mover.cpp
engines/titanic/star_control/camera_auto_mover.h
engines/titanic/star_control/dvector.cpp
engines/titanic/star_control/dvector.h
engines/titanic/star_control/fmatrix.cpp
engines/titanic/star_control/fmatrix.h
engines/titanic/star_control/fvector.cpp
engines/titanic/star_control/fvector.h
engines/titanic/star_control/marked_auto_mover.cpp
engines/titanic/star_control/marked_camera_mover.cpp
engines/titanic/star_control/star_camera.cpp
engines/titanic/star_control/star_camera.h
engines/titanic/star_control/star_control.cpp
engines/titanic/star_control/star_crosshairs.cpp
engines/titanic/star_control/star_view.cpp
engines/titanic/star_control/star_view.h
engines/titanic/star_control/unmarked_auto_mover.cpp
engines/titanic/star_control/unmarked_camera_mover.cpp

1. Added an enum for star_camera that is more informative about number of stars locked on. Many other classes still use it as an int so this could be expanded to those, later.
2. Reduce some file dependencies of files related to the star_camera class.
3. Some function renames and more comments
4. Fix for #10126. There were a lot of ways it crashed then mentioned in the ticket so I fixed all the different ways and tested the puzzle a lot. That section of code may benefit from case statements or more functions.

TITANIC: CStarCamera Refactoring and CStarCrosshairs logic fix

---

engines/titanic/star_control/camera_auto_mover.cpp
engines/titanic/star_control/camera_auto_mover.h
engines/titanic/star_control/fmatrix.cpp
engines/titanic/star_control/fvector.cpp
engines/titanic/star_control/fvector.h
engines/titanic/star_control/marked_auto_mover.cpp
engines/titanic/star_control/star_camera.cpp
engines/titanic/star_control/star_camera.h
engines/titanic/star_control/star_view.cpp
engines/titanic/star_control/unmarked_auto_mover.cpp
engines/titanic/star_control/viewport.cpp

The code was preventing the position and view from changing
when the distance between the current and new position for
a marked auto mover was zero. This happens if you lock the
2nd or 3rd star and then unlock and relock again.
It was prevented this with asserts and if statement checks
and I removed them all.
This section of code isn't doing any inverses based on the
reciprocal of the distance so there is no issue with allowing
transition speeds/distances of zero.
Fixes #10148.

TITANIC: Change ship view and position even if not moved

---

image/codecs/indeo/indeo.cpp
image/codecs/indeo/indeo.h
image/codecs/indeo4.cpp
image/codecs/indeo4.h
image/codecs/indeo5.cpp

This fixes the various SGT stateroom furniture and Titania parts (and maybe a couple other miscellaneous places using Indeo4 transparency) in TITANIC engine.
There are still a few visual artefacts remaining for some transparent videos:
* The Major Horizontally Mobile Storage Compartment (b14.avi) renders a block of half-shelf, half-black to the right of the top shelf whenever it is opened (or closed when you leave and re-enter the stateroom) which gets stuck on the screen.
* The Personal Maintenance Hub (b7.avi) seems to have its top-left edges cut off on some frames, and on other frames the lower-right draws pixels that should be transparent.
I don’t *think* these are Indeo4 transparency problems any more since the validation checks pass (the code reads exactly the right number of pixels …

IMAGE: Implement Indeo4 transparency

---

engines/titanic/star_control/camera_auto_mover.cpp
engines/titanic/star_control/camera_auto_mover.h
engines/titanic/star_control/camera_mover.cpp
engines/titanic/star_control/camera_mover.h
engines/titanic/star_control/daffine.cpp
engines/titanic/star_control/dvector.cpp
engines/titanic/star_control/dvector.h
engines/titanic/star_control/marked_auto_mover.cpp
engines/titanic/star_control/marked_auto_mover.h
engines/titanic/star_control/marked_camera_mover.cpp
engines/titanic/star_control/marked_camera_mover.h
engines/titanic/star_control/matrix_inv.h
engines/titanic/star_control/star_camera.cpp
engines/titanic/star_control/star_camera.h
engines/titanic/star_control/unmarked_auto_mover.cpp
engines/titanic/star_control/unmarked_auto_mover.h
engines/titanic/star_control/unmarked_camera_mover.cpp
engines/titanic/star_control/unmarked_camera_mover.h

1. Renaming of variables and functions names for Camera mover and derived classes, Automover and derived classes,
2. Lots of work on starcamera since thats were lockMarker2 is and the 9961 locking issue.
3. Added a 4x4 inverse, one of the issues was that the col4 for the inverse of the daffine matrix being calculated in lockMarker2 was not quite right. So using a full on inverse lets me get the correct col4. This was from the mesa 3d library and I put that function in a separate file with the MIT license header (star_control/matrix_inv.h)
4. In lockMarker2 istead of having the mover transition from the old position to the move I have it just start at the new position and do the required orientation change to lock star2. This fixes 9961 since locking on now does not overshoot the lock on …

TITANIC: Star_Control/Fix9961

---

engines/titanic/star_control/star_camera.cpp
engines/titanic/star_control/star_camera.h
engines/titanic/star_control/star_view.cpp

Fixes #10170.
I've added a boolean variable that tracks whether the game is
in the process of locking onto a star or not.
When the user hits the unlock button _isInLockingProcess gets checked and
the request to unlock is denied if the locking on is currently happening.
Once the locking on is finished then the release is lifted and the user
can unlock at this time (or after locking onto the next star).

TITANIC: Don't allow unlocking stars while locking onto a star

---

common/rect.h
engines/sci/graphics/helpers.h

I’ve been using this macro fairly frequently in all sorts of code that uses rects during debugging, so it seems like something that would be generally useful. Since this changes `common/rect.h` it will invalidate pretty much every object cache so I didn’t want to just commit this and tie up buildbot for hours unexpectedly. Unless there is some objection to its inclusion in common, please feel free to land this whenever it won’t be too disruptive to others (or just let me know when that would be and I will do it then).

COMMON: Add helper macro for printing rects

---

engines/titanic/star_control/camera_auto_mover.cpp
engines/titanic/star_control/camera_auto_mover.h
engines/titanic/star_control/marked_auto_mover.cpp
engines/titanic/star_control/marked_auto_mover.h
engines/titanic/star_control/marked_camera_mover.cpp
engines/titanic/star_control/star_camera.cpp
engines/titanic/star_control/star_camera.h
engines/titanic/star_control/unmarked_auto_mover.cpp
engines/titanic/star_control/unmarked_auto_mover.h
engines/titanic/star_control/unmarked_camera_mover.cpp
engines/titanic/star_control/viewport.cpp
engines/titanic/star_control/viewport.h

1. Removed some todos
2. Improved naming of mover handler in star camera
3. camera auto mover improved naming and usage of setPath and setOrientation

TITANIC: Star_control-cleanup

---

engines/titanic/game/captains_wheel.cpp
engines/titanic/game/nav_helmet.cpp
engines/titanic/game/nav_helmet.h
engines/titanic/star_control/star_control.cpp
engines/titanic/star_control/star_control.h

1. Better naming for flag of helmet being on or off
2. Only play locking/unlocking sounds in starview
3. After hitting go once on captain wheel it resets
Item 2 made more sense. Previously, it would play the locking and unlocking sounds when in skyview, but not actually do any unlocking/locking. This is a deviation from the original, but I think it makes more sense.
Item 3 makes it line up with the original and I think it makes more sense.

TITANIC: Star-control_changes

---

graphics/pixelformat.h

GRAPHICS: Compare all fields in a PixelFormat individually instead of using memcmp.

---

engines/bbvs/minigames/bbant.cpp

These shifted values are replaced with their literal equivalents
as would be calculated on an x86.

BBVS: Fix UB shifting negative signed integers

---

engines/agos/draw.cpp

In commit f0581bab4a4b1b4102a7fbdd4a3d54d4397e00e9 the index value
for the array was changed from a constant to a variable, but uint8
is too small to contain 293, so this value was ending up as 37.

AGOS: Fix value truncation in AGOSEngine::animateSprites

---

engines/xeen/map.cpp

Corrected spelling in xeen/map.cpp

---

engines/cge/detection.cpp
engines/cge2/detection.cpp
engines/director/detection.cpp
engines/sludge/detection.cpp

This makes the engines cge, cge2, sludge and directory leave `SearchMan` unchanged by their fallback detection. This fixes https://bugs.scummvm.org/ticket/10173 .

Clean up use of SearchMan in fallback detection

---

audio/decoders/quicktime.cpp
audio/midiparser_qt.cpp
backends/networking/curl/networkreadstream.cpp
backends/networking/curl/networkreadstream.h
common/memstream.h
engines/agi/sound_midi.cpp
engines/dm/eventman.cpp
engines/fullpipe/statesaver.cpp
engines/gnap/menu.cpp
engines/pegasus/ai/ai_area.cpp
engines/scumm/saveload.cpp
engines/sword1/control.cpp
engines/sword25/gfx/screenshot.cpp
engines/sword25/script/luascript.cpp
engines/xeen/saves.cpp
engines/xeen/saves.h
engines/zvision/file/save_manager.cpp

The default value was DisposeAfterUse::NO, which made it easy to accidentally leak memory by omitting to specify a value.
Also fix various memory leaks due to not setting DisposeAfterUse::YES when constructing dynamic memory streams.
Some non trivial changes were needed in the XEEN engine that @dreammaster may want to check.
I was intending to mark the `MemoryReadWriteStream` and `MemoryWriteStreamDynamic` classes as final because subclassing those seems like a bad idea to me (And they have a non-virtual destructor making it easy to leak memory in a creative way). However there are two remaining subclasses in LASTEXPRESS and SCI. Thoughts?

COMMON: Remove the DisposeAfterUse default value from dynamic write memory streams constructors

---

engines/titanic/core/game_object.cpp
engines/titanic/core/project_item.cpp
engines/titanic/core/project_item.h
engines/titanic/debugger.cpp
gui/console.cpp
gui/debugger.cpp
gui/debugger.h

This implements splitting of lines entered in the debugger into parameters with support for double quoted strings. In the Titanic engine, this allows for easier specification of specific views to jump to. In other engines, it may make it easier to specify things like item names that include spaces.

GUI: Support double quoted debugger parameters

---

common/array.h
common/memory.h
test/common/array.h

This PR adds:
1. New [constructor signatures (2) and (3)](http://en.cppreference.com/w/cpp/container/vector/vector), for common constructions to create arrays of a specific size.
2. New [data method](http://en.cppreference.com/w/cpp/container/vector/data), for retrieving a pointer to the underlying storage of a Common::Array, even when the array is empty.
I don’t feel like these should be at all controversial since they are just imports from the C++ standard library, and there are tests, but let me know if there are any objections.

COMMON: Add new standard methods to Array

---

configure
ports.mk

Tremor and (in most cases) FLAC require libogg, however it was only being checked for when building with Vorbis support, meaning that Tremor couldn't be used when linking statically. This adds separate detection for libogg, and modifies detection for Vorbis, Tremor and FLAC accordingly.

CONFIGURE: Add proper detection for libogg

---

backends/midi/coreaudio.cpp
backends/midi/coremidi.cpp

After reading this [forum post](http://forums.scummvm.org/viewtopic.php?t=14422) I decided to take a look at the CoreMIDI API documentation, and since it seemed easy enough changed the code to try to list available devices so that the user can select which one to use.
I tried this with a software synthesiser and it seems to work correctly. However since I know absolutely nothing about MIDI and don't have any MIDI hardware I decided to open this pull request so that others can have a look, and hopefully try it, before this gets merged.

MACOSX: Allow selecting device for CoreMidi

---

audio/decoders/qdm2.cpp
common/endian.h
common/hash-ptr.h
common/scummsys.h
common/stream.h
configure
devtools/create_project/cmake.cpp
devtools/create_project/msvc.cpp
engines/director/lingo/lingo.h
engines/fullpipe/utils.h

ScummVM has a `HAVE_INT64` define to check is the target platform supports 64 bits integers. However `uint64` is used without any checks in the main source code: https://github.com/scummvm/scummvm/blob/d75dab4e55f15133eaef3c25f616e04566427101/common/str.h#L166 
It has been that way for some time, including a release. This is proof enough to me that our target platforms support 64 bits integers, and that the `HAVE_INT64` check can be removed.
This pull request removes that check and makes 64 bits integers mandatory in `configure`. It goes a bit further along that path by replacing the `SCUMM_64BITS` define by a pointer sized integer, `uintptr`, bringing us closer to C99's `stdint.h`.
This pull request also adds a partial template specialization to `Hash` for pointers (Like C++11's …

BUILD: Require 64bits integers

---

engines/scumm/detection.cpp

Ignore steam files of which we don't know the MD5. Currently this causes a [crash (assert)](https://bugs.scummvm.org/ticket/10290) on trying to read the (non-existing) index file from the executable. Unknown steam variants can't be handled anyway because we need to hardcode the offset to the game index file in ScummVM.

SCUMM: Prevent false detection of Steam games

---

engines/lure/res.cpp

While usage of these pointers was technically safe because they
were read through an alignment-aware API, taking the address of an
unaligned pointer was generating warnings in Clang, and is not
strictly necessary here. This change solves the warning and also
protects this code from any future change that might cause it to
start reading unsafely.
I think this change should be safe and not cause any trouble, but
I do not have this game so cannot test it myself to be sure. So
if someone else can either test it or look and make sure I did
not do something stupid, I would appreciate it.

LURE: Stop taking address of unaligned pointer

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp

On the OpenPandora handheld, the OSD message would not render unless you moved the cursor in the area where it was supposed to show. Additionally, the OSD message was not transparent like in v1.8.
This fixes both these issues, but to be honest, I not exactly sure why.

SDL: fix OSD message artifacts

---

engines/hugo/display.cpp
engines/hugo/display.h
engines/hugo/inventory.cpp
engines/hugo/inventory.h
engines/kyra/screen_lol.cpp
engines/kyra/screen_lol.h
engines/lure/res_struct.cpp
engines/lure/res_struct.h
engines/mohawk/riven_scripts.cpp
engines/mohawk/riven_scripts.h
engines/tony/mpal/mpal.cpp
engines/tony/mpal/mpal.h
engines/tsage/core.cpp
engines/tsage/core.h

Passing an argument of a type that undergoes default argument promotion as last argument of a variadic function results in an undefined behaviour. This includes bool, char, short, and enumerations.
See http://en.cppreference.com/w/cpp/language/variadic_arguments#Default_conversions
In ScummVM some code was using an enum or an uint16 as last argument of variadic functions, and they have been replaced by int and uint respectively in this PR to avoid the undefined behaviour.
Note: they were reported by clang when compiling with -Wvarargs

Fix undefined behaviour in variadic functions

---

engines/neverhood/resourceman.cpp

Patched size was wrong too.
[https://bugs.scummvm.org/ticket/7085](https://bugs.scummvm.org/ticket/7085)

NEVERHOOD: fix musical hut crash in DR, bug #7085

---

engines/tinsel/object.h

This needs to be at least 374 to avoid crashes in the in-game
save/load dialogues with save games using the maximum 40 letters
per save game, so just round up to the next power of two (which
increases memory usage by a whopping ~20KiB) to give more than
enough space for long save game names.
Fixes Trac#6748.
Pretty sure this is fine, save code does not seem to care
about this object list and some quick save/load tests seemed
to work fine, but since I am not familiar with this engine it
seemed like a good idea to PR the change even though it is
otherwise trivial.

TINSEL: Increase maximum number of objects

---

backends/events/default/default-events.cpp
backends/events/default/default-events.h
backends/events/sdl/sdl-events.cpp
backends/platform/android/events.cpp
backends/platform/sdl/sdl.cpp
backends/platform/tizen/form.cpp
backends/vkeybd/virtual-keyboard.cpp
common/events.h
common/recorderfile.cpp
engines/agi/keyboard.cpp
engines/dm/eventman.cpp
gui/EventRecorder.cpp

Unlike its predecessor, SDL2 always generates keydown repeat events. ScummVM was not updated to account for it. As a result, key repeat events received by the engines are not properly flagged.
This pull request makes sure the repeat events are flagged and disables ScummVM's own repeat event generation when using SDL2. This allows to use the operating system's configured timings for key repeats instead of ScummVM's hardcoded values.

SDL2: Improve handling of keyboard repeat events

---

engines/neverhood/resourceman.cpp

After player gets to the castle using a robot, there are no Willie's notes any more. Instead, there are notes from "Windows'" (in "Dyadyushka Risech" Russian version) on red paper. These notes require patching.

NEVERHOOD: fix late game notes crash in DR

---

configure

This allows more engines to be linked at once. While this isn't enough to link all engines, this does mean that all engines currently marked as stable can be enabled, so it'll do for now.

RISCOS: Attempt to reduce binary size

---

engines/sky/compact.cpp
engines/sky/compact.h
engines/sky/logic.cpp

Dereferencing an unaligned pointer will cause a memory fault on
at least older ARM and SPARC architectures, and is warned about
starting in Clang 4.

SKY: Fix unaligned pointer dereferences

---

engines/composer/detection.cpp

Fixes bug [10199](https://bugs.scummvm.org/ticket/10199)

COMPOSER: Added MD5 for the German version of Imo and the King

---

engines/wage/entities.h
engines/wage/script.cpp
engines/wage/script.h

This reverts commit ea0fb987e042a86b8da683cafa7b9cf04d1636e6.
This issue was discovered during a full build of ScummVM using Clang 5,
which was generating a warning about this code since it is not valid.
It is UB to call a null pointer. Whatever caller is trying to do so needs
to be fixed instead.
My opinion is that keeping this workaround in the codebase instead of
fixing the bad calls runs the risk of allowing more bad calls to slip in
during development of the engine, and may make it more difficult (if it
is not already very difficult already since this engine has not been
worked on for a while) remember what the condition was where this invalid
call happened and fix it.

Revert "WAGE: Fix crashes for poorly initialized objects"

---

engines/sherlock/resources.cpp

Sherlock Holmes - Case Of The Rose Tattoo:
Low memory devices (for example the WII) throws an "Out Of Memory" error during the intro and the gameplay. The reason is that all resources are cached in the memory. It improves the performance when resources are compressed. But the cache shouldn't be used for uncompressed resources.

SHERLOCK: Disable cache for uncompressed resources

---

backends/platform/psp/display_manager.cpp
backends/platform/psp/display_manager.h

This patch is derived from dam-soft's information on bug #10239 "PSP port incorrect 4:3 aspect radio":
https://bugs.scummvm.org/ticket/10239
This should be reviewed by the PSP porter prior to merging.

Proposed Fix for PSP Aspect Ratio Preservation in 4:3

---

engines/neverhood/neverhood.cpp

Currently the Neverhood-Engine kills the mainprocess instead of breaking the gameloop on shutdown. The WII throws an dsi error after closing the game.

NEVERHOOD: Graceful shutdown of the engine

---

backends/events/sdl/sdl-events.cpp
configure
engines/cge/snail.cpp

* Yopy: https://en.wikipedia.org/wiki/Yopy
Production ceased in 2005. There was never an official release. I can't find traces of an unofficial release.
* Zaurus: https://fr.wikipedia.org/wiki/Zaurus
Production ceased in 2007. There was never an official release. The last unofficial release of ScummVM was 0.6.0.
I'm working on improving the keymapper. They look very obsolete, I'd rather remove them than port them to the new model.

PORTS: Remove the Zaurus and Yopy ports

---

backends/platform/maemo/maemo.cpp
backends/platform/sdl/ps3/ps3.cpp
backends/platform/sdl/psp2/psp2.cpp
backends/vkeybd/virtual-keyboard.cpp
backends/vkeybd/virtual-keyboard.h
common/ptr.h

Virtual keyboard data files are now searched in the `datadir` provided at configure time.
This allows ports to use the virtual keyboard without custom code or shipping default configuration.

 VKEYBD: Fallback to SearchMan when loading keyboard packs

---

engines/zvision/scripting/scr_file_handling.cpp

Since no one has been able to suggest a fix for any ScummVM bug responsible for bug #6770 ("ZVISION: Control lever still visible after opening Perils of Magic time tunnel"), here's my attempt at fixing it as a script bug in Zork: Grand Inquisitor.
NB: I've only tried the puzzle itself, and I've only tested with the English DVD version of the game. Oh, and I'm also not that familiar with the game engine itself. What could go wrong? :-)

ZVISION: Workaround for bug #6770

---

image/codecs/indeo3.cpp

This gets rid of all
warning: this statement may fall through [-Wimplicit-fallthrough=]
`gcc` warnings in `indeo3.cpp`.
I'm not familiar with the code but obviously the decoder is working and based on how the `case` statements are grouped it's obvious that these fallthroughs are intentional.

IMAGE: Fix Indeo3 compiler warnings

---

audio/mods/protracker.cpp

Mission Supernova uses the ProtrackerStream to play its intro and outro music.
For some time I noticed sound artifacts but I couldn't find the cause on my side.
So, after some digging I tracked down an overflow in the 'Portamento to note' effect.
Currently agos, gob, hopkins and parallaction are the only engines besides Supernova
that make use of a ProtrackerStream.
I have tested it only on Supernova so far but if anyone is aware of sound glitches in the
mentioned engines, it would be great if you could test it or create a bug report.
EDIT: I uploaded a before/after video [here](https://www.youtube.com/watch?v=9PsFNE_VlnM)

AUDIO: Fixes Protracker Portamento effect

---

backends/platform/null/null.cpp
backends/platform/sdl/posix/posix-main.cpp
configure

Listing RISC OS as a POSIX platform initially allowed me to use the POSIX filesystem classes, however once the RISC OS filesystem classes were introduced, the RISC OS port no longer makes any meaningful use of ScummVM's POSIX functionality, with some exceptions.
This disables the POSIX-specific code in Networking for now, this is something I'll address in a separate PR.
The key combination has also changed from Ctrl-Q to Ctrl-Z. I'm not sure what to do about this at the moment - neither combination is standard on RISC OS (although I've seen at least one program use Ctrl-Q). Thoughts?

 RISCOS: Don't list RISC OS as a POSIX platform

---

backends/events/sdl/sdl-events.cpp
backends/events/sdl/sdl-events.h

The mouse cursor now moves across the screen in a similar amount of time irrespective of the display resolution.

SDL: Scale the joystick mouse speed with the vertical window size

---

engines/scumm/sound.cpp

It looks like the code was there, but it was never fully implemented
because _curSoundPos was never being incremented. Experimentally,
it looks like it works if it is a 60FPS counter.

SCUMM: really implement lipsync

---

engines/scumm/actor.cpp

These two fixes should be good to go as-is, but I wanted
to open this as a PR anyway since I don’t think these are the
only two places where there is a stack overflow in SCUMM, didn’t
want to commit these and not check all the other places first,
but I don’t have the time right now to do research on all the
other places where I found some `int args[N]` in the codebase.
So maybe someone else can look for me? It could be an interesting
small project taking an hour or two, and I would appreciate it.

SCUMM: Fix stack overflows

---

engines/tucker/tucker.cpp

This ensures that the calculated offsets for Bud and Billy are [0,2] px
and follow the sequence 0px -> 1px -> 2px -> 1px -> 0px as opposed to
the earlier 0px -> 1px -> 2px -> 3px -> 0px which resulted in them
teleporting back to their original location and on top of that being
out of sync with the boat.
Fixes Trac#6643.
/cc @raziel- (you reported this bug)

TUCKER: Cure Bud's and Billy's seasickness

---

engines/tucker/tucker.cpp

This fixes a bug in `drawStringInteger()` (used for drawing savegame slots in the original game UI) where the x-coordinate for the dirty rect was wrongly calculated.

TUCKER: Fix dirty rects drawing bug in drawStringInteger()

---

engines/tucker/saveload.cpp
engines/tucker/tucker.cpp
engines/tucker/tucker.h

Before, the ingame load dialog pretended to allow loading savegames from all possible slots even if no savegames existed.
This introduces the original interpreter's behavior which instead loads a resource string from `infobar.txt` informing the user that no savegames are available.
Fixes Trac#10417.

TUCKER: Print infobar string if no savegame exists

---

engines/scumm/detection.cpp
engines/scumm/detection_tables.h

Rewrote the detection matching to use the extra field like the other
two.
This requires extensive testing due to touching code shared for a lot of
games and being sensitive to individual versions of games.

SCUMM: Check for and flag demos correctly (PR#931 Fixup)

---

engines/sci/engine/script_patches.cpp

This ensures the detected speed will end up at the highest level. This
improves the detail in Yorick's room (96), and slightly changes the
timing in other rooms.
Fixes bug #10296.

SCI: Sabotage qfg1vga's speed test

---

backends/platform/sdl/sdl-sys.h

It’s questionable that the SDL backend code is trying so hard to
maintain forbidden symbols at all since backend code is exactly
where such things are allowed, and it is a game of whack-a-mole
to keep system API changes from breaking this fragile system of
symbol redefinitions. Probably this should all just get replaced
with a FORBIDDEN_SYMBOL_ALLOW_ALL, but for the time being this at
least gets builds working again on up-to-date msys2/mingw-w64
compilers.
Fixes Trac#10405.

Fix broken compilation on up-to-date msys2/mingw-w64

---

engines/scumm/dialogs.cpp
engines/scumm/dialogs.h
graphics/VectorRenderer.h
gui/EventRecorder.cpp
gui/ThemeEngine.cpp
gui/ThemeEngine.h
gui/Tooltip.cpp
gui/Tooltip.h
gui/about.cpp
gui/about.h
gui/console.cpp
gui/console.h
gui/dialog.cpp
gui/dialog.h
gui/gui-manager.cpp
gui/massadd.cpp
gui/widgets/popup.cpp

Pull request #1102 added dirty checking as a level of indirection when drawing
the GUI. This PR removes a previously existing level of indirection, the draw
queues. With this, we are back to one level only. This makes it easier to debug why
a particular low level draw method was called, by inspecting the call stack.
Draw calls now happen directly instead of being queued to the backbuffer or
screen queues. The background and foreground dialog layers are now drawn
to the appropriate surface by doing a rendering pass for each layer.
The goal here is only code cleanup. There should be no significant performance
changes.

GUI: Remove the ThemeItem draw queues

---

README
backends/events/sdl/sdl-events.cpp
backends/events/sdl/sdl-events.h

1) Allow to load a custom game controller mapping file 
- Either define a "gcdbfile" property in your configuration file (pointing to desired file)
- Or copy a file named "gamecontrollerdb.txt" in your extra path
This file completes the standard SDL one to support more game controllers.
Can be found here, for instance: https://github.com/gabomdq/SDL_GameControllerDB
2) Add a specific joystick button to open virtual keyboard (button 7), only for joysticks with no game controller support or SDL1

SDL: Can load game controller DB file + joystick button for virtual keyboard

---

common/scummsys.h

Compatibility based on the information provided [here](https://stackoverflow.com/questions/4226308/msvc-equivalent-of-attribute-warn-unused-result/49468398#49468398).

COMMON: Add WARN_UNUSED_RESULT to scummsys.h

---

.gitignore
audio/softsynth/opl/mame.cpp
backends/fs/ds/ds-fs-factory.cpp
backends/fs/ds/ds-fs.cpp
backends/platform/ds/arm7/source/main.cpp
backends/platform/ds/arm9/source/cdaudio.cpp
backends/platform/ds/arm9/source/dsmain.cpp
backends/platform/ds/arm9/source/dsmain.h
backends/platform/ds/arm9/source/dsoptions.cpp
backends/platform/ds/arm9/source/fat/disc_io.c
backends/platform/ds/arm9/source/osystem_ds.cpp
backends/platform/ds/arm9/source/osystem_ds.h
backends/platform/ds/arm9/source/wordcompletion.cpp
backends/platform/ds/arm9/source/zipreader.cpp
backends/platform/ds/ds.mk
backends/plugins/ds/ds-provider.cpp
configure
gui/predictivedialog.cpp

This continues off of PR #1057.
The commits from there would allow it to build, but the .nds file produced wasn't working; it would whitescreen on load. My first commit tweaked the arguments to ndstool to get it working. I'm not certain why it was using objcopy in the first place, perhaps ndstool itself changed?
The second commit fixed the touch screen, which wasn't working at all. At first I thought it just wasn't working on my 3ds due to the removal of pressure sensitivity from the original DS; but, my original DS had the same issue, so I suppose that wasn't the problem.
There are still some outstanding issues:
* The binaries are larger than the old ScummVM DS releases. I'm not sure if the core is just bigger now or there's some other reason for it. I can't put as many engines into a …

DS: Fix compilation and touch input

---

audio/fmopl.cpp
audio/module.mk
audio/softsynth/opl/nuked.cpp
audio/softsynth/opl/nuked.h
base/commandLine.cpp

This commit adds Nuked OPL3 core.
This core emulates OPL3 chip nearly perfectly as it is based on chip's internal logic reverse engineering and extensive hardware tests.
On downside this core requires more powerful device than MAME and DOSBox cores.

AUDIO: Add Nuked OPL3 core

---

image/codecs/cinepak.cpp
image/codecs/cinepak.h

I noticed that Starship Titanic produces lots of "uninitialized value" warnings when turning right at the very beginning. This appears to be because the very first frame of the CinePak movie uses codebooks that haven't been explicitly loaded.
This pull request works on the assumption that all codebook data should be initialized with 0 before the decoding starts.

IMAGE: Explicitly initialize CinePak codebooks

---

engines/mohawk/myst_stacks/myst.cpp

Fixes #Trac10486.
In ScummVM when the hour was set to what should be 12:XX it was
displayed as 0:XX. This differs with the original which displays
the 12:xx.
I verified this fix in both Myst ME and Myst English CD.

MOHAWK: MYST: Fix Observatory displayed hour from 0:XX to 12:XX

---

gui/ThemeEngine.cpp
gui/ThemeEngine.h
gui/Tooltip.cpp
gui/about.cpp
gui/console.cpp
gui/dialog.cpp
gui/object.cpp
gui/object.h
gui/widget.cpp
gui/widget.h
gui/widgets/editable.cpp
gui/widgets/edittext.cpp
gui/widgets/list.cpp
gui/widgets/popup.cpp
gui/widgets/scrollbar.cpp
gui/widgets/scrollcontainer.cpp
gui/widgets/scrollcontainer.h
gui/widgets/tab.cpp

This is a clean up for the GUI code. The main change is that the draw clipping rect is now part of the ThemeEngine state, allowing to unify the clip and non-clip variants methods, reducing code duplication.
This also contains some unused code removal.

GUI: Unify clip and non-clip draw calls

---

engines/mohawk/myst_stacks/selenitic.cpp

1. Slow down sound receiver turn rate at maximum speed so it can actually be possible to stop close to a desired angle.
2. The receiver direction hint is now given when < 5 degrees away rather than when <= 5 degrees away. This has it line up with the original.
I think the sound receiver rotating could probably be improved further as it is jumpy, but at least now it is more usable. 
I've also seen the directional hint behavior sporadic and I will try to see if I can repo that. Sometimes the hint stop blinking and such.

MOHAWK: Myst: Selentic receiver improvements

---

engines/sci/graphics/animate.cpp
engines/sci/graphics/palette.cpp
engines/sci/graphics/palette.h

The new approach is to delay kAnimate briefly (with a 100ms timeout)
while there is a zero-tick PalVary running, so that it has time to
trigger.
The previous workaround would immediately process a zero-tick
PalVaryInit/PalVaryReverse. This caused problems in QfG3 (bug #10304)
where it interfered with PalVaryPause.
The previous workaround could also be modified to handle pause/resume,
but this new approach should be closer to SSCI's behaviour, which used a
timer for a zero-tick PalVary too.
This fixes bug #10304, and keeps #5298 fixed too.

SCI: Change workaround for PalVary / Animate race condition

---

engines/mohawk/dialogs.cpp
engines/mohawk/myst.cpp
engines/mohawk/myst_scripts.cpp
engines/mohawk/myst_stacks/channelwood.cpp
engines/mohawk/myst_stacks/dni.cpp
engines/mohawk/myst_stacks/mechanical.cpp
engines/mohawk/myst_stacks/myst.cpp
engines/mohawk/myst_stacks/selenitic.cpp
engines/mohawk/myst_stacks/stoneship.cpp
engines/mohawk/myst_state.cpp
engines/mohawk/myst_state.h

Previously, the held page stage was an unsigned int 16
with values 0-13. The enum will make its state more clear.
Because enums are implicitly ints in c++03 and _global->heldPage
is an uint16 I have to typecast to uint16 when ever I compare
the enum. This is not ideal, but I still think the enum with
the cast is more clear.
I have also noted interesting behavior as TODO's.

MOHAWK: MYST: Turn held page state into an enum

---

README
base/commandLine.cpp

This include two changes:
- Change the syntax of the command to use `--game=TARGET` to specify the target, and thus be consistent with other commands.
- Allow listing save games for all known targets (when no target is specified by the user).

Improve command line --list-saves command

---

engines/mohawk/myst.cpp
engines/mohawk/myst_stacks/intro.cpp
engines/mohawk/myst_stacks/myst.cpp
engines/mohawk/myst_stacks/preview.cpp
engines/mohawk/myst_state.cpp
engines/mohawk/myst_state.h

This global basically tracks what age/book/stack
the player is in.
E.x., instead of _global.currentAge = 2
now _global.currentAge = kMystLibrary.
Interestingly, two integer values (5,8) are
never used.
Also two of the endings are considered Ages
instead of being apart of _global.ending.

MOHAWK: MYST: Make global currentAge an enum

---

engines/mohawk/myst.cpp
engines/mohawk/myst_stacks/credits.cpp
engines/mohawk/myst_stacks/dni.cpp
engines/mohawk/myst_stacks/myst.cpp
engines/mohawk/myst_state.cpp
engines/mohawk/myst_state.h

The global variable "ending" tracks various
states that Atrus can be in.
This variable determines what video of
Atrus will be playing and if the brother
books have been destroyed.
Despite this variable being called ending
there are other endings not captured by
this variable (like the brother endings).
Additionally, the enum could also be called DiniState. 
I originally had the 4rth enum called kAtrusReturns since that state is also associated with him returning, but because of it usage in places like Myst::toggleVar were the brother book states were being checked it made sense to give it the kBooksDestroyed name. So I could have a 5th enum value that is called kAtrusReturns and just map that to kBooksDestroyed so that when it is more clear to use one form, kAtrusReturns in Dini, and, …

MOHAWK: MYST: Make Dini/Atrus endings an enum

---

common/str.cpp
common/str.h
gui/debugger.cpp

It made little sense for the tab-completion to be case sensitive while command execution itself is case insensitive.

GUI: Make the tab completion case insensitive in the debug console

---

README
backends/audiocd/audiocd.h
backends/audiocd/default/default-audiocd.cpp
backends/audiocd/default/default-audiocd.h
backends/audiocd/win32/win32-audiocd.cpp
engines/xeen/scripts.cpp

The current CD manager play method always internally plays the given track/file using the kMusicSoundType. This is a problem for the World of Xeen 2 CD  Talkie, since for it, the audio tracks are all exclusively voice samples. This would be an exacerbated problem for it, since the game keeps playing background music when the CD voice samples are played. And we don't want the voice playback to be reduced in volume when players try to reduce the music volume so they can hear the speech more clearly.

XEEN: Add an optional param to CD playback to specify sound type

---

gui/console.cpp
gui/console.h

Ctrl-C copies the input line.
Ctrl-V inserts the clipboard content at the cursor position.

GUI: Add copy and paste support to the graphical debugger

---

engines/xeen/scripts.cpp

Track 31 is on the first cd, but contains speech for Darkside content
(e.g. Ellinger). It is referenced as track 31, so the offset must not
be added.

XEEN: Fix voice playback from track 31

---

engines/scumm/scumm.cpp

v5+ scripts can request saving/loading of savegames, this type of
savegame is internally called a "temporary" savegame
(_saveStateTemporary == true) which is invisible to the user (I'm not
sure whether this is by design or not).
Currently the savegame handling in scummLoop_handleSaveLoad() doesn't
distinguish between such temporary savegames and normal autosaves and
unconditionally resets _lastSaveTime (even after loading).
This has the unwanted side effect of potentially delaying the creation
of normal autosaves which are supposed to be created in accordance with
the autosave period setting in the GUI.
This commit makes sure that _lastSaveTime only gets updated if and only
if saving a (non-temporary) autosave.

SCUMM: Improve autosave handling for v5+ games

---

engines/fullpipe/modal.cpp

The previous URI spawns many useless subshells on the POSIX backend
through (harmless) shell command injection.

FULLPIPE: fix URI

---

common/hashmap.h

Calling clear(1) makes the size of hashMap wrong
Examples:
```
Common::StringMap map;
Common::StringMap mapTest;
map.setVal("CabinOnGround1", "FALSE");
map.setVal("CabinOnGround3", "FALSE");
map.setVal("CabinOnGround2", "FALSE");
map.setVal("CabinOnGround5", "FALSE");
map.setVal("CabinOnGround4", "FALSE");
map.setVal("CabinOnGround6", "FALSE");
map.setVal("VSInSS", "FALSE");
map.setVal("SetSummer", "TRUE");
map.setVal("BNWelcomed", "TRUE");
map.setVal("SSEmptied", "TRUE");
map.setVal("IsWinter", "FALSE");
mapTest = map;
map.clear(1);
// 1 test
for (auto it = mapTest.begin(); it != mapTest.end(); ++it) {
map.setVal(it->_key, it->_value); // endless execution
}
// 2 test
map = mapTest; // SIGSEGV 
```

COMMON: fix wrong size assignment in HashMap

---

README
engines/mohawk/myst_state.cpp
engines/mohawk/riven_saveload.cpp

1. Made the autosave section of the README to be a list of engines and games, added myst, riven, and tucker to it.
2. Prevented myst from autosaving over an original game save since it doesn't have a metadata and the autosave enable check looks at metadata file to determine if autosave should be enabled.
3. Allow non-autosave in slot 0 to be delete-able via the gui in myst and riven. Fixes Trac#10536

MOHAWK: README: Minor autosave changes and notes for autosaving

---

engines/mohawk/sound.cpp

This is used by the Living Books v3 sampler.

MOHAWK: Fix decoding sounds with 16 bit samples

---

common/math.h

This should of been included in PR1175.
I've changed naming and spaces to matched what is stated or implied in the style guide.
Let me know if I missed any other coding conventions.

COMMON: Style guide update for rad2Deg and deg2Rad 

---

devtools/credits.pl

I happened to notice that the MacOS version of ScummVM had a few character encoding issues in the credits, where some HTML entities were not being properly translated.  I went through the credits.pl script and checked each of the entities from html_entities_to_ascii to ensure that they were also correctly defined in html_entities_to_rtf.
While I was in making changes, I also noticed that there is still a function containing translations for the TeX version - which seems to have been deprecated.  I took the liberty of removing that function, to reduce future confusion.

Fix RTF credits encoding inconsistencies

---

engines/scumm/object.cpp
engines/scumm/players/player_ad.cpp
engines/scumm/players/player_towns.cpp

In some cases the pointer returned is used directly without further
error checking.
As most instances already assert() in this case this commit simply
adds asserts where missing and deemed appropriate.

SCUMM: Ensure pointer returned by getResourceAddress() is usable

---

engines/saga/detection.cpp
engines/saga/saveload.cpp

Fixes Trac#10008. 
Previously, the game would show a paused game message in the thumbnail when the
game was saved using the gmm.

SAGA: Don't show paws message in saved thumbnail

---

engines/scumm/debugger.cpp
engines/scumm/resource.cpp
engines/scumm/sound.cpp

This commit introduces the following (seemingly non-invasive) changes
to make the 'imuse play' debugger command more useful (i.e. don't crash
when trying to load the wrong kind of (sound) resource.
* ScummEngine::readSoundResource()
Instead of fatally error()'ing upon hitting a non-sound resource type,
e.g. a room header (0x524d4844 aka RMHD), we now only issue a warning().
This enables the already existing dead code which properly returns 0
(aka no resource loaded).
* ResourceManager::validateResource()
Instead of fatally error()'ing upon hitting an illegal glob type we now
only issue a warning() and return false (also existing dead code).
All methods calling validateResource() check its return value so this
seems like the right thing to do anyway.
* ScummDebugger::Cmd_IMuse()
Instead of …

SCUMM: Improve 'imuse play' debugger command error handling

---

NEWS
engines/scumm/sound.cpp

The speech sample at offset 0x76ccbca ("Hey you!") which is used when
Indy gets caught on the German submarine seems to not be a VOC but plain
PCM s16be at 44.1 kHz with a bogus VOC header.
To work around this we play this sample using the raw PCM decoder.
Fixes [Trac#10559](https://bugs.scummvm.org/ticket/10559).

SCUMM: Work around distorted speech on submarine in Indy4

---

backends/platform/sdl/riscos/riscos.mk
configure
dists/riscos/!Help,feb
dists/riscos/FindHelp,fd1

Previously, selecting the "Help" option in the RISC OS Filer menu would simply open the docs directory inside the application. This PR changes it so that it will additionally open the README or QuickStart file, using a translated version if a supported Territory module is installed.
The script is stored in plain text so that changes can be tracked by Git. As such, it needs to be converted using [Tokenize](http://www.stevefryatt.org.uk/software/build/) before it can be used on RISC OS. This is handled automatically by the packaging rules if Tokenize is installed.

RISCOS: Add a script to open the README file based on the system territory

---

engines/mohawk/myst_stacks/myst.cpp

Fixes Trac#10572.
The day slider does not go all the way to the bottom (day 31st)
when the down arrow is used to increment the day. This change
increases how much y displacement happens with each change
in the day so that the bottom is reach on day 31st.
This is just a graphical bug and doesn't affect the logic
of the puzzle. The day slider can also be dragged to the bottom
without using the buttons.

MOHAWK: MYST: Increment y_pos of observatory day slider faster

---

Makefile.common
backends/platform/sdl/riscos/riscos.mk
doc/da/HurtigStart
doc/se/Snabbstart

The RISCOS-LATIN1 encoding is provided by libiconv when built with the --enable-extra-encodings option. When using other iconv implementations (such as the one provided by glibc), the similar ISO-8859-1 encoding will be used as a fallback.
Some encoding issues in the various QuickStart files have also been fixed.

 RISCOS: Convert documentation to RISCOS-LATIN1 when packaging

---

engines/sci/graphics/celobj32.cpp

This is the solution discussed in bug #10568 ("SCI: PHANT1: Crash on startup"). A temporary-maybe-permanent fix was committed recently (fab1894f21, "ISCI32: Only enable larry scaler for LSL7") but I believe that this is the correct solution, and that ScummVM will do the right thing... but I'm not 100% sure.
The idea is that since games can declare that they will use an engine-specific setting (in this case the Larry scaler), it's better to test for that than to just assume that only LSL7 will ever use it.

SCI: Use LarryScale in games that support it, not just LSL7

---

engines/titanic/core/project_item.cpp

A function had a bool return that was not being used
now it is checked and an error is issued if the call fails.

TITANIC: Address readSavegameHeader compiler warning

---

NEWS
engines/sky/intro.cpp
engines/sky/screen.cpp
engines/sky/screen.h
engines/sky/sky.cpp

This commit adds a workaround to unlock existing fullscreen images in
the intro of Beneath a Steel Sky.
The original engine clips the whole intro to 320x192 (the common game
format) even though some images exist as 320x200 in the game data files.
This workaround whitelists all images which actually are 320x200px and
displays them as must have originally been intended.
Fixes Trac#7559.

SKY: Show full 320x200px in intro where possible

---

engines/avalanche/avalot.cpp
engines/avalanche/graphics.cpp
engines/fullpipe/scenes/scene18and19.cpp
engines/mohawk/myst_stacks/myst.cpp
engines/titanic/star_control/fpose.cpp
engines/titanic/star_control/fvector.cpp
engines/titanic/star_control/fvector.h
engines/titanic/star_control/star_closeup.cpp
engines/titanic/star_control/star_closeup.h
engines/titanic/star_control/star_points1.cpp
engines/titanic/star_control/star_points2.cpp
engines/titanic/star_control/viewport.cpp
engines/wintermute/base/scriptables/script_ext_math.cpp
engines/zvision/graphics/render_table.cpp
graphics/transform_tools.cpp
graphics/transparent_surface.cpp

In several engines various M_PI/180.0, its reciprocal, and engine specific functions (radianToDegree...) have been replaced with these degree conversions functions from common math.
In sci I changed a few doubles to floats since the extra precision/expensiveness seemed unnecessary.

ALL: Use deg2rad and rad2deg for degree conversions

---

configure

Clang 6 enables `-Wpragma-pack` which warns when leaving an included file which changes the current alignment.
Our `common/pack-{start,end}.h` trigger this and it cannot easily and portably be disabled inside `pack-{start,end}.h` so we disable it globally for now.

CONFIGURE: Disable -Wpragma-pack for >=clang-6.0

---

backends/graphics/windowed.h

When the graphics scale was 2x or higher, it was possible for the mouse to go too far right or down. If the game's resolution was 320x200, it could range from 0-320 or 0-200, giving it a 321x201 range; it should really range from 0-319 or 0-199, which is what this does.
It looks like only the SDL backend uses this function.

SDL: Clip mouse range in convertWindowToVirtual

---

engines/tinsel/detection.cpp
gui/saveload-dialog.cpp

Previously, if playtime or date/time support was added it would not be displayed
unless thumbnail support was also valid.
Now they will be shown even if the thumbnail is not valid.
No container is shown if only metainfo support is enabled.
Removed thumbnail support from tinsel.
The behavior is the same as before if thumbnail support is enabled.
Currently, Tinsel supports date time, but not playtime nor thumbnail, but it must enable thumbnail to show the date time and it looks like this:
After this PR it will look like this:
And if playtime support is added:
For this PR I have kept the container top to be level with the save list.

GUI: Show saveload date/time, or playtime even if thumbnail not enabled

---

engines/xeen/detection_tables.h

Another German version of "Darkside of Xeen" is added.
This one can be found on the CD of the Bestseller Games Magazine #8.
The same Magazine had "Clouds of Xeen" in issue #6 which seems identical
in filesize and checksum to the version from GOG.com, so a comment is added.
Finally, both set of files form another version of  "World of Xeen",
which had already a detection entry (German), so a comment is added to it.

Xeen: add a version of Darkside and some comments

---

engines/lure/lure.h

This required switching the ternary true and false operands.

LURE: Don't report failed to save/load when it is sucessful

---

engines/pink/saveload.cpp
engines/savestate.cpp
engines/savestate.h

1. Add playtime in msecs to SaveStateDescriptor (SaveStateDescriptor is in the Graphics namespace)
2. Use first commit to have pink load playtime from saved game into engine.

PINK: Set engine playtime to playtime in saved game

---

engines/lab/lab.h
engines/lab/savegame.cpp

Fixes Trac#10619.
The thumbnail loading for the saved games was defaulting to
disabled so no thumbnail was being loaded and this caused trying
to show the thumbnail to crash scummvm.
So I have set the thumbnail pointer to be null if the thumbnail
doesn't get loaded and I've set the thumnail to not be skipped
so that thumbnails get shown when using the gui.

LAB: Fix thumbnail issues

---

backends/platform/ios7/ios7_keyboard.mm
backends/platform/ios7/ios7_video.mm

These have not been compiled or otherwise tested, but are cleaned up
version of code changes from forum user "dottostring" in thread:
http://forums.scummvm.org/viewtopic.php?t=14524
This should add Fake ESC key support replacing the '`' key and add full
support for the Arrow keys.

IOS: Add Keyboard and UI Fixes for Smartkeyboard on IPad Pro.

---

common/cosinetables.cpp
common/cosinetables.h
common/sinetables.cpp
common/sinetables.h

The cos/sin table class now has its array index operator
overridden so that it can be indexed rather than have
the internal table indexed directly.
This allows the checking and computing of the correct
indexes to be done internally.
The indexing in allows cos/sine of 0 to 2pi to be
obtained. Internally, cos/sine values of only 0 to pi/2
are computed.
An alternate way can have all 0 to 2pi cos/sine values
stored in memory, which will duplcate values, but require
less if checks for the correct index in operator[].
getByValue also allows the cosine/sine value
that is closests to the radian value returned.
Which is an approximation to cos and sine.
I am not sure why the current cosine Table only generates
cos values at angles where the cosine is positive.
If we feel good about the current …

COMMON: Expand cosine and sine table features

---

engines/mohawk/riven_stacks/domespit.cpp
engines/mohawk/riven_stacks/domespit.h

Fixes Trac#10642.
The original engine will move the dome sliders whenever the player is
dragging a dome slider to the left or right regardless of y position.
In ScummVM the dome slider position would only change to the players x
mouse position when the y value was also in the slider hotspot. This
change removes the y check by making the point to be checked always
have a y value in the hotspot rect.

MOHAWK: RIVEN: Only use x mouse position to move dome sliders

---

engines/wintermute/wintermute.cpp

Now, the GUI will display a message box if the required screen format is unavailable, whereas previously, ScummVM would simply quit without warning if that happens.

WINTERMUTE: Return Common::kUnsupportedColorMode if the required screen format is unavailable

---

backends/platform/android/android.cpp

The touchpad_mouse_mode option was previously added for the Android-SDL port. This updates the Android port to match.
A side effect is that you no longer have to restart ScummVM after changing touchpad mode for it to take effect.

ANDROID: Use the dedicated GUI option for enabling the touchpad mode

---

engines/zvision/scripting/scr_file_handling.cpp

This is one possible way of working around ZGI bug #10605. It was possible for the "Fire! Fire!" timer to get stuck if you brought up the inventory screen before it had timed out. (Unless you brought it up _very_ quickly so that there was still more than 10 units left on the clock.)
I have a sneaking suspicion that there may be other timer-related script bugs, but I haven't looked for them. See the bug report for some further thoughts.

ZVISION: Add workaround for ZGI bug #10605

---

graphics/font.cpp

Fix kerning issue in wordWrapText.
In certain situation, we have to recompute kerning for the current character because we deleted the previous one.

COMMON: Fix kerning issue in wordWrapText.

---

engines/bladerunner/actor.cpp
engines/bladerunner/actor_walk.cpp
engines/bladerunner/bladerunner.cpp
engines/bladerunner/bladerunner.h
engines/bladerunner/vector.h

This uses the one in Common.
The engine now contains a 10-bit cosine and sine table.
It used mostly for vector math.
This also allows two vector functions to be removed from vector.h.

BLADERUNNER: Add cos/sine table

---

engines/lab/detection.cpp
engines/lab/lab.h
graphics/thumbnail.cpp

Since Graphics::loadThumbnail can return successfully when a thumbnail is skipped
the caller may want to check to the see that the thumbnail is not null before using
it. Setting it to null is just defensive in case the caller didn't do so.

GRAPHICS: Set thumbnail to nullptr when loading the thumbnail is skipped

---

engines/tinsel/detection.cpp
engines/tinsel/saveload.cpp

Also bumps the saved game format version to 3.
I changed the order of how the data is saved so that
the playtime could be read in without skipping as much data.
This is because querySaveMetaInfos only needs the metafields
where as saveload::DoRestore() needs more of the header.
A crash was happening when trying to delete a saved game from the
launcher. It is because the engine is not initalized. I assign a
dummy value to resolve the issue.
Loading saved games from previous versions works.
When an old version saved game is loaded it will start with
zero playtime.
Old saved games are shown as not having playtime data.

TINSEL: Add playTime to saved game and display it

---

engines/groovie/groovie.cpp
engines/groovie/groovie.h
engines/groovie/saveload.cpp
engines/groovie/saveload.h
engines/groovie/script.cpp
engines/groovie/script.h

If the user enters in an invalid description for the save then it will be
simplified by the saved name cache process in Script::savegame.
I checked this with t7g, but not with the 11th guest or any other Groovie game.
The original in-game loading/saving can still only access the first 10 save
slots (0-9).
Its possible to saving via the GMM when the game is interactive.
Loading a game saved via the gui using the original in-game load menu
works fine.
Saving via the GMM with timestamp works, but only only saves the characters
up to the first non-alpha non-letter characer.

GROOVIE: Allow saving via GMM and increase save slots to 25

---

engines/saga/saga.h

The underlying type of an enum cannot be a float so the following doesn't really make sense:
enum ScriptTimings {
kScriptTimeTicksPerSecond = (728L/10L),
kScriptTimeTicksPerSecondIHNM = 72,
kRepeatSpeedTicks = (728L/10L)/3,
[...]
};
Because of that, `kScriptTimeTicksPerSecond ` gets truncated to `72` and is therefore identical to `kScriptTimeTicksPerSecondIHNM`.
This commit removes `kScriptTimeTicksPerSecondIHNM`, but if the engine actually requires a higher precision then this is not correct and the constant(s) need(s) to be made floating point.
If it's OK to truncate I suggest adding a comment to the enum.

SAGA: Deduplicate kScriptTimeTicksPerSecond constant

---

Makefile
configure

This pull request includes the changes from #1185 to use pkg-config if it is available when buillding with FreeType support. This is necessary because FreeType stopped shipping the freetype-config script starting from version 2.9.1.
In addition to the changes in #1185, this adds some quality of life improvements:
* Check that pkg-config is available before using it
* Warn when cross-compiling and the `PKG_CONFIG_LIBDIR` environment variable is not set, because pkg-config would use the host package description files instead of the ones for the target system
* Save and restore the `PKG_CONFIG_LIBDIR` environment variable value across automatic re-runs of `configure`
* Include the changes from #1128 to allow to overriding more tools using environment variables. This allows using most of …

BUILD: Prefer pkg-config to freetype-config v2

---

engines/tinsel/detection.cpp

This corrects the displayed month for querySaveMetaInfos being a month
behind.

TINSEL: Fix displayed saved game month off by one

---

engines/mohawk/riven.cpp
engines/mohawk/riven.h

1. Move input handling from doFrame to another function
2. Delay less if doFrame loop takes longer.

MOHAWK: RIVEN: Delay less for slower systems

---

backends/events/default/default-events.h

Based on c47089d from PR #1128

BACKENDS: Mark resetQuit and getKeymapper as override

---

backends/platform/dc/dreamcast.mk
configure

> $(ronindir) and the explicit crt0 may have happened to work because
library detection state for libmad was forced, but it was always
breaking the feature detection of the build system. Now we can
compile to Dreamcast using the normal detection system.

BUILD: Fix broken Dreamcast ronin handling & feature detection

---

Makefile.common
configure
rules.mk

> This should improve linker time as well as reduce the size of the
built binaries (though this does not affect runtime memory usage
since the debug segments are not loaded into memory except by a
debugger) whilst still giving debug information.

 BUILD: Use split-dwarf debug symbol files by default, when available

---

configure

BUILD: Use normal host alias auto-prefixing for riscos and amigaos

---

Makefile
backends/platform/psp/psp.mk

> Instead of hard-coding these lists into the CI system's packaging
code, expose them from Make so that everything is sourced off the
same one list.

 BUILD: Add commands for retrieving calculated binaries & dist files

---

configure

The new buildbot worker adds the include directories [here](https://github.com/csnover/scummvm-buildbot/blob/master/workers/dreamcast/Dockerfile#L259) instead of in the configure script.

DREAMCAST: Fix compilation

---

.gitignore
Makefile.common
rules.mk

I noticed that the ScummVM build process creates .dwo files in addition to the .o files when -gsplit-dwarf is used. This pull request is my attempt to remove them on "make clean". I'm rather rusty on Makefile syntax, but I _hope_ it's correct.

BUILD: Remove .dwo files on clean

---

engines/wintermute/base/base_keyboard_state.cpp

1. _currentPrintable was set depending on _currentCharCode, which is 112
for both F1 and 'p' keys, fixed after detailed research on which keys
should be considered printable
2. some keypresses was producing warnings because was not listed in
mappings, added
3. vKeyToKeyCode was not safe if vkey > KEYSTATES_ARRAY_SIZE was
provided, fixed

WINTERMUTE: Printable flag fix, more keyboard mapping, array index check at vKeyToKeyCode()

---

rules.mk

Only happens when `--enable-plugins` is turned on.
It has to do with `$(PLUGIN-$(MODULE))` not substituting while inside of a make recipe, resulting in `dwp -e` executing with no argument, hence the FTBFS.
Version information:
- GNU make 4.2.1
- GNU dwp version 2.31.1-slack15
- scummvm e97b1e560d4f3a0eed758047e8c40ecc69c98231

Fix build failure

---

common/dct.cpp
common/rdft.cpp

When the constructor for the cos/sin table was changed from
number of bits to number of points all usages thoughout the
code should of been changed, but this was missed in RDFT and DCT.
Fixes Trac#10683.

COMMON: Update RDFT and DCT cos/sin table constructor usage

---

common/cosinetables.cpp
common/cosinetables.h
common/sinetables.cpp
common/sinetables.h

A new internal table has been added so that no if checks need to
be performed for the at() lookup.
The old table can still be accessed using getTable or atLegacy().
at() and atLegacy() return the same values, but at() is faster.
I am seeing that on average the at() is about 30% faster than the atLegacy() call.

COMMON: Cos/Sin Table switch internal structure so at() is faster

---

engines/bladerunner/script/ai/leon.cpp
engines/bladerunner/script/ai/maggie.cpp
engines/bladerunner/script/script.cpp
engines/bladerunner/slice_renderer.cpp
engines/bladerunner/vector.h
engines/bladerunner/view.cpp
engines/sword25/math/region.cpp
engines/sword25/math/vertex.h

> C++ math functions are overloaded so operate using single-precision
when receiving a float input. The C standard library on FreeMiNT
does not fully support C99 math so use of sqrtf, sinf, etc.
instead of the C++ API does not work.

ENGINES: Remove use of C99 math

---

backends/graphics/opengl/framebuffer.cpp
backends/graphics/opengl/framebuffer.h
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/texture.cpp

This fixes colour fringing on keyed cursors when using filtering.
Before:
After:
I have tested this with:
* Classic Myst (color-keyed 8-bits cursors)
* Myst ME (color-keyed 32-bits cursors)
* Riven (color-keyed 16-bits cursors)
* Starship Titanic (alpha-blended 32-bits cursors)

OPENGL: Use premultiplied alpha for color-keyed cursors

---

backends/platform/sdl/macosx/appmenu_osx.h
backends/platform/sdl/macosx/appmenu_osx.mm
backends/platform/sdl/macosx/macosx-compat.h
backends/platform/sdl/macosx/macosx.cpp
backends/platform/sdl/macosx/macosx.h
devtools/create_project/xcode.cpp
ports.mk

> The local documents are not currently internationalised simply
because the internationalised resources are not put into the right
places (NSBundle will handle this automatically when they are);
Trac#10464 is a tracking bug for this outstanding issue.
Originally from PR #1296.

MACOSX: Put documentation links in Help menu

---

engines/mohawk/riven_graphics.cpp
engines/mohawk/riven_graphics.h
engines/mohawk/riven_stack.cpp

Fixes Trac#10675.
Previously, the credits ended as soon as the last row was shown
of the final credits image.
Now some more black rows (empty rows) are shown and finally a few
seconds of black. I set it to 8 seconds of wait beyond where
the credits where previously stopping.
In order to do this updateCredits was enhanced to work past the end
of the last credits image (and just keep adding empty rows).
The original game shows a black screen for a longer period than this.
The first and last credit image indices were also assigned to #defines.

MOHAWK: RIVEN: Let credits roll longer

---

engines/lastexpress/entities/alexei.cpp
engines/lastexpress/entities/august.cpp

```
engines/lastexpress/entities/alexei.cpp: In member function ‘void LastExpress::Alexei::standingAtWindow(const LastExpress::SavePoint&)’:
engines/lastexpress/entities/alexei.cpp:772:49: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C++      engines/lastexpress/entities/chapters.o
engines/lastexpress/entities/august.cpp: In member function ‘void LastExpress::August::function21(const LastExpress::SavePoint&)’:
engines/lastexpress/entities/august.cpp:672:4: warning: this statement may fall through [-Wimplicit-fallthrough=]
switch(params->param5) {
^~~~~~
engines/lastexpress/entities/august.cpp:694:3: note: here
case 9:
^~~~
```

LASTEXPRESS: fixed warnings with gcc 8.2

---

engines/sword2/screen.cpp

```
engines/sword2/screen.cpp: In member function ‘void Sword2::Screen::rollCredits()’:
engines/sword2/screen.cpp:1121:102: warning: cast from type ‘const char*’ to type ‘byte*’ {aka ‘unsigned char*’} casts away qualifiers [-Wcast-qual]
creditsLines[i]->sprite = _vm->_fontRenderer->makeTextSprite((byte *)creditsLines[i]->str.c_str(), 600, 14, _vm->_speechFontId, 0);
```

SWORD2: fixed compiler warning with gcc 8.2

---

engines/lastexpress/detection.cpp

This adds a detection entry for the GOG release of LastExpress.
Questions:
- What about `AD_LISTEND` - should it be used?
- The `CD*` files are in a subdir named `data/` - how to deal with that. Using `data/CD1.HPF` didn't work. I had to copy the files into the same dir as `HD.HPF` to be able to detect the game.

LASTEXPRESS: added detection entry for gog release

---

engines/sci/engine/script_patches.cpp

SCI: Script patch for LB2 crate room bug #10701

---

engines/wintermute/base/base_game.cpp
engines/wintermute/base/saveload.cpp
engines/wintermute/base/sound/base_sound_manager.cpp

There are 4 use-cases of storing persistent data by WME in ConfMan: registry read/write, remembering MostRecentSaveSlot, storing volume settings, and some "last_run" flag that seems to be never used both by engine and games I know of. However, only writing to ConfMan is implemented for all those cases, without flushing. In master branch of ScummVM the only place where ConfMan.flushToDisk() is called is BaseGame::autoSaveOnExit() that is actually never called (commented at platform_osystem.cpp). This means that all those settings are actually not saved to disk.
https://github.com/scummvm/scummvm/blob/3e34cec7ced19e3a0f91588653b8cf4868db18d6/engines/wintermute/platform_osystem.cpp#L122
Registry read/write is an API that is rarely used in most WME games I decompiled (not used at all by games …

WINTERMUTE: Flush ConfMan to disk on every change

---

engines/scumm/script_v5.cpp

The different behavior in FM-TOWNS is caused by a few extra lines of code the is specifically added to move the map piece directly to the tree house. This patch bypassed the extra code causing the FM-TOWNS version behave like the other versions. All other required resources are still there.

SCUMM: MONKEY2: Skip extra code on FMTOWNS, fixes bug #2233

---

backends/platform/android/android.cpp
backends/platform/android/android.h
backends/platform/android/jni.cpp
backends/platform/android/jni.h
backends/platform/android/org/scummvm/scummvm/ScummVM.java
backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java

This uses the older [android.text.ClipboardManager](https://developer.android.com/reference/android/text/ClipboardManager) API rather than the newer [android.content.ClipboardManager](https://developer.android.com/reference/android/content/ClipboardManager) in order to maintain compatibility with older Android versions.

ANDROID: Implement clipboard support

---

engines/sci/engine/message.cpp

Fixes wrong message in floppy versions, bug #10723

SCI: Fix LB2 Yvette/Tut premature murder message

---

backends/platform/ios7/ios7_video.mm

On iOS12 at least, the rotation did not force the keyboard to hide. This
fix will force it to be retracted in landscape and restored when
rotating back to the portrait position.

IOS: Hide keyboard when rotating to landscape

---

engines/sci/engine/workarounds.cpp

GK1 does an uninitialized param1 read whenever the iconbar is displayed with an inventory item in all versions.

SCI: GK1 workaround for iconbar uninit param read

---

engines/sci/engine/script_patches.cpp

Fixes missing points in english pc floppy version, bug #10763

SCI32: Fix GK1 missing points for Mosely/veve

---

backends/graphics/dinguxsdl/dinguxsdl-graphics.cpp
backends/graphics/gph/gph-graphics.cpp
backends/graphics/linuxmotosdl/linuxmotosdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h
graphics/scaler/aspect.cpp
graphics/scaler/aspect.h

This change is related to the discussion in http://forums.scummvm.org/viewtopic.php?t=14733
The idea is to do a nearest neighbour aspect ratio correction when filtering is turned off instead of the usual bilinear filtering aspect ratio correction.
I am not sure what others think of this change, so I am putting it here for comments.
I have tested the change with both SDL 1.2 and SDL 2.0.7 on macOS.
SDL 1.2 was not previously supporting the filtering feature, so this is added by this commit to allow to control which aspect ratio correction we want.

SURFACESDL: Respect filtering setting when performing aspect ratio correction

---

engines/kyra/sound_lol.cpp

This occurs because of an out of buffer access when trying to play the monster sound effect.
This is from bug Trac #10665.
While this code change is restricted to Kyra's LOL code and thus only that game, and the fix does work to prevent the out of range access, it is not clear that this is the correct solution and will not stop other sound effects from playing. Also, it removes the sound effect from this monster, rather than correcting it to the correct effect... This could do with amendment by someone familar with the KYRA / LOL engine to see if there is a better solution, but if not, then merging this at least prevents LOL from crashing.

KYRA: Fix Urbish Mines Lobster Monster Crash in LOL.

---

engines/sci/engine/script_patches.cpp

Fixes ego speed bugs in the original game, bug #10780
I made two versions of the police station patch because there are two significantly different versions of that room's script. Please take a look and see if they can be rewritten as one that applies to both. The big obstacle is that in the second version the compiler switched from a 2 byte jmp instruction to a 3 byte one right in the middle of the section being patched.

SCI32: Fix GK1 ego speed bugs

---

engines/sci/engine/script_patches.cpp

Removes a problematic active debug hotkey, bug #10781

SCI32: Remove GK1 French/Spanish CD SysLogger hotkey

---

engines/groovie/groovie.cpp
engines/groovie/script.cpp
engines/groovie/script.h

As per discussion in #1306. This patch blocks GMM saves within a puzzle (we can't guarantee valid save state) and handles properly loading by properly jumping back into the base game script.

GROOVIE: Fix GMM loads, block saves in a puzzle

---

audio/softsynth/opl/mame.cpp
backends/events/symbiansdl/symbiansdl-events.cpp
base/commandLine.cpp
common/scummsys.h
gui/options.cpp

The GP32 backend was removed 10 years ago in commit defc030.

BACKENDS: Remove references to the GP32 backend

---

engines/groovie/saveload.cpp
engines/groovie/script.cpp

This is a patch originally submitted as part of Trac bug 6276 with minor fixup:
https://bugs.scummvm.org/ticket/6276

GROOVIE: Fix Spaces in Savegame Names

---

engines/sci/engine/script_patches.cpp

Prevents the autosave script from enforcing a 20 savegame limit, bug [#10758](https://bugs.scummvm.org/ticket/10758)
To trigger it reliably for testing, I enable autosave inside the adventurers' guild and walk outside.
// When autosave is enabled, Glory::save() (script 0) deletes savegame files in
// a loop: while disk space is insufficient for a new save, or while there are
// 20+ saves.
[...]
// No good can come of this loop. So we skip it entirely. If the disk truly is
// out of space, a message box will complain, and the player can delete saves
// voluntarily.
I haven't caused that circumstance to confirm. SCI Companion says it would create a Print object (apparently an in-game dialog), with the message "Save Error".
// Note: Glory::save() contains another space freeing loop, but it …

SCI32: Fix QFG4 autosave deleting manual saves

---

engines/sci/engine/script_patches.cpp

This leak was introduced in commit [#a37e388](https://github.com/scummvm/scummvm/commit/a37e38830496f4a414bd671428aedbe8831652ff), as discovered after request #1383 had merged.
Moreover, the autosave patch is confirmed to work with the German floppy edition.

SCI32: Fix QFG4 autosave stack leak

---

backends/platform/sdl/win32/win32.mk
configure
ports.mk

Also removed the now-unused win32setup rule.

WIN32: Move the Windows-specific packaging rules into a separate file

---

engines/sci/engine/script_patches.cpp

Fixes a lockup in the original when walking to a corner, bug #10702
This adjusts some obstacle coordinates to prevent walking to one of the several problem coordinates. It would be good if @dafioram, who found the bug, could test before this gets merged. I've thrown click frenzies and diagonal num-pad keys at it and can't get it stuck anymore but if there's still accessible bad-coordinates I can adjust the polygon to exclude them.

SCI: Fix LB2 elevator lockup

---

engines/sci/engine/script_patches.cpp

Fixes typos that lead to a "y value less than vanishingY" message, bug [#10726](https://bugs.scummvm.org/ticket/10726)
// There are typos where hero is passed to Prop::setScale(), a method which
// expects integers. We change it to Prop::setScaler().

SCI32: Fix QFG4 setScale error when levitating

---

dists/scummvm.6

Add missing cmdline options and hotkeys to the manpage. Add long options
where they were missing. Update existing options description and values.
Improve formatting for important words, arguments, etc. Sort the options
in the same way they are sorted in README, so that future synchronization
is easier. Add info into several places saying that README is more
comprehensive than this manpage.
----
Hello, it took me a while to realize that your manpage contained much less information than the readme file. I decided to fix that and update it. This is my first time editing a manpage, I wasn't familiar with the syntax, but I verified in renders fine for me (Fedora 29).

manpage: update cmdline options and hotkeys

---

engines/sci/engine/workarounds.cpp

Allows KQ6's in-game debugger to load

SCI: Add workaround for KQ6 debugger

---

README
backends/platform/sdl/posix/posix.cpp
backends/platform/sdl/posix/posix.h

The screenshots are written to `$XDG_PICTURES_DIR/ScummVM Screenshots` as defined in the XDG user directories specification (https://www.freedesktop.org/wiki/Software/xdg-user-dirs/).
With this change the screenshots are saved to a user writable path by default on Linux when ScummVM is installed through a package manager.

POSIX: Set the default screenshots path to the XDG Pictures directory

---

engines/sci/engine/script_patches.cpp

Works around pathfinding algorithm difference that breaks the game

SCI: Fix LB2 armor hall door pathfinding bug #9952

---

engines/sci/graphics/animate.cpp
engines/sci/graphics/view.cpp

The new stuff added to view.cpp for SCI11+ never actually triggers because I'd neglected to have `GfxAnimate::drawCels()` pass the scaleSignal that the remap effect requires, thus defaulting to zero.
This has been tested and correctly lets the work-in-progress full version of The Dating Pool draw characters standing in shadow.

SCI: fix full view remap effect

---

engines/sci/engine/script_patches.cpp

Fixes a script bug which causes a kernel signature mismatch

SCI: Fix LONGBOW Amiga pub error, bug #9688

---

engines/sci/engine/script_patches.cpp

Fixes a second door sound when entering certain rooms, bug [#10827](https://bugs.scummvm.org/ticket/10827)
````
// Rooms 622 and 623 play an extra door sound when entering. They both
// delegate to script 645. It schedules sEnter, which indeed has an extra
// sound. The CD edition removed the line. We remove it, too.
//
// Applies to at least: English floppy, German floppy
````
To test, teleport to either room.

SCI32: Fix QFG4 extraneous door sound in castle

---

backends/platform/sdl/win32/win32.cpp

Fixes bug [#10613](https://bugs.scummvm.org/ticket/10613) by replacing API calls not available in Windows 98 with older equivalents.
You still need to compile with SDL 1.2 yourself, but otherwise it works: https://i.imgur.com/MEhve8U.png

WIN32: Fix missing export errors in Windows 98

---

engines/sci/engine/script_patches.cpp

Fixes hero getting stuck due to inactive nightfall detection, bug [#10830](https://bugs.scummvm.org/ticket/10830)
````
// Waking after a dream by the staff in town prevents the room from creating a
// doorMat at nightfall, if hero rests repeatedly. The town gate closes at
// night. Without the doorMat, hero isn't prompted to climb over the gate.
// Instead, hero casually walks south and gets stuck in the next room behind
// the closed gate.
//
// Since hero wakes in the morning, sAfterTheDream disposes any existing
// doorMat. It neglects to reset local[2], which toggles rm270::doit()'s
// constant checks for nightfall to replace the doorMat.
//
// We cache an object lookup and use the spare bytes to reset local[2].
//
// Note: There was never any sunrise detection. If hero rests …
```

SCI32: Fix QFG4 town gate after a staff dream

---

engines/sci/engine/script_patches.cpp

Simplifies a script patch into one version instead of two larger ones.
When I first wrote this I believed the fix (calling normalize) had to
take place in state 5 of the script, but state 4 is okay too. State 4
is simpler to patch and avoids the problem bytes that changed between
versions and required two patches.

SCI32: Simplify GK1 ego speed script patch

---

engines/sci/engine/script_patches.cpp

Fixes item properties that weren't getting reset, bug [#10768](https://bugs.scummvm.org/ticket/10768)
````
// Some inventory item properties leak across restarts. Most conspicuously, the
// torch icon appears pre-lit after a restart, if it had been lit before.
//
// script 16 - thePiepan (item #28): loop, cel, value
// script 35 - theBroom (item #39): cel, value
// script 35 - theTorch (item #44): cel
//
// Glory::restart() tries to revert a bunch of globals to their original state.
// Each value was individually loaded into acc and assigned (ldi+sag, ldi+sag,
// ldi+sag, etc).
//
// One range of globals could be distilled to multiples of 45. We optimize
// those with a loop. Another range was arbitrary. We stack up those values all
// at once, then loop over the stack to pop(), assign, …
```

SCI32: Fix QFG4 inventory leaks across restarts

---

devtools/create_project/create_project.cpp
devtools/create_project/create_project.h
devtools/create_project/msbuild.cpp
devtools/create_project/msvc.cpp
devtools/create_project/msvc.h
devtools/create_project/msvc10/create_project.vcxproj
devtools/create_project/msvc11/create_project.vcxproj
devtools/create_project/msvc12/create_project.vcxproj
devtools/create_project/msvc14/create_project.vcxproj
devtools/create_project/msvc15/create_project.vcxproj
devtools/create_project/msvc9/create_project.vcproj
devtools/create_project/scripts/installer.vbs
devtools/create_project/scripts/postbuild.cmd
devtools/create_project/scripts/scummvm.natvis
devtools/create_project/visualstudio.cpp
ports.mk

For the few of us actually building ScummVM with Visual Studio. 😉 
- Clean up `create_project` warnings. They were caused by the implicit casts when using `tolower`/`toupper` so I think they're fine silenced.
- Improve compile times by replacing the [/Gm flag](https://docs.microsoft.com/en-us/cpp/build/reference/gm-enable-minimal-rebuild) with the [/MP flag](https://docs.microsoft.com/en-us/cpp/build/reference/mp-build-with-multiple-processes) which is better suited for large projects (shaved a whole minute off a clean build).
- Fix natvis known issues and add new classes.
- Fix `missing translations.dat` error when not using build events.
- Update build event scripts (old DLLs, old installer, etc).
- Update `ideprojects` target.

MSVC: Update project generation

---

engines/sci/engine/script_patches.cpp

Fixes an exception casting Trigger after using grapnel, bug [#10837](https://bugs.scummvm.org/ticket/10837)
````
// At the squid monolith (room 800), using the grapnel on the eastern ledge
// disposes hero's scaler to freeze hero's size. A scaler dynamically shrinks
// hero into the horizon as y-pos increases. It makes sense that hero should
// maintain their size while climbing a vertical rope.
//
// Problem: After climbing the rope, both standing on the ledge and back on the
// ground, hero's scaler will remain null. An exception will occur if a script
// calls Prop::setScaler(hero) while hero's scaler is null. Casting Trigger on
// the monolith, from either location, does it. As will climbing down, then
// casting Levitate. Both spells have auras intended to fit hero's size. They
// …
```

SCI32: QFG4 Fix null scaler, climbing by monolith

---

engines/sci/engine/script_patches.cpp

Fixes incorrect cards and placement in the third and fifth readings.
[#10822](https://bugs.scummvm.org/ticket/10822)
```
// The fortune teller's third reading places the "Two of Cups" across another
// card, off-center. That View (1023) is cropped (130x64). All other horizontal
// cards (130x86, 130x87) are padded at the bottom with transparent pixels.
//
// A utility script (sShowCard) is scheduled to create each card with a given
// View (passed as local[0]) and move it onto a given pile (passed as local[2]:
// center, west, south, east, north). It has a switch block deciding x,y coords
// depending on the pile.
//
// We optimize a couple cases by consolidating their common code in a
// subroutine to make room. The rewritten case for the east pile checks if the
// requested card was …
```

SCI32: Fix QFG4 tarot readings

---

Makefile.common
backends/platform/maemo/debian/rules
backends/platform/symbian/S60v3/scummvm-CVS-SymbianS60v3.pkg
backends/platform/symbian/S60v3/scummvm-CVS-SymbianS60v3_split.pkg
backends/platform/symbian/UIQ3/scummvm-CVS-SymbianUIQ3.pkg
backends/platform/symbian/UIQ3/scummvm-CVS-SymbianUIQ3_split.pkg
devtools/create_project/xcode.cpp
dists/irix/scummvm.idb
dists/scummvm.rc
engines/wintermute/base/font/base_font_truetype.cpp
engines/zvision/text/truetype_font.cpp
engines/zvision/zvision.cpp
graphics/fonts/ttf.cpp
graphics/fonts/ttf.h
gui/ThemeEngine.cpp

This PR implements common support for loading fonts from the fonts.dat datafile introduced in PR #1393. Currently it's used by the Wintermute and ZVision engines, as well as by the GUI.
The PR does not include fonts.dat in order to avoid conflicting with PR #1393, however, it will need to contain `FreeMonoBold.ttf`, `FreeSans.ttf` and `FreeSansBold.ttf` from `gui/themes/fonts`.

 GRAPHICS: Add a function to load TrueType fonts from fonts.dat

---

engines/sci/console.cpp
engines/sci/engine/features.cpp
engines/sci/engine/features.h
engines/sci/engine/script_patches.cpp
engines/sci/graphics/plane32.cpp

This pull request provides a proper fix for bug #10773, #10778 and possibly other bugs that don't have tickets.
SCI32 creates a number of internal planes for various purposes. In most interpreters, these planes have ID numbers starting at 20000. These planes do not have a corresponding script object, and are denoted by (scummvm) in the output of the plane_list command. One such plane (and the only one relevant to GK1 and QfG4) is called initPlane in the scummvm source code. Most memory handles are smallish, so starting at 20000 makes conflicts with script-created planes much less likely (but not impossible). In the early interpreters of GK1 and QfG4 floppy, the numbering actually starts at zero. This means that operations on screen items with plane == 0 will operate on the initPlane …

SCI32: Plane id fixes 

---

engines/sci/engine/message.cpp
engines/sci/resource_audio.cpp

Fixes mixed up text/audio when giving her flowers, bug [#10849](https://bugs.scummvm.org/ticket/10849)
````
// The CD edition mangled the Rusalka flowers dialogue.
// In the floppy edition, there are 3 lines, the first from
// the narrator, then two from Rusalka. The CD edition omits
// narration and only has the 3rd text, with the 2nd audio! The
// 3rd audio is orphaned but available.
//
// We only restore Rusalka's lines, providing the correct text
// for seq:1 to match the audio. We respond to seq:2 requests
// with Rusalka's last text. The orphaned audio (seq:3) has its
// tuple adjusted to seq:2 in resource_audio.cpp.
````
To test...
* Restore or create a character.
* Acquire flowers.
* send hero get 40
* Teleport to the lake.
* room 520
* Click the flowers on Rusalka.

SCI32: Fix QFG4 Rusalka flowers dialogue

---

engines/sci/engine/message.cpp

Fixes an inaccurate message when examining the statue, bug [#10770](https://bugs.scummvm.org/ticket/10770)
````
// Examining the statue inventory item from the monastery - bug #10770
// The description says "squid-like monster", yet the icon is
// clearly an insect. It turned Chief into "an enormous beetle". We
// change the phrase to "monstrous insect".
//
// Note: The German string contains accented characters.
//  0x84 "a with diaeresis"
//  0x94 "o with diaeresis"
//
// Values were pulled from SCI Companion's raw message data. They
// are escaped that way here, as encoded bytes.
````
This PR intercepts a message lookup and returns a hardcoded string, matching the language of the detected edition.
English
* Before: "Carefully wrapped in a shopping bag is the grotesque sculpture of a …

SCI32: Fix QFG4 statue item description

---

engines/sci/engine/script_patches.cpp
engines/sci/engine/workarounds.cpp

Fixes wriggling and retraction when hero travels over the pit, bug [#10615](https://bugs.scummvm.org/ticket/10615)
Wriggle
````
// When crossing the cave's tightrope in room 710, a tentacle emerges, and then
// its animation freezes - in ScummVM, not the original interpreter. This
// happens because of an extraneous argument passed to setCycle().
//
// (tentacle setCycle: RandCycle tentacle)
//
// RandCycle can accept an optional arg, but it expects a number, not an
// object. ScummVM doesn't catch the faulty arithmetic and behaves abnormally.
// We remove the bad arg.
````
This supersedes an arithmetic workaround added in commit 259f262.
Fighter
````
// When crossing the cave's tightrope in room 710, a tentacle emerges. The
// tentacle is supposed to reach a state where it waits …
```

SCI32: Fix QFG4 cave tentacle

---

engines/sci/engine/script_patches.cpp

Fixes a script bug in the mac version that always kills the player

SCI: Fix QFG1VGA Mac Antwerp controls, bug #10856

---

engines/sci/engine/kpathing.cpp
engines/sci/engine/script_patches.cpp

Adds workarounds for odd detours during entry
[#10857](https://bugs.scummvm.org/ticket/10857) - Script patch
````
// When entering forest room 557 from the east (563), hero is supposed to move
// only a short distance into the room. ScummVM's pathfinding sends hero off
// course, to the middle of the room and back.
//
// There's an unwalkable stream in the SE corner, and hero's coords were within
// its polygon. We lower the top two points to keep hero on the outside.
````
Side note: Hand decompiled code for the forest::init() is attached there, in case in case anyone is curious about random encounters and pre-combat setup. It's shared across all the forest rooms.
&nbsp;
[#10858](https://bugs.scummvm.org/ticket/10858) - AStar() workaround
ScummVM's pathfinding has a penalty that …

SCI32: Fix QFG4 forest pathfinding

---

engines/sherlock/journal.cpp

Some messages spoken to Watson show up in the journal as if spoken to the inspector. (And, presumably, the other way around, but I haven't gotten that far in playing the game yet.)
Since I couldn't reproduce this in DOSBox, I assume it's a simple cut and paste error.
You should be able to easily reproduce the bug in the attached savegame. Simply exhaust all conversation options with Watson. At least one of them should show up as "the inspector" in the journal afterwards.
[rosetattoo.000.gz](https://github.com/scummvm/scummvm/files/2705906/rosetattoo.000.gz)

SHERLOCK: Fix misattribution in Rose Tattoo journal

---

engines/sci/console.cpp

Fixes the help for bp_action: 'none' arg should be 'ignore'
&nbsp;
[Source](https://github.com/scummvm/scummvm/blob/95b53f3737262929fd5bb87b3949e3acd82884a2/engines/sci/console.cpp#L4015): console.cpp - Console::cmdBreakpointAction()
````
Usage: %s <breakpoint index> break|log|bt|inspect|none
^^^^
````
[Source](https://github.com/scummvm/scummvm/blob/95b53f3737262929fd5bb87b3949e3acd82884a2/engines/sci/console.cpp#L3983): console.cpp - stringToBreakpointAction()
````
if (str == "break")
action = BREAK_BREAK;
else if (str == "log")
action = BREAK_LOG;
else if (str == "bt")
action = BREAK_BACKTRACE;
else if (str == "inspect")
action = BREAK_INSPECT;
else if (str == "ignore")
action = BREAK_NONE;
````

SCI: Fix debugger bp_action help message

---

engines/sci/engine/script_patches.cpp

Fixes hero being able to walk through the closed gate, bug [#10871](https://bugs.scummvm.org/ticket/10871)
````
// After hero is geas'd in the dungeon (room 670) and teleported to the gate
// (600), hero can walk through the closed gate and exit north to the castle
// entrance. Two IF blocks with inconsistent conditions decide whether the
// gate is open and whether to use a polygon that extends beyond the gate.
// When re-entering from the forest (552), the gate is only open and passable
// if hero is qualified.
//
// The room has distinct situations for merely teleporting from the dungeon
// (local[0] = 11) and for entering from the forest while geas'd and carrying
// all the ritual scrolls (local[0] = 10). The latter sets a vital plot flag.
// Adding those checks and the flag to the …
```

SCI32: Fix QFG4 castle gate after geas

---

engines/sci/detection_tables.h

This commit adds support for the French version 1.0c of Lighthouse.
Current master branch gives:
```
The game in '/home/jc/ScummVM/Games/Lighthouse' seems to be an unknown game
variant.
Please report the following data to the ScummVM team at
https://bugs.scummvm.org/ along with the name of the game you tried to add and
its version, language, etc.:
Matched game IDs for the SCI [all games] engine: lighthouse,
phantasmagoria-demo, rama-demo
{"ressci.001", 0, "dbb615146ec943e4ff7764a485c90511", 122184234},
{"ressci.002", 0, "6635764dc258b2041ca9a387e5aaab25", 114880156},
{"resmap.001", 0, "7f768cb4ee53026ea8fc662e44e7c0de", 7870},
{"resmap.002", 0, "3fa427abab4c1d7bbea3033c064fc182", 7636},
```

SCI: Add French version 1.0c of Lighthouse

---

engines/sci/engine/script_patches.cpp

* Corrected opcode comments.
* Corrected SIG macros in patches and vice versa.
* Added some ticket numbers to descriptions.
* Named & bracketed indices for [ global | local | temp | param ] vars.
* Indices themselves are left in each author's markup.
* Some description revision and word wrapping.
* Lowered uppercase hex bytes. Padded single-digit hex bytes.
* Space-padded decimal bytes so their lack of 0x prefix stands out among the regular hex bytes.
* Removed stray whitespace characters.
* Parenthesizd any hex values where selector macros are present, since they've become reminders.
* Four digit uint16 macros. An afterthought. Not exhaustively enforced.
* Removed a workaround I'd commented away and forgotten about.
These should be innocuous changes.

SCI: Cleanup for all script patches

---

engines/sci/console.cpp

Fixes bp_function and bp_address not printing the created breakpoint, as
happens with the other bp_ commands.
````
) bp_function 0 4
) bp_method hero::hide
#1: Execute hero::hide
) bp_kernel RestoreGame
#2: Kernel call kRestoreGame
) bp_read hero::plane
#3: Read hero::plane
) bp_write hero::plane
#4: Write hero::plane
) bp_address 0000:1234
) bp_list
Breakpoint list:
#0: Execute script 0, export 4
#1: Execute hero::hide
#2: Kernel call kRestoreGame
#3: Read hero::plane
#4: Write hero::plane
#5: Execute address 0000:1234
)
````

SCI: Fix inconsistent debugger breakpoint messages

---

engines/sci/engine/script_patches.cpp

Fixes a script bug in the CD version, bug #10881

SCI: Fix ECO1CD giving Superfluous the oily shell

---

gui/debugger.cpp

When built with enable-text-console and disable-readline, flushing output
immediately after printing the debugger prompt, before waiting for input,
ensures that external tools can spawn ScummVM, detect the prompt, and pipe
in automated responses (e.g., [expect scripts](https://en.wikipedia.org/wiki/Expect)).
Explicit flushing was necessary at least on Windows, where support for
automating terminal input is less sophisticated. Otherwise, the prompt
string doesn't make it through the pipe, and both the script and ScummVM
get stuck waiting for input.
&nbsp;
Readline wasn't flushing for me on Windows, and I couldn't find a way to
make it do so. I imagine the readline lib works better on Linux inside
pseudoterminals.

GUI: Flush debugger prompts on text console

---

engines/saga/sfuncs.cpp

This is my attempt at fixing bug #10365 - SAGA: ITE: Crash when talking to Sist
Thanks to dafioram, there is an easily reproducable test case. Unfortunately it involves navigating through the rat maze, but it could be worse.
This is what appears to happen:
When Rif puts on the rat disguise, he is swapped out for a different actor. When he takes off the disguise, after reaching Sist's office, the old actor is swapped back in again.
At that point, original Rif's actor will have a _lastZone pointer which not only is for the wrong room, it was deleted when Rif in disguise left the room.
My fix for this is to also have the actors swap their _lastZone pointers. This seems to work fine in this case, but I don't know if sfSwapActors() is used anywhere else in the game. At the very least, I think …

SAGA: Fix potential crash when talking to Sist (bug #10365)

---

engines/sci/engine/script_patches.cpp
engines/sci/engine/workarounds.cpp

It was superseded by commit aa9a1ab.
I'd meant to do this in the script cleanup PR, and it got left out.
In fact, it was the original reason I'd gone looking for little things to polish.
I thought to myself, "I can't justify a PR for one comment." XD
Also removes a stray space character I'd left in longbowSignatureShowHandCode's description during the cleanup.

SCI32: Cleanup QFG4 Remove a commented workaround

---

.gitattributes

Currently this specifies the encoding of the `.po` files that use an encoding other than ISO-8859-1.  This allows those files to be displayed in the correct encoding with GUIs that support it.

GIT: Add a .gitattributes file

---

engines/sci/video/robot_decoder.cpp

Right know RAMA (SCI32) is currently broken as it crashes right after the Sierra intro:
```
scummvm: ./common/array.h:197: const T& Common::Array<T>::operator[](Common::Array<T>::size_type) const [with T = Sci::ScreenItem*; Common::Array<T>::size_type = unsigned int]: Assertion `idx < _size' failed.
```
This issue has been introduced by the following commit 9ceb2e858658cac3c7e4d592c3fa6f59a5776b9a trying to fix [#10700](https://bugs.scummvm.org/ticket/10700), because it assumes that there is at least one item in the list.
This PR takes care of the zero item case and returns a (0,0,0,0) Rect instead of crashing (previous behavior).
[#10700](https://bugs.scummvm.org/ticket/10700) should still be fixed, but I cannot test it myself.
For info I'm using the following version of RAMA:
```
// …
```

SCI: Fix out of bounds issue in getFrameSize

---

engines/sci/engine/script_patches.cpp

Fixes a bad byte.
Original qfg3PatchCombatSpeedThrottling1
```
0x80, 0xd2,                         // lsg global[D2h]
^^^^
0x14,                               // or
0x31, 0x06,                         // bnt [skip code] - saves 4 bytes
```
The op byte does not match the instruction's expected length or opcode comment.
* 0x80 would be: lag uint16.
* 0x89 is: lsg byte.
&nbsp;
Confirmed with the debugger's disasm...
Original (0x80)
````
0027:102f: 83 01          lal   01
0027:1031: 1c             ne?
0027:1032: 80 d2 14       lag   14d2            ; 5330
0027:1035: 31 06          bnt   06  [103d]
````
Corrected (0x89)
````
0027:102f: 83 01          lal   01
0027:1031: 1c             ne?
0027:1032: 89 d2          lsg   d2              ; 210
0027:1034: 14             or
0027:1035: 31 06 …
```

SCI: Fix QFG3 combat speed throttling patch

---

audio/decoders/ac3.cpp
audio/decoders/ac3.h
engines/zvision/video/video.cpp
engines/zvision/zvision.h
video/mpegps_decoder.cpp
video/mpegps_decoder.h

The high-resolution videos play back at much lower volume than the original ones. This adds hard-coded values for how much to amplify each cutscene. It's all done by ear, and it does introduce some
clipping, but I think it should be acceptable. 
Of course, it could also be a problem with the audio decoder, so this may be the wrong approach entirely.

ZVISION: Boost volume for MPEG cutscenes

---

backends/graphics/dinguxsdl/dinguxsdl-graphics.cpp
backends/graphics/dinguxsdl/dinguxsdl-graphics.h

The dingux backend port will not compile anymore (bool setGraphicsMode(const char *name) no longer exists it seems) so removing it allows GCC to compile it.
There's also an issue with ScummVM's cursor being drawn in-game, this affects games like Gabriel.
Mainline SDL code fixed this but the Dingux port was not brought up to par so fixing that of course.
(On a side note, i did notice that some other backends similar to this one (GPH, MotoSDL etc...) can suffer from the same issues)

DINGUX: Fix dinguxsdl graphics backend

---

engines/sci/engine/script_patches.cpp

Fixes the walkable polygon not changing when it's revealed, bug [#9894](https://bugs.scummvm.org/ticket/9894)
````
// In the thieves' guild (room 430), the tunnel is not immediately walkable
// when it is revealed (by moving a barrel and solving a puzzle). Hero must
// re-enter the room to update the polygon.
//
// Curing Chief *will* immediately replace the polygon. However, most players
// will lack the item necessary on the first visit. Meeting Chief is how they
// learn about the item. If they go get it, they'll re-enter the room.
//
// The room's init has a cond block to check plot flags and declare one of 3
// polygons. The 3rd condition also inits secritExit, an invisible Feature
// that sends hero out of town when walked upon.
````
````
// Patch 1: Other patches ensure the passage …
```

SCI32: Fix QFG4 guild secret passage

---

engines/sky/control.cpp

Currently, there's a very noticeable mouse cursor lag in the save/load/settings dialog in Beneath a Steel Sky. I noticed that for whatever reason the redrawing delay is set to 50ms which causes this behavior. By reducing the redrawing delay to 20ms I achieved a very smooth cursor behavior which now matches the behavior of the original interpreter (tested with the latest DosBox release).
Even though this change seems to be quite trivial, I'm submitting this patch as a pull request since I am not familiar with the engine code at all. I couldn't spot any unwanted side effects.

SKY: Decrease cursor redraw delay in menu

---

configure

I'm unable to test this at the moment, however this should hopefully fix the buildbot.

WIN32: Fix building outside the source directory

---

engines/glk/frotz/processor.cpp
engines/glk/frotz/processor.h
engines/glk/frotz/processor_screen.cpp

The Beyond Zork graphics font doesn't support Unicode, so allowing it to convert things like straight quotes into curly ones can cause ScummVM to crash. Disable these conversions while the Beyond Zork graphics font is used to avoid that. This fixes bug #10865.

GLK: FROTZ: Disable typographic niceties for Beyond Zork font

---

configure

CPPFLAGS should only contain options that are used by the preprocessor, however pkg-config may return C/C++ specific options which are unrecognised by windres.

CONFIGURE: Append pkg-config cflags to CXXFLAGS

---

engines/sci/engine/script_patches.cpp

Work around a lockup that occurs due to our pathfinding, bug #10896

SCI: Fix LONGBOW Day 8 archer pathfinding

---

engines/sci/engine/script_patches.cpp

Fixes script bugs in the original that prevent messages.
Replaces a script patch that fixed one of the symptoms.

SCI: Fix LB2 armor exhibit messages, bug #10895

---

engines/sci/engine/script_patches.cpp

Fixes bug in original that doesn't redraw objects

SCI: Fix LB2 disappearing desk items, bug #10894

---

backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
common/endian.h
graphics/surface.cpp
image/bmp.cpp
image/bmp.h
image/png.cpp

This hasn't been tested on big endian machines, although I suspect additional changes will be needed.

 IMAGE: Move bitmap writing code out of OpenGLGraphicsManager

---

base/internal_plugins.h
base/plugins.h
dists/scummvm.rc

Fix Windows builds (msvc and mingw) including data files from disabled
engines as embedded resources in executable. Bug #10878

WIN32: Fix embedding disabled engine files

---

engines/sci/engine/script_patches.cpp

Fixes castle doors when all bats have been killed, bug [#10789](https://bugs.scummvm.org/ticket/10789)
One patch for the lower door.
````
// In the room (644) connected to the lower door of the bat-infested stairway,
// peering through the keyhole *always* reports bats.
//
// As you kill the bats, global plot flags are set. Normally flags 331-334
// would be checked via proc0_4(). They're in a bitmask, among other flags, so
// we can check all simultaneously (0000000000011110).
//
// global[520] & 30 == 30
//
// Room 644 has an IF-ELSE deciding between largely redundant calls to
// gloryMessager::say(). We make room by combining them.
````
Three for the upper door.
````
// In the crest bookshelf room (663) connected to the upper door of the
// bat-infested stairway, peering through the …
```

SCI32: Fix QFG4 peering at absent bats

---

dists/riscos/!Run,feb

The part of the Run command redirecting stdout/stderr to files has to be evaluated before ScummVM is executed. Previously this was accomplished using the Do command, however this has the side effect of expanding any variables passed to the command line. which is undesirable as ScummVM uses Unix-style paths internally, while expanding variables used in paths in the !Run file would result in them being expanded as RISC OS style paths.

RISCOS: Don't expand system variables passed via the command line

---

base/main.cpp
base/plugins.cpp
base/plugins.h

> The other plugins do not need to be reloaded. Reloading
the scaler plugins breaks the graphics.
Originally from PR #271

BASE: Only reload engine plugins after return to launcher

---

graphics/VectorRendererSpec.cpp

I am currently working on a "Classic Mode" theme that uses another background color than the default block.
For "unknown" reasons (at least they are unknown to me), the current code throws an assertion failure when the background color in the theme is not set to black. I almost assume that this is a leftover from previous times, but since I'm not absolutely sure if this will break something else, I'm submitting this as a PR.

GUI: Allow GUI background colors other than black in Classic Theme

---

engines/scumm/he/moonbase/moonbase.cpp

What:
The bug is reproducible in the following ways:
1. quiting the game
2. enter challenge mode state 2, when the game starts move mouse around
the menu buttons (choose building or weapons)
Observed behavior: In he/wiz_he.cpp:2839, the function failed to return since
the stack around variable 'color' was corrupted. The game will crash then.
Analysis:
Since other function will modify memory area around local variable 'color',
the bug shoud be caused by memory overwritten. The memory write happens
in this modified file. From the code, it only wants to write a certain amount
of pixels. So I found 2 places where more pixels are written. This causes
stack memory corruption.
Fix:
Add checking. If we have written enough pixels then break.
Testing:
The game UI looks correct. Single player mode …

SCUMM HE: Bug fix for moonbase stack memory corruption

---

engines/sci/engine/scriptdebug.cpp

Fixes debugger crash when disassembling an instruction whose operand
is an invalid property. This occurs in LB2 floppy 1.0 script 720 in
sGetUp:changeState and sStepOnNail:changeState.

SCI: Fix disassembler crash on invalid property

---

engines/sci/engine/kgraphics.cpp
engines/sci/engine/script_patches.cpp

Fixes bug #6193 by applying the SQ4 floppy kPaletteAnimation timing
workaround from 99de89c974fc24bf58b034842750e522d7d441d4 to versions
with less than 256 colors. This includes DOS EGA, PC-98, and Amiga.
This also patches out the intro script's workaround that uses different
timing in EGA mode, as this is incompatible with ours and makes the
intro screen last over 3 minutes instead of 5 seconds.

SCI: Apply SQ4 timing workaround to non-VGA versions

---

engines/pink/detection_tables.h

Detection information was provided by sauravisus in
https://bugs.scummvm.org/ticket/10919.
@whiterandrek, can you please take a look at this? Since the detection table for the PINK engine doesn't do any "fancy" stuff, the change itself is quite trivial and *should* be ready to go as is.

PINK: Add detection entry for Danish "pokus" version

---

engines/sci/engine/kmisc.cpp
engines/sci/graphics/maciconbar.cpp
engines/sci/graphics/maciconbar.h

Add support for reinitializing the mac icon bar when restarting.
Restarting runs the game's init script which calls KPlatform again.
Prior to this, restarting these games would fail an assertion.

SCI: Fix Mac icon bar crash on restart (KQ6, FPFP)

---

engines/sci/engine/guest_additions.cpp

Fixes bug #10924 where starting or restoring in text mode and then
changing to speech mode within a game results in muted speech.
This is a regression introduced between 1.9 and 2.0, probably as part
of the synchronization refactor that created GuestAdditions.

SCI: Fix broken speech after starting in text mode

---

engines/sci/engine/guest_additions.cpp
engines/sci/engine/vm.h

Fixes Audio button in control panel getting out of sync with
the message mode set by ScummVM.

SCI: Synchronize QFG4 control panel audio settings

---

engines/sci/graphics/menu.cpp

Fixes bug #10926 that prevents SQ3 German Amiga from loading

SCI: Fix kAddMenu language separator parsing

---

engines/sci/sound/drivers/amigamac.cpp
engines/sci/sound/drivers/mididriver.h
engines/sci/sound/music.cpp

Tell MidiDriver_AmigaMac the game's platform instead of it
attempting to infer this by which patch resources exist.
Fixes bug #10925 where SQ3 German Amiga is treated as Mac because
it happens to contain a patch 7 resource.

SCI: Remove MidiDriver_AmigaMac platform inference

---

image/pict.cpp
image/pict.h

Add limited support for unpacked PICT bits which FPFP Mac requires.
SCI games use packed PICT bits unless an image is less than 8 bytes
per row in which case they can't be packed, like FPFP's shovel icon.
Fixes bug #7059 which prevents the game from being completed.

GRAPHICS: Add support for PICT opcode $90 BitsRect

---

engines/sci/engine/kevent.cpp
engines/sci/graphics/maciconbar.cpp
engines/sci/graphics/maciconbar.h

This fixes two edge cases that allow mouse presses to fall through the icon bar in Mac versions of KQ6 and FPFP. Depending on the cursor this results in unexpected messages or walking to unexpected rooms when clicking an icon.
The problem is that the mac icon bar peeks at the first mouse press event in the queue whenever kGetEvent is called and handle only that message. After this kGetEvent continues to handle whatever is in the queue. This has two problems:
1. If there are two mouse press events in the queue when kGetEvent is called then the mac icon bar will handle the first and kGetEvent will handle the second, even though mac icon bar should have handled both. This is easily reproducible by clicking two mouse buttons at the same time. (Just mash 'em.)
2. If a mouse press event appears …

SCI: Fix Mac icon bar event handling

---

engines/sci/module.mk
engines/sci/resource.h
engines/sci/resource_audio.cpp
engines/sci/sound/drivers/midi.cpp
engines/sci/sound/drivers/mididriver.h
engines/sci/sound/drivers/pc9801.cpp
engines/sci/sound/midiparser_sci.cpp
engines/sci/sound/music.cpp

This is a sound driver for the PC-98 versions of Quest for Glory, Police Quest II, Space Quest IV, Kings Quest V and Castle of Dr. Brain.
I commit this in the form of a pull request, since I've not just added the driver file, but also had to make a  change to the SCI audio code (commit 5c49a2a).
To be more specific, I had to add an implementation of SCI0 sound driver opcode 3 which initializes the sound resource in the driver. PQ II checks two different playId flags and assigns different channel types accordingly. This can't be done through the existing music engine code (especially not by abusing midi control change 0x4B which isn't even implemented in the original PQ II PC-98 driver).
The only one of the existing driver which uses some sort of init method is the MT-32/GM driver. I've …

SCI: PC-98 sound driver

---

backends/platform/sdl/riscos/riscos.cpp
backends/platform/sdl/riscos/riscos.h

This provides a way for debug messages to be displayed while ScummVM is running. Since calling any of the Report_* SWIs will automatically open the !Reporter window if it isn't already visible, support for this is hidden behind a config option.

RISCOS: Log messages using !Reporter

---

engines/sci/engine/kernel.cpp
engines/sci/engine/script_patches.cpp
engines/sci/sci.cpp

This PR fixes the three game breaking bugs in Longbow version 1.0 that make Sierra's patch practically mandatory. This allows us to remove the warning at startup recommending Sierra's patch.
Endless Green Man riddles & Forest sweep instant-death: 
These two are symptoms of the same script bug that one patch fixes. A global variable is re-used from another scene without being initializing and its random value can break things.
Ordering a drink & other pub actions:
A text resource is missing 8 entries in the 5.25 floppy version. I added a workaround to detect the broken resource, repair the offsets, and return "** MISSING MESSAGE **" for the rest. This isn't perfect but it's an improvement from incorrect messages and a game-ending error. The missing entries are really just a one-time …

SCI: Fix LONGBOW v1.0 game breaking bugs

---

backends/graphics/dinguxsdl/dinguxsdl-graphics.cpp
backends/graphics/dinguxsdl/dinguxsdl-graphics.h
backends/graphics/gph/gph-graphics.cpp
backends/graphics/gph/gph-graphics.h
backends/graphics/linuxmotosdl/linuxmotosdl-graphics.cpp
backends/graphics/linuxmotosdl/linuxmotosdl-graphics.h

By moving the switch into `getGraphicsModeScale`, the function becomes identical to the parent function, meaning that it can be removed.

BACKENDS: Simplify setGraphicsMode on GPH, Dingux and LinuxMoto

---

engines/sci/engine/script_patches.cpp

Fixes an icon lingering in the verb bar after scheduled meals, bug [#10772](https://bugs.scummvm.org/ticket/10772)
````
// Rations are not properly decremented by daily scheduled meal consumption.
// Rations are consumed periodically as time advances. If rations are the
// active inventory item when the last of them is eaten, that icon will persist
// in the verb bar.
//
// We make room by consolidating common gloryMessager::say() args in a
// subroutine and cache values with temp variables. We add code to clean up
// the verb bar when rations are exhausted (test if rations were the active
// item, advance the cursor, hide the bar's invItem icon) - similar to the
// localproc in script 16, called by combinable items to remove themselves.
````
Pseudocode for the patch is …

SCI32: Fix QFG4 rations icon removal after eating

---

engines/sci/engine/kparse.cpp
engines/sci/parser/vocabulary.cpp
engines/sci/sci.cpp
engines/sci/sci.h

I recently got a hold of the dual German/English Amiga versions of LSL3 and SQ3. They're unusual in that they were released in 1991 and are SCI_VERSION_1_MIDDLE, making them now the latest known EGA parser games, and breaking some existing version checks.
This updates the parser/vocab version checks so that vocab gets loaded.
I've done some spot-checking of the Amiga interpreter for version 1 middle code to make sure that these versions weren't being misidentified, and they indeed have newer code. For example, they contain the Sound:vol update in UpdateCues (https://github.com/scummvm/scummvm/pull/1536), which wasn't in the first version of SQ4.

SCI: Add parser support for LSL3, SQ3 German Amiga

---

engines/sword25/gfx/renderobjectmanager.cpp

Fix: https://bugs.scummvm.org/ticket/7061
Additional check in RenderObjectQueue::exists() that 
checks if a RenderObject should be 
redrawn. 
After the change RenderObjectManager::render() 
was tested to update 0 objects in the first active scene,
when player does nothing including not moving cursor 
& 2 objects when player moves cursor.
It seems glitch happens when  cursor image
changes from image X to image Y to image X in a short 
time frame leaving image of state Y not re-rendered.

Sword25: image trace on quick cursor changes fix

---

backends/events/sdl/sdl-events.cpp

*reset .ascii to 0, when Num-Lock is NOT enabled and keypad directional keys are pressed* (original description) is causing the numpad to play dead completely on AmigaOS4 (no matter if numlock is active or not), so i´m excluding the platform from this change.
Please see here for reference:
https://github.com/scummvm/scummvm/commit/f5ed14e93d85b638c8e49468b2885c1278d56d20
@m-kiewitz talks about fixing the engine if it causes problems.
quote
The latter shouldn't cause issues, but in case it does, the
affected engine should get fixed and use keycodes instead.
/quote
So i´m not really sure if this is the correct approach, but since no one else seems to have problems after all the time the change is in place i´d believe it may be(?) It doesn´t change anything for any other platform, does it? …

AmigaOS4: Exclude platform from a SDL1/2 keyboard fix that breaks numpad usage

---

engines/sci/resource.cpp

This fixes a bug in the 'diskdump' debugging command that creates an additional patch file header when dumping resources that were loaded from a patch file instead of a volume. This would corrupt the dumped patch file.
The code would always create and write a new header, even if it was about to write an existing one that was read in from a patch file. Now it's either one or the other.

SCI: Fix diskdump patch file headers

---

engines/sci/engine/script_patches.cpp

Updates the speed test patch to work with the newer and significantly
different Mac version

SCI: Update QFG1VGA speed test patch for Mac

---

backends/module.mk
backends/mutex/pthread/pthread-mutex.cpp
backends/mutex/pthread/pthread-mutex.h
backends/platform/android/android.cpp
backends/platform/android/android.h

This is a first step towards moving the Android backend to use ModularBackend.

ANDROID: Add a pthreads-based mutex manager

---

common/ustr.cpp

Compiling emits the following warning:
`comparison between signed and unsigned integer expressions`
Cast the string character type to native type for comparison to fix it.

COMMON: Fix compiler warning

---

devtools/create_project/create_project.cpp
devtools/create_project/xcode.cpp

This adds a feature flag to create_project so that --enable-text-console sets USE_TEXT_CONSOLE_FOR_DEBUGGER.
The configure script has this, and create_project always sets it for xcode, and now it can be set for others like Visual Studio.

CREATE_PROJECT: Add Text console debugger feature

---

engines/sci/engine/script_patches.cpp

Fixes an uninitialized temp read in Mac version. This requires a small script patch as opposed to a workaround because the value being read is dynamic.

SCI: Fix QFG1VGA Mac great hall, bug #10945

---

graphics/managed_surface.h

Fixes an invalidRect assert when drawing lines which don't go from top-left to bottom-right.

GRAPHICS: Fix ManagedSurface dirty rects when drawing lines

---

engines/sci/engine/script_patches.cpp

Another uninitialized temp read introduced in the Mac version. Script patch because the value is dynamic.

SCI: Fix QFG1VGA Mac giant fight, bug #10948

---

engines/glk/picture.cpp
engines/groovie/roq.cpp
engines/titanic/support/image_decoders.cpp
graphics/yuv_to_rgb.h
image/codecs/mjpeg.cpp
image/jpeg.cpp
image/jpeg.h
image/png.cpp
image/png.h

In ResidualVM:
* Myst III decodes large amounts of JPEG images (each node is made of at least 6 640x640 images).
* The WIP HD mod for The Longest Journey has its backgrounds stored as 1080p PNG images.
The issue I've been having with the current JPEG and PNG decoders is that they perform color conversion to a somewhat arbitrary pixel format.
* That color conversion is rather slow when dealing with large images.
* The output pixel format being arbitrary, the calling code is required to perform a second pass of color conversion. Ideally images should be decoded directly to the screen format so they can be blitted to the screen directly.
* The output pixel format has a different byte order on big endian and little endian systems, making it hard for the caller to do byte level pixel …

IMAGE: Avoid pixel format conversions in the JPEG and PNG decoders

---

dists/androidsdl/How_to_Build.txt
dists/androidsdl/build.sh
dists/androidsdl/scummvm/AndroidAppSettings.cfg
dists/androidsdl/scummvm/AndroidAppSettings.cfg.in
dists/androidsdl/scummvm/AndroidBuild.sh

This will disable cloud support (libcurl, sdl-net and cloud are disabled in the configure command).
I will also update the wiki page (https://wiki.scummvm.org/index.php/Compiling_ScummVM/Android-SDL) if or when this PR is merged. The info there should reflect the contents of the updated How_to_Build.txt

ANDROIDSDL: Fix build with NDK r15c

---

backends/events/riscossdl/riscossdl-events.cpp
backends/events/riscossdl/riscossdl-events.h
backends/events/sdl/sdl-events.cpp
backends/events/sdl/sdl-events.h
backends/module.mk
backends/platform/sdl/riscos/riscos.cpp
common/events.h
dists/macosx/Info.plist
dists/macosx/Info.plist.in
gui/dialog.cpp
gui/dialog.h
gui/gui-manager.cpp
gui/launcher.cpp
gui/launcher.h

This PR allows adding games by dragging them to the ScummVM window from an external filer window. Currently this is only implemented with SDL2, although I might consider implementing it on RISC OS as well using `SDL_SYSWMEVENT` events if there's enough demand, since RISC OS applications typically make greater use of drag and drop compared to other OSes.

GUI: Support adding games via Drag and Drop

---

engines/sci/graphics/view.cpp

This adds support for view loops that mirror loops that mirror loops, and so on. ScummVM only supports one level of loop referencing. Sierra's interpreter loops through all the mirror references until it finds a "real" loop and then mirrors that. FPFP depends on this this when the cook leaves the town in room 200, otherwise ScummVM doesn't populate these loops and fails an assert, bug #10953. 
FPFP View 844's relevant loops:
- 	loop 0: the cook walking to the right
- 	loop 1: mirror of loop 0
- 	loop 3: mirror of loop 1
- 	loop 5: mirror of loop 3
The script uses loops 3 and 5. Since they both trace back to loop 0, they are both loops of the cook walking to the left, just like loop 1. SCI Companion displays loops 3 and 5 backwards as it applies mirroring to the previous loop instead of …

SCI: Handle recursive view loop references

---

configure

--disable-updates was omitted from the supported options during the reformat (b3d5bb34ae52063abb23175de9bd4d6d525145e1).

CONFIGURE: Fix missing option

---

engines/sci/sound/music.cpp

This changes an error() to warning() when SciMusic::cmdSendMidi is called against a non-midi sound as this occurs in FPFP.
FPFP sets its gameMusic2 to an audio sample in at least one scene, and other scenes call gameMusic2:mute which calls kDoSound SendMidi. This occurs in all FPFP versions. Fixes bug #10952
This was promoted from warning() to error() in: https://github.com/scummvm/scummvm/commit/db70d66e4ae872ebdeb2a88ef0870708a30c7667

SCI: Change sendMidiCommand non-midi error to warn

---

po/pt_PT.po

Fixes the Portuguese language name displayed by ScummVM and the plural rule (not sure if ScummVM uses plurals but can't hurt).

I18N: Correct Portuguese (Portugual) metadata

---

engines/scumm/costume.cpp
engines/scumm/gfx.cpp
engines/scumm/saveload.cpp
engines/scumm/scumm.cpp

Fix to use the correct shape/size of the flashlight used by the original engine, covers [10951](https://bugs.scummvm.org/ticket/10951) and [10947](https://bugs.scummvm.org/ticket/10947) 
C64 MM
V1
V2
Zak C64
Zak V1
Zak V2

SCUMM: Implement original V0-V2 flashlight shape and size for MM/Zak

---

audio/decoders/adpcm_intern.h
audio/softsynth/mt32/FileStream.cpp
backends/cloud/cloudicon.cpp
backends/platform/sdl/sdl-sys.h
image/jpeg.cpp

Fixes MSVC warnings in the common ScummVM code. More details are in the commit messages.

JANITORIAL: Fix MSVC warnings

---

configure

This will probably require a toolchain update on our current buildbot.

ANDROID: Update to compile with modern NDKs

---

backends/fs/stdiostream.h
common/file.cpp
common/file.h
common/memstream.h
common/stream.cpp
common/stream.h

This introduces a new SeekableWriteStream class to play a similar
role as the SeekableReadStream class, but for write streams.
It add methods for seek and size, and the following classes have
been changed to support it:
1) Memory stream classes
2) DumpFile class
3) StdIOStream class
I tried to have minimal impact on the existing system. Please note
the following:
1) DumpFile still only has a reference to a WriteStream internally. I
didn't want to change it to SeekableWriteStream, since that would
require also converting he file system node methods to return it as
well. And I'm not sure if there are any backends that have their own
custom implementations of files other than StdIOStream. If there are,
they'd eventually need to be updated to use SeekableWriteStream
as well, and we can …

COMMON: Add SeekableWriteStream class

---

base/plugins.cpp
engines/game.cpp
engines/game.h
gui/launcher.cpp
gui/unknown-game-dialog.cpp
gui/unknown-game-dialog.h

* The list of candidates now includes unknown variants. When an unknown
variant is selected, the unknown game dialog is shown.
* On the unknown game dialog, users are given the choice to add the game
when that is possible, or to cancel.
The goal of those changes is to make the unknown game dialog less
confusing for users, especially when both known and unknown games
variants are found.
This is meant to supersede #1493.

GUI: Better integrate the unknown game dialog when adding games

---

engines/sci/engine/script_patches.cpp

FPFP Mac is missing view 844 of the cook leaving town. This is the unusual view that 67908559167844a1a207d1544dfcdbd8f8ca1260 fixed for PC versions. In Mac it's simply missing and the scene would crash in the original.
This a minor optional scene so I patched it out for Mac so that it doesn't crash. Fixes bug #10954

SCI: Disable FPFP Mac script that uses missing view

---

AUTHORS
devtools/credits.pl
gui/credits.h

He was last active in 2009 and has long moved on to work on other things.
Thank you for merging my PR from yesterday so quickly. I just realized that Vicent's entry should also be updated.
Perhaps also further people should be given credit for the GUI? Here's the top 10 of people who modified the GUI C++ source code (to filter out i18n changes; of course one may also want to credit people who worked on the themes
```
$ git shortlog -sn gui/*.cpp gui/*.h gui/*/*.cpp gui/*/*.h  | head -n 10
580	Max Horn
297	Eugene Sandulenko
290	Johannes Schickel
118	Vicent Marti
114	Alexander Tkachev
105	Thierry Crozat
98	Torbjörn Andersson
41	Filippos Karapetis
39	Bastien Bouclet
29	Willem Jan Palenstijn
```

CREDITS: mark Vicent Marti as retired

---

engines/wintermute/base/gfx/osystem/base_render_osystem.cpp

Wintermute fills screen area with black color when save/load process is finished.
There was a misprint in ScummVM's code which caused only left part of the screen go black.

WINTERMUTE: Fix fill rect area on endSaveLoad()

---

.gitignore
Makefile.common
backends/platform/sdl/riscos/riscos.mk
backends/platform/sdl/win32/win32.mk
doc/de/NEUES.md

This is a conversion of the German edition of the NEWS file, now called NEUES.md. Don't worry about the outdated contents of the file itself - it will get updated as soon as the conversion is done.
I know the integration into the win32.mk file is very rough at the moment and only intended to avoid breaking the compilation progress.
@ccawley2011, could you assist with integrating this file in the pandoc system? :)

NEWS: Convert German NEWS file to Markdown

---

.travis.yml

Mac OS X builds were previously disabled in commit 41ee643 due to the build machines at the time being unreliable, however that was over a year ago, so it's likely that things have changed since then.
Currently, this only builds with `configure`, as it did before, however in the future it would be a good idea to also build with `create_project` and Xcode as well, since that's something that can't be done on the buildbot.

TRAVIS: Re-enable Mac OS X builds

---

backends/events/default/default-events.cpp

When warping mouse, if there is a mouse release event in the event queue, it gets eaten by the purgeMouseEvents function and _buttonState gets desynchronized.
This pull request prevents this by updating _buttonState even when purging events.

COMMON: Fix button state desynchronization when warping mouse

---

engines/sci/engine/message.cpp
engines/sci/engine/message.h

This fixes 17 message texts in the CD version of FPFP, bug #10964.
This is a new one, the audio is right but the text is in all the wrong places, with strings like "Dummy Msg" in most of them. I'm assuming this is because this game didn't formally offer a text mode in the CD version. The installer didn't even have a No Soundcard option. What's weird is that these three sequences are the only ones like this, everything else seems fine, so I don't expect this to need future updates.
Let me know what you think. I'm not wild about touching processString() for this, but it's const char* on down, and now future workarounds can also trim trailing text by setting MessageRecord::length.

SCI: Fix FPFP CD 'Dummy Msg' message texts

---

engines/bladerunner/bladerunner.cpp
engines/bladerunner/detection.cpp
engines/bladerunner/savefile.cpp
engines/bladerunner/savefile.h
engines/bladerunner/ui/kia_section_save.cpp

Bumped saved game version to 2 to add play time.
Can load version 1 saves and save/load version 2 saves.

BLADERUNNER: Show saved game creation date and add play time

---

engines/bladerunner/script/ai/free_slot_a.cpp
engines/bladerunner/script/scene/ug15.cpp

This will make that part less frustrating. The rat can still get you.

BLADERUNNER: Add flag to disable sewer bridge breaking

---

configure

This patch silences the warnings about the (outdated?) 'u'
flag that appears at least when building and linking ScummVM
statically on mingw32:
"`u' modifier ignored since `D' is the default (see `U')"
The cause for this appears to be a bug in recent versions of
libtool that most likely will also appear when building on
Linux. However, since I have not tested this yet, this patch
only disables it for mingw32.
The only downside from this patch is that building a non-clean
build will take (slightly?) longer since we are no longer
just updating (that's what the 'u' is for) changed libraries
during the linking stage, but linking all .a files again.

CONFIGURE: Remove the 'u' flag from 'ar' in mingw32

---

engines/bladerunner/script/ai/moraji.cpp
engines/bladerunner/script/scene/dr04.cpp

This extending the bomb duration by 10secs while Moraji
is chained.
It extends the bomb from blowing up by 1.1 secs after Moraji
is freed.
Finally, the blast radius is decreased so that the player may survive closer.
All of this only happens on the uncut version when playing on easy.
I picked 1.1 sec for the post-freed time because if it is longer
Moraji will continue to run in place when he reaches his destination
outside Dermo Design (If its the path where he falls after the bomb
blows).

BLADERUNNER: Make the Moraji encounter easier on easy

---

engines/agos/drivers/accolade/adlib.cpp
engines/agos/midi.cpp
engines/agos/midi.h

Work in progress on https://bugs.scummvm.org/ticket/10310
This implements _masterVolume and setVolume in MidiDriver_Accolade_AdLib and uses a cast to call setVolume() in agos/midi.cpp in pause() if AdLib & Accolade are used.
The other drivers mostly seem to not implement channel allocation so I decided to follow TO_DO comment in the MidiDriver_Accolade_AdLib code.
Not in the PR: 
Implementing the same _masterVolume and setVolume in MidiDriver_Simon1_AdLib  and calling that in pause() seems to fix the same defect for Simon 1.
For mt32 using _driver to send control message for volume for all channels seems to fix this for mt32.
Making PR in hopes of getting some input on how to proceed.

agos: mute fix for adlib accolade

---

backends/platform/sdl/win32/win32.cpp

Make sure to close handles created by `CreateProcess` as per https://docs.microsoft.com/en-us/windows/desktop/ProcThread/creating-processes
(closing them doesn't affect the running process)

WIN32: Fix leaked handles in CreateProcess

---

engines/wintermute/detection_tables.h

Some info for ScummVM wiki:
Game resolution: 1105x700
WME version is avaliable here: https://anatolii.itch.io/the-kite
Moddb link goes to steam that seems to serve Unity version that is not supported...
Game can be marked as completable.

WINTERMUTE: Add detection for the Kite v1.4

---

engines/sci/event.cpp

This fixes several backend events being misinterpreted as SCI keyboard events.
The most noticeable is EVENT_SCREEN_CHANGED which gets translated as kSciEventKeyDown. For example, toggling fullscreen during the SQ4 intro will cause the game to prompt if you want to skip the intro. (This isn't due to the ALT+ENTER keys as the backend code claims those events.)
EventManager::getScummVMEvent() is a large function that translates an incoming Common::Event to an SciEvent. First it handles a few misc event types, then mouse events, and finally it does a lot of keyboard event mapping, but it doesn't verify that the event type is keyboard and instead assumes it must be. Non-keyboard events that the function doesn't first explicitly handle bounce around the mapping code and come out as effectively …

SCI: Fix backend events treated as keyboard events

---

backends/platform/sdl/amigaos/amigaos.mk
devtools/update-version.pl
dists/amiga/RM2AG.rexx
dists/amiga/RM2AG.rexx.in

Complete rewrite of the (AmigaOS4-only) RM2AG.rexx script to cover the change to markdown.
I´d like to ask for review and some questions before it gets merged.
- Is there some kind of list where someone could add this file regarding "automatic" version updates?
I have added a version information (line 33) to the script (amongst other things) but would refrain from doing a manual change everytime a new version appears.
There are of course other options:
1) I could drop the whole line.
2) I could stick with the scripts version (0.20 right now e.g.)
- Lines 163-166 add a conversion from the markdown/html in-readme link (of the files NEWS.md and AUTHORS) to an AmigaGuide specific one, which will open the given files locally from within the installed archive (if available).
I don´t really like …

AMIGAOS4: RM2AG.rexx rewrite

---

engines/sci/engine/script_patches.cpp

This updates the script patch for the SQ4 floppy crash when clicking inventory items on sequel police in the mall:
- Applies the patch to the arcade where the bug also exists (and in more versions)
- Fixes additional instance of the bug/crash when clicking the ATM card on police in arcade
- Fixes English PC floppy verb handling in arcade so that police can be clicked as intended
- Updates patch to not leak a stack element
This bug has a complex history but the short version is that now no versions crash and all versions display messages.
The leaked stack element didn't cause a problem in practice because the ScummVM interpreter masked it by thinking there were temp variables on the stack (I don't think there are) and tossing the extra element along with the rest when returning from the …

SCI: Update SQ4 Sequel Police patch for arcade

---

engines/xeen/scripts.cpp

uint32 parameters for script commands (e.g. give experience to character) are intermediate stored in a uint16 (`result`), so the 2 high bytes are cut off. This breaks late game behaviour when XP > 65535 is given. The commit corrects the type of the intermediate value.

XEEN: fix result type for readUint32LE()

---

engines/wintermute/detection_tables.h

This commit adds detection entries for two demo versions (Chapter 1 and Chapter 5) for "Rhiannon: Curse of The Four Branches", reported via Trac. After adding the detection entries, both demos start in ScummVM.
closes #10972
closes #10973

WINTERMUTE: Add detection entries for reported rhiannon demos

---

graphics/managed_surface.cpp
graphics/managed_surface.h

When calling ``ManagedSurface::copyFrom()``, ``_disposeAfterUse`` should be set to
``DisposeAfterUse::YES`` because inner surface frees up old pixels array and creates a new one.
If you don't do this, creating an empty ``ManagedSurface`` through default constructor and then using ``copyFrom()`` on it will lead to memory leak when the ``ManagedSurface`` will be destroyed because it won't call ``Surface::free()`` on it.
In addition I fix a bug on ``copyFrom()`` which should use ``addDirtyRect()`` like ``create()`` does instead of ``clearDirtyRects()``.
I don't think this will break any engine but, in doubt, the engines using ``ManagedSurface::copyFrom()`` seems to be: director, cryomni3d, xeen and access.

GRAPHICS: Fix ManagedSurface::copyFrom memory and rectangles handling

---

engines/sci/engine/message.cpp
engines/sci/engine/message.h
engines/sci/engine/script_patches.cpp
engines/sci/engine/workarounds.cpp
engines/sci/engine/workarounds.h
engines/sci/resource.cpp
engines/sci/resource_audio.cpp

Adds a new workaround system for known broken messages and their
corresponding audio and sync resources. This replaces all special
cases in c++ and several script patches with data structures and
generic handling.
Common message bugs:
- Wrong tuple requested by game script
- Wrong tuple in message resource
- Wrong message text that exists in another record
- Missing message text
- Audio or sync resource with different tuple than message
Some notes:
- I've tested each workaround (whew!)
- The first commit is for a message script patch of mine that should have been an uninitialized parameter workaround from the start. Oops!
- The existing c++ workarounds in getRecord() wouldn't have worked on CD versions since they didn't remap audio tuples, but they happened to all be for floppy versions. …

 SCI: Create message workaround system 

---

engines/sci/engine/script_patches.cpp

This message bug requires a script patch because the wrong message it asks for is a valid message which it correctly asks for on a different line.

SCI: Fix SQ4 Monolith Burger door message, bug #10976

---

engines/wintermute/detection_tables.h

Official downloads page for the White Chamber
(http://www.studiotrophis.com/site/downloads) contains 2 links:
1. Download from IndieDB (thewhitechamber1.7SETUP.exe, 376180149 bytes)
(built 2008.06.29, installed game is detectable by ScummVM)
2. Direct Download (thewhitechamber1.7SETUP - Definitive Edition.exe,
376180083 bytes) (built 2008.06.26, installed game is unknown to
ScummVM)
Both version are called "v1.7 - Definitive Edition".
speech.dcp is different: "german/COMPUT050.ogg" was renamed to
"german/COMPUT050.ogg"
data.dcp & language.dcp content is the same for those versions, except
for timestamps (Wed, 25 Jun 2008 21:01:32 GMT vs Sun, 29 Jun 2008
19:36:33 GMT)
Several questions:
1. Is it alright to list those builds as Common::UNK_LANG ? Should we
change this to 9 records for exact …

WINTERMUTE: Add another variant of White Chamber to detection table

---

engines/wintermute/detection_tables.h

Actual name of "hamlet" is "Hamlet or the last game without MMORPG
features, shaders and product placement". Fixed misprint in word
"MMORPG".
Also added one more Hamlet version from
https://bugs.scummvm.org/ticket/10980.
My version has another checksum, so I can't test this addition.

WINTERMUTE: Fix Hamlet title, add one more detection variant

---

engines/wintermute/detection_tables.h

This pull request adds all games listed in
https://bugs.scummvm.org/ticket/10863:
// Carol Reed 10 - Bosch's Damnation
// Carol Reed 11 - Shades Of Black
// Carol Reed 12 - Profound Red
// Carol Reed 13 - The Birdwatcher
// Carol Reed 14 - The Fall Of April
// Rebecca Carlson Mystery 01 - Silent Footsteps
// Corrosion: Cold Winter Waiting (Enhanced Edition)
// Rhiannon: Curse of the four Branches (Premium Edition)
I don't have those games, so I can't check if those sums are correct.

WINTERMUTE: Add detection for games listed in defect #10863

---

engines/sci/engine/script_patches.cpp

"How's QFG4 going?"
"Let's just say even SQ4 mall bugs are more fun..."
This fixes lockup, animation, and flag bugs when hiding in the electronics store, bug #10977.
Whew! This one has been sitting in the queue for a while, but the hole kept getting deeper. It looks like this entire sequence was never tested on CD, since it locks up immediately and has message typos and animation and flag bugs after that. I never knew you could do this stuff as it takes an inefficient escape route, which I guess is how testers missed it.
These fixes make a dozen lines of audio available for the first time, including a "new" death message in front of monolith burger.

SCI: Fix SQ4 Sequel police electronics store bugs

---

engines/sludge/fileset.cpp

```
scummvm: ./common/array.h:192: T& Common::Array<T>::operator[](Common::Array<T>::size_type) [with T = Common::String; Common::Array<T>::size_type = unsigned int]: Assertion `idx < _size' failed.
Thread 1 "scummvm" received signal SIGABRT, Aborted.
0x00007ffff642082f in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff642082f in raise () from /usr/lib/libc.so.6
#1  0x00007ffff640b672 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff640b548 in __assert_fail_base.cold.0 () from /usr/lib/libc.so.6
#3  0x00007ffff6418db6 in __assert_fail () from /usr/lib/libc.so.6
warning: Could not find DWO CU engines/sludge/fileset.dwo(0x9165f29a3fab4d8b) referenced by CU at offset 0x1d65c [in module /usr/bin/scummvm]
#4  0x0000555556c9cc08 in …
```

SLUDGE: fix crash in ResourceManager::readResourceNames

---

engines/sludge/floor.cpp

numPolygons wasn't getting reset to 0, so the next invocation was trying to delete non-existent polygons.

SLUDGE: fix crash in FloorManager::setFloorNull

---

engines/sludge/savedata.cpp

The check was inverted - it failed when everything was alright and succeeded on error...

SLUDGE: fix data file handling with custom encoding setting

---

engines/sludge/backdrop.cpp

When a game sets camera position with aimCamera, the background should move together with all the objects above it.

SLUDGE: fix background position not taking camera into account

---

engines/wintermute/base/scriptables/script_ext_string.cpp

It's hard to believe, but this fixes [bug #10432](https://bugs.scummvm.org/ticket/10432) WME Carol Reed
Mysteries hint system not working.
Carol Reed hint system happen to heavily use line.Split(";") results,
which were wrong by 1 byte (delimeter was appended to result while it
shouldn't be).
I started with decompiling Carol Reed source code, reproducing issue
with a stand-alone test project (which worked with WME and showed [null]
with ScummVM). then minimized it to a minimal testcase:
```
var line = new String("New Goal;Visit Christina at the Art
Museum;1;0;S;;");
var ar = line.Split(";");
if((ar[0] == "New Goal")) { var g = ar[1]; }
```

WINTERMUTE: Fix Split() method of ext_string

---

devtools/create_project/create_project.cpp
devtools/create_project/create_project.h
devtools/create_project/msvc.cpp

Do you dread everytime you run create_project, watching as MSVC has to reload the whole solution from scratch, probably messing up your workspace state and losing your open files?
Well, dread no more! This updates create_project so that the project UUIDs are deterministic (instead of changing everytime) between regenerations, so that MSVC can more effectively cache and reload the workspace.
This is done by replacing them with MD5 hashes of the project names, which are effectively unique across the solution, but consistent everytime. I used the Win32 APIs to do it since this is only applicable to MSVC so I didn't think it's worth pulling in a whole md5.cpp for it.

MSVC: Use determinstic UUIDs for project files

---

configure

This is useful on RISC OS, as when building on RISC OS, linking fails with a number of `relocation truncated to fit: R_ARM_PC24 against symbol...` errors when the executable size gets too large, so this provides a simple way to split the build.
At some point, I would like to set up a RISC OS builder on the buildbot, if someone else could help with that.

CONFIGURE: Add --enable-all-unstable-engines option

---

engines/sci/engine/script_patches.cpp

Fixes bugs in the final room of QFG4, all versions:
- Ad Avis comes back to life and kills player after being killed
- Less than half the intended time limit (symptom of previous bug)
- Not allowed to cast spells after casting the first spell or throwing a rock/dagger
- Staff doesn't transform if you cast a spell or threw a rock/dagger (symptom of previous bug)
- Not allowed to cast final spell and complete game if speed wasn't set to high
- Transposed responses from Ad Avis when casting spell or throwing rock/dagger 
- Throwing a rock/dagger after telling the joke kills Ad Avis (game mistakes it for staff spell)
- Infinite animation loop when staff turns into spear if you threw a rock/dagger or cast a spell
This room is such a tangle that without completing all the patches I couldn't be …

SCI32: Fix QFG4 Ad Avis end-of-game bugs

---

.travis.yml

gcc on Mac OS X is just a frontend for LLVM.

TRAVIS: Don't build with gcc on Mac OS X

---

engines/bladerunner/bladerunner.cpp

Previously any keyup event skipped the intro videos (including Shift)

BLADERUNNER: Skip videos with Esc key only

---

engines/sci/engine/kernel.cpp
engines/sci/engine/kernel.h
engines/sci/engine/kernel_tables.h
engines/sci/engine/kmisc.cpp
engines/sci/graphics/view.cpp
engines/sci/sci.cpp

I've been sitting on this for a while, uncertain if I should bother making a PR. I feel like using the text-mode end screen resource's presence instead of the game ID to gate the SCI11+ features might inspire fangame creators as they wouldn't need to get their work added to the detection tables, but on the other hand there are a bunch of interesting SCI11+ features left out of this PR that even The Dating Pool doesn't use. And frankly, one of those features scares me.
No other SCI games use vocab 184 for anything.
So... do what you want, really.

SCI: Add some more SCI11+ features

---

graphics/transparent_surface.cpp

This fixes [defect #10686](https://bugs.scummvm.org/ticket/10686), which was first reproduced with an actual game FoxTail on WME, then reduced to a WME testcase https://github.com/tobiatesan/wme_testsuite/tree/master/light_test/packages (you can try it with ScummVM nightly)
In BLEND_NORMAL mode with color != 0xffffffff, blending fully
transparent pixel was resulted in slightly modifying some background
colors, because old value X was a bit different from new value (X*255>>8). This pull request provides a workaround by doing nothing on transparent pixels.
It also raises larger question if it is alright to do other shifts like "in[kAIndex] * ca >> 8", "in[kRIndex] * ina * cr >> 16", "((in[kGIndex] * cg  * (out[kGIndex]) * in[kAIndex]) >> 24" instead of devision by 255, 65025 and ‭16581375‬ …

GRAPHICS: Fix fully transparent pixel blit

---

backends/platform/sdl/win32/win32.cpp

This implementation now matches previous ShellExecute() calls, so we are now consistent in that regard. It also silences a warning in Mingw complaining about a type mismatch.

WIN32: Use HINSTANCE for OSystem_Win32::openUrl

---

backends/platform/sdl/win32/win32.cpp
backends/platform/sdl/win32/win32.h

It's generally good practice to provide the window handle when you have one.

WIN32: Make use of the window handle when calling ShellExecute.

---

engines/wintermute/base/gfx/osystem/base_surface_osystem.cpp

This kind of fixes https://bugs.scummvm.org/ticket/6572 WME: Rosemary -
Sprite flaw on going upwards
Some Rosemary sprites have non-fully transparent background pixels,
sprites of walking up has LOTS of them. Testing Rosemary walking
character in a test WME game demonstrates some glitches with original
WME as well. However, character sprite is downscaled most of time, and
with original WME it isn't that seen when sprite is downscaled.
This pull request provides a workaround for this case instead of
changing downscaling algorithms:
* if game ID is "rosemary"
* if loaded sprite is from "actors" folder
* if bytesPerPixel is 4
* if some pixel's alpha is between 1 and 15
* set this pixel's alpha to 0

WINTERMUTE: Add workaround for sprite glitch at Rosemary game

---

engines/wintermute/base/base_game.cpp

Game.OpenDocument() is used to open links for developer's site or social
account in games like hellavuday, 5ld, etc.

WINTERMUTE: Implement Game.OpenDocument() method

---

engines/sci/engine/script_patches.cpp

Fixes a lockup in a mandatory scene in the first floppy version

SCI32: Fix QFG4 Ad Avis capture lockup, bug #11001

---

engines/wintermute/base/gfx/osystem/base_surface_osystem.cpp
engines/wintermute/base/gfx/osystem/render_ticket.cpp

This fixes [defect #10684](https://bugs.scummvm.org/ticket/10684): 1-pixel width sprite becomes a big rectangle
if rotation is applied.
Case was originally reproduced with FoxTail game for WME, then reduced
to testcase
https://github.com/tobiatesan/wme_testsuite/tree/master/time_test/packages

WINTERMUTE: Do not optimize out alpha blits on rotation

---

engines/sci/engine/kgraphics32.cpp

kShakeScreen32's kernel signature allows its second parameter to be optional but the implementation doesn't check and always attempts to use it, in which case the shake direction is determined by random memory.
At least GK1 and QFG4 have scripts that don't pass direction. In SCI16 the optional direction parameter defaulted to vertical.
Using random memory is a technically accurate SCI32 implementation! =) I checked the disassembly of GK1 floppy, QFG4 CD, and GK2 and they don't validate parameter count. I tested in DOSBox and indeed these scenes randomly shake vertical, horizontal, diagonal, or not at all. (SCI 3 replaced ShakeScreen with a stub.)
This restores the default vertical parameter value as it was in SCI16, which is what the scripts expect. The alternative would be to make the …

SCI32: Fix kShakeScreen32 parameter count check

---

engines/bladerunner/bladerunner.cpp

Fixes this compiler warning:
`engines/bladerunner/bladerunner.cpp:2176:71: warning: cast from type ‘const void*’ to type ‘uint16* {aka short unsigned int*}’ casts away qualifiers [-Wcast-qual]
uint16  srcPixel = *(uint16 *)_surfaceFront.getBasePtr(x * 8, y * 8);`
I am not able to test this, so review it first.

JANITORIAL: Fix compiler warning with const cast.

---

engines/wintermute/ui/ui_window.cpp

For some reason getFontHeight() is off-by-one comparing to height set in
TITLE_RECT, which made text being bigger then title rect and drawing was
skipped.
Which means, either game author was wrong by 1 and original Wintermute was more tolerant to off-by-one errors, or something is wrong with getFontHeight(). As there are no reports of bugs related to wrong font height, I believe the issue is with this one game, not the graphics\fonts\ttf.cpp.
So, let's provide a quick workaround for this game.
This fixes https://bugs.scummvm.org/ticket/6501

WINTERMUTE: Increase window title viewport height by 1 for "5 Lethal Demons" game

---

backends/platform/ios7/ios7_common.h
backends/platform/ios7/ios7_keyboard.h
backends/platform/ios7/ios7_keyboard.mm
backends/platform/ios7/ios7_osys_events.cpp
backends/platform/ios7/ios7_video.mm

I am submitting this as a Pull Request to see if others have feedback before I merge this. I am in particular looking for feedback from iPhone users since I only have an iPad, and was only able to test iPhone using the simulator. I am planning to leave it open for one week and then merge.
The first commit adds an input accessory view to the keyboard, which allows to add one row of buttons. <del>Due to widths limitation, less buttons are added on iPhone than iPad.</del> _A scrollview is used so that we can have more buttons than fits the screen._
* iPad _and iPhone_
* Main Menu button
* Escape key
* _Tab key_
* Return key
* F1 to F12 keys
* Arrow keys
* <del>iPhone</del>
* <del>Return key</del>
* <del>F1 to F10 keys</del>
Here is a screenshot for iPad:
The second commit removes the mapping …

Improve iOS inputs

---

common/hashmap.h
graphics/VectorRenderer.h

C4121 is about 'symbol': alignment of a member was sensitive to packing

JANITORIAL: Avoid C4121 warnings in MSVC by reordering fields

---

devtools/create_project/create_project.cpp
devtools/create_project/msvc.cpp

This addresses the issues brought up in PR #1722 in a more robust way;
To disable nasm from x64, the whole define list was rewritten from scratch using `getFeatureDefines` and `getEngineDefines`. This ended up removing [important defines](https://github.com/scummvm/scummvm/blob/master/devtools/create_project/create_project.cpp#L391) added later in the setup phase, which presumably someone noticed, as they were [poorly re-added](https://github.com/scummvm/scummvm/blob/master/devtools/create_project/msvc.cpp#L158).
Instead, I opted to just find and remove the nasm define for x64. Better one little hack than a whole pile of them. :)
This also adds the new libcurl Win32 dependencies and cleans up the rest so they're only generated for the appropriate targets. More detailed explanations in the …

CREATE_PROJECT: Fix missing MSVC x64 defines

---

engines/wintermute/detection_tables.h

WINTERMUTE: Add detection for 6 more Carol Reed demos
Fixes https://bugs.scummvm.org/ticket/11005
WINTERMUTE: Reorder Carol Reed detection records 
On undetected game user gets message like this:
```
Matched game IDs for the Wintermute engine: actualdest-win,
basisoctavus-win-cz,
agustin-win, bthreshold-win, bickadoodle-win, bookofgron-win-ru,
carolreed4-demo-win, carolreed5-win, carolreed6-win,
carolreed7-demo-win,
carolreed8-win, carolreed9-win, carolreed10-win, carolreed11-win,
carolreed12-win, carolreed13-win, carolreed14-win, chivalry-win,
corrosion-win,
deadcity-win-cz, dfafadventure-win, dirtysplit-win, dreaming-win,
driller-win,
...
```
It's confusing that some carolreed games are mentioned as demos and some
are not.
Fixed this by reordering records.

WINTERMUTE: Add detection for 6 more Carol Reed demos

---

engines/wintermute/ad/ad_game.cpp
engines/wintermute/base/base_engine.h
engines/wintermute/detection_tables.h

There is a bug introduced in WME Lite.
Testcase:
1. Download https://github.com/lolbot-iichan/wme_testsuite/tree/master/slider_test/packages
2. Download https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/wmelite/wmelite_10_win.zip
3a. Run game.exe -> Slider moves with the mouse while it is pressed and
released when mouse is released
3b. Run wmelite.exe -> Slider is never released
3c. Run ScummVM -> Slider is never released
Related bugs:
https://bugs.scummvm.org/ticket/6567
https://bugs.scummvm.org/ticket/9861
Reason: slider is a button object that changes it's X until "LeftRelease" event is revieved and breaks the endless loop.
Sample code: https://github.com/lolbot-iichan/wme_testsuite/blob/master/slider_test/data/interface/system/speechvolume.script
However, …

WINTERMUTE: Fix slider bug at 1 1/2 Ritter and Oknytt

---

backends/saves/default/default-saves.cpp

fopen() fails, but the null handle was passed on to OutSaveFile.

BACKENDS: Fix crash when save file is owned by another user

---

engines/glk/alan2/alan2.cpp

I think this part of code is erroneous as it shouldn't check the previous item on the first iteration of the loop.
Moreover, this code seems to raise an internal compiler error of OpenPandora build. I hope my rewrite will fix it as well.

GLK: Fix off-by-one memory read

---

backends/events/sdl/sdl-events.cpp
backends/events/sdl/sdl-events.h
common/EventMapper.cpp
common/events.h
engines/engine.h
engines/pegasus/detection.cpp
engines/pegasus/input.cpp
engines/pegasus/input.h
engines/pegasus/pegasus.cpp

This PR provides the option for engines to receive joystick events from the backend. It's based ResidualVM's joystick handling.
Currently this implements joystick support for The Journeyman Project: Pegasus Prime. The joystick mapping is based on the on the [PlayStation](https://www.giantbomb.com/images/1300-2609821) and [Pippin](https://www.giantbomb.com/images/1300-2609822) versions, with some changes.
All games with joystick support will open the main menu when the start button is pressed.
This PR is not 100% complete. The most notable thing missing is proper handling for analog sticks. Since Pegasus Prime simply uses the analog stick to simulate mouse input, I simply opted to disable passing axis events and let the backend handle it. In the long term though, the joystick to mouse code …

 SDL: Initial implementation of joystick events

---

engines/sci/engine/features.cpp
engines/sci/engine/features.h
engines/sci/graphics/text16.cpp
engines/sci/graphics/text16.h

This implements an off-by-one bug and comparison change in text length calculations that was in all SCI interpreters until late 1990. This fixes bug #10000 (mwahahaha)
On the notebook screen at the end of LB1, the last "E" in the word "INCOMPLETE" is wrapped onto the next line in ScummVM. It's a script bug, but thanks to the interpreter bug it accidentally works in the original.
GetLongest() returns the number of characters that can be displayed in a given width. "INCOMPLETE" is 52 pixels but the script specifies a width of 50. GetLongest() should return 9 and set the string pointer to "E" but in SSCI when a string exceeds the width before a space character is reached, the exceeding character was originally applied to the result. Normally this isn't a scenario that a script should be in, …

SCI: Implement early GetLongest() behavior, bug #10000

---

engines/sci/detection_tables.h

This removes the option for using original save/load screens from SCI16 and GK1 Mac versions because they didn't have them and so it currently crashes with signature mismatches and other problems.
Instead the Mac interpreter would just launch the operating system's open/save file dialog. The game scripts don't contain the original UI.

SCI: Remove GAMEOPTION_ORIGINAL_SAVELOAD from Mac versions

---

engines/queen/detection.cpp

QUEEN: Remove a bad detection entry
This is a bad entry: *DOS Floppy - Russian*
> "queen.1","0d1c10d5c3a1bd90bc0b3859a3258093",22677657
The proper one is already documented in the entry: *DOS Floppy - Russian (From Bugreport #6946)*
> "queen.1", "f5e827645d3c887be3bdf4729d847756", 22677657
The removed entry matched the MD5 hash values for the ***full*** original file:
> File : QUEEN.1
> Size : 22677657
> Hashes for the full file (22677657 bytes)
>   * CRC32: 3c266e5f
>   * MD5  : 0d1c10d5c3a1bd90bc0b3859a3258093
>   * SHA1 : c5ec968e926702efc3a58fff6bddc1e193ca890e
> Hashes for the first 5000 bytes
>   * CRC32: 28a15ba1
>   * MD5  : f5e827645d3c887be3bdf4729d847756
The proper entry (marked as *"DOS Floppy - Russian (From Bugreport #6946)"*) matches the right hash value for ***the first …

QUEEN: Remove a bad detection entry

---

common/events.h

Fixes the following compiler warning:
> backends/events/sdl/sdl-events.cpp: In member function ‘virtual bool SdlEventSource::handleControllerButton(const SDL_Event&, Common::Event&, bool)’:
backends/events/sdl/sdl-events.cpp:1194:33: warning: comparison is always false due to limited range of data type [-Wtype-limits]
if (event.joystick.button == -1)
Quote of code segment;
`event.joystick.button = mapSDLControllerButtonToOSystem(ev.cbutton.button);`
`if (event.joystick.button == -1)
return false;`
`	return true;`
As comparison will always fail as joystick.button is of type byte (unsigned char), it can also return true with invalid number 255 as the joystick.button.
This happens when `mapSDLControllerButtonToOSystem()` can not find a button mapping, as it returns -1 in this case.
Simplest …

SDL: Fix compiler warning and joystick handling

---

graphics/managed_surface.cpp

Should be fairly self-explanatory, just some copy-paste errors in ManagedSurface. PRing in case something was relying on them (it only seems to be called by macgui).

GRAPHICS: Fix ManagedSurface transBlitFrom bugs

---

engines/made/made.cpp

Use of this variable was removed previously in commit 9ba6b7.
Removes the following compiler warning:
> engines/made/made.cpp: In constructor ‘Made::MadeEngine::MadeEngine(OSystem*, const Made::MadeGameDescription*)’:
engines/made/made.cpp:59:22: warning: unused variable ‘g’ [-Wunused-variable]
const GameSettings *g;

MADE: Remove unused variable

---

common/language.cpp
common/language.h
engines/wintermute/base/base_file_manager.cpp
engines/wintermute/base/base_file_manager.h
engines/wintermute/base/base_game.cpp
engines/wintermute/base/base_game.h
engines/wintermute/base/base_scriptable.h
engines/wintermute/base/file/base_savefile_manager_file.cpp
engines/wintermute/base/file/base_savefile_manager_file.h
engines/wintermute/base/scriptables/script_engine.cpp
engines/wintermute/base/scriptables/script_ext_directory.cpp
engines/wintermute/base/scriptables/script_ext_directory.h
engines/wintermute/base/scriptables/script_ext_file.cpp
engines/wintermute/detection_tables.h
engines/wintermute/module.mk
engines/wintermute/persistent.cpp

COMMON changes:
1. Add Turkish to language table
2. Add createDirectory() method to Common::FSNode
WINTERMUTE changes:
1. Add detection for all 12 languages that Hamlet supports (featuring Turkish, that never had ScummVM-playable games before). Hamlet does not use True Type Fonts, so this works allright.
2. Implement File and Directory methods required for Hamlet autosave code (see details in commit messages)
Hamlet is now fully completable with ScummVM.

WINTERMUTE: Improve Hamlet game support

---

engines/scumm/imuse/drivers/amiga.cpp

Class SoundChannel_Amiga has a function note() and function noteOn() has a parameter named note. This causes the following compiler warning:
> engines/scumm/imuse/drivers/amiga.cpp:` In member function ‘void Scumm::SoundChannel_Amiga::noteOn(byte, byte, byte, int8, int16)’:
engines/scumm/imuse/drivers/amiga.cpp:251:102: warning: declaration of ‘note’ shadows a member of 'this' [-Wshadow]
void SoundChannel_Amiga::noteOn(byte note, byte volume, byte program, int8 transpose, int16 pitchBend) {
As function note() is just a getter for private member _note and it is only used once,
I renamed it to getNote().
Renaming the function parameter note would also be possible, but this parameter is used more, and then maybe parameter note of function noteOff() should also be renamed to keep them …

SCUMM: (iMUSE/Amiga) - Fix compiler warning

---

engines/bladerunner/subtitles.cpp

It was previously only being deleted when the subtitles file was found.

BLADERUNNER: Delete subtitles temporary variable

---

engines/wintermute/detection_tables.h

This sets exact WME 1.x versions for remeaining Carol Reed series games.
* Carol Reed 4 EN is using WME 1.7.2, like Carol Reed 4 EN Demo, unlike Carol Reed 4 RU.
* Carol Reed 12+ are all using WME 1.9.3
Thanks to Albadross for collecting those versions:
https://bugs.scummvm.org/ticket/10863

WINTERMUTE: Update Carol Reed series engine versions

---

engines/composer/graphics.cpp

Don't try to run a NULL animation. This fixes a segmentation
fault in Gregory and the Hot Air Balloon that sometimes occurs
when making sundaes.

COMPOSER: Don't crash when skipping invalid animations

---

engines/sci/engine/kgraphics.cpp
engines/sci/engine/state.cpp
engines/sci/engine/state.h
engines/sci/graphics/frameout.cpp
engines/sci/graphics/portrait.cpp
engines/sci/graphics/screen.cpp
engines/sci/graphics/transitions.cpp

This implements kWait's full behavior as in SSCI. This fixes PQ3 bug #11020 where ScummVM adds a half-second delay before every message when a character's portrait is displayed.
kWait is currently implemented as a simple sleep for the specified ticks, but SSCI factors in the last time kWait was called, and doesn't necessarily sleep at all. The specified ticks is the maximum to sleep for. If that many ticks haven't yet elapsed since kWait was last called then that difference is the amount to sleep for.
PQ3 calls kWait 30 before displaying a message after a portrait, and so in the original this would only pause if kWait had been called within the last half a second, which usually wasn't the case. (Script 0, exported function 16)
kWait's work is done in EngineState:wait() which was also …

SCI: Implement full kWait behavior

---

engines/sci/graphics/picture.cpp

This fixes kDrawPic's palette validation, fixing Camelot bug #11024.
Camelot calls kDrawPic 112 2 1 4 in the aqueduct to paint a black screen, but four is an invalid palette number.
GfxPicture::drawVectorData validates _EGApaletteNo by resetting it to zero if it's greater than three, the max legal value, but it does this after _EGApaletteNo has already been used to read from the array EGApalettes and set the pointer *EGApalette, and it doesn't reset the pointer, so it continues to read out of bounds values.
Visual Studio debug builds expose this, causing the pic to be drawn pink instead of black.

SCI: Fix kDrawPic palette validation

---

engines/composer/composer.cpp

This fixes Gregory and the Hot Air Balloon. See bug #11021.
This is just a quick and lazy fix. I have not looked into the underlying reason 
why the game tries to unload a library which isn't loaded in the first place,
but making it a warning does not seem to have any adverse effects.

COMPOSER: Make unload library error a warning

---

engines/wintermute/base/base_file_manager.cpp
engines/wintermute/detection_tables.h

Ooops. Latest refactoring of those if/else blocks was wrong, as a result
Reversion 1&2 ignored all the xlanguage packages. Fixed.

WINTERMUTE: Fix language selection regression bug for Reversion

---

engines/wintermute/detection_tables.h

NOTE: This is a 2.5D game that is out of ScummVM scope
Developer's Download page states that there are EN/RU/IT versions:
http://reptilesquest.000webhostapp.com/index.php?page=5
However, rq_demo_beta25_multilang.exe allows to select only EN/RU.
italian.dcp can be extracted from rq_demo_beta25_multilang.exe using any
tool for Inno Setup installer.

WINTERMUTE: Add detection for Italian demo of On the Tracks of Dinosaurs

---

common/util.cpp
common/util.h
engines/sword25/util/lua/llex.cpp
engines/sword25/util/lua/lstrlib.cpp

Note that this PR conflicts with PR #1566.

 SWORD25: LUA: Remove direct use of ctype.h functions

---

engines/sci/detection_tables.h

This special debug build was salvaged by Clint Basinger ("LGR") from an IBM PCjr that was previously owned by Ken Williams from Sierra On-Line.
The story of this particular PC is pretty wild. Clint got it from a PC warehouse/thrift store and the most interesting stuff at the beginning was the pretty rare hard drive expansion. Later it was revealed that the PC was previously owned by Sierra On-Line. Later Ken Williams confirmed that the PC was previously owned by himself.
Clint managed to copy the files from the (almost dead) hard drive that only occasionally even started and uploaded them to archive.org.
Full video: https://www.youtube.com/watch?v=Z-VBITW94zI
Screenshots taken with ScummVM:

SCI: Add detection entry for debug version of Codename: Iceman

---

engines/queen/input.cpp
engines/queen/talk.cpp

DOS version of the game allows skip talking on right mouse click,
this commit adds support for this functionality.
Also, when talking the game ignores click on the close button (of the window)
until dialogue is ended. so it applies skip talk on this event as well.
old behaviour:
right click while talking -> wait for talking to end -> do action as if there was right click now
(if meanwhile mouse was moved, it clicks somewhere else).
new behaviour (matches DOS executable):
right click while talking -> skip dialogue -> do action because there was right click now.
Thanks
EDIT:
add skip talk to left click as well to match DOS executable

QUEEN: skip talk on right click

---

graphics/font.cpp
graphics/font.h

The new arguments are optional. The lines segments will be close to the same width.
The algorithm is similar to the one we had for Blade Runner but not exactly the same, since that one would wrap a line at a white space after the theoretical split point (quotient of full line text width divided by target lines number)

COMMON: Support text wrapping with even width line segments

---

gui/ThemeEngine.cpp
gui/Tooltip.cpp
gui/widgets/edittext.cpp
gui/widgets/list.cpp
gui/widgets/scrollcontainer.cpp
gui/widgets/tab.cpp

I've been making a custom theme based on Modern Remastered these couple of days (I call it Midnight theme). While I was at it, I locally fixed some things in GUI. Well, some changes are not really fixes, but edits that I thought look better.
These **are not** changes for my theme only, but sometimes they are better illustrated with my theme (scrollbars, for example). Below are pics comparing what was before the fixes and after these in both my theme and Modern Remastered (click to view in full size).
- list widget scrollbar is not cropped on the right now:
.
- scrollbar buttons now take as much space as they should, not overlapping with scrollbar handle:
(illustrated in Midnight theme only, because Modern Remastered does not have any background or borders in scrollbar buttons, so you …

GUI: Minor fixes (scrollbars, tooltips, tabs, EditText)

---

devtools/create_project/msbuild.cpp
devtools/create_project/visualstudio.cpp
dists/scummvm.rc
dists/win32/scummvm.exe.manifest

DISTS: Fix OpenGL renderer for MSYS2/Mingw(64 or 32)
The issue pertains to MSYS2 adding a default manifest file (default-manifest.o) to the executable
The bug is for PC systems with GPU drivers that were not properly supported for Windows 10 systems, like Intel HD Graphics series 1rst and 2nd generations. In those systems, launching a game in ScummVM (built with MSYS2/Mingw) with the OpenGL renderer would cauase the game screen to be a white blank image, and various warnings would be output to the console eg.
"WARNING: GL ERROR: GL_INVALID_ENUM on glTexSubImage2D(0x0DE1, 0, 0, area.top, src.w, area.height(), _glFormat, _glType, src.gere.cpp:167)!"
This was due to MSYS2/Mingw builds trying to load the (poorly supported) GPU driver, while "advertising" support for Windows 10 in their …

DISTS: Fix OpenGL renderer for builds with MSYS2

---

backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/texture.cpp
backends/graphics/opengl/texture.h

OpenGL ES only supports RGBA8888 on big endian systems, which means that any games requiring a 32-bit colour mode will fail to start when using OpenGL ES on little endian systems.

OPENGL: Support RGBA8888 swapped textures when using OpenGL ES

---

backends/fs/abstract-fs.h
backends/fs/amigaos4/amigaos4-fs.cpp
backends/fs/amigaos4/amigaos4-fs.h
backends/fs/chroot/chroot-fs.cpp
backends/fs/chroot/chroot-fs.h
backends/fs/ds/ds-fs.cpp
backends/fs/ds/ds-fs.h
backends/fs/n64/n64-fs.cpp
backends/fs/n64/n64-fs.h
backends/fs/posix/posix-fs.cpp
backends/fs/posix/posix-fs.h
backends/fs/ps2/ps2-fs.cpp
backends/fs/ps2/ps2-fs.h
backends/fs/psp/psp-fs.cpp
backends/fs/psp/psp-fs.h
backends/fs/riscos/riscos-fs.cpp
backends/fs/riscos/riscos-fs.h
backends/fs/symbian/symbian-fs.cpp
backends/fs/symbian/symbian-fs.h
backends/fs/wii/wii-fs.cpp
backends/fs/wii/wii-fs.h
backends/fs/windows/windows-fs.cpp
backends/fs/windows/windows-fs.h
backends/networking/sdl_net/handlers/createdirectoryhandler.cpp
backends/platform/dc/dc-fs.cpp
backends/platform/tizen/fs.cpp
backends/platform/tizen/fs.h
common/file.cpp

This PR includes only the changes from PR #1727 related to AbstractFSNode. Merging this PR should allow implementations of `createDirectory()` to be worked on independently of PR #1727.

 BACKENDS: Rename and simplify AbstractFSNode::create()

---

engines/wintermute/detection_tables.h

WINTERMUTE: Fix detection for Chinese reversion2
Current "data.dcp" infromation is from reversion1 and not from reversion2 game... surely a C&P mistake

WINTERMUTE: Fix detection for Chinese reversion2

---

devtools/create_xeen/constants.cpp

This fixes a small typo in the `create_xeen` tool.

XEEN: Fix typo

---

backends/graphics/dinguxsdl/dinguxsdl-graphics.cpp
backends/graphics/dinguxsdl/dinguxsdl-graphics.h
backends/graphics/gph/gph-graphics.cpp
backends/graphics/gph/gph-graphics.h
backends/graphics/linuxmotosdl/linuxmotosdl-graphics.cpp
backends/graphics/linuxmotosdl/linuxmotosdl-graphics.h
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h

The implementation of `setGraphicsModeIntern()` in the GPH, Dingux and LinuxMoto backends are not quite identical to the base SDL backend, however the only differences are the call to `updateShaders()` (which does nothing on platforms other than the PS Vita) and the code for setting `_scalerType` (which shouldn't make a difference since `s_gfxModeSwitchTable` doesn't contain any reference to `GFX_HALF`). As such, this change should be harmless.

SDL: Move selecting the required ScalerProc into a separate function

---

engines/sci/graphics/screen_item32.cpp

This fixes an off by one error in our SCI32 mirrored pic drawing. This can be seen in any room with style property bit $0400. The pic is drawn one coordinate to the left of where it should be and leaves a line of garbage on the right or left edge of the screen, depending on the compiler.
This fixes at least QFG4, which has many mirrored rooms such as 551, and LSL6 Hi Res rooms 305, 640, and 680.
Confirmed in disassembly. Fixes bug #10748

SCI32: Fix Mirrored Pic Drawing

---

engines/sci/engine/message.cpp

This fixes SQ4CD's hintbook layout, which is currently drawn incorrectly, due to parsing message text as if it were escaped hex codes. SQ4CD's interpreter doesn't have this feature. Converting this text to hex codes, and then applying the buggy hex conversion that appeared in later interpreters, causes newlines to appear and the text sizing to be off.,
Fixes #11070

SCI: Fix SQ4CD hintbook text layout

---

engines/sci/sound/soundcmd.cpp

Sound:vol is updated when updating cues starting in SCI_VERSION_1_MIDDLE.
Fixes bug #10244. SQ4 localized floppy versions depend on this when getting
in the orange ship, they fade music and wait for the volume to reach zero.
Confirmed against asm that this is not in SQ4 floppy (early) but is in
LSL1VGA (middle) and SQ4 localized floppies and SQ4CD (late).

SCI: Update Sound:vol in processUpdateCues

---

engines/tsage/detection_tables.h

TSAGE: Removed "pirated" flag from Spanish fanmade translation
I have been talking to the translation team... they didn't mean to distribute any "pirate" version.
At first, they just released the modified files and didn't notice they were releasing all the needed files to run the game... the same way they have done with all other translations in their webpage (http://www.pakolmo.galeon.com), but this time with a fatal result. They have presented their apologies for that
Now they have changed the downladed file to a patch requiring the original game to be applied.
http://www.pakolmo.galeon.com/RingWorld2.htm

TSAGE: Removed "pirated" flag from Spanish fanmade translation

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/windowed.h

This simple PR adds a fourth stretch mode to the SDL2 backend, called "Fit to window (4:3)". It fits the screen to the window similar to the existing "Fit to window" stretch mode, but enforces a 4:3 aspect ratio.
Using this stretch mode and unticking the "aspect ratio correction" does hardware aspect ratio correction on all SDL2 platforms, making use of the SDL2 scaler. This is similar to what has always been done on Vita.
This method is faster and often better looking than the software aspect ratio correction that can be enabled with the checkbox.
One downside compared to checking the "aspect ratio correction" tick mark is that the menu and user interface will also be hardware-scaled just like the game screen. This means the menu font, mouse pointer and buttons will look slightly …

BACKENDS: add Fit to window (4:3) stretch mode to SDL2 backend

---

backends/events/psp2sdl/psp2sdl-events.cpp
backends/graphics/psp2sdl/psp2sdl-graphics.cpp
backends/graphics/psp2sdl/psp2sdl-graphics.h

This PR changes the Vita graphics manager so that the AR correction and game screen texture scaling is done similarly to other surfaceSDL platforms. However, several issues came to light concerning aspect ratio correction now that Vita does it similarly as other platforms:
- AR doesn't work at all in Dreamweb when using 2x or 1x rendering. I observe this also on latest MacOS nightly. It works using OpenGL on MacOS though.
- AR works just fine in the main menu, and seems to work fine in Monkey Island on first glance. On closer inspection, enabling AR causes dirty rect gfx glitches in Monkey Island when the mouse is moved across the screen (warped) with the analog stick or touch input. When the cursor is close to the top edge of the screen, also significant slowdown occurs, not just …

VITA: Use activeArea rectangle also on Vita

---

backends/graphics/dinguxsdl/dinguxsdl-graphics.cpp
backends/graphics/gph/gph-graphics.cpp
backends/graphics/linuxmotosdl/linuxmotosdl-graphics.cpp
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/opengl/opengl-graphics.h
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h
backends/graphics/wincesdl/wincesdl-graphics.cpp
backends/graphics/windowed.h

Note that the Vita backend appears to ignore the active DisplayArea, meaning that screen shaking is unlikely to work on the Vita with this PR.

BACKENDS: Handle screen shaking in WindowedGraphicsManager

---

common/ini-file.cpp

Ini files with structure like this can't be read. This pull request fixes this. 
[section]
Key1 = Value1
Key2
Key3
Key4 = Value2

COMMON: fixed reading ini files which have not value for key

---

engines/sci/graphics/cursor.cpp
graphics/maccursor.cpp
graphics/maccursor.h

This adds limited support for Macintosh monochrome cursors that have inverted pixels. Currently ScummvM treats these as transparent and so FPFP and KQ6 are missing cursor features, bug #7050.
Mac monochrome cursors have a 1 bit per pixel image and mask. Bits that are set in the image but not the mask are a fourth color other than black, white, or transparent: the underlying target pixel would be inverted. The knob on the classic mac watch cursor is an example of this:
The Waiting cursor from FPFP also does this:
This PR does not add inversion. That would change the cursor interface layers, and as I understand it, require implementing inversion in each backend. That's a lot of files to touch to make a handful of mac cursors look better and I wouldn't be able to test most of those changes. …

GRAPHICS: Display Mac monochrome cursor inverted pixels

---

audio/fmopl.cpp
audio/opl2lpt.cpp

The OPL3LPT is like the OPL2LPT with an OPL3 chip.  Add OPL3 support to the existing OPL2LPT driver.
There is no auto-detection of OPL3 capability. The user is required to explicitly select OPL3LPT as their OPL device.
Tested with Sam & Max Hit the Road.

AUDIO: (opl2lpt) add OPL3LPT support

---

backends/platform/sdl/sdl.cpp

With some older versions of SDL1, the SDL_iconv_string takes char * instead of const char * as it's argument. This should fix the build issue with gp2xwiz.

SDL: Use a non-const string for SDL_iconv_string

---

common/encoding.h
configure

This should fix issues with building on the ds and osx_intel.
I tryed to include config.h, so I have the USE_ICONV define available and can include iconv.h before including the scummsys.h, thinking, that forbidden.h wouldn't allow me to include the iconv.h. This wasn't necessary and it broke the ds build, so I don't do that anymore.
I looked at how the ResidualVM works with iconv when implementing Encoding. They use a define ICONV_USES_CONST to determine the signature of iconv() function. I thought this is defined in iconv.h and used it. Now I noticed, they test this in their configure and define it by themselves. I added this test and define to configure. This should fix the osx_intel build.

Common: Fix Encoding building

---

backends/cloud/box/boxlistdirectorybyidrequest.cpp
backends/cloud/box/boxtokenrefresher.cpp
backends/cloud/downloadrequest.cpp
backends/cloud/dropbox/dropboxcreatedirectoryrequest.cpp
backends/cloud/dropbox/dropboxinforequest.cpp
backends/cloud/dropbox/dropboxlistdirectoryrequest.cpp
backends/cloud/dropbox/dropboxuploadrequest.cpp
backends/cloud/googledrive/googledrivelistdirectorybyidrequest.cpp
backends/cloud/googledrive/googledrivetokenrefresher.cpp
backends/cloud/googledrive/googledriveuploadrequest.cpp
backends/cloud/onedrive/onedrivecreatedirectoryrequest.cpp
backends/cloud/onedrive/onedrivelistdirectoryrequest.cpp
backends/cloud/onedrive/onedrivetokenrefresher.cpp
backends/cloud/onedrive/onedriveuploadrequest.cpp
backends/cloud/savessyncrequest.cpp
backends/networking/curl/curlrequest.cpp
backends/networking/curl/networkreadstream.cpp
backends/networking/curl/networkreadstream.h
backends/networking/curl/request.cpp
backends/networking/curl/request.h

wolfgangr had an issue with Google Drive he told me on IRC. We spent a couple hours debugging and found out that his machine (Debian x64, though it's probably not the reason) gets HTTP headers in lowercase (while I always seen them coming in titlecase). So, as Google Drive file uploading routine in ScummVM expected header in titlecase, it didn't work in his environment. Empty error messages along with 200 OK HTTP code were not helping too.
So, I've added a new method to handle HTTP headers case-insensitively (more or less matching RFC) and updated all places that had empty error messages to provide at least some information.

CLOUD: Treat HTTP headers names case-insensitively and add more verbose error messages

---

common/encoding.cpp
common/encoding.h

Move #include<iconv.h> from common/encoding.h to
common/encoding.cpp and change the methods accordingly.
This resulted in not saving the iconvHandle if using the
"non-static" version of conversion, but it simplified the code
and hopefuly resolved issues with forbidden symbols on some
platforms.
I tested this on arch linux (but there was no issue with forbidden
symbols before) and on Windows with MinGW and MinGW-w64
(this had the issue and now the issue is gone). Unfortunately
I cannot test this with MacOS.

COMMON: Don't include iconv.h in common/encoding.h

---

backends/fs/psp/psp-fs.cpp

Originally from PR #1727. This change has not been tested.

PSP: Implement AbstractFSNode::createDirectory()

---

engines/xeen/sprites.cpp

Fixed a compiler warning by renaming the SpriteDrawer instance name from draw to drawer.
Compiler warning was:
> engines/xeen/sprites.cpp:137:17: warning: declaration of ‘draw’ shadows a member of 'this' [-Wshadow]

XEEN: Fix compiler warning

---

backends/platform/sdl/win32/win32.h
common/encoding.h

Currently encoding.h includes win32.h to expose `switchEndian` to the backend. This has the nasty side effect of exposing poor defenseless engines to the cthulhuian horrors of Win32. In this case, Testbed doesn't compile on MSVC because Win32 requires language extensions.
I replaced the include with just making `switchEndian` public, since it's static anyways, so a friend class seems excessive. @vyzigold let me know if this is ok.

COMMON: Don't include win32.h in common/encoding.h

---

engines/bladerunner/framelimiter.cpp

Changed variable name from `time` to `waittime`.
Fixes the following compiler warning:
> engines/bladerunner/framelimiter.cpp: In member function ‘void BladeRunner::Framelimiter::wait()’:
engines/bladerunner/framelimiter.cpp:58:10: warning: declaration of ‘wait’ shadows a member of 'this' [-Wshadow]
uint32 wait = _speedLimitMs - frameDuration;
^

BLADERUNNER: Fix compiler warning

---

backends/platform/sdl/sdl.cpp
backends/text-to-speech/windows/windows-text-to-speech.cpp
common/encoding.cpp
common/encoding.h

This pull request resolves crashing when compiling with msvc and using text to speech. The crashes were actualy caused by Common::Encoding, that returned a converted string from SDL_iconv_string(), which couldn't be freed by free(), while strings returned by Common::Encoding should be freed by free().
This also fixes the freezing caused by waiting on a thread while trying to stop speech (the freeze could last up to multiple seconds). There still is a barely noticable lag when using TTS in the GUI and moving fast with the cursor between multiple GUI widgets and thus starting and stoping multiple speeches too quickly. This is caused by a call to ISpVoice->Speak() inside the stop() method. I haven't found a better solution to stopping the speech yet, but the lag shouldn't be noticable with …

TTS: Fix crashing and freezing when compiled with msvc

---

common/hashmap.h

GCC emits "warning: type qualifiers ignored on cast result type" when
some types are used for HashMap because of the const modifier.
This applies especially to pointer-to-member-functions.
The const there is not really useful as it only prevents unfortunate
object editions.

BUILD: Fix GCC bogus warning by removing const

---

backends/platform/ios7/ios7_osys_main.cpp

When quitting the ios7 backend, either through the launcher's Quit button or through a game's Quit function, the process always hangs instead of exiting. From the launcher I get a black screen, in the SCI games it hangs on the game frame. At that point I have to force kill the process.
I don't know why it isn't exiting cleanly, but the existing TODO comments suggests this wasn't quite finished. This has always happened to me on my non-jailbroken iphone se throughout its major ios versions. Seems like throwing an exit(0) at it is a good fix until the root cause is discovered, if it even matters. iOS7_main() finishes but UIApplicationMain() isn't returning, and there's no further code after that.
I have an iphone 4 running ios4 with the old 1.5 scummvm on it, and it exited cleanly, so I …

IOS: Call exit(0) when exiting to prevent hanging

---

engines/bladerunner/color.h

This fixes a crash on RISC OS due to the size of the structure being padded to a multiple of 4 bytes, and `ScreenEffects::readVqa()` assuming the structure size is 3 when reading the palette data.

BLADERUNNER: Ensure the Color256 struct is correctly packed

---

backends/fs/windows/windows-fs.cpp

This fixes a regression from commit aca627b.

WIN32: Fix getting the parent directory of non-existant file nodes

---

backends/saves/default/default-saves.cpp
common/file.cpp
common/fs.cpp
common/fs.h

Fixing this is a lot more complicated than I had anticipated, so for now it's best to just revert this commit so that cloud saves work again.

Revert "COMMON: Implement FSNode::createDirectoryRecursive()"

---

backends/fs/windows/windows-fs.cpp

As this commit didn't fix anything, I think we should revert it just in case, and keep this assert().

Revert "WIN32: Fix getting the parent directory of non-existant file nodes"

---

configure

The old test would only detect iconv if it was part of a separate library, and would fail to detect iconv when it's included in the main C library.

CONFIGURE: Replace the iconv test with the one from ResidualVM

---

devtools/create_project/scripts/revision.vbs

That avoids superfluous recompilation and linkage of project when nothing
has changed.

MSVC: Don't overwrite version.h if it hasn't changed

---

configure

This is useful when the libpng.a symlink isn't installed, which is the case with the dockerized buildbot from https://github.com/lephilousophe/dockerized-bb

CONFIGURE: Allow using pkg-config to detect libpng

---

backends/networking/sdl_net/getclienthandler.cpp
backends/networking/sdl_net/handlers/createdirectoryhandler.cpp
backends/networking/sdl_net/handlers/downloadfilehandler.cpp
backends/networking/sdl_net/handlers/filesajaxpagehandler.cpp
backends/networking/sdl_net/handlers/filespagehandler.cpp
backends/networking/sdl_net/handlers/indexpagehandler.cpp
backends/networking/sdl_net/handlers/listajaxhandler.cpp
backends/networking/sdl_net/handlers/uploadfilehandler.cpp
backends/networking/sdl_net/handlerutils.cpp
backends/networking/sdl_net/handlerutils.h
backends/networking/sdl_net/uploadfileclienthandler.cpp
common/json.cpp
common/json.h

Translating the text for the local web server is not working correctly when using non-ASCII characters as the html pages expect UTF-8. In commit 0c605e3 I played with the idea of injecting the current GUI encoding into the html pages instead of specifying utf-8. However I think that it might be better instead to keep utf-8 encoding for the html pages and convert all the text to utf-8, as it might work better for file lists. So this is what I am proposing in this PR.
I have however an issue with the AJAX version of the file list: I cannot get it to properly handle UTF-8. I am not familiar with AJAX, so if anybody has an idea how to fix this, please let me know.
Here is what it looks like with this PR when displaying a page in French using the AJAX handler:
And here is what it looks like …

NETWORKING: Convert translation results to UTF-8 for local webserver pages

---

backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/wincesdl/wincesdl-graphics.cpp

The previous check would incorrectly treat BGR555 as a 565 mode. Previously, scalers would produce incorrect results on RISC OS as a result, however the issue went away for me due to an SDL change adding support for the additional pixel formats introduced in RISC OS 5.21, however the issue is still likely to still be present for users of older RISC OS versions. I haven't been able to personally check this on such a system, though.

SURFACESDL: Properly distinguish between 555 and 565 modes

---

configure

I would have used the linux entry, but -ldl does not exist on amigaos4 and i still need -use-dyn-ld

CONFIGURE: Add amigaos to the plugins family

---

engines/engine.cpp

Originally from libretro/scummvm#113.
> The core has always had an infuriating little bug - if you try to open the main ScummVM menu while the initial splash screen is shown, it generates a segfault. This is very easy to trigger - if you are continuing a game and just want to load your last save, it is natural to try and open the menu as soon as the game itself loads... which causes it to crash.
>
> I had a look, and it seems there's some stupidity in the splash screen code. While the screen is shown, it sits in a wait loop polling for events - which I imagine was intended to allow a quick response if the user were to 'exit' (i.e. close the window in ScummVM standalone). The problem is that this wait loop occurs at a very early stage of initialisation, when most of the game engines …

ENGINES: Disable event polling while splash screen is shown

---

engines/queen/queen.cpp
engines/queen/queen.h

Originally from libretro/scummvm#114.
> [The game engine for 'Flight of the Amazon Queen'] allows you to load a previous save before the game is properly initialised. At best, this leads to undefined behaviour. Most of the time it causes a segfault.

QUEEN: Disable load/save until game is properly initialised

---

engines/queen/sound.cpp

Originally from libretro/scummvm#114.
> If you try to close the core while a dialogue is in progress, it gets stuck in an infinite loop and hangs RetroArch indefinitely.

QUEEN: Prevent hang when closing core during dialog

---

engines/illusions/duckman/illusions_duckman.cpp
engines/illusions/sound.cpp
engines/illusions/sound.h

The sfx in this scene is from the global sfx resource which doesn't get unloaded on scene change. I've added some logic to stop looping sfx when changing scenes.

ILLUSIONS: DUCKMAN: Fix endless SFX bug #11161

---

devtools/scumm-md5.txt

Commit 0899ecc98760bba79bccc2026bcfa44542d46d8f directly hacks into
engines/scumm/scumm-md5.h which is normally generated by
devtools/md5table using devtools/scumm-md5.txt as input.
This back-ports the scumm-md5.h changes in the scumm-md5.txt

SCUMM: Backport scumm-md5.h changes into scumm-md5.txt

---

common/math.h
engines/bladerunner/rect_float.h
engines/bladerunner/slice_renderer.cpp

This is a follow-up to PR #1295.

BLADERUNNER: Remove use of C99 math functions

---

graphics/VectorRenderer.cpp
graphics/VectorRenderer.h
graphics/VectorRendererSpec.cpp
graphics/VectorRendererSpec.h
gui/ThemeEngine.cpp
gui/ThemeEngine.h
gui/dialog.cpp
gui/widget.cpp

Selecting whether a clipping variant of a draw call needs to be used is no longer the responsibility to the caller.
Also fix some of the draw calls to (better) apply the clipping rect.

GRAPHICS: Vector renderer clipping rect related cleanups

---

engines/hdb/detection.cpp
engines/supernova/detection.cpp

The two new engines Hyperspace Delivery Boy! and Mission Supernova display their copyright "sign" in lowercase, while every other engine is upper-case.

JANITORIAL: Keep copyright "sign" upper-case in "About"

---

backends/fs/amigaos4/amigaos4-fs.cpp

We need to explicitely open dos.library and it's IDOS interface.
Otherwise we will hit an IDOS NULL pointer after compiling a shared binary with (shared) plugins.
The hit will happen on loading a game from any engine, if more than one engine/plugin is available.

AMIGAOS4: Fix NULL pointer access on using plugins

---

backends/fs/wii/wii-fs-factory.cpp
backends/platform/wii/main.cpp
backends/platform/wii/osystem.cpp
backends/plugins/elf/elf32.h
backends/plugins/elf/ppc-loader.cpp
configure

This pull request lets ScummVM compile and run with the latest version of devkitPPC.
There are various fixes :
- paths to portlibs directory are added as it's where 3rd party libraries are expected to be installed
- -fpermissive is needed because reset_cb hasn't the expected signature. The proper way would be to fix the callback signature but I don't know how it would behave with an old toolchain.
- time.h is included in recent versions of network.h and must be excluded from forbidden symbols list
- Recent versions of GCC emits NONE relocations which prevents plugins to be loaded. Adding handling of them to elf-loader code make them work (and as it's a no-op it's easy to add).
- Last commit was an attempt to fix a bug which ended up to be in libgxflux. It destroys everything (and close …

WII: Fix compilation and runtime with latest version of devkitPPC

---

backends/text-to-speech/windows/sphelper-scummvm.h
backends/text-to-speech/windows/windows-text-to-speech.cpp
configure

This PR gets Text To Speech working in default Mingw-w64 environments.
- Removes reference to sapiddk.h which isn't used and isn't in Mingw-w64
- Defines guids whose symbols are missing from Mingw-w64
- Restores TTS detection to configure script
With these changes, TTS works out of the box in Mingw-w64 environments. Mingw32 doesn't include speech api headers or libraries and so configure still correctly detects that TTS is unavailable there.

TTS: Enable in Mingw-w64 builds

---

engines/hdb/sound.cpp
engines/hdb/sound.h

This moves a bunch of music playback code into the Song class, which makes it easy to DRY out all the repeated code.
Specifically, the code now works with "this" Song and not "song1" or "song2". Additionally, the decoder setup code is factored out to a separate member function, eliminating some quadruple code duplicates.
As a quick bonus, I fixed [bug #11194](https://bugs.scummvm.org/ticket/11194).

HDB: Clean up music playback code

---

engines/mohawk/cursors.cpp
engines/mohawk/cursors.h

On 3DS builds of ScummVM, attempting to start Riven results in an instant crash due to the way cursor preloading is coded. This commit resolves that issue.

MOHAWK: RIVEN: Modify cursor preloading to resolve crashing on 3DS

---

backends/fs/amigaos4/amigaos4-fs.cpp
backends/platform/sdl/amigaos/amigaos.mk

I have a request to make, since i can't do it on my own.
Would someone please be so nice and move
scummvm_drawer.info
scummvm.info
from icons/
to
dists/amiga
Otherwise the amigaos.mk changes will break due to the wrong path.
Thank you very much
Reason is, that everyone with it's own platform (except windows if i see that right?) dists has their icons in their own subdir and i think it looks much more cleaner that way too. (Also amiga has it´s dists subdir aswell)

AMIGAOS4: Further update amigaos.mk and fix shared plugins workaround

---

backends/platform/sdl/amigaos/amigaos.mk

OK, now i´m embarrassed, this obviously won't work :-( 
I was testing
`strip plugins/*`
which produces broken plugins for me and forgot to get rid of the flag.
Doing the stripping locally for now.
Sorry again

AMIGAOS4: amigaos.mk - Fix cp command

---

gui/widgets/tab.cpp

The crash happens on all platforms, but is very easy to trigger by accident on Android.

GUI: Fix crash when clicking and dragging a tab widget

---

gui/ThemeLayout.cpp

* Testing if a widget can be centered was ignoring the padding.
* Only resize a layout based on its content if it was not explicitly
sized by its parent. Fixes the logo causing incorrect layout
computations when the window width is lower than the image width.
Before:
After:
There are very obvious remaining issues (I have a fix for the wrapping logo planned for another PR), but at least the layout is correct.

GUI: Fix launcher layout for small widths

---

configure

When building scummvm with TTS support for the Linux platform, the final linking of the scummvm binary fails since libpthread is not linked:
<pre>
g++  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fuse-ld=gold -Wl,--gdb-index -Wl,-export-dynamic -Wl,-whole-archive backends/platform/sdl/sdl.o backends/platform/sdl/sdl-window.o backends/platform/sdl/posix/posix-main.o backends/platform/sdl/posix/posix.o base/libbase.a gui/libgui.a backends/libbackends.a engines/libengines.a video/libvideo.a image/libimage.a graphics/libgraphics.a audio/libaudio.a common/libcommon.a audio/softsynth/mt32/libmt32.a -Wl,-no-whole-archive  -lSDL2 -ldl -lm  -lvorbisfile -lvorbis  -lFLAC  -logg  -lmad  -lasound  -ljpeg -lpng16 -lz   -ltheoradec -lz  -lmpeg2 -lcurl …

TTS: Link libpthread explicitly on Linux platform

---

backends/platform/ios7/ios7_scummvm_view_controller.mm

This makes the annoying white line at the bottom of the screen go away on newer (home button-less) iPhones.
See also https://developer.apple.com/documentation/uikit/uiviewcontroller/2887510-prefershomeindicatorautohidden
I tested this on iOS10 to make sure it's backwards compatible.

IOS7: enable home indicator auto-hide on iPhone X and up

---

backends/platform/3ds/3ds.mk

Set 'scummvm.romfs' to be removed in cleaning, as it is a byproduct of "make scummvm.cia".

3DS: Set 'scummvm.romfs' to be removed by 3ds_clean in 3ds.mk

---

backends/platform/3ds/3ds.mk
backends/platform/3ds/README.md
backends/platform/3ds/app/scummvm.rsf

This patch alters the way the .cia is build. It removes the need for 3dstool.
Instead of first generating a .romfs file using 3dstool, let makerom generate the romfs while building the .cia.

3DS: Remove 3dstool dependency

---

common/archive.cpp
common/archive.h
common/fs.cpp
common/fs.h

This lets engine mute warnings about name clashes when there are useless
for its case. This will be used by Versailles as the tree has
directories with the same name at various places.
Files are duplicated too in different directories but are identical.
I removed the mutable flag on _depth and _flat as they shouldn't have it. Their change on a const object would change behaviour of the object.

COMMON: Add ignoreClashes flag to SearchSet and FSDirectory

---

backends/networking/curl/connectionmanager.cpp
backends/networking/curl/connectionmanager.h
backends/networking/curl/networkreadstream.cpp
backends/networking/curl/networkreadstream.h

So that platforms where libcurl cannot access the native CA store can ship a CA bundle along with the other ScummVM support files.
Also improve libcurl error handling so warnings are issued for failed requests.

NETWORKING: Try loading the CA bundle from DATA_PATH

---

backends/module.mk
backends/networking/curl/curlrequest.cpp
backends/networking/curl/curlrequest.h
backends/networking/curl/networkreadstream.cpp
backends/networking/curl/networkreadstream.h
backends/networking/curl/request.h
backends/networking/curl/session.cpp
backends/networking/curl/session.h
backends/networking/curl/sessionrequest.cpp
backends/networking/curl/sessionrequest.h

Originally intended to be a speedup for libcurl by reusing the same handle in keep-alive connections. Turns out, libcurl automatically does that.
Anyways, this PR does some useful edits in backends/networking/curl and adds SessionRequest, which might be not only used asynchronously as before (via callbacks), but also synchronously using wait(). Session class allows to reuse these SessionRequests.

NETWORKING: Enter Session and SessionRequest

---

backends/platform/sdl/win32/win32.cpp
backends/updates/win32/win32-updates.cpp
backends/updates/win32/win32-updates.h

Currently, when WinSparkle runs the downloaded installer, ScummVM remains open and must be manually exited or else the installer will fail. This is awkward since at this point the installer has focus.
WinSparkle has callbacks to handle this, so now ScummVM will exit as soon as WinSparkle runs the downloaded installer. At this point the user has clicked the Install Update button in the WinSparkle dialog so this isn't surprising behavior.
To test this, set SCUMMVM_VERSION to "2.0.0", or patch the version fields in scummvm.rc, and use the Check Now update button. After 2.1.0 downloads click Install Update.
https://bugs.scummvm.org/ticket/10368

WIN32: Exit when WinSparkle runs installer

---

backends/platform/sdl/win32/win32.cpp
common/system.h

The current implementation of OSystem_Win32::convertEncoding causes some arrays allocated with `new []` being freed using `free()` and not `delete []`. This is an attempt to fix this.
Since I am not even able to compile the code, not being on Windows, I would appreciate if others could review and try this before this is pushed to master.
This commit also removes what appeared to be an unused variable (`wString`) and adds a sanity check as the result of `Win32::ansiToUnicode` could be null.

Fix free/delete inconsistencies in OSystem_Win32::convertEncoding

---

backends/fs/posix-drives/posix-drives-fs.cpp
backends/fs/posix-drives/posix-drives-fs.h

Parameter name isDirectory shadowed a method with same name.
The new name isDirectoryFlag has been also used elsewhere in similar situations.

POSIX: Fix compiler warning

---

backends/base-backend.cpp
backends/graphics/opengl/opengl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
common/system.h

The OpenGL graphics manager already uses `Graphics::Surface::fillRect` to implement `fillScreen`, so this changes the other backends to match.

BACKENDS: Fix using fillScreen in non-paletted screen modes

---

backends/graphics/sdl/sdl-graphics.cpp

Use Common::FSNode to test for screenshot existence instead of
SDL_RWFromFile(). SDL does different character encoding conversions
which fail on Windows when a unicode character is in the path.
Fixes bug #11118

SDL: Fix Windows screenshots with unicode paths

---

backends/cloud/storage.cpp

When using the cloud save sync features, It seems to me there are too many user interface elements, I feel a bit overwhelmed. There is a blinking overlay icon indicating network activity, OSD messages indicating success or failure, and a progress dialog when the save / load dialog is open.
With this PR, I propose removing the OSD message indicating the save sync finished successfully. For me, it breaks the experience when it appears while in-game after the engine autosaved. IMO, the overlay icon disappearing is a good enough indication that the saves synchronized.

CLOUD: Remove the saves sync finished OSD message

---

configure

Currently, --enable-release always enables updates even on unsupported platforms.
This additional check disables updates entirely if no proper sparkle implementation
is found.
Fixes #11217.
I tested this with a current Fedora installation and a mingw-w64 build and everything works as expected. Could somebody please check if it doesn't break macOS?

BUILD: Disable updates if no Sparkle implementation is available

---

engines/director/archive.cpp
engines/director/cast.cpp
engines/director/cast.h
engines/director/detection.cpp
engines/director/detection_tables.h
engines/director/frame.cpp
engines/director/images.cpp
engines/director/images.h
engines/director/lingo/lingo-bytecode.cpp
engines/director/lingo/lingo-code.cpp
engines/director/lingo/lingo-codegen.cpp
engines/director/lingo/lingo-events.cpp
engines/director/lingo/lingo-gr.cpp
engines/director/lingo/lingo-gr.y
engines/director/lingo/lingo.cpp
engines/director/lingo/lingo.h
engines/director/module.mk
engines/director/score.cpp
engines/director/score.h

This patch adds the foundations of a bytecode interpreter for Director v4 Lingo scripts, using the same execution framework as the Lingo parser. 
There's still quite a lot of work to be done, especially with respect to context management, script invocation, event callbacks, etc.

DIRECTOR: Add Lingo v4 bytecode interpreter

---

devtools/create_toon/subtitles/pakdir.py
devtools/create_toon/subtitles/submaker.py
engines/toon/font.cpp
engines/toon/font.h
engines/toon/module.mk
engines/toon/movie.cpp
engines/toon/movie.h
engines/toon/subtitles.cpp
engines/toon/subtitles.h
engines/toon/toon.cpp
engines/toon/toon.h

This allows subtitles during cutscenes in Toonstruck.
Attaching subtitles file for first part of intro cutscene - should be extracted to `MISC` directory
[209_1M.zip](https://github.com/scummvm/scummvm/files/3721733/209_1M.zip)
Subtitles rendered using the same text draw method from the game so they look consistent.
text color changes with the palette of the cutscene.
The original game does not have subtitles in cutscenes (new feature),
I also could not find a transcript of the cutscenes' texts.
so the hard work of transcribing and timing the subtitles is still ahead.
Subtitles files are stored  in custom simple format (`tss` for Toonstruck Subtitles) consists of:
index - start frame, end frame, text offset
texts - null terminated strings
subtitles files should have the same name as …

TOON: Add subtitles support for cutscenes

---

engines/sci/engine/script_patches.cpp

Fixes the error in the CD version when starting to automatically walk (then slide) down the top of the slope in room 800: https://bugs.scummvm.org/ticket/11268
I'm doing this as a PR so that the bug reporter can test it first since it replaces an existing script patch.

SCI32: Fix QFG4 error when sliding down slope

---

backends/platform/ds/arm9/source/osystem_ds.cpp
backends/platform/ds/arm9/source/osystem_ds.h
backends/platform/n64/osys_n64.h
backends/platform/n64/osys_n64_base.cpp
backends/platform/psp/display_manager.cpp
backends/platform/psp/display_manager.h
backends/platform/psp/osys_psp.cpp
backends/platform/psp/osys_psp.h
backends/platform/symbian/src/SymbianOS.cpp
backends/platform/symbian/src/SymbianOS.h

* The N64 and PSP implementations are functionally identical to the versions in the base OSystem class, apart from the fact that neither of them recognise "normal" or "default" as values.
* The Symbian implementation ignores the argument passed to it and just uses the first available graphics mode. However, there isn't any reason to do this since attempting to use an unrecognised graphics mode will already be handled gracefully by the backend.
* The DS implementation is just a stub.

BACKENDS: Remove unnecessary implementations of setGraphicsMode(const char *)

---

backends/fs/posix/posix-fs.cpp
backends/fs/posix/posix-iostream.cpp
backends/fs/posix/posix-iostream.h
backends/module.mk

fstat is generally faster as is does not cause the IO buffer to be
invalidated / refilled.
Benchmark results for the startup time of the SCI engine with Gabriel
Knight 1 CD:
- Linux, glibc, spinning HDD, fseek/ftell: 140 ms
- Linux, glibc, spinning HDD, fstat: 100 ms
- 3DS, newlib, SD card, fseek/ftell: 68 s
- 3DS, newlib, SD card, fstat: 11 s

POSIX: Use fstat instead of fseek / ftell to retrieve file stream sizes

---

Makefile.common

Due to a quirk of target specific make variables which means they
are added to all pre-requisities, this resulted in the defines which
were meant to be applied only to the version module being applied to
most of the codebase.
This did not cause any direct issues, but was untidy and unexpected
behaviour which was reported in Pull Request 1946 by janisozaur.
Fix it by defining a special rule for version.o with own flags
instead of using template rule.
Signed-off-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>

BUILD: Fix Version Define Being Added to All Code Objects

---

common/str-enc.cpp
common/str-enc.h

It uses Encoding::convert to do the conversion first and try old method if it fails.
This also adds an invalid encoding which can be used when encoding is unknown (yet).
In this case encode and decode fail.

COMMON: Add CJK encodings to Common::CodePage

---

engines/wintermute/base/scriptables/script_ext_directory.cpp

Unused variables were cleaned up at
47811167d5ddd9cbf64099ad36f2da5ae413fc86, commenting out a bit too much
code, since stack->pop() has a side effect (popping a value from data
stack).

WINTERMUTE: restored commented out stack->pop()

---

engines/wintermute/base/base_file_manager.cpp

Latest Steam updates for Reversion titles include Simplified and Traditional Chinese languages that were not properly identified

WINTERMUTE: Add Simplified and Traditional Chinese flavours

---

gui/editgamedialog.cpp

Games using midi always uses it for music. A game without music will not use midi. As such, don't show the midi tabs at all for that game.

GUI: Don't show midi setting tabs if the game has no music at all.

---

engines/composer/composer.cpp
engines/composer/composer.h
engines/composer/detection.cpp

Support for games and demos found in Hebrew CDs of "The Little Samurai" and "Imo and the King".
Note:
Demos from "Imo and the King" are in English.
Demos from "The Little Samurai" are in Hebrew.
Note 2: 
The games and demos from "Imo and the King" are trying to access `RETAIL2.RSC` from `DEMO` directory in CD because it is the one referenced in the `.INI`.
It does not affect the game, but triggers an error message when leaving the game.
(The exact same file is also available in actual game data directory - `IMO/MENU/RETAIL2.RSC`)

COMPOSER: add support for v1 hebrew versions (Windows + Macintosh)

---

engines/queen/input.cpp

Quick fix for https://bugs.scummvm.org/ticket/11272.
This undoes https://github.com/scummvm/scummvm/pull/1779
So the behaviour of left click during player's talk now once again does not match DOS executable.

QUEEN: fix bellboy dialogue - bug #11272

---

backends/platform/psp/osys_psp.cpp
backends/platform/psp/osys_psp.h
backends/timer/psp/timer.cpp
backends/timer/psp/timer.h

This has been briefly tested using PPSSPP, but has not been tested on real hardware.

PSP: Make the PspTimer class a subclass of DefaultTimerManager

---

engines/wintermute/detection_tables.h

Ticket: https://bugs.scummvm.org/ticket/11061
Matched game IDs for the Wintermute engine: facenoir-win
{"data.dcp", 0, "50a7a01b97cd3658fc84f2bec7c1212b", 555533359},
This is a version from one of the many times Face Noir has been bundled.

WINTERMUTE: Fix bug 11061: Unknown game variant for Wintermute - Face Noir

---

engines/glk/level9/detection.cpp

The crash occurs when the detection code is checking a non-Level 9 .dat file that is under a certain size, which causes issues when one is found by the mass add dialog.

GLK: LEVEL9: Fix crash in detection code

---

engines/wintermute/base/base_keyboard_state.cpp
engines/wintermute/ui/ui_edit.cpp

WINTERMUTE: Refactor UIEdit::handleKeypress()
This fixes https://bugs.scummvm.org/ticket/11033
Removed checking printable property for system keys.
Refactored whole function to make it a bit more readable.
Reference implementations:
https://github.com/retrowork/wmelite/blob/master/src/UIEdit.cpp#L724
https://github.com/retrowork/Wintermute-Engine/blob/master/src/engine_core/wme_base/UIEdit.cpp#L708
WINTERMUTE: Handle isCurrentPrintable property for WME 1.x and WME Lite
Moved KEYCODE_SPACE to "alphanumeric or punctuation" group.
Splited "else" into before and after WME_LITE.

WINTERMUTE: Fix backspace handling on text input

---

engines/lure/detection.cpp
engines/lure/surface.cpp

LURE: Enable the optional use of TTS to read descriptions as a narrator in Lure of the Temptress
Added an option to use TTS to read descriptions in Lure of the Temptress.
Following the discussion in #1953, this option will only appear if the user
compiles with TTS support. It will read scene and object descriptions but
omit any character dialog.

LURE: Enable the optional use of TTS to read descriptions as a narrator in "Lure of the Temptress"

---

engines/scumm/scumm.h
engines/scumm/string.cpp

Fix fake BiDi (from #1989 ) issues with systems in which char is unsigned by default (e.g. Android).
By using types explicitly defined by ScummVM.

SCUMM: use reliable types in fake bidi

---

backends/graphics/opengl/opengl-graphics.cpp
graphics/surface.cpp
graphics/surface.h
image/bmp.cpp
image/bmp.h
image/png.cpp
image/png.h

This removes the need to flip surfaces the right way up in `writePNG()` or `writeBMP()`.

OPENGL: Ensure surfaces created by saveScreenshot are the right way up

---

engines/wintermute/detection_tables.h

"Hor" is a small ("Game for five minutes in the dark"), complete and really nice game by Roman
Koksharov.
It has no in-game text except the game title, so I marked is at
Common::UNK_LANG.
Source: https://gamejolt.com/games/hor/258037
Source: https://www.indiedb.com/games/hor
v1.0 and v1.3 are actually almost the same, difference is only in
"ALLOW_WINDOWED_MODE" game property and settings binary.
P.S. Have you found a secret ending? ^_~

WINTERMUTE: Add detection for Hor game

---

engines/wintermute/ad/ad_actor.cpp
engines/wintermute/ad/ad_entity.cpp
engines/wintermute/ad/ad_entity.h
engines/wintermute/ad/ad_game.cpp
engines/wintermute/ad/ad_item.cpp
engines/wintermute/ad/ad_response_box.cpp
engines/wintermute/base/base_engine.h
engines/wintermute/base/base_file_manager.cpp
engines/wintermute/base/base_file_manager.h
engines/wintermute/base/base_frame.cpp
engines/wintermute/base/base_game.cpp
engines/wintermute/base/base_keyboard_state.cpp
engines/wintermute/base/base_keyboard_state.h
engines/wintermute/base/base_persistence_manager.h
engines/wintermute/base/base_sub_frame.cpp
engines/wintermute/base/file/base_package.cpp
engines/wintermute/base/file/base_package.h
engines/wintermute/base/font/base_font_bitmap.cpp
engines/wintermute/base/gfx/base_renderer.cpp
engines/wintermute/base/gfx/base_renderer.h
engines/wintermute/base/gfx/osystem/base_render_osystem.cpp
engines/wintermute/base/gfx/osystem/base_render_osystem.h
engines/wintermute/base/gfx/osystem/base_surface_osystem.h
engines/wintermute/base/saveload.cpp
engines/wintermute/base/saveload.h
engines/wintermute/base/scriptables/script.cpp
engines/wintermute/base/scriptables/script_ext_array.cpp
engines/wintermute/configure.engine
engines/wintermute/detection_tables.h
engines/wintermute/wintermute.cpp

FoxTail is a point-and-click adventure game by Gingertips Game Studio, featuring extended and hacked WinterMute engine fork with closed sources. Most features are added by introducing new API methods and properties, but some are just hardcoded to be different from normal WME stuff.
I'd like to get some feedback on how I implemented those features while I look if I can do anything with known issues and re-test everything. Most arguable things are:
0. should new methods and properties be avaliable for other WME games or should we add if(BaseEngine::instance().getGameId() == "foxtail") guard everywhere in addition to subengine's #ifdef? Is if(BaseEngine::instance().getGameId() == "foxtail") the right way to detect FoxTail inside engine?
1. most SX-objects don't have "normal" constructors, …

WINTERMUTE: Wintermute subengine for FoxTail game

---

engines/mohawk/riven.cpp
engines/mohawk/riven.h

This is based on PR #1990, and includes fixes for the comments made in that pull request.
It's been two weeks without any activity in the other PR, and the changes requested were pretty straightforward, so I decided to continue the work that @ccawley2011 started.

MOHAWK: RIVEN: Add keymapper support (continued)

---

engines/griffon/detection.cpp

Yet another engine that doesn't use MIDI.

GRIFFON: Game uses vorbis, not midi, for the music.

---

engines/wintermute/base/base_engine.cpp
engines/wintermute/base/base_engine.h
engines/wintermute/base/base_file_manager.cpp
engines/wintermute/detection.cpp
engines/wintermute/detection_tables.h
engines/wintermute/wintermute.cpp
engines/wintermute/wintermute.h

Game flags GF_IGNORE_SD_FILES and GF_IGNORE_HD_FILES are introduced to ignore *_sd.dcp and *_hd.dcp packages (needed for J.U.L.I.A.: Among the Stars)
Marked some 2.5D games as 2.5D games.
Add detection for some more games, both 2D and 2.5D.

WINTERMUTE: Add flags for SD/HD games and some more detection

---

backends/graphics/opengl/opengl-graphics.cpp

This implements the hardware stretch mode "Fit to Window (4:3)" as an alternative to the aspect ratio correction option.
- No existing functionality is being removed, this is just an additional option the user might select.
- One benefit why users might want to select this stretch mode is that the scaling is done via hardware scaling. This is fast on platforms with slow cpu, and uses a hardware scaling algorithm which can look better on some platforms than the software-based stretch.
- A second benefit why users might want to select this mode is that it allows to stretch ANY game to 4:3, even games that do not respect the aspect ratio correction option, like Dreamweb for example, or games that run in other resolutions or engines that are not covered by the aspect ratio correction option. …

OPENGL: Implement stretch mode Fit to window (4:3)

---

backends/graphics/sdl/sdl-graphics.cpp

Makes it a bit easier to recognize files in the screenshot folder, IMO.

SDL: Use the name of the running target as a base for screenshot files

---

backends/platform/iphone/iphone_video.h
backends/platform/iphone/iphone_video.mm
backends/platform/iphone/osys_main.h
backends/platform/iphone/osys_video.mm

This prevents the iOS device from going to sleep when an engine is running, for example while the intro of a game is playing (this happened to me with DOTT for example, and both Scorp and @waltervn mentioned this today in the Discord server).
This changes here are a port of commits 4a94464 and 58f3aac from the iOS7 backend to the old iPhone backend. It replaces the use of `dispatch_async`, that is only present since SDK 4.0, with `performSelectorOnMainThread` that exists since SDK 2.0. This means all the APIs used by the commit here should work with SDK 2.0 or above.
I am however unable to test that it compiles or works, so I am submitting this here for review.

IPHONE: Disable idle timer while an engine is running

---

engines/director/lingo/lingo-builtins.cpp

We check of the current char in a string is a space,
if so check if the previous one wasn't a space, then count it as a word.
And count the last word when the text doesn't end in a space.
This is to prevent off by one errors.
Director 4 counts everything non-space (i.e. \n, \t, etc) as a
word separator. A word can be a single '.'.

DIRECTOR: LINGO: Add numberofwords implementation

---

engines/wintermute/detection_tables.h

Russian translation of the game "The Lost Crown - A Ghost Hunting Adventure" (Akella DVD version)

WINTERMUTE: Add russian localization of "The Lost Crown"

---

engines/wintermute/base/file/base_disk_file.cpp

1. Fix knownPrefix for Tanya Grotter 2. Octal bytes are now used instead of incorrect pseudo-hex writing.
2. Add 5 more knownPrefixes for file seeking
3. Add known absolute EDITOR_BG_FILE paths and prefixes. EDITOR_BG_FILE path is currently ignored, so this is useless now, however it may come handy in some deep future, if something like a sprite viewer would be implemented.

WINTERMUTE: Update known prefixes of absolute paths

---

engines/wintermute/base/base_game.cpp
engines/wintermute/base/gfx/base_renderer.h
engines/wintermute/base/gfx/osystem/base_render_osystem.cpp
engines/wintermute/base/gfx/osystem/base_render_osystem.h
engines/wintermute/base/scriptables/script.cpp
engines/wintermute/platform_osystem.cpp

To test those functions with a test game (https://github.com/lolbot-iichan/wme_testsuite/tree/master/external_test/packages) you would need original DLL binary from related games.
Emulated DLLs:
* James Peris - geturl.dll - used to get news headers at Demo 2012, emulated with hardcoded lines of current news
* HeroCraft games (e.g. Pole Chudes) - tools.dll and img.dll - used to control windowed mode, window header, etc, binded to actual engine API where possible
* Wilma Tetris - shell32.dll - used to open URLs with browser, binded to actual engine API
* Art of Murder - installutil.dll - used to check if DVD is installed, hardcoded with True
* Corbomite Games (Pizza Morgana & ZBang) - dlltest.dll - used to send debug lines to an IRC server if option is enabled, implemented with logging …

WINTERMUTE: Implement external functions for lots of games

---

engines/wintermute/detection_tables.h

"Dr. Doyle & The Mystery Of The Cloche Hat" is a 2D point and click
adventure game by PnC Narratives.
Interesting detail about this game is that not actual items, but ideas
and clues are stored in inventory. Combining them and using on people
and objects leads to interrogations, more clues, etc.
Buy game URL: https://store.steampowered.com/app/574420
Depot details: https://steamdb.info/depot/574421

WINTERMUTE: Add detection of Dr. Doyle & The Mystery Of The Cloche Hat

---

engines/director/images.cpp

Use a cast to fix a compiler warning about comparison between signed
and unsigned integer expressions.

DIRECTOR: Fix compiler warning

---

graphics/macgui/macwindowmanager.h

Change variable to unsigned to fix a compiler warning about
comparison between signed and unsigned integer expressions.

GRAPHICS: MACGUI: Fix compiler warning

---

engines/gob/sound/sound.cpp

Fix for https://bugs.scummvm.org/ticket/11335
Added the fix directly below an existing precedent for this type of issue.
One potential problem might be if there is a version of the game out there in the wild without this bug, but given the naive approach of the aforementioned precedent and the fact that I can't find any other versions of the game to test it...

GOB: Add workaround for incorrect Goblins 3 CD audio track strings

---

engines/zvision/core/clock.cpp

This fixes an out-of-bounds condition when the clock is queried for the first time. Without this patch, Zork Nemesis crashes on my iPad after the initial cut scene.

ZVISION: Fix initial out-of-bounds condition in clock.

---

engines/sci/resource.cpp

Since ~2 weeks ago, when adding a pirated SCI game that has no fallback, there is a segfault.
Fixing it here.
(this is not related to my other PR, since it was introduced earlier, I just encountered it while working on the other PR ;-) )

SCI: fix segfault upon detection of pirated game, without fallback

---

engines/advancedDetector.cpp

ENGINES: add GUI warning when encountering a pirated game

---

engines/wintermute/platform_osystem.cpp

"MouseWheelUp" event was generated instead of "MouseWheelDown" event on
Common::EVENT_WHEELDOWN.
Affected 2D games: FoxTail, Looky, Helga Deep in Trouble, Carol Reed
series, Reversion 2, James Peris, Vsevolod

WINTERMUTE: Fix handling of EVENT_WHEELDOWN

---

engines/kyra/detection_tables.h

Add checksum of "GEMCUT.PAK" for Polish text translation to kyra1 engine.

KYRA: Add detection for Polish fan translation of kyra1

---

engines/cge/POTFILES
engines/cge/events.cpp
engines/cge2/POTFILES
engines/cge2/events.cpp
engines/cruise/POTFILES
engines/cruise/menu.cpp
engines/engine.cpp
engines/engine.h
engines/griffon/POTFILES
engines/griffon/detection.cpp
engines/griffon/dialogs.cpp
engines/griffon/engine.cpp
engines/griffon/griffon.cpp
engines/griffon/griffon.h
engines/griffon/saveload.cpp
engines/titanic/main_game_window.cpp
engines/titanic/titanic.cpp
engines/titanic/titanic.h
engines/ultima/nuvie/keybinding/key_actions.cpp
engines/ultima/nuvie/menus/game_menu_dialog.cpp
engines/ultima/shared/early/ultima_early.cpp
engines/ultima/shared/early/ultima_early.h
engines/ultima/shared/engine/ultima.cpp
engines/ultima/shared/engine/ultima.h
engines/ultima/ultima1/actions/quit.cpp
engines/ultima/ultima1/u1gfx/view_char_gen.cpp
engines/ultima/ultima1/u1gfx/view_title.cpp
engines/ultima/ultima8/ultima8.cpp
engines/ultima/ultima8/ultima8.h

This pull request aims to simply provide some simplification and improvements for the savegame code, particularly going forward for new engines added in the future. It consists of:
1. Showing the save/load dialogs due to in-game actions
A common feature of a lot of the existing games is that they need to trigger showing the save/restore dialogs from in-game buttons, menus, etc., in addition to from the GMM. As such, engines have gotten into the habit of continuously repeating code copied from the GMM to instantiate the dialog, get the result, and call saveGameState/loadGameState. Two new methods are added to the Engine class - loadGameDialog and saveGameDialog. I've also converted several of the engines to use the new methods rather than their own code. I wasn't pedantic about it.. some …

ENGINES: Savegame code simplifications

---

engines/pink/gui.cpp

Fairly obvious and straightforward implementation.
Seems to expose a bug with the pause logic, scenes don't resume correctly, either freezing entirely or loosing the BGM. #NotMyFault

PINK: Implement save & load in the menubar

---

engines/testbed/detection.cpp

The testbed "engine" doesn't do any of the possible engine features, mark it as such.

TESTBED: Provide correct engine feature implementation data

---

engines/engine.cpp

Without this change, loading / saving fails silently (none of the callers check the return code).

ENGINES: Display a GUI error message when loading / saving failed

---

engines/sci/detection_tables.h
engines/sci/engine/script_patches.cpp
engines/sci/engine/script_patches.h
gui/message.cpp
gui/message.h

GUI: add optional 'alignment' parameter to 'MessageDialog', and SCI: GK2: if subtitles patch is missing, explain how to install it

---

engines/testbed/detection.cpp

This continues the work of #2042 to provide correct metadata for the `testbed` "engine".

TESTBED: Set the NOLAUNCHLOAD GUI option

---

engines/director/lingo/lingo.cpp

Fixes a compiler warning about comparing signed and unsigned variables

DIRECTOR: LINGO: Fix compiler warning

---

engines/sci/engine/kfile.cpp

Some SCI32 games have an issue that the saved games thumbnails is useless because it's hidden
by the configuration panel (QFG4) or by the keyboard (Shivers).
Maybe this problems appears on other SCI32 games as well, should be checked.
We avoid that by keeping the thumbnail everytime the menu bar is hidden,
and when time comes to save the game, we use that thumbnail instead of taking
a new one (which would be with the control panel/keyboard).
This fix is for QfG4 only.

SCI32: fix bug #9752 (for all games)

---

engines/pink/gui.cpp
engines/pink/pink.h

While the online pages are long dead, the menu bar commands refer to local pages in the game folder.

PINK: Open local webpages from the menu bar

---

engines/pink/gui.cpp
engines/pink/pink.cpp
engines/pink/pink.h

Using an argument for what is already in the class definition is pointless, especially when there is no chance of an alternative value being used.

PINK: Use existing member variable

---

engines/director/lingo/lingo-codegen.cpp

Debug print statement that ran before the stack showed 'after', should be before.

DIRECTOR: LINGO: Debug print before string fix

---

engines/metaengine.cpp

Buffer is too small compared to what snprintf tries to put in it.

ENGINES: Fix incoherent buffer size

---

common/ustr.cpp
common/ustr.h

This is like strchr but for uint32 based strings

COMMON: Add find() method for character to U32String

---

engines/director/lingo/lingo-code.cpp
engines/director/lingo/lingo-codegen.cpp

Lingo implements the for each loop as `repeat with VAR in ARRAY`.
1) The `ARRAY` is evaluated,
2) a loop counter is created of size(ARRAY),
3) consume the loop counter, starting at 0.
3) the ARRAY[counter] item is assiged to `VAR` and
4) the loop body executed,
5) update the loop counter with + 1 and
6) goto 3 till the loop counter is exhausted.

DIRECTOR: LINGO: Implement repeat with var in array

---

engines/sci/sound/drivers/midi.cpp

This fixes https://bugs.scummvm.org/ticket/10374 where the Windows version randomly fails an assertion when exiting an SCI game. The bug isn't Windows-only, it's just that the Windows code has an assertion that revealed the bug.
Certain platforms/MIDI-configurations use a background timer thread to send MIDI commands from a queue populated by the main thread. The bug is that SCI makes no attempt at thread synchronization with these commands when exiting. It doesn't attempt to clear them, it doesn't attempt to wait on them, it just proceeds to shut down even though the timer thread might be in the middle of sending a queued command. The assertion failure occurs when SciMusic's destructor is deep in the middle of destruction while its own timer attempts to send queued commands.
I've opted …

SCI: Wait for MIDI commands to be sent on exit

---

audio/mididrv.cpp
audio/mididrv.h
engines/kyra/sound/drivers/midi.cpp
engines/sci/sound/drivers/midi.cpp

MIDI/SCI/KYRA: Add support for Roland GS drumkits
This PR adds support for the alternate drumkits in Roland GS devices (also present in various GM devices). These are used in the MIDI data of Quest for Glory 3, Space Quest 5, Pepper's Adventures in Time and Lands of Lore.
Most of these games contain invalid drumkit numbers; they relied on a feature of the Roland SC-55 which corrected this. Later devices do not include this feature and drumkit selection would not work. This PR contains code to emulate the correction feature to make the drumkit selections work on later devices.
SCI did not send program changes on the rhythm channel. This has been added as well as the invalid drumkit number correction.
KYRA did already send program changes on the rhythm channel; invalid drumkit correction …

MIDI/SCI/KYRA: Add support for Roland GS drumkits

---

Makefile.common

In this case, the linker optimizes out Debugger which get required
later by Engine due to @dreammaster rework. Building with all engines
prevents optimization because several engines subclass Debugger and they
are included before gui.a in linker command line

Fix building when selected engines don't have their own debugger

---

engines/director/lingo/lingo-code.cpp

Lingo has two ways to break from loops: `return` and `exit repeat`.
Both are now handled in repeat with VAR in ARRAY.
Example Lingo code:
```
on exitRepeat
set aList = [1,2,3,4]
repeat with a in aList
if a = 3 then
exit repeat
end if
end repeat  
return a
end exitRepeat
on returnRepeat
set aList = [1,2,3,4]
repeat with a in aList
if a = 3 then
return a
end if
end repeat  
end return
put exitRepeat()
put returnRepeat()
```

DIRECTOR: LINGO: handle break from loops

---

engines/sci/sound/drivers/midi.cpp

There are many situations that GM sounds worse than MT, even for games that were written for GM.
I think this is related to this.
And, there is a note in midi.cpp, added by Walter van Niftrik on his commit from 2010:
```// NOTE: SSCI uses channels 1 through 8 for General MIDI as well, in the drivers I checked```
Thus, I took @waltervn's note and made GM use the same channels as MT-32.
Also, issue #6686 reports that using the "higher" channels causes problem on a real SC-55.
This change solves at least bugs: #6686, #9578, #9735, #10297 and #11012.
Notes:
- I have verified all these bugs, except for #6686, as I don't have SC-55
- On PR #2070 , @sluicebox mentioned that the master volume is changing, but slowly. That's the cause of issues #9578 and #11012 , so it's better to have it fixed. …

SCI: using only channels 1-8 on GM devices

---

configure

_(I accidentally deleted PR #2033. These are the same commits)_
- CONFIGURE: fix documentation for `--with-sdl-prefix` flag
- CONFIGURE: --help: indent subengines
Instead of showing subengines directly under their parent engine, like:
```
kyra                   Kyra engine
lol                    Lands of Lore in Kyra engine
eob                    Eye of the Beholder in Kyra engine
lab                    Labyrinth of Time engine
```
Show them slightliy indented, like:
```
kyra                   Kyra engine
- lol                  Lands of Lore in Kyra engine
- eob                  Eye of the Beholder in Kyra engine
lab                    Labyrinth of Time engine
```
It keeps the list sorted, and makes it easier to skim through it.

CONFIGURE: fix documentation for '--with-sdl-prefix' and indent subengines

---

engines/sky/control.cpp
engines/sky/control.h
engines/sky/detection.cpp
engines/sky/intro.cpp
engines/sky/mouse.cpp
engines/sky/sky.cpp
engines/sky/sky.h

SKY: Keymapper integration

---

engines/bladerunner/slice_renderer.cpp

In my opinion, there is no need to initialize this array every time drawShadowPolygon() is called, so I would suggest to declare it as "static const".

BLADERUNNER: Set 'ditheringFactor' as static const object.

---

engines/ultima/ultima8/graphics/base_soft_render_surface.cpp

As part of the porting work from Pentagram, the format masks used during blend
operations are not set correctly, resulting in grey shadows under lamps (rather
than lighting the underlying surface).  This sets the masks correctly so lamps
now look right.
attn @dreammaster to save you trying to find this.

ULTIMA8: Fix blends to SDL surface (corrects lamps, smoke, etc)

---

rules.mk

Some distributions populate their build environment with special linker flags, e.g. for hardening purposes such as immediate binding and/or read-only relocations.
Those flags should be honored when linking dynamic libraries.

BUILD: Apply LDFLAGS on modules/plugins

---

configure

RPM-based distributions come with a configure macro, that sets up the whole build environment.  In order to be able to use this macro, some options, which are valid for the configure script generated by GNU Autotools, should not error-out when preparing the build stage.
Unfortunately the configure script, as used by ScummVM uses the `--host` option to determine the target system it will actually be build for.  Autotools based configure scripts have a `--target` option for such a purpose, and use the `--host` option to determine the system the build is performed on.
For that reason there should be a way to discard the parameters passed to the configure script with the `--host` option.  The easiest approach to achieve this goal, is to have an environment variable, which when set influences …

CONFIGURE: Add compatibility for RPM's configure macro

---

engines/director/lingo/lingo-builtins.cpp
engines/director/lingo/lingo-the.cpp

Some versions were mismatched as 3 or 4.
The source for these changes is the book: 'Director for the MACINTOSH: GETTING STARTED & WHAT'S NEW' for Director 3.1.

DIRECTOR: LINGO: Specify version 3.1 for commands

---

engines/director/score.cpp

The background color is called stageColor in Director.
Director uses a palette with 256 colors.
The colors in the Palette have an offset of 255.

DIRECTOR: Set the backgroundcolor

---

engines/ultima/ultima8/ultima8.h

For an unknown key, it's possible for `key` to be `HID_LAST` when recording the down state and last-down timestamp, which results in accesses off the end of the arrays. The simplest  fix is to just extend the arrays by 1 - in practice we never care about the down state or last down timestamp for unknown keys so this is a harmless fix as far as I can tell.

ULTIMA8: Fix OOB access to arrays for HID events

---

engines/ultima/ultima8/usecode/uc_machine.cpp

After using the keyring to unlock a chest, occasionally opcode 0x44
references a value higher than the length of the source list. The
simple workaround is to ignore this opcode in this case.  It's not
a proper fix but it prevents a crash and I haven't found any
side-effect of doing it.

ULTIMA8: Ignore opcode which could cause crash closing backpack

---

common/encoding.cpp

Testcase: convert 1-byte encoded single character string (e.g. "=") from 125X to
UTF32.
Expected result: got widestring, first dword contains "=", next dword
contains "\0"
Actual result: got widestring, first dword contains "=", second dword
contains garbage, next dword contains "\0"
Reference implementation:
http://www-personal.umich.edu/~bazald/l/api/_s_d_l__iconv_8c_source.html
, line 887

COMMON: Fix conversion to UTF32 for short strings

---

engines/ultima/ultima8/misc/istring.cpp
engines/ultima/ultima8/misc/istring.h

The `istring` class file and header redefine a few common string functions, but they're not used any more now that it's using the `Common::String` functions.

ULTIMA8: Clean up unused functions in istring

---

engines/ultima/ultima8/usecode/uc_list.h

The code for `UCList.remove` is buggy in 2 ways:
* The loop resets the value of `equal` for each byte
* The removal check is reversed, removing items which are `!equal`
In practice this function is only called from `substractList` for engine opcode `0x1B`.  The comment in `uc_engine.cpp` says `0x1B` only happens in Crusader, so this code is probably never called in U8 but it feels better to fix it anyway and match the behavior of `substractStringList`.

ULTIMA8: Fix buggy UCList.remove

---

engines/ultima/ultima8/audio/sonarc_audio_sample.cpp

In practice it probably does the expected thing on every platform, but
it's an easy fix and better to be safe.

ULTIMA8: Avoid left shifts of -ve numbers (undefined in c spec)

---

engines/ultima/ultima8/ultima8.cpp

This fixes the direct loading of save games from the ScummVM menu by
blocking autosave during the startup.
There may be some more elegant way to fix this so I'm not sure if this is the nicest solution - it does the job though.

ULTIMA8: Don't save while starting up

---

common/str.cpp

The `Common::String::findLastNotOf(char c)` function returns the char it's looking for, rather than the index of that char (compare this with `findLastNotOf(*chars)` which returns `idx`).  I think this is probably wrong.

COMMON: Fix return value of String::findLastNotOf

---

engines/dragons/dragonflg.cpp
engines/dragons/font.cpp
engines/dragons/scene.cpp
engines/dragons/talk.cpp

This PR contains several simple and unrelated commits that address compiler warnings about comparison between signed and unsigned variables.

DRAGONS: Fix several compiler warnings

---

engines/dragons/dragonimg.h
engines/dragons/dragonrms.h

This PR contains two commits to fix compiler warnings about signed vs unsigned variables.
In both files/classes, the private member variable  _count is of type int16, but it does not need negative values so it is changed to type uint16.

DRAGONS: Fix compiler warnings

---

backends/events/androidsdl/androidsdl-events.cpp
backends/events/default/default-events.cpp
backends/events/gph/gph-events.cpp
backends/events/openpandora/op-events.cpp
backends/events/sdl/sdl-events.cpp
backends/keymapper/action.h
backends/keymapper/hardware-input.cpp
backends/keymapper/input-watcher.cpp
backends/keymapper/keymap.cpp
backends/keymapper/keymapper.cpp
common/events.h
common/recorderfile.cpp
engines/testbed/events.cpp

This allows the forward and back mouse buttons to be used by the keymapper. This PR also includes one of the commits from PR #2051 to stop the two PRs from conflicting with each other.

BACKENDS: Add events for additional mouse buttons

---

engines/advancedDetector.cpp

Checking if a file exists is somewhat costly on the 3DS. Remembering which files do not exist instead of repeatedly checking for them reduces the time it takes to detect games from ~1 minute to ~10 seconds in some cases.

ENGINES: Keep track of the unavailable files in AdvancedDetector

---

engines/macventure/gui.h

This PR fixes multiple compiler warnings about comparison between signed and unsigned variables, as it is reported each time this header is included.
The type int should be large enough to handle calculations between uint16 surface height and int font height.

MACVENTURE: Fix compiler warnings

---

engines/ultima/ultima8/graphics/palette_manager.cpp
engines/ultima/ultima8/graphics/palette_manager.h
engines/ultima/ultima8/gumps/menu_gump.cpp
engines/ultima/ultima8/gumps/menu_gump.h
engines/ultima/ultima8/world/actors/avatar_death_process.cpp

If the avatar dies while tripping on mushrooms or the menu is opened
when the palette is changed (eg, during a scripted fight with the
guards where the screen blackens) then the tombstone and menu palette
are also changed.
This resets the palette temporarily while showing the menu, and
permanently on avatar death.
I'm not totally sure if this is the cleanest way to do it, there may be some better way I'm missing, or some side-effect of doing it this way I haven't noticed - for now it seems to work well in my testing.

ULTIMA8: Reset palette when showing menu

---

engines/wintermute/detection.cpp
engines/wintermute/detection_tables.h

Reversion 3 was released today! 
You can buy it here: https://store.steampowered.com/app/281080
I wonder if it's completable with ScummVM, since there is no Linux&Mac builds yet...
Reversion 1 was recently updated:
https://steamdb.info/depot/270571/manifests/
https://steamdb.info/depot/270572/manifests/
https://steamdb.info/depot/270573/manifests/

WINTERMUTE: Add 2020 builds of Reversion 1&3

---

engines/ultima/ultima8/gumps/minimap_gump.cpp
engines/ultima/ultima8/misc/memset_n.h

The minimap appears incorrectly for 2 reasons:
* The memset_{32|16} implementations are buggy - uses a logical or instead
of a binary or, and it fails to move the buffer pointer after doing
the aligned section. This becomes more obvious in 16bpp mode.
* The top line is not long enough
This corrects both issues.

ULTIMA8: Fix apperance of minimap

---

engines/ultima/ultima8/usecode/uc_stack.h
test/engines/ultima/shared/core/str.h
test/engines/ultima/ultima8/misc/box.h
test/engines/ultima/ultima8/misc/id_man.h
test/engines/ultima/ultima8/misc/memset_n.h
test/engines/ultima/ultima8/misc/util.h
test/engines/ultima/ultima8/usecode/bit_set.h
test/engines/ultima/ultima8/usecode/uc_list.h
test/engines/ultima/ultima8/usecode/uc_stack.h
test/module.mk

I've been slowly writing these unit tests, which helped me find the cause of #2088, #2094, and #2104.
There is also one change to the engine code in `uc_stack.h` to make a previously implicit header dependency explicit.

ULTIMA8: Add some unit tests for base U8 classes

---

engines/ultima/ultima8/filesys/odata_source.h
test/engines/ultima/ultima8/filesys/odata_source.h

Also add a unit test for the class to make sure the problem
is fixed.
The unit test doesn't directly detect the problem, it just exercises the class - but it will show this sort of error:
```
Running 282 tests...........................................................................................................................................................................................................................................................................runner(58520,0x113aac5c0) malloc: *** error for object 0x7f8f094004ca: pointer being freed was not allocated
runner(58520,0x113aac5c0) malloc: *** set a breakpoint in malloc_error_break to debug
make: *** [test] Abort trap: 6
```
`~OAutoBufferDataSource()` is freeing the wrong pointer - `bufPtr` is the moving pointer to …

ULTIMA8: Free the correct pointer in ~OAutoBufferDataSource

---

engines/ultima/ultima8/gumps/credits_gump.cpp

If a line contains only a modifier, the function continues and then tries to erase from an empty string.  This avoids that.
The credits are still broken in other ways out of scope for this change :)

ULTIMA8: Avoid calling erase on empty string in credits

---

engines/ultima/ultima8/graphics/base_soft_render_surface.cpp

This corrects the appearance of the credits.
When the pitch is not configured, effectively the `sy` offset parameter in `_tex->getBasePtr(sx, sy)` (in `SoftRenderSurface<uintX>::Blit`) does nothing, so each credit texture gets stuck at the top of the screen when the y offset is >0.

ULTIMA8: Set pitch when configuring a surface texture

---

engines/ultima/ultima8/audio/music_process.cpp
engines/ultima/ultima8/audio/music_process.h
engines/ultima/ultima8/gumps/menu_gump.cpp
engines/ultima/ultima8/gumps/menu_gump.h

There are 2 problems with the way combat music interacts with the menu (and the
credits you can view from there):
* When the menu is closed, the combat music becomes the "last request", so it
never stops even if combat finishes.
* If the creidts are viewed, the requested credits music is ignored because
combat is active, and the music player is checking the actor's status to
decide whether to change tracks.
This fixes both those problems, and restores the original game behavior of just
turning off the music when the menu is opened.  I also removed the coupling of
actor state from the music process.  I think this now works properly in all
situations.

ULTIMA8: Fix menu/credits music behavior

---

engines/ultima/ultima8/kernel/mouse.cpp

In the original game, the mouse length is determined by some simple rectangles.  The Pentagram version significantly adjusted these, making it harder to walk slowly and too easy to accidentally run.  This mostly restores the original behavior.
I also fixed a bug where the mouse direction would not swivel exactly under the avatar's feet, because the fixed offset (14px) was not scaled with resolution.

ULTIMA8: Make mouse length better match original game

---

engines/ultima/ultima8/world/map.cpp

I found a few holes in the North Road (aka Herdsman's Valley) map, some of which you can fall into. The most noticeable one is in the tunnel entrance to the northern end, which can be seen after moving the rubble aside.  The other two are behind cliffs so can't be seen.
As a FYI note, I learned while debugging this that the current map tiles are stored as objects in the savegame, so for these map patches to take effect you can't check with a savegame in that map (or you need to leave that map and go back).

ULTIMA8: Fix some holes in the North Road map

---

engines/ultima/ultima8/world/current_map.cpp
engines/ultima/ultima8/world/item.h

While debugging this code I got lost because there are a few places that calculate exactly the same thing.  This removes a bit of redundancy.

ULTIMA8: Remove a bit of redundant logic for getFootpadWorld

---

engines/kyra/engine/eobcommon.cpp
engines/kyra/engine/lol.cpp

In Lands of Lore and EOB, left and right mouse click via game controller broke when a custom keymap was implemented.
This PR fixes that issue by adding re-mappable left and right click "interact" actions. It also  adds sensible game controller default mappings for other game-specific keymap actions such as attacking and moving.

KYRA: add mouse buttons and controller defaults to LOL and EOB keymaps

---

engines/ultima/ultima8/meta_engine.cpp

The custom keymap used in Ultima 8 broke mouse click that are triggered via game controller buttons A and B.
This PR adds remappable mouse click events that can be mapped to game controller buttons. It also adds some other default game controller mappings to the custom keymap used in Ultima 8.

ULTIMA8: add mouse buttons and controller defaults to keymap

---

engines/metaengine.cpp

This maps game controller X button to '.' (skip line of dialog) by default. I don't see a reason not to map it like this, since that is how it used to be before the keymapper, see here: https://wiki.scummvm.org/index.php?title=Nintendo_Switch

KEYMAPPER: Map Joy_X to skip lines by default

---

engines/dialogs.cpp
engines/dialogs.h
engines/tsage/dialogs.cpp
engines/ultima/ultima8/gumps/menu_gump.cpp

This is a fairly minor change, but since it touches the GMM, I thought it worthwhile doing as a pull request for review.
Essentially, it moves the class declaration of ConfigDialog, used for the GMM Options/keymapper dialog, from the code file to the header file. This lets it be instantiated by engines that have in-game options buttons, but whose settings are all now handled by the ScummVM GUI. As is the case for Ultima VIII. I briefly considered moving the class's code into an entirely new file, but for now it still remains in the engines/dialogs.cpp/.h
Additionally, the TsAGE also used the dialog, but made the mistake of creating it's own sublcass of GUI::OptionsDialog rather than exposing the existing one. Due to various changes over time, this "mini" config dialog is now erroring out. …

ENGINES: Exposed ConfigDialog

---

graphics/fonts/ttf.cpp
graphics/fonts/ttf.h

Implement a kind of font mapper which takes a list of font files, font
face name, size, slant and weight and finds the best matching face.
Fakes italic and bold if there it isn't available.
This commit adds support for TTC files which contains multiple faces
(used by CJK Windows fonts).

GRAPHICS: Mimic CreateFont Windows API

---

engines/ultima/ultima8/audio/speech_flex.cpp
engines/ultima/ultima8/games/game_data.cpp

Speech wasn't working because of a couple of behavior differences with the Std string and vector:
* Initializing with an int sets capacity but not size (so the `_speech` vector size was 0)
* Initializing a string with a buffer including nulls will stop at the first null, so it doesn't split correctly using `SplitString`
Fixed both and now the guardian speech works.

ULTIMA8: Fix guardian speech events

---

engines/wintermute/detection.cpp
engines/wintermute/detection_tables.h

1. WINTERMUTE: Add detection for Italian version of thelostcrowngha
Fixes https://bugs.scummvm.org/ticket/11383
2. WINTERMUTE: Add detection and keymap for "Myth: A Guff's Tale"
"Myth: A Guff's Tale" is a cutscene-rich point and click game about a troll fixing a labyrinth in a dreamworld. 
SOLO DESIGN decided to distribute "Myth: A Guff's Tale" for free since game's co-creator Phil Argent passed away...
Download it here: https://www.kartridge.com/games/solodesign/myth-a-guffs-tale
UPD: game can be download without installing Kartridge appstore, see https://www.gameboomers.com/forum/ubbthreads.php/topics/1180355/re-myth-a-guffs-tale#Post1180355 for details

WINTERMUTE: Detect more games

---

backends/events/gph/gph-events.cpp
backends/platform/gph/gph-backend.cpp
backends/platform/maemo/maemo.cpp
backends/platform/openpandora/op-backend.cpp
configure

This is useful for testing changes to the relevant backends, particularly with regards to downscaling or event handling. It isn't a perfect way of testing compared to using actual hardware, but it's better than nothing.
This affects the GPH, Dingux, LinuxMoto, Maemo and OpenPandora backends.

BACKENDS: Allow compiling certain backends for standard Linux platforms

---

backends/graphics/dinguxsdl/dinguxsdl-graphics.cpp
backends/graphics/dinguxsdl/dinguxsdl-graphics.h
backends/graphics/gph/gph-graphics.cpp
backends/graphics/gph/gph-graphics.h
backends/graphics/surfacesdl/surfacesdl-graphics.cpp
backends/graphics/surfacesdl/surfacesdl-graphics.h

This removes the need for platform specific `#ifdef`s in `loadGFXMode()`.

SDL: Add a separate function for setting the hardware size

---

backends/events/default/default-events.cpp
backends/events/sdl/sdl-events.cpp
backends/events/sdl/sdl-events.h
backends/keymapper/keymap.h
backends/keymapper/keymapper.cpp
backends/keymapper/keymapper.h
backends/keymapper/remap-widget.cpp
backends/keymapper/remap-widget.h
backends/platform/3ds/osystem.cpp
backends/platform/sdl/sdl.cpp
backends/platform/sdl/switch/switch.cpp
base/commandLine.cpp
base/main.cpp
common/events.h
gui/options.cpp
gui/options.h

With the keymapper, game controllers are more configurable. I believe it's time to enable them by default in the SDL port. This pull request also includes a change to reload the keymapper's keymaps when a joystick is plugged or unplugged so the the default joystick bindings are picked up if necessary.

SDL: Enable joystick input by default

---

backends/platform/sdl/switch/switch.cpp

Fixes #11384.
I don't have a Switch, this is untested. Based on my experience with the 3DS, ScummVM's implementation of file buffering has better performance than newlib's when seeks are involved. The buffer size probably needs some tuning.

SWITCH: Use ScummVM file buffering instead of newlib's implementation

---

engines/director/cast.cpp
engines/director/director.h
engines/director/frame.cpp
engines/director/graphics.cpp
engines/director/score.cpp

The palettes are reversed by default. This is useful when rendering
sprites, as they use reversed ids as well.
When a color is read directly as an int, it is in the original
unreversed order.
So, reverse it by hand when it's coming from lingo or other sources.
This was done in multiple places by subtracting the color id from 255.
The function transformColor handles this now.
Reversing the color means: 255 - color_id.

DIRECTOR: implement transformColor function

---

engines/ultima/module.mk
engines/ultima/ultima8/audio/music_process.cpp
engines/ultima/ultima8/games/game.cpp
engines/ultima/ultima8/games/game.h
engines/ultima/ultima8/games/remorse_game.cpp
engines/ultima/ultima8/games/remorse_game.h
engines/ultima/ultima8/games/start_u8_process.cpp
engines/ultima/ultima8/games/u8_game.cpp
engines/ultima/ultima8/graphics/fade_to_modal_process.cpp
engines/ultima/ultima8/graphics/fade_to_modal_process.h
engines/ultima/ultima8/graphics/palette_fader_process.cpp
engines/ultima/ultima8/gumps/menu_gump.cpp
engines/ultima/ultima8/gumps/movie_gump.cpp
engines/ultima/ultima8/gumps/movie_gump.h
engines/ultima/ultima8/kernel/process.cpp
engines/ultima/ultima8/kernel/process.h
engines/ultima/ultima8/misc/debugger.cpp

This adds a palette fade out / in when opening the credits, intro movie, etc from the menu.
In hindsight it's quite a bit of code for a pretty minor thing, but it makes it behave more like the original game so it made me happy 😅

ULTIMA8: Add short fade in/out around menu items to match original game

---

engines/ultima/ultima8/graphics/base_soft_render_surface.cpp
engines/ultima/ultima8/graphics/render_surface.cpp
engines/ultima/ultima8/graphics/render_surface.h
engines/ultima/ultima8/graphics/scaler.h
engines/ultima/ultima8/graphics/soft_render_surface.cpp
engines/ultima/ultima8/graphics/soft_render_surface.inl
engines/ultima/ultima8/ultima8.cpp

The Ultima8 engine defined its own `PixelFormat` struct with very similar members to the ScummVM one.  I refactored it to extend that struct instead of redefining it.
This refactor should help the planned changes that I mentioned in #2158.

ULTIMA8: Use ScummVM PixelFormat struct

---

backends/dialogs/gtk/gtk-dialogs.cpp
backends/dialogs/gtk/gtk-dialogs.h
backends/dialogs/macosx/macosx-dialogs.mm
backends/dialogs/win32/win32-dialogs.cpp
backends/module.mk
backends/platform/sdl/posix/posix.cpp
common/dialogs.h
configure
po/POTFILES

Suggested by @lotharsm 
Building on #1414, this adds a native file browser to Linux-based distros that support the GTK3 GUI, falling back to the ScummVM GUI when not available.
This is only enabled if the "system dialogs" feature is active and libgtk3-dev is present, similar to the current Ubuntu taskbar feature, so it shouldn't disrupt builds.
I'd appreciate testing on various distros to make sure it works correctly across GUIs and buildsystems.

POSIX: Add native file browser via GTK

---

engines/ultima/ultima8/games/game_data.cpp
engines/ultima/ultima8/games/game_data.h
engines/ultima/ultima8/graphics/shape.cpp
engines/ultima/ultima8/graphics/shape.h
engines/ultima/ultima8/graphics/shape_frame.cpp
engines/ultima/ultima8/graphics/shape_frame.h
engines/ultima/ultima8/graphics/soft_render_surface.inl
engines/ultima/ultima8/gumps/book_gump.cpp
engines/ultima/ultima8/gumps/container_gump.cpp
engines/ultima/ultima8/gumps/gump.cpp
engines/ultima/ultima8/gumps/menu_gump.cpp
engines/ultima/ultima8/gumps/mini_stats_gump.cpp
engines/ultima/ultima8/gumps/minimap_gump.cpp
engines/ultima/ultima8/gumps/paged_gump.cpp
engines/ultima/ultima8/gumps/paperdoll_gump.cpp
engines/ultima/ultima8/gumps/quit_gump.cpp
engines/ultima/ultima8/gumps/readable_gump.cpp
engines/ultima/ultima8/gumps/scroll_gump.cpp
engines/ultima/ultima8/gumps/slider_gump.cpp
engines/ultima/ultima8/gumps/u8_save_gump.cpp
engines/ultima/ultima8/gumps/widgets/button_widget.cpp
engines/ultima/ultima8/gumps/widgets/sliding_widget.cpp
engines/ultima/ultima8/world/item_sorter.cpp

A mostly trivial change to make all the use of `ShapeFrame` pointers const (and also remove the never-used parameter `need_bytes_rle` on `ShapeFrame::getConvertShapeFrame`), so that I can more confidently decompress the frames after loading and avoid separate render paths (as mentioned in #2158).
I think this will conflict with #2158 if one is merged first, I'll rebase if needed.

ULTIMA8: Make ShapeFrame pointers const

---

engines/ultima/ultima8/convert/convert_shape.cpp
engines/ultima/ultima8/graphics/render_surface.h
engines/ultima/ultima8/graphics/shape.h
engines/ultima/ultima8/graphics/shape_frame.h
engines/ultima/ultima8/graphics/soft_render_surface.cpp
engines/ultima/ultima8/graphics/soft_render_surface.h
engines/ultima/ultima8/graphics/soft_render_surface.inl

Some changes to make the code a bit clearer for `Shape` and `SoftRenderSurface`.
This is a first small PR of a longer-term plan I have to unify `Shape` and `Surface` code inside the U8 codebase and get it all a bit more using native ScummVM surfaces.
The rough plan is:
1. Tidy up the shape and render code - remove unused features, make it easier to analyze (this and maybe some other PRs)
1. Remove the in-memory use of RLE shapes - uncompress them on load so that we can remove 1 of the 2 separate render paths.
1. Change shapes internal representation more - from having row-level data to instead use RGBA surfaces so they can be blitted directly to the render surface
1. Change the `SoftRenderSurface` to always be a managed surface and use the line-draw/fill/blit provided by that instead
1. …

ULTIMA8: Some minor shape and render cleanups

---

engines/director/lingo/lingo-code.cpp
engines/director/lingo/lingo-code.h
engines/director/lingo/lingo.cpp
engines/director/lingo/tests/lists.lingo

This implements Lingo list math. e.g.
```
set a to [1, 2, 3]
set b to [4, 5, 6, 7]
set floats to [4.0, 5.0, 6.0, 7.0]
set strings to ["4", "5", "6", "7"]
put a + b
-- [5, 7, 9]
put a + floats
-- [5.0, 7.0, 9.0]
put a + strings
-- [5.0, 7.0, 9.0]
put a + 1
-- [2, 3, 4]
```
This also fixes a bug in Datum::toString() which caused arrays' contents to be overwritten with strings. Since Datum::toString() is called frequently, this prevented list math from working properly.

DIRECTOR: LINGO: Implement list math

---

gui/widgets/tab.cpp

Fixes #7123.
Previously the scroll buttons at extreme edges were clickable but did nothing. For example, if it were on the rightmost side, ">" would be clickable but useless. This fix addresses that.

GUI: Scroll buttons properly display at edge.

---

gui/predictivedialog.cpp
gui/predictivedialog.h

Fixes #7125
The predictive dialog box is unable to handle multiple presses via the keypad. This fixes it, only one press is allowed, and the simultaneous button presses are ignored - only the fastest one is registered.

GUI: Predictive dialog box can handle multiple keypad press

---

backends/platform/sdl/sdl-window.cpp

This is a one line fix to silence the weird 'window && window->magic == &this->window_magic' assert that gets triggered at the start of ScummVM with some SDL2 builds (for me it does that with the debug Win64 version from vcpkg).
This shouldn't have any negative impact.  Calling SDL_GetWindowWMInfo() with a nullptr parameter can't really return anything useful. Nonetheless I commit this as a pull request, so that any interested team member can comment on it.

SDL2: silence 'window magic' assert

---

engines/wintermute/detection_tables.h

Added detection for:
- Russian and Italian versions of "Art of Murder: FBI Confidential"
- GoG versions of "J.U.L.I.A: Among the Stars" and "J.U.L.I.A: Untold"
- Spanish fanmade translations of "J.U.L.I.A: Among the Stars", GoG and Steam versions
- English, Italian and Russian versions of "Ghost in the Sheet"

WINTERMUTE: Add some games versions

---

engines/griffon/dialogs.cpp
engines/griffon/draw.cpp
engines/griffon/logic.cpp
engines/griffon/resources.cpp
engines/griffon/sound.cpp

GRIFFON: Simplify rendering calls
Griffon takes many setAlpha calls in its loops to set Alpha . That wastes 
CPU resources and make the game slow. Change uilt call's params will
help.

GRIFFON: Simplify rendering calls

---

engines/ultima/module.mk
engines/ultima/ultima8/graphics/raw_shape_frame.cpp
engines/ultima/ultima8/graphics/raw_shape_frame.h
engines/ultima/ultima8/graphics/shape.cpp
engines/ultima/ultima8/graphics/shape.h
engines/ultima/ultima8/graphics/shape_frame.cpp
engines/ultima/ultima8/graphics/shape_frame.h
engines/ultima/ultima8/graphics/soft_render_surface.inl

Creating a PR for this since it's a slightly larger change and I'd like some other eyes on it.  I changed it to unpack/un-RLE the shape data on load into simpler buffers, allowing me to simplify the render code a lot as a result.

ULTIMA8: Uncompress shapes on load for simpler render path

---

engines/director/director.cpp
engines/director/director.h
engines/director/score.cpp
engines/director/score.h

The debugflag fewframesonly exits the program after running 10 frames.
This is used when running a large amount of Director programs in an
automated fashion. The example script below saves the output for further
inspection.
CAVEAT: A score is ran for 10 frames. The counter is reset if it is
switched before that.
An example script in fishshell:
```
for movie in (cat list_of_files_to_check.txt)
./scummvm --debugflags=runfirstframes -p DIRECTORY/ --start-movie=$movie workshop > output/$movie.txt 2>&1
if test $status -eq 0
echo $movie >> output/passed.txt
else
echo $movie >> output/failed.txt
end
end
```

DIRECTOR: Adds debug option to automate tests.

---

backends/platform/android/android.mk
configure
dists/android/build.gradle

With the merge of the new Gradle build system, builds running on Android 10 don't have access to SD card anymore.
When playing around, I noticed that gradle.build in android_project build directory is not updated when it is changed in source tree and various variables in configure are overriden.
These commits fix all of this and should not break existing setups (ie. buildbot should still be happy).

ANDROID: Multiple fixes for the new Gradle based build

---

backends/platform/android/events.cpp
backends/platform/android/events.h
backends/platform/android/org/scummvm/scummvm/MouseHelper.java
backends/platform/android/org/scummvm/scummvm/ScummVMEvents.java

With this PR, the Android backend now sends events for the middle, forward and back mouse buttons, as well as the primary and secondary stylus buttons. Unfortunately, on my device at least, Android maps the middle mouse button to opening the home menu, and I can't find any obvious way of working around it. I also wasn't able to test the stylus changes.
This should fix [Trac 11352](https://bugs.scummvm.org/ticket/11352).

ANDROID: Add support for additional mouse buttons

---

engines/director/director.h
engines/director/events.cpp
engines/director/lingo/lingo-the.cpp
engines/director/score.cpp
engines/director/score.h

This pull request implements tick-based timekeeping, and uses 
it to implement time-dependent `last`* Lingo functions 
(lastKey, lastClick, lastEvent, lastRoll). lastFrame is also implemented.
The respective movies from the Lingo Workshop dictionary now run properly.
The Lingo function `last` is a bit different and is not implemented in this PR.

DIRECTOR: LINGO: Implement last* functions

---

engines/director/director.h
engines/director/events.cpp
engines/director/frame.cpp
engines/director/lingo/lingo-builtins.cpp
engines/director/lingo/lingo-the.cpp
engines/director/sprite.h

This pull request implements the `moveableSprite of sprite`
property. We must thus track sprite positions based upon their 
current point and not just their start point.

DIRECTOR: LINGO: Implement moveableSprite of sprite

---

engines/director/lingo/lingo.cpp

Lingo tests can be run with:
`./scummvm -d11 -p engines/director/lingo/tests/ directortest`
This runs all the .lingo files in that directory to run in sequence.
When one script fails, the others won't run.
With this commit it's now possible to use the commandline option `--start-movie=` to run a specific lingo script.
`start-movie` already made it possible to run a specific director
movie.
The following command will only run the `c2.lingo` file.
`./scummvm -d11 -p engines/director/lingo/tests/ --start-movie=c2.lingo directortest`

DIRECTOR:LINGO: implements run only one lingo test

---

backends/platform/sdl/sdl.cpp
base/commandLine.cpp

This adds a `-l PATH` or `--logfile=PATH` command line argument to specify a custom log file. Since log files are overwritten with each launch, this could help get a more persistent one when we want to (this remove the need to copy the default one after closing ScummVM, and this also removes the need to know where the default one is ;-) ).
This may also be useful to get a more portable application as mentioned in [bug #11412](https://bugs.scummvm.org/ticket/11412).
This only works with the SDL-based  backends.
Note that for this to work I had to delay a bit the creation of the log file. It is now done in the initBackend() function instead of `OSystem_SDL::init()`. This means for example that using a command line command such as `--detect` no longer overwrites the log file (since ScummVM …

SDL: Add --logfile command line argument to specify logfile path
