- engines/zvision/zvision.cpp
ZVISION: made error messages detailed for missing files INQUIS.ZIX and MEDIUM.ZIX
> ZVISION: made error messages detailed

- engines/mortevielle/mortevielle.h
- engines/mortevielle/utils.cpp
Hi,
Here are some missing drawBox() adjustments/ They should all match original code now. Also I changed DISK_ACESS_DELAY to 1000msecs which seems to be far enough to read such a short message on screen.
Thanks!
> Small adjustments to match original code 

- engines/mortevielle/mortevielle.h
- engines/mortevielle/utils.cpp
Hi,
This addition to the code to give credits to the original authors and developers.
The font should be DOS font but it is not implemented, so I used game font instead, as done with the title screen.
Thanks!
> MORTEVIELLE: added starting screen

- devtools/scumm-md5.txt
Using http://jradventures.forumotion.com/t14-the-uk-english-dubs as source for determining which games are both available in en_us and en_gb I came up with these patches. I also marked the games which still need some more checking but which I don't have access to.
> SCUMM: language fixes for HE games

- audio/rate.cpp
- audio/rate_arm.cpp
- audio/rate_arm_asm.s
This is an updated version of PR #348 with corrections for ARM ASM.
> AUDIO: Add support for sample rates >65kHz.

- doc/de/Neues
I just updated the few stringss that changed until commit 9dbaf8d. Nothing fancy at all, just the announcement of the latest supported games and the addition of the Raspberry Pi port.
> NEWS: Update German NEWS file to address all changes made until 9dbaf8d

- README
Hello,
I found a couple dead links in `README`, here is a fixed version.
Thanks!
> README: Fix broken links

- engines/wintermute/base/base_keyboard_state.cpp
Add mappings for numpad keys, tab, pause and backspace.
Suppressed unnecessary warnings for keys that are text-input.
> WINTERMUTE: Add more keyboard mappings, fix console warnings.

- po/de_DE.po
This pull request addresses all changes introduced to the scummvm.pot template in commit 7ae0f29. I also removed two fuzzy tags I forgot to remove in my last PR.
> I18N: Update German language file updated

- doc/de/Liesmich
- doc/de/Neues
This PR updates the German README and NEWS file (Liesmich and Neues) to the very latest versions of it's English originals. Should be ready for merging before the 1.8.0 release.
best regards
rootfather
> I18N: Update German README and NEWS file

- po/pl_PL.po
Updated the Polish translation for ScummVM 1.8.0 and added proper plurals to the few strings that needed them.
> I18N: Update Polish translation

- doc/cz/PrectiMe
- po/cs_CZ.po
With this update, the Czech Readme and localization file have all the latest changes for the next release.
> I18N: Czech localization and documentation update.

- README
Missed to fix the changed chapter (5.x) sorting in main chapter list, sorry
> README: Fix wrong sorting in main chapter list

- doc/de/Neues
This PR updates the German translation of the NEWS file to the latest changes made to the original file.
> NEWS/DE: Last minute fixes

- doc/de/Neues
Import the NEWS stub for 1.9.0.
> NEWS/DE: Added stub for 1.9.0

- doc/de/Neues
The German translation of the NEWS file is now based
on the original NEWS file as of commit
e63cbdb6a7f79aeb25b2053197e060dca548a940
> NEWS: Add AGI Hercules rendering + pause feature info

- doc/de/Neues
This PR updates the German NEWS file to the current state of the original NEWS file as of commit fc8875b5962c9e187d9497f8fbb5b97f27e9d32a.
Do you cherry-pick the 1.8.1 section or should I submit those changes separately to the 1.8.1 branch?
Sorry for the delay - the last weeks have been *very* busy for me, because I had my final exam last week. Luckily, I passed everything, so I can now continue my work on the ScummVM website and localization.
Best regards
rootfather
> NEWS: Update German NEWS file

- engines/sci/detection_tables.h
Official russian translate from SoftClub
> SCI: Add Russian translate of Torin's Passage (Windows version)

- backends/platform/sdl/amigaos/amigaos-main.cpp
Adding a bit of code to make ScummVM AmiUpdate aware.
Everything else will be dealt with through a (yet to finish) AmigaOS installer script and the entries in AmiUpdate's database.
I'd like to ask for hints regarding
- Code Formatting
- Optimizations
- Comments
- Obivous errors
or
- Ill-designed code.
It's not much code, but i'm sure i still messed up glorious either way
> AMIGAOS: Preparations for use with AmiUpdate

- engines/sci/engine/script_patches.cpp
The hero is unable to tell Rakeesh and Kreesha about the Simabani initiation, which would award him 3 points.
This is caused by a heap bug in room 285: the local array of possible messages omits this message.
The patch fixes the bug by adding this message to the array.
Fixes bug #7086
> SCI: Script patch for fixing 3 missing points in QfG3

- engines/neverhood/detection.cpp
Apparently contains a placeholder song or soundtrack. Download link in the sourceforge issue tracker.
https://sourceforge.net/p/scummvm/bugs/7117/
> NEVERHOOD: Add earlier English demo of Neverhood

- engines/sci/engine/script_patches.cpp
At the base of the giant tree, when entering from the top east path, the hero can get out of bounds and walk freely in the room.
This is caused by an incorrect cutoff used to determine whether the hero entered from the top or bottom path.
The patch changes this cutoff, and prevents going out of bounds.
Fixes bug #6693
> SCI: Script patch for QfG3 giant tree bounds

- po/nl_NL.po
update to 1.9.0git and some other improvements/fixes.
> Update dutch translation

- engines/wage/entities.cpp
- engines/wage/entities.h
- engines/wage/module.mk
- engines/wage/saveload.cpp
- engines/wage/wage.cpp
- engines/wage/wage.h
- engines/wage/world.cpp
- engines/wage/world.h
This adds some save/load code (based on asvitkine/wage-engine). It works, but there is no GUI dialogs to save or load yet.
> WAGE: Add save/load code

- devtools/create_kyradat/resources/eob1_dos_italian.h
Minor translation changes from the creator of the original translation. Oldgamesitalia.net
http://www.oldgamesitalia.net/forum/index.php?showtopic=21335&st=50
> KYRA: Update Italian EOB1 translation

- dists/scummvm.appdata.xml
- ports.mk
This adds metadata for Linux software stores. See https://people.freedesktop.org/~hughsient/appdata/ for reference. My main motivation is to get you listed in https://software.opensuse.org/packages/Games
> Added an appdata.xml file

- devtools/create_project/xcode/create_project.xcodeproj/project.pbxproj
This PR fixes the compilation of the "create_project" tool under Xcode.
> CREATE_PROJECT: Fix Xcode project

- engines/scumm/he/intern_he.h
- engines/scumm/object.cpp
- engines/scumm/script_v6.cpp
- engines/scumm/scumm.cpp
Here's a proposal for fixing 3 bugs in SCUMM HE games. Feel free to cherry-pick. Feedback appreciated.
All fixes have been play-tested by me.
> SCUMM: Bugfixes

- configure
- dists/androidsdl/scummvm/AndroidBuild.sh
Enabled mt32emu for android-sdl port.
> ANDROIDSDL: Enabled mt32emu

- engines/voyeur/configure.engine
VOYEUR: remove empty first line in configure.engine
> VOYEUR: remove empty first line

- po/be_BY.po
- po/ru_RU.po
As always, I've updated Belarusian translation and have fixed some typos in Russian translation.
> I18N: Update Belarusian and Russian translations

- doc/cz/PrectiMe
- po/cs_CZ.po
I have updated the .po file with the latest changes and the ReadMe file with only minor edits.
> I18N: Czech translation update

- backends/events/androidsdl/androidsdl-events.cpp
- backends/platform/androidsdl/androidsdl-sdl.cpp
- dists/androidsdl/scummvm/AndroidAppSettings.cfg
- dists/androidsdl/scummvm/AndroidAppSettings.cfg.in
> ANDROIDSDL: Changed logic for back button & getting sdcard storage location

- engines/composer/composer.cpp
- engines/composer/composer.h
- engines/composer/detection.cpp
- engines/composer/graphics.cpp
- engines/composer/graphics.h
- engines/composer/module.mk
- engines/composer/resource.cpp
- engines/composer/resource.h
- engines/composer/saveload.cpp
This is #261 with minimal changes to make it work with the latest ScummVM code. It has only been tested with Darby the Dragon on Mac OS.
> (Updated) COMPOSER: Support GMM saving/loading and load from launcher

- backends/midi/timidity.cpp
As the title says this will port the timidity code to use `getaddrinfo` instead of `gethostbyname`.
Not even that `gethostbyname` is deprecated, but also it will limit the address resolution to one possible ip (but maybe that one is not working?) and will limit the name resolution to IPv4.
That is fixed by this commit, moreover on at least openSUSE the buildsystem warns if code is using `gethostbyname`.
Also some other minor cleanup (fixed a FIXME etc).
> BACKENDS: timidity: Get rid of gethostbyname, use getaddrinfo.

- common/error.cpp
- engines/advancedDetector.cpp
- engines/agi/detection.cpp
- engines/agos/saveload.cpp
- engines/cine/detection.cpp
- engines/dialogs.cpp
- engines/drascula/detection.cpp
- engines/drascula/saveload.cpp
- engines/dreamweb/detection.cpp
- engines/engine.cpp
- engines/gob/inter_geisha.cpp
- engines/gob/inter_playtoons.cpp
- engines/gob/inter_v2.cpp
- engines/kyra/saveload.cpp
- engines/kyra/saveload_eob.cpp
- engines/neverhood/detection.cpp
- engines/parallaction/saveload.cpp
- engines/pegasus/pegasus.cpp
- engines/sci/detection.cpp
- engines/scumm/detection.cpp
- engines/scumm/help.cpp
- engines/scumm/scumm.cpp
- engines/sherlock/detection.cpp
- engines/sword1/control.cpp
- engines/tinsel/saveload.cpp
- engines/toltecs/detection.cpp
- engines/toon/toon.cpp
- engines/zvision/detection_tables.h
- engines/zvision/file/save_manager.cpp
- gui/saveload-dialog.cpp
While redoing the dutch translation I came up with these editorial suggestions. Feedback appreciated.
> ALL: Unify messages wording

- engines/fullpipe/gfx.cpp
- engines/fullpipe/gfx.h
- engines/fullpipe/statics.cpp
> FULLPIPE: Fix leaks in surface and bitmap usage.

- engines/fullpipe/gameloader.cpp
- engines/fullpipe/gameloader.h
- engines/fullpipe/input.cpp
- engines/fullpipe/messagehandlers.cpp
- engines/fullpipe/messages.cpp
- engines/fullpipe/messages.h
- engines/fullpipe/scene.cpp
- engines/fullpipe/sound.cpp
- engines/fullpipe/sound.h
- engines/fullpipe/stateloader.cpp
This is the first of a series of PRs to plug memory leaks in Full Pipe. There are more pending changes, which will need further testing and will be submitted in separate PRs
> Fullpipe: Plug some memory leaks

- engines/director/archive.cpp
- engines/director/archive.h
- engines/director/cast.cpp
- engines/director/cast.h
- engines/director/director.h
- engines/director/frame.cpp
- engines/director/frame.h
- engines/director/images.cpp
- engines/director/images.h
- engines/director/lingo/lingo-builtins.cpp
- engines/director/lingo/lingo-funcs.cpp
- engines/director/lingo/lingo.h
- engines/director/resource.cpp
- engines/director/score.cpp
- engines/director/score.h
- engines/director/sound.cpp
- engines/director/sound.h
- engines/director/sprite.h
- graphics/macgui/macwindowmanager.cpp
- graphics/macgui/macwindowmanager.h
Initial commit of work to get D4 cast members loading. Also work on
Sounds and Cursors. The Apartment and HandV now render much better.
> DIRECTOR: Support for D4 cast and images

- backends/platform/wii/osystem.cpp
- backends/platform/wii/osystem_events.cpp
- backends/platform/wii/osystem_gfx.cpp
- backends/platform/wii/osystem_sfx.cpp
WII: Fix compiler warnings
Compiler: DevKitPPC R28
> WII: Fix compiler warnings

- engines/director/cachedmactext.cpp
- engines/director/cachedmactext.h
- engines/director/cast.cpp
- engines/director/cast.h
- engines/director/frame.cpp
- engines/director/frame.h
- engines/director/module.mk
- engines/director/score.cpp
- engines/director/score.h
- engines/director/stxt.cpp
- engines/director/stxt.h
- graphics/macgui/mactext.cpp
- graphics/macgui/mactext.h
This includes #943 and adds caching of MacTexts (one per textCast) on top.
See how you like it; consider merging this one directly if you like it.
> DIRECTOR: Cache Mactexts

- backends/platform/androidsdl/androidsdl-sdl.cpp
- dists/androidsdl/How_to_Build.txt
- dists/androidsdl/build.sh
- dists/androidsdl/scummvm/AndroidAppSettings.cfg
- dists/androidsdl/scummvm/AndroidAppSettings.cfg.in
- dists/androidsdl/scummvm/AndroidBuild.sh
- dists/androidsdl/scummvm/DataBuild.sh
> ANDROIDSDL: fixes, new features, script for build.apk, build instrictions

- engines/wage/gui-console.cpp
- engines/wage/gui.cpp
- engines/wage/gui.h
- engines/wage/wage.cpp
- graphics/macgui/macfontmanager.h
- graphics/macgui/mactext.cpp
- graphics/macgui/mactext.h
- graphics/macgui/mactextwindow.cpp
- graphics/macgui/mactextwindow.h
- graphics/macgui/macwindowmanager.cpp
- graphics/macgui/macwindowmanager.h
- graphics/module.mk
**Edit:** I have fixed the bad commits, but this should still not be merged yet, it's not complete.
I'm submitting it now because it's my GSoC qualification PR.
> WAGE: MacText integration

- engines/titanic/star_control/base_stars.cpp
- engines/titanic/star_control/dvector.h
- engines/titanic/star_control/fpose.cpp
- engines/titanic/star_control/fpose.h
- engines/titanic/star_control/fvector.h
- engines/titanic/star_control/star_camera.cpp
- engines/titanic/star_control/star_camera.h
- engines/titanic/star_control/star_closeup.cpp
- engines/titanic/star_control/star_field.cpp
- engines/titanic/star_control/star_view.cpp
- engines/titanic/star_control/viewport.cpp
- engines/titanic/star_control/viewport.h
1. Improved naming of functions
2. Improved variable names
3. Lots of comments and TODOs added for suspicious behavior
4. Changes in other classes that viewport renaming affected
5. Added saving a field for viewport that wasn't being saved
6. Move useful const variable from dvector to fvector.
7. Fpose made a useful function into non-member function.
I did most of these commits as one and then split it afterwords to make some of the changes stand out so some of the middle commits may not build.
> TITANIC: Viewport refactor

- audio/mods/mod_xm_s3m.cpp
- audio/mods/mod_xm_s3m.h
- audio/mods/module_mod_xm_s3m.cpp
- audio/mods/module_mod_xm_s3m.h
- audio/module.mk
This commit is based on https://github.com/martincameron/micromod
The principal is to convert these tracker sound formats into wav and feed it to wav decoder to make an audio stream.
> AUDIO: Import micromod code, xm/s3m/mod decoder

- image/codecs/indeo/indeo.cpp
- image/codecs/indeo3.cpp
This fixes Urban Runner on RISC OS.
> IMAGE: Support rendering Indeo videos at 15bpp

- backends/fs/riscos/riscos-fs-factory.cpp
- backends/fs/riscos/riscos-fs-factory.h
- backends/fs/riscos/riscos-fs.cpp
- backends/fs/riscos/riscos-fs.h
- backends/module.mk
- backends/platform/sdl/riscos/riscos.cpp
The POSIX filesystem doesn't handle Fat32fs drives very well.
> RISCOS: Add RISC OS filesystem

- engines/saga/detection_tables.h
- engines/saga/introproc_ite.cpp
- engines/saga/itedata.cpp
- engines/saga/itedata.h
- engines/saga/puzzle.cpp
- engines/saga/saga.cpp
This code was supplied by Darknior (hugues.fabien@gmail.com).
> SAGA: Add Code to Support French Fan Translation.

- engines/tsage/core.cpp
- engines/tsage/sound.cpp
- engines/tsage/sound.h
- engines/tsage/user_interface.cpp
This is a small collection of fixes to TsAGE engine.
There will probably be at least one more, but this clears
three of the release blockers so I wanted to get it in
front of eyes as quickly as possible for review.
> TSAGE: Various fixes

- README
1. Readme: Added function keys
2. Readme: Converting german saved from original and incompatibility between languages.
> TITANIC: Readme additions

- dists/amiga/RM2AG.rx
- Obviously AREXX doesn´t feature an ENDIF clause
- Cleaned it up a bit
- Checked and still working
> AMIGAOS: Clean up README conversion script

- engines/tucker/tucker.cpp
> TUCKER: Fix font rendering bug

- engines/tucker/locations.cpp
> TUCKER: Fix color cycling in submarine room

- engines/tucker/tucker.cpp
> TUCKER: Fix walking Royston glitch

- engines/tucker/locations.cpp
- engines/tucker/tucker.h
Fixes Trac#6641.
/cc @raziel- (you reported the bug)
> TUCKER: Fix bubbles in Plugs shop

- engines/tucker/locations.cpp
Sort of fixes Trac#6371 which is only half a bug.
> TUCKER: Fix dentist music in mall being played incorrectly

- engines/tucker/tucker.cpp
Fixes Trac#10413 and Trac#10414.
> TUCKER: Fix sentence bar offsets

- NEWS
I have never done News updates, and am not even sure if I should. So I am doing this as a PR just to be safe.
> NEWS: Mention touch controls in PS Vita port

- engines/scumm/actor.cpp
- engines/scumm/actor.h
Fixed an issue with Purple Tentacle getting stuck during the 'Hands Free' demo of MM V0.
Also did a slight cleanup and some commenting of the V0 walk function
> SCUMM: MM V0: Fix regression with PurpleTentacle in Demo

- engines/tucker/tucker.cpp
Fixes Trac#6645.
I'm pretty confident about this one but this should be tested a bit more in other places.
/cc @raziel- (you reported this bug)
> TUCKER: Fix alleyway cellar location hotspot bug

- README
Taken mostly from the wiki and from criezy´s latest additions
> README: Add notes about Quest for Glory character import

- engines/lilliput/detection.cpp
- engines/lilliput/lilliput.cpp
- engines/lilliput/lilliput.h
- engines/lilliput/script.cpp
- engines/lilliput/script.h
- engines/lilliput/sound.cpp
- engines/lilliput/sound.h
- engines/lilliput/stream.cpp
This PR adds support for 'The Adventures of Robin Hood' by Millenium Interactive.
The game is in a playable state but input handling / engine structure needs some more love
as it is still quite laggy. Also audio is not working yet.
Despite those shortcomings, its core, the scripting engine seems to be completely reversed
and implemented. Also during my play testing I haven't had any issues except those
aforementioned. I must add that I haven't played it through as I'm not that familiar with the
game yet (and the controls are quite frustrating) so there may be problems I am not aware of.
@Strangerke may be able to correct me and go into more details.
Tested on Linux 4.15.7-1-ARCH
[Playtest video (7a978b6)](https://www.youtube.com/watch?v=019tv7Dea9k)
Looking forward to your suggestions :)
> LILLIPUT: Merge of Lilliput Engine

- engines/fullpipe/modal.cpp
- engines/fullpipe/stateloader.cpp
Remove duplicate headers in two files and ordered
the headers similar to other fullpipe files.
> FULLPIPE: Reduce duplicate header includes

- engines/wintermute/base/sound/base_sound_buffer.cpp
> WINTERMUTE: Fix loading Vorbis files

- common/ptr.h
Replaces some more ptr=0 with ptr=nullptr.
> COMMON: More nullptr usage in common/ptr

- engines/sci/graphics/celobj32.cpp
> SCI32: Only enable larry scaler for LSL7

- dists/scummvm.appdata.xml
Add [OARS](https://hughsie.github.io/oars/) metadata.
> DISTS: Update appdata.xml file

- engines/tinsel/detection.cpp
Saved games inspected via the ScummVM load or save
gui will now show the year, month, day, hour, and minute
of its creation. This was already being saved in the
saved game header so no version bump is necessary.
This required adding kSavesSupportMetaInfo and
kSavesSupportCreationDate features. I also had to
add kSavesSupportThumbnail or the saved date is not
shown.
It was necessary to write querySaveMetaInfos.
> TINSEL: Show saved game creation time in load/save gui

- engines/mohawk/riven.cpp
> MOHAWK: RIVEN: Don't allow autosaving during credits

- common/language.cpp
- common/language.h
Common::UA_UKR is needed for FoxTail game at WinterMute engine
> COMMON: Added Ukrainian language

- configure
- video/theora_decoder.cpp
Reference: http://lists.xiph.org/pipermail/tremor/2010-April/001642.html
> VIDEO: Fix Theora playback when building with Tremor

- configure
- devtools/update-version.pl
- dists/win32/ScummVM.iss
- dists/win32/ScummVM.iss.in
- ports.mk
> WINDOWS: Installer updates from PR #1128

- backends/fs/psp/psp-stream.cpp
- backends/fs/psp/psp-stream.h
- backends/platform/psp/cursor.cpp
- backends/platform/psp/default_display_client.cpp
- backends/platform/psp/display_manager.cpp
- backends/platform/psp/memory.cpp
- backends/platform/psp/memory.h
- backends/platform/psp/mp3.cpp
- backends/platform/psp/osys_psp.cpp
- backends/platform/psp/png_loader.cpp
> PSP: Various updates from PR #1128

- backends/fs/chroot/chroot-fs-factory.cpp
- backends/fs/chroot/chroot-fs.cpp
- backends/fs/posix/posix-fs-factory.cpp
- backends/fs/posix/posix-fs.cpp
- backends/midi/stmidi.cpp
- backends/platform/sdl/posix/posix.cpp
- backends/saves/posix/posix-saves.cpp
- configure
Originally from PR #1128. See also: PR #1295
> FREEMINT: Fix compilation

- common/cosinetables.cpp
- common/cosinetables.h
- common/fft.cpp
- common/sinetables.cpp
- common/sinetables.h
- engines/bladerunner/bladerunner.cpp
- engines/startrek/math.cpp
- engines/startrek/startrek.cpp
1.) Sin/Cos table now takes number of points into the constructor rather than exponent of power of 2. It must now be divisible by 4.
2.) Update places that use sin/cos table.
> Sin/Cos Table update

- .gitignore
> GIT: Ignore scummvm.dwp

- engines/mutationofjb/commands/changecommand.cpp
- engines/mutationofjb/commands/ifcommand.cpp
- engines/mutationofjb/gamedata.cpp
- engines/mutationofjb/gamedata.h
- engines/mutationofjb/mutationofjb.cpp
See commit messages for more information.
> MUTATIONOFJB: Various small fixes.

- backends/fs/ps2/ps2-fs.cpp
- backends/platform/ps2/Gs2dScreen.cpp
- backends/platform/ps2/fileio.cpp
- backends/platform/ps2/ps2mutex.cpp
- backends/plugins/ps2/ps2-provider.cpp
- configure
This compiles, but has not been tested.
> PS2: Fix compilation with latest PS2SDK

- engines/sci/engine/script_patches.cpp
Fixes a broken message in floppy version
> SCI: Script patch for LB2 desk lamp, bug #10706

- engines/sci/engine/script_patches.cpp
> SCI: Script patch for LB2 act 4 init, bug #10716

- engines/sci/engine/script_patches.cpp
Fixes wrong message in cd versions, bug #10724
> SCI: Fix LB2CD Yvette/Tut murderless message

- engines/sci/engine/script_patches.cpp
> SCI: Fix LB2 'Bugs With Meat' lockup, bug #10730

- engines/sci/engine/script_patches.cpp
> SCI: Fix LB2 back rub east entrance bug #10729

- engines/sci/engine/script_patches.cpp
Fixes wrong and missing messages in DOS version
> SCI: Script patch for LB1 Lillian/bed, bug #10742

- engines/sci/engine/script_patches.cpp
> SCI: Disable LB2 speed test

- engines/sci/engine/script_patches.cpp
Fixes a missing message error in floppy version. bug #10782
> SCI32: Fix GK1 floppy Magentia missing message

- engines/sci/engine/script_patches.cpp
Fixes graphics glitch in the original game, bug #9760
> SCI32: Fix GK1 ego flicker in Gran's chair

- engines/sci/engine/script_patches.cpp
Fixes timing that cuts off speech. bug #10787
> SCI32: Fix GK1 day 1 Grace phone speech timing

- engines/sci/engine/script_patches.cpp
Fixes an incorrect message in the original. bug #10801
> SCI: Fix KQ6 look ribbon response

- engines/sci/engine/script_patches.cpp
Fixes typos that lead to Grooper::doit() arithmetic errors, bug [#10777](https://bugs.scummvm.org/ticket/10777)
> SCI32: Fix QFG4 crash when gliding across swamp

- engines/sci/engine/script_patches.cpp
Fixes a lockup in floppy version. bug #10797
> SCI32: Fix GK1 day 2 binoculars lockup

- engines/sci/engine/script_patches.cpp
Fixes audio, timing, and graphics problems in the original. bug #10793
> SCI32: Fix GK1 day 5 snake attack problems

- engines/sci/engine/script_patches.cpp
Fixes script bug in the original that kept music from completing. bug #10808
> SCI: Fix LB2CD act 5 finale music

- devtools/create_project/msvc14/create_project.vcxproj
- devtools/create_project/msvc15/create_project.vcxproj
Just something that's been bugging me for a while. :)
> CREATE_PROJECT: Remove obsolete references to msvc8

- engines/sci/engine/script_patches.cpp
Fixes the time panel never switching from night to day, bug [#10775](https://bugs.scummvm.org/ticket/10775)
> SCI32: Fix QFG4 consecutive moonrises

- engines/sci/engine/script_patches.cpp
Fixes script bug in the original in Text mode. bug #10811
> SCI: Fix KQ6CD wallflower dance bug

- dists/scummvm.6
> DISTS: Fix typo

- engines/sci/engine/script_patches.cpp
Fixes bugs in the original that lockup and crash the interpreter
> SCI: Fix QFG1VGA antwerp wandering, bug #9564

- engines/sci/detection.cpp
- engines/sci/detection_tables.h
- engines/sci/engine/kernel.cpp
- engines/sci/engine/kernel.h
- engines/sci/engine/kernel_tables.h
- engines/sci/engine/kgraphics.cpp
- engines/sci/engine/kmisc.cpp
- engines/sci/graphics/paint16.cpp
- engines/sci/graphics/paint16.h
- engines/sci/graphics/view.cpp
- engines/sci/graphics/view.h
- engines/sci/sci.cpp
- engines/sci/sci.h
Very sorry about the utter train wreck that is the last attempt.
> SCI: Add support for The Dating Pool

- engines/sci/engine/script_patches.cpp
Works around a pathfinding algorithm edge case
> SCI: Fix SQ5 drive bay pathfinding, bug #7155

- engines/sci/engine/script_patches.cpp
Fixes an obstacle not always being added to a room
> SCI32: Fix GK1 knitting basket obstacle bug #10707

- engines/illusions/detection.cpp
- engines/illusions/duckman/duckman_videoplayer.cpp
The demo can be found at https://archive.org/details/Duckman_demo
> ILLUSIONS: DUCKMAN: Add support for the demo version

- engines/sci/engine/script_patches.cpp
Updated patch comments to better explain error, as requested in #1431
> SCI32: Update QFG4 script patch description

- engines/sci/engine/script_patches.cpp
Fixes an animation script bug that occurs in the original
> SCI32: Fix GK1 mummy animation, bug #10828

- engines/sci/engine/script_patches.cpp
Fixes a script bug in the original
> SCI: Fix LONGBOW day 9 cobbler's hut, bug #10834

- engines/sci/engine/script_patches.cpp
Fixes a bug in the original that plays a scene when it shouldn't
> SCI: Fix LONGBOW Day 7 Tuck/Net scene, bug #10847

- README.md
I should probably split this into several commits before this is merged.
> README: Clean up formatting, update URLs to use HTTPS, update supported platforms list

- engines/sci/engine/script_patches.cpp
Fixes bug in original which places ego outside the room's obstacle boundary
> SCI32: Fix GK1 Wolfgang phone obstacle bug, #10853

- engines/glk/alan2/acode.h
- engines/glk/alan2/alan2.cpp
- engines/glk/alan2/alan2.h
- engines/glk/alan2/decode.cpp
- engines/glk/alan2/decode.h
- engines/glk/alan2/execute.cpp
- engines/glk/alan2/execute.h
- engines/glk/alan2/interpreter.cpp
- engines/glk/alan2/interpreter.h
- engines/glk/alan2/parse.cpp
- engines/glk/alan2/parse.h
- engines/glk/alan2/rules.cpp
- engines/glk/alan2/rules.h
- engines/glk/alan2/saveload.cpp
- engines/glk/alan2/saveload.h
- engines/glk/alan2/types.h
- engines/glk/alan2/util.h
- engines/glk/module.mk
- engines/glk/tads/tads2/data.cpp
- engines/glk/tads/tads2/data.h
- engines/glk/tads/tads2/regex.cpp
- engines/glk/tads/tads2/regex.h
Initial work on the Alan2 GLK subengine, found here:
https://www.alanif.se/
The code has been adapted from the gargoyle Alan2 subengine:
https://github.com/garglk/garglk/tree/master/terps/alan2
It's still in an early stage, and a lot of work is still needed
> GLK: ALAN2: Initial work on the Alan2 subengine

- engines/sci/engine/script_patches.cpp
> SCI: Fix LB1 attic stairs lockup, bug #9949

- engines/sci/engine/script_patches.cpp
Fixes repeat casting and combination with Summon Staff, bug [#10860](https://bugs.scummvm.org/ticket/10860)
````
// The Trigger spell stalls and never reaches handsOn when preceded by a
// successful Summon Staff. An IF block calls hero::setCycle(Beg, self), which
// cues self on completion. Its condition tests hero's "view" property and
// executes if the staff is absent. There are no means to advance when the
// staff is present.
//
// Open (script 13) is largely identical w/o this bug. We match its behavior.
//
// Due to differences between editions, this is addressed with two patches. The
// first inserts a "seconds" property assignment before the IF, where it'll
// always cue. We make room by condensing the IF conditions. There are two
// "view" comparisons. Instead of sending for it …
```
> SCI32: Fix QFG4 Trigger and Open spells

- dists/android/README.Android
The [wiki page for Android](https://wiki.scummvm.org/index.php?title=Android) will need to be updated as well, however I don't have an account, so I can't do this myself at the moment.
> ANDROID: Update the README file

- engines/sci/engine/script_patches.cpp
Fixes a lockup in the original
> SCI: Fix LB1 left staircase lockup, bug #10879

- engines/sci/engine/script_patches.cpp
Fixes a script bug that breaks messages
> SCI: Fix ECO1CD prophecy scroll, bug #10883

- engines/sci/engine/script_patches.cpp
Fixes a bug in the original that crashes the interpreter
> SCI: Fix ECO1CD Mosaic puzzle crash, bug #10884

- engines/sci/engine/script_patches.cpp
Works around a script bug that locks up the game
> SCI: Fix FPFP Mac easter egg, bug #7065

- engines/sci/engine/script_patches.cpp
Works around a script bug that prevents the game from being completed
> SCI: Fix ECO1 column puzzle, bug #10885

- engines/sci/engine/script_patches.cpp
Fixes graphics not being drawn in the CD version
> SCI: Fix ECO1CD missing ocean cliffs, bug #10893

- backends/graphics/surfacesdl/surfacesdl-graphics.cpp
- backends/graphics/surfacesdl/surfacesdl-graphics.h
- backends/graphics/wincesdl/wincesdl-graphics.cpp
Based on cad8342 and 5397eeb from PR #271
> SDL: Add a function to convert from SDL_PixelFormat to Graphics::PixelFormat

- engines/sci/detection_tables.h
Again, very sorry about all that. As I said in the other attempt:
Not even three hours after #1546, I got a bug report involving a missing sound effect that'd crash the game. Can you believe it?
> SCI: Update The Dating Pool 2019 demo

- engines/sci/engine/script_patches.cpp
Fixes several game-breaking script bugs in the bike dodging scenes
that were exposed in the CD version by slowing down the bikes.
> SCI: Fix SQ4CD bike dodging, bug #9806

- configure
- configure now tests whether or not SDL is usable by compiling a test program.
- SDL_net can now be used on platforms without sdl-config.
> CONFIGURE: Improve detection of SDL and SDL_net

- engines/glk/blorb.cpp
- engines/glk/blorb.h
- engines/glk/frotz/detection.cpp
- engines/glk/glulxe/detection.cpp
- engines/glk/magnetic/detection.cpp
- engines/glk/scott/detection.cpp
- engines/glk/tads/detection.cpp
This PR improves the detection of Blorb files by checking if the file contains a FORM type instead of looking at the file extension, as well as a more in-depth check to determine what interpreter the file should be used by.
> GLK: Improved detection of Blorb files

- engines/sci/engine/script_patches.cpp
Fixes a scene which is incompatible with our text+speech mode, bug #10241
> SCI: Fix SQ4CD Vohaul pocketpal text+speech mode

- test/common/math.h
- test/common/str.h
- test/common/util.h
COMMON: Add several missing unit tests
Add tests for Common::rad2deg, Common::deg2rad from common/math.h
Add tests for Common::isPunct from Common/util
Add more tests for Common::String (firstChar, setChar, insertChar) from common/str
> COMMON: More unit tests for common

- configure
Based on PR #1341, and adapted slightly to make use of it on RISC OS.
> CONFIGURE: allow pkg-config override

- backends/events/wincesdl/wincesdl-events.cpp
- backends/events/wincesdl/wincesdl-events.h
- backends/fs/stdiostream.cpp
- backends/graphics/dinguxsdl/dinguxsdl-graphics.cpp
- backends/graphics/wincesdl/wincesdl-graphics.cpp
- backends/mixer/wincesdl/wincesdl-mixer.cpp
- backends/platform/wince/CEDevice.h
- backends/platform/wince/CELauncherDialog.cpp
- backends/platform/wince/CEgui/GUIElement.h
- backends/platform/wince/missing/assert.h
- backends/platform/wince/missing/errno.h
- backends/platform/wince/missing/fopen.h
- backends/platform/wince/missing/missing.cpp
- backends/platform/wince/missing/time.h
- backends/platform/wince/portdefs.h
- backends/platform/wince/wince-sdl.cpp
- backends/platform/wince/wince.mk
- backends/plugins/win32/win32-provider.cpp
- common/scummsys.h
- configure
- engines/agos/script.cpp
- engines/agos/script_s1.cpp
- engines/scumm/scumm_v7.h
- engines/sky/sky.cpp
This just about compiles with [this Docker image](https://github.com/ccawley2011/scummvm-docker/tree/wince/workers/wince), but has not been tested. However, because of the large amount of bitrot resulting from the port's age and lack of a maintainer, I would be surprised if it works at all. As such, it might not be worth keeping the Windows CE port around, especially since as-is, it blocks other developments such as scaler plugins.
> WINCE: Fix compilation

- engines/sci/engine/script_patches.cpp
Fix a script bug that breaks the game when picking mushrooms or other
actions if they trigger an inventory weight warning
> SCI: Fix QFG1VGA inventory weight warn, bug #10942

- configure
Thank you for contributing to ScummVM. Please read the following carefully before submitting your Pull Request.
Make sure your individual commits follow the guidelines found in the ScummVM Wiki: https://wiki.scummvm.org/index.php?title=Commit_Guidelines. If they're not please edit them before submitting the Pull Request.
Commits and Pull Requests should use the following template:
```
SUBSYSTEM: Short (50 chars or less) summary of changes
More detailed explanatory text, if necessary.  Wrap it to about 72
characters or so.  In some contexts, the first line is treated as the
subject of an email and the rest of the text as the body.  The blank
line separating the summary from the body is critical (unless you omit
the body entirely); tools like rebase can get confused if you run the
two …
```
> Fix typo in comment

- AUTHORS
- devtools/credits.pl
- gui/credits.h
I just noticed that I wasn't listed in the credits for the GUI. But the GUI system was originally designed and written by me, as is easily verifiable by inspecting the commit logs of the gui subdirectory, or e.g. specific files like gui/widget.cpp.
> CREDITS: Added Max Horn to GUI credits

- engines/sci/engine/script_patches.cpp
Fixes a lockup in the PC version and an error in the Mac fix, bug #10958
> SCI: Fix QFG1VGA dagger game lockup and error

- AUTHORS
- devtools/credits.pl
- gui/credits.h
> Revert "CREDITS: mark Vicent Marti as retired"

- engines/sci/engine/script_patches.cpp
Another win for a well placed warning() in the engine! =)
> SCI: Fix QFG4 random revenant kopeks, bug #10966

- engines/startrek/detection.cpp
Reported by ccorbacho in trac/#10921
> STARTREK: Add detection for reported English floppy variant

- backends/platform/sdl/win32/win32.cpp
This applies DRY to the console config and avoids junk code changes seen by git.
> WIN32: Let the PE header control showing the console.

- engines/sci/engine/script_patches.cpp
Celebrating the new message workaround system with a message bug that can't be worked around.
Now you can click Look in room 381 (CD version)
> SCI: Fix SQ4 Big & Tall missing room message

- engines/sci/engine/script_patches.cpp
Fixes two similar bugs where inventory items reappear after being
used due to incorrect or missing flag checks
> SCI: Fix FPFP reappearing items, bug #10975

- engines/sci/engine/script_patches.cpp
This fixes a frequently encountered bug that subtly leaves the game in an unwinnable state. It's a regression in the CD version.
This patch does not change the game's behavior unless it's in the state where you're stuck, in which case the floppy behavior is restored and the necessary event still occurs. It took a while to work through all the surrounding events and prove that, hence the big comment.
> SCI32: Fix QFG4CD Domovoi inn events, bug #10978

- .travis.yml
Should fix running the test runner.
> TRAVIS: Install jack on Mac OS X

- engines/wintermute/detection_tables.h
Carol Reed 4 was published in Russia by "Cd Navigator":
http://www.cdnavigator.ru/Game.aspx?id=184
> WINTERMUTE: Add detection for Carol Reed Mistery 4 (RUS)

- engines/bladerunner/bladerunner.cpp
This doesn't suffer from key-repeating.
> BLADERUNNER: Skip movies on keydown not keyup

- engines/sci/graphics/view.cpp
- engines/sci/graphics/view.h
As per a suggestion by @bluegr in PR #1661
> SCI: Split out duplicated color remapping code

- engines/sci/engine/script_patches.cpp
This excludes NRS patches 53.HEP/SCR from QFG4CD since they introduce a lockup bug with wraiths. (Occurs when game-time global 88 is >= $8000.) The GOG release includes every NRS patch except this one.
The only consequence to excluding is that it can break existing save games, but since this game is tagged as unstable, and this only affects save games using this patch that also have the wraith script currently loaded, I think that's acceptable.
I think we should support the rest of the NRS patches in this game since the GOG release includes them, making them effectively a real version, and since this game is so buggy that fans are likely to have already applied them.
By "support" I just mean:
- Don't enable the "fan-made patch" warning
- Do our best to make our script patches compatible …
> SCI32: Fix QFG4 Wraith fan-patch, bug #10711

- engines/wintermute/base/base_keyboard_state.cpp
- engines/wintermute/base/file/base_disk_file.cpp
- engines/wintermute/base/scriptables/script_engine.cpp
- engines/wintermute/detection_tables.h
Add a pair of russian games made with WME by Creative Dream Studio at 2008.
More info on added games: 
(in English, announcement at WME forum)
http://forum.dead-code.org/index.php?topic=2720
(info & walkthrough, in Russian)
http://questzone.ru/enzi/game/1221
http://questzone.ru/enzi/game/1225
Both games are now completable with ScummVM!
Only a few hacks were required:
1. one path was absolute in released game, added prefix for workaround code
2. fixed IsKeyDown to support a cheat code (Ctrl+Alt+A, works with debug_mode=true only)
3. silenced a warning that was flooding console with debug_log=true
> WINTERMUTE: Support Tanya Grotter dilogy

- engines/sci/engine/script_patches.cpp
> SCI32: Fix QFG4CD Grooper crashes at inn and monolith

- engines/sci/engine/script_patches.cpp
This makes the tentacle script patch compatible with the NRS scripts that ship with the GOG release. The instructions are just too different between versions for a single signature to match, and I don't see an alternate patch approach. Without this, only one half of the patch is applied and the tentacles in this scene get stuck . 
One of the other tentacle script patches still doesn't match but that's good because the NRS version fixes that bug.
I've tested all the existing script patches for compatibility with the fan patches (whew!) and this is the only one that needs adjustment. Everything else matches and works great, which is a relief.
> SCI32: Make QFG4 tentacle patch GOG compatible

- engines/sci/engine/script_patches.cpp
For those of you wondering if the game with a bug in its very last click could also manage to break the very first...
=)
> SCI32: Fix QFG4 character selection, bug #11002

- engines/sci/engine/script_patches.cpp
This disables a timepod code that crashes the CD version because it's for a room that was removed from the game.
Normally this wouldn't be necessary, since no one will accidentally enter the *eighteen* digits, but the NRS version of SQ4 recreates this room and so the code appears on easter egg sites. People aren't reading the fine print about fan patches and think it's a regular easter egg code. Recently a video appeared on youtube of people attempting it, crashing in ScummVM as they would have in the original, and loudly blaming ScummVM.
Now that I see how easy it is to selectively enable patches by resource, which I was way wrong about, I'm doing that here. A fan version of this room's script already exists, and I love it, so if you have that as patch files then it will still work. …
> SCI: Disable SQ4 timepod code for missing room

- engines/sci/engine/script_patches.cpp
Fixes a refreshingly simple QFG4 message bug when clicking Look in room 670
> SCI32: Fix QFG4 Look-Dungeon Message

- engines/sci/detection_tables.h
SCI11 doesn't have split volumes after all. Fixes The Dating Pool.
> SCI: allow fanmade games to use resource.000

- engines/bladerunner/script/scene/ma06.cpp
Prevent confusion with function.
> BLADERUNNER: Improve variable name

- engines/wintermute/base/base_file_manager.cpp
- engines/wintermute/detection_tables.h
This PR add more detection records, mostly for 2.5D that are out of ScummVM scope.
This fixes bugs:
https://bugs.scummvm.org/ticket/6528
https://bugs.scummvm.org/ticket/6532
https://bugs.scummvm.org/ticket/6563
Fun fact: J.U.L.I.A. is using 3D features, however this game was reported as completable with VFX low
> WINTERMUTE: More detection records

- engines/sci/engine/script_patches.cpp
> SCI: Fix CAMELOT Missing Hunter points

- engines/sci/engine/script_patches.cpp
> SCI: Fix CAMELOT Fatima room messages

- engines/sci/engine/script_patches.cpp
> SCI: Fix MOTHERGOOSE Main menu crash

- engines/sci/engine/script_patches.cpp
> SCI: Fix ICEMAN 'Climb down hatch'

- engines/teenagent/teenagent.cpp
> TEENAGENT: Add the music directory to the search path

- engines/sci/engine/script_patches.cpp
> SCI: Fix CAMELOT sword sheathing during room change

- engines/sci/engine/script_patches.cpp
> SCI: Fix SQ4 Sock's dressing room obstacles

- engines/sci/engine/script_patches.cpp
> SCI: Fix SQ4CD Unstable ordnance bug

- engines/made/made.cpp
The code that used this was removed in commit 9ba6b79
> MADE: Remove unused structure

- backends/platform/sdl/amigaos/amigaos.mk
...and add another comment and clean up.
> AMIGAOS4: Properly copy the doc drawer

- backends/platform/sdl/amigaos/amigaos.mk
Forgot to add the plugins target...sorry about that :-(
> AMIGAOS4: amigaos.mk - Add plugins target

- gui/about.cpp
- gui/about.h
- gui/gui-manager.cpp
- gui/gui-manager.h
For a long while, I wanted to implement an easter egg to our About dialog. Here it goes.
Looking for your comments, on how suitable that is, or I am completely crazy here.
Request for Comments!
PS. Launch 'about', press 'v'. After browsing through the menu, use arrow keys for the character on the right. or enjoy AI (original one) entertaining you. ESC to quit.
> GUI: Easter egg

- backends/platform/sdl/amigaos/amigaos.mk
- dists/amiga/Ext_Inst_so.rexx
- dists/amiga/RM2AG.rexx
> AMIGAOS4: Automate special target installation even more

- engines/sludge/detection_tables.h
Unstable engine, unstable games.
> SLUDGE: All games are unstable, since the engine is unstable.

- backends/platform/android/android.cpp
- backends/platform/android/android.h
- backends/platform/android/events.cpp
Similar functionality is provided by the AndroidSDL backend.
> ANDROID: Add swap menu and back buttons option

- dists/amiga/Ext_Inst_so.rexx
- dists/amiga/RM2AG.rexx
Fix a bad path and some EXIT case errors
> AMIGAOS4: Fix dist scripts

- backends/platform/3ds/3ds.mk
backends/platform/3ds/shader.shbin (byproduct of "make"),
backends/platform/3ds/shader_shbin.h (byproduct of "make"),
$(TARGET).smdh (aka scummvm.smdh, byproduct of "make scummvm.3dsx"),
$(TARGET).bnr (aka scummvm.bnr, byproduct of "make scummvm.cia")
> 3DS: Add files to be removed by 3ds_clean in 3ds.mk:

- dists/amiga/RM2AG.rexx
- Fix comments
- Fix path error
- Fix output format error
> AMIGAOS4: Fix more bugs in RM2AG.rexx

- backends/fs/amigaos4/amigaos4-fs.cpp
- backends/platform/sdl/amigaos/amigaos-main.cpp
- Cleanup, formatting and more verbose debug messages
- Change printf to snprintf
- Increase stack cookie
Tested locally and working
> AMIGAOS4: Bits of cleanup

- engines/toltecs/detection.cpp
- added Czech version definition
- reported in trac:#11263
> TOLTECS: Added Czech language support

- .travis.yml
Based on https://stackoverflow.com/a/53331571
> TRAVIS: Cache homebrew packages

- engines/wintermute/detection_tables.h
Add new Steam flavours for "Reversion: The Meeting"
> WINTERMUTE: Add new Steam flavours for "Reversion: The Meeting"

- configure
This should fix the current buildbot failure.
> 3DS: Move -Wl,--gc-sections to avoid it interfering with the library checks

- engines/wintermute/detection_tables.h
Add public demos for several wintermute games
> WINTERMUTE: Add some public demos

- engines/wintermute/detection_tables.h
Added more game entries from Steam and my personal collection
> WINTERMUTE: Added more Steam references

- engines/director/lingo/lingo-builtins.cpp
- engines/director/lingo/lingo-funcs.cpp
- Convert beep called with zero arguments to beep(1)
- Beep argument starts counting at 1.
> DIRECTOR: Fix calling of Beep

- engines/wintermute/detection.cpp
Now the singleId property has been removed, the gameIds returned by a
MetaEngine when detecting games must be accepted by the `findGame`
method. Wintermute was generating gameIds based on datafiles in the
fallback detector. With this change, the gameId for fallback detected
games is always `wintermute`. The target name is generated based on the
game caption.
The `(unknown)` mention that was previously added to the game title is gone.
The unknown game dialog now makes it very clear that the game version
is not known to ScummVM.
Fixes https://bugs.scummvm.org/ticket/11288.
> WINTERMUTE: Fix fallback detection

- graphics/wincursor.cpp
A similar fix was made for PE cursors in commit 5b907e8.
> GRAPHICS: Fix loading NE cursors

- engines/griffon/dialogs.cpp
- engines/griffon/engine.cpp
- engines/griffon/input.cpp
- engines/griffon/resources.cpp
- graphics/transparent_surface.cpp
Fix crash issue when Griffon.s03 map is loaded.
> Fix final boss is sluggish and crash issue

- backends/platform/android/org/scummvm/scummvm/ScummVMActivity.java
This hasn't been properly tested, since I don't have a recent enough Android device.
> ANDROID: Hide the system mouse cursor on Android N

- engines/agi/detection_tables.h
There are 2 bug reports regarding one version of GoldRush that
wasn't recognized by the detection table.
On bug #3320, it was explained to be a pirated version. Therefore,
this update, in order to avoid further reporting of the same issue.
It closes bug #11308.
> AGI: Add pirated version of GoldRush! to detection table

- README.md
> README: Added debug console information for AGI and SCI

- backends/platform/sdl/switch/README.SWITCH
- backends/platform/sdl/switch/switch.mk
The new mode is useful for Dungeon RPG games like Lands of Lore.
When pressing R+L to switch control modes, a message pops up saying either
`Gamepad Mode - First Person RPG`
or
`Gamepad Mode - Regular`.
The message is displayed using `g_system->displayMessageOnOSD()`.
More details, using Switch as example.
Note, on Switch, B,A,Y,X are bottom,right,left,top buttons, and Plus is Start and
Minus is Select.
Compared to Switch, SDL Gamecontroller standard uses swapped A<->B and Y<->X button names.
Old regular controls (default, as before)
|Input          |Effect                                                            |
|---------------|------------------------------------------------------------------|
|Left stick     |Mouse                                                             |
|R + …
> SDL: Implement first person gamepad mode, toggle with R+L

- engines/director/lingo/lingo-builtins.cpp
Implement the following Lingo functions:
numberofchars: the string length
numberofitems: count of ','. An empty string counts as 1 item.
numberoflines: count of '\n'. An empty string counts as 1 line.
> DIRECTOR: LINGO: Add number of functions.

- engines/wintermute/ad/ad_talk_holder.cpp
Refactored AdTalkHolder code to something shorter & more readable, since copy-and-paste and out-of-loop assignments on flags seemed useless to me (Please, review this!)
Implemented additional method GetTalkSprites() that is used once in the latest FoxTail at grandma's house.
> WINTERMUTE: Refactor AdTalkHolder and implement new method for FoxTail

- engines/sci/console.cpp
- engines/sci/console.h
- engines/sci/engine/scriptdebug.cpp
`bcc` is based on `bc`, but prints in format that's can be used in
C code for patches - just copy and paste (without the address column).
> SCI: debugger: disasm - added 'bcc' parameter, to use in C code

- engines/director/lingo/lingo-code.cpp
- engines/director/lingo/lingo-codegen.cpp
Arrays can be:
- assigned to variables and 
- those variables can be fetched.
Includes implementation to `put`, i.e. print the array.
> DIRECTOR: LINGO: Implement ARRAY variable

- engines/ultima/ultima8/graphics/palette_manager.cpp
- engines/ultima/ultima8/graphics/soft_render_surface.inl
Some small changes to make whitespace style more consistent.
> ULTIMA8: Tiny whitespace fixes

- README.md
- audio/adlib.cpp
- audio/mididrv.cpp
- audio/mididrv.h
- audio/midiplayer.h
- audio/miles_adlib.cpp
- audio/miles_mt32.cpp
- audio/softsynth/eas.cpp
- audio/softsynth/fluidsynth.cpp
- audio/softsynth/mt32.cpp
- backends/midi/alsa.cpp
- backends/midi/camd.cpp
- backends/midi/coreaudio.cpp
- backends/midi/coremidi.cpp
- backends/midi/dmedia.cpp
- backends/midi/seq.cpp
- backends/midi/sndio.cpp
- backends/midi/stmidi.cpp
- backends/midi/timidity.cpp
- backends/midi/windows.cpp
- base/commandLine.cpp
- base/main.cpp
This mechanism is enabled by `--dump-midi` command line parameter.
The midi events are printed to screen, and dumped to 'dump.mid' file.
It doesn't handle SysEX events, which can be printed to screen by adding:
`  #define DEBUG_SYSEX`
> AUDIO: Added dump-midi mechanism

- engines/illusions/actor.cpp
- engines/illusions/duckman/duckman_specialcode.cpp
- engines/illusions/gamarchive.cpp
- engines/illusions/gamestate.cpp
- engines/illusions/screentext.cpp
- engines/illusions/thread.cpp
- engines/illusions/thread.h
ILLUSIONS: Fix some memory leaks
It fixes some of the memory leaks mentioned on https://bugs.scummvm.org/ticket/11237
> ILLUSIONS: Fix some memory leaks

- engines/sci/console.cpp
> SCI: debugger: disasm_addr - fixed 'bcc' parameter

- test/engines/ultima/ultima8/filesys/idata_source.h
Adding some basic unit tests for IBufferDataSource.  Didn't find any bugs in here.
> ULTIMA8: Add unit tests for IBufferDataSource

- engines/ultima/ultima8/world/item_sorter.cpp
Changed the render order logic so it only declares two items "clear" of each other if their diagonals don't overlap at all - rather than just checking the corners.  This fixes the problem of the avatar's foot disappearing under some land when in combat mode.
I also cleaned up the code to use logical operators instead of bitwise, and corrected some comments in the process of debugging this.
Note this doesn't fix 100% of cases - I still see some small problems in testing, but I confirmed they are present before this change too.
> ULTIMA8: Fix render order (stop Avatar's foot from disappearing)

- engines/ultima/ultima8/world/map.cpp
- engines/ultima/ultima8/world/map.h
I felt bad adding more copy-paste code in #2122, so I went back and refactored a bit so each added tile is only a single line.  It's still not perfect but it's a lot cleaner this way.
> ULTIMA8: Refactor adding map fixes so it's a bit cleaner

- engines/ultima/ultima8/world/current_map.cpp
A whitespace-only change.
It's helpful when setting breakpoints in the IDE to have the branch of an if statement on a new line (and I think that's the ScummVM preferred style anyway), so while debugging this file I did that on each one.
> ULTIMA8: Break if statements to new lines in CurrentMap

- backends/graphics/gph/gph-graphics.cpp
- backends/graphics/linuxmotosdl/linuxmotosdl-graphics.cpp
This was fixed in the Dingux backend in commit b080311, however the fix seems to be needed for the GPH and LinuxMoto backends as well.
> GPH/LINUXMOTO: Fix drawing the mouse cursor

- engines/ultima/ultima8/world/item_factory.cpp
There's a lot of duplicate code in the ItemFactory for configuring the constructed objects.  This removes most of it.
As a side-note this adds another use of `0` literal to mean null pointer which I don't think is great. I've got a TODO item to go through replacing such things with `nullptr` but it's kinda out-of-scope for this change.
> ULTIMA8: Remove duplicate code in ItemFactory

- engines/dragons/actor.cpp
- engines/dragons/background.cpp
- engines/dragons/bag.cpp
- engines/dragons/credits.cpp
- engines/dragons/cutscene.cpp
- engines/dragons/dragonini.cpp
- engines/dragons/dragons.cpp
- engines/dragons/dragons.h
- engines/dragons/inventory.cpp
- engines/dragons/minigame2.cpp
- engines/dragons/minigame3.cpp
- engines/dragons/minigame4.cpp
- engines/dragons/minigame5.cpp
- engines/dragons/scene.cpp
- engines/dragons/scriptopcodes.cpp
- engines/dragons/sound.cpp
- engines/dragons/specialopcodes.cpp
- engines/dragons/talk.cpp
- engines/dragons/vabsound.cpp
Replacing NULL with nullptr
Just checking with CI that there are no build failures.
> DRAGONS: replace NULL with nullptr

- engines/ultima/ultima8/audio/music_flex.cpp
- engines/ultima/ultima8/graphics/anim_dat.cpp
- engines/ultima/ultima8/graphics/base_soft_render_surface.cpp
- engines/ultima/ultima8/graphics/gump_shape_archive.cpp
- engines/ultima/ultima8/graphics/main_shape_archive.cpp
- engines/ultima/ultima8/graphics/wpn_ovlay_dat.cpp
- engines/ultima/ultima8/gumps/paged_gump.cpp
- engines/ultima/ultima8/gumps/paperdoll_gump.cpp
- engines/ultima/ultima8/gumps/widgets/edit_widget.cpp
- engines/ultima/ultima8/gumps/widgets/text_widget.cpp
- engines/ultima/ultima8/kernel/memory_manager.cpp
- engines/ultima/ultima8/usecode/uc_machine.cpp
- engines/ultima/ultima8/world/map_glob.cpp
Cleaned up a few destructors which unnecessarily set member pointers to null or empty vectors just before the object is destroyed.
I double-checked that all of these were members of their respective classes, so the change should be safe.
> ULTIMA8: Remove redundant cleanup in destructors (emptying vectors etc)

- engines/mohawk/detection_tables.h
Add detection for the Macintosh CD 'La Tartaruga e la Lepre' (The Turtle and the Hare) [Italian, English], and a demo included on it for the game 'Al mare con la Nonna' (Grandma and me)
> MOHAWK: Add detection for a Mac CD game and demo

- engines/zvision/core/events.cpp
- engines/zvision/detection.cpp
- engines/zvision/graphics/render_manager.cpp
- engines/zvision/scripting/controls/input_control.cpp
- engines/zvision/scripting/controls/input_control.h
- engines/zvision/video/video.cpp
- engines/zvision/zvision.cpp
- engines/zvision/zvision.h
This works with Zork Grand Inquisitor, but hasn't been tried with Zork Nemesis.
> ZVISION: Add keymapper support

- engines/sci/engine/vm.cpp
- engines/sci/engine/vm_hooks.cpp
- engines/sci/engine/vm_hooks.h
- engines/sci/module.mk
The current patch mechanism allows only replacing intructions in current
scripts, but not adding new instructions out of nowhere.
Thus, issue like #9646 is about to be closed as WONTFIX.
This new mechanism adds a hook on vm.cpp, before executing opcodes, and
if required, executs a new code.
It solves one of the issues of #9646, the others can be solved as well using that mechanism.
> SCI: Added new VM hook mechanism, allowing new instructions

- engines/sci/engine/savegame.cpp
- engines/sci/engine/savegame.h
> SCI: adding `stopAfterFading` to savegame, fixing #10685 and #7073

- engines/sci/sound/soundcmd.cpp
> SCI: fix #9907 by choosing queued sound with highest priority

- engines/director/lingo/lingo-builtins.cpp
Builtin getAt gets the nth item in a 1 indexed list.
> DIRECTOR:LINGO: Implement getAt

- engines/director/lingo/lingo-builtins.cpp
- engines/director/lingo/lingo-code.cpp
- engines/director/lingo/lingo-code.h
- engines/director/lingo/lingo.cpp
- engines/director/lingo/lingo.h
- engines/director/lingo/tests/lists.lingo
This pull request creates a unified Datum::compareTo() function, adds list support to the comparison operators, and implements b_max and b_min.
> DIRECTOR: LINGO: Comparison improvements

- engines/wintermute/detection_tables.h
Added new "Reversion 3 - The Return" release (Steam), including Italian language
Fixed WME version of previous release
> WINTERMUTE: Added new reversion3 release (Steam)

- backends/platform/sdl/macosx/macosx.cpp
- devtools/credits.pl
- engines/dragons/credits.cpp
- engines/dragons/credits.h
- engines/dragons/screen.cpp
- engines/dragons/screen.h
- engines/pink/cel_decoder.cpp
- engines/sci/engine/vm_hooks.cpp
- engines/ultima/ultima4/sound/music.cpp
The individual commit message state what's going on.
> A few random changes to fix warnings and a typo.

- engines/director/lingo/lingo-builtins.cpp
- engines/director/lingo/lingo-code.cpp
- engines/director/lingo/lingo-code.h
- engines/director/lingo/lingo-codegen.cpp
- engines/director/lingo/lingo.cpp
- engines/director/lingo/lingo.h
- engines/director/types.h
This pull request implements Lingo property array functions, and updates other array functions to act appropriately on property arrays. Updates to the tests are forthcoming.
> DIRECTOR: LINGO: Implement property array functions

- devtools/create_project/cmake.cpp
- devtools/create_project/create_project.cpp
- devtools/create_project/xcode.cpp
This PR follows @criezy 's suggestion in https://github.com/scummvm/scummvm/pull/2208 
Note:
I have checked it in VS. However, I don't have a Mac, so XCODE changes weren't verified.
> DEVTOOLS: add fribidi library support to create_project

- audio/mods/module_mod_xm_s3m.cpp
- audio/mods/module_mod_xm_s3m.h
Creating a PR for comments - I want to hear opinions as I'm adding functionality to something which was previously a fairly clean import of the micromod/ibxm player code.
This plays the Asylum AMF files *pretty* well, but there's still a bug with some instruments I haven't worked out.  The drums in the menu music sound a bit wrong.
The ibxm player also doesn't support loop points, so it would be nice to add them.  That would be a different change though.
> AUDIO: Add support for loading Crusader AMF files

- common/language.cpp
- common/language.h
- engines/wintermute/detection_tables.h
Added new reversion1 and reversion3 Steam releases.
Also added support for a new language: Serbian
> WINTERMUTE: Add new reversion Steam releases

- engines/wintermute/base/base_file_manager.cpp
Added a missing check to fully support the new Serbian reversion1 release
> WINTERMUTE: Fix for the new Serbian game

- engines/petka/detection_tables.h
> PETKA: Flag demo as demo

- engines/sci/sound/midiparser_sci.cpp
- engines/sci/sound/midiparser_sci.h
- engines/sci/sound/music.cpp
This fixes a regression from 3154d57. The fix is based on my findings in the QFG1 DOS disasm (counterchecked a bit with PQ2 DOS disasm).
> SCI: fix bug #11476 (QFG1: Incomplete Music)

- engines/wintermute/detection_tables.h
Added Steam releases of "James Peris: No License Nor Control - Definitive Edition"
> WINTERMUTE: Added jamesperis Steam releases

- engines/sci/detection_tables.h
- engines/sci/engine/script_patches.cpp
- engines/sci/engine/vm.cpp
- engines/sci/engine/vm_hooks.cpp
- engines/sci/engine/vm_hooks.h
- engines/sci/event.cpp
- engines/sci/graphics/controls16.cpp
- engines/sci/graphics/menu.cpp
- engines/sci/graphics/text16.cpp
- engines/sci/parser/vocabulary.cpp
- engines/sci/parser/vocabulary.h
- vm_hooks: fully support `call*`
- make required changes to support Hebrew SQ3 (which is still a WIP project)
* Thanks @BLooperZ  for his help with this project!
I know you're all eager to see a screenshot ;-)
> SCI: Improve vm_hooks ; Support Hebrew SQ3

- engines/director/director.cpp
- engines/director/ink.cpp
- engines/director/score.cpp
- engines/director/sprite.cpp
- graphics/macgui/macwindowmanager.cpp
- graphics/macgui/macwindowmanager.h
This PR fixes several artefacts and segfaults noticed in Warlock, related to the new approach to rendering that I implemented a while ago.
> DIRECTOR: Fix regressions on channel-based rendering

- common/encoding.cpp
There was a bug when trying to convert the Hebrew string `"\e0\e1\e2"`
from WINDOWS-1255 to UTF-32LE, because there was a last call to
`iconv` with `NULL`s, without error checking, and the buffer needed to
be extended for that last one call.
Now this call is inserted to the main `iconv` loop, with error checking.
> COMMON: Encoding::convertIconv - check errors on last call to `iconv`

- backends/graphics/surfacesdl/surfacesdl-graphics.cpp
`Image::writePNG()` and `Image::writeBMP()` already convert the passed surface to the correct format, making it unnecessary to do so using SDL's conversion functions.
> SDL: Simplify code for taking screenshots

- engines/director/lingo/lingo-bytecode.cpp
cb_thepush2 pushes the value of an entity to the stack.
> DIRECTOR: LINGO: Implement cb_thepush2

- engines/gob/detection/tables_gob1.h
> GOB: Add detection for new Gobliiins CD-i variant

- engines/director/cast.cpp
- engines/director/score-loading.cpp
unk1 in loadCastDataVWCR is probably a flag, based on D4Player.
https://github.com/renaldobf/D4Player/blob/master/src/director/cast.c#L90
> DIRECTOR: Move flag loading to casts itself for D4.

- backends/text-to-speech/linux/linux-text-to-speech.cpp
- backends/text-to-speech/linux/linux-text-to-speech.h
- configure
This fixes [Trac #11347](https://bugs.scummvm.org/ticket/11347).
> POSIX: Support building with TTS support on FreeBSD

- graphics/managed_surface.cpp
- graphics/managed_surface.h
- graphics/screen.cpp
These changes are needed by and have been tested with [the WIP Biik engine I'm working on](https://github.com/ccawley2011/scummvm/tree/biik), however I haven't verified these changes with any other engines.
> GRAPHICS: Improve mask and palette handling in ManagedSurface

- engines/director/cast.cpp
- engines/director/cast.h
- engines/director/castmember.cpp
- engines/director/castmember.h
- engines/director/channel.cpp
- engines/director/channel.h
- engines/director/cursor.cpp
- engines/director/events.cpp
- engines/director/lingo/lingo-the.cpp
- engines/director/score.cpp
- engines/director/sprite.cpp
- graphics/macgui/macbutton.cpp
- graphics/macgui/mactext.cpp
- graphics/macgui/macwidget.cpp
- graphics/macgui/macwindowmanager.cpp
- graphics/macgui/macwindowmanager.h
DIRECTOR: Move widgets from cast members to channels
This change is required to support copies of the same cast member running in different channels.
> DIRECTOR: Move widgets from cast members to channels

- engines/director/lingo/lingo-code.cpp
- engines/director/lingo/tests/lists.lingo
c_itemOf returns the specified item in a chunk expression.
A chunk expression is any sequence of characters delimited by
commas. It's 1 indexed in director.
Edge cases:
< 1 returns the whole chunkExpression and
> number of chunks return ""
> DIRECTOR: LINGO: Implement c_itemOf

- engines/glk/adrift/detection_tables.h
If this is wrong, please tell and reject
> GLK: ADRIFT - Move known v5 game to unsupported list

- engines/agi/font.cpp
> AGI: Issue GUI warning when there is a missing Hercules font

- backends/graphics/surfacesdl/surfacesdl-graphics.cpp
- backends/graphics/surfacesdl/surfacesdl-graphics.h
- backends/platform/android/android.cpp
- backends/platform/android/android.h
- backends/platform/android/events.cpp
- common/mutex.cpp
- common/mutex.h
- common/str.cpp
- engines/lure/sound.cpp
- engines/lure/sound.h
- engines/testbed/misc.cpp
- engines/testbed/misc.h
- engines/tony/gfxcore.h
- engines/tony/inventory.cpp
- engines/tony/inventory.h
- engines/tony/loc.cpp
- engines/tony/loc.h
The changes to the Tony engine haven't been tested, but it should work fine.
> ALL: Remove direct use of OSystem::createMutex()

- engines/bbvs/detection.cpp
- engines/bbvs/minigames/bbloogie.cpp
- engines/bbvs/scene.cpp
This partially fixes [Trac #11599](https://bugs.scummvm.org/ticket/11599). Only the longer demo is covered by this PR.
> BBVS: Add support for the demo version

- engines/sci/parser/vocabulary.cpp
> SCI: Hebrew - add prefix rule (second letter is Yud)

- engines/hdb/detection.cpp
- engines/hdb/hdb.cpp
- engines/hdb/input.cpp
- engines/hdb/input.h
- engines/hdb/menu.cpp
- engines/hdb/menu.h
This fixes [Trac#11622 ](https://bugs.scummvm.org/ticket/11622).
> HDB: Add keymapper support

- devtools/credits.pl
Alternatively you can simply remove the handle.
I'll leave the decision to you guys
> CREDITS: Fix handle

- backends/platform/psp/image_viewer.cpp
- backends/platform/psp/input.cpp
- common/ustr.cpp
- Fix compilation for PSP
- Fix incorrect usage of %i in U32::vformat
> GUI: U32: Fix issues

- engines/cine/cine.cpp
- engines/cine/detection_tables.h
- engines/cine/main_loop.cpp
- engines/cine/various.cpp
- engines/cine/various.h
Hi!
Here are a few bug fixes for Operation Stealth to the branch-2-2.
The fixes are related to the bugs #11466, #11617, #11621 and #11625.
I am not 100% sure how the handling of pull requests and bug fixes
is done with ScummVM related to a particular upcoming release so
please could you inform me of anything relevant. Thank you!
Kari Salminen
> CINE: Fixes to branch-2-2 for #11466, #11617, #11621 and #11625.

- engines/wintermute/ext/plugins.h
- engines/wintermute/ext/wme_commandlinehelper.cpp
- engines/wintermute/ext/wme_commandlinehelper.h
- engines/wintermute/module.mk
- engines/wintermute/persistent.cpp
Added basic support for Commandline helper plugin (wme_commandlinehelper.dll) used by "Pizza Morgana: Episode 1" game.
This allow start game in free demo mode.
> WME: Added Commandline helper plugin for "Pizza Morgana: Episode 1" game

- engines/sci/engine/vm_hooks.cpp
solves one of the issues described at #11265 - the puker alien's sound is still heard on next room
> SCI: SQ4 intro - stop puker alien's sound

- backends/platform/symbian/S60v3/ScummVM_common.mmh
- backends/platform/symbian/S60v3/ScummVM_pt1.rss
- backends/platform/symbian/S60v3/ScummVM_pt1_reg.rss
- backends/platform/symbian/S60v3/ScummVM_pt2.rss
- backends/platform/symbian/S60v3/ScummVM_pt2_reg.rss
- backends/platform/symbian/S60v3/ScummVM_pt3.rss
- backends/platform/symbian/S60v3/ScummVM_pt3_reg.rss
- backends/platform/symbian/S60v3/ScummVM_pt4.rss
- backends/platform/symbian/S60v3/ScummVM_pt4_reg.rss
- backends/platform/symbian/S60v3/build_config.mmh
- backends/platform/symbian/src/SymbianActions.cpp
- backends/platform/symbian/src/SymbianActions.h
- backends/platform/symbian/src/portdefs.h
Symbian: silence more warnings from SDK headers.
Symbian: add new project files.
> Symbian: fix incorrect return type in SymbianActions::actionName().

- backends/events/gph/gph-events.cpp
- backends/events/openpandora/op-events.cpp
The changes made here were accidentally left out of a1648cbb97b6e100486afa8654c3fb3b3e16ed28.
> GPH/OPENPANDORA: Minor cleanup

- configure
> CONFIGURE: Enable additional functionality on OpenBSD

- backends/platform/sdl/amigaos/amigaos.mk
- configure
- Stole a setting from MorphOS :-)
- Moved MorphOS further down to keep the alphabetic order intact ;-)
Also, indented comments seem to work now in AmigaOS shell
> AMIGAOS/MORPHOS: Add non-debug build optimization and fix ordering

- engines/director/detection.cpp
> DIRECTOR: Show the unknown game dialog for fallback detection entries

- engines/sci/detection_tables.h
> SCI: Add another detection entry for Betrayed Alliance 1.2

- engines/agi/appleIIgs_timedelay_overwrite.h
> AGI: Mixedup 2gs - fix Jack and Jill cutscene (issue #11210)

- common/rect.h
They're convenient for performing computations and I use
them in Hades Challenge engine
> Add division and multiplication operators to Common::Point

- backends/base-backend.cpp
- backends/base-backend.h
- backends/platform/3ds/osystem-graphics.cpp
- backends/platform/3ds/osystem.h
- backends/platform/dc/dc.h
- backends/platform/dc/display.cpp
- backends/platform/ds/arm9/source/osystem_ds.cpp
- backends/platform/ds/arm9/source/osystem_ds.h
- backends/platform/iphone/osys_main.h
- backends/platform/iphone/osys_video.mm
- backends/platform/n64/osys_n64.h
- backends/platform/n64/osys_n64_base.cpp
- backends/platform/psp/osys_psp.cpp
- backends/platform/psp/osys_psp.h
- backends/platform/wii/osystem.h
- backends/platform/wii/osystem_gfx.cpp
> BACKENDS: Move default implementations of getScreenPixelBuffer into BaseBackend

- engines/wintermute/detection_tables.h
- engines/wintermute/keymapper_tables.h
This adds detection & keymaps for "Red Comrades 0.2: Operation F." fangame.
Project site: https://vk.com/petkafans 
Forum thread: https://petka.ucoz.com/forum/6-369-1 
Download link 1: https://www.dropbox.com/s/emyuw64c9u5zf40/Petka02_demo1.zip?dl=0 
Download link 2: https://www.dropbox.com/s/72bz2prnuxej7j0/P15_demo_0007.zip
> WINTERMUTE: Add "Red Comrades 0.2: Operation F." demos

- engines/stark/module.mk
> STARK: Allow module to be built as a plugin

- backends/graphics/sdl/sdl-graphics.cpp
- backends/graphics/sdl/sdl-graphics.h
- backends/graphics3d/sdl/sdl-graphics3d.cpp
- backends/platform/sdl/sdl-window.cpp
- backends/platform/sdl/sdl-window.h
> SDL: Implement lockMouse() in the 2D graphics managers

- engines/prince/sound.cpp
BUG: https://bugs.scummvm.org/ticket/11771
This conversation have no audio files, because it is performed using gestures. So it shouldn't try to load audio.
> PRINCE: fix bug in the conversation with the priest

- engines/access/events.cpp
they are used later on already to fill the allocated memory
> ACCESS: replaced magic numbers with contants

- backends/platform/sdl/sdl-window.cpp
- backends/platform/sdl/sdl-window.h
This should fix [Trac #11893](https://bugs.scummvm.org/ticket/11893).
> SDL: Fix the mouse being grabbed when returning from full screen

- engines/plumbers/detection.cpp
- engines/plumbers/plumbers.cpp
- engines/plumbers/plumbers.h
- engines/sherlock/module.mk
- engines/sherlock/scalpel/scalpel.cpp
- engines/sherlock/scalpel/scalpel_talk.cpp
- image/cel_3do.cpp
- image/cel_3do.h
- image/module.mk
- video/3do_decoder.cpp
- video/3do_decoder.h
- video/module.mk
It was fun to reverse engineer but the game is garbage, so I didn't test
it a lot, please report bugs.
Currently missing parts:
* effect when changing between scenes
* 3DO boot logo
* return to previous scene
* hide cursor
> PLUMBERS: support for 3DO version

- po/ko.po
I was making a bunch of suggestions on https://translations.scummvm.org, then I realized that it would be easier to edit the translation file manually.
So this is (hugely) updated Korean translation.
Almost all GUI strings are done, port-specific and engine-specific strings are in progress.
There are inconsistencies here and there, so I might make additional PRs.
> I18N: Update Korean translation

- engines/hadesch/hadesch.h
- engines/hadesch/herobelt.h
- engines/hadesch/metaengine.cpp
- engines/hadesch/persistent.h
- engines/hadesch/rooms/crete.cpp
- engines/hadesch/rooms/ferry.cpp
- engines/hadesch/rooms/medisle.cpp
- engines/hadesch/rooms/monster.h
- engines/hadesch/rooms/monster/cyclops.cpp
- engines/hadesch/rooms/monster/illusion.cpp
- engines/hadesch/rooms/monster/typhoon.cpp
- engines/hadesch/rooms/walloffame.cpp
- engines/hadesch/video.h
This fixes global constructors, struct/class differences and anonymous enums
> HADESCH: fix series of warnings and couple of build failures

- common/random.cpp
- common/random.h
- engines/hadesch/persistent.cpp
- engines/hadesch/pod_image.cpp
- engines/hadesch/rooms/crete.cpp
- engines/hadesch/rooms/daedalus.cpp
- engines/hadesch/rooms/medisle.cpp
- engines/hadesch/rooms/minotaur.cpp
- engines/hadesch/rooms/monster.cpp
- engines/hadesch/rooms/monster/illusion.cpp
- engines/hadesch/rooms/monster/projectile.cpp
- engines/hadesch/rooms/monster/typhoon.cpp
- engines/hadesch/rooms/quiz.cpp
- engines/hadesch/rooms/troy.cpp
- engines/hadesch/rooms/walloffame.cpp
- engines/hadesch/video.cpp
Fixes all MSVC warnings and many on minor platforms
> HADESCH: Warning pass

- engines/sci/detection_tables.h
> SCI: Add Macintosh version of Hoyle 1

- README.md
Fix a small typo causing the link to not work.
> TLJ: Fix internal link in README.md

- engines/sci/resource.cpp
The resource validation fails big time because no file Data9 exists.
It's expected as its in Data9.bin instead. Since we check resource fork
explicitly in the case of resource-fork resources this check is redundant
> SCI: Fix crash when running sq6-mac with macbinary

- engines/grim/gfx_opengl_shaders.cpp
Currently when saving on EMI (gles2 only), screenshot is not correctly
stored. When going in "Load game", screenshot is a black blank image.
This commit fixes this problem.
<details>
Before
After
</details>
> EMI: Fix screenshot when saving on ES2

- backends/platform/android3d/jni-android.cpp
- backends/platform/android3d/jni-android.h
SAF was added to android but not android3d yet it is in both cases
in posifxfs.
Merging android and android3d will be a separate project
> ANDROID: Fix android3d compilation

- backends/platform/iphone/iphone_common.h
- backends/platform/iphone/iphone_video.mm
- backends/platform/iphone/osys_main.cpp
- backends/platform/iphone/osys_main.h
- backends/platform/iphone/osys_video.mm
This is based on commit 2882424306bfb8a85a211002394611d3a6b4ac9b. This has not been tested.
> IPHONE: Use kFeatureFilteringMode to toggle filtering

- engines/kyra/resource/resource_intern.cpp
- engines/kyra/sound/drivers/audstream.cpp
Russian translation of MR dumbs out aud files, so don't attempt to read them
> KYRA: Add a sanity test for aud files

- backends/platform/sdl/psp2/psp2-main.cpp
Add support for booting a pre configured game directly via a custom bubble similar to RetroArch on the PSVita.
@rsn8887 Here's the new PR with 1 single commit.
> VITA: add support for booting game directly via bubble

- configure
This matches commit da77bfd7928f47438063e5e2d7ffffdc40e0c7d2 in real code.
> CONFIGURE: Fix TTS detection with Mingw

- engines/bbvs/detection.h
GF_GUILANGSWITCH and GF_LOOGIE_DEMO have the same value and hence the code
treats Russian version as loogie demo and crashes as bbloogie.000 is in
an unexpected directory for the demo
> BBVS: Fix misdetection of Russian version as demo

- engines/agi/detection_tables.h
https://realityonthenorm.info/game.php?id=115
> Add The Sorceror's Appraisal to detection table

- NEWS.md
- backends/dialogs/morphos/morphos-dialogs.cpp
Add news fetures to MorphOS port
And remove include "common/encoding.h" in morphos-dialogs.cpp
> MORPHOS: update NEWS.md

- engines/sci/detection_tables.h
Russian version can be downloaded here: &lt;link&gt;
> SCI: Add Conquests of the Longbow Russian detection table entry

- engines/sci/detection_tables.h
> SCI: Add alternative SQ5 Russian release

- doc/doxygen/groups.dox
- image/bmp.h
- image/cel_3do.h
- image/iff.h
- image/image_decoder.h
- image/jpeg.h
- image/pcx.h
- image/pict.h
- image/png.h
- image/tga.h
There is only one file in this folder that is in scope of
GSoD - image_decoder.h. It was in great shape docwise though,
so not much review required.
The rest of the headers have received a doxy group definition.
@criezy
> DOXYGEN: Doxy work on files from 'image'

- doc/doxygen/groups.dox
- doc/doxygen/scummvm.doxyfile
- graphics/VectorRenderer.h
- graphics/VectorRendererSpec.h
- graphics/conversion.h
- graphics/cursor.h
- graphics/cursorman.h
- graphics/font.h
- graphics/fontman.h
- graphics/korfont.h
- graphics/maccursor.h
- graphics/managed_surface.h
- graphics/palette.h
- graphics/pixelbuffer.h
- graphics/pixelformat.h
- graphics/renderer.h
- graphics/screen.h
- graphics/sjis.h
- graphics/surface.h
- graphics/thumbnail.h
- graphics/transparent_surface.h
- graphics/wincursor.h
- graphics/yuv_to_rgb.h
Editing doxygen comments in:
- cursorman.h
- font.h
- managed_surface.h
- pixelformat.h
- surface.h
Still working on other files but pushing what I have now.
> DOXYGEN: Review of high prio files from graphics

- audio/audiostream.h
- audio/fmopl.h
- audio/mididrv.h
- audio/midiparser.h
- audio/midiparser_qt.h
- audio/midiplayer.h
- audio/miles.h
- audio/mixer.h
- audio/mixer_intern.h
- audio/mt32gm.h
- audio/musicplugin.h
- audio/rate.h
- audio/timestamp.h
- doc/doxygen/groups.dox
This PR has 3 headers in scope of GSoD.
The files are:
- audiostream.h
- mixer.h
- timestamp.h
The rest of the files are only receiving a doxy group.
> DOXYGEN: Review headers from 'audio'

- base/plugins.h
- doc/doxygen/groups.dox
- doc/doxygen/mainpage.dox
- doc/doxygen/scummvm.doxyfile
- engines/sci/engine/kernel.h
This commit introduces a couple tweaks to the
doxygen build configuration to assure the
overall structure looks correct.
@criezy @Mataniko @sev-
> DOXYGEN: Fix the build output and structure

- NEWS.md
- configure
Thanks Raziel to see that on AmigaOS platform :-)
> MorphOS: active nuked OPL Adlib driver

- devtools/create_xeen/clouds.cpp
- devtools/create_xeen/constants.cpp
- devtools/create_xeen/create_xeen.cpp
- devtools/create_xeen/map.cpp
> XEEN: Various create_xeen janitorial work

- engines/scumm/he/localizer.cpp
- engines/scumm/he/localizer.h
- engines/scumm/he/script_v72he.cpp
- engines/scumm/metaengine.cpp
- engines/scumm/module.mk
- engines/scumm/scumm.cpp
- engines/scumm/scumm.h
- engines/scumm/string.cpp
This was used by Russian translation of Pajama Sam 2 and Spy Fox 3
> SCUMM: Support Lokalizator plugin.

- engines/director/detection_tables.h
First released in Taiwan by InterServ prior to English release.
> DIRECTOR: Add detection for original Chinese Karma

- engines/kyra/sound/drivers/adlib.cpp
Name all unknown variables and callback methods except a few that don't do anything useful.
I'm not very good at naming things, so I don't mind if somebody comes up with further improvements, but the code should be easier to understand than before.
Also includes two small checks I missed for the last PR.
> KYRA: Name most unknowns in AdLib driver

- engines/startrek/action.h
x86 uses signed chars but this is architecture-dependent and on arm it's
unsigned and leads to compilation failure
> STARTREK: Specify that action is signed char

- engines/hadesch/configure.engine
Aggregate initialization for classes with constructor requires C++11
> HADESCH: Mark the engine as C++11 dependent

- devtools/create_xeen/cc.cpp
- devtools/create_xeen/create_xeen.cpp
- devtools/create_xeen/swords.cpp
- engines/xeen/debugger.cpp
- engines/xeen/dialogs/dialogs_query.cpp
- engines/xeen/dialogs/please_wait.cpp
- engines/xeen/files.cpp
- engines/xeen/sound.cpp
- engines/xeen/sound_driver.cpp
- engines/xeen/sound_driver.h
- engines/xeen/sound_driver_adlib.cpp
The goal of these changes is to fix all files that are in the "B" quality level or worse for the Xeen engine & creation tool. I noticed other small problems while working on that I also fixed.
> XEEN: Fix many codacy issues

- engines/dialogs.cpp
> ENGINES: fix wrong parameter in constructor.

- engines/sci/graphics/controls16.cpp
> SCI: RTL: right align entries in drawListControl

- backends/keymapper/keymap.cpp
- base/commandLine.cpp
- base/plugins.cpp
- common/config-manager.cpp
- common/config-manager.h
- common/hashmap.cpp
- common/hashmap.h
- engines/advancedDetector.cpp
- engines/cryomni3d/font_manager.cpp
- engines/cryomni3d/versailles/engine.cpp
- engines/grim/pool.h
- engines/myst3/database.cpp
- engines/petka/q_manager.cpp
- engines/sci/engine/seg_manager.cpp
- engines/sci/resource/resource.cpp
- engines/sci/resource/resource_audio.cpp
- engines/stark/resources/location.cpp
- engines/wage/randomhat.cpp
- graphics/macgui/macfontmanager.cpp
- gui/launcher.cpp
Refactoring the getVal function as seen in HashMap and ConfMan. It is now an error to try to get the value of an unknown key, with the variant for getting a default being called out by name. There is a separate `getValOrDefault` function for when a default is actually requested.
> ALL: HashMap & ConfMan getVal refactoring

- backends/module.mk
> MORPHOS: fix module.mk

- README.md
Fix few broken links from the table of contents to their respective subsections in README.md
> README: Fix broken links in Table of Contents

- configure
- ports.mk
Following @ccawley2011 work, this is a batch of backports which should fix remaining problems with stable in new Buildbot.
> Backports for stable

- devtools/steam_achivements.py
This script automatically extracts the needed entries for the steam achievements from e.g. https://steamdb.info/app/212050/stats/
It currently uses the macros found in the AGS `achivements_tables.h` file.
Just give it the steam game id as parameter followed by the scummvm game id
Also see this PR: https://github.com/scummvm/scummvm/pull/2815
We could even auto create the full list of achievements if we could look up the detection entries for steam game ids.
`./steam_achivements.py 212050 resonance`
Example output:
```
~/dev/scummvm$  ./devtools/steam_achivements.py                                                                                                                                                                                                     
missing steam game id as first …
```
> DEVTOOLS: added script to create steam achievement table

- configure
Reduces link time significantly.
Times comparison:
Linux+SSD
=========
ld: 14.2s
gold: 4.5s
lld: 1.7s
Windows+HDD
===========
ld: 110s
lld: 7s
> BUILD: Support LLD linker in configure (opt-in)

- engines/agi/sound_midi.cpp
Makes sound_midi.cpp respect VM_FLAG_SOUND_ON
> AGI: MIDI sound - turn sounds off if requested

- engines/lure/sound.h
> LURE: Remove unused private member

- engines/lure/hotspots.cpp
> LURE: Fix misleading indentation

- engines/glk/comprehend/comprehend.h
- engines/glk/comprehend/game_oo.cpp
- engines/glk/comprehend/game_oo.h
- engines/glk/quest/geas_util.cpp
- engines/glk/quest/geas_util.h
> GLK: Remove unused private members and one define

- graphics/tinygl/zblit.cpp
With logic similar to the copy ctor.
> TINYGL: Implement a real operator=

- engines/glk/quest/string.h
> GLK: Fix copy assignment operator warning once again

- engines/dragons/midimusicplayer.cpp
- engines/dragons/midimusicplayer.h
- engines/dragons/sound.cpp
> DRAGONS: Remove unused private member

- engines/ultima/ultima4/meta_engine.cpp
Amends commit e403c7c6f51b2ed5758078ff4d528a2bb3317dcf.
> ULTIMA: Remove unused global

- engines/glk/level9/os_glk.cpp
- engines/glk/magnetic/glk.cpp
> GLK: Fix unused variable warnings

- doc/docportal/other_platforms/ios.rst
Cherry-picked from master.
Proposed as a pull request since I cannot push directly to branch-2-2 (it tells me the branch is protected).
> DOCS: Fix link to the iOS Libraries

- graphics/macgui/mactext.cpp
- graphics/macgui/mactext.h
it now can deal with the word with many font
it now can deal with multi paragraph and had it`s own wrapping
empty string and sequence of \n is tested
> GRAPHICS: MACGUI:: fix the bug of dealing with long word in MacText

- engines/sci/detection_tables.h
HebrewAdventure team has finished translation of QFG1VGA:
> SCI: Added fan made Hebrew translation for QFG1VGA

- engines/private/code.cpp
> PRIVATE: Fix potentially uninitialized variable on release build

- devtools/md5table.cpp
- engines/scumm/detection_internal.h
- engines/scumm/detection_steam.h
- engines/scumm/detection_tables.h
- engines/scumm/scumm-md5.h
Pre-included files are not reliable.
> SCUMM: Add some missing includes

- engines/grim/textobject.cpp
> GRIM: improve RTL support for Hebrew fan translation

- base/main.cpp
This fixes a regression from PR #2754.
> BASE: Fix a crash when attempting to run a disabled engine

- graphics/macgui/macwindow.cpp
Amends commit 0443d5a133e571b3937ba3ca2d045708448a77ca.
Detected by Clang.
> GRAPHICS: Remove unused const

- gui/gui-manager.cpp
> GUI: Fix GCC warning

- engines/tsage/blue_force/blueforce_logic.cpp
- engines/tsage/detection_tables.h
> TSAGE: BlueForce bugfix and Ringworld Spanish improved detection

- engines/wintermute/base/gfx/osystem/render_ticket.cpp
- graphics/conversion.cpp
- graphics/conversion.h
- graphics/surface.cpp
- graphics/surface.h
- graphics/transparent_surface.cpp
- graphics/transparent_surface.h
> GRAPHICS: Move rotoscale code out of TransparentSurface

- doc/docportal/_static/version.js
- doc/docportal/use_scummvm/taskbar_integration.rst
> DOCS: minor fixes 

- doc/docportal/advanced_topics/configuration_file.rst
> DOCS: removes accidental extra column on Config page

- graphics/svg.cpp
> GRAPHICS: Fix SVG rendering on big endian

- engines/agos/res_snd.cpp
- engines/agos/script_s1.cpp
Slightly increase the destination buffer to satisfy the theorical
copy of 5 characters for a 16-bit value.
> AGOS: Fix format-overflow warnings

- engines/scumm/script_v5.cpp
- engines/scumm/verbs.cpp
> SCUMM: Fix unclickable centered verbs

- graphics/macgui/macmenu.cpp
- graphics/macgui/macmenu.h
- graphics/macgui/macwindowmanager.cpp
add intersection check with macmenu and macwindow
fix the offset problem
> GRAPHICS: MACGUI: fix the incorrect behaviour of macmenu in wage

- engines/lure/detection.cpp
Buildbot failed on latest commit: https://buildbot.scummvm.org/#/builders/73/builds/1064
> LURE: Fix compilations on platforms without TTS

- engines/director/lingo/lingo-builtins.cpp
after the normilization of path style, we either get a relative path to the current directory, or get an absolute path, so we try to match the path with the game directory, and then do the things we want
> DIRECTOR: fix the builtin command NthFileName of lingo

- engines/scumm/actor.cpp
> SCUMM: Workaround missing subtitle in The Dig

- graphics/macgui/mactext.cpp
- graphics/macgui/mactext.h
- graphics/macgui/mactextwindow.cpp
- graphics/macgui/macwindow.cpp
- graphics/macgui/macwindowmanager.cpp
- graphics/macgui/macwindowmanager.h
fix the incorrect behaviour of selection in mactext and mactextwindow
provide basic edit operations for mactext, e.g. copy, cut, paste
> GRAPHICS: MACGUI: selection fix in mactext

- base/commandLine.cpp
For the command line, lists games only for the specified engine.
(optional)
Usage:
--list-all-games --engine=sci 
--list-games --engine=ags
> BASE: Added --engine=ID for --list-all-games and --list-games

- engines/director/castmember.cpp
- engines/director/castmember.h
- engines/director/channel.cpp
- graphics/macgui/mactext.cpp
director didn't handle the size of mactext correctly. e.g. it will accumulate the border size.
thus, we will calculate the pure text size of mactext first.
also fixed some offsets problem in mactext. e.g. cursor offsets in mactext
> DIRECTOR: offset fix

- common/achievements.h
- engines/ags/achievements_tables.h
- engines/ags/metaengine.cpp
- engines/ags/metaengine.h
- engines/metaengine.cpp
- engines/metaengine.h
- engines/twine/achievements_tables.h
- engines/twine/metaengine.cpp
- engines/wintermute/achievements_tables.h
- engines/wintermute/metaengine.cpp
getAchievementsInfo is also moved into the MetaEngine to reduce code duplication
> COMMON: moved AchievementDescriptionList into Common namespace

- engines/director/castmember.cpp
- engines/director/castmember.h
- engines/director/channel.cpp
- engines/director/channel.h
- engines/director/events.cpp
- engines/director/lingo/lingo-builtins.cpp
- engines/director/lingo/lingo-code.cpp
- engines/director/score.cpp
- engines/director/score.h
- engines/director/sprite.cpp
- engines/director/window.cpp
- graphics/macgui/macbutton.cpp
- graphics/macgui/macbutton.h
- graphics/macgui/mactext.cpp
- graphics/macgui/mactext.h
re-organize the logic of mactext and macbutton, eliminate many magic offsets
fix the logic of builtin function within.
copying the value instead of pass the pointer of sprites to channel. which will prevent modifing sprites directly.
keep the widgets when we don't have to replace them
keep fixing mactext
> DIRECTOR: Apartment/User Event fix

- engines/buried/detection_tables.h
The demo can be found at https://archive.org/details/BuriedInTimeDemo
> BURIED: Add detection for another demo version

- engines/sci/detection_tables.h
> SCI: Add fan made Hebrew translation of GK1

- engines/director/cast.cpp
- engines/director/castmember.cpp
- engines/director/channel.cpp
- engines/director/channel.h
- engines/director/lingo/lingo-builtins.cpp
- engines/director/lingo/lingo-builtins.h
- engines/director/lingo/lingo-code.cpp
- engines/director/lingo/lingo-the.cpp
- engines/director/sprite.cpp
- engines/director/sprite.h
- graphics/macgui/mactext.cpp
- graphics/macgui/mactext.h
- graphics/macgui/macwindowmanager.cpp
- graphics/macgui/macwindowmanager.h
bring a better way to handling sprites
handling macwidget events when we are calling alert in director
add partial color support for mactext
implement matte for quick draw shape
fix offsets for constrain box
support auto expand for mactext
more precise definition for highlight sprites
implement immediateSprite
keep fixing mactext and director rendering
> DIRECTOR: Apartment/Puppets fix

- backends/platform/3ds/README.md
- [`devkitpro-pkgbuild-helpers` is now deprecated in favor of `dkp-toolchain-vars`](https://github.com/devkitPro/pacman-packages/commit/f2fa9349470e7d42a4999bbea537ef9821782416#diff-1ad351cc587a0b9fc4008f8094e8935e2b4c2a3063b1e470c37c4fdeac92f105). The `devkitarm.sh` and `3dsvars.sh` files are still in `/opt/devkitpro/`.
- Update Section 4.1.2 with values from [`devkitarm.sh`](https://github.com/devkitPro/pacman-packages/blob/master/dkp-toolchain-vars/devkitarm.sh) and [`3dsvars.sh`](https://github.com/devkitPro/pacman-packages/blob/master/dkp-toolchain-vars/3dsvars.sh).
- Add libtheora portlib.
- Add link to devkitPro pacman instructions.
> 3DS: Update README.md

- engines/director/cast.cpp
- engines/director/cast.h
- engines/director/castmember.cpp
- engines/director/castmember.h
- engines/director/channel.cpp
- engines/director/channel.h
- engines/director/events.cpp
- engines/director/graphics.cpp
- engines/director/images.cpp
- engines/director/lingo/lingo-builtins.cpp
- engines/director/lingo/lingo-builtins.h
- engines/director/lingo/lingo-events.cpp
- engines/director/lingo/lingo-funcs.cpp
- engines/director/lingo/lingo-object.cpp
- engines/director/movie.cpp
- engines/director/movie.h
- engines/director/score.cpp
- engines/director/sprite.cpp
- engines/director/sprite.h
- engines/director/transitions.cpp
- engines/director/window.cpp
- engines/director/window.h
- graphics/macgui/mactext.cpp
- graphics/macgui/mactext.h
the fixing that aiming to bring ss warlock back
also including some operations for text chunk fields
mostly the detail problems
> DIRECTOR: warlock fix

- engines/ags/detection_tables.h
Add Symploke games from Steam store and moved the games to the commercial section
> AGS: Add missing games

- engines/ags/detection_tables.h
Added some entries from the Steam store and added some comments
> AGS: Add some missing entries

- engines/cge/cge.cpp
- engines/cge/cge.h
- engines/cge/detection.cpp
- engines/cge/talk.cpp
- engines/cge/talk.h
Adding TTS for the object, options and speech that are shown in the game. This also includes, the TTS option on engine menu, and TTS for the ending message
> CGE: Text To Speech (TTS) for the Soltys Game 

- backends/platform/symbian/src/SymbianMain.cpp
That fix multiple User 42 panics at exit.
Apply style fixes from #3170.
> SYMBIAN: Avoid deletion argv if no cmdlne args set.

- engines/chewy/detection.cpp
Add Spanish fanmade translation
> CHEWY: Add Spanish translation

- engines/ags/detection_tables.h
Added detection entry for the Spanish fanmade translation of  "al-emmo" and "kq2vga"
Added detection entry for 3 fanmade "Monkey Island" games
> AGS: Add few more game entries

- backends/platform/symbian/symbian_builder/build_apps.py
- backends/platform/symbian/symbian_builder/piper.py
Add cleanup from results previous build before new start.
Code style fixes from #3170.
Forced CPU usage.
> SYMBIAN: Fix race condition in build scripts.

- backends/platform/symbian/symbian_builder/parse_gamedata.py
Apply code style fixes from #3170.
> SYMBIAN: Allow installation help file for beta versions.

- backends/platform/symbian/src/SymbianOS.cpp
> SYMBIAN: Can find and use game data placed by installer on any drive.

- engines/cine/cine.cpp
- engines/drascula/drascula.cpp
- engines/engine.cpp
- engines/engine.h
- engines/gob/gob.cpp
- engines/groovie/groovie.cpp
- engines/kyra/sound/sound_pc98_v2.cpp
- engines/kyra/sound/sound_towns_lok.cpp
- engines/made/made.cpp
- engines/scumm/scumm.cpp
This is PR #3018 "rebased" on the current HEAD, after the conflicts with PR #3003 and me botching the rebase in that PR
Old PR is here: https://github.com/scummvm/scummvm/pull/3018
> ENGINES: Replace checkCD with isolated partial methods (re-issued)

- .github/workflows/ci.yml
- devtools/create_project/msvc.cpp
Issues in vcpkg are already resolved.
> CI: Enable fribidi

- common/module.mk
That strange makefile structure break Symbian makefile parser.
> COMMON: Fix code style in makefile.

- backends/platform/android/jni-android.cpp
- backends/platform/android3d/org/residualvm/residualvm/ResidualVM.java
- backends/platform/android3d/org/residualvm/residualvm/ResidualVMActivity.java
This allows the android3d backend to start correctly.
> ANDROID3D: Fix JNI code

- ports.mk
* Add also `engines/detection_table.h` to Git
* Replace literal `\t` with a tab in output.
> DEVTOOLS: Minor fixes in ideprojects target

- engines/prince/inventory.cpp
- engines/prince/option_text.h
Add initial support for Spanish translation.
> PRINCE: Add initial support for Spanish translation

- engines/sludge/builtin.cpp
This has not been tested, but should fix [Trac #12789](https://bugs.scummvm.org/ticket/12789).
> SLUDGE: Avoid direct use of remove()

- NEWS.md
I didn't know I could do it before, but I've finally included my fixes (some were minor so I didn't include those) in NEWS.md, here you go.
> NEWS: Mention DiMUSE and SCUMM fixes

- engines/director/detection_tables.h
Game name taken from [MobyGames entry](https://www.mobygames.com/game/windows/activisions-commodore-64-15-pack) as well as the ["About" window title](https://cdn.discordapp.com/attachments/870528165255188530/875558971136671844/image.png).
> DIRECTOR: Add name for c64pack

- engines/director/detection_paths.h
- engines/director/detection_tables.h
Adds new titles to the detection tables, mostly Dutch localizations.
> DIRECTOR: Add Dutch detection entries

- engines/sword1/detection.cpp
- engines/sword1/sword1.cpp
- engines/sword1/sword1.h
- engines/sword1/text.cpp
Support the ongoing Hebrew fan translation project for Broken Sword 1:
> SWORD1: Add support for Hebrew translation

- engines/drascula/saveload.cpp
- engines/grim/grim.cpp
- engines/kyra/gui/saveload_eob.cpp
- engines/mohawk/myst_stacks/menu.cpp
- engines/mohawk/riven_stacks/aspit.cpp
- engines/parallaction/saveload.cpp
- engines/sword1/control.cpp
- engines/testbed/testsuite.h
- gui/message.cpp
- gui/message.h
This is an infrastructure for introducing autosave prompts. See #3261.
> GUI: Support multiple alt buttons in MessageDialog

- doc/docportal/use_scummvm/game_files.rst
Reported on discord by eientei: https://discord.com/channels/581224060529148060/581224061091446795/877767492146196541
> DOCS: added notes about the extracted audio cd files

- backends/platform/symbian/symbian_builder/mmp_gen.py
Add ARM assembly to project file from Scumm engine
Avoid compiling ARM assembly for x86 emulator
> SYMBIAN: Fix command order in mmp_gen.py

- backends/platform/symbian/src/SymbianOS.cpp
Fix printf() usage for logging
> SYMBIAN: Allow usage by default OSystem_SDL_Symbian::openUrl() 

- devtools/dumper-companion.py
Small QoL change as requested by @trembyle via Discord.
> DEVTOOLS: COMPANION: Set last modified time to one from volume

- gui/options.cpp
- gui/options.h
...if non-autosave games are stored in autosave slot
> GUI: Warn when enabling autosave on options

- doc/docportal/_static/custom.css
- Makes CSS selectors more specific for :before content. This fixes an issue where some headings were not displaying correctly
- Removes empty table cells
- Fixes word wrapping
- Sets minimum height for Description/Options rows on config file page
> DOCS: Improves tables display on small screens

- engines/petka/interfaces/main.cpp
- engines/petka/objects/heroes.cpp
- engines/petka/objects/object_bg.cpp
- engines/petka/q_manager.cpp
- engines/petka/q_system.cpp
- engines/petka/sound.cpp
- engines/petka/video.cpp
This fixes [Trac #12681](https://bugs.scummvm.org/ticket/12681).
> PETKA: Fix crash on startup

- engines/director/cursor.cpp
- engines/director/lingo/lingo-builtins.cpp
- engines/director/lingo/lingo-code.cpp
- engines/director/lingo/lingo.cpp
- engines/director/lingo/lingo.h
Used to simplify comparison-related code
> DIRECTOR: LINGO: Add overloaded operators for Datum structs

- common/winexe.cpp
When running my CD version of Buried in Time, the loadFromCompresedEXE() function would try to decompress beyond the allocated buffer, causing it to crash. Up to that point, the decompressed data was identical to what I would get if I let the original installer decompress the EXE and DLL files.
See https://bugs.scummvm.org/ticket/12900 for details.
> COMMON: Don't decompress more bytes than the file specifies (bug 12900)

- engines/buried/biochip_view.cpp
- engines/buried/environ/da_vinci.cpp
- engines/buried/frame_window.cpp
- engines/buried/scene_view.cpp
Minor improvements to the codebase. No functional changes.
> BURIED: Fixing spelling errors in comments

- audio/audiostream.cpp
- backends/audiocd/default/default-audiocd.cpp
This used to be supported by the DS backend.
> AUDIO: Support using .wav files for extracted Audio CD tracks

- doc/docportal/help/faq.rst
@sev- I've added some questions back in - think I've covered most of them now in some form or another. 
Can I confirm with you whether 5.15, 5.16 and 5.18 in the old FAQ is still applicable? They seem specific to either Windows or SDL, so I assume with time these bugs would've been ironed out. If not I'll add them back in too.
> DOCS: revises FAQ and adds numbering

- engines/macventure/gui.cpp
- engines/macventure/gui.h
- engines/macventure/macventure.cpp
- engines/macventure/macventure.h
- engines/macventure/text.cpp
- engines/macventure/windows.cpp
- engines/macventure/windows.h
- graphics/macgui/macwindow.cpp
- graphics/macgui/macwindow.h
- graphics/macgui/macwindowborder.cpp
- graphics/macgui/macwindowborder.h
- graphics/macgui/macwindowmanager.cpp
- graphics/macgui/macwindowmanager.h
Cleanup of https://github.com/scummvm/scummvm/pull/3168
> MACVENTURE: Fix/Refactor code to work with changes made in macgui and other parts of engine

- engines/sci/sound/drivers/fb01.cpp
- engines/sci/sound/drivers/midi.cpp
Fixes https://bugs.scummvm.org/ticket/12947 , a regression from b67c2d72d6c40fda2d67cfaf6a8aab9f44f7cd1e.
@tsoliman, please give this a test. @athrxx and @bluegr, please give this a look. =)
> SCI: Don't poll input events from MIDI thread

- engines/grim/gfx_opengl_shaders.cpp
This is a quick attempt at trying to fix the broken positioning of text in Grim when using the OpenGL shader renderer.
@eriktorbjorn noted that this may stem from the OpenGL (with shaders)-renderer lacking a proper implementation of getScreenBoundingBox, so I went ahead and adapted one.
This was done by comparing the getScreenBoundingBox implementations for EFMI/Grim in the OpenGL-renderer, and noticing that those were only different in how they got at their data, as there was already an implementation for EFMI in the shader-renderer, I copy pasted that code, and adapted the differences I found when comparing the OpenGL-implementation, which seems to improve things.
> [GRIM] Fix subtitle alignment for OpenGL with shaders

- engines/cryomni3d/cryomni3d.cpp
- engines/cryomni3d/cryomni3d.h
- engines/cryomni3d/detection.cpp
- engines/cryomni3d/detection.h
- engines/cryomni3d/detection_tables.h
- engines/cryomni3d/metaengine.cpp
- video/hnm_decoder.cpp
- video/hnm_decoder.h
This PR also includes detection for an unsupported demo for Atlantis: The Lost Tales. The demos can be found at https://archive.org/details/playhns_003 and https://archive.org/details/ATLANTIS_201610.
> CRYOMNI3D: Support the Versailles 1685 demo

- backends/platform/sdl/morphos/morphos.mk
This seems like a c&p oversight.
> MORPHOS: Fix a regression/oversight

- backends/graphics3d/openglsdl/openglsdl-graphics3d.cpp
Replace query with the correct one used on every other .cpp file.
> AMIGAOS: Replace query with correct one

- backends/platform/3ds/main.cpp
Currently, the 3DS port's stack size is set by running ScummVM within a thread, a behavior introduced in fb39b94384884050a7007d2752b2c2916a73b176. Changing the stack size is necessary because libctru's default stack size of 32KiB is not large enough for ScummVM.
This commit introduces a simpler method for changing the stack size. By setting a global variable ```__stacksize__```, we can override the identically-named, weak-attributed [```__stacksize__```](https://github.com/devkitPro/libctru/blob/master/libctru/source/system/stack_adjust.s#L39) defined in libctru. [This is an intentional feature](https://github.com/devkitPro/libctru/commit/192b88b6a21d83345a4635deba417c191c156c80), and renders it unnecessary to run ScummVM within a thread.
Explanation: …
> 3DS: Set stack size w/o running ScummVM inside a thread

- engines/director/lingo/xlibs/movemousexobj.cpp
- engines/director/util.cpp
Some Mac games have file extensions for movies, but use
extensionless filenames in the code (e.g. Total Distortion).
> DIRECTOR: Check for movie file extensions on Mac

- engines/sci/console.cpp
Nit: I forgot to also update the help context for this new alias which was recently added.
> SCI: Update help documentation for the new stack alias named: "st"

- engines/lure/detection.cpp
```
Copyright Revolution Software 1990-1992   System design and code: David Sykes and Tony Warriner. Some other people did the rest.   This version assembled 09:19:10 on 09/23/92
```
> LURE: Add detection for later Konami version

- engines/director/detection_tables.h
I finally got a good rip of this. I have more Director games to add later but I figured I'd submit this now since it had been vexing me for months.
> DIRECTOR: add Mac version of Rodem

- devtools/dumper-companion.py
Also added some comments. I don't know if `os.utime` counts as modifying a file, so I just duplicated the `os.utime` line in case it does.
> DEVTOOLS: Set the modified time for folders in dumper_companion

- backends/midi/windows.cpp
- base/plugins.cpp
- devtools/create_neverhood/create_neverhood.cpp
- devtools/create_titanic/zlib.cpp
- graphics/larryScale.cpp
- graphics/wincursor.cpp
- video/bink_decoder.cpp
Using clang-tidy modernize-use-override
> JANITORIAL: Use override

- engines/buried/biochip_view.cpp
- engines/buried/environ/agent3_lair.cpp
- engines/buried/environ/ai_lab.cpp
- engines/buried/environ/alien.cpp
- engines/buried/environ/castle.cpp
- engines/buried/environ/da_vinci.cpp
- engines/buried/environ/future_apartment.cpp
- engines/buried/environ/mayan.cpp
- engines/buried/environ/scene_factory.cpp
Using clang-tidy modernize-use-override
> BURIED: Use override

- common/archive.h
- common/file.h
- common/fs.h
- common/installshield_cab.cpp
- common/lua/scummvm_file.h
- common/memstream.h
- common/osd_message_queue.h
- common/stream.cpp
- common/substream.h
- common/unarj.cpp
- common/unzip.cpp
- common/xmlparser.h
- common/zlib.cpp
Using clang-tidy modernize-use-override
> COMMON: Use override

- engines/sci/detection_tables.h
> SCI: Add fan made Hebrew translation of SQ1VGA

- engines/sci/detection_tables.h
> SCI: Add fan made Hebrew translation of LB1

- engines/twine/detection.cpp
- engines/twine/menu/menu.cpp
- engines/twine/metaengine.cpp
- engines/twine/module.mk
- engines/twine/slideshow.cpp
- engines/twine/slideshow.h
- engines/twine/twine.cpp
- engines/twine/twine.h
- image/pcx.h
This adds support for the lba_show data which can be found here: https://archive.org/details/lbashow
It's a non-interactive slideshow of lba1
> TWINE: added support for lbashow

- devtools/create_xeen/constants.cpp
- devtools/create_xeen/de_constants.h
XEEN: DE: Initial support for german version
This pull request adds initial support for the german versions
of Clouds of Xeen and Darkside of Xeen. Some very few texts
remain untranslated. Either they were not translated in the
original game or the text were not found in the original
game.
> XEEN: DE: Initial support for german version

- engines/myst3/cursor.cpp
- engines/myst3/gfx.cpp
- engines/myst3/gfx.h
- engines/myst3/gfx_opengl.cpp
- engines/myst3/gfx_opengl.h
- engines/myst3/gfx_opengl_shaders.cpp
- engines/myst3/gfx_opengl_shaders.h
- engines/myst3/gfx_tinygl.cpp
- engines/myst3/gfx_tinygl.h
- engines/myst3/gfx_tinygl_texture.cpp
- engines/myst3/gfx_tinygl_texture.h
- engines/myst3/inventory.cpp
- engines/myst3/menu.cpp
- engines/myst3/movie.cpp
- engines/myst3/node.cpp
- engines/myst3/node.h
- engines/myst3/nodecube.cpp
- engines/myst3/subtitles.cpp
- engines/myst3/transition.cpp
This is similar to what the Stark engine does.
> MYST3: Split TinyGLTexture into two separate subclasses

- backends/graphics/opengl/context.cpp
- backends/graphics/opengl/opengl-defs.h
- backends/graphics/opengl/shader.cpp
This should hopefully fix the crash described here: https://forums.scummvm.org/viewtopic.php?t=16449
> OPENGL: Lower the minimum GLSL version to 1.10

- engines/twine/debugger/console.cpp
- engines/twine/debugger/console.h
Adding play_music and play_midi commands for testing music tracks and fun!
I had implemented these for debugging issues with the midi in the Steam DotEmu release, and it's trivial code.
> TWINE: Add Debugger commands for playing music

- engines/sherlock/detection_tables.h
Copy of the patching utility is available here https://cdn.discordapp.com/attachments/711242520415174666/918882191805648896/TCotSS.patch_ITAv1.0a.zip
> SHERLOCK: Add earlier version (v1.0a) of Italian fan translation

- engines/sci/detection_tables.h
If needed, I can separate the commits into individual PRs, I just wanted to clear them out at once.
> SCI: Add German floppy KQ5 v0.000.149; some minor comment/janitorial commits

- engines/director/detection_tables.h
This contains changes requested by @trembyle on #3627 after it was merged.
> DIRECTOR: PR review

- engines/director/detection_tables.h
Add detection for Star Trek: Captain's Chair (Macromedia 5)
Add detection for Star Trek: Starship Creator (Macromedia 6)
> DIRECTOR: Add director star trek chair and creator

- engines/sci/detection_tables.h
> Add korean translation for ecoquest2 and gk2

- engines/tony/detection_tables.h
TONY: Added Spanish official release
> TONY: Added Spanish official release

- dists/amigaos/md2ag.rexx
- dists/amigaos/md2ag.rexx.in
Janitorial and optimize
I need a little help, i forgot how to update the corresponding .in file
> AMIGAOS: Update md2ag.rexx

- doc/docportal/advanced_topics/understand_search_box.rst
- Style edits to align with style guide
- Minor grammar/punctuation edits
> DOCS: style edits to search box page

- configure
This pull request is pretty much cut and paste from the LLD linker support, so I don't know for sure that I got it right. The aim is to support the [mold linker](https://github.com/rui314/mold). Supposedly it can be faster than LLD, but I don't see much difference myself. Perhaps because LLD is pretty darn fast already, and perhaps because I don't have enough CPU cores for the improvements in parallelization to really shine.
Or perhaps I did something wrong.
But I'm submitting it for discussion here anyway.
> BUILD: [RFC] Support mold linker

- gui/widgets/edittext.cpp
Fixes bug https://bugs.scummvm.org/ticket/13339
Solution is taken from our ListWidget (gui/widgets/list.cpp) which performs a similar check in its ListWidget::getEditRect()
> GUI: Fix bad EditTextWidget rect at low window widths

- backends/graphics/opengl/shader.cpp
Fixes [Trac #13327](https://bugs.scummvm.org/ticket/13327).
> OPENGL: Fix shader compilation with older Android GPU drivers

- engines/ngi/modal.cpp
Checking for SC_MAP and SC_30 in preloadItem to change param to TrubaRight.
> NGI: Scene 30 - Fix stuck when teleporting to foot (bug #10395)

- devtools/create_project/cmake.cpp
Compliments 04b1ce5a6e88c7b9d8320f5c12b745131479e397.
> CREATE_PROJECT: Fix cmake project with opengl enabled

- engines/glk/scott/detection_tables.h
Based on the quest2.dat file within AdamsGames.zip 08 Apr 1994
From http://www.ifarchive.org/indexes/if-archive/scott-adams/games/scottfree/
Discussed on Discord: 
https://discord.com/channels/581224060529148060/581224061091446795/952165554385465414
> GLK: SCOTT: Add detection for Marvel Adventure 2

- engines/director/events.cpp
For the case when a script has locked off quitting the game
> DIRECTOR: Rephrase quit warning

- common/macresman.cpp
It's possible for Macbinary files to have a resource fork. It's not common, but it's possible. An example of this I've run into is a particular Director game, contained within a single file, as processed via ScummVM's Python dumper companion.
Right now, the Mac code assumes that if a file it's opening contains a resource fork at all, it's a raw file and not Macbinary. That's not a safe assumption in this case. Instead, the Mac-specific code should check if the data fork is Macbinary first, and ignore the resource fork in that case.
I've tested with one game that's broken in master and which is fixed by this change.
> COMMON: macresman: handle macbinary with resource forks

- engines/ultima/detection_tables.h
Also renamed "GOG The Savage Empire" to "The Savage Empire v1.6"
> ULTIMA: Add detection for The Savage Empire v2.1

- engines/tsage/detection_tables.h
> TSAGE: Add demos from Wacky Funsters! and Geekwad

- engines/director/lingo/xlibs/winxobj.cpp
- engines/director/lingo/xlibs/winxobj.h
- graphics/macgui/macwindowmanager.cpp
- graphics/macgui/macwindowmanager.h
These methods were found by @einstein95 in a Voyager Japan disc. It currently crashes on startup, so I haven't really tested, but this appears to line up with their expected meaning.
I opened this in a separate PR from #3762 since they're less tested, but I can merge this into one PR if preferred.
> DIRECTOR: additional RearWindow methods

- engines/sci/detection.cpp
> SCI: Correct name of Pepper's Adventures in Time

- backends/platform/sdl/morphos/morphos.cpp
- backends/platform/sdl/morphos/morphos.h
MorphOS backend: 
delete system OpenURL and use SDL_OpenURL
> MorphOS: delete system OpenURL

- engines/director/castmember.cpp
- engines/director/castmember.h
- engines/director/channel.cpp
- engines/director/lingo/lingo-builtins.cpp
- engines/director/score.cpp
- engines/director/sprite.cpp
Implements the erase LINGO command as `b_erase()` in lingo_builtins.
> DIRECTOR: Implement erase lingo command

- engines/director/cast.cpp
- engines/director/lingo/lingo-builtins.cpp
Implements duplicate lingo command in `b_duplicate()` of lingo_builtins.cpp
> DIRECTOR: Add duplicate lingo command

- engines/glk/tads/detection_tables.h
There is a similarly named game in ifdb.org named 'Lost in New York' but it's not the TADS game 'Lost New York' by Neil deMause.
> TADS: Lost New York name corrected

- engines/glk/magnetic/detection_tables.h
> MAGNETIC: Fix case of The Pawn first word.

- backends/graphics/opengl/context.cpp
Previous OpenGL parsing algorithm was too fragile and failed to parse GL ES 1 versions and Amiga OGLES2 version.
This is not a real problem today because version is only checked in OpenGL mode.
> OPENGL: Fix OpenGL version parsing

- graphics/renderer.cpp
- graphics/renderer.h
- gui/options.cpp
This allows us to not offer a renderer which is not available on the
platform.
> GRAPHICS: Create a dynamic list of available renderers

- engines/agi/detection_tables.h
> AGI: Add more information to detection for Black Cauldron 2.10 3.5"

- engines/scumm/sound.cpp
[Trac#10559](https://bugs.scummvm.org/ticket/10559) reported a broken vocal sample in Indy4, if you go down the submarine deck while the sailors are still there (see that ticket for details). PR #1208 provided a workaround for this.
The problem is that this PR limited the fix to `Common::EN_ANY` games, but:
* LucasArts released (at least) an official version with Japanese text and the original English voices, which won't match this condition, as far as I can say (I don't own it);
* and there are some fan-made translations of Indy4 which apply to the original English talkie release (e.g. the ATP-2003 patch for French players), which don't match either (I own that one).
So, if you play these versions, you'll still get the original bug, with its really distorted noise.
We would maybe …
> SCUMM: Don't restrict the Indy4 MONSTER.SOU workaround to English versions

- engines/agi/detection.cpp
> AGI: fixed typo in fallbackWarning

- engines/tinsel/tinlib.cpp
Stub INVENTORY3 and NOTEBOOKADDHYPERLINK libcodes.
This allows the game to reach the first scene when PCM playback is disabled.
Add warning messages when stubbed libcodes are executed.
> TINSEL: Add complete opcode mappings for v3

- engines/pink/director.cpp
- engines/pink/objects/actions/action_text.cpp
- graphics/macgui/mactext.cpp
> PINK: Supports Hebrew text font and alignment

- engines/ags/detection_tables.h
> AGS: Add new games reported in bugtracker / add language detection for games (initial D)

- doc/docportal/use_scummvm/keyboard_shortcuts.rst
The general debugger works in most if not all engines.
> DOCS: Add a shortcut for the general debugger

- common/ptr.h
Improvements to SharedPtr and WeakPtr.
Adds std::weak_ptr compatible owner_before to WeakPtr (which allows them to be sorted and compared) and adds cast methods to SharedPtr/WeakPtr so they can be cast to derived types.
> COMMON: Add cast to SharedPtr/WeakPtr and ordered compare to WeakPtr

- doc/docportal/advanced_topics/understand_graphics.rst
I read through the page and made some minor corrections here and there.
> DOCS: Minor syntax fixes for graphics settings page

- engines/sci/parser/vocabulary.cpp
> sci: Hebrew parser: support 'vav' conjunctive

- engines/ags/detection_tables.h
> AGS: Add language detection for games/demos (H-K)

- engines/scumm/script_v2.cpp
- engines/scumm/scumm.cpp
- engines/scumm/string.cpp
- Add MM to existing fixes of RTL support
- Add zak and MM Hebrew preposition
> SCUMM: Add Hebrew support for MM

- engines/director/detection_tables.h
> DIRECTOR: Add detection for Wolfgang the Cyberwolf (Director 4.04)

- engines/ags/detection_tables.h
> AGS: Add language detection for games/demos (L-M) + minor renames

- backends/events/sdl/sdl-events.cpp
Just a typo fix in two comments
> BACKENDS: Typo in comments

- backends/platform/sdl/morphos/morphos.mk
Just a simple c&p error in a comment
> MORPHOS: Fix c&p error

- engines/ags/detection_tables.h
> AGS: Add language detection (N-O) + add few missing games

- engines/scumm/gfx.cpp
- engines/scumm/insane/insane.cpp
- engines/scumm/scumm.cpp
- engines/scumm/scumm.h
- engines/scumm/sound.cpp
- engines/scumm/sound.h
Ciao! This PR implements the handling of game timers done by the original interpreters:
* By using [eriktorbjorn's work](https://github.com/scummvm/scummvm/pull/3754) as a basis, whose waitForTimer function is scaringly accurate, so thank you for that!
* By using quarter frames as a base unit instead of milliseconds (nicknamed piffies, by the way), so that screen effects can behave as they should;
* By using four quarter frames (one jiffie!) per game tick;
* By using the [Intel 8253/54 PIT](https://en.wikipedia.org/wiki/Intel_8253) as a reference for the timings, which is the one referenced by the DOS versions of each game;
* By implementing what SCUMM exactly expects from VAR_MUSIC_TIMER (now the Monkey Island logo appears in sync with the music on MI1 Floppy!) and from the speech timer …
> SCUMM: Implement timing handling from the original interpreters

- gui/launcher.cpp
- gui/widget.cpp
- gui/widget.h
following code review feedback from https://github.com/scummvm/scummvm/pull/3724
> GUI: button widget auto size with screen width

- engines/director/lingo/lingo-the.cpp
- engines/director/lingo/lingo.cpp
- engines/director/lingo/lingo.h
Added boolean member `_trace` in `g_lingo` and implemented its STUB in `setTheEntity()` and `getTheEntity`
> DIRECTOR: implement STUB for kTheTrace

- engines/grim/lua/lobject.cpp
Reverts scummvm/scummvm#3911
I'll look into after release branch off, for now I'm revert it.
> Revert "GRIM: Fix string comparison in lua"

- engines/agi/detection.cpp
- engines/agi/detection_tables.h
This should address the remaining issues with ticket https://bugs.scummvm.org/ticket/13155
The requirement to have a copy of FLASHLIT.OOO outside of its OBJ folder too for detection to work, is now removed. Note that the OBJ and DAT subfolders must be preserved and not flattened (ie. do not move all of their files in the main game data folder) for the game to work properly.
> AGI: Fix detection for Mickey's Space Adventure

- engines/plumbers/detection.cpp
> PLUMBERS: Add 3DO md5 hash

- engines/glk/scott/detection.cpp
- engines/glk/scott/detection_tables.h
Game source: http://www.ifarchive.org/indexes/if-archive/scott-adams/games/c64/
Has the following games:
1. The Golden Baton
2. The Time Machine
3. Arrow of Death 1
4. Arrow of Death 2
5. Escape from Pulsar 7
6. Circus
7. Feasibility Experiment
8. The Wizard of Akyrz
9. Perseus and Andromeda
10. Ten Little Indians
11. Waxworks
> GLK: SCOTT: Add detection for 11 Mysterious Adventures (C64)

- doc/docportal/use_scummvm/how_to_settings.rst
> DOCS: add command line to settings section

- engines/ags/detection_tables.h
> AGS: Add language detection for games/demos (initial S)

- NEWS.md
Various more SCUMM changes for the 2.6.0 news file, after reading the Git log between 2.5.1 and 2.6.0 a bit :)
(A really nice release for SCUMM: nearly every title was improved in some way!)
> NEWS: Add more SCUMM changes for version 2.6.0
